### ISSUE TITLE
Python interface - memory usage

### ISSUE THREAD

**Issue by gugatr0n1c** [Microsoft/LightGBM#100]
Hi, I just trying new Python interface, learning working nicely, but I am detecting double usage of memory.

To compare: when I used pyLightGMB interface it took 3G in Python and 3G in LightGBM, now it takes about 12.5G in Python.
I have active gc and deleting big variable during process.

Is there space for memory optimalization in Python wrapper?

thx

**Comment by guolinke** [comment]
@gugatr0n1c  I will investigate about this.

And it will be an great help if can you run it with interactive python, and record the memory usage on each step.
Thanks

**Comment by gugatr0n1c** [comment]
My workflow: I am using 10 fold cv, I am doing cross validation manualy with for loop. It seems to me that possible leak is in second iteration of this loop, fun is, that when I am making third iteration the memory stays same about 11.5G

First iteration:
a] before fit call: 2.9G
b] during traning 5.6G
c] after training 5.7G

Second iteration:
a] before fit call: 5.3G
b] during traing: 11.5G (but with pyLightGBM I have no this issue) and on my laptop it crashed (run out memory and swap), on server with 16G RAM running...

Not sure if this will help

**Comment by guolinke** [comment]
did you call lightgbm.cv ?
can you share your main code framework?

**Comment by gugatr0n1c** [comment]
sorry, bug on my site.. closing for now
