### ISSUE TITLE
[R_package] lgb.cv calls wrong lgb.Dataset method

### ISSUE THREAD

**Issue by pshashk** [Microsoft/LightGBM#1001]
I think, that there is an extra underscore in
https://github.com/Microsoft/LightGBM/blob/53b99854aa9046740e4ca12c401b28fb596e5d6d/R-package/R/lgb.cv.R#L158

the lgb.Dataset method is called `setinfo`
https://github.com/Microsoft/LightGBM/blob/53b99854aa9046740e4ca12c401b28fb596e5d6d/R-package/R/lgb.Dataset.R#L415

**Comment by guolinke** [comment]
@Laurae2
