### ISSUE TITLE
[Python] Prediction phase - get Warning: model has no end of line, still using this line

### ISSUE THREAD

**Issue by gugatr0n1c** [Microsoft/LightGBM#1012]
## Environment info
Operating System: Win10
C++/Python/R version: Python 3.5.2 Anaconda

## Warning Message:

[LightGBM] [Info] Warning: last line of C:\path_to_model/model.txt has no end of line, still using this line

Hi,

in prediction phase I still get this warning. I did not modify model manually.
Model was built on same platform as it is used for prediction = Win10, 64bit, Python 3.5.2 Anaconda.
Predicition is  calculated corretly, I am just wondering why this warning is shwing up and if this can regress speed of prediction.

Model here, be ware of model is 37 MB big:
https://www.dropbox.com/s/ly9ztlebz204wt4/model.txt?dl=0

Prediction code is:

model = lg.Booster(model_file = workingDir + sub_dir + 'model.txt')
prediction = model.predict(matrix)

Thx

**Comment by wxchan** [comment]
The last line in python is to store pandas categorical feature, you can ignore it.
