### ISSUE TITLE
new scikit-learn release breaks tests

### ISSUE THREAD

**Issue by StrikerRUS** [Microsoft/LightGBM#1015]
The new scikit-learn release 0.19.1 breaks our tests: https://ci.appveyor.com/project/guolinke/lightgbm/build/2.0.10.1064/job/fg7fvmf5v5shwbeq#L2151

At first sight from logs it seems to be that `StratifiedKFold` is the root of problems.

I have no free time today (tonight in my timezone), maybe @guolinke, @wxchan, @henry0312 can perform quickfix.

http://scikit-learn.org/stable/whats_new.html#version-0-19-1

**Comment by StrikerRUS** [comment]
The commit that brings this error: https://github.com/scikit-learn/scikit-learn/commit/94fa697356210a4f38cdb7b0576cfecfa1fe2791#diff-b127807ffe58ea714328428b780f0afb

**Comment by guolinke** [comment]
@StrikerRUS we need to change the target to ``int`` type in binary and multi classification ?

**Comment by StrikerRUS** [comment]
@guolinke I'm not sure, but it seems that in `test_cv` **StratifiedKFold** is used for the regression task (boston dataset).
