### ISSUE TITLE
[python] refine categorical feature support

### ISSUE THREAD

**Issue by wxchan** [microsoft/LightGBM#1021]
to do list:

- [ ] remove categorical features = 'auto' -> use None instead
- [ ] let user confirm categorical features are set successfully: maybe add some debug level log? #893 (but do no use too much logging: #2157) 
- [ ] check train, valid, predict consistency
- [ ] pandas category: #960 
- [ ] auto convert string type or object type: #1020 
- [ ] test_category.py

some other issues:
- [x] #921  
- [x] #994

**Comment by StrikerRUS** [comment]
Closed in favor of being in #2302. We decided to keep all feature requests in one place.

Welcome to contribute this feature! Please re-open this issue (or post a comment if you are not a topic starter) if you are actively working on implementing this feature.
