### ISSUE TITLE
Python package should visualize the trees if running in jupyter notebooks

### ISSUE THREAD

**Issue by AbdealiJK** [Microsoft/LightGBM#1022]
This is a feature request.

It would be great if when I run the python package of lightgbm, I can visualize the trees in an ipython nodebook. Preferably using some ipywidgets/d3 to change the tree number and so on.

**Comment by chivee** [comment]
we do have an visualization tools with the help of [boostvis](shixialiu.com/boostvis/demo/) and it should be released in few days.

**Comment by eamag** [comment]
This site is down(

**Comment by AbdealiJK** [comment]
Would be awesome to check in the python package if Running on Jupyter + boostvis is installed and show a quick plot using boostvis as I assume visualization would take little time

**Comment by Laurae2** [comment]
@chivee Is there any news about boostvis?

**Comment by StrikerRUS** [comment]
I don't think that it's worth it to implement a separate visualizer, like [catboost does](https://github.com/catboost/catboost/tree/master/catboost/python-package/catboost/widget).
I suppose that providing the [example notebook](https://github.com/Microsoft/LightGBM/blob/master/examples/python-guide/notebooks/interactive_plot_example.ipynb), from which users can copy-paste interactive functions, is enough.

What do you think @AbdealiJK @chivee ?
Can we close this issue?

**Comment by chivee** [comment]
yes, I think the current implementation was enough and the case could be close.
