### ISSUE TITLE
[Python] GPU not working python package

### ISSUE THREAD

**Issue by up201007037** [Microsoft/LightGBM#1028]
Please search your question on previous issues, [stackoverflow](https://stackoverflow.com/questions/tagged/lightgbm) or other search engines before you open a new one.

For bugs and unexpected issues, please provide following information, so that we could reproduce on our system.

## Environment info
Operating System: Ubuntu 16.04
CPU: i7, Nvidia 1060
C++/Python/R version: Python 2.7

## Error Message:
LightGBMError: bin size 5858 cannot run on GPU
## Reproducible examples
lgb.train({'device':'gpu'}, ds)
## Steps to reproduce

Hi, I am sorry if this is already been answered but I did not find the answer for this. I was able to install the gpu version of lightgbm and I ran this with sucess: ./lightgbm config=lightgbm_gpu.conf data=higgs.train valid=higgs.test objective=binary metric=auc

However, with all the defaults, when I try to use the python package, with gpu support, this error occurs. Any idea of what might be causing this? Thank you.

**Comment by guolinke** [comment]
@up201007037 how did you install the python package ?

**Comment by chivee** [comment]
@up201007037 please make sure that the gpu support was enabled via  `pip install lightgbm --install-option=--gpu` 
more information : https://pypi.python.org/pypi/lightgbm

**Comment by up201007037** [comment]
@guolinke I installed via github. Then I did `python setup.py install`. The cpu version works fine and the gpu version also works (but not with python).
I uninstalled the version from github and did ` pip install lightgbm --install-option=--gpu` and when I try to import lightgbm the following error occurs:

OSError: /home/carlos/anaconda2/lib/python2.7/site-packages/lightgbm/lib_lightgbm.so: symbol clCreateCommandQueueWithProperties, version OPENCL_2.0 not defined in file libOpenCL.so.1 with link time reference

Thank you so much, and I am sorry for the dumb question.

**Comment by chivee** [comment]
checking your openGL version by 
`ls -l /usr/lib64 | grep -i opencl`

make sure you are using the same version of header file and GPU drivers.

and try to compile from source:

https://github.com/Microsoft/LightGBM/blob/master/docs/GPU-Tutorial.rst#install-python-interface-optional

**Comment by up201007037** [comment]
I ran `ls -l /usr/local/cuda/lib64/libOpenCL.so | grep -i opencl` and the result is lrwxrwxrwx 1 root root 14 Jan 26  2017 /usr/local/cuda/lib64/libOpenCL.so -> libOpenCL.so.1

I do not have the directory lib64 under /usr. I do have usr/lib32/nvidia-384 but your command does not return results under that folder. 

I built from source. I did: 

git clone --recursive https://github.com/Microsoft/LightGBM
cd LightGBM
mkdir build ; cd build
cmake -DUSE_GPU=1 ..
make -j$(nproc)
cd ..

Then I went to the python folder and ran:

python setup.py install --precompile

I can import and run lightgbm in python, but not with the gpu it gives that error. 

I also tried to modify the setup.py to
```
cmake_cmd = ["cmake", "../compile/"]
    if use_gpu:
        cmake_cmd.append("-DUSE_GPU=ON")
	cmake_cmd.append("-DOpenCL_LIBRARY=/usr/local/cuda/lib64/libOpenCL.so")
```

And then python setup.py install --gpu

I remember that I already had CUDA installed but I got some kind of error in the compile and I did sudo apt-get install libboost-all-dev and was able to compile and install. 
I also ran with gpu support successfully `./lightgbm config=lightgbm_gpu.conf data=higgs.train valid=higgs.test objective=binary metric=auc`.

Thank you so much for your help.

**Comment by up201007037** [comment]
I uninstalled lightgbm via pip uninstall and then:

`git clone --recursive https://github.com/Microsoft/LightGBM
cd ./LightGBM
mkdir build; cd build
sudo cmake -DUSE_GPU=1 -DOpenCL_LIBRARY=/usr/local/cuda-8.0/lib64/libOpenCL.so -DOpenCL_INCLUDE_DIR=/usr/local/cuda-8.0/include/ ..
sudo make -j$(nproc)
cd ../python-package; python setup.py install --precompile
`
I was able to install with sucess, but when I run:

`lgb.train({'device':'gpu'}, ds)`

The same error occurs: 
`LightGBMError: bin size 5858 cannot run on GPU`

I am running that with all the defaults... This is the terminal message:

`[LightGBM] [Info] This is the GPU trainer!!
[LightGBM] [Info] Total Bins 14838
[LightGBM] [Info] Number of data: 1000000, number of used features: 22
[LightGBM] [Fatal] bin size 5858 cannot run on GPU
`

**Comment by StrikerRUS** [comment]
@up201007037 It seems that this answer https://github.com/Microsoft/LightGBM/issues/715#issuecomment-317158169 helped to 4 people, maybe you'll be the happy 5th one 😄 .
#902 is another issue where you could find the solution.

**Comment by up201007037** [comment]
@StrikerRUS I already followed all the steps described on those threads. It still does not work. This is not a problem of OpenCL I guess... 
update: I am also able to run the gpu version with python in some datasets.

I am using the features from a pandas dataframe as categorical and I am not doing one hot encoding as suggested.

**Comment by StrikerRUS** [comment]
Then maybe @huanzhang12 have some thoughts about this situation.

**Comment by up201007037** [comment]
Thank you @StrikerRUS  for your thoughts on this.
I am running with the gpu support. I removed some features... and it works... 
I am trying to run this: https://www.kaggle.com/kamilkk/simple-fast-lgbm-0-6685/code and the error occurs. If I remove the feature artist_name, composer and lyricist it runs good... Anyone knows why?

**Comment by chivee** [comment]
@up201007037  the previous error that you encounter is because of that linking error, which has already solved by linking  to the right opengl.
And the second error you have faced is that our GPU version did't support bin size more than 255.  for the kaggle code that you are running, most of it's feature are sparse feature, which will leads to lots of bin

**Comment by up201007037** [comment]
Thank you @chivee. I would like to just give a suggestion to improve the documentation that is: if someone has CUDA installed then should run this: 
`sudo cmake -DUSE_GPU=1 -DOpenCL_LIBRARY=/usr/local/cuda-8.0/lib64/libOpenCL.so -DOpenCL_INCLUDE_DIR=/usr/local/cuda-8.0/include/ ..`

Thank you for your attention and help!
