### ISSUE TITLE
Lightgbm memory explodes in start train

### ISSUE THREAD

**Issue by beutlgb** [Microsoft/LightGBM#1032]
Hey,

Using lgb on a dataset size of 3G numpy array
X is int8
Y is float32
400 features 32 leafes 
Using the lgb.dataset

When starting the train  memory starts to increase massively more than twice the input size.. Getting to 16G.
I understood that lgb should be memory efficient, why does it us so much memory. The input is 3G so it shouldn't use much more.

**Comment by chivee** [comment]
can you share more settings about your jobs? what task?(regression?), what is the bin number?

**Comment by beutlgb** [comment]
Regression l2 task using 50 bins. Running on Ubuntu with 32G.
Can you explain the ram usage pipeline 
1. When creating dataset there is no ram increase.. Is this because the dataset uses reference to x and y?
2. When start training I understand that the dataset constructor starts to build the histograms and here I think the memory starts to build up massively inspire of the low max bin 50

**Comment by Laurae2** [comment]
How many maximum leaves/depth are you using? Too large increases memory requirement exponentially.

**Comment by beutlgb** [comment]
Max leaves 32 max depth 5
Doesn't seem like much
There are 12Gb that I can't understand how it uses so much

**Comment by Laurae2** [comment]
I think your matrix is 6GB in reality (when taken as float16), but doesn't explain why it jumps to 16GB.
@guolinke int8 matrix is supported in Python?

**Comment by chivee** [comment]
@Laurae2 @beutlgb  actually not, all the value will be transfer to int32_t. so the size should be 12Gb + structure & additional logic

**Comment by beutlgb** [comment]
If the x is int8 why would it be converted to int32... lgb should be memory efficient?

**Comment by Laurae2** [comment]
Ah yes it is float32. Therefore, 16GB usage is normal.

**Comment by chivee** [comment]
@beutlgb we don't implement the responding logic in the C side(yet). you can change it at [here].(https://github.com/Microsoft/LightGBM/blob/master/include/LightGBM/meta.h#L16)

**Comment by beutlgb** [comment]
If I only change this line to int8_t and build would it work? Won't there be overflows?

**Comment by guolinke** [comment]
@beutlgb
lightgbm do use int8 inside for you data set. however, the temporary memory for construct dataset in python package is float32.

If you want the efficient on memory, please use the CLI  instead. we didn’t ensure the memory efficient on python/R package.

**Comment by guolinke** [comment]
BTW,  another solution is saving your data to csv or lightsvm, then constructing dataset from file.

**Comment by beutlgb** [comment]
I don't understand, I thought the memory explodes when the dataset is constructed because the constructor uses int32 regardless what the input type is

**Comment by Laurae2** [comment]
You are converting data in Python, it's normal the memory explodes there.  You must use another format (ex: on disk as CSV/SVMLight) if you don't want such overhead.

**Comment by beutlgb** [comment]
My data is int8 so I don't understand why loading from a csv file in Python will be better memory wise

**Comment by beutlgb** [comment]
So if I load the data in Python from a csv file you think the memory won't explode? The constructor of the dataset won't convert it to float32

**Comment by guolinke** [comment]
@beutlgb the memory overhead is caused before Dataset constructed. 
When constructing Dataset in python package, it will convert the whole Dataset to float32 type first (on python side), then pass the converted float32 dataset to LightGBM api. 
If you pass filename to LightGBM.Dataset directly, the file will be read by LightGBM api, without python. As a result, it will be memory efficient.

**Comment by beutlgb** [comment]
Ok great! I will try that and updat
Thanks for the quick and effective  help guys

**Comment by Guillermogsjc** [comment]
Hello,

got the same problem. LightGBM 2.0.10 just explodes in memory when training from the Python api.

I know that there are no warranties outside the CLI, but I was using intensively the 2.0.4 version through Python without that problem. 

Could maybe be a change in any default parameter? I read something about the `histogram` parameter, I changed it but still crashing.

Thank you for this awesome library, by the way.

**Comment by guolinke** [comment]
@Guillermogsjc did you use categorical feature ? can you provide the example code ?

**Comment by Guillermogsjc** [comment]
@guolinke yes of course did, got many values in each categorical column. In fact i am putting this in model params, in lgb.Dataset when generating the dmatrix, and after also in the lgb.train command.

I cant provide example code because it is over a private dataset, this problem does not appear in the version i am used to work (2.0.4). Tried to move ahead into several new versions along the time but the Python api worked irregular (not happening in 2.0.4). I am over linux (Ubuntu).. 

Kind regards

**Comment by guolinke** [comment]
@Guillermogsjc The new categorical feature support will cause the increase of memory usage. You can try to disable it and see what happen.

**Comment by Guillermogsjc** [comment]
@guolinke ok, thank you very much, thank for your quick responses

**Comment by Laurae2** [comment]
@guolinke Do you know which commit/PR increases the memory usage of categoricals?

**Comment by guolinke** [comment]
@Laurae2 
the reason is the categorical feature may exceed 255, as a result, it needs to use uint16 or uint32 type to store the feature values. 
However, I think @Guillermogsjc 's case is caused by python package.

**Comment by Guillermogsjc** [comment]
@guolinke @laurae i preprocess the categorical features reducing them to 63 or 255 distinct values  by column, so the train is fed with categoricals as uint8

**Comment by guolinke** [comment]
@Guillermogsjc okay, so the reason is not caused by categorical feature. can you provide a example code?

**Comment by MasterScrat** [comment]
I have a similar problem of memory explosion when training starts, I tried dumping the datasets to CSVs to build the `Dataset`s from files on disk, but this actually results in even higher memory usage.

**Comment by guolinke** [comment]
@MasterScrat you can try the parameter "two_round=true"
