### ISSUE TITLE
Subsampling rows with replacement

### ISSUE THREAD

**Issue by mayer79** [microsoft/LightGBM#1038]
As far as I understand, the random forest (rf) mode differs from a genuine rf in three key aspects:

1. Column subsampling is done per tree instead of per split. 
2. Row subsampling is done without replacement instead of with replacement. 
3. No OOB predictions

How realistic would it be to add a "bagging_with_replacement" option? If set to True, then the rows would be subsampled with replacement, mimicking the idea of bagging. This might even be an interesting option for non-rf application.

**Comment by StrikerRUS** [comment]
Related issue #883.

**Comment by mayer79** [comment]
`bootstrap` seems to be a suitable name. Any form of row subsampling would thus be required if either `bagging_fraction` < 1 **or** `bootstrap = True`.

**Comment by guolinke** [comment]
It is not trivial to have this in the core algorithm. 
However, a simple solution is using weight, that is, giving weight 0 to the no-sampled data, 1 to the “one-sample” data, and k to the “k-sample” data...
It is easy to have this in python package, since you can change the weight on each iteration.

**Comment by mayer79** [comment]
Good hint. I was actually not aware that case weights could be updated during training. The Poisson distribution with mean 1 will provide an efficient and approximately correct weight distribution.

**Comment by mayer79** [comment]
I am reopening this as 

1. I am still interested in this feature :-)

2. Sampling with replacement is computationally more efficient than without.

**Comment by StrikerRUS** [comment]
Closed in favor of being in #2302. We decided to keep all feature requests in one place.

Welcome to contribute this feature! Please re-open this issue (or post a comment if you are not a topic starter) if you are actively working on implementing this feature.

**Comment by guolinke** [comment]
hi @rdbuf , yeah, callback is the most convenient way to do this, I think.

**Comment by rdbuf** [comment]
I see, thanks :)

**Comment by AhmedThahir** [comment]
> hi [@rdbuf](https://github.com/rdbuf) , yeah, callback is the most convenient way to do this, I think.

Could you share any reference implementation? I'm not sure I follow along with this idea.
