### ISSUE TITLE
Read from AWS S3

### ISSUE THREAD

**Issue by AbdealiJK** [microsoft/LightGBM#1039]
Would be useful to have a function to read data files from the AWS s3 buckets directly.

**Comment by AbdealiJK** [comment]
I think this can be made more generic to use the HDFS functionalities to read using. As amazon sdk support for HDFS would add S3 support too. 
Kind of like how Spark or Hive use the same libraries for HDFS and S3

Related to:
https://github.com/Microsoft/LightGBM/issues/1183

**Comment by StrikerRUS** [comment]
Closed in favor of being in #2302. We decided to keep all feature requests in one place.

Welcome to contribute this feature! Please re-open this issue (or post a comment if you are not a topic starter) if you are actively working on implementing this feature.
