### ISSUE TITLE
lgb boosting : i use shrinkage of 0.05 but the model first tree uses shrinkage 1

### ISSUE THREAD

**Issue by beutlgb** [Microsoft/LightGBM#1041]
Hey,

Im using shrinkage of 0.05
objective : regression l2
boosting

when i write the model to a txt file and open it,
is see that the first tree uses shrinkage:1 
while all the rest do use the requested shrinkage:0.05 .. 

is this true? 
feature or bug?
Thanks

**Comment by guolinke** [comment]
you can set ```boost_from_average=false```. 
When enable boost_from_average, there will be a bias on first tree.
