### ISSUE TITLE
Adjust probabilities for undersampled binary datasets?

### ISSUE THREAD

**Issue by ivangomezv** [Microsoft/LightGBM#1042]
Hi, how are you?

I have a highly imbalanced dataset (A/B - 1/99). Due to memory constrains I'm undersampling the majority class B by X (for example, X = 0.2, therefore I'm sampling 0.2 * rows from majority class). Therefore, my nodes will have an incorrect probability Y. From my understanding, each node's CORRECT probability (Z) would approximately be:

Z = A / ( A + B / X ) - this simply estimates original rows of B by doing B / X.

At model training, both A and B are known already. I know X. I haven't found a way of informing X in Python LGBM, is there a way? Is there another way to adjust probability output for imbalanced datasets, without programming the mentioned formula myself?

Do you think it would be correct?

Thanks a lot!

Best regards.

**Comment by Laurae2** [comment]
@ivangomezv Most metrics are not linear and therefore do not behave the linear way you describe.

Use weights of 5 for your undersampled majority class to attempt to recover the behavior of the full majority class.

**Comment by ivangomezv** [comment]
Hey, thanks!

I had forgotten about weights. It's really simple. Works like a charm, pretty equal to percentile by unweighted score probability.
