### ISSUE TITLE
Feature Importance in Python package

### ISSUE THREAD

**Issue by srhumir** [Microsoft/LightGBM#105]
A feature importance attribute  for the model would be really useful.

**Comment by guolinke** [comment]
Sure, we will provide this soon.

**Comment by binga** [comment]
Adding various feature importance metrics and highlighting important feature interactions just like this project (https://github.com/Far0n/xgbfi or https://github.com/limexp/xgbfir) could be a useful addition to this project.

**Comment by guolinke** [comment]
refer to https://github.com/Microsoft/LightGBM/pull/109
