### ISSUE TITLE
Why double hessian of the logloss function?

### ISSUE THREAD

**Issue by morning-wind** [Microsoft/LightGBM#1052]
https://github.com/Microsoft/LightGBM/blob/bd5e5e3ebb8c93da0ef13d76eb54618fd2d95426/src/objective/multiclass_objective.hpp#L94

Ref :https://stats.stackexchange.com/questions/231220/how-to-compute-the-gradient-and-hessian-of-logarithmic-loss-question-is-based

hessian of the logloss function should be p*(1-p), and why 2*p(1-p) here?

**Comment by Laurae2** [comment]
2* is below or equal to the guaranteed convergence issued from the Hessian approximation, therefore we use 2.

**Comment by morning-wind** [comment]
thanks

**Comment by LiYan1988** [comment]
Could you please give me some more information or reference about the guaranteed convergence from the Hessian approximation? Thanks!
