### ISSUE TITLE
[Python] max_bin weird behaviour

### ISSUE THREAD

**Issue by fl2o** [Microsoft/LightGBM#1053]
Hello,

I quickly read the recent issue about max_bin deprecated in python but I think this one is not linked.

I use lightGBM 2.0.10.

I observed a weird behaviour with max_bin:
When setting max_bin in the "parameters" dictionnary, the value used by lgb.cv is the default value (ie:255) instead of the value set in the dictionnary, but this is happens ONLY for the first call.
For other calls to lgb.cv, even if I change max_bin value in the dictionnary, this value will be correctly used.

Code to reproduce and output:

```
import lightgbm as lgb
from sklearn import datasets

iris = datasets.load_iris()
iris_X = iris.data
iris_y = iris.target

param_algo = {
                'task': 'train',
                'boosting_type': 'gbdt',
                'objective': 'multiclass',
                'num_class' : 3,
                'metric':{'multi_logloss'},
                'num_leaves': 31,
                'min_data_in_leaf': 1,
                'learning_rate': 0.1,
                'max_bin': 63,
                'num_threads': 1,
            }

feature_name=['a', 'b', 'c', 'd']

lgb_train = lgb.Dataset(iris_X, 
                        iris_y,
                        feature_name=feature_name)

for i in range(2):
    print('call', i+1)

    param_algo['max_bin'] += i
    params = param_algo.copy()
    print('before', params['max_bin'])

    gbm = lgb.cv(params,
                    lgb_train, 
                    num_boost_round=6,
                    feature_name=feature_name)

    print('after', params['max_bin'])
```

Output:
```
call 1
before 63
after 255
call 2
before 64
after 64
```

EDIT: I don't observe any difference in the result dictionnary for the 2 calls, so I suppose 255 is used in both cases ?

**Comment by Laurae2** [comment]
ping @wxchan

**Comment by beutlgb** [comment]
I have the same issue.
I resolved it by setting
lgb_train.max_bin = X before training.
than it will effect the train as i see...

**Comment by wxchan** [comment]
@fl2o the demo you give might have 3 issues:
1. you can try latest codes on master, before != after should be fixed now.
2. you should use smaller max_bin for such small dataset, otherwise it won't make any difference changing from 63 to 64; try 15 and 16 for example.
3. the max_bin can be changed once the Dataset is construct. so the right code can be:
```
for i in range(2):

    lgb_train = lgb.Dataset(iris_X, 
                        iris_y,
                        feature_name=feature_name)
    print('call', i+1)

    param_algo['max_bin'] += i
    params = param_algo.copy()
    print('before', params['max_bin'])

    gbm = lgb.cv(params,
                    lgb_train, 
                    num_boost_round=6,
                    feature_name=feature_name)

    print('after', params['max_bin'])
```
We might give some warning in such case in the future.

**Comment by wxchan** [comment]
@beutlgb I am not sure your issue is the same, you can show us a runnable code for debug.

**Comment by fl2o** [comment]
@wxchan 
This dataset and the max_bin numbers were used only for reproductibility.
Regarding 3, you are right and I was unaware of that since 'max_bin' can be set in params, I was expecting it to modify the lgb.cv result. A warning is a good answer to this problem.

To make it work I use @beutlgb answer: place the dataset construction in the for loop and pass max_bin argument to it. Thanks.

The only remaining issue is that passing max_bin in the parameter dictionnary doesn't have any effect on the model, 255 is always used.

**Comment by wxchan** [comment]
@fl2o do you try latest codes? max_bin=15 and 16 generates different results on my machine using your provided codes.

**Comment by fl2o** [comment]
@wxchan Until now I was waiting for pip updates ...
I will try to compile latest code tomorrow (unless there is a pip update :p) and will keep you updated!
Thank you for your answers

**Comment by StrikerRUS** [comment]
@fl2o Try the latest code - now `max_bin` is accessible only via `params` dict and issue should be gone.

**Comment by fl2o** [comment]
The issue is resolved.
max_bin in params now affects lgb.cv results 👍
