### ISSUE TITLE
LightGBM model files should include version information

### ISSUE THREAD

**Issue by vruusmann** [Microsoft/LightGBM#1054]
The "header section" of model files should specify the exact version of the LightGBM library that produced it. The requirement is to make it possible to reject unsupported model files with an informative message (eg. "the model file was produced by LightGBM vX.Y.Z, but this application only supports LightGBM versions A through B"), and to make troubleshooting easier.

For example, see the following issue, where it's necessary to identify why there's some attribute missing from the model file (clearly a version mismatch issue): https://github.com/jpmml/jpmml-lightgbm/issues/8

**Comment by Laurae2** [comment]
@guolinke What do you think about this?

**Comment by guolinke** [comment]
@Laurae2 I think we can have this start from now. And the old model format are not longer supported any more.

**Comment by guolinke** [comment]
added in the latest commit

**Comment by StrikerRUS** [comment]
@guolinke Why not to add the full version like it was asked?

**Comment by guolinke** [comment]
@StrikerRUS 
I think the version of model should depend on the model format, not the LightGBM subversions.
We can increase the version number of model if we changing the model format.

**Comment by StrikerRUS** [comment]
@guolinke OK, got it.
