### ISSUE TITLE
is there coef in binary classification??

### ISSUE THREAD

**Issue by amjiuzi** [Microsoft/LightGBM#1056]
hi, @Laurae2
could i get coefs from logistic regression by lightgbm like linear model glm()?
is lightgbm a muli-model stacking algorithm and impossible for coefs ?

**Comment by amjiuzi** [comment]
Does lightgbm use a different algorithm to fit logistic regression? or if in same way, can we get coefs from lgb model?

**Comment by Laurae2** [comment]
@amjiuzi LightGBM is a GBDT, not a logistic regression. Therefore, there are no regression coefficients.
