### ISSUE TITLE
easier R package installation with devtools::install_github ?

### ISSUE THREAD

**Issue by thierrygosselin** [Microsoft/LightGBM#1057]
Hi, I know there is a plan to submit to CRAN do you have an ETA on this ?
In the meantime, using submodules makes it impossible to use devtools to install lightgbm. Can this be changed ?

For package developper wanting to integrate LightGBM in their package, this is a must... (or you have other suggestion to ease the install process?)

**Comment by Laurae2** [comment]
> Hi, I know there is a plan to submit to CRAN do you have an ETA on this ?

I don't think so, and I have no time to work on this.

> In the meantime, using submodules makes it impossible to use devtools to install lightgbm. Can this be changed ?

You need my `lgbdl` package: https://github.com/Microsoft/LightGBM/tree/master/R-package#installation-with-precompiled-dlllib-from-r-using-github

> For package developper wanting to integrate LightGBM in their package, this is a must... (or you have other suggestion to ease the install process?)

Which one is a must? (CRAN or `devtools`? Both are non-issues for developers as long as Internet is available)

**Comment by thierrygosselin** [comment]
Do you an example of a package DESCRIPTION using LightGBM ?

**Comment by Laurae2** [comment]
@thierrygosselin You can use https://github.com/Microsoft/LightGBM/blob/master/R-package/DESCRIPTION but I didn't check if it passes CRAN checks.
