### ISSUE TITLE
max_bin doesnt change result

### ISSUE THREAD

**Issue by beutlgb** [Microsoft/LightGBM#1060]
Hey,

Im using the python API.
For regression 
when i change the max_bin param to say 51 by using a dict 
params = {"max_bin":51}
and then : 
lgb_train = lgb.dataset(x,y);
gbm = lgb.train(params,lgb_train,10)

i get the same result as if i used params = {"max_bin":255}
also if i check after the training 
lgb_train .max_bin = 255

Only if before training i set the dataset to 
lgb_train .max_bin = 51
then i do get differnt results .. 

Is this how i should use the max_bin params? shouldnt the first method work as well?

thanks!

**Comment by StrikerRUS** [comment]
Same issue #1053.
