### ISSUE TITLE
ignore_column doesnt ignore the features

### ISSUE THREAD

**Issue by beutlgb** [Microsoft/LightGBM#1061]
Hey,
Im using lightgbm ver 2.0.1.0 for regression using python

I want to ignore some of the feature .. because i didnt see there is a way for feature weighting
i set the params dict:
params = {"ignore_column":"0,1,2,3"}
but aftar training is see the model does use the blacklisted features .. 

is this a known bug?
thanks!

**Comment by guolinke** [comment]
@beutlgb ```ignore_column``` only works for CLI version. For the python-package, it is very convenient to drop useless columns.

**Comment by beutlgb** [comment]
i wanted to use the ignore_colum as a method for feature weighting so different iterations would run with different feature groups .. 
any way to do that in python?

**Comment by StrikerRUS** [comment]
@guolinke Sure, will do this when get home.

**Comment by guolinke** [comment]
@beutlgb even with ignore_column, you cannot ignore features during training. 
you can rewrite this: https://github.com/Microsoft/LightGBM/blob/master/src/treelearner/serial_tree_learner.cpp#L239-L251 to implement custom used feature.

**Comment by StrikerRUS** [comment]
@guolinke Does `ignore_column` not work even in case of `lightgbm.Dataset(data="path/to/data")`?

**Comment by guolinke** [comment]
@StrikerRUS it works if data is loaded by filepath.

**Comment by StrikerRUS** [comment]
@guolinke So we need to rewrite the note about it in docs, right?

**Comment by guolinke** [comment]
@StrikerRUS yeah

**Comment by StrikerRUS** [comment]
@guolinke OK, I'll create a PR.
