### ISSUE TITLE
Support for reading Compressed formats

### ISSUE THREAD

**Issue by AbdealiJK** [Microsoft/LightGBM#1069]
In many cases it becomes very difficult to keep large CSV or TSV files lying around. It would be useful to support CSV/TSV with gz or bz2 compression or the best case scenario support Parquet reading for the data.

Would this be something that the CLI command aims to allow ? Or should pandas/spark be handling the data reading in such cases ?

**Comment by guolinke** [comment]
@AbdealiJK 
The CLI version is focused on core algorithm. Adding these detailed IO function will increase many dependencies and is also not trivial.

These IO function can be easily done by high-level wrapper. e.g. the python package or spark package.

**Comment by AbdealiJK** [comment]
Makes sense. I was thinking the same that IO should be handled by pandas or other tools rather than LightGBM. 
Closing this
