### ISSUE TITLE
Sample weights in python sklearn interface

### ISSUE THREAD

**Issue by Nyamhyy** [Microsoft/LightGBM#107]
Please add "sample_weight" parameter in fit function and "class_weight" parameter when initializing LGBMClassifier()

**Comment by wxchan** [comment]
You can use `train_fields={'weight'=YOUR_WEIGHT_ARRAY}` for sample weight now. We can make it more clear in the future. By class weight, do you mean scale_pos_weight for binary classification? It's not supported in multiclass classification yet. But you can use the same sample weights for each class to achieve it.
