### ISSUE TITLE
Option to use double for label

### ISSUE THREAD

**Issue by AbdealiJK** [Microsoft/LightGBM#1070]
When using lightgbm, I've seen that some data inputs are not being well handled because the data is being read into floats - https://github.com/Microsoft/LightGBM/blob/master/include/LightGBM/dataset.h#L228

It would be great to have an option to read this as double as it reduces loss of precision. This would definitely increase RAM usage by 2x so this should be optional.

**Comment by guolinke** [comment]
@AbdealiJK the features values are read by double. 
For the metadata, i am not sure why need to use double type ? What is the problem for them to use float type?

**Comment by AbdealiJK** [comment]
It leads to a minor loss of precision in regression problems.
It would be awesome if there is a global typedef that is used for all such cases so that if double is needed for all metadata it can easily be changed by people.
Similarly if the features have a typedef people can change it to float to reduce RAM usage (similar to the GPU arg)

**Comment by guolinke** [comment]
@AbdealiJK 
We can have the type define. However, it may break the support of python/R package.

**Comment by AbdealiJK** [comment]
I understand that changing the type could break some of the packages - but I think it would be a step forward to make it more flexible. 
Later if required the packages could be modified to bake this appropriately too
