### ISSUE TITLE
Reduce floating point error

### ISSUE THREAD

**Issue by AbdealiJK** [Microsoft/LightGBM#1071]
In the code, the gradients and hessians within every bin gets added up.This can cause for a lot of floating point error because float addition or double addition is inexact. While this is not a major impact point, this approximation can be reduced and near ties can be better resolved.

We can try using https://en.wikipedia.org/wiki/Kahan_summation_algorithm which should reduce this to some extent.

I'm not sure about the impact to the model performance - but it would reduce un-accounted for errors in the calculations.

**Comment by guolinke** [comment]
@AbdealiJK I had tested the sum up error of the gradients and hessians. And I remember it actually doesn't has many errors (#data is about 10M). 
Sumup speed is the bottleneck of LightGBM, Using Kahan sumup will be much slower.
