### ISSUE TITLE
Enforce split point to be in the given data

### ISSUE THREAD

**Issue by AbdealiJK** [Microsoft/LightGBM#1072]
In a problem I am looking at, I need the split point from GBM to be from the dataset that I am training on. Having it on hypothetical values is not usable.

Example: If a variable has 1,2,3,4,5,6,...
But my split value for this variable can also be 4.5

I'd like to understand how I can handle something like this in LightGBM ? Can we have this as a parameter within LightGBM instead of doing a secondary pass on the data for this ?

**Comment by guolinke** [comment]
you need to change the bin_upper_bounds: https://github.com/Microsoft/LightGBM/blob/master/src/io/bin.cpp#L82 and https://github.com/Microsoft/LightGBM/blob/master/src/io/bin.cpp#L139 .
and you should set ```bin_construct_sample_cnt``` to your number of training data.
