### ISSUE TITLE
CoreML support for LightGBM models

### ISSUE THREAD

**Issue by karthikv2k** [microsoft/LightGBM#1074]
Is there a plan to support ONNX as an output format for LightGBM models?

**Comment by Laurae2** [comment]
@karthikv2k Probably not, GBDT has mostly nothing to do with tensor programming, logical (boolean) tensors for computational graphs are not appropriate (both in speed and efficiency) versus the current implementation of prediction.

Unless someone generates a converter from tree ensembles to neural network / computational graph.

**Comment by karthikv2k** [comment]
@Laurae2 Thanks for your prompt response. I am looking for a standard way to export LightGBM models into a language agnostic format. This will allow us to build production ML inferencing systems that can take this format as input. For example, CoreML provides a way to convert XGBoost models to their open CoreML protobuf based spec. I see there is a link to JPMML in the readme to convert LightGBM into PMML format but JPMML has the viral AGPL licensing.

**Comment by karthikv2k** [comment]
I just realized there is a PMML convertor in pmml/pmml.py . It is good to have CoreML support too similar to XGBoost and CatBoost . I think I can work on it.

**Comment by guolinke** [comment]
@karthikv2k Thanks.
unfortunately, the pmml support is broken now due to the missing of categorical feature support.

**Comment by guolinke** [comment]
@wxchan @StrikerRUS what is your thoughts about CoreML support ?

**Comment by StrikerRUS** [comment]
@guolinke I've never hear about CoreML before this issue, because I'm far away from Apple world.

> I think I can work on it.

However, if @karthikv2k have time and interest in developing it, then it's good and valuable enhancement for LightGBM.

**Comment by StrikerRUS** [comment]
@karthikv2k Any news?

Guys from ONNX have added support for LightGBM (only `GBDT` mode): https://github.com/onnx/onnxmltools/pull/52.

**Comment by TechnikEmpire** [comment]
AFAIK ML.NET uses LightGBM internally and supports ONNX export.

**Comment by schliffen** [comment]
I used xgboost to coreml conversion, the problem is that the inputs for converted mlmodel are so that we should input features separately! (not sure if we can enter features as a single vector).
Can anyone help me in converting lightGBM to coreml?

**Comment by StrikerRUS** [comment]
Closed in favor of being in #2302. We decided to keep all feature requests in one place.

Welcome to contribute this feature! Please re-open this issue (or post a comment if you are not a topic starter) if you are actively working on implementing this feature.

**Comment by StrikerRUS** [comment]
Open PR for adding LightGBM to CoreML: https://github.com/apple/coremltools/pull/254.

It was opened on *Oct 4 2018* but still is not merged. Someone with the CoreML knowledge may help to review and push that PR forward.
