### ISSUE TITLE
Impossible to compile generated file gbdt_prediction.cpp

### ISSUE THREAD

**Issue by araujoalexandre** [Microsoft/LightGBM#1075]
Hi !

If I am not mistaken, it seems that commit #1045 break the possibility to compile the generated file gbdt_prediction.cpp with the option convert_model. 

It seems that the linkage for the functions bellow is not working. 

- PredictRawByMap
- PredictByMap
- PredictLeafIndexByMap

Thank you !

**Comment by guolinke** [comment]
@WWLoveBasketball

**Comment by WWLoveBasketball** [comment]
Hi:
      I have tested the cases in the folder "example" and it seems work right. Could you please show me the error message or provide the data demo?
Thanks!

**Comment by guolinke** [comment]
@araujoalexandre I will update the tests on categorical features, it seems everything is fine.
https://github.com/Microsoft/LightGBM/pull/1077

**Comment by araujoalexandre** [comment]
Hi, 
I realized the file gbdt_prediction.cpp was generated with a version of LightGBM prior to the one I was trying to compile. 
Everyting works fine. 
Thanks !
