### ISSUE TITLE
Row wise feature importance on scoring?

### ISSUE THREAD

**Issue by ivangomezv** [Microsoft/LightGBM#1076]
Hi how are you?

We are trying to better understand how features affect the scoring on a row by row basis. I believe it is theoretically possible in the prediction to generate X extra columns where X is the total number of features used by the model, and dial in for each row how many times each feature is used or if possible how much gain each feature brings to prediction.

If this is not done already, is it planned? Does it sound like a good idea? Could you give us a hint as to how to contribute it ourselves?

On the other hand... since there are so many trees and nodes for each row to go through, I suspect in the end the results won't vary much row by row, but I might be wrong and I'd like to see it myself.

As always thanks a lot!

**Comment by Laurae2** [comment]
If you are using R, "feature importance" per row is already available thanks to @yanyachen .

**Comment by Laurae2** [comment]
@ivangomezv any news?

**Comment by ivangomezv** [comment]
Hey!

I can't work on this myself and it's not priority 1 so I'm hiring an external programmer to do it. We will definitely contribute it once it's done, I promise.

**Comment by JoshuaC3** [comment]
Is it possible to get this information for the training phase as well as the prediction phase? I ask this w.r.t the R package @Laurae2 and also with LIME @julioasotodv ?

**Comment by lucasecardoso** [comment]
Hi,

I'm working on implementing this functionality in the Python package, but I'm finding inconsistencies between the data accessed by the R package in the file lgb.interprete.R and the data we're seeing in the Python package.

Specifically, when parsing the model with R, the program is looking for elements of the model that we're not finding when printing the model in Python:

```
single.tree.interprete <- function(tree_dt,
                                   tree_id,
                                   leaf_id) {
  
  # Match tree id
  single_tree_dt <- tree_dt[tree_index == tree_id, ]
  
  # Get leaves
  leaf_dt <- single_tree_dt[leaf_index == leaf_id, .(leaf_index, leaf_parent, leaf_value)]
  
  # Get nodes
  node_dt <- single_tree_dt[!is.na(split_index), .(split_index, split_feature, node_parent, internal_value)]
  
...

  # Perform leaf to root conversion
  leaf_to_root(leaf_dt[["leaf_parent"]], leaf_dt[["leaf_value"]])
  
  # Return formatted data.table
  data.table::data.table(Feature = feature_seq, Contribution = diff.default(value_seq))
  
}

```
When looking at the model in Python that we obtain from Booster.dump_model(), I can't see the elements _leaf_parent_ or _node_parent_ anywhere. Looking through the C++ Booster code, I can see that both R and Python end up referencing the same _LGBM_BoosterDumpModel_ function (the R package calls a wrapper function, _LGBM_BoosterDumpModel_R_, that only seems to add some text encoding functionality). 

Is there anything wrong in my approach? I'm trying to understand if there's any difference between the model data we're seeing R access and the model data we're manipulating with Python.

**Comment by yanyachen** [comment]
Sorry for replying late. You need to parse the boosting trees to a format that contain the parent index of a node or a leaf. I did that here: https://github.com/Microsoft/LightGBM/blob/master/R-package/R/lgb.model.dt.tree.R#L78

**Comment by guolinke** [comment]
it seems this issue is solved. feel free to reopen if there are problems.
