### ISSUE TITLE
How do you encode high cardinality categorical features?

### ISSUE THREAD

**Issue by b0wl** [Microsoft/LightGBM#1078]
From your docs: "Not like simply one-hot coding, LightGBM can find the optimal split of categorical features."

Could you briefly explain or just explicitly name methods you use to obtain the optimal split? I'm looking for better alternative for one-hot encoding for my project. 

PS. By really-multi-value I mean hundreads of possible values for one category, while dataset has several categorical features like this.

**Comment by guolinke** [comment]
@b0wl I Do you mean the multi-hot categorical features?

**Comment by b0wl** [comment]
@guolinke I mean features like "city" with few hundreds possible values. I don't know its professional description.

**Comment by Laurae2** [comment]
@b0wl do you mean high cardinality features?

**Comment by b0wl** [comment]
@Laurae2 Yes! Thank you!

**Comment by guolinke** [comment]
@b0wl refer to this PR: https://github.com/Microsoft/LightGBM/pull/762
and this issue: https://github.com/Microsoft/LightGBM/issues/699
