### ISSUE TITLE
RAM explodes using LightGBM models in Parallel with large data

### ISSUE THREAD

**Issue by AlexandraBomane** [Microsoft/LightGBM#1081]
Hello,

I'm trying to run 20 LGBMClassifier models in parallel (joblib.Parallel of Python) with a large numpy array (79.6+ MB memory usage, 34 rows and 306933 columns, dtypes : 306931 64float & 2 object).
During the computation, the memory usage suddenly increases getting to 61G : I would like to decrease it in order to avoid memory usage problems.

I've already tried to convert my 64float-features into 32float-features before training (driven by https://github.com/Microsoft/LightGBM/issues/1032), but it doesn't change anything.
And when I try to store my data as a lightgbm.Dataset I get this error message : "[LightGBM] [Fatal] Cannot construct Dataset since there are not useful features."

I've already managed to do this kind of parallel computation with smaller datasets in very reasonable execution times (few seconds/minutes). So, I think that this huge memory usage is due to my big input file.

Is there a way to reduce memory consumption for this case ? On LightGBM side ? Python (joblib.Parallel) side ?

Thanks a lot,
Alexandra

**Comment by guolinke** [comment]
number of row is 34 ? if yes, you need to use set "min_data=1" and "min_data_per_bin=1" when constructing dataset. 

How many parallel jobs you are running with ? And how many memories will be used for one job ?

**Comment by AlexandraBomane** [comment]
Thanks for replying so fast,
I'll give a try with lightgbm.Dataset(data, min_data=1, min_data_per_bin=1). Can you tell which relationship there is between #data and "min_data" & "min_data_per_bin" parameters, so I can adjust them on the fly.

I run 20 jobs in parallel but I don't know how joblib.Parallel manage memory for each job.

I'll also give a try in benchmarking Parallelization vs Sequential to see. But I remember in some previous experiments I carried out that parallelization was much more faster.

Thanks

**Comment by guolinke** [comment]
refer to : https://lightgbm.readthedocs.io/en/latest/Parameters.html

In general, you don't need to tune these two parameters. except your data (#row) is very small (like your case).

I think the reason of slow is your #row is too small, as a result it can not make use of multi-core in single training task.

**Comment by guolinke** [comment]
The most  momery-efficient way is saving your data to csv, then constructing dataset from saved csv file.
It this still cannot work, the memory overhead is caused by python side (numpy or something else).
