### ISSUE TITLE
LightGBM 2.0.4 is "better" than all further versions

### ISSUE THREAD

**Issue by Laurae2** [Microsoft/LightGBM#1082]
I am seeing lot of complaints about LightGBM 2.0.4 being better than any further versions of LightGBM.

Example: https://www.kaggle.com/c/porto-seguro-safe-driver-prediction/discussion/41165#237078

> Also I have tried all version of lgb (from 2.04 to 2.0.10) and agree with man who declare that 2.0.4 is the best. This version give me best score (in the same testing conditions).

Is there any reason the 2.0.4 version is giving better results in most scenarii?

ping @guolinke

**Comment by guolinke** [comment]
@Laurae2 I just check the code. 
I think the main different is the missing value handle.
In v2.0.4, zeros and nan are both treated as missing values.
