### ISSUE TITLE
Updated Model with new Train Data

### ISSUE THREAD

**Issue by beutlgb** [Microsoft/LightGBM#1087]
Hey,

Is there a way to update an existing model, with new train data
in a way that we update the leaf values only and dont change the model selected features and splits?

Thanks!

**Comment by guolinke** [comment]
@beutlgb 
you can use this function: https://github.com/Microsoft/LightGBM/blob/master/include/LightGBM/tree_learner.h#L51 
It can update the leaf output by existing tree. However, this function isn't be exposed yet. 

I am not sure whether is this useful or not. Why need this function ?

**Comment by guolinke** [comment]
refer to this PR #1124
