### ISSUE TITLE
can't use ranking with label value >= 31

### ISSUE THREAD

**Issue by alexeib** [Microsoft/LightGBM#1090]
gbm = lgb.LGBMRanker(n_estimators=10)
    feats = []
    labels = []
    for i in range(50):
        feats.append([random.random(), random.random()])
        labels.append(0 if random.random() > 0.5 else 31)
    gbm.fit(X=feats, y=labels, group=[50])
will get an error:
lightgbm.basic.LightGBMError: b'label (31) excel the max range 31'

using any value less than 31 in labels works fine. using any value >= 31 will always produce the error above, with the "max range" being the max value of the label (but it will always say (31) for label value)

**Comment by guolinke** [comment]
you should set “label_gain”

**Comment by alexeib** [comment]
that doesnt seem to be one of the parameters either on LGBMRanker or on the fit() function in sklearn interface?

**Comment by alexeib** [comment]
closing although i think error message, documentation and sklearn interface could use a touch up :) thanks again

**Comment by guolinke** [comment]
@StrikerRUS can you help to add this to the document ?

**Comment by StrikerRUS** [comment]
@guolinke Sure, will do it today.

**Comment by Edmondguo** [comment]
how to change label_gain in Python API? I can't find it whether in LGBMRanker or in the fit() function.

**Comment by StrikerRUS** [comment]
@Edmondguo Use `**kwargs` for any parameter which isn't presented in arguments.

**Comment by mayritaspring** [comment]
> how to change label_gain in Python API? I can't find it whether in LGBMRanker or in the fit() function.

hi Edmondguo, do you figure out this problem? because I also cannot find it.....thank you so much

**Comment by cmcai0104** [comment]
Hi, @alexeib What's "the size of my maximum label size" means?

if I my label is: 1,2,3,...,100,1,2,3,...,200,1,2,3,...,1000, how to set my “label_gain”?

**Comment by guolinke** [comment]
@cmcai0104 
just make sure `label_gain[label_value]` is valid.
