### ISSUE TITLE
voting parallel run bad result

### ISSUE THREAD

**Issue by weidong8405347** [Microsoft/LightGBM#1091]
voting parallel's hyper is top_k?  
when setting voting parallel, the result is worse than data parallel
but in fact the result should be feature parallel > voting parallel > data parallel?
speed  data parallel > voting parallel > feature parallel?

**Comment by guolinke** [comment]
@weidong8405347 it depends. 
if you #data is small, using data/voting isn't help.

if you #feature is small, using data parallel is enough, and it is a accurate algorithm, so the accuracy so almost the same as feature parallel.

if you #feature is large, you can use voting parallel to speed up. The accuracy depends how many data on each machines.

**Comment by weidong8405347** [comment]
@guolinke  my question is that why voting result worse than data, i know the algorithm

**Comment by guolinke** [comment]
for speed, voting is faster when #feature is large. 
for accuracy, voting is also the same as data when #instances(rows) is large.

**Comment by weidong8405347** [comment]
@guolinke  voting should better than data,cause it use the voting to choose the top k candidate,the nips 
ok i read the paper, maybe in fact the result do not as well as the paper said

**Comment by guolinke** [comment]
As I said before, it depends. we never said the voting is better, our word is the “tradeoff between speed and accuracy”. It may need to tune “top_k” for different datasets.
