### ISSUE TITLE
Suggestion: Add training_data metrics in cv return 

### ISSUE THREAD

**Issue by CliveHugo** [Microsoft/LightGBM#1105]
## Environment info
Operating System: WIN10
CPU: 
C++/Python/R version: python3.6

a suggestion : 
Add training_data performance(metrics) in cv return for drawing validation curve (just as Xgboost.cv's return) since skleran.validation_curve is very inefficient (run n time , n =number of iteration). Don't know if anyone else has this need though.

------------------------------------------------------------------
Example from return of Xgboost.cv (after` pandas.from_dict):

Out[23]: 
    test-auc-mean  test-auc-std  train-auc-mean  train-auc-std
0        0.847553      0.011909        0.849978       0.000601
1        0.852323      0.012572        0.856189       0.000791
2        0.856945      0.011464        0.863983       0.000770
3        0.857423      0.011400        0.869057       0.000768
4        0.857955      0.010694        0.872355       0.000579
5        0.858113      0.011444        0.874590       0.000896
6        0.857701      0.011529        0.876404       0.000870
`

**Comment by jcrosskey** [comment]
This would be a nice feature to have, it'll help monitor whether overfit occurred judging from cv.

**Comment by wjmj** [comment]
It will be a very useful feature, I hope it will be implemented as soon as possible.

**Comment by StrikerRUS** [comment]
Closed via #2089.
