### ISSUE TITLE
Bounds of lambdarank predictions

### ISSUE THREAD

**Issue by travisbrady** [Microsoft/LightGBM#1106]
What are the bounds of predictions generated using `LGBMRanker` aka `application=lambdarank`?

Are there hard limits on these scores? Should I expect values < -2 for example?

On a medium sized dataset I've observed scores with min=-1.5119 and max=1.0944.

Pointers to relevant portions of the code appreciated.

thank you

**Comment by guolinke** [comment]
there is not limitation for the scores.
