### ISSUE TITLE
sklearn.base.clone does not work

### ISSUE THREAD

**Issue by srhumir** [Microsoft/LightGBM#111]
When I try to clone a model using "sklearn.base.clone", I get the error

TypeError: __init__() got an unexpected keyword argument 'verbose'

It does not deem that 'verbose' is a problem, as clone works fine for instance with LogisticRegression() from 
sklearn.linear_model has 'verbose' parameter and works fine.

Here is a reproducible example

import lightgbm as lgb
from sklearn.linear_model import LogisticRegression
from sklearn.base import clone

lgbm = lgb.LGBMClassifier()
lgbm_c = clone(lgbm)

**Comment by guolinke** [comment]
@wxchan  can you help to look into this?
And I also want to know the reason of use sklearn.base.clone ..

**Comment by srhumir** [comment]
I would like to implement some form of esemble. It would be more safe to give copies of the models to the ensemble function. I found clone the most comfortable.

I am still too beginner, will come back to it later.
