### ISSUE TITLE
How to do predict with pyspark

### ISSUE THREAD

**Issue by TerrenceVarada** [Microsoft/LightGBM#1110]
I dumped the model with pickle, and then I uploaded the model file to spark cluster, which did not install lighgbm by some reasons. when I run the code, it showed 'ImportError: No module named lightgbm.basic'. So how can I predict the data with pyspark by using lighgbm model file?
The following was how I upload the model file and do the predict.
sc.addPyFile("model_test/lightgbm/model.pkl")
with open('model.pkl', 'rb') as fin:
    pkl_bst = pickle.load(fin)
pred_probs = pkl_bst.predict(csc)

**Comment by guolinke** [comment]
@TerrenceVarada I am not familiar with pyspark.
However, I think the prediction of lightgbm model needs lightgbm package itself.

**Comment by louis925** [comment]
You can try using the new `pandas_udf` for pyspark 2.3.0+:

```
import lightgbm as lgb
import pandas as pd
import pyspark.sql.functions as F

# training on the driver or load model from the file
model = lgb.train(....)

# model feature columns
cols_features = ['feat_1', 'feat_2', ...]

# pandas udf for prediction task
@F.pandas_udf(returnType='id int, probability float', 
              functionType=F.PandasUDFType.GROUPED_MAP)
def predict_udf(df):
  df['probability'] = model.predict(df.loc[:, cols_features])  
  return df.loc[:, ['id', 'probability']]

# predict on executors
predict_test_df = (
  test_df
  .groupBy(F.spark_partition_id())
  .apply(predict_udf)
)
```
