### ISSUE TITLE
Instability with small feature values

### ISSUE THREAD

**Issue by sejlermonster** [Microsoft/LightGBM#1112]
## Environment info
Operating System: Windows-7-6.1.7601-SP1
CPU: AMD64
C++/Python/R version: Python', '2.7.13

## Error Message:
lightgbm.basic.LightGBMError: Cannot construct Dataset since there are not useful features.

## Reproducible examples
import numpy as np
from sklearn.utils.testing import assert_true, assert_false
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn import datasets
import lightgbm as lgb

data = datasets.load_breast_cancer()
X = data.data[:, :30] 
X *= 10**(-19)
assert_true(np.isfinite(X).all())
assert_false(np.any(np.isnan(X)))

X_scaled = MinMaxScaler().fit_transform(X)
assert_true(np.isfinite(X_scaled).all())
assert_false(np.any(np.isnan(X_scaled)))

y = data.target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=7)
X_train_s, X_test_s, y_train_s, y_test_s = train_test_split(X_scaled, y, test_size=0.2, random_state=7)

lgbmClassi = lgb.LGBMClassifier(max_bin=1000, min_data_in_bin=1, min_data=1)
lgbmClassi.fit(X_train_s, y_train_s)
print lgbmClassi.feature_importances_
y_pred_s= lgbmClassi.predict(X_test_s)
accuracy = accuracy_score(y_test_s, y_pred_s)
print("Accuracy: %.2f%%" % (accuracy * 100.0))

lgbmClassi = lgb.LGBMClassifier(max_bin=1000, min_data_in_bin=1, min_data=1)
lgbmClassi.fit(X_train, y_train)
print lgbmClassi.feature_importances_
y_pred = lgbmClassi.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy: %.2f%%" % (accuracy * 100.0))

## Steps to reproduce
To reproduce simply run the example, it cannot fit the tree because no useful features are found

I have tried to look into the code but not been able to identify what causes this problem. Setting max_bin=1000, min_data_in_bin=1 should allow for a single bin for each sample even though the sample values have similar(but not identical) value.  Not sure what could cause this problem.

**Comment by guolinke** [comment]
I think the problem is caused by small data (400+ examples). such small data is not stable in most machine learning model.

you also need to set ```min_hessian=0``` for small dataset.

**Comment by sejlermonster** [comment]
If you don't scale the data, or preprocess it with MinMaxScaler, there is not problem and the classifier learns as expected. Also when setting min_hessian=0

Running the example code also shows that the scaled data with MinMaxScale runs perfectly. Therefore i do not believe your right that it is caused by the small data size

I also get similar behavior when using a larger data set such as:

from sklearn.datasets import make_classification
X, y = make_classification(n_samples=3000, n_features=5, n_informative=2,
                           n_classes=2, n_clusters_per_class=1, random_state=0)

I get an accuracy of approximately 90%, but when applying X *= 10**(-19) and scaling the feature values  the get the same error

"lightgbm.basic.LightGBMError: Cannot construct Dataset since there are not useful features."

**Comment by guolinke** [comment]
okay, i see. In lightgbm, the values small than 1^-20 will be treated as zero.

**Comment by guolinke** [comment]
I just reduce the range of zero to 1e-150 in the latest commit.

**Comment by sejlermonster** [comment]
Was it set to 1e-20 for optimization reasons? and do you have any thoughts on your choice of the new threshold of 1e-150?

**Comment by guolinke** [comment]
@sejlermonster not particular reason. it is unusual to use such small feature values. 
set to 1e-150 just to reduce these cases.
