### ISSUE TITLE
Dose lightgbm has corresponding params smooth and entropy as fastrank ?

### ISSUE THREAD

**Issue by chenghuige** [Microsoft/LightGBM#1115]
I'm not sure "Try lambda_l1, lambda_l2 and min_gain_to_split for regularization" is the same as smooth and entropy. 
for smooth:
 paramter for tree regularization, can take values from
      zero to one, zero means that no smoothing takes place while one means
      that trees are smoothed to the extent that no learning takes place at
      all. Smoothing essentially mixes each the output value of each leaf in
      the tree with the output values of its neighboring leaves. Leaves with
      many training documents will be modified less than leaves with few
for entropy:
sets the entropy coefficient, which encourages
      the algorithm to prefer balanced splits in the tree (splits where an
      equal number of training documents go in each direction)

smooth like below:

	void SmoothLeafOutputs(double parentOutput, double smoothing)
	{
		double myOutput = ((1.0 - smoothing) * GetWeightedOutput()) + (smoothing * parentOutput);
		if (IsLeaf())
		{
			Tree.SetOutput(~NodeIndex, myOutput);
		}
		else
		{
			LTENode->SmoothLeafOutputs(myOutput, smoothing);
			GTNode->SmoothLeafOutputs(myOutput, smoothing);
		}
	}

entropy like below:

    if (_entropyCoefficient > 0.0)  {      

          Float entropyGain = ((totalCount * std::log((Float)totalCount)) - (LTECount * std::log((Float)LTECount))) - (GTCount * std::log((Float)GTCount)); 

           currentShiftedGain += _entropyCoefficient * entropyGain; }

**Comment by guolinke** [comment]
@chenghuige not have this yeah. welcome to contribute

**Comment by chenghuige** [comment]
@guolinke Thanks,  close this issue for now. And I will see if I can contribute.
