### ISSUE TITLE
bin size error

### ISSUE THREAD

**Issue by ewrfdv** [Microsoft/LightGBM#1116]
## Environment info
Operating System:WINDOWS 10
CPU:Intel i7
C++/Python/R version: python 2.7 and 3.5

## Error Message:
D:\coding\Python\Anaconda\envs\tf_with_lgbm\lib\site-packages\lightgbm\engine.py:99: UserWarning: Found `num_rounds` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))
D:\coding\Python\Anaconda\envs\tf_with_lgbm\lib\site-packages\lightgbm\basic.py:642: UserWarning: max_bin keyword has been found in `params` and will be ignored. Please use max_bin argument of the Dataset constructor to pass this parameter.
  'Please use {0} argument of the Dataset constructor to pass this parameter.'.format(key))
[LightGBM] [Warning] Met negative value in categorical features, will convert it to NaN
[LightGBM] [Warning] Met negative value in categorical features, will convert it to NaN
[LightGBM] [Warning] Met negative value in categorical features, will convert it to NaN
[LightGBM] [Warning] Met negative value in categorical features, will convert it to NaN
[LightGBM] [Warning] Met negative value in categorical features, will convert it to NaN
[LightGBM] [Warning] Met negative value in categorical features, will convert it to NaN
[LightGBM] [Fatal] bin size 16948 cannot run on GPU
Traceback (most recent call last):
  File "D:/coding/Python/Projects/Recommendation/lightgbm_test.py", line 264, in <module>
    lgbm_model = lgb.train(params, train_set = lgb_train, valid_sets = lgb_val, verbose_eval=5)
  File "D:\coding\Python\Anaconda\envs\tf_with_lgbm\lib\site-packages\lightgbm\engine.py", line 178, in train
    booster = Booster(params=params, train_set=train_set)
  File "D:\coding\Python\Anaconda\envs\tf_with_lgbm\lib\site-packages\lightgbm\basic.py", line 1296, in __init__
    ctypes.byref(self.handle)))
  File "D:\coding\Python\Anaconda\envs\tf_with_lgbm\lib\site-packages\lightgbm\basic.py", line 48, in _safe_call
    raise LightGBMError(_LIB.LGBM_GetLastError())
lightgbm.basic.LightGBMError: b'bin size 16948 cannot run on GPU'

## Reproducible examples
params = {
        'objective': 'binary',
        'boosting': 'gbdt',
        'learning_rate': 0.1 ,
        'verbose': 0,
        'num_leaves': 120,
        'bagging_fraction': 0.95,
        'bagging_freq': 1,
        'bagging_seed': 1,
        'feature_fraction': 0.9,
        'feature_fraction_seed': 233,
        'max_bin': 256,
        'num_rounds': 800,
        'lambda_l1': 0.3,
        'lambda_l2': 0.3,
        'metric' : 'auc',
        'is_unbalance' : 'true',
        'device' : 'gpu',
        'gpu_platform_id' : 0,
        'gpu_device_id' : 0,
        'gpu_use_dp' : 'false'
    }

## Other information
visual studio 2017
lightgbm Version: 2.0.11
CUDA 8.0
I installed LightGBM GPU Version and my GPU is GTX 1070 8GB, I thought it should be able to run my program but failed, there are some pages I found that seems have the same problem like me:
https://www.kaggle.com/c/instacart-market-basket-analysis/discussion/37836
https://github.com/Microsoft/LightGBM/issues/1003  (the last commented)

**Comment by guolinke** [comment]
GPU version cannot support categorical features with high cardinality. 
You can fix it by split one categorical feature into multi categorical features.
