### ISSUE TITLE
Can LightGBM support svm_light(for rank) data format？

### ISSUE THREAD

**Issue by freshguy** [Microsoft/LightGBM#1117]
When i run examples/lambdarank use [svm_light](http://www.cs.cornell.edu/people/tj/svm_light/svm_rank.html) data format, I will get the following errors：

> [LightGBM] [Info] Using column number 0 as group/query id
[LightGBM] [Fatal] Input format error when parsing as LibSVM
Met Exceptions:
Input format error when parsing as LibSVM

I add the following line into 'train.conf' file:
> query=0

Here is some data fragments which comes from the [Microsoft  Letor](https://www.microsoft.com/en-us/research/project/letor-learning-rank-information-retrieval/?from=http%3A%2F%2Fresearch.microsoft.com%2Fen-us%2Fum%2Fbeijing%2Fprojects%2Fletor%2F) dataset 'MQ2008'：
`0 qid:11909 1:0.049554 2:0.000000 3:0.000000 4:0.000000 5:0.048537 6:0.000000 7:0.000000 8:0.000000 9:0.000000 10:0.000000 11:0.585689 12:0.000000 13:0.000000 14:0.000000 15:0.590289 16:0.054201 17:0.500000 18:0.333333 19:0.000000 20:0.054362 21:0.341587 22:0.453490 23:0.669057 24:0.669136 25:0.000000 26:0.000000 27:0.000000 28:0.000000 29:0.000000 30:0.000000 31:0.000000 32:0.000000 33:0.000000 34:0.000000 35:0.000000 36:0.000000 37:0.298798 38:0.480544 39:0.638397 40:0.682844 41:0.000000 42:0.000000 43:0.000000 44:0.208262 45:0.089286 46:1.000000 #docid = GX000-01-8011551 inc = 1 prob = 0.278009`

The [RankLib](https://sourceforge.net/p/lemur/wiki/RankLib%20How%20to%20use/)  can handle this dataset correctly. 
Can LightGBM support this data format? If can, how can i do? Thank you!

**Comment by guolinke** [comment]
This isn't supported due to the efficiency problem.
you can solve it by:
1. use python package and use http://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_svmlight_file.html to load query_id.
2. use a simple convert script like this: https://github.com/guolinke/boosting_tree_benchmarks/blob/master/data/msltr2libsvm.py
