### ISSUE TITLE
Adding Cost Effective Gradient Boosting to LightGBM

### ISSUE THREAD

**Issue by souravsingh** [Microsoft/LightGBM#1119]
S Peter proposes a feature which can be added to LightGBM as a feature. The work has already been done in a fork here- https://github.com/svenpeter42/LightGBM-CEGB

Paper related to the topic- https://papers.nips.cc/paper/6753-cost-efficient-gradient-boosting.pdf

**Comment by guolinke** [comment]
ping @svenpeter42

**Comment by Laurae2** [comment]
@svenpeter42 Are you interested into adding Cost Efficient Gradient Boosting to the official LightGBM?

**Comment by svenpeter42** [comment]
Sorry for the late reply, I just came back from my Christmas break. 
Yes, I'm definitely interested in adding this to the official LightGBM!

**Comment by chivee** [comment]
@svenpeter42 , Happy new year! you can send the PR when code is ready.

**Comment by svenpeter42** [comment]
Happy new year to you, too! I'll clean up the code and rebase on your current master and will file a PR then.

**Comment by StrikerRUS** [comment]
ping @svenpeter42

**Comment by svenpeter42** [comment]
sorry, i've been pretty busy with research lately. I'll try to eventually get back to this but cannot tell when I'll have enough time :(

**Comment by souravsingh** [comment]
@svenpeter42 Can I use your code to integrate it into core LightGBM repository as a PR?

**Comment by svenpeter42** [comment]
Sure, absolutely!

**Comment by remcob-gr** [comment]
I have an implementation of this, integrated in the serial tree learner, in https://github.com/rvb/LightGBM/tree/CEGB-rebase .
Would you be interested in a PR based on that branch?
There's a bunch of other stuff on there as well, I'm happy to rebase just the CEGB commits onto current master.

**Comment by souravsingh** [comment]
@remcob-gr Go ahead make a PR for the same. I will close my current PR for CEGB.
