### ISSUE TITLE
Python: loading model ending with error - size doesnt match

### ISSUE THREAD

**Issue by gugatr0n1c** [Microsoft/LightGBM#112]
I have built model, than save the model with

model.save_model(working_dir + '/modely/model_' + str(tt) + '_' + str(cv) + '.txt', num_iteration = -1)
tt and cv just iterators = both 0 in this case..
Building model was ended with early_stopping.

I can share with dropbox (35M), seems to be everything OK.
https://dl.dropboxusercontent.com/u/36271853/model_0_0.txt

But when I tried to load it with this:
model = lg.Booster(model_file = workingDir + '/modely/model_0_' + str(cv) + '.txt')
I get this error, I tried to go basic.py to look a it, but not sure what is the problem.
Running yestarday checkouted version, 3 days ago with older version it was working.

Traceback (most recent call last):
  File "predikuj.py", line 22, in <module>
    model = lg.Booster(model_file = workingDir + '/modely/model_0_' + str(cv) + '.txt')
  File "/usr/local/lib/python3.5/dist-packages/lightgbm-0.1-py3.5.egg/lightgbm/basic.py", line 919, in __init__
    ctypes.byref(self.handle)))
  File "/usr/local/lib/python3.5/dist-packages/lightgbm-0.1-py3.5.egg/lightgbm/basic.py", line 53, in _safe_call
    raise LightGBMError(_LIB.LGBM_GetLastError())
lightgbm.basic.LightGBMError: b"StringToArray error, size doesn't match."

**Comment by guolinke** [comment]
@gugatr0n1c can you try to rebuild library and python package? I fix this yesterday night.

**Comment by gugatr0n1c** [comment]
sure, thx for quick info

**Comment by gugatr0n1c** [comment]
jop, working, thx
