### ISSUE TITLE
md to rst conversion issue

### ISSUE THREAD

**Issue by Laurae2** [Microsoft/LightGBM#1122]
@StrikerRUS Can you fix this?

https://github.com/Microsoft/LightGBM/blob/master/docs/Parameters.rst#metric-parameters

![image](https://user-images.githubusercontent.com/9083669/34083533-8aaa4032-e372-11e7-82ed-403f812cc31c.png)

**Comment by StrikerRUS** [comment]
@Laurae2 Please explain what's wrong on this screenshot?

**Comment by Laurae2** [comment]
@StrikerRUS Is that formatting expected?

![image](https://user-images.githubusercontent.com/9083669/34084699-3a9c0946-e385-11e7-819b-37d0bffb2cc9.png)

(default opening 3x {} when only 1 needed (?), options listed twice)

**Comment by StrikerRUS** [comment]
Such pattern was created by @guolinke https://github.com/Microsoft/LightGBM/blob/de36b3296da4b794ff0b2e622917426461a20787/docs/Parameters.md#metric-parameters
Better ask him, don't he mind about changes.

**Comment by guolinke** [comment]
any suggestions for that formats?

**Comment by Laurae2** [comment]
@guolinke Maybe this?

* metric, default={`l2` for regression, `binary_logloss` for binary classification, `ndcg` for lambdarank}, type=multi-enum

It seems the "options" tag is redundant as the full list is always specified below it. It's not used elsewhere:

![image](https://user-images.githubusercontent.com/9083669/34120265-54db49ca-e425-11e7-9cde-226252546854.png)

**Comment by guolinke** [comment]
It looks good to me. Please feel free to create PR to fix.
