### ISSUE TITLE
Issue with "make -j" in R installation

### ISSUE THREAD

**Issue by wsnavely** [Microsoft/LightGBM#1125]
Hi,

I ran into some odd behavior installing LightGBM from rstudio, using a command like:
```
library(devtools)
options(devtools.install.args = "--no-multiarch") 
install_github("Microsoft/LightGBM", subdir = "R-package")
```

My machine would become nonresponsive for many minutes, apparently crashing. I cloned the LightGBM repo and ran
```
R CMD INSTALL --build . --no-multiarch
```
With apparently the same affect. What fixed the issue for me was removing the "-j" from the make command, e.g. by editing install.libs.R. Evidently a few people have run into a similar problem, e.g.:
https://github.com/Microsoft/LightGBM/issues/605
https://github.com/Microsoft/LightGBM/issues/373

Would it make sense to consider removing the -j by default from the R installer script? Or, perhaps adding an argument to -j such as -j4? Alternatively, is there some option one can pass to the installer to disable parallel make?

Thank you for the consideration.

## Environment info
Operating System: Ubuntu 16.04 x86_64
CPU: VMWare VM with 1 processor clocked at 3.3Ghz from guest

C++/Python/R version:
g++ (Ubuntu 6.2.0-5ubuntu12) 6.2.0 20161005
Python 2.7.12+
R version 3.4.3 (2017-11-30) -- "Kite-Eating Tree"

## Error Message:
No error message appeared, my virtual machine became unresponsive.

## Reproducible examples
The command I ran was:
```
library(devtools)
options(devtools.install.args = "--no-multiarch") 
install_github("Microsoft/LightGBM", subdir = "R-package")
```
But I think the behavior depends on the specific machine, so this might be hard to reproduce.

**Comment by guolinke** [comment]
ping @Laurae2  , @StrikerRUS

**Comment by StrikerRUS** [comment]
@guolinke Unfortunately, I know no more than nothing about R.

**Comment by guolinke** [comment]
@StrikerRUS i think the build of python package has the same issue

**Comment by StrikerRUS** [comment]
@guolinke There is no `-j` option in the Python-package at all at present time. Do you mean that we should add `-j4`?

**Comment by guolinke** [comment]
oh, that is fine.
