### ISSUE TITLE
run 'R CMD INSTALL --build' has an error

### ISSUE THREAD

**Issue by xiaohuangdudu123** [Microsoft/LightGBM#1126]
Please search your question on previous issues, [stackoverflow](https://stackoverflow.com/questions/tagged/lightgbm) or other search engines before you open a new one.

For bugs and unexpected issues, please provide following information, so that we could reproduce on our system.

## Environment info
Operating System:
CPU:
C++/Python/R version:R-3.4.0

## Error Message:
I already change the directory to LighGBM/R-package,and it's ok 
but then I run 'R CMD INSTALL --build' it print that
'D:\Program' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
## Steps to reproduce

1.
2.
3.

**Comment by guolinke** [comment]
@xiaohuangdudu123 
did you install cmake, Rtools, R and MSBuild ?
Can you provide full log ?

**Comment by StrikerRUS** [comment]
I believe that this error happens due to the space character in the path: `D:\Program Files\...` should be, but only `D:\Program` is recognised.
