### ISSUE TITLE
a newbie question about custom objective function

### ISSUE THREAD

**Issue by goldenbull** [Microsoft/LightGBM#1127]
https://github.com/Microsoft/LightGBM/blob/92f2a570efbd9af898cbb4bf42dec1a595c6e9d7/examples/python-guide/advanced_example.py#L136

Why objective function returns `(grad: array, hess: array)` ? What's the meaning of the two returned arrays? In textbook it's a function returns a real number.

**Comment by guolinke** [comment]
refer to https://github.com/Microsoft/LightGBM/blob/92f2a570efbd9af898cbb4bf42dec1a595c6e9d7/examples/python-guide/advanced_example.py#L138-L143:

grad is the first-order gradient of objective function. 
hess is the second-order gradient of objective function.
