### ISSUE TITLE
Unexpected excel the max range encountered in lambdarank task training

### ISSUE THREAD

**Issue by TaiChiBagua** [Microsoft/LightGBM#1128]
## Environment info
Operating System:   centos
CPU:

i used the config just like the example shows, but i changed the data
the data.train is in the format of libsvm, and i add an data.train.query file to indicate how many lines belong to the one query.   the label ranges from 0 to 15, and duplicate labels may in one query
but i get excel the max range  error

how does is caused by?

**Comment by guolinke** [comment]
please check your label range. It is really [0, 15], it cannot be exceed.
