### ISSUE TITLE
Python-API: error when training finishes without early stopping

### ISSUE THREAD

**Issue by jeongyoonlee** [Microsoft/LightGBM#1132]
## Environment info
Operating System: Ubuntu 16.04.3 LTS
CPU: x86_64
C++/Python/R version: Python 3.5.2

## Error Message:
```
...
File "/anaconda/envs/py35/lib/python3.5/site-packages/lightgbm/engine.py", line 220, in train
    for dataset_name, eval_name, score, _ in evaluation_result_list:
UnboundLocalError: local variable 'evaluation_result_list' referenced before assignment
```

## Reproducible examples
During `train()` with the `ealry_stopping_rounds` option, if validation errors keep decreasing till the end, it throws an error as above.

## Steps to reproduce

1. set `num_boost_round` small enough so that validation error keeps decreasing
2. set `early_stopping_rounds` big enough so that it doesn't meet the early stopping condition
3. train

**Comment by guolinke** [comment]
@jeongyoonlee 
just try it on example dataset, and didn't met the error:

based on https://github.com/Microsoft/LightGBM/blob/master/examples/python-guide/simple_example.py

code:
```
# coding: utf-8
# pylint: disable = invalid-name, C0111
import json
import lightgbm as lgb
import pandas as pd
from sklearn.metrics import mean_squared_error


# load or create your dataset
print('Load data...')
df_train = pd.read_csv('../regression/regression.train', header=None, sep='\t')
df_test = pd.read_csv('../regression/regression.test', header=None, sep='\t')

y_train = df_train[0].values
y_test = df_test[0].values
X_train = df_train.drop(0, axis=1).values
X_test = df_test.drop(0, axis=1).values

# create dataset for lightgbm
lgb_train = lgb.Dataset(X_train, y_train)
lgb_eval = lgb.Dataset(X_test, y_test, reference=lgb_train)

# specify your configurations as a dict
params = {
    'task': 'train',
    'boosting_type': 'gbdt',
    'objective': 'regression',
    'metric': {'l2'},
    'num_leaves': 10,
    'learning_rate': 0.05,
    'feature_fraction': 0.9,
    'bagging_fraction': 0.8,
    'bagging_freq': 5,
    'verbose': 0
}

print('Start training...')
# train
gbm = lgb.train(params,
                lgb_train,
                num_boost_round=10,
                valid_sets=lgb_eval,
                early_stopping_rounds=150)
```

**Comment by guolinke** [comment]
please try the latest code.

**Comment by jeongyoonlee** [comment]
@guolinke I found the issue.

It happened because of two bugs:
1. In `train()`, `best_iteration` is initialized to `0` at [line 187 in `engine.py`](https://github.com/Microsoft/LightGBM/blob/5a89a76df3613492837b29916cf24b0c4707643e/python-package/lightgbm/engine.py#L187) and if early stopping condition isn't met during training, it doesn't get updated. In this case, it should be updated to `num_boost_round`.
2. At [line 190 in `engine.py`](https://github.com/Microsoft/LightGBM/blob/5a89a76df3613492837b29916cf24b0c4707643e/python-package/lightgbm/engine.py#L190), when `init_iteration + num_boost_round` is `0`, `evaluation_result_list` doesn't get initialized before it is used at [line 220](https://github.com/Microsoft/LightGBM/blob/5a89a76df3613492837b29916cf24b0c4707643e/python-package/lightgbm/engine.py#L220). It should either handle the case of `num_boost_round == 0` as an exception or initialize `evaluation_result_list` before the `for` loop in [line 220](https://github.com/Microsoft/LightGBM/blob/5a89a76df3613492837b29916cf24b0c4707643e/python-package/lightgbm/engine.py#L190).

My case was that I trained 5-CV, and used `best_iteration` from the 1st fold as `num_boost_round` for the rest of 4 folds. So when the 1st fold didn't meet the early stopping condition, the 2nd fold used `num_boost_round` of `best_iteration` from the 1st fold, which was `0`. Then it threw the error I described above.

Hope it helps. :)
Best,
Jeong

**Comment by guolinke** [comment]
@jeongyoonlee 
I see. Actually, `best_iteration==0` means use all models. 
However, in this PR: https://github.com/Microsoft/LightGBM/pull/1133, the best_iteration will be set even not met the early stopping. 

So the problem is caused when `num_boost_round` is zero. I think I can add a check for this. 

Thanks very much.

**Comment by jeongyoonlee** [comment]
Sounds good. Thanks @guolinke for the prompt response!

**Comment by startakovsky** [comment]
@guolinke , @jeongyoonlee the following image with the current version in master shows the same  issue presenting itself... 

![image](https://user-images.githubusercontent.com/689723/34428279-eb3b8358-ebff-11e7-91ee-878c0fd3087f.png)

**Comment by guolinke** [comment]
@startakovsky 
if you did't set early-stopping, the best-iteration is always zero (means using all models).

**Comment by startakovsky** [comment]
@guolinke, thanks for your response. What exactly does it mean  _using all models_? Is that iteration 3 in the image? When I run `gbm.predict(X_test, num_iteration=n)` where `n` can be any of `-1, 0, 3`, it shows up with the exact same results.

![image](https://user-images.githubusercontent.com/689723/34430212-8c8c7688-ec17-11e7-93eb-9e97e1b16347.png)

**Comment by guolinke** [comment]
if num_iterations is smaller than or equal to zero, the prediction will use all models
