### ISSUE TITLE
R CMD Install error

### ISSUE THREAD

**Issue by xiaohuangdudu123** [Microsoft/LightGBM#1134]
After run the code 'Rscript build_package.R',I already have lightgbm_2.0.11.tar under the LightGBM/R-package.
Then I run 
C:\Users\ASUS\LightGBM\R-package>R CMD INSTALL lightgbm_2.0.11.tar.gz
but it print:
* installing to library 'C:/Users/ASUS/Documents/R/win-library/3.4'
* installing *source* package 'lightgbm' ...
** libs
installing via 'install.libs.R' to C:/Users/ASUS/Documents/R/win-library/3.4/lightgbm
Warning: 'cmake  -G "MinGW Makefiles"  ..'127
Warning: 'cmake  -G "MinGW Makefiles"  ..'127
MINGW3~1.EXE: *** No rule to make target '_lightgbm'.  Stop.
Warning: 'mingw32-make.exe _lightgbm -j'2
Error in eval(ei, envir) : Cannot find lib_lightgbm.dll
* removing 'C:/Users/ASUS/Documents/R/win-library/3.4/lightgbm'

#I already install Cmake,Visual Studio，Rtools，but still run error.
Thank you!

**Comment by guolinke** [comment]
@xiaohuangdudu123 please don't open so much issues. 

For your log, you didn't install VS correctly, please choose c++ when installing.
