### ISSUE TITLE
how to pass group parameter for sklearn gridsearch for ranking

### ISSUE THREAD

**Issue by dancaspi** [Microsoft/LightGBM#1137]
hey,
I have been trying to use LightGBM for a ranking task (objective:lambdarank). it works fine on my data if i modify the examples in the tests/ dir of lightgbm, but can't seem to be able to use GridSearchCV in order to param tune this model. Specifically my problem is passing the group param. 

would appreciate any tip.
Thanks,
Dan

**Comment by StrikerRUS** [comment]
@dancaspi There is a `fit_params` (currently deprecated) in GridSearchCV constructor. With the latest version of sklearn you can pass parameters to `fit()` method of the LGBMRanker via `**fit_params` of `fit()` method of GridSearchCV. See http://scikit-learn.org/stable/modules/generated/sklearn.model_selection.GridSearchCV.html#sklearn.model_selection.GridSearchCV.fit

**Comment by dancaspi** [comment]
sorry for the delay and thanks for the reply. I believe I tried that and it didn't work, however, please allow me to get back to you on that with a reproducible example in the next day or two, sorry again for the delay

**Comment by StrikerRUS** [comment]
@dancaspi No problem! Feel free to ask questions.

**Comment by dancaspi** [comment]
Hey, so shamefully enough, it seems my mistake was writing group*s*. anyhow, I still encountered some difficulty and supply this  fully reproducible example:
I actually use lambdarank as type of ordinal regression - I only have one ordering task. Therefore I pass to groups just the number of observations (as if they all come from a single query). The "native" lgbm apparently works with these settings. However, the sklearn random search exists with error: 
LightGBMError: b'sum of query counts is not same with #data'. I copy-pasted the group parameter from the native lgbm to the sklearn grid search



```
from sklearn.model_selection import RandomizedSearchCV
import lightgbm as lgb
import numpy as np
import pandas as pd
ngrid=2
ranking_param_grid = {

    'learning_rate': [0.01, 0.02],
    'n_estimators': [300, 400, 600, 800,1000],
    # 'num_leaves':[4,8,16,32],
    'max_depth': [2, 3, 4, 5, 6],

    'boosting_type': ['gbdt'],
    'objective': ['lambdarank'],
    'random_state': [777],
    # feature_fraction -> colsample_bytree
    # bagging_fraction -> subsample
    # bagging_freq -> subsample_freq
    "min_data_in_leaf": [10,20],
    'scoring':['ndcg'],
    # 'colsample_bytree' : [0.25,0.5,0.6,0.7,0.8],
    # 'colsample_bytree' : [0.6,0.7,0.8,0.9],
    'feature_fraction': [1, 0.9, 0.8,0.4],

    'subsample': [1, 0.9, 0.8,0.5],
    'max_bin':[50,100,200],
    'is_unbalance': [True, False],

    # 'min_child_weight':[5,10,25,50],
    # 'n_jobs': [3]

}

params={'boosting_type':'gbdt','score':'ndcg',
'colsample_bytree':1.0, 'learning_rate':0.02,
#max_bin=255},
'max_depth':5, 'min_child_samples':10,
'n_estimators':500,
'n_jobs':-1, 'objective':'lambdarank', 'random_state':777,
'silent':False, 'subsample':1.0,
}


gbm = lgb.LGBMRanker(**params)
#X_train = pd.read_csv("/home/dan/X_train.csv")
#X_test = pd.read_csv("/home/dan/X_test.csv")
#y_train = pd.read_csv("/home/dan/y_train.csv",header=None)
#y_test = pd.read_csv("/home/dan/y_test.csv",header=None)


n_class = 5
n_samples = 1000
n_dim = 10

X_train = pd.DataFrame(np.random.randn(n_samples, n_dim))
y_train = pd.DataFrame(np.random.randint(0,5,size=n_samples))
    

gbm.fit(X_train, np.array(y_train[0]), group=np.array([X_train.shape[0]]),
       # eval_set=[(X_test, np.array(y_test[0]))],eval_group=[np.array([X_test.shape[0]])],
        verbose=5,eval_metric='ndcg')#,eval_at=int(y_test.shape[0]/3.000) )  ## exampole the setup works for lgb

## now searchcv

gridgbm = RandomizedSearchCV(gbm, param_distributions=ranking_param_grid,
                             n_iter=ngrid, cv=10, verbose=10,
                             fit_params={'group':np.array([X_train.shape[0]])})  # n_jobs=3#,



gridgbm.fit(X_train, np.array(y_train[0]))


```



Thanks and sorry for the long delays in supplying an example,
Dan

**Comment by dancaspi** [comment]
@StrikerRUS  thanks! will update on that

**Comment by StrikerRUS** [comment]
@dancaspi 
In general, it's better to use GroupKFold for ranking.
http://scikit-learn.org/stable/modules/generated/sklearn.model_selection.GroupKFold.html
Example can be found here:
https://github.com/Microsoft/LightGBM/blob/4df7b21dcf2ca173a812f9667e30a21ef827104e/python-package/lightgbm/engine.py#L267-L274

**Comment by rovedream** [comment]
With the same problem, the LambdaRank task can't be optimized for parameters.

**Comment by StrikerRUS** [comment]
@rovedream What's your usecase?

**Comment by rovedream** [comment]
修改的自带示例：
https://github.com/Microsoft/LightGBM/blob/master/tests/python_package_test/test_sklearn.py
[https://avatars2.githubusercontent.com/u/6154722?s=400&v=4]<https://github.com/Microsoft/LightGBM/blob/master/tests/python_package_test/test_sklearn.py>

LightGBM/test_sklearn.py at master ・ Microsoft/LightGBM ...<https://github.com/Microsoft/LightGBM/blob/master/tests/python_package_test/test_sklearn.py>
github.com
A fast, distributed, high performance gradient boosting (GBDT, GBRT, GBM or MART) framework based on decision tree algorithms, used for ranking, classification and many other machine learning tasks.




        X_train, y_train = load_svmlight_file(os.path.join(os.path.dirname(os.path.realpath(__file__)), '../../examples/lambdarank/rank.train'))
        X_test, y_test = load_svmlight_file(os.path.join(os.path.dirname(os.path.realpath(__file__)), '../../examples/lambdarank/rank.test'))
        q_train = np.loadtxt(os.path.join(os.path.dirname(os.path.realpath(__file__)), '../../examples/lambdarank/rank.train.query'))
        q_test = np.loadtxt(os.path.join(os.path.dirname(os.path.realpath(__file__)), '../../examples/lambdarank/rank.test.query'))
        params={'boosting_type':'gbdt', 'objective':'lambdarank', 'score':'ndcg',
            'colsample_bytree':0.5, 'subsample':1.0, 'learning_rate':0.02,
            'num_leaves': 100, 'max_depth':20, 'min_child_samples':5,
            'n_estimators':30, 'random_state':42,
        }
        params_grid = {'n_estimators': [10, 20, 30, 40],
                       'num_leaves': [20, 50, 100, 200],
                       'max_depth': [5,10,15,20],
                       'learning_rate': [0.01, 0.02, 0.03],
                      }
        gbm = lgb.LGBMRanker(**params)
        gbm = RandomizedSearchCV(gbm, params_grid, n_iter=20, cv=10, verbose=1,
                                 #fit_params={'group':q_train}
                                 )
        gbm.fit(X_train, y_train, group=q_train)



________________________________
发件人: Nikita Titov <notifications@github.com>
发送时间: 2018年8月1日 10:10
收件人: Microsoft/LightGBM
抄送: rovedream; Mention
主题: Re: [Microsoft/LightGBM] how to pass group parameter for sklearn gridsearch for ranking (#1137)


@rovedream<https://github.com/rovedream> What's your usecase?

―

**Comment by rovedream** [comment]
@StrikerRUS  sklearn v0.19 already supports ndcg scorer.

**Comment by StrikerRUS** [comment]
@rovedream Use `GroupKFold` generator instead of `cv=10`. See this post https://github.com/Microsoft/LightGBM/issues/1137#issuecomment-409190481

**Comment by StrikerRUS** [comment]
@rovedream NDCG was broken and reverted if `19.1`: http://scikit-learn.org/stable/whats_new.html#api-changes

**Comment by rovedream** [comment]
@StrikerRUS I'll try. thanks!

**Comment by StrikerRUS** [comment]
@rovedream Sorry, I'm kind of busy now, so haven't had a chance to test this snippet properly. Anyway, it maybe helpful to start from:

```
import lightgbm as lgb
import numpy as np
from sklearn.datasets import load_svmlight_file       
from sklearn.model_selection import GroupKFold, RandomizedSearchCV

X_train, y_train = load_svmlight_file(os.path.join(os.path.dirname(os.path.realpath(__file__)), '../../examples/lambdarank/rank.train'))
X_test, y_test = load_svmlight_file(os.path.join(os.path.dirname(os.path.realpath(__file__)), '../../examples/lambdarank/rank.test'))
q_train = np.loadtxt(os.path.join(os.path.dirname(os.path.realpath(__file__)), '../../examples/lambdarank/rank.train.query'))
q_test = np.loadtxt(os.path.join(os.path.dirname(os.path.realpath(__file__)), '../../examples/lambdarank/rank.test.query'))

params={'boosting_type':'gbdt', 'objective':'lambdarank',
    'colsample_bytree':0.5, 'subsample':1.0, 'learning_rate':0.02,
    'num_leaves': 100, 'max_depth':20, 'min_child_samples':5,
    'n_estimators':30, 'random_state':42,}     
params_grid = {'n_estimators': [10, 20, 30, 40],
    'num_leaves': [20, 50, 100, 200],
    'max_depth': [5,10,15,20],
    'learning_rate': [0.01, 0.02, 0.03],
              }

gbm = lgb.LGBMRanker(**params)

group_info = q_train.astype(int)
flatted_group = np.repeat(range(len(group_info)), repeats=group_info)
gkf = GroupKFold(n_splits=5)
cv = gkf.split(X_train, y_train, groups=flatted_group)
cv_group = gkf.split(X_train, groups=flatted_group)  # separate CV generator for manual splitting groups

# generator produces `group` argument for LGBMRanker for each fold
def group_gen(flatted_group, cv):
    for train, _ in cv:
        yield np.unique(flatted_group[train], return_counts=True)[1]

gen = group_gen(flatted_group, cv_group)
grid = RandomizedSearchCV(gbm, params_grid, n_iter=10, cv=cv, verbose=2, scoring=<your_custom_ndcg_scorrer>, refit=False)
grid.fit(X_train, y_train, group=next(gen))
```

As I said, scikit-learn hasn't built-in NDCG scorer, so you should implement it on yourself.
Maybe good points to start:
https://www.kaggle.com/davidgasquez/ndcg-scorer
https://gist.github.com/mblondel/7337391
