### ISSUE TITLE
R-package isFalse function doesn't exists

### ISSUE THREAD

**Issue by jacquespeeters** [Microsoft/LightGBM#1147]
https://github.com/Microsoft/LightGBM/blob/a5f43c9d559848aed71a870321d2729fe64beab1/R-package/R/callback.R#L362

I had an error with this specific line stating isFalse function didn't exist.

Replaced isFalse function with ! as done in other part of the script. Re-installed the package and now it's working fine.

I'm on Mac OS, followed these instructions 
http://lightgbm.readthedocs.io/en/latest/Installation-Guide.html#macos
Then these ones
https://github.com/Microsoft/LightGBM/tree/master/R-package#install (only the export and R CMD INSTALL parts).

**Comment by guolinke** [comment]
@Laurae2

**Comment by amir-ghasemi** [comment]
I can confirm the isFalse issue and the fix by @jacquespeeters on Windows also.
