### ISSUE TITLE
Typo in SerialTreeLearner header

### ISSUE THREAD

**Issue by lgrz** [Microsoft/LightGBM#1148]
I believe this may be a typo in serial_tree_learner.h:

https://github.com/Microsoft/LightGBM/blob/master/src/treelearner/serial_tree_learner.h#L160

Should `leafIdx` be changed to `leaf_idx`? See the class declaration:

https://github.com/Microsoft/LightGBM/blob/master/src/treelearner/serial_tree_learner.h#L100

Happy to submit a patch if that is required.

**Comment by guolinke** [comment]
@lgrz yeah, welcome to fix it.

**Comment by StrikerRUS** [comment]
Fixed in #1149.
