### ISSUE TITLE
Python error - unknown type

### ISSUE THREAD

**Issue by gugatr0n1c** [Microsoft/LightGBM#115]
Hi, trying to run this code a getting this error, any help? (latest version)

for ii in range(0, 100000):
    
    lr = np.random.choice([0.25, 0.1, 0.05, 0.025, 0.01, 0.005])
    listy = np.random.choice([25, 50, 100, 250, 500, 750, 1000, 2000])
    min_in_leaf = np.random.choice([25, 50, 100, 250, 500, 750, 1000, 2000])
    subF = np.random.choice([0.15, 0.2, 0.3, 0.5, 0.66, .75, 0.83])
    subR = np.random.choice([0.15, 0.2, 0.3, 0.5, 0.66, .75, 0.83])
    max_depth = np.random.choice([6, 10, 15, 25, 45, 100, 250])
    
    iterace = 10000
    if only_testing:
        min_in_leaf = 25
        iterace = 10
    
    params = {
                        'task' : 'train',
                        'boosting_type' : 'gbdt',
                        'objective' : 'binary',
                        'metric' : 'binary_logloss',
                        'max_depth' : max_depth,
                        'num_leaves' : listy,
                        'min_data_in_leaf' : min_in_leaf,
                        'learning_rate' : lr,
                        'feature_fraction' : subF,       
                        'bagging_fraction' : subR,
                        'bagging_freq': 1,
                        'verbose' : 0,
                        'nthread' : 4,
                        'is_unbalance' : True
                    }
    model = lg.train(
                        params,
                        (matrix_learn, target_learn),
                        num_boost_round = iterace,
                        valid_datas = (matrix_test, target_test),
                        early_stopping_rounds = 50
                    )

    prediction_test = model.predict(matrix_test)

error:
Traceback (most recent call last):
  File "search_37.py", line 128, in <module>
    early_stopping_rounds = 50
  File "/usr/local/lib/python3.5/dist-packages/lightgbm-0.1-py3.5.egg/lightgbm/engine.py", line 149, in train
    predictor=predictor)
  File "/usr/local/lib/python3.5/dist-packages/lightgbm-0.1-py3.5.egg/lightgbm/engine.py", line 43, in _construct_dataset
    params=params)
  File "/usr/local/lib/python3.5/dist-packages/lightgbm-0.1-py3.5.egg/lightgbm/basic.py", line 475, in __init__
    params_str = param_dict_to_str(params)
  File "/usr/local/lib/python3.5/dist-packages/lightgbm-0.1-py3.5.egg/lightgbm/basic.py", line 121, in param_dict_to_str
    % (key, type(val).__name__))
TypeError: unknow type of parameter:num_leaves , got:int64
Exception ignored in: <bound method Dataset.__del__ of <lightgbm.basic.Dataset object at 0x7f2f0deb58d0>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/lightgbm-0.1-py3.5.egg/lightgbm/basic.py", line 636, in __del__
    _safe_call(_LIB.LGBM_DatasetFree(self.handle))
AttributeError: 'Dataset' object has no attribute 'handle'

**Comment by guolinke** [comment]
@gugatr0n1c It seems we cannot handle numpy object as parameter now. 
you can change 
listy = np.random.choice([25, 50, 100, 250, 500, 750, 1000, 2000])
to
listy = int(np.random.choice([25, 50, 100, 250, 500, 750, 1000, 2000]))
for quick fix.

**Comment by guolinke** [comment]
@wxchan  Is it any way to convert numpy data to python type elegantly?

**Comment by gugatr0n1c** [comment]
yeap, working... so it is up to you then to close this issue or not... thx

**Comment by wxchan** [comment]
@guolinke It may be better to convert them directly to string, by adding more types in param_dict_to_str:
```
def param_dict_to_str(data):
    pairs = []
    for key, val in data.items():
        if is_str(val) or isinstance(val, (int, float, bool, np.integer, np.float, np.float32)):
            pairs.append(str(key)+'='+str(val))
        elif isinstance(val, (list, set, tuple, Series)) or is_numpy_1d_array(val):
            pairs.append(str(key)+'='+','.join([str(v) for v in val]))
        else:
            raise TypeError('unknow type of parameter:%s , got:%s'
                            % (key, type(val).__name__))
    return ' '.join(pairs)
```
