### ISSUE TITLE
Parameters check

### ISSUE THREAD

**Issue by StrikerRUS** [Microsoft/LightGBM#1156]
@guolinke 
Is this duplicated check OK:
https://github.com/Microsoft/LightGBM/blob/968a353f4a0432cfb2b68b7c7df08346858d1480/src/io/config.cpp#L441-L443
?
Refer to 42710827455dd3530ff59830f655aefd7376fdb1.

**Comment by guolinke** [comment]
oh, it is typo. they should top_rate and other_rate
