### ISSUE TITLE
ERROR  pip install lightgbm --install-option=--gpu 

### ISSUE THREAD

**Issue by shitian-ni** [Microsoft/LightGBM#1170]
## Environment info
Operating System:Ubuntu 16.04.3 LTS
CPU:Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz
C++/Python/R version:g++ (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609
/Python 2.7.12

## Error Message:
root@281b04545321:/workspace/xgboost/build# pip install lightgbm --install-option=--gpu
/usr/local/lib/python2.7/dist-packages/pip/commands/install.py:194: UserWarning: Disabling all use of wheels due to the use of --build-options / --global-options / --install-options.
  cmdoptions.check_install_build_global(options)
Collecting lightgbm
  Using cached lightgbm-2.0.12.tar.gz
Requirement already satisfied: numpy in /usr/local/lib/python2.7/dist-packages (from lightgbm)
Collecting scipy (from lightgbm)
  Using cached scipy-1.0.0.tar.gz
Collecting scikit-learn (from lightgbm)
  Using cached scikit-learn-0.19.1.tar.gz
Skipping bdist_wheel for lightgbm, due to binaries being disabled for it.
Skipping bdist_wheel for scipy, due to binaries being disabled for it.
Skipping bdist_wheel for scikit-learn, due to binaries being disabled for it.
Installing collected packages: scipy, scikit-learn, lightgbm
  Running setup.py install for scipy ... error
    Complete output from command /usr/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-V49OgN/scipy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-SW3Nmy-record/install-record.txt --single-version-externally-managed --compile --gpu:
    
    Note: if you need reliable uninstall behavior, then install
    with pip instead of using `setup.py install`:
    
      - `pip install .`       (from a git repo or downloaded source
                               release)
      - `pip install scipy`   (last SciPy release on PyPI)
    
    
    usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: -c --help [cmd1 cmd2 ...]
       or: -c --help-commands
       or: -c cmd --help
    
    error: option --gpu not recognized
    
    ----------------------------------------
Command "/usr/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-V49OgN/scipy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-SW3Nmy-record/install-record.txt --single-version-externally-managed --compile --gpu" failed with error code 1 in /tmp/pip-build-V49OgN/scipy/
## Steps to reproduce

1. [pip install lightgbm --install-option=--gpu](https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-version)

**Comment by guolinke** [comment]
@StrikerRUS

**Comment by guolinke** [comment]
@shitian-ni it seems you need to install scipy first independently .

**Comment by StrikerRUS** [comment]
Yeah, I think scipy installation (``pip install scipy``) should solve the problem.

**Comment by shitian-ni** [comment]
Using `pip install scipy` worked. Thanks.
