### ISSUE TITLE
Allow distributed training to have a 'master' for organizing correct ports

### ISSUE THREAD

**Issue by ebernhardson** [Microsoft/LightGBM#1172]
I'm doing training in a hadoop cluster, not necessarily because it's the best way but because it's where I have the ability to request hundreds of cores of compute power on-demand from our infrastructure. Talking to lightgbm from pyspark to get execution on the remote machines is relatively easy, but setting up the distributed training is painful due to having to pre-agree on port numbers to use.

It would be convenient if I could spin up some sort of 'master' organizer on the instance driving pyspark and distribute just the port number for this to the individual workers. Those workers could then open up some random port, tell the master about it, and once the right number of workers have reported their port the master could distribute that information back to the individual workers.

This could all even be done outside lightgbm, handled strictly in my own python code. It would require a change to lightgbm though to allow providing an open file descriptor instead of having lightgbm open the port itself. This would allow the python side code to gracefully handle situations where the port it wants to use has already been taken, trying to listen on ports until it finds an open one. Because there are potentially many different applications (or even training instances of the same application) on the same host it seems like some pre-determined port being already used will be a common error case.

Does this seem reasonable? Are there perhaps other options I havn't considered?

**Comment by guolinke** [comment]
I think "the application master" is independent with LightGBM. 

the application master logic is:
1. A 24-hours-run master server(independent with LightGBM), that just used to collect the ip/ports from clients. 
2. the clients (independent with LightGBM). When start a new parallel job, the clients send its ip/port, application ID and num_nodes to master.
3. Servers send all clients' information back to all clients, when receive enough nodes for one application ID.
4. the  clients now can save ip/ports information to the 'machine_list' file, which can be used in LightGBM.
5. With the dynamic generated 'machine_list' file, you can start a new distributed LightGBM job.

I think this logic suits for any distributed job.

**Comment by ebernhardson** [comment]
My main concern with this solution is the ordering of selecting ports and opening them. Typically in an application running on shared servers you first start opening ports until you find an open one, then you report back "running on port 23456". If you decide ahead of time you are running on a specific port, but then find out when lightgbm tries to open it that some other application decided to use the same port, you are stuck. This is why i think having the ability to open ports on the python side and pass in an open file descriptor would be useful.

**Comment by guolinke** [comment]
@ebernhardson You can add some `try` logics to get available ports in your clients. I think this is also the problem in `application master`.
