### ISSUE TITLE
got an error Exception: Cannot get label before construct Dataset

### ISSUE THREAD

**Issue by TaiChiBagua** [Microsoft/LightGBM#1173]
data_set = lgb.Dataset(data=svm_light_file)
labels = data_set.get_label()

i ran this code, but got an error   Exception: Cannot get label before construct Dataset.
how should i use dataset to get the labels.
the data format i use is svmlight

**Comment by guolinke** [comment]
`
data_set = lgb.Dataset(data=svm_light_file).construct()
labels = data_set.get_label()
`
