### ISSUE TITLE
Can LightGBM support do the feature discretize and feature combination 

### ISSUE THREAD

**Issue by weidong8405347** [Microsoft/LightGBM#1176]
i have a continous dataset, want to use logistic regression model to train
i want to use lightGBM do the feature discretizing and feature combination
because i want to visualize the lightGBM model to tell use how the feature is discretize and is combined, so i wonder if there is a tools to visualize the lightGBM models

**Comment by guolinke** [comment]
refer to https://github.com/Lcorvle/BOOSTVis2
