### ISSUE TITLE
`gbm.best_iteration_ is None` when `early_stopping_round = 3` in sklearn API

### ISSUE THREAD

**Issue by startakovsky** [Microsoft/LightGBM#1181]
The code in the image below indicates that in the sklearn API, `best_iteration_` is not set even when early_stopping_round > 0.

Is this expected behavior?

![image](https://user-images.githubusercontent.com/689723/34657608-a5b1f558-f3dc-11e7-9389-5ddb30e74b50.png)

**Comment by guolinke** [comment]
@startakovsky 
I think it is ```early_stopping_rounds``` in `fit` function: https://github.com/Microsoft/LightGBM/blob/master/python-package/lightgbm/sklearn.py#L295-L300

ping @StrikerRUS @wxchan 
However, I am confused about why early stopping is working in @startakovsky 's case. 
BTW, why `best_score` is set independently ? : https://github.com/Microsoft/LightGBM/blob/master/python-package/lightgbm/sklearn.py#L478-L481

**Comment by startakovsky** [comment]
@guolinke the following does work... and for now I will use this approach to track `gbm.best_iteration_`. Just hoping it would also work when supplied to `params` (i.e. `lgb.LGBClassifier(**params)`.

![image](https://user-images.githubusercontent.com/689723/34657898-84e1b176-f3df-11e7-817a-571983a99f87.png)

**Comment by StrikerRUS** [comment]
@guolinke 
>BTW, why best_score is set independently ? https://github.com/Microsoft/LightGBM/blob/master/python-package/lightgbm/sklearn.py#L478-L481

The answer is #890.

**Comment by StrikerRUS** [comment]
@guolinke 
Yeah, it seems that in this situation `early_stopping_rounds` is passed through `params` into `train()` and used there.

>Should we have the same conversion in sklearn interface?

In my opinion, all users are adult enough to read the docstring and notice that `early_stopping_rounds` has own parameter and shouldn't be passed via `**kwargs`.

**Comment by guolinke** [comment]
@startakovsky I agree with @StrikerRUS . Logically, `early_stopping_rounds` is used to control the `fit`(training) process, so using it in `fit` is more reasonable.
