### ISSUE TITLE
can i use hdfs as the datasource to train lambdarank with multiple machines ?

### ISSUE THREAD

**Issue by TaiChiBagua** [Microsoft/LightGBM#1183]
I have the formated data stored in hdfs, which is 40G
can i train the model with multiple machines without first copy to local, 
or is there some methods to use to accelerate the process ?
thanks!

**Comment by Laurae2** [comment]
I think you need to convert first to a readable format for LightGBM (CSV, SVMLight, or LightGBM binary) then do local copies.

ping @guolinke for more information

**Comment by guolinke** [comment]
I think with the help of MMLSpark(https://github.com/azure/mmlspark), this issue is solved.

**Comment by levyfan** [comment]
Hi @guolinke, does mmlspark support lambdarank? I can not find how to train lambdarank model with mmlspark. And the comment here says it is not supported:

https://github.com/Azure/mmlspark/blob/d98b58b34b9a7f7690bee949283a098621ddfac3/src/lightgbm/src/main/scala/LightGBMParams.scala#L47

**Comment by StrikerRUS** [comment]
@levyfan They are working on this: https://github.com/Azure/mmlspark/issues/446.
