### ISSUE TITLE
Can we use GPU in python package? 

### ISSUE THREAD

**Issue by PayneJoe** [Microsoft/LightGBM#1185]
I've already install GPU versioned Lightgbm successfully, unfortunately not got a way to use it yet. Providing any examples about this is much appreciated!

**Comment by StrikerRUS** [comment]
You need to set an additional parameter `device` : `gpu` (along with your other options like` learning_rate`, `num_leaves`, etc) to use GPU in Python. It will use the first GPU installed on the system by default (`gpu_platform_id=0 `and `gpu_device_id=0`). https://lightgbm.readthedocs.io/en/latest/Parameters.html#gpu-parameters

You may read the following (examples in R, but everything should be clear):
https://lightgbm.readthedocs.io/en/latest/GPU-Targets.html

**Comment by StrikerRUS** [comment]
BTW, @huanzhang12 is it OK that GPU-Tutorial says
>It will use the first GPU installed on the system by default (gpu_platform_id=0 and gpu_device_id=0).

But actually default values are -1 (like it's said in Parameters):
>gpu_platform_id, default=-1, type=int
...
default value is -1, means the system-wide default platform

>gpu_device_id, default=-1, type=int
...
default value is -1, means the default device in the selected platform

?

**Comment by huanzhang12** [comment]
@StrikerRUS Yes I think you are right. The language in documentation is inaccurate. I will fix it.

My understanding is that a id = 0 means the first platform/GPU. When setting the id to -1, it will use the default platform/GPU. The default/GPU does not have to be the first platform/GPU (with id = 0).

**Comment by PayneJoe** [comment]
Thanks @StrikerRUS ! Cannot imagine a super parameter can get GPU running. I'll go and confirm it later on.
