### ISSUE TITLE
sklearn remove warning, there is no `verbose_eval`

### ISSUE THREAD

**Issue by startakovsky** [Microsoft/LightGBM#1186]
Is there any way to remove warnings in the sklearn API?  The [fit](http://lightgbm.readthedocs.io/en/latest/Python-API.html#lightgbm.LGBMModel.fit) function only takes `verbose` which seems to only toggle the display of the per iteration details.

`[LightGBM] [Warning] min_data_in_leaf is set=74, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=74.`

**Comment by StrikerRUS** [comment]
You are trying to set one parameter twice (or you are using an alias of parameter which shouldn't be passed via `**kwargs`). Please pay attention to the `aliases` in docs: https://lightgbm.readthedocs.io/en/latest/Parameters.html#learning-control-parameters

**Comment by startakovsky** [comment]
Thanks @StrikerRUS , you seem to be responding specifically to this warning. Here is another warning: `[LightGBM] [Warning] No further splits with positive gain, best gain: -inf`.

I am seeing this line appear too many times and other lines during training and I am interested in completely suppressing this warning. 

These warnings are generated from the C++ code, and doesn't seem to be suppressed by filtering warnings from Python's warnings library.

I have tried setting verbose=-1, but it is not suppressing the warning. 

Any advice, hacks or ways I might be able to suppress all warnings?

**Comment by StrikerRUS** [comment]
@startakovsky Yeah, I was talking about that concrete warning.

Now ping @guolinke because you've already discussed this with him in #1157.

**Comment by startakovsky** [comment]
thanks @StrikerRUS 

@guolinke how do I suppress the C++ generated warnings in the sklearn API?
 https://github.com/Microsoft/LightGBM/issues/1157

**Comment by guolinke** [comment]
@startakovsky 
you can set `verbose=-1` in Constructor, not the `fit` function.

**Comment by tnmichael309** [comment]
import warnings 
warnings.filterwarnings('ignore')

**Comment by AdamsMi** [comment]
doesn't work (the filter warnings hack). This is really annoying, this warning. Can anybody finally tell us how to get rid of this message?

**Comment by StrikerRUS** [comment]
@AdamsMi filtering warnings cannot work in this case because warnings come directly from C++ code. Passing `verbose=-1` or  `verbose_eval=-1` doesn't work?

**Comment by guolinke** [comment]
for sklearn interface, you can set `verbose=-1` when defining the model (not in `fit`).
for lgb.train interface, you can set `verbose=-1` in `param` dict.

**Comment by tnmichael309** [comment]
Sadly... I use warining filter along with @guolinke mentioned and it works.
In my case, my warning came from resetting categorical features.
I'm using jupyter notebook on windows.

**Comment by tnmichael309** [comment]
Maybe I used notebook and the warning was not shown on it but console only.

**Comment by marcioribp** [comment]
I am having the same problem @tnmichael309.

`[LightGBM] [Warning] Met categorical feature which contains sparse values. Consider renumbering to consecutive integers started from zero`

Tried everything suggested and nothing works, this warning is haunting me.

Using lgb interface on linux console.

**Comment by StrikerRUS** [comment]
@marcioribp Please refer to https://lightgbm.readthedocs.io/en/latest/Advanced-Topics.html#categorical-feature-support, #1636
> Categorical features must be encoded as non-negative integers (int) less than Int32.MaxValue (2147483647). It is best to use a contiguous range of integers started from zero.

https://github.com/microsoft/LightGBM/issues/1920#issuecomment-449228884
> If you don't have memory issues, you can ignore this.

**Comment by marcioribp** [comment]
> @marcioribp Please refer to https://lightgbm.readthedocs.io/en/latest/Advanced-Topics.html#categorical-feature-support, #1636
> 
> > Categorical features must be encoded as non-negative integers (int) less than Int32.MaxValue (2147483647). It is best to use a contiguous range of integers started from zero.
> 
> [#1920 (comment)](https://github.com/microsoft/LightGBM/issues/1920#issuecomment-449228884)
> 
> > If you don't have memory issues, you can ignore this.

@StrikerRUS 
Thank you very much! As it turns out, I had to convert my category columns to int 32 as mentioned in the documentation page.
