### ISSUE TITLE
what's the libsvm format using weight_column parameter?

### ISSUE THREAD

**Issue by ryan7th** [Microsoft/LightGBM#1188]
i wanna use the weight parameter describe in the doc 
```
weight, default="", type=string, alias=weight_column
specify the weight column
use number for index, e.g. weight=0 means column_0 is the weight
add a prefix name: for column name, e.g. weight=name:weight
Note: index starts from 0. And it doesn't count the label column when passing type is Index, e.g. when label is column_0, and weight is column_1, the correct parameter is weight=0
```
but i do not quite understand the doc above.
i suppose if i set the label=0 and weight=0, the data format should be
label weight fid:v1 fid:v2 .....

but what's the meaning of 'name:weight'?
can anybody give me an advice?

**Comment by guolinke** [comment]
you cannot skip the index of weight column, only the index of label can be skipped in Libsvm format. 
so when you use 0-th column as weight, the format should be like `label 0:weight 1:f1 2:f2 `

It is `weight=name:name_of_weight_column`, which is used in csv/tsv format.

**Comment by guolinke** [comment]
@StrikerRUS do you think current descriptions of these columns is clear ? should we refine them ?

**Comment by ryan7th** [comment]
@guolinke i think it will be better to give an example, since every has its own understanding

**Comment by StrikerRUS** [comment]
@guolinke I think the descriptions are OK, but we could give example [here](https://lightgbm.readthedocs.io/en/latest/Parameters.html#weight-data) as suggested by @ryan7th .
