### ISSUE TITLE
error message: TypeError: __init__() got an unexpected keyword argument 'max_bin'

### ISSUE THREAD

**Issue by shenmemingzine** [Microsoft/LightGBM#1190]
Please search your question on previous issues, [stackoverflow](https://stackoverflow.com/questions/tagged/lightgbm) or other search engines before you open a new one.

For bugs and unexpected issues, please provide following information, so that we could reproduce on our system.

## Environment info
Operating System: Kaggle kernel
CPU: N/A
C++/Python/R version: Python

## Reproducible examples
import numpy as np
import pandas as pd
train = pd.read_csv("../input/train.tsv", sep = "\t", low_memory = True, )
test = pd.read_csv("../input/test.tsv", sep = "\t", low_memory = True)

merge = pd.concat([train.drop(["train_id", "price"], axis = 1), 
                   test.drop(["test_id"], axis = 1)], axis = 0)
def fill_missing_data(data):
    data.category_name.fillna(value = "Other/Other/Other", inplace = True)
    data.brand_name.fillna(value = "Unknown", inplace = True)
    data.item_description.fillna(value = "No description yet", inplace = True)
    return data

merge = fill_missing_data(merge)
def split_cat(data):
    data["main_cat"], data["subcat1"], data["subcat2"] = data["category_name"].str.split("/", 2).str
    return data

merge = split_cat(merge)
merge = merge.drop(["category_name"], axis = 1)

cat_features = ["main_cat", "subcat1", "subcat2", "item_condition_id"]
for f in cat_features: 
    merge[f] = merge[f].astype("category")

from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.preprocessing import LabelBinarizer

cv = CountVectorizer(min_df = 10,
                     max_features = 55000,
                     ngram_range = (1, 2))
names = cv.fit_transform(merge["name"])

cv = CountVectorizer()
main_cat = cv.fit_transform(merge["main_cat"])
subcat1 = cv.fit_transform(merge["subcat1"])
subcat2 = cv.fit_transform(merge["subcat2"])

tv = TfidfVectorizer(max_features = 150000,
                     ngram_range = (1, 3),
                     stop_words = "english")
descrip = tv.fit_transform(merge["item_description"])

# from sklearn.feature_extraction.text import HashingVectorizer
# hv = HashingVectorizer(norm = "l1",
#                        ngram_range = (1, 3),
#                        stop_words = "english")
# descrip = hv.fit_transform(merge["item_description"])

lb = LabelBinarizer(sparse_output = True)
brands = lb.fit_transform(merge["brand_name"])

from scipy.sparse import csr_matrix, hstack

dummies = csr_matrix(pd.get_dummies(merge[["item_condition_id", "shipping"]],
                                          sparse = True).values)
sparse_merge = hstack((names, main_cat, subcat1, subcat2, descrip, brands, dummies)).tocsr()

nrow_train = train.shape[0]
X_train = sparse_merge[:nrow_train]
Y_train = np.log(train["price"] + 1)
X_test = sparse_merge[nrow_train:]

import lightgbm as lgb
from sklearn.model_selection import train_test_split

params = {"learning_rate": 0.45,
          "application": "regression",
          "max_depth": 4,
          "num_leaves": 90,
          "verbosity": -1,
          "metric": "RMSE",
          "data_random_seed": 1,
          "bagging_fraction": 0.5,
          "nthread": 4}

train_X, valid_X, train_y, valid_y = train_test_split(X_train, Y_train, test_size = 0.15, random_state = 150) 
d_train = lgb.Dataset(train_X, label = train_y, max_bin = 8000)
d_valid = lgb.Dataset(valid_X, label = valid_y, max_bin = 8000)
watchlist = [d_train, d_valid]
lgb_model = lgb.train(params, train_set = d_train, num_boost_round = 8000, valid_sets = watchlist, 
                      early_stopping_rounds = 50, verbose_eval = 1000)
lgb_preds = lgb_model.predict(X_test)

## Steps to reproduce
run the example
1.
2.
3.

**Comment by StrikerRUS** [comment]
`max_bin` parameter was deprecated and now should be passed via `params`.
