### ISSUE TITLE
predict on saved binrary datasets

### ISSUE THREAD

**Issue by yitang** [Microsoft/LightGBM#1191]
Hi, I wonder why we can't predict using the binary data format like?

if i run the following code line, i get the unknown train dataset format error.

```
p = lgb.Dataset(Xtrain).construct()
p2 = lgb.Dataset(Xval, reference=p).construct()
p3 = lgb.Dataset(Xtest, reference=p).construct()
p.save_binary(join(output_dir, 'Xtrain.ldt'))
p2.save_binary(join(output_dir, 'Xval.ldt'))
p3.save_binary(join(output_dir, 'Xtest.ldt'))

bst = lgb.train({}, 'Xtrain.ldt')
bst.predict('Xval.ldt'")
```

**Comment by guolinke** [comment]
@yitang 
The reason is the binary Dataset only contains the binned index of feature values, which cannot be used in prediction. 

If you want to predict with files, you can use csv/libsvm format.
