### ISSUE TITLE
A bug in ResetGoss

### ISSUE THREAD

**Issue by Zibi789** [Microsoft/LightGBM#1192]
There is a bug in ResetGoss (file boosting/goss.hpp), lines 77 and 78.
The buggy case is here:
```
gbdt_config_->top_rate is 0.1
gbdt_config_->other_rate is 0.2
num_data_ is 3
```
Then `bag_data_cnt` is 0, and `new Dataset(bag_data_cnt)` generates an error message informing that `bag_data_cnt must be > 0`.
The simplest way to fix it is to add this line after line 77:
```
bag_data_cnt = std::max(1, bag_data_cnt);
```
And then it is necessary to add the header file `algorithm`

**Comment by guolinke** [comment]
@Zibi789 thanks very much! 
Would you like to create a PR to fix it ?

**Comment by Zibi789** [comment]
Yes, I can. How can I push a branch to LightGBM? It seems that I need a permission to do it.

**Comment by chivee** [comment]
@Zibi789 , you can fork into your own repo, fix the bug and send it back though https://github.com/Microsoft/LightGBM/compare
