### ISSUE TITLE
Bug in ArgMaxAtK

### ISSUE THREAD

**Issue by aazz521** [Microsoft/LightGBM#1195]
I accidentally found there's a bug in function ArgMaxAtK(file include/LightGBM/utils/array_args.h)

Test case:
a = {2, 4, 1, 3}
MaxK(a, 3, out)  => out = {4, 3, 1}
which I expected to be {4, 3, 2}

In line 136
(
if ((k > l && k < r) || l == 0 || r == end - 1)
),
condition "l == 0" is buggy.
When l == 0 and k > 1, the max number is the first element, while the right hand side of pivot may still be unordered, so further partitioning is necessary.

Simple fix is to remove this condition (validation is tbd),  please check this out.

**Comment by guolinke** [comment]
@aazz521 can you try the #1196? I think it should fix this.
