### ISSUE TITLE
Boosting type specification in  Python sklearn

### ISSUE THREAD

**Issue by jcrosskey** [Microsoft/LightGBM#120]
Can you add option to specify the boosting type for sklearn?

**Comment by wxchan** [comment]
You can try `fit(..., other_params={'boosting': 'dart'})` now. 

We will discuss where to put this option. @guolinke

**Comment by jcrosskey** [comment]
Thank you. This is a quick solution!
I was thinking about specifying it when a model is instantiated, so that this can be used in other methods provided in sklearn.
