### ISSUE TITLE
Cannot get GPU to work with lightgbm in R

### ISSUE THREAD

**Issue by originalchris** [Microsoft/LightGBM#1200]
Hello,

I followed the steps in the following link.

[GitHub](https://lightgbm.readthedocs.io/en/latest/GPU-Windows.html)

and tested with the code:

```
library(lightgbm)
data(agaricus.train, package = "lightgbm")
train <- agaricus.train
train$data[, 1] <- 1:6513
dtrain <- lgb.Dataset(train$data, label = train$label)
data(agaricus.test, package = "lightgbm")
test <- agaricus.test
dtest <- lgb.Dataset.create.valid(dtrain, test$data, label = test$label)
valids <- list(test = dtest)

params <- list(objective = "regression",
               metric = "rmse",
               device = "gpu",
               gpu_platform_id = 0,
               gpu_device_id = 0,
               nthread = 1,
               boost_from_average = FALSE,
               num_tree_per_iteration = 10,
               max_bin = 32)
model <- lgb.train(params,
                   dtrain,
                   2,
                   valids,
                   min_data = 1,
                   learning_rate = 1,
                   early_stopping_rounds = 10)
```

and I get the following error:

```
[LightGBM] [Fatal] GPU Tree Learner was not enabled in this build. Recompile with CMake option -DUSE_GPU=1
Error in .subset2(public_bind_env, "initialize")(...) : 
  lgb.Booster: cannot create Booster handle
```
Would anyone be able to help me with this problem? I have lightgbm working properly when I train other under my cpu.

I currently use an Intel i7 2600K and an Nvidia GTX TITAN Black Edition (the old GK110 Kepler version) on Windows 10.

Thank you.

**Comment by guolinke** [comment]
@Laurae2 

BTW, Use the GPU install guide here [https://github.com/Microsoft/LightGBM/tree/master/R-package] is working.

**Comment by slfan2013** [comment]
I followed exactly the [guide](https://github.com/Microsoft/LightGBM/tree/master/R-package) but still got the same error of `[LightGBM] [Fatal] GPU Tree Learner was not enabled in this build.
Please recompile with CMake option -DUSE_GPU=1`

**Comment by BovenPeng** [comment]
> I followed exactly the [guide](https://github.com/Microsoft/LightGBM/tree/master/R-package) but still got the same error of `[LightGBM] [Fatal] GPU Tree Learner was not enabled in this build. Please recompile with CMake option -DUSE_GPU=1`

Maybe you can check your CUDA version.
I have met the same issue before, `[LightGBM] [Fatal] GPU Tree Learner was not enabled in this build. Please recompile with CMake option -DUSE_GPU=1`.
But I find it was my CUDA version is too old to support relevant GPU computations on python 3.5.6.

## Environment info
Operating System: Windows10

CPU/GPU model: GPU - NVIDIA 1080TI

C++/Python/R version: Python 3.5.6

CUDA 9.0, which has this error when I use CUDA 8.0 even though I have transformed to use Python 3.5.6 but I forget to update my CUDA version.

Hope this can help u. 😺
