### ISSUE TITLE
VS 2017 Compilation Warnings

### ISSUE THREAD

**Issue by Laurae2** [Microsoft/LightGBM#1207]
@guolinke Are those warnings expected in VS 2017?

## Environment info

Operating System: Windows 8.1 Pro
CPU: i7-7700HQ
C++/Python/R version: R 3.4.2

## Warning Message:

```r
"E:\GitHub\LightGBM\R-package\src\build\_lightgbm.vcxproj" (default target) (1) ->
(ClCompile target) -> 
  cl : Command line warning D9025: overriding '/DNDEBUG' with '/UNDEBUG' [E:\GitHub\LightGBM\R-package\src\build\_lightgbm.vcxproj]
  cl : Command line warning D9002: ignoring unknown option '-pedantic' [E:\GitHub\LightGBM\R-package\src\build\_lightgbm.vcxproj]
  cl : Command line warning D9002: ignoring unknown option '-g' [E:\GitHub\LightGBM\R-package\src\build\_lightgbm.vcxproj]
  cl : Command line warning D9002: ignoring unknown option '-O0' [E:\GitHub\LightGBM\R-package\src\build\_lightgbm.vcxproj]
  e:\github\lightgbm\r-package\src\src\metric\regression_metric.hpp(277): warning C4100: 'sum_weights': unreferenced formal parameter [E:\GitHub\LightGBM\R-package\src\build\_lightgbm.vcxproj]
```

## Reproducible examples

Compile package for R using VS 2017.

**Comment by guolinke** [comment]
I am not sure about these `cl` warning. I think these flags are generated by cmake.
I will fix the last warning.

**Comment by guolinke** [comment]
@StrikerRUS Do you have any ideas about these warnings?

**Comment by StrikerRUS** [comment]
@guolinke Nope. Unfortunately, as I said earlier, I'm not able to compile with VS on my local compute, but I'll google about these warnings.

**Comment by StrikerRUS** [comment]
If I'm not mistaken, these warnings appear only while compiling R-package (Appveyor logs are clear). Because we are not setting listed flags, I think that they are generated by default. Since they are ignored, I suppose we shouldn't worry.

**Comment by Laurae2** [comment]
I am getting no more warnings from 3dc5716.
