### ISSUE TITLE
lightgbm process stop suddenly after running for a while

### ISSUE THREAD

**Issue by bylake** [Microsoft/LightGBM#1216]
Please search your question on previous issues, [stackoverflow](https://stackoverflow.com/questions/tagged/lightgbm) or other search engines before you open a new one.

For bugs and unexpected issues, please provide following information, so that we could reproduce on our system.

## Environment info
Operating System: centos 7
CPU: 
C++/Python/R version: python3.6

## Error Message:
kernel: python[23544]: segfault at 2c5 ip 00007f25cf1a41d5 sp 00007f25b2cede10 error 6 in lib_lightgbm.so[7f25cf10e000+153000]

type=ANOM_ABEND msg=audit(1516784833.446:3293): auid=3002 uid=0 gid=0 ses=228 pid=23544 comm="python" reason="memory violation" sig=11

## Reproducible examples

 data size: 3000 samples,1700 variables

## Steps to reproduce

1.
2.
3

**Comment by guolinke** [comment]
@bylake 
can you provide a re-produce example ?

**Comment by bylake** [comment]
Hi, I failed to upload my data, so I have just written the email to you,and my data is in the email
