### ISSUE TITLE
LightGBM and  RFE can't reproduce the score as in another computer.

### ISSUE THREAD

**Issue by tianke0711** [Microsoft/LightGBM#1221]
I used the the feature selection method: RFE to select feature for features, and selected features for LightGBM trained. But I found that the score result can't be reproduced, although it is slightly difference. one is about 0.5516(win 7), another one is 0.5513(win 10). The reason I think that it is the selected features is different: I want to select 20 features(there are about 50 features or more) with LGBM model as following code: But I found that the features(sel.ranking_) are different when the os or os version, or computer is changed. I don't know what caused the changing. Thanks!

gbm = lgb.LGBMClassifier(
    boosting_type='gbdt',
    objective='binary',
    learning_rate=0.01,
    colsample_bytree=0.9,
    subsample=0.8,
    random_state=21,
    n_estimators=200,
    num_leaves=18)
sel = RFE(gbm, step=1, n_features_to_select=20, verbose=1)
sel.fit(X_train, y_train)
print (sel.ranking_)

**Comment by Laurae2** [comment]
Try to set number of threads to 1.

**Comment by guolinke** [comment]
you can figure the problem is cause by `REF` or not first.
For example, you can both use all features (without 'REF') in different computers, and see what happen.

If the reason is caused by 'REF', LightGBM cannot know that, since 'REF' is a high level controller. So we cannot fix it. And you should open issue in 'REF' project.

**Comment by tianke0711** [comment]
@Laurae2  thanks for your comment, I am trying!

**Comment by tianke0711** [comment]
hi @Laurae2  could you tell me why you suggest to set number of threads to 1, if you explain it, it is best. Thanks!

**Comment by guolinke** [comment]
@tianke0711 that is because, the same "subsample" with different "num_therads" will produce different result, since the bagging is optimized with multi-threading.

**Comment by tianke0711** [comment]
hi @guolinke  do you know some methods are good for feature selection for lgbmclassifier model?
