### ISSUE TITLE
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

### ISSUE THREAD

**Issue by lw3259111** [Microsoft/LightGBM#1224]
Please search your question on previous issues, [stackoverflow](https://stackoverflow.com/questions/tagged/lightgbm) or other search engines before you open a new one.

For bugs and unexpected issues, please provide following information, so that we could reproduce on our system.

## Environment info
Operating System:
CPU:
C++/Python/R version:

## Steps to reproduce

when I used lightgbm to train my data, i meet some warnning, as show in below:
`[LightGBM]` [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
`
the ouput is normal of the train and predict,but ,I wanted to know when the gain == -inf,. I use xgboost to train the data ,no found the problem. so, could you help me?

**Comment by guolinke** [comment]
refer to https://github.com/Microsoft/LightGBM/issues/640

**Comment by pillarsunshine** [comment]
i met the same problem,how can I fix it?
