### ISSUE TITLE
Comparing performance with and without Hessian?

### ISSUE THREAD

**Issue by Laurae2** [Microsoft/LightGBM#1228]
I want to add docs for Hessian-less optimization for R, using LightGBM, what vector value should I use for the hessian?

ping @guolinke

**Comment by guolinke** [comment]
the non-hessian solution require the post-fix of leave outputs. 
So it cannot use custom grad/hess to achieve it now.
You can use current code (non-hessian) and the old code(with hessian) to compare.

**Comment by guolinke** [comment]
@Laurae2 can we close this ?

**Comment by Laurae2** [comment]
@guolinke yes unless you think there is a way to get custom metrics to work with hessian-less optimization.

**Comment by guolinke** [comment]
I think it is not possible in current solution.
Also it is not needed due to it is rare case.

**Comment by guolinke** [comment]
The cost is very big to support postfix in python/R package.
I think it is also not needed due to it is not common.

For the comparison, you can just use different versions of LightGBM.
