### ISSUE TITLE
Python-package installation error 

### ISSUE THREAD

**Issue by dsl10brc** [Microsoft/LightGBM#123]
when I do: python setup.py install

I get this error:

```
Traceback (most recent call last):
  File "setup.py", line 17, in <module>
    LIB_PATH = libpath['find_lib_path']()
  File "lightgbm/libpath.py", line 28, in find_lib_path
    raise Exception('Cannot find lightgbm Library')
Exception: Cannot find lightgbm Library
```

It works fine on this wrapper: https://github.com/ArdalanM/pyLightGBM

But I have to always give exec_path="/Users/my_name/Downloads/openmpi-2.0.1/LightGBM/lightgbm" when I run it

**Comment by guolinke** [comment]
You are windows user? right?
Did you build lightgbm with ```DLL|x64``` before install python package?

**Comment by dsl10brc** [comment]
@guolinke  I am a mac user. I followed this procedure for build on mac : https://github.com/Microsoft/LightGBM/wiki/Installation-Guide

**Comment by guolinke** [comment]
did it show any errors when build library? you can paste your full commands and output logs here.

**Comment by dsl10brc** [comment]
@guolinke  I cloned from https://github.com/Microsoft/LightGBM/wiki/Installation-Guide to a new location and it worked. Thanks

**Comment by matiasfb80** [comment]
Hi guolinke
How can i build lightgbm with DLL|x64 before install python package in Win7? Thanks

**Comment by guolinke** [comment]
@matiasfb80  by Visual studio
