### ISSUE TITLE
R package with CUDA?

### ISSUE THREAD

**Issue by cdeterman** [Microsoft/LightGBM#1236]
This is a general question.  I see there is an R package for this and I also see in the installation [docs](https://github.com/Microsoft/LightGBM/blob/master/docs/Installation-Guide.rst) that it requires installation of an OpenCL SDK.  Is the installation for the R package limited to only using the OpenCL backend or is there a CUDA backend available?

**Comment by Laurae2** [comment]
There is no CUDA backend available currently.

**Comment by guolinke** [comment]
OpenCL is included in CUDA.

**Comment by cdeterman** [comment]
@guolinke I understand that, I was curious about the actual use of CUDA not OpenCL within the CUDA toolkit.  Thanks.

**Comment by cdeterman** [comment]
@guolinke I understand that, I was curious about the actual use of CUDA not OpenCL within the CUDA toolkit.  Thanks.

**Comment by guolinke** [comment]
ping @huanzhang12
