### ISSUE TITLE
Outdated line in Python docs?

### ISSUE THREAD

**Issue by g-leech** [Microsoft/LightGBM#1237]
Isn't [this line](https://github.com/Microsoft/LightGBM/blame/819df01278fc7f5ef5f135f6e9a09f8d419f21fb/docs/Python-Intro.rst#L96) no longer needed, given the direct categorical split feature?:

> Note: You should convert your categorical features to int type before you construct Dataset.

**Comment by guolinke** [comment]
it is still true for cli version.
