### ISSUE TITLE
[R] Accessing model estimate in parallel leads to a segfault

### ISSUE THREAD

**Issue by rbagd** [Microsoft/LightGBM#1238]
Since `lgb.interprete` in `R` only uses a single thread, I attempted to calculate feature importance for many observations in parallel by chunks. This resulted in `R` segfaulting with `memory not mapped` errors (see full log in the attachment). I investigated a little bit further and it seems that whenever model is accessed with one of the LightGBM functions, there's a memory conflict leading to a segfault, e.g.

```
library(doParallel)
cl <- makeCluster(2, outfile = "")
registerDoParallel(cl)
foreach(i = 1:2, .packages="lightgbm") %dopar% lgb.importance(bst)
```

Same problem results with `mclapply`. See attached file for a fully reproducible example.

[bug.txt](https://github.com/Microsoft/LightGBM/files/1707042/bug.txt)
[error_log.txt](https://github.com/Microsoft/LightGBM/files/1707043/error_log.txt)

```
> sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8
 [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8
 [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods
[8] base

other attached packages:
[1] doParallel_1.0.11 iterators_1.0.8   foreach_1.4.3     lightgbm_2.1.0
[5] R6_2.2.2

loaded via a namespace (and not attached):
[1] magrittr_1.5        codetools_0.2-15    data.table_1.10.4-3
```

**Comment by guolinke** [comment]
It can work in single thread ?

**Comment by guolinke** [comment]
I check the code of dump_model, and I think it is thread-safe.
So I think the problem is in R side. 
When you use doParallel, you may need to load model from file, since the pointer will be freed if you create a new process. 
ping @Laurae2 to confirm.

**Comment by rbagd** [comment]
The workaround with loading model from a file seems to help indeed.

`cl <- makeCluster(1)` still results in a segfault while replacing `%dopar%` by `%do%` (sequential execution) terminates normally. So it must be related to forking.

**Comment by Laurae2** [comment]
@rbagd pointers are not forkable (serialization fails). You must export the model first, then load the model from the separate (forked) R session.

Use `clusterEvalQ` to run an arbitrary script in R on the forked R sessions (also, beware of I/O locks).
