### ISSUE TITLE
Expose C_API_PREDICT_CONTRIB in R package

### ISSUE THREAD

**Issue by Zelazny7** [Microsoft/LightGBM#1242]
Returning predictor contributions have been added directly to the C++ code.  These predictions are available from Python (using `predict_contrib=True`) but it doesn't look like they are accessible from R.

Please add an option to `predict.lgb.Booster` to return predictor contributions as well. These are used extensively in https://github.com/slundberg/shap and would help interpret lightGBM models.

**Comment by Zelazny7** [comment]
I would be happy to give this a shot given some pointers are which pieces of code are affected. I'll attempt it either way and cross my fingers I only need to twiddle with the R package code.

**Comment by chivee** [comment]
@Zelazny7 , thanks so much, we could help to check the logic when PR is ready.

**Comment by Zelazny7** [comment]
I created a PR for this feature here:
https://github.com/Microsoft/LightGBM/pull/1259
