### ISSUE TITLE
v 0.1

### ISSUE THREAD

**Issue by Trottefox** [Microsoft/LightGBM#1247]
Hello,

I'm working on python with an old compiled windows version  of the program (v 0.1) and I have more interesting results on a trainset I'm working on than with the newest version with the same parameters (or I think so)
I tried a lot of thing to find the reason why, but not having the source of the v0.1 makes it really uneasy.

I tried the first version available v1 and result are consistent with the v2. So v1 doesn't look like the v0.1 I have. Could you by any chance make v 0.1 source available ? Or explain me the main changes between v0.1 and v1 ?

Thanks a lot !

**Comment by guolinke** [comment]
Hi @Trottefox , we had lots of changes after v0.1. 
I think it is very hard to get a full change list after 1 year.

following are some major changes that may affect the result: 
1. the bin finding algorithm 
2. the missing value handle
3. some default parameters
4. random number generator

**Comment by Trottefox** [comment]
Thanks for your reply, I'm sure there is a lot of changes, that's why I needed a source.

I use no missing value, and whatever random seed I take, results are consistent with both algorithms.
So my guess was more the third option for which I could maybe do something. But I didn't think the first one could be involved.

I also thought about the way categorical values are detected, but choosing them instead of the algorithm gives the same result.

**Comment by Laurae2** [comment]
@Trottefox fetch an old commit using git then install the package. You can get the history of this repository using `git log`.

This document (https://github.com/Microsoft/LightGBM/blob/master/docs/Key-Events.md) shows all the key events to this repository with the associated commit.

**Comment by Trottefox** [comment]
I didn't know I could do that on my own, thanks a lot !
The next thing to do is a revert on the chosen commit id, I suppose.
