### ISSUE TITLE
Class labels in predict result or model file

### ISSUE THREAD

**Issue by adavanisanti** [Microsoft/LightGBM#1248]
Hi,

Is there a way to get the correct class labels in the prediction result or model file? It looks like both model and result files have label indices and not labels themselves. Appreciate any pointer to get this info instead of reading the file again.

Thanks
Santi

**Comment by guolinke** [comment]
@adavanisanti 
what is your definition of `label` ?  the name of class? 

LightGBM is not just for the classification. And it is very common to provide the class probability in prediction, not the class name.
To get the final classification result on `label`, you should map it by yourself.

**Comment by adavanisanti** [comment]
@guolinke Yes, label = name of the class. I understand that LightGBM is not just for classification and probability is the output of prediction. However, it is not clear what the internal representation of the label in LightGBM is. Since I don't explicitly pass a map to train the model, can I assume that the internal mapping from the name of class to label has alphanumeric order? This will help me to map the label by myself for interpreting the probabilities for binary and multiclass classification.

For example: for the below binary classification problem, few rows of libsvm are as follows:
```
-1 3:1 11:1 14:1 19:1 39:1 42:1 55:1 64:1 67:1 73:1 75:1 76:1 80:1 83:1
-1 3:1 6:1 17:1 27:1 35:1 40:1 57:1 63:1 69:1 73:1 74:1 76:1 81:1 103:1
-1 4:1 6:1 15:1 21:1 35:1 40:1 57:1 63:1 67:1 73:1 74:1 77:1 80:1 83:1
-1 5:1 6:1 15:1 22:1 36:1 41:1 47:1 66:1 67:1 72:1 74:1 76:1 80:1 83:1
-1 2:1 6:1 16:1 22:1 36:1 40:1 54:1 63:1 67:1 73:1 75:1 76:1 80:1 83:1
-1 2:1 6:1 14:1 20:1 37:1 41:1 47:1 64:1 67:1 73:1 74:1 76:1 82:1 83:1
-1 1:1 6:1 14:1 22:1 36:1 42:1 49:1 64:1 67:1 72:1 74:1 77:1 80:1 83:1
-1 1:1 6:1 17:1 19:1 39:1 42:1 53:1 64:1 67:1 73:1 74:1 76:1 80:1 83:1
-1 2:1 6:1 18:1 20:1 37:1 42:1 48:1 64:1 71:1 73:1 74:1 76:1 81:1 83:1
+1 5:1 11:1 15:1 32:1 39:1 40:1 52:1 63:1 67:1 73:1 74:1 76:1 78:1 83:1
-1 5:1 16:1 30:1 35:1 41:1 64:1 67:1 73:1 74:1 76:1 80:1 83:1
-1 5:1 6:1 15:1 20:1 37:1 40:1 50:1 63:1 67:1 73:1 75:1 76:1 80:1 83:1
-1 5:1 7:1 16:1 29:1 39:1 40:1 48:1 63:1 67:1 73:1 74:1 76:1 78:1 83:1
```

Once I build the model and convert to a pmml file, I see that target labels are mapped to `0` and `1`. 

```
<DataField name="_target" optype="categorical" dataType="string">
<Value value="0"/>
<Value value="1"/>
</DataField>
```
For multiclass classification, I see multiple columns with probabilities in prediction. Is there a way to know which column is mapped to which label?

Thanks for your help!

**Comment by guolinke** [comment]
@adavanisanti 
LightGBM only accepts numbers for the class labels.
for binary class, >0 means positive, otherwise is negative.
for multi-class, it only  accepts number of >=0 .

**Comment by adavanisanti** [comment]
@guolinke Got it! Thanks for the clarification.
