### ISSUE TITLE
[docs] Wining solution links are broken.

### ISSUE THREAD

**Issue by fukatani** [Microsoft/LightGBM#1251]
https://github.com/Microsoft/LightGBM/blob/master/examples/README.md

e.g. I clicked Porto Seguro’s Safe Driver Prediction solution, and reached different competition solution,
Thanks,

**Comment by StrikerRUS** [comment]
ping @ChenZhiyong 
Practically all links are wrong. Could you please fix it?

**Comment by guolinke** [comment]
fixed
