### ISSUE TITLE
feature_fraction warning needed if only one feature

### ISSUE THREAD

**Issue by zkurtz** [Microsoft/LightGBM#1253]
I don't think this qualifies as a bug, but it would be handy to have a warning in place in case a user tries to do training on a single feature and sets feature_fraction < 1. This tripped me up for a little while -- I could not figure out why the predicted values were zero everywhere:

```
import lightgbm as lgb
import numpy as np

n = 1000
x = np.reshape(np.random.normal(loc=0.0, scale=1.0, size=n), (-1,1))
y = x[:,0] + np.random.normal(loc=0.0, scale=1.0, size=n)

params = {
    'task': 'train',
    'boosting_type': 'gbdt',
    'objective': 'regression',
    'metric': {'l2'},
    'feature_fraction': 0.99,
}

data = lgb.Dataset(x, y)
bst = lgb.train(params = params,
                train_set = data,
                num_boost_round = 10,
                verbose_eval = False)

z = bst.predict(x)
z.max() - z.min()
```

**Comment by guolinke** [comment]
@zkurtz what version you are using?
I think have set the num_used_feature to 1 if it is smaller than 1.

https://github.com/Microsoft/LightGBM/blob/master/src/treelearner/serial_tree_learner.cpp#L248

**Comment by zkurtz** [comment]
I'm on 2.0.10 -- looks like it's time for me to update, thanks!
