### ISSUE TITLE
LightGBM Earth Mover's Distance

### ISSUE THREAD

**Issue by vruvora** [microsoft/LightGBM#1256]
Thanks for designing such an awesome library. I was curious if you have plans to incorporate Earth Mover's Distance into LightGBM so we can optimize over distributions.

**Comment by olofer** [comment]
Could you specify more precisely what you have in mind? Even computing the EMD requires solving a linear program if I'm not mistaken.

**Comment by chivee** [comment]
@vruvora , what's situation/scenario do you want to use Wasserstein/EMD?  considering it's normally seen in deep learning scenario.

![image](https://user-images.githubusercontent.com/2283057/37286249-5ccb9bcc-263c-11e8-8963-0eb5307e9de0.png)


![image](https://user-images.githubusercontent.com/2283057/37286224-4dfb966a-263c-11e8-9e3e-4d7829deb87a.png)

**Comment by vruvora** [comment]
I want to train the LightGBM to output a distribution.

**Comment by StrikerRUS** [comment]
Closed in favor of being in #2302. We decided to keep all feature requests in one place.

Welcome to contribute this feature! Please re-open this issue (or post a comment if you are not a topic starter) if you are actively working on implementing this feature.
