### ISSUE TITLE
There are lots of errors when I compile LightGBM on Windows by using cmake

### ISSUE THREAD

**Issue by Raise-me-up** [Microsoft/LightGBM#1261]
## Environment info
Operating System:  Windows 10
CPU:  i5-7300HQ 
CMake version: 3.11.0-rc3

## Error Message: 
F:\Microsoft visual studio 2015\installation\VC\include\utility(180): error C2065: “__this”: 未声明的标识符 [E:\Anaconda\Light
GBM\LightGBM\build\_lightgbm.vcxproj]
  F:\Microsoft visual studio 2015\installation\VC\include\utility(205): note: 参见对正在编译的函数 模板 实例化“void std::swap<int,doub
  le>(std::pair<int,double> &,std::pair<int,double> &) noexcept(<expr>)”的引用
F:\Microsoft visual studio 2015\installation\VC\include\utility(180): error C2227: “->first”的左边必须指向类/结构/联合/泛型类型 [E:\Ana
conda\LightGBM\LightGBM\build\_lightgbm.vcxproj]
  F:\Microsoft visual studio 2015\installation\VC\include\utility(180): note: 类型是“unknown-type”
F:\Microsoft visual studio 2015\installation\VC\include\utility(180): error C2056: 非法表达式 [E:\Anaconda\LightGBM\LightGBM
\build\_lightgbm.vcxproj]
F:\Microsoft visual studio 2015\installation\VC\include\utility(180): error C2227: “->second”的左边必须指向类/结构/联合/泛型类型 [E:\An
aconda\LightGBM\LightGBM\build\_lightgbm.vcxproj]
  F:\Microsoft visual studio 2015\installation\VC\include\utility(180): note: 类型是“unknown-type”
  application.cpp
F:\Microsoft visual studio 2015\installation\VC\include\utility(180): error C2065: “__this”: 未声明的标识符 [E:\Anaconda\Light
GBM\LightGBM\build\_lightgbm.vcxproj]
  F:\Microsoft visual studio 2015\installation\VC\include\utility(205): note: 参见对正在编译的函数 模板 实例化“void std::swap<int,doub
  le>(std::pair<int,double> &,std::pair<int,double> &) noexcept(<expr>)”的引用
F:\Microsoft visual studio 2015\installation\VC\include\utility(180): error C2227: “->first”的左边必须指向类/结构/联合/泛型类型 [E:\Ana
conda\LightGBM\LightGBM\build\_lightgbm.vcxproj]
  F:\Microsoft visual studio 2015\installation\VC\include\utility(180): note: 类型是“unknown-type”
F:\Microsoft visual studio 2015\installation\VC\include\utility(180): error C2056: 非法表达式 [E:\Anaconda\LightGBM\LightGBM
\build\_lightgbm.vcxproj]
F:\Microsoft visual studio 2015\installation\VC\include\utility(180): error C2227: “->second”的左边必须指向类/结构/联合/泛型类型 [E:\An
aconda\LightGBM\LightGBM\build\_lightgbm.vcxproj]
  F:\Microsoft visual studio 2015\installation\VC\include\utility(180): note: 类型是“unknown-type”
已完成生成项目“E:\Anaconda\LightGBM\LightGBM\build\_lightgbm.vcxproj”(默认目标)的操作 - 失败。

项目“E:\Anaconda\LightGBM\LightGBM\build\ALL_BUILD.vcxproj”(1)正在节点 1 上生成“E:\Anaconda\LightGBM\LightGBM\build\lightgbm.vcx
proj”(4) (默认目标)。
InitializeBuildStatus:
  正在对“lightgbm.dir\Release\lightgbm.tlog\unsuccessfulbuild”执行 Touch 任务。
CustomBuild:
  所有输出均为最新。
ClCompile:
  F:\Microsoft visual studio 2015\installation\VC\bin\x86_amd64\CL.exe /c /IE:\Anaconda\LightGBM\LightGBM\include /nolo
  go /W4 /WX- /O2 /Ob2 /Oi /Ot /Oy /GL /D WIN32 /D _WINDOWS /D NDEBUG /D USE_SOCKET /D "CMAKE_INTDIR=\"Release\"" /D _M
  BCS /Gm- /EHsc /MD /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /openmp /Fo"lightgbm.dir\Release\\" /Fd"li
  ghtgbm.dir\Release\vc140.pdb" /Gd /TP /errorReport:queue E:\Anaconda\LightGBM\LightGBM\src\application\application.cp
  p
  application.cpp
F:\Microsoft visual studio 2015\installation\VC\include\utility(180): error C2065: “__this”: 未声明的标识符 [E:\Anaconda\Light
GBM\LightGBM\build\lightgbm.vcxproj]
  F:\Microsoft visual studio 2015\installation\VC\include\utility(205): note: 参见对正在编译的函数 模板 实例化“void std::swap<int,doub
  le>(std::pair<int,double> &,std::pair<int,double> &) noexcept(<expr>)”的引用
F:\Microsoft visual studio 2015\installation\VC\include\utility(180): error C2227: “->first”的左边必须指向类/结构/联合/泛型类型 [E:\Ana
conda\LightGBM\LightGBM\build\lightgbm.vcxproj]
  F:\Microsoft visual studio 2015\installation\VC\include\utility(180): note: 类型是“unknown-type”
F:\Microsoft visual studio 2015\installation\VC\include\utility(180): error C2056: 非法表达式 [E:\Anaconda\LightGBM\LightGBM
\build\lightgbm.vcxproj]
F:\Microsoft visual studio 2015\installation\VC\include\utility(180): error C2227: “->second”的左边必须指向类/结构/联合/泛型类型 [E:\An
aconda\LightGBM\LightGBM\build\lightgbm.vcxproj]
  F:\Microsoft visual studio 2015\installation\VC\include\utility(180): note: 类型是“unknown-type”
已完成生成项目“E:\Anaconda\LightGBM\LightGBM\build\lightgbm.vcxproj”(默认目标)的操作 - 失败。

已完成生成项目“E:\Anaconda\LightGBM\LightGBM\build\ALL_BUILD.vcxproj”(默认目标)的操作 - 失败。

生成失败。

“E:\Anaconda\LightGBM\LightGBM\build\ALL_BUILD.vcxproj”(默认目标) (1) ->
“E:\Anaconda\LightGBM\LightGBM\build\_lightgbm.vcxproj”(默认目标) (3) ->
(ClCompile 目标) ->
  F:\Microsoft visual studio 2015\installation\VC\include\utility(180): error C2065: “__this”: 未声明的标识符 [E:\Anaconda\Lig
htGBM\LightGBM\build\_lightgbm.vcxproj]
  F:\Microsoft visual studio 2015\installation\VC\include\utility(180): error C2227: “->first”的左边必须指向类/结构/联合/泛型类型 [E:\A
naconda\LightGBM\LightGBM\build\_lightgbm.vcxproj]
  F:\Microsoft visual studio 2015\installation\VC\include\utility(180): error C2056: 非法表达式 [E:\Anaconda\LightGBM\LightG
BM\build\_lightgbm.vcxproj]
  F:\Microsoft visual studio 2015\installation\VC\include\utility(180): error C2227: “->second”的左边必须指向类/结构/联合/泛型类型 [E:\
Anaconda\LightGBM\LightGBM\build\_lightgbm.vcxproj]
  F:\Microsoft visual studio 2015\installation\VC\include\utility(180): error C2065: “__this”: 未声明的标识符 [E:\Anaconda\Lig
htGBM\LightGBM\build\_lightgbm.vcxproj]
  F:\Microsoft visual studio 2015\installation\VC\include\utility(180): error C2227: “->first”的左边必须指向类/结构/联合/泛型类型 [E:\A
naconda\LightGBM\LightGBM\build\_lightgbm.vcxproj]
  F:\Microsoft visual studio 2015\installation\VC\include\utility(180): error C2056: 非法表达式 [E:\Anaconda\LightGBM\LightG
BM\build\_lightgbm.vcxproj]
  F:\Microsoft visual studio 2015\installation\VC\include\utility(180): error C2227: “->second”的左边必须指向类/结构/联合/泛型类型 [E:\
Anaconda\LightGBM\LightGBM\build\_lightgbm.vcxproj]

“E:\Anaconda\LightGBM\LightGBM\build\ALL_BUILD.vcxproj”(默认目标) (1) ->
“E:\Anaconda\LightGBM\LightGBM\build\lightgbm.vcxproj”(默认目标) (4) ->
  F:\Microsoft visual studio 2015\installation\VC\include\utility(180): error C2065: “__this”: 未声明的标识符 [E:\Anaconda\Lig
htGBM\LightGBM\build\lightgbm.vcxproj]
  F:\Microsoft visual studio 2015\installation\VC\include\utility(180): error C2227: “->first”的左边必须指向类/结构/联合/泛型类型 [E:\A
naconda\LightGBM\LightGBM\build\lightgbm.vcxproj]
  F:\Microsoft visual studio 2015\installation\VC\include\utility(180): error C2056: 非法表达式 [E:\Anaconda\LightGBM\LightG
BM\build\lightgbm.vcxproj]
  F:\Microsoft visual studio 2015\installation\VC\include\utility(180): error C2227: “->second”的左边必须指向类/结构/联合/泛型类型 [E:\
Anaconda\LightGBM\LightGBM\build\lightgbm.vcxproj]

    0 个警告
    12 个错误

## Run the following commands to reproduce:

git clone --recursive https://github.com/Microsoft/LightGBM
cd LightGBM
mkdir build
cd build
cmake -DCMAKE_GENERATOR_PLATFORM=x64 ..
cmake --build . --target ALL_BUILD --config Release

**Comment by guolinke** [comment]
Did you choose cpp components  when installing visual studio?

**Comment by Raise-me-up** [comment]
Of course!

**Comment by guolinke** [comment]
from your log, it seems you didn’t install visual studio correctly. you can try to repair it and reinstall c++ components. If problem still exists, you can try to install MSBuild 2017 with c++, English version.
