### ISSUE TITLE
is there a demo that shows how to train data from hdfs？

### ISSUE THREAD

**Issue by janelu9** [Microsoft/LightGBM#1266]
I am wondering if the algorithm is paralleled of hdfs version or just read data  parallelized on hadoop?

**Comment by chivee** [comment]
Not yet, Let's using feature parallel for example,  you can build with USE_HDFS  enabled and set datasource to the hdfs files. it should works file

**Comment by guolinke** [comment]
hdfs is just a IO interface, and independent with parallel learning. If you want to train parallel, you can refer to https://github.com/Microsoft/LightGBM/blob/master/docs/Parallel-Learning-Guide.rst

**Comment by janelu9** [comment]
@guolinke could you give me a demo

**Comment by guolinke** [comment]
@janelu9 refer to this: https://github.com/Microsoft/LightGBM/tree/master/examples/parallel_learning, 
but replace the data file with the hdfs path.

**Comment by janelu9** [comment]
@guolinke thank you ！

**Comment by CanYouGiveMeAName** [comment]
But I have a large amount of data. And they are all in hdfs。
