### ISSUE TITLE
Exclusive Feature Bundling (EFB) Python

### ISSUE THREAD

**Issue by Nzteb** [Microsoft/LightGBM#1267]
Hi,

the paper in table 2 you compare the implementations  lgb_baseline, EFB_only, LightGBM. It says lgb_baseline is without EFB and without GOSS.

How is it possible to reproduce these implementations with the Python package?

E. g.  I see switching boosting type from GOSS to GBDT but I cannot find any information about EFB in the documentation. Is this implemented in all of the different boosting types?

Thanks

C++/Python/R version: Python

**Comment by guolinke** [comment]
EFB is enable by default. you can disable it by set `enable_bundle=false` when construct dataset.

**Comment by Nzteb** [comment]
Perfect, thanks!

**Comment by guolinke** [comment]
you should add it to the parameter dict and then pass to Dataset

**Comment by gaohang** [comment]
the same question with Nzteb. I cannot find enable_bundle param and  enable_bundle is not in the parameter dict.

**Comment by guolinke** [comment]
@gaohang set it to the `params` dict, not the python function arguments.

**Comment by StrikerRUS** [comment]
@gaohang like in the following code:
```
data = lgbm.Dataset(train, train_label, params={'enable_bundle': False})
```

@guolinke It seems that we have no information about `enable_bundle` in Parameters.rst.
