### ISSUE TITLE
may you explain what is data format for lambdarank

### ISSUE THREAD

**Issue by Sandy4321** [Microsoft/LightGBM#1268]
In order to use this project example is it important to share how data from recommended systems/ranking  
can be transformed to data files examples in this folder
https://github.com/Microsoft/LightGBM/tree/master/examples/lambdarank

so how data in this folder connected to real data from real live ranking task
Thanks

**Comment by guolinke** [comment]
refer to https://github.com/Microsoft/LightGBM/blob/master/docs/Parameters.rst#query-data 

This data is sampled from Yahoo Learning to rank dataset: https://webscope.sandbox.yahoo.com/catalog.php?datatype=c
