### ISSUE TITLE
how to use lightgbm of hdfs version?

### ISSUE THREAD

**Issue by janelu9** [Microsoft/LightGBM#1269]

**Comment by chivee** [comment]
Build from source with HDFS enabled, detailed could be found at :

https://github.com/Microsoft/LightGBM/pull/1243

**Comment by janelu9** [comment]
@chivee  well I know how to build it but wonder how to use it from python api

**Comment by janelu9** [comment]
@chivee  need I train it like https://github.com/Microsoft/LightGBM/issues/396?

**Comment by guolinke** [comment]
@janelu9 it supports the hdfs file. I don't think it can support spark rdd. 
For the spark version, please refer to https://github.com/Azure/mmlspark, which support LightGBM
