### ISSUE TITLE
documentation error for LGBMRanker group format

### ISSUE THREAD

**Issue by asos-gordon** [Microsoft/LightGBM#1271]
When executing

LGBMRanker().fit(X, y, group=groups)

I get the following error message

LightGBMError: b'sum of query counts is not same with #data'

The cause was the form of groups. The documentation states that the shape of groups should be n_samples but this is false. Instead, groups.sum() should equal n_samples, where groups is an array of successive group sizes and not, as I inferred from the shape, group labels.

**Comment by guolinke** [comment]
Thanks for point out, you can create a PR to directly fix it.
Thank you.

**Comment by guolinke** [comment]
@asos-gordon I didn't find about ` states that the shape of groups should be n_samples ` . can you point it out ?

**Comment by asos-gordon** [comment]
Sure, here are screenshots from the readthedocs page and the internal documentation

<img width="1440" alt="lightgbmdocumentation_screenshot" src="https://user-images.githubusercontent.com/32770683/37587184-7fcd6906-2b56-11e8-82ce-83ec1bf09de6.png">
<img width="846" alt="lightgbmdocumentation_screenshot2" src="https://user-images.githubusercontent.com/32770683/37587186-7feed5be-2b56-11e8-85b1-534f36b5b935.png">

**Comment by guolinke** [comment]
fixed in the latest commit .

**Comment by rem2016** [comment]
I think the current doc is very confusing. I have to try several times to figure out what it means.

![image](https://user-images.githubusercontent.com/18425020/47254905-a69a9200-d49a-11e8-8456-c587a03344d1.png)

**Comment by StrikerRUS** [comment]
@rem2016 Feel free to create a PR with documents improvements!
