### ISSUE TITLE
[R-package] add support for gamma/tweedie objective functions

### ISSUE THREAD

**Issue by miclegr** [Microsoft/LightGBM#1272]
Would be possible to support in the R pakage gamma and tweedie objective functions as it is in the python package?

Currently possible objective function are hardcoded in utils.R lgb.check.obj function:
```
lgb.check.obj <- function(params, obj) {

  OBJECTIVES <- c("regression", "regression_l1", "regression_l2", "huber", "fair", "poisson", "binary", 
"lambdarank", "multiclass")
  
...
```

Unfortunately adding gamma and tweedie there doesn't do the trick.

**Comment by guolinke** [comment]
fix in the latest commit.

**Comment by miclegr** [comment]
Fix is not working unfortunately, as I was mentioning adding gamma in the OBJECTIVES vector in lgb.check.obj function doesn't do the trick.

Reploducile Example:
-----------------------

```r
library(lightgbm)

#Generate data
set.seed(123)
N <- 10000
X1 <- rnorm(N, 0, 3)
X2 <- rnorm(N, 50, 15)
Y <- rgamma(N,10)
data <- data.frame(X1, X2, Y)

#Split test/train
train_ind <- sample(seq_len(nrow(data)), size = 7000)
train.x <- as.matrix(data[train_ind, c("X1", "X2") ])
train.y <- as.matrix(data[train_ind, "Y" ])
test.x <- as.matrix(data[-train_ind, c("X1", "X2") ])
test.y <- as.matrix(data[-train_ind, "Y" ])

#Fit data
dtrain <- lgb.Dataset(train.x, label = train.y)
model <- lgb.train(data = dtrain,
                   objective = "gamma",
                   alpha = 0.1,
                   rounds = 1000,
                   min_data = 1,
                   learning_rate = .1,
                   metric='gamma')
```

Error
-----
[LightGBM] [Fatal] No object function provided

**Comment by guolinke** [comment]
Are you on the latest master code ? 
Can you try to clean the old package and reinstall ?

**Comment by AraneoA** [comment]
I was referred to this issue from #1281. This fixed quantile as well. I can also confirm that gamma is working as well.
