### ISSUE TITLE
lightgbm uses only one core for training

### ISSUE THREAD

**Issue by mutexliu** [Microsoft/LightGBM#1277]
I'm using lightgbm for recently [kaggle competition](https://www.kaggle.com/c/talkingdata-adtracking-fraud-detection), where the training data has 180,000,000 rows and about 15 features.

The computer (centos) has 24 cores, but only uses one core for training.
Training parameter `nthreads` is set to 8.

Is it common for lightgbm when training with small features?
Any suggestions for using more cores?

**Comment by guolinke** [comment]
can you provide a example code? I think it should be run multi-threading

**Comment by mutexliu** [comment]
After rechecking the cpu usage, I found the cpu usage changes drastically, from 100% to 800%, which mean the program is run multi-threading.

So, apology for my correct information. I will close this issue.
