### ISSUE TITLE
Can anyone tell me how lightgbm cal split gain?

### ISSUE THREAD

**Issue by qianrenliang** [Microsoft/LightGBM#1283]
in xgboost paper:
one node impurity score: sum_grad / (sum_hess + gamma)

but i dont see it in lightgbm paper,  in the issue#1230 , author say split gain is calculated by sum_grad / sum_hess, but i want know where is gamma ,alias min_split_gain

**Comment by guolinke** [comment]
gamma is the parameter  `lambda_l2`. 
refer to: https://github.com/Microsoft/LightGBM/blob/master/src/treelearner/feature_histogram.hpp#L291-L297
