### ISSUE TITLE
Typo in Python API document page 

### ISSUE THREAD

**Issue by borntoburnyo** [Microsoft/LightGBM#1288]
## Environment info
Operating System: NA
CPU: NA
C++/Python/R version: NA

## Error Message:
There is typo in page: 
http://lightgbm.readthedocs.io/en/latest/Python-API.html#training-api
Under `lightgbm.cv` return value:

eval_hist – Evaluation history. The dictionary has the following format: {‘metric1-mean’: [values], ‘metric1-stdv’: [values], ‘metric2-mean’: [values], ‘**metric1-stdv**’: [values], …}.

should be: 
eval_hist – Evaluation history. The dictionary has the following format: {‘metric1-mean’: [values], ‘metric1-stdv’: [values], ‘metric2-mean’: [values], ‘**metric2-stdv**’: [values], …}.

## Steps to reproduce

1.
2.
3.

**Comment by chivee** [comment]
thank you

**Comment by borntoburnyo** [comment]
Thank you for the great work.
