### ISSUE TITLE
Is it possible to pass additional arguments to a custom objective function?

### ISSUE THREAD

**Issue by peeyman** [Microsoft/LightGBM#1292]
I want to write a custom objective function which can accept prediction of the other models as arguments. To be more precise, I want something like the following as header:

`def customObjective(preds, lgb_train , otherArgs):`

Or, is it possible to pass those predictions in lgb_train and extract them inside?

Thank you in advance.

**Comment by peeyman** [comment]
@Laurae2  Thank you very much for the answer.

**Comment by RoyalTS** [comment]
@Laurae2 What exactly would that look like?
