### ISSUE TITLE
Just questions

### ISSUE THREAD

**Issue by IbanezJS** [Microsoft/LightGBM#1293]
Hi !

1)Is there 'feature importance' in LightGbm like in XGBoost?
2)What is the fastest way to get prediction for single row on already trained model. If say i have a stream of newcoming data rows and i want to get prediction for each row as fast as possible

**Comment by guolinke** [comment]
@IbanezJS cpp predict function is in https://github.com/Microsoft/LightGBM/blob/master/src/application/predictor.hpp 
However, it isn't design for steam data. 
If you want speed up the single row prediction by multi-threading, you can change this function:
https://github.com/Microsoft/LightGBM/blob/master/src/boosting/gbdt_prediction.cpp#L9-L27

**Comment by IbanezJS** [comment]
@guolinke Hi
which part you suggest to go parallel?
`for (int k = 0; k < num_tree_per_iteration_; ++k)`
this cycle? Are the `models_` all independent?

Actually I don't get math here. Why `num_iteration_for_pred_` and `early_stop` need for prediction on already trained model?
How `early_stop` may decide to stop prediction iterations? 
Please give some educational references for this questions.

**Comment by guolinke** [comment]
you can use openmp. 
The models_ are independent. 
sorry, not everything has reference. 

The pr of early_stopping in prediction : https://github.com/Microsoft/LightGBM/pull/550

you can specific `num_iteration_for_pred_` to use part of trees for prediction, default is using all trees.

BTW, if you are not using multi-class, and didn't use early stopping in prediction, the changes is quite easy:
```cpp
  double sum = 0.0f;
  #pragma omp parallel for schedule(static) reduction(+:sum)
  for (int i = 0; i < num_iteration_for_pred_; ++i) {
    sum += models_[i]->Predict(features);
  }
  output[0] = sum;
```

**Comment by IbanezJS** [comment]
@guolinke thanks for the hint!

does `#pragma omp parallel` really beneficial?
I mean how heavy model->Predict() could be and what is average of num_iteration_for_pred_?
If compare to threads synchronization and context switch time.

Are there any further simplifications if using only binary classification output?

**Comment by guolinke** [comment]
@IbanezJS it depends on the complexity of your model, e.g. num_leaves, num_trees. You can just test it by run it.
I think it cannot be further simplified.
