### ISSUE TITLE
Class weight for multiclass

### ISSUE THREAD

**Issue by econkc** [Microsoft/LightGBM#1300]
Hi,

I have a quick question regarding the is_unbalance option whether or not it is supported for multiclass classification. I have gone through some of the threads and it seems like there are attempts to update this but the document still states that this option is only for binary classification. It appears that the sklearn version supports class_weight='balanced'. What about the python (non-sklearn) version?

Thanks,

**Comment by guolinke** [comment]
@StrikerRUS it seems the document is out-of-date.
The PR is https://github.com/Microsoft/LightGBM/pull/1114
And it only support the sklearn version.
