### ISSUE TITLE
[R-package] num_iteration=NULL behaviour for prediction

### ISSUE THREAD

**Issue by alberthkcheng** [Microsoft/LightGBM#1301]
In **documentation** : 
num_iteration - number of iteration want to predict with, NULL or <= 0 means use best iteration

In **code**:
```
# Check if number of iterations is existing - if not, then set it to -1 (use all)
if (is.null(num_iteration)) {
        num_iteration <- -1
      }
```

So, is the actual behaviour  *use all* or *best iteration*?
Thanks.

(similar question applied to methods like *lgb.model.dt.tree*)

**Comment by guolinke** [comment]
@alberthkcheng if you used early_stopping (and without re-load model from file), it will use the best_iteration, otherwise it uses all models.

**Comment by alberthkcheng** [comment]
Thanks.. so this logic is handled in the C++ code?
