### ISSUE TITLE
Segfault on repeated fits of large datasets

### ISSUE THREAD

**Issue by AFanthomme** [Microsoft/LightGBM#1303]
Hi !

While trying to adapt Boruta to work with LGBM on a fairly large dataset (18000 features, each of them being 0, 1 or 2, and 26500 examples) I ran into the following crash (simplified for clarity) :

## Steps to reproduce
`for i in range(100):
    Generate large dataset X, y
    clf = LGBMClasssifier()
    clf.fit(X, y)
`

When executing this, the first iterations always work, but most of the times the program crashes after ~10 iterations. Some additional details :

- it sometimes runs for much longer than others (it once managed to go to 100 iterations, but the size of the dataset was reduced each time). Restarting the computer seemed to grant an extra 5 iterations at least.

- adding garbage collection / removing all useless copies of the data in the rest of the code has been done, it did improve slightly but did not make it disappear.

- same for switching to the native Dataset / lgbm.train API

- the problem should be memory related : although not 100% of the memory is used by python, the crash seems to happen when all memory is either used or cached by python

- the crash always happens just before the first iteration of boosting, likely when the data is being copied for the fit.

## Environment info 
Operating System: Ubuntu 16.04 LTS
CPU: AMD Ryzen 7 1700 Eight-Core Processor × 16
C++/Python/R version: Python 3.6

## Error Message:
Segmentation Fault (core dumped)

**Comment by guolinke** [comment]
hi @AFanthomme , can you provide the type of X and y, e.g. 2d matrix or CSR matrix ? what is the data type? float32 or float64 ?

**Comment by AFanthomme** [comment]
You're right, this is relevant info 

X is a 2D dense matrix of int8 (to avoid extra memory), and once loaded in a dataset it is encoded in 3 bins as expected

**Comment by guolinke** [comment]
@AFanthomme refer to the code here: https://github.com/Microsoft/LightGBM/blob/master/python-package/lightgbm/basic.py#L757-L761
even when your data type is int8, it will be converted to float32. As a result, there may have some memory problem in the above code.

**Comment by AFanthomme** [comment]
@guolinke Thanks a lot, this is probably where the problem lies (the data barely fits into memory when on float32, since I also keep some intermediate results this could explain why the error happens only after some time). Is there a workaround to keep memory usage lower at this step?

Also it seemed the error happened during the fit and not the Dataset construction when I separated the two, but I will have to check

**Comment by guolinke** [comment]
@AFanthomme The data construction is by lazy fashion unless you call `dataset.construct()` explicitly. 

you can save your data to csv flie, then construct dataset it from csv file with parameter `two_round=True`.

**Comment by guolinke** [comment]
how do you pass `two_round=True`? can you provide a code?

**Comment by AFanthomme** [comment]
The relevant portion of the code is here :
           X, X_val, y, y_val = train_test_split(X, y, test_size=0.25, random_state=np.random.randint(2**12))

            # Dump dataset as csv to reload it as dataset without float32 conversion
            y = y.astype(np.int8)
            y_val = y_val.astype(np.int8)
            X = np.hstack((np.reshape(y, (-1,1)), X))
            print(X.shape, X.dtype)
            df = pd.DataFrame(X)
            del X
            print('Start dumping temporary csv train')
            toc = time.time()
            df.to_csv("./files/X_train_ordinal_boruta_tmp.csv", header=False, index=False)
            print('Done dumping temporary csv train in {}s'.format(time.time()-toc))
            del df

            X_val = np.hstack((np.reshape(y_val, (-1,1)), X_val))
            df = pd.DataFrame(X_val)
            del X_val
            print('Start dumping temporary csv val')
            toc = time.time()
            df.to_csv("./files/X_val_ordinal_boruta_tmp.csv", header=False, index=False)
            del df
            print('Done dumping temporary csv val in {}s'.format(time.time()-toc))

            data_train = lgb.Dataset("./files/X_train_ordinal_boruta_tmp.csv")
            data_val = lgb.Dataset("./files/X_val_ordinal_boruta_tmp.csv", reference=data_train)

            print('Start fitting estimator')
            params = {'learning_rate':0.02, 'num_boost_round':2000, 'objective':'binary', 'metric': 'auc', 'two_round':True}
            bst = lgb.train(params, data_train, valid_sets=[data_val])`

**Comment by guolinke** [comment]
can you try:
```
        params = {'learning_rate':0.02, 'num_boost_round':2000, 'objective':'binary', 'metric': 'auc', 'two_round':True}
        data_train = lgb.Dataset("./files/X_train_ordinal_boruta_tmp.csv", params=params)
        data_val = lgb.Dataset("./files/X_val_ordinal_boruta_tmp.csv", reference=data_train)
        data_train.construct()
        data_val.construct() 
        print('Start fitting estimator')
        bst = lgb.train(params, data_train, valid_sets=[data_val])
```

**Comment by AFanthomme** [comment]
@guolinke No change unfortunately...

**Comment by guolinke** [comment]
@AFanthomme what is your memory capacity ?

**Comment by AFanthomme** [comment]
16Gb
It seems like it could store this dataset, especially since the first fits work

**Comment by guolinke** [comment]
how about add force gc in the loop ?

**Comment by rgranvil** [comment]
@AFanthomme I may have had a similar issue before where my first call to lgb.train ran fine and then I ran out of memory on the 2nd fit.  Adding 2 explicit calls to gc before each lgb.train solved the problem for me.  When I monitored the memory usage at each step, it looked like some memory would not get freed until the 2nd call to gc.  You could give that a try.

**Comment by AFanthomme** [comment]
I tried with two gc, still does not solve the problem 
I also switched back to constructing from numpy arrays, csv is long to write and did not help
It seems that the available memory (monitored by "free -m") is 6,5Gb after constructing datasets and gc, it then drops to 3.1 during beginning of training and that is at that point that it segfaults (did not catch the precise value at time of segfault, but the memory consumption seems perfectly cyclic and never got below 3 on the 5 first fits before it broke)

**Comment by guolinke** [comment]
@AFanthomme can you try `histogram_pool_size=1024` or `is_sparse=false` or both of them ?

**Comment by AFanthomme** [comment]
That did make a change : using

            params = {'learning_rate':0.02, 'objective':'binary', 'metric': 'auc', 'two_round':True,
                        'histogram_pool_size':1024, 'is_sparse':False}
            data_train = lgb.Dataset(X, label=y, params=params)
            data_val = lgb.Dataset(X_val, label=y_val, reference=data_train)
            print('Begin constructing datasets')
            data_train.construct()
            data_val.construct()
            del X, X_val, y, y_val
            print('Start fitting estimator')
            gc.collect()
            print('First gc done')
            gc.collect()
            print('Second gc done')
            bst = lgb.train(params, data_train, valid_sets=[data_val], num_boost_round=4)

The segfault happens during the construct calls (the memory usage is still cyclic, now it drops at 2.7 (but immediately backs up to 5 at beginning of fit)

**Comment by guolinke** [comment]
how about set `is_sparse=true` ?

**Comment by AFanthomme** [comment]
Also dies at construct...

**Comment by AFanthomme** [comment]
Do you think that could help even if the dataset is really not sparse at all?

**Comment by guolinke** [comment]
from your log, it seems your dataset is sparse, as a reslut, using the dense format is memory costly.

**Comment by AFanthomme** [comment]
With csr matrix, if i use int8 matrices lightgbm yields :

TypeError: Expected np.float32 or np.float64, met type(int8) 

If I switch back to float32 (during csr_matrix construction) the memory consumption is increased and segfault at dataset construction as before

**Comment by guolinke** [comment]
@AFanthomme can you send your data(int8 type) to pickle, and send it to me ? 
I think it is more efficient for me to debug on it directly.

**Comment by guolinke** [comment]
after some offline syncs, it seems this problem is casued by AMD Ryzen CPU. close for now.
