### ISSUE TITLE
[Python] Confused about the difference between 'save_binary' in the Dataset class and 'save_binary' parameter for training?

### ISSUE THREAD

**Issue by bbennett36** [Microsoft/LightGBM#1304]
As said in the title, I'm a bit confused on the 'best' way to store my dataset as a binary file.  
  
I'm currently calling it like this from a pandas dataframe-
```
lgb_train = lgb.Dataset(X_train, label=y_train, free_raw_data=False)
lgb_train.save_binary("./data/lgb_train.bin") 

lgb_test = lgb.Dataset(X_test, label=y_test, free_raw_data=False)
lgb_test.save_binary("./data/lgb_test.bin") 

lgb_model = lgb.train(params, lgb_train, early_stopping_rounds, valid_sets=[lgb_test], evals_result=evals_result, early_stopping_rounds=200, verbose_eval=100)
```

The params in the example above DOES NOT use the `save_binary `parameter . (Not sure if the model even uses the binary dataset versions that I output)
  
Using it this way forces me to use` free_raw_data=false` which [according to the quickstart](https://lightgbm.readthedocs.io/en/latest/Python-Intro.html) is not the best way to make this 'memory efficient'. I'm not sure why this is though because their example doesn't require to use `free_data_raw=false`.
  
If I don't save the binary file using from the Dataset class and use the `save_binary` parameter, I don't see this file actually being saved anywhere so I'm not sure how to verify that it's working correctly.
  
Could someone explain the 'correct' way to save as binary to speed up training? Is it better to call it on the dataset prior to training? Or should I pass it as a parameter?

**Comment by guolinke** [comment]
@bbennett36 if you use the `reference` parameter for the validation data, you can always use `save_binary` with `free_raw_data=True`. 
for example:
 ```
lgb_train = lgb.Dataset(X_train, label=y_train)
lgb_train.save_binary("./data/lgb_train.bin") 

lgb_test = lgb.Dataset(X_test, label=y_test, reference=lgb_train)
lgb_test.save_binary("./data/lgb_test.bin") 
```
