### ISSUE TITLE
Issue with num_class for multi-class classification

### ISSUE THREAD

**Issue by econkc** [Microsoft/LightGBM#1306]
Hi,

When I try to run a multiclass classification in python, I always need to add 1 to num_class variable from the actual number of class, otherwise the model won't run. Once I add 1, class 0 (which seems to be read as the extra class added) will have no observation. This doesn't seem to affect the accuracy of the model, although I think it might cause the slow down in estimation process because the model needs to try to classify an extra class. Plus, this is a bit confusing in practice. Attached below is the error I've got when I use the correct number of classes.

Thanks,

> ---------------------------------------------------------------------------
> LightGBMError                             Traceback (most recent call last)
> <ipython-input-26-7b29b7f2039d> in <module>()
>       2 
>       3 get_ipython().magic('time')
> ----> 4 bst = lgb.train(param, train_data)
> 
> ~/anaconda3/lib/python3.6/site-packages/lightgbm/engine.py in train(params, train_set, num_boost_round, valid_sets, valid_names, fobj, feval, init_model, feature_name, categorical_feature, early_stopping_rounds, evals_result, verbose_eval, learning_rates, keep_training_booster, callbacks)
>     178     # construct booster
>     179     try:
> --> 180         booster = Booster(params=params, train_set=train_set)
>     181         if is_valid_contain_train:
>     182             booster.set_train_data_name(train_data_name)
> 
> ~/anaconda3/lib/python3.6/site-packages/lightgbm/basic.py in __init__(self, params, train_set, model_file, silent)
>    1302                 train_set.construct().handle,
>    1303                 c_str(params_str),
> -> 1304                 ctypes.byref(self.handle)))
>    1305             # save reference to data
>    1306             self.train_set = train_set
> 
> ~/anaconda3/lib/python3.6/site-packages/lightgbm/basic.py in _safe_call(ret)
>      46     """
>      47     if ret != 0:
> ---> 48         raise LightGBMError(_LIB.LGBM_GetLastError())
>      49 
>      50 
> 
> LightGBMError: b'Check failed: index < num_tree_per_iteration_ at /Users/travis/build/Microsoft/LightGBM/python-package/compile/src/boosting/gbdt.cpp, line 131 .\n'

**Comment by guolinke** [comment]
@econkc the classes should start from 0, and contiguous.
As a result, if the number of your max class is k, the num_class  = k+1
