### ISSUE TITLE
Keep predictions from valid_sets using lgb.train

### ISSUE THREAD

**Issue by dkivaranovic** [Microsoft/LightGBM#1309]
I am running lgb.train with early stopping and want to save the predictions of the validation set of the best round. However, it seems that this is not possible at the moment. I am working with large data sets and loading data and predicting is very time consuming... Such an option would save me a lot of time.

My question is related to #283

**Comment by guolinke** [comment]
you can use this function (https://github.com/Microsoft/LightGBM/blob/master/python-package/lightgbm/basic.py#L1923) to get the prediction.
data_idx=1 means the first validation dataset, data_idx=2 means the second one, and so on.

And you should set `keep_training_booster=True` when using `lgb.train` .

**Comment by dkivaranovic** [comment]
Thank you @guolinke! Not sure if I'm missing something but when I run 
```
import numpy as np
import lightgbm as lgb

Xtrain = np.random.randn(100, 10)
ytrain = np.where((np.sum(Xtrain, axis = 1) + np.random.randn(100)) > 0, 1, 0)
Xtest = np.random.randn(50, 10)
ytest = np.where((np.sum(Xtest, axis = 1) + np.random.randn(50)) > 0, 1, 0)
dtrain = lgb.Dataset(Xtrain, label = ytrain)
dtest = lgb.Dataset(Xtest, label = ytest)

params = {
    'boosting_type': 'gbdt',
    'objective':     'binary',
    'metric':        'binary_logloss',
    'learning_rate': 0.01,
    'num_leaves':    10,
    'min_data_in_leaf': 5,
    'verbosity':       0
}

max_rounds = 1000
early_stopping = 10

gbm = lgb.train(params,
                dtrain,
                num_boost_round = max_rounds,
                early_stopping_rounds = early_stopping,
                valid_sets = dtest,
                verbose_eval = 10,
                keep_training_booster=True)

pred = gbm.__inner_predict(data_idx = 1)
```

I get the following error:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Booster' object has no attribute '__inner_predict'

I am using Ubuntu 16.04.4 LTS, Python 3.6.0 :: Anaconda 4.3.1 (64-bit) and Lightgbm 2.1.0

**Comment by sbensoussan** [comment]
Hi, @dkivaranovic. 

You can retrieve the predictions using `gbm._Booster__inner_predict` and the `data_idx`.

```DIFF
- pred = gbm.__inner_predict(data_idx = 1)
+ pred = gbm._Booster__inner_predict(data_idx=1)
```
