### ISSUE TITLE
MPI example in Python

### ISSUE THREAD

**Issue by MikolajMizera** [Microsoft/LightGBM#1312]
Hello,
is it possible to start parallel learning via MPI in python (preferably using scikit-learn api)? According to docs, I should start mpi workers first, but they won't start without training set specified, which I specify in python script. I use LightGBM from pip with --install-option=--mpi . 
I tried to fit the LGBMClassifier
`LGBMClassifier(n_jobs=56, boosting_type ='dart', random_state=42, max_depth=-1, tree_learner='data', num_machines=2, machine_list_file='mlist.txt', n_estimators=200)`
and I am getting 

> [Warning] Only find one worker, will switch to serial tree learner.

 I have 2 machines 28 cores each.

**Comment by guolinke** [comment]
@MikolajMizera python version doesn't support parallel version yet.

**Comment by MikolajMizera** [comment]
@guolinke ok, thank you
