### ISSUE TITLE
Random Forest prediction on very large matrices is extremely slow

### ISSUE THREAD

**Issue by Laurae2** [Microsoft/LightGBM#1313]
## Environment info
Operating System: Windows Server 2016
CPU: Dual Xeon E5-2697v3
C++/Python/R version: 3.4.4

## Error Message:

LightGBM gets "stuck" when attempting to predict a from a Random Forest model using very large data (approx 4TB RAM, sparse 1GB RAM).

## Reproducible examples

Private data, can't share unfortunately. But steps below can help.

## Steps to reproduce

* Step 1: create an extremely dense (sparse) matrix of size 25M x 20K in R
* Step 2: train a Random Forest for 2000 trees + depth unlimited + 4095 leaves
* Step 3: attempt to predict on the first row of the original matrix, it works fine
* Step 4: attempt to predict on the original matrix, it is way too slow and eventually R gets stuck for a very long time (I cancelled after 15 mins of prediction attempts)

**Comment by Laurae2** [comment]
This should be tested as a convenience alternative: https://github.com/dmlc/treelite

TO-DO benchmark

In R, requires converting dgCMatrix to SciPy sparse format, it might explode memory (untested).

**Comment by guolinke** [comment]
@Laurae2 the GBDT model is normal ?

**Comment by guolinke** [comment]
@Laurae2 it is possible slow if using the csc(dgcMatrix) format. The dense matrix will stuck as well ? 
BTW, can you change `20000` in this line(https://github.com/Microsoft/LightGBM/blob/master/src/application/predictor.hpp#L63) to a larger value, and test again ?

**Comment by guolinke** [comment]
ping @Laurae2

**Comment by Laurae2** [comment]
@guolinke It seems to work fine when putting 100000 instead of 20000.
