### ISSUE TITLE
Piecewise linear trees

### ISSUE THREAD

**Issue by sosmond** [microsoft/LightGBM#1315]
I recently discovered [this paper](https://arxiv.org/pdf/1802.05640.pdf) which was submitted earlier this year showing impressive results of GBDTs utilizing piecewise linear trees. It's claimed that PL trees converge faster and are more accurate than the constant trees xgboost & lightgbm uses, and that optimizations exist to make GBDT-PL competitive speed-wise. 

The repo for the paper can be found [here](https://github.com/GBDT-PL/GBDT-PL). Is there any chance of adding this feature?

**Comment by StrikerRUS** [comment]
Closed in favor of being in #2302. We decided to keep all feature requests in one place.

Welcome to contribute this feature! Please re-open this issue (or post a comment if you are not a topic starter) if you are actively working on implementing this feature.

**Comment by kruda** [comment]
I'd like to work on this issue.

**Comment by jameslamb** [comment]
Thanks @kruda ! I'll re-open and assign to you. Let us know if you have any questions.

**Comment by StrikerRUS** [comment]
@jameslamb I believe we should re-open a feature request issue only after any evidence of active work on it. Otherwise, we may fall down into dozens of open stale issues like it was before #2302, e.g. here https://github.com/microsoft/LightGBM/issues/261#issuecomment-436995220.

@kruda You can submit a PR any time you want marking it `[WIP]` so that it will be easier to discuss implementation aspects and ask related questions.

**Comment by jameslamb** [comment]
> @jameslamb I believe we should re-open a feature request issue only after any evidence of active work on it. Otherwise, we may fall down into dozens of open stale issues like it was before #2302, e.g. here [#261 (comment)](https://github.com/microsoft/LightGBM/issues/261#issuecomment-436995220).
> 
> @kruda You can submit a PR any time you want marking it `[WIP]` so that it will be easier to discuss implementation aspects and ask related questions.

ok fair enough!

**Comment by stanpcf** [comment]
Hi @kruda How is your process going?

**Comment by StrikerRUS** [comment]
Implemented in #3299.
