### ISSUE TITLE
Pytthon API. best_iteration, best_score for custom evaluation function

### ISSUE THREAD

**Issue by BasDost** [Microsoft/LightGBM#1332]
I'm using lightgbm.train with valid_sets, early_stopping_rounds and feval function for multiclass problem with "objective":  "multiclass". I want to find best_iteration and best_score for my custom evaluation function. But it finds them for multi_logloss metrics, which is corresponding to specified objective. So the question is can I find in LightGBM best_iteration and best_score for my feval function and how?

**Comment by mlisovyi** [comment]
Early stopping (and thus best_xxx) is defined based on stop of improvement of **any** included metric. By default, the objective function is included as a default metric. If you want to drop that from the metrics list, you have to specify `metric='None'` in the parameters, see #1318, where basically the same question was asked :) I'm trying to get through a PR for the docs to make this feature clear to users

**Comment by BasDost** [comment]
Thanks!
