### ISSUE TITLE
boosting_type "rf" leads to unresolvable failures

### ISSUE THREAD

**Issue by namato** [Microsoft/LightGBM#1333]
Hey guys, I'm doing some grid searching with various boosting_type settings, and notice that whenever I use boosting_type rf, the fit fails:

```
[LightGBM] [Fatal] Check failed: config->bagging_freq > 0 && config->bagging_fraction < 1.0f && config-
>bagging_fraction > 0.0f at /home/travis/build/Microsoft/LightGBM/python-package/compile/src/boosting/r
f.hpp, line 29 .
```

Even though in the sklearn API:
1) There are no other parameters set other than the defaults
2) The fit succeeds with "gbd", "dart" and "goss"
3) There is no way to actually set these values in the sklearn API (bagging_freq, bagging_fraction) other than through additional kwargs, which is apparently unsupported

**Comment by guolinke** [comment]
for random forest, you should use subsets. As a result, you should set ``baggeng_freq=1`` with `bagging_fraction < 1.0f `
