### ISSUE TITLE
cat_l2 feature

### ISSUE THREAD

**Issue by nirupamkar** [Microsoft/LightGBM#1335]
I am trying to use cat_smooth and cat_l2 feature.  it seems like it's not a valid option. However the parameter list contains these 2 parameters.

## Environment info
Python 2.7

## Error Message:

LightGBMErrorTraceback (most recent call last)
<ipython-input-14-0858c9cebd11> in <module>()
     44                valid_sets=lgb_test_data,
     45                num_boost_round=1000,
---> 46                early_stopping_rounds=50)
     47 # model = lightgbm.train(parameters,
     48 #                lgb_train_data,

/home/nirupam.k/anaconda2/lib/python2.7/site-packages/lightgbm/engine.pyc in train(params, train_set, num_boost_round, valid_sets, valid_names, fobj, feval, init_model, feature_name, categorical_feature, early_stopping_rounds, evals_result, verbose_eval, learning_rates, keep_training_booster, callbacks)
    176     """construct booster"""
    177     try:
--> 178         booster = Booster(params=params, train_set=train_set)
    179         if is_valid_contain_train:
    180             booster.set_train_data_name(train_data_name)

/home/nirupam.k/anaconda2/lib/python2.7/site-packages/lightgbm/basic.pyc in __init__(self, params, train_set, model_file, silent)
   1265                 train_set.construct().handle,
   1266                 c_str(params_str),
-> 1267                 ctypes.byref(self.handle)))
   1268             """save reference to data"""
   1269             self.train_set = train_set

/home/nirupam.k/anaconda2/lib/python2.7/site-packages/lightgbm/basic.pyc in _safe_call(ret)
     46     """
     47     if ret != 0:
---> 48         raise LightGBMError(_LIB.LGBM_GetLastError())
     49 
     50 

LightGBMError: Unknown parameter: cat_l2

## Reproducible examples
parameters = {
    'application': 'binary',
    'objective': 'binary',
    'metric': 'binary_logloss,auc',
    'train_metric':'true',
    'is_unbalance': 'true',
    'boosting': 'gbdt',
    'num_leaves': 200,
    'feature_fraction': 0.7,
    'bagging_fraction': 0.7,
    'bagging_freq': 20,
    'learning_rate': 0.1,
    'lambda_l1':0.0001,
    'lambda_l2':0.0001,
    'verbose': 0,
    'min_data_in_leaf':10,
    'max_cat_threshold':200,
    'cat_smooth':100,
    'cat_l2':0.00001
}

for feature_name in valid_features:
    if feature_name in categorical_features:
        train[feature_name] = train[feature_name].astype('category')
        test[feature_name] = test[feature_name].astype('category')
lgb_train_data = lightgbm.Dataset(train, label=train_y.values,
                                  categorical_feature = [feature for feature in categorical_features if feature in valid_features],free_raw_data=False)
lgb_test_data = lightgbm.Dataset(test,label=test_y.values,
                                 categorical_feature=[feature for feature in categorical_features if feature in valid_features],free_raw_data=False)
model = lightgbm.train(parameters,
               lgb_train_data,
               valid_sets=lgb_test_data,
               num_boost_round=1000,
               early_stopping_rounds=50)

Please let me know if the python api does not have these 2 parameters.

**Comment by guolinke** [comment]
which version you are using with? 
I have test with parameter `cat_l2`: https://github.com/Microsoft/LightGBM/blob/e005cdb049271ecdd4e631043517ac18f6c9a867/tests/python_package_test/test_engine.py#L214-L246 . 
If python api cannot use these 2 parameters, these tests will fail.
