### ISSUE TITLE
Build on win10 do not produce DLL dir

### ISSUE THREAD

**Issue by gugatr0n1c** [Microsoft/LightGBM#134]
Hi,

I am trying to build library on new win10 server, 64bit.
I am using Visual Studio (Community 2015) 14.0

Build seems to be OK, log below. But when I try to install Python interface from python-package folder I get this error below. LightGBM/windows/x64/Release/ is created, but no DLL folder is created.

$ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 17, in <module>
    LIB_PATH = libpath['find_lib_path']()
  File "lightgbm/libpath.py", line 29, in find_lib_path
    raise Exception('Cannot find lightgbm Library in following paths: '+','.join                                                                      (dll_path))
Exception: Cannot find lightgbm Library in following paths: C:\Users\MATH.DESKTO                                                                      P-3D73V0B\LightGBM\python-package\lightgbm\lib_lightgbm.dll,C:\Users\MATH.DESKTO                                                                      P-3D73V0B\LightGBM\lib\lib_lightgbm.dll,C:\Users\MATH.DESKTOP-3D73V0B\LightGBM\l                                                                      ib_lightgbm.dll,C:\Users\MATH.DESKTOP-3D73V0B\LightGBM\python-package\lightgbm\l                                                                      ib\lib_lightgbm.dll,C:\Program Files\Anaconda3\lightgbm\lib_lightgbm.dll,C:\User                                                                      s\MATH.DESKTOP-3D73V0B\LightGBM\windows\x64\Dll\lib_lightgbm.dll,C:\Users\MATH.D                                                                      ESKTOP-3D73V0B\LightGBM\python-package\lightgbm\windows\x64\Dll\lib_lightgbm.dll                                                                      ,C:\Users\MATH.DESKTOP-3D73V0B\LightGBM\Release\lib_lightgbm.dll

Visual Studio log:
1>------ Build started: Project: LightGBM, Configuration: Release x64 ------
1>  application.cpp
1>  boosting.cpp
1>  gbdt.cpp
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\utility(172): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data
1>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xmemory0(737): note: see reference to function template instantiation 'std::pair<int,int>::pair<size_t&,size_t&,void,0>(_Other1,_Other2) noexcept' being compiled
1>          with
1>          [
1>              _Other1=size_t &,
1>              _Other2=size_t &
1>          ]
1>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xmemory0(737): note: see reference to function template instantiation 'std::pair<int,int>::pair<size_t&,size_t&,void,0>(_Other1,_Other2) noexcept' being compiled
1>          with
1>          [
1>              _Other1=size_t &,
1>              _Other2=size_t &
1>          ]
1>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xmemory0(857): note: see reference to function template instantiation 'void std::allocator<_Ty>::construct<_Objty,size_t&,size_t&>(_Objty *,size_t &,size_t &)' being compiled
1>          with
1>          [
1>              _Ty=std::pair<int,int>,
1>              _Objty=std::pair<int,int>
1>          ]
1>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xmemory0(857): note: see reference to function template instantiation 'void std::allocator<_Ty>::construct<_Objty,size_t&,size_t&>(_Objty *,size_t &,size_t &)' being compiled
1>          with
1>          [
1>              _Ty=std::pair<int,int>,
1>              _Objty=std::pair<int,int>
1>          ]
1>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xmemory0(996): note: see reference to function template instantiation 'void std::allocator_traits<_Alloc>::construct<_Ty,size_t&,size_t&>(std::allocator<_Ty> &,_Objty *,size_t &,size_t &)' being compiled
1>          with
1>          [
1>              _Alloc=std::allocator<std::pair<int,int>>,
1>              _Ty=std::pair<int,int>,
1>              _Objty=std::pair<int,int>
1>          ]
1>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xmemory0(995): note: see reference to function template instantiation 'void std::allocator_traits<_Alloc>::construct<_Ty,size_t&,size_t&>(std::allocator<_Ty> &,_Objty *,size_t &,size_t &)' being compiled
1>          with
1>          [
1>              _Alloc=std::allocator<std::pair<int,int>>,
1>              _Ty=std::pair<int,int>,
1>              _Objty=std::pair<int,int>
1>          ]
1>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\vector(930): note: see reference to function template instantiation 'void std::_Wrap_alloc<std::allocator<_Ty>>::construct<_Ty,size_t&,size_t&>(_Ty *,size_t &,size_t &)' being compiled
1>          with
1>          [
1>              _Ty=std::pair<int,int>
1>          ]
1>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\vector(929): note: see reference to function template instantiation 'void std::_Wrap_alloc<std::allocator<_Ty>>::construct<_Ty,size_t&,size_t&>(_Ty *,size_t &,size_t &)' being compiled
1>          with
1>          [
1>              _Ty=std::pair<int,int>
1>          ]
1>  ..\src\boosting\gbdt.cpp(351): note: see reference to function template instantiation 'void std::vector<std::pair<int,int>,std::allocator<_Ty>>::emplace_back<size_t&,size_t&>(size_t &,size_t &)' being compiled
1>          with
1>          [
1>              _Ty=std::pair<int,int>
1>          ]
1>  ..\src\boosting\gbdt.cpp(351): note: see reference to function template instantiation 'void std::vector<std::pair<int,int>,std::allocator<_Ty>>::emplace_back<size_t&,size_t&>(size_t &,size_t &)' being compiled
1>          with
1>          [
1>              _Ty=std::pair<int,int>
1>          ]
1>  c_api.cpp
1>  bin.cpp
1>  config.cpp
1>C:\Users\MATH.DESKTOP-3D73V0B\LightGBM\include\LightGBM/utils/common.h(294): warning C4127: conditional expression is constant
1>  ..\src\io\config.cpp(231): note: see reference to function template instantiation 'std::vector<double,std::allocator<_Ty>> LightGBM::Common::StringToArray<double>(const std::string &,char)' being compiled
1>          with
1>          [
1>              _Ty=double
1>          ]
1>  dataset.cpp
1>  dataset_loader.cpp
1>  metadata.cpp
1>  parser.cpp
1>  tree.cpp
1>C:\Users\MATH.DESKTOP-3D73V0B\LightGBM\include\LightGBM/utils/common.h(278): warning C4127: conditional expression is constant
1>  ..\src\io\tree.cpp(217): note: see reference to function template instantiation 'std::vector<int,std::allocator<_Ty>> LightGBM::Common::StringToArray<int>(const std::string &,char,std::size_t)' being compiled
1>          with
1>          [
1>              _Ty=int
1>          ]
1>  dcg_calculator.cpp
1>  metric.cpp
1>  network.cpp
1>  linkers_mpi.cpp
1>  linkers_socket.cpp
1>  linker_topo.cpp
1>  objective_function.cpp
1>  main.cpp
1>  data_parallel_tree_learner.cpp
1>  Compiling...
1>  feature_parallel_tree_learner.cpp
1>  serial_tree_learner.cpp
1>  tree_learner.cpp
1>  voting_parallel_tree_learner.cpp
1>  application.obj : MSIL .netmodule or module compiled with /GL found; restarting link with /LTCG; add /LTCG to the link command line to improve linker performance
1>     Creating library C:\Users\MATH.DESKTOP-3D73V0B\LightGBM\windows\x64\Release\lightgbm.lib and object C:\Users\MATH.DESKTOP-3D73V0B\LightGBM\windows\x64\Release\lightgbm.exp
1>  Generating code
1>  Finished generating code
1>  LightGBM.vcxproj -> C:\Users\MATH.DESKTOP-3D73V0B\LightGBM\windows\x64\Release\lightgbm.exe
1>  LightGBM.vcxproj -> C:\Users\MATH.DESKTOP-3D73V0B\LightGBM\windows\x64\Release\lightgbm.pdb (Full PDB)
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========

**Comment by guolinke** [comment]
@gugatr0n1c  you should choose config to "DLL|x64" if you want to build library. 
It seems you choose "Release|x64".

**Comment by gugatr0n1c** [comment]
oh man, I am stupid, I just over see this in manual "after built (library(.dll) file is in  ./windows/x64/DLL/ )."
