### ISSUE TITLE
Single process for predict in python (scikit interface)

### ISSUE THREAD

**Issue by chytufk** [Microsoft/LightGBM#1340]
I am trying to run the prediction (using predict_proba from the scikit interface) without parallelization (in a single process/using single CPU core). I've tried tried training with n_jobs=1 (while training to see if it helps) and tried setting environment variable OMP_NUM_THREADS from within the predict function like so, with no improvement.
`os.environ["OMP_NUM_THREADS"]` = "1"

Only thing that seems to be working right now is to set the environment variable from command line.
It would be good if we can control the parallelization of predict function from within python code. 

## Environment info
Operating System: Linux Debian 7
CPU: Intel Haswell
C++/Python/R version: Python 2.7 with lightGBM version 2.1.0

**Comment by guolinke** [comment]
you can set ```num_threads=1``` in create predict booster(lightgbm.Booster), in the `params` dict.

**Comment by StrikerRUS** [comment]
@guolinke Can we provide the same functionality in sklearn wrapper via `**kwargs` [here](https://github.com/Microsoft/LightGBM/blob/fb55d72fcb9096a7a78c523df9f8d711938fc223/python-package/lightgbm/sklearn.py#L511)?

**Comment by StrikerRUS** [comment]
ping @guolinke

**Comment by guolinke** [comment]
@StrikerRUS I think we can have this in predict function
