### ISSUE TITLE
n_jobs=-1 caused problem at GCM

### ISSUE THREAD

**Issue by ghostintheshellarise** [Microsoft/LightGBM#1345]
## Environment info
Operating System: Ubuntu 16.04 on Google Compute Engine
CPU: 16vCPU with no GPU support
C++/Python/R version: Python 3.6

## Error Message:
There is no error message but an unexpected slow down in the process.  The CPU seems to stop processing anything when I change the setting of the regressor from n_jobs=1 to n_jobs=-1

## Reproducible examples
[https://drive.google.com/drive/my-drive](url)

## Steps to reproduce
1. I am using the UCI Data from Parkinson Telemetry Data (https://archive.ics.uci.edu/ml/machine-learning-databases/parkinsons/telemonitoring/parkinsons_updrs.data)
2. I run the lightgbm with n-jobs=-1 (see the above link) with the provided ipynb at Colaboratory, later at Google VM and Datalab.
3. And it just froze.

[LightGBM-GPU.zip](https://github.com/Microsoft/LightGBM/files/1953947/LightGBM-GPU.zip)

**Comment by guolinke** [comment]
did you test it in other platforms? e.g. local machines and other VMs?

**Comment by ghostintheshellarise** [comment]
Yes. I run it on my local Macbook Pro and same issues happened

**Comment by guolinke** [comment]
can you try to run it with native python, not the ipynb?

**Comment by guolinke** [comment]
@ghostintheshellarise Just read your notebook, I think the problem is in following code, right?
```
# LightGBM Regressor True Performance
scaler = MinMaxScaler()
y = df['total_UPDRS']
x = scaler.fit_transform(df[features])
lgb = LGBMRegressor(n_jobs=-1)
title = lgb
# Cross validation with 100 iterations to get smoother mean test and train, but it's costly to do. So I change to 20
# score curves, each time with 20% data randomly selected as a validation set.
cv = ShuffleSplit(n_splits=20, test_size=0.2, random_state=0)
plot_learning_curve(lgb, title, x, y, ylim=(0.0, 1.01), cv=cv, n_jobs=4)
plt.show()
```
The reason is, when you set `n_jobs=-1` in LightGBM, it will use all CPU cores. In that situation, you cannot set `n_jobs=4` in `plot_learning_curve`, otherwise the CPU is overload, and cause the halt. 

If want to set `n_jobs=4` in `plot_learning_curve`, you should set `n_jobs` to #CORES/4 in LightGBM side.
