### ISSUE TITLE
[bug] installation of python package fails with python 3.5.2

### ISSUE THREAD

**Issue by dancaspi** [Microsoft/LightGBM#135]
after compiling the package on ubuntu 16.04 LTS 64-bit, with gcc5, the python package installation fails because of the "include_package_data=True" in the setup.py. when running the script with the flag on, the error is:
 error: Error: setup script specifies an absolute path:

after turning off the installation succeeds and import to python also succeeds.
can this be turned off by default? what are the implications?

**Comment by wxchan** [comment]
Actually I am facing this issue all the time too. Have you checked [this thread on stackoverflow](http://stackoverflow.com/questions/18085571/pip-install-error-setup-script-specifies-an-absolute-path)? It looks like some bug in setuptools.

Do you have some suggestions on it? It should work on different systems including linux, windows, macos and etc..

**Comment by dancaspi** [comment]
Hey,
yes, this is exactly the thread that lead me to try and turn off "include_package_data". 
**I run the python_package_tests and they seem to have passed**.... so maybe this can be marked as a solution? i admit, I am not sure what are the exact implications of the flag i turned off....

**Comment by wxchan** [comment]
It's a solution for personal user. `include_package_data=True` is needed for pypi package, so we can't remove it. Before we have a better solution, I think we need user to remove that line manually.

**Comment by dancaspi** [comment]
fair enough... should I close or leave that open as the matter isn't really solved? your call

**Comment by wxchan** [comment]
You can close it. It's not our bug.
