### ISSUE TITLE
[python] What iteration the Booster stops on in early stopping?

### ISSUE THREAD

**Issue by mlisovyi** [Microsoft/LightGBM#1355]
Hi,

the documentation [here](http://lightgbm.readthedocs.io/en/latest/Python-Intro.html#early-stopping) claims that in the case of early stopping the last evaluated iteration is returned by `train()`. This would be in line with what xgboost does. However, in practice I observe that the `Booster` object stored inside `LGBMModel` points at the optimal iteration. 

I assume it is a known behaviour and the docs have to be updated. But if not, let me know and I can prepare a minimal example to reproduce this behaviour.

Cheers,
M.

**Comment by guolinke** [comment]
@mlisovyi I update it to the best iteration, but forget to update the doc

**Comment by mlisovyi** [comment]
@guolinke would you mind updating the docs or shall i?

**Comment by guolinke** [comment]
@mlisovyi you can update it in your PR~
