### ISSUE TITLE
How to load libsvm text file as dataset?

### ISSUE THREAD

**Issue by zeushera140** [Microsoft/LightGBM#1368]
## Environment info
Operating System: win7-64bit
CPU: i5-5200U
Python: 3.6.5

## Reproducible examples: 
I tried to load a libsvm format text file with python-api, but failed. Maybe it's due to the wrong format, so I wonder if there is an example to show how to load libsvm format text files. thanks.

below is my file format
-1 15515:1 280:1 2:1 3:1 310:1 150:1 115:1 311:1

## Steps to reproduce
1. train_train_file = file_path+'train.txt'
2. train_train_lgb =  lgb.Dataset(train_train_file)
3. qq_lgb = lgb.train(params,train_train_lgb)

**Comment by zeushera140** [comment]
problem solved, seems due to the file encoding

**Comment by ttpro1995** [comment]
> problem solved, seems due to the file encoding, UTF-8 works for me

How do you fix UTF-8 problem ? Please give me example code.
