### ISSUE TITLE
How to use feature_fraction,bagging_fraction,bagging_freq with RandomizedSearchCV

### ISSUE THREAD

**Issue by dancaspi** [Microsoft/LightGBM#137]
Hey,
I want to create a parameter grid using RandomizedSearchCV, however, it appears that the scikit binding doesn't include those parameters (maybe under a different name?)

Am I missing something or is this yet to be implemented?

Thanks,
Dan

**Comment by ekerazha** [comment]
feature_fraction -> colsample_bytree
bagging_fraction -> subsample
bagging_freq -> subsample_freq

**Comment by dancaspi** [comment]
Thanks!
