### ISSUE TITLE
gbm train process with valid res is not the same with valid predict from train model

### ISSUE THREAD

**Issue by summersunshine1** [Microsoft/LightGBM#1370]
Please search your question on previous issues, [stackoverflow](https://stackoverflow.com/questions/tagged/lightgbm) or other search engines before you open a new one.

For bugs and unexpected issues, please provide following information, so that we could reproduce on our system.

## Environment info
Operating System:
CPU:
C++/Python/R version:

## Error Message:
gbm train process with valid res is not the same with valid predict from train model

## Reproducible examples
```python
import lightgbm as lgb
import re
import pickle
import operator
from sklearn.metrics import roc_auc_score
import numpy as np
import gc

data = np.random.rand(500, 10)  # 500 entities, each contains 10 features
label = np.random.randint(2, size=500)  # binary target

valid_data = np.random.rand(100, 10)  # 500 entities, each contains 10 features
valid_label = np.random.randint(2, size=100)

model_path = 'model'

def train():
    train_dataset = lgb.Dataset(data, label=label)
    test_dataset = lgb.Dataset(valid_data, label=valid_label)
    
    param = {'objective':'binary','task': 'train','boosting_type':'gbdt', 'num_leaves':31,'metric': {'auc','binary_logloss'},
     'learning_rate': 0.05,
    'feature_fraction': 0.8,
    'bagging_fraction': 0.8,
    'bagging_freq': 5,
    'verbose': 0,
    'lambda_l1':2,
    'bagging_seed':1993
    }
    # if os.path.exists(model_path):
        # bst = lgb.train(param, init_model = model_path, train_set  = train_dataset, num_boost_round=500,valid_sets=[valid_dataset],early_stopping_rounds = 100)
    # else:
    bst = lgb.train(param, train_set  = train_dataset, num_boost_round=2,valid_sets=[test_dataset],early_stopping_rounds = 10)
    bst.save_model(model_path)
    
def valid():
    bst = lgb.Booster(model_file=model_path)
    pres = bst.predict(valid_data)
    print(roc_auc_score(valid_label,pres))
    
if __name__=="__main__":
    train()
    valid()
```
## Steps to reproduce

1.run the script above ,and get auc of valid dataset
2.comment train()
3.two valid auc res are different

**Comment by guolinke** [comment]
@summersunshine1 Have they a large gap ? 
I think the slight difference is not a problem. 
There may is some floating point precision issues between cpp and python in AUC calculation.

**Comment by summersunshine1** [comment]
when valid() function call after train() successively,the valid function result is fixed and is the same with eval result in train(),but when i just call valid() ,the valid results is seriously different at every time.

**Comment by guolinke** [comment]
@summersunshine1 
when you comment the `train` and re-run this script, and valid data (generated randomly) is changed. 
As a result, it will have the different result, right ? 

To check it, you should use the same valid data for the test.

**Comment by summersunshine1** [comment]
sorry, it's my fault, i close the issue
