### ISSUE TITLE
LightGBM Installation Error in MacOS with Anaconda Python3

### ISSUE THREAD

**Issue by wushengzhong** [Microsoft/LightGBM#1372]
Please search your question on previous issues, [stackoverflow](https://stackoverflow.com/questions/tagged/lightgbm) or other search engines before you open a new one.

For bugs and unexpected issues, please provide following information, so that we could reproduce on our system.

## Environment info
Operating System: mac OS 10.13.4 
CPU: intel core i7
C++/Python/R version: Anaconda Python 3.6.4

## Error Message:
OSError: dlopen(/Users/{xxx}/anaconda3/lib/python3.6/site-packages/lightgbm/lib_lightgbm.so, 6): Library not loaded: /usr/local/opt/gcc/lib/gcc/7/libgomp.1.dylib
  Referenced from: /Users/{xxx}/anaconda3/lib/python3.6/site-packages/lightgbm/lib_lightgbm.so
  Reason: image not found

## Steps to reproduce

1. brew install cmake
2. brew install gcc --without-multilib 
3. git clone --recursive https://github.com/Microsoft/LightGBM ; cd LightGBM
4. export CXX=g++-8 CC=gcc-8
5. mkdir build ; cd build  
6. cmake ..  
7. make -j4  
8. pip install lightgbm
---------------------------------------
**new terminal window**
1.  python
2.  import lightgbm

**Comment by guolinke** [comment]
I think the problem is gcc 8 in macos.
Move to https://github.com/Microsoft/LightGBM/issues/1369
