### ISSUE TITLE
How to load a scpiy.sparse.csr_matrix array into Dataset and specify categorical features meantime?

### ISSUE THREAD

**Issue by ShawnyXiao** [Microsoft/LightGBM#1375]
I know how to load a scpiy.sparse.csr_matrix array into Dataset and specify categorical features seperately. But as scpiy.sparse.csr_matrix has no column names, how could I load a it into Dataset and specify categorical features meantime?

**Comment by Laurae2** [comment]
You can use indexes (column number, starting from 0).

**Comment by ShawnyXiao** [comment]
Thanks for ansering! :)
