### ISSUE TITLE
Issues with categorical features since commit b51c7be

### ISSUE THREAD

**Issue by ekerazha** [Microsoft/LightGBM#138]
Since commit b51c7be I get the `Too many categoricals are ignored` warning and poor results on my data set. I use the sklearn interface.

No issues before b51c7be with the same code.

**Comment by guolinke** [comment]
@ekerazha can you paste an example code that how you call sklearn interface?
And how you use categorical_feature? by indices or feature_name?

**Comment by ekerazha** [comment]
@guolinke I use indeces:
```
        model = lgb.LGBMRegressor(objective='regression',
                                 n_estimators=5000,
                                 learning_rate=0.05,
                                 nthread=8,
                                 max_bin=8000,
                                 num_leaves=1000,
                                 colsample_bytree=0.6)
        model.fit(X_train,
                 y_train,
                 eval_set=[(X_val, y_val)],
                 early_stopping_rounds=10,
                 categorical_feature=[1, 3, 5, 7, 9])
```
I double checked that categorical columns use integer values.

Everything works fine if I use the python-package interface before b51c7be, while it's broken since b51c7be.

**Comment by guolinke** [comment]
@ekerazha , one other thing is, the index of feature is start from ```0```. so is it 2nd, 4th, 6th, 8th and 10th col  are categorical features ?

**Comment by ekerazha** [comment]
@guolinke It starts from 0.
0, 2, 4, 6, 8 are not categorical.

If I take the current LightGBM code and I replace the python-package content with the python-package code before b51c7be, it works fine. Commit b51c7be has broken something inside python-package.

**Comment by guolinke** [comment]
@ekerazha OK, i finally find out why, forget to set max_bin in sklearn interface.

Thanks!
