### ISSUE TITLE
Mac OS install instructions need to be updated

### ISSUE THREAD

**Issue by Gunnvant** [Microsoft/LightGBM#1387]
The gcc has been updated to version 8.1 since 17-05-18. The install documentation needs to be updated. Instead of 
`git clone --recursive https://github.com/Microsoft/LightGBM ; cd LightGBM
export CXX=g++-7 CC=gcc-7
mkdir build ; cd build
cmake ..
make -j4`

It should now be
`git clone --recursive https://github.com/Microsoft/LightGBM ; cd LightGBM
export CXX=g++-8 CC=gcc-8
mkdir build ; cd build
cmake ..
make -j4`

This needs to be changed in the install docs here https://lightgbm.readthedocs.io/en/latest/Installation-Guide.html

**Comment by StrikerRUS** [comment]
Thank you @Gunnvant ! PR is on the way!
