### ISSUE TITLE
Compile with Intel Compiler?

### ISSUE THREAD

**Issue by Laurae2** [Microsoft/LightGBM#1388]
@guolinke do you know how to compile LightGBM with icp (Windows) in R?

With Linux, seems straightforward by replacing gcc by icc, but not in Windows (controlled by Visual Studio cmake?)

**Comment by guolinke** [comment]
sorry, I didn't use icp before. 
But I think it can be achieved by using cmake. 

Here is link: https://stackoverflow.com/questions/27623110/how-to-generate-a-visual-studio-project-that-uses-the-intel-compiler-using-cmake

**Comment by Laurae2** [comment]
In Linux, I managed to compile LightGBM with Intel compilers by modifying the Makevars by adding the flags `"cmake -DCMAKE_C_COMPILER=icc -DCMAKE_CXX_COMPILER=icpc "`. Gave up for the Windows version, requires to push a command line to setup environment variables which gets lost afterwards.

However, it seems it is slower with LightGBM when using Intel Compilers against the default gcc.

You can check out my results here: https://public.tableau.com/views/IntelCompilervsgccv1/Dashboard?%3Aembed=y&%3AshowVizHome=no&%3Adisplay_count=y&%3Adisplay_static_image=y&%3AbootstrapWhenNotified=true&publish=yes#3
