### ISSUE TITLE
Optimization on predict output 

### ISSUE THREAD

**Issue by germayneng** [Microsoft/LightGBM#1390]
Hi all,

Once again, thank you for building lgbm. it is one of my most used algorithm and favorite. I have opened this similar issue to xgboost and obtained the answer. However, i am having trouble implementing it back to lgbm. 

The thread that i opened is [here](https://github.com/dmlc/xgboost/issues/3334)

hcho proposed a brute force algorithm where i create a spread of values of all the feature variables to fit into all the possible threshold splits. 

However, I can having difficulty extracting the threshold splits for all the features. Here is the sample code that he proposed: 

```python 
import xgboost
import json
import itertools
import numpy as np

def combine_thresh_table(old, new):
  for k, v in new.items():
    if k not in old:
      old[k] = set()
    old[k] |= v
  return old

def get_thresh(tree):
  table = dict()
  if 'children' in tree:
    fid = tree['split']
    val = tree['split_condition']
    if fid not in table:
      table[fid] = set()
    table[fid].add(val)
    table = combine_thresh_table(table, get_thresh(tree['children'][0]))
    table = combine_thresh_table(table, get_thresh(tree['children'][1]))
  return table

def get_thresh_ensemble(ensemble):
  table = dict()
  for tree in ensemble:
    table = combine_thresh_table(table, get_thresh(tree))
  return table

def get_ensemble_json_dump(bst):
  tree_dump = []
  for dump in bst.get_dump(with_stats=True, dump_format='json'):
    tree_dump.append(json.loads(dump))
  return tree_dump

bst = xgboost.Booster()
bst.load_model('xgb_labels_model.bin')
ensemble = get_ensemble_json_dump(bst)
threshold = get_thresh_ensemble(ensemble)
threshold = {k:list(v) for k,v in threshold.items()}
x = {k:[np.nan] + \
     [-np.finfo('f').max] + \
     [(v[i] + v[i+1]) / 2.0 for i in range(len(v)-1)] + \
     [np.finfo('f').max] for k, v in threshold.items()}

max_pred = 0
max_pred_input = None
for e in itertools.product(*x.values()):
  dtest = xgboost.DMatrix(np.array([e]))
  pred = bst.predict(dtest, output_margin=True)[0]
  if pred > max_pred:
      max_pred_input = e[:]
      max_pred = pred
```

From this sample code, I am able to extract out the split values for all variables. Essentially, i have a dictionary key of the feature names with a list of splits as key. From there, we can customize and do a brute algorithm to find the maximum value. 

i have tried many methods to replicate it using lgbm but i am not able to extract the model dump. I tried using lgbm_model.dump_model() as well. It will be good if you guys can help me 

Regards
Germayne

**Comment by guolinke** [comment]
@germayneng 
I think you can use the similar solution. However, you should use `split_feature` to get `fid`, and `threshold` to get `val` .

**Comment by germayneng** [comment]
@guolinke Thank you! However, i am still getting error : 

```python
def get_ensemble_json_dump(bst):
  tree_dump = []
  for dump in bst.dump_model():
    tree_dump.append(json.loads(dump))
  return tree_dump
```

![image](https://user-images.githubusercontent.com/22788747/40417852-593c990c-5eb3-11e8-9d86-6a62f37658df.png)


Is there a way to dump it and reload it back as a list/ array ?
