### ISSUE TITLE
simple LightGBM fork questions

### ISSUE THREAD

**Issue by IbanezJS** [Microsoft/LightGBM#1392]
Hi there.
I do LightGBM simplifications for my own purpose.
The restrictions are:
-Single threaded. No network no OMP parallel
-Features are all numeric without missing values (so Dataset is dense)
-only binary and regression objectives
-only single class label
-optimized for prediction on streaming data (after training)

The main question is: So if there are no missing values in features then can i completly remove
`default_bin` and `BinMapper::GetDefaultBin()` from code?

The Lines that bother me:
1)`Dataset::FixHistogram`  `if (default_bin > 0)`
2)`FeatureGroup` constructors `if (bin_mappers_[i]->GetDefaultBin() == 0) {
        num_bin -= 1;
      }`
3)`FeatureGroup::PushData`  `if (bin == bin_mappers_[sub_feature_idx]->GetDefaultBin()) { return; }` and `if (bin_mappers_[sub_feature_idx]->GetDefaultBin() == 0) {
      bin -= 1;
    }`
4)`DenseBinIterator` constructor `if (default_bin_ == 0) {
      bias_ = 1;
    } else {
      bias_ = 0;
    }`
5)`DenseBin::Split` `if (default_bin == 0) {
      th -= 1;
      t_default_bin -= 1;
    }`  and `if ((default_left && missing_type == MissingType::Zero) || (default_bin <= threshold && missing_type != MissingType::Zero)) {
        default_indices = lte_indices;
        default_count = &lte_count;
      }`
6)`HistogramPool::DynamicChangeSize`  `if (train_data->FeatureBinMapper(i)->GetDefaultBin() == 0) {
          feature_metas_[i].bias = 1;
        } else {
          feature_metas_[i].bias = 0;
        }`  and  `if (train_data->FeatureBinMapper(j)->GetDefaultBin() == 0) {
          num_bin -= 1;
        }`
and so on

Can you also suggest any other simplifications that i can made according to restictions above?

**Comment by guolinke** [comment]
@IbanezJS default bin is for the zero-value, not the missing value, so it cannot remove it. 

We have a parameter to control missing value handle, it is named, `use_missing`. you can search it and find how to disable it from code.

**Comment by IbanezJS** [comment]
@guolinke 
Ok. What about io_config_.zero_as_missing ?
Does it relates to default_bin?

the concern is if features all numerical without "missing values" then why 0 must be special treated?

**Comment by guolinke** [comment]
@IbanezJS 
the zero_as_missing is disabled by default. And default_bin doesn't relate to missing value handles.

The 0 will not be special treated in numerical data without missing values, if you didn't set zero_as_missing to true.

**Comment by IbanezJS** [comment]
@guolinke i know that all))
But i still don't get why default_bin can't be removed from code if use_missing=false (in my case).

Concrete code parts that depends on default_bin == 0:
`bin -= 1;`  `num_bin -= 1;`  '{ feature_metas_[i].bias = 1; } else { feature_metas_[i].bias = 0; }'

Can i remove it also?

**Comment by IbanezJS** [comment]
@guolinke Ok. I will find out by myself and tell you later if is default_bin needed or not.

Next question is can i remove `min_constraint` and `max_constraint` stuff if i dont need `monotone_constraints` for features ?

**Comment by guolinke** [comment]
@IbanezJS yeah, you can remove the constraints.

**Comment by IbanezJS** [comment]
@guolinke 
What is the main idea of FeatureGroup entity?
Does it relate to feature_fraction config parameter?

**Comment by guolinke** [comment]
It is used to merge these sparse features into much fewer dense feature.
This can improve the speed of using high dimensional sparse datasets.
refer to the "exclusive feature bundling" idea in our paper.

**Comment by IbanezJS** [comment]
@guolinke  thanks for explanation.
So if Dataset is completely dense i can remove `FeatureGroup` and all code relative to `enable_bundle` config parameter?

Also can you tell if there is chat channel where i can ask questions like this? To speed up my development process. 
Later on i will post on GitHub LightGbmNetCore .netcore version with restrictions mentioned above

**Comment by guolinke** [comment]
I think asked in here is the best option. I will check it regularly. 
You also can email me directly if it is urgent.

**Comment by guolinke** [comment]
close now, but you can continue to ask questions in this thread.

**Comment by IbanezJS** [comment]
@guolinke Hi!  What is the meaning of is_use_subset_ = true; in GBDT class ?

I'm about this code:
`const int group_threshold_usesubset = 100;
    const int sparse_group_threshold_usesubset = train_data_->num_feature_groups() / 4;
    if (average_bag_rate <= 0.5
        && (train_data_->num_feature_groups() < group_threshold_usesubset || sparse_group < sparse_group_threshold_usesubset)) {
      if (tmp_subset_ == nullptr || is_change_dataset) {
        tmp_subset_.reset(new Dataset(bag_data_cnt_));
        tmp_subset_->CopyFeatureMapperFrom(train_data_);
      }
      is_use_subset_ = true;
      Log::Debug("Use subset for bagging");
    }`

**Comment by guolinke** [comment]
@IbanezJS 
It is use to speed up the training with bagging. 
This can reduce the cache-miss when using bagging.

**Comment by IbanezJS** [comment]
@guolinke Hello !

In BinMapper::FindBin method there is a cycle:

`for (int i = 1; i < num_sample_values; ++i) {
      if (!Common::CheckDoubleEqualOrdered(values[i - 1], values[i])) {
        if (values[i - 1] < 0.0f && values[i] > 0.0f) {
          distinct_values.push_back(0.0f);
          counts.push_back(zero_cnt);
        }
        distinct_values.push_back(values[i]);
        counts.push_back(1);
      } else {
        // use the large value
        distinct_values.back() = values[i];
        ++counts.back();
      }
    }`

I don't get why in 
` if (values[i - 1] < 0.0f && values[i] > 0.0f) {
          distinct_values.push_back(0.0f);
          counts.push_back(zero_cnt);
        }`
you do `counts.push_back(zero_cnt);` and not `counts.push_back(1);` ???

**Comment by guolinke** [comment]
@IbanezJS the zeros are not in sample values, as a result, there is special treatment.

**Comment by IbanezJS** [comment]
@guolinke Yes. i've got it.

Another thing 

BinMapper::GreedyFindBin
line
`cur_cnt_inbin += counts[num_distinct_values - 1];`

is useless

**Comment by IbanezJS** [comment]
@guolinke 
What is the main idea to devide samples in BinMapper::FindBin to LEFT_PART - ZEROS_PART - RIGHT_PART chuncks?

**Comment by guolinke** [comment]
@IbanezJS to special treatment for zeros, since there may be many zeros in real world data.

**Comment by MrTuesday1020** [comment]
@guolinke 
Hi there, I am doing LightGBM as well recently. For omp parallel version, it needs to find bin distributed if there are multi-machines and different machines will find bin for different features. So far it's clear. However why we need to gather all the global features according to global max_bin then restore features bins(code between line 909 to 954 in dataset_loader.cpp)? I am confused about it.

**Comment by guolinke** [comment]
Hi @MrTuesday1020 ,
In data parallel, each worker needs to know all feature information, for they are needed to consturct local histogram (based on local data), and then sync-up for the global histogram.
