### ISSUE TITLE
[doc][Parameters-Tuning] Fix the document about num_leaves in case of max_depth=6

### ISSUE THREAD

**Issue by fujii** [Microsoft/LightGBM#1394]
https://lightgbm.readthedocs.io/en/latest/Parameters-Tuning.html

> For example, when the max_depth=6 the depth-wise tree can get good accuracy, but setting num_leaves to 127 may cause over-fitting, and setting it to 70 or 80 may get better accuracy than depth-wise.

Where does this number `127` come from?
Other sentence says:

> we should let it be smaller than 2^(max_depth)

`2^6 = 64`. `70` and `80` are larger than `2^(max_depth)`. The sentence doesn't make sense.
I think it should be:

> For example, when the max_depth=6 the depth-wise tree can get good accuracy, but setting num_leaves to 63 may cause over-fitting, and setting it to 40 or 50 may get better accuracy than depth-wise.

**Comment by guolinke** [comment]
welcome to create a PR to fix it : )

**Comment by fujii** [comment]
Thanks for your feedback. I wanted to confirm that before creating a PR.  I will try.

**Comment by fujii** [comment]
Merged https://github.com/Microsoft/LightGBM/commit/1a1262cceb1121287eb44c60c491f0dbaee8f015
