### ISSUE TITLE
Dataset::ConstructHistograms() redundant cycle

### ISSUE THREAD

**Issue by IbanezJS** [Microsoft/LightGBM#1396]
Hello. it seems that this cycle is useless:
https://github.com/Microsoft/LightGBM/blob/e2a0de5082cc4f5630f0d446592547a7e4026801/src/io/dataset.cpp#L624

is it a bug?
after this cycle `used_group` vector is always 0,1,...num_groups_-1
`int num_used_group = static_cast<int>(used_group.size());` is always equals to `num_groups_`

so `is_feature_used` function argument does not affect "used_group" at all...

**Comment by guolinke** [comment]
@IbanezJS 
It depends on your data. For the dense dataset, one group only contains one feature. But for sparse features, it is not true.

**Comment by IbanezJS** [comment]
@guolinke 
absolutly dont get how it associated with the code issue...
the cycle is obviously useless.
A BUG in code!

**Comment by guolinke** [comment]
@IbanezJS 
one group may contain many features, if there are many spare feature. 
And `continue` is not needed anymore, since the useful group is saved in `use_group`. 
If you think it is not correct, you can provide a example.

**Comment by guolinke** [comment]
@IbanezJS 
sorry, you are right. I will fix it soon.
