### ISSUE TITLE
BUG in Dataset::ConstructHistograms

### ISSUE THREAD

**Issue by IbanezJS** [Microsoft/LightGBM#1397]
@guolinke 
commit 850f03913a5f182188abf4e291c0ec71db72b7b6  "remove some duplicate codes"
Did bug:
Old Code: `if (!is_groud_used) { continue; }`

After refactoring that line disappered. So now used_group always equals to all groups.

**Comment by guolinke** [comment]
@IbanezJS oh, you are right. Thanks for pointing it out.
