### ISSUE TITLE
How to set qid when predict in LGBMRanker?

### ISSUE THREAD

**Issue by deepfuzzy** [Microsoft/LightGBM#1398]
In python, qid can be set to group in fit(X, y, group), but  predict() has no parameter group, so where to set qid?

**Comment by guolinke** [comment]
qid is not needed in prediction. LightGBM will predict the relevant score, and you should rank the result by yourself.

**Comment by mlisovyi** [comment]
@guolinke is it possible to elaborate more on this? Shall one make predictions on each group separately? What is the output of the `LGBM.predict()` method? The docs are very short on the subject and examples in the tests and elsewhere address rnker fit, but not prediction

**Comment by guolinke** [comment]
@mlisovyi qid have no effects on ranking predictions in lgb.predict, as the predicted results are the relevant scores. And you can use the relevant scores to get the correct ranking order results by yourself, and qid is needed in this step.

**Comment by guolinke** [comment]
@mlisovyi the same, you can just sort by prediction values.

**Comment by aabelya** [comment]
@guolinke could you please elaborate on how does one convert the result of lgb.predict (_M_ relevant scores) into _M_ x _N_ ranks, i. e. how to sort documents using these scores? Thanks.

**Comment by nonva** [comment]
but, not in same query group, is the scores can be comparable?

**Comment by guolinke** [comment]
@nonva theoretically, they could be comparable.

**Comment by kondo-kk** [comment]
@guolinke Can I put several different qid data together in test data, when lgb.predict()? Shoud I predict by each qid?
