### ISSUE TITLE
"Build Java Wrapper" always failed

### ISSUE THREAD

**Issue by ywskycn** [Microsoft/LightGBM#1399]
Due to runtime env issue, I need to rebuild lib_lightgbm.so and lib_lightgbm_swig.so files. I followed the "Build Java Wrapper" [tutorial](https://github.com/Microsoft/LightGBM/blob/master/docs/Installation-Guide.rst#linux-4), but the build is always failed.

The error messages:
> [ 96%] Building CXX object CMakeFiles/lightgbm.dir/src/treelearner/tree_learner.cpp.o
Linking CXX shared library ../lib_lightgbm.so
[ 96%] Built target _lightgbm
[ 98%] Swig source
**Unable to open file /root/develop/LightGBM/build/swig/lightgbmlibJAVA_wrap.cxx: No such file or directory**
make[2]: *** [swig/lightgbmlibJAVA_wrap.cxx] Error 1
make[1]: *** [CMakeFiles/_lightgbm_swig.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
Linking CXX executable ../lightgbm
[ 98%] Built target lightgbm
make: *** [all] Error 2

The light_lightgbm.so can be generated. The swig version is
> #swig -version
SWIG Version 3.0.12
Compiled with g++ [x86_64-pc-linux-gnu]
Configured options: +pcre

And the gcc version is
>#gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-4)

I'm kind of new to swig. Not sure whether I miss anything there?
@imatiach-msft do you have any idea?

**Comment by imatiach-msft** [comment]
@ywskycn this error seems to be the key reason:
"Unable to open file /root/develop/LightGBM/build/swig/lightgbmlibJAVA_wrap.cxx: No such file or directory"
This file should be generated in the "build/swig" folder by swig.
Do you see any cxx file generated anywhere, and what is the full path to the file?

**Comment by ywskycn** [comment]
@imatiach-msft  thanks for the reply.
SWIG didn't generate .cxx files out...Under the build dir, it only has:
>-rw-r--r-- 1 root root 14224 May 25 05:59 CMakeCache.txt
drwxr-xr-x 8 root root  4096 May 25 06:11 CMakeFiles
-rw-r--r-- 1 root root  4984 May 25 05:57 cmake_install.cmake
drwxr-xr-x 3 root root  4096 May 25 05:59 com
drwxr-xr-x 2 root root  4096 May 25 06:00 java
-rw-r--r-- 1 root root 49145 May 25 05:59 Makefile

Also search the dir, and cannot find the .cxx file. Is there sth I need to do to config SWIG itself?

**Comment by ywskycn** [comment]
Looks like my cmake is too old. Upgrade cmake, and then the files generated.
