### ISSUE TITLE
[Feature] Support for monotonic constraints?

### ISSUE THREAD

**Issue by alexvorobiev** [Microsoft/LightGBM#14]
Are you planning support for monotonic constraints? See e.g. here https://github.com/dmlc/xgboost/issues/1514

**Comment by chivee** [comment]
I'm pasting the snippets for the monotonic constraints here

`IF (split is a continuous variable and monotonic)`

`THEN take average of left and right child nodes if current split is used`

`   IF monotonic increasing THEN CHECK left average <= right average`

`   IF monotonic decreasing THEN CHECK left average >= right average`

@alexvorobiev , do you  have referable papers for this features?

**Comment by alexvorobiev** [comment]
@chivee I only have the reference to the R GBM package https://cran.r-project.org/package=gbm

**Comment by chivee** [comment]
@alexvorobiev , thanks for your sharing. I'm trying to get the idea behind this method.

**Comment by AbdealiJK** [comment]
Note that the given pseudo code only ensures the split to be in the correct order and not the whole model as a later split could lead the model to be non monotonic

**Comment by aldanor** [comment]
Any thoughts on this?

**Comment by mayer79** [comment]
From practical perspective (outside kaggle-world!), this feature would be extremely helpful in many applications where reasonable model behavior is relevant.

**Comment by aldanor** [comment]
@guolinke Would you be able to advise how to approach this and whether it's feasible? I.e., where should it belong, would it be sufficient to implement it just somewhere in `feature_histogram.hpp`? I guess `FeatureMetainfo` could just contain the `-1/0/1` constraint then.

Here's the meat of the implementation in XGBoost, for reference: https://github.com/dmlc/xgboost/blob/master/src/tree/param.h#L422 -- all of it pretty much contained in `CalcSplitGain()`, plus `CalcWeight()`. Where would stuff like this go in LightGBM?

**Comment by guolinke** [comment]
@aldanor 
I don't know the details about the monotonic constraints. 
What is the idea? And why it is needed? 

following may is useful:

The split gain calculation: https://github.com/Microsoft/LightGBM/blob/master/src/treelearner/feature_histogram.hpp#L291-L297 

The leaf-output calculation:
https://github.com/Microsoft/LightGBM/blob/master/src/treelearner/feature_histogram.hpp#L305-L308

**Comment by aldanor** [comment]
> @aldanor
> I don't know the details about the monotonic constraints.
> What is the idea? And why it is needed?

@guolinke Monotonic constraints may be a very important requirement for the resulting models. For many reasons: first, as noted above, there could be domain knowledge that must be respected - e.g., in insurance and risk management problems. Second, you may want to emit a model that's monotonic with respect to certain features so you can infer in a very fast way whether the predicted score improves or not if certain features change but others stay -- this is important for ultra-low latency models, and it's the only reason my team is currently stuck with xgboost :/ 

How about we all cooperate and make this work?

**Comment by guolinke** [comment]
@aldanor very cool, would like to work together with it.

**Comment by guolinke** [comment]
It seems the MC(Monotonic constraints) could be cumulative, that is, if both model A and B is MC, then A+B is MC. 
So we only need to enable MC in decision tree learning. 

combine @chivee  's pseudo code and @AbdealiJK 's suggestion.

I think the algorithm is:

```

min_value = node.min_constraint
max_value = node.max_constraint

check(min_value <= split.left_output) 
check(min_value <= split.right_output)
check(max_value >= split.left_otput)
check(max_value >= split.right_output)
mid = (split.left_output + split.right_output) / 2;

if (split.feature is monotonic increasing) {
  check(split.left_output <= split.right_output)
  node.left_child.set_max_value(mid)
  node.right_child.set_min_value(mid)
}
if (split.feature is monotonic decreasing ) {
  check(split.left_output >= split.right_output)
  node.left_child.set_min_value(mid)
  node.right_child.set_max_value(mid)
}
```

**Comment by guolinke** [comment]
@aldanor would you like to create a PR first ? I can provide my help in the PR.

**Comment by aldanor** [comment]
@guolinke I will give it a try, yep. Your suggested algorithm in the snippet above looks fine, that's kind of what like xgboost does (in exact mode though, not histogram; do you think there would be any complications here because of binning?)

Where would this code belong then, `treelearner/feature_histogram.hpp`? (I still have to read through most of the code)

**Comment by guolinke** [comment]
@alexvorobiev 
The `check` means return gain with `-inf`, as a result, that split will not be chosen. 
I think there is not different for the MC in binned algorithm.

We need to update the calculation of gain: https://github.com/Microsoft/LightGBM/blob/master/src/treelearner/feature_histogram.hpp#L354-L357 and https://github.com/Microsoft/LightGBM/blob/master/src/treelearner/feature_histogram.hpp#L415-L418 .

We may need to wrap these to a new function, and implement both non-constraint and MC for them.

**Comment by guolinke** [comment]
@aldanor any updates ?

**Comment by redditur** [comment]
@guolinke @chivee 

I would also be very interested in seeing this feature implemented in LightGBM. As aldanor stated above the Pseudo-code suggested earlier is correct and is how XGBoost implements monotonic constraints.

As such this feature should be fairly trivial to implement for someone with an intimate knowledge of the codebase.

**Comment by j-mark-hou** [comment]
Hey, so unfortunately I'm not very familiar with the code base and it's been a while since I've written any c++, but here's an attempt:
https://github.com/Microsoft/LightGBM/compare/master...j-mark-hou:add_monotone

I also haven't tested this code so not sure it works.
If this looks logically correct, the next step would be to actually add the monotone_constraint argument into the parameters.  I don't know where I would add that so if there's interest in my putting in a PR i'll need some guidance on how to do that.

**Comment by guolinke** [comment]
@j-mark-hou 
there is one bug in your code, refer to @AbdealiJK `s comment and my algorithm below.

**Comment by j-mark-hou** [comment]
got it, I'll continue waiting for someone with a better understanding of the codebase to take a look then.
