### ISSUE TITLE
[Improvement][Python] support numpy boolean type

### ISSUE THREAD

**Issue by gugatr0n1c** [Microsoft/LightGBM#140]
I was trying to test xboost_dart_mode with some random search by np.random.choice([True, False]) on this parameter, but then I need to convert it with bool().

It would by nice to support/convert np.boolean inside.
Same for 'is_sparse'.

thx

**Comment by guolinke** [comment]
can you try to test it again. I just push a commit

**Comment by wxchan** [comment]
We can make it 'duck type' here. Pseudo code:
```
if val is str: return val
elif val is 1-d iterable: return ','.join(map(str, val))
elif val is numeric: return str(val)
else: raise Exception('Unknown type')
```
[For 1-d iterable](http://stackoverflow.com/questions/1952464/in-python-how-do-i-determine-if-an-object-is-iterable).
[For val is numeric](http://stackoverflow.com/questions/500328/identifying-numeric-and-array-types-in-numpy).

**Comment by guolinke** [comment]
@wxchan I think you can create a new PR for this

**Comment by wxchan** [comment]
@guolinke About sklearn.model_selection.GridSearchCV/RandomizedSearchCV, there are no options to search over dart parameters, should we add other_params to LGBMModel.__init__?

**Comment by guolinke** [comment]
@wxchan maybe use kwargs to replace other_params ?

**Comment by gugatr0n1c** [comment]
thx, now it is working, feel free to close this when you will want to..

**Comment by wxchan** [comment]
@guolinke I tried it, not work. In sklearn, BaseEstimator.get_params use inspect.signature(__init__) to get parameter keys first, so kwargs won't count into parameters.

**Comment by guolinke** [comment]
@wxchan So how do you let ```BaseEstimator.get_params``` get parameters in ```other_params```? Expand them into ```init```?

**Comment by wxchan** [comment]
@guolinke just add them one by one at the end of __init__, for example:

```
def ___init___(..., drop_rate=0.1, skip_drop=0.5)
```

**Comment by guolinke** [comment]
@wxchan I am not sure how it works.
If we set ```self.key=val``` for some parameters not in ```init```, can ```BaseEstimator.get_params``` get these keys?

**Comment by wxchan** [comment]
@guolinke it can't.

**Comment by wxchan** [comment]
@guolinke xgboost uses another method [get_xgb_params](https://github.com/dmlc/xgboost/blob/master/python-package/xgboost/sklearn.py#L175), it won't override get_params, may be better.
