### ISSUE TITLE
huber `alpha` not getting used as expected?

### ISSUE THREAD

**Issue by zkurtz** [Microsoft/LightGBM#1403]
In the following experiment I simulate a small dataset with standard normal variance in the labels except for a single outlier. I then fit with `objective = huber` and two different values of `alpha`. The goal of the experiment is to observe _any_ difference in fitted values based on `alpha`, but I'm not able to get such a difference and the concluding assertion fails. 

```
import lightgbm as lgb
import numpy as np

def lgb_fit(alpha):
    np.random.seed(0)
    ######
    # Data
    n = 100
    x = np.reshape(np.random.normal(loc=0.0, scale=1.0, size=n), (-1, 1))
    y = x[:, 0] + np.random.normal(loc=0.0, scale=1.0, size=n)
    # Create an outlier:
    y[0] = 50
    data = lgb.Dataset(x, y)
    #####
    # Model
    params = {
        'task': 'train',
        'boosting_type': 'gbdt',
        'objective': 'huber',
        'alpha': alpha,
        'feature_fraction': 1,
    }
    bst = lgb.train(params = params,
                    train_set = data,
                    num_boost_round = 2,
                    verbose_eval = False)
    # Return the fitted values
    return bst.predict(x)

x1 = lgb_fit(0.1)
x2 = lgb_fit(1000)

assert sum(np.abs(x1 - x2)) > 0
```

## Environment info
Operating System: OSX 10.13.4
Python version: 3.6.5

**Comment by guolinke** [comment]
@zkurtz 
What is the range of your label ? will it happen to have no effect in huber objective  ?

**Comment by zkurtz** [comment]
@guolinke The data presented above is carefully constructed to ensure (not quite at the level of 'proof') that the Huber objective *should* have an effect. To review the data construction:

```
import lightgbm as lgb
import numpy as np
import pandas as pd

pd.set_option('display.float_format', lambda x: '%.3f' % x)
np.random.seed(0)

n = 100
x = np.reshape(np.random.normal(loc=0.0, scale=1.0, size=n), (-1, 1))
y = x[:, 0] + np.random.normal(loc=0.0, scale=1.0, size=n)
y[0] = 50
>>> pd.Series(y).describe()
...
min      -3.760
25%      -0.981
50%       0.074
75%       1.510
max      50.000
```
So you can see the range of the label above. Maybe even more relevant is the range of the residuals, since [Huber looks at the residuals](https://github.com/Microsoft/LightGBM/blob/dc6995742a5284a1e942978e2542fc49adda9ea1/src/metric/regression_metric.hpp#L181-L186) rather than the raw values: 

```
params = {
    'task': 'train',
    'boosting_type': 'gbdt',
    'objective': 'regression',
    'feature_fraction': 1,
}
bst = lgb.train(params = params,
                train_set = lgb.Dataset(x, y),
                num_boost_round = 2,
                verbose_eval = False)
fitted_values = bst.predict(x)
residuals = fitted_values - y
pd.Series(residuals).describe()
>>> pd.Series(residuals).describe()
...
min     -48.814
25%      -0.601
50%       0.508
75%       1.518
max       3.962
```
These are the regression (l2) residuals, and you can see that they are generally greater than 0.1 (and very unbalanced, due to the outlier -48), so Huber should have an effect with `alpha = 0.1`. On the other hand, all of the residuals are far less than 1000, so Huber should have no effect with `alpha = 1000`. That is why I'm surprised that the predictions for these two choices of `alpha` are the same.

**Comment by guolinke** [comment]
@zkurtz can you try `reg_sqrt=false` ?

**Comment by zkurtz** [comment]
That triggers
```
[LightGBM] [Fatal] Check failed: alpha > 0 && alpha < 1 at /private/var/folders/5z/v7h2glds0cg094cc4g1czlts740knq/T/pip-install-utxzyugy/lightgbm/compile/src/io/config.cpp, line 329 .
```
I don't understand why this made a difference, since `reg_sqrt` is supposedly `false` by default, but it looks like the problem could be stemming from the fact that `alpha` is being used for two different objectives. The error appears to [get triggered in RegressionQuantileLoss](https://github.com/Microsoft/LightGBM/blob/f660b5fe4148fc3f5985b10c1fea969b695cb8de/src/objective/regression_objective.hpp#L454-L457) , and probably this is the same issue underlying #1321 (why was that closed?). 

Feature request/proposal: decouple Huber loss from quantile loss by introducing a new `huber_alpha` parameter which should only be restricted to (0, infinity).

**Comment by mayer79** [comment]
@zkurtz: The specific implementation needs some clarification. My very unqualified guess is that alpha represents the proportion of observations outside the quadratic window, unlike the default parametrization of Huber loss.

**Comment by zkurtz** [comment]
@mayer79 The specific implementation looks like a straightforward thresholding to me: https://github.com/Microsoft/LightGBM/blob/dc6995742a5284a1e942978e2542fc49adda9ea1/src/metric/regression_metric.hpp#L181-L186

**Comment by guolinke** [comment]
@zkurtz It is not possible to call quantile objective when set `objective=huber`. I think it is possible that your package is corrupted. 

And I just run your code in the latest branch, and seems everything is okay:

![image](https://user-images.githubusercontent.com/16040950/40785548-53f6bdba-651b-11e8-8ec0-8e6ccf5f900e.png)

**Comment by zkurtz** [comment]
Ugh ... sorry for all the fuss -- I'll upgrade now.

**Comment by zkurtz** [comment]
Oddly related: https://stackoverflow.com/questions/51233684/trouble-installing-basic-lightgbm-under-miniconda-mac

**Comment by Laurae2** [comment]
@zkurtz on the last link:

> Page Not Found
> This question was voluntarily removed by its author.

**Comment by zkurtz** [comment]
@Laurae2 sorry I forgot I had linked to it when I deleted it. The link should now work. I'm still investigating and was hoping to post a more intelligent version of the question, but haven't really gotten much further.

**Comment by zkurtz** [comment]
@Laurae2 nevermind about that link (I'm removing it again). The last thing I've done is a very straightforward install directly from github and re-tried my script at the beginning of this this thread. I now fails even sooner than before:

```
>>> x2 = lgb_fit(1000)
[LightGBM] [Fatal] Check failed: alpha <1.0 at /Users/me/Applications/LightGBM/python-package/compile/src/io/config_auto.cpp, line 449 .
```

**Comment by guolinke** [comment]
sorry, just fix it in the latest commit.
