### ISSUE TITLE
Nuget package for dotnet Core 2.0

### ISSUE THREAD

**Issue by tarashypka** [Microsoft/LightGBM#1405]
There is a [nuget](https://www.nuget.org/packages/LightGBM/) package and some nice wrappers (like [LightGBMSharp](https://github.com/ttustonic/LightGBMSharp)) for LightGBM built with .NET Framework as target framework. 

We can't use it because are restricted to dotnet Core 2.0 framework. 

Given the results and compared to other models we've tried, LightGBM shows the best. 

Is there a hope to find in some future a nuget package of LightGBM for dotnet Core 2.0?

**Comment by guolinke** [comment]
refer to https://github.com/dotnet/machinelearning/pull/392 
LightGBM will be in ML.Net soon.

**Comment by StrikerRUS** [comment]
@guolinke Can we close this issue, since LightGBM is in ML.NET now?
