### ISSUE TITLE
Can LightGBM run in batch as the dataset is big?

### ISSUE THREAD

**Issue by rosefun** [Microsoft/LightGBM#1406]
As my laptop's RAM is only 8G, my dataset has about 400M. But when I use lgb to run the program,my laptop crashes.

So can I use lgb to run the dataset in batch? If can,how?

Hopefully for help.

**Comment by guolinke** [comment]
in CLI version, you can try parameter `two_round=true`

**Comment by rosefun** [comment]
Thanks！
