### ISSUE TITLE
Can't install R-package on macOS

### ISSUE THREAD

**Issue by toshi71** [Microsoft/LightGBM#1407]
I tried to install R-package on my mac according to the installation guide below.

```
git clone --recursive https://github.com/Microsoft/LightGBM
cd LightGBM/R-package
Rscript build_package.R
export CXX=g++-7 CC=gcc-7  # for macOS (replace 7 with version of gcc installed on your machine)
R CMD INSTALL lightgbm_2.1.0.tar.gz --no-multiarch
```
(on https://github.com/Microsoft/LightGBM/tree/master/R-package)

However I couldn't install it. Please tell me how should I do.

## Environment info
OS: macOS High Sierra 10.13.4
R version 3.5.0 (2018-04-23) -- "Joy in Playing"

## Error Message:
```
$ Rscript build_package.R
Error: Cannot find folder LightGBM/include
In addition: Warning message:
In file.copy("./../include", "./src/", overwrite = TRUE, recursive = TRUE) :
  'recursive' will be ignored as 'to' is not a single existing directory
Execution halted
```

**Comment by guolinke** [comment]
you can try: 
```
rm -rf LightGBM
git clone --recursive https://github.com/Microsoft/LightGBM
cd LightGBM/R-package
export CXX=g++-7 CC=gcc-7  # for macOS (replace 7 with version of gcc installed on your machine)
R CMD INSTALL --build . --no-multiarch
```

BTW, did you install gcc-7, or it is gcc-8?

**Comment by toshi71** [comment]
@guolinke 
Thanks for your advice.
I tried the commands you showed above, but after the last command, an error occurred.
```
$ R CMD INSTALL --build . --no-multiarch
Warning: invalid package '.'
Error: ERROR: no packages specified
```

I installed gcc-8 via homebrew, so I did `export CXX=g++-8 CC=gcc-8`.

**Comment by guolinke** [comment]
@toshi71 are you in the right path of LightGBM/R-package ?

**Comment by toshi71** [comment]
@guolinke 
Yes. Current directory is `~/LightGBM/R-package`.
```
$ cd
$ pwd
/Users/toshi
$ rm -rf LightGBM
$ git clone --recursive https://github.com/Microsoft/LightGBM
Cloning into 'LightGBM'...
remote: Counting objects: 10283, done.
remote: Compressing objects: 100% (97/97), done.
remote: Total 10283 (delta 45), reused 64 (delta 31), pack-reused 10153
Receiving objects: 100% (10283/10283), 8.00 MiB | 2.74 MiB/s, done.
Resolving deltas: 100% (7224/7224), done.
Submodule 'include/boost/compute' (https://github.com/boostorg/compute) registered for path 'compute'
Cloning into '/Users/toshi/LightGBM/compute'...
remote: Counting objects: 21447, done.
remote: Total 21447 (delta 0), reused 0 (delta 0), pack-reused 21447
Receiving objects: 100% (21447/21447), 8.44 MiB | 1.76 MiB/s, done.
Resolving deltas: 100% (17397/17397), done.
Submodule path 'compute': checked out '6de7f6448796f67958dde8de4569fb1ae649ee91'
$ cd LightGBM/R-package
$ export CXX=g++-8 CC=gcc-8
$ pwd
/Users/toshi/LightGBM/R-package
$ R CMD INSTALL --build . --no-multiarch
Warning: invalid package '.'
Error: ERROR: no packages specified
```

**Comment by mayer79** [comment]
What happens if you use "R CMD INSTALL lightgbm_2.1.1.tar.gz --no-multiarch" in last command?

**Comment by toshi71** [comment]
@mayer79 
Thanks for your advice.
The same error has occurred.
```
$ cd LightGBM/R-package
$ export CXX=g++-8 CC=gcc-8
$ pwd
/Users/toshi/LightGBM/R-package
$ R CMD INSTALL lightgbm_2.1.1.tar.gz --no-multiarch
Warning: invalid package 'lightgbm_2.1.1.tar.gz'
Error: ERROR: no packages specified
```

**Comment by toshi71** [comment]
And I tried the commands below on RStudio.
```
> library(devtools)
> install_github("Microsoft/LightGBM", subdir = "R-package")
```
An error has occurred as below.
```
> install_github("Microsoft/LightGBM", subdir = "R-package")
Downloading GitHub repo Microsoft/LightGBM@master
from URL https://api.github.com/repos/Microsoft/LightGBM/zipball/master
Installing lightgbm
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/5n/8jscplj12gg0b6_p9h_rqcmc0000gn/T/RtmpeMswpW/devtools5cb3be93b14/Microsoft-LightGBM-713f5e6/R-package'  \
  --library='/Library/Frameworks/R.framework/Versions/3.5/Resources/library' --install-tests 

* installing *source* package ‘lightgbm’ ...
** libs
installing via 'install.libs.R' to /Library/Frameworks/R.framework/Versions/3.5/Resources/library/lightgbm
-- The C compiler identification is AppleClang 9.1.0.9020039
-- The CXX compiler identification is AppleClang 9.1.0.9020039
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:27 (message):
  AppleClang wasn't supported.  Please see
  https://github.com/Microsoft/LightGBM/blob/master/docs/Installation-Guide.rst#macos


-- Configuring incomplete, errors occurred!
See also "/private/var/folders/5n/8jscplj12gg0b6_p9h_rqcmc0000gn/T/RtmpeMswpW/devtools5cb3be93b14/Microsoft-LightGBM-713f5e6/R-package/src/build/CMakeFiles/CMakeOutput.log".
make: *** No rule to make target `_lightgbm'.  Stop.
Error in eval(ei, envir) : Cannot find lib_lightgbm.so
* removing ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/lightgbm’
Installation failed: Command failed (1)
Warning message:
GitHub repo contains submodules, may not function as expected! 
```
I need to change devtools' compiler setting? How can I do that?
```
$ cat working_directory_of_R/.R/Makevars
CC=/usr/local/opt/gcc@8/bin/gcc-8
CXX=/usr/local/opt/gcc@8/bin/g++-8
SHLIB_OPENMP_CFLAGS = -fopenmp
SHLIB_OPENMP_CXXFLAGS = -fopenmp
SHLIB_OPENMP_FCFLAGS = -fopenmp
SHLIB_OPENMP_FFLAGS = -fopenmp
```

**Comment by Laurae2** [comment]
Try the following:

```sh
git clone --recursive https://github.com/Microsoft/LightGBM
cd LightGBM
cd R-package
```

Then in src/install.libs.R, replace cmake_cmd content line 50 by `"cmake -DCMAKE_C_COMPILER=/usr/local/opt/gcc@8/bin/gcc-8 -DCMAKE_CXX_COMPILER=/usr/local/opt/gcc@8/bin/g++-8 "` (one space before quote end)

Then compile LightGBM:

```
R CMD INSTALL --build . --no-multiarch
```

**Comment by guolinke** [comment]
@toshi71 is your problem solved ?

**Comment by toshi71** [comment]
@Laurae2 @guolinke 
Sorry for replying so late and thanks for your advices.
As @Laurae2 advised, I tried to replace src/install.libs.R cmake_cmd content, and then do `R CMD INSTALL --build . --no-multiarch`, but the result was same.
The error message was as below.
```
Warning: invalid package '.'
Error: ERROR: no packages specified
```

**Comment by jameslamb** [comment]
@guolinke I can look at this this weekend, see if I can help

**Comment by Laurae2** [comment]
@toshi71 Are you running the command from the R-package path? The error you show is exactly the error when using the wrong path.

**Comment by jameslamb** [comment]
sorry for the delayed response from me. I agree, this looks like the error that shows up when the wrong path is used.

Maybe we need to make the install instructions clearer (like using an env variable for `$LIGHTGBM_REPO_ROOT` or something

**Comment by jameslamb** [comment]
PR coming tomorrow! I've moved some stuff out of `install.libs.R` so it isn't as sensitive to where you run from. Will update this issue when the PR goes up.

**Comment by toshi71** [comment]
I finally successed to install lightgbm package.
Thanks everyone.
(However I can't install it via terminal. The same error above occurs...)

on terminal
```
$ brew install libomp
```
on RStudio
```
> library("devtools")
> install_github("Microsoft/LightGBM", subdir = "R-package")
```

**Comment by liwen611** [comment]
> you can try:
> 
> ```
> rm -rf LightGBM
> git clone --recursive https://github.com/Microsoft/LightGBM
> cd LightGBM/R-package
> export CXX=g++-7 CC=gcc-7  # for macOS (replace 7 with version of gcc installed on your machine)
> R CMD INSTALL --build . --no-multiarch
> ```
> BTW, did you install gcc-7, or it is gcc-8?

HI I did the same thing, but instead I got this:
* installing to library ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library’
* installing *source* package ‘lightgbm’ ...
** libs
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c R_init.c -o R_init.o
In file included from R_init.c:4:
/Library/Frameworks/R.framework/Resources/include/R.h:55:11: fatal error:
      'stdlib.h' file not found
# include <stdlib.h> /* Not used by R itself, but widely assumed in packages */
          ^~~~~~~~~~
1 error generated.
make: *** [R_init.o] Error 1
ERROR: compilation failed for package ‘lightgbm’
* removing ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/lightgbm’

**Comment by jameslamb** [comment]
@liwen611 did you recently upgrade your operating system on your Mac? I did and couldn't build any R packages (because of these common headers not being found).

Often it's fixed by running

```
 xcode-select --install
```

But for me I had to also run

```
open /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg
```
