### ISSUE TITLE
Windows Install LightGBM

### ISSUE THREAD

**Issue by HuangZhanPeng** [Microsoft/LightGBM#141]
I follow the guide to install LightGBM in windows, when I execute 
>python setup.py install

`
it raises error
error: Error: setup script specifies an absolute path:

C:\Users\Ryan\LightGBM-master\python-package\lightgbm\..\..\windows\x64\Dll\lib_lightgbm.dll

setup() arguments must *always* be /-separated paths relative to the
setup.py directory, *never* absolute paths.
`

I have no idea to solve the problem

###  Solution

1. Delete the line contains the codes: 

    `include_package_data=True`

2. Replace 

    `LIB_PATH = libpath['find_lib_path']()`

    to

    `LIB_PATH = ['../windows/x64/Dll/lib_lightgbm.dll']`

For more detail, access the following links:

[pip install Error: setup script specifies an absolute path](http://stackoverflow.com/questions/18085571/pip-install-error-setup-script-specifies-an-absolute-path)

[[bug] installation of python package fails with python 3.5.2 ](https://github.com/Microsoft/LightGBM/issues/135)

**Comment by wxchan** [comment]
check #135

**Comment by guolinke** [comment]
@wxchan  I think you can add this to document

**Comment by wxchan** [comment]
@guolinke I will. I think it probably can be solved. I am not very familiar with this part. 

[Same issue in xgboost](https://github.com/dmlc/xgboost/issues/1846).

**Comment by HuangZhanPeng** [comment]
I have done the same thing 

LIB_PATH = libpath['find_lib_path']()
to
LIB_PATH = libpath['../windows/x64/Dll/lib_lightgbm.dll']

but it raise another error

Traceback (most recent call last):
  File "setup.py", line 18, in <module>
    LIB_PATH = libpath['/windows/x64/Dll/lib_lightgbm.dll']
KeyError: '../windows/x64/Dll/lib_lightgbm.dll'

**Comment by guolinke** [comment]
@HuangZhanPeng , ```libpath``` is a List, you cannot use ```str``` to index it.

**Comment by HuangZhanPeng** [comment]
Thank you very much, Actually I just make a mistake, when I modify LIB_PATH = ['../windows/x64/Dll/lib_lightgbm.dll'], everything is Ok @guolinke @wxchan

**Comment by ostrokach** [comment]
I was running into this error on Linux running Anaconda 3.5 as well.

I fixed it using the following patch to setup.py (same as the patch for xgboost dmlc/xgboost#1846).

```
diff --git a/python-package/setup.py b/python-package/setup.py
index dfed9ae..46fc5a3 100644
--- a/python-package/setup.py
+++ b/python-package/setup.py
@@ -8,13 +8,14 @@ from setuptools import setup, find_packages
 
 sys.path.insert(0, '.')
 
-CURRENT_DIR = os.path.dirname(__file__)
+CURRENT_DIR = os.path.abspath(os.path.dirname(__file__))
 
 libpath_py = os.path.join(CURRENT_DIR, 'lightgbm/libpath.py')
 libpath = {'__file__': libpath_py}
 exec(compile(open(libpath_py, "rb").read(), libpath_py, 'exec'), libpath, libpath)
 
 LIB_PATH = libpath['find_lib_path']()
+LIB_PATH = [os.path.relpath(LIB_PATH[0], CURRENT_DIR)]
 print("Install lib_lightgbm from: %s" % LIB_PATH)
```

**Comment by wxchan** [comment]
@ostrokach this solution does not work for me. I think the bug is caused by `packages=find_packages()` not LIB_PATH.
