### ISSUE TITLE
"Unknown parameter: device" warning when using sklearn wrapper with gpu support

### ISSUE THREAD

**Issue by chencjGene** [Microsoft/LightGBM#1412]
params 
{"n_estimators": 50, "max_depth": 5,
             "objective": "multiclass",
             "verbose": -1, "n_jobs": -1, 
             "learning_rate": 0.1,
              "device": "gpu", 
              "num_class": 6
}

**Comment by StrikerRUS** [comment]
@chencjGene what is the version of LightGBM?

You can get it by
```
import lightgbm as lgb

lgb.__version__
```

**Comment by chencjGene** [comment]
My lightgbm version is 2.1.1. This warning does not show up in 2.1.0 version

**Comment by StrikerRUS** [comment]
Does it work despite warning?

**Comment by guolinke** [comment]
@StrikerRUS I think we forget the alias of `device` in the new version, it is `device_type` now.

**Comment by chencjGene** [comment]
@StrikerRUS It seems work. @guolinke Thanks for informing.

**Comment by StrikerRUS** [comment]
@guolinke Yeah! The alias was lost, but `device` is still using here:
https://github.com/Microsoft/LightGBM/blob/a39c848e6456d473d2043dff3f5159945a36b567/src/io/config.cpp#L123

**Comment by StrikerRUS** [comment]
Seems that auto-closing mechanism of GitHub is broken...
