### ISSUE TITLE
Multi-Layered Gradient Boosting Decision Trees

### ISSUE THREAD

**Issue by guolinke** [microsoft/LightGBM#1423]
Paper link: https://arxiv.org/pdf/1806.00007.pdf   @kingfengji

It is interesting to see how it work. 
Contribution is welcomed.

**Comment by kingfengji** [comment]
@guolinke 
Thanks for inviting.  it's a multi-layered structure explicitly build for representation learning purposes using gbdt instead of neurons.
Questions are welcomed.

**Comment by StrikerRUS** [comment]
Closed in favor of being in #2302. We decided to keep all feature requests in one place.

Welcome to contribute this feature! Please re-open this issue (or post a comment if you are not a topic starter) if you are actively working on implementing this feature.

**Comment by kruda** [comment]
I'd like to work on this issue.

**Comment by jameslamb** [comment]
Thanks @kruda ! I'll re-open it and assign it to you. Leave a comment here if you have any questions.

**Comment by StrikerRUS** [comment]
Refer to https://github.com/microsoft/LightGBM/issues/1315#issuecomment-592963235.
