### ISSUE TITLE
Incremental learning using Dataset.subset LightGBM 2.1.1 python API

### ISSUE THREAD

**Issue by goraj** [Microsoft/LightGBM#1439]
It seems that using lightgbm.Dataset.subset for iterative training does not work even with Datasets created with _free_raw_data=False_

## Error Message:

> LightGBMError: Cannot set predictor after freed raw data, set free_raw_data=False when construct Dataset to avoid 

## Reproducible examples
[https://gist.github.com/goraj/6df8f22a49534e042804a299d81bf2d6](https://gist.github.com/goraj/6df8f22a49534e042804a299d81bf2d6)

**Comment by guolinke** [comment]
@goraj sorry, `free_raw_data` doesn't work for subset. 
in your case, you should use `indices` on `X_train` and `y_train` first, then construct dataset from that as a subset.

**Comment by goraj** [comment]
Alright. Thank you @guolinke. 
For what application was _keep_training_booster_ originally implemented? Performance seems to be rather poor compared to retraining on the whole dataset. Is anyone using this to address data with concept drift or large datasets sucessfully?

**Comment by guolinke** [comment]
@goraj 
keep_training_booster can be used for parameters changes during training, without changing dataset.

**Comment by guolinke** [comment]
close now. feel free to reopen if there still is a problem.
