### ISSUE TITLE
[Improvement] Support nthread in predict()

### ISSUE THREAD

**Issue by gugatr0n1c** [Microsoft/LightGBM#144]
Seems to me that when calling model.predict() it is using only one cpu. It would be great to support nthread also in predict().
I think predict() is only additive calculation and each tree can be evaluate in separate cpu, then it is only weighted sum of local predictions. Parallelization on trees can be also effective. What do you think?

Also, not sure how the residuals in DART are calculated, but this can speed it up as well?

**Comment by guolinke** [comment]
I think the predict is always multi-threading now.
I will check why python-package only use one cpu.

**Comment by gugatr0n1c** [comment]
Seems to be working on linux, but not on win10 server

**Comment by guolinke** [comment]
can you try the quick fix i commit just now?

**Comment by gugatr0n1c** [comment]
seems to be working, much faster now, thx

Just from curiosity how is multi-threading supported here? all cpu working on one trees or one cpu working on tree?

**Comment by guolinke** [comment]
@gugatr0n1c 
the multi-threading is for samples. 
if using multi-threading for trees, it will have lots of cost of create/delete threads.

**Comment by gugatr0n1c** [comment]
@guolinke thx
feel free to close this issue, when you wanted to

**Comment by gugatr0n1c** [comment]
@guolinke so, the expectation is to predict more then one sample (at least num_sample_to_predict >= nthreads) this is reasonble...

Just maybe for tasks where you can predict only one sample (some financial trading) may be other parallelization better... 

thx for info..

**Comment by guolinke** [comment]
@gugatr0n1c I think predict only for one sample is not the common case. 
close for now.
