### ISSUE TITLE
[R-package] Ability to control the printed messages?

### ISSUE THREAD

**Issue by Laurae2** [microsoft/LightGBM#1440]
Currently, LightGBM is not using the R printf message, leading to bypassing any sink (see #513).

An alternative, without losing performance on metric computation, is to return to R the metric values required and have a callback to print the messages.

Currently, we can log the printed messages by using the metric callback. But that's not the best scenario unfortunately (performance wise, especially on large datasets).

Taking 100M observations, training a model and computing AUC on my machine for 10 iterations:

* Using LightGBM metric: 628 seconds
* Using optimized R metric: 1159 seconds (optimized R AUC metric has around/less than 2M/s observation throughput, see https://github.com/Laurae2/R_benchmarking#area-under-the-curve-roc-benchmarks)

It would be beneficial for logging the performance of the model throughout the training to a file. Such case would be very useful, especially in RStudio Server: if a user is disconnected (for any reason) from the R session, he/she would not be able to get back on RStudio Server until LightGBM finishes training (logging performance would be a great addition).

**Comment by guolinke** [comment]
@Laurae2 
Maybe "redirect" can solve your problem ? 
https://stackoverflow.com/questions/6674327/redirect-all-output-to-file

**Comment by guolinke** [comment]
@Laurae2 any response ?

**Comment by Laurae2** [comment]
Redirecting this way is not possible when the session creation is not controlled by the user (same issue with any server spawning R sessions).

**Comment by guolinke** [comment]
@Laurae2 got it. However, this require to rewrite the R package, more specifically, the dynamic library used by R. 
Maybe the better solution is using some third-party high-performance metric evaluation packages.

**Comment by StrikerRUS** [comment]
Closed in favor of being in #2302. We decided to keep all feature requests in one place.

Welcome to contribute this feature! Please re-open this issue (or post a comment if you are not a topic starter) if you are actively working on implementing this feature.

**Comment by jameslamb** [comment]
Reopening this one since we have an active PR (#2901) for it
