### ISSUE TITLE
Get number of leaves/depth of a trained model

### ISSUE THREAD

**Issue by MingRuey** [Microsoft/LightGBM#1442]
I've trained a gbdt model  in python 3.5 by grid searching the best parameters, saved the model but somehow lost the info.  

By looking the [python API](http://lightgbm.readthedocs.io/en/latest/Python-API.html#) and the related source code, I can not find a simple way to get some model info like depth and number of leaves. 

I can think of two possible ways:
(1) Use Booster.get_leaf_output() to test every possible indices
(2) Analyze the graph representation of the tree

Are there better ways to do this?

**Comment by guolinke** [comment]
You can use the latest code, which will save the parameters used in training to the end of the model file.
