### ISSUE TITLE
Race condition in Dense4bitsBin::Push

### ISSUE THREAD

**Issue by tt83** [Microsoft/LightGBM#1446]
https://github.com/Microsoft/LightGBM/blob/92a45bebc321a822136ab99838c6817487cfb661/src/io/dense_nbits_bin.hpp#L50
```
if (buf_.empty()) {
      #pragma omp critical
      {
        if (buf_.empty()) {
          int len = (num_data_ + 1) / 2;
          buf_ = std::vector<uint8_t>(len, static_cast<uint8_t>(0));
        }
      }
}

```
The buf_ variable is concurrently read and written by multiple threads.

**Comment by guolinke** [comment]
Thus, there is a “omp critical”.

**Comment by tt83** [comment]
No, first condition is not in critical clause.

**Comment by guolinke** [comment]
The buf.empty()? It is a checking by read, and there is another check in the critical region

**Comment by tt83** [comment]
> The buf.empty()? It is a checking by read, and there is another check in the critical region. Thus, only one thread has chance to allocate buf_.

While one thread is allocating the buf_ another threads are trying to read the buf_ at the same time. These operations are not atomic and lead to UB.

**Comment by guolinke** [comment]
yeah, but it will not affect the allocating of another thread. 
And that thread will step into the critical region then, but at that time, the allocating is finished (otherwise the thread cannot step in). 
Is there any problem ?

**Comment by tt83** [comment]
> While one thread is allocating the buf_ another threads are trying to read the buf_ at the same time.

This is already undefined behaviour. It does not matter what happens after.
While the buf_ is in the middle of allocating process it cannot be accessed from another thread even for reading, but this happens here.

**Comment by guolinke** [comment]
yeah, it is undefined, but I think most compilers can handle that.
Current implementation was tested by windows/unix/osx about one year and without reporting error happening there.

However, this allocation could be put into Constructor and then avoid this potential issue. 
Welcome to create a PR to fix it : ) .

**Comment by tt83** [comment]
> yeah, it is undefined, but I think most compilers can handle that.
> Current implementation was tested by windows/unix/osx about one year and without reporting error happening there.

No, this bug causes segmentation faults. That's why I found it)
But this error does not appear on every start. It has happened several times over many starts.

Fast fix is to remove first condition before the critical section.

**Comment by guolinke** [comment]
I think the problem is caused by the assigning. 
can you try to change `buf_ = std::vector<uint8_t>(len, static_cast<uint8_t>(0));` to `buf_.risize(len, static_cast<uint8_t>(0));` ?

**Comment by tt83** [comment]
> Put it into constructor is more efficient.

For sure and it's more clean way. But be aware that Resize function or maybe other stuff can modify num_data_ member and hence the buf_ has to be resized accordingly..

> I think the problem is caused by the assigning.
> can you try to change buf_ = std::vector<uint8_t>(len, static_cast<uint8_t>(0)); to buf_.risize(len, static_cast<uint8_t>(0)); ?

I don't think this resolves the issue because it does not eliminate concurrent read-write access to the buf_(more precisely its size) from multiple threads. This can work if these operations are atomic, but there is no guaranty. And it's not so easy to check as the error occurs too rarely. I vote for your first solution.
