### ISSUE TITLE
data_parallel_tree_learner fails to build

### ISSUE THREAD

**Issue by talfirevic** [Microsoft/LightGBM#1454]
## Environment info
Operating System: Windows 10
CPU: Intel i5 6600k
C++/Python/R version: mingw-w64/x86_64-8.1.0, python2.7
Boost version: 1.67
Cmake: 3.11.3
commit: 3f401477872813a81ca98e90b9b42d085b1013d2

## Error Message:
Scanning dependencies of target lightgbm
[  1%] Building CXX object CMakeFiles/lightgbm.dir/src/main.cpp.obj
[  3%] Building CXX object CMakeFiles/lightgbm.dir/src/application/application.cpp.obj
[  4%] Building CXX object CMakeFiles/lightgbm.dir/src/boosting/boosting.cpp.obj
[  6%] Building CXX object CMakeFiles/lightgbm.dir/src/boosting/gbdt.cpp.obj
[  7%] Building CXX object CMakeFiles/lightgbm.dir/src/boosting/gbdt_model_text.cpp.obj
[  9%] Building CXX object CMakeFiles/lightgbm.dir/src/boosting/gbdt_prediction.cpp.obj
[ 11%] Building CXX object CMakeFiles/lightgbm.dir/src/boosting/prediction_early_stop.cpp.obj
[ 12%] Building CXX object CMakeFiles/lightgbm.dir/src/io/bin.cpp.obj
[ 14%] Building CXX object CMakeFiles/lightgbm.dir/src/io/config.cpp.obj
[ 15%] Building CXX object CMakeFiles/lightgbm.dir/src/io/config_auto.cpp.obj
[ 17%] Building CXX object CMakeFiles/lightgbm.dir/src/io/dataset.cpp.obj
[ 19%] Building CXX object CMakeFiles/lightgbm.dir/src/io/dataset_loader.cpp.obj
[ 20%] Building CXX object CMakeFiles/lightgbm.dir/src/io/file_io.cpp.obj
[ 22%] Building CXX object CMakeFiles/lightgbm.dir/src/io/json11.cpp.obj
[ 23%] Building CXX object CMakeFiles/lightgbm.dir/src/io/metadata.cpp.obj
[ 25%] Building CXX object CMakeFiles/lightgbm.dir/src/io/parser.cpp.obj
[ 26%] Building CXX object CMakeFiles/lightgbm.dir/src/io/tree.cpp.obj
[ 28%] Building CXX object CMakeFiles/lightgbm.dir/src/metric/dcg_calculator.cpp.obj
[ 30%] Building CXX object CMakeFiles/lightgbm.dir/src/metric/metric.cpp.obj
[ 31%] Building CXX object CMakeFiles/lightgbm.dir/src/objective/objective_function.cpp.obj
[ 33%] Building CXX object CMakeFiles/lightgbm.dir/src/network/linker_topo.cpp.obj
[ 34%] Building CXX object CMakeFiles/lightgbm.dir/src/network/linkers_mpi.cpp.obj
[ 36%] Building CXX object CMakeFiles/lightgbm.dir/src/network/linkers_socket.cpp.obj
[ 38%] Building CXX object CMakeFiles/lightgbm.dir/src/network/network.cpp.obj
[ 39%] Building CXX object CMakeFiles/lightgbm.dir/src/treelearner/data_parallel_tree_learner.cpp.obj

In file included from C:/local/boost-build/include/boost/mpl/aux_/na_assert.hpp:23,
                 from C:/local/boost-build/include/boost/mpl/arg.hpp:25,
                 from C:/local/boost-build/include/boost/mpl/placeholders.hpp:24,
                 from C:/local/boost-build/include/boost/iterator/iterator_categories.hpp:16,
                 from C:/local/boost-build/include/boost/iterator/iterator_adaptor.hpp:12,
                 from C:/local/boost-build/include/boost/iterator/transform_iterator.hpp:11,
                 from C:/local/boost-build/include/boost/algorithm/string/iter_find.hpp:17,
                 from C:/local/boost-build/include/boost/algorithm/string/split.hpp:16,
                 from D:/Code/lightgbm/compute/include/boost/compute/device.hpp:18,
                 from D:/Code/lightgbm/compute/include/boost/compute/context.hpp:19,
                 from D:/Code/lightgbm/compute/include/boost/compute/buffer.hpp:15,
                 from D:/Code/lightgbm/compute/include/boost/compute/core.hpp:18,
                 from D:\Code\lightgbm\src\treelearner\gpu_tree_learner.h:27,
                 from D:\Code\lightgbm\src\treelearner\parallel_tree_learner.h:8,
                 from D:\Code\lightgbm\src\treelearner\data_parallel_tree_learner.cpp:1:
C:/local/boost-build/include/boost/mpl/assert.hpp:188:21: warning: unnecessary parentheses in declaration of 'assert_arg' [-Wparentheses]
 failed ************ (Pred::************
                     ^
C:/local/boost-build/include/boost/mpl/assert.hpp:193:21: warning: unnecessary parentheses in declaration of 'assert_not_arg' [-Wparentheses]
 failed ************ (boost::mpl::not_<Pred>::************
                     ^
In file included from D:/Code/lightgbm/compute/include/boost/compute/detail/meta_kernel.hpp:37,
                 from D:/Code/lightgbm/compute/include/boost/compute/iterator/buffer_iterator.hpp:26,
                 from D:/Code/lightgbm/compute/include/boost/compute/algorithm/detail/copy_on_device.hpp:18,
                 from D:/Code/lightgbm/compute/include/boost/compute/algorithm/copy.hpp:26,
                 from D:/Code/lightgbm/compute/include/boost/compute/container/vector.hpp:32,
                 from D:\Code\lightgbm\src\treelearner\gpu_tree_learner.h:28,
                 from D:\Code\lightgbm\src\treelearner\parallel_tree_learner.h:8,
                 from D:\Code\lightgbm\src\treelearner\data_parallel_tree_learner.cpp:1:
D:/Code/lightgbm/compute/include/boost/compute/memory/svm_ptr.hpp: In member function 'boost::compute::context& boost::compute::svm_ptr<T>::get_context() const':
D:/Code/lightgbm/compute/include/boost/compute/memory/svm_ptr.hpp:131:16: error: binding reference of type 'boost::compute::context&' to 'const boost::compute::context' discards qualifiers
         return m_context;
                ^~~~~~~~~
mingw32-make[2]: *** [CMakeFiles\lightgbm.dir\build.make:399: CMakeFiles/lightgbm.dir/src/treelearner/data_parallel_tree_learner.cpp.obj] Error 1
mingw32-make[1]: *** [CMakeFiles\Makefile2:67: CMakeFiles/lightgbm.dir/all] Error 2
mingw32-make: *** [Makefile:129: all] Error 2

**Comment by guolinke** [comment]
@StrikerRUS it seems the reason is the update of compute library.

**Comment by guolinke** [comment]
@talfirevic Which commit version you used?

**Comment by talfirevic** [comment]
@guolinke I've just cloned master branch 2 hours ago. So I'm using 3f401477872813a81ca98e90b9b42d085b1013d2

**Comment by StrikerRUS** [comment]
@talfirevic Could you please try to build this commit?
34a643f67527b742ce9084de7616301a82ff890e

**Comment by StrikerRUS** [comment]
Also ping @huanzhang12

**Comment by huanzhang12** [comment]
It seems to be a Boost.Compute and compiler version problem. @talfirevic Are you using gcc 8.1.0? Seems related to this issue:
https://github.com/boostorg/compute/issues/778

**Comment by huanzhang12** [comment]
@StrikerRUS We need the develop branch of Boost.Compute to fix this problem. Can you update the submodule and see if it passes the tests?

https://github.com/boostorg/compute/tree/develop

**Comment by talfirevic** [comment]
@StrikerRUS 34a643f67527b742ce9084de7616301a82ff890e did not help, unfortunately.

**Comment by talfirevic** [comment]
@huanzhang12 yes, gcc is 8.1.0 version. Should I try compiling latest develop branch of boost and try the process again?

**Comment by StrikerRUS** [comment]
@huanzhang12 Tests passed!
Is it gcc 8.1 version specific problem and it was the reason why we didn't catch the problem at CI?

**Comment by huanzhang12** [comment]
@StrikerRUS yes, I believe this problem is specific to gcc 8.1.0
