### ISSUE TITLE
importing difficulties with newly complied python module

### ISSUE THREAD

**Issue by Diyago** [Microsoft/LightGBM#1458]
Sorry for dummy question. But how to import  compiled version instead of anaconda version?
Simple adding path to repo to global variables didnt help

## Environment info
Operating System: Windows 10 x64
CPU: amd ryzen 2700
Python: 3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)]
Cmake 3.12.0
miniqw 8.1.0
cuda 9.2.88
gtx 1070ti

## Error Message:
LightGBMError: b'GPU Tree Learner was not enabled in this build. Recompile with CMake option -DUSE_GPU=1'
-- wrong import
## Reproducible examples
``` python
from sklearn.datasets import load_iris
iris = load_iris() 
 
import lightgbm as lgb 
lgtrain = lgb.Dataset(iris.data, iris.target)
lgb_clf = lgb.train(
        {
    'objective' : 'regression',
    'metric' : 'rmse',
    'num_leaves' : 350,
    #'max_depth': 14,
    'learning_rate' : 0.017,
    'feature_fraction' : 0.5,
    'bagging_fraction' : .8,
    'verbosity' : -1 ,
    'device' : 'gpu'
},
        lgtrain,
        num_boost_round=3500,
        verbose_eval=100
    )
```
## Steps to reproduce

1. Compile library following this guide http://lightgbm.readthedocs.io/en/latest/GPU-Windows.html
2. Validated succesful installation 

```
C:\github_repos\LightGBM\examples\binary_classification>"../../lightgbm.exe" config=train.conf data=binary.train valid=binary.test objective=binary device=gpu
[LightGBM] [Warning] objective is set=binary, objective=binary will be ignored. Current value: objective=binary
[LightGBM] [Warning] data is set=binary.train, data=binary.train will be ignored. Current value: data=binary.train
[LightGBM] [Warning] valid is set=binary.test, valid_data=binary.test will be ignored. Current value: valid=binary.test
[LightGBM] [Info] Finished loading parameters
[LightGBM] [Info] Loading weights...
```
3.  Stuck with importing

**Comment by StrikerRUS** [comment]
Have you successfully compiled the GPU-version of LightGBM library?
If yes, then remove previously installed Python package with the following command:
```
pip uninstall lightgbm
```
or
```
conda uninstall lightgbm
```

After doing that navigate to the Python package directory and install it with the library file which you've compiled:
```
cd LightGBM/python-package
python setup.py install --precompile
```

**Comment by Diyago** [comment]
@StrikerRUS  thank you, now its works

**Comment by StrikerRUS** [comment]
@Diyago Glad that your problem has been solved!
