### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by veran441** [Microsoft/LightGBM#1459]
## Environment info
Operating System: Red Hat Enterprise Linux Server 7.3
CPU: Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz
C++/Python/R version: gcc 4.8.5 

## Error Message:
Segmentation fault (core dumped)

## Reproducible examples
Everywhere but for example:
examples/binary_classification

## Steps to reproduce
1. Install repo according to the Linux version on [](https://github.com/Microsoft/LightGBM/blob/master/docs/Installation-Guide.rst)
2. In /examples/binary_classification run `../../lightgbm config=train.conf `

This appeared after I deleted the whole repo from my computer and tried to re-clone it. First time I cloned it (Thursday last week) it worked perfectly. Tried to checkout earlier commits from around Thursday but still the same output.

**Comment by guolinke** [comment]
Just run it, and seems everything is fine...
can you try before and after this commit (0584065c036414f6e4ae01e72314f2f9cbed7329) ?

**Comment by veran441** [comment]
Strange.. I get the same with both this commit and the ones before and after..

**Comment by guolinke** [comment]
the same ? still crash ?

can you try the commit of last month ? 
Maybe there are some changes in your environment. can you also try to use another computer to test again ?

**Comment by veran441** [comment]
Yes it still gives me Segmentation fault (core dumped). 

Might be my environment then. A firend tried and works on her environment. 

Running with gdb i get the following: 
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff6ded8e7 in __libc_start_main (main=0x43aff0 <main>, argc=1, 
    ubp_av=0x7fffffffdc58, init=<optimized out>, fini=<optimized out>, 
    rtld_fini=<optimized out>, stack_end=0x7fffffffdc48) at libc-start.c:228
228	libc-start.c: No such file or directory.

And this seems to be about glibc. I run with 2.17 verison. So I will try to solve it there!

**Comment by veran441** [comment]
Yes it still gives me Segmentation fault (core dumped).

Might be my environment then. A firend tried and works on her environment.

Running with gdb i get the following:
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff6ded8e7 in __libc_start_main (main=0x43aff0
, argc=1,
ubp_av=0x7fffffffdc58, init=, fini=,
rtld_fini=, stack_end=0x7fffffffdc48) at libc-start.c:228
228 libc-start.c: No such file or directory.

**Comment by guolinke** [comment]
@veran441 any updates ?
