### ISSUE TITLE
object importance (LeafInfluence)

### ISSUE THREAD

**Issue by doktrster** [microsoft/LightGBM#1460]
I know that in CatBoost in Python API there is a possibility to calculate object importance (don't confuse it with feature importance) with get_object_importance method.

I would like to know is there a similar option in LightGMB?

**Comment by StrikerRUS** [comment]
At present, there is no functionality for calculating object importance in LightGBM.

Are you talking about this one method?
https://github.com/catboost/catboost/blob/8973ca5c3a6b524abd0cd698f94a05a90c43ba73/catboost/python-package/catboost/core.py#L1450

According to the documentation, the algorithm behind is described in this paper: https://arxiv.org/pdf/1802.06640.pdf

**Comment by StrikerRUS** [comment]
Closed in favor of being in #2302. We decided to keep all feature requests in one place.

Welcome to contribute this feature! Please re-open this issue (or post a comment if you are not a topic starter) if you are actively working on implementing this feature.
