### ISSUE TITLE
Choice of `feature_importance_` in sklearn API

### ISSUE THREAD

**Issue by mlisovyi** [Microsoft/LightGBM#1466]
I would like to ask to add a new argument to `lightgbm.LGBMModel` to be able to choose the feature importance type that is returned by `lightgbm.LGBMModel.feature_importance_`. 

Right now it is always the default of `lighgbm.Booster.feature_importance()`, that defaults to `split`, but that has undesired behavior in particular for categorical features treated internally in lightgbm, see [this kaggle kernel](https://www.kaggle.com/mlisovyi/beware-of-categorical-features-in-lgbm?scriptVersionId=4070588) for an illustration. In contrast, `gain` behaves better in such case.

Of course, one can use `lightgbm.LGBMModel.booster_.feature_importance(importance_type='gain')`, but this is not sufficient, if one wants to use feature selection algorithms in sklearn (those use `model.feature_importances_` to sorf features, see [RFE](http://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.RFE.html#sklearn.feature_selection.RFE), as an example).

P.S. I'm aware of SHAP, which is discussed in #1350. But it is slow at the moment and one needs to write a derived wrapper class to implement `model.feature_importances_` as mentioned above.

**Comment by StrikerRUS** [comment]
Good idea about adding the `importance_type` argument!

Does new argument should be added to `__init__()`?

**Comment by StrikerRUS** [comment]
Please clarify this moment about `model.importance_type`.

>feature selection algorithms in sklearn (those use model.importance_type to sorf features, see RFE, as an example).

Scikit-learn estimators don't have this attribute. Related issue: https://github.com/scikit-learn/scikit-learn/issues/7926.

**Comment by mlisovyi** [comment]
My proposal was to have an attribute of `lgbm.LGBMModel.importance_type`, that would be set in constructor. That attribute would be passed into the function [here](https://github.com/Microsoft/LightGBM/blob/c803b5cbca7b53ad83b473ffa1e1ed0436015e5c/python-package/lightgbm/sklearn.py#L613). This way the user would be able to configure what is to be stored in `model.feature_importances_`.

Apologies, there was a typo of `model.importance_type` in place of `model.feature_importances_` in the original issue. I will edit it

**Comment by StrikerRUS** [comment]
Thanks for the comment. Now everything is clear.

Would you mind working on it?

**Comment by mlisovyi** [comment]
sure, i will do it tomorrow.
