### ISSUE TITLE
cannot use bagging in GOSS

### ISSUE THREAD

**Issue by jingcb** [Microsoft/LightGBM#1467]
hi, in python,
clf = LGBMClassifier(
            nthread=4,
            n_estimators=10000,
            learning_rate=0.02,
            num_leaves=34,
            colsample_bytree=0.9497036,
            subsample=0.8715623,
            max_depth=8,
            reg_alpha=0.041545473,
            reg_lambda=0.0735294,
            min_split_gain=0.0222415,
            min_child_weight=39.3259775,
            silent=-1,
            verbose=-1, )

but get error
lightgbm.basic.LightGBMError: b'cannot use bagging in GOSS'

**Comment by StrikerRUS** [comment]
The error is quite simple to understand.

Remove the `subsample` parameter.
