### ISSUE TITLE
train the lightgbm model with libsvm format dataset

### ISSUE THREAD

**Issue by lxianwei003** [Microsoft/LightGBM#1471]
## Environment info
Operating System: linux + python3
CPU:
C++/Python/R version:

## Error Message:
Traceback (most recent call last):
  File "lightgbm_vas.py", line 39, in <module>
    clf.fit(train_data,train_label,eval_metric='auc',early_stopping_rounds=200)
  File "/home/platform_user/anaconda3/lib/python3.6/site-packages/lightgbm/sklearn.py", line 675, in fit
    callbacks=callbacks)
  File "/home/platform_user/anaconda3/lib/python3.6/site-packages/lightgbm/sklearn.py", line 414, in fit
    X, y = _LGBMCheckXY(X, y, accept_sparse=True, force_all_finite=False, ensure_min_samples=2)
  File "/home/platform_user/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py", line 521, in check_X_y
    ensure_min_features, warn_on_dtype, estimator)
  File "/home/platform_user/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py", line 416, in check_array
    context))

ValueError: Found array with 1 sample(s) (shape=(1, 1)) while a minimum of 2 is required.
## Question
 i want to train the lightgbm model with libsvm format dataset ,

`train_file = "../../sample/gbdt/train_ctr_2018-05-21_file"
train_set = lgb.Dataset(train_file)
train_set.construct()

train_label = train_set.label
train_data = train_set.data
print(train_set.num_data())
print(train_set.num_feature())
evals_file = "../../sample/gbdt/test_ctr_2018-05-22_file"
evals_set = lgb.Dataset(evals_file)
evals_set.construct()
evals_label = evals_set.label
evals_data = evals_set.data

clf = lgb.LGBMClassifier(
    boosting_type='gbdt', num_leaves=31, reg_alpha=0.0, reg_lambda=1,
    max_depth=-1, n_estimators=10000, objective='binary',
    subsample=0.7, colsample_bytree=0.7, subsample_freq=1,
    learning_rate=0.05, min_child_weight=50, random_state=2018, n_jobs=-1
)
clf.fit(train_data,train_label,eval_set = 
    [(evals_data,evals_label)],eval_metric='auc',early_stopping_rounds=200)
`
but i get error 
ValueError: Found array with 1 sample(s) (shape=(1, 1)) while a minimum of 2 is required.

**Comment by guolinke** [comment]
lgb.Dataset only works with lgb.train or lgb.cv, not for sklearn interface.
