### ISSUE TITLE
python segfault error 6

### ISSUE THREAD

**Issue by llsb** [Microsoft/LightGBM#1472]
列超过2700 且行超过25000的时候，使用网格搜索运行lightgbm会导致linux系统出现segfault错误，使得python程序down掉。
![image](https://user-images.githubusercontent.com/37059894/41766731-533fcba2-763a-11e8-87f2-342abcfeee9d.png)

**Comment by guolinke** [comment]
What is the memory of your machine ?
can you provide a re-produce code with random generated data ?
Can you try the latest version (2.1.2) ? 

BTW, it is better to use English in Github.
