### ISSUE TITLE
OSError: exception: access violation writing

### ISSUE THREAD

**Issue by leftluoyi** [Microsoft/LightGBM#1475]
Windows 10 + Python 3.6.3 x64 + CUDA 8.0

Have successfully installed **LightGBM** and can run the **binary_classification** example from command prompt.

If set the classifier as **XGBClassifier**, everything is okay. When change to **LGBMClassifier**, the following exceptions is thrown.

```
 File "D:\Anaconda3\lib\site-packages\lightgbm\sklearn.py", line 695, in fit
    callbacks=callbacks)
  File "D:\Anaconda3\lib\site-packages\lightgbm\sklearn.py", line 474, in fit
    callbacks=callbacks)
  File "D:\Anaconda3\lib\site-packages\lightgbm\engine.py", line 183, in train
    booster = Booster(params=params, train_set=train_set)
  File "D:\Anaconda3\lib\site-packages\lightgbm\basic.py", line 1307, in __init__
    train_set.construct().handle,
  File "D:\Anaconda3\lib\site-packages\lightgbm\basic.py", line 860, in construct
    categorical_feature=self.categorical_feature, params=self.params)
  File "D:\Anaconda3\lib\site-packages\lightgbm\basic.py", line 714, in _lazy_init
    self.__init_from_np2d(data, params_str, ref_dataset)
  File "D:\Anaconda3\lib\site-packages\lightgbm\basic.py", line 776, in __init_from_np2d
    ctypes.byref(self.handle)))
OSError: exception: access violation writing 0xFFFFFFFF98090000
```
Any idea?

======================== UPDATE ==========================

Now I can run [this](https://github.com/Microsoft/LightGBM/blob/master/examples/python-guide/simple_example.py) example with CPU version and GPU version with lightgbm.exe, but the GPU version with python throws this exception.

**Comment by guolinke** [comment]
are you on the latest version ?

**Comment by guolinke** [comment]
BTW, can you provide a re-produce code with randomly generated data ?

**Comment by leftluoyi** [comment]
I tried with [this](https://github.com/Microsoft/LightGBM/blob/master/examples/python-guide/simple_example.py) example. The problem still exists.

**Comment by guolinke** [comment]
can you try to uninstall and re-install ? you can install version 2.1.2 from pypi directly.

**Comment by leftluoyi** [comment]
@guolinke I will try to reinstall. BTW, here is what I got.
![image](https://user-images.githubusercontent.com/7591374/41836424-41056582-788d-11e8-8914-dd625efe8fac.png)

**Comment by guolinke** [comment]
BTW, we have the tests for these examples in Windows: https://github.com/Microsoft/LightGBM/blob/master/.appveyor.yml#L51-L58 
So these examples should be run without errors, since the tests are passed

**Comment by leftluoyi** [comment]
@guolinke Thanks for the advice. I installed the cpu version via `pip install lightgbm` and things works fine. But I forgot to mention that I am trying with gpu version. So if I install with `pip install lightgbm --install-option=--gpu --install-option=--mingw`, the **access violation** exception happens again.

**Comment by guolinke** [comment]
ping @huanzhang12 @StrikerRUS

**Comment by leftluoyi** [comment]
The problem is solved by update relevant packages by `pip install setuptools numpy scipy scikit-learn -U`. @guolinke thanks for your advice. Please close this issue.
