### ISSUE TITLE
utils::Atof doesn't respect user locale

### ISSUE THREAD

**Issue by Ivanidzo4ka** [Microsoft/LightGBM#1481]
We have C# wrapper on top of LightGBM nuget (2.1.2.2).
At some point during interaction with library we call LGBM_DatasetCreateFromSampledColumn
and among all  parameters we pass string filled with "training options" (https://github.com/Microsoft/LightGBM/blob/162509aeadf61e527891fe96d6a4707a270cd4a8/include/LightGBM/c_api.h#L76 ).

Since we using C# at some point we convert doubles to string, and we use default ToString() method which cast double value into string with respect of current locale.
And for En-Us locale everything works perfectly, but for locales where decimal separator is "," we got following error:
Parameter learning_rate should be of type double, got "0,2"

From what I see in your code https://github.com/Microsoft/LightGBM/blob/ba3e1ff24fd43ed33d7703881d8efad83a5ed452/include/LightGBM/utils/common.h#L174
you deliberately wrote your own Atof function which respect only "." as decimal point
https://github.com/Microsoft/LightGBM/blob/ba3e1ff24fd43ed33d7703881d8efad83a5ed452/include/LightGBM/utils/common.h#L199

Any chance you can switch current behavior and use std::numpunct::decimal_point (http://www.cplusplus.com/reference/locale/numpunct/decimal_point/) to detect current decimal point (any other solution which respect user locale is fine :))

## Environment info
Operating System: Windows 
## Error Message:
Parameter learning_rate should be of type double, got "0,2"
##Steps to reproduce
1. Pass configuration string which contains "," as decimal separator for double value

**Comment by guolinke** [comment]
This will break our multi-double parameter, e.g. `0.1,0.2,0.3`. Thus, To have this feature, we will need to change the delimiter and cause confuse.

**Comment by Ivanidzo4ka** [comment]
Thank you for reply @guolinke! Any chance you can accept parametrized object instead of just string?
If no, it's fine we can have workaround in our code, so feel free to close this issue.

**Comment by guolinke** [comment]
it is not so easy for cpp to accept object parameter. and changing to parameter schema will have a big impact for users.
