### ISSUE TITLE
Install LightGBM R package got error

### ISSUE THREAD

**Issue by nannan121** [Microsoft/LightGBM#1482]
## Environment info
Windows 10 x64
R version 3.5.0(Path)
Rtools (Path)
VS 2017
Cmake(Path)

## Running following command in rstudio
devtools::install_github("Laurae2/lgbdl", force = TRUE)
library(lgbdl)
lgb.dl(commit = "master",
       compiler = "vs",
       repo = "https://github.com/Microsoft/LightGBM")

## Error Message:
Error in file(file, ifelse(append, "a", "w")) : 
  cannot open the connection
In addition: Warning message:
In file(file, ifelse(append, "a", "w")) :
  cannot open file 'C:\User\Rstudio\AppData\Local\Temp\RtmpOEmMnU\LightGBM\R-package\src\install.libs.R': No such file or directory

Please extend help, thanks so much. Kind of running desperate here cause I tried the ways mentioned in other issues and it didn't work for me.

**Comment by nannan121** [comment]
I also tried another way
## run following command in Rstudio
library(devtools)
options(devtools.install.args = "--no-multiarch")
install_git("https://github.com/Microsoft/LightGBM", subdir = "R-package")

## Error message
<img width="363" alt="db361531344fc6b4c59f7a8e7e4f748" src="https://user-images.githubusercontent.com/40712124/42123001-1cb26862-7c7d-11e8-8f93-df8ab3992b08.png">

**Comment by guolinke** [comment]
@Laurae2

**Comment by Laurae2** [comment]
@guolinke Just tried now, it worked fine (tested both way of installing the original poster provided).

`.Internal(internalsID())` error usually happen when multiple R versions are installed, and one R attempts to loads the wrong R version of a package.

@nannan121 How many R versions do you have on your computer? Can you also provide your PATH environment variable content?

**Comment by nannan121** [comment]
Hi Laurae2,

Thanks so much for the quick reply. I got two versions of R on my computer 3.3.0 / 3.5.0.  To Avoid the mistake `internal(internalID())` , I have changed to 3.4.0, which now is the only version of R on my laptop.

##Error Message
installing via 'install.libs.R' to C:/Program Files/R/R-3.4.0/library/lightgbm
CMake Error at CMakeLists.txt:9 (PROJECT):
  Generator

    Visual Studio 15 2017 Win64

  could not find any instance of Visual Studio.

But I have installed VS 2017. What's wrong?

Thanks again for the time.

**Comment by nannan121** [comment]
![Uploading 3f96c91f22efec3a29363b461a8f72d.png…]()

**Comment by nannan121** [comment]
<img width="310" alt="3f96c91f22efec3a29363b461a8f72d" src="https://user-images.githubusercontent.com/40712124/42124518-831ec9ec-7c96-11e8-9ef9-5ae8f62fa4fd.png">

**Comment by guolinke** [comment]
can you try the latest cmake?

**Comment by mustaphaweather** [comment]
hey guys i just installed lightgbm package these are the steps to reproduce :

1 - git clone --recursive https://github.com/Microsoft/LightGBM
2 - cd LightGBM
3 - open R-package/src/install.lib and change use_precompile from FALSE to TRUE
4 - go to root directory of lightgbm and copy cmakelists and paste it to R-package/inst/bin
5 - cd lightGBM 
6 - Rscript build_r.R
7 - cd r_lightgbm
8 - R CMD INSTALL --build . --no-multiarch

**Comment by Laurae2** [comment]
@nannan121 any news?

**Comment by StrikerRUS** [comment]
Closed due to inactivity.
Feel free to reopen with new details.

**Comment by gouherdanish** [comment]
Recently I installed lightgbm in R successfully on my mac os x using gcc compiler. Here are the steps -
1) Install cmake 
![Screen Shot 2019-06-29 at 12 58 25 PM](https://user-images.githubusercontent.com/41228470/60381269-7797df80-9a6f-11e9-8842-8af0381c2919.png)

2) Install libomp
![Screen Shot 2019-06-29 at 12 58 42 PM](https://user-images.githubusercontent.com/41228470/60381271-841c3800-9a6f-11e9-8883-b9afbe73d7e0.png)

3) install open-mpi
![Screen Shot 2019-06-29 at 1 00 06 PM](https://user-images.githubusercontent.com/41228470/60381276-a0b87000-9a6f-11e9-8adc-69bd31bb7212.png)

This installs gcc in /usr/local/bin. Check gcc and g++ version (For me, it is 9)
![Screen Shot 2019-06-29 at 1 01 35 PM](https://user-images.githubusercontent.com/41228470/60381307-32c07880-9a70-11e9-9764-d86b1da4162d.png)

4) Now Check Environment Variables - Check variables CC and CXX (For me, it is 7)
![Screen Shot 2019-06-29 at 1 04 22 PM](https://user-images.githubusercontent.com/41228470/60381297-f1c86400-9a6f-11e9-9e24-7bad97d5a43e.png)

5) So, we need to change the environment variables CC and CXX
![Screen Shot 2019-06-29 at 1 04 45 PM](https://user-images.githubusercontent.com/41228470/60381329-b1b5b100-9a70-11e9-86da-f5aadcbca65f.png)

6) Now proceed with further installation from Github - 
![Screen Shot 2019-06-29 at 12 59 17 PM](https://user-images.githubusercontent.com/41228470/60381335-e164b900-9a70-11e9-89cd-86ed7605a7f8.png)

7) mkdir build ; cd build
cmake ..
make -j4
![Screen Shot 2019-06-29 at 1 03 30 PM](https://user-images.githubusercontent.com/41228470/60381363-7071d100-9a71-11e9-8a71-548392f1326c.png)

8) cd ..
RScript build_r.R
![Screen Shot 2019-06-29 at 1 04 59 PM](https://user-images.githubusercontent.com/41228470/60381375-96977100-9a71-11e9-818b-7c7bba1e58de.png)
