### ISSUE TITLE
TweedieMetric instability when score is close to zero

### ISSUE THREAD

**Issue by BlindApe** [Microsoft/LightGBM#1489]
class TweedieMetric in regression_metric.hpp needs similar truncation that class PoissonMetric for avoid log(score) instability:

const double eps = 1e-10f;
    if (score < eps) {
      score = eps;
    }

This problem was reported a year ago in xgboost:
https://github.com/dmlc/xgboost/issues/2473
still unsolved.

**Comment by guolinke** [comment]
@BlindApe you can open a PR to fix it

**Comment by StrikerRUS** [comment]
@BlindApe Would you mind to create a PR?
