### ISSUE TITLE
how to save model with sklearn's joblib?

### ISSUE THREAD

**Issue by henry0312** [Microsoft/LightGBM#149]
How to save model with [joblib](http://scikit-learn.org/stable/modules/model_persistence.html "3.4. Model persistence — scikit-learn 0.18.1 documentation")?

## Environment info

Operating System: OS X 10.11.6
CPU: Intel Core i7

## Error Message

`ValueError: ctypes objects containing pointers cannot be pickled`

For detail, please see https://gist.github.com/henry0312/7ae4ab3257152849819d84fca19f4108#file-gistfile1-txt

## Reproducible examples

https://gist.github.com/henry0312/7ae4ab3257152849819d84fca19f4108#file-tset_gbm_joblib-py

## Steps to reproduce

1. move the above example file into `examples/python-guide`
2. `python  tset_gbm_joblib.py`

**Comment by wxchan** [comment]
Not support yet. I will fix it soon.

**Comment by henry0312** [comment]
Are some codes like https://github.com/dmlc/xgboost/blob/master/python-package/xgboost/core.py#L671 needed?

**Comment by wxchan** [comment]
Yes, but xgboost only has booster pointer, LightGBM has 3 parts of pointers: booster, train set and valid sets. Also class Dataset is kinda complicated.

**Comment by wxchan** [comment]
I think dataset pointer can be deleted directly and rest is same as xgboost. I did it on my [pickle branch](https://github.com/wxchan/LightGBM/tree/pickle). But with python build-in pickle module, the loaded model is a little different. Can you try if joblib works?

**Comment by henry0312** [comment]
Saving models with joblib works fine, but predictions of loaded model aren't the same with those of before model.
(I updated the example, https://gist.github.com/henry0312/7ae4ab3257152849819d84fca19f4108#file-tset_gbm_joblib-py)

**Comment by henry0312** [comment]
```
» python test_gbm_joblib.py 
Load data...
Start training...
[1]	valid_0's l1:0.536072
Train until valid scores didn't improve in 5 rounds.
[2]	valid_0's l1:0.528484
[3]	valid_0's l1:0.521163
[4]	valid_0's l1:0.514374
[5]	valid_0's l1:0.508836
[6]	valid_0's l1:0.502996
[7]	valid_0's l1:0.497912
[8]	valid_0's l1:0.492616
[9]	valid_0's l1:0.487243
[10]	valid_0's l1:0.482528
[11]	valid_0's l1:0.478176
[12]	valid_0's l1:0.473355
[13]	valid_0's l1:0.469354
[14]	valid_0's l1:0.465396
[15]	valid_0's l1:0.46168
[16]	valid_0's l1:0.45808
[17]	valid_0's l1:0.454562
[18]	valid_0's l1:0.451392
[19]	valid_0's l1:0.448304
[20]	valid_0's l1:0.445538
[ 0.51777881  0.32673674  0.18207698  0.26050393  0.20691852]
Save model
Load model
[ 0.51777863  0.32673657  0.18207691  0.26050403  0.20691861]
```

**Comment by wxchan** [comment]
The reason is discussed in #151 , related to float and double precision. I think they are same model since gbm.get_params() == gbm2.get_params().

**Comment by henry0312** [comment]
> related to float and double precision

I got it :)
