### ISSUE TITLE
'Booster' object has no attribute 'plot_metric'

### ISSUE THREAD

**Issue by janelu9** [Microsoft/LightGBM#1491]
lgb_model = lgb.train(lgb_params,
                lgb_train,
                categorical_feature=cat_features_index,
                num_boost_round=300,
                valid_sets=lgb_eval)

error happened 'Booster' object has no attribute 'plot_metric'
booster (dict or LGBMModel) – Dictionary returned from lightgbm.train() or LGBMModel instance.
it means lgb_model is not a LGBMModel instance?

**Comment by StrikerRUS** [comment]
Please provide extended piece of code. What are you trying to achieve?

You can see the example of how to plot metric here:
https://github.com/Microsoft/LightGBM/blob/2e93cdab9eee02d4d7f5cb3b6b31128dec94e25e/examples/python-guide/plot_example.py#L32-L47

**Comment by StrikerRUS** [comment]
ping @janelu9

**Comment by StrikerRUS** [comment]
@janelu9 Are you still experience this problem?
