### ISSUE TITLE
[Feature] Integration with Azure ML Studio

### ISSUE THREAD

**Issue by PerformanceGenetics** [Microsoft/LightGBM#15]
This is a great package. I'd suggested (politely) that if there are not any plans to bring XGBoost within the Azure ML Studio GUI, this would be a good module to add as an option and provide a much needed tool within the interface

**Comment by chivee** [comment]
hi @PerformanceGenetics . we would happy to talk to Azure ML team to make this happen.

**Comment by taifeng1205** [comment]
We are actively collaborating with Azure ML team on bring this onboard. And internally there is another GBDT tool available on AzureML, which will be even more powerful in the future with our help.
