### ISSUE TITLE
Nuget package of LightGBM (2.1.2.2) can not be installed at .net framework 4.6.1

### ISSUE THREAD

**Issue by sharpwood** [Microsoft/LightGBM#1506]
Nuget package of LightGBM can not be installed at .net framework 4.6.1

**Comment by StrikerRUS** [comment]
Already reported to ML.NET-team:
https://github.com/dotnet/machinelearning/issues/494

**Comment by sharpwood** [comment]
@StrikerRUS

**Comment by StrikerRUS** [comment]
We don't have `2.1.2.2` version

**Comment by petterton** [comment]
Current [NuGet version](https://www.nuget.org/packages/LightGBM/) is 2.1.2.2...

**Comment by guolinke** [comment]
@codemzs 
Current Nuget folder structure has problems for the  .net framework 4.6.1 ?

**Comment by codemzs** [comment]
Hi @guolinke I believe in the nuget folder we need two subfolders 1) net45 and 2) .netstandard2.0. So the folder structure under "lightgbm" folder would look like:
2.2.2.2
         ---lib
              ---net46
                  ---lib_lightgbm.dll
                  ---lightgbm.exe
              ---netstandard2.0
                  ---runtimes
                      ---linux-x86
                          ---native
                               ---lib_lightgbm.so
                      ---osx-x64
                          ---native
                              ---lib_lightgbm.dylib
                      ---win-x64
                          ---native
                              ---lib_lightgbm.dll
                              ---lightgbm.exe

Let me know once you have the nuget ready and I can verify before you push it. @https://github.com/dotnet/machinelearning/issues/494

CC: @eerhardt @shauheen @galoshri @tomfinley
