### ISSUE TITLE
Number of trees in multi-class classification in LightGBM depends on number of classes

### ISSUE THREAD

**Issue by abhishek-jha13** [Microsoft/LightGBM#1517]
In [https://lightgbm.readthedocs.io/en/latest/Parameters.html#num_iterations](https://lightgbm.readthedocs.io/en/latest/Parameters.html#num_iterations) , we see that the number of trees in multi-class problem is equal to num_class * num_iterations. 
Why does this happen?

**Comment by guolinke** [comment]
it uses one-vs-rest multi-class algorithm.
