### ISSUE TITLE
Apple Clang support

### ISSUE THREAD

**Issue by StrikerRUS** [Microsoft/LightGBM#1523]
Since we've started to support Apple Clang in #1501, we should clarify installation instructions with the notes about the possibility of compiling certain versions of LightGBM with Apple Clang.

For ordinary version we have the requirement `CMake >=3.12` because of `FindOpenMP`. And what about
- MPI version;
- GPU version;
- HDFS version

?

ping @guolinke @chivee @levyfan @huanzhang12 @ebernhardson @henry0312

**Comment by StrikerRUS** [comment]
@chivee Sorry, probably I was unclear, but I wanted to know about the general possibility of compiling these LightGBM versions with AppleClang and its required version for doing this.

**Comment by StrikerRUS** [comment]
@guolinke 
>How about the binary(python wheel) ?
can we replace it with clang version ? and then users don't need to install gcc. However, it may still require to upgrade clang.

Maybe it's overkill, but what about providing several Python wheels with different versions? For instance, `lightgbm`, `lightgbm-gpu` (like `tensorflow` does), `lightgbm-gcc` (compiled with gcc on macOS and with MinGW on Windows).

**Comment by StrikerRUS** [comment]
To speak about `MPI` version, compilation at Travis with Apple Clang 8.1 is successful:
https://travis-ci.org/Microsoft/LightGBM/jobs/407115085#L3681

**Comment by StrikerRUS** [comment]
Hi @huanzhang12 !

Don't you know what `Invalid Work Group Size` error means?
https://travis-ci.org/Microsoft/LightGBM/builds/409535904

https://github.com/Microsoft/LightGBM/tree/gpu-apple (base branch is `macos`)

The error appears even after adding OpenCL headers from Khronos too. https://stackoverflow.com/a/23079478

This file cannot be placed into system directory due to SIP on new macOS, so I made the following:

https://github.com/Microsoft/LightGBM/blob/f1fb6438f74dd7f551acf778e63e8ae830364f76/.travis/test.sh#L84-L87
https://github.com/Microsoft/LightGBM/blob/f1fb6438f74dd7f551acf778e63e8ae830364f76/.travis/test.sh#L107

**Comment by StrikerRUS** [comment]
Thank you very much, @huanzhang12 ! As usual, detailed answer :-)

Shame on me that I've missed #667.

To speak about the issue title, are there any special requirements for Apple Clang/CMake/Boost version?

In general, I think it's good to write several words in the [installation guide](https://github.com/Microsoft/LightGBM/blob/master/docs/Installation-Guide.rst#build-gpu-version) about macOS building process of the GPU version. Did I get it right that built-in Apple's OpenCL works fine in case of **real GPU device**? And does Khronos headers are needed in this case?

**Comment by StrikerRUS** [comment]
@huanzhang12

**Comment by huanzhang12** [comment]
If it compiles on macOS, it should be able to run on real GPU devices. I don't think Khronos headers help if the compilation already works without it. However, I have no macOS system to test Apple OpenCL build. More tests should be done to draw a final conclusion.

**Comment by StrikerRUS** [comment]
@huanzhang12 Thanks! Got it! I agree that no instruction is better than misleading one.

**Comment by StrikerRUS** [comment]
Default compiler for macOS is now Apple Clang (https://github.com/Microsoft/LightGBM/pull/1727#issuecomment-426634413).

All other unresolved issues mentioned here have their own GitHub issues. So, closing this.
