### ISSUE TITLE
Bagging logic question

### ISSUE THREAD

**Issue by IbanezJS** [Microsoft/LightGBM#1526]
let bagging_freq=3. bagging_fraction<1
What is the expected behaviour?
1)
iter1 = bag1
iter2 = bag1
iter3 = bag1
iter4 = bag2
iter5 = bag2
iter6 = bag2
etc

or
2)
iter1 = all_data
iter2 = all_data
iter3 = bag1
iter4 = all_data
iter5 = all_data
iter6 = bag2

?

**Comment by Laurae2** [comment]
It should be situation 1:

iter1 = bag1
iter2 = bag1
iter3 = bag1
iter4 = bag2
iter5 = bag2
iter6 = bag2

ping @guolinke for confirmation

**Comment by guolinke** [comment]
@Laurae2 is right.

**Comment by IbanezJS** [comment]
@Laurae2 @guolinke thx.
2 questions more. I asked in https://github.com/Microsoft/LightGBM/issues/1392
