### ISSUE TITLE
segfault due to missing path due to boost

### ISSUE THREAD

**Issue by pseudotensor** [Microsoft/LightGBM#1531]
In a docker container it's common to run with / as base directory and without any /home at all.

In that case, lightgbm segfaults, sometimes saying why like this:

```
import numpy as np
import pandas as pd
import lightgbm as lgb
X1= np.repeat(np.arange(10), 1000)
X2= np.repeat(np.arange(10), 1000)
np.random.shuffle(X2)
y = (X1 + np.random.randn(10000)) * (X2  + np.random.randn(10000))
data = pd.DataFrame({'y': y, 'X1': X1, 'X2': X2})
lgb_params = {'learning_rate'    : 0.1,
                   'boosting'         : 'dart',
                   'objective'        : 'regression',
                   'metric'           : 'rmse',
                   'feature_fraction' : 0.9,
                   'bagging_fraction' : 0.75,
                   'num_leaves'       : 31,
                    'bagging_freq'     : 1,
                   'min_data_per_leaf': 250, 'device_type': 'gpu', 'gpu_device_id': 0}
cv = lgb.cv(lgb_params,
                   lgb_train,
                   num_boost_round=100,
                   early_stopping_rounds=15,
                   stratified=False,
                   verbose_eval=50)
```
output:
```
[LightGBM] [Info] This is the GPU trainer!!
[LightGBM] [Info] Total Bins 20
[LightGBM] [Info] Number of data: 8000, number of used features: 2
[LightGBM] [Info] Using GPU Device: TITAN X (Pascal), Vendor: NVIDIA Corporation
[LightGBM] [Info] Compiling OpenCL Kernel with 16 bins...
[LightGBM] [Warning] boost::filesystem::create_directories: Permission denied: "/home/tester1/.boost_compute/d8"
[LightGBM] [Warning] boost::filesystem::create_directories: Permission denied: "/home/tester1/.boost_compute/b4"
[LightGBM] [Warning] boost::filesystem::create_directories: Permission denied: "/home/tester1/.boost_compute/46"
[LightGBM] [Warning] boost::filesystem::create_directories: Permission denied: "/home/tester1/.boost_compute/02"
[LightGBM] [Warning] boost::filesystem::create_directories: Permission denied: "/home/tester1/.boost_compute/9c"
[LightGBM] [Warning] boost::filesystem::create_directories: Permission denied: "/home/tester1/.boost_compute/82"
[LightGBM] [Warning] boost::filesystem::create_directories: Permission denied: "/home/tester1/.boost_compute/4f"
[LightGBM] [Warning] boost::filesystem::create_directories: Permission denied: "/home/tester1/.boost_compute/27"
[LightGBM] [Warning] boost::filesystem::create_directories: Permission denied: "/home/tester1/.boost_compute/d8"
[LightGBM] [Warning] boost::filesystem::create_directories: Permission denied: "/home/tester1/.boost_compute/b6"
[LightGBM] [Warning] boost::filesystem::create_directories: Permission denied: "/home/tester1/.boost_compute/96"
terminate called without an active exception
Aborted
```

It seems cached binaries are forced to be saved to /home/$USER , but that may not exist or have enough space.  This seems bad practice in general to need to write to disk, although this seems to be how boost works.

Question is whether lightgbm has way to tell boost which cached path to use so there is sufficient control.  Also, lightgbm segfaulting in this case is pretty bad.

**Comment by pseudotensor** [comment]
https://boostorg.github.io/compute/boost_compute/getting_started.html

Looks like the option BOOST_COMPUTE_USE_OFFLINE_CACHE can be set to 0 to avoid these caches, and for large data compiling the kernel doesn't take a long time (1 second).

**Comment by pseudotensor** [comment]
https://github.com/Microsoft/LightGBM/blob/master/src/treelearner/gpu_tree_learner.h#L25

But by default it seems lightgbm forces disk cache to be used.

**Comment by guolinke** [comment]
ping @huanzhang12 to follow up

**Comment by huanzhang12** [comment]
The path for Boost.Compute path is hard coded in the library and cannot be easily changed. I think we can mention this issue in document, and encourage the user to unset `BOOST_COMPUTE_USE_OFFLINE_CACHE` when observing problem with Boost library. Another benefit of doing so is that by disabling the compute cache, Boost.Compute will not depends on Boost.FileSystem and Boost.System any more, avoiding issues like #1508.

**Comment by huanzhang12** [comment]
The path is determined here:
https://github.com/boostorg/compute/blob/master/include/boost/compute/detail/path.hpp#L31-L48

Ideally, we should submit pull requests to Boost.Compute upstream and make these functions more robust, i.e., disable the cache automatically and don't crash if the filesystem goes wrong.
