### ISSUE TITLE
Feature request: please add set_params method to scikit-learn wrappers

### ISSUE THREAD

**Issue by Ingvar-Y** [Microsoft/LightGBM#1535]
Recently I have been using LightGBM sklearn wrappers to combine LightGBM it with other scikit-learn compatible projects. One thing that I miss the most is ability to selectively change parameters like `n_estimators` in an already defined booster via `set_params` before retraining it - and other packages like boruta_py rely on it.

**Comment by StrikerRUS** [comment]
`LGBMModel` and other subclasses already have `set_params` method.

Maybe you are using **very** old version?
