### ISSUE TITLE
Adaptive Neural Trees (ANT)

### ISSUE THREAD

**Issue by chivee** [microsoft/LightGBM#1542]
https://arxiv.org/pdf/1807.06699.pdf

details later

**Comment by zsano1** [comment]
Hello! Do you know where can i see the code??

**Comment by StrikerRUS** [comment]
Closed in favor of being in #2302. We decided to keep all feature requests in one place.

Welcome to contribute this feature! Please re-open this issue (or post a comment if you are not a topic starter) if you are actively working on implementing this feature.

**Comment by jameslamb** [comment]
This was locked accidentally. I just unlocked it. We'd still welcome contributions related to this feature!
