### ISSUE TITLE
how does the multi class actually work

### ISSUE THREAD

**Issue by naarkhoo** [Microsoft/LightGBM#1543]
I wonder what is the methodology behind the multi class prediction ? seems the probability of predictions sum to 1, so it can not be one-versus-all. 

I wonder if it is possible to add one-versus-all methodologies ?

**Comment by guolinke** [comment]
try objective = multiclassova

**Comment by naarkhoo** [comment]
sorry for not being clear - I am asking about the underlying methodology  not the argument in the function- I am asking e.g. if multiclass argument has an one-versus-all procedure beneath.
