### ISSUE TITLE
how can i find the father node of the leaf node?

### ISSUE THREAD

**Issue by fword** [Microsoft/LightGBM#1552]
Tree=3
num_leaves=5
num_cat=0
split_feature=3 0 0 3
split_gain=47.5105 11.0491 9.29408 7.83675
threshold=1.7675000000000003 1.4585000000000004 1.3475000000000004 0.58450000000000013
decision_type=2 2 2 2
left_child=2 -2 3 -1
right_child=1 -3 -4 -5
leaf_value=0.01332043325992209 -0.022753384734832266 -0.065793851286836777 -0.0045065842519547627 0.0031221752792782837
leaf_count=1021 441 69 1141 2928
internal_value=0 -0.571645 0.0691096 0.115177
internal_count=5600 510 5090 3949
shrinkage=0.05

we can see that in the root left node is 2,and right node is 1.
but the " -2,-3" node's father is which one? 2 or 1, how can i figure it out?

**Comment by guolinke** [comment]
the positive number represents to leaf node.
the negative number represents to non-leaf node, and you can use ~x to convert it to positive number, and get the right index of non-leaf node.

**Comment by fword** [comment]
if '1,2' is leaf node  which is father node . i  find it's hard to understand the model, like which leaf is attached to which no-leaf node

**Comment by guolinke** [comment]
@fword sorry, I made a mistake. updated the comment above.
use your model as example:
![image](https://user-images.githubusercontent.com/16040950/43442625-17bf8a3a-94d1-11e8-807a-47a20e6e8b0e.png)

x -> the non-leaf node with index x
Lx -> the leaf node with index x
