### ISSUE TITLE
refine HDFS version installation

### ISSUE THREAD

**Issue by StrikerRUS** [Microsoft/LightGBM#1555]
At present it's rather hard to understand how to build `HDFS` version, e.g. which env. variables and paths should be specified before compiling.

The minimum goal is to update the corresponding section in installation guide. Also, it'll be good to adopt CMake `FindHDFS` module for LightGBM.

Original discussion:
> @StrikerRUS:

>- left only guide for compiling HDFS version on Linux and marked it as `untested` (to be honest, I'm not sure that this version can be compiled at all. For instance, we don't provide `FindHDFS` CMake module like this one https://github.com/dmlc/dmlc-core/blob/master/cmake/Modules/FindHDFS.cmake and `HDFS_CXX_LIBRARIES` variable appears in Google results only in LightGBM repo (see screen below));
>![image](https://user-images.githubusercontent.com/25141164/43114735-16739d42-8f09-11e8-9b9c-3611e4302211.png)

>@ebernhardson:

>@StrikerRUS I'm not sure how to test hdfs on macos, even if i borrowed a macbook for a few days I don't have any hdfs cluster that could be connected to by that macbook.
I didn't see in your linked message what the actual error reported was, only that a variable both created and used in that file isn't seen anywhere else.
>For the acutal implementation, indeed this doesn't use a FindHDFS package. I suppose it could, i wasn't aware of one at the time. The current cmake code primarily works via find_package(JNI_REQUIRED). That sets up all the things regarding java which may give trouble. The rest is looking for hdfs.h and the related shared library which is very boilerplate and all paths should be externally providable. I have indeed only tested this on debian and ubuntu systems running cloudera hadoop and wouldn't be surprised if the build step didn't work elsewhere.
The linked cmake package in dmlc-core certainly looks more robust, converting to it would be a reasonable goal imo.

>@StrikerRUS:

>@ebernhardson Thank you very much for your response!
>I tried to compile HDFS version at Appveyor but with no luck. As I remember, the errors were about that HDFS_INCLUDE_DIR cannot be found. After I set this variable manually, error about HDFS_LIB appeared, and I stopped experiments :-) .
>The linked cmake package in dmlc-core certainly looks more robust, converting to it would be a reasonable goal imo.
>It will be great if you can take this! Or at least if you have no time, please provide some instructions about what should be done in order to compile HDFS version (if you know any special platform-dependent requirements for compiler, CMake, etc., please include them too). You can either do it here in comment (I'll add them in this PR), or in your PR (in this case, base branch should be macos due to significant rework of the installation guide structure).
Thanks in advance!

Please help, @ebernhardson

**Comment by ebernhardson** [comment]
I'm not great at documentation, but perhaps a (hopefully) working demo will do the trick?

https://gist.github.com/ebernhardson/c1fbe7c7c2425afe5131d8d6130572f8

I put together a dockerfile that will pull appropriate dependencies into a vanilla debian jessie image, compile lightgbm with hdfs, and install the python library with it. I added additional instructions for how to connect that image to cloudera's quickstart image to see training data load from hdfs into lightgbm and be utilized.

**Comment by StrikerRUS** [comment]
Thank you very much!

I'll definitely add your Gist as an example in the guide!

And what about `FindHDFS` CMake module? Will it be useful to adopt this module for LightGBM?

**Comment by StrikerRUS** [comment]
BTW, don't you want to contribute your dockerfile from Gist to LightGBM's [docker folder](https://github.com/Microsoft/LightGBM/tree/master/docker) under new `hdfs` directory?

**Comment by StrikerRUS** [comment]
ping @ebernhardson

**Comment by StrikerRUS** [comment]
Another attempt to ping @ebernhardson

**Comment by ebernhardson** [comment]
I gave the dmlc FindHDFS module a shot, it unfortunately completely fails to build on my cdh cluster.  They try to link the .a instead of .so, which for unknown reasons causes a relocation error related to -fPIC. They also explicitly do not check /usr/include for hdfs.h, but that's where cdh installs it. I can start changing things, but without a system that works that way I can't verify anything in particular.

Overall it seems like replacing the current setup with dmlc FindHDFS simply breaks one configuration to work on another. I'm not sure that's worthwhile? At best perhaps document that there are two paths that might have to be explicitly set:

HDFS_INCLUDE_DIR: Path containing hdfs.h
HDFS_LIB_DIR: Path containing libhdfs.so

If someone wants to try and collect containers for various hadoop distributions, and attempt to make a FindHDFS that works on all of them that would be great, but the existing version in xgboost (which looks quite similar to the impala version) isn't working for me.

**Comment by StrikerRUS** [comment]
Thanks a lot @ebernhardson for coming back here! And thank you very much for giving it a try! I think that it's better to leave the current setup as is and abandon the idea about adopting dmlc FindHDFS module.

I'll definitely document PATH tips for users and the fact that the current implementation works fine on CDH.

And what about your Gist? Would you mind creating a PR with it as a new entry in `docker` folder?

BTW, there are several open issue in the LightGBM repo connected with Hadoop/HDFS. We'll really appreciate if you take a look at they when you have a free time. Thanks!

**Comment by StrikerRUS** [comment]
Closed via #1890.
