### ISSUE TITLE
R custom eval function help

### ISSUE THREAD

**Issue by DSQueen** [Microsoft/LightGBM#1561]
Hi all,

I am having trouble trying to create a custom evaluation function for R package. I would like lightgbm to evaluate the models based on the AUPRC instead of AUC (if this is possible?). I am a newbie to predictive models and I'm sure I'm making multiple errors here. I tried to follow the example I found from Laurae2. I originally tried to modify the summary function (the last lines of code) but it prompts for grad & hess being present.. so I tried to use the example logregobj below with my evalauprc. Any help is greatly appreciated. Thanks!!

**EXAMPLE I FOUND:**
```
logregobj <- function(preds, dtrain) {
  labels <- getinfo(dtrain, "label")
  preds <- 1 / (1 + exp(-preds))
  grad <- preds - labels
  hess <- preds * (1 - preds)
  return(list(grad = grad, hess = hess))
}
evalerror <- function(preds, dtrain) {
  labels <- getinfo(dtrain, "label")
  err <- as.numeric(sum(labels != (preds > 0.5))) / length(labels)
  return(list(name = "error", value = err, higher_better = FALSE))
}

```

**MY  EVAL FUNCTION:**
```

evalauprc <- function(preds, dtrain) {
  labels <- getinfo(dtrain, "label")
  the_curve <- pr.curve(scores.class0=preds,
                        weights.class0 = labels,
                        curve = TRUE)
  auprc <- the_curve$auc.integral
  return(list(name = "auprc", value = auprc, higher_better = TRUE))
}
```

**ATTEMPT TO MODIFY SUMMARY FUNCTION**
```
auprcSummary <- function(preds, dtrain){
  
  labels <- getinfo(dtrain, "label")
  preds <- 1 / (1 + exp(-preds))
  
  roc <- roc(labels, preds)
  auc <- auc(roc)
  
  the_curve <- pr.curve(scores.class0=preds,
                        weights.class0 = labels,
                        curve = FALSE)
  
  pr <- the_curve$auc.integral
  return(list(auc=auc, auprc= pr))
  }
```
Note: Using the pr.curve function from PRROC package.

**Comment by Laurae2** [comment]
@DSQueen can you provide a script example for your use case, such as iris with 2 classes only? (for easier reproducibility, not sure where to put your `auprcSummary` fits)

**Comment by StrikerRUS** [comment]
ping @DSQueen
