### ISSUE TITLE
probability calibration for lightgbm using sklearn's CalibratedClassifierCV()

### ISSUE THREAD

**Issue by munitech4u** [Microsoft/LightGBM#1562]
## Environment info
Operating System: Windows 10
CPU: i7
C++/Python/R version: Python 3.6

## Error Message: 
ValueError: could not convert string to float.

## Reproducible examples
[clf = LGBMClassifier(
boosting_type= 'gbdt',
objective= 'multiclass',
num_class=5,
metric= 'multi_logloss',
learning_rate= 0.05,
max_depth= 7,
num_leaves= 60,
feature_fraction= 0.7,
bagging_fraction= 1,
bagging_freq= 20,
nthread=4,
n_estimators=50)

calibrated_clf = CalibratedClassifierCV(clf, method='isotonic', cv=5)
calibrated_clf.fit(train_df[v1], train_df['label'])](url)

I am trying to use sklearn's CalibratedClassifierCV to see if, this makes any impact to classification problem. However it's throwing me error, because there are some categorical variables, which lightgbm can handle efficiently without having to convert into one hot encoding but CalibratedClassifierCV not.

Is there anyway I can make CalibratedClassifierCV  work with lightgbm? Is it even necessary?

**Comment by StrikerRUS** [comment]
Hi @munitech4u !

Are you trying to feed your data in pandas Dataframe? Or what issue is about?

Please provide the snippet with random data where the issue can be observed.

**Comment by munitech4u** [comment]
Yes, It's a pandas dataframe. There are few columns which are stored as 'category'. Now lightgbm can handle such data, but using along with CalibratedClassifierCV is causing problem

**Comment by StrikerRUS** [comment]
OK, I see.

Then you can convert those columns into integers and specify `categorical_feature` parameter. LightGBM still will treat specified columns as categorical, but they'll be acceptable by `CalibratedClassifierCV `.

**Comment by munitech4u** [comment]
Thanks. This seems to resolve the problem, however if I use verbose, early_stopping_rounds in .fit() it's now allowing to use:
calibrated_clf.fit(train_x, train_y,verbose= 100, early_stopping_rounds= 100)

**Comment by StrikerRUS** [comment]
`verbose= 100, early_stopping_rounds= 100` this is parameters of `LightGBM`, not `CalibratedClassifierCV`.

For early stopping rounds you need to provide evaluation data. So, you cannot combine these two mechanisms: early stopping and calibration.

**Comment by munitech4u** [comment]
ok. Last question. should it make a difference using calibrated probabilities in lightgbm?

**Comment by StrikerRUS** [comment]
Sorry, I've read `CalibratedClassifierCV`'s documentation more attentively. And it seems that you **CAN** combine early stopping and calibration. But I'm not sure that it's the case you need.

`CalibratedClassifierCV` allows to use **prefitted** classifier, so you can fit LightGBM as usual with early stopping mechanism and then calibrate this classifier by passing `cv='prefit'` parameter to `CalibratedClassifierCV`.
Refer to way **Number one** here https://stats.stackexchange.com/a/263411

**Comment by munitech4u** [comment]
Thanks, that was helpful

**Comment by shantanukarve** [comment]
When I use a lightgbm model that was prebuilt / prefitted using the lightgbm interface( lightgbm.train) , and feed that to CalibratedClassifierCV I get the error:

> RuntimeError: classifier has no decision_function or predict_proba method

Is there any way I can wrap the lightgbm model built using the lightgbm.train interface as a scikit object so that it delivers a predict_proba method. Or wrap its predict method as a predict_proba method ? I've looked at the code of the lightgbm scikit wrapper so it seems doable but that's as far as I can get.

**Comment by StrikerRUS** [comment]
@shantanukarve You should not mix standard interface with sklearn one. You have to rewrite your code for sklearn API: https://lightgbm.readthedocs.io/en/latest/Python-API.html#scikit-learn-api. However, you may try to load model via [`est.booster_.model_from_string()`](https://lightgbm.readthedocs.io/en/latest/pythonapi/lightgbm.Booster.html#lightgbm.Booster.model_from_string), but it's untested and unapproved way of usage. It's highly likely you'll face inconsistency errors.

**Comment by shantanukarve** [comment]
Thanks for the pointer. I seem to have working code.  There's really two variables that need to be hacked - the class labels array, and converting the predictions into a array with number of columns with 'class_labels' size. For my purposes this code gets me there:
```
mdl_as_string=mdl_lgb.model_to_string()
def my_predict(X):
    one_dim_preds=mdl_lgb.predict(X)
    two_dim_preds=np.zeros(shape=(len(one_dim_preds),2))
    two_dim_preds[:,1]=one_dim_preds
    return two_dim_preds

lgb_base._Booster=mdl_lgb
lgb_base=lgb_base.booster_.model_from_string(mdl_as_string)
lgb_base.predict_proba=my_predict
lgb_base.classes_=[0,1]
calibrated_mdl = CalibratedClassifierCV(lgb_base, method='isotonic', cv='prefit')
calibrated_mdl.fit(X_valid_scaled, y_valid)
yhat_calibrated=calibrated_mdl.predict_proba(X_valid_scaled)
# for comparison with original preds
yhat_uncalibrated=mdl_lgb.predict(X_valid_scaled)

```
Thanks for pointing out the use of model_from_string. And also code that's so well written, that its easy to follow in a debugger.

**Comment by Solly7** [comment]
Hi @shantanukarve , I need your help..was trying to edit your code and it says 'lgb_base' is undefined...did you perhaps define it somewhere in your code?

**Comment by shantanukarve** [comment]
Hi Solly7, yes I've defined lgb_base earlier as follows:
```
import lightgbm as lgb
lgb_base=lgb.LGBMClassifier( num_leaves=31, max_depth=-1, learning_rate=0.02, n_estimators=2000, objective='binary', importance_type='gain',
            metric= ['binary_logloss'],
        metric_freq=5,
        num_threads= 6,
        min_data_in_leaf = 100,
        is_provide_training_metric= True,
        feature_fraction= 0.80,
        bagging_fraction= 0.80,
        bagging_freq= 5,
        verbose= 1)

```

**Comment by le1tz3y** [comment]
I tried to implement early stopping and calibration as described by @StrikerRUS above. However, I am seeing a '' from the `_get_fit_params` function. This function just checks that the model passed to the EarlyStoppingShapRFECV class is a lightgbm, xgboost, or catboost instance and calls the appropriate _get_fit_params_* function. Due to this, I don't see how the above suggestion will ever work as the code is now. Maybe these checks are a recent addition though. I have considered branching and including this code to resolve the issue, but I am concerned that I will break proper fitting and CV, if I do this. 

I know I can simply not use early stopping, but early stopping is a very nice addition to my project.

Any help would be much appreciated!

**Comment by le1tz3y** [comment]
Well, I tested the code above, and I am still getting the same error.

**Comment by le1tz3y** [comment]
I tried running CCCV through ShapRFECV, so without early stopping, and that causes an error during the Shap analysis as well as shown below.

```
Exception: The passed model is not callable and cannot be analyzed directly with the given masker! Model: CalibratedClassifierCV(base_estimator=LGBMClassifier(metric='average_precision',
                                                     objective='binary',
                                                     random_seed=99,
                                                     verbose=-1))
```
