### ISSUE TITLE
Combining LightGBM with AWS SageMaker

### ISSUE THREAD

**Issue by adodd202** [Microsoft/LightGBM#1563]
## Environment info (AWS SageMaker instance)
Operating System: Ubuntu 16.04 (I think...it's AWS SageMaker)
CPU: (Not sure? It's on SageMaker)
C++/Python/R version: 2.7

## Error Message:

From AWS SageMaker CloudWatch:

19:25:42
Traceback (most recent call last): File "/opt/program/train", line 108, in train early_stopping_rounds=100) File "/opt/conda/lib/python2.7/site-packages/lightgbm/engine.py", line 186, in train booster = Booster(params=params, train_set=train_set) File "/opt/conda/lib/python2.7/site-packages/lightgbm/basic.py", line 1351, in __init__ ctypes.byref(self.handle))) File "/opt/conda/
Traceback (most recent call last):
File "/opt/program/train", line 108, in train
early_stopping_rounds=100)
File "/opt/conda/lib/python2.7/site-packages/lightgbm/engine.py", line 186, in train
booster = Booster(params=params, train_set=train_set)
File "/opt/conda/lib/python2.7/site-packages/lightgbm/basic.py", line 1351, in __init__
ctypes.byref(self.handle)))
File "/opt/conda/lib/python2.7/site-packages/lightgbm/basic.py", line 49, in _safe_call
raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))

19:25:42
LightGBMError: No OpenCL device found

## Steps to reproduce

There are a lot of steps to reproducing this problem. It may not be a problem that is easily reproducible. I'll try to summarize my steps to get to where I am now. It's likely that I'm not setting a path variable correctly somewhere as I've seen discussion of similar problems [elsewhere.] (https://github.com/Microsoft/LightGBM/issues/586) I think it has to do with the Dockerfile, but I'm not sure what...Also I'm kind of a noob with Docker, LightGBM, SageMaker, so I apologize if any of this is obvious.

1. Create AWS account, boot up a SageMaker instance
2. Follow SageMaker walkthrough on custom [algorithms](https://aws.amazon.com/blogs/machine-learning/train-and-host-scikit-learn-models-in-amazon-sagemaker-by-building-a-scikit-docker-container/)
3. Adapt code to use LightGBM GPU instance by editing train and serve file.
4. Edit LightGBM GPU Dockerfile for Ubuntu slightly by adding the following lines:
```
ENV PYTHONUNBUFFERED=TRUE
ENV PYTHONDONTWRITEBYTECODE=TRUE
ENV PATH="/opt/program:${PATH}"

Set up the program in the image
COPY decision_trees /opt/program
WORKDIR /opt/program
```

5. I also removed the Jupyter notebook section and instead of running the "source activate, deactivate" lines, I ran
```RUN cd /usr/local/src/lightgbm/LightGBM/python-package && python setup.py install --precompile```
6. In summary, I've attached the entire Dockerfile. Sorry if this is a bad format, first time posting. Let me know if another format is easier!
[Dockerfile.pdf](https://github.com/Microsoft/LightGBM/files/2255145/Dockerfile.pdf)
7. Build and push the code to SageMaker ECR (elastic container service). Run training job using a sample dataset with LightGBM. Wait ~4 minutes for error message.

Thanks for the help!

**Comment by StrikerRUS** [comment]
I suppose the answer is the same as here https://github.com/Microsoft/LightGBM/issues/1577#issuecomment-412821667 .

@huanzhang12 Have you had any experience with SageMaker?

**Comment by huanzhang12** [comment]
Unfortunately I have no experience with SageMaker... It also looks quite complicated to try it :'(

**Comment by huanzhang12** [comment]
It is very likely they don't have OpenCL driver installed, and probably even don't have a GPU and NVIDIA frameworks installed at all. Since we don't have direct access to the machine it is hard to say what is happening here.

**Comment by adodd202** [comment]
Thanks for the comments, yes, it is quite difficult to troubleshoot. I will be closing this issue just because I have changed to a different project and it is probably a fairly niche problem.

**Comment by RobertWan91** [comment]
Is there any further update regarding to using lightgbm in sagemaker? Can this combination be done or just not possible? I am also trying to do this. Many thanks.

**Comment by zangell44** [comment]
I got LightGBM up and running on SageMaker without an issue today

**Comment by jgorham** [comment]
@zangell44 , with the gpus working too? I can't figure out if its possible to install opencl on the sagemaker machines either.

**Comment by tejavenkatk** [comment]
@zangell44  did you run it using the cpu notebook instances or gpu instances?

**Comment by pavel-is24** [comment]
> I got LightGBM up and running on SageMaker without an issue today

@zangell44 Could you share you Dockerfile?
