### ISSUE TITLE
Dataset::FixHistogram anomalies

### ISSUE THREAD

**Issue by IbanezJS** [Microsoft/LightGBM#1564]
@guolinke 
let assume that dataset completely dense without zeros and nans.
default_bin > 0 (features contains negative and positive values but not 0)

So after:
`data[default_bin].sum_gradients = sum_gradient;
    data[default_bin].sum_hessians = sum_hessian;
    data[default_bin].cnt = num_data;
    for (int i = 0; i < num_bin; ++i) {
      if (i != default_bin) {
        data[default_bin].sum_gradients -= data[i].sum_gradients;
        data[default_bin].sum_hessians -= data[i].sum_hessians;
        data[default_bin].cnt -= data[i].cnt;
      }
    }`

data[default_bin] must be all zeros (AM I RIGHT ?)

But sometimes its not...
sometimes sum_hessians is like -1.7763568394002505E-15 
and sometimes it affect result tree

**Comment by IbanezJS** [comment]
i can provide dataset file to reproduce this

**Comment by guolinke** [comment]
I think it is due to float point sum-up error.

**Comment by IbanezJS** [comment]
@guolinke 
yes of course
But FixHistogram is like a magic)))
i get rip of it and happy))

**Comment by guolinke** [comment]
you can close this issue if it is good now.
