### ISSUE TITLE
[Minor Issue] stable tag points to 2.1.0, is 2.1.2 unstable? It seems 2.1.2 is a release..

### ISSUE THREAD

**Issue by DaniCybereason** [Microsoft/LightGBM#1568]
See title :)

**Comment by guolinke** [comment]
it doesn’t mean 2.1.2 is unstable. the stable tag is for the release that had been released for a period of time.

**Comment by DaniCybereason** [comment]
I'm sorry, it seemed like both 2.1.0 and 2.1.2 were pushed to repo on the
same day (github displayed the same date).

Thanks!

**Comment by guolinke** [comment]
you should check the date in git commit log.

**Comment by StrikerRUS** [comment]
> I'm sorry, it seemed like both 2.1.0 and 2.1.2 were pushed to repo on the
same day (github displayed the same date).

It was me. Before that day those releases were in `Draft`.
