### ISSUE TITLE
PredictionEarlyStopInstance questions

### ISSUE THREAD

**Issue by IbanezJS** [Microsoft/LightGBM#1574]
In PredictionEarlyStopInstance CreateBinary
1)
`const auto margin = 2.0 * fabs(pred[0]);`
Why 2x?

2)
`if (margin > margin_threshold) {
      return true;`
Any recommendations about margin_threshold values?
Someone says use 1.5. But what physical meaning ?

**Comment by StrikerRUS** [comment]
ping @guolinke

**Comment by guolinke** [comment]
refer to #550 and ping @cbecker
