### ISSUE TITLE
Unable to compile lightgbm on aws p8 deep learning ami

### ISSUE THREAD

**Issue by vishaljhala** [Microsoft/LightGBM#1577]
Hi - I am unable to compile lightgbm with flag -DUSE_GPU=1. 
I continue to get following error.
Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES)

Thinking it could be path issue, I tried following commands.
sudo -E env "PATH=$PATH" cmake -DUSE_GPU=1

sudo -E env "PATH=$PATH" cmake -DUSE_GPU=1 -DOpenCL_LIBRARY=/usr/lib/libnvidia-opencl.so.396.37 -DOpenCL_INCLUDE_DIR=/usr/local/cuda-9.2/include/ ..

sudo -E env "PATH=$PATH" cmake -DUSE_GPU=1 -DOpenCL_LIBRARY=/usr/local/cuda-8.0/lib64/libOpenCL.so -DOpenCL_INCLUDE_DIR=/usr/local/cuda-8.0/include/ ..

sudo -E env "PATH=$PATH" cmake -DUSE_GPU=1 -DOpenCL_LIBRARY=/usr/local/cuda-9.0/lib64/libOpenCL.so -DOpenCL_INCLUDE_DIR=/usr/local/cuda-9.0/include/ ..

I also uninstalled / reinstalled, g++,gcc,cmake just to make sure something obvious is not stopping it from compiling.

Any ideas what else can be done?

## Environment info
Operating System: AWS Linux - Deep Learning AMI
CPU: P8 -> 32 cores, 8 GPU
C++/Python/R version: Python

## Error Message:
Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES)

**Comment by Laurae2** [comment]
ping @huanzhang12

**Comment by huanzhang12** [comment]
It looks like the OpenMP library cannot be corrected detected on this Amazon Linux AMI.

I have no idea what package is needed to get it working on this OS - don't use Amazon Linux if possible. Use a common distribution like Ubuntu, Debian or CentOS will make your life much easier.

A Similar issue has been reported before and was resolved by switching to Ubuntu deep learning AMI: https://github.com/dmlc/xgboost/issues/3270 (xgboost also uses OpenMP)

[Do Not Use Amazon Linux](https://www.exratione.com/2014/08/do-not-use-amazon-linux/)

**Comment by vishaljhala** [comment]
Thanks @huanzhang12 and @Laurae2 - I used ubuntu Deep learning AMI and P3. And it worked on AWS.
