### ISSUE TITLE
Parallel training in python

### ISSUE THREAD

**Issue by jiazhe0909** [Microsoft/LightGBM#1578]
Please search your question on previous issues, [stackoverflow](https://stackoverflow.com/questions/tagged/lightgbm) or other search engines before you open a new one.

For bugs and unexpected issues, please provide following information, so that we could reproduce on our system.

## Environment info
Operating System: Linux
CPU: Intel xeon
C++/Python/R version: gcc 6.0

Hi LightGBM experts,

Does the lastest LightGBM support parallel training with MPI in python.

Thanks,

**Comment by Laurae2** [comment]
ping @guolinke

**Comment by guolinke** [comment]
Python version cannot support parallel training now.
You can use MMLSpark for parallel LightGBM. https://github.com/Azure/mmlspark

**Comment by StrikerRUS** [comment]
Also, please see #985.
