### ISSUE TITLE
sigmoid not available during sklearn grid search

### ISSUE THREAD

**Issue by tobigithub** [Microsoft/LightGBM#158]
Hi,
the sigmoid and is_enable_sparse are not available during the python sklearn grid search.
The parameters work in stand-alone scripts and the sigmoid function can have a decent impact
on the results. I used binary classification, but attached an example from the wiki (regression).
There may be other parameters that are not available during grid search, I did not test all of them.

```
'sigmoid' : [0.85,0.90,0.95] ## throws error during grid search
'is_enable_sparse' : ['TRUE'] ## throws error during grid search 
```
## Environment info
Operating System: ubuntu
CPU: corei7

## Error Message:
can be 
```
TypeError: __init__() got an unexpected keyword argument 'sigmoid'
```

Can be
```
ValueError: Invalid parameter sigmoid for estimator LGBMRegressor. Check the list of available parameters with `estimator.get_params().keys()`.
```

## Reproducible examples

```
# coding: utf-8
# pylint: disable = invalid-name, C0111
import lightgbm as lgb
import pandas as pd
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import GridSearchCV

# load or create your dataset
print('Load data...')
df_train = pd.read_csv('../regression/regression.train', header=None, sep='\t')
df_test = pd.read_csv('../regression/regression.test', header=None, sep='\t')

y_train = df_train[0]
y_test = df_test[0]
X_train = df_train.drop(0, axis=1)
X_test = df_test.drop(0, axis=1)

print('Start training...')
# train
gbm = lgb.LGBMRegressor(objective='regression',
                        num_leaves=31,
                        learning_rate=0.05,
                        n_estimators=20)
gbm.fit(X_train, y_train,
        eval_set=[(X_test, y_test)],
        eval_metric='l1',
        early_stopping_rounds=5)

print('Start predicting...')
# predict
y_pred = gbm.predict(X_test, num_iteration=gbm.best_iteration)
# eval
print('The rmse of prediction is:', mean_squared_error(y_test, y_pred) ** 0.5)

print('Calculate feature importances...')
# feature importances
# print('Feature importances:', list(gbm.feature_importance_))

# other scikit-learn modules
estimator = lgb.LGBMRegressor(num_leaves=31)

param_grid = {
    'learning_rate': [0.01, 0.1, 1],
    'n_estimators': [20, 40],
    'sigmoid' : [0.85,0.90,0.95]
}

gbm = GridSearchCV(estimator, param_grid)

gbm.fit(X_train, y_train)

print('Best parameters found by grid search are:', gbm.best_params_)

```
## Steps to reproduce

run the example or integrate sigmoid into python sklearn grid search to see error.

**Comment by wxchan** [comment]
I check the parameters not in sklearn interface:
tree_learner
is_pre_partition
is_sparse
bin_construct_sample_cnt
sigmoid
max_position
label_gain

@guolinke any these parameters have an alias or not support for sklearn?


Also there is an alternative way now
```
from sklearn.model_selection import ParameterGrid
import lightgbm as lgb
X_train, X_test, y_train, y_test = ...
lgb_train = lgb.Dataset(X_train, y_train)
lgb_test = lgb.Dataset(X_test, y_test, reference=lgb_train)
params = {...}
params_grid = {...}
for param_grid in ParameterGrid(param_grid):
  param_grid.update(params)
  gbm = lgb.train(params, lgb_train, valid_sets=lgb_test, num_boost_round=...)
```

**Comment by guolinke** [comment]
@wxchan 
tree_learner and is_pre_partition is used for parallel learning, so it is not need to add them.
is_sparse has not effect on training, so doesn't need to add it either.
you can add rest of them, they are not in sklearn now. And you also can change the alias if needed. 
BTW, ```max_position``` and ```label_gain``` are used for the ranking. and sigmoid only used in binary classification.

**Comment by wxchan** [comment]
Is sigmoid also used in ranking? It's said in docs.
What's the effect of is_sparse? We can add it to fit().

**Comment by guolinke** [comment]
@wxchan  
yes, I forget it. Sigmoid is used in ranking as well.
if disable ```is_binary``` it will slow for the sparse data.
default label gain: https://github.com/Microsoft/LightGBM/blob/master/src/io/config.cpp#L250-L252

**Comment by ekerazha** [comment]
@guolinke @wxchan CLI and sklearn interfaces also use different default values, e.g.:

_CLI default values:_
min_data_in_leaf = 100
min_sum_hessian_in_leaf = 10.0

_sklearn default values:_
min_child_samples (min_data_in_leaf) = 10
min_child_weight (min_sum_hessian_in_leaf) = 5

I think they should be equalized (**on my datasets**, sklearn default values give better results).

**Comment by wxchan** [comment]
@guolinke the default label gain on docs is {0,1,3,7,15,31,63,...}. Is brace required? Can I set default to None and if it's None, pop it from params?

**Comment by guolinke** [comment]
No brace , and you can just use list as parameter in python interface. 

you want to pop all params with '''None''' ? I think it is OK, and for the ```objective``` keep it as string (```"None"```).

**Comment by wxchan** [comment]
No, just label gain. The default is too long to write in __init__.
