### ISSUE TITLE
Poisson regression exposure as offset

### ISSUE THREAD

**Issue by psinger** [Microsoft/LightGBM#1582]
I am trying to model data where my outcome is also defined by a varying exposure. This means that each sample measures a count over a different amount of time in days. In traditional Poisson models, this can be handled by an offset with constant coefficient of 1. For details see:

https://en.wikipedia.org/wiki/Poisson_regression#.22Exposure.22_and_offset

Is this somehow possible to incorporate in Lightgbm?

**Comment by psinger** [comment]
@pford221 Yes, this is definitely an option and I have thought of it. I will continue to play around with it. However, there seem to be some differences in how GBT utilizes the weight compared to e.g., a GLM model, see: https://stats.stackexchange.com/questions/325008/why-is-xgboost-giving-me-seriously-biased-predictions-with-small-nrounds

I am also wondering whether lightgbm has a similar functionality as xgboost to set a base margin.

**Comment by guolinke** [comment]
@psinger you can use `init_score`, which is set per-sample.

**Comment by psinger** [comment]
@guolinke Thanks!
