### ISSUE TITLE
c_api.h uses undefined THREAD_LOCAL macro

### ISSUE THREAD

**Issue by alokpr** [Microsoft/LightGBM#1585]
## Environment info

Operating System: x86_64-linux-gnu

CPU: Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz

C++/Python/R version: gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.9)

## Error message

/usr/local/include/LightGBM/c_api.h: In function ‘char* LastErrorMsg()’:
/usr/local/include/LightGBM/c_api.h:765:38: error: ‘THREAD_LOCAL’ does not name a type
 static char* LastErrorMsg() { static THREAD_LOCAL char err_msg[512] = "Everything is fine"; return err_msg; }
                                      ^
/usr/local/include/LightGBM/c_api.h:765:100: error: ‘err_msg’ was not declared in this scope
 static char* LastErrorMsg() { static THREAD_LOCAL char err_msg[512] = "Everything is fine"; return err_msg; }

## Reproducible examples

In any source file, including <LightGBM/c_api.h>
results in compile error about undefined THREAD_LOCAL

The only workaround is to include <LightGBM/utils/log.h> before including <LightGBM/c_api.h>. Moving the definition of THREAD_LOCAL to c_api.h (or export.h) would fix the issue.

**Comment by guolinke** [comment]
that is very strange, we have CI to check the build in linux. So it should not have the compile issue.

**Comment by alokpr** [comment]
You need to include <LightGBM/c_api.h> first thing in c_api.cpp to actually catch this issue. This is also a good practice in general to ensure that header files are self-sufficient:

https://google.github.io/styleguide/cppguide.html#Self_contained_Headers
https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes

**Comment by johnduffynh** [comment]
The library build works fine.
When calling the library from a c program, I only include c_api.h.
My work around was to `#define THREAD_LOCAL thread_local` for non-widows.
