### ISSUE TITLE
Segfault: memory not mapped when using device "gpu"

### ISSUE THREAD

**Issue by clinchergt** [Microsoft/LightGBM#1587]
I'm trying to train a model through `.cv()` and if I set the `device` parameter to `"gpu"` it just crashes like this on me:

## Error message

```
[LightGBM] [Info] Number of positive: 1117, number of negative: 78883
[LightGBM] [Info] This is the GPU trainer!!
  [LightGBM] [Info] Total Bins 91915
[LightGBM] [Info] Number of data: 80000, number of used features: 482

*** caught segfault ***
  address 0x8, cause 'memory not mapped'
```

## Environment info

```
R version 3.5.1 (2018-07-02)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.5 LTS

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] lightgbm_2.1.2 R6_2.2.2
```

## Reproducible example

```r
rm(list = ls())
library(lightgbm)
library(data.table)

set.seed(0)
n_samples = 100
n_features = 450
binary_labels = rbinom(n_samples, size = 1, prob = 0.5)
features = data.table(
  do.call(cbind,
          lapply(1:n_features,
                 function(x){
                   sample(1:10, size = n_samples, replace = TRUE)
                 }
          )
  )
)
features = as.matrix(lightgbm::lgb.prepare2(features))
features[, 1] <- as.numeric(features[, 1])
train = lightgbm::lgb.Dataset(data = features, label = binary_labels)

bst = lightgbm::lgb.cv(
  objective = "binary", 
  data = train, 
  nrounds = 40L,
  verbose = 0,
  device = "gpu") # change this to "cpu"
```

~~Working on a reproducible example and I'm gonna update R to 3.5 in case that makes a difference.~~

Please note that if I run this on a cpu device **it will run just fine**, it's when I set `device` to `"gpu"` that I get the issue. As far as I know I compiled LightGBM just fine with GPU support enabled. It is my understanding that the error would be different if I hadn't.

Also, the matrix does have at least one `numeric` column so it doesn't seem related to #964 ~~but it does seem to crash after a specific number of features (450 I believe)~~

**EDIT**: I've installed R 3.5.1 and got the same error. Edited the info above to reflect that

**EDIT 2**: Trying the reproducible example from above now it just fails regardless of how many features i pick... Using `"cpu"` still works fine tho

**EDIT 3**: I should probably mention that I'm running this code on a [p2.xlarge](https://aws.amazon.com/ec2/instance-types/) instance which has a K80 NVIDIA GPU.

**Comment by clinchergt** [comment]
Hey, just touching base here.

It's been almost a week since I opened this issue. Could someone tell me if they could reproduce it?

**Comment by StrikerRUS** [comment]
@huanzhang12 @Laurae2 
Can you please take a look?

**Comment by huanzhang12** [comment]
Try to run the clpeak benchmark and see if it works on GPU: https://github.com/krrishnarraj/clpeak If it doesn't work then something is wrong with your machine.

Can you reinstall CUDA driver? Make sure the latest driver version is installed (currently it is 390.77).

On the other hand, I doubt the K80 GPU will give you any speed up on GPU, because it is quite old and does not support atomic operations in local memory. We recommend using a newer GPU (like NVIDIA P100, AMD VEGA 64, etc).
