### ISSUE TITLE
Debug flag in cmake

### ISSUE THREAD

**Issue by alokpr** [microsoft/LightGBM#1588]
## Environment info

Operating System: x86_64-linux-gnu

CPU: Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz

C++/Python/R version: gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.9)

## Error message

https://github.com/Microsoft/LightGBM/blob/master/CMakeLists.txt#L111

CMakeLists.txt specifies -O3 optimization flag, which makes it difficult to build the library for different build configs. Optimization flag should be defined as part of external build config using CMAKE_BUILD_TYPE=[Debug,Release].

**Comment by guolinke** [comment]
For most users, Debug flags are not needed.
For developers, I think they can aware these flags and able to change them correctly. 

However, having a Debug parameter for cmake is great. PR is welcomed.

**Comment by StrikerRUS** [comment]
Closed in favor of being in #2302. We decided to keep all feature requests in one place.

Welcome to contribute this feature! Please re-open this issue (or post a comment if you are not a topic starter) if you are actively working on implementing this feature.

**Comment by StrikerRUS** [comment]
Added in #2825.
