### ISSUE TITLE
Installing lightgbm for R in windows 7: how to proceed with the .exe file? 

### ISSUE THREAD

**Issue by Quaterion** [Microsoft/LightGBM#1595]
I have successfully followed the steps [here](https://github.com/Microsoft/LightGBM/blob/master/docs/Installation-Guide.rst#visual-studio-or-msbuild) and the .exe file is indeed in the `LightGBM-master/windows/x64/Release` folder. 

Great, but how do I move on from here? Do I need to call `install.packages(lightgbm)` after copying the exe file in another directory? 

Thanks!

**Comment by StrikerRUS** [comment]
Hi @Quaterion !

Please read this: https://github.com/Microsoft/LightGBM/tree/master/R-package#installation

**Comment by StrikerRUS** [comment]
@Quaterion We've refined the R-package installation process in #1499.
Please, try the latest version of the installation guide: https://github.com/Microsoft/LightGBM/tree/master/R-package#installation
