### ISSUE TITLE
For early stopping, at least one dataset and eval metric is required for evaluation

### ISSUE THREAD

**Issue by Drxan** [Microsoft/LightGBM#1597]
## Environment info

Operating System:ubuntu16.04 amd64

CPU: 12  Intel(R) Core(TM) i7-6800K CPU @ 3.40GHz

C++/Python/R version:Python 3.6.5 :: Anaconda, Inc.

## Error message
Traceback (most recent call last):
  File "/home/yw/study/competition/datagrand/hehe.py", line 223, in <module>
    feat_imp=modelfit(lgbc,x,y,cat_vars,cvparams,feature_names,useTrainCV=True,cv_folds=5,early_stopping_rounds=30, metric='f1_macpro')
  File "/home/yw/study/competition/datagrand/hehe.py", line 113, in modelfit
    verbose_eval=20, show_stdv=True, seed=9)
  File "/home/yw/anaconda3/lib/python3.6/site-packages/lightgbm/engine.py", line 459, in cv
    evaluation_result_list=res))
  File "/home/yw/anaconda3/lib/python3.6/site-packages/lightgbm/callback.py", line 197, in callback
    init(env)
  File "/home/yw/anaconda3/lib/python3.6/site-packages/lightgbm/callback.py", line 178, in init
    raise ValueError('For early stopping, at least one dataset and eval metric is required for evaluation')
ValueError: For early stopping, at least one dataset and eval metric is required for evaluation

## Reproducible examples

    from sklearn.datasets import make_classification
    x,y=make_classification(n_samples=1000,n_redundant=0, n_features=20, n_informative=20, n_classes=19,random_state=9)
    x = pd.DataFrame(x,columns=['feat_'+str(i) for i in range(x.shape[1])])

    def modelfit(alg, X, y, cat_features, cvparams, feature_names, folds=None, useTrainCV=True, cv_folds=5,
             early_stopping_rounds=30, metric=metric):
    # feature_names=list(X.columns)
        if useTrainCV == True:
            dtrain = lgb.Dataset(X.values, label=y, reference=None,
                             weight=None, group=None, silent=False, feature_name=feature_names,
                             categorical_feature=cat_features, params=None, free_raw_data=True)
            dtrain.construct()
            cvresult = lgb.cv(cvparams, dtrain, num_boost_round=5000, folds=folds, nfold=cv_folds, stratified=True,
                          metrics=metric, feature_name=feature_names, categorical_feature=cat_features,
                          early_stopping_rounds=early_stopping_rounds,
                          verbose_eval=20, show_stdv=True, seed=9)
        # ,feval=gini_normalized
            alg.set_params(n_estimators=len(cvresult['f1_macro-mean']))
            print('Best Iteration:', len(cvresult['f1_macro-mean']))

    alg.fit(X, y, eval_metric=metric, feature_name=feature_names, categorical_feature=cat_features,
            eval_set=[(X, y)], eval_names=['train'], verbose=20)

    # Predict training set:
    dtrain_predictions = alg.predict(X)

    # Print Mode report:
    print('Model report on trian:')
    print('Train f1:{0:.4f}'.format(np.sqrt(metrics.f1_score(y, dtrain_predictions, average='macro'))))

    feat_imp = pd.Series(alg.feature_importances_, index=X.columns).sort_values(ascending=True)
    # plt.figure()
    # feat_imp.plot(kind='barh',title='Feature Importances',color='green')
    # plt.ylabel('Feature Importance Score')
    lgb.plot_importance(alg, importance_type='gain')
    lgb.plot_metric(alg)
    return feat_imp

    params = {'boosting_type': 'gbdt',
          'colsample_bytree': 1.0,
          'learning_rate': 0.2,
          'max_bin': 255,
          'max_depth': 9,
          'min_child_samples': 1,
          'min_child_weight': 0,
          'min_split_gain': 0,
          'n_estimators': 200,
          'n_jobs': -1,
          'num_leaves': 60,
          'objective': 'multiclass',
          'random_state': 9,
          'reg_alpha': 0,
          'reg_lambda': 0,
          'subsample': 1.0,
          'subsample_freq': 1,
          'num_class': 19
          }

    cvparams = {'boosting_type': 'gbdt',
            'num_leaves': 60,
            'max_depth': 9,
            'learning_rate': 0.2,
            'max_bin': 255,
            'objective': 'multiclass',
            'min_gain_to_split': 0,
            'min_sum_hessian_in_leaf': 0,
            'min_data_in_leaf': 1,
            'bagging_fraction': 1.0,
            'bagging_freq': 1,
            'feature_fraction': 1.0,
            'lambda_l1': 0,
            'lambda_l2': 0,
            'num_threads': -1,
            'num_class': 19
            }
    tran_table = {'min_split_gain': 'min_gain_to_split',
              'min_child_weight': 'min_sum_hessian_in_leaf',
              'min_child_samples': 'min_data_in_leaf',
              'subsample': 'bagging_fraction',
              'subsample_freq': 'bagging_freq',
              'colsample_bytree': 'feature_fraction',
              'reg_alpha': 'lambda_l1',
              'reg_lambda': 'lambda_l2',
              'n_jobs': 'num_threads',

              'boosting_type': 'boosting_type',
              'num_leaves': 'num_leaves',
              'max_depth': 'max_depth',
              'learning_rate': 'learning_rate',
              'max_bin': 'max_bin',
              'objective': 'objective'}

    def get_lgb_params(sklearn_params, cvparams, tran_table):
        for sklearn_param, lgb_param in tran_table.items():
            cvparams[lgb_param] = sklearn_params[sklearn_param]

    cat_vars='auto'
    lgbc=lgb.LGBMClassifier(**params)
    get_lgb_params(lgbc.get_params(),cvparams,tran_table)    modelfit(lgbc,x,y,cat_vars,cvparams,feature_names,useTrainCV=True,cv_folds=5,early_stopping_rounds=30, metric='f1_macpro')

**Comment by Drxan** [comment]
I don't know why this doesn't work

**Comment by StrikerRUS** [comment]
Hi @Drxan !

Please post example with random data, which everyone can run on their machine. https://stackoverflow.com/help/mcve

Also, format your code properly.

**Comment by StrikerRUS** [comment]
Maybe the error is caused by the function definition:
```
def modelfit(alg, X, y, cat_features, cvparams, feature_names, folds=None, useTrainCV=True, cv_folds=5,
early_stopping_rounds=30, metric=metric):
```
```
... metric=metric):
```

**Comment by Drxan** [comment]
Thank you!@StrikerRUS 
you are right,I define a eval function for metric,and it works.
`def f1_macro(preds, train_data):
    labels = train_data.get_label()
    preds = np.transpose(np.reshape(preds, (19, -1)))
    y_pred = np.argmax(preds, axis=1)
    score = metrics.f1_score(labels, y_pred, average='macro')
    return 'f1_macro', score, True
metric = f1_macro`

**Comment by Drxan** [comment]
Thank you!@StrikerRUS 
you are right. the parameter metric should be string or list of string, not function.I define a function and set it to parameter "feval". it works!

**Comment by StrikerRUS** [comment]
Glad you've solved your problem!

What was the reason for reopening the issue?

**Comment by Drxan** [comment]
sorry, i'm unfamiliar with this forum.I'll close this question. @StrikerRUS

**Comment by unnir** [comment]
for those who may come here: 

I fixed that issue with explicitly defining the metric function: 

`'objective': 'binary', `

**Comment by StrikerRUS** [comment]
@unnir Setting `'objective': 'binary',` you are specifying **loss function**, not metric function. By default, metric function is the same as the specified objective one, but you are free to set any metric function(s) you want. You can do it by choosing any predefined metrics and pass their names as strings in `metric` param, or you can create your own metric and pass it as a function via `feval` param.

**Comment by louis925** [comment]
This error message appear whenever you have invalide `metric`.
