### ISSUE TITLE
LightGBM always ends up using Intel Integrated Graphics card rather than the NVIDIA GTX 1060 discrete one that I have

### ISSUE THREAD

**Issue by suraggupta** [Microsoft/LightGBM#1608]
I installed LightGBM on Windows using the instructions from https://lightgbm.readthedocs.io/en/latest/GPU-Windows.html

Now when I try training after setting 

`lgb_model = lgb.LGBMClassifier(nthread=3,silent=False, device = 'gpu')`

![image](https://user-images.githubusercontent.com/20293894/44602689-ecdaba00-a7a5-11e8-89e5-ac4bb236ea02.png)

As seen above, it defaults to my Intel integrated graphics card.

The page https://lightgbm.readthedocs.io/en/latest/GPU-Targets.html states that 

> If you have integrated graphics card (Intel HD Graphics) and a dedicated graphics card (AMD, NVIDIA), the dedicated graphics card will automatically override the integrated graphics card. The workaround is to disable your dedicated graphics card to be able to use your integrated graphics card.

^ According to this, it should automatically default to my NVIDIA card instead of the Integrated card.

Here is a screenshot from GPU Caps Viewer:

![image](https://user-images.githubusercontent.com/20293894/44602770-2e6b6500-a7a6-11e8-98d5-2ba2f5dff1ae.png)

When I train XGBoost, it is able to detect and use the NVIDIA card. I've tried combinations of the `gpu_platform_id` and `gpu_device_id` separately, as an example below:

`lgb_model = lgb.LGBMClassifier(nthread=3,silent=False, device = 'gpu',gpu_platform_id=0, gpu_device_id=0, verbose = 3)`

OR 

`lgb_model = lgb.LGBMClassifier(nthread=3,silent=False, device = 'gpu',gpu_platform_id=-1, gpu_device_id=-1, verbose = 3)`

Could someone point out what could be going on? 

TIA
Surag

**Comment by StrikerRUS** [comment]
@huanzhang12 Your advice is needed

**Comment by huanzhang12** [comment]
Please set gpu_platform_id=1 and gpu_device_id=0

**Comment by suraggupta** [comment]
I could have almost sworn that I had tried that combination. Thank you so much for this. It worked. :)

**Comment by huanzhang12** [comment]
@suraggupta Glad to know it works for you!

I have no idea. I did not write that page. And it seems some information on that page are inaccurate.

@StrikerRUS We should fix the GPU-Targets page. I guess it crashed on one machine (the creator of that page), but such parameter setting (gpu_platform_id=1) is sometimes required.

**Comment by StrikerRUS** [comment]
@huanzhang12 Got it! The source of that html page is [here](https://github.com/Microsoft/LightGBM/blob/master/docs/GPU-Targets.rst).
According to this https://github.com/Microsoft/LightGBM/pull/423, the creator is @Laurae2 (it was quite expected because of R code examples, hehe).

**Comment by huanzhang12** [comment]
Closing this issue now, I opened a pull request #1609 for updating the documents

**Comment by suraggupta** [comment]
@Laurae2 But my first GPU is technically the integrated Graphics card, and I believe it comes under this section:

![image](https://user-images.githubusercontent.com/20293894/44612098-41dcf700-a7cb-11e8-9b88-8aaa2e39e04c.png)

So I'm not sure what I'm missing. My computer would come under the above criteria, right? I have an integrated graphics card (Intel HD Graphics) and a dedicated one (Nvidia GTX 1060).

**Comment by Laurae2** [comment]
@suraggupta do you use a laptop or a desktop?

**Comment by suraggupta** [comment]
@Laurae2 I use a laptop.

**Comment by Laurae2** [comment]
@suraggupta If your laptop does not have G-SYNC, then both GPUs are available (except only one can be used at the same time). Therefore, it is considered as two separate GPUs which cannot override each other (you have 1 CPU + 2 GPU).
