### ISSUE TITLE
ggplot2() crashes R after using lgb.cv() / lgb.train()

### ISSUE THREAD

**Issue by ben519** [Microsoft/LightGBM#1641]
R crashes on me whenever I attempt to do a simple `geom_point()` plot after having trained a lgbm model. Details below.  Note that `ggplot(iris, aes(x = Sepal.Length, y = Petal.Length))` works just fine, but `ggplot(iris, aes(x = Sepal.Length, y = Petal.Length))+geom_point()` causes the crash. Not sure if this issue belongs here or in [ggplot2 issues](https://github.com/tidyverse/ggplot2/issues), but I use ggplot2 *a lot* and I've only seen this behavior in the presence of lightgbm.

Thanks!

## Environment info

Operating System: OS X 10.13.6

CPU: 3.1 GHz Intel Core i7

R version: 3.5.1

## Error message

R Session Aborted. R encountered a fatal error.

<img width="1106" alt="screen shot 2018-09-04 at 5 27 58 pm" src="https://user-images.githubusercontent.com/723099/45061035-45446e00-b068-11e8-9aad-eee80bcb4605.png">

## Reproducible example

```
library(lightgbm)  # version 1.2.1
library(ggplot2)  # version 3.0.0

# Simple lightgbm snippet
data(agaricus.train, package='lightgbm')
train <- agaricus.train
dtrain <- lgb.Dataset(train$data, label=train$label)
params <- list(objective="regression", metric="l2")
model <- lgb.cv(params, dtrain, 10, nfold=5, min_data=1, learning_rate=1, early_stopping_rounds=10)

# Attempt simple plot
ggplot(iris, aes(x = Sepal.Length, y = Petal.Length))+geom_point()
```

**Comment by ben519** [comment]
Note that placing the ggplot() call at the top results in the same behavior (R crashing). That is,

```
library(lightgbm)  # version 1.2.1
library(ggplot2)  # version 3.0.0

# Attempt simple plot
ggplot(iris, aes(x = Sepal.Length, y = Petal.Length))+geom_point()

# Simple lightgbm snippet
data(agaricus.train, package='lightgbm')
train <- agaricus.train
dtrain <- lgb.Dataset(train$data, label=train$label)
params <- list(objective="regression", metric="l2")
model <- lgb.cv(params, dtrain, 10, nfold=5, min_data=1, learning_rate=1, early_stopping_rounds=10)
```
also crashes R

**Comment by ben519** [comment]
UPDATE

I initially installed lightgbm using Apple Clang, following the instructions [here](https://github.com/Microsoft/LightGBM/tree/master/R-package).  After re-installing using gcc7, the above code works as I'd expect it to.

**Comment by StrikerRUS** [comment]
Glad that you've managed to make LightGBM work.

I suppose this is connected to the conflict between shared libraries.

Possibly related issues: #1444, Question 10 in our [FAQ](https://lightgbm.readthedocs.io/en/latest/FAQ.html#lightgbm).
