### ISSUE TITLE
Impact of redundant features

### ISSUE THREAD

**Issue by psinger** [Microsoft/LightGBM#1659]
In my data, I have a few features which are constant in the training data and thus, should be redundant. Yet, depending on whether I include them when using LightGBM or not, impacts the results, usually with better results on those models that exclude them. Sometimes the differences are only extremely minor, but I have also seen some larger impacts.

I am struggling in understanding how this can happen. From my understanding the trees should never split for constant features anyways.

Code for exclusing features and LightGBM model currently look like:

```
import lightgbm as lgb
from sklearn.feature_selection import VarianceThreshold
pipeline = Pipeline(memory=None,
        steps=[
            ('variance_threshold', VarianceThreshold(0.0)),
            ('clf', lgb.LGBMRegressor(n_estimators=100))
        ])
```

**Comment by guolinke** [comment]
@psinger yeah, the constant features should be ignored by lightgbm.
Did you use the `feature_fraction`(sub_feature) ? 
If yes, that is possible, as LightGBM use original feature index to sample features.

**Comment by StrikerRUS** [comment]
ping @psinger

**Comment by psinger** [comment]
@psinger Don't have the data at hand any longer unfortunately, but I did not use feature sampling. But issue can be closed, I will re-ping if I identify issue again.

**Comment by StrikerRUS** [comment]
@psinger Thanks for letting us know! Of course, feel free to reopen in case it'll happen again.
