### ISSUE TITLE
understanding the lightGBM  algorithm

### ISSUE THREAD

**Issue by hrkrx** [Microsoft/LightGBM#1667]
I want to make some visualizations for my lightGBM models. 

So i thought it would be cool to see the improvement of a decision with the growing number of weak learners (trees)

I think i understand the basic concept of gradient boosted decision trees.
But what i don't understand is how does lightGBM adds up the weak learners when the objective is multiclass, to get the probabilities for each class?

In detail:
I want to know if the trees are linked in any particular way, or if the are just sequential.
So, for example if i have 100 trees per class, that the first 100 are for class 0, the next 100 are for class 1 and so on.

**Comment by henry0312** [comment]
Did you read https://github.com/Microsoft/LightGBM/blob/master/docs/Features.rst?

**Comment by hrkrx** [comment]
I think i should've been more precise here with what i mean:

I have a trained model:

```
tree
version=v2
num_class=10
[...]

Tree=0
[...]

Tree=1
[...]

Tree=999
[...]

feature importances:
[...]

parameters:
[boosting: gbdt]
[objective: multiclass]
[...]
[num_iterations: 100]
[...]
```

In which order are the Trees 0 to 999 assigned to one of the 10 classes?

**Comment by guolinke** [comment]
@hrkrx LightGBM use one-vs-rest fashion for multi-class. you can view it as 10 binary classification tasks, so there are 10 GBDTs, each with 100 trees.
