### ISSUE TITLE
how to specify new gcc path for cmake using gcc_6.2.0 in CentOS

### ISSUE THREAD

**Issue by PerfectWzp** [Microsoft/LightGBM#167]
[](For bugs and unexpected issues, please provide the following information, so that we could reproduce in our system)

## Environment info
Operating System:CentOS release 6.2
CPU:Intel(R) Xeon(R) CPU E5606  @ 2.13GHz, 8 cores

## Error Message:
( in LightGBM/build) 
cmake -DCMAKE_C_COMPILER="/home/wzp/workspace/software/gcc_620_wzp/bin/gcc" -DCMAKE_CXX_COMPILER="/home/wzp/workspace/software/gcc_620_wzp/bin/g++" ..

-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
-- Check for working C compiler: /home/wzp/workspace/software/gcc_620_wzp/bin/gcc
-- Check for working C compiler: /home/wzp/workspace/software/gcc_620_wzp/bin/gcc -- broken
CMake Error at /usr/local/share/cmake-2.8/Modules/CMakeTestCCompiler.cmake:61 (message):
  The C compiler "/home/wzp/workspace/software/gcc_620_wzp/bin/gcc"
  is not able to compile a simple test program.

  It fails with the following output:

   Change Dir: /home/wzp/work/LightGBM/build/CMakeFiles/CMakeTmp

  Run Build Command:/usr/bin/gmake "cmTryCompileExec377371663/fast"

  /usr/bin/gmake -f CMakeFiles/cmTryCompileExec377371663.dir/build.make
  CMakeFiles/cmTryCompileExec377371663.dir/build

  gmake[1]: Entering directory
  `/home/wzp/work/LightGBM/build/CMakeFiles/CMakeTmp'

  /usr/local/bin/cmake -E cmake_progress_report
  /home/wzp/work/LightGBM/build/CMakeFiles/CMakeTmp/CMakeFiles 1

  Building C object
  CMakeFiles/cmTryCompileExec377371663.dir/testCCompiler.c.o

  /home/wzp/workspace/software/gcc_620_wzp/bin/gcc -o
  CMakeFiles/cmTryCompileExec377371663.dir/testCCompiler.c.o -c
  /home/wzp/work/LightGBM/build/CMakeFiles/CMakeTmp/testCCompiler.c

  
  /home/wzp/workspace/software/gcc_620_wzp/libexec/gcc/x86_64-pc-linux-gnu/6.2.0/cc1:
  error while loading shared libraries: libmpc.so.2: cannot open shared
  object file: No such file or directory

  gmake[1]: Leaving directory
  `/home/wzp/work/LightGBM/build/CMakeFiles/CMakeTmp'

  gmake[1]: *** [CMakeFiles/cmTryCompileExec377371663.dir/testCCompiler.c.o]
  错误 1

  gmake: *** [cmTryCompileExec377371663/fast] 错误 2

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:3 (PROJECT)

-- Configuring incomplete, errors occurred!
See also "/home/wzp/work/LightGBM/build/CMakeFiles/CMakeOutput.log".
See also "/home/wzp/work/LightGBM/build/CMakeFiles/CMakeError.log".

___________________________________________________________________

____________________________________CMakeFiles/CMakeError.log______________________________________________

Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
Compiler: /home/wzp/workspace/software/gcc_620_wzp/bin/gcc
Build flags:
Id flags:

The output was:
1
/home/wzp/workspace/software/gcc_620_wzp/libexec/gcc/x86_64-pc-linux-gnu/6.2.0/cc1: error while loading shared libraries: libmpc.so.2: cannot open shared object file: No such file or directory

Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
Compiler: /home/wzp/workspace/software/gcc_620_wzp/bin/gcc
Build flags:
Id flags: -c

The output was:
1
/home/wzp/workspace/software/gcc_620_wzp/libexec/gcc/x86_64-pc-linux-gnu/6.2.0/cc1: error while loading shared libraries: libmpc.so.2: cannot open shared object file: No such file or directory

Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
Compiler: /home/wzp/workspace/software/gcc_620_wzp/bin/gcc
Build flags:
Id flags: -Aa

The output was:
1
/home/wzp/workspace/software/gcc_620_wzp/libexec/gcc/x86_64-pc-linux-gnu/6.2.0/cc1: error while loading shared libraries: libmpc.so.2: cannot open shared object file: No such file or directory

Checking whether the C compiler is IAR using "" did not match "IAR .+ Compiler":
gcc: 致命错误：没有输入文件
编译中断。
Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
Compiler: /home/wzp/workspace/software/gcc_620_wzp/bin/g++ 
Build flags: 
Id flags: 

The output was:
1/home/wzp/workspace/software/gcc_620_wzp/libexec/gcc/x86_64-pc-linux-gnu/6.2.0/cc1plus: error while loading shared libraries: libmpc.so.2: cannot open shared object file: No such file or directory

Checking whether the CXX compiler is IAR using "" did not match "IAR .+ Compiler":
g++: 致命错误：没有输入文件
编译中断。
Determining if the C compiler works failed with the following output:
Change Dir: /home/wzp/work/LightGBM/build/CMakeFiles/CMakeTmp

Run Build Command:/usr/bin/gmake "cmTryCompileExec3929218552/fast"
/usr/bin/gmake -f CMakeFiles/cmTryCompileExec3929218552.dir/build.make CMakeFiles/cmTryCompileExec3929218552.dir/build
gmake[1]: Entering directory `/home/wzp/work/LightGBM/build/CMakeFiles/CMakeTmp'
/usr/local/bin/cmake -E cmake_progress_report /home/wzp/work/LightGBM/build/CMakeFiles/CMakeTmp/CMakeFiles 1
Building C object CMakeFiles/cmTryCompileExec3929218552.dir/testCCompiler.c.o
/home/wzp/workspace/software/gcc_620_wzp/bin/gcc    -o CMakeFiles/cmTryCompileExec3929218552.dir/testCCompiler.c.o   -c /home/wzp/work/LightGBM/build/CMakeFiles/CMakeTmp/testCCompiler.c
/home/wzp/workspace/software/gcc_620_wzp/libexec/gcc/x86_64-pc-linux-gnu/6.2.0/cc1: error while loading shared libraries: libmpc.so.2: cannot open shared object file: No such file or directory
gmake[1]: Leaving directory `/home/wzp/work/LightGBM/build/CMakeFiles/CMakeTmp'
gmake[1]: *** [CMakeFiles/cmTryCompileExec3929218552.dir/testCCompiler.c.o] 错误 1
gmake: *** [cmTryCompileExec3929218552/fast] 错误 2

## Reproducible examples
I installed gcc-6.2.0 into "/home/wzp/workspace/software/gcc_620_wzp".
```
wget https://ftp.gnu.org/gnu/gcc/gcc-6.2.0/gcc-6.2.0.tar.bz2
tar -jxvf  gcc-6.2.0.tar.bz2
install gmp/mpfr/mpc
```

I already turn to below websites and tried all methods, but no solution.
http://stackoverflow.com/questions/17275348/how-to-specify-new-gcc-path-for-cmake
http://stackoverflow.com/questions/11588855/how-do-you-set-cmake-c-compiler-and-cmake-cxx-compiler-for-building-assimp-for-i

## Steps to reproduce

1. git clone --recursive https://github.com/Microsoft/LightGBM ; cd LightGBM
2. mkdir build ; cd build
3. cmake -DCMAKE_C_COMPILER="/home/wzp/workspace/software/gcc_620_wzp/bin/gcc" -DCMAKE_CXX_COMPILER="/home/wzp/workspace/software/gcc_620_wzp/bin/g++" ..

**Comment by guolinke** [comment]
I think it is a cmake issue..
Did you try following:
```
export CC=/usr/local/bin/gcc
export CXX=/usr/local/bin/g++
cmake /path/to/your/project
```

if still not work, maybe you didn't install gcc correctly.

And this error may be the main reason:
`/home/wzp/workspace/software/gcc_620_wzp/libexec/gcc/x86_64-pc-linux-gnu/6.2.0/cc1: error while loading shared libraries: libmpc.so.2:`

http://stackoverflow.com/questions/19625451/cc1-error-while-loading-shared-libraries-libmpc-so-2-cannot-open-shared-objec

**Comment by PerfectWzp** [comment]
Thank you for your solution, I alreay run `cmake` and `make -j` successfully.

The problem comes from below error, I forget to set LD_LIBRARY_PATH to reference my own mpc.
"/home/wzp/workspace/software/gcc_620_wzp/libexec/gcc/x86_64-pc-linux-gnu/6.2.0/cc1: **error while loading shared libraries: libmpc.so.2: cannot open shared object file: No such file or directory**"

My error disappeared after I issued the following commands.
```
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/wzp/workspace/software/mpc_081_wzp/lib
```

Now the correct steps are as following:

```
1. git clone --recursive https://github.com/Microsoft/LightGBM ; cd LightGBM
2. mkdir build ; cd build
3. export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/wzp/workspace/software/mpc_081_wzp/lib
4. cmake -DCMAKE_C_COMPILER="/home/wzp/workspace/software/gcc_620_wzp/bin/gcc" -DCMAKE_CXX_COMPILER="/home/wzp/workspace/software/gcc_620_wzp/bin/g++" ..
5. make -j
```
