### ISSUE TITLE
dump_model() leaf nodes missing class for multiclass

### ISSUE THREAD

**Issue by calebmadrigal** [Microsoft/LightGBM#1675]
The dump_model() function outputs JSON representing the model, and it works great for binary classification, but for multiclass classification problems, the JSON representing the leaf nodes doesn't appear to contain the data necessary to tell which class the value is being added to. Here is what the leaf nodes look like for a 4-class classification model:

```
    "left_child": {
        "leaf_index": 9,
        "leaf_value": 2.824074270431741e-05,
        "leaf_count": 28
    },

    "left_child": {
        "leaf_index": 10,
        "leaf_value": -0.05756293935599476,
        "leaf_count": 37
    },

    "right_child": {
        "leaf_index": 19,
        "leaf_value": -0.0596629916292374,
        "leaf_count": 27
    }
```

So if I'm trying to run this model from this data, I don't know which class the leaf_value should be applied to. I would expect something like `{0: 0.0439}` or `{2: -0.02923}` where the key indicates which class the value is being added to (or some other way of indicating which class involved). Of course, for binary classification this isn't needed, but for multiclass, it is.

So am I missing something, or does the dump_model() function simply not output all necessary data for executing the model?

Sample program which dumps a 4-class classifier:

```
from sklearn.datasets import make_classification
import lightgbm as lgb

num_classes = 4

X_multiclass, y_multiclass = make_classification(n_samples=1000, n_features=3, n_classes=num_classes,
                             n_informative=3, n_redundant=0,
                             random_state=0, shuffle=False)

lgb_train_multiclass = lgb.Dataset(X_multiclass, y_multiclass)

params_multiclass = {
    'boosting_type': 'gbdt',
    'objective': 'multiclass',
    'num_class': num_classes,
    'verbose': 0
}

gbm_multiclass = lgb.train(params_multiclass,
                           lgb_train_multiclass,
                           num_boost_round=10,
                           valid_sets=lgb_train_multiclass)

import pprint
pprint.pprint(gbm_multiclass.dump_model())

```

**Comment by guolinke** [comment]
refer to https://github.com/Microsoft/LightGBM/issues/1667 
https://github.com/Microsoft/LightGBM/issues/1518

**Comment by calebmadrigal** [comment]
@guolinke Thanks, I get it.
