### ISSUE TITLE
Silent failure when sparse training matrix has > 2^31 non-zero elements

### ISSUE THREAD

**Issue by bauks** [Microsoft/LightGBM#1689]
When training data is in the form of a scipy.sparse.csr_matrix and the number of non-zero values exceeds 2^31 - 1 (haven't checked precisely but max_int32 is the only thing that makes sense here), model predictions suddenly become awful. I strongly suspect there's a 32 bit integer used as an index into the non-zero elements of the sparse matrix, which ends up mixing up data from different columns incoherently.  

## Environment info
Operating System: Ubuntu 14.04.4
CPU: 4x Intel Xeon 24 core processors
Python version: 2.7.6
LightGBM built from source on commit 44ed4270eef68f0dd2ba093d4e5aa34460ddeecc

## Reproducible examples
Note the predictions improve as we add more training data until the number of non-zero entries is too large, at which point the predictions are very close to 0.5 and the model is providing essentially no predictive power:
![results_1000](https://user-images.githubusercontent.com/43455488/45850511-4d98dc00-bceb-11e8-8bc2-073880a2f7f0.png)
![results_10000](https://user-images.githubusercontent.com/43455488/45850512-4d98dc00-bceb-11e8-8348-0ab75a2a2485.png)
![results_100000](https://user-images.githubusercontent.com/43455488/45850513-4d98dc00-bceb-11e8-9442-572f0ae5b25a.png)
![results_5300000](https://user-images.githubusercontent.com/43455488/45850514-4d98dc00-bceb-11e8-800f-4a91f732614f.png)
![results_5400000](https://user-images.githubusercontent.com/43455488/45850515-4d98dc00-bceb-11e8-923c-ea2bb82ba206.png)

## Script to produce examples:
```
import matplotlib
matplotlib.use('Agg')

import numpy as np
import lightgbm as lgb
import scipy.sparse
from scipy.special import logit, expit
import matplotlib.pyplot as plt

np.random.seed(0)

def true_proba(X):
    return X[:, 0]

def simulate_y(X):
    probs = true_proba(X)
    return (np.random.random(len(X)) < probs)

def simulate_X(nrows, n_sparse_cols, non_zero_frac):
    X = np.zeros((nrows, n_sparse_cols + 1))
    X[:, 0] = np.random.random(nrows)
    for i in range(n_sparse_cols):
        X[:, i+1] = (np.random.random(nrows) < non_zero_frac)
    return X

def get_data(nrows, n_sparse_cols, non_zero_frac):
    X = simulate_X(nrows, n_sparse_cols, non_zero_frac)
    y = simulate_y(X)
    X = scipy.sparse.csr_matrix(X)
    return X, y

def run_study(figfile, params, nrows, n_sparse_cols, non_zero_frac=0.2, n_test=1000):
    X, y = get_data(nrows, n_sparse_cols, non_zero_frac)
    print "With %s rows, got %s non-zero entries"%(nrows, X.nnz)
    data = lgb.Dataset(X, label=y)
    model = lgb.train(params, data, num_boost_round=10)
    X_test = simulate_X(n_test, n_sparse_cols, non_zero_frac)
    preds = model.predict(X_test)
    plt.plot(true_proba(X_test), preds, 'o')
    plt.title("nnz in train = %s"%(X.nnz))
    plt.xlabel("True probability")
    plt.ylabel("Model prediction")
    plt.savefig(figfile)
    plt.clf()

params = {
    'learning_rate': 1.0,
    'objective': 'binary',
    'max_depth': 2,
}

for nrows in [1000, 10000, 100000, 5400000, 5300000]:
    run_study('results_%s.png'%(nrows), params, nrows, 2000)
```

I'll be happy to provide further environment information if needed and can re-run modified versions of the script if more output or model information is needed.

**Comment by StrikerRUS** [comment]
@bauks Thank you for reporting this and special thanks for the reproducible example!

Unfortunately, I can't run your snippet even for `nrow=5400000` due to the lack of the RAM. How much RAM is on your machine?

@guolinke From the Python side my assumption is only this line:
https://github.com/Microsoft/LightGBM/blob/44ed4270eef68f0dd2ba093d4e5aa34460ddeecc/python-package/lightgbm/basic.py#L884

**Comment by bauks** [comment]
@StrikerRUS Yes unfortunately the example uses about 90GB of RAM. I used a machine with around 360GB of RAM. I tried reducing the memory usage by constructing the sparse matrix directly instead of from the full 2d matrix, but it ends up using a similar amount of memory.

**Comment by StrikerRUS** [comment]
@bauks Hmmm, I tested on the machine with 112GB. Will try again.

**Comment by StrikerRUS** [comment]
@bauks BTW, is this issue presented in case of dense data (numpy/pandas)?

**Comment by bauks** [comment]
@StrikerRUS Hmm this script tries to use only as much memory as is required but I didn't see a noticeable drop in memory consumption (still around 90GB):

```
import gc
import matplotlib
matplotlib.use('Agg')

import numpy as np
import lightgbm as lgb
import scipy.sparse
from scipy.special import logit, expit
import matplotlib.pyplot as plt

np.random.seed(0)

def true_proba(X):
    return X[:, 0].toarray()[:, 0]

def simulate_y(X):
    probs = true_proba(X)
    return (np.random.random(X.shape[0]) < probs)

def simulate_X(nrows, n_sparse_cols, non_zero_frac):
    # Pre-allocate enough to confidently hold all non-zero elements
    n_rand_expected = nrows * n_sparse_cols * non_zero_frac
    nalloc = int(nrows + n_rand_expected + 5 * np.sqrt(n_rand_expected))
    data = np.ones(nalloc, dtype=np.float32) # We can leave the sparse data as ones
    row_ind = np.zeros(nalloc, dtype=np.int32)
    col_ind = np.zeros(nalloc, dtype=np.int32)

    # Setup the single dense column
    data[:nrows] = np.random.random(nrows).astype(np.float32)
    row_ind[:nrows] = np.arange(nrows, dtype=np.int32)
    col_ind[:nrows] = np.zeros(nrows, dtype=np.int32)
    ndata = nrows

    # Add the sparse columns
    row_range = np.arange(nrows, dtype=np.int32)
    for i in range(n_sparse_cols):
        new_col = (np.random.random(nrows) < non_zero_frac)
        n = new_col.sum()
        row_ind[ndata:ndata + n] = row_range[new_col]
        col_ind[ndata:ndata + n] = (i+1) * np.ones(n, dtype=np.int32)
        ndata += n
        if i%10 == 0:
            gc.collect()

    assert ndata <= nalloc
    return scipy.sparse.csr_matrix((data[:ndata], (row_ind[:ndata], col_ind[:ndata])))

def get_data(nrows, n_sparse_cols, non_zero_frac):
    X = simulate_X(nrows, n_sparse_cols, non_zero_frac)
    y = simulate_y(X)
    return X, y

def run_study(figfile, params, nrows, n_sparse_cols, non_zero_frac=0.2, n_test=1000, dense=False):
    X, y = get_data(nrows, n_sparse_cols, non_zero_frac)
    print "With %s rows, got %s non-zero entries"%(nrows, X.nnz)
    if dense:
        X = X.toarray()
        print "Dense X has shape {}".format(X.shape)
    data = lgb.Dataset(X, label=y, free_raw_data=True)
    model = lgb.train(params, data, num_boost_round=10)
    X_test = simulate_X(n_test, n_sparse_cols, non_zero_frac)
    preds = model.predict(X_test)
    plt.plot(true_proba(X_test), preds, 'o')
    if hasattr(X, 'nnz'):
        nnz = X.nnz
    else:
        nnz = (X != 0).sum()
    plt.title("nnz in train = %s"%(nnz))
    plt.xlabel("True probability")
    plt.ylabel("Model prediction")
    plt.savefig(figfile)
    plt.clf()

params = {
    'learning_rate': 1.0,
    'objective': 'binary',
    'max_depth': 2,
}

for nrows in [1000, 10000, 100000, 5400000, 5300000]:
    #run_study('results_%s.png'%(nrows), params, nrows, 1000, non_zero_frac=0.4, dense=True)
    run_study('results_%s.png'%(nrows), params, nrows, 2000)
```

Note the 2nd last line is commented out but converts to dense numpy matrices before passing the training data to lightgbm. When I run that version and comment out the last line, I find that even when the number of non-zero elements is larger than 2**31 the model behaves well, so this seems like just an issue with initializing from sparse matrices:
![results_5400000](https://user-images.githubusercontent.com/43455488/45978858-2b140500-c002-11e8-9d96-8722a3435c05.png)

**Comment by StrikerRUS** [comment]
@bauks Unfortunately, your code fails on my machine at the step with `nrows=5400000`:
```
C:\Miniconda3\lib\site-packages\ipykernel_launcher.py:29: RuntimeWarning: overflow encountered in long_scalars
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-e5eec86a161e> in <module>()
      7 for nrows in [1000, 10000, 100000, 5400000, 5300000]:
      8     #run_study('results_%s.png'%(nrows), params, nrows, 1000, non_zero_frac=0.4, dense=True)
----> 9     run_study(params, nrows, 2000)

<ipython-input-2-535e61a28d6b> in run_study(params, nrows, n_sparse_cols, non_zero_frac, n_test, dense)
     42 
     43 def run_study(params, nrows, n_sparse_cols, non_zero_frac=0.2, n_test=1000, dense=False):
---> 44     X, y = get_data(nrows, n_sparse_cols, non_zero_frac)
     45     print("With %s rows, got %s non-zero entries"%(nrows, X.nnz))
     46     if dense:

<ipython-input-2-535e61a28d6b> in get_data(nrows, n_sparse_cols, non_zero_frac)
     37 
     38 def get_data(nrows, n_sparse_cols, non_zero_frac):
---> 39     X = simulate_X(nrows, n_sparse_cols, non_zero_frac)
     40     y = simulate_y(X)
     41     return X, y

<ipython-input-2-535e61a28d6b> in simulate_X(nrows, n_sparse_cols, non_zero_frac)
     27         new_col = (np.random.random(nrows) < non_zero_frac)
     28         n = new_col.sum()
---> 29         row_ind[ndata:ndata + n] = row_range[new_col]
     30         col_ind[ndata:ndata + n] = (i+1) * np.ones(n, dtype=np.int32)
     31         ndata += n

ValueError: could not broadcast input array from shape (1080249) into shape (0)
```

**Comment by StrikerRUS** [comment]
@bauks BTW, why not to create sparse matrix simply by https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.random.html#scipy-sparse-random ?

**Comment by bauks** [comment]
@StrikerRUS Thanks for pointing out scipy.sparse.random, that leads to much more simple code. The simulate_X function can be replaced with:
```
def simulate_X(nrows, n_sparse_cols, non_zero_frac):
    dense_col = scipy.sparse.csr_matrix(np.random.random((nrows, 1)).astype(np.float32))
    sparse_random = scipy.sparse.random(nrows, n_sparse_cols, density=non_zero_frac,
                                        format='csr', dtype=np.float32)
    return scipy.sparse.hstack([dense_col, sparse_random], format='csr')
```
Unfortunately it looks like this method is slower and requires more memory; it used around 140GB and took 2 hours to run the 5400000 case. The results are similar, with the 5400000 case showing very poor predictions. If you have a suitable machine you could try running it; perhaps the error you encountered before won't show up.

Do you know if that warning was only for the 5400000 case? If so perhaps it's related to the failure. The failure indicates `row_range[new_col]` has shape (1080249), so we should also have `n = 1090249`. For row_ind[ndata:ndata + n] to have shape (0) it would mean we somehow did not allocate enough rows in row_ind, which would be quite startling (at 5 sigma) unless there's a bug somewhere else or something related to the warning is affecting row_ind.

Could you print out nalloc, data.shape, row_ind.shape and col_ind.shape after allocating them? You could also double the size of nalloc before creating the arrays for safety. And perhaps within the loop, just before the line that failed, print out row_ind.shape, ndata, n, row_range.shape, new_col.shape, and row_range[new_col].shape.

**Comment by guolinke** [comment]
@StrikerRUS 
I checked the cpp code, and think it is fine..

I don't have a machine to test that, can you provide the types
```
        ptr_indptr, type_ptr_indptr, __ = c_int_array(csr.indptr)
        ptr_data, type_ptr_data, _ = c_float_array(csr.data)
```
in https://github.com/Microsoft/LightGBM/blob/master/python-package/lightgbm/basic.py#L888-L889

especially for  type_ptr_indptr. 
Thanks very much.

**Comment by bauks** [comment]
Hi @guolinke,

Hopefully the following helps:
csr.shape is (5400000, 2001)
csr.data is a numpy array with length 2165402340 and dtype float32.
csr.indices is a numpy array with length 2165402340 and dtype int64.
csr.indptr is a numpy array with length 5400001 and dtype int64.

Running
```
ptr_indptr, type_ptr_indptr, __ = c_int_array(csr.indptr)
ptr_data, type_ptr_data, _ = c_float_array(csr.data)
```
gives
type_ptr_indptr = 3,
type_ptr_data = 0,
type(ptr_indptr) = lightgbm.basic.LP_c_long,
type(ptr_data) = lightgbm.basic.LP_c_float
