### ISSUE TITLE
Model file doesn't specify the label index ? 

### ISSUE THREAD

**Issue by senadibraimoski** [Microsoft/LightGBM#1691]
Hi all,

I get this error when using the library to do regression. I am using the sklearn wrapper where I instantiate the Regressor and call something like this:

``` 
def regression_train(self, indices: numpy.array, Xs: numpy.array, ys: numpy.array):
        self.model.fit(Xs, ys)
def regression_predict(self, indices: numpy.array, Xs: numpy.array) -> numpy.array:
        return self.model.predict(Xs)
```

And I get this error. I could not find the documentation that will help me a bit and when I run the provided sklearn example it works I guess - so its really wierd and I lost a lot of time trying to find out what is happening: 

```    
raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))
lightgbm.basic.LightGBMError: Model file doesn't specify the label index
```

## Environment info

Operating System:  High Sierra (MAC)

CPU: 2.2 GHz Intel Core i7

C++/Python/R version: g++-8, python3.6

## Error message

```    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))
lightgbm.basic.LightGBMError: Model file doesn't specify the label index
```

**Comment by guolinke** [comment]
I think it is something wrong here: https://github.com/Microsoft/LightGBM/blob/7825084f160f3f8093cef3fdd13d1e49351e9e13/python-package/lightgbm/engine.py#L235

@senadibraimoski can you provide a reproduce example with random generated data ?

**Comment by StrikerRUS** [comment]
ping @senadibraimoski

**Comment by senadibraimoski** [comment]
Could not reproduce this with random data using example script.

**Comment by harshakokel** [comment]
I am getting similar error. Any insight on what may be wrong.

I get it when I am loading a light gbm model from string, in python.
