### ISSUE TITLE
mean prediction for data with all constant features

### ISSUE THREAD

**Issue by pseudotensor** [Microsoft/LightGBM#1697]
Getting this even if follow the advice.  Certainly this particular case has a constant column, but LightGBM should predict the average model at least as a last resort, not result in a fatal error in this simplest case.

[lgb_min_data_issue.zip](https://github.com/Microsoft/LightGBM/files/2412973/lgb_min_data_issue.zip)

**Comment by pseudotensor** [comment]
Params used,  note that min_data_in_bin=1 and min_child_samples=1 (sklearn default for min_data).
```
LGBMRegressor(bagging_seed=4959091, boosting_type='gbdt', class_weight=None,
       colsample_bytree=0.9, device_type='cpu',
       feature_fraction_seed=4959090, gpu_device_id=0, gpu_platform_id=0,
       importance_type='gain', learning_rate=0.05, max_bin=255,
       max_delta_step=0.0, max_depth=5, min_child_samples=1,
       min_child_weight=1, min_data_in_bin=1, min_split_gain=0.0,
       n_estimators=600, n_jobs=4, num_class=1, num_leaves=32,
       objective='regression', random_state=None, reg_alpha=0.0,
       reg_lambda=2.0, scale_pos_weight=1.0, silent=True, subsample=0.5,
       subsample_for_bin=200000, subsample_freq=1, verbose=2)
```

**Comment by guolinke** [comment]
@pseudotensor Do you mean that all columns are constants?

**Comment by pseudotensor** [comment]
Yes

**Comment by pseudotensor** [comment]
Any way this can be fixed.  Any reasonable model should be able to predict the "average" for regression or the most frequent for classification.

**Comment by Laurae2** [comment]
@guolinke is there any way to bypass the "not useful feature" option?

**Comment by pseudotensor** [comment]
One can use xgboost as backup, but a bit silly.

**Comment by guolinke** [comment]
@pseudotensor you can check the fixes in #1735

**Comment by psinger** [comment]
Might this have also been the reason for https://github.com/Microsoft/LightGBM/issues/1659 ?

**Comment by guolinke** [comment]
@psinger I think they are irrelevant. This is for the situation that all features are constants.
