### ISSUE TITLE
failure bilding lightgbm for R when using "classical approach"

### ISSUE THREAD

**Issue by spedygiorgio** [Microsoft/LightGBM#1702]
Hi, I have R 3.5.1. I successful compiled a dll for GPU support that I moved in the main Lightgm folder.
In order to compile the package I run Rscipt build_r.R after having modified install_libs.R setting `use_precompile <- TRUE`. 
First question:

1. I want to use GPU and I have precompiled a DLL. I have NOT set `use_gpu <- TRUE` keeping it to false since I assumed that GPU will be handled by the DLL (am I right?). Or shall in every case set 
`use_gpu <- TRUE`?
2. Is it correct to call cmake `cmake -DCMAKE_GENERATOR_PLATFORM=x64 -DUSE_R35=ON -DUSE_GPU=1 .. to take into account R version 3.5?`
3. I receive the following errors when running: `Rscript build_r.R`

```
Updating lightgbm documentation
Loading lightgbm
Re-compiling lightgbm
"C:/PROGRA~1/R/R-35~1.1/bin/x64/R" --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD INSTALL "z:\LightGBM\lightgbm_r"  \
  --library="Z:\TEMP\RtmpYZJOTL\devtools_install_368847da40a3" --no-R  \
  --no-data --no-help --no-demo --no-inst --no-docs --no-exec --no-multiarch  \
  --no-test-load --preclean

In R CMD INSTALL
* installing *source* package 'lightgbm' ...
** libs
c:/Rtools/mingw_64/bin/gcc  -I"C:/PROGRA~1/R/R-35~1.1/include" -DNDEBUG          -O2 -Wall  -std=gnu99 -mtune=generic -c R_init.c -o R_init.o
c:/Rtools/mingw_64/bin/gcc -shared -s -static-libgcc -o lightgbm.dll tmp.def R_init.o -LC:/PROGRA~1/R/R-35~1.1/bin/x64 -lR
installing via 'install.libs.R' to Z:/TEMP/RtmpYZJOTL/devtools_install_368847da40a3/lightgbm
Found library file: z:/LightGBM/lightgbm_r/../lib_lightgbm.dll to move to Z:/TEMP/RtmpYZJOTL/devtools_install_368847da40a3/lightgbm/libs/x64* DONE (lightgbm)
Loading required package: R6
Error in getDLLRegisteredRoutines.DLLInfo(dll, addNames = FALSE) :
  must specify DLL via a "DLLInfo" object. See getLoadedDLLs()
Calls: <Anonymous> ... assignNativeRoutines -> getDLLRegisteredRoutines.DLLInfo
```

Thanks in advance for the support

**Comment by BruceZhaoR** [comment]
@spedygiorgio  you can see #1678 and read the code  https://github.com/Laurae2/lgbdl/blob/master/R/lgb.dl.R

## 1. You have precompiled GPU dll
JUST SET `use_precompile <- TRUE`  and make sure your precompiled files are in the following dirs
 `eg. R_PACKAGE_SOURCE = "C:\LightGBM\R-package"`

https://github.com/Microsoft/LightGBM/blob/7825084f160f3f8093cef3fdd13d1e49351e9e13/R-package/src/install.libs.R#L87-L95

## for question 2

```shell
cmake -DCMAKE_GENERATOR_PLATFORM=x64 -DUSE_R35=ON -DUSE_GPU=1
```
is the right command for compile GPU dll

https://github.com/Microsoft/LightGBM/blob/7825084f160f3f8093cef3fdd13d1e49351e9e13/R-package/src/install.libs.R#L40-L42

## for question 3
make sure you copied `CMakeLists.txt` to `R-package\inst\bin` , and config the `R-package\src\install.libs.R`, then in the R console run 
```r
install.packages(file.path("C:", "LightGBM", "R-package"), repos = NULL, type = "source")
```

<details>

```r
> install.packages(file.path("C:", "LightGBM", "R-package"), repos = NULL, type = "source")
Installing package into ‘E:/R/R-3.5-library’
(as ‘lib’ is unspecified)
* installing *source* package 'lightgbm' ...
** libs
c:/Rtools/mingw_64/bin/gcc  -I"E:/R/R-3.5.1/include" -DNDEBUG          -O2 -Wall  -std=gnu99 -mtune=generic -c R_init.c -o R_init.o
c:/Rtools/mingw_64/bin/gcc -shared -s -static-libgcc -o lightgbm.dll tmp.def R_init.o -LE:/R/R-3.5.1/bin/x64 -lR
installing via 'install.libs.R' to E:/R/R-3.5-library/lightgbm
Found library file: C:/LightGBM/R-package/../lib_lightgbm.dll to move to E:/R/R-3.5-library/lightgbm/libs/x64** R
** data
** demo
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'lightgbm'
    finding HTML links ... done
    agaricus.test                           html  
    agaricus.train                          html  
    bank                                    html  
    dim                                     html  
    dimnames.lgb.Dataset                    html  
    getinfo                                 html  
    lgb.Dataset                             html  
    lgb.Dataset.construct                   html  
    lgb.Dataset.create.valid                html  
    lgb.Dataset.save                        html  
    lgb.Dataset.set.categorical             html  
    lgb.Dataset.set.reference               html  
    lgb.cv                                  html  
    lgb.dump                                html  
    lgb.get.eval.result                     html  
    lgb.importance                          html  
    lgb.interprete                          html  
    lgb.load                                html  
    lgb.model.dt.tree                       html  
    lgb.plot.importance                     html  
    lgb.plot.interpretation                 html  
    lgb.prepare                             html  
    lgb.prepare2                            html  
    lgb.prepare_rules                       html  
    lgb.prepare_rules2                      html  
    lgb.save                                html  
    lgb.train                               html  
    lgb.unloader                            html  
    lgb_shared_params                       html  
    lightgbm                                html  
    predict.lgb.Booster                     html  
    readRDS.lgb.Booster                     html  
    saveRDS.lgb.Booster                     html  
    setinfo                                 html  
    slice                                   html  
** building package indices
** testing if installed package can be loaded
* DONE (lightgbm)
In R CMD INSTALL
```
</deatils>

**Comment by BruceZhaoR** [comment]
@guolinke @Laurae2 @jameslamb I run the 
```shell
git clone --recursive https://github.com/Microsoft/LightGBM
cd LightGBM
Rscript build_r.R
```
It generated the `lib_lightgbm.dll` with 33.5M, which can't be run in R.
Actually the right `lib_lightgbm.dll` is 4.6M in my computer. 
Something wrong with the `devtools`? 

I think the R package install [README](https://github.com/Microsoft/LightGBM/blob/master/R-package/README.md) should be changed, and do not need to use `ldgdl` package to `git clone` the whole repos again when there is something updated. 

Here are 3steps to install the R package :
1. git clone the repo once
2. creat `lightbgm_r` dir and copy the relative files to there and modify the `src/install.libs.R`, eg.`use_gpu <- TRUE; use_mingw <- TRUE`. if you want to use precompiled dll, just put it in repo root dir and set `use_precompile <- TRUE`
https://github.com/Microsoft/LightGBM/blob/7825084f160f3f8093cef3fdd13d1e49351e9e13/build_r.R#L14-L46
3. use `install.packages`
eg. `install.packages(file.path("C:", "LightGBM", "lightbgm_r "), repos = NULL, type = "source")`

When there is something updated , just delete the `lightbgm_r ` dir and `git pull`, then do the steps upon.

Just a suggestion, FYI.
Best.

**Comment by guolinke** [comment]
ping @Laurae2 @jameslamb

**Comment by Laurae2** [comment]
@BruceZhaoR lgbdl is only for convenience when not wanting to setup from scratch a temporary directory and a manual installation.

Note that the DLL created from R cannot be used elsewhere (the same is true for any other R packages). If you want to precompile the DLL, make sure to precompile without R.

**Comment by jameslamb** [comment]
@Laurae2 what do you think about @BruceZhaoR 's suggestion for changing the README?

To be transparent, I am not very familiar with the process of using precompiled DLLs in R on Windows so I am a bit outside of my experience area here.

**Comment by Laurae2** [comment]
@jameslamb The process of using precompiled DLL in Windows is identical to using precompiled lib in Linux.

Maybe adding into the README how to use precompiled DLL/lib without lgbdl can be helpful.

**Comment by BruceZhaoR** [comment]
The LightGBM repo is about 64M. When I want to update the pacakge, I need to git clone again and install, it is really slow. I mean we can add a more detail way to guide people compile the dll in  README.

**Comment by guolinke** [comment]
@BruceZhaoR @Laurae2 @jameslamb 
I think the previous build does not have this problem. Is Anything wrong now ?

**Comment by BruceZhaoR** [comment]
`Rscript build_r.R`
It generated the lib_lightgbm.dll with 33.5M in my computer, which can't run in R. This is the main problem.

**Comment by Laurae2** [comment]
@BruceZhaoR The DLL built by R is not made to be re-used for another R compilation as it is already compiled for R (static). Compile the DLL without R if you want to use a DLL to be used for R.

**Comment by guolinke** [comment]
@Laurae2 I believe our dll does not depend on R, as we already hacked this.

**Comment by Laurae2** [comment]
@jameslamb This issue is for all OSes (not Windows only), LightGBM can be precompiled, giving out a DLL (Windows) or so (Linux) file. That file can be re-used when compiling LightGBM for R.

We place the DLL/so file at the root of the LightGBM folder, then for the R installation it "should" work out of the box (after forcing to use a precompiled DLL).

Check it here: https://github.com/Laurae2/lgbdl/blob/master/R/lgb.dl.R#L112-L114 and https://github.com/Microsoft/LightGBM/blob/master/R-package/src/install.libs.R#L2

@BruceZhaoR I could add a way to allow local installation in https://github.com/Laurae2/lgbdl. It would copy the folder you would specify instead of the git.

Compiling DLL/so file is already documented here: https://github.com/Microsoft/LightGBM/blob/master/docs/Installation-Guide.rst (it is the same as compiling the binaries). Maybe we could add a link to point there.
