### ISSUE TITLE
Categorical Features + Feature Importance in Light GBM

### ISSUE THREAD

**Issue by vishesh123456** [Microsoft/LightGBM#1712]
## Environment info

Operating System:

CPU

Python

## Error message

So when I use the categorical features in Light GBM, i have to encode it to integers before doing so. 

1. Will the encoding of categorical to integers not introduce hierarchy in the values?

Secondly, after I run the model, and use the feature importance of light gbm, it gives me integer values from the encoded categorical features instead of the features themselves. Why is that?

## Reproducible examples

predictors = ['offer_id', 'affiliate_id', 'click_device_model', 'click_os', 'click_os_version',"click_country",'click_carrier']

categorical = ['offer_id', 'affiliate_id', 'click_device_model', 'click_os', 'click_os_version',"click_country",'click_carrier']

m=[X_train,X_test]
for a in m:
    for col in categorical:
        a[col] = a[col].astype('category')
        a[col] = pd.Categorical(a[col].cat.codes+1)
        a[col] = a[col].astype(np.int64)

import pandas as pd
import numpy as np
import lightgbm as lgb
import gc

target = 'tracker_fraud_flag'
dtrain = lgb.Dataset(X_train, y_train,
                      feature_name=predictors,
                      categorical_feature=categorical
                      )
dvalid = lgb.Dataset(X_test, y_test,
                      feature_name=predictors,
                      categorical_feature=categorical
                      )

evals_results = {}

print("Training the model...")

lgb_model = lgb.train(params, 
                 dtrain, 
                 valid_sets=[dtrain, dvalid], 
                 valid_names=['train','valid'], 
                 evals_result=evals_results, 
                 num_boost_round=350,
                 early_stopping_rounds=30,
                 verbose_eval=True)

# Feature names:
print('Feature names:', lgb_model.feature_name())

# Feature importances:
print('Feature importances:', list(lgb_model.feature_importance()))

The output comes as :

Feature names: ['offer_id', 'affiliate_id', 'click_device_model', 'click_os', 'click_os_version', 'click_country', 'click_carrier']

Feature importances: [0, 1, 0, 0, 0, 0, 0]

^ Why are the feature importance coming as values and not the feature names?

## Steps to reproduce

1.
2.
3.

**Comment by bbennett36** [comment]
Feature importance is showing the number of times the features was 'split' on.  
  
This is what you're looking for - 

'Split' is the number of times the modle split on that feature. 'Gain' is essentially a measure of how much a feature contributes to the accuracy of the model.
```
lgb.plot_importance(lgb_model, importance_type='split', max_num_features=20)

lgb.plot_importance(lgb_model, importance_type='gain', max_num_features=20)
```

**Comment by StrikerRUS** [comment]
Thanks a lot @bbennett36 for your detailed answer!
