### ISSUE TITLE
Publish lib_lightgbm.dll symbols to Microsoft Symbols Server

### ISSUE THREAD

**Issue by eerhardt** [microsoft/LightGBM#1725]
When using the lib_lightgbm.dll from https://www.nuget.org/packages/LightGBM/, and either trying to debug or perf profiling, I am not able to load symbols for this assembly.

We should publish the symbols for this assembly to the Microsoft Symbols Server, so others will be able to debug and profile correctly.

**Comment by danmosemsft** [comment]
@eerhardt is referring to the public symbol server, not the internal one. This will be consistent with what we do for ML.NET, .NET Core, etc. In all these cases we publicly post the non-stripped (complete) symbols.

**Comment by Laurae2** [comment]
ping @guolinke

**Comment by StrikerRUS** [comment]
ping @guolinke

**Comment by guolinke** [comment]
very sorry for the late response.
@eerhardt @danmosemsft I didn't use Microsoft Symbols Server before, any guidelines about it?
should I follow this (https://docs.microsoft.com/en-us/windows/desktop/dxtecharts/debugging-with-symbols#using-the-microsoft-symbol-server) to publish a symbol?

**Comment by eerhardt** [comment]
That section is about how users are able to download the symbols in order to debug/profile. There is a section below titled `Adding Symbols to a Symbol Server`, but that doesn't really apply to the official Microsoft symbols servers.

The process we use to publish ML.NET's symbols is in our official build script:

https://github.com/dotnet/machinelearning/blob/6f576de0ef99408b9505a52af47855a6b6230ffe/build/vsts-ci.yml#L246-L260

which calls into some MSBuild code:

https://github.com/dotnet/machinelearning/blob/6f576de0ef99408b9505a52af47855a6b6230ffe/build/publish.proj#L45-L53

In order to use those scripts, you need to set up a security token/secret in the official build to allow publishing the symbols to the server.

One question about the LightGBM NuGet package, is it an official Microsoft distributed binary? I see it isn't owned by Microsoft on nuget.org, but this repo is in the Microsoft github org. So it is a bit confusing on whether this is a Microsoft asset or not.

Another option (if that NuGet package isn't considered an official Microsoft product/library), is to put the symobls in a .zip or .tar.gz file on the `Releases` tab in GitHub. At least that way, any dev who needs the symbols will be able to download them from somewhere. It would be better than nothing.

**Comment by StrikerRUS** [comment]
Closed in favor of being in #2302. We decided to keep all feature requests in one place.

Welcome to contribute this feature! Please re-open this issue (or post a comment if you are not a topic starter) if you are actively working on implementing this feature.
