### ISSUE TITLE
Irreproducible Segfault with LightGBM

### ISSUE THREAD

**Issue by vruvora** [Microsoft/LightGBM#1743]
We are experiencing cases of irreproducible Segfault with LightGBM. Does anyone else have this issue? 

## Environment info

Operating System:

CPU/GPU model:

C++/Python/R version:

## Steps to reproduce

1.
2.
3.

**Comment by henry0312** [comment]
Did you install LightGBM from PyPI?
The distributions on PyPI may be broken.
(I guess compile optimization may be a cause)
So, can you try to compile from source?

**Comment by vruvora** [comment]
We are installing with pip install. It just hangs in a middle of an optimization. We can try compiling from source but is there a reason why PyPI may be broken?

**Comment by henry0312** [comment]
I guess there are something wrong with [manylinux](https://github.com/pypa/manylinux) and `-O3`.
Maybe, we should compile without `-O3` on manylinux.

**Comment by vruvora** [comment]
Interesting. Have you or anyone else experienced this because we have been experiencing this a fair amount but I have not seen any big reported use cases?

**Comment by guolinke** [comment]
@vruvora 
Did the Segfault occur often?

**Comment by vruvora** [comment]
Yes. It has been happening a quiet a bit as of late.

**Comment by henry0312** [comment]
I saw uncertain crash many times in my main job.

**Comment by vruvora** [comment]
@henry0312 Interesting. Have you been able to fix it?

**Comment by henry0312** [comment]
@vruvora you should be sure to uninstall the package from PyPI and install manually.

**Comment by henry0312** [comment]
@vruvora Yeah, installing from source have solved the problem.

**Comment by vruvora** [comment]
@henry0312 I will try this out and update accordingly. Thanks.

**Comment by vruvora** [comment]
@henry0312 Is this what you did for building from sources: `pip install --no-binary :all: lightgbm`?

**Comment by henry0312** [comment]
No, please see https://github.com/Microsoft/LightGBM/blob/master/docs/Installation-Guide.rst.

**Comment by guolinke** [comment]
@vruvora you can use 
```
pip install --no-binary :all: lightgbm
``` 
as well.

**Comment by guolinke** [comment]
@henry0312 
building without O3 may slow-down the running speed. 

I am not very sure why Segfault happened, and why building from source can fix it.

**Comment by henry0312** [comment]
@guolinke Yes, `-O3` makes cumpting perfomance better, but there may be something wrong with tunes for manylinux.

**Comment by vruvora** [comment]
@guolinke Will this be slower `pip install --no-binary :all: lightgbm` than regular `pip`? Can you elaborate on the differences?

**Comment by vruvora** [comment]
@henry0312 Yes. As far as we know. No more segafults.

**Comment by guolinke** [comment]
should we add this problem and solution to the document?

**Comment by StrikerRUS** [comment]
ping @henry0312

**Comment by vruvora** [comment]
Yes. We should.

**Comment by henry0312** [comment]
yeah, I also think so.
