### ISSUE TITLE
only one tree model generated during model fitting

### ISSUE THREAD

**Issue by AlexandraBomane** [Microsoft/LightGBM#1762]
Here, the `LGBMClassifier()` object that I created via the Python API (sklearn wrapper) : 
```
clf = LGBMClassifier(boosting_type='gbdt', colsample_bytree=0.8, learning_rate=0.1,
        max_bin=255, max_depth=-1, min_child_samples=10,
        min_child_weight=5, min_split_gain=0.0, n_estimators=1000,
        n_jobs=1, num_leaves=31, objective=None, random_state=58554051,
        reg_alpha=0.0, reg_lambda=0.0, silent=True, subsample=0.8,
        subsample_for_bin=50000, subsample_freq=1)
```
I built a classifier using this algorithm on a dataset made of 60489 columns and 61 rows.

Then, my goal was to investigate the feature importances. That's why I used the function `clf.booster_.feature_importance(importance_type='gain')` to see the feature importances obtained from the model. Focusing on non-zero-importance features, I noticed that only one feature present non null importance.

After that, I dumped the model to see the tree model(s) involving this feature : 
```
>>> clf.booster_.dump_model()['tree_info']
[{u'num_leaves': 2, u'num_cat': 0, u'tree_index': 0, u'tree_structure': {u'internal_count': 48, u'right_child': {u'leaf_index': 1, u'leaf_value': 0.19999999999999996, u'leaf_count': 36}, u'split_feature': 30728, u'missing_type': u'None', u'default_left': True, u'internal_value': 0, u'threshold': -0.03415, u'split_gain': 32.55652092003208, u'split_index': 0, u'decision_type': u'<=', u'left_child': {u'leaf_index': 0, u'leaf_value': -0.14098360813044117, u'leaf_count': 12}}, u'shrinkage': 0.1}]
```
As we can see, only one tree (decision stump) have been generated during model fitting.

I would like to know which parameter(s)/process can be involved in the construction of this **single** tree model ?

Thanks in advance

**Comment by guolinke** [comment]
@AlexandraBomane objective = "None" ?
BTW, can you disable "silent" and provide the running logs ?

**Comment by AlexandraBomane** [comment]
Please, find attached the running logs.
[log.txt](https://github.com/Microsoft/LightGBM/files/2492648/log.txt)

When I do `clf.objective_`, I obtain "binary".

**Comment by guolinke** [comment]
@AlexandraBomane it seems your data is hard to learn.
you can try to set min_child_weight=0 .

**Comment by guolinke** [comment]
@AlexandraBomane I think it is due to low amount of data points, or imbalance data.

**Comment by AlexandraBomane** [comment]
Thank you. I saw that default `min_child_weight` is set to 5 : is it because LightGBM is basically designed to fit datasets made of high amount of data points (like thousands) ?

**Comment by guolinke** [comment]
@AlexandraBomane I think the default value of min_child_weight is 1e-3, not the 5.
I recommend `min_child_samples`, which is more intuitive to constraint the amount of data in one leaf.

**Comment by AlexandraBomane** [comment]
At one time, default `min_child_weight` was set to 1e-3. But as reported in #1014 and #1033, some changes occurred  in the scikit-learn API. So, with the default parameters of LightGBM 2.0.10, I obtain `min_child_weight = 5`.

**Comment by guolinke** [comment]
ping @StrikerRUS

**Comment by StrikerRUS** [comment]
@AlexandraBomane Also, please update LightGBM version. The latest one is `2.2.1`.

`2.0.10` version indeed has default value `min_child_weight=5`:
https://github.com/Microsoft/LightGBM/blob/a668045e3f28e101885ea88826e94815b41682fa/python-package/lightgbm/sklearn.py#L143
