### ISSUE TITLE
Dataset has no data when passed to fpreproc in Python cv function

### ISSUE THREAD

**Issue by JoshuaC3** [Microsoft/LightGBM#1763]
## Environment info

Operating System: Ubuntu 16.04

CPU/GPU model: 

C++/Python/R version: 
3.7.0 (default, Oct  9 2018, 10:31:47) 
[GCC 7.3.0]

```
lgb.__version__, pd.__version__, np.__version__
```
`('2.2.1', '0.23.4', '1.15.2')`

## Error message

`dtrain.data` should be a pandas DataFrame and should not be `None`. When I get the below error, I can see that the dtrain.data _is_ being set to `None`:

`AttributeError: 'NoneType' object has no attribute 'assign'`

## Reproducible examples

```
import numpy as np
import pandas as pd
import lightgbm as lgb


data = pd.DataFrame({'x1': np.random.rand(1000),
                     'x2': 5 + np.random.rand(1000),
                     'target': np.random.randint(0, 2, 1000)})

data_train = lgb.Dataset(data.drop(['target'], axis=1), data.target, free_raw_data=False)


def fpreproc_rebalance(dtrain, dtest, params,):
    data = dtrain.data.assign(target=data.label)
    neg = data.loc[lambda x: x.target == 0]

    data = (
        pd.concat([data] + [neg] * negative_upsample_rate)
    )

    fdtrain = lgb.Dataset(data.drop('target', axis=1), data.target, free_raw_data=False)
    return fdtrain, dtest, params


params = {
    'objective': 'xentlambda',
    'feature_fraction': 0.8,
    'learning_rate': 0.4,
}

results = lgb.cv(
    params,
    data_train,
    nfold=5,
    fpreproc=fpreproc_rebalance,
)
```

## Steps to reproduce

1. Run above code.
2. Weep into keyboard ;)

**Comment by StrikerRUS** [comment]
Thanks for reporting this, @JoshuaC3 !

@guolinke I think the problem is that `subset()` passes `data=None` before executing `fpreproc()`, so `data` field is always `None` in new Dataset object:
https://github.com/Microsoft/LightGBM/blob/9a2bf26626c55ee9d7a1615a071fbc1a0b2dd2c0/python-package/lightgbm/engine.py#L308-L312
https://github.com/Microsoft/LightGBM/blob/9a2bf26626c55ee9d7a1615a071fbc1a0b2dd2c0/python-package/lightgbm/basic.py#L1031

**Comment by guolinke** [comment]
yeah,
subset actually cannot p artition the `data`.
@JoshuaC3 you can fix it by construct the dataset in freproc function instead.

**Comment by JoshuaC3** [comment]
@guolinke - I don't understand. `cv` function only accepts a Dataset onbject. you get errors if you try to pass pd.DataFrame or np.array.

**Comment by guolinke** [comment]
@JoshuaC3 sorry, I miss-understood your question. It indeed is a bug in LightGBM side.
@StrikerRUS I think we can fix this by giving a `data` to subset dataset.

**Comment by StrikerRUS** [comment]
@guolinke How can we retrieve the needed data? Via slicing?

**Comment by StrikerRUS** [comment]
@guolinke Hmm... Sounds good! Let me think about it.
