### ISSUE TITLE
python using multiprocessing.Pool  failed

### ISSUE THREAD

**Issue by forestchen1224** [Microsoft/LightGBM#1768]
## Environment info

Operating System:ubuntu

CPU/GPU model:cpu

C++/Python/R version:python

## Error message

    I want to train tree models in different processes, but lgb.LGBMRegressor not work,it works when in one process
---> 19 pool.join()
     20 print(queue.qsize())
     21 # for i in range(3):

/usr/lib/python3.5/multiprocessing/pool.py in join(self)
    508         util.debug('joining pool')
    509         assert self._state in (CLOSE, TERMINATE)
--> 510         self._worker_handler.join()
    511         self._task_handler.join()
    512         self._result_handler.join()

/usr/lib/python3.5/threading.py in join(self, timeout)
   1052 
   1053         if timeout is None:
-> 1054             self._wait_for_tstate_lock()
   1055         else:
   1056             # the behavior of a negative timeout isn't documented, but

/usr/lib/python3.5/threading.py in _wait_for_tstate_lock(self, block, timeout)
   1068         if lock is None:  # already determined that the C code is done
   1069             assert self._is_stopped
-> 1070         elif lock.acquire(block, timeout):
   1071             lock.release()
   1072             self._stop()

## Reproducible examples

parameters={
    'boosting':'gbdt',
    'num_leaves':4,
    'application':'regression',
    'objective':'rmse',
    'device':'cpu',
    'max_depth':3,
    'min_child_samples':20,
    'feature_fraction':0.5,
    'bagging_fraction':0.8,
    'bagging_freq':5,
    'lambda_l1':0.5,
    'learning_rate':0.05}
from multiprocessing import Pool,Manager
import lightgbm as lgb

def train_test(model,X_train,y_train,X_val,queue):
    model.fit(X_train,y_train)
    queue.put(model.predict(X_val))
    print(model.__class__,queue.qsize())

gbm = lgb.LGBMRegressor(**parameters)
lr = Lasso(alpha=0.001,max_iter=10000,tol=0.005)
lr1 = Ridge()
models = [lr,lr1,gbm,]
queue = Manager().Queue()
pool = Pool(3)
for i,model in enumerate(models):
    pool.apply_async(func=train_test,args=(models[i],X_train,y_train,X_val,queue))
pool.close()
pool.join()

## Steps to reproduce

1.
2.
3.

**Comment by guolinke** [comment]
you can try `num_threads=1` in parameters.

**Comment by forestchen1224** [comment]
it works,thanks.
I wonder what is the reason behind this operation.
it seems that the lock didn't release when having multiple threads. But if I don't use mutiprocess, multiple threads still works.

**Comment by guolinke** [comment]
refer to https://github.com/Microsoft/LightGBM/pull/1796
