### ISSUE TITLE
Why the forced_splits argument is ignored?

### ISSUE THREAD

**Issue by AnchorBlues** [Microsoft/LightGBM#1783]
Hello.
I'm trying to use lightgbm with the [forced_splits argument](https://github.com/Microsoft/LightGBM/blob/master/docs/Parameters.rst#forcedsplits_filename).  
I found that the forced_splits argument doesn't work in the case of following.

## Environment info

Operating System:
Ubuntu 14.04.5 LTS, Trusty Tahr

CPU/GPU model: 
cpu
Intel(R) Core(TM) i7-6800K CPU @ 3.40GHz

C++/Python/R version:

python version : 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56) 
[GCC 7.2.0]
lightgbm version : 2.1.2

## source

```python
import numpy as np
from sklearn.datasets import load_breast_cancer
import lightgbm as lgb

# load data (binary classification)
data = load_breast_cancer()
x_train = data.data
y_train = data.target

# create a new feature that takes a value 0 or 1.
np.random.seed(0)
dummy = np.random.randint(0, 2, size=len(x_train))
x_train = np.c_[dummy, x_train]

# create json file that forces the tree to split by the new feature. threshold is 0.5.
s = """
{
    "feature": 0,
    "threshold": 0.5,
    "left": {
    },
    "right": {
    }
}
"""

with open("forced_splits-0.json", mode='w') as f:
    f.write(s)

# model training
model = lgb.LGBMClassifier(random_state=42, forced_splits="forced_splits-0.json", num_leaves=3, n_estimators=10)
model.fit(x_train, y_train)


ax = lgb.plot_tree(model, tree_index=0, figsize=(30, 8), show_info=['split_gain'])
plt.savefig("./result.png")
plt.show()
```

## terminal output
```
[LightGBM] [Warning] Gain with forced split worse than without split
[LightGBM] [Warning] Gain with forced split worse than without split
[LightGBM] [Warning] Gain with forced split worse than without split
[LightGBM] [Warning] Gain with forced split worse than without split
[LightGBM] [Warning] Gain with forced split worse than without split
[LightGBM] [Warning] Gain with forced split worse than without split
[LightGBM] [Warning] Gain with forced split worse than without split
[LightGBM] [Warning] Gain with forced split worse than without split
[LightGBM] [Warning] Gain with forced split worse than without split
[LightGBM] [Warning] Gain with forced split worse than without split
```
## result.png

The structure of the first tree is like this.

![result](https://user-images.githubusercontent.com/12887397/47473690-96920200-d84e-11e8-8917-9c426c894ddf.png)

the 0th feature that is specified by the json file is not used at the split of the root node.
the result seems the lightgbm completely ignore the forced_splits argument.

Why does the model behave like this?

**Comment by guolinke** [comment]
@AnchorBlues 
you can try the
s = """
{
    "feature": 0,
    "threshold": 0.0
}
"""

**Comment by guolinke** [comment]
@jerryjliu
It seems current json cannot process the null fields correctly. it will treat it as feature=0 with threshold=0 split.

**Comment by AnchorBlues** [comment]
@guolinke 

Thanks.
I made a fix in reference to
https://github.com/Microsoft/LightGBM/pull/1785/files
and built the LightGBM source.
As a result, the above code worked.

I have a last question.

1. https://github.com/Microsoft/LightGBM/issues/1783#issue-373757095
2. https://github.com/Microsoft/LightGBM/issues/1783#issuecomment-432929410

I think both of the above 2 codes force the completely same split of the dataset at the root node of each decision tree.
However, when the code 1 is executed, the warning message 

```
[LightGBM] [Warning] Gain with forced split worse than without split
```

appears and `forced_splits` argument is ignored.
On the other hands, when the code 2 is executed, no warning message appears and `forced_splits` argument is used.

What's the difference between these two?

**Comment by jerryjliu** [comment]
@guolinke thanks for fixing and accounting for the null case. @AnchorBlues isn't this because your thresholds are different between the two code snippets (one is 0.5 and the other is 0)?

**Comment by AnchorBlues** [comment]
@jerryjliu 
The two cases have the different threshold values, but the values of the split feature are also different.
Please check 3 changes at https://github.com/Microsoft/LightGBM/issues/1783#issuecomment-432929410 .
