### ISSUE TITLE
Mean Squared Error for Binary Classification

### ISSUE THREAD

**Issue by MotoRZR** [Microsoft/LightGBM#1786]
I know this is typically not done but in my case, the metric I'm being judged on is the Brier Score which is the mean squared error of the prediction relative to target.  Is it possible to use mean squared error as an objective for classification?

**Comment by guolinke** [comment]
you can write a customed objective function by yourself. refer to https://github.com/Microsoft/LightGBM/blob/master/examples/python-guide/advanced_example.py#L137-L166
