### ISSUE TITLE
How can I set parameter to get rid of any verbose?

### ISSUE THREAD

**Issue by aaliwei91** [Microsoft/LightGBM#1792]
I've tried

`fit.lgb <- lgb.train(params, light.train, verbose_eval=0)`

but it still shows multiple lines of

`LightGBM] [Warning] No further splits with positive gain, best gain: -inf [LightGBM] [Warning] No further splits with positive gain, best gain: -inf [LightGBM] [Warning] No further splits with positive gain, best gain: -inf [LightGBM] [Warning] No further splits with positive gain, best gain: -inf [LightGBM] [Warning] No further splits with positive gain, best gain: -inf [LightGBM] [Warning] No further splits with positive gain, best gain: -inf [LightGBM] [Warning] No further splits with positive gain, best gain: -inf [LightGBM] [Warning] No further splits with positive gain, best gain: -inf [LightGBM] [Warning] No further splits with positive gain, best gain: -inf`
--
 
How can I get rid of them, just show nothing after running the command?

**Comment by guolinke** [comment]
set verbose=0 in params.
