### ISSUE TITLE
Install Clang in Docker for Azure Pipelines

### ISSUE THREAD

**Issue by StrikerRUS** [Microsoft/LightGBM#1795]
In order to test Clang on Azure Pipelines after #1745 we need install it inside Docker. For the consistency with non-containerized `Linux_gpu` task it's better to install 6.0 version:
https://github.com/Microsoft/LightGBM/blob/087d30623aef4b50592cf528eb50c1c55baeaab8/.ci/setup.sh#L28-L31

**Comment by guolinke** [comment]
@StrikerRUS so we need an additional image for clang ?

**Comment by StrikerRUS** [comment]
I think that updating [existent file](https://github.com/Microsoft/LightGBM/blob/master/.ci/dockers/ubuntu-14.04/Dockerfile) will be enough.
We need something [like this](https://superuser.com/a/1280073), but for clang 6 https://apt.llvm.org/. I've tried, but with no luck.

**Comment by StrikerRUS** [comment]
@guolinke Got it work with the following code:

```
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
sudo apt-add-repository "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-6.0 main"
sudo apt-get update
sudo apt-get install -y --no-install-recommends clang-6.0
```

Can be this embedded in dockerfile? Could you help please?

**Comment by guolinke** [comment]
okay, sure.

**Comment by guolinke** [comment]
@StrikerRUS The build is in https://hub.docker.com/r/lightgbm/vsts-agent/builds/ , you can try the new image after the build finished.

**Comment by StrikerRUS** [comment]
@guolinke Many thanks! Now `COMPILER` variable works great again on both Travis and Azure Pipelines.

The only thing I'm afraid of is that Clang installs a lot of dependencies:
```
The following extra packages will be installed:
  gcc-4.9-base gcc-7-base gcc-8-base libasan1 libatomic1 libcilkrts5
  libclang-common-6.0-dev libclang1-6.0 libedit2 libgc1c2 libgcc-4.9-dev
  libgcc1 libgomp1 libitm1 libjsoncpp0 libllvm6.0 liblsan0 libobjc-4.9-dev
  libobjc4 libquadmath0 libstdc++-4.9-dev libstdc++6 libtsan0 libubsan0
Suggested packages:
  gnustep gnustep-devel clang-6.0-doc libstdc++-4.9-doc
Recommended packages:
  llvm-6.0-dev python libomp-dev
The following NEW packages will be installed:
  clang-6.0 gcc-7-base gcc-8-base libasan1 libcilkrts5 libclang-common-6.0-dev
  libclang1-6.0 libedit2 libgc1c2 libgcc-4.9-dev libjsoncpp0 libllvm6.0
  liblsan0 libobjc-4.9-dev libobjc4 libstdc++-4.9-dev libubsan0
The following packages will be upgraded:
  gcc-4.9-base libatomic1 libgcc1 libgomp1 libitm1 libquadmath0 libstdc++6
  libtsan0

8 upgraded, 17 newly installed, 0 to remove and 10 not upgraded.
```

Can you please check is everything OK with glibc and other libraries versions in our artifacts?

**Comment by guolinke** [comment]
@StrikerRUS any binaries built by this docker that I can test with ?

**Comment by StrikerRUS** [comment]
> It seems everything is okay,

Nice to hear!

> BTW, maybe we can add above checks into tests, to avoid manually checking ?

Hmm, great idea! I'll try later today.
