### ISSUE TITLE
Meaning of [cat_boundaries] and [cat_threshold] in model txt file

### ISSUE THREAD

**Issue by acrushdjn** [Microsoft/LightGBM#1803]
What's the meaning of cat_boundaries and cat_threshold in model txt file?
Why can one node with category feature have multiple category features with the same decision direction? I just see one threshold in the model txt file.
[Tree0.gv.pdf](https://github.com/Microsoft/LightGBM/files/2530406/Tree0.gv.pdf)
[Tree1.gv.pdf](https://github.com/Microsoft/LightGBM/files/2530408/Tree1.gv.pdf)
[binary_test_model.txt](https://github.com/Microsoft/LightGBM/files/2530409/binary_test_model.txt)

**Comment by guolinke** [comment]
@acrushdjn it is the int value of bit vectors of use categorical values.
you can refer to this code: https://github.com/Microsoft/LightGBM/blob/master/src/io/tree.cpp#L270-L279, to see how we use it.
