### ISSUE TITLE
how to find the best split point in each bin?

### ISSUE THREAD

**Issue by moseshu** [Microsoft/LightGBM#1814]
1. 2. I wonder that how to find the best split point in the bins of  LightGBM ? 
2.  which is the function to compute the split ? Is it same to the Xgboost ?
3. In each leaf, the dataset is redivided  to bins again? or it is divided  well  by the number of bins when inited ?thank you

**Comment by guolinke** [comment]
LightGBM uses the static bin mapping, therefore, the bins aren't re-constructed during training.
As for best split point, it is almost the same as XGBoost, as well as the standard decision tree growing.
