### ISSUE TITLE
unittest of lambdarank failed

### ISSUE THREAD

**Issue by AlexQie** [Microsoft/LightGBM#1819]
https://github.com/Microsoft/LightGBM/blob/59f10453dc4a3841339702524124063fa5db6870/tests/python_package_test/test_sklearn.py#L59
I want to use lambdarank, but I found the unittest failed. Is there any thing goes wrong?

**Comment by guolinke** [comment]
all tests pass in master branch:

![image](https://user-images.githubusercontent.com/16040950/47978038-63752b80-e0f6-11e8-9cde-d4c04e5af701.png)
