### ISSUE TITLE
Index out of range exception on small dataset with quantile regression.

### ISSUE THREAD

**Issue by mjmckp** [Microsoft/LightGBM#1823]
There is an index out of range exception generated somewhere in the `WeightedPercentileFun` macro called by `RegressionQuantileloss.RenewTreeOutput`.

The attached zip file contains a reproduction of the error, just unzip to `c:\temp` and run `lightgbm.exe config=train.conf`.

[repro.zip](https://github.com/Microsoft/LightGBM/files/2550912/repro.zip)

**Comment by guolinke** [comment]
fixed in 0f224c05683991d84ab38cb1730195a1c57ff487
