### ISSUE TITLE
Installing on windows: Error in getDLLRegisteredRoutines.DLLInfo(dll, addNames = FALSE)

### ISSUE THREAD

**Issue by DavytJ** [Microsoft/LightGBM#1830]
I am trying to install lightgbm. Sorry but always I install from RStudio but there are this way to install in the documentation guide that it's not what I usually do, so I can to mistakes. Thank for help.

## Environment info

Operating System: Windows

CPU/GPU model:

C++/Python/R version: R 3.5.1

## Error message

 Error in getDLLRegisteredRoutines.DLLInfo(dll, addNames = FALSE) :
  must specify DLL via a "DLLInfo" object. See getLoadedDLLs()

## Reproducible examples

git clone --recursive https://github.com/Microsoft/LightGBM
cd LightGBM
Rscript build_r.R

## Steps to reproduce

1.
2.
3.

**Comment by DavytJ** [comment]
If I do this:

install.packages(file.path("C:/Program Files/R/R-3.5.1/library", "LightGBM", "R-package"), repos = NULL, type = "source")

Suggested in issue #1702 I have the next error:

Installing package into ‘C:/Users/usuario/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
* installing *source* package 'lightgbm' ...
** libs
C:/RBuildTools/3.5/mingw_64/bin/gcc  -I"C:/PROGRA~1/R/R-35~1.1/include" -DNDEBUG          -O2 -Wall  -std=gnu99 -mtune=generic -c R_init.c -o R_init.o
Assembler messages:
Fatal error: can't create R_init.o: Permission denied
make: *** [C:/PROGRA~1/R/R-35~1.1/etc/x64/Makeconf:208: R_init.o] Error 1
ERROR: compilation failed for package 'lightgbm'
* removing 'C:/Users/usuario/Documents/R/win-library/3.5/lightgbm'
In R CMD INSTALL
Warning in install.packages :
  installation of package ‘C:/PROGRA~1/R/R-35~1.1/library/LightGBM/R-package’ had non-zero exit status

**Comment by guolinke** [comment]
@Laurae2

**Comment by Laurae2** [comment]
@DavytJ Install cmake and add it to PATH.

**Comment by DavytJ** [comment]
I install visual studio community yesterdar (first time) and I add the PATH, but I dont't know if is the correctly path, ¿what file need to run?
I put different PATH :
1) C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\CMake
2) C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake
3) C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin

But the error persist
thanks for help

**Comment by Laurae2** [comment]
Use this cmake instead: https://cmake.org/download/

After installation, you will need to add to PATH the following: C:\Program Files\CMake\bin

**Comment by DavytJ** [comment]
I install your suggest and add to PATH but still the error remains, maybe I'll abandon the idea of installing lightgbm in R. What does the error mean?

**Comment by Laurae2** [comment]
@DavytJ The issue is explicit:

```r
Warning in system(paste0(tmp_cmake_cmd, " ..")) : 'cmake' not found
Warning in system(paste0(tmp_cmake_cmd, " ..")) : 'cmake' not found
Warning in system(paste0(cmake_cmd, " ..")) : 'cmake' not found
Warning in system(build_cmd) : 'cmake' not found
```

You don't have cmake in your PATH, therefore the command line cannot find it.

Run `cmake --version` from a command line to check if cmake is available:

```
C:\WINDOWS\system32>cmake --version
cmake version 3.8.0

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

If it is not available, then your PATH is set incorrectly.

**Comment by DavytJ** [comment]
yes, I have:
C:\WINDOWS\system32>cmake --version
cmake version 3.13.0-rc3

CMake suite maintained and supported by Kitware (kitware.com/cmake).

Sorry about my ignorance, but, can be my cmake version the problem?

**Comment by Laurae2** [comment]
@DavytJ cmake is available from command line, therefore you should be fine.

However it does not explain why from R, your system cannot find it.

Can you run the following from R?

```r
system("cmake --version")
```

**Comment by DavytJ** [comment]
Yes.
> system("cmake --version")
cmake version 3.13.0-rc3

CMake suite maintained and supported by Kitware (kitware.com/cmake).

**Comment by jameslamb** [comment]
@Laurae2 @knausb I think this is related to `roxygen2` version. There's quite a long thread in klutometis/roxygen#822 and it seems like:

1. The issue can't be reliably reproduced yet
2. It does not happen on `roxygen2` v6.0.1

One possible answer they arrive at in that thread seems similar to what @knausb noted in knausb/vcfR#119.

**Comment by jameslamb** [comment]
@Laurae2 oh it was removed from the install script. I think because of this error or possibly other users reporting the same error. 

I agree (looking back through this) that the issue I linked to on `roxygen2` might not be the root cause here but I am still experiencing it locally trying to build the documentation.

**Comment by Laurae2** [comment]
@DavytJ any news?

@jameslamb It could be also the user did not close the R session after loading LightGBM and before attempting to install LightGBM. Installing LightGBM over a loaded LightGBM leads to unexpected behaviors as R does not warn about a loaded DLL not writable. We use the following hack to attempt cleaning a LightGBM session in R (it is not fully clean, as LightGBM remains partially loaded even if unloaded by R): https://github.com/Microsoft/LightGBM/blob/master/R-package/R/lgb.unloader.R

**Comment by StrikerRUS** [comment]
Closed due to inactivity.
Feel free to reopen with new details.
