### ISSUE TITLE
Simple question about LightGBM PredictContrib

### ISSUE THREAD

**Issue by IbanezJS** [Microsoft/LightGBM#1833]
Hello there!
LightGBM::GBDT::PredictContrib(const double* features, double* output)

1)Does this method calculates "true" shap_values which are deltas from model expected value on whole dataset?
OR
2)I have to substract beforehand calculated expected_value from each output for every sample row ?

**Comment by StrikerRUS** [comment]
ping @slundberg

**Comment by slundberg** [comment]
This got answered here: https://github.com/slundberg/shap/issues/317

**Comment by StrikerRUS** [comment]
Thanks a lot!
