### ISSUE TITLE
why lightgbm can not predict on Dataset , but eval data can be evaluated (example auc) when training?

### ISSUE THREAD

**Issue by OMonkey** [Microsoft/LightGBM#1835]
## Environment info

Operating System:

CPU/GPU model:

C++/Python/R version:

## Steps to reproduce

1.
2.
3.

**Comment by guolinke** [comment]
LightGBM uses bucketized int values (converted from float feature values) in the training, for speed-up.
 
For the prediction over new test data, converting them from float to int is not efficient, as we don't need to do this (the bucketized cannot help the speed-up for inference).
