### ISSUE TITLE
Cox Proportional Hazard Regression

### ISSUE THREAD

**Issue by zanemarkson** [microsoft/LightGBM#1837]
Hello LightGBM Ninjas

Thanks for all the awesomeness in LightGBM. Quick question: Do we/Can we have the "objective=cox_proportional_hazard_breslow_approx" option? I am not sure if it is feasible to add Cox Proportional Hazard survival model into LightGBM from engineering standpoint, but it would be very nice if we can use SHAP with CPH in LightGBM just like @slundberg's "NHANES I Survival Model" notebook.

Thanks!

**Comment by StrikerRUS** [comment]
Implementation in XGBoost: https://github.com/dmlc/xgboost/blob/f9302a56fbdabb28d071ed9e402ca75e03673b4d/src/objective/regression_obj.cu#L273-L358
and corresponding PR: https://github.com/dmlc/xgboost/pull/3043.

**Comment by StrikerRUS** [comment]
Closed in favor of being in #2302. We decided to keep all feature requests in one place.

Welcome to contribute this feature! Please re-open this issue (or post a comment if you are not a topic starter) if you are actively working on implementing this feature.

**Comment by MotoRZR** [comment]
Another survival model for consideration (now implemented in XGBoost)

https://arxiv.org/abs/2006.04920

https://xgboost.readthedocs.io/en/latest/tutorials/aft_survival_analysis.html

> Closed in favor of being in #2302. We decided to keep all feature requests in one place.
> 
> Welcome to contribute this feature! Please re-open this issue (or post a comment if you are not a topic starter) if you are actively working on implementing this feature.
