### ISSUE TITLE
How to use LightGBM on distributed clusters?

### ISSUE THREAD

**Issue by xiaoxiaofengzi** [Microsoft/LightGBM#1838]
The size of my data set is very big, but the memory of my machine is a little small. So I want to use LightGBM to train my data on distributed clusters like spark mlib. I can't find the solution by reading the API doc, could you tell me how I can do it? Thank you very much!

**Comment by guolinke** [comment]
1. spark version: MMLSpark  https://github.com/Azure/mmlspark
2. python version: https://github.com/SfinxCZ/dask-lightgbm
3. cli version: https://github.com/Microsoft/LightGBM/tree/master/examples/parallel_learning
