### ISSUE TITLE
regression_l1 does not converge without boost_from_average.

### ISSUE THREAD

**Issue by trivialfis** [Microsoft/LightGBM#1839]
## Environment info
Operating System: Ubuntu 18.04
CPU/GPU model: AMD Ryzen 7 2700
C++/Python/R version: Python 3.6 Virtualenv

# Tested datasets:
**Wine Quality** including both red and white wine: http://archive.ics.uci.edu/ml/datasets/Wine+Quality
- Plot for red wine
![wine-quality-red-lightgbm](https://user-images.githubusercontent.com/16746409/48379873-7a410100-e73a-11e8-831d-0d3d4b702ebb.png)
- Plot for white wine
![wine-quality-white-lightgbm](https://user-images.githubusercontent.com/16746409/48379886-8462ff80-e73a-11e8-8f45-fc10c3b7b8b0.png)

**YearPredictionMSD**: http://archive.ics.uci.edu/ml/datasets/YearPredictionMSD
- Plot
![yearpredictionmsd-lightgbm](https://user-images.githubusercontent.com/16746409/48379906-9e9cdd80-e73a-11e8-8e63-f2f044374ea4.png)

**Boston**: https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_boston.html
- Plot
![boston-lightgbm](https://user-images.githubusercontent.com/16746409/48379927-a492be80-e73a-11e8-9d54-454decf5fee1.png)

# Script to reproduce
Here is the most relevant part of a simple testing script
``` python
class Benchmark(object):
    candidates = [
        'LightGBM',
    ]

    def __init__(self,
                 x: np.ndarray, y: np.ndarray,
                 tx: np.ndarray, ty: np.ndarray,
                 dataset_name: str):
        self.train_x = x
        self.train_y = y
        self.test_x = tx
        self.test_y = ty
        self.dataset_name = dataset_name

        self.candidiates_mapping = {
            'LightGBM': self.train_lightgbm,
        }

    def run(self, name):
        self.candidiates_mapping[name]()

    def train_lightgbm(self):
        '''Plot LightGBM training results.'''
        def _train(
                dtrain: lgb.Dataset, dtest: lgb.Dataset,
                boost_from_average=False):

            results = dict()
            params = {'objective': 'mae',
                      'boosting': 'gbdt',
                      'boost_from_average': boost_from_average,
                      'tree_learner': 'serial'}

            lgb.train(params,
                      dtrain,
                      valid_sets=[dtrain, dtest],
                      evals_result=results)

            train_log = results['training']['l1']
            test_log = results['valid_1']['l1']

            return (train_log, test_log)

        dtrain = lgb.Dataset(self.train_x, self.train_y)
        dtest = lgb.Dataset(self.test_x, self.test_y)

        train_logs = []
        test_logs = []
        labels = []
        for is_average in (True, False):
            train_log, test_log = _train(dtrain, dtest, is_average)
            train_logs.append(train_log)
            test_logs.append(test_log)
            labels.append('Boost from average:' + str(is_average))

        self._plot_results_layered(train_logs, test_logs, labels, 'LightGBM')
        return (train_log, test_log, labels)

    def _plot_results_layered(
            self,
            train_logs: List[List], test_logs: List[List],
            labels: List[str],
            name: str):
        fig, axs = plt.subplots(2, 1, constrained_layout=True)
        fig.suptitle(name)
        for i, t in zip([0, 1], ['Training', 'Testing']):
            axs[i].set_title(t+' error')
            axs[i].set_xlabel('Number of iterations')
            axs[i].set_ylabel(t+' MAE')
        for train_log, test_log, label in zip(train_logs, test_logs, labels):
            axs[0].plot(train_log, label=label)
            axs[1].plot(test_log, label=label)
        for i in (0, 1):
            axs[i].legend(loc='best', fontsize='xx-small', ncol=2)

        plt.savefig(fname=self.dataset_name+'-'+name+'.png',
                    quality=100, dpi=800)

```

# Misc
I have also tested implementations from `CatBoost` and `Scikit-Learn` obtaining good convergence. The only dataset I found for LightGBM to work is the regression sample dataset from the source tree. :)
**Update**: Note that CatBoost and Scikit-Learn have similar strategist and I haven't found a way to disable it.  So it's not clear to me that if this is an expected behavior.

**Comment by guolinke** [comment]
It is the expected behavior: refer to https://github.com/Microsoft/LightGBM/blob/c920e6345bcb41fc1ec6ac338f5437034b9f0d38/src/boosting/gbdt.cpp#L327

**Comment by trivialfis** [comment]
@guolinke Pleae notice that it's not converging at all, neither training error nor test error has changed a bit during the entire session.  There is a warning message at each iteration:
> [LightGBM] [Warning] No further splits with positive gain, best gain: -inf
> [LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements

As a result, the total number of output trees is 1.

If that's normal behavior I will close the issue. :)

**Comment by guolinke** [comment]
Yeah, it is normal as all residuals are the same (therefore cannot split trees) in you case.

**Comment by trivialfis** [comment]
Thanks for the explanation.
