### ISSUE TITLE
[Fatal] Input format error when parsing as CSV when using ignore_column

### ISSUE THREAD

**Issue by gbatt** [Microsoft/LightGBM#1840]
I discovered a bug when using parameter ignore_column while constructing a Dataset from CSV.

On my original dataset (about ~15GB uncompressed CSV), LightGBM failed with error "[Fatal] Input format error when parsing as CSV" and did not provide a more informative message when running with increased verbosity. After much trial and error, I was able to isolate the cause of the error to the parameter "ignore_column". 

I have constructed the following minimal example CSVs (using a small ~80kB subset of my dataset) demonstrating this bug.

1. "working_example.csv": 1000 rows including header, 11 numeric columns including binary (0/1) label. This dataset is constructed without any error.
2. "failing_example.csv": identical to "working_example.csv" with three additional columns (named "IGNORE_0", "IGNORE_1", "IGNORE_2") which are all passed to "ignore_column" parameter as "name:IGNORE_0,IGNORE_1,IGNORE_2". This dataset throws a fatal error when .construct() is called.

I've attached both these csv files and a notebook demonstrating the error to this message.

It seems quite strange that the addition of columns which are to be ignored causes an error.

Happy to provide more information and / or help to the extent I can.

Thanks in advance!

## Environment info

Operating System: Ubuntu 18.04

CPU/GPU model:  CPU: i7-6700 GPU: GTX 1080

C++/Python/R version: Python 3.66, lightgbm 2.2.1 [built from pip with GPU support]

## Error message

LightGBMErrorTraceback (most recent call last)
<ipython-input-3-c18cc80856a3> in <module>()
      1 params['ignore_column'] = 'name:IGNORE_0,IGNORE_1,IGNORE_2'
      2 data = lgb.Dataset(data='failing_example.csv', params=params, free_raw_data=True)
----> 3 data.construct()

~/anaconda3/envs/fin/lib/python3.6/site-packages/lightgbm/basic.py in construct(self)
    983                                 init_score=self.init_score, predictor=self._predictor,
    984                                 silent=self.silent, feature_name=self.feature_name,
--> 985                                 categorical_feature=self.categorical_feature, params=self.params)
    986             if self.free_raw_data:
    987                 self.data = None

~/anaconda3/envs/fin/lib/python3.6/site-packages/lightgbm/basic.py in _lazy_init(self, data, label, reference, weight, group, init_score, predictor, silent, feature_name, categorical_feature, params)
    763                 c_str(params_str),
    764                 ref_dataset,
--> 765                 ctypes.byref(self.handle)))
    766         elif isinstance(data, scipy.sparse.csr_matrix):
    767             self.__init_from_csr(data, params_str, ref_dataset)

~/anaconda3/envs/fin/lib/python3.6/site-packages/lightgbm/basic.py in _safe_call(ret)
     43     """
     44     if ret != 0:
---> 45         raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))
     46 
     47 

LightGBMError: Input format error when parsing as CSV

## Reproducible examples
[csv_error_example.zip](https://github.com/Microsoft/LightGBM/files/2574641/csv_error_example.zip)

## Steps to reproduce

1. Unzip attached file (csv_error_example.zip) - contains working_example.csv, failing_example.csv, and an ipynb demonstrating the error
2. Run notebook

**Comment by guolinke** [comment]
@gbatt LightGBM only accepts the csv with valid number format, if even these string columns are set to ignore.

**Comment by gbatt** [comment]
> @gbatt LightGBM only accepts the csv with valid number format, if even these string columns are set to ignore.

Thanks @guolinke! 

I did not see this anywhere in the documentation (perhaps I missed this), but if it is indeed not present anywhere, can we add it so that other users in the future do not face this issue?
