### ISSUE TITLE
I can't install lightGBM in R

### ISSUE THREAD

**Issue by weisskatze** [Microsoft/LightGBM#1847]
## Environment info

Operating System: Windows 10

CPU/GPU model: Ryzen 3 2200g

C++/Python/R version: R 3.5.1

## Error message
Downloading GitHub repo Microsoft/LightGBM@master
from URL https://api.github.com/repos/Microsoft/LightGBM/zipball/master
Installing lightgbm
"C:/PROGRA~1/R/R-35~1.1/bin/x64/R" --no-site-file --no-environ --no-save --no-restore  \
  --quiet CMD INSTALL  \
  "C:/Users/Public/Documents/ESTsoft/CreatorTemp/Rtmpgj4D3a/devtools1bdc3b9b678d/Microsoft-LightGBM-a694712/R-package"  \
  --library="C:/Users/Sihyun Kwon/Documents/R/win-library/3.5" --install-tests  \
  --no-multiarch 

* installing *source* package 'lightgbm' ...
** libs
c:/Rtools/mingw_64/bin/gcc  -I"C:/PROGRA~1/R/R-35~1.1/include" -DNDEBUG          -O2 -Wall  -std=gnu99 -mtune=generic -c R_init.c -o R_init.o
c:/Rtools/mingw_64/bin/gcc -shared -s -static-libgcc -o lightgbm.dll tmp.def R_init.o -LC:/PROGRA~1/R/R-35~1.1/bin/x64 -lR
installing via 'install.libs.R' to C:/Users/Sihyun Kwon/Documents/R/win-library/3.5/lightgbm
Error in eval(ei, envir) : Copying CMakeLists failed
* removing 'C:/Users/Sihyun Kwon/Documents/R/win-library/3.5/lightgbm'
In R CMD INSTALL
Installation failed: Command failed (1)
Warning message:
GitHub repo contains submodules, may not function as expected! 

## Reproducible examples

devtools::install_github("Laurae2/lgbdl", force= TRUE)
options(devtools.install.args = "--no-multiarch")

install_github("Microsoft/LightGBM", subdir = "R-package")

I tried a lot of things for 5 hours, but I couldn't.
I also found many ways for this issue, but it didn't work.
How can I solve this issue?
@Laurae2 
@BruceZhaoR

**Comment by weisskatze** [comment]
> @weisskatze `devtools` can't work when there is a space in your library path on Windows(**not sure if it works now**),
> like `C:/Users/Sihyun Kwon/Documents/R/win-library/3.5`. Mabe try another dir to put your user library, such as `C:/R/R-3.5-library`.
> If you moved your libraries, you should use `.libpath(C:/R/R-3.5-library)` and add it to `R.home/etc/Rprofile.site` as startup.

How can I add  `.libpath(C:/R/R-3.5-library)` to `R.home/etc/Rprofile.site` ?

**Comment by weisskatze** [comment]
> @weisskatze `devtools` can't work when there is a space in your library path on Windows(**not sure if it works now**),
> like `C:/Users/Sihyun Kwon/Documents/R/win-library/3.5`. Mabe try another dir to put your user library, such as `C:/R/R-3.5-library`.
> If you moved your libraries, you should use `.libpath(C:/R/R-3.5-library)` and add it to `R.home/etc/Rprofile.site` as startup.

@BruceZhaoR 
I uninstalled R, and install it again into a different directory.
So, I could install 'devtools' into new dir, but there is still same error.
What is a problem?

**Comment by Laurae2** [comment]
Your .libPaths() should point first to your R library folder which has no space.
devtools actually works with a space, but here it is not because we don't support spaces in extra commands for compilation.

In Windows I would always run R/RStudio as Administrator from a fresh R installation to make sure there is no incompatibility issue with the library folder path.

**Comment by weisskatze** [comment]
> Your .libPaths() should point first to your R library folder which has no space.
> devtools actually works with a space, but here it is not because we don't support spaces in extra commands for compilation.
> 
> In Windows I would always run R/RStudio as Administrator from a fresh R installation to make sure there is no incompatibility issue with the library folder path.

Thanks a lot!! I solved this issue : )
