### ISSUE TITLE
Please add reset_data to lgb.cv

### ISSUE THREAD

**Issue by NamLQ** [Microsoft/LightGBM#1854]
The lgb.train has the argument `reset_data = T` to release the data from the model as in https://github.com/Microsoft/LightGBM/issues/879. In the case of multiple k-fold cv the RAM is eaten so fast, so it would much better if lgb.cv also has the argument `reset_data`. 

Thank you very much.

**Comment by guolinke** [comment]
@NamLQ you can call gc every time after cv, since lgb.cv don't save cv-folds objects.

**Comment by guolinke** [comment]
sorry, it seems R-package returns a CV-booster. 
@Laurae2 it that possible to only returns the cv-results like in python-package: https://github.com/Microsoft/LightGBM/blob/master/python-package/lightgbm/engine.py#L501 ?

**Comment by guolinke** [comment]
@Laurae2 @StrikerRUS 
why the cv has different behaviours (return results) in python and R package.
Should we make them the same?

**Comment by guolinke** [comment]
@NamLQ updated

**Comment by StrikerRUS** [comment]
@guolinke I've discovered LightGBM when `cv` has been already implemented, therefore I don't know.

Also, we have several issues about Python `cv` behavior enhancements: #283, #1445, #1105.
