### ISSUE TITLE
Incorrect result returned by LightGBM with LGBM_BoosterPredictForMat

### ISSUE THREAD

**Issue by lv-zhaoyu** [Microsoft/LightGBM#1856]
## Environment info

Operating System: Linux

C++/Python/R version: C++ 11

## Error message

when I use LightGBM C_API  LGBM_BoosterPredictForMat to predict, the same input but different predict result;

input 22.303967,110.944046,5,90,1.000,0.617,0.0164,0.581,190,28,86,883.01,99.00,225.47,86,92,91,123,1,1.00,0.61,10.00,30
The initial time is :0
[LightGBM] [Info] ------ gbdt predict
Prediction out Result is 0.001278 

The initial time is :0
[LightGBM] [Info] ------ gbdt predict
Prediction out Result is 0.098537 

## paraments

    int data_type = C_API_DTYPE_FLOAT32;
    int row=1;
    int columns=23;
    int is_row_major=1;
    int predict_type= 0;//C_API_PREDICT_NORMAL;
    int num_iteration=5000;
    int64_t outlen=1;
    double outresult=0;
    printf("start predict\n");
    timeval tBegin, tEnd, Diff_time;
    gettimeofday(&tBegin, 0);
    printf("input %s\n",inputdata.c_str());
    int suc2 =
LGBM_BoosterPredictForMat(out,&inputdata,data_type,row,columns,is_row_major,predict_type,num_iteration,"early_stopping=10000",&outlen,&outresult);

**Comment by guolinke** [comment]
@lv-zhaoyu 
you may need to set `outresult` to all zeros every time before calling LGBM_BoosterPredictForMat.

**Comment by guolinke** [comment]
@lv-zhaoyu 
The input data should be an array (float32 type in your case), not the string.
From your log, it seems the inputdata is std::string.

**Comment by lv-zhaoyu** [comment]
It works .thanks!

**Comment by MenglaiWang** [comment]
hi，@guolinke 最近在使用C API的LGBM_BoosterPredictForMat函数时，产出结果和用命令行产出的结果不一致。辛苦抽空帮忙看一下，万分感谢！
原始数据如下，第一列是label：
`1	0	1	0	0	0	0	-1	-1	1	15.69	46.32	0.338730569948	3469888	3000397	0.348328977823`
python调用脚本如下：
`# coding: utf-8
# pylint: skip-file
import ctypes
import os
import sys

from platform import system

import numpy as np
from scipy import sparse


def LoadDll():
    lib_path='./lib_lightgbm.so'
    lib = ctypes.cdll.LoadLibrary(lib_path)
    return lib


LIB = LoadDll()

LIB.LGBM_GetLastError.restype = ctypes.c_char_p

dtype_float32 = 0
dtype_float64 = 1
dtype_int32 = 2
dtype_int64 = 3


def c_array(ctype, values):
    return (ctype * len(values))(*values)


def c_str(string):
    return ctypes.c_char_p(string.encode('ascii'))


def test_booster():
    booster2 = ctypes.c_void_p()
    num_total_model = ctypes.c_long()
    LIB.LGBM_BoosterCreateFromModelfile(
        c_str('LightGBM_model.txt'),
        ctypes.byref(num_total_model),
        ctypes.byref(booster2))
    data = []
    with open(os.path.join(os.path.dirname(os.path.realpath(__file__)),
                           './binary.test'), 'r') as inp:
        for line in inp.readlines():
            data.append([float(x) for x in line.split('\t')[1:]])
    mat = np.array(data)
    preb = np.zeros(mat.shape[0], dtype=np.float64)
    num_preb = ctypes.c_long()
    data = np.array(mat.reshape(mat.size), copy=False)
    LIB.LGBM_BoosterPredictForMat(
        booster2,
        data.ctypes.data_as(ctypes.POINTER(ctypes.c_void_p)),
        dtype_float64,
        mat.shape[0],
        mat.shape[1],
        1,
        0,
        100,
        c_str(''),
        ctypes.byref(num_preb),
        preb.ctypes.data_as(ctypes.POINTER(ctypes.c_double)))
    for s in preb:
        print s
    LIB.LGBM_BoosterFree(booster2)
test_booster()`
api调用结果是0.0195047078089
C++命令行结果是0.34214991867081529
不知道是哪里出了问题。模型文件见附件。
[LightGBM_model.txt](https://github.com/Microsoft/LightGBM/files/2864990/LightGBM_model.txt)

**Comment by MenglaiWang** [comment]
找到问题了，和格式有关。格式一致以后就正常了。
