### ISSUE TITLE
A bug with pred_contrib=True

### ISSUE THREAD

**Issue by canorbal** [Microsoft/LightGBM#1857]
Hi!

There is a bug with predict(data, pred_contrib=True) when we want to count shap values. Usually, the output of shap values calculation has the following shape (len(data), num_features). Check this [link](https://tech.yandex.com/catboost/doc/dg/concepts/output-data_feature-analysis_shap-values-docpage/) for catboost and check predict function [here](https://xgboost.readthedocs.io/en/latest/python/python_api.html) for xgboost. Also, you can check the official explanation of shap values [here](https://github.com/slundberg/shap/blob/master/notebooks/tree_explainer/Understanding%20Tree%20SHAP%20for%20Simple%20Models.ipynb)

In this [line](https://github.com/Microsoft/LightGBM/blob/master/python-package/lightgbm/basic.py#L540) the output of predict function of LightGBM Booster is hardcoded to have output shape 1d instead of 2d.

**Comment by StrikerRUS** [comment]
Hi @canorbal !

The line you're pointing is the raw pre-result which is reshaped later.

The actual output for predict_`contrib` is 
https://github.com/Microsoft/LightGBM/blob/a694712b7fb86cd532eea2c1781b58d4ba58436a/python-package/lightgbm/sklearn.py#L591
So, it's always has 2D shape.

Please provide the example when you get 1D result.

**Comment by canorbal** [comment]
Sorry 

Everything is ok

**Comment by StrikerRUS** [comment]
Glad that now everything is clear for you!

The reason why I provided description from sklearn is that it just calls `Booster.predict()`
https://github.com/Microsoft/LightGBM/blob/a694712b7fb86cd532eea2c1781b58d4ba58436a/python-package/lightgbm/sklearn.py#L604-L605
And the reshaping is performed here:
https://github.com/Microsoft/LightGBM/blob/a694712b7fb86cd532eea2c1781b58d4ba58436a/python-package/lightgbm/basic.py#L476-L481

**Comment by canorbal** [comment]
@StrikerRUS thank you very much!

The problem appeared because of in xgboost the flag for shap values is called "pred_contribs" and in LightGBM is "pred_contrib". There was no error message and it was difficult to find bug in my own code :)

**Comment by StrikerRUS** [comment]
Oh, I see! That makes sense. It was assuming that `pred_contribs` is an argument from `**kwargs`. However, when I pass `pred_contribs` I see the following warning:
```
[LightGBM] [Warning] Unknown parameter: pred_contribs
```

P.S. If you use Jupyter Notebook, then all warnings are printed to stdout of Jupyter console, not notebook's cells output.

![image](https://user-images.githubusercontent.com/25141164/48783791-54939900-ecf2-11e8-801b-d6ffd3d5d36d.png)
