### ISSUE TITLE
Build and store appveyor artifacts

### ISSUE THREAD

**Issue by KOLANICH** [Microsoft/LightGBM#1860]
It'd be nice if you enabled storage of the artifacts on Appveyor.

**Comment by StrikerRUS** [comment]
@KOLANICH We were doing this in the past.

Now all artifacts can be found in the one place - Azure Pipelines.

Is there any reason why Appveyor is more preferable than Azure?

![image](https://user-images.githubusercontent.com/25141164/48833320-25316a80-ed8c-11e8-9c2f-5257b9fb2ec2.png)

**Comment by KOLANICH** [comment]
>Now all artifacts can be found in the one place - Azure Pipelines.

Thank you for the info. Though I don't see any really good reason to make appveor to discard artifacts.

**Comment by KOLANICH** [comment]
BTW, is it possible to add to readme the direct links to the latest binaries of artifacts?

**Comment by StrikerRUS** [comment]
>Though I don't see any really good reason to make appveor to discard artifacts.

Duplicated work, additional time for CI checks, only `dll` artifact can be published by Appveyor, artifacts from Azure are better tested before publishing, older VS version on Appveyor, additional questions from users about which artifact they should choose, etc.

To sum up, we won't publish (publicly available) artifacts from Appveyor without special reason. Sorry.

>BTW, is it possible to add to readme the direct links to the latest binaries of artifacts?

I think it's good thought! Where do you think we should place such link?

**Comment by KOLANICH** [comment]
>Duplicated work

redundancy, fail-safeness. and the work is duplicated anyway, but then wasted.

>only dll artifact can be published by Appveyor

not true. I have set up building publishing python wheels in other JPype for many versions of python, you can see how it is done there.

>additional questions from users about which artifact they should choose, etc.

It gives them a choice. It would be better to have a deterministic build though.

>Where do you think we should place such link?

Under the line of badges create a yet another line of badges, each badge for each combination of python version and platform shows the build status of that job, the link leads to wheel.
