### ISSUE TITLE
is there a c++ example of lightgbm predict calling python trained model? I can not find the c++ api that predict data by one row

### ISSUE THREAD

**Issue by xiaopangjun** [Microsoft/LightGBM#1866]
## Environment info

Operating System: linux

CPU/GPU model:cpu

C++/Python/R version:
c++
## question
I trained a lightgbm model in python, and saved as a model file, then I want to predict new data in C++. I search in the web but cannot find a good example.

**Comment by guolinke** [comment]
you can use the trained model files, with compiled lightgbm execute files (like exe) to run your prediciton. refer to https://github.com/Microsoft/LightGBM/tree/master/examples/binary_classification#prediction
