### ISSUE TITLE
Are there more Python examples in classification and prediction?

### ISSUE THREAD

**Issue by neal668** [Microsoft/LightGBM#188]
## Environment info
Operating System: Centos 6.0
CPU: Core i5-3320M

## Error Message:
The listed three python examples is good. However, can please provide more examples in classification and predictions (include the use of parameters)?

**Comment by wxchan** [comment]
What kind of examples would you like? You can give us an example what task you are facing.

**Comment by neal668** [comment]
@wxchan Hi, I am using LightGBM for some classification task in Python. By following the examples provided, I notice LightGBM can provide the leaf index in prediction process, in basic.py, as shown below

pred_leaf : bool
            True for predict leaf index

Setting this parameter as True, I didn't see the predicted leaf index thus I hope could provide some more  Python examples. Thank you for your time.

**Comment by wxchan** [comment]
just set pred_leaf=True

for example, change https://github.com/Microsoft/LightGBM/blob/master/examples/python-guide/simple_example.py#L50 to `y_leaf = gbm.predict(X_test, pred_leaf=True)`

**Comment by neal668** [comment]
@wxchan  Many thanks. I tried this method. However, in the simple-example.py, some mistake occurs. I prefer this example is on regression instead of classification.

![image](https://cloud.githubusercontent.com/assets/15664226/21806400/f5abcb1e-d773-11e6-8c4d-4adf0be46245.png)

After delete this code, the program worked while I could not find where the result was saved. Thus I said I am not clear about the use of prediction function.

**Comment by guolinke** [comment]
@neal668 
Just comment this line: https://github.com/Microsoft/LightGBM/blob/master/examples/python-guide/simple_example.py#L52

the prediction result is saved to the return value of Line50

**Comment by neal668** [comment]
@guolinke Thank you for your help
