### ISSUE TITLE
[R-package] LightGBM OpenCL is broken

### ISSUE THREAD

**Issue by Laurae2** [Microsoft/LightGBM#1880]
Currently, LightGBM R installation with GPU support is broken.

More information: https://github.com/Laurae2/lgbdl/issues/5

ping @jameslamb

**Comment by jameslamb** [comment]
@Laurae2 How do you foresee addressing this issue? I propose we use an environment variable to control:

a) copying in the boost submodule to the right place
b) setting the use_gpu flag

Does that make sense? I have correctly interpreted the resolution on that issue?

**Comment by Laurae2** [comment]
@jameslamb You need to modify the R install script (https://github.com/Microsoft/LightGBM/blob/master/build_r.R) to add something like this:

https://github.com/Laurae2/lgbdl/commit/b36919201ce1998de29e9a5f6de69459f03f5364

I could not manage to change your script to add something similar, there was always something wrong/missing due to the handling of trailing "/" + folder existence.

**Comment by jameslamb** [comment]
@Laurae2 looks like this is addressed by #1918 , can you confirm?

**Comment by Laurae2** [comment]
@jameslamb yes it is correct by that one.
