### ISSUE TITLE
[R] int overflow in LGBM_BoosterCalcNumPredict_R

### ISSUE THREAD

**Issue by nbenn** [Microsoft/LightGBM#1884]
I'm skipping the reproducible example, but I can add one on request.

If I call `predict.lgb.Booster()` on a sufficiently large test dataset (e.g. 120 cols, 3.5M rows) in a multiclass setting with 700 classes (`n_col * n_class > .Machine$integer.max`), I get an error

```
Error in numeric(npred) : invalid 'length' argument

11: numeric(npred)
10: predictor$predict(data, num_iteration, rawscore, predleaf, predcontrib,
        header, reshape)
9: object$predict(data, num_iteration, rawscore, predleaf, predcontrib,
       header, reshape, ...)
8: predict.lgb.Booster(mod, test_dat, reshape = TRUE)
```

This comes from `LGBM_BoosterCalcNumPredict_R` returning something that looks like an overflowed value (`-1792749607` in my case), which in turn is an invalid `length` arg to `numeric()`.

A fix similar to e55c815821f0abbb23d52a391a622a2c96e6ba14, in response to #1861, might resolve this issue as well.

The same problem *might* also show up in
* `LGBM_BoosterGetNumPredict_R`
* `LGBM_BoosterGetPredict_R `

**Comment by guolinke** [comment]
I remember this is limited by R, ao its int type is int32

**Comment by Laurae2** [comment]
Ah, Matrix of 3.5m x 700 > 2^32. Therefore, we can't solve it unless we were to choose a less flexible data structure.
Have to wait R to support matrices of size >2^32.

**Comment by nbenn** [comment]
@Laurae2 @guolinke thanks for taking an interest in this issue.

Could you please elaborate a bit on the exact limitation imposed by R?

R 3.0.0 introduced support for long vectors, using the `R_xlen_t` type as index (see [source](https://github.com/wch/r-source/blob/4b1ec20ba6620a389449eda54c8b842d5173c967/src/main/array.c#L205) and [docs](https://stat.ethz.ch/R-manual/R-patched/library/base/html/LongVectors.html)). So in any reasonably recent R version, matrices of length greater than 2^32 are most definitely supported (as long as n_row and n_col can each be represented by int32).

If the problem is to communicate an int64 value to an R session, there exists a CRAN package that enables support for this: [bit64](https://cran.r-project.org/package=bit64).

**Comment by Laurae2** [comment]
@nbenn Matrices in R do not support a number of elements larger than 2^32 even if they are vectors behind the hood (because not all operations are supported). Only vectors do (long int).

**Comment by nbenn** [comment]
I'm sorry, but I still don't precisely understand you claim. Are you saying that in base R, a matrix with more than 2^32 elements is not supported?

**Comment by nbenn** [comment]
@Laurae2 If you are interested in this, please help me understand what you think the limitation imposed by R is exactly. Currently, I believe that the problem you see is actually based on a misconception on your side. Of course, I might very well be mistaken, either due to a misunderstanding between us or due to lacking understanding of R on my side.

**Comment by Laurae2** [comment]
@nbenn Actually you are right, I mixed the two following stuff:

* Matrices do support 2^31+ values
* Matrices do not support more than 2^31+ rows or columns

@guolinke I think a workaround is possible if we use `long int` instead of only `int`.

Perhaps changing the following to long int (or defining a new type) may work? (not sure what else requires to be modified)

https://github.com/Microsoft/LightGBM/blob/5bee6489ac4293328c826e72e7de339206c456da/include/LightGBM/R_object_helper.h#L129

**Comment by guolinke** [comment]
thanks @Laurae2 
How about CSC format?

**Comment by Laurae2** [comment]
@guolinke CSC format currently should not be able handle more than 2^31-1 elements because it uses int. I'll try to work on a package for big CSC format as a workaround.

Do you know if LightGBM handles more than int32 rows?
