### ISSUE TITLE
[PYTHON]Can I use roc_auc_score or accuracy_score for evaluating Multi-class classification in the LightGBM?

### ISSUE THREAD

**Issue by saksim** [Microsoft/LightGBM#1885]
Hello,guys:
    I am a newcomer in LightGBM.  Using the LightGBM to train million data for getting a multiclass Train-Model contains num_class*num_iterations trees. However, the model_evaluate method does not work!

My setting as follows:
    Params = {
            'num_class': 9,
            'boosting_type': 'gbdt',
            'objective': 'multiclass',
            'learning_rate': 0.1,
            'max_depth': 4
              }
Get the train model:
   trainModel = lgb.train(params,lgb_train,num_boost_round=100)

Evaluate:
   y_test = trainModel.predict(test_data)
   train_auc = roc_auc_score(y, y_test)

However,  when I print train_auc out, there is nothing printed and no error printed. Does any one have ideas?

**Comment by guolinke** [comment]
I think this is not a LightGBM's issue. 
refer to https://scikit-learn.org/stable/auto_examples/model_selection/plot_roc.html 
https://www.researchgate.net/post/Is_it_possible_to_plot_a_ROC_curve_for_a_multiclass_classification_algorithm_to_study_its_performance_or_is_it_better_to_analyze_by_confusion_matrix

**Comment by saksim** [comment]
> I think this is not a LightGBM's issue.
> refer to https://scikit-learn.org/stable/auto_examples/model_selection/plot_roc.html
> https://www.researchgate.net/post/Is_it_possible_to_plot_a_ROC_curve_for_a_multiclass_classification_algorithm_to_study_its_performance_or_is_it_better_to_analyze_by_confusion_matrix

Yes, it seems not a LightGBM's issue. Thanks for your recommendation materials. 
Best Wishes
