### ISSUE TITLE
Incorrect bin bounds for toy example

### ISSUE THREAD

**Issue by cbecker** [Microsoft/LightGBM#189]
hi. First thanks for LightGBM, I am so far very happy with it.

I found out that there is an issue with the bin finder, in a very simple example.
To reproduce, you can compile this example https://gist.github.com/cbecker/fb628bec3c179fc49617ba369cbb1aab

It creates a 2-class toy example, where each class is a unit-standard-deviation Gaussian, with means 0 and 10 respectively. Training error should be almost 0%.

However, if using the default number of bins (255), it does really bad: 44% training error.
The training error is computed at the end of the script.

Let me know if I can provide you with more information, or if I am making a mistake somewhere.

**Comment by guolinke** [comment]
@cbecker 
The error is caused by this line: https://gist.github.com/cbecker/fb628bec3c179fc49617ba369cbb1aab#file-main-cpp-L63
it should be ```dset.reset( loader.CostructFromSampleData(sampleData, numSamples, numSamples) );``` 
The second argument is ```sample_cnt```, not the number of features. 

BTW, For 2 class classification, you can use ```binray```.

**Comment by cbecker** [comment]
Thanks, that fixes it.

Can I find the documentation of the C++ api somewhere? It took me a while to make this example, as I was missing some information and had to guess it from how the C api files.

I am closing this issue, problem solved :)
