### ISSUE TITLE
Loading a model within Pytest exits the program

### ISSUE THREAD

**Issue by brandonschabell** [Microsoft/LightGBM#1892]
## Environment info

Operating System: Windows 10

CPU/GPU model: Intel i7-8550U (no GPU)

C++/Python/R version: Python 3.6.7

## Error message

Launching pytest with arguments test_lightgbm.py::test_load_model in C:\Git\LightGBMModel\tests\

============================= test session starts =============================
platform win32 -- Python 3.6.7, pytest-4.0.1, py-1.7.0, pluggy-0.8.0
rootdir: C:\Git\LightGBMModel, inifile:collected 1 item

test_lightgbm.py 
Process finished with exit code -1073740791 (0xC0000409)

## Reproducible examples

```python
import lightgbm as lgb

def test_load_model():
    try:
        bst = lgb.Booster(model_file='saved_model.txt')
    except Exception as e:
        print(e)
```

## Steps to reproduce

1. Create a simple test that loads a model.
2. Run the test using Pytest
3. The test will not finish running, an exit code of -1073740791 is given.

Note: If the model_file argument is removed, the test passes.

**Comment by brandonschabell** [comment]
Update: This error occurs when the weights I'm loading were generated from an LGBMClassifier(), not when using lgb.train().

**Comment by StrikerRUS** [comment]
Hi @brandonschabell !

This behavior was discussed in #1217.
