### ISSUE TITLE
when i use csr_matrix as my data format,need i set which col is the label?

### ISSUE THREAD

**Issue by Simon-Liu622** [Microsoft/LightGBM#190]
Is there any example for this,Only i find this:
csr = scipy.sparse.csr_matrix((dat, (row, col)))
train_data = lgb.Dataset(csr)
but i think the code can't know which is the label?

**Comment by guolinke** [comment]
@Simon-Liu622 
you can should pass an additional array as label.
```
label = ...
csr = scipy.sparse.csr_matrix((dat, (row, col)))
train_data = lgb.Dataset(csr, label=label)
```

**Comment by Simon-Liu622** [comment]
thx a lot!
