### ISSUE TITLE
Error installing lgbm with gpu support ubuntu 18.04

### ISSUE THREAD

**Issue by melgazar9** [Microsoft/LightGBM#1901]
## Environment info

Operating System: Ubuntu 18.04

CPU/GPU model: GPU - NVIDIA 1080TI

C++/Python/R version: Python 3.6.6

## Error message

LightGBMError                             Traceback (most recent call last)
<ipython-input-44-cecb4634e72d> in <module>
----> 1 model.fit(x,y)

~/anaconda3/lib/python3.6/site-packages/lightgbm/sklearn.py in fit(self, X, y, sample_weight, init_score, eval_set, eval_names, eval_sample_weight, eval_class_weight, eval_init_score, eval_metric, early_stopping_rounds, verbose, feature_name, categorical_feature, callbacks)
    698                                         verbose=verbose, feature_name=feature_name,
    699                                         categorical_feature=categorical_feature,
--> 700                                         callbacks=callbacks)
    701         return self
    702 

~/anaconda3/lib/python3.6/site-packages/lightgbm/sklearn.py in fit(self, X, y, sample_weight, init_score, group, eval_set, eval_names, eval_sample_weight, eval_class_weight, eval_init_score, eval_group, eval_metric, early_stopping_rounds, verbose, feature_name, categorical_feature, callbacks)
    500                               verbose_eval=verbose, feature_name=feature_name,
    501                               categorical_feature=categorical_feature,
--> 502                               callbacks=callbacks)
    503 
    504         if evals_result:

~/anaconda3/lib/python3.6/site-packages/lightgbm/engine.py in train(params, train_set, num_boost_round, valid_sets, valid_names, fobj, feval, init_model, feature_name, categorical_feature, early_stopping_rounds, evals_result, verbose_eval, learning_rates, keep_training_booster, callbacks)
    190     # construct booster
    191     try:
--> 192         booster = Booster(params=params, train_set=train_set)
    193         if is_valid_contain_train:
    194             booster.set_train_data_name(train_data_name)

~/anaconda3/lib/python3.6/site-packages/lightgbm/basic.py in __init__(self, params, train_set, model_file, silent)
   1487                 train_set.construct().handle,
   1488                 c_str(params_str),
-> 1489                 ctypes.byref(self.handle)))
   1490             # save reference to data
   1491             self.train_set = train_set

~/anaconda3/lib/python3.6/site-packages/lightgbm/basic.py in _safe_call(ret)
     43     """
     44     if ret != 0:
---> 45         raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))
     46 
     47 

LightGBMError: GPU Tree Learner was not enabled in this build.
Please recompile with CMake option -DUSE_GPU=1

I have cuda properly installed since I can use Keras and Tensorflow. My steps for installing LGBM with gpu support are on the website. I am also using anaconda and tried following this link but get the same error https://github.com/dsmilab/WSDM2018-KKBox-MRC/wiki/Install-LightGBM-within-anaconda3-with-GPU-support

When I set model = LGBMClassifier() the model fits. I can call model.fit(X,y). However I cannot when I call model = LGBMClassifier(device='gpu')

**Comment by StrikerRUS** [comment]
Hi @melgazar9 !

Here is the guide how to install GPU version of LightGBM with one-line command:
https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-version

**Comment by melgazar9** [comment]
It says all packages are already installed. I still get the same error

LightGBMError: GPU Tree Learner was not enabled in this build.
Please recompile with CMake option -DUSE_GPU=1

**Comment by melgazar9** [comment]
Hello - I have tried this along with many other steps but I am running into the same issue. I don't think I'm doing anything outside of the directions. Take a look at the screen shots. It says it successfully installed but I cannot use the gpu version of LGBM. 

![screenshot from 2018-12-12 22-48-19](https://user-images.githubusercontent.com/31749392/49916353-18220b80-fe60-11e8-9c64-2e904d4a31eb.png)
![screenshot from 2018-12-12 22-48-31](https://user-images.githubusercontent.com/31749392/49916354-18220b80-fe60-11e8-87ed-03ed03340018.png)

**Comment by StrikerRUS** [comment]
Hmm, I see you're installing GPU version in `lgbm-gpu` conda environment, but the error is raisied from **default** conda environment. You should run your Python session from the same environment where LightGBM GPU is installed.

![49916353-18220b80-fe60-11e8-9c64-2e904d4a31eb](https://user-images.githubusercontent.com/25141164/49934328-219e8880-fedf-11e8-8c25-68d1c4ac49dc.png)

![49916354-18220b80-fe60-11e8-87ed-03ed03340018](https://user-images.githubusercontent.com/25141164/49934329-219e8880-fedf-11e8-9441-d3455d78a241.png)

**Comment by melgazar9** [comment]
I tried installing it both in base environment and in lgbm-gpu conda environment and receive the same issue. Regardless of what environment I'm in I still get that location. Please take a look at the attached screen shots.

file:///home/melgazar9/Pictures/Screenshot%20from%202018-12-13%2010-11-06.png
file:///home/melgazar9/Pictures/Screenshot%20from%202018-12-13%2010-15-52.png

**Comment by StrikerRUS** [comment]
Try to uninstall LightGBM from base environment and install GPU version there, if you cannot launch Python from `lgbm-gpu` environment.

**Comment by StrikerRUS** [comment]
Also, read this: https://github.com/ipython/ipython/issues/10986#issuecomment-385742255, https://stackoverflow.com/questions/44682872/using-conda-environment-in-ipython-interactive-shell.

And I suppose that the easiest way to fix your environment problem is reinstalling Anaconda from scratch.

**Comment by melgazar9** [comment]
Ahh got it working by uninstalling lightgbm from base! I reinstalled it to the conda environment lgbm-gpu. Thanks!

**Comment by StrikerRUS** [comment]
Glad that you've solved the problem!
