### ISSUE TITLE
model become bigger

### ISSUE THREAD

**Issue by ganzhiruyi** [Microsoft/LightGBM#1903]
I complied lightgbm from 2.0.6 to 2.2, the model size increase from 12M to 2.2G. There is no difference among config and train data. Is there any new parameter to control the model size? Thanks.

**Comment by guolinke** [comment]
do you have categorical features in your data ?

**Comment by ganzhiruyi** [comment]
> do you have categorical features in your data ?

Yes, I have some categorical features, is there any changes from 2.0.6 to 2.2?
![image](https://user-images.githubusercontent.com/4384420/49992630-947f3080-ffbf-11e8-96fc-0619c29a7207.png)

**Comment by guolinke** [comment]
Yes, refer to https://github.com/Microsoft/LightGBM/pull/762

**Comment by ganzhiruyi** [comment]
> Yes, refer to #762

Ok, thanks for your time!
