### ISSUE TITLE
[R]Unable to install LGBM, due to CMake being recognised by our organisation’s antivirus as a Trojan. Any chance for CRAN/non-CMake installation?

### ISSUE THREAD

**Issue by mant07** [Microsoft/LightGBM#1904]
As in title. I can’t install CMake on organisation’s computers, because CMake was marked by our security department as a Trojan. We have quite restrictive software security policies and I do not have admin rights to my PC. Any chance to install LGBM without CMake?

**Comment by Laurae2** [comment]
Ping @guolinke @jameslamb

**Comment by guolinke** [comment]
If your os is Windows, you can build the LightGBM dll by visual studio/ms build, then install R package via pre-compiled solution.

**Comment by mant07** [comment]
@guolinke - R-package installation guide (  https://github.com/Microsoft/LightGBM/tree/master/R-package) states that CMake is still needed while installing from precompiled dll. Or is it not true anymore?

**Comment by Laurae2** [comment]
@mant07 cmake is not used for precompiled DLL when installing from R.

However, precompiled DLL requires cmake (or, use Visual Studio if you are allowed).

**Comment by StrikerRUS** [comment]
Linking https://github.com/Microsoft/LightGBM/issues/1702#issuecomment-453817191 here.

@mant07  You may want to track #629 (and #1910, #1909 for subissues) for release on CRAN progress.
