### ISSUE TITLE
predicting single numpy/sparse matrix row with model trained using libsvm dataset has inconsistent results

### ISSUE THREAD

**Issue by byte-dance** [Microsoft/LightGBM#1908]
## Environment info

Operating System:
osx
CPU/GPU model:
cpu
C++/Python/R version:
python
## Reproducible examples

```
data = "1:4050.0 2:26309.0 3:5973.5735 4:17478.0 5:19111.0 6:0.1539 7:0.2271 8:0.6643 9:0.7264 10:0.494 11:0.8515 12:18 15:0.1003 16:0.1867 34:1.0 53:1.0 59:1.0 65:1.0 68:2.0 78:1.0 79:1.0 89:1.0 94:2.0 99:1.0 104:3.0 108:1.0 113:1.0 118:1.0 119:0.015267175572519083"

data = to_numpy_array(data)
bst = lgb.Booster(model_file=model_file)

res1 = bst.predict(data_numpy)
res2 = bst.predict(path_to_libsvm_data)
```

res1 is completely different with res2, and res2 has the correct prediction result.

## Steps to reproduce

1.train binary classification model using libsvm dataset and save model file
2.load model, predict using single numpy/sparse matrix row record
3.load model, predict with same record above, but put them in file as libsvm format

compare res1 and res2, they are different.

similar issue in [https://github.com/Microsoft/LightGBM/issues/684](url)

**Comment by guolinke** [comment]
LightGBM uses the zero-based libsvm format. You can add a dummy column at first column.
