### ISSUE TITLE
Different max_bin for each predictor

### ISSUE THREAD

**Issue by BlindApe** [microsoft/LightGBM#1921]
Is there a way to set different numbers of bins for each predictor?
This would be useful when a predictor has much more noise than other.
Setting max_bin as an array (one element for each variable) should be very useful.

Could you please give a general idea of which part of code is necessary to change?
Thanks

**Comment by guolinke** [comment]
@BlindApe it is not possible for using different max_bin in different trees, in one GBDT model.
But you can using multiply GBDT model, each with different max_bin

**Comment by BlindApe** [comment]
@guolinke what I want is use different max_bin for each variable, not change across the trees.

That is, for V1 use 63 bins, for V2 use 255 and for V3 use 15. I understand this is done in lgb.Dataset constructor before the model fitting so should be possible to set the bins using an array with different numbers for each variable.

**Comment by guolinke** [comment]
@BlindApe 
This function is not supported yet, but it may is easy to achieve.
Using different max_bin in the loop of bin finder can achieve. 
But it needs to change cpp code, in this file: https://github.com/Microsoft/LightGBM/blob/master/src/io/dataset_loader.cpp

**Comment by StrikerRUS** [comment]
Closed via #2190.
