### ISSUE TITLE
leaf_node is not correspond

### ISSUE THREAD

**Issue by sunjiaxin111** [Microsoft/LightGBM#1922]
when i use gbm.predict(trainX, pred_leaf=True),i get pred_leaf value from 0 to 30,but i get the leaf node from the model file is -1 to -31,how can i correspond?

**Comment by guolinke** [comment]
In model file, we use negative numbers to represent the leaf nodes, and positive numbers for internal nodes. 
And -1 represents to 0-th leaf, -2 represents to 1st leaf, and so on.
