### ISSUE TITLE
share some memory while creating dataset while using the same data

### ISSUE THREAD

**Issue by ebhrz1** [Microsoft/LightGBM#1925]
## Environment info

Operating System:
ubuntu
CPU/GPU model:
GPU
C++/Python/R version:
Python
## Error message
OOM

## Reproducible examples
the situation is that I need to train 6 models using the same data but different labels.I want to train them parallel and I create 6 threads，but when I'm creating the dataset(lgb.Dataset(X,y)) ,the memory useage is instantly up to 60g,and after starting training,OOM happened,all the 128g memory ran out.Because my data is kind of huge(about 10g in the memory),I'm wondering can I use the same data  without allocating extra memory in all the 6 models.Thank you

**Comment by Laurae2** [comment]
@ebhrz1 Are you able to fork the process to re-use the same master data?

**Comment by ebhrz1** [comment]
@Laurae2 Well,the question is ,constructing the dataset will use a lot of memory,multi theads make no sense,not to speak of fork.Eventurally,I trained them one by one.I have seen the code,it seems like while using Dataset(X,y),it's just a lazy initial.And when the taringing starts ,it use a lot of time to 'really' initial it .Is there any param that i can use to completely initial it?Thanks

**Comment by Laurae2** [comment]
@ebhrz1 You may call expicitly `lgb.Dataset.construct` to build the LightGBM binary dataset before training.

**Comment by StrikerRUS** [comment]
@ebhrz1 You can try [`two_round` parameter](https://lightgbm.readthedocs.io/en/latest/Parameters.html#two_round) to decrease the memory usage.
