### ISSUE TITLE
Potential issue in Python plot_tree: Always taking left node as default True

### ISSUE THREAD

**Issue by gilgorios** [Microsoft/LightGBM#1926]
In LightGBM/blob/master/python-package/lightgbm/plotting.py lines 294-297 the decission label
allocation for left and right branches of every node is as follows:       
   
```
if root['decision_type'] == '<=':
    l_dec, r_dec = '<=', '>'

elif root['decision_type'] == '==':
    l_dec, r_dec = 'is', "isn't"
```
This code assumes that left branch is always the true one, but there is a "default_left" attribute in 
every node that can be true or false:

```
  "left_child": {
      "decision_type": "==",
      "default_left": false,
   ...
   }
```
If this attribute is inverting the true value of branches the code should be corrected to:

```
if root['decision_type'] == '<=':
    if root['default_left'] == True:
        l_dec, r_dec = '<=', '>'
    else:
        l_dec, r_dec =  '>', '<='
elif root['decision_type'] == '==':
    if root['default_left'] == True:
        l_dec, r_dec = 'is', "isn't"
    else:
        l_dec, r_dec = 'isn't, "is"
```

**Comment by guolinke** [comment]
`default_left` is used for missing value handle.

**Comment by gilgorios** [comment]
That closes the issue. Thanks for the clarification!
