### ISSUE TITLE
modify only label part of a saved binary file

### ISSUE THREAD

**Issue by AStupidBear** [Microsoft/LightGBM#1930]
In my work, I need to train a LGBMRegressor itetatively and at each iteration, x is the same but y changes (the dimensions of x and y are always invariant) . My data is large (around 1T), so it takes a long time to convert raw data to binned data from scratch at every iteration like this:
```python
import lightgbm
dset = lightgbm.Dataset(data=x, label=y) # x is memory mapped so it can fit in memory
dset.save_binary("lgbm.data")
# then run mpirun from command line
```
What I want is to save y independently of x and I know that the python API cannot do this. I think the only way to do this is to modify the coresponding part of y on disk, but I don't know the internal structure of the saved binary and feasibility of this approach. Could you give me some advice?

**Comment by guolinke** [comment]
refer to 
https://github.com/Microsoft/LightGBM/blob/fb28070e1daa500b087d3102145ae48988030195/src/io/dataset.cpp#L542-L621

The label is in `metadata_`.

**Comment by AStupidBear** [comment]
@guolinke is label saved as float32 or uint8? How can I get the starting and ending posision of label?

**Comment by guolinke** [comment]
@AStupidBear refer to
https://github.com/Microsoft/LightGBM/blob/fb28070e1daa500b087d3102145ae48988030195/src/io/metadata.cpp#L512
it is float32. 
The position varies in different data (mainly depends on num_features), you can use my pasted code above to calculate it.

**Comment by AStupidBear** [comment]
@guolinke Thanks!
