### ISSUE TITLE
Install issue OS X / Not loading while installed ?! 

### ISSUE THREAD

**Issue by NicolasGaraude** [Microsoft/LightGBM#1933]
Hi,

I tried to install LightGBM, and I'm running into issues. Before everything, I have Clang 10.0, Cmake 3.12.1, libomp installed, wheels as well. When running the python install here is what I obtain in the Terminal :

MacBook-Pro-de-Nicolas-2:~ nicolasgaraude$ cd LightGBM/python-package
MacBook-Pro-de-Nicolas-2:python-package nicolasgaraude$ python setup.py install
running install
INFO:LightGBM:Starting to compile the library.
INFO:LightGBM:Starting to compile with CMake.
Traceback (most recent call last):
  File "setup.py", line 77, in silent_call
    output = subprocess.check_output(cmd, stderr=subprocess.STDOUT)
  File "/anaconda3/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/anaconda3/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['cmake', '../compile/']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 299, in <module>
    'Topic :: Scientific/Engineering :: Artificial Intelligence'])
  File "/anaconda3/lib/python3.6/site-packages/setuptools/__init__.py", line 140, in setup
    return distutils.core.setup(**attrs)
  File "/anaconda3/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/anaconda3/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 222, in run
    opencl_include_dir=self.opencl_include_dir, opencl_library=self.opencl_library)
  File "setup.py", line 166, in compile_cpp
    silent_call(cmake_cmd, raise_error=True, error_msg='Please install CMake and all required dependencies first')
  File "setup.py", line 86, in silent_call
    raise Exception("\n".join((error_msg, LOG_NOTICE)))
Exception: Please install CMake and all required dependencies first
The full version of error log was saved into /Users/nicolasgaraude/LightGBM_compilation.log

I don't understand the "Please install CMake and all required dependencies first" when I have installed everything. 

I tried the simple version as well :

MacBook-Pro-de-Nicolas-2:python-package nicolasgaraude$ **pip install lightgbm**
Requirement already satisfied: lightgbm in /anaconda3/lib/python3.6/site-packages (2.2.2)
Requirement already satisfied: scipy in /anaconda3/lib/python3.6/site-packages (from lightgbm) (1.1.0)
Requirement already satisfied: numpy in /anaconda3/lib/python3.6/site-packages (from lightgbm) (1.15.1)
Requirement already satisfied: scikit-learn in /anaconda3/lib/python3.6/site-packages (from lightgbm) (0.19.1)

It is showing that lightgbm is installed, but when I try to load it in Python, I obtain the following :

MacBook-Pro-de-Nicolas-2:python-package nicolasgaraude$ python3
Python 3.6.7 |Anaconda custom (64-bit)| (default, Oct 23 2018, 14:01:38) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import lightgbm
/Users/nicolasgaraude/LightGBM/python-package/lightgbm/__init__.py:46: UserWarning: Starting from version 2.2.1, the library file in distribution wheels for macOS is built by the Apple Clang (Xcode_8.3.1) compiler.
This means that in case of installing LightGBM from PyPI via the ``pip install lightgbm`` command, you don't need to install the gcc compiler anymore.
Instead of that, you need to install the OpenMP library, which is required for running LightGBM on the system with the Apple Clang compiler.
You can install the OpenMP library by the following command: ``brew install libomp``.
  "You can install the OpenMP library by the following command: ``brew install libomp``.", UserWarning)

I am completely lost. Can you kindly help me ?

Thanks a lot in advance
Nicolas

**Comment by StrikerRUS** [comment]
Hi @NicolasGaraude !
There are some problems with the latest macOS (Mojave). Tge fix is here: #1923.

Speaking about the installation via `pip`, everithing should be OK with it, if ypu have `libomp` installed on your MacBook. As you can see, this is a **warning**, not error.

**Comment by StrikerRUS** [comment]
For the error happens during the istallation from sources you can track this issue: #1898.

**Comment by NicolasGaraude** [comment]
Hi,

Thanks for the quick answer. But I still don’t understand what I should do :
	- It is said in the link you provided that, given the bugs with Mojave, a hot fix had been made
	- The hot fix has been been 6 days ago, I cloned the GitHub folder 2 hours ago again, so the setup.py file was already containing the hotfix
 
I don’t understand, in simple words, what I have to do, given that libomp is installed on my Macbook (I get : "Warning: libomp 7.0.0 is already installed and up-to-date, To reinstall 7.0.0, run `brew reinstall libomp`).

The pip issue I have is, as was written in my post, that pip shows me that LightGBM is installed, but when I try to launch it in Python, it fails. 

Please help me, this is driving me mad :(

**Comment by StrikerRUS** [comment]
> The hot fix has been been 6 days ago, …

Hotfix hasn't been **merged** yet.

> The pip issue I have is, as was written in my post, that pip shows me that LightGBM is installed, but when I try to launch it in Python, it fails.

You didn't say that you cannot run LightGBM. Please privide a error log.
