### ISSUE TITLE
JSON decoder error when using Shap.TreeExplainer on lightGBM predictor

### ISSUE THREAD

**Issue by kalkairis** [Microsoft/LightGBM#1935]
## Environment info

Operating System: CentOS07

C++/Python/R version: Python3

## Error message

/data1/anaconda3/lib/python3.6/site-packages/lightgbm/basic.py in dump_model(self, num_iteration, start_iteration)
   2109                 ctypes.byref(tmp_out_len),
   2110                 ptr_string_buffer))
-> 2111         ret = json.loads(string_buffer.value.decode())
   2112         ret['pandas_categorical'] = json.loads(json.dumps(self.pandas_categorical,
   2113                                                           default=json_default_with_numpy))

/data1/anaconda3/lib/python3.6/json/__init__.py in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    352             parse_int is None and parse_float is None and
    353             parse_constant is None and object_pairs_hook is None and not kw):
--> 354         return _default_decoder.decode(s)
    355     if cls is None:
    356         cls = JSONDecoder

/data1/anaconda3/lib/python3.6/json/decoder.py in decode(self, s, _w)
    337 
    338         """
--> 339         obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    340         end = _w(s, end).end()
    341         if end != len(s):

/data1/anaconda3/lib/python3.6/json/decoder.py in raw_decode(self, s, idx)
    353         """
    354         try:
--> 355             obj, end = self.scan_once(s, idx)
    356         except StopIteration as err:
    357             raise JSONDecodeError("Expecting value", s, err.value) from None

JSONDecodeError: Expecting ',' delimiter: line 7 column 42224 (char 42339)

## Reproducible examples

shap.TreeExplainer(gbm_predictor)

## Steps to reproduce

1. Create a lightGBM predictor with NaNs
2. Run shap.TreeExplainer(predictor)

**Comment by kalkairis** [comment]
Solved in Shape version 0.27.0

**Comment by billydentsu** [comment]
Sorry for reopening this issue, but I am facing the same issue with:
-lightgbm==2.2.3 and shap==0.30.1
Can you please tell me your lightgbm version?
