### ISSUE TITLE
lightgbm parameters by feature? ex: categoricals/high cardinality

### ISSUE THREAD

**Issue by rquintino** [microsoft/LightGBM#1938]
Hi! is there any way/guidance available or planned feature to allow per column/feature parameterization, ex: categorical features? (on the possibility that different features can gain from different encoding params)
thanks!

**Comment by StrikerRUS** [comment]
ping @guolinke

**Comment by guolinke** [comment]
very sorry for the late response.
@rquintino which parameters you think is needed for per-column parameterization?

**Comment by StrikerRUS** [comment]
ping @rquintino

**Comment by StrikerRUS** [comment]
Closed in favor of being in #2302. We decided to keep all feature requests in one place.

Welcome to contribute this feature! Please re-open this issue (or post a comment if you are not a topic starter) if you are actively working on implementing this feature.
