### ISSUE TITLE
[Python] How to create LGBMClassifier from booster?

### ISSUE THREAD

**Issue by PhilipMay** [Microsoft/LightGBM#1942]
Hi,
I trained a LightGBM booster and saved it to disk with `model_to_string()`.
Then I loaded it with `lgbm_booster = lgb.Booster().model_from_string(model_str)`.

Bit how do I create a LGBMClassifier from my `lgbm_booster ` now?

Can someone please help me?

Thanks
Philip

**Comment by StrikerRUS** [comment]
Hi @PhilipMay !

Unfortunately, it's impossible. You shouldn't mix up sklearn and standard train interfaces.
Please read this issue #1217 and use `joblib` to save/load your sklearn model.

If you really need such possibility for some reason, then you can try the following hacky solution (but it's strongly **NOT** recommended!):

```
from sklearn.datasets import load_iris

import numpy as np
import lightgbm as lgb

X, y = load_iris(True)

clf = lgb.LGBMClassifier()
clf.fit(X, y)

model_str = clf.booster_.model_to_string()
lgbm_booster = lgb.Booster(params={'model_str': model_str})

new_clf = lgb.LGBMClassifier()
new_clf._Booster = lgbm_booster
new_clf._n_features = X.shape[1]
new_clf._n_classes = len(np.unique(y))

np.testing.assert_array_almost_equal(new_clf.predict_proba(X), lgbm_booster.predict(X))
```
