### ISSUE TITLE
[Feature] Probabilistic Random Forest

### ISSUE THREAD

**Issue by akaniklaus** [microsoft/LightGBM#1946]
Dear Everyone, I believe that the following methodology can be a very good addition to the library:

The paper: https://arxiv.org/abs/1811.05994

The code: https://github.com/ireis/PRF

From the abstract of the paper:
> We perform a variety of experiments where we inject different types of noise to a dataset, and compare the accuracy of the PRF to that of RF. The PRF outperforms RF in all cases, with a moderate increase in running time. We find an improvement in classification accuracy of up to 10% in the case of noisy features, and up to 30% in the case of noisy labels. . The PRF accuracy decreased by less then 5% for a dataset with as many as 45% misclassified objects, compared to a clean dataset.

**Comment by StrikerRUS** [comment]
Closed in favor of being in #2302. We decided to keep all feature requests in one place.

Welcome to contribute this feature! Please re-open this issue (or post a comment if you are not a topic starter) if you are actively working on implementing this feature.
