### ISSUE TITLE
dllexport for Booster and other classes

### ISSUE THREAD

**Issue by cbecker** [Microsoft/LightGBM#195]
Is there an interest in exporting classes such as Booster, ObjectiveFunction, Dataset and other classes/functions?

I am writing code that deals with those classes directly and needs them exported, which for Windows needs adding the `dllexport` decl. I can create a PR with the changes if there's interest of having this in the LightGBM upstream repo.

**Comment by chivee** [comment]
Sure, any PR is welcoming. Porting these classes would contributed to the customization in the binding language.

**Comment by cbecker** [comment]
Fixed with https://github.com/Microsoft/LightGBM/pull/203
