### ISSUE TITLE
a question about lightgbm for lambdarank

### ISSUE THREAD

**Issue by RobotZZZZZ** [Microsoft/LightGBM#1950]
In lightgbm, for lambdarank, we need cal ndcg for pairs.

I saw the source code about it,

in the function,"void GetGradientsForOneQuery(...)", lightgbm regular the ndcg by score distance,
       // regular the delta_pair_NDCG by score distance
        if (high_label != low_label && best_score != wrost_score) {
          delta_pair_NDCG /= (0.01f + fabs(delta_score));
        }

I doubt about that, I have seen RankLib for lambdamart, it didn't do the regular.

please tell me, why lightgbm do that ? for what?
I will appreciate it if you can give some citations about it.

**Comment by guolinke** [comment]
@RobotZZZZZ this normalization is for different queries, to avoid the result dominated by query with large scores.

**Comment by RobotZZZZZ** [comment]
hi@guolinke ,
so far as I know, ndcg is normalized dcg in range [0, 1]. why we need normalize again?

**Comment by RobotZZZZZ** [comment]
@guolinke I think about it. 
You means, when training model, we don't want that training is dominated by query with large scores, maybe model is hard to rank them right. we want model focus on what it can do.

**Comment by guolinke** [comment]
@RobotZZZZZ 
yeah, it is similar the `log` or `sqrt` trick for regression program, avoid the bad effect of outliers.
