### ISSUE TITLE
Windows GPU Version Installation Error after cmake -DCMAKE_GENERATOR_PLATFORM=x64 -DUSE_GPU=1 ..

### ISSUE THREAD

**Issue by slfan2013** [Microsoft/LightGBM#1961]
I am following this link to install GPU version on my Windows 10 PC, 
https://github.com/Microsoft/LightGBM/blob/master/docs/Installation-Guide.rst#build-gpu-version. I am using MSVC (visual studio 2017). cmake version is 3.13.3.

When I am in this step,

`cmake -DCMAKE_GENERATOR_PLATFORM=x64 -DUSE_GPU=1 ..`

I got following eror message:
```
  Failed to run MSBuild command:

    C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/MSBuild/15.0/Bin/MSBuild.exe

  to get the value of VCTargetsPath:


    Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework
    Copyright (C) Microsoft Corporation. All rights reserved.

    MSBUILD : error MSB1009: Project file does not exist.
    Switch: VCTargetsPath.vcxproj


  Exit code: 1

```

How to fix this?

**Comment by StrikerRUS** [comment]
Hi @slfan2013 !

Very strange problem! Please provide the full log of your actions in cmd starting from `git clone --recursive https://github.com/Microsoft/LightGBM` command.

Also, please attach your `PATH` variable content and make sure that you aren't executing commands from `C:\WINDOWS\system32` folder (default starting place when you run cmd as administrator).

**Comment by StrikerRUS** [comment]
If this is your [question](https://stackoverflow.com/questions/54208735/cmake-error-at-cmakelists-txt7-project-failed-to-run-msbuild-command), then I see from logs that you are compiling LightGBM in `System32` folder. Do not do this. After changing the directory the problem should be solved.

Feel free to reopen with more details if changing a directory didn't help.
