### ISSUE TITLE
parallel learning to rank，the training ndcg is larger than 1?

### ISSUE THREAD

**Issue by alishandefeng** [Microsoft/LightGBM#1965]
I trained a ranking task in parallel mode, using two machine, I found it the training ndcg is larger than 1,but when i used single machine, the largest ndcg is 1. Is there any problem or bug in parallel mode? Has anyone met this problem? Thanks！

**Comment by guolinke** [comment]
@alishandefeng this seems a bug. Could you provide more details? a reproduce example is better.

**Comment by StrikerRUS** [comment]
ping @alishandefeng

**Comment by StrikerRUS** [comment]
Closed due to inactivity.
Feel free to reopen with new details.
