### ISSUE TITLE
lightgbm.cv weighted stratified sampling

### ISSUE THREAD

**Issue by nirupamkar** [Microsoft/LightGBM#1966]
Hi,
Wanted to know whether lgb.cv() does weighted stratified sampling when it's marked as True.
Could anyone confirm it?

**Comment by StrikerRUS** [comment]
Hi @nirupamkar !

LightGBM uses scikit-learn's stratified K-Folds:
https://github.com/Microsoft/LightGBM/blob/b37065dbd5510079aac341a34895f4854c782fcb/python-package/lightgbm/engine.py#L291-L295

https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.StratifiedKFold.html#sklearn.model_selection.StratifiedKFold

**Comment by nirupamkar** [comment]
Thanks for the response. But could you tell me whether this particular solution is doing weighted stratified sampling or equal weight stratified sampling?

**Comment by StrikerRUS** [comment]
Please clarify what do you mean by "weighted". Stratification makes folds with the same proportion of target classes in them.

**Comment by Laurae2** [comment]
@StrikerRUS Instead of duplicating rows, @nirupamkar would like to assign weights to each sample. This changes how stratification is supposed to work (instead of each observation = weight of 1, it would be an arbitrary weight).

**Comment by nirupamkar** [comment]
@Laurae2 you are correct. I have grouped data and if stratification is being done by assuming equal weights, all folds might not have same target rate

**Comment by StrikerRUS** [comment]
@nirupamkar sample weights are implemented in sklearn interface:
https://github.com/Microsoft/LightGBM/blob/b37065dbd5510079aac341a34895f4854c782fcb/python-package/lightgbm/sklearn.py#L343-L344
Also, it's possible to assign weights to whole classes instead of doing this for each sample via `class_weight`:
https://github.com/Microsoft/LightGBM/blob/b37065dbd5510079aac341a34895f4854c782fcb/python-package/lightgbm/sklearn.py#L169-L177

**Comment by nirupamkar** [comment]
@StrikerRUS thanks for the reply.
1.Yes I can see sample weight is there in lightgbm fit. I am aware of this. But if the stratification is not done as per the weight it could change the effective target rate of the data
2.It's not I am trying to change the weight of positive manually. Data can be  a groupby data and the weight is nothing but the number of replications.
Consider this example

feature1 | target | weight/replication | target_rate
-- | -- | -- | --
a | 0 | 10 | 0.66
a | 1 | 20 | 0.6
b | 0 | 3 | 0.25
b | 1 | 1 | 0.25
c | 0 | 25 | 0.14
c | 1 | 4 | 0.14

If we try to do stratified sampling with 3 folds, it might give me sample with feature1=a,feature1=b,feature1=c in different folds as it's seeing the target rate to be 50%(considering weight=1 for each row). However effectively we will have a huge difference in target rate in 3 folds.

**Comment by nirupamkar** [comment]
@StrikerRUS  any help regarding this? and could you please reopen the issue as it was closed before discussing in details

**Comment by StrikerRUS** [comment]
@nirupamkar 

> Wanted to know whether lgb.cv() does weighted stratified sampling when it's marked as True.

No, stratification in LightGBM is not "weighted".
As I already said earlier, you can see the code of how stratified folds are cooked in scikit-learn repo.
https://github.com/scikit-learn/scikit-learn/blob/7389dbac82d362f296dc2746f10e43ffa1615660/sklearn/model_selection/_split.py#L628

`X` isn't taken into account at all when stratification is performed. Only `y` matters.
