### ISSUE TITLE
Dataset not setting sparse threshold when created from bin file

### ISSUE THREAD

**Issue by adibsurani** [Microsoft/LightGBM#1981]
## Environment info

Operating System: Windows 10

C++/Python/R version: Visual C++ 2017 / Python 3

LightGBM version or commit hash: v2.2.2

## Description of problem

Suppose you have an existing (already binned) dataset on disk. You have some new data which you want to bin (using the first dataset as reference), and then also save to disk. This process is non-deterministic, and this saved file can have various filesizes when you try it multiple times.

## Steps to reproduce (pseudocode-ish)

```
dataset1 = DatasetCreateFromMat(somedata);
dataset1.DatasetSaveBinary("dataset1.bin");
dataset2 = DatasetCreateFromFile("dataset1.bin");
dataset3 = DatasetCreateFromMat(somedata, reference=dataset2);
dataset3.DatasetSaveBinary("dataset3.bin")
```

Result: dataset3.bin is non-deterministic, and can have different filesizes depending on when you run it.

## Underlying issue

The underlying issue seems to be that `dataset2.sparse_threshold_` is uninitialised, so takes "random values". This then causes `dataset3` to "randomly" decide to use dense or sparse bins when binning the data.

**Comment by guolinke** [comment]
Thanks very much! It indeed is a bug.
