### ISSUE TITLE
Python scikit-learn API difference: .feature_importance_ vs. .feature_importances_

### ISSUE THREAD

**Issue by ClimbsRocks** [Microsoft/LightGBM#199]
This is a minor annoyance: 

scikit-learn has an "s" at the end of `.feature_importances_`, while lgbm does not: `.feature_importance_`. It's easily worked around, but thought I'd mention it here. Happy to submit a PR for this if you guys are ok with the change!

**Comment by guolinke** [comment]
@wxchan

**Comment by wxchan** [comment]
I see, you can create a pr to change it, don't forget to change the docs.
