### ISSUE TITLE
Where can I find sample applicationss using C# ?

### ISSUE THREAD

**Issue by sdg002** [Microsoft/LightGBM#1999]
Hi All,
I have been looking at https://lightgbm.readthedocs.io/en/latest/  but I cant find anything that points me to sample code using C#.

I can see that there is a nuget package available. This is good news.
https://www.nuget.org/packages/LightGBM/

However, I have nothing that helps me to get started. The MSDN page is very scanty.
https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.lightgbm.lightgbm?view=ml-dotnet

Any suggestions?

thanks,
Sau

**Comment by StrikerRUS** [comment]
Hi @sdg002 !

For C# code please see this project: https://github.com/dotnet/machinelearning. It uses the NuGet package you've mentioned.

LightGBM itself doesn't provide any C# API, so you'll not find any C# code here.

**Comment by sdg002** [comment]
Thank you. Very good efforts by MS. But, I would look forward to integrating all of ML documentation under a single umbrella. Right now I am seeing 3 different locations
1)microsoft.docs
2)Github
3)lightgbm.readthedocs.io

Once upon a time there used to be MSDN.
