### ISSUE TITLE
lambdarank prediction error

### ISSUE THREAD

**Issue by fengqifang** [Microsoft/LightGBM#2]
Running the lambdarank example, training finished.

When run "LightGBM config=predict.conf

gives error

"[LightGBM Error] input format error, should be LibSVM"

**Comment by guolinke** [comment]
Thanks. I cannot debug it for my laptop is broken now. 
Can you help to test that other examples work or not?
Thanks

**Comment by chivee** [comment]
@fengqifang , thanks for your feedback.

the test data indeed has label which cannot be ignore by the IO reader.

you can add `data_has_label = true' in your predict.conf.

**Comment by guolinke** [comment]
@chivee I think it will be better if we can set data_has_label according to the input model and data file. I will add this soon.

**Comment by chivee** [comment]
@guolinke, sure, adding an try logic for parser will fix this problem

**Comment by guolinke** [comment]
fixed, the parameters "data_has_label" is not need any more.
