### ISSUE TITLE
what format shoud be when data has missing value?

### ISSUE THREAD

**Issue by fengqifang** [Microsoft/LightGBM#20]
Tried to repeat the example using my own data. 

There are missing values in the data, with default value 'NA', the LightGBM gave error message.

( No luck after replaces as 'nan')

"[LightGBM] finished load parameters
[LightGBM Error] meet error while parsing string to float, expect a nan here"

**Comment by guolinke** [comment]
I just have an new commit. you can use NA(na) and NaN(nan) now.

**Comment by guolinke** [comment]
If you still meet errors, please feel free to reopen this issue.
