### ISSUE TITLE
Sparrow 

### ISSUE THREAD

**Issue by MotoRZR** [microsoft/LightGBM#2001]
There was an interesting arxiv paper introducing sparrow which is another iteration of gradient boosted decision trees

https://arxiv.org/pdf/1901.09047.pdf

The premise is that this iteration can handle massive datasets using sampling and other techniques while using a small memory footprint.  Food for thought as to whether the suggestions could be implemented in LightGBM.

**Comment by GUEEN** [comment]
I would like to take this task. Does anyone mind? Seems to be relevant to my interests

**Comment by MotoRZR** [comment]
Hoping your offer of help gets sanctioned.  This change is a potential gamechanger

**Comment by StrikerRUS** [comment]
Hi @GUEEN !
How is your process going?

**Comment by GUEEN** [comment]
Working on it. I tried to run the original rust code, but couldn't because of some error.
Now I am building a separate C++ sparrow library following the paper directly (please see my repository). After that, I'd like to integrate it into Lightgbm. Still a couple of weeks away, sorry.

**Comment by MotoRZR** [comment]
Hi Gueen any further progress?

**Comment by StrikerRUS** [comment]
@MotoRZR Why did you close the issue?

**Comment by MotoRZR** [comment]
Sorry didn’t realise I did.  Must have been a fat finger on my part.  Will reopen

**Comment by GUEEN** [comment]
Hello. Sorry, I have been busy on some other projects lately. I have written a standalone C++ sparrow library that seems to work, but still requires some polishing and bugfixes. Planning to return soon.

**Comment by StrikerRUS** [comment]
@GUEEN Good news, keep doing! We'll be happy to merge this into LightGBM eventually.

**Comment by StrikerRUS** [comment]
Closed in favor of being in #2302. We decided to keep all feature requests in one place.

Welcome to contribute this feature! Please re-open this issue (or post a comment if you are not a topic starter) if you are actively working on implementing this feature.

**Comment by StrikerRUS** [comment]
@MotoRZR 
> For everyone's information, the sparrow algorithm has been implemented in CatBoost
  https://github.com/microsoft/LightGBM/issues/2302#issuecomment-543641394

Can you please provide some references/details?

@GUEEN How is your progress going?

**Comment by GUEEN** [comment]
Sorry, I've been busy with other commitments recently. Still planning to return sometime
