### ISSUE TITLE
implement datatable ingest directly into lightgbm

### ISSUE THREAD

**Issue by pseudotensor** [microsoft/LightGBM#2003]
https://github.com/dmlc/xgboost/blob/master/python-package/xgboost/core.py#L277-L322
￼￼￼￼￼
9:26 PM
https://github.com/dmlc/xgboost/blob/master/python-package/xgboost/core.py#L490-L515
9:27 PM
https://github.com/dmlc/xgboost/blob/master/tests/python/test_dt.py
9:28 PM
https://github.com/dmlc/xgboost/blob/master/include/xgboost/c_api.h#L231-L246
9:29 PM
https://github.com/dmlc/xgboost/blob/master/src/c_api/c_api.cc#L627-L693
9:30 PM
https://github.com/dmlc/xgboost/blob/master/tests/cpp/c_api/test_c_api.cc#L6-L31

**Comment by StrikerRUS** [comment]
Closed in favor of being in #2302. We decided to keep all feature requests in one place.

Welcome to contribute this feature! Please re-open this issue (or post a comment if you are not a topic starter) if you are actively working on implementing this feature.
