### ISSUE TITLE
Some LightGBM predictions are not coming in quantile regression range

### ISSUE THREAD

**Issue by pratyush19** [Microsoft/LightGBM#2004]
## Environment info

Operating System: Ubuntu 16.04.3 LTS

CPU/GPU model: Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz

C++/Python/R version: Python

LightGBM version or commit hash: 2.2.3

## Issue

Some predictions of LightGBM regression are not coming in the quantile regression range. In the below code, `y_pred` outputs are not in between `y_lower` and `y_upper` after taking prediction interval (PI) range 98%.
Also, shouldn't the mean of `y_lower` and `y_upper`  always be same irrespective of the PI range? I'm getting different mean value of `y_lower` and `y_upper` for different PI.

```python
clfl = lgb.LGBMRegressor(objective = 'quantile', alpha = 0.01, metric = 'l2')
clf = lgb.LGBMRegressor(objective = 'regression', metric = 'l2')
clfh = lgb.LGBMRegressor(objective = 'quantile', alpha = 0.99, metric = 'l2')

xx = [...]

y_pred = clf.predict(xx)
y_lower = clfl.predict(xx)
y_upper = clfh.predict(xx)
```

**Comment by guolinke** [comment]
@pratyush19 the quantile regression cannot ensure 100% predictions are in the ranges.
The goal of quantile is too reduce the quantile loss.
