### ISSUE TITLE
LightGBM exception on GPUs for wide training matrices

### ISSUE THREAD

**Issue by ironv** [microsoft/LightGBM#2007]
I am running a docker container with the following details:

    OS:     Ubuntu 16.04.5 LTS
    GPU:    Tesla V100-SXM2
    CUDA:   10.0.130
    PYTHON: 3.5.2
    LGBM:   2.2.4

When using a GPU for training (device=GPU), LGBM throws an exception when the number of features in the training matrix is greater than 5800.  My training matrix has the following dimensions `466,770 x 9,183`.  When the training matrix is restricted to 5800 features, it works fine but then the number of features is 5900 or more.

```
param_final = dict(max_bin=63, num_leaves=255, num_iterations=500, learning_rate=.1, 
             tree_learner='serial', min_data_in_leaf=100, num_threads=16, device='gpu')
model_gbm = lgb.cv(param_final, train_lgb, nfold=4, verbose_eval=False)
```

```
LightGBMError                             Traceback (most recent call last)
<timed exec> in <module>

/usr/local/lib/python3.5/dist-packages/lightgbm/engine.py in cv(params, train_set, num_boost_round, folds, nfold, stratified, shuffle, metrics, fobj, feval, init_model, feature_name, categorical_feature, early_stopping_rounds, fpreproc, verbose_eval, show_stdv, seed, callbacks)
    456     cvfolds = _make_n_folds(train_set, folds=folds, nfold=nfold,
    457                             params=params, seed=seed, fpreproc=fpreproc,
--> 458                             stratified=stratified, shuffle=shuffle)
    459 
    460     # setup callbacks

/usr/local/lib/python3.5/dist-packages/lightgbm/engine.py in _make_n_folds(full_data, folds, nfold, params, seed, fpreproc, stratified, shuffle)
    315         else:
    316             tparam = params
--> 317         cvbooster = Booster(tparam, train_set)
    318         cvbooster.add_valid(valid_set, 'valid')
    319         ret.append(cvbooster)

/usr/local/lib/python3.5/dist-packages/lightgbm/basic.py in __init__(self, params, train_set, model_file, silent)
   1552                 train_set.construct().handle,
   1553                 c_str(params_str),
-> 1554                 ctypes.byref(self.handle)))
   1555             # save reference to data
   1556             self.train_set = train_set

/usr/local/lib/python3.5/dist-packages/lightgbm/basic.py in _safe_call(ret)
     44     """
     45     if ret != 0:
---> 46         raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))
     47 
     48 

LightGBMError: bin size 272 cannot run on GPU
```

**Comment by huanzhang12** [comment]
Do you have any categorical features? or all features are continuous values?

**Comment by ironv** [comment]
No categorical features.  Only continuous values.

**Comment by huanzhang12** [comment]
If you only have continuous values, then max_bin should strictly limit the number of bins to less 63. It is part of the data preprocessing process.
@guolinke Do you have any idea why the number of bins can exceed max_bin with continuous features?

**Comment by julioasotodv** [comment]
@ironv can you try using another subset of 5800 features, just in case a specific column is causing the error? With this I mean: if you are using the [:5800] first features, try to do for instance [5800:]

**Comment by StrikerRUS** [comment]
ping @ironv and @guolinke

**Comment by guolinke** [comment]
@huanzhang12 
I think the root cause the feature bundling in LightGBM, which will merge multiple sparse features into one dense feature. Therefore, it could execeed the max_bin after feature bundling.
you can disable this by `enable_bundle=false`.

**Comment by StrikerRUS** [comment]
@ironv Did `enable_bundle=false` helped you?

**Comment by StrikerRUS** [comment]
Feel free to reopen, if proposed solution didn't help.
