### ISSUE TITLE
slow down while running concurrent fit procedures

### ISSUE THREAD

**Issue by jonrosenskispark** [Microsoft/LightGBM#2011]
## Environment info

Operating System: ubuntu 16.04

CPU/GPU model: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz

C++/Python/R version: Python version 3.6.3

LightGBM version or commit hash: 2.2.2

The issue summary: There is a significant slowdown when running multiple processes in parallel which are running the train/fit procedure while categorical columns are specified.

## Steps to reproduce

1. write two python scripts which call the fit method with the `categorical_feature` set equal to a list of indices which correspond to columns of type `np.int32`. (note that they do not access the same file for reading/accessing training data) (python code below)
```python
    import argparse
    import codecs
    import json
    import glob
    import pandas as pd
    import os
    import pprint
    import sys
    import uuid
    import zipfile
    from multiprocessing import Pool
    from sklearn.externals import joblib
    import tempfile
    import numpy as np
    if sys.version_info[0] == 2:
        from io import BytesIO as StringIO
    else:
        from io import StringIO

    def main():
        parser = argparse.ArgumentParser(description='Train a scikit-learn model on training data.')
        parser.add_argument('-i', '--input', required=True, help='Path to input file in TSV format')
        parser.add_argument('-p', '--model_params', default="{}", required=True,
                            help='Model params in JSON format, e.g., {"penalty":"l1","C":1.0}')
        parser.add_argument('--delimiter', default='\t', help='The delimiter in the input file')
        args = parser.parse_args()
    
        print('input is', args.input)
        try:
            model_params = json.loads(args.model_params)
        except:
            model_params = {}
    
        df = pd.read_csv(args.input, sep=args.delimiter, skiprows=[1])
        col_names = df.columns
        # extract label column
        y = df.ix[:, -2]
        sample_weight = df.ix[:, -1].values.astype(float)
        x = df.ix[:, :-2]
    
        from lightgbm import LGBMRegressor
        from sklearn.model_selection import train_test_split
        model = LGBMRegressor(num_leaves=32, seed=0, n_estimators=500)
    
        early_stopping_rounds = model_params.pop('early_stopping_rounds', 40)
        test_size = model_params.pop('test_size', 0.1)
        eligible_params = {}
        for param in set(model_params) & set(model.get_params()):
            eligible_params[param] = model_params[param]
        model.set_params(**eligible_params)
        x.columns = [str(i) for i in range(x.shape[1])]
    
        x_train, x_validation, y_train, y_validation = train_test_split(
            x, y, test_size=test_size, random_state=0)
        del x, y
        eval_set = [(x_train, y_train), (x_validation, y_validation)]
        model = model.fit(x_train, y_train, eval_set=eval_set, early_stopping_rounds=early_stopping_rounds, verbose=True)
    if __name__ == '__main__':
        main()
```
[input_file_655bd236-7adb-4e57-9912-6944ee9febde.tsv.gz](https://github.com/Microsoft/LightGBM/files/2865233/input_file_655bd236-7adb-4e57-9912-6944ee9febde.tsv.gz)
[input_file_c85ac2a5-d6f2-41fc-b180-67ba5b7fad5a.tsv.gz](https://github.com/Microsoft/LightGBM/files/2865236/input_file_c85ac2a5-d6f2-41fc-b180-67ba5b7fad5a.tsv.gz)

2. execute the two scripts in parallel (using a shell script or some other method)

3. compare the time it takes to finish running each script in series and note a significant slowdown (note that output models are equivalent when running in series vs in parallel)

**Comment by guolinke** [comment]
How many unique categories in your data?

**Comment by jonrosenskispark** [comment]
in the case i studied (i noticed it happening in other cases) there were 4 categorical columns. The cardinality of each one was ~ 500, 450, 20, 10.

**Comment by StrikerRUS** [comment]
ping @guolinke

**Comment by guolinke** [comment]
I guess the reason is the cache miss/bandwidth.
When using categorical features, the size of the histogram is much larger, and results in the much worse cache-miss problem. And it will be much worse when there are multiply processes.
