### ISSUE TITLE
get_split_value_histogram XGBoost equivalent in LightGBM

### ISSUE THREAD

**Issue by dsl10brc** [Microsoft/LightGBM#2013]
I want histogram/values of all the splits happening in a particular feature. Just like get_split_value_histogram in XGBoost. Is there any way to get it currently? 

I am aware of plot_tree and create_tree_digraph methods. But those are for visualizations

**Comment by guolinke** [comment]
I think this could be achieved by tree models.
You can use dump_model: https://lightgbm.readthedocs.io/en/latest/Python-API.html#lightgbm.Booster.dump_model, to get the model content. And then get your statistics from the model.
@StrikerRUS do you think this function is needed? maybe we can implement one in python-package.

**Comment by StrikerRUS** [comment]
@guolinke I haven't here about such function. It seems to be a useful feature, I'll take a look.
