### ISSUE TITLE
Encountered a problem, I tried to get rid of the age 0 data, but the model is wrong when the typerror is reported, I suspect it is caused by the removal of a category of data, but why is this? It should not know in advance that my data has Which categories are right?

### ISSUE THREAD

**Issue by zhouwuji** [Microsoft/LightGBM#2017]
## Environment info

Operating System: win10

CPU/GPU model: CPU

C++/Python/R version: Python3.7

LightGBM version or commit hash: 2.2.1

## Error message

F:\ProgramData\Anaconda3\python.exe F:/pycharmProject/DataFountain_ChinaMobile_Newland/code/describe.py
Pre-processing.....................
Feature Engineering.....................
F:/pycharmProject/DataFountain_ChinaMobile_Newland/code/describe.py:47: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  train_data['top_up_amount'] != 0] = 1
Training.....................
F:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:652: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=5.
  % (min_groups, self.n_splits)), Warning)
fold:  0  training
F:\ProgramData\Anaconda3\lib\site-packages\pandas\core\series.py:942: FutureWarning: 
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike
  return self.loc[key]
F:\ProgramData\Anaconda3\lib\site-packages\lightgbm\engine.py:118: UserWarning: Found `early_stopping_rounds` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
Training until validation scores don't improve for 50 rounds.
Traceback (most recent call last):
  File "F:/pycharmProject/DataFountain_ChinaMobile_Newland/code/describe.py", line 139, in <module>
    bst.fit(X_train, label_train, eval_set=[(X_validate, label_validate)], eval_metric='mae',verbose=-1)
  File "F:\ProgramData\Anaconda3\lib\site-packages\lightgbm\sklearn.py", line 642, in fit
    callbacks=callbacks)
  File "F:\ProgramData\Anaconda3\lib\site-packages\lightgbm\sklearn.py", line 502, in fit
    callbacks=callbacks)
  File "F:\ProgramData\Anaconda3\lib\site-packages\lightgbm\engine.py", line 228, in train
    evaluation_result_list=evaluation_result_list))
  File "F:\ProgramData\Anaconda3\lib\site-packages\lightgbm\callback.py", line 214, in callback
    best_iter[i] + 1, '\t'.join([_format_eval_result(x) for x in best_score_list[i]])))
TypeError: 'NoneType' object is not iterable
## Reproducible examples
train_data = train_data[train_data.age!=0] #(50000,30)-->(49710,30) If I comment this line,model could work
X_train = train_data.iloc[:,:30].values
y_train = train_data.iloc[:,-1].values
bst.fit(X_train, label_train, eval_set=[(X_validate, label_validate)], eval_metric='mae',verbose=-1)

## Steps to reproduce

1.
2.
3.

**Comment by guolinke** [comment]
I think this problem is fixed in this commit: https://github.com/Microsoft/LightGBM/commit/5530f2862e2a549f4ace93024a9f4898270bee72

please try the latest master branch.
