### ISSUE TITLE
Python scikit-learn GridSearchCV bagging_freq bug

### ISSUE THREAD

**Issue by ClimbsRocks** [Microsoft/LightGBM#202]
Running GridSearchCV to test out a few theories, and ran into this bug:

LightGBMError(b'Parameter bagging_freq should be of type int, got [0.7]',)

Obviously for the sklearn interface, this is called subsample_freq at the user level, but gets translated to bagging_freq internally. 

The rest of the parameters appear to be fine, it's just this one that's thrown an error so far. 

For what it's worth, I did see this error message where 0.7 was swapped out for at least one other value I passed into the GSCV params. 

This causes that particular fit to fail: 
/Users/preston/anaconda3/lib/python3.5/site-packages/sklearn/model_selection/_validation.py:252: FitFailedWarning: Classifier fit failed. The score on this train-test partition for these parameters will be set to -1000000000.000000. Details:
LightGBMError(b'Parameter bagging_freq should be of type int, got [0.7]',)

**Comment by guolinke** [comment]
@ClimbsRocks 
subsample_freq is the frequency of re-subsample. e.g if you set it to 1, it will re-sample in every iteration.

**Comment by ClimbsRocks** [comment]
@guolinke : yeah, i think this error is just a data type error. 

It's getting a list `[0.7]` instead of a float `0.7`. I removed this from my grid search and the rest of it worked fine. i wouldn't expect this to be a super important param to tune given the other options available, but thought i'd mention it since it threw an error.

**Comment by wxchan** [comment]
@ClimbsRocks subsample_freq/bagging_freq should be int, not float, it represents after [how many] iterations do one re-subsample. The parameter you want is `subsample`.

**Comment by wxchan** [comment]
@guolinke perhaps you should remove `[]` in this error message, it may be misleading.

**Comment by ClimbsRocks** [comment]
ah, got it. that makes much more sense. Thanks for the explanation!
