### ISSUE TITLE
Data source for the Expo benchmark experiment as shown in the docs

### ISSUE THREAD

**Issue by julioasotodv** [Microsoft/LightGBM#2028]
Perhaps this is a dumb question, but I am trying LightGBM in different datasets and devices: cpu, gpu and flags (experimental), and I see that tests have been done with the Expo dataset (as stated in https://lightgbm.readthedocs.io/en/latest/Experiments.html), which redirects to the link with the dataset.

However, the dataset does not seem to have the number of features that appears in the table (700), but rather 119.

I'm not sure who conducted the benchmark as shown in the Experiments table, but it would be very useful for me if anyone can point me to the link of the dataset with the 700 features and 11M rows.

Thank you!

**Comment by guolinke** [comment]
@julioasotodv 700 is the dimension after one-hot encoding for categorical features. 
refer to this script: https://github.com/guolinke/boosting_tree_benchmarks/blob/master/data/dataexpo.txt
