### ISSUE TITLE
Get individual tree depths

### ISSUE THREAD

**Issue by abhishek-ghose** [Microsoft/LightGBM#2034]
Hi,

I am using the Python version of LightGBM (not the sklearn API though). After I have run the `train()` function with `boosting_type='gbdt'`, is there anyway to get the  depths of individual trees? I have the prescribed `max_depth`s; I am interested in the actual depths.

I see that this information is printed out per iteration:
`[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 8`

But I am unable to locate this information in the object `train()` returns (checked it in debug mode). Is this information stored only in the C backend? Any means to access it from Python?

Thanks!

**Comment by guolinke** [comment]
set `verbose=2`

**Comment by abhishek-ghose** [comment]
Hi, what attribute of the Python model should I use to access the tree depths? To be clear, I already see it printed; I want to access the depths of each of the trees in the gbm model within my Python code.

**Comment by guolinke** [comment]
@abhishek-ghose 
sorry, the depth is not stored in the model content. 
I think the simplest solution for your question is, redirecting the log into a file, and get the depths from that.

**Comment by abhishek-ghose** [comment]
Got it, thanks!
