### ISSUE TITLE
Does the sample order in queries influence Lambdarank training?

### ISSUE THREAD

**Issue by simon19891101** [Microsoft/LightGBM#2036]
Hi there, I'm wondering if the order of samples in each query would have any impact on Lambdarank training? 

From my experiment, ordering samples in different ways surprisingly led to different training progress. 

In my case, the j-th sample in the i-th query, (x_ij, y_ij), carries the following info:
x_ij: search term, url, ..., etc
y_ij: score (binary, 0 or 1) 

Each query q_i is composed of two samples with different y:
q_1: (x_11, y_11)
q_1: (x_12, y_12)
q_2: (x_21, y_21)
q_2: (x_22, y_22)
...
So the corresponding group is set to [2,2,2,2....]

I found that pre-ordering the samples in each query resulted in the best training:
q_1: (x_11, 1)
q_1: (x_12, 0)
q_2: (x_21, 1)
q_2: (x_22, 0)
...
[1]	valid_0's ndcg@1: 0.684	valid_0's ndcg@2: 0.883374
[2]	valid_0's ndcg@1: 0.69	valid_0's ndcg@2: 0.885588
[3]	valid_0's ndcg@1: 0.7	valid_0's ndcg@2: 0.889279

Breaking the order would slow down the training:
q_1: (x_12, 0)
q_1: (x_11, 1)
q_2: (x_21, 1)
q_2: (x_22, 0)
...
[1]	valid_0's ndcg@1: 0.618	valid_0's ndcg@2: 0.859015
[2]	valid_0's ndcg@1: 0.642	valid_0's ndcg@2: 0.867873
[3]	valid_0's ndcg@1: 0.656	valid_0's ndcg@2: 0.87304

or
q_1: (x_12, 0)
q_1: (x_11, 1)
q_2: (x_22, 0)
q_2: (x_21, 1)
...
[1]	valid_0's ndcg@1: 0.546	valid_0's ndcg@2: 0.832442
[2]	valid_0's ndcg@1: 0.594	valid_0's ndcg@2: 0.850157
[3]	valid_0's ndcg@1: 0.614	valid_0's ndcg@2: 0.857539

According to the source code, the above behaviour doesn't seem to make sense as the samples in query are supposed to be sorted during training so the original order shouldn't impact (if Im not wrong).

Is this behaviour expected? Much appreciated for any comments. Cheers!

**Comment by guolinke** [comment]
@simon19891101 
could you provide a reproduce example, with randomly generated data ?

**Comment by simon19891101** [comment]
Thanks for the fast response. Sure, unfortunately the original data is not feasible due to business confidentiality but I will try to synthesize/find some other data that could trigger the same behavior. Cheers.

**Comment by simon19891101** [comment]
Sorry for the late response. Unfortunately I failed to find a dataset that demonstrates the same behaviour however I found that it was actually caused by the queries that have identical predicted scores for all samples. In this case the final score is decided by the specific way that python sorts equal numbers.
