### ISSUE TITLE
Saving weight values of a node

### ISSUE THREAD

**Issue by nirupamkar** [microsoft/LightGBM#2037]
Hi, right now for lightgbm trees following information is stored
1.Node index
2.Leaf count
3.Splitting variable
4.Threshold
5.Internal value
6.Leaf value
Is it possible to store the sum of weights too? It would be a great help in debugging or understanding the prediction.

**Comment by guolinke** [comment]
@nirupamkar did you mean the sample weigths? or the hessian weights (second-order gradients).

**Comment by nirupamkar** [comment]
@guolinke if possible both. As let's say for shap value calculation, we want to calculate the value of a node when the splitting feature is assumed to be missing. It will not be exactly equal to the weighted average of left and right nodes with weight being leaf count.
