### ISSUE TITLE
Build issue with GPU on Ubuntu 16.04

### ISSUE THREAD

**Issue by cheungwoonming** [Microsoft/LightGBM#2038]
Linking CXX shared library ../lib_lightgbm.so
[100%] Linking CXX executable ../lightgbm
CMakeFiles/lightgbm.dir/src/treelearner/data_parallel_tree_learner.cpp.o：在函数‘boost::system::error_category::std_category::equivalent(std::error_code const&, int) const’中：
data_parallel_tree_learner.cpp:(.text._ZNK5boost6system14error_category12std_category10equivalentERKSt10error_codei[_ZNK5boost6system14error_category12std_category10equivalentERKSt10error_codei]+0x44)：对‘boost::system::detail::generic_category_ncx()’未定义的引用
data_parallel_tree_learner.cpp:(.text._ZNK5boost6system14error_category12std_category10equivalentERKSt10error_codei[_ZNK5boost6system14error_category12std_category10equivalentERKSt10error_codei]+0xd1)：对‘boost::system::detail::generic_category_ncx()’未定义的引用
data_parallel_tree_learner.cpp:(.text._ZNK5boost6system14error_category12std_category10equivalentERKSt10error_codei[_ZNK5boost6system14error_category12std_category10equivalentERKSt10error_codei]+0x121)：对‘boost::system::detail::generic_category_ncx()’未定义的引用
CMakeFiles/lightgbm.dir/src/treelearner/data_parallel_tree_learner.cpp.o：在函数‘boost::system::error_category::std_category::equivalent(int, std::error_condition const&) const’中：
data_parallel_tree_learner.cpp:(.text._ZNK5boost6system14error_category12std_category10equivalentEiRKSt15error_condition[_ZNK5boost6system14error_category12std_category10equivalentEiRKSt15error_condition]+0x3f)：对‘boost::system::detail::generic_category_ncx()’未定义的引用
data_parallel_tree_learner.cpp:(.text._ZNK5boost6system14error_category12std_category10equivalentEiRKSt15error_condition[_ZNK5boost6system14error_category12std_category10equivalentEiRKSt15error_condition]+0xe1)：对‘boost::system::detail::generic_category_ncx()’未定义的引用
collect2: error: ld returned 1 exit status
CMakeFiles/lightgbm.dir/build.make:521: recipe for target '../lightgbm' failed
make[2]: *** [../lightgbm] Error 1
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/lightgbm.dir/all' failed
make[1]: *** [CMakeFiles/lightgbm.dir/all] Error 2
make[1]: *** 正在等待未完成的任务....
[100%] Built target _lightgbm
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

I have tried a couple of recommended fixes for similar errors, but have been unable to resolve this yet.
The most similar problem is  https://github.com/Microsoft/LightGBM/issues/458, but it can not resolve my problem.

**Comment by guolinke** [comment]
ping @huanzhang12

**Comment by StrikerRUS** [comment]
@cheungwoonming Can you please share the **full** error log? And try to reinstall the Boost library.
