### ISSUE TITLE
order of columns and rows

### ISSUE THREAD

**Issue by gcelano** [Microsoft/LightGBM#2042]
I use LightGBM via the scikit-learn API. Does the order of columns and/or rows in a DataFrame - _ceteris paribus_ - influence the results?

**Comment by guolinke** [comment]
@gcelano yes, it will have slight differences with different row/col orders.

**Comment by macyli01** [comment]
@guolinke  I've got a similar questions in relation to this issue. If I reorder the row in a dataFrame - ceteris paribus, would it produce different split points or the number of bins for a numerical features?

**Comment by guolinke** [comment]
@macyli01 
yeah, it will be slightly different, as the bin bucketed uses a sample set of data. And different row order will produce a different sample result.
