### ISSUE TITLE
BuildIssure “g++: error trying to exec 'jc1': execvp: No such file or directory”

### ISSUE THREAD

**Issue by andrewliuxxx** [Microsoft/LightGBM#2046]
## Environment info

Operating System:Centos7.3

CPU model:

C++  version: 4.8.5
HDFS ：CDH-5.14.4

LightGBM version or commit hash: V2.2.3

## Error message

g++: error trying to exec 'jc1': execvp: No such file or directory

## Steps to reproduce

1.git clone --recursive https://github.com/Microsoft/LightGBM ; cd LightGBM
2.cmake -DUSE_HDFS=ON -DHDFS_INCLUDE_DIR=/opt/cloudera/parcels/CDH-5.14.4-1.cdh5.14.4.p0.3/include/ -DHDFS_LIB=/opt/cloudera/parcels/CDH-5.14.4-1.cdh5.14.4.p0.3/lib/hadoop/hadoop-common.jar ..

3.make -j4

**Comment by StrikerRUS** [comment]
@ebernhardson Can you please take a look?

**Comment by ebernhardson** [comment]
Could you grep through the cloudera distribution for `jc1` ? I've never seen this program, and it's not available on our CDH servers (running cdh 5.15.0)

**Comment by StrikerRUS** [comment]
@ebernhardson Thank you very much for the response!
Can please help me with #1890 (especially with https://github.com/Microsoft/LightGBM/pull/1890#discussion_r238286022) to eliminate compatibility issues similar to this one?

**Comment by andrewliuxxx** [comment]
@ebernhardson @StrikerRUS  Thank you very much for the response!The problem is resolved.  Modify HDFS_LIB as quotes "HDFS_LIB=/opt/cloudera/parcels/CDH-5.14.4-1.cdh5.14.4.p0.3/lib64/libhdfs.so"

**Comment by StrikerRUS** [comment]
@andrewliuxxx Glad that you've solved this issue!

May I ask you paste the working commands (and description of other manipulations you did to compile and use LightGBM HDFS-version, if any), please? It'll allow complete #1890 and help other users with installation of HDFS-version.

**Comment by StrikerRUS** [comment]
gentle ping @andrewliuxxx
