### ISSUE TITLE
Muticlass  and grid search [python]

### ISSUE THREAD

**Issue by watermelonboss** [Microsoft/LightGBM#205]
When  the  LightGBM is used to muticlass ,"objective" is set to 'muticlass' .But objective and metrics don't match.So I set "eval_metric" is "multi_error" when fit , it success. 
Now , I need to grid search but I find "eval_metric"  can be set "multi_error".

How can I use grid search when muticlass  ?

**Comment by guolinke** [comment]
@wxchan  any idea about this?

**Comment by wxchan** [comment]
I did not understand the question.

@watermelonboss Do you want to set eval_metric = multi_error in GridSearchCV?

I think it's duplicate with #146

**Comment by watermelonboss** [comment]
@wxchan yes

**Comment by wxchan** [comment]
it's duplicate with #146 

use fit_params, please check original sklearn GridSearchCV api.

**Comment by watermelonboss** [comment]
@wxchan Thanks!!!
