### ISSUE TITLE
centos7 lightgbm gpu run error,can anybody help!

### ISSUE THREAD

**Issue by mathlf2015** [Microsoft/LightGBM#2050]
## Environment info

Operating System:

CPU/GPU model:tesla m40

C++/Python/R version:python 36

LightGBM version or commit hash:2.2.4

## Error message

Try to set boost_from_average=false, if your old models produce bad results
[LightGBM] [Info] Number of positive: 5962691, number of negative: 9735181
[LightGBM] [Info] This is the GPU trainer!!
[LightGBM] [Info] Total Bins 33610
[LightGBM] [Info] Number of data: 15697872, number of used features: 150
[LightGBM] [Info] Using GPU Device: Tesla M40 24GB, Vendor: NVIDIA Corporation
[LightGBM] [Info] Compiling OpenCL Kernel with 256 bins...
[LightGBM] [Warning] boost::filesystem::create_directories: Invalid argument
[LightGBM] [Warning] boost::filesystem::create_directories: Invalid argument
[LightGBM] [Warning] boost::filesystem::create_directories: Invalid argument
[LightGBM] [Warning] boost::filesystem::create_directories: Invalid argument
[LightGBM] [Warning] boost::filesystem::create_directories: Invalid argument
[LightGBM] [Warning] boost::filesystem::create_directories: Invalid argument
[LightGBM] [Warning] boost::filesystem::create_directories: Invalid argument
[LightGBM] [Warning] boost::filesystem::create_directories: Invalid argument
[LightGBM] [Warning] boost::filesystem::create_directories: Invalid argument
[LightGBM] [Warning] boost::filesystem::create_directories: Invalid argument
[LightGBM] [Warning] boost::filesystem::create_directories: Invalid argument
terminate called without an active exception
Aborted

when i run  make -j$(nproc)
follows the log 
/root/anaconda3/lib/libboost_filesystem.so: undefined reference to `__cxa_throw_bad_array_new_length@CXXABI_1.3.8'
/root/anaconda3/lib/libboost_filesystem.so: undefined reference to `std::_V2::error_category::~error_category()@GLIBCXX_3.4.21'
/root/anaconda3/lib/libboost_filesystem.so: undefined reference to `std::_V2::error_category::_M_message[abi:cxx11](int) const@GLIBCXX_3.4.21'
/root/anaconda3/lib/libboost_filesystem.so: undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)@GLIBCXX_3.4.20'
/root/anaconda3/lib/libboost_filesystem.so: undefined reference to `std::runtime_error::runtime_error(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)@GLIBCXX_3.4.21'
/root/anaconda3/lib/libboost_filesystem.so: undefined reference to `std::runtime_error::runtime_error(char const*)@GLIBCXX_3.4.21'
/root/anaconda3/lib/libboost_filesystem.so: undefined reference to `std::_V2::generic_category()@GLIBCXX_3.4.21'
/root/anaconda3/lib/libboost_filesystem.so: undefined reference to `typeinfo for std::_V2::error_category@GLIBCXX_3.4.21'
/root/anaconda3/lib/libboost_filesystem.so: undefined reference to `operator delete(void*, unsigned long)@CXXABI_1.3.9'

collect2: error: ld returned 1 exit status
make[2]: *** [../lightgbm] Error 1
make[1]: *** [CMakeFiles/lightgbm.dir/all] Error 2
make: *** [all] Error 2
## Steps to reproduce

1.sudo pip3 install lightgbm --install-option=--gpu --install-option="--opencl-include-dir=/usr/local/cuda/include/" --install-option="--opencl-library=/usr/local/cuda/lib64/libOpenCL.so"
2.
3.

**Comment by StrikerRUS** [comment]
Hi @mathlf2015 !

Your Boost library is broken: incompatible versions of Boost and GLIBCXX in conda environment. Please reinstall it. And it's better if you can get it **NOT** from conda.

**Comment by mathlf2015** [comment]
> Hi @mathlf2015 !
> 
> Your Boost library is broken: incompatible versions of Boost and GLIBCXX in conda environment. Please reinstall it. And it's better if you can get it **NOT** from conda.

thank you for your reply!
