### ISSUE TITLE
Problem about tuning hyper-parametres

### ISSUE THREAD

**Issue by LaymounaLhoulwa** [Microsoft/LightGBM#2058]
I have tried GridSearchCV and BayesSearchCV for tuning my lightGBM algorithm (for binary classification). 

I have used 10 iterations. And I have indicated scoring ="**roc_auc**"

In the **first** iteration, I have got:
 
```
best score : 0.71...
and best param : max-depth: 10 , learning-rate: 0.17..., num-leave:175, n-estimators: 176, ....

```

In the **10th** iteration, I have got :

```
best score : 0.72...
and best param : max-depth: 9 , learning-rate: 0.19..., num-leave:168, n-estimators: 172, ....

```
Then I tried to train my LightGBM classifier with the **10th** param (which supposed that it get the best score!!). I have got :

```
AUC : (0.7541...    , 0.6467...)
Accuracy: 0.7338..
RMSE: 0.5216..
```

Then because I had some curiosity I have tried to train my classifier with (best param) of the **First** iteration (which is considered as worst score)!. I had surprised by the result that I have got:

```
AUC : (0.7545...   , 0.6592...)
Accuracy: 0.7332..
RMSE: 0.5152..
```

Because I have fixed previously **scoring** by **roc-auc**, Generally, I should get AUC in the **10th** iteration better than the **first** iteration but I have got the contrary.

I have supposed that it is considered AUC train of **10th** iteration **0.7541** as better than **0.7545** of the **1st** iteration because of the overfitting but when I tried to check the **3rd** and the **5th** iteration I get on the **3rd : 0.7532**   and in the **5th : 0.7548**.

So I don't know what the best score in this algorithm means. And what is its role exactly if it gets values as the described situation. I had tried then many times with other tuning parameters but I have got the same case. I don't know where is the problem exactly.

**Comment by LaymounaLhoulwa** [comment]
My Source Code:

```
# X and y data are splited to 10 fold Cross- validation


import lightgbm as lgb
from skopt import BayesSearchCV
from sklearn.model_selection import StratifiedKFold

ITERATIONS =10
lghtboost = lgb.LGBMClassifier(silent=False, n_jobs=7, verbose=0,  metric=['roc_auc'])

param_grid ={'max_depth': [6, 15], 'learning_rate': [0.1,0.2], 'num_leaves': [150, 210], 
                       'n_estimators': [100,180], 'min_child_samples': [5], 'colsample_bytree': [1] }

bayes_cv_tuner_lgh = BayesSearchCV(
        lghtboost,
        param_grid,
        n_iter=ITERATIONS,
        scoring = 'roc_auc',
        cv = StratifiedKFold(n_splits=3, shuffle=True, random_state=0),
        refit = True,
        random_state = 0,
        verbose=0,
        n_jobs=7 
        )

def status_print(optim_result):
     print('Best ROC-AUC: {}'.format(bayes_cv_tuner_lgh.best_score_))
     print('params = {}'.format(bayes_cv_tuner_lgh.best_params_))

result_Lightboost = bayes_cv_tuner_lgh.fit(X_train.values, y_train.values, callback=status_print)



d_train = lgb.Dataset(X_train, label=y_train)

## I press the last best parameter:
best param = {max-depth: 9 , learning-rate: 0.19..., num-leave:168, n-estimators: 172, ....}

model_lgh = lgb.train(params, d_train)
y_pred = model_lgh.predict(X_test)

def auc_LGBM(m, train, test): 
    return (metrics.roc_auc_score(y_train,m.predict(train)), metrics.roc_auc_score(y_test,m.predict(test)))

print('AUC : ', auc_LGBM(model_lgh, X_train, X_test))
print("Accuracy : ", metrics.accuracy_score(y_test, y_pred.round()))
print("RMSE : ", np.sqrt(metrics.mean_squared_error(y_test, y_pred.round())))
```

**Comment by StrikerRUS** [comment]
@LaymounaLhoulwa You are performing the parameters search on **train** data with cv and then you're testing your best parameters on **test** data after refitting on the whole train data. Of course, the best params for train data can be **not** the best for test data. Perhaps, your train and test data distributions are slight different. Try to find better train/test splitting.
