### ISSUE TITLE
when all features are categorical, how to setup configuration

### ISSUE THREAD

**Issue by moveforever** [Microsoft/LightGBM#206]
My data format is as followed:
```
0 0 2 3 1 31 312 0 51 2 10 2 340 514 0 2 132 4 2 203 1 49 29 46
0 0 2 3 1 31 312 0 51 2 10 2 505 1082 0 0 130 4 2 203 1 49 60 46
0 0 2 3 1 31 312 0 51 2 10 2 505 858 0 0 130 4 2 203 1 49 60 46
0 0 2 3 1 31 312 0 51 2 10 2 505 1028 0 0 132 4 2 203 1 49 60 46
0 0 2 3 0 122 362 6 51 2 10 2 505 138 0 0 427 4 2 27 1 49 29 2
0 0 2 3 1 401 88 14 51 2 10 2 505 858 0 0 45 4 2 324 1 58 4 9
0 0 2 3 1 110 212 14 51 2 10 2 505 824 0 0 819 4 2 154 1 42 29 2
0 0 2 3 0 431 180 14 51 2 10 2 505 747 0 0 669 4 2 125 2 42 29 23
1 0 2 3 1 31 312 0 51 2 10 2 505 585 0 2 133 4 2 203 1 49 29 46
0 0 2 5 1 221 267 11 51 2 10 1 505 205 1 0 607 4 2 280 2 38 131 23
```
The first column is label, and the remaining columns are categorical features. And I setup categorical_feature = 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23
When input of light_gbm data is these data, there appear error:
```
[LightGBM] [Fatel] Cannot recognising input data format, filename: data/train

```
what should data format be? Or maybe i setup configuration wrong.
Can u help me?

**Comment by guolinke** [comment]
The feature  index is start from 0 , not 1

**Comment by wxchan** [comment]
index starts from 0
categorical_feature = 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22

**Comment by moveforever** [comment]
you mean a categorical feature encoding, and i have done as that feature index is start from 0.

**Comment by wxchan** [comment]
he means `categorical_feature = 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22`

**Comment by moveforever** [comment]
i have tried  categorical_feature = 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22, and it failed.

**Comment by moveforever** [comment]
it still appear data format error

**Comment by wxchan** [comment]
oh, the delimiter in your file should be tab(tsv) or comma(csv), not space

**Comment by moveforever** [comment]
yeah, it's delimiter, now it's ok.
tks
