### ISSUE TITLE
what  histogram calculation algorithm does lightgbm use?

### ISSUE THREAD

**Issue by tbonewmy** [Microsoft/LightGBM#2063]
Hello everyone. Could you please tell me if light-gbm use the same quantile histogram summary as XGboost when it comes to calculated split factor such as information gain? I read the paper. It's excellent by the way. But it did not specified much on this part. I am hoping to get some answer here. Thank you.

## Environment info

Operating System:

CPU/GPU model:

C++/Python/R version:

LightGBM version or commit hash:

## Steps to reproduce

1.
2.
3.

**Comment by guolinke** [comment]
LightGBM uses the simplest greedy equally density binning algorithm. 
The code:
https://github.com/Microsoft/LightGBM/blob/7a89d0054bcf0db9f96af3c53a078b6aa3152efe/src/io/bin.cpp#L207-L401

**Comment by tbonewmy** [comment]
Thank you very much.



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
03/26/19,
3:08:37 PM
