### ISSUE TITLE
Different Results With x, 1/x ,and x/10

### ISSUE THREAD

**Issue by Qiuyan918** [Microsoft/LightGBM#2069]
Scenario A: Change x to 1/x. 
Scenario B: Change x to x/10.  

In the scenarios above, I had different results compared to training on my numeric feature x (I only use one feature in the model). 
Could you please clarify why would this happen? 
In my understanding, in tree models, only the order of values matters. 
The scenario A which reverses the order of values would not affect the split point of feature x. The scenario B does not change the order at all. 
Thanks for your time.  

I did not use any subsampling. 
My parameters: 
```
params = {
                'boosting_type': 'gbdt',
                'colsample_bytree': 1, 
                'learning_rate': 0.5, 
                'max_depth': 5,
                'min_child_samples': 100,
                'min_child_weight': 1,
                'min_split_gain': 0.0, 
                'num_leaves': 20, 
                'objective': 'binary',
                'random_state': 50,
                'subsample': 1.0, 
                'subsample_freq': 0, 
                'metric': 'cross_entropy',
                'num_threads': 8
            }
```

**Comment by guolinke** [comment]
refer to #2062
