### ISSUE TITLE
Error 'CMake option -DUSE_GPU=1' in Windows GPU version

### ISSUE THREAD

**Issue by max-jan** [Microsoft/LightGBM#2070]
## Environment info

Operating System:

CPU/GPU model:

C++/Python/R version:

Python 3.7

LightGBM version or commit hash:

## Error message

LightGBMError: b'GPU Tree Learner was not enabled in this build. Recompile with CMake option -DUSE_GPU=1'
-- wrong import

## Steps to reproduce

If an error such as --------------
LightGBMError: b'GPU Tree Learner was not enabled in this build. Recompile with CMake option -DUSE_GPU=1'
-----------------------------------
 occurs when using GPU...
solution:
Install and import cmake. like this---------------------
pip install cmake

**Comment by StrikerRUS** [comment]
@max-jan LightGBM GPU-version can be built only with the help of CMake: https://github.com/Microsoft/LightGBM/tree/master/python-package#build-gpu-version (and often require to pass some other options).
