### ISSUE TITLE
Python 3.7 and LightGBM gpu with boost 1.68 windows 10

### ISSUE THREAD

**Issue by dishkakrauch** [Microsoft/LightGBM#2073]
## Environment info

Operating System: Windows 10

CPU/GPU model: Intel Core i7-8700/NVIDIA GeForce GTX 1060 6GB

C++/Python/R version: 3.7.1

LightGBM version or commit hash: 2.2.1

## Error message

Error 2 while installing LightGBM gpu according to the tutorial.
[https://lightgbm.readthedocs.io/en/latest/GPU-Windows.html](url)

## Reproducible examples

I installed CUDA Toolkit 10.1 cause it's only way to install tensorflow 2 on gpu with python 3.7

## Steps to reproduce

1. Make everything same with the tutorial except CUDA Toolkit version (you need to install 10.1):
[https://lightgbm.readthedocs.io/en/latest/GPU-Windows.html](url)
2. Configure Lightgbm with CMake and you'll get message than it's compiled up to boost with version 1.68
3. Use GitBash to compile Lightgbm and you'll get Error 2 at 49% of installing.

So there is the question - will you change tutorial of LightGBM installation for Windows with Python 3.7 and CUDA Toolkit 10.1.
The point is - you can't use less version of CUDA if you want use GPU versions of LightGBM and tensorflow at the same time cuse second lib works only with CUDA Toolkit 10.1 unfortunatelly.

**Comment by StrikerRUS** [comment]
@dishkakrauch We have a test for GPU-version of LightGBM on CI: 
https://github.com/Microsoft/LightGBM/blob/691b842832f511a72b4aaab715b3cb6b00de8f90/.ci/test.sh#L95-L104
and it indicates that everything is OK with Boost 1.68.

Also, we have a case of successful compilation on Windows with Boost 1.69.0 and CUDA 10.0: https://github.com/Microsoft/LightGBM/issues/2081#issuecomment-480504939.
I think you should adjust Boost and CUDA paths. You can read about it here with latest corrections: #2082.

Unfortunately, we are not going to check compatibility of Tensorflow and LightGBM in terms of dependencies. We encourage users to use the latest versions, if nothing special is written.

In case you post your error log, we can dig deeper in the problem.
