### ISSUE TITLE
Scikit-Learn wrapper cannot fit multi-class tasks

### ISSUE THREAD

**Issue by vruusmann** [Microsoft/LightGBM#208]
## Environment info
Operating System: GNU/Linux (Fedora)
CPU: N/A
LightGBM: latest source checkout (commit 7dec4dec6ab45afa753cd9069f85dbbaaeefad43)
Python: 2.7 and 3.4
Scikit-Learn: 0.18.1

## Error Message:

The function `LGBMClassifier#fit(X, y)` contains logic which is supposed to detect and properly handle multi-class classification problems. However, something doesn't work quite as expected, because the function invocation fails with "Objective and metrics don't match":
```
Traceback (most recent call last):
  File "multiclass.py", line 11, in <module>
    iris_classifier.fit(iris_X, iris_y)
  File "/usr/lib/python3.4/site-packages/lightgbm-0.1-py3.4.egg/lightgbm/sklearn.py", line 581, in fit
    callbacks=callbacks)
  File "/usr/lib/python3.4/site-packages/lightgbm-0.1-py3.4.egg/lightgbm/sklearn.py", line 406, in fit
    callbacks=callbacks)
  File "/usr/lib/python3.4/site-packages/lightgbm-0.1-py3.4.egg/lightgbm/engine.py", line 163, in train
    booster = Booster(params=params, train_set=train_set)
  File "/usr/lib/python3.4/site-packages/lightgbm-0.1-py3.4.egg/lightgbm/basic.py", line 1167, in __init__
    ctypes.byref(self.handle)))
  File "/usr/lib/python3.4/site-packages/lightgbm-0.1-py3.4.egg/lightgbm/basic.py", line 45, in _safe_call
    raise LightGBMError(_LIB.LGBM_GetLastError())
lightgbm.basic.LightGBMError: b"Objective and metrics don't match"
```

## Reproducible examples

```Python
import pandas

iris_df = pandas.read_csv("Iris.csv")

iris_X = iris_df[["Sepal.Length", "Sepal.Width", "Petal.Length", "Petal.Width"]]
iris_y = iris_df["Species"]

from lightgbm import LGBMClassifier

iris_classifier = LGBMClassifier()
iris_classifier.fit(iris_X, iris_y)
```

## Steps to reproduce

1. Download the Iris-Species dataset file [Iris.csv](https://github.com/jpmml/jpmml-lightgbm/blob/master/src/test/resources/csv/Iris.csv).
2. Run the above Python script. The error persists even if the `objective = "multiclass"` argument is specified.

**Comment by wxchan** [comment]
the default eval_metric="binary_logloss", you can pass "multi_logloss" to it for now, I will fix it

but should it be checked if eval_set=None? @guolinke

**Comment by guolinke** [comment]
@wxchan I think it is not need to check metric when not passing validation data. 
You can alter this logic in ```config.cpp``` as well.

**Comment by vruusmann** [comment]
Thanks, the LGBMClassifier instance is new able to detect the "arity" (ie. binary vs. multiclass) of the classification problem.
