### ISSUE TITLE
min_gain_to_split

### ISSUE THREAD

**Issue by nirupamkar** [microsoft/LightGBM#2080]
I am using lightgbm 2.2.3. This is the issue that I have faced.
I am trying to use min_gain_to_split to regularize. However wen I print the individual tree 
lgb.create_tree_digraph(clf,tree_index=8000,show_info=["split_gain","leaf_count"])
it shows the split_gain to be less than what I have specified in parameters.
Am I missing something  ? I do not have any reproducible code right now.

**Comment by ekerazha** [comment]
If it's the "minimum gain" and it is higher, it's ok, isn't it?

**Comment by nirupamkar** [comment]
Well, that was a typo :) . I edited it. It was doing splits and the gain is less than what is specified.

**Comment by guolinke** [comment]
@nirupamkar could you provide a reproduce example? with randomly generated data.

**Comment by StrikerRUS** [comment]
ping @nirupamkar

**Comment by StrikerRUS** [comment]
Feel free to reopen with MCVE.
