### ISSUE TITLE
Load model from file and update model

### ISSUE THREAD

**Issue by wyfSunflower** [Microsoft/LightGBM#2092]
How to use lightgbm implement multi time train? 
For example,  I use lightgbm to train on some samples, and I save model into file.
Next time,  I  have some other sample data, I want to use these sample improve model parameter, 
is there a way to load model from file and continue to train model on new sample data?
Thanks!

**Comment by StrikerRUS** [comment]
Hi @wyfSunflower !
You can use [`input_model`](https://lightgbm.readthedocs.io/en/latest/Parameters.html#input_model) or [`refit`](https://lightgbm.readthedocs.io/en/latest/Parameters.html#task) parameter. For the difference between them and more details please see these issues: #1529, #1473, #2030.
