### ISSUE TITLE
num_threads not working in MPI version

### ISSUE THREAD

**Issue by yangtian62** [microsoft/LightGBM#2095]
```
# task type, support train and predict
task = train

# boosting type, support gbdt for now, alias: boosting, boost
boosting_type = gbdt

objective = multiclass

metric = multi_logloss

num_class = 3

# frequence for metric output
metric_freq = 1

# true if need output metric for training data, alias: tranining_metric, train_metric
is_training_metric = true

learning_rate = 0.05

# number of bins for feature bucket, 255 is a recommend setting, it can save memories, and also has good accuracy. 
max_bin = 255

# training data
# if exsting weight file, should name to "regression.train.weight"
data = /home/lightgbm_mpi/data/training_set/full_input.svm

# valid data
#valid_data = "0-3.npy"

# round for early stopping
early_stopping = 0

# number of trees(iterations), alias: num_tree, num_iteration, num_iterations, num_round, num_rounds
num_iterations = 5

# number of leaves for one tree, alias: num_leaf
num_leaves = 31

use_two_round_loading = false

# frequency of saving model file snapshot
snapshot_freq = 2

output_model = /home/lightgbm_mpi/models/LightGBM_mpi_model.txt

# number of threads for multi-threading. One thread will use one CPU,
# defalut is setted to #cpu.
num_threads = 4

tree_learner = data

num_machines = 2
```

I found that `num_threads` here is not working properly. I have a 4-core machine, no matter I set 2 or 6, it will always use all cores. And for hyper threading machines, it will always use half the number of threads. For cluster, it will use all cores of every machine. I can't control it.

Also, for `num_machines` here, it seems that once the `mlist.txt` fixed, it will work the same as long as I set  `num_machines > 1`, no matter what exact number it is.

**Comment by guolinke** [comment]
@yangtian62 it should have no difference when using mpi version, the number of threads is set before running lightgbm: https://github.com/Microsoft/LightGBM/blob/50ce01b55e6bbac1dd00e2f9b1b639dcc37f2660/src/application/application.cpp#L30

A possible reason: https://stackoverflow.com/questions/11095309/openmp-set-num-threads-is-not-working


For the quick fix, you can try:
```
mpirun OMP_NUM_THREADS=nthreads xxx
```

For the `num_machines` problem, I didn't get it. Could you explain it more clearly?

**Comment by StrikerRUS** [comment]
ping @yangtian62

**Comment by StrikerRUS** [comment]
Feel free to reopen with new details.
