### ISSUE TITLE
Why is _CVBooster object hidden class?

### ISSUE THREAD

**Issue by matsuken92** [microsoft/LightGBM#2105]
Some of Kaggler use out-of-fold prediction (oof) which is calculated with validation dataset for stacking, blending, evaluation etc. In order to  calculate oof with lgb.cv(), we need to return Boosters however it is not returned from the function. If I customize to return `_CVBooster` object, it can be calculated, but `_CVBooster` is hidden class, so I think it is not appropriate to return officially. 

Is it possible to remove prefix underscore from  `_CVBooster`? Then I can customize to return the object on lgb.cv().

I would appreciate it if you could advise to it.

### _CVBooster
https://github.com/Microsoft/LightGBM/blob/master/python-package/lightgbm/engine.py#L248-L267

### Example
https://www.kaggle.com/kenmatsu4/using-trained-booster-from-lightgbm-cv-w-callback

**Comment by guolinke** [comment]
ping @StrikerRUS

**Comment by matsuken92** [comment]
Thank you for your comment!  Minimum requirements are:
  * Returning list of `Boosters`
  * Returning `best_iteration` to identify which iteration is best for predict when using early stopping.

In addition to above, current `_CVBooster.__getattr__` function is useful for batch operation of boosters on each fold. The following link is the part of usage of the `_CVBooster.__getattr__` calculating prediction result for test data.

https://github.com/matsuken92/LightGBM_test/blob/master/src/cv_booster_test.py#L117

I will send my idea as PR, so I would appreciate it if you could review it then!

**Comment by StrikerRUS** [comment]
@matsuken92 I see! Thanks for the clarification!

Of course, I'll be happy to review it.

Can you please also think about backward compatibility in terms of `cv` function return type? Maybe a new key in results dict or something else, idk...

**Comment by StrikerRUS** [comment]
Closing in favor of being in #2302. We decided to keep all feature requests in one place.

Welcome to contribute this feature! Please re-open (or post a comment if you are not a topic starter) this issue if you are actively working on implementing this feature.

**Comment by StrikerRUS** [comment]
Closed via #3204.
