### ISSUE TITLE
Are SKLEARN API estimators can distinguish PANDAS nominal type feature and PANDAS ordinal type feature?

### ISSUE THREAD

**Issue by muketer** [Microsoft/LightGBM#2108]
Are SKLEARN API estimators can recognize difference between
'ordinal feature (applying pandas.api.types.CategoricalDtype(data, ordered=True))'
and
'nominal feature (applying pandas.api.types.CategoricalDtype(data, ordered=False))' ?

thank you for your help.

**Comment by guolinke** [comment]
Currently, it cannot. But I think it is a good feature for enhancement. 
@StrikerRUS can you help to this ?

**Comment by StrikerRUS** [comment]
@guolinke I'll take a look.

**Comment by StrikerRUS** [comment]
@guolinke What the difference should be  for LightGBM in handling these types?
Lists are used for pandas categorical columns, so order is supported by default.
https://github.com/Microsoft/LightGBM/blob/ca85b6795002cc0c74d8e97d19fee88ca6ecc98e/python-package/lightgbm/basic.py#L263

**Comment by guolinke** [comment]
@StrikerRUS, for ordinal (order=true), it is better to treat them as numerical features and nominal(order=false) as categorical features.

**Comment by StrikerRUS** [comment]
@guolinke Ah, got it! Thanks!
