### ISSUE TITLE
Histogram caching problem

### ISSUE THREAD

**Issue by songchuangyuan** [Microsoft/LightGBM#2114]
All histograms are cached in Histogram Pool and initialized in the DynamicChangeSize method, but why does the starting pointer of each feature's histogram shift backwards? As shown in the following figure, offset = 1。
![image](https://user-images.githubusercontent.com/46445562/56339342-6feecb80-61e0-11e9-87e2-497c7ecbd50a.png)
When constructing the histogram, the position is moved forward to the initial location of the histogram storage, but when zeroing out, only num_bin-1 histogram content of each feature is zeroed out.why？
![image](https://user-images.githubusercontent.com/46445562/56339489-13d87700-61e1-11e9-9668-09d6676e9679.png)
![image](https://user-images.githubusercontent.com/46445562/56339522-35d1f980-61e1-11e9-8c42-27266cbe4888.png)
But when the fix histogram is constructed, the original location of the histogram storage space is shifted back by 1. So if you go to the last position of the histogram, isn't it the wild space? Why? Is that unreasonable?
![image](https://user-images.githubusercontent.com/46445562/56339703-e50ed080-61e1-11e9-9965-875bbe5efd3d.png)

**Comment by guolinke** [comment]
The bin_0 is not needed to cache. LightGBM always use the sum_of_all_bins - sum_of_positive_bins to get the values in bin_0.
