### ISSUE TITLE
Difference in scores returned by cross_val_score when n_jobs is set and when not set?

### ISSUE THREAD

**Issue by NagabhushanS** [microsoft/LightGBM#2120]
I came across a weird issue while cross validating my lightgbm model using a sklearn's TimeSeriesSplit cv.
Following is the sample code:
```

model1 = LGBMClassifier(random_state=7)
scores1 = cross_val_score(model1, X, y, cv=TimeSeriesSplit(5), scoring='roc_auc')

model2 = LGBMClassifier(random_state=7)
scores2 = cross_val_score(model2, X, y, cv=TimeSeriesSplit(5), scoring='roc_auc', n_jobs=-1)
```
Here scores1.mean() is not equal to scores2.mean(). How is this possible? cross_val_score is giving different results only for LightGBM but not for other native sklearn models.

**Comment by NagabhushanS** [comment]
The issue is cross_val_score is returning incorrect cv score when n_jobs is set to -1. I have tried this on other sklearn classifiers. The issue seems to be related uniquely to LGBMClassifier. Any updates?

**Comment by guolinke** [comment]
it is very strange.
I check the source fo cross_val_score: https://github.com/scikit-learn/scikit-learn/blob/7b136e9/sklearn/model_selection/_validation.py#L276, and find the n_jobs are only used in "Parallel", not in LigihtGBM. So there is no reason to produce different results.

BTW, Did you try xgb?

**Comment by NagabhushanS** [comment]
Yes XGBoost also gave same results irrespective of n_jobs=-1.

**Comment by StrikerRUS** [comment]
I can't reproduce this either.
@NagabhushanS Can you please provide MCVE?

**Comment by StrikerRUS** [comment]
Feel free to reopen with the example.
