### ISSUE TITLE
Booster.dump_model() sporadically crashes if a model has a tree with num_leaves=1

### ISSUE THREAD

**Issue by ivankolesnikov** [Microsoft/LightGBM#2130]
If a model has a tree with num_leaves=1, `Booster.dump_model()` sporadically crashes because LGBM_BoosterDumpModel() can produce an invalid json with `"shrinkage": nan`

I think I found the reason:

In https://github.com/Microsoft/LightGBM/blob/v2.2.3/src/io/tree.cpp#L511 returns from the constructor early, `shrinkage_` remains uninitialized and in a very rare case its value is NaN. 

https://github.com/Microsoft/LightGBM/blob/v2.2.3/src/io/tree.cpp#L247 outputs it as is and produces invalid JSON.

## Environment info

Operating System: Linux, OSX

Python 3.6

LightGBM version or commit hash: 2.1.2, 2.2.3, master

## Error message

```
  Traceback (most recent call last):
  File "[removed]/test.py", line 4, in <module>
    gbm.dump_model()
  File "[removed]/lib/python3.6/site-packages/lightgbm/basic.py", line 2153, in dump_model
    ret = json.loads(string_buffer.value.decode())
  File "[removed]/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "[removed]/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File [removed]/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 117884 column 13 (char 2428486)
```

## Reproducible examples

It is really hard to catch the issue, but after I added `shrinkage_ = nan("")` here: https://github.com/Microsoft/LightGBM/blob/v2.2.3/src/io/tree.cpp#L511, it is reproducible by running:

```
import lightgbm as lgb

gbm = lgb.Booster(model_file="test-model.txt")
gbm.dump_model()
print("OK")
```
The code crashes instead of printing OK.

Note: [test-model.txt](https://github.com/Microsoft/LightGBM/files/3114677/test-model.txt) contains several trees with num_leaves=1, e.g.:
```
Tree=111
num_leaves=1
...
shrinkage=0
```

**Comment by imatiach-msft** [comment]
@ivankolesnikov I'm also seeing the JSONDecodeError sporadically in our builds with lightgbm 2.2.3 on linux (in our azureml-explain-model pypi package).  I was actually hoping to debug this myself and try to send a PR but haven't had a chance.  I'm not sure if my issue is caused by the same underlying bug as what you are experiencing though.
