### ISSUE TITLE
[Question] what's the behavior of the tweedie regression in lightgbm?

### ISSUE THREAD

**Issue by chjq201410695** [microsoft/LightGBM#2135]
tweedie distribution has a key parameter----p that point out relation between u and σ2. 

The question is how to determine the p in lightgbm? and if I can set the p as a superparameter?

##update
--------------------------------
there is a parameter "tweedie_variance_power" to set the p in tweedie regression

Question
----------------------------------
when I use the tweedie regression, if it will automaticly add a log-link for y?

**Comment by chjq201410695** [comment]
Sorry, I find the parameter called "tweedie_variance_power". 

the rest question is when I use the tweedie regression, if it will automaticly add a log-link for y?

**Comment by mayer79** [comment]
Yes, it will automatically use the log link.

**Comment by chjq201410695** [comment]
> Yes, it will automatically use the log link.

Thanks for your response.  I wonder the log-link is log(x) or log(x+1),  could you tell me that?

**Comment by chjq201410695** [comment]
if I don't want to use log link, where can I set it?
