### ISSUE TITLE
Are there any specific things worth a notice when I install CMake?

### ISSUE THREAD

**Issue by Alexi-Herc** [Microsoft/LightGBM#2146]
Today I was installing the lgb r version from git bash and I already get cmake rtools r and of course git installed properly(I guess..). But when I start installing some error message about CMake comes up and I don't know why. Somehow there is a * DONE (lightgbm) at the end of the message and I run the test code in R, seems everything is doing fine, no error popup and I just got a lot of [LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements. The thing is I really need to make sure the whole package can work properly and I don't know is that CMake error going to make the code goes wrong. Guys sorry to interrupt but I am new to lgb and I hope I can get some help, can you guys teach me how to install the thing correctly? Thank you so much!

## Environment info

Operating System: Win 10 pro 1809

CPU/GPU model: i7-4710HQ

C++/Python/R version: R version 3.6.0

LightGBM version or commit hash: I don't know but I think it s the latest because I just install it from Git Bash today.

## Error message

CMake Error at CMakeLists.txt:7 (PROJECT):
  Generator

    Visual Studio 16 2019

  could not find any instance of Visual Studio.

-- Configuring incomplete, errors occurred!
See also "C:/Users/Alexi/AppData/Local/Temp/RtmpQXAsQI/R.INSTALL11001aa658cc/lightgbm/src/build/CMakeFiles/CMakeOutput.log".
CMake Error at CMakeLists.txt:7 (PROJECT):
  Generator

    Visual Studio 15 2017

  could not find any instance of Visual Studio.

-- Configuring incomplete, errors occurred!
See also "C:/Users/Alexi/AppData/Local/Temp/RtmpQXAsQI/R.INSTALL11001aa658cc/lightgbm/src/build/CMakeFiles/CMakeOutput.log".
-- Selecting Windows SDK version  to target Windows 10.0.17763.
CMake Error at CMakeLists.txt:7 (PROJECT):
  Failed to run MSBuild command:

    MSBuild.exe

  to get the value of VCTargetsPath:

    The system cannot find the file specified.

-- Configuring incomplete, errors occurred!
See also "C:/Users/Alexi/AppData/Local/Temp/RtmpQXAsQI/R.INSTALL11001aa658cc/lightgbm/src/build/CMakeFiles/CMakeOutput.log".
CMake Error at D:/Program Files/CMake/share/cmake-3.14/Modules/CMakeMinGWFindMake.cmake:12 (message):
  sh.exe was found in your PATH, here:

  D:/Program Files/Git/usr/bin/sh.exe

  For MinGW make to work correctly sh.exe must NOT be in your path.

  Run cmake from a shell that does not have sh.exe in your PATH.

  If you want to use a UNIX shell, then use MSYS Makefiles.

Call Stack (most recent call first):
  CMakeLists.txt:7 (PROJECT)

CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!

## All message

$ Rscript build_r.R
  checking for file 'C:\Users\Alexi\LightGBM\lightgbm_r/DESCRIPTION'' ...
-  preparing 'lightgbm': (1.1s)
  checking DESCRIPTION meta-informationn ...
-  cleaning src
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories (1.4s)
-  looking to see if a 'data/datalist' file should be added
-  building 'lightgbm_2.2.4.tar.gz'

[1] "C:/Users/Alexi/LightGBM/lightgbm_2.2.4.tar.gz"
* installing to library 'D:/Program Files/R/R-3.6.0/library'
* installing *source* package 'lightgbm' ...
** using staged installation
** libs
c:/Rtools/mingw_64/bin/gcc  -I"D:/PROGRA~2/R/R-36~1.0/include" -DNDEBUG          -O2 -Wall  -std=gnu99 -mtune=generic -c R_init.c -o R_init.o
c:/Rtools/mingw_64/bin/gcc -shared -s -static-libgcc -o lightgbm.dll tmp.def R_init.o -LD:/PROGRA~2/R/R-36~1.0/bin/x64 -lR
installing via 'install.libs.R' to D:/Program Files/R/R-3.6.0/library/00LOCK-lightgbm/00new/lightgbm
CMake Error at CMakeLists.txt:7 (PROJECT):
  Generator

    Visual Studio 16 2019

  could not find any instance of Visual Studio.

-- Configuring incomplete, errors occurred!
See also "C:/Users/Alexi/AppData/Local/Temp/RtmpQXAsQI/R.INSTALL11001aa658cc/lightgbm/src/build/CMakeFiles/CMakeOutput.log".
CMake Error at CMakeLists.txt:7 (PROJECT):
  Generator

    Visual Studio 15 2017

  could not find any instance of Visual Studio.

-- Configuring incomplete, errors occurred!
See also "C:/Users/Alexi/AppData/Local/Temp/RtmpQXAsQI/R.INSTALL11001aa658cc/lightgbm/src/build/CMakeFiles/CMakeOutput.log".
-- Selecting Windows SDK version  to target Windows 10.0.17763.
CMake Error at CMakeLists.txt:7 (PROJECT):
  Failed to run MSBuild command:

    MSBuild.exe

  to get the value of VCTargetsPath:

    The system cannot find the file specified.

-- Configuring incomplete, errors occurred!
See also "C:/Users/Alexi/AppData/Local/Temp/RtmpQXAsQI/R.INSTALL11001aa658cc/lightgbm/src/build/CMakeFiles/CMakeOutput.log".
CMake Error at D:/Program Files/CMake/share/cmake-3.14/Modules/CMakeMinGWFindMake.cmake:12 (message):
  sh.exe was found in your PATH, here:

  D:/Program Files/Git/usr/bin/sh.exe

  For MinGW make to work correctly sh.exe must NOT be in your path.

  Run cmake from a shell that does not have sh.exe in your PATH.

  If you want to use a UNIX shell, then use MSYS Makefiles.

Call Stack (most recent call first):
  CMakeLists.txt:7 (PROJECT)

CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
-- The C compiler identification is GNU 4.9.3
-- The CXX compiler identification is GNU 4.9.3
-- Check for working C compiler: C:/Rtools/mingw_64/bin/gcc.exe
-- Check for working C compiler: C:/Rtools/mingw_64/bin/gcc.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Rtools/mingw_64/bin/g++.exe
-- Check for working CXX compiler: C:/Rtools/mingw_64/bin/g++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenMP_C: -fopenmp (found version "4.0")
-- Found OpenMP_CXX: -fopenmp (found version "4.0")
-- Found OpenMP: TRUE (found version "4.0")
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/Alexi/AppData/Local/Temp/RtmpQXAsQI/R.INSTALL11001aa658cc/lightgbm/src/build
Scanning dependencies of target _lightgbm
[  3%] Building CXX object CMakeFiles/_lightgbm.dir/src/c_api.cpp.obj
C:\Users\Alexi\AppData\Local\Temp\RtmpQXAsQI\R.INSTALL11001aa658cc\lightgbm\src\src\c_api.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
 /*!
 ^
cc1plus.exe: warning: unrecognized command line option "-Wno-ignored-attributes"
[  6%] Building CXX object CMakeFiles/_lightgbm.dir/src/lightgbm_R.cpp.obj
C:\Users\Alexi\AppData\Local\Temp\RtmpQXAsQI\R.INSTALL11001aa658cc\lightgbm\src\src\lightgbm_R.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
 /*!
 ^
cc1plus.exe: warning: unrecognized command line option "-Wno-ignored-attributes"
[  9%] Building CXX object CMakeFiles/_lightgbm.dir/src/application/application.cpp.obj
C:\Users\Alexi\AppData\Local\Temp\RtmpQXAsQI\R.INSTALL11001aa658cc\lightgbm\src\src\application\application.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
 /*!
 ^
cc1plus.exe: warning: unrecognized command line option "-Wno-ignored-attributes"
[ 12%] Building CXX object CMakeFiles/_lightgbm.dir/src/boosting/boosting.cpp.obj
C:\Users\Alexi\AppData\Local\Temp\RtmpQXAsQI\R.INSTALL11001aa658cc\lightgbm\src\src\boosting\boosting.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
 /*!
 ^
cc1plus.exe: warning: unrecognized command line option "-Wno-ignored-attributes"
[ 15%] Building CXX object CMakeFiles/_lightgbm.dir/src/boosting/gbdt.cpp.obj
C:\Users\Alexi\AppData\Local\Temp\RtmpQXAsQI\R.INSTALL11001aa658cc\lightgbm\src\src\boosting\gbdt.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
 /*!
 ^
cc1plus.exe: warning: unrecognized command line option "-Wno-ignored-attributes"
[ 18%] Building CXX object CMakeFiles/_lightgbm.dir/src/boosting/gbdt_model_text.cpp.obj
C:\Users\Alexi\AppData\Local\Temp\RtmpQXAsQI\R.INSTALL11001aa658cc\lightgbm\src\src\boosting\gbdt_model_text.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
 /*!
 ^
cc1plus.exe: warning: unrecognized command line option "-Wno-ignored-attributes"
[ 21%] Building CXX object CMakeFiles/_lightgbm.dir/src/boosting/gbdt_prediction.cpp.obj
C:\Users\Alexi\AppData\Local\Temp\RtmpQXAsQI\R.INSTALL11001aa658cc\lightgbm\src\src\boosting\gbdt_prediction.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
 /*!
 ^
cc1plus.exe: warning: unrecognized command line option "-Wno-ignored-attributes"
[ 25%] Building CXX object CMakeFiles/_lightgbm.dir/src/boosting/prediction_early_stop.cpp.obj
C:\Users\Alexi\AppData\Local\Temp\RtmpQXAsQI\R.INSTALL11001aa658cc\lightgbm\src\src\boosting\prediction_early_stop.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
 /*!
 ^
cc1plus.exe: warning: unrecognized command line option "-Wno-ignored-attributes"
[ 28%] Building CXX object CMakeFiles/_lightgbm.dir/src/io/bin.cpp.obj
C:\Users\Alexi\AppData\Local\Temp\RtmpQXAsQI\R.INSTALL11001aa658cc\lightgbm\src\src\io\bin.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
 /*!
 ^
cc1plus.exe: warning: unrecognized command line option "-Wno-ignored-attributes"
[ 31%] Building CXX object CMakeFiles/_lightgbm.dir/src/io/config.cpp.obj
C:\Users\Alexi\AppData\Local\Temp\RtmpQXAsQI\R.INSTALL11001aa658cc\lightgbm\src\src\io\config.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
 /*!
 ^
cc1plus.exe: warning: unrecognized command line option "-Wno-ignored-attributes"
[ 34%] Building CXX object CMakeFiles/_lightgbm.dir/src/io/config_auto.cpp.obj
C:\Users\Alexi\AppData\Local\Temp\RtmpQXAsQI\R.INSTALL11001aa658cc\lightgbm\src\src\io\config_auto.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
 /*!
 ^
cc1plus.exe: warning: unrecognized command line option "-Wno-ignored-attributes"
[ 37%] Building CXX object CMakeFiles/_lightgbm.dir/src/io/dataset.cpp.obj
C:\Users\Alexi\AppData\Local\Temp\RtmpQXAsQI\R.INSTALL11001aa658cc\lightgbm\src\src\io\dataset.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
 /*!
 ^
cc1plus.exe: warning: unrecognized command line option "-Wno-ignored-attributes"
[ 40%] Building CXX object CMakeFiles/_lightgbm.dir/src/io/dataset_loader.cpp.obj
C:\Users\Alexi\AppData\Local\Temp\RtmpQXAsQI\R.INSTALL11001aa658cc\lightgbm\src\src\io\dataset_loader.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
 /*!
 ^
cc1plus.exe: warning: unrecognized command line option "-Wno-ignored-attributes"
[ 43%] Building CXX object CMakeFiles/_lightgbm.dir/src/io/file_io.cpp.obj
C:\Users\Alexi\AppData\Local\Temp\RtmpQXAsQI\R.INSTALL11001aa658cc\lightgbm\src\src\io\file_io.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
 /*!
 ^
cc1plus.exe: warning: unrecognized command line option "-Wno-ignored-attributes"
[ 46%] Building CXX object CMakeFiles/_lightgbm.dir/src/io/json11.cpp.obj
C:\Users\Alexi\AppData\Local\Temp\RtmpQXAsQI\R.INSTALL11001aa658cc\lightgbm\src\src\io\json11.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
 /* Copyright (c) 2013 Dropbox, Inc.
 ^
cc1plus.exe: warning: unrecognized command line option "-Wno-ignored-attributes"
[ 50%] Building CXX object CMakeFiles/_lightgbm.dir/src/io/metadata.cpp.obj
C:\Users\Alexi\AppData\Local\Temp\RtmpQXAsQI\R.INSTALL11001aa658cc\lightgbm\src\src\io\metadata.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
 /*!
 ^
cc1plus.exe: warning: unrecognized command line option "-Wno-ignored-attributes"
[ 53%] Building CXX object CMakeFiles/_lightgbm.dir/src/io/parser.cpp.obj
C:\Users\Alexi\AppData\Local\Temp\RtmpQXAsQI\R.INSTALL11001aa658cc\lightgbm\src\src\io\parser.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
 /*!
 ^
cc1plus.exe: warning: unrecognized command line option "-Wno-ignored-attributes"
[ 56%] Building CXX object CMakeFiles/_lightgbm.dir/src/io/tree.cpp.obj
C:\Users\Alexi\AppData\Local\Temp\RtmpQXAsQI\R.INSTALL11001aa658cc\lightgbm\src\src\io\tree.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
 /*!
 ^
cc1plus.exe: warning: unrecognized command line option "-Wno-ignored-attributes"
[ 59%] Building CXX object CMakeFiles/_lightgbm.dir/src/metric/dcg_calculator.cpp.obj
C:\Users\Alexi\AppData\Local\Temp\RtmpQXAsQI\R.INSTALL11001aa658cc\lightgbm\src\src\metric\dcg_calculator.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
 /*!
 ^
cc1plus.exe: warning: unrecognized command line option "-Wno-ignored-attributes"
[ 62%] Building CXX object CMakeFiles/_lightgbm.dir/src/metric/metric.cpp.obj
C:\Users\Alexi\AppData\Local\Temp\RtmpQXAsQI\R.INSTALL11001aa658cc\lightgbm\src\src\metric\metric.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
 /*!
 ^
cc1plus.exe: warning: unrecognized command line option "-Wno-ignored-attributes"
[ 65%] Building CXX object CMakeFiles/_lightgbm.dir/src/network/linker_topo.cpp.obj
C:\Users\Alexi\AppData\Local\Temp\RtmpQXAsQI\R.INSTALL11001aa658cc\lightgbm\src\src\network\linker_topo.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
 /*!
 ^
cc1plus.exe: warning: unrecognized command line option "-Wno-ignored-attributes"
[ 68%] Building CXX object CMakeFiles/_lightgbm.dir/src/network/linkers_mpi.cpp.obj
C:\Users\Alexi\AppData\Local\Temp\RtmpQXAsQI\R.INSTALL11001aa658cc\lightgbm\src\src\network\linkers_mpi.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
 /*!
 ^
cc1plus.exe: warning: unrecognized command line option "-Wno-ignored-attributes"
[ 71%] Building CXX object CMakeFiles/_lightgbm.dir/src/network/linkers_socket.cpp.obj
C:\Users\Alexi\AppData\Local\Temp\RtmpQXAsQI\R.INSTALL11001aa658cc\lightgbm\src\src\network\linkers_socket.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
 /*!
 ^
cc1plus.exe: warning: unrecognized command line option "-Wno-ignored-attributes"
[ 75%] Building CXX object CMakeFiles/_lightgbm.dir/src/network/network.cpp.obj
C:\Users\Alexi\AppData\Local\Temp\RtmpQXAsQI\R.INSTALL11001aa658cc\lightgbm\src\src\network\network.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
 /*!
 ^
cc1plus.exe: warning: unrecognized command line option "-Wno-ignored-attributes"
[ 78%] Building CXX object CMakeFiles/_lightgbm.dir/src/objective/objective_function.cpp.obj
C:\Users\Alexi\AppData\Local\Temp\RtmpQXAsQI\R.INSTALL11001aa658cc\lightgbm\src\src\objective\objective_function.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
 /*!
 ^
cc1plus.exe: warning: unrecognized command line option "-Wno-ignored-attributes"
[ 81%] Building CXX object CMakeFiles/_lightgbm.dir/src/treelearner/data_parallel_tree_learner.cpp.obj
C:\Users\Alexi\AppData\Local\Temp\RtmpQXAsQI\R.INSTALL11001aa658cc\lightgbm\src\src\treelearner\data_parallel_tree_learner.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
 /*!
 ^
cc1plus.exe: warning: unrecognized command line option "-Wno-ignored-attributes"
[ 84%] Building CXX object CMakeFiles/_lightgbm.dir/src/treelearner/feature_parallel_tree_learner.cpp.obj
C:\Users\Alexi\AppData\Local\Temp\RtmpQXAsQI\R.INSTALL11001aa658cc\lightgbm\src\src\treelearner\feature_parallel_tree_learner.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
 /*!
 ^
cc1plus.exe: warning: unrecognized command line option "-Wno-ignored-attributes"
[ 87%] Building CXX object CMakeFiles/_lightgbm.dir/src/treelearner/gpu_tree_learner.cpp.obj
C:\Users\Alexi\AppData\Local\Temp\RtmpQXAsQI\R.INSTALL11001aa658cc\lightgbm\src\src\treelearner\gpu_tree_learner.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
 /*!
 ^
cc1plus.exe: warning: unrecognized command line option "-Wno-ignored-attributes"
[ 90%] Building CXX object CMakeFiles/_lightgbm.dir/src/treelearner/serial_tree_learner.cpp.obj
C:\Users\Alexi\AppData\Local\Temp\RtmpQXAsQI\R.INSTALL11001aa658cc\lightgbm\src\src\treelearner\serial_tree_learner.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
 /*!
 ^
cc1plus.exe: warning: unrecognized command line option "-Wno-ignored-attributes"
[ 93%] Building CXX object CMakeFiles/_lightgbm.dir/src/treelearner/tree_learner.cpp.obj
C:\Users\Alexi\AppData\Local\Temp\RtmpQXAsQI\R.INSTALL11001aa658cc\lightgbm\src\src\treelearner\tree_learner.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
 /*!
 ^
cc1plus.exe: warning: unrecognized command line option "-Wno-ignored-attributes"
[ 96%] Building CXX object CMakeFiles/_lightgbm.dir/src/treelearner/voting_parallel_tree_learner.cpp.obj
C:\Users\Alexi\AppData\Local\Temp\RtmpQXAsQI\R.INSTALL11001aa658cc\lightgbm\src\src\treelearner\voting_parallel_tree_learner.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
 /*!
 ^
cc1plus.exe: warning: unrecognized command line option "-Wno-ignored-attributes"
[100%] Linking CXX shared library ..\lib_lightgbm.dll
[100%] Built target _lightgbm
Found library file: C:\Users\Alexi\AppData\Local\Temp\RtmpQXAsQI\R.INSTALL11001aa658cc/lightgbm/src/lib_lightgbm.dll to move to D:/Program Files/R/R-3.6.0/library/00LOCK-lightgbm/00new/lightgbm/libs/x64** R
** data
** demo
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'lightgbm'
    finding HTML links ... done
    agaricus.test                           html
    agaricus.train                          html
    bank                                    html
    dim                                     html
    dimnames.lgb.Dataset                    html
    getinfo                                 html
    lgb.Dataset                             html
    lgb.Dataset.construct                   html
    lgb.Dataset.create.valid                html
    lgb.Dataset.save                        html
    lgb.Dataset.set.categorical             html
    lgb.Dataset.set.reference               html
    lgb.cv                                  html
    lgb.dump                                html
    lgb.get.eval.result                     html
    lgb.importance                          html
    lgb.interprete                          html
    lgb.load                                html
    lgb.model.dt.tree                       html
    lgb.plot.importance                     html
    lgb.plot.interpretation                 html
    lgb.prepare                             html
    lgb.prepare2                            html
    lgb.prepare_rules                       html
    lgb.prepare_rules2                      html
    lgb.save                                html
    lgb.train                               html
    lgb.unloader                            html
    lgb_shared_params                       html
    lightgbm                                html
    predict.lgb.Booster                     html
    readRDS.lgb.Booster                     html
    saveRDS.lgb.Booster                     html
    setinfo                                 html
    slice                                   html
** building package indices
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (lightgbm)
[1] 0

**Comment by StrikerRUS** [comment]
Hi @Alexi-Herc!

The fact that you can run LightGBM with test task successfully, i.e. without segfaults and other crashes, indicates that you had done everything correctly.

The only one thing you can do is to remove from your PATH directory with shell which comes with Git

```
D:/Program Files/Git/usr/bin
```

> CMake Error at D:/Program Files/CMake/share/cmake-3.14/Modules/CMakeMinGWFindMake.cmake:12 (message):
sh.exe was found in your PATH, here:
D:/Program Files/Git/usr/bin/sh.exe
For MinGW make to work correctly sh.exe must NOT be in your path.
Run cmake from a shell that does not have sh.exe in your PATH.
If you want to use a UNIX shell, then use MSYS Makefiles.

This error is avoided in our installation script by duplicated command execution, but removing that folder from your PATH may save your time in the future during using CMake with MinGW in other projects.
https://github.com/Microsoft/LightGBM/blob/804c5cdfa7c187f3197d4fa69452bf4ad48ca060/R-package/src/install.libs.R#L48-L52

Also, it will be great if you provide the content of your PATH variable.

Speaking about the warning you get during tests execution, it's OK. Warning about split requirements may come from parameters and data inconsistency, e.g. a model is too complicated for random generated data.

And ping @Laurae2 and @jameslamb for any other thoughts and further assistance.

**Comment by Alexi-Herc** [comment]
@StrikerRUS Thank you for the reply and I really appreciate that! 

I don't have that `D:/Program Files/Git/usr/bin ` in my path.
Here is my path variable.
`C:\Rtools\bin`
`C:\Rtools\mingw_64\bin`
`D:\Program Files\R\R-3.6.0\bin`
`D:\Program Files\CMake\bin`
`D:\Program Files\Git\cmd`
and these is where the softwere being installed.

Again, It's really good to know that the package is right!
Thank you again!

**Comment by StrikerRUS** [comment]
@Alexi-Herc 

> I don't have that `D:/Program Files/Git/usr/bin` in my path.

Ah, I overlooked this aspect:

> Today I was installing the lgb r version from git bash …

I think that Git Bash is the cause of that error with

> sh.exe was found in your PATH, here: …

You can check it by `echo %PATH%` in Git Bash.

**Comment by Alexi-Herc** [comment]
@StrikerRUS 

> You can check it by echo %PATH% in Git Bash.
Git Bash:
Alexi@Alexi MINGW64 ~
$ echo %Path%
%Path%

If I put this on cmd it will work.
Anyway, a big thanks to you for helping me figure these out!

**Comment by StrikerRUS** [comment]
@Alexi-Herc My bad! It should be in Unix style, of course:
```
echo $PATH
```
In addition, I think you may want to get familiar with Question 4 and 8 in FAQ: https://lightgbm.readthedocs.io/en/latest/FAQ.html#lightgbm.

**Comment by Alexi-Herc** [comment]
@StrikerRUS Thank you for your suggestion! I should just reinstall Git and change it to VS right?

**Comment by StrikerRUS** [comment]
@Alexi-Herc 
>  I should just reinstall Git and change it to VS right?

For the `sh.exe` error I think you can simply not use Git Bash 😃 . And for the second part, you may (it's optional, everything is quite good already) install VS to get the maximum performance as it's said in FAQ.

**Comment by Laurae2** [comment]
@Alexi-Herc You can ignore the first sh.exe error as it is a workaround for Windows users with Rtools / MinGW.

This is a (known) bug of Windows CMake.
