### ISSUE TITLE
Scikit-Learn wrapper fails if the `fit` method has `categorical_feature` argument

### ISSUE THREAD

**Issue by vruusmann** [Microsoft/LightGBM#215]
## Environment info
LightGBM: latest source checkout (commit e7431447e158b1b55f81d2fb7b16e4668c782fad)

## Error Message:

```
/usr/lib/python3.4/site-packages/lightgbm-0.1-py3.4.egg/lightgbm/basic.py:477: FutureWarning: using '+' to provide set union with Indexes is deprecated, use '|' or .union()
  categorical_feature += cat_cols
Traceback (most recent call last):
  File "auto.py", line 11, in <module>
    auto_lgbm.fit(auto_X, auto_y, categorical_feature = ["cylinders", "model_year", "origin"])
  File "/usr/lib/python3.4/site-packages/lightgbm-0.1-py3.4.egg/lightgbm/sklearn.py", line 521, in fit
    callbacks=callbacks)
  File "/usr/lib/python3.4/site-packages/lightgbm-0.1-py3.4.egg/lightgbm/sklearn.py", line 406, in fit
    callbacks=callbacks)
  File "/usr/lib/python3.4/site-packages/lightgbm-0.1-py3.4.egg/lightgbm/engine.py", line 163, in train
    booster = Booster(params=params, train_set=train_set)
  File "/usr/lib/python3.4/site-packages/lightgbm-0.1-py3.4.egg/lightgbm/basic.py", line 1165, in __init__
    train_set.construct().handle,
  File "/usr/lib/python3.4/site-packages/lightgbm-0.1-py3.4.egg/lightgbm/basic.py", line 763, in construct
    categorical_feature=self.categorical_feature, params=self.params)
  File "/usr/lib/python3.4/site-packages/lightgbm-0.1-py3.4.egg/lightgbm/basic.py", line 575, in _lazy_init
    data, feature_name, categorical_feature, self.pandas_categorical = _data_from_pandas(data, feature_name, categorical_feature, self.pandas_categorical)
  File "/usr/lib/python3.4/site-packages/lightgbm-0.1-py3.4.egg/lightgbm/basic.py", line 477, in _data_from_pandas
    categorical_feature += cat_cols
  File "/home/vfed/.local/lib/python3.4/site-packages/pandas/indexes/base.py", line 1657, in __radd__
    return Index(other + np.array(self))
ValueError: operands could not be broadcast together with shapes (3,) (0,) 
```

## Reproducible examples

```Python
import pandas

auto_df = pandas.read_csv("Auto.csv")

auto_X = auto_df[["cylinders", "displacement", "horsepower", "weight", "acceleration", "model_year", "origin"]]
auto_y = auto_df["mpg"]

from lightgbm import LGBMRegressor

auto_lgbm = LGBMRegressor(n_estimators = 11)
auto_lgbm.fit(auto_X, auto_y, categorical_feature = ["cylinders", "model_year", "origin"])
```

## Steps to reproduce

1. Download the Auto-MPG dataset file [Auto.csv](https://github.com/jpmml/jpmml-lightgbm/blob/master/src/test/resources/csv/Auto.csv).
2. Run the above Python script. The experiment succeeds if the `categorical_feature` argument is removed, but in that case LightGBM treats all features as continuous features (meaning that the automatic categorical feature detection logic also fails?).

**Comment by vruusmann** [comment]
This regression happened sometimes within the past 24 hours (ie. commits on Jan 13-14th?), because this Python script was working correctly yesterday.

**Comment by vruusmann** [comment]
I can temporarily work around this problem, if I convert Pandas' `DataFrame` to Numpy's `matrix`, and supply both `feature_name` and `categorical_feature` arguments:

```Python
auto_lgbm = LGBMRegressor(n_estimators = 11)
auto_lgbm.fit(auto_X.as_matrix(), auto_y, feature_name = ["cylinders", "displacement", "horsepower", "weight", "acceleration", "model_year", "origin"], categorical_feature = ["cylinders", "model_year", "origin"])
```

**Comment by wxchan** [comment]
It's some bug how we deal with pandas 'category' type. I will fix it later.

btw, do you know any good deterministic way to do 'ad hoc encoding', so we don't need to pass the categorical encoding of train dataset to eval and test dataset?

@guolinke now we only make train and test category encoding same, how about prediction? Then we need to pass self.pandas_categorical to InnerPredictor. What if user saves and loads model, where should we save self.pandas_categorical?

**Comment by wxchan** [comment]
@guolinke any ideas on this? How about we do some hash encoding for string categorical feature? (Or revert this feature for now).

**Comment by guolinke** [comment]
@wxchan 
I think we can expose two more api:
1. set_encoding, 
2. get_encoding,
both of them are interactive with Booster. And inner_predictor can use them to get encoding methods.

**Comment by wxchan** [comment]
Is that too complicated? Use pandas to transfer categorical features to numerical is pretty simple and flexible, if make it auto in lightgbm, it may not turn out to be what user wants, and user probably won't know that. (even I don't know whether one feature is treated as categorical feature some time)

**Comment by guolinke** [comment]
@wxchan 
Not change any logic in LightGBM.
encoding can be just an string, And LightGBM only write/read it with model file. 
Python can just parse this encoding string to get what it want.

**Comment by WittmannF** [comment]
Was this problem really solved? I am having the same problem when running on a Kaggle kernel. The version is `2.3.1`
