### ISSUE TITLE
Problem of the use of fobj

### ISSUE THREAD

**Issue by QAZASDEDC** [microsoft/LightGBM#2156]
The parameter fobj does not work on my code and there exists no zero in hessian. The preds always 0 yet.Have someone successfully used fobj？
```
def smape_obj(preds, dtrain):
    labels = dtrain.get_label()
    print(preds)
    diff = preds - labels
    epsilon = 0.0001
    pl_mn = np.where(diff >= 0, 1, -1)
    grad = np.divide(labels*2+epsilon,np.power(preds+labels+epsilon,2))
    hess = np.divide(-labels*4-epsilon*2,np.power(preds+labels+epsilon,3))
    grad = pl_mn*grad
    hess = pl_mn*hess
    print(hess)
    return grad, hess

clf = lgb.train(param, trn_data, num_round, valid_sets=[trn_data, val_data], verbose_eval=1, early_stopping_rounds=500, categorical_feature = cate,fobj = smape_obj, feval = smape_eval)
```

_Originally posted by @QAZASDEDC in https://github.com/microsoft/LightGBM/issues/2128#issuecomment-490408141_

**Comment by Hongyun1993** [comment]
the reason may be the elements of grad/hess are too huge.

**Comment by StrikerRUS** [comment]
> Have someone successfully used fobj？

`fobj` works correctly, which can be proven by tests and examples run on our CI service, e.g.:
https://github.com/microsoft/LightGBM/blob/74ce2cfe9418b0def315c5e17f6244eefac64a60/examples/python-guide/advanced_example.py#L156-L162

You should double check your `SMAPE` derivatives and data. #1645 and #1150 may help you in it.
