### ISSUE TITLE
Build from source with HDFS support error: reinterpret_cast from type ‘const void*’ to type ‘char*’ casts away qualifiers

### ISSUE THREAD

**Issue by Paperone80** [microsoft/LightGBM#2160]
## Environment info

Operating System: Ubuntu 16.04 LTS

CPU/GPU model: XEON 4110/RTX 2080 Ti

C++/Python/R version: 5.4.0 / 3.5 / -

LightGBM version or commit hash: v2.2.4

## Error message

> /opt/lightgbm/src/io/file_io.cpp: In instantiation of ‘size_t LightGBM::HDFSFile::FileOperation(BufferType, size_t, LightGBM::HDFSFile::fileOp<BufferType>) const [with BufferType = const void*; size_t = long unsigned int; LightGBM::HDFSFile::fileOp<BufferType> = int (*)(hdfs_internal*, hdfsFile_internal*, const void*, int); tSize = int; hdfsFS = hdfs_internal*; hdfsFile = hdfsFile_internal*]’:
> /opt/lightgbm/src/io/file_io.cpp:92:62:   required from here
> /opt/lightgbm/src/io/file_io.cpp:101:49: error: reinterpret_cast from type ‘const void*’ to type ‘char*’ casts away qualifiers
>      char* buffer = reinterpret_cast<char *>(data);
> 
> cc1plus: warning: unrecognized command line option ‘-Wno-ignored-attributes’
> CMakeFiles/_lightgbm.dir/build.make:398: recipe for target 'CMakeFiles/_lightgbm.dir/src/io/file_io.cpp.o' failed
> make[2]: *** [CMakeFiles/_lightgbm.dir/src/io/file_io.cpp.o] Error 1
> make[2]: *** Waiting for unfinished jobs....

## Reproducible examples
```
$ export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/
$ sudo -E cmake .. \
-DUSE_GPU=1 \
-DOpenCL_LIBRARY=/usr/local/cuda/lib64/libOpenCL.so \
-DOpenCL_INCLUDE_DIR=/usr/local/cuda/include \
-DUSE_MPI=ON \
-DUSE_SWIG=ON \
-DUSE_HDFS=ON \
-DHDFS_INCLUDE_DIR=/opt/hadoop/hadoop-2.9.2/include \
-DHDFS_LIB=/opt/hadoop/hadoop-2.9.2/lib/native/libhdfs.so
```

## Steps to reproduce
Downloaded also binary packages of HDFS for v2.5.0, v2.6.0, v3.1.2. Even build Apache Hadoop HDFS Project 2.9.2 from source. Always the same error. 

I did not use CDH 5.14.0 as in the documentation.

Thanks.

**Comment by Paperone80** [comment]
Hi @StrikerRUS, @ebernhardson, 

Based on here: [here](https://stackoverflow.com/questions/43298862/how-to-convert-const-void-to-unsigned-char)

I changed the following code in line 101 in /src/io/file_io.cpp:
`
char* buffer = reinterpret_cast<char *>(data);
`
to 
`
char* buffer = reinterpret_cast<char*>(const_cast<void*>(data));
`

The code is compiling but I am not a C/C++ programmer at all so no idea whether this is actually correct. I guess you know instantly and will have tests for that :D

**Comment by guolinke** [comment]
@StrikerRUS do we have the test for hdfs version build ?

**Comment by StrikerRUS** [comment]
@guolinke Nope

**Comment by guolinke** [comment]
refer to https://github.com/microsoft/LightGBM/commit/2027f6b485b1b707b774ca6cfbf6142aa71e8665#r33603258

**Comment by zhangyafeikimi** [comment]
same as #2185
