### ISSUE TITLE
Doc should mention that is_unbalance is relevant for multiclassova

### ISSUE THREAD

**Issue by rauhs** [microsoft/LightGBM#2163]
It seems that the parameter `is_unbalance` is also relevant for MultiClass OVA objective. Isn't that true? Should the doc also mention this?

**Comment by nwnlp** [comment]
@rauhs I think 'is_unbalance' is not necessary for OVA classifiers. for example, we have k classes , when using OVA, all classifiers may suffer from unbalanced problem. no class has  an advantage or disadvantage. so for the class which has few samples, it is relatively fair.

**Comment by guolinke** [comment]
yeah, is_unbalance will be used in the binary classifiers of `multiclassova`.

**Comment by guolinke** [comment]
closed via https://github.com/microsoft/LightGBM/commit/c17a5f5b8402908da1b1dfdc74a6e40530a6ffe0

**Comment by StrikerRUS** [comment]
@guolinke Doesn't `pos_bagging_fraction`, `neg_bagging_fraction` and `boost_from_average` affect MultiClassOVA training indirectly as well?

**Comment by guolinke** [comment]
@StrikerRUS yeah, you are right! would you help to refine them as well?
