### ISSUE TITLE
Why underscore is added for a feature name? 

### ISSUE THREAD

**Issue by TGalaxy** [microsoft/LightGBM#2165]
I use python version of lightgbm. Code below: 

`model = lgb.train(params, d_train, num_iteration, valid_sets=d_validation, early_stopping_rounds=50, verbose_eval=100)`
`model.save_model('lgbm.txt', num_iteration=model.best_iteration)`

I noticed that when a feature name is 'abc def chi', the output lgbm.txt will change the name to 'abc_def_chi'. 

Since the feature name is defined by some other parties, the inconsistency makes it really difficult to deploy the model. It is also difficult to identify which names are modified. 

Could we please keep the feature name as it is?

**Comment by guolinke** [comment]
we don't allow the feature name with spaces, as it is caused confusing in visualization and parsing for it looks like multiple features.
Therefore, we convert spaces as underscore.
