### ISSUE TITLE
[Question] Figure out which data has been used to train individual trees (Random Forest)

### ISSUE THREAD

**Issue by joelrich** [microsoft/LightGBM#2179]
I am trying to implement some experiments on top of LightGBM's random forest implementation. However, I am not sure if LightGBM exposes all the required information through its python API. I should be able to:

1) Figure out which rows have been used to train an individual tree
2) Perform predictions with separate trees

The idea is to calibrate every tree separately on out of sample data. I think I can achieve 2) by using pred_leaf together with get_leaf_output and only look at a single tree. However, I still need to figure out which data has been used to train the different trees.

Is there a solution for this? A hack is fine too. I would prefer though if I don't have to adjust the C code.

In case this isn't possible yet, could `booster.dump_model()` be extended to include this information or if it isn't preserved, passed to a callback during training? Or could it be possible to generate the same samples in python by knowing the seed?

**Comment by guolinke** [comment]
@joelrich 
Firstly, the used sample indices will be reset at each iteration, so it is not possible to get them all after training finish. But you can access them at each iteration. Saving these information is possible, but it will significantly increase the model size.
Secondly, python cannot access the sample indices now, it (bag_data_indices_) can only be accessed in cpp now:
https://github.com/microsoft/LightGBM/blob/c9d681ac0d8c7e242b2fff217db268c11c83c745/src/boosting/rf.hpp#L121-L122

For a quick hack, I suggest that write the indics into files at the end of each iteration:
https://github.com/microsoft/LightGBM/blob/master/src/boosting/rf.hpp#L165

And you will need to write some cpp code, and compile your own python library.

**Comment by joelrich** [comment]
Yes, saving them in the model file was not such a good idea. However, if there are other use cases for this, I think a callback would solve this elegantly. For now, this is all I need. Thank you.
