### ISSUE TITLE
linux gcc 4.8.5 failed to compile the latest code

### ISSUE THREAD

**Issue by zhangyafeikimi** [microsoft/LightGBM#2185]
gcc 4.8.5 doesn't have the option "-Wno-ignored-attributes".

And this reinterpret_cast is not good.

/home/kimmyzhang/LightGBM/src/io/file_io.cpp:101:49: 错误：从类型‘const void*’到类型‘char*’的 reinterpret_cast 丢失了限定符
     char* buffer = reinterpret_cast<char *>(data);

**Comment by zhangyafeikimi** [comment]
Change it to
char* buffer = reinterpret_cast<char*>(const_cast<char*)(data));
?

**Comment by guolinke** [comment]
refer to https://github.com/microsoft/LightGBM/commit/2027f6b485b1b707b774ca6cfbf6142aa71e8665#r33603258

**Comment by zhangyafeikimi** [comment]
It is a compilation ERROR, not warning.

**Comment by zhangyafeikimi** [comment]
fix it first, then talk abot style?
