### ISSUE TITLE
Extracting decision path

### ISSUE THREAD

**Issue by Sebber123** [microsoft/LightGBM#2187]
Hi all,

I was wondering if it is possible to extract the decision path for a specific sample.
If this is not possible. Does anyone know how I can extract the splits used for a specific sample? 

Thanks in advance!

**Comment by StrikerRUS** [comment]
Closed in favor of being in #2302. We decided to keep all feature requests in one place.

Welcome to contribute this feature! Please re-open this issue (or post a comment if you are not a topic starter) if you are actively working on implementing this feature.
