### ISSUE TITLE
Add CODEOWNERS

### ISSUE THREAD

**Issue by jameslamb** [microsoft/LightGBM#2194]
I learned from @Paxanator and @mjermann over on [fRanz](https://github.com/UptakeOpenSource/fRanz/issues/24) that GitHub supports a notion of "default reviewers" similar to [Bitbucket](https://confluence.atlassian.com/bitbucketserver/add-default-reviewers-to-pull-requests-834221295.html).

You just have to add a `.github/CODEOWNERS`, per [instructions here](https://help.github.com/en/articles/about-code-owners). You can even put owners on particular file extensions or sub-directories, which I think aligns well with [the way we've been handling it](https://github.com/microsoft/LightGBM/blob/76170788c4bd6239334408f88cf51183ec791fa2/docs/FAQ.rst#critical).

This might save us a few clicks and put into code what we've been managing by convention.

Thoughts?

**Comment by guolinke** [comment]
very cool! let us add it.
