### ISSUE TITLE
How to reset sample_weight using callbacks

### ISSUE THREAD

**Issue by xwang9401** [microsoft/LightGBM#2197]
## Environment info

Operating System: Win 10

CPU/GPU model: Intel Xeon

C++/Python/R version: Python 3.6

LightGBM version or commit hash: 2.2.3

## Error message

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

## Reproducible examples

import lightgbm as lgb

weightVec = np.random.rand(len(trainData))
cb = lgb.reset_parameter(sample_weight=lambda x: weightVec)
gbm = lgb.LGBMRegressor()
gbm.set_params(**params)
gbm.fit(trainData, trainLabel, callbacks=[cb])

## Steps to reproduce

I was trying to adjust the value of sample_weight for each cycle within the training process, by providing such a function to param callbacks. However, seems to me that after invoking the callback func, the model would compare the old param with the new one, using operator != (this is just my guess by reading the traceback). Since sample_weight is a vector with cannot be compared using !=, the model fails here.

I wonder if there's some workaround for my purpose, or make the comparison in the callback part to handle the case of sample_weight (or any other params which is not just a scalar)? Thanks a lot!

Traceback (most recent call last):

  File "<ipython-input-1735-8f3fae9a2b7a>", line 3, in <module>
    gbm.fit(transTrain, labelTrain, eval_metric=toyEval, eval_set=[(transTrain, labelTrain), (transTest, labelTest)], callbacks=[cb])

  File "D:\WinPython-64bit-3.6.6.2Qt5\python-3.6.6.amd64\lib\site-packages\lightgbm\sklearn.py", line 685, in fit
    callbacks=callbacks)

  File "D:\WinPython-64bit-3.6.6.2Qt5\python-3.6.6.amd64\lib\site-packages\lightgbm\sklearn.py", line 544, in fit
    callbacks=callbacks)

  File "D:\WinPython-64bit-3.6.6.2Qt5\python-3.6.6.amd64\lib\site-packages\lightgbm\engine.py", line 216, in train
    evaluation_result_list=None))

  File "D:\WinPython-64bit-3.6.6.2Qt5\python-3.6.6.amd64\lib\site-packages\lightgbm\callback.py", line 143, in _callback
    if new_param != env.params.get(key, None):

**Comment by guolinke** [comment]
you can call lgb.Dataset.set_weight(w) in the callback.

**Comment by xwang9401** [comment]
I see. Then I would have to use lgb.train API rather than the sklearn API, right?
Thanks!
