### ISSUE TITLE
String labels not functional with class_weight

### ISSUE THREAD

**Issue by striajan** [microsoft/LightGBM#2198]
String labels are accepted in `y` vector passed to `fit` function, but not in `class_weight`.

## Environment info

Operating System: MacOS 10.14.5
Python version: 3.7
LightGBM version or commit hash: 2.2.3

## Error message

ValueError: Class label positive not present.

## Reproducible examples

```
import random
import numpy as np
import lightgbm

n = 10
class_weight = {'positive': 1, 'negative': 2}

X = np.random.rand(n, 1)
y = random.choices(list(class_weight.keys()), k=n)

classifier = lightgbm.LGBMClassifier(class_weight=class_weight)
classifier.fit(X, y)
```

**Comment by StrikerRUS** [comment]
@striajan Thanks a lot for catching this bug! I'll really appreciate if you check the fix from #2199.
