### ISSUE TITLE
add_features_from not functional

### ISSUE THREAD

**Issue by Jingyu-Fan** [microsoft/LightGBM#2200]
Thank you for your time!

## Environment info

Operating System: linux

CPU/GPU model: CPU

C++/Python/R version:Python 

LightGBM version or commit hash:2.2.3

## Error message

AttributeError: 'Dataset' object has no attribute 'add_features_from'

## Reproducible examples

import numpy as np
import lightgbm as lgb

X1 = np.random.random((1000, 1))
X2 = np.random.random((1000, 1))

d1 = lgb.Dataset(X1).construct()
d2 = lgb.Dataset(X2).construct()
d1.add_features_from(d2)

**Comment by StrikerRUS** [comment]
Hi @Jingyu-Fan !
Unfortunately, `add_features_from` is presented only in `master` branch now. You can either build the package from sources or wait for #2138.

**Comment by Jingyu-Fan** [comment]
It seems that if lightgbm is installed through "pip install lightgbm", the problem would occur, while building from source would resolve the problem

**Comment by Jingyu-Fan** [comment]
> Hi @Jingyu-Fan !
> Unfortunately, `add_features_from` is presented only in `master` branch now. You can either build the package from sources or wait for #2138.

Thank you. Just found out the problem.
