### ISSUE TITLE
incorrect logged parameters in model file

### ISSUE THREAD

**Issue by guolinke** [microsoft/LightGBM#2208]
There is a config2string after training model:
https://github.com/microsoft/LightGBM/blob/b1e5a843ab57c64b01c8896ef3cda6fdf907d417/src/io/config_auto.cpp#L549-L654

However, as some parameters are not visible in cpp side when using python/R package, such as `num_iteration` in python package. Therefore, some logged parameters are not correct.

**Comment by guolinke** [comment]
to fix this, I think we should pass all parameters to cpp code, even though some of them are not used in cpp side.

**Comment by Xiad32** [comment]
So, what other configurations are needed here beside num_iteration? Would they differ based on the class where they are used; RF,GOSS or DART?

**Comment by guolinke** [comment]
@Xiad32 these configurations just log the error values in the model file, it doesn't affect the normal usage.

**Comment by StrikerRUS** [comment]
Python-package has been fixed in #2589.

ping @jameslamb and @Laurae2 for R-package.

**Comment by jameslamb** [comment]
@StrikerRUS hey thanks for the ping, this one was not on my radar. I'll pick it up

**Comment by StrikerRUS** [comment]
@jameslamb Great! Thank you.
