### ISSUE TITLE
Error when import python

### ISSUE THREAD

**Issue by Kyla0606** [Microsoft/LightGBM#221]
I followed the instruction in https://github.com/Microsoft/LightGBM/blob/master/docs/Python-intro.md, then I tried to import lightgbm in Python, and I got the followed error:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "lightgbm/__init__.py", line 13, in <module>
    from .sklearn import LGBMModel, LGBMRegressor, LGBMClassifier, LGBMRanker
  File "lightgbm/sklearn.py", line 123, in <module>
    class LGBMModel(LGBMModelBase):
  File "lightgbm/sklearn.py", line 471, in LGBMModel
    @LGBMDeprecated('Use attribute booster_ instead.')
TypeError: 'NoneType' object is not callable

**Comment by wxchan** [comment]
sorry, it's a bug

a quick solution: install scikit-learn with `pip install scikit-learn` and re-install lightgbm python-package

**Comment by Kyla0606** [comment]
It's solved. Thanks.
