### ISSUE TITLE
Booster can not load anymore from a string, documentation still says so

### ISSUE THREAD

**Issue by AdrienHEH** [microsoft/LightGBM#2212]
Python Version

LightGBM version: 2.2.3

## Error message

Latest documentation (https://lightgbm.readthedocs.io/en/latest/Python-API.html#lightgbm.Booster) says that `Booster`'s constructor can load from a string  using parameter `model_str`:
`class lightgbm.Booster(params=None, train_set=None, model_file=None, model_str=None, silent=False)`

But this option is not supported anymore:
Current source code for Booster's constructor is:
`def __init__(self, params=None, train_set=None, model_file=None, silent=False)`
and trying to use it logically results in the following exception:
`TypeError: __init__() got an unexpected keyword argument 'str_model'`

**Comment by StrikerRUS** [comment]
> Latest documentation …

is for `master` branch.

Please wait for #2138 or use old unofficial way: https://github.com/microsoft/LightGBM/issues/2097#issuecomment-482332232.
