### ISSUE TITLE
multi-class classification  num_class limited

### ISSUE THREAD

**Issue by wyfSunflower** [microsoft/LightGBM#2219]
## Environment info

Operating System:Ubuntu 16.04 64bit

CPU/GPU model:Intel® Core™ i7-8550U CPU @ 1.80GHz × 8 

C++/Python/R version:python 3.5

LightGBM version or commit hash:2.2.3

## Error message

{'num_class': 875, 'num_iterations': 3500, 'metric': 'multi_logloss', 'lambda_l2': 0.01, 'lambda_l1': 0.45, 'objective': 'softmax', 'learning_rate': 0.001, 'max_bin': 512, 'verbose': -1, 'train_metric': False, 'num_leaf': 511}
Plotting metrics recorded during training...
Plotting feature importances...
[1]	training's multi_logloss: 6.39353	valid_1's multi_logloss: 6.40702

[905]	training's multi_logloss: 0.967207	valid_1's multi_logloss: 1.06062
./constructModel.sh: line 35: 19937 Killed    

## Reproducible examples

param dict is {'learning_rate': 0.001, 'lambda_l1': 0.45, 'lambda_l2': 0.01, 'num_leaf': 511, 'objective': 'softmax','metric': 'multi_logloss',
 'num_class': CLASS_NUMBER, 'verbose': -1, 'num_iterations': 3500, 'max_bin': 512, 'train_metric': False}

## Steps to reproduce

1.Feature dimension is 45,   num_class = 3500,   sample count is 269898.
2.The model actual num_class is limit to 875.  Not 3500.
3.And when iterate to 905th , process was killed on my 32GB memory laptop with memory leak.
Can anyone tell me how to do? Thanks!

**Comment by guolinke** [comment]
@wyfSunflower 
I think it is out of memory, not memory leak. Suggestion: use smaller num_leaves and set max_bin smaller than 256, to reduce memory cost. BTW, num_class will time the memory usage.

as for the num_class problem, how did you print `num_class': 875`? 
Did you explicitly set `num_class=3500` ? what is `CLASS_NUMBER` ?

**Comment by wyfSunflower** [comment]
CLASS_NUMBER=3500.after training, I want to show the feature importance in figure,but I got this error:
    evals_result=evals_result,feature_name=[index2beacon[i] for i in range(X_train_norm.shape[-1])])
  File "/home/gml/venv/lib/python3.5/site-packages/lightgbm/engine.py", line 242, in train
    booster.model_from_string(booster.model_to_string(), False).free_dataset()
  File "/home/gml/venv/lib/python3.5/site-packages/lightgbm/basic.py", line 2106, in model_to_string
    ptr_string_buffer))
  File "/home/gml/venv/lib/python3.5/site-packages/lightgbm/basic.py", line 46, in _safe_call
    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))
lightgbm.basic.LightGBMError: std::bad_alloc

**Comment by wyfSunflower** [comment]
clf=lgb.train(params, train_data, valid_sets=[train_data, validation_data],categorical_feature=[FEATURE_DIMENSION],
              evals_result=evals_result,feature_name=[index2beacon[i] for i in range(X_train_norm.shape[-1])])
FEATURE_DIMENSION=45
params = {'learning_rate': 0.001, 'lambda_l1': 0.45, 'lambda_l2': 0.01, 'num_leaf': 64, 'objective': 'softmax','metric': 'multi_logloss',
 'num_class': CLASS_NUMBER, 'verbose': -1, 'num_iterations': 3500, 'max_bin': 64, 'train_metric': False}

**Comment by guolinke** [comment]
how many memories in your machines?
For your log, it learns `3500 * 3500` (about 12M) trees, which costs many memories when converting to string.

**Comment by guolinke** [comment]
duplicate to https://github.com/microsoft/LightGBM/issues/2265
