### ISSUE TITLE
Better release notes

### ISSUE THREAD

**Issue by guolinke** [microsoft/LightGBM#2220]
It is my bad for the empty release notes.

It seems Azure Pipeline can automatically generate release notes: https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/GitHubReleaseV0

Let us enable it.

**Comment by StrikerRUS** [comment]
It will look like this:
> Another exciting feature included in this task is the ability to automatically compile changelog. This task can automatically compute the changes that were done in this release compared to the last published release and append them to the release notes. The list of changes include the commit SHA, message and linked issues.

https://devblogs.microsoft.com/devops/automating-releases-in-github-through-azure-pipelines/


![image](https://user-images.githubusercontent.com/25141164/59027074-a8b23500-8860-11e9-9b85-2d64ac3e97bb.png)
