### ISSUE TITLE
LightGBMError: GPU Tree Learner was not enabled in this build.

### ISSUE THREAD

**Issue by zhuqunxi** [microsoft/LightGBM#2222]
![image](https://user-images.githubusercontent.com/22273557/59056607-93400980-8866-11e9-824d-3df958d0e3d5.png)

How to fix it? Any document for this problem?

**Comment by StrikerRUS** [comment]
Build GPU version:
https://github.com/microsoft/LightGBM/tree/master/python-package#build-gpu-version
https://lightgbm.readthedocs.io/en/latest/Installation-Guide.html#build-gpu-version

**Comment by zhuqunxi** [comment]
![image](https://user-images.githubusercontent.com/22273557/59063743-c25e7700-8876-11e9-9511-f29f8e628b46.png)
![image](https://user-images.githubusercontent.com/22273557/59063919-21bc8700-8877-11e9-9497-f835dd660cb6.png)

I am using : Win 10,  Visual Studio 2015, GTX1060
_____________________________________________________________________________
I follower your link 
https://lightgbm.readthedocs.io/en/latest/Installation-Guide.html#build-gpu-version
and download the Cmake,  Boost binaries 1.63.0 version  (msvc-14.0-64.exe). Since I am also using Tensorflow and Kearas and Pytorch, the Cuda and Cudnn should be right.

But,  still not work, what's going on？

**Comment by StrikerRUS** [comment]
Something is wrong with CMake + VS toolchain in your environment. Try to add `-G "Visual Studio 14 2015"` in your build command. Or reinstall VS.

![image](https://user-images.githubusercontent.com/25141164/59067403-3bcb8900-88ba-11e9-9d3a-4e496c0f9dd4.png)

**Comment by zhuqunxi** [comment]
![image](https://user-images.githubusercontent.com/22273557/59075400-4f68f680-889e-11e9-98fd-dcba3e91691b.png)

`if device == 'gpu':
        classifiers = [xgb.XGBClassifier(random_state=42, tree_method = 'gpu_hist'),
                      lgbm.LGBMClassifier(seed = 42, device = 'gpu')]
    else:
        classifiers = [xgb.XGBClassifier(random_state=42, tree_method = 'hist'),
                      lgbm.LGBMClassifier(seed = 42, device = 'cpu')]`

Firstly, great thanks for your help an I have implemented the gpu version. But it is  strange in  LGBMClassifier.fit(X, y) -- (X shape = (500, 75), y shape = (500, )), using gpu method is so slow and even not end.  Also,  the Nvidia  gpu did not work at all. But for the XGBClassifier, it runs well (using gpu much faster than using cpu)

**Comment by zhuqunxi** [comment]
![image](https://user-images.githubusercontent.com/22273557/59078783-9b239c00-88ae-11e9-9a88-d90e0058e33f.png)

![image](https://user-images.githubusercontent.com/22273557/59079046-eab69780-88af-11e9-8537-465c55e5ace2.png)


![image](https://user-images.githubusercontent.com/22273557/59078819-c27a6900-88ae-11e9-9250-af6f7702b026.png)

![image](https://user-images.githubusercontent.com/22273557/59078830-cd34fe00-88ae-11e9-93aa-990617cbd42f.png)

![image](https://user-images.githubusercontent.com/22273557/59078863-01a8ba00-88af-11e9-858e-a4b736ff75ac.png)

-----------------------------------------------------
Sorry to bother you again. I noticed that I have made a mistake in setting the parameters (gpu_platform_id = 1, gpu_device_id = 0). Because in my computer there are 2 gpus,  e.x., 1) Intel gpu, 2) Nvidia gpu.  But, as a result, in my testing experiment, it is really strange that the Lightgbm gpu ( **16.49** s) costs much time than the cpu version (**10.66** s).  Compared to XGBoost, it really works well, the gpu version (**5.10** s) is much better than cpu (**15.99** s).

**Comment by StrikerRUS** [comment]
Glad that you've managed to utilize your NVIDIA GPU!
Yeah, `gpu_platform_id, gpu_device_id` params are very important for GPU version, because bad values can mimic real GPU training or simply crash the whole application.

For GPU-version performance, please consider starting reading from this issue #768 and follow some links in it. Then, you may want to get familiar with some benchmarks: https://github.com/Laurae2/ml-perf/issues/8, https://github.com/Laurae2/ml-perf/issues/6, https://github.com/szilard/GBM-perf/issues/11.

**Comment by zhuqunxi** [comment]
Thanks again for your great help! I'll read these information carefully.
