### ISSUE TITLE
Errors when hosted in azure functions with Docker

### ISSUE THREAD

**Issue by akoz0r** [microsoft/LightGBM#2223]
## Environment info - Ubuntu docker file:
Ubuntu docker file with lightgbm==2.2.3
See attached docker file and requirements.txt for info
[requirements.txt](https://github.com/microsoft/LightGBM/files/3262947/requirements.txt)
[Dockerfile.txt](https://github.com/microsoft/LightGBM/files/3262950/Dockerfile.txt)

## Error message

```
Executed 'Functions.TrainModel' (Failed, Id=f28ff9e7-2e77-4c77-a4c0-72e88042a067)
Microsoft.Azure.WebJobs.Host.FunctionInvocationException: Exception while executing function: Functions.TrainModel ---> Microsoft.Azure.WebJobs.Script.Rpc.RpcException: Result: Failure
Exception: OSError: libgomp.so.1: cannot open shared object file: No such file or directory
Stack:   File "/usr/local/lib/python3.6/site-packages/azure/functions_worker/dispatcher.py", line 230, in _handle__function_load_request
    func_request.metadata.entry_point)
  File "/usr/local/lib/python3.6/site-packages/azure/functions_worker/loader.py", line 66, in load_function
    mod = importlib.import_module(fullmodname)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/site/wwwroot/TrainModel/__init__.py", line 14, in <module>
    from lightgbm import LGBMRegressor
  File "/usr/local/lib/python3.6/site-packages/lightgbm/__init__.py", line 8, in <module>
    from .basic import Booster, Dataset
  File "/usr/local/lib/python3.6/site-packages/lightgbm/basic.py", line 34, in <module>
    _LIB = _load_lib()
  File "/usr/local/lib/python3.6/site-packages/lightgbm/basic.py", line 29, in _load_lib
    lib = ctypes.cdll.LoadLibrary(lib_path[0])
  File "/usr/local/lib/python3.6/ctypes/__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "/usr/local/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)

```
[error.log](https://github.com/microsoft/LightGBM/files/3262956/error.log)

## Reproducible examples

from lightgbm import LGBMRegressor
...
lgb = LGBMRegressor(colsample_bytree=0.8, learning_rate=0.12, n_estimators=150, num_leaves=100)
lgb.fit(X_train, y_train.reshape(-1))

## Steps to reproduce

1. Create new azure functions for python project
2. Create docker image using attached docker file and requirements.txt
3. Reference and use LGBMRegressor in a http function call

**Comment by StrikerRUS** [comment]
Seems that something is wrong with your environment. LightGBM requires OpenMP library.
> Exception: OSError: libgomp.so.1: cannot open shared object file: No such file or directory

What compiler do you use?
You may try to install LightGBM from sources in your docker to catch error at compilation time which can be more verbose.

**Comment by akoz0r** [comment]
Thank you for your reply!

The docker image is built using docker for windows 2.0.
The python packages are just fetched through requirements.txt.

Installing from sources didn't go so well;

`>pip install --no-binary :all: lightgbm
Collecting lightgbm
  Using cached https://files.pythonhosted.org/packages/c9/ce/3aff55e25e282383c19c5a5fb7387fd400e64b1a1036671aefa63ceeaaf4/lightgbm-2.2.3.tar.gz
Requirement already satisfied: numpy in c:\users\jante\appdata\local\conda\conda\envs\shiny_new_env\lib\site-packages (from lightgbm) (1.16.4)
Requirement already satisfied: scipy in c:\users\jante\appdata\local\conda\conda\envs\shiny_new_env\lib\site-packages (from lightgbm) (1.3.0)
Requirement already satisfied: scikit-learn in c:\users\jante\appdata\local\conda\conda\envs\shiny_new_env\lib\site-packages (from lightgbm) (0.21.2)
Requirement already satisfied: joblib>=0.11 in c:\users\jante\appdata\local\conda\conda\envs\shiny_new_env\lib\site-packages (from scikit-learn->lightgbm) (0.13.2)
Skipping bdist_wheel for lightgbm, due to binaries being disabled for it.
Installing collected packages: lightgbm
  Running setup.py install for lightgbm ... error
    ERROR: Complete output from command 'C:\Users\jante\AppData\Local\conda\conda\envs\shiny_new_env\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\jante\\AppData\\Local\\Temp\\pip-install-qx64ce0e\\lightgbm\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\jante\AppData\Local\Temp\pip-record-4g86ptb4\install-record.txt' --single-version-externally-managed --compile:
    ERROR: running install
    INFO:LightGBM:Starting to compile the library.
    INFO:LightGBM:Starting to compile with MSBuild from existing solution file.
    WARNING:LightGBM:Compilation with MSBuild from existing solution file failed.
    INFO:LightGBM:Starting to compile with Visual Studio 15 2017 Win64.
    INFO:LightGBM:Starting to compile with Visual Studio 14 2015 Win64.
    INFO:LightGBM:Starting to compile with Visual Studio 16 2019.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\jante\AppData\Local\Temp\pip-install-qx64ce0e\lightgbm\setup.py", line 338, in <module>
        'Topic :: Scientific/Engineering :: Artificial Intelligence'])
      File "C:\Users\jante\AppData\Local\conda\conda\envs\shiny_new_env\lib\site-packages\setuptools\__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "C:\Users\jante\AppData\Local\conda\conda\envs\shiny_new_env\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Users\jante\AppData\Local\conda\conda\envs\shiny_new_env\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "C:\Users\jante\AppData\Local\conda\conda\envs\shiny_new_env\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\jante\AppData\Local\Temp\pip-install-qx64ce0e\lightgbm\setup.py", line 261, in run
        openmp_include_dir=self.openmp_include_dir, openmp_library=self.openmp_library)
      File "C:\Users\jante\AppData\Local\Temp\pip-install-qx64ce0e\lightgbm\setup.py", line 163, in compile_cpp
        LOG_NOTICE)))
    Exception: Please install Visual Studio or MS Build and all required dependencies first
    The full version of error log was saved into C:\Users\jante\LightGBM_compilation.log
    ----------------------------------------
ERROR: Command "'C:\Users\jante\AppData\Local\conda\conda\envs\shiny_new_env\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\jante\\AppData\\Local\\Temp\\pip-install-qx64ce0e\\lightgbm\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\jante\AppData\Local\Temp\pip-record-4g86ptb4\install-record.txt' --single-version-externally-managed --compile" failed with error code 1 in C:\Users\jante\AppData\Local\Temp\pip-install-qx64ce0e\lightgbm\`

Not sure what to make of that as I do have VS2019 installed and MSBuild set in path variables.
I did end up installing CMake for good measure though. Same error still.

Contents of LightGBM_compilation.log:

`CMake Error at CMakeLists.txt:7 (PROJECT):
  Generator
    Visual Studio 15 2017 Win64
  could not find any instance of Visual Studio.

-- Configuring incomplete, errors occurred!
See also "C:/Users/jante/AppData/Local/Temp/pip-install-iw9f4pnw/lightgbm/build_cpp/CMakeFiles/CMakeOutput.log".
-- Selecting Windows SDK version  to target Windows 10.0.17134.
CMake Error at CMakeLists.txt:7 (PROJECT):
  Failed to run MSBuild command:

    C:/Program Files (x86)/MSBuild/14.0/bin/MSBuild.exe

  to get the value of VCTargetsPath:

    Microsoft (R) Build Engine version 14.0.23107.0
    Copyright (C) Microsoft Corporation. All rights reserved.
    
    Build started 6/6/2019 10:56:02 PM.
    Project "C:\Users\jante\AppData\Local\Temp\pip-install-iw9f4pnw\lightgbm\build_cpp\CMakeFiles\3.14.5\VCTargetsPath.vcxproj" on node 1 (default targets).
    C:\Users\jante\AppData\Local\Temp\pip-install-iw9f4pnw\lightgbm\build_cpp\CMakeFiles\3.14.5\VCTargetsPath.vcxproj(14,2): error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
    Done Building Project "C:\Users\jante\AppData\Local\Temp\pip-install-iw9f4pnw\lightgbm\build_cpp\CMakeFiles\3.14.5\VCTargetsPath.vcxproj" (default targets) -- FAILED.
    
    Build FAILED.
    
    "C:\Users\jante\AppData\Local\Temp\pip-install-iw9f4pnw\lightgbm\build_cpp\CMakeFiles\3.14.5\VCTargetsPath.vcxproj" (default target) (1) ->
      C:\Users\jante\AppData\Local\Temp\pip-install-iw9f4pnw\lightgbm\build_cpp\CMakeFiles\3.14.5\VCTargetsPath.vcxproj(14,2): error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
    
        0 Warning(s)
        1 Error(s)
    
    Time Elapsed 00:00:00.05
      Exit code: 1

-- Configuring incomplete, errors occurred!
See also "C:/Users/jante/AppData/Local/Temp/pip-install-iw9f4pnw/lightgbm/build_cpp/CMakeFiles/CMakeOutput.log".
CMake Error at CMakeLists.txt:7 (PROJECT):
  Generator

    Visual Studio 16 2019

  could not find any instance of Visual Studio.

-- Configuring incomplete, errors occurred!
See also "C:/Users/jante/AppData/Local/Temp/pip-install-iw9f4pnw/lightgbm/build_cpp/CMakeFiles/CMakeOutput.log".
`

If you have any further pointers that would be much appreciated.

**Comment by StrikerRUS** [comment]
Sorry, I was not clear enough. I meant compilation from sources by this guide: https://lightgbm.readthedocs.io/en/latest/Installation-Guide.html#windows.
Also please tell your CMake and VS versions.

**Comment by StrikerRUS** [comment]
In addition, I see your LightGBM is run under Ubuntu.
```
Microsoft.Azure.WebJobs.Host.FunctionInvocationException: Exception while executing function: Functions.TrainModel ---> Microsoft.Azure.WebJobs.Script.Rpc.RpcException: Result: Failure
Exception: OSError: libgomp.so.1: cannot open shared object file: No such file or directory
Stack:   File "/usr/local/lib/python3.6/site-packages/azure/functions_worker/dispatcher.py", line 230, in _handle__function_load_request
    func_request.metadata.entry_point)
```
But you're telling that you're compiling for Windows. It's confusing...

**Comment by akoz0r** [comment]
Thank you for your replies again.

As mentioned I am building a docker image with LightGBM as a python package.

I finally found the solution to my problems; I was missing libgompl in the docker image.
Solved by adding this to my docker file;

```
RUN apt-get update && apt-get install -y --no-install-recommends apt-utils
RUN apt-get -y install curl
RUN apt-get install libgomp1
```

**Comment by StrikerRUS** [comment]
Glad that you solved the problem! 🎉 
And thanks a lot for sharing the solution.
