### ISSUE TITLE
.txt file representation of model

### ISSUE THREAD

**Issue by Chiragasourabh** [microsoft/LightGBM#2232]
what does these numbers represent in Booster.save_model() ( .txt file representation of model)

left_child=1 15 -2 -3 6 -5 9 8 10 -4 -6 12 18 14 -14 16 -1 -17 -10 -13 -20
right_child=2 3 4 5 7 -7 -8 -9 11 -11 -12 19 13 -15 -16 17 -18 -19 20 -21 -22

**Comment by guolinke** [comment]
refer to https://github.com/microsoft/LightGBM/issues/1552
