### ISSUE TITLE
Never used variable 'pred_early_stop'

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [microsoft/LightGBM#2233]
https://github.com/microsoft/LightGBM/blob/cdba71475f3751e26b62beb3e6bfec9a3f6f6962/src/application/application.cpp#L88

advice: delete the variable which is never used

**Comment by jameslamb** [comment]
Thank you @QiAnXinCodeSafe for reporting. We would be happy to consider a PR if you'd like to make one!

**Comment by QiAnXinCodeSafe** [comment]
I make a PR here, please reviewed, thanks!
https://github.com/microsoft/LightGBM/pull/2294
