### ISSUE TITLE
Decision_type in save_model 

### ISSUE THREAD

**Issue by Chiragasourabh** [microsoft/LightGBM#2234]
Is that decision type is constant to 2 in every intermediate node or will it change ?

**Comment by guolinke** [comment]
it will be different when you use categorical features or missing values.
https://github.com/microsoft/LightGBM/blob/master/src/io/tree.cpp#L54-L62

**Comment by Chiragasourabh** [comment]
Thank you

by the way
<= maps to 2
>= maps to ?
== maps to ?

and if below conditions are used, then
< maps to ?
> maps to ?

**Comment by Chiragasourabh** [comment]
'default_left': True

is this is constant ?

**Comment by guolinke** [comment]
refer to https://github.com/microsoft/LightGBM/blob/cdba71475f3751e26b62beb3e6bfec9a3f6f6962/include/LightGBM/tree.h#L192-L207
and
https://github.com/microsoft/LightGBM/blob/cdba71475f3751e26b62beb3e6bfec9a3f6f6962/include/LightGBM/tree.h#L19-L20

default_left is for missing value, it means the missing value will go to left child, otherwise go to right child.

**Comment by Chiragasourabh** [comment]
any way to extract feature_infos of a LGBM model without saving model in text format

**Comment by guolinke** [comment]
@Chiragasourabh you can try to dump_json.

**Comment by Chiragasourabh** [comment]
feature_infos is not available in json representation of model

**Comment by Chiragasourabh** [comment]
@guolinke  what does this mean in threshold value ? threshold =  0||3||5||9||11||13

**Comment by guolinke** [comment]
this is for categorical features, it means equal one of them then will choose the left child.

**Comment by Chiragasourabh** [comment]
ok then how to get cat_threshold values for categorical features

**Comment by guolinke** [comment]
In josn format, they both use threshold field.

**Comment by Chiragasourabh** [comment]
Yeah
JSON representation of model will have values like 2 0||3||5||9|11||13 in threshold field 
.
But in text representation of model , the respective threshold value will be different
And text representation will have one more field named cat_threshold with some values like  4 10793

How to get this cat_threshold ?

Whats the relation between threshold values of categorical features in JSON and respective cat_threshold values of text ?

**Comment by Chiragasourabh** [comment]
Tree=0
num_leaves=31
num_cat=2
split_feature=3 4 0 7 7 7 5 0 7 0 7 0 0 5 5 7 5 0 0 5 5 5 7 5 0 0 5 5 0 0
split_gain=361.371 134.881 24.9509 13.835 11.7551 8.17127 6.42183 11.0431 6.41492 6.11853 5.2612 5.15376 4.88231 4.62766 4.44582 4.42574 3.82318 3.55908 3.55679 3.47276 3.35683 2.77087 2.58136 2.80828 9.76656 8.86537 6.69678 6.56981 2.49933 8.62454
threshold=0 1 31.500000000000004 30.500000000000004 48.500000000000007 41.500000000000007 56318.030000000006 36.500000000000007 48.500000000000007 38.500000000000007 41.500000000000007 28.500000000000004 25.500000000000004 27097.545000000002 47640.350000000006 38.500000000000007 32239.695000000003 38.500000000000007 32.500000000000007 123098.33500000002 40403.080000000009 54296.495000000003 55.500000000000007 29386.665000000005 47.500000000000007 50.500000000000007 21538.500000000004 43617.120000000003 31.500000000000004 36.500000000000007
decision_type=1 5 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
left_child=1 5 10 -4 9 11 7 8 -5 -2 21 -1 -6 -7 16 -13 -11 -8 -15 -14 -20 -3 23 24 26 27 -9 -25 -17 -30
right_child=4 2 3 6 12 13 17 22 -10 14 -12 15 19 18 -16 28 -18 -19 20 -21 -22 -23 -24 25 -26 -27 -28 -29 29 -31
leaf_value=-1.2915606834429865 -1.3003464425259985 -1.2079023876322035 -1.0836734445414333 -1.1237179390175791 -1.3089237259697526 -1.200887016914318 -0.78108723315605744 -0.90483837261955569 -0.96405777785191205 -1.2493932944494113 -1.0221534752050967 -1.2584130568009781 -1.1729747972495401 -1.1826470530478161 -1.271441602419908 -1.1104889542352809 -1.1144576496699703 -0.90237443753815183 -1.0231776546721132 -1.2811428579269266 -1.1296923192418427 -1.0866767816271443 -0.98125194905436841 -0.77914903306004657 -0.84855505554577793 -0.96166287543442697 -1.0708019998883864 -0.93110392058731839 -1.2925820388857374 -1.1596533902172546
leaf_count=32 583 22 37 27 24 36 20 22 29 28 31 44 94 22 252 28 20 41 35 20 31 20 39 43 35 56 35 25 34 134
internal_value=0 1.07325 1.87641 2.31928 -0.93069 -0.0149285 2.45601 2.31885 1.37102 -1.08133 0.823284 -0.245642 -0.34156 0.484463 -0.807796 -0.127164 -0.150315 3.1553 0.775714 -0.13813 1.04931 0.279627 2.527 2.62777 2.31574 2.85928 1.71393 3.43124 0.0244965 -0.0841702
internal_count=1899 878 482 409 1021 396 372 311 56 883 73 272 138 124 300 240 48 61 88 114 66 42 255 216 92 124 57 68 196 168
cat_boundaries=0 1 2
cat_threshold=4 10793
shrinkage=1

**Comment by guolinke** [comment]
`threshold` in model file is the index for cat_boundaries and cat_threshold, and then use cat_boundaries and cat_threshold to get the real "threshold". 
Json format already store the results of the real threshold, so it doesn't need cat_boundaries and cat_threshold.

refer to code:
https://github.com/microsoft/LightGBM/blob/86269ee38da20785097cd35aa7eb0b946864fe76/src/io/tree.cpp#L265-L276

BTW, for these details, finding them in the code is more efficient.
