### ISSUE TITLE
How to find unnecessary feature in the model? 

### ISSUE THREAD

**Issue by Yang-HangWA** [microsoft/LightGBM#2235]
When I use feature importance to sort the split importance value, it can't say the feature with  higher importance play a more important role in the features, so I drop the feature in the feature table one by one to see the influence to the model and find I can drop some features to get a model with same predict result . Does it mean i can make a search algorithm to find the smallest feature set to get the model? Or there is a way to get the essential feature set ?

**Comment by StrikerRUS** [comment]
There are a lot of different algorithms for feature selection. I think you can start reading from https://scikit-learn.org/stable/modules/feature_selection.html#feature-selection and then move to more complicated methods.
