### ISSUE TITLE
[R] Submitting to CRAN?

### ISSUE THREAD

**Issue by coforfe** [Microsoft/LightGBM#224]
Hello,

What is the idea of submitting LightGBM to CRAN?.

Thanks,
Carlos.

**Comment by Laurae2** [comment]
Currently we need to have a stable release first. Then we also need to check if the package can be compiled on any OS, including exotic ones (Solaris, etc.).

After it will be [submitted to CRAN](https://github.com/Microsoft/LightGBM/issues/19#issuecomment-271212946) once we reach that level and a good documentation of the R package (currently the doc is sparse about parameters and their impacts). @guolinke did so far a great job at fixing all the issues we are finding when it comes to the LightGBM backend integration in R.

About the R package documentation issue, anyone can submit PRs to help us (and also provide larger / more custom examples).

**Comment by coforfe** [comment]
Sorry, thanks for your reply and clarifications.
If I see the possibility I could participate in creating a vignette for the package.

Thanks again,
Carlos.

**Comment by guolinke** [comment]
@Laurae2 
Do you think it is ready now ?

**Comment by Laurae2** [comment]
@guolinke We will need to switch to MinGW by default first and fix all CRAN issues encountered.

**Comment by guolinke** [comment]
move to #629
