### ISSUE TITLE
LightGBM classifier cannot learn simple example

### ISSUE THREAD

**Issue by humzaiqbal** [microsoft/LightGBM#2243]
### System setup
OS: Mac OS 10.13.6
LightGBM version: '2.2.4'
scikit-learn version: '0.21.2'

### Code 
```
import lightgbm as lgb
import numpy as np
from sklearn.ensemble import GradientBoostingClassifier

X = np.array([[1,1,1],[2,2,2]])
y = [0,1]

model = lgb.LGBMClassifier()
model.fit(X,y)
lgb_probabilities = model.predict_proba(X)
print('lgb_probabilities: ', lgb_probabilities)

model = GradientBoostingClassifier()
model.fit(X,y)
sk_probabilities = model.predict_proba(X)
print('sk_probabilities: ', sk_probabilities)
```

### Results
The lgb probabilities are 
```
array([[0.5, 0.5],
       [0.5, 0.5]])
```

While the sklearn probabilities are 
```
array([[9.99705117e-01, 2.94883265e-04],
       [2.94883265e-04, 9.99705117e-01]])
```

The LightGBM probabilities imply that the classifier is unable to learn the simple case above. Any insights into why that may be? I made sure that `reg_alpha`, `reg_lambda`, and `min_split_gain` are all 0 so I don't think regularization is playing a role. Any help would be appreciated, thanks.

**Comment by guolinke** [comment]
check `min_data` and `min_data_in_bin` parameters.
