### ISSUE TITLE
latest version inconsistent with PyPI

### ISSUE THREAD

**Issue by chloe-wang** [microsoft/LightGBM#2244]
the latest lightgbm version showed in the VERSION.TXT file in github is 2.2.4. But we can only find 2.2.3 verison in PyPI. Some important function like "get_split_value_histogram" can't be found in 2.2.3.

## Environment info

Operating System:

CPU/GPU model:

C++/Python/R version:

LightGBM version or commit hash:

## Steps to reproduce

1.
2.
3.

**Comment by StrikerRUS** [comment]
`2.2.4` version is a development version and is available only from `master` branch on GitHub yet. We hope to publish it soon (see #2138), so please stay tuned.
