### ISSUE TITLE
Does Booster.dump_model really save its best iteration?

### ISSUE THREAD

**Issue by takaiyuk** [microsoft/LightGBM#2246]
Does `Booster.dump_model` really save its best iteration? `dump_model` says in [the document](https://lightgbm.readthedocs.io/en/latest/Python-API.html#lightgbm.Booster.dump_model): 

> num_iteration – Index of the iteration that should be dumped. If None, if the best iteration exists, it is dumped; otherwise, all iterations are dumped. If <= 0, all iterations are dumped.

In my reproducible example, I set `early_stopping_round` and the training stopped when the iteration is 19th. However, `model.dump_model` save 56 trees (not its best iteration), **even if I specified `num_iteration`.** 

I don't why. Please tell me the reason if I am not wrong.

## Environment info

Operating System: MacOS

CPU/GPU model: CPU

C++/Python/R version: Python

LightGBM version or commit hash: 2.2.3

## Error message

Nothing

## Reproducible examples

```
import lightgbm as lgb
import seaborn as sns
from sklearn.model_selection import train_test_split

print(f"lgb version: {lgb.__version__}")  # lgb version: 2.2.3

LGB_PARAMS = {
    "objective": "multiclass", 
    "num_class": 3, 
    "metric": "multi_logloss",
    "learning_rate": 0.3,
}


def load_data():
    df = sns.load_dataset("iris")
    return df


def prepare_data(df, target_column):
    convert_spicies = {"setosa": 0, "versicolor": 1, "virginica": 2}
    X = df.drop(target_column, axis=1)
    y = df[target_column].apply(lambda x: convert_spicies[x])
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
    return X_train, X_test, y_train, y_test


def build_lgb(data, params):
    X_train, X_test, y_train, y_test = prepare_data(data, target_column="species")
    lgb_train = lgb.Dataset(X_train, y_train)
    lgb_test = lgb.Dataset(X_test, y_test, reference=lgb_train)
    model = lgb.train(params, lgb_train, num_boost_round=100, valid_sets=lgb_test, early_stopping_rounds=10, verbose_eval=False)

    print(f"best iteration: {model.best_iteration}")  # best iteration: 19

    return model


def main():
    data = load_data()
    model = build_lgb(data, LGB_PARAMS)
    return model


model = main()

model_json = model.dump_model()
print(model_json["tree_info"][-1]["tree_index"])  # 56

model_json = model.dump_model(num_iteration=model.best_iteration)
print(model_json["tree_info"][-1]["tree_index"])  # 56
```

**Comment by takaiyuk** [comment]
I didn't read the document much. It says that:
> Note: internally, LightGBM constructs num_class * num_iterations trees for multi-class classification problems

https://lightgbm.readthedocs.io/en/latest/Parameters.html#num_iterations

**Comment by StrikerRUS** [comment]
19 * 3 = 57
Your task is multiclass, that's why you have more trees than iterations (3 trees per iteration).

**Comment by takaiyuk** [comment]
Exactly.
