### ISSUE TITLE
RAM issue with float and bool features

### ISSUE THREAD

**Issue by victordek** [microsoft/LightGBM#2248]
Lightgbm could face RAM exploison on datasets, containing float and bool features (mixed dataset).
RAM required for mixed dataset is doubles the RAM required for the same shape dataset of floats.
Finally, casting mixed dataset to float makes fitting less RAM intensive.
(though size of dataset in memory is increased).

## Environment info

Operating System: Ubuntu 18.04 LTS (GNU/Linux 4.15.0-20-generic x86_64)

CPU/GPU model: Intel(R) Xeon(R) CPU E3-1230 v6 @ 3.50GHz

C++/Python/R version: Python

LightGBM version or commit hash: lightgbm==2.2.2

## Error message

lib/python3.6/site-packages/lightgbm/basic.py in _data_from_pandas(data, feature_name, categorical_feature, pandas_categorical)
    276                    "Did not expect the data types in fields ")
    277             raise ValueError(msg + ', '.join(bad_fields))
--> 278         data = data.values.astype('float')
    279     else:
    280         if feature_name == 'auto':

MemoryError: 

OR jupyter kernel restart

## Reproducible examples

```
from sklearn.datasets import make_regression
from lightgbm import LGBMRegressor
import pandas as pd

# n_samples is choosen for 32Gb RAM:
# model on base dataset could be fitted
# model on bool and float fails in OOM (kernel restart/MemoryError)

X, y = make_regression(n_samples=int(6e6), random_state=0)

base_type = 'float16'
X = pd.DataFrame(X, dtype=base_type)
y = pd.DataFrame(y, dtype=base_type)

print('Source dataset')
X.info(memory_usage='deep', max_cols=1)
print()

# duplicating is used to train models on datasets of same shape

print('Base dataset')
X_base = X.join(X + .1, rsuffix='duplicate').astype(base_type)
X_base.info(memory_usage='deep', max_cols=1)
print()

print('Mixed dataset with float and bool')
X_mixed = X.join(X == 0, rsuffix='bool')
X_mixed.info(memory_usage='deep', max_cols=1)
print()

del X

model_base = LGBMRegressor()
model_base.fit(X_base, y)
print('Base ok')

# extra run
# model = LGBMRegressor()
# model.fit(X_mixed.astype(base_type), y)
# print('Mixed converted to float ok')

model_mixed = LGBMRegressor()
model_mixed.fit(X_mixed, y)
print('Mixed ok... Increase n_samples and rerun to face the issue!')
```
## Steps to reproduce

1. Decrease n_sample, so model could be fitted on base dataset on your system using > half of RAM
2. Try fitting on mixed dataset

**Comment by guolinke** [comment]
This is expected, for the pandas dataframe is converting to numpy object, before passing to LightGBM.
refer to 
https://github.com/microsoft/LightGBM/blob/16751b3803e847592dba3bab876c4f052507e45d/python-package/lightgbm/basic.py#L290

In short, for memory limit tasks, it is better to use numpy arrays directly.

**Comment by victordek** [comment]
Thanks for a hint, @guolinke  But everything is contraversial...
Using numpy `np.array(X_mixed)` leads to OOM:
```
-------------------------------
MemoryErrorTraceback (most recent call last)
<ipython-input-7-d7701638b4ae> in <module>
----> 1 np.array(X_mixed)

MemoryError: 
```
Same result  for:
```
model_mixed = LGBMRegressor()
model_mixed.fit(np.array(X_mixed), np.array(y))
print('Mixed ok... Increase n_samples and rerun to face the issue!')
```

BUT using pandas (commented block in example, replaced type parameter):
```
# extra run
model = LGBMRegressor()
model.fit(X_mixed.astype('float16'), y)
print('Mixed converted to float ok')
```
results in successful run.

Concluding:
`DataFrame.astype` could be more memory efficient than `np.array.astype` for datasets with mixed types.


FYI, source dataset from example takes 1.1Gb RAM as `pd.DataFrame` (mixed and base around 2Gb).

**Comment by guolinke** [comment]
@victordek 
I mean, using numpy array directly, for extracting features, not converting pandas to numpy.
The converting will always need additional memory.

**Comment by victordek** [comment]
Well, I got a successfully run:
```
X, y = make_regression(n_samples=int(6e6), random_state=0)

base_type = 'float16'
X = X.astype(base_type)
y = y.astype(base_type)

# didn't find another appropriate dtype unfortunately
X_mixed = np.empty((X.shape[0], 2 * X.shape[1]), dtype='object')

X_mixed[:, :100] = X 
X_mixed[:, 100:] = X == 0
del X

model_mixed = LGBMRegressor()
model_mixed.fit(X_mixed, y)
print('Mixed ok... Increase n_samples and rerun to face the issue!')
```
Though, it took a bit more than 32Gb RAM.

Is there any other way to use different types of data for model?

**Comment by guolinke** [comment]
please don't use float16, LightGBM often accpet float32 and float64.
Therefore, float16 will be converted to float32 when pass to lightgbm, and increase peak memory.

**Comment by victordek** [comment]
That make sense. But what about using mixed types of features for estimator?
Boolean (or integer) might be a good choice for categorical features. Should I avoid mixed types as well?

**Comment by guolinke** [comment]
@victordek unfortunately, LightGBM cannot accpet mix-type as input. Therefore, all mix-type inputs will be converted to floating point inputs. So there are no advantages.
