### ISSUE TITLE
Question about Computation of LambdaRank Gradient

### ISSUE THREAD

**Issue by dszhengyu** [microsoft/LightGBM#2255]
Hi, 

For the computation of delta NDCG for LambdaRank gradient in: https://github.com/microsoft/LightGBM/blob/master/src/objective/rank_objective.hpp#L139
Shouldn't it be:
`const double dcg_gap = fabs(high_label_gain - low_label_gain);`
?
That the dcg_gap should take the abs value?

Thx

**Comment by guolinke** [comment]
It is always the non-negative values, fabs is not needed.

**Comment by dszhengyu** [comment]
Sorry I don't get it. 
Given label_gain_ = 0,1,3,7,15,31,63,...,2^30-1 from https://lightgbm.readthedocs.io/en/latest/Parameters.html#label_gain, 
if 
    high_label = 0, low_label=1, 
then 
    dcg_gap = high_label_gain - low_label_gain = 0 - 1= = -1 <0, right?

**Comment by dszhengyu** [comment]
Aha, sorry I miss this 
`if (high_label <= low_label || low_score == kMinScore) { continue; }`
Not more questions. 
Thx
