### ISSUE TITLE
min_data_per_group and min_data_in_leaf

### ISSUE THREAD

**Issue by nirupamkar** [microsoft/LightGBM#2258]
For training lgb with weights for each rows what do these parameters mean?
1. min_data_per_group
2. min_data_in_leaf

Is it sum of weights for the group/leaf or count?

**Comment by nirupamkar** [comment]
@guolinke any help on this?

**Comment by guolinke** [comment]
Min data per group is for categorical features, please check the document carefully.

**Comment by nirupamkar** [comment]
@guolinke I understand min_data_per_group is for categorical and yes I have read the document carefully. What I meant min_data_per_group constraint  could be imposed at a row level(count) or at a weight level. 
When we work with categorical features and size of data is huge, it sometime helps if we do a groupby on categorical features with weight being number of times the row is there in data. For example


f1 | f2 | weight | Target
-- | -- | -- | --
a1 | b1 | 2 | 1
a1 | b2 | 3 | 2
a2 | b1 | 3 | 3
a3 | b2 | 5 | 4

For categorical feature f1 if we put min_data_per_group=2, split of f1=a2 will be a valid split if we consider the weight(it has been there 2 times) but invalid if we consider row count(which is 1 here).

The "documentation" says "min_data_per_group 🔗︎, default = 100, type = int, constraints: min_data_per_group > 0
minimal number of data per categorical group"

The term "minimal number of data" is confusing in this context hence the question. Let me know if this context helps. 

Let me know the case which is being used here.

**Comment by guolinke** [comment]
@nirupamkar both min_data_per_group and min_data_in_leaf do not consider the sample weights. 

you can use `min_sum_hessian_in_leaf` to replace the `min_data_in_leaf`, for sample weights.

As for `min_data_per_group`, there is no replacement for now.

**Comment by nirupamkar** [comment]
@guolinke Thanks for the reply. Could you please help me with the following
1. it would be really helpful if you add min_sum_hessian_in_leaf in this [request](https://github.com/microsoft/LightGBM/issues/2037)
2.When cat_l2 is used, is lambda_l2  used? Or how is cal_l2 being used?

**Comment by guolinke** [comment]
for the former, I will add it when I have time.
for the latter, it is the sum of cat_l2 and lambda_l2, refer to https://github.com/microsoft/LightGBM/blob/0a4a7a86f5a1d3146c36c7d8c082154a193d4893/src/treelearner/feature_histogram.hpp#L178
