### ISSUE TITLE
Please add more explanation in the README.md file for LightGBM/examples/regression/

### ISSUE THREAD

**Issue by sbalaspace** [microsoft/LightGBM#2260]
The LightGBM/examples/regression/  works fine when run. However, it is not possible to make sense of the outputs.

For **regression.train** what is the target and where is it specified in **train.conf**. Can you explain this in the **README.md**

**Comment by jameslamb** [comment]
Thanks for the feedback, @sbalaspace . It has been a while since the files in https://github.com/microsoft/LightGBM/tree/master/examples/regression were touched. We will take a look.

**Comment by StrikerRUS** [comment]
@sbalaspace The target is the first column in https://github.com/microsoft/LightGBM/blob/master/examples/regression/regression.train.

For the semantics, according to the GitHub history, I guess only @guolinke or @chivee know the story behind examples files.

**Comment by sbalaspace** [comment]
Thank you @jameslamb and @StrikerRUS for looking into this issue.

I discovered the solution from the docs page.

The target column is specified using `label_column` parameter. The default value for same is an empty string i.e. `""`. But it picks the first column as target by default.

On hindsight this looks straight forward but it is something good to have in the **README**

**Comment by chivee** [comment]
Hi @sbalaspace , the default data format we are using is the [libsvm](https://stats.stackexchange.com/questions/61328/libsvm-data-format) , We 'll adding link that pointer to the[ data format](https://lightgbm.readthedocs.io/en/latest/Quick-Start.html#training-data-format) in README.
