### ISSUE TITLE
Install lightgbm-gpu ERROR

### ISSUE THREAD

**Issue by crazycatii** [microsoft/LightGBM#2262]
I need help.
Cmake run error
## Error message

OpenCL include directory: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0/include
CMake Error at D:/Program Files/CMake/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Boost (missing: filesystem system) (found suitable version
  "1.70.0", minimum required is "1.56.0")
Call Stack (most recent call first):
  D:/Program Files/CMake/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  D:/Program Files/CMake/share/cmake-3.15/Modules/FindBoost.cmake:2143 (find_package_handle_standard_args)
  CMakeLists.txt:100 (find_package)

Configuring incomplete, errors occurred!
See also "D:/LightGBM/Build/CMakeFiles/CMakeOutput.log".
See also "D:/LightGBM/Build/CMakeFiles/CMakeError.log".

## Cmake error logs
Determining if the CL_VERSION_2_2 exist failed with the following output:
Change Dir: D:/LightGBM/Build/CMakeFiles/CMakeTmp

Run Build Command(s):D:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/MSBuild/15.0/Bin/MSBuild.exe cmTC_70fc3.vcxproj /p:Configuration=Debug /p:Platform=Win32 /p:VisualStudioVersion=15.0 /v:m && 用于 .NET Framework 的 Microsoft (R) 生成引擎版本 15.9.20+g88f5fadfbe

版权所有(C) Microsoft Corporation。保留所有权利。

  用于 x86 的 Microsoft (R) C/C++ 优化编译器 19.16.27024.1 版

  版权所有(C) Microsoft Corporation。保留所有权利。

  

  cl /c /I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\include" /Zi /W3 /WX- /diagnostics:classic /Od /Ob0 /Oy- /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_70fc3.dir\Debug\\" /Fd"cmTC_70fc3.dir\Debug\vc141.pdb" /Gd /TC /analyze- /errorReport:queue D:\LightGBM\Build\CMakeFiles\CMakeTmp\CheckSymbolExists.c

  CheckSymbolExists.c

  

D:\LightGBM\Build\CMakeFiles\CMakeTmp\CheckSymbolExists.c(8): error C2065: “CL_VERSION_2_2”: 未声明的标识符 [D:\LightGBM\Build\CMakeFiles\CMakeTmp\cmTC_70fc3.vcxproj]

File D:/LightGBM/Build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0/include/CL/cl.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef CL_VERSION_2_2
  return ((int*)(&CL_VERSION_2_2))[argc];
#else
  (void)argc;
  return 0;
#endif
}

Determining if the CL_VERSION_2_1 exist failed with the following output:
Change Dir: D:/LightGBM/Build/CMakeFiles/CMakeTmp

Run Build Command(s):D:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/MSBuild/15.0/Bin/MSBuild.exe cmTC_e9a8e.vcxproj /p:Configuration=Debug /p:Platform=Win32 /p:VisualStudioVersion=15.0 /v:m && 用于 .NET Framework 的 Microsoft (R) 生成引擎版本 15.9.20+g88f5fadfbe

版权所有(C) Microsoft Corporation。保留所有权利。

  用于 x86 的 Microsoft (R) C/C++ 优化编译器 19.16.27024.1 版

  版权所有(C) Microsoft Corporation。保留所有权利。

  

  cl /c /I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\include" /Zi /W3 /WX- /diagnostics:classic /Od /Ob0 /Oy- /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_e9a8e.dir\Debug\\" /Fd"cmTC_e9a8e.dir\Debug\vc141.pdb" /Gd /TC /analyze- /errorReport:queue D:\LightGBM\Build\CMakeFiles\CMakeTmp\CheckSymbolExists.c

  CheckSymbolExists.c

  

D:\LightGBM\Build\CMakeFiles\CMakeTmp\CheckSymbolExists.c(8): error C2065: “CL_VERSION_2_1”: 未声明的标识符 [D:\LightGBM\Build\CMakeFiles\CMakeTmp\cmTC_e9a8e.vcxproj]

File D:/LightGBM/Build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0/include/CL/cl.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef CL_VERSION_2_1
  return ((int*)(&CL_VERSION_2_1))[argc];
#else
  (void)argc;
  return 0;
#endif
}

Determining if the CL_VERSION_2_0 exist failed with the following output:
Change Dir: D:/LightGBM/Build/CMakeFiles/CMakeTmp

Run Build Command(s):D:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/MSBuild/15.0/Bin/MSBuild.exe cmTC_8dd00.vcxproj /p:Configuration=Debug /p:Platform=Win32 /p:VisualStudioVersion=15.0 /v:m && 用于 .NET Framework 的 Microsoft (R) 生成引擎版本 15.9.20+g88f5fadfbe

版权所有(C) Microsoft Corporation。保留所有权利。

  用于 x86 的 Microsoft (R) C/C++ 优化编译器 19.16.27024.1 版

  版权所有(C) Microsoft Corporation。保留所有权利。

  

  cl /c /I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\include" /Zi /W3 /WX- /diagnostics:classic /Od /Ob0 /Oy- /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_8dd00.dir\Debug\\" /Fd"cmTC_8dd00.dir\Debug\vc141.pdb" /Gd /TC /analyze- /errorReport:queue D:\LightGBM\Build\CMakeFiles\CMakeTmp\CheckSymbolExists.c

  CheckSymbolExists.c

  

D:\LightGBM\Build\CMakeFiles\CMakeTmp\CheckSymbolExists.c(8): error C2065: “CL_VERSION_2_0”: 未声明的标识符 [D:\LightGBM\Build\CMakeFiles\CMakeTmp\cmTC_8dd00.vcxproj]

File D:/LightGBM/Build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0/include/CL/cl.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef CL_VERSION_2_0
  return ((int*)(&CL_VERSION_2_0))[argc];
#else
  (void)argc;
  return 0;
#endif
}

**Comment by StrikerRUS** [comment]
@crazycatii CMake 3.15 is in RC stage now. Try 3.14 version, we have no problems with it.

**Comment by StrikerRUS** [comment]
> Could NOT find Boost (missing: filesystem system) (found suitable version
"1.70.0", minimum required is "1.56.0")

Also, do not forget to specify `Boost` folders according to the installation guide.

**Comment by crazycatii** [comment]
@StrikerRUS thank your answer...but，I have a new problem.

## Problem message：
(tf) D:\LightGBM\Build> cmake -A x64 -DUSE_GPU=1 -DBOOST_ROOT=D:\local\boost_1_70_0 -DBOOST_LIBRARYDIR=C:/local/boost_1_63_0/lib -DOpenCL_LIBRARY="C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0/lib/x64/OpenCL.lib" -DOpenCL_INCLUDE_DIR="C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0/include" ..
-- Building for: Visual Studio 15 2017
-- The C compiler identification is MSVC 19.16.27024.1
-- The CXX compiler identification is MSVC 19.16.27024.1
-- Check for working C compiler: D:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe
-- Check for working C compiler: D:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: D:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe
-- Check for working CXX compiler: D:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenMP_C: -openmp (found version "2.0")
-- Found OpenMP_CXX: -openmp (found version "2.0")
-- Found OpenMP: TRUE (found version "2.0")
-- Looking for CL_VERSION_2_2
-- Looking for CL_VERSION_2_2 - not found
-- Looking for CL_VERSION_2_1
-- Looking for CL_VERSION_2_1 - not found
-- Looking for CL_VERSION_2_0
-- Looking for CL_VERSION_2_0 - not found
-- Looking for CL_VERSION_1_2
-- Looking for CL_VERSION_1_2 - not found
-- Looking for CL_VERSION_1_1
-- Looking for CL_VERSION_1_1 - not found
-- Looking for CL_VERSION_1_0
-- Looking for CL_VERSION_1_0 - not found
-- Found OpenCL: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0/lib/x64/OpenCL.lib
-- OpenCL include directory: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0/include
-- Boost version: 1.70.0
-- Found the following Boost libraries:
--   filesystem
--   system
-- Configuring done
-- Generating done
-- Build files have been written to: D:/LightGBM/Build

(tf) D:\LightGBM\Build>cmake --build . --target ALL_BUILD --config Release
用于 .NET Framework 的 Microsoft (R) 生成引擎版本 15.9.20+g88f5fadfbe
版权所有(C) Microsoft Corporation。保留所有权利。

  Checking Build System
  CMake does not need to re-run because D:/LightGBM/Build/CMakeFiles/generate.stamp is up-to-date.
  Building Custom Rule D:/LightGBM/CMakeLists.txt
  CMake does not need to re-run because D:/LightGBM/Build/CMakeFiles/generate.stamp is up-to-date.
  c_api.cpp
  lightgbm_R.cpp
  application.cpp
  boosting.cpp
  gbdt.cpp
  gbdt_model_text.cpp
  gbdt_prediction.cpp
  prediction_early_stop.cpp
  bin.cpp
  config.cpp
  config_auto.cpp
  dataset.cpp
  dataset_loader.cpp
  file_io.cpp
  json11.cpp
  metadata.cpp
  parser.cpp
  tree.cpp
  dcg_calculator.cpp
  metric.cpp
  linker_topo.cpp
  linkers_mpi.cpp
  linkers_socket.cpp
  network.cpp
  objective_function.cpp
  data_parallel_tree_learner.cpp
  feature_parallel_tree_learner.cpp
  gpu_tree_learner.cpp
  serial_tree_learner.cpp
  tree_learner.cpp
D:\LightGBM\compute\include\boost/compute/cl.hpp(19): fatal error C1083: 无法打开包括文件: “CL/cl.h”: No such file or directory (编译源文件 D:\LightGBM\src\treelearner\data_parallel_tree_learner.cpp) [D:\LightGBM\Build\_lightgbm.vcxproj]
  voting_parallel_tree_learner.cpp
D:\LightGBM\compute\include\boost/compute/cl.hpp(19): fatal error C1083: 无法打开包括文件: “CL/cl.h”: No such file or directory (编译源文件 D:\LightGBM\src\treelearner\feature_parallel_tree_learner.cpp) [D:\LightGBM\Build\_lightgbm.vcxproj]
D:\LightGBM\compute\include\boost/compute/cl.hpp(19): fatal error C1083: 无法打开包括文件: “CL/cl.h”: No such file or directory (编译源文件 D:\LightGBM\src\treelearner\gpu_tree_learner.cpp) [D:\LightGBM\Build\_lightgbm.vcxproj]
D:\LightGBM\compute\include\boost/compute/cl.hpp(19): fatal error C1083: 无法打开包括文件: “CL/cl.h”: No such file or directory (编译源文件 D:\LightGBM\src\treelearner\tree_learner.cpp) [D:\LightGBM\Build\_lightgbm.vcxproj]
D:\LightGBM\compute\include\boost/compute/cl.hpp(19): fatal error C1083: 无法打开包括文件: “CL/cl.h”: No such file or directory (编译源文件 D:\LightGBM\src\treelearner\voting_parallel_tree_learner.cpp) [D:\LightGBM\Build\_lightgbm.vcxproj]
  Building Custom Rule D:/LightGBM/CMakeLists.txt
  CMake does not need to re-run because D:/LightGBM/Build/CMakeFiles/generate.stamp is up-to-date.
  main.cpp
  application.cpp
  boosting.cpp
  gbdt.cpp
  gbdt_model_text.cpp
  gbdt_prediction.cpp
  prediction_early_stop.cpp
  bin.cpp
  config.cpp
  config_auto.cpp
  dataset.cpp
  dataset_loader.cpp
  file_io.cpp
  json11.cpp
  metadata.cpp
  parser.cpp
  tree.cpp
  dcg_calculator.cpp
  metric.cpp
  linker_topo.cpp
  linkers_mpi.cpp
  linkers_socket.cpp
  network.cpp
  objective_function.cpp
  data_parallel_tree_learner.cpp
  feature_parallel_tree_learner.cpp
  gpu_tree_learner.cpp
  serial_tree_learner.cpp
  tree_learner.cpp
D:\LightGBM\compute\include\boost/compute/cl.hpp(19): fatal error C1083: 无法打开包括文件: “CL/cl.h”: No such file or directory (编译源文件 D:\LightGBM\src\treelearner\data_parallel_tree_learner.cpp) [D:\LightGBM\Build\lightgbm.vcxproj]
  voting_parallel_tree_learner.cpp
D:\LightGBM\compute\include\boost/compute/cl.hpp(19): fatal error C1083: 无法打开包括文件: “CL/cl.h”: No such file or directory (编译源文件 D:\LightGBM\src\treelearner\feature_parallel_tree_learner.cpp) [D:\LightGBM\Build\lightgbm.vcxproj]
D:\LightGBM\compute\include\boost/compute/cl.hpp(19): fatal error C1083: 无法打开包括文件: “CL/cl.h”: No such file or directory (编译源文件 D:\LightGBM\src\treelearner\gpu_tree_learner.cpp) [D:\LightGBM\Build\lightgbm.vcxproj]
D:\LightGBM\compute\include\boost/compute/cl.hpp(19): fatal error C1083: 无法打开包括文件: “CL/cl.h”: No such file or directory (编译源文件 D:\LightGBM\src\treelearner\tree_learner.cpp) [D:\LightGBM\Build\lightgbm.vcxproj]
D:\LightGBM\compute\include\boost/compute/cl.hpp(19): fatal error C1083: 无法打开包括文件: “CL/cl.h”: No such file or directory (编译源文件 D:\LightGBM\src\treelearner\voting_parallel_tree_learner.cpp) [D:\LightGBM\Build\lightgbm.vcxproj]

object build fail.....

**Comment by StrikerRUS** [comment]
@crazycatii Don't you forget to clone the repo with `--recursive` flag?

**Comment by crazycatii** [comment]
@StrikerRUS
no……
you can look at my installation procedures.

## Installation step
(tf) D:\LightGBM>git clone --recursive https://github.com/microsoft/LightGBM
Cloning into 'LightGBM'...
remote: Enumerating objects: 39, done.
remote: Counting objects: 100% (39/39), done.
remote: Compressing objects: 100% (29/29), done.
remote: Total 13740 (delta 19), reused 16 (delta 9), pack-reused 13701
Receiving objects: 100% (13740/13740), 9.71 MiB | 17.00 KiB/s, done.
Resolving deltas: 100% (9823/9823), done.
Submodule 'include/boost/compute' (https://github.com/boostorg/compute) registered for path 'compute'
Cloning into 'D:/LightGBM/LightGBM/compute'...
remote: Enumerating objects: 72, done.
remote: Counting objects: 100% (72/72), done.
remote: Compressing objects: 100% (47/47), done.
remote: Total 21728 (delta 30), reused 44 (delta 19), pack-reused 21656
Receiving objects: 100% (21728/21728), 8.53 MiB | 31.00 KiB/s, done.
Resolving deltas: 100% (17550/17550), done.
Submodule path 'compute': checked out '36c89134d4013b2e5e45bc55656a18bd6141995a'

(tf) D:\LightGBM>cd Build

(tf) D:\LightGBM\Build>cmake -A x64 -DUSE_GPU=1 -DBOOST_ROOT=D:\local\boost_1_70_0 -DBOOST_LIBRARYDIR=C:/local/boost_1_63_0/lib -DOpenCL_LIBRARY="C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0/lib/x64/OpenCL.lib" -DOpenCL_INCLUDE_DIR="C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0/include" ..
-- Building for: Visual Studio 15 2017
-- The C compiler identification is MSVC 19.16.27024.1
-- The CXX compiler identification is MSVC 19.16.27024.1
-- Check for working C compiler: D:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe
-- Check for working C compiler: D:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: D:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe
-- Check for working CXX compiler: D:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenMP_C: -openmp (found version "2.0")
-- Found OpenMP_CXX: -openmp (found version "2.0")
-- Found OpenMP: TRUE (found version "2.0")
-- Looking for CL_VERSION_2_2
-- Looking for CL_VERSION_2_2 - not found
-- Looking for CL_VERSION_2_1
-- Looking for CL_VERSION_2_1 - not found
-- Looking for CL_VERSION_2_0
-- Looking for CL_VERSION_2_0 - not found
-- Looking for CL_VERSION_1_2
-- Looking for CL_VERSION_1_2 - not found
-- Looking for CL_VERSION_1_1
-- Looking for CL_VERSION_1_1 - not found
-- Looking for CL_VERSION_1_0
-- Looking for CL_VERSION_1_0 - not found
-- Found OpenCL: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0/lib/x64/OpenCL.lib
-- OpenCL include directory: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0/include
-- Boost version: 1.70.0
-- Found the following Boost libraries:
--   filesystem
--   system
-- Configuring done
-- Generating done
-- Build files have been written to: D:/LightGBM/Build

(tf) D:\LightGBM\Build>cmake --build . --target ALL_BUILD --config Release
用于 .NET Framework 的 Microsoft (R) 生成引擎版本 15.9.20+g88f5fadfbe
版权所有(C) Microsoft Corporation。保留所有权利。

  Checking Build System
  CMake does not need to re-run because D:/LightGBM/Build/CMakeFiles/generate.stamp is up-to-date.
  Building Custom Rule D:/LightGBM/CMakeLists.txt
  CMake does not need to re-run because D:/LightGBM/Build/CMakeFiles/generate.stamp is up-to-date.
  c_api.cpp
  lightgbm_R.cpp
  application.cpp
  boosting.cpp
  gbdt.cpp
  gbdt_model_text.cpp
  gbdt_prediction.cpp
  prediction_early_stop.cpp
  bin.cpp
  config.cpp
  config_auto.cpp
  dataset.cpp
  dataset_loader.cpp
  file_io.cpp
  json11.cpp
  metadata.cpp
  parser.cpp
  tree.cpp
  dcg_calculator.cpp
  metric.cpp
  linker_topo.cpp
  linkers_mpi.cpp
  linkers_socket.cpp
  network.cpp
  objective_function.cpp
  data_parallel_tree_learner.cpp
  feature_parallel_tree_learner.cpp
  gpu_tree_learner.cpp
  serial_tree_learner.cpp
  tree_learner.cpp
D:\LightGBM\compute\include\boost/compute/cl.hpp(19): fatal error C1083: 无法打开包括文件: “CL/cl.h”: No such file or directory
 (编译源文件 D:\LightGBM\src\treelearner\data_parallel_tree_learner.cpp) [D:\LightGBM\Build\_lightgbm.vcxproj]
  voting_parallel_tree_learner.cpp
D:\LightGBM\compute\include\boost/compute/cl.hpp(19): fatal error C1083: 无法打开包括文件: “CL/cl.h”: No such file or directory
 (编译源文件 D:\LightGBM\src\treelearner\gpu_tree_learner.cpp) [D:\LightGBM\Build\_lightgbm.vcxproj]
D:\LightGBM\compute\include\boost/compute/cl.hpp(19): fatal error C1083: 无法打开包括文件: “CL/cl.h”: No such file or directory
 (编译源文件 D:\LightGBM\src\treelearner\feature_parallel_tree_learner.cpp) [D:\LightGBM\Build\_lightgbm.vcxproj]
D:\LightGBM\compute\include\boost/compute/cl.hpp(19): fatal error C1083: 无法打开包括文件: “CL/cl.h”: No such file or directory
 (编译源文件 D:\LightGBM\src\treelearner\tree_learner.cpp) [D:\LightGBM\Build\_lightgbm.vcxproj]
D:\LightGBM\compute\include\boost/compute/cl.hpp(19): fatal error C1083: 无法打开包括文件: “CL/cl.h”: No such file or directory
 (编译源文件 D:\LightGBM\src\treelearner\voting_parallel_tree_learner.cpp) [D:\LightGBM\Build\_lightgbm.vcxproj]
  Building Custom Rule D:/LightGBM/CMakeLists.txt
  CMake does not need to re-run because D:/LightGBM/Build/CMakeFiles/generate.stamp is up-to-date.
  main.cpp
  application.cpp
  boosting.cpp
  gbdt.cpp
  gbdt_model_text.cpp
  gbdt_prediction.cpp
  prediction_early_stop.cpp
  bin.cpp
  config.cpp
  config_auto.cpp
  dataset.cpp
  dataset_loader.cpp
  file_io.cpp
  json11.cpp
  metadata.cpp
  parser.cpp
  tree.cpp
  dcg_calculator.cpp
  metric.cpp
  linker_topo.cpp
  linkers_mpi.cpp
  linkers_socket.cpp
  network.cpp
  objective_function.cpp
  data_parallel_tree_learner.cpp
  feature_parallel_tree_learner.cpp
  gpu_tree_learner.cpp
  serial_tree_learner.cpp
  tree_learner.cpp
D:\LightGBM\compute\include\boost/compute/cl.hpp(19): fatal error C1083: 无法打开包括文件: “CL/cl.h”: No such file or directory
 (编译源文件 D:\LightGBM\src\treelearner\data_parallel_tree_learner.cpp) [D:\LightGBM\Build\lightgbm.vcxproj]
  voting_parallel_tree_learner.cpp
D:\LightGBM\compute\include\boost/compute/cl.hpp(19): fatal error C1083: 无法打开包括文件: “CL/cl.h”: No such file or directory
 (编译源文件 D:\LightGBM\src\treelearner\feature_parallel_tree_learner.cpp) [D:\LightGBM\Build\lightgbm.vcxproj]
D:\LightGBM\compute\include\boost/compute/cl.hpp(19): fatal error C1083: 无法打开包括文件: “CL/cl.h”: No such file or directory
 (编译源文件 D:\LightGBM\src\treelearner\gpu_tree_learner.cpp) [D:\LightGBM\Build\lightgbm.vcxproj]
D:\LightGBM\compute\include\boost/compute/cl.hpp(19): fatal error C1083: 无法打开包括文件: “CL/cl.h”: No such file or directory
 (编译源文件 D:\LightGBM\src\treelearner\tree_learner.cpp) [D:\LightGBM\Build\lightgbm.vcxproj]
D:\LightGBM\compute\include\boost/compute/cl.hpp(19): fatal error C1083: 无法打开包括文件: “CL/cl.h”: No such file or directory
 (编译源文件 D:\LightGBM\src\treelearner\voting_parallel_tree_learner.cpp) [D:\LightGBM\Build\lightgbm.vcxproj]

**Comment by crazycatii** [comment]
@StrikerRUS Major error messages is：
D:\LightGBM\compute\include\boost/compute/cl.hpp(19): fatal error C1083
“CL/cl.h”: No such file or directory

**Comment by StrikerRUS** [comment]
@crazycatii I see. CMake cannot find OpenCL: 
```
-- Looking for CL_VERSION_2_2
-- Looking for CL_VERSION_2_2 - not found
-- Looking for CL_VERSION_2_1
-- Looking for CL_VERSION_2_1 - not found
-- Looking for CL_VERSION_2_0
-- Looking for CL_VERSION_2_0 - not found
-- Looking for CL_VERSION_1_2
-- Looking for CL_VERSION_1_2 - not found
-- Looking for CL_VERSION_1_1
-- Looking for CL_VERSION_1_1 - not found
-- Looking for CL_VERSION_1_0
-- Looking for CL_VERSION_1_0 - not found
```


Double check paths you pass to CMake. This may help you: #2096.

**Comment by crazycatii** [comment]
@StrikerRUS  Aha，it's working!
thanks for your help！

**Comment by StrikerRUS** [comment]
@crazycatii Glad that your problem has been solved! 🎉
