### ISSUE TITLE
Change FAQs in docs so we can link to individual questions

### ISSUE THREAD

**Issue by jameslamb** [microsoft/LightGBM#2268]
While helping out with #2267 tonight, I wanted to link to a very specific question [in our FAQs](https://lightgbm.readthedocs.io/en/latest/FAQ.html). However, because they're set up as a bulleted list, they can't be linked to.

Changing the questions to header-3s or header-4s will create hyperlinks! To do this in `sphinx`, one could go into [the FAQ rst file](https://github.com/microsoft/LightGBM/blob/master/docs/FAQ.rst) and change stuff like this:

```
**Question 4**: I am using Windows. Should I use Visual Studio or MinGW for compiling LightGBM?
```

into something like

```
I am using Windows. Should I use Visual Studio or MinGW for compiling LightGBM?
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
```

I would also recommend removing the "Question 1", "Question 2", etc. numbering, as I don't think it's providing any value.

**Comment by StrikerRUS** [comment]
> I would also recommend removing the "Question 1", "Question 2", etc. numbering, as I don't think it's providing any value.

It's better to leave numbering for "backward compatibility", because in previous issues we have many refs to FAQ with words like "See Question 4 and 8", or "Refer to FAQ Question 9".

**Comment by hayesall** [comment]
#2272 should probably to be merged before addressing this issue (at least to avoid merge conflicts and different formatting).

I made local changes to address this issue, and can open a pull request soon:

<img width="1267" alt="Screen Shot 2019-07-27 at 1 07 45 PM" src="https://user-images.githubusercontent.com/11916674/61997464-c2594700-b06f-11e9-8bf7-7fd1495ba233.png">

**Comment by jameslamb** [comment]
> > I would also recommend removing the "Question 1", "Question 2", etc. numbering, as I don't think it's providing any value.
> 
> It's better to leave numbering for "backward compatibility", because in previous issues we have many refs to FAQ with words like "See Question 4 and 8", or "Refer to FAQ Question 9".

Does "previous issues" mean things that we control in this repo? If so, having hyperlinks means we could change those to point to the actual FAQs. If it's only things in this repo that we control, I would be willing to do the work to change them.

**Comment by StrikerRUS** [comment]
@jameslamb I'm 100% sure only about that we have such links in the repo. And for them, I think we as collaborators have enough permissions to edit old (even not own) comments. But what about third-party sites? I don't know, maybe you can google whether other sites refer to our FAQ. But I guess it's bad idea.

We had the similar problem some time ago, when I moved Wiki content to RTD docs. That's why we still have the following: 

https://github.com/microsoft/LightGBM/pull/945#issuecomment-333433300

![image](https://user-images.githubusercontent.com/25141164/62000369-fff4b900-b0dd-11e9-8b06-6bca55461f49.png)

**Comment by StrikerRUS** [comment]
@jameslamb I think that numbered list in @hayesall's preview is very good compromise: it's not so "heavy" as current `Question #` and preserves numeration.
