### ISSUE TITLE
categorical with high levels

### ISSUE THREAD

**Issue by geoHeil** [Microsoft/LightGBM#227]
When running lightgbm with support for categorical variables I see the following warning
`[LightGBM] [Warning] Too many categoricals are ignored,                    please use bigger max_bin or partition this column` it would be great if lightgbm would tell me the name of the problematic column.

**Comment by guolinke** [comment]
@geoHeil OK, i think I can add this kind of warning.

**Comment by guolinke** [comment]
fixed in latest version.
