### ISSUE TITLE
Sklearn cross_val_predict failing (IndexError: index 1 is out of bounds for axis 1 with size 1) 

### ISSUE THREAD

**Issue by MotoRZR** [microsoft/LightGBM#2276]
This is a cross post from the Sklearn github repository.  It was suggested the issue should be opened here rather than there and it was suggested LightGBM doesn't meet the check_estimator test.  I'm running LightGBM 2.2.4

https://github.com/scikit-learn/scikit-learn/issues/14429

#### Description
I'm currently getting the above message when running cross_val_predict.  This was working correctly as at 20.2 but I've recently needed to reinstall an now have the latest version of sklearn.  

I'm running a LightGBM model and attempting to get cross validated predictions.

The traceback first indicates a fail when _enforce_prediction_order is called.  When I comment out this code below (from validation.py), it works as expected (appreciate this is just a temporary patch as I'm not sure what causes this issue).

```
    if method in ['decision_function', 'predict_proba', 'predict_log_proba']:
        pass
        #if isinstance(predictions, list):
        #    predictions = [_enforce_prediction_order(
        #        estimator.classes_[i_label], predictions[i_label],
        #        n_classes=len(set(y[:, i_label])), method=method)
        #        for i_label in range(len(predictions))]
        #else:
        #    # A 2D y array should be a binary label indicator matrix
        #    n_classes = len(set(y)) if y.ndim == 1 else y.shape[1]
        #    predictions = _enforce_prediction_order(
        #        estimator.classes_, predictions, n_classes, method)
    return predictions, test
```

#### Steps/Code to Reproduce
```
nfolds = 5
kfold = GroupKFold(n_splits=5)

lgbm_params = {'max_depth': 7, 
               'num_leaves': 45, 
               'min_data_in_leaf': 150, 
               'feature_fraction': 0.75 
               'lambda_l2': 10, 
               'bagging_fraction': 0.5, 
               'boosting_type': 'gbdt', 
               'objective': 'binary', 
               'random_seed': 0, 
               'num_boost_round': 1000, 
               'learning_rate': 0.05}

lgbm_model = LGBMClassifier(**lgbm_params)

cv_predictions = cross_val_predict(lgbm_model, train2,train_target2,cv=kfold.split(train2,train_target2.values,account_grouping2.values),
                                              verbose=10, method='predict_proba',n_jobs=1)
```

#### Expected Results
No error thrown

#### Actual Results

> ---------------------------------------------------------------------------

> IndexError                                Traceback (most recent call last)
> <ipython-input-17-e6e89ae59650> in <module>
>       1 cv_predictions = cross_val_predict(lgbm_model, train2,train_target2,cv=kfold.split(train2,train_target2.values,account_grouping2.values),
> ----> 2                                               verbose=10, method='predict_proba',n_jobs=1)
> 
> ~\AppData\Local\Continuum\miniconda3\envs\testenv\lib\site-packages\sklearn\model_selection\_validation.py in cross_val_predict(estimator, X, y, groups, cv, n_jobs, verbose, fit_params, pre_dispatch, method)
>     778     prediction_blocks = parallel(delayed(_fit_and_predict)(
>     779         clone(estimator), X, y, train, test, verbose, fit_params, method)
> --> 780         for train, test in cv.split(X, y, groups))
>     781 
>     782     # Concatenate the predictions
> 
> ~\AppData\Local\Continuum\miniconda3\envs\testenv\lib\site-packages\joblib\parallel.py in __call__(self, iterable)
>     919             # remaining jobs.
>     920             self._iterating = False
> --> 921             if self.dispatch_one_batch(iterator):
>     922                 self._iterating = self._original_iterator is not None
>     923 
> 
> ~\AppData\Local\Continuum\miniconda3\envs\testenv\lib\site-packages\joblib\parallel.py in dispatch_one_batch(self, iterator)
>     757                 return False
>     758             else:
> --> 759                 self._dispatch(tasks)
>     760                 return True
>     761 
> 
> ~\AppData\Local\Continuum\miniconda3\envs\testenv\lib\site-packages\joblib\parallel.py in _dispatch(self, batch)
>     714         with self._lock:
>     715             job_idx = len(self._jobs)
> --> 716             job = self._backend.apply_async(batch, callback=cb)
>     717             # A job can complete so quickly than its callback is
>     718             # called before we get here, causing self._jobs to
> 
> ~\AppData\Local\Continuum\miniconda3\envs\testenv\lib\site-packages\joblib\_parallel_backends.py in apply_async(self, func, callback)
>     180     def apply_async(self, func, callback=None):
>     181         """Schedule a func to be run"""
> --> 182         result = ImmediateResult(func)
>     183         if callback:
>     184             callback(result)
> 
> ~\AppData\Local\Continuum\miniconda3\envs\testenv\lib\site-packages\joblib\_parallel_backends.py in __init__(self, batch)
>     547         # Don't delay the application, to avoid keeping the input
>     548         # arguments in memory
> --> 549         self.results = batch()
>     550 
>     551     def get(self):
> 
> ~\AppData\Local\Continuum\miniconda3\envs\testenv\lib\site-packages\joblib\parallel.py in __call__(self)
>     223         with parallel_backend(self._backend, n_jobs=self._n_jobs):
>     224             return [func(*args, **kwargs)
> --> 225                     for func, args, kwargs in self.items]
>     226 
>     227     def __len__(self):
> 
> ~\AppData\Local\Continuum\miniconda3\envs\testenv\lib\site-packages\joblib\parallel.py in <listcomp>(.0)
>     223         with parallel_backend(self._backend, n_jobs=self._n_jobs):
>     224             return [func(*args, **kwargs)
> --> 225                     for func, args, kwargs in self.items]
>     226 
>     227     def __len__(self):
> 
> ~\AppData\Local\Continuum\miniconda3\envs\testenv\lib\site-packages\sklearn\model_selection\_validation.py in _fit_and_predict(estimator, X, y, train, test, verbose, fit_params, method)
>     879             n_classes = len(set(y)) if y.ndim == 1 else y.shape[1]
>     880             predictions = _enforce_prediction_order(
> --> 881                 estimator.classes_, predictions, n_classes, method)
>     882     return predictions, test
>     883 
> 
> ~\AppData\Local\Continuum\miniconda3\envs\testenv\lib\site-packages\sklearn\model_selection\_validation.py in _enforce_prediction_order(classes, predictions, n_classes, method)
>     935                                               default_values[method],
>     936                                               dtype=predictions.dtype)
> --> 937         predictions_for_all_classes[:, classes] = predictions
>     938         predictions = predictions_for_all_classes
>     939     return predictions
> 
> IndexError: index 1 is out of bounds for axis 1 with size 1

#### Versions

> Could not locate executable g77
> Could not locate executable f77
> Could not locate executable ifort
> Could not locate executable ifl
> Could not locate executable f90
> Could not locate executable DF
> Could not locate executable efl
> Could not locate executable gfortran
> Could not locate executable f95
> Could not locate executable g95
> Could not locate executable efort
> Could not locate executable efc
> Could not locate executable flang
> don't know how to compile Fortran code on platform 'nt'
> 
> System:
>     python: 3.7.3 (default, Apr 24 2019, 15:29:51) [MSC v.1915 64 bit (AMD64)]
> executable: C:\Users\emarcano\AppData\Local\Continuum\miniconda3\envs\testenv\python.exe
>    machine: Windows-10-10.0.17763-SP0
> 
> BLAS:
>     macros: 
>   lib_dirs: 
> cblas_libs: cblas
> 
> Python deps:
>        pip: 19.1.1
> setuptools: 41.0.1
>    sklearn: 0.21.2
>      numpy: 1.16.4
>      scipy: 1.2.1
>     Cython: None
>     pandas: 0.24.2

**Comment by StrikerRUS** [comment]
> It was suggested the issue should be opened here rather than there and it was suggested LightGBM doesn't meet the check_estimator test. 

Actually it does:
https://github.com/microsoft/LightGBM/blob/7189743d224a405bb48050834460d107fb7c1c0b/tests/python_package_test/test_sklearn.py#L200-L216

I'll take a look, when have time. Is this data-dependent issue?

**Comment by MotoRZR** [comment]
I don't believe this is a LightGBM issue as discussed here, 

https://github.com/scikit-learn/scikit-learn/issues/14429#issuecomment-513887163

so closing this.  Thanks.

**Comment by StrikerRUS** [comment]
@MotoRZR Thanks for letting us know! Please ping me if any updates from LightGBM side will be needed.
