### ISSUE TITLE
Unknown parameter metric warning

### ISSUE THREAD

**Issue by EgriSzabi** [microsoft/LightGBM#2284]
LightGBM version or commit hash:   v2.2.3

## Error message
[LightGBM] [Warning] Unknown parameter metric=

## Steps to reproduce

During the training I get the error message mentioned above, the program runs and makes some decently accurate predictions, but it's not perfect and I believe it has to do something with that error. I suspect the error should be at the pipeline building part although the error message comes during model training and it is only displayed in console.

` public static IEstimator<ITransformer> BuildTrainingPipeline(MLContext context)
        {
            Console.WriteLine("=============== Creating pipeline ===============");
            var pipeline = context.Transforms.Conversion.MapValueToKey("Label")
                    .Append(context.Transforms.Concatenate("Features", new[] { nameof(DocsData.Left), nameof(DocsData.Top) }));

            var trainer = context.MulticlassClassification.Trainers.LightGbm("Label", "Features")
                .Append(context.Transforms.Conversion.MapKeyToValue("PredictedLabel"));
            IEstimator<ITransformer> trainingPipeLine = pipeline.Append(trainer);
            Console.WriteLine("=============== Pipeline created ===============");
            return trainingPipeLine;
        }

 public static ITransformer TrainModel(MLContext context, IDataView trainingDataView, IEstimator<ITransformer> trainingPipeline)
        {
            Console.WriteLine("=============== Training  model ===============");

            ITransformer model = trainingPipeline.Fit(trainingDataView);

            Console.WriteLine("=============== End of training process ===============");
            return model;
        }`

**Comment by StrikerRUS** [comment]
@EgriSzabi `metric` is a valid parameter: https://lightgbm.readthedocs.io/en/latest/Parameters.html#metric, but logs from your code indicates that the param which comes to cpp side is `metric=`. Unfortunately, we do not maintain C# wrapper. Please open the issue in https://github.com/dotnet/machinelearning repo.

**Comment by StrikerRUS** [comment]
Just found the following: https://github.com/dotnet/machinelearning/pull/4007.
