### ISSUE TITLE
Sklearn  GridSearchCV with categorical_feature ,  not work

### ISSUE THREAD

**Issue by oras903** [microsoft/LightGBM#2288]
My code is  that :  
  
model_lgb = LGBMClassifier(boosting_type='gbdt',objective='binary',learning_rate=0.1,num_leaves =30, max_depth =5,subsample = 0.8,colsample_bytree = 0.8,bagging_fraction = 0.8,feature_fraction = 0.8,is_unbalance = 'True')

params_test ={'n_estimators': range(10,110,10),
              'categorical_feature': ['0,13,17']}

gsearch = GridSearchCV(estimator=model_lgb, param_grid=params_test, scoring='neg_log_loss', cv=5, verbose=1, n_jobs=4)
gs_results = gsearch.fit(x,y)

**I get the warning : “categorical_feature   keyword has been found in `params` and will be ignored. Please use categorical_feature argument of the Dataset constructor to pass this parameter.”**

**Comment by StrikerRUS** [comment]
Try
```
params_test ={'n_estimators': range(10, 110, 10),
              'cat_column': ['0','13','17']}
```
