### ISSUE TITLE
Handling of missing data in production

### ISSUE THREAD

**Issue by nicolaiiversen92** [microsoft/LightGBM#2292]
Hi.

I'm using a lightgbm classifier that is about to be deployed in production.
Therefore, I would like to know how lgbm handles missing values in columns that did not contain missingness during traning? 
I can only find information of how it handles missingness in columns that contained missingness throghout training.

**Comment by guolinke** [comment]
Where there are no missing values in training data, the NaN in test data will always go the right child.
refer to the code:
https://github.com/microsoft/LightGBM/blob/6c210209fbe4694af613bca405fa5de72f10d72a/include/LightGBM/tree.h#L221-L241

the missing type is 0 in your case.
