### ISSUE TITLE
sklearn_examples.py runs error in python. 

### ISSUE THREAD

**Issue by linrio** [Microsoft/LightGBM#230]
[](For bugs and unexpected issues, please provide the following information, so that we could reproduce in our system)

## Environment info
Operating System: Win64
CPU: intel core i5

## Error Message:
D:\Program Files (x86)\Anaconda\setup\anaconda\lib\site-packages\pandas\core\frame.py:2834: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  **kwargs)

## Steps to reproduce

1. After change the build config to **DLL** ,  I run the sklearn_examples.py by `python sklearn_examples.py` . Then I get back above error message.
2. The other examples is normal, such as `simple_examples.py` , `advanced_examples.py`

## the complete results  : 
`
"D:\Program Files (x86)\Anaconda\setup\anaconda\python.exe" G:/codes/python/Microsoft/LightGBM/examples/python-guide/sklearn_example.py
Load data...
Start training...
[1]	valid_0's l1: 0.536072
Train until valid scores didn't improve in 5 rounds.
[2]	valid_0's l1: 0.528484
[3]	valid_0's l1: 0.521163
[4]	valid_0's l1: 0.514374
[5]	valid_0's l1: 0.508836
[6]	valid_0's l1: 0.502996
[7]	valid_0's l1: 0.497912
[8]	valid_0's l1: 0.492616
[9]	valid_0's l1: 0.487243
[10]	valid_0's l1: 0.482528
[11]	valid_0's l1: 0.478176
[12]	valid_0's l1: 0.473355
[13]	valid_0's l1: 0.469354
[14]	valid_0's l1: 0.465396
[15]	valid_0's l1: 0.46168
[16]	valid_0's l1: 0.45808
[17]	valid_0's l1: 0.454562
[18]	valid_0's l1: 0.451392
[19]	valid_0's l1: 0.448304
[20]	valid_0's l1: 0.445538
Start predicting...
('The rmse of prediction is:', 0.49226770162247319)
Calculate feature importances...
('Feature importances:', [0.038333334, 0.015, 0.0033333334, 0.061666667, 0.0066666668, 0.10166667, 0.025, 0.0033333334, 0.0, 0.031666666, 0.0049999999, 0.0083333338, 0.0016666667, 0.036666665, 0.013333334, 0.0066666668, 0.0016666667, 0.015, 0.0, 0.0083333338, 0.0, 0.053333335, 0.094999999, 0.0066666668, 0.086666666, 0.15666667, 0.086666666, 0.13166666])
D:\Program Files (x86)\Anaconda\setup\anaconda\lib\site-packages\pandas\core\frame.py:2834: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  **kwargs)
('Best parameters found by grid search are:', {'n_estimators': 40, 'learning_rate': 0.1})

Process finished with exit code 0
`

**Comment by wxchan** [comment]
Warning is not error. Just ignore it. I will fix it later.

**Comment by linrio** [comment]
@wxchan Tks! Expecting a better version
