### ISSUE TITLE
init score does not work as expected

### ISSUE THREAD

**Issue by chtx900326** [microsoft/LightGBM#2301]
## Environment info

Operating System: Windows 7

CPU/GPU model: Intel i7

C++/Python/R version: Python 3.6

LightGBM version or commit hash: 2.2.3

## Problem description

I tried to assign the init score when fitting the lightgbm model, but I found the results were unexpected. 

First I ran lightgbm once to get the predictions. Then I used the score from first lightgbm model as the init score to the second lightgbm model (exactly the same model except for init score). However, the second model gives worse mse than the first model.

In this case, it seems to me that the second model is just like a continuation of the first model. So I double the "n_estimators" of the first model. However, I cannot reproduce the numbers. 

I just wonder why the second model with init scores has worse mse, and which hyperparameters should I change to produce similar results.

```python
model1 = LGBMRegressor(max_depth=3, n_estimators=200, silent=True, num_leaves=6,
                      subsample=0.8, colsample_bytree=1, n_jobs=2,
                      objective='regression', learning_rate=0.01, random_state=0)
model1.fit(X_train, y_train)
yhat1 = model1.predict(X_train)
y_score = model1.predict(X_train, raw_score=True)

model2 = model1
model2.fit(X_train, y_train, init_score=y_score)  # the only difference from model 1
yhat2 = model2.predict(X_train)

model3 = LGBMRegressor(max_depth=3, n_estimators=400, silent=True, num_leaves=6,
                      subsample=0.8, colsample_bytree=1, n_jobs=2,
                      objective='regression', learning_rate=0.01, random_state=0)  # double n_estimators
model3.fit(X_train, y_train)
yhat3 = model3.predict(X_train)

# eval
print('The mse of model 1 is:', mean_squared_error(y_train, yhat1))  # 0.93
print('The mse of model 2 is:', mean_squared_error(y_train, yhat2))  # 0.95 does not make sense because higher than 0.93
print('The mse of model 3 is:', mean_squared_error(y_train, yhat3))  # 0.92 makes sense because lower than 0.93
```

**Comment by guolinke** [comment]
You should add the init_score to your predictions. The prediction only produce the outputs of trees.

**Comment by chtx900326** [comment]
Thank you for the explanation. I got the same results for model 2 and model 3 after adding init_score to the predictions.
