### ISSUE TITLE
When will v2.2.4 be released?

### ISSUE THREAD

**Issue by vishalbajaj2000** [microsoft/LightGBM#2312]
Release date?

**Comment by hayesall** [comment]
#2138 is probably relevant to this. There are a couple open checkboxes on the list.

**Comment by StrikerRUS** [comment]
@vishalbajaj2000 Keep eye on #2138. We need to merge #2209 firstly.

**Comment by vishalbajaj2000** [comment]
Thank you for the prompt update @hayesall and @StrikerRUS !
