### ISSUE TITLE
Python-LightGBM compiled for GPU crashes

### ISSUE THREAD

**Issue by Gerenuk** [microsoft/LightGBM#2313]
(I've seen that this is specific to the Python package. The CLI version works fine with GPU. Is it possible that it accesses Anaconda libraries which are incompatible and how can I detect that?)

(I've realized I can avoid the bug with num_threads=1. Any other value produces segmentation fault.)

I've installed LightGBM 2.2.3 on Manjaro Linux, Python 3.7, nvidia gpu and generally new versions of libraries with `pip install lightgbm --install-option=--gpu` (I also tried from github). The installations seems to work, but when I run the training, it starts, the RAM usage goes up, and after a while I get a segmentation fault.

The only message I can see is something like

    double free or corruption (out)

or sometimes

    malloc(): unsorted double linked list corrupted

or

    malloc(): invalid size (unsorted)

How can I proceed or get more information?

This also happens when I start the training without GPU mode.

Here is the line trace just before segmentation fault, but I do not know trace and not sure if it's just cut off.

The same happens for float32 data types. The number of shown trace lines varies, but it always crashes after the `ptr_data = ...` line.

```
basic.py(820):         if isinstance(data, string_type):
basic.py(827):         elif isinstance(data, scipy.sparse.csr_matrix):
basic.py(829):         elif isinstance(data, scipy.sparse.csc_matrix):
basic.py(831):         elif isinstance(data, np.ndarray):
basic.py(832):             self.__init_from_np2d(data, params_str, ref_dataset)
 --- modulename: basic, funcname: __init_from_np2d
basic.py(864):         if len(mat.shape) != 2:
basic.py(867):         self.handle = ctypes.c_void_p()
basic.py(868):         if mat.dtype == np.float32 or mat.dtype == np.float64:
basic.py(869):             data = np.array(mat.reshape(mat.size), dtype=mat.dtype, copy=False)
basic.py(874):         ptr_data, type_ptr_data, _ = c_float_array(data)
 --- modulename: basic, funcname: c_float_array
basic.py(215):     if is_1d_list(data):
 --- modulename: basic, funcname: is_1d_list
basic.py(68):     return isinstance(data, list) and (not data or is_numeric(data[0]))
basic.py(217):     if is_numpy_1d_array(data):
 --- modulename: basic, funcname: is_numpy_1d_array
basic.py(63):     return isinstance(data, np.ndarray) and len(data.shape) == 1
basic.py(218):         data = convert_from_sliced_object(data)
 --- modulename: basic, funcname: convert_from_sliced_object
basic.py(205):     if data.base is not None and isinstance(data, np.ndarray) and isinstance(data.base, np.ndarray):
basic.py(206):         if not data.flags.c_contiguous:
basic.py(210):     return data
basic.py(219):         assert data.flags.c_contiguous
basic.py(220):         if data.dtype == np.float32:
basic.py(223):         elif data.dtype == np.float64:
basic.py(224):             ptr_data = data.ctypes.data_as(ctypes.POINTER(ctypes.c_double))
 --- modulename: _internal, funcname: __init__
_internal.py(290):         self._arr = array
_internal.py(292):         if ctypes:
_internal.py(293):             self._ctypes = ctypes
_internal.py(295):             self._data = _get_void_ptr(array)
 --- modulename: _internal, funcname: _get_void_ptr
_internal.py(276):     import numpy as np
_internal.py(279):     simple_arr = np.asarray(_unsafe_first_element_pointer(arr))
 --- modulename: _internal, funcname: __init__
_internal.py(258):         self.base = arr
 --- modulename: numeric, funcname: asarray
numeric.py(538):     return array(a, dtype, copy=False, order=order)
 --- modulename: _internal, funcname: __array_interface__
```

**Comment by StrikerRUS** [comment]
@Gerenuk Have read this https://github.com/microsoft/LightGBM/tree/master/python-package#build-gpu-version? Very often, you need to pass additional options to `pip` command with OpenCL paths.

Also, please provide add `-v` option to `pip` with the aim to get verbose installation and paste the log here. And of course, we need logs from your failed training process.

**Comment by Gerenuk** [comment]
@StrikerRUS Yes, I also did try passing OpenCL paths. Either way the logs seem to indicate that it happily finds everything.

**Comment by Gerenuk** [comment]
I've updated the description. It now shows the line trace and the observation that segmentation fault happens for num_threads>1 only.

**Comment by StrikerRUS** [comment]
@Gerenuk It's quite hard to be 100% sure without the reproducible example and full backtrace, but my assumption is that it's due to broken `numpy` package in your conda environment. To be more precise, with `mkl` library, which is `numpy`'s dependency. I would recommend create new clean conda environment and install only required packages (and install `lightgbm` without `gpu` option to confirm that this is not GPU-related problem).

**Comment by Gerenuk** [comment]
@StrikerRUS With a completely fresh installation of LightGBM there is still the same bug. And without gpu compilation it works normally.

**Comment by Gerenuk** [comment]
@StrikerRUS It turns out it works it works when I remove MKL. I have a AMD CPU btw. Interestingly everything else worked so far (e.g. XGBoost GPU).

Maybe a note in the FAQ would be good, because for a casual user Anaconda comes with MKL by default and you have no idea. It seems you have to install Miniconda and do `conda install nomkl` first if you have an AMD CPU.

**Comment by StrikerRUS** [comment]
@Gerenuk Nice to hear that your problem has been solved!

We already have a note about the `mkl` from conda in our FAQ: https://lightgbm.readthedocs.io/en/latest/FAQ.html#lightgbm-crashes-randomly-with-the-error-like-initializing-libiomp5-dylib-but-found-libomp-dylib-already-initialized
