### ISSUE TITLE
Feature request: colsample by node

### ISSUE THREAD

**Issue by BlindApe** [microsoft/LightGBM#2315]
My experience with xgboost is adding colsample_bynode to colsample_bytree improves a lot the performance with high noise / low signal datasets.

Time ago, in #98 issue @guolinke said about the inclusion of colsample_bylevel:
https://github.com/microsoft/LightGBM/issues/98#issuecomment-263532581

Indeed I think the easiest way to do it is calculating the histogram as now (for all the features of the current tree) but then picking random a subset of features and only check the reduction for these features.

In this way the histogram computing will remains exactly as now and only a random selection of features is needed at node level.

**Comment by guolinke** [comment]
cool idea!

**Comment by StrikerRUS** [comment]
Closed via #2330.
