### ISSUE TITLE
@joseortiz3, @StrikerRUS, @huanzhang12

### ISSUE THREAD

**Issue by Untoha2** [microsoft/LightGBM#2317]
Problem with pip install of lightgbm gpu
@joseortiz3, @StrikerRUS, @huanzhang12 
Hello, I understand that the issue is quite outdated, but I've faced it. I've followed [the guide](https://github.com/Microsoft/LightGBM/blob/master/docs/Installation-Guide.rst#build-gpu-version) and managed to build boost with cmake and Visual Studio 2019 (I've tried various versions of boost: at least those that are in the attached guide), but I always get the same error. I would be so thankful if somebody explains to me what is the problem. I attach screenshots with cmake configurations and with the error. I have windows 10 x64.
![Screenshot_3](https://user-images.githubusercontent.com/53869544/62694594-54047500-b9dd-11e9-8d0b-41b7df78dab2.png)
![Screenshot_7](https://user-images.githubusercontent.com/53869544/62694660-772f2480-b9dd-11e9-8507-ad5e099efe0d.png)

_Originally posted by @Untoha2 in https://github.com/microsoft/LightGBM/issues/1121#issuecomment-519457231_

**Comment by StrikerRUS** [comment]
Refer to https://github.com/microsoft/LightGBM/issues/1121#issuecomment-519655436.
