### ISSUE TITLE
R - Precision Recall Curve as a Custom Metric

### ISSUE THREAD

**Issue by dragie** [microsoft/LightGBM#2323]
## Environment info

Operating System: Linux

CPU/GPU model: GPU

C++/Python/R version: R

LightGBM version or commit hash: 2.2.4

## Question

I am trying to create a custom eval metric function in R. I want to use Precision Recall Curve instead of AUC. Can someone help to create that?

**Comment by jameslamb** [comment]
Thanks for opening this @dragie ! I will look at the relevant part of the R package and get back to you in a day or two.

**Comment by StrikerRUS** [comment]
@dragie I think you can use [`PRROC` package](https://cran.r-project.org/web/packages/PRROC/index.html). It's [the highest voted answer at CrossValidated](https://stats.stackexchange.com/a/226972). or you can simply take the needed part of computations to your code from [its' sources](https://github.com/cran/PRROC/blob/master/R/PRROC.R).
