### ISSUE TITLE
a question about calculating delta ndcg

### ISSUE THREAD

**Issue by 12301098-Heminghui** [microsoft/LightGBM#2326]
The source code in the project is as below
![image](https://user-images.githubusercontent.com/11437820/62944136-a515ce00-be0e-11e9-93d5-9737cf5431cf.png)
but i think the right calculation is like
![image](https://user-images.githubusercontent.com/11437820/62944270-e0b09800-be0e-11e9-89e3-3cd3fbb6c24c.png)

**Comment by sbruch** [comment]
The calculation in the code is correct. Denoting gain by G(.), discount by D(.), and rank of a document in the list sorted by scores by rank_:

NDCG of the list where documents are sorted by scores has these two terms: G(m)/D(rank_m) + G(n)/D(rank_n)
NDCG after swapping documents m and n has these two terms: G(n)/D(rank_m) + G(m)/D(rank_n)

So the difference is of the following form:

G(m) * (1/D(rank_m) - 1/D(rank_n)) + G(n) * (1/D(rank_n) - 1/D(rank_m))
= [G(m) - G(n)] * [1/D(rank_m) - 1/D(rank_n)],

which is then multiplied by inverse max DCG.
