### ISSUE TITLE
Code Refactoring

### ISSUE THREAD

**Issue by guolinke** [microsoft/LightGBM#2341]
Thanks to the active community, LightGBM receives many PRs for the new features.
Consequently, some codes become missing the readability and maintainability, for the coupling of many different functions.
For the convenience of future developments and friendliness for new users, I would like to have a code refactoring.

ping @chivee  @StrikerRUS @jameslamb @Laurae2 @huanzhang12 @henry0312 

you can add the files, which you think needs to refactor, to this issue.

- [x] Cost efficient gradient boosting
- [ ] merge the logic of subset and subfeature
- [ ] remove the macro functions, maybe convert them to template functions
- [ ] refine the tree learning pipelines
- [ ] refine prediction codes 
- [ ] remove the duplicate codes in **_bin

**Comment by StrikerRUS** [comment]
@guolinke Can we tick `serial_tree_learner.cpp`? Or do you want to do more refactoring?

**Comment by lcsdavid** [comment]
May I add that there is an error in
<[LightGBM/include/LightGBM/dataset_loader.h](https://github.com/microsoft/LightGBM/blob/master/include/LightGBM/dataset_loader.h)>:30:26-48
CostructFromSampleData should be ConstructFromSampleData ?

Regards.

**Comment by guolinke** [comment]
@lcsdavid I think it is a typo. welcome to create PR to fix it.

**Comment by StrikerRUS** [comment]
I'd like to propose refactoring additional config structures introduced in the initial CUDA support (I believe they can be replaced by ordinary config object)
https://github.com/microsoft/LightGBM/blob/1782fcb1e46ad0f06993d403b62d013d1e2cf76b/include/LightGBM/cuda/vector_cudahost.h#L16-L34
https://github.com/microsoft/LightGBM/pull/3160#discussion_r474855979

**Comment by jameslamb** [comment]
It's been a few years since the last comment on this issue. I think we should close it, what do you think @guolinke ?

**Comment by guolinke** [comment]
Sure, let us close it for now

**Comment by jameslamb** [comment]
thank you very much!
