### ISSUE TITLE
Question of categorical features

### ISSUE THREAD

**Issue by nirupamkar** [microsoft/LightGBM#2343]
@guolinke 
1.is there any way to directly access the grouping of categorical features?
2.If the init score is given the optimum spilt for categorical/numerical feature will be a function of "residual error" or the original error?

**Comment by nirupamkar** [comment]
@StrikerRUS @guolinke any help on this?

**Comment by guolinke** [comment]
@nirupamkar 
1. you can access by cpp code.
2. it currently is based on `residual` (gradient), not the original label.
