### ISSUE TITLE
Add AUC mu metric for multiclass training

### ISSUE THREAD

**Issue by MotoRZR** [microsoft/LightGBM#2344]
There was a paper written on a new AUC metric for multiclass problems.  

http://proceedings.mlr.press/v97/kleiman19a/kleiman19a.pdf

The authors have provided the code in the repository below so this should be straightforward to incorporate as an inbuilt metric.

https://github.com/kleimanr/auc_mu/blob/master/auc_mu.py

**Comment by StrikerRUS** [comment]
For the reference: catboost has already implemented AUC Mu: https://github.com/catboost/catboost/commit/298ca12c7c7c8bda54ef1291b3fb1ea0888e6539.

**Comment by StrikerRUS** [comment]
Closed in favor of being in #2302. We decided to keep all feature requests in one place.

Welcome to contribute this feature! Please re-open this issue (or post a comment if you are not a topic starter) if you are actively working on implementing this feature.

**Comment by btrotta** [comment]
PR is open for this.

**Comment by StrikerRUS** [comment]
Closed via #2567.
