### ISSUE TITLE
Add Smarter Backoffs for MPI ring connection

### ISSUE THREAD

**Issue by mhamilton723** [microsoft/LightGBM#2348]
Hey, I am running many LightGBM training runs as part of LightGBM on Spark's CI process and i notice that it does alot of waiting because of bad network and this dramatically slows the tests:

https://github.com/microsoft/LightGBM/blob/0a4a7a86f5a1d3146c36c7d8c082154a193d4893/src/network/linkers_socket.cpp#L190

Could you potentially make it first wait for half a second, then wait for 10 seconds? Or make this configurable. Thanks for the help!

**Comment by guolinke** [comment]
This could be configurable. 
I will create a PR for it.
