### ISSUE TITLE
Using categorical_feature and save_binary confusion.

### ISSUE THREAD

**Issue by IsaacLance** [microsoft/LightGBM#2349]
When calling train on my dataset and a validation set, I'm getting the error:
`LightGBMError: Cannot set categorical feature after freed raw data, set free_raw_data=False when construct Dataset to avoid this.`

It seems that in order to set free_raw_data to False I would have to give up using:
`my_dataset.save_binary('test.bin')`
Since it frees the raw data. Is there a way around this? My datasets are very large.

Another related question: I can set the categorical features when I create a dataset, as well as when I train on the dataset. Is one of these preferred? Are they both required? This is unclear to me.

**Comment by guolinke** [comment]
@IsaacLance 
the best use case for categorical features is set it when declaring the lgb.Dataset, not in lgb.train. 
If you set categorical feature before `save_binary`, this problem could be avoided.
After `save_binary`, the loaded dataset object from binary file is unchangeable. 

If the parameters (of dataset) is set in lgb.Dataset, you don't need to set it again when training.

**Comment by IsaacLance** [comment]
So my code right now is in this order:
```
x, y = get_my_dataset()
cats = ['f1', 'f2' ...]
dataset = lgb.Dataset(x, label= y, categorical_feature = cats)
dataset.save_binary(path)
params = ...
clf = lgb.train(params, dataset ...)
```
And I'm getting the error.

**Comment by guolinke** [comment]
I think it happens to `valset`? do you have the same processing?

**Comment by guolinke** [comment]
BTW, do `params` contains `categorical_feature` ? if yes, you can try to remove it.

**Comment by IsaacLance** [comment]
Valset is made the same exact way I just wanted to save lines here! 
I'm using categorical_feature in params, if I remove it, won't the features be treated differently? I have categorical features. @StrikerRUS

**Comment by IsaacLance** [comment]
This may be related to the same underlying problem or not, I'm not sure, but I also am not able to get this to work:
```
params['metric'] = 'multi_error','multi_logloss'
params['first_metric_only'] = True
```
My training still stops based on the second metric, even when this is set to True. I tried switching the order of my two metrics but it still stopped on multi_error with either order.

**Comment by guolinke** [comment]
@IsaacLance if you set `categorical_feature` in lgb.Dataset, you don't need to set it again in lgb.train.
@StrikerRUS to confirm this.

**Comment by guolinke** [comment]
for the `first_metric_only`, refer to this PR: https://github.com/microsoft/LightGBM/pull/2209

**Comment by StrikerRUS** [comment]
> @IsaacLance if you set categorical_feature in lgb.Dataset, you don't need to set it again in lgb.train.
@StrikerRUS to confirm this.

Yeah, cat features can (and should) be set once in `lgb.Dataset()` constructor.

**Comment by StrikerRUS** [comment]
Seems that I cannot reproduce the problem.

```
import lightgbm as lgb

from sklearn.datasets import load_boston
from sklearn.model_selection import train_test_split

X, y = load_boston(True)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
cats = [2]
dataset = lgb.Dataset(X_train, label=y_train, categorical_feature=cats, free_raw_data=False)
dataset.save_binary('test.bin')
valset = lgb.Dataset(X_test, y_test, reference=dataset, categorical_feature=cats)
params = {'objective': 'regression'}
clf = lgb.train(params, dataset, num_boost_round=10, valid_sets=valset)
```

```
[1]	valid_0's l2: 64.4937
[2]	valid_0's l2: 55.7111
[3]	valid_0's l2: 48.119
[4]	valid_0's l2: 42.2772
[5]	valid_0's l2: 37.1135
[6]	valid_0's l2: 32.9122
[7]	valid_0's l2: 29.7798
[8]	valid_0's l2: 27.0391
[9]	valid_0's l2: 24.9934
[10]	valid_0's l2: 23.1061
```

**Comment by StrikerRUS** [comment]
@IsaacLance
> I'm using categorical_feature in params, if I remove it, won't the features be treated differently?

You can check it by changing `cats = None`. After doing that the output changes, so cat features are treated as expected.
```
[1]	valid_0's l2: 64.4937
[2]	valid_0's l2: 55.7111
[3]	valid_0's l2: 48.119
[4]	valid_0's l2: 42.2591
[5]	valid_0's l2: 37.0764
[6]	valid_0's l2: 32.882
[7]	valid_0's l2: 29.7398
[8]	valid_0's l2: 26.9836
[9]	valid_0's l2: 24.9355
[10]	valid_0's l2: 22.8902
```

**Comment by IsaacLance** [comment]
It seems that categorical features don't work with Datasets loaded from binary made with save_binary. I set free_raw_data=False but I assume saving it doesn't actually save the raw_data with it, so that is my problem. If categorical data is not helping performance (this is still unclear to me whether it is helpful) I can just remove it.

**Comment by StrikerRUS** [comment]
@IsaacLance Can you please provide any reproducible example illustrating what are you saying?

**Comment by IsaacLance** [comment]
```
import lightgbm as lgb
x, y = get_data()
x_val, y_val = get_val()
cats = ['string1', 'string2']
dataset = lgb.Dataset(X_train, label=y_train, categorical_feature=cats, free_raw_data=False)
valset = lgb.Dataset(x_val, y_val, categorical_feature=cats)
dataset.save_binary('test.bin')
#Using Dataset from .bin file
loaded_dataset = lgb.Dataset('test.bin')
params = {'objective': 'regression'}
clf = lgb.train(params, loaded_dataset, num_boost_round=10, valid_sets=valset)
```
Results in
`LightGBMError: Cannot set categorical feature after freed raw data, set free_raw_data=False when construct Dataset to avoid this.`

**Comment by guolinke** [comment]
@IsaacLance still cannot reproduce:

```
import lightgbm as lgb

from sklearn.datasets import load_boston
from sklearn.model_selection import train_test_split

X, y = load_boston(True)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
cats = [2]
dataset = lgb.Dataset(X_train, label=y_train, categorical_feature=cats)
dataset.save_binary('test.bin')
valset = lgb.Dataset(X_test, y_test,  categorical_feature=cats)
loaded_dataset = lgb.Dataset('test.bin')
params = {'objective': 'regression'}
clf = lgb.train(params, loaded_dataset, num_boost_round=10, valid_sets=valset)
```

```
[LightGBM] [Info] Total Bins 999
[LightGBM] [Info] Number of data: 404, number of used features: 13
[LightGBM] [Info] Start training from score 22.796535
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[1]     valid_0's l2: 64.4717
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[2]     valid_0's l2: 55.6018
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[3]     valid_0's l2: 48.1258
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[4]     valid_0's l2: 42.1648
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[5]     valid_0's l2: 37.1796
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[6]     valid_0's l2: 33.0232
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[7]     valid_0's l2: 29.4764
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[8]     valid_0's l2: 26.8515
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[9]     valid_0's l2: 24.6031
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[10]    valid_0's l2: 22.5085
```

**Comment by guolinke** [comment]
BTW, it is better to specific reference to valset, like `valset = lgb.Dataset(X_test, y_test,  reference=dataset, categorical_feature=cats)`

-

**Comment by IsaacLance** [comment]
Thanks for the tip! I made a mistake, my code didn't exactly match what I posted as an example. I was also loading the valset from a file. When I only load the dataset from a file, but not valset, it works! So my mistake was using save_binary with the valset.

**Comment by StrikerRUS** [comment]
Loading validation dataset from file works fine as well.
```
import lightgbm as lgb

from sklearn.datasets import load_boston
from sklearn.model_selection import train_test_split

X, y = load_boston(True)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
cats = [2]

dataset = lgb.Dataset(X_train, label=y_train, categorical_feature=cats, free_raw_data=False)
dataset.save_binary('test.bin')
valset = lgb.Dataset(X_test, y_test, reference=dataset, categorical_feature=cats)
valset.save_binary('test_val.bin')

loaded_dataset = lgb.Dataset('test.bin')
loaded_valset = lgb.Dataset('test_val.bin')

params = {'objective': 'regression'}
clf = lgb.train(params, loaded_dataset, num_boost_round=10, valid_sets=loaded_valset)
```


```
[1]	valid_0's l2: 64.4937
[2]	valid_0's l2: 55.7111
[3]	valid_0's l2: 48.119
[4]	valid_0's l2: 42.2772
[5]	valid_0's l2: 37.1135
[6]	valid_0's l2: 32.9122
[7]	valid_0's l2: 29.7798
[8]	valid_0's l2: 27.0391
[9]	valid_0's l2: 24.9934
[10]	valid_0's l2: 23.1061
```

**Comment by IsaacLance** [comment]
I corrected my mistake and it's working now. Thank you for your help!
