### ISSUE TITLE
RStudio crashes when I try to run light gbm train process

### ISSUE THREAD

**Issue by henry090** [microsoft/LightGBM#2350]
Hi, I have just installed Light GBM and this time RStudio crashes when I try to run one of your examples: e.g. cross_validation.R

<img width="1280" alt="Screen Shot 2019-08-23 at 7 17 26 PM" src="https://user-images.githubusercontent.com/38523699/63603780-5bca3900-c5db-11e9-92e7-d58fb16f5c7c.png">

```
sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] lightgbm_2.2.4 R6_2.4.0      

loaded via a namespace (and not attached):
[1] compiler_3.6.1    magrittr_1.5      tools_3.6.1       data.table_1.12.2 jsonlite_1.6     
> 
```

**Comment by jameslamb** [comment]
Thanks for the report and the session information! I'd like to help you out.

Could you paste in here the exact code you ran (so I can copy paste it and try to run myself)? I want to be sure you ran exactly `cross_validation.R`. It's possible we have some combination of parameters there which causes an issue with newer versions of the library.

Could you also tell us what steps you took to install the R library? Namely, I'm curious if you use `clang` or `gcc`/`g++` to compile `lightgbm`.

Finally, have you tried completely restarting your R session after re-installing `lightgbm`? Sometimes you can get into trouble if you re-build the library and then try to run `lightgbm` code from a session where an older version had already been loaded (that is not specific to `lightgbm` but true of many R packages).

**Comment by henry090** [comment]
```
require(lightgbm)
# load in the agaricus dataset
data(agaricus.train, package = "lightgbm")
data(agaricus.test, package = "lightgbm")
dtrain <- lgb.Dataset(agaricus.train$data, label = agaricus.train$label)
dtest <- lgb.Dataset.create.valid(dtrain, data = agaricus.test$data, label = agaricus.test$label)

nrounds <- 2
param <- list(num_leaves = 4,
              learning_rate = 1,
              objective = "binary")

print("Running cross validation")
# Do cross validation, this will print result out as
# [iteration]  metric_name:mean_value+std_value
# std_value is standard deviation of the metric
lgb.cv(param,
       dtrain,
       nrounds,
       nfold = 5,
       eval = "binary_error")

print("Running cross validation, disable standard deviation display")
# do cross validation, this will print result out as
# [iteration]  metric_name:mean_value+std_value
# std_value is standard deviation of the metric
lgb.cv(param,
       dtrain,
       nrounds,
       nfold = 5,
       eval = "binary_error",
       showsd = FALSE)

# You can also do cross validation with cutomized loss function
print("Running cross validation, with cutomsized loss function")

logregobj <- function(preds, dtrain) {
  labels <- getinfo(dtrain, "label")
  preds <- 1 / (1 + exp(-preds))
  grad <- preds - labels
  hess <- preds * (1 - preds)
  return(list(grad = grad, hess = hess))
}
evalerror <- function(preds, dtrain) {
  labels <- getinfo(dtrain, "label")
  err <- as.numeric(sum(labels != (preds > 0))) / length(labels)
  return(list(name = "error", value = err, higher_better = FALSE))
}

# train with customized objective
lgb.cv(params = param,
       data = dtrain,
       nrounds = nrounds,
       obj = logregobj,
       eval = evalerror,
       nfold = 5)
```

__This is how I built__
```
# replace 8 with version of gcc installed on your machine
export CXX=/usr/local/bin/g++-8 CC=/usr/local/bin/gcc-8
git clone --recursive https://github.com/microsoft/LightGBM
cd LightGBM
Rscript build_r.R
```

```
Sometimes you can get into trouble if you re-build the library and then try to run lightgbm code from a session where an older version had already been loaded
```

__I removed the old folder and cloned, again. And the process was successful.__

**Comment by henry090** [comment]
Hi, I updated gcc and cloned+reinstalled again. Works fine. No fatal error.

**Comment by jameslamb** [comment]
@henry090 thanks for the thorough updates. Sorry that it took me a few days to get back to you, I have been traveling.

I'm glad that it is working for you! You have already given us so much of your time... if you'd be willing to give us just a bit more of it, would you show the result of `gcc --version` here for people who find this issue in the future and want to know what combination of `lightgbm` + `R` + `gcc` was known to work? You already provided the output of `sessionInfo()` but I'd like to know the `gcc` version.

I think we will close this issue if it's now working for you, but it is a bit unsettling to me that it's one of those "don't know why it was broken, don't know why it works now" situations 😬

**Comment by henry090** [comment]
gcc 9.2.0, AFAIR previously the version was 8 :)

**Comment by StrikerRUS** [comment]
@henry090 Thanks a lot for your feedback! It's great that your problem has been solved by reinstalling. I guess it maybe related to #2267.
