### ISSUE TITLE
Segmentation fault on binary format but not libsvm format

### ISSUE THREAD

**Issue by mhoward2718** [microsoft/LightGBM#2351]
I'm running the command line LightGBM binary. I have a dataset with several hundred million records. After experiencing some long load times, I converted it to the binary format using Python: 

```
import lightgbm as lgb
train_data = lgb.Dataset('data.libsvm')
train_data.save_binary('data.bin')
```

When the data was in LibSVM format, LightGBM is able to successfully train a model. When loading the binary data, though, it dies instantly with a segmentation fault.

Using the linux `head` and `tail` commands I chopped down smaller and smaller versions of the original data. I now have a LibSVM file just under 1000 lines that still causes the segmentation fault after conversion to binary. I'm happy to share that file to help debug.

## Environment info

Operating System: 
Ubuntu 16.04.6 LTS

CPU/GPU model:

Tried on various AWS EC2 instances. For testing/debugging I use a T2 2XLarge. Per the instance types page, that has: 
Intel AVX, Intel Turbo
3.0 GHz Intel Scalable Processor

C++/Python/R version: 
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
Python 3.6.5

LightGBM version or commit hash:

LightGBM 2.2.4

## Error message
```
[LightGBM] [Info] Finished loading parameters
Segmentation fault (core dumped)
```
## Reproducible examples

I'm happy to share my LibSVM data file that causes the problem.

## Steps to reproduce

1. Run LightGBM on data in LibSVM format and observe successful training.
2. Convert data to binary format using Python.
3. Run LightGBM on data in binary format and observe segmentation fault.

**Comment by guolinke** [comment]
@mhoward2718 sure, please share the data.

**Comment by mhoward2718** [comment]
Thanks. 

I've put the data in both formats, conversion script and configuration files in this Git Gist:

https://gist.github.com/mhoward2718/9acd0903b62643b817ae954971b2259e

You should be able to clone it or download it as a zip.

**Comment by guolinke** [comment]
@mhoward2718 I run your code with the latest code, and everything is fine.
But with 2.2.3, it indeed throws an error `[LightGBM] [Fatal] Wrong size of feature_names`
I think this should be fixed in the latest code.

**Comment by mhoward2718** [comment]
How strange - I'm using 2.4.4. Maybe the different is from the compiler version. I'll see if I can update that and will try again.

**Comment by guolinke** [comment]
BTW, did you use the same compiled application for the save and load?

**Comment by mhoward2718** [comment]
Hello.

Upgrading to GCC-7 seems to have solved it. It crashes when I use that binary data I had exported before. However, after recompiling with GCC7, I was succesfully able to re-save the data from LibSVM, load it, and train without without a crash.

> BTW, did you use the same compiled application for the save and load?

Yes, it was the same application.
