### ISSUE TITLE
sample_weight (or weight) is ignored when the hessians of the loss are constant

### ISSUE THREAD

**Issue by adrinjalali** [microsoft/LightGBM#2365]
It seems like LightGBM assumes if sample weights are given, the hessian and the gradients are multiplied by the sample weight, and the rest of the pipeline doesn't have to worry about the weights. For instance, `FindBestThresholdSequence` doesn't care about the weights.

The issue is that when the hessian is constant, the `dadaset.cpp` ignores the weights, around here:

https://github.com/microsoft/LightGBM/blob/0551f77517d971ce9bc32e2633768245957b410a/src/io/dataset.cpp#L824-L883

As a result, if the hessian is constant, sample weights are ignored. Is this intentional?

cc @NicolasHug

**Comment by NicolasHug** [comment]
Basically I think that this line should take into account the weights instead of just the counts.

```c
     for (int i = 0; i < num_bin; ++i) { 
       data_ptr[i].sum_hessians = data_ptr[i].cnt * hessians[0]; 
     } 
```

**Comment by guolinke** [comment]
refer to
https://github.com/microsoft/LightGBM/blob/0551f77517d971ce9bc32e2633768245957b410a/src/objective/regression_objective.hpp#L148-L154

when weights are provided, `is_constant_hessian` is false.
