### ISSUE TITLE
[R-package] Standardize R code on comma-first

### ISSUE THREAD

**Issue by jameslamb** [microsoft/LightGBM#2373]
Per [this comment](https://github.com/microsoft/LightGBM/pull/2334#discussion_r317414998) on #2334 . We should standardize all R code in the repo on comma-first.

**Comment by StrikerRUS** [comment]
Closed in favor of being in #2302. We decided to keep all feature requests in one place.

Welcome to contribute this feature! Please re-open this issue (or post a comment if you are not a topic starter) if you are actively working on implementing this feature.

**Comment by jameslamb** [comment]
reopening this issue as there is an active PR to fix it
