### ISSUE TITLE
ignore_column doesn't ignore the features when input is a binary file

### ISSUE THREAD

**Issue by Jingyu-Fan** [microsoft/LightGBM#2376]
Related to https://github.com/Microsoft/LightGBM/issues/1061

## Environment info

Operating System: Linux

CPU/GPU model: CPU

C++/Python/R version: Python

LightGBM version or commit hash: 2.2.3

## Reproducible examples

```

import numpy as np
import lightgbm as lgb
import pickle

data = np.random.random((500, 10))
y = [1] * 250 + [0] * 250
lgb_train = lgb.Dataset(data, y)
lgb_train.save_binary("lgb_train_data.bin")

lgb_train =  lgb.Dataset("lgb_train_data.bin", y)
params = {
    'ignore_column': '0,1',
    'objective': 'binary',
    'verbose': 1
}

gbm = lgb.train(params=params,
                train_set=lgb_train,
                num_boost_round=2,
                )

```

**Comment by guolinke** [comment]
Once the dataset is constructed, the ignore column will not take effect. 
Bin file is the constructed dataset, so it cannot used the ignore column.
