### ISSUE TITLE
gpu donot work

### ISSUE THREAD

**Issue by Jie-Yuan** [microsoft/LightGBM#2388]
clf = LGBMClassifier(**{    'device': 'gpu',
    'gpu_platform_id': 0,
    'gpu_device_id': 0,
    'gpu_use_dp':True})

**Comment by Jie-Yuan** [comment]
LightGBMError                             Traceback (most recent call last)
<ipython-input-1-980474718830> in <module>
     37 
     38 data = lgb.Dataset(X, y)
---> 39 _ = lgb.cv(param, data, num_boost_round=10000, verbose_eval=1000)

/usr/local/lib/python3.6/dist-packages/lightgbm/engine.py in cv(params, train_set, num_boost_round, folds, nfold, stratified, shuffle, metrics, fobj, feval, init_model, feature_name, categorical_feature, early_stopping_rounds, fpreproc, verbose_eval, show_stdv, seed, callbacks, eval_train_metric)
    527                             params=params, seed=seed, fpreproc=fpreproc,
    528                             stratified=stratified, shuffle=shuffle,
--> 529                             eval_train_metric=eval_train_metric)
    530 
    531     # setup callbacks

/usr/local/lib/python3.6/dist-packages/lightgbm/engine.py in _make_n_folds(full_data, folds, nfold, params, seed, fpreproc, stratified, shuffle, eval_train_metric)
    346         else:
    347             tparam = params
--> 348         cvbooster = Booster(tparam, train_set)
    349         if eval_train_metric:
    350             cvbooster.add_valid(train_set, 'train')

/usr/local/lib/python3.6/dist-packages/lightgbm/basic.py in __init__(self, params, train_set, model_file, model_str, silent)
   1634                 train_set.construct().handle,
   1635                 c_str(params_str),
-> 1636                 ctypes.byref(self.handle)))
   1637             # save reference to data
   1638             self.train_set = train_set

/usr/local/lib/python3.6/dist-packages/lightgbm/basic.py in _safe_call(ret)
     45     """
     46     if ret != 0:
---> 47         raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))
     48 
     49 

LightGBMError: Out of Host Memory

**Comment by mhoward2718** [comment]
This is failing before it begins training. It is trying to convert your dataset into the internal LightGBM format and running out of memory. This might fail whether you use `device': 'gpu',` or `device': 'cpu'. 

Have you considered using the `use_two_round_loading` parameter? It will help prevent a memory explosion when loading data.

**Comment by StrikerRUS** [comment]
I think the error message is quite clear and self-described. It comes from OpenCL and indicates the lack of GPU memory. It's possible that your model is very large and cannot be fitted into memory.
