### ISSUE TITLE
Can I change io params(like max_bin) after lgb.Dataset().construct()?

### ISSUE THREAD

**Issue by aprilffff** [microsoft/LightGBM#2395]
I have constructed and saved binary lgb dataset to save ram usage. But I noticed that the io params are fixed  once contructed. Any solution to change io params after construct being called? 

And do you have any plan on slicing features just like use_indices on samples? Because after construct() there would be no direct way to delete features.

**Comment by guolinke** [comment]
for the first question, very sorry, there is no work-around, especially for `max_bin`, which highly relies on the raw data, so it is not possible.
for the second question, you can use https://github.com/microsoft/LightGBM/blob/master/docs/Parameters.rst#feature_contri , to force mask some features.
