### ISSUE TITLE
Loading a model from Python into C++ just for predictions.

### ISSUE THREAD

**Issue by IsaacLance** [microsoft/LightGBM#2397]
Is there example code anywhere of training and saving a model in Python and then loading and using it in C++? I'm not sure of the best/fastest way to do this. Python can save boosters three different ways, save_model, model_to_string, and dump_model. I assume for the C api we would use save_model? I saw some other discussion about saving a model as if statements for C++, too.

If it matters, the predictions would be done one example at a time.

**Comment by StrikerRUS** [comment]
@IsaacLance

Here is the original cpp code for the `predict` task:
https://github.com/microsoft/LightGBM/blob/b310fb417e4078cc30b153a5ef8f60c06d9ca9cf/src/application/application.cpp#L240-L249
https://github.com/microsoft/LightGBM/blob/master/src/application/predictor.hpp

You can use LightGBM CLI version for prediction via saved from Python model:
https://lightgbm.readthedocs.io/en/latest/Parameters.html#task
#1866

You can load model and then call prediction function from C API:
https://lightgbm.readthedocs.io/en/latest/C-API.html
https://github.com/microsoft/LightGBM/blob/b310fb417e4078cc30b153a5ef8f60c06d9ca9cf/tests/c_api_test/test_.py#L241-L277
#1666
#666

You can use Treelite for model compilation:
https://github.com/dmlc/treelite

You can covert your model to `if-else` format:
https://lightgbm.readthedocs.io/en/latest/Parameters.html#convert_model
https://github.com/microsoft/LightGBM/blob/b310fb417e4078cc30b153a5ef8f60c06d9ca9cf/.ci/test.sh#L63-L65
