### ISSUE TITLE
Documentation: parameters on booster model vs dataset

### ISSUE THREAD

**Issue by imatiach-msft** [microsoft/LightGBM#2398]
It seems that the categorical_feature parameter needs to be set on the dataset instead of the booster (or perhaps both)?
https://github.com/microsoft/LightGBM/blob/master/docs/Parameters.rst#categorical_feature

Should the documentation here mention which parameters are on the dataset vs the booster?  Or is there documentation available with this breakdown already?
https://github.com/microsoft/LightGBM/blob/master/docs/Parameters.rst

**Comment by StrikerRUS** [comment]
> It seems that the categorical_feature parameter needs to be set on the dataset instead of the booster (or perhaps both)?

It is expected that `categorical_feature` parameter is set on the Dataset #1408.

> Should the documentation here ...

This is page with parameters for CLI version of LightGBM.  There is no Dataset/Booster abstraction there.

**Comment by imatiach-msft** [comment]
"This is page with parameters for CLI version of LightGBM"
@StrikerRUS Ah I see, good point.  Let me close this defect then.

**Comment by StrikerRUS** [comment]
@imatiach-msft To be honest, I'd like to see these mentions somewhere too. But I don't know how and where it can be done elegantly without duplicating params descriptions for all language-packages.

Maybe @guolinke knows?
