### ISSUE TITLE
lightgbm memory spike

### ISSUE THREAD

**Issue by RainFung** [microsoft/LightGBM#2404]
`lightgbm.Dataset()` always raise a memory spike which make jupyter kernel crash.Like discussed in kaggle, https://www.kaggle.com/c/talkingdata-adtracking-fraud-detection/discussion/55325#319189.

**Comment by RainFung** [comment]
when to use np.float32 directly？ can you give some example

**Comment by guolinke** [comment]
To avoid any conversions, you should always use np.float32

**Comment by StrikerRUS** [comment]
Some use cases should be fixed by #2383.
