### ISSUE TITLE
Homebrew Formula for LightGBM

### ISSUE THREAD

**Issue by StrikerRUS** [microsoft/LightGBM#2408]
Upstream issue: https://github.com/Homebrew/homebrew-core/pull/43244.

@ankane Thanks a lot for your efforts!

Please ping us if any help is needed from our side.

Want to hear opinion of macOS users @jameslamb @Laurae2 @henry0312.

**Comment by ankane** [comment]
Hey @StrikerRUS, the formula was just accepted, so Mac users can now do:

```ruby
brew install lightgbm
```

Homebrew pre-compiles ("bottles") formula, so it installs in a couple seconds :fire:

**Comment by jameslamb** [comment]
WOW thank you so much @ankane this is great!

I read the formula and it looks good to me. @StrikerRUS we should consider updating that formula as a part of our release process. I think all we'd need to do is update which archive it points to.

**Comment by StrikerRUS** [comment]
@ankane Awesome! Many thanks to you!

@jameslamb 
> we should consider updating that formula as a part of our release process.

That's for sure! We should send PR to Homebrew repo right after LightGBM new release.

> I think all we'd need to do is update which archive it points to.

@ankane Can you please confirm this? Should we only update `url` and `sha256` fields in the formula?

**Comment by ankane** [comment]
@StrikerRUS Yeah, unless the build instructions change.

**Comment by StrikerRUS** [comment]
@ankane Got it! Thanks a lot for your kindness!

**Comment by StrikerRUS** [comment]
@ankane BTW, is it possible to add an option `--mpi` to the formula to install with the MPI support? Maybe for some users it will be useful.
It will require only adding `open-mpi` dependency and `-DUSE_MPI=ON` flag for CMake.
https://github.com/microsoft/LightGBM/blob/master/docs/Installation-Guide.rst#apple-clang-2

**Comment by ankane** [comment]
It looks like options aren't allowed in formula in Homebrew core. From the docs:

> Note: options are not allowed in Homebrew/homebrew-core as they are not tested by CI.

https://github.com/Homebrew/brew/blob/master/docs/Formula-Cookbook.md

**Comment by StrikerRUS** [comment]
@ankane Oh, I see! I'm sorry, I'm not very familiar with brew. I asked only because I have `brew install gcc --without-multilib` command ([outdated already](https://github.com/Homebrew/homebrew-core/pull/16751)) in my head 😃 .
