### ISSUE TITLE
Unreliable categorical groups

### ISSUE THREAD

**Issue by nirupamkar** [microsoft/LightGBM#2411]
I am dealing with a classification problem with categorical features. While doing so I have encountered a strange situation. I have trimmed down the situation to a base case.
 
1.Say I have 100M rows with 1 feature having more than 1M categories. The actual target rate of this categories can range from 0 to 1.  

2.While predicting on the train dataset itself I observed there are categories with (say ~500 count and 0 target)  and the prediction is coming to be close to the mean target of the train data

3.It could be because of regularisation or the categorical split. I reduced the regularisation to practically zero and it was still similar

4.So it appeared it might be how the categorical splits have been made for the feature. What I did was I created 1 tree with say 150 nodes and with max_cat_thresold=150 and boosting_from_average=True, so that I can broadly check the categorical splits. (right now the split cannot be accessed from python interface )

5.I predicted the leaf index and calculated the target rate for each leaf index. There were almost 150 leaves so I can assume categorical histogram has got ~150 bins.

6.Coming to the observations

- There was a leaf(say L) with almost 50-60% of data with target rate almost same as the overall data
- There were leaves with ~200-300 counts and 0 target rate. So bins were made for these.
- However there was a significant number of categories(say C) with ~ 500 count and 0 target being clubbed in leaf L and thereby predicting average value for those

My question is why these categories are not being combined with 0 target rate bins. I wanted to upload the data over here, however the size is very big and the issue is less significant for lower volume of data. However I can give clarification of any questions if needed.

I am using server and it has got memory of 256GB.

@guolinke any help is really appreciated.

**Comment by guolinke** [comment]
I think you misunderstood the categorical split algorithm.
There is no "merge bins" for categorical features, all categories are unique, except the long tail (the last 1% sorted by frequence) will be in the one bin. 
Therefore, in your case, with `max_cat_thresold=150`, only 300 (two side scanning, the first 150 and the last 150) are evaluated in categorical splits. And as a result, the categorical without counts=500 may in the middle, and be ignored. 

For the categorical features with many categories, I recommender to use the target encoding outside of GBDT.

**Comment by nirupamkar** [comment]
@guolinke thanks for the quick reply. Really appreciate it. I misunderstood  the algorithm of categorical split of lgb. However if i put cat threshold=150, so there will be 1 bin with more than 1 category and rest will be having single category. Please confirm this.
Now if I put num_leaves=150, I am getting around 148 leaves with most having more than 1 categories. Am I missing something?

**Comment by nirupamkar** [comment]
@guolinke probably the earlier post is wrong. It orders the categories by (G/(H+cat_smooth)) and then try to find best split from first 150 categories and last 150 categories.  
If optimum split is found at say 80th index, for next split 81-231 and last 150 categories will be tested.
So how many bins will be there at the end? As I am seeing lots of categories falling under 1 bin, is there any way to stop that?

**Comment by guolinke** [comment]
I think you still misunderstood it. 
1. max cat threshold don't mean to merge categories to bigger categories. It is the number categories will be considered for one leaf split. For example, when set it to 1, the split will only consider the one vs rest splits; if set it to 2, it is one vs rest or two vs rest; and so on.
2. LightGBM will sort the categories according to its dynamic encoding value (regards to gradient and hessian) and only considere the largest max_cat_threshold and the smallest max_cat_threshold categories.

**Comment by guolinke** [comment]
Did you mean there are many one vs rest splits?

**Comment by nirupamkar** [comment]
Ok things got confused a bit. 
1.The categorical histogram bins are created before the tree building right?
2."It is the number categories will be considered for one leaf split."- do you mean bin or split?
3.First lgb will sort categories by frequency and put all categories coming in last(say this is Cat_last) 1% in a bin, right?
4.Then lgb will sort categories by gradient/(hessisan +cat_smooth)?
5.Could you please elaborate "only considere the largest max_cat_threshold and the smallest max_cat_threshold categories."

First of all I was putting num_leaves= very large value, depth=-1 and built 1 tree and predicted leaf index. 1 of the leaves was having quite a large number of categories with Cat_last. 
Does it mean there was a bin of the feature with this many categories? Even if I increase the num_leaves it does not decrease after a large value. Any way to avoid it?

**Comment by nirupamkar** [comment]
Is there a role of "bin_construct_sample_cnt" for creating bins for categorical features?

**Comment by guolinke** [comment]
@nirupamkar 
1. yeah, the bin is pre-allocated, and fixed in tree growing.
2. on each splits, the number of bins (almost equal to categories, except the long-tailed bin) will be considered.
3. No, the merged of long-tailed categories is at the bin constructed stage, no the tree growing stage. 
4. yeah, the sorted is over categorical bins.
5. the split finding is a two side scanning: 1) from the largest to the smallest; 2) from the smallest to the largest. the largest and smallest regard to the gradient/(hessisan +cat_smooth). As we limit the `max_cat_threshold`, one side scanning may is not sufficient. Although two-side scanning still cannot cover all categories, but it may find the better splits than one side scanning.
6. yeah, it will always have a leaf with rest categories, since there are all k-vs-rest splits. The only way to avoid this is to use the categorical features with fewer categories.
7. `bin_construct_sample_cnt` is also used for categorical features. It will sample the subrows for the bin construction.

**Comment by nirupamkar** [comment]
@guolinke 
Thanks for the detailed reply. I think the entire discrepancy is with bin_construct_sample_cnt. As I have a feature with long tail and the default value of bin_construct_sample_cnt  as 200000 makes things more complicated. For example with 1M categories with 100M rows, there is a chance, it will put those categories(say row count~ 500) to the long tail bin.
1. is min_data_per_group related to this sampled data or full data?
2. If count is less than cat_smooth is it pushed to cat_last? If so is this count based on sampled data?
3. Can max_bin be used to control categorical histogram bins?
4. What I am seeing is for certain categories even if the actual target rate is zero without any regularization the prediction is still larger than 0 (say around 0.003-0.005). The leaf output is 
-ThresholdL1(sum_gradients, l1) / (sum_hessians + l2) (if max_delta_step=0). For classification 
-  Gradient= p - y
-  Hessian=  p*(1-p)
Pls confirm above. As p goes to zero, the denominator value will increase without any regularization. Is is the reason for final probability being a bit too high?

**Comment by nirupamkar** [comment]
@guolinke Thanks for all the help. Any pointer to my last question?

**Comment by guolinke** [comment]
1. the count is for the data in the current leaf. the sampled data is only used in bin construction.
2. no, max_bin only for numerical features.
3. the p is the prediction of the previous trees, so it is 0.5 (`sigmoid(0)`) on the first tree. So your assumption is wrong. It may cause by the `kEpsilon` in the sum_hessians.
4. it behaviors like the cat_last. And cat_last will not be chosen as the `cat_splits`.
