### ISSUE TITLE
LightGBM distributed training can get stuck in some edge-case scenarios with labels missing on some partitions

### ISSUE THREAD

**Issue by imatiach-msft** [microsoft/LightGBM#2419]
LightGBM distributed training can get stuck in some edge-case scenarios, specifically:

1.) In binary classification scenario where some workers have a dataset with only 1 label instead of 2 labels, the workers with 1 label exit early.  The workers with 2 labels then get stuck waiting on the workers with 1 label.

2.) In multiclass classification scenario, if a worker has a dataset with non-consecutive integer labels, eg 0,1,2,4,5 with "3" missing, for some reason training gets stuck and times out (note unlike the binary classification scenario the worker does not exit successfully).

## Environment info

Operating System: windows, linux, macosx

CPU/GPU model: CPU

C++/Python/R version: Distributed MMLSpark version only

LightGBM version or commit hash: latest master

## Error message

LightGBM times out during training

## Reproducible examples
I have a test case that can reproduce this, but currently I have been able to fix the issue by tracking labels and throwing in case some label is missing or if there are fewer than 2 labels for classification on any of the partitions.

https://github.com/Azure/mmlspark/blob/master/src/test/scala/com/microsoft/ml/spark/lightgbm/split1/VerifyLightGBMClassifier.scala#L337

## Steps to reproduce

1. Create a pre-partitioned dataset where one of the partitions only has a single label but the others have 2 labels
2. Train lightgbm on that distributed dataset, note one of the workers finishes early with Warning message, while others are stuck waiting for it to finish

**Comment by imatiach-msft** [comment]
I've been able to get around this issue by detecting missing labels on partitions and throwing an exception, but ideally lightgbm should 1.) either work in this scenario, even if the results may be less than ideal 2.) fail gracefully with error message when detecting this scenario, so that the checks would not need to be done in non-native Scala code

**Comment by guolinke** [comment]
good issues. 
I think we can avoid these fails when distributed model is enable.

**Comment by guolinke** [comment]
for binary classification, the root cause is:
https://github.com/microsoft/LightGBM/blob/023749239ebf390b5d56e08f227a013cbd972eb0/src/objective/binary_objective.hpp#L76-L80

**Comment by guolinke** [comment]
for the multi-class, the root cause is:
https://github.com/microsoft/LightGBM/blob/023749239ebf390b5d56e08f227a013cbd972eb0/src/objective/multiclass_objective.hpp#L147-L154

the `class_init_probs_` should be synced from different workers.

**Comment by imatiach-msft** [comment]
I'm amazed you fixed it so quickly, great to hear this can be avoided
