### ISSUE TITLE
How to get every leaf preidction of every tree in a gbm tree?

### ISSUE THREAD

**Issue by anddelu** [Microsoft/LightGBM#242]
I want to use a gbm tree to get features for other models to use.
I know I can get a gbm tree prediction, but I want to get every leaf  prediction of every tree in a gbm tree in details. For example, tree A in a gbm tree, I want to know which leaf of A is  chosen to predict and the other leaves location in A. 
please see the following picture:
![fb_gbdt1](https://cloud.githubusercontent.com/assets/5293824/22172319/5d62b53e-dfde-11e6-88e8-e1c35378aa61.png)

**Comment by guolinke** [comment]
refer to https://github.com/Microsoft/LightGBM/blob/master/docs/Parameters.md#io-parameters.

Set "predict_leaf_index=true"
