### ISSUE TITLE
forcing a feature for consideration in every tree while using feature_fraction

### ISSUE THREAD

**Issue by ironv** [microsoft/LightGBM#2424]
`lgbm 2.2.3 / py 2.7.x`

Is it possible to force a feature to be considered for every tree while still using `feature_fraction < .5`?  I am working on datasets where `age` is a very important predictor and surrogates (age-related conditions) are chosen when it is not available as a variable.

**Comment by guolinke** [comment]
you can use forced_split, https://github.com/microsoft/LightGBM/blob/master/docs/Parameters.rst#forcedsplits_filename
