### ISSUE TITLE
Cannot Plot Tree

### ISSUE THREAD

**Issue by trashprogrammer** [microsoft/LightGBM#2428]
When I try to plot a tree I get an error saying I must install graphviz to plot tree. I tried installing it with conda and pip. I am able to import it just fine and am using graphviz version (2, 30, 1). I am also using the most up to date lightgbm version. I installed graphviz after lightgbm - could that be why it doesn't work? Any help would be greatly appreciated. Thank you 

Here's the error and code

``
graph = lgb.create_tree_digraph(gbm2, tree_index=53, name='Tree54')

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/mydrive/anaconda3/envs/myenv/lib/python3.6/site-packages/lightgbm/plotting.py", line 538, in create_tree_digraph
    graph = _to_graphviz(tree_info, show_info, feature_names, precision, monotone_constraints, **kwargs)
  File "/mnt/mydrive/anaconda3/envs/myenv/lib/python3.6/site-packages/lightgbm/plotting.py", line 381, in _to_graphviz
    raise ImportError('You must install graphviz to plot tree.')
ImportError: You must install graphviz to plot tree.
``

**Comment by jameslamb** [comment]
@trashprogrammer why did you close this? Could you share how you resolved the problem? Was it that thing where, when you work in a Jupyter notbeook, you need to reload the notebook to account for new packages you've installed?

**Comment by trashprogrammer** [comment]
> @trashprogrammer why did you close this? Could you share how you resolved the problem? Was it that thing where, when you work in a Jupyter notbeook, you need to reload the notebook to account for new packages you've installed?

I installed graphviz while the python session was still open. So I was able to import graphviz, but the variable in lightgbm was set so that it thought it was uninstalled. I think I literally just needed to reimport lightgbm after it got installed or restart python. Sorry for wasting your time. Thank you

**Comment by jameslamb** [comment]
Ahhhhh ok, got it. Not a waste of our time at all, thanks for reporting!

I think we could add a better message like "if you've recently installed graphviz, be sure to restart your session". We'd welcome a PR to add that if you'd like to contribute it! Otherwise I will probably add it in a few days.
