### ISSUE TITLE
Question about refit

### ISSUE THREAD

**Issue by PsLiKrypt** [microsoft/LightGBM#2433]
Hi,
I am now applying the refit method on my pre-trained model(model A) with new data (model B after). However, it performs worse than model A on a valid dataset. I know it could happen, but is it possible to tune the parameters during refitting to get a better result? Or my question also can be explained as Should I use the very same parameters during refitting?

**Comment by guolinke** [comment]
could you provide the code about how you do it?
It model B is tested over "new data", you should be better than model A.
But for valid data, it is hard to say. if it is closer to data of the pretrain, the refit could not improve it.

**Comment by PsLiKrypt** [comment]
Thanks for replying!
Well, I use the CLI version of lightgbm so it's hard to provide the code. In more details, I train model A over 7 days data, say, Sep.15 to Sep.21, model A, which will be used during Sep.22 all day.
Every hours I can collect realtime brand new data. Now I want to  update it within Sep.22. Since 'refit' is quit faster than just retraining a new model over 7 plus half days data, if I do this in the middle of Sep.22, I try using the data from half of Sep.22 to refit the model A to get model B. Another half data is my valid data, and I calculate AUC(in turn AUC_A, AUC_B).  Parameters in configure files are the same except 'task'.
The result is, AUC_B is smaller than AUC_A.

**Comment by guolinke** [comment]
I feel like the distribution of two halves (let us donate them to p and q) in one day is much different.
So it is possible the model B is fit to p. So I think a more reasonable usage is to update it per day, not per half day.

**Comment by guolinke** [comment]
I think the only parameter in refit is refit_decay. Others are not used.

**Comment by PsLiKrypt** [comment]
Thanks! That helps a lot.
