### ISSUE TITLE
bundle OpenMP dynamic library with wheels on macOS

### ISSUE THREAD

**Issue by douglasdavis** [microsoft/LightGBM#2435]
The [delocate](https://github.com/matthew-brett/delocate) package helps bundle dynamic libraries with Python wheels on macOS. I've used this to bundle the OpenMP dynamic library installed via Homebrew with wheels compiled with Clang shipped by Apple. This allows LightGBM users to install wheels without having to setup Homebrew. Of course it's not a large inconvenience to `brew install libomp`, but it's a small simplification to the installation process.

**Comment by StrikerRUS** [comment]
@douglasdavis Thanks for the proposal! I don't think that bundling dynamic libraries with wheels is good idea, even for macOS. Moreover, OpenMP is very "sensitive" (~problematic~) dependency, refer to https://github.com/microsoft/LightGBM/pull/2414#issuecomment-532403860. It leads to random crashes in case of multiple copies of the library across the system.

Similar discussion in XGBoost about `delocate`: https://github.com/dmlc/xgboost/issues/4477#issuecomment-530892414.

Furthermore, `delocate` is in alpha stage:

> Warning
Please be careful - this software is alpha quality and has not been much tested in the wild. Make backups of your paths and wheels before trying the utilities on them, please report any problems on the issue tracker (see below).

**Comment by StrikerRUS** [comment]
Due to the lack of comments, I'm going to close this for now. I think we can get back to the discussion once `delocate` become more adult.
