### ISSUE TITLE
[R-package] use commandArgs instead of hardcoded stuff in the installation script

### ISSUE THREAD

**Issue by StrikerRUS** [microsoft/LightGBM#2441]
Today, installing the R package with CMake like this:

```shell
Rscript build_r.R
```

Might require you to manually change some flags in `R-package/install.libs.R`.

https://github.com/microsoft/LightGBM/blob/e77658205d3b1bc5c19e4ba3821f4222f5be8c05/R-package/src/install.libs.R#L1-L4

Refer to https://github.com/microsoft/LightGBM/pull/2164#issuecomment-491576282.

To close this issue, expose those flags as command-line flags so users can do something like this:

```shell
Rscript build_r.R --use-gpu
```

**Comment by StrikerRUS** [comment]
Closed in favor of being in #2302. We decided to keep all feature requests in one place.

Welcome to contribute this feature! Please re-open this issue (or post a comment if you are not a topic starter) if you are actively working on implementing this feature.

**Comment by jameslamb** [comment]
if you're reading this and interested in contributing this feature, please comment here. Feel free to `@` me with questions
