### ISSUE TITLE
Running R-package on Rstudio error.

### ISSUE THREAD

**Issue by linrio** [Microsoft/LightGBM#245]
Please search your question on previous issues, stackoverflow or other search engines before you open a new one.

For bugs and unexpected issues, please provide following information, so that we could reproduce on our system.

## Environment info
Operating System: Win10
CPU: Intel Core i5
C++/Python/R version: R version x64 3.3.2, Rtools version: Rtools 34

## Code:
'
#install.packages("devtools")
library(devtools)
devtools::install_github("Microsoft/LightGBM", subdir = "R-package")
'
After I 'source' the file, I got
## Error Message:
'
> source('G:/codes/R/Microsoft/me.R')
Downloading GitHub repo Microsoft/LightGBM@master
from URL https://api.github.com/repos/Microsoft/LightGBM/zipball/master
Error: Could not find build tools necessary to build lightgbm
'

## Install Rtools
> install.packages("Rtools")
Warning in install.packages :
  package Rtools?is not available (for R version 3.3.2)

**Comment by guolinke** [comment]
@linrio can you install successfully in command line?

**Comment by Laurae2** [comment]
@linrio Rtools must be downloaded and installed manually (along with PATH setup correctly), not installed via `install.packages`.

Run this in an interactive R console and paste us the output:

```r
system("g++ -v")
system("where make")
```

The second call must give you `c:\Rtools\bin\make.exe` or anything similar.
