### ISSUE TITLE
Gpu acceleration is not obvious

### ISSUE THREAD

**Issue by Jie-Yuan** [microsoft/LightGBM#2450]
Gpu acceleration is not obvious

**Comment by StrikerRUS** [comment]
GPU can be enabled in a super easy way: just set [this param](https://lightgbm.readthedocs.io/en/latest/Parameters.html#device_type).

... And get the following fatal error which says you need to install GPU version:
https://github.com/microsoft/LightGBM/blob/f1a1486929f8e981c44cba45132f5b4929453f8a/src/treelearner/gpu_tree_learner.h#L281-L282

For the GPU installation refer to https://lightgbm.readthedocs.io/en/latest/Installation-Guide.html#build-gpu-version.

**Comment by guolinke** [comment]
GPU could not always accelerate the training. When the #feature is large, the memory copy between gpu and cpu will be large and becomes the bottleneck.
