### ISSUE TITLE
Dockerfile GPU Build Permissions Error

### ISSUE THREAD

**Issue by dalekube** [microsoft/LightGBM#2458]
The standard Dockerfile, [dockerfile.gpu](https://github.com/microsoft/LightGBM/blob/master/docker/gpu/dockerfile.gpu), for the GPU build in a container, results in permissions errors when run as non-root in Kubernetes. The python process appears to be creating directories under the root directory, which is restricted. Most managed Kubernetes clusters force containers to be run as non-root only for security reasons.

https://github.com/microsoft/LightGBM/blob/master/docker/gpu/dockerfile.gpu

## Environment info
Operating System: Linux
CPU/GPU model: GPU Build
C++/Python/R version: Python

## Error message

> Traceback (most recent call last):
>   File "/opt/conda/envs/py3/lib/python3.6/site-packages/traitlets/traitlets.py", line 528, in get
>     value = obj._trait_values[self.name]
> KeyError: 'runtime_dir'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/opt/conda/envs/py3/bin/jupyter-notebook", line 11, in <module>
>     sys.exit(main())
>   File "/opt/conda/envs/py3/lib/python3.6/site-packages/jupyter_core/application.py", line 267, in launch_instance
>     return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
>   File "/opt/conda/envs/py3/lib/python3.6/site-packages/traitlets/config/application.py", line 657, in launch_instance
>     app.initialize(argv)
>   File "</opt/conda/envs/py3/lib/python3.6/site-packages/decorator.py:decorator-gen-7>", line 2, in initialize
>   File "/opt/conda/envs/py3/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
>     return method(app, *args, **kwargs)
>   File "/opt/conda/envs/py3/lib/python3.6/site-packages/notebook/notebookapp.py", line 1676, in initialize
>     self.init_configurables()
>   File "/opt/conda/envs/py3/lib/python3.6/site-packages/notebook/notebookapp.py", line 1349, in init_configurables
>     connection_dir=self.runtime_dir,
>   File "/opt/conda/envs/py3/lib/python3.6/site-packages/traitlets/traitlets.py", line 556, in __get__
>     return self.get(obj, cls)
>   File "/opt/conda/envs/py3/lib/python3.6/site-packages/traitlets/traitlets.py", line 535, in get
>     value = self._validate(obj, dynamic_default())
>   File "/opt/conda/envs/py3/lib/python3.6/site-packages/jupyter_core/application.py", line 99, in _runtime_dir_default
>     ensure_dir_exists(rd, mode=0o700)
>   File "/opt/conda/envs/py3/lib/python3.6/site-packages/jupyter_core/utils/__init__.py", line 13, in ensure_dir_exists
>     os.makedirs(path, mode=mode)
>   File "/opt/conda/envs/py3/lib/python3.6/os.py", line 210, in makedirs
>     makedirs(head, mode, exist_ok)
>   File "/opt/conda/envs/py3/lib/python3.6/os.py", line 210, in makedirs
>     makedirs(head, mode, exist_ok)
>   File "/opt/conda/envs/py3/lib/python3.6/os.py", line 220, in makedirs
>     mkdir(name, mode)
> PermissionError: [Errno 13] Permission denied: '/.local'

**Comment by StrikerRUS** [comment]
@dalekube Please try the fix from #2459. You may need to adjust `CONDA_DIR` value according to your restrictions.
