### ISSUE TITLE
gridsearchcv() freezes? 

### ISSUE THREAD

**Issue by cnglen** [Microsoft/LightGBM#246]
Sometimes(When the param_grid is large) GridSearchCV() freezes. 
Each process use CPU 0%. I have to kill it by C-c C-c.

## Environment info
Operating System: Linux
CPU:
C++/Python/R version: Python

**Comment by wxchan** [comment]
try with smaller data or fewer parameters

**Comment by wxchan** [comment]
there is a gridsearch example in examples/python-guide/sklearn_example.py, can it work on your machine?

**Comment by cnglen** [comment]
It works for small data  or small parameters. 
Maybe the data is too large. 
Finally: I set n_jobs=1.
