### ISSUE TITLE
Changing the name of output prediction file obtained through CLI.

### ISSUE THREAD

**Issue by nalin-mathur** [microsoft/LightGBM#2462]
After having trained a ranking model using the CLI, with lightgbm executable file (obtained after building the repo using cmake) and the 'LightGBM/examples/lambdarank/train.conf'. The model gets saved in a LightGBM_model.txt file.
I am then making predictions using the command './lightgbm config='predict.conf' '.

This predictions obtained get saved in a file named LightGBM_predict_result.txt. Is there a way where I can change the name of the file in which the prediction results are saved?

**Comment by guolinke** [comment]
refer to https://github.com/microsoft/LightGBM/blob/master/docs/Parameters.rst#output_result
