### ISSUE TITLE
[R] Feature importance

### ISSUE THREAD

**Issue by minimaxir** [Microsoft/LightGBM#248]
Feature importance appears to be available in the core binary and accessible by the Python API, but not via the R API.

Is there a way to work around this?

**Comment by minimaxir** [comment]
Implemented in PR https://github.com/Microsoft/LightGBM/pull/257/commits/2d8af6dfc807645bae51122268e236a79a9cfddf

Tested it and it looks great!

**Comment by ZellW** [comment]
Hmm, I just installed lightGBM and I get `Error in lgb.importance(bst, percentage = TRUE) : 
  could not find function "lgb.importance"`
