### ISSUE TITLE
Lambdarank test data with no labels

### ISSUE THREAD

**Issue by wyzrxrs** [microsoft/LightGBM#2490]
Hello, how do you test unseen cases after training the model? I've noticed from the discussions here and the MQ2008 data set, it seems that test data must have a column for labels. I've tested on c code, it returns the following error:
" [LightGBM] [Info] Data file rank.test doesn't contain a label column".

I also experimented on python, the error says "ValueError: invalid literal for float(): 1:0.89 (value of first column, first row from input data)

I am not interested in cross-validation. I'd like to use the model trained from lambdarank on real data without labels. Please advice! Thanks!

**Comment by guolinke** [comment]
How did perform the prediction? Code example? I believe that is a mis-usage.

**Comment by wyzrxrs** [comment]
Thanks for your prompt reply! My code is in fact based on https://mlexplained.com/2019/05/27/learning-to-rank-explained-with-code/. 
x_train, y_train = load_svmlight_file("mq2008.train")
x_valid, y_valid = load_svmlight_file("mq2008.vali")
x_test, y_test = load_svmlight_file("mq2008.test")

q_train = np.loadtxt('mq2008.train.group')
q_valid = np.loadtxt('mq2008.vali.group')
q_test = np.loadtxt('mq2008.test.group')

gbm = lgb.LGBMRanker()
gbm.fit(x_train, y_train, group=q_train, eval_set=[(x_valid, y_valid)],
eval_group=[q_valid], eval_at=[1, 3], early_stopping_rounds=20, verbose=True,
callbacks=[lgb.reset_parameter(learning_rate=lambda x: 0.95 ** x * 0.1)])

preds_train = gbm.predict(x_train)

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
here, the gbm.predict() function takes input the training dataset, which contains labels in the first column.
I removed the first columns, and got the errors.

Could you suggest how to fix this problem? Thanks!

**Comment by guolinke** [comment]
I don't think the `x_train` contains the label, the label is loaded to `y_train`.
And which error is shown? which lightgbm version you are run with?

**Comment by wyzrxrs** [comment]
You are right, thanks very much! 

My question is, since my data has no labels,  and I am only interested in the return value of gbm.predict(x_test), should I create a dummy label, and use load_svmlight_file() to split into x_test and y_test (y_test is faked label)? Will the fake y_test label affect the predict result?

Or, is there another way to use the predict function, for example, preprocess the testing data so it has the same format as x_train?

**Comment by guolinke** [comment]
you don't need the label for the test data, and `predict` method does not the label input as well.
as in your code, using the `gbm.predict(x_test)` is enough. and make the `x_test` have the same shape as the `x_train`.

**Comment by wyzrxrs** [comment]
Great, thanks very much for your prompt replies!!
