### ISSUE TITLE
Parsing the tree model json dump into a data.table structure

### ISSUE THREAD

**Issue by yanyachen** [Microsoft/LightGBM#250]
I think it would be great if we can parse the model object to a data.table structure, so that we can compute advanced feature importance and interaction from it.

I have implemented a simple version in R for doing that, the output is similar to the xgboost::xgb.model.dt.tree function. 

But it require several packages as dependencies (Imports): jsonlite, data.table, magrittr.
I use jsonlite to parse the json file to R list. And the data.table and magrittr package is for data processing, these two packages are already in the "Suggests".

I want to check with members whether adding 3 packages to "Imports" is okay to you guys, or you are planing to do similar things from C++ side. Thanks.

**Comment by guolinke** [comment]
@yanyachen I think it is ok. 
welcome to create PR.

**Comment by yanyachen** [comment]
Close this issue, since PR #253 merged
