### ISSUE TITLE
LGBMRegressor error: NotFittedError: No booster found. Need to call fit beforehand.

### ISSUE THREAD

**Issue by agcala** [microsoft/LightGBM#2505]
**I am running the following code**

    reg = lgb.LGBMRegressor(boosting_type='gbdt',                                               
                            objective='regression', 
                            metric='l2',
                            device='gpu',
                            verbose=1)
    m = MultiOutputRegressor(reg).fit(X_train,y_train) 
    m.estimator.booster_.feature_name()

And I get the error

    sklearn.exceptions.NotFittedError: No booster found. Need to call fit beforehand.

I have just called fit, **_haven't I?_**

I asked the  **scikit-learn** team. They sent me here for answers.

**Comment by StrikerRUS** [comment]
@agcala You should use `estimators_`, not `estimator`.

```
m.estimators_[0].booster_.feature_name()
```

**Comment by agcala** [comment]
**Yikes.** The **scikit-learn** people should have spotted that one. Thank you so much.
