### ISSUE TITLE
Results vary depending on sorting method

### ISSUE THREAD

**Issue by arnonbruno** [microsoft/LightGBM#2508]
Hi,
I'm working on a classification problem where each observation is series of approx 90 features in a given moment of time. All observations are independent.
I noticed that, if I sort my data in ascending order (say, for year) before prediction, I get a result different from what I'd get sorting in descending.
Is this the diserable behaviour? I don't recall this issue happening in the past.

Thanks

**Comment by guolinke** [comment]
@arnonbruno yeah, it is desirable.

Firstly, if you used `bagging`, which uses sub-rows in each iteration, the results will be different.
secondly, the floating-point sum-up will cause the different sum-up results when using different sum-up order.
Finally, LightGBM will use a sub-sampled set (refer to parameter 'bin_construct_sample_cnt` to construct "bin mapper", when the`bin_construct_sample_cnt` is smaller than your #data, the bin mapper may is different.
