### ISSUE TITLE
How to reduce the GPU memory usage?

### ISSUE THREAD

**Issue by sandrawing** [microsoft/LightGBM#2509]
How can I reduce the GPU memory usage in case that my CPU memory is enough and GPU memory is limited?
Besides, what's the function of GPU and CPU when running tree model in LightGBM? Which part of the tree model computation do GPU and CPU process?

**Comment by StrikerRUS** [comment]
Refer to _Huan Zhang, Si Si and Cho-Jui Hsieh. "[GPU Acceleration for Large-scale Tree Boosting](https://arxiv.org/abs/1706.08359)". SysML Conference, 2018._ and https://github.com/microsoft/LightGBM/issues/768#issuecomment-320573774.

Maybe @huanzhang12 can add something.

**Comment by StrikerRUS** [comment]
Please refer to https://github.com/microsoft/LightGBM/issues/2657#issuecomment-570108524.
