### ISSUE TITLE
crash with new version

### ISSUE THREAD

**Issue by cbecker** [Microsoft/LightGBM#251]
I am experiencing a crash when running a simple test case, which seems to be due to commit https://github.com/Microsoft/LightGBM/commit/4948dcc5f1da21e572b283e9ffd3035308055998

I haven't had time to debug it yet, but this is what I get
```
Num classes: 2
[LightGBM] [Info] Number of data: 5000, number of features: 2
Iteration 1
Score: 0.693147
terminate called after throwing an instance of 'std::runtime_error'
  what():  Check failed: buffer[bag_data_cnt - 1] > buffer[bag_data_cnt] at /home/cjb/.conan/data/LightGBM/0.0.1-0/pix4d/testing/build/376ea0804ce8fafcea70f651db612a88f50c6971/LightGBM/src/boosting/gbdt.cpp, line 205 .
```

when running the code here http://pastebin.com/xyhJ97YM

I will take a second look later, but I wanted to leave it here for reference. Maybe this test could be added to the test suite as well.

**Comment by guolinke** [comment]
Thanks!
have fixed, you can try it again.
