### ISSUE TITLE
refit using lgb binary dataset

### ISSUE THREAD

**Issue by aprilffff** [microsoft/LightGBM#2514]
I would like to refit the model using very large dataset (train+valid), so it'll be appericated if refit function accept lgb binary dataset as input. As far as I know, the fitting accuracy wont be different between train and refit, right?

**Comment by guolinke** [comment]
refer to the code:
https://github.com/microsoft/LightGBM/blob/198d0f3bf1d7f183aabaa6ee7d9cc145dd944dcc/python-package/lightgbm/basic.py#L2394

you can pass the `leaf_preds` and `train_set`, then the raw data is not needed.
