### ISSUE TITLE
Are there plans for a go aka golang wrappers or package?

### ISSUE THREAD

**Issue by arnwas** [microsoft/LightGBM#2515]
Are there plans for a go aka golang wrappers or package?

So similarly as those for python or R?

Greetings, Arno

**Comment by StrikerRUS** [comment]
@arnwas Hi! As I know, we don't have any plans for full Go package.

However, there is a Go package for prediction part with LightGBM models. Will [`leaves` package](https://github.com/dmitryikh/leaves) be enough for your task?

Can you please describe your use case?

**Comment by arnwas** [comment]
I am already using Go, mainly for speed reasons, when big amounts are to be prepared, and python's friends e. g. numpy are too slow and consume too much memory. On the other hand i realized lightGBM giving better models, so i wondered how i would combine those two. Rewriting my things in python is not really an option, as i had to give up python for above reasons. If you have suggestions for workarounds feel free to tell me!

**Comment by StrikerRUS** [comment]
Thanks for the explanation!

Seems that https://github.com/dmitryikh/leaves/issues/64 can be treated as upstream issue. However, I'm adding this request in our hub.

**Comment by StrikerRUS** [comment]
Closed in favor of being in #2302. We decided to keep all feature requests in one place.

Welcome to contribute this feature! Please re-open this issue (or post a comment if you are not a topic starter) if you are actively working on implementing this feature.

**Comment by mirekphd** [comment]
>  Rewriting my things in python is not really an option,
Out of genuine interest: would someone interested in following your lead and switching to Go be able to find pandas, numpy, scipy, sklearn, (mlflow, redis, minio) equivalents in Go?

**Comment by arnwas** [comment]
He would, although those might be less well-known. But not all projects do need those, as mine does hardly at all. The only reaason to use numpy would - in my case - be sheer performance, an go does it by itself as opposed to python.
