### ISSUE TITLE
Different scale of sample weight cause different accuracy.

### ISSUE THREAD

**Issue by LaughingGo** [microsoft/LightGBM#2519]
I'm using lightgbm in a regression task. Could anyone tell me that why I get very different result when I just change the sample weight to different scale? 

For example, 
case #1: all the sample weight are 1/N (N is the number of samples),
case #2: all the sample weight are 1,
and the result of case #1 has a big gap with case #2. 

Many thanks for any reply!

**Comment by StrikerRUS** [comment]
Please refer to #905.
