### ISSUE TITLE
More parameters for customized evaluation function?

### ISSUE THREAD

**Issue by sandrawing** [microsoft/LightGBM#2521]
In LightGBM docs, customized evaluation function should accept two parameters: preds, train_data. However, if I need another 1-D array which is not in train_data nor preds to calculate evaluation function (for instance, I want to group the train_data first and then calculate the evaluation function), how can I solve this issue?

**Comment by StrikerRUS** [comment]
@sandrawing You can modify this line to pass more params in `feval` function:
https://github.com/microsoft/LightGBM/blob/7cfb492e7733f73526fbf8958d850bbb94af83ed/python-package/lightgbm/basic.py#L2658
https://github.com/microsoft/LightGBM/blob/7cfb492e7733f73526fbf8958d850bbb94af83ed/R-package/R/lgb.Booster.R#L635
