### ISSUE TITLE
[R-package] Add unit tests for best metric iteration/value

### ISSUE THREAD

**Issue by Laurae2** [microsoft/LightGBM#2525]
After PR https://github.com/microsoft/LightGBM/pull/2471 gets merged, unit tests should be added to ensure correctness of the iteration and value of the best metric during training of a LightGBM model.

A test matrix could be the following:

* Train + 1 metric
* Train + n metric
* n test + 1 metric
* n test + n metric
* Train + n test + 1 metric
* Train + n test + n metric

**Comment by StrikerRUS** [comment]
@Laurae2 Are you going to work on this issue? If not, we should add `help wanted` label and close it according to the feature requests policy.

**Comment by StrikerRUS** [comment]
Closed in favor of being in #2302. We decided to keep all feature requests in one place.

Welcome to contribute this feature! Please re-open this issue (or post a comment if you are not a topic starter) if you are actively working on implementing this feature.

**Comment by jameslamb** [comment]
This has been solved by #2961
