### ISSUE TITLE
standard headers are not found

### ISSUE THREAD

**Issue by gaoJava** [microsoft/LightGBM#2531]
Scanning dependencies of target lightgbm
Scanning dependencies of target _lightgbm
[  4%] Building CXX object CMakeFiles/_lightgbm.dir/src/lightgbm_R.cpp.o
[  4%] Building CXX object CMakeFiles/lightgbm.dir/src/main.cpp.o
[  4%] Building CXX object CMakeFiles/lightgbm.dir/src/application/application.cpp.o
[  6%] Building CXX object CMakeFiles/_lightgbm.dir/src/c_api.cpp.o
In file included from In file included from /Users/apple/LightGBM/src/main.cpp:5:
In file included from /Users/apple/LightGBM/include/LightGBM/application.h:8:
In file included from /Users/apple/LightGBM/include/LightGBM/config.h:12:
/Users/apple/LightGBM/include/LightGBM/meta.h:8:10: fatal error: 'limits' file not found
#include <limits>
         ^~~~~~~~
In file included from /Users/apple/LightGBM/src/c_api.cpp:5:
/Users/apple/LightGBM/include/LightGBM/c_api.h:18:10: fatal error: 'cstdint' file not found
#include <cstdint>
         ^~~~~~~~~
/Users/apple/LightGBM/src/lightgbm_R.cpp:5:
In file included from /Users/apple/LightGBM/include/LightGBM/lightgbm_R.h:8:
/Users/apple/LightGBM/include/LightGBM/c_api.h:18:10: fatal error: 'cstdint' file not found
#include <cstdint>
         ^~~~~~~~~
In file included from /Users/apple/LightGBM/src/application/application.cpp:5:
In file included from /Users/apple/LightGBM/include/LightGBM/application.h:8:
In file included from /Users/apple/LightGBM/include/LightGBM/config.h:12:
/Users/apple/LightGBM/include/LightGBM/meta.h:8:10: fatal error: 'limits' file not found
#include <limits>
         ^~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/lightgbm.dir/src/main.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[  7%] Building CXX object CMakeFiles/_lightgbm.dir/src/application/application.cpp.o
1 error generated.
1 error generated.
make[2]: *** [CMakeFiles/lightgbm.dir/src/application/application.cpp.o] Error 1
make[1]: *** [CMakeFiles/lightgbm.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/_lightgbm.dir/src/lightgbm_R.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[  9%] Building CXX object CMakeFiles/_lightgbm.dir/src/boosting/boosting.cpp.o
In file included from /Users/apple/LightGBM/src/application/application.cpp:5:
In file included from /Users/apple/LightGBM/include/LightGBM/application.h:8:
In file included from /Users/apple/LightGBM/include/LightGBM/config.h:12:
/Users/apple/LightGBM/include/LightGBM/meta.h:8:10: fatal error: 'limits' file not found
#include <limits>
         ^~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/_lightgbm.dir/src/c_api.cpp.o] Error 1
In file included from /Users/apple/LightGBM/src/boosting/boosting.cpp:5:
In file included from /Users/apple/LightGBM/include/LightGBM/boosting.h:8:
In file included from /Users/apple/LightGBM/include/LightGBM/config.h:12:
/Users/apple/LightGBM/include/LightGBM/meta.h:8:10: fatal error: 'limits' file not found
#include <limits>
         ^~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/_lightgbm.dir/src/application/application.cpp.o] Error 1
1 error generated.
make[2]: *** [CMakeFiles/_lightgbm.dir/src/boosting/boosting.cpp.o] Error 1
make[1]: *** [CMakeFiles/_lightgbm.dir/all] Error 2
make: *** [all] Error 2

**Comment by StrikerRUS** [comment]
@gaoJava Please provide info about your environment (it was in the issue template).

**Comment by gaoJava** [comment]
> @gaoJava Please provide info about your environment (it was in the issue template).

**environment**
lightgbm+MacOS+Anaconda 安装
1 macos:  3.1GHz intel core i5
                 8 GB 2133MHz LPDDR3
2 anaconda:  anaconda3
3 python:3.7

**error**
  OSError: dlopen(/Users/{xxx}/anaconda3/lib/python3.6/site- packages/lightgbm/lib_lightgbm.so, 6): Library not loaded: /usr/local/opt/gcc/lib/gcc/7/libgomp.1.dylib
Referenced from: /Users/{xxx}/anaconda3/lib/python3.6/site-packages/lightgbm/lib_lightgbm.so
Reason: image not found

**solution**
1 brew install cmake
2 brew install gcc
3 git clone --recursive https://github.com/Microsoft/LightGBM ; cd LightGBM.        
4 cmake -DCMAKE_CXX_COMPILER=$(which g++) -DCMAKE_C_COMPILER=$(which gcc) ./
5 clang-omp
   First, the default clang does not support OpenMP, so you need a special one:
6 brew install clang-omp
   CMakeLists.txt
   Second, CMakeLists.txt needs a few changes:
   set(CMAKE_C_COMPILER clang-omp CACHE STRING "C compiler" FORCE)
   set(CMAKE_CXX_COMPILER clang-omp++ CACHE STRING "C++ compiler" FORCE)
   find_package(OpenMP REQUIRED)
   set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${OpenMP_C_FLAGS}")
   set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${OpenMP_CXX_FLAGS}")
   set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS}
   ${OpenMP_EXE_LINKER_FLAGS}")
7 CC=clang-omp CXX=clang-omp++ cmake /path/to/source/
8 make -j4( That's what happened when I did step eight.)

**Comment by gaoJava** [comment]
thanks,This problem has been solved,The reason is that I should use root to perform these steps.
