### ISSUE TITLE
How does  lgb handles category features internally? 

### ISSUE THREAD

**Issue by cnglen** [Microsoft/LightGBM#254]
two questions:

1. How does  lgb handles category features internally? 

2. How does  lgb handles "null"?  Like xgboost? Try split left and right, and chooses the best one?

Thanks.

**Comment by chivee** [comment]
I'm not quite understand what you are asking.
the usage of LightGBM or how the LightGBM works?

category can be set at: 
https://github.com/Microsoft/LightGBM/blob/master/docs/Parameters.md#io-parameters

**Comment by cnglen** [comment]
@chivee 
How the LightGBM works? (for category features)

**Comment by guolinke** [comment]
categorical features support is deprecated now.

**Comment by WangHanbin** [comment]
I found that the categorical features support is deprecated when the LightGBM v2 released. However, it is added back 2 days ago(2017.3.1). I wonder to know what are the reasons behind the engineering or algorithm itself?

**Comment by wxchan** [comment]
@WangHanbin refer to #319

**Comment by AbdealiJK** [comment]
Now that the categorical feature support is back - coming back to the original question ... is there any documentation on how the categorical features are handled internally ?

**Comment by guolinke** [comment]
@AbdealiJK 
it is basically the same as one-hot coding explicitly. 
but we are refining it : https://github.com/Microsoft/LightGBM/issues/699
