### ISSUE TITLE
Tune parameters for quantile regression

### ISSUE THREAD

**Issue by lpolisi** [microsoft/LightGBM#2546]
I have a problem where I will need to compute both predictions and some type of uncertainty along with the predictions. I've come across quantile regression which is available in LightGBM.

With this method, I will basically need three models. One for the lower bound, one for the higher bound and then the usual mean predictions.

How should the parameter tuning be done for these three models?

1. Should they all be tuned separately such that I do a full grid search on all three models?

2. Should the two quantile regressors have the same hyper parameters and then only do two grid searches, one for the quantile regressors and one for the mean predictions?

3. Should they all use the same hyper parameters that are found for the model for the mean predictions?

**Comment by StrikerRUS** [comment]
@lpolisi I think that StackOverflow is a better place to ask questions of a such type with the aim to get more answers. You can start reading from the following tutorials:
https://medium.com/@qucit/a-simple-technique-to-estimate-prediction-intervals-for-any-regression-model-2dd73f630bcb
https://towardsdatascience.com/regression-prediction-intervals-with-xgboost-428e0a018b
https://scikit-learn.org/stable/auto_examples/ensemble/plot_gradient_boosting_quantile.html
