### ISSUE TITLE
lightgbm.basic.LightGBMError: Cannot add validation data, since it has different bin mappers with training data

### ISSUE THREAD

**Issue by kangshaoshun** [microsoft/LightGBM#2547]
## Environment info

Operating System:

CPU/GPU model:

C++/Python/R version:
python3.6
LightGBM version or commit hash:
2.1.2
## Error message

raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))
lightgbm.basic.LightGBMError: Cannot add validation data, since it has different bin mappers with training data

## Reproducible examples

```
def load_oot_dataset(oot_data_path):
    oot_dataset_list = []
    for oot_cur_path in oot_data_path.split(","):
        #not work
        oot_cur_dataset = lgb.Dataset(oot_cur_path)
        oot_dataset_list.append(oot_cur_dataset)

        #work
        oot_cur_data = load_svmlight_file(oot_cur_path)
        oot_cur_dataset = lgb.Dataset(oot_cur_data[0], label=oot_cur_data[1])
        oot_dataset_list.append(oot_cur_dataset)
    return oot_dataset_list

train_dataset = load_train_data(args.trainf)
oot_dataset_list = load_oot_dataset(args.ootf)
bst = lgb.train(param, train_dataset, valid_sets=oot_dataset_list)
```

"""
## Steps to reproduce

the same valid data,  load into lgb.Dataset by the lgb.Dataset(path), and set valid_sets not work.
chage into lgb.Dataset(data, label=...) works. 

why ?

**Comment by guolinke** [comment]
you should set the `reference` to the validation sets.

**Comment by StrikerRUS** [comment]
Or use `create_valid` method.

https://lightgbm.readthedocs.io/en/latest/pythonapi/lightgbm.Dataset.html#lightgbm.Dataset.create_valid
