### ISSUE TITLE
What does `FeatureMetainfo.bias` mean? 

### ISSUE THREAD

**Issue by Yellow-Duck-Type** [microsoft/LightGBM#2561]
Hello there, I would like to know if anyone could explain a little bit about `FeatureMetainfo.bias`?
The only place modifying this value is in `HistogramPool.DynamicChangeSize`
```
        if (train_data->FeatureBinMapper(i)->GetDefaultBin() == 0) {
          feature_metas_[i].bias = 1;
        } else {
          feature_metas_[i].bias = 0;
        }
```
But `BinMapper.GetDefaultBin()` is the bin index for feature value 0.0f. 
Since for **numerical feature**, the bins are ordered from low to high values, `BinMapper.GetDefaultBin() == 0` means all of a feature's values >=0.
For **categorical feature**, we always have `BinMapper.GetDefaultBin() > 0`.
Does `FeatureMetainfo.bias` means this feature is biased? Does it makes a difference if a feature's value >=0? 

I saw `FeatureMetainfo.bias` is frequently used in the code, e.g.:
`FeatureHistogram.FindBestThresholdSequence`: Suppose NOT using NAN as missing
- Swipe Bin from Right:
  - `num_bin_ - 1` to `1` if bias is `0`
  - `num_bin_ - 2` to `0` if bias is `1`
- Swipe Bin from Left:
  - `0` to `num_bin_ - 2` no matter whether bias is `0` or `1`
What does the `bias` mean here?

Thanks for answering!

**Comment by guolinke** [comment]
it is offset.

**Comment by guolinke** [comment]
The histogram actually is not fully scanned. For the "offset=1", you can skip the first bin, by the subtraction of other bins.

**Comment by Yellow-Duck-Type** [comment]
Thanks for explaining!

**Comment by Yellow-Duck-Type** [comment]
> The histogram actually is not fully scanned. For the "offset=1", you can skip the first bin, by the subtraction of other bins.

Could you please explain a little bit more about the **benefit** of this?
For every node split, the histogram is scanned twice: from left and from right. I observed the only difference of the 2 scans are the skipped bins. If it does not skip bins, could it only scan once? That probably saves a good amount of time.

**Comment by guolinke** [comment]
the default_bin could be the missing value (when missing_type is zero and default_bin is zero). Then it could be in left or right side.
https://github.com/microsoft/LightGBM/blob/master/src/treelearner/feature_histogram.hpp#L97-L111

**Comment by Yellow-Duck-Type** [comment]
> the default_bin could be the missing value (when missing_type is zero and default_bin is zero). Then it could be in left or right side.
> https://github.com/microsoft/LightGBM/blob/master/src/treelearner/feature_histogram.hpp#L97-L111

Thanks for explaination!
I understand if `skip_default_bin` is **True**, the default bin gradient and hessian will be put on left or right according to `dir`, just like the `use_na_as_missing=True` case.
However, I thought this feature is already achieved by line:
https://github.com/microsoft/LightGBM/blob/3e3d76f64bfa3d95f9769bd82be7124158ff3df7/src/treelearner/feature_histogram.hpp#L529
https://github.com/microsoft/LightGBM/blob/3e3d76f64bfa3d95f9769bd82be7124158ff3df7/src/treelearner/feature_histogram.hpp#L587
Why is `default_bin == 0` different from `default_bin != 0`, so that it needs to be handled by an **extra** variable `offset`?

Moreover, `offset` does **more** than putting the `default_bin` on either left or right side: It also (intentionally or accidentally?)**put the last bin(which is a normal bin)** on left or right in certain conditions. 
Please see below case:
Suppose `offset=1`( `default_bin == 0`), `dir=-1`(put on left), `skip_default_bin=True` and `use_na_as_missing=False`:
On lines: https://github.com/microsoft/LightGBM/blob/3e3d76f64bfa3d95f9769bd82be7124158ff3df7/src/treelearner/feature_histogram.hpp#L523-L524
```
int t = meta_->num_bin - 2; // The last bin num_bin - 1 is skipped, but it is not NaN bin because use_na_as_missing=False
const int t_end = 0;
for (; t >= t_end; --t) {
...
```

**Comment by guolinke** [comment]
I remember when offset=1,  the histogram actually only contains (num_bin -1) bins. The last bin is `num_bin -2`.
