### ISSUE TITLE
mape metrics calculate result not equal to the equation

### ISSUE THREAD

**Issue by cyhong549** [microsoft/LightGBM#2566]
In the mape metrics, the calculation code is below, for my understanding, it may avoid the unlimit inf value, however, it will cause the error result when label is small. should we reduce the 1.0f or it is a bug? 

std::fabs((label - score)) / std::max(1.0f, std::fabs(label));

## Environment info

Operating System:linux

CPU/GPU model:cpu

C++/Python/R version:python

LightGBM version or commit hash: lgb version 2.3.0

**Comment by guolinke** [comment]
This is by design. 
And when label is small, the mape is naturally unstable. 
It is better to use mape for non small lables.
