### ISSUE TITLE
Why labels in dataset are float32 only?

### ISSUE THREAD

**Issue by yekimov** [microsoft/LightGBM#2570]
I've delved some source code, and have found that labels for datasets can have only float32[] type.
I wonder why is there such restriction exists? Won't it be segnificant restriction if I want to
predict big numbers, like hundreds of millions or maybe billions?

Sorry for my English, thanks.

**Comment by StrikerRUS** [comment]
It's done for better memory usage and speed.
You can use `double` (#1120): 
https://github.com/microsoft/LightGBM/blob/26ff099ab47cd98f7613503ff5976f7359e3465b/include/LightGBM/meta.h#L23-L24
However, it's better to transform your labels before training.
