### ISSUE TITLE
Output tree structure to dataframe

### ISSUE THREAD

**Issue by pford221** [microsoft/LightGBM#2578]
Hi -

Similar to how XGBoost provides a method for its Booster class to output the tree structures learned to a Pandas.DataFrame, would the maintainers have interest in having something similar for LightGBM?

I have a prototype working with Python API that I could clean up and submit a PR?

Here's the XGBoost Python implementation:
https://github.com/dmlc/xgboost/blob/master/python-package/xgboost/core.py#L1712

**Comment by StrikerRUS** [comment]
Hi @pford221 !

Sure, go for it!

As I can observe, users are often interested in everything connected to model exploration.

**Comment by StrikerRUS** [comment]
Closed via #2592.
