### ISSUE TITLE
Merge Dataset objects on condition that they hold same binmapper

### ISSUE THREAD

**Issue by aprilffff** [microsoft/LightGBM#2579]
## Summary
need a function to add more samples(lgb.Dataset) to another lgb.Dataset if they have same bin_mapper

## Motivation
I would like to retrain the model with train+valid data without reconstructing lgb.Dataset using huge raw data.

**Comment by StrikerRUS** [comment]
Closed in favor of being in #2302. We decided to keep all feature requests in one place.

Welcome to contribute this feature! Please re-open this issue (or post a comment if you are not a topic starter) if you are actively working on implementing this feature.
