### ISSUE TITLE
Question about category feature in model file

### ISSUE THREAD

**Issue by ltzhang12** [microsoft/LightGBM#2582]
In the saved model file, for the category feature, the split threshold are as  0,1,2,3,4,5... , not the category feature_names or feature_infos. So How I can get the concrete category_feature? Does the cat_threshold or cat_boundaries helpful?  
Thanks.

**Comment by StrikerRUS** [comment]
I guess you are searching for something like this https://github.com/microsoft/LightGBM/issues/2234#issuecomment-504061840, aren't you?

**Comment by ltzhang12** [comment]
> I guess you are searching for something like this [#2234 (comment)](https://github.com/microsoft/LightGBM/issues/2234#issuecomment-504061840), aren't you?

**Comment by ltzhang12** [comment]
> I guess you are searching for something like this [#2234 (comment)](https://github.com/microsoft/LightGBM/issues/2234#issuecomment-504061840), aren't you?

Yes, Thanks
