### ISSUE TITLE
Extremely randomized trees

### ISSUE THREAD

**Issue by joegaotao** [microsoft/LightGBM#2583]
The variety of mdels plays an important role in model ensemble. I tried some parameters such as "colsample_bytree, colsample_bynode" to make model more stable and different, but trees still grow by some criterion, resulting in the similar models. However, I tried the combination "extratree+lgb", and randomized tree could be used as the certain feature embeding tool  that improves model variety. So I suggest adding extremely randomized tree as base learner.

**Comment by StrikerRUS** [comment]
Closed in favor of being in #2302. We decided to keep all feature requests in one place.

Welcome to contribute this feature! Please re-open this issue (or post a comment if you are not a topic starter) if you are actively working on implementing this feature.

**Comment by StrikerRUS** [comment]
Opening as we have active PR for this feature: #2671.

**Comment by StrikerRUS** [comment]
Closed via #2671.
