### ISSUE TITLE
[Documentation Needed] LightGBM on Kubernetes

### ISSUE THREAD

**Issue by cyzhangchenya** [microsoft/LightGBM#2584]
## Summary

Documentation for LightGBM on Kubernetes is missing.

## Motivation

LightGBM is already supported in Kubeflow 2019 May. https://github.com/kubeflow/fairing/issues/242

## Description

The documentation for "Distributed XGBoost with Kubernetes" is a good example.
https://xgboost.readthedocs.io/en/latest/tutorials/kubernetes.html

## References

https://xgboost.readthedocs.io/en/latest/tutorials/kubernetes.html

**Comment by jameslamb** [comment]
Thank you for pointing this out for us @cyzhangchenya ! Was not aware that support for `LightGBM` had been added in kubeflow, that's fantastic.

Would you like to contribute this documentation? If not, I'll close the issue and add it to our catch-all feature request issue #2302

**Comment by StrikerRUS** [comment]
According to the `Followup task #2`, there should be `Detailed documentation` released in their repo. I think we can wait for it and provide a link from our docs to it. It will allow to avoid copy-pasting and the need to update that guide from our side for changes happen at their side.

In other words, I don't think that we should document something that we do not maintain.

https://github.com/kubeflow/fairing/pull/252

**Comment by StrikerRUS** [comment]
Unfortunately, I'm not familiar with kurerflow. Will these links be enough to get started?
- [Folder with example Notebooks](https://github.com/kubeflow/fairing/tree/master/examples/lightgbm).
- [API reference](https://kubeflow-fairing.readthedocs.io/en/latest/source/kubeflow.fairing.frameworks.html#module-kubeflow.fairing.frameworks.lightgbm).
