### ISSUE TITLE
Categorical feature support with string

### ISSUE THREAD

**Issue by henry0312** [Microsoft/LightGBM#259]
Currently, LightGBM supports categorical feature with only int type.
Is it possible (and easy) to support not only int type but also strng?

**Comment by guolinke** [comment]
@henry0312 It will increase complexity of IO part.
Actually, we are refining the support of categorical features. 
Will come out a better solution in next release.

**Comment by henry0312** [comment]
Hum, I see.
I'm looking forward to the nex release :)
