### ISSUE TITLE
reset_param feature_contrib not fixed 

### ISSUE THREAD

**Issue by aprilffff** [microsoft/LightGBM#2590]
this bug is mentioned and fixed below,but found not really fixed. pls check again
[#2452](https://github.com/microsoft/LightGBM/issues/2452) 
[#2453](https://github.com/microsoft/LightGBM/issues/2453)

**Comment by guolinke** [comment]
Refer to this comment: https://github.com/microsoft/LightGBM/pull/2453#issuecomment-558070708

**Comment by guolinke** [comment]
actually, I am thinking about moving these changeable parameters from Dataset to config. Then, we can keep the Dataset fixed, without worrying about these parameter belonging issues.
@StrikerRUS what do you think?

**Comment by StrikerRUS** [comment]
I'd like to say that I think maybe not the main problem but very related one is that users cannot distinguish between Dataset and Booster params. There is no differentiation in params list because there are no such abstractions in CLI version. Refer to #2535, #2517, #2398.

**Comment by guolinke** [comment]
yeah, I think we could a refactoring for these parameters and avoid these confuses.
