### ISSUE TITLE
Use initial score for multiclass objective

### ISSUE THREAD

**Issue by matanschlesinger** [microsoft/LightGBM#2595]
Hi,
I'm trying to use a custom initial score on a multiclass problem (three classes), and can't find if and how is it possible.

Does LightGBM supports this feature? and if yes, how can I set the initial score for all three classes?

Thanks,

**Comment by guolinke** [comment]
refer to code here: https://github.com/microsoft/LightGBM/blob/102893a11c1dd712bb70d87b3b129ddf42daf06f/src/io/metadata.cpp#L390-L434
you can use the tsv format. One line for one sample.
For python package, you can just set the init_score by [n, k] array, where k is the number of classes.
