### ISSUE TITLE
[Feature] silence the progress or verbosity

### ISSUE THREAD

**Issue by fengqifang** [Microsoft/LightGBM#26]
Is there any way to silence the progress?

If I do not want the output "[LightGBM] 1.501629 seconds elapsed, finished 50 iteration]"

**Comment by wxchan** [comment]
Try to comment out the line `Log::Stdout("%f seconds elapsed, finished %d iteration", std::chrono::duration<double, std::milli>(end_time - start_time) * 1e-3, iter + 1);` in src/gdbt.cpp and recompile.

**Comment by fengqifang** [comment]
Thanks, wxchan.

It would be better put that option in conf

**Comment by chivee** [comment]
@fengqifang , thanks for your advice, we will update the log level settings

**Comment by guolinke** [comment]
The contribute about this is also welcomed

**Comment by chivee** [comment]
I will add this feature soon.

**Comment by wxchan** [comment]
Not sure what people actually need. If the silence parameter exists, which parts of output would disappear? 

I have another suggestion: if run lightgbm without 'config=', it will show some helps about configurations like [libsvm](https://github.com/cjlin1/libsvm/blob/master/svm-train.c#L13) does.

**Comment by chivee** [comment]
@wxchan ,we are adding an optional logger for lightGBM, with which you can set your logging levels to choose the verbosity.

we can adding some -h --help options for this case.
