### ISSUE TITLE
'mutex' in namespace 'std' does not name a type on win10 64

### ISSUE THREAD

**Issue by jiliguluss** [microsoft/LightGBM#2608]
## Environment info

Operating System:
windors10 64bit

CPU/GPU model:

C++/Python/R version:
MinGW64
gcc version 8.1.0 (x86_64-win32-seh-rev0, Built by MinGW-W64 project)

LightGBM version or commit hash:

## Error message

C:/Users/Downloads/LightGBM/include/LightGBM/utils/openmp_wrapper.h:42:8: error: 'mutex' in namespace 'std' does not name a type
   std::mutex lock_;
        ^~~~~
C:/Users/Downloads/LightGBM/include/LightGBM/utils/openmp_wrapper.h:42:3: note: 'std::mutex' is defined in header '<mutex>'; did you forget to '#include <mutex>'?
C:/Users/Downloads/LightGBM/include/LightGBM/utils/openmp_wrapper.h:15:1:
+#include <mutex>
 #include <stdexcept>
C:/Users/Downloads/LightGBM/include/LightGBM/utils/openmp_wrapper.h:42:3:
   std::mutex lock_;
   ^~~
C:/Users/Downloads/LightGBM/include/LightGBM/utils/openmp_wrapper.h: In member function 'void ThreadExceptionHelper::CaptureException()':
C:/Users/Downloads/LightGBM/include/LightGBM/utils/openmp_wrapper.h:35:27: error: 'mutex' is not a member of 'std'
     std::unique_lock<std::mutex> guard(lock_);
                           ^~~~~
C:/Users/Downloads/LightGBM/include/LightGBM/utils/openmp_wrapper.h:35:27: note: 'std::mutex' is defined in header '<mutex>'; did you forget to '#include <mutex>'?
C:/Users/Downloads/LightGBM/include/LightGBM/utils/openmp_wrapper.h:35:27: error: 'mutex' is not a member of 'std'
C:/Users/Downloads/LightGBM/include/LightGBM/utils/openmp_wrapper.h:35:27: note: 'std::mutex' is defined in header '<mutex>'; did you forget to '#include <mutex>'?
C:/Users/Downloads/LightGBM/include/LightGBM/utils/openmp_wrapper.h:35:32: error: template argument 1 is invalid
     std::unique_lock<std::mutex> guard(lock_);
                                ^
C:/Users/Downloads/LightGBM/include/LightGBM/utils/openmp_wrapper.h:35:40: error: In file included from '
' was not declared in this scope
     std::unique_lock<std::mutex> guard(C:/Users/Downloads/LightGBM/include/LightGBM/utils/common.h:9lock_);
                                        ,
                 from ^~~~~C:/Users/Downloads/LightGBM/include/LightGBM/config.h:13
,
                 from C:/Users/Downloads/LightGBM/include/LightGBM/application.h:8,
                 from C:\Users\Downloads\LightGBM\src\main.cpp:5C:/Users/Downloads/LightGBM/include/LightGBM/utils/openmp_wrapper.h:35:40::
 C:/Users/Downloads/LightGBM/include/LightGBM/utils/openmp_wrapper.h:42:8:note:  suggested alternative: 'error: clock''
     std::unique_lock<std::mutex> guard(mutexlock_' in namespace ');
                                        std^~~~~' does not name a type
   std::
                                        mutexclock lock_;

C:/Users/Downloads/LightGBM/include/LightGBM/utils/openmp_wrapper.h:35:34: warning: ^~~~~unused variable '
C:/Users/Downloads/LightGBM/include/LightGBM/utils/openmp_wrapper.h:42:3:guard ' [note: -Wunused-variable']
     std::unique_lock<std::mutex> guardstd::mutex' is defined in header '(lock_);
                                  <mutex>^~~~~'; did you forget to '
#include <mutex>'?

## Steps to reproduce

Does windows not support mutex? How should I fix this?

**Comment by guolinke** [comment]
it seems is the mingw problem: https://stackoverflow.com/questions/14191566/c-mutex-in-namespace-std-does-not-name-a-type

we recommend using vc++ in Windows.

**Comment by StrikerRUS** [comment]
Also refer to https://github.com/microsoft/LightGBM/issues/2593#issuecomment-558749711. Please make sure to use MinGW-w64 with posix threads.
