### ISSUE TITLE
Have Application::InitPredictByData and Application::PredictByData been cancelled?

### ISSUE THREAD

**Issue by jiliguluss** [microsoft/LightGBM#2609]
## Environment info

Operating System:

CPU/GPU model:

C++/Python/R version:

LightGBM version or commit hash:

## Error message
I received project from others. In the project, the appliction.h is different with the github. There are two member functions and one constructor function that I don't find in the github:
  Application(char *model_filename, char *config_file);
  
  void InitPredictByData();
  
  void PredictByData(std::vector<std::string>& vector_datas, int label_index, std::map<int,  std::vector<double> >& result);

## Steps to reproduce

1. Are the three functions been cancelled? Can I still use Application and InitPredictByData to load the model, and then use PredictByData to predict data?
2. What's the difference between predict through Application::Predict and LGBM_BoosterCreateFromModelfile+LGBM_BoosterPredictForMat?

**Comment by StrikerRUS** [comment]
1. You can use GitHub history to check that.
    https://github.com/microsoft/LightGBM/commits/master/include/LightGBM/application.h
    Seems that they have never been there. So you should ask those from whom you got your fork code.
2. `Application::Predict` is for CLI, while `LGBM_Booster*` are C API functions, refer to the code
https://github.com/microsoft/LightGBM/blob/6129208006c91f9ac94891690aca6f0c49d9b08e/src/application/application.cpp#L214
https://github.com/microsoft/LightGBM/blob/6129208006c91f9ac94891690aca6f0c49d9b08e/src/c_api.cpp#L1074
https://github.com/microsoft/LightGBM/blob/6129208006c91f9ac94891690aca6f0c49d9b08e/src/c_api.cpp#L1429
