### ISSUE TITLE
Need much more tests

### ISSUE THREAD

**Issue by henry0312** [microsoft/LightGBM#261]
It's necessary to write much more tests to keep the quality of LightGBM.
I can contribute to python-package.

TODO:

- [ ] Tests for C++
- [x] Tests for Python
- [ ] Tests for R

**Comment by chivee** [comment]
That will be great! Please help us on the test, and leveraging travis for a better release strategies. we are planing a better versioning for the release, so that the package users can stick to the stable version

**Comment by wxchan** [comment]
Adding some tests on multi-class and lambdarank tasks will be great.

**Comment by henry0312** [comment]
I start with python-package from today :)

**Comment by Laurae2** [comment]
@henry0312 tests are completed for Python I think. For R we need to setup Travis for it.

**Comment by henry0312** [comment]
@Laurae2 no, the current tests doesn't cover all of the python-package.

@wxchan I'd like to use [nose](http://nose.readthedocs.io/en/latest/index.html). What do you think about nose?

**Comment by henry0312** [comment]
I'll go with [nose](http://nose.readthedocs.io/en/latest/index.html)

**Comment by StrikerRUS** [comment]
@b1shal711 It will be great!

**Comment by StrikerRUS** [comment]
Closed in favor of being in #2302. We decided to keep all feature requests in one place.

Welcome to contribute this feature! Please re-open this issue (or post a comment if you are not a topic starter) if you are actively working on implementing this feature.

**Comment by StrikerRUS** [comment]
@jameslamb Thanks to all your hard work, I believe we can tick `Tests for R` now in the original comment. WDYT?

**Comment by jameslamb** [comment]
I think so, yes! I think the R tests are in a much better place than they were when this issue was opened
