### ISSUE TITLE
mistake in doc : Categorical features must be encoded as non-negative integers 

### ISSUE THREAD

**Issue by Sandy4321** [microsoft/LightGBM#2616]
is mistaken in your doc
Categorical features must be encoded as non-negative integers (int) less than Int32.MaxValue (2147483647). It is best to use a contiguous range of integers started from zero

from
https://lightgbm.readthedocs.io/en/latest/Advanced-Topics.html

when we see in 
https://github.com/Microsoft/LightGBM/blob/3400e3899d1c45997337bdbd0c8a2f729e805cbc/tests/python_package_test/test_engine.py#L477-L510

X = pd.DataFrame({"A": np.random.permutation(['a', 'b', 'c', 'd'] * 75),  # str

by the way 
is it possible to use target as categorical as well for example yes and no
instead 0 and 1
as in line 482
y = np.random.permutation([0, 1] * 150)

**Comment by StrikerRUS** [comment]
@Sandy4321 You're referring to CLI version documentation, not Python one.

**Comment by Sandy4321** [comment]
great thanks
so how to make sure we use correct documentation
for example
where it is written in documentation that :"It doesn’t need to convert to one-hot coding, and is much faster than one-hot coding (about 8x speed-up)"

per
Specific feature names and categorical features:train_data = lgb.Dataset(data, label=label, feature_name=['c1', 'c2', 'c3'], categorical_feature=['c3'])LightGBM can use categorical features as input directly. It doesn’t need to convert to one-hot coding, and is much faster than one-hot coding (about 8x speed-up).https://lightgbm.readthedocs.io/en/latest/Python-Intro.html


this link
https://lightgbm.readthedocs.io/en/latest/Parameters.html
relates to all options ? 
as it is written : This page contains descriptions of all parameters in LightGBM

or not ?
for example 
1
is_unbalance can not be used for 
https://lightgbm.readthedocs.io/en/latest/pythonapi/lightgbm.LGBMClassifier.html#lightgbm.LGBMClassifier ?

2
can 
https://lightgbm.readthedocs.io/en/latest/pythonapi/lightgbm.cv.html#lightgbm.cv
be used with LGBMClassifier  if yes then how ? where is example?

**Comment by StrikerRUS** [comment]
> so how to make sure we use correct documentation

Read document's title, I guess.

> this link
https://lightgbm.readthedocs.io/en/latest/Parameters.html
relates to all options ?

Yes. Pay attention to notes below some params.

> 1
is_unbalance can not be used for
https://lightgbm.readthedocs.io/en/latest/pythonapi/lightgbm.LGBMClassifier.html#lightgbm.LGBMClassifier ?

Yes.

> 2
can
https://lightgbm.readthedocs.io/en/latest/pythonapi/lightgbm.cv.html#lightgbm.cv
be used with LGBMClassifier if yes then how ? where is example?

No. The are different APIs. 


Python examples (if you need them) are in this folder: https://github.com/microsoft/LightGBM/tree/master/examples/python-guide.

**Comment by Sandy4321** [comment]
so how to make sure we use correct documentation

Read document's title, I guess.

this link
https://lightgbm.readthedocs.io/en/latest/Parameters.html
relates to all options ?

Yes. Pay attention to notes below some params.
You are mistaken
Try answer again
Think what is related to cli and what is not
Try to be serious: most of your answers are mistaken

1
is_unbalance can not be used for
https://lightgbm.readthedocs.io/en/latest/pythonapi/lightgbm.LGBMClassifier.html#lightgbm.LGBMClassifier ?

Yes, it can be
Mistake again it can not be
To treat unbalanced data another parameter used
You make shame on Microsoft by your unprofessional answers

**Comment by StrikerRUS** [comment]
Being toxic is the most unprofessional thing. This is unacceptable and we will not tolerate it here.

I was completely serious and all of my answers above is correct. You can check it.

**Comment by guolinke** [comment]
@Sandy4321 most of the documents are maintained by @StrikerRUS , thanks for his great efforts in his sparse time. And I believe he is right for your questions.

For the issue discussion, please keep it objective. If you believe there are still problems, please prove it, such as the reproducing code.

**Comment by guolinke** [comment]
@StrikerRUS maybe we need to add notes to https://lightgbm.readthedocs.io/en/latest/Parameters.html#categorical_feature , to clarify the python package (specifically, pandas) could pass the categorical values directly.

**Comment by StrikerRUS** [comment]
Thank you, @guolinke !

>maybe we need to add notes to https://lightgbm.readthedocs.io/en/latest/Parameters.html#categorical_feature , to clarify the python package (specifically, pandas) could pass the categorical values directly.

I think it makes sense.
