### ISSUE TITLE
Basic user guide for C-API?

### ISSUE THREAD

**Issue by duckladydinh** [microsoft/LightGBM#2625]
Hi,

I want to create some Java/Kotlin API for my personal project, which means I need to use the C API, but to be honest, I am lost. Is there any better documentation for the C-API? I am not asking for the complete documentation, but something like an example (in code) for performing a simple binary classification with the C API for example. Is there anyone using it for your project? Would you mind sharing an example for reference? An example speaks a thousand times louder than documentation.

Right now, I am stuck at the following:
1. What exactly is the 'handle'? Like the handle of dataset and the handle or booster? What role do they play?
2. What are the parameters of data? I know training has parameters, but this is the first time I know that data also has some?
3. How to specify the 'label' (as in Python) for the data? I mean, the parameter in the DatasetCreateFromMath only has a pointer to the whole C 2D Matrix (actually 1D). It has no way to specify the label.

For now, I only have these questions, because I am too stuck to continue :'(. If I cannot understand them, my only choice would be to call the command line from Java, which I am not sure if there will be any overhead.

Please, could someone share your experience.

Happy Coding!

**Comment by guolinke** [comment]
refer to our python/R package, they are all based on C API.

**Comment by guolinke** [comment]
for your other questions:
1. handle is the pointer to the object (Dataset or Booster). It is like a key to access the cpp object in other languages like python.
2. As LightGBM will bucket the floating values to the discrete values, there are some parameters to control the process. such as `max_bin`. 
3. https://github.com/microsoft/LightGBM/blob/9fd378e2bc95bbe9c85a4478bb3112c354fbbb59/python-package/lightgbm/basic.py#L1371-L1389

**Comment by StrikerRUS** [comment]
Also, I believe, C API test may help to get familiar with the basic usage:
https://github.com/microsoft/LightGBM/blob/master/tests/c_api_test/test_.py

**Comment by duckladydinh** [comment]
Hi @StrikerRUS and @guolinke , thank you! Actually I already figured them out and already built some Kotlin bindings for it, but I forgot to close the issue :) . Thanks
