### ISSUE TITLE
code example "monotone_constraints"  parameter for LGBMClassifier

### ISSUE THREAD

**Issue by Sandy4321** [microsoft/LightGBM#2626]
Can you pls help find code example how to use 
"monotone_constraints"  parameter for LGBMClassifier
at least for binary classification for example target is yes and no

to see how useful it is in improving performance for example F1
Thanks

**Comment by guolinke** [comment]
refer to our test:
https://github.com/microsoft/LightGBM/blob/master/tests/python_package_test/test_engine.py#L869-L907

**Comment by Sandy4321** [comment]
Thanks for soon answer
As I can see 
This code provides only functionality testing
But not performance improvement from using monotone constraints vs case not using monotone constraints for the same data
Am I right ?
If yes
Then for sure you did in another place  this kind of compression for classifying using Python or at least not Python
It would be great to share this code and test results ...

**Comment by guolinke** [comment]
I don't believe that mc constraints could always bring the improvement. It depends on your data and task.

**Comment by Sandy4321** [comment]
It is the point
To see real case when it helps
And also key word is calssifier but not regression
Meaning how to choose right direction of monotonicity for features for binary targets 
For example target had 2 states
One 'big'
Second 'small'
So not 0 and 1
