### ISSUE TITLE
Possible Bug: C API does not have anyway to input missing values!!!

### ISSUE THREAD

**Issue by duckladydinh** [microsoft/LightGBM#2629]
Hi,

I tried to search for it, but the C-API does not seems to have anyway to input missing values. Is this a bug or hidden somewhere? If I have missing value in my CSV, how can I input it using the C-API?

Thanks!

**Comment by guolinke** [comment]
you can use zero as missing value (need to set `zero_as_missing=true`), or use the nan (the float/double format, not the string format) in your data directly.
