### ISSUE TITLE
continue-train/predict from binary dataset

### ISSUE THREAD

**Issue by aprilffff** [microsoft/LightGBM#2636]
https://github.com/microsoft/LightGBM/pull/2252#issuecomment-509637035

**Comment by aprilffff** [comment]
I looked through the fixed and comments about this issue (#2252 ) but cannot figure out why need rawdata to continue train. My raw data is really big so has to constructed into binary file, so continue train from binary is needed in my case.

**Comment by guolinke** [comment]
LGBM_BoosterGetPredict is not for prediction for bin dataset. It is only used in training and store the training scores. After loading booster from file, there is not way to predict for bin dataset.
