### ISSUE TITLE
Support ingestion of training data from parquet files in the CLI version

### ISSUE THREAD

**Issue by ogru** [microsoft/LightGBM#2638]
## Summary
Implement a feature for ingesting the training data from multiple parquet files with the CLI version. 

## Motivation

In memory efficient model fitting with big data we are often utilizing the CLI version to read the data and then convert it into binaries in order to reduce the memory footprint. There are two bottlenecks with such approach: 1) The data needs to be in one big csv file which often requires time consuming file concatenation 2) If using pandas to write the files into many chunks, the csv format writing tends to be inefficient. Since pandas can write into parquet quite efficiently, it would be awesome if we could read such parquet files directly into the LightGBM CLI version. This would remove the need to do csv file writing and concatenation.

## Description
Have the LightGBM CLI version read one or many parquet files. In the case of many, have the code read all parquet files inside a folder. 

## References
None, it is a productivity hack.

**Comment by StrikerRUS** [comment]
@ogru Thank you very much for posting this request here!

Just one question: can't [MMLSpark with native parquet support](https://github.com/microsoft/LightGBM/issues/1286#issuecomment-517380041) fit for your scenario?

**Comment by ogru** [comment]
Hi @StrikerRUS, 

Thank you for the quick reply. I am aware of the MMLSpark solution you referenced. The problem is not that we cannot provide parquet data to LightGBM, we can always load it into python/pandas and proceed in the conventional manner. However, this approach is insanely memory expensive, mostly due to pandas. I doubt that spark would be more efficient than pandas on a single machine (i.e. GCP VMs). 

To overcome memory bottlenecks with pandas, we utilize the CLI version which is super efficient. The problem is that the CLI version wants ONE training file as input. If the training data is in many files (csv of pq), which it usually is, concatenating them is a huge pain in the neck. If it is all going to end up inside LightGBM anyways, why not reading individual files and concatenating the data inside LightGBM? 

I am not fixated on parquet, reading multiple csv files would also be a huge improvement. 

Many thanks!

**Comment by StrikerRUS** [comment]
@ogru Thanks for the clarification! 

We already have a feature request for possibility to read data from multiple files. So I'm going to reference your experience from there.
