### ISSUE TITLE
Build LightGBM with GPU error.

### ISSUE THREAD

**Issue by lk1983823** [microsoft/LightGBM#2641]
## Environment info

Operating System:  Ubuntu 16.04 

CPU/GPU model: Nvidia cuda 10, cudnn 7.6.0

C++/Python/R version: Python 3.6.7

LightGBM version or commit hash:

## Error message

<[  1%] Building CXX object CMakeFiles/lightgbm.dir/src/main.cpp.o
[  3%] Building CXX object CMakeFiles/_lightgbm.dir/src/lightgbm_R.cpp.o
[  4%] Building CXX object CMakeFiles/lightgbm.dir/src/boosting/gbdt.cpp.o
[ 23%] Building CXX object CMakeFiles/_lightgbm.dir/src/boosting/prediction_early_stop.cpp.o
[  6%] Building CXX object CMakeFiles/_lightgbm.dir/src/application/application.cpp.o
[  7%] Building CXX object CMakeFiles/lightgbm.dir/src/boosting/prediction_early_stop.cpp.o
[  9%] Building CXX object CMakeFiles/lightgbm.dir/src/boosting/gbdt_model_text.cpp.o
[ 11%] Building CXX object CMakeFiles/_lightgbm.dir/src/c_api.cpp.o
[ 57%] Building CXX object CMakeFiles/_lightgbm.dir/src/io/dataset_loader.cpp.o
[ 12%] Building CXX object CMakeFiles/_lightgbm.dir/src/io/config.cpp.o
[ 74%] Building CXX object CMakeFiles/_lightgbm.dir/src/boosting/boosting.cpp.o
[ 14%] Building CXX object CMakeFiles/lightgbm.dir/src/boosting/boosting.cpp.o
[ 15%] Building CXX object CMakeFiles/lightgbm.dir/src/application/application.cpp.o
[ 17%] Building CXX object CMakeFiles/_lightgbm.dir/src/io/tree.cpp.o
[ 20%] Building CXX object CMakeFiles/_lightgbm.dir/src/objective/objective_function.cpp.o
[ 20%] Building CXX object CMakeFiles/_lightgbm.dir/src/boosting/gbdt.cpp.o
[ 22%] Building CXX object CMakeFiles/_lightgbm.dir/src/io/bin.cpp.o
[ 25%] Building CXX object CMakeFiles/lightgbm.dir/src/io/json11.cpp.o
[ 26%] Building CXX object CMakeFiles/_lightgbm.dir/src/treelearner/voting_parallel_tree_learner.cpp.o
[ 28%] Building CXX object CMakeFiles/_lightgbm.dir/src/treelearner/feature_parallel_tree_learner.cpp.o
[ 30%] Building CXX object CMakeFiles/_lightgbm.dir/src/treelearner/serial_tree_learner.cpp.o
[ 31%] Building CXX object CMakeFiles/lightgbm.dir/src/boosting/gbdt_prediction.cpp.o
[ 33%] Building CXX object CMakeFiles/_lightgbm.dir/src/io/parser.cpp.o
[ 34%] Building CXX object CMakeFiles/_lightgbm.dir/src/treelearner/data_parallel_tree_learner.cpp.o
[ 36%] Building CXX object CMakeFiles/lightgbm.dir/src/io/metadata.cpp.o
[ 38%] Building CXX object CMakeFiles/_lightgbm.dir/src/network/linkers_mpi.cpp.o
[ 39%] Building CXX object CMakeFiles/_lightgbm.dir/src/network/network.cpp.o
[ 42%] Building CXX object CMakeFiles/_lightgbm.dir/src/io/dataset.cpp.o
[ 44%] Building CXX object CMakeFiles/lightgbm.dir/src/io/config_auto.cpp.o
[ 42%] Building CXX object CMakeFiles/_lightgbm.dir/src/treelearner/gpu_tree_learner.cpp.o
[ 46%] Building CXX object CMakeFiles/lightgbm.dir/src/io/dataset.cpp.o
[ 47%] Building CXX object CMakeFiles/lightgbm.dir/src/io/file_io.cpp.o
[ 76%] Building CXX object CMakeFiles/_lightgbm.dir/src/io/json11.cpp.o
[ 49%] Building CXX object CMakeFiles/lightgbm.dir/src/io/bin.cpp.o
[ 50%] Building CXX object CMakeFiles/_lightgbm.dir/src/io/metadata.cpp.o
[ 52%] Building CXX object CMakeFiles/_lightgbm.dir/src/io/file_io.cpp.o
[ 53%] Building CXX object CMakeFiles/_lightgbm.dir/src/metric/metric.cpp.o
[ 55%] Building CXX object CMakeFiles/_lightgbm.dir/src/network/linker_topo.cpp.o
[ 60%] Building CXX object CMakeFiles/_lightgbm.dir/src/boosting/gbdt_model_text.cpp.o
[ 58%] Building CXX object CMakeFiles/lightgbm.dir/src/io/tree.cpp.o
[ 61%] Building CXX object CMakeFiles/lightgbm.dir/src/io/dataset_loader.cpp.o
[ 63%] Building CXX object CMakeFiles/_lightgbm.dir/src/boosting/gbdt_prediction.cpp.o
[ 65%] Building CXX object CMakeFiles/lightgbm.dir/src/io/config.cpp.o
[ 66%] Building CXX object CMakeFiles/_lightgbm.dir/src/network/linkers_socket.cpp.o
[ 68%] Building CXX object CMakeFiles/lightgbm.dir/src/io/parser.cpp.o
[ 69%] Building CXX object CMakeFiles/_lightgbm.dir/src/treelearner/tree_learner.cpp.o
[ 71%] Building CXX object CMakeFiles/_lightgbm.dir/src/metric/dcg_calculator.cpp.o
[ 73%] Building CXX object CMakeFiles/_lightgbm.dir/src/io/config_auto.cpp.o
[ 77%] Building CXX object CMakeFiles/lightgbm.dir/src/metric/dcg_calculator.cpp.o
[ 79%] Building CXX object CMakeFiles/lightgbm.dir/src/metric/metric.cpp.o
[ 80%] Building CXX object CMakeFiles/lightgbm.dir/src/objective/objective_function.cpp.o
[ 82%] Building CXX object CMakeFiles/lightgbm.dir/src/network/linker_topo.cpp.o
[ 84%] Building CXX object CMakeFiles/lightgbm.dir/src/network/linkers_mpi.cpp.o
[ 85%] Building CXX object CMakeFiles/lightgbm.dir/src/network/network.cpp.o
[ 87%] Building CXX object CMakeFiles/lightgbm.dir/src/network/linkers_socket.cpp.o
[ 88%] Building CXX object CMakeFiles/lightgbm.dir/src/treelearner/gpu_tree_learner.cpp.o
[ 90%] Building CXX object CMakeFiles/lightgbm.dir/src/treelearner/serial_tree_learner.cpp.o
[ 92%] Building CXX object CMakeFiles/lightgbm.dir/src/treelearner/voting_parallel_tree_learner.cpp.o
[ 93%] Building CXX object CMakeFiles/lightgbm.dir/src/treelearner/feature_parallel_tree_learner.cpp.o
[ 95%] Building CXX object CMakeFiles/lightgbm.dir/src/treelearner/data_parallel_tree_learner.cpp.o
[ 96%] Building CXX object CMakeFiles/lightgbm.dir/src/treelearner/tree_learner.cpp.o
[ 98%] Linking CXX shared library ../lib_lightgbm.so
[ 98%] Built target _lightgbm
[100%] Linking CXX executable ../lightgbm
CMakeFiles/lightgbm.dir/src/treelearner/gpu_tree_learner.cpp.o: In function `boost::compute::detail::program_binary_path(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)':
gpu_tree_learner.cpp:(.text._ZN5boost7compute6detail19program_binary_pathERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEb[_ZN5boost7compute6detail19program_binary_pathERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEb]+0x22f): undefined reference to `boost::filesystem::detail::status(boost::filesystem::path const&, boost::system::error_code*)'
gpu_tree_learner.cpp:(.text._ZN5boost7compute6detail19program_binary_pathERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEb[_ZN5boost7compute6detail19program_binary_pathERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEb]+0x27d): undefined reference to `boost::filesystem::detail::create_directories(boost::filesystem::path const&, boost::system::error_code*)'
CMakeFiles/lightgbm.dir/src/treelearner/gpu_tree_learner.cpp.o: In function `boost::compute::detail::parameter_cache::make_file_name[abi:cxx11]() const':
gpu_tree_learner.cpp:(.text._ZNK5boost7compute6detail15parameter_cache14make_file_nameB5cxx11Ev[_ZNK5boost7compute6detail15parameter_cache14make_file_nameB5cxx11Ev]+0x8a6): undefined reference to `boost::filesystem::detail::status(boost::filesystem::path const&, boost::system::error_code*)'
gpu_tree_learner.cpp:(.text._ZNK5boost7compute6detail15parameter_cache14make_file_nameB5cxx11Ev[_ZNK5boost7compute6detail15parameter_cache14make_file_nameB5cxx11Ev]+0x8fb): undefined reference to `boost::filesystem::detail::create_directories(boost::filesystem::path const&, boost::system::error_code*)'
CMakeFiles/lightgbm.dir/src/treelearner/gpu_tree_learner.cpp.o: In function `boost::detail::sp_if_not_array<boost::compute::detail::parameter_cache>::type boost::make_shared<boost::compute::detail::parameter_cache, boost::compute::device const&>(boost::compute::device const&)':
gpu_tree_learner.cpp:(.text._ZN5boost11make_sharedINS_7compute6detail15parameter_cacheEJRKNS1_6deviceEEEENS_6detail15sp_if_not_arrayIT_E4typeEDpOT0_[_ZN5boost11make_sharedINS_7compute6detail15parameter_cacheEJRKNS1_6deviceEEEENS_6detail15sp_if_not_arrayIT_E4typeEDpOT0_]+0x11d): undefined reference to `boost::filesystem::detail::status(boost::filesystem::path const&, boost::system::error_code*)'
CMakeFiles/lightgbm.dir/src/treelearner/gpu_tree_learner.cpp.o: In function `_GLOBAL__sub_I_gpu_tree_learner.cpp':
gpu_tree_learner.cpp:(.text.startup+0x2b): undefined reference to `boost::system::generic_category()'
gpu_tree_learner.cpp:(.text.startup+0x30): undefined reference to `boost::system::generic_category()'
gpu_tree_learner.cpp:(.text.startup+0x39): undefined reference to `boost::system::system_category()'
CMakeFiles/lightgbm.dir/src/treelearner/voting_parallel_tree_learner.cpp.o: In function `_GLOBAL__sub_I_voting_parallel_tree_learner.cpp':
voting_parallel_tree_learner.cpp:(.text.startup+0x2b): undefined reference to `boost::system::generic_category()'
voting_parallel_tree_learner.cpp:(.text.startup+0x30): undefined reference to `boost::system::generic_category()'
voting_parallel_tree_learner.cpp:(.text.startup+0x39): undefined reference to `boost::system::system_category()'
CMakeFiles/lightgbm.dir/src/treelearner/feature_parallel_tree_learner.cpp.o: In function `_GLOBAL__sub_I_feature_parallel_tree_learner.cpp':
feature_parallel_tree_learner.cpp:(.text.startup+0x2b): undefined reference to `boost::system::generic_category()'
feature_parallel_tree_learner.cpp:(.text.startup+0x30): undefined reference to `boost::system::generic_category()'
feature_parallel_tree_learner.cpp:(.text.startup+0x39): undefined reference to `boost::system::system_category()'
CMakeFiles/lightgbm.dir/src/treelearner/data_parallel_tree_learner.cpp.o: In function `_GLOBAL__sub_I_data_parallel_tree_learner.cpp':
data_parallel_tree_learner.cpp:(.text.startup+0x2b): undefined reference to `boost::system::generic_category()'
data_parallel_tree_learner.cpp:(.text.startup+0x30): undefined reference to `boost::system::generic_category()'
data_parallel_tree_learner.cpp:(.text.startup+0x39): undefined reference to `boost::system::system_category()'
CMakeFiles/lightgbm.dir/src/treelearner/tree_learner.cpp.o: In function `_GLOBAL__sub_I_tree_learner.cpp':
tree_learner.cpp:(.text.startup+0x2b): undefined reference to `boost::system::generic_category()'
tree_learner.cpp:(.text.startup+0x30): undefined reference to `boost::system::generic_category()'
tree_learner.cpp:(.text.startup+0x39): undefined reference to `boost::system::system_category()'
collect2: error: ld returned 1 exit status
CMakeFiles/lightgbm.dir/build.make:849: recipe for target '../lightgbm' failed
make[2]: *** [../lightgbm] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/lightgbm.dir/all' failed
make[1]: *** [CMakeFiles/lightgbm.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
>

## Steps to reproduce

I make set as : cmake -DUSE_GPU=1 -DOpenCL_LIBRARY=/usr/local/cuda/lib64/libOpenCL.so -DOpenCL_INCLUDE_DIR=/usr/local/cuda/include/ ..
Then,  make -j4$(nproc) and the error happens. 
Thanks!

**Comment by StrikerRUS** [comment]
@lk1983823 Seems that CMake cannot find `Boost` package. Please post a whole log of CMake run from the beginning. It should start like the following:
```
-- The C compiler identification is Clang 7.0.0
-- The CXX compiler identification is Clang 7.0.0
-- Check for working C compiler: /usr/local/clang-7.0.0/bin/clang
-- Check for working C compiler: /usr/local/clang-7.0.0/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/local/clang-7.0.0/bin/clang++
-- Check for working CXX compiler: /usr/local/clang-7.0.0/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenMP_C: -fopenmp=libomp (found version "3.1") 
-- Found OpenMP_CXX: -fopenmp=libomp (found version "3.1") 
-- Found OpenMP: TRUE (found version "3.1")  
-- Looking for CL_VERSION_2_2
-- Looking for CL_VERSION_2_2 - not found
-- Looking for CL_VERSION_2_1
-- Looking for CL_VERSION_2_1 - not found
-- Looking for CL_VERSION_2_0
-- Looking for CL_VERSION_2_0 - found
-- Found OpenCL: /usr/lib/x86_64-linux-gnu/libOpenCL.so (found version "2.0") 
-- OpenCL include directory: /home/travis/AMDAPPSDK/include
CMake Warning at /usr/local/cmake-3.12.4/share/cmake-3.12/Modules/FindBoost.cmake:847 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /usr/local/cmake-3.12.4/share/cmake-3.12/Modules/FindBoost.cmake:963 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/local/cmake-3.12.4/share/cmake-3.12/Modules/FindBoost.cmake:1622 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:100 (find_package)
CMake Warning at /usr/local/cmake-3.12.4/share/cmake-3.12/Modules/FindBoost.cmake:847 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /usr/local/cmake-3.12.4/share/cmake-3.12/Modules/FindBoost.cmake:963 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/local/cmake-3.12.4/share/cmake-3.12/Modules/FindBoost.cmake:1622 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:100 (find_package)

-- Boost version: 1.70.0
-- Found the following Boost libraries:
--   filesystem
--   system
-- Configuring done
-- Generating done
-- Build files have been written to: /home/travis/build/microsoft/LightGBM/build
Scanning dependencies of target _lightgbm
[  3%] Building CXX object CMakeFiles/_lightgbm.dir/src/c_api.cpp.o
```

And try to specify Boost paths as it's suggested for Windows users `-DBOOST_ROOT=C:/local/boost_1_63_0 -DBOOST_LIBRARYDIR=C:/local/boost_1_63_0/lib64-msvc-14.0`.

**Comment by lk1983823** [comment]
@StrikerRUS 
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: -fopenmp  
-- Looking for CL_VERSION_2_0
-- Looking for CL_VERSION_2_0 - not found
-- Looking for CL_VERSION_1_2
-- Looking for CL_VERSION_1_2 - found
-- Found OpenCL: /usr/local/cuda/lib64/libOpenCL.so (found version "1.2") 
-- OpenCL include directory: /usr/local/cuda/include
-- Found Boost 1.70.0 at /home/lukuan/.pyenv/versions/anaconda3-5.1.0/envs/sgcc/lib/cmake/Boost-1.70.0
--   Requested configuration: QUIET REQUIRED COMPONENTS filesystem;system
-- Found boost_headers 1.70.0 at /home/lukuan/.pyenv/versions/anaconda3-5.1.0/envs/sgcc/lib/cmake/boost_headers-1.70.0
-- Found boost_filesystem 1.70.0 at /home/lukuan/.pyenv/versions/anaconda3-5.1.0/envs/sgcc/lib/cmake/boost_filesystem-1.70.0
--   libboost_filesystem.a
-- Adding boost_filesystem dependencies: headers
-- Found boost_system 1.70.0 at /home/lukuan/.pyenv/versions/anaconda3-5.1.0/envs/sgcc/lib/cmake/boost_system-1.70.0
--   libboost_system.a
-- Adding boost_system dependencies: headers
Boost 1.56.0 found.
Found Boost components:
   filesystem;system
-- Configuring done
-- Generating done
-- Build files have been written to: /home/lukuan/git_sgcc/LightGBM/build

**Comment by guolinke** [comment]
did you clone the code with ``--recursive`` ?

**Comment by lk1983823** [comment]
@guolinke 

`[ 98%] Linking CXX executable ../lightgbm
CMakeFiles/lightgbm.dir/src/treelearner/gpu_tree_learner.cpp.o: In function `boost::compute::detail::program_binary_path(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)':
gpu_tree_learner.cpp:(.text._ZN5boost7compute6detail19program_binary_pathERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEb[_ZN5boost7compute6detail19program_binary_pathERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEb]+0x22f): undefined reference to `boost::filesystem::detail::status(boost::filesystem::path const&, boost::system::error_code*)'
gpu_tree_learner.cpp:(.text._ZN5boost7compute6detail19program_binary_pathERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEb[_ZN5boost7compute6detail19program_binary_pathERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEb]+0x27d): undefined reference to `boost::filesystem::detail::create_directories(boost::filesystem::path const&, boost::system::error_code*)'
CMakeFiles/lightgbm.dir/src/treelearner/gpu_tree_learner.cpp.o: In function `boost::compute::detail::parameter_cache::make_file_name[abi:cxx11]() const':
gpu_tree_learner.cpp:(.text._ZNK5boost7compute6detail15parameter_cache14make_file_nameB5cxx11Ev[_ZNK5boost7compute6detail15parameter_cache14make_file_nameB5cxx11Ev]+0x8a6): undefined reference to `boost::filesystem::detail::status(boost::filesystem::path const&, boost::system::error_code*)'
gpu_tree_learner.cpp:(.text._ZNK5boost7compute6detail15parameter_cache14make_file_nameB5cxx11Ev[_ZNK5boost7compute6detail15parameter_cache14make_file_nameB5cxx11Ev]+0x8fb): undefined reference to `boost::filesystem::detail::create_directories(boost::filesystem::path const&, boost::system::error_code*)'
CMakeFiles/lightgbm.dir/src/treelearner/gpu_tree_learner.cpp.o: In function `boost::detail::sp_if_not_array<boost::compute::detail::parameter_cache>::type boost::make_shared<boost::compute::detail::parameter_cache, boost::compute::device const&>(boost::compute::device const&)':
gpu_tree_learner.cpp:(.text._ZN5boost11make_sharedINS_7compute6detail15parameter_cacheEJRKNS1_6deviceEEEENS_6detail15sp_if_not_arrayIT_E4typeEDpOT0_[_ZN5boost11make_sharedINS_7compute6detail15parameter_cacheEJRKNS1_6deviceEEEENS_6detail15sp_if_not_arrayIT_E4typeEDpOT0_]+0x11d): undefined reference to `boost::filesystem::detail::status(boost::filesystem::path const&, boost::system::error_code*)'
CMakeFiles/lightgbm.dir/src/treelearner/gpu_tree_learner.cpp.o: In function `_GLOBAL__sub_I_gpu_tree_learner.cpp':
gpu_tree_learner.cpp:(.text.startup+0x2b): undefined reference to `boost::system::generic_category()'
gpu_tree_learner.cpp:(.text.startup+0x30): undefined reference to `boost::system::generic_category()'
gpu_tree_learner.cpp:(.text.startup+0x39): undefined reference to `boost::system::system_category()'
CMakeFiles/lightgbm.dir/src/treelearner/voting_parallel_tree_learner.cpp.o: In function `_GLOBAL__sub_I_voting_parallel_tree_learner.cpp':
voting_parallel_tree_learner.cpp:(.text.startup+0x2b): undefined reference to `boost::system::generic_category()'
voting_parallel_tree_learner.cpp:(.text.startup+0x30): undefined reference to `boost::system::generic_category()'
voting_parallel_tree_learner.cpp:(.text.startup+0x39): undefined reference to `boost::system::system_category()'
CMakeFiles/lightgbm.dir/src/treelearner/feature_parallel_tree_learner.cpp.o: In function `_GLOBAL__sub_I_feature_parallel_tree_learner.cpp':
feature_parallel_tree_learner.cpp:(.text.startup+0x2b): undefined reference to `boost::system::generic_category()'
feature_parallel_tree_learner.cpp:(.text.startup+0x30): undefined reference to `boost::system::generic_category()'
feature_parallel_tree_learner.cpp:(.text.startup+0x39): undefined reference to `boost::system::system_category()'
CMakeFiles/lightgbm.dir/src/treelearner/data_parallel_tree_learner.cpp.o: In function `_GLOBAL__sub_I_data_parallel_tree_learner.cpp':
data_parallel_tree_learner.cpp:(.text.startup+0x2b): undefined reference to `boost::system::generic_category()'
data_parallel_tree_learner.cpp:(.text.startup+0x30): undefined reference to `boost::system::generic_category()'
data_parallel_tree_learner.cpp:(.text.startup+0x39): undefined reference to `boost::system::system_category()'
CMakeFiles/lightgbm.dir/src/treelearner/tree_learner.cpp.o: In function `_GLOBAL__sub_I_tree_learner.cpp':
tree_learner.cpp:(.text.startup+0x2b): undefined reference to `boost::system::generic_category()'
tree_learner.cpp:(.text.startup+0x30): undefined reference to `boost::system::generic_category()'
tree_learner.cpp:(.text.startup+0x39): undefined reference to `boost::system::system_category()'
collect2: error: ld returned 1 exit status
CMakeFiles/lightgbm.dir/build.make:849: recipe for target '../lightgbm' failed
make[2]: *** [../lightgbm] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/lightgbm.dir/all' failed
make[1]: *** [CMakeFiles/lightgbm.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[100%] Linking CXX shared library ../lib_lightgbm.so
[100%] Built target _lightgbm
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by StrikerRUS** [comment]
@lk1983823 
Indeed, `--recursive` git flag is critical for GPU computing.

> -- Found Boost 1.70.0 at 

> Boost 1.56.0 found.

Do you have two Boost versions installed on your machine?

Or is it a new CMake logging "feature"?..

**Comment by lk1983823** [comment]
@StrikerRUS Yes, I have built a pyenv environment  and the boost version mismatch with the system installed one. After I deactivate that environment and cmake again, I succeed to compile Lightgbm. Btw, after the cmake process, I activate sgcc (the name of my environment)

**Comment by lk1983823** [comment]
(

**Comment by StrikerRUS** [comment]
@lk1983823 
> After I deactivate that environment and cmake again, I succeed to compile Lightgbm.

That's cool!

> Btw, after the cmake process, I activate sgcc and use python setup.py install --precompile command to install lightgbm under sgcc. Is it proper?

Absolutely!

> Will there be any problem due to the mismatch between boost version?

To be honest, I have no idea! But I strongly believe that there should be only one instance of Boost library installation for the safety reasons. Is it possible to remove your system-wide Boost if you need a newer one from Python environment? Or instead, you can remove 1.70 version because 1.56 is the oldest supported version by LightGBM, if it is not required for any other software.

**Comment by lk1983823** [comment]
@StrikerRUS Thanks, I will try.
