### ISSUE TITLE
for scala ,how lightGBM outPut the path of leaf  node

### ISSUE THREAD

**Issue by zengqingxue** [microsoft/LightGBM#2650]
When I use the scala version of lightGBM for model prediction, I need to get the output path of the model leaf nodes, but I don't know how to set this parameter. I queried the parameters of the output leaf nodes in the lightGBM official website: predict_leaf_index or leaf_index or is_predict_leaf_index
However, the official website only provides APIs for Python or R, and does not provide APIs for scala. So ,I need a help: 

for scala ,how lightGBM outPut the path of leaf  node?

the code of my project of the mode part is the follow:

 ` val classifierModel  = new LightGBMClassifier()

      .setLabelCol("label")
      .setFeaturesCol("assemberFeatures")
      .setRawPredictionCol("rawPrediction")
      .setObjective("binary")
      //      .setParallelism("voting_parallel")
      .setLearningRate(0.1)
      .setMaxBin(128)
      .setNumLeaves(500)
      .setMaxDepth(6)
      .setNumLeaves(6)
      //      .setFeatureFraction(0.8)
      .setNumIterations(50)
      .fit(trainInput)
val testRanking = classifierModel.transform(testInput)`

If you have time, can give me this method how to output the path of the leaf node, I will be very grateful！

**Comment by StrikerRUS** [comment]
Hi @zengqingxue !

I'm sorry, but we do not have official scala bindings for LightGBM in this repo. I guess you're using MMLSpark, aren't you? If so, please ask your question in their repo: https://github.com/Azure/mmlspark.

Probably you'll need to wait the following PR: https://github.com/Azure/mmlspark/pull/768.
