### ISSUE TITLE
[lambdarank]Question for param label_gain.

### ISSUE THREAD

**Issue by fydlzr** [microsoft/LightGBM#2655]
I got a rank task, label in [0,19];
I use the default params of lambdarank, and I got a bad result (much worse than regression);
I tried to change the label_gain to [0...19], and I got a better result (a little better than regression);

why is that?
Is label_gain [0...19] equal to regression?

**Comment by guolinke** [comment]
the default label_gain is `2^i`, which is very large for the label [0, 19], and may cause the bad result.
Which metric you used to eval the result? NDCG@k? if k is small, you can reduce the label range [0, k], by merging the small labels (e.g. k=10, you can merge [0, 9] into 0.), or set the same (and small) label gain to these small labels.

it is not equal to regression. the lambdarank loss is: https://github.com/microsoft/LightGBM/blob/master/src/objective/rank_objective.hpp
