### ISSUE TITLE
[gpu] device_type="gpu" loses determinism for randomness

### ISSUE THREAD

**Issue by Gerenuk** [microsoft/LightGBM#2659]
Fixing seeds in LGBM Regressor does not work as soon as `device_type='gpu'` is activated. The results vary randomly despite fixing seeds.

(Tested with Python lightgbm 2.3.0)

**Comment by guolinke** [comment]
I think we don't provide the fixed seed for GPU version now.
ping @huanzhang12

**Comment by StrikerRUS** [comment]
@Gerenuk Have you tried to set `gpu_use_dp` parameter?
https://lightgbm.readthedocs.io/en/latest/Parameters.html#gpu_use_dp

**Comment by Gerenuk** [comment]
@StrikerRUS 
With `gpu_use_dp=True` it becomes reproducible again.
Btw, I'm using the "nomkl" setup if that matters.

I'm working on my data and not sure how to create a minimal example :/

**Comment by StrikerRUS** [comment]
@Gerenuk 
Great! Then it's expected behaviour and no repro is needed.
https://lightgbm.readthedocs.io/en/latest/FAQ.html#when-using-lightgbm-gpu-i-cannot-reproduce-results-over-several-runs
