### ISSUE TITLE
LightGBM very slow on AWS but not locally

### ISSUE THREAD

**Issue by lpolisi** [microsoft/LightGBM#2661]
I have a i7 9700 CPU @ 3.00GHz on my local ubuntu machine and I am able to tune and train my LightGBM model in around 5 hours. When I repeat the procedure on an AWS EC2 instance, c5.12xlarge, I see a significantly slower training time and it can take up to 20 hours to complete the tuning procedure.

The dataset I use has around 20 features and 2 million rows and this is the parameter I use for the model:

```
 model_params = {"boosting_type": "gbdt",
                 "num_threads": 16,
                 "colsample_bytree": 0.51,
                 "importance_type": "split",
                 "learning_rate": 0.1,
                 "max_depth": -1,
                 "min_child_samples": 35,
                 "min_child_weight": 0.001,
                 "min_split_gain": 0.11,
                 "n_estimators": 5000,
                 "num_leaves": 412,
                 "objective": "regression_l1",
                 "random_state": 1337,
                 "reg_alpha": 0.3,
                 "reg_lambda": 3.5,
                 "subsample": 0.59,
                 "subsample_for_bin": 200000,
                 "subsample_freq": 0,
                 "verbose": -1}
```

What should I do to increase the performance on AWS?

**Comment by guolinke** [comment]
Not familiar with aws. You can check 1. Number of threads, explicitly set it to the number of cores; 2. Numa. LightGBM is not numa-aware, if the VM is multi-sockets, you may downgrade it to the single-socket, or set the number of threads to the cores of one socket.
