### ISSUE TITLE
2.3.1 does not handle model.predict("file.svm") well if the file has a smaller cardinality of features than what the model was trained with

### ISSUE THREAD

**Issue by andrewortman** [microsoft/LightGBM#2668]
I appear to have found a regression with 2.3.1 on how lightgbm  handles predictions from a libsvm file. After train, we have a holdout-lite set that we use for analysis. This holdout-lite set does not contain labels, we just use it to plot the distribution of outputs in different scenarios. These files may not have all the features the model was trained with. In 2.3.0, this was fine - the prediction happened anyway and the missing features were treated as mising. In 2.3.1 though, it breaks with a fatal exception error. See below:

## Environment info

Operating System: Linux

CPU/GPU model: i9900k

C++/Python/R version: Python / v2.3.1

## Error message

LightGBMError: The number of features in data (8013) is not the same as it was in training data (8355).

## Reproducible examples

https://gist.github.com/andrewortman/27997cb467ab77b4311f26efd26ecfae

## Steps to reproduce

1.  Use gist above as a template. Create a sample_train.svm file with say 5 features, but create a sample_predict.svm file with only 3 features
2. When using v2.3.0, prediction succeeds
3. When using 2.3.1, prediction fails with fatal exception that number of columns do not match

I would expect the prediction will still occur, allowing unseen columns to be treated as missing in the tree.

**Comment by guolinke** [comment]
refer to https://github.com/microsoft/LightGBM/pull/2464
This is for checking the shape in prediction, avoid misusage in prediction.
I think we can add a parameter, which can disable the shape check.

**Comment by andrewortman** [comment]
that would be a sufficient solution for me. I can also pass in the original n_features that the model was trained with
