### ISSUE TITLE
param:class_weight in binary class generates better results than param:is_unbalanced

### ISSUE THREAD

**Issue by abarbosa94** [microsoft/LightGBM#2672]
## Environment info

Operating System: Ubuntu

CPU/GPU model: CPU

C++/Python/R version: python

LightGBM version or commit hash: 2.2.3

I'm not sure if this is a bug or a misusage from my part, but I was dealing with a classification problem with unbalanced classes (where the positive class proportion was bigger than the negative one) setting in my company. If I set the parameter `is_unbalanced=True` or scale_pos_weight for lightgbm the model always predicted positive class, resulting in True Positive and False Positive only.

As this wasn't expected, I tried to use `class_weight=balanced` even though this is specified in the documentation that for this kind of problem it should not be used. However, the results made much more sense since there were fell False Negatives and True Negatives in this case. 

I got a little confused by getting these results and any appreciation would be grateful.

**Comment by guolinke** [comment]
class_weight uses the `compute_sample_weight` in sklearn: https://scikit-learn.org/stable/modules/generated/sklearn.utils.class_weight.compute_sample_weight.html
the balanced rule are different in LightGBM: 
https://github.com/microsoft/LightGBM/blob/ef0b2d8287c21a1960b4e212f58e828f0ef264c4/src/objective/binary_objective.hpp#L95-L103

**Comment by StrikerRUS** [comment]
I'm not sure, but maybe the cause was in that `class_weight` (contributes to `weights_`) and `is_unbalanced` (contributes to `label_weight`) were used together? In that case, their effects were multiplied according to the following:
https://github.com/microsoft/LightGBM/blob/ef0b2d8287c21a1960b4e212f58e828f0ef264c4/src/objective/binary_objective.hpp#L134-L135
