### ISSUE TITLE
Impossible num_leaves parameter

### ISSUE THREAD

**Issue by Sanchita-P** [microsoft/LightGBM#2673]
Hi Team,

I am facing an anomaly while using LightGBM which I would love your thoughts on. As per my understanding from the docs, max_depth is the maximum depth for the tree and num_leaves is the maximum number of leaves in one tree. So as per this definition, in LightGBM, if the maximum depth is 3, the maximum number of leaves possible would be 8. 
However, after doing hyperparameter tuning in LightGBM, I get the following parameters - 
-  'max_depth': 4,
-  'num_leaves': 83

How is this possible? Is my understanding of the num_leaves incorrect?

Thanks!

**Comment by StrikerRUS** [comment]
Hello @Sanchita-P !

According to the following code, it seems that `max_depth` has higher priority:
https://github.com/microsoft/LightGBM/blob/f6b8ecf648f77f48d95a15e9ba5220e52f5d584c/src/io/config.cpp#L301-L314
