### ISSUE TITLE
OverflowError: The '_length_' attribute is too large

### ISSUE THREAD

**Issue by HaimianYu** [microsoft/LightGBM#2675]
Hello, how can I solve this problem? This error will be reported every time after the model training early stopping. After checking a lot of data, no solution can be found

 18     verbose=20
     19 )
     20 print('runtime:', time.time() - t)

F:\Anoconda3\lib\site-packages\lightgbm\sklearn.py in fit(self, X, y, sample_weight, init_score, eval_set, eval_names, eval_sample_weight, eval_class_weight, eval_init_score, eval_metric, early_stopping_rounds, verbose, feature_name, categorical_feature, callbacks)
    803                                         verbose=verbose, feature_name=feature_name,
    804                                         categorical_feature=categorical_feature,
--> 805                                         callbacks=callbacks)
    806         return self
    807 

F:\Anoconda3\lib\site-packages\lightgbm\sklearn.py in fit(self, X, y, sample_weight, init_score, group, eval_set, eval_names, eval_sample_weight, eval_class_weight, eval_init_score, eval_group, eval_metric, early_stopping_rounds, verbose, feature_name, categorical_feature, callbacks)
    598                               verbose_eval=verbose, feature_name=feature_name,
    599                               categorical_feature=categorical_feature,
--> 600                               callbacks=callbacks)
    601 
    602         if evals_result:

F:\Anoconda3\lib\site-packages\lightgbm\engine.py in train(params, train_set, num_boost_round, valid_sets, valid_names, fobj, feval, init_model, feature_name, categorical_feature, early_stopping_rounds, evals_result, verbose_eval, learning_rates, keep_training_booster, callbacks)
    271         booster.best_score[dataset_name][eval_name] = score
    272     if not keep_training_booster:
--> 273         booster.model_from_string(booster.model_to_string(), False).free_dataset()
    274     return booster
    275 

F:\Anoconda3\lib\site-packages\lightgbm\basic.py in model_to_string(self, num_iteration, start_iteration)
   2306         # if buffer length is not long enough, re-allocate a buffer
   2307         if actual_len > buffer_len:
-> 2308             string_buffer = ctypes.create_string_buffer(actual_len)
   2309             ptr_string_buffer = ctypes.c_char_p(*[ctypes.addressof(string_buffer)])
   2310             _safe_call(_LIB.LGBM_BoosterSaveModelToString(

F:\Anoconda3\lib\ctypes\__init__.py in create_string_buffer(init, size)
     58         return buf
     59     elif isinstance(init, int):
---> 60         buftype = c_char * init
     61         buf = buftype()
     62         return buf

OverflowError: The '_length_' attribute is too large
-->

**Comment by HaimianYu** [comment]
The parameters of the model are as follows：
clf = LGBMClassifier(
    learning_rate=0.025,
    n_estimators=best_rounds,
    num_leaves=255,
    subsample=0.9,
    colsample_bytree=0.8,
    random_state=2019
)
print('************** training **************')
clf.fit(
    train_df, train_df_target,
    eval_set=[(train_df, train_df_target)],
    eval_metric='auc',
    categorical_feature=cate_cols,
    early_stopping_rounds=100,
    verbose=20
)

**Comment by StrikerRUS** [comment]
@HaimianYu Hi!

Can you please provide [MCVE](https://stackoverflow.com/help/minimal-reproducible-example)?

You can try to switch to standard API (not scikit-learn) and set `keep_training_booster=True`. Refer to https://github.com/microsoft/LightGBM/issues/2265#issuecomment-511642593.

Unfortunately there is no better workaround for now.
