### ISSUE TITLE
Multi thread or multi process for LightGBM coupled with RandomizedSearchCV

### ISSUE THREAD

**Issue by TGalaxy** [microsoft/LightGBM#2676]
I have a question on multi thread vs multi process for LGBM but couldn't find answers elsewhere. Figure it may worth posting the question here for insights.

I'm using LightGBM coupled with RandomizedSearchCV for hyper parameter tuning
`    mdl = lgb.LGBMClassifier(n_estimators=num_iterations,**params)`
 `  grid = RandomizedSearchCV(mdl, grid_param, verbose=0, cv=4, scoring=scoring, n_jobs=n_jobs, refit=False, n_iter=n_iter)
`
In the  lgb.LGBMClassifier, n_jobs=-1 by default which uses all available cores I assume. From https://lightgbm.readthedocs.io/en/latest/pythonapi/lightgbm.LGBMClassifier.html, it indicates multi thread.

In the RandomizedSearchCV, https://scikit-learn.org/stable/glossary.html#term-n-jobs, https://joblib.readthedocs.io/en/latest/parallel.html#thread-based-parallelism-vs-process-based-parallelism n_jobs sets multi process by default.

Say I have a machine of 4 cores. What is the more optimized way to set the n_jobs in lgb_LGBMClassifer and RandomizedSearchCV? For LightGBM algorithm in particular, which is more beneficial, multi-thread or multi-process? My goal is to have shorter run time without exploding CPU or memory.

**Comment by StrikerRUS** [comment]
@TGalaxy I'll suggest setting `-1` got LightGBM and `1` for RandomizedSearchCV. Or you can do some experiments on your machine.

But you should be aware of the following:
https://github.com/scikit-learn/scikit-learn/issues/10533#issuecomment-360981152
