### ISSUE TITLE
LightGBM installation gets stuck on linux and windows

### ISSUE THREAD

**Issue by mlubej** [microsoft/LightGBM#2702]
I'm trying to install lightgbm on the latest ubuntu image on AWS. It gets stuck at:
```python
Collecting lightgbm
  Using cached lightgbm-2.3.1.tar.gz (679 kB)
Requirement already satisfied: numpy in ./base/lib/python3.6/site-packages (from lightgbm) (1.18.1)
Requirement already satisfied: scikit-learn in ./base/lib/python3.6/site-packages (from lightgbm) (0.22.1)
Requirement already satisfied: scipy in ./base/lib/python3.6/site-packages (from lightgbm) (1.4.1)
Requirement already satisfied: joblib>=0.11 in ./base/lib/python3.6/site-packages (from scikit-learn->lightgbm) (0.14.1)
Building wheels for collected packages: lightgbm
  Building wheel for lightgbm (setup.py) ... \
```
This can go on to up to an hour and more.

When I spin up the image, I set up the environment with the following script

```bash
#!/bin/bash
export DEBIAN_FRONTEND=noninteractive

# general
sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable -y
sudo apt-get -q -y update
sudo apt-get install gdal-bin libgdal-dev -y

export CPLUS_INCLUDE_PATH=/usr/include/gdal
export C_INCLUDE_PATH=/usr/include/gdal

sudo apt-get install gcc python3-venv python3.6-dev libgeos-c1v5 libgeos-dev curl screen s3fs nodejs npm cmake -y
sudo apt-get install graphviz -y
```
I try to install lightgbm in a python3.6.9 venv, ofcourse I also install other things first, but can't say exactly what at the moment.

**Comment by mlubej** [comment]
Also, this was not the problem up until y-day or so. Did anything change on your side? I didn't see anything, though...

**Comment by ucabsdp** [comment]
Also suddenly getting installation issues randomly occurring today,

[  running install
  INFO:LightGBM:Starting to compile the library.
  INFO:LightGBM:Starting to compile with CMake.
  Traceback (most recent call last):
    File "/tmp/pip-install-2k6_q4kj/lightgbm/setup.py", line 77, in silent_call
      output = subprocess.check_output(cmd, stderr=subprocess.STDOUT)
    File "/usr/local/lib/python3.6/subprocess.py", line 356, in check_output
      **kwargs).stdout
    File "/usr/local/lib/python3.6/subprocess.py", line 423, in run
      with Popen(*popenargs, **kwargs) as process:
    File "/usr/local/lib/python3.6/subprocess.py", line 729, in __init__
      restore_signals, start_new_session)
    File "/usr/local/lib/python3.6/subprocess.py", line 1364, in _execute_child
      raise child_exception_type(errno_num, err_msg, err_filename)
  FileNotFoundError: [Errno 2] No such file or directory: 'cmake': 'cmake'
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-2k6_q4kj/lightgbm/setup.py", line 338, in <module>
      'Topic :: Scientific/Engineering :: Artificial Intelligence'])
    File "/usr/local/lib/python3.6/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/usr/local/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/local/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 228, in run
      self.run_command('install')
    File "/usr/local/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-2k6_q4kj/lightgbm/setup.py", line 261, in run
      openmp_include_dir=self.openmp_include_dir, openmp_library=self.openmp_library)
    File "/tmp/pip-install-2k6_q4kj/lightgbm/setup.py", line 200, in compile_cpp
      silent_call(cmake_cmd, raise_error=True, error_msg='Please install CMake and all required dependencies first')
    File "/tmp/pip-install-2k6_q4kj/lightgbm/setup.py", line 86, in silent_call
      raise Exception("\n".join((error_msg, LOG_NOTICE)))
  Exception: Please install CMake and all required dependencies first
  The full version of error log was saved into /root/LightGBM_compilation.log
  ----------------------------------------
  ERROR: Failed building wheel for lightgbm
  Running setup.py clean for lightgbm
  Building wheel for PyYAML (setup.py): started
  Building wheel for PyYAML (setup.py): finished with status 'done'
  Created wheel for PyYAML: filename=PyYAML-3.13-cp36-cp36m-linux_x86_64.whl size=43087 sha256=509a08e77cc9d7c5d42f4a2b579033ec8187ab1fc2fda15ea45ea128b742544a
  Stored in directory: /tmp/pip-ephem-wheel-cache-8plv9ik6/wheels/ab/80/60/97eaebe423482bcf0963b19495b4cfe6c4caef59761a0c427d
  Building wheel for sklearn (setup.py): started
  Building wheel for sklearn (setup.py): finished with status 'done'
  Created wheel for sklearn: filename=sklearn-0.0-py2.py3-none-any.whl size=1316 sha256=785b05d3eb19fbdc07aa3bb50e65173786abd91407bf76fd7b1a14168ecc3f60
  Stored in directory: /tmp/pip-ephem-wheel-cache-8plv9ik6/wheels/23/9d/42/5ec745cbbb17517000a53cecc49d6a865450d1f5cb16dc8a9c
  Building wheel for wrapt (setup.py): started
  Building wheel for wrapt (setup.py): finished with status 'done'
  Created wheel for wrapt: filename=wrapt-1.11.1-cp36-cp36m-linux_x86_64.whl size=70712 sha256=54d36c0348cc222346442a22b537115c6801c5b96919a4e722126717abd19e06
  Stored in directory: /tmp/pip-ephem-wheel-cache-8plv9ik6/wheels/94/0f/ec/66085641573800014bb0c8b657f3366eff641c42df79abbfe9
  Building wheel for psycopg2 (setup.py): started
  Building wheel for psycopg2 (setup.py): finished with status 'done'
  Created wheel for psycopg2: filename=psycopg2-2.8.4-cp36-cp36m-linux_x86_64.whl size=424336 sha256=ba000dbdc0e25ddc26f1cd1b41344e0d5d37728b5a95514d2b135ae3c4daf459
  Stored in directory: /tmp/pip-ephem-wheel-cache-8plv9ik6/wheels/1e/cb/03/20479d63812e4a01da92afa8753f6ad37f87806c24a620aaa0
Successfully built Bottleneck empyrical googleapis-common-protos PyYAML sklearn wrapt psycopg2
Failed to build lightgbm
Installing collected packages: numpy, Bottleneck, cachetools, certifi, chardet, six, python-dateutil, pytz, pandas, scipy, idna, urllib3, requests, wrapt, lxml, pandas-datareader, empyrical, pyasn1, rsa, pyasn1-modules, google-auth, protobuf, googleapis-common-protos, google-api-core, google-cloud-core, google-resumable-media, google-cloud-storage, joblib, scikit-learn, lightgbm, numexpr, PyYAML, sklearn, tables, influxdb, websocket-client, oauthlib, requests-oauthlib, kubernetes, psycopg2
    Running setup.py install for lightgbm: started
    Running setup.py install for lightgbm: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-2k6_q4kj/lightgbm/setup.py'"'"'; __file__='"'"'/tmp/pip-install-2k6_q4kj/lightgbm/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-azijamx_/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.6m/lightgbm
         cwd: /tmp/pip-install-2k6_q4kj/lightgbm/
    Complete output (38 lines):
    running install
    INFO:LightGBM:Starting to compile the library.
    INFO:LightGBM:Starting to compile with CMake.
    Traceback (most recent call last):
      File "/tmp/pip-install-2k6_q4kj/lightgbm/setup.py", line 77, in silent_call
        output = subprocess.check_output(cmd, stderr=subprocess.STDOUT)
      File "/usr/local/lib/python3.6/subprocess.py", line 356, in check_output
        **kwargs).stdout
      File "/usr/local/lib/python3.6/subprocess.py", line 423, in run
        with Popen(*popenargs, **kwargs) as process:
      File "/usr/local/lib/python3.6/subprocess.py", line 729, in __init__
        restore_signals, start_new_session)
      File "/usr/local/lib/python3.6/subprocess.py", line 1364, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'cmake': 'cmake'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-2k6_q4kj/lightgbm/setup.py", line 338, in <module>
        'Topic :: Scientific/Engineering :: Artificial Intelligence'])
      File "/usr/local/lib/python3.6/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-2k6_q4kj/lightgbm/setup.py", line 261, in run
        openmp_include_dir=self.openmp_include_dir, openmp_library=self.openmp_library)
      File "/tmp/pip-install-2k6_q4kj/lightgbm/setup.py", line 200, in compile_cpp
        silent_call(cmake_cmd, raise_error=True, error_msg='Please install CMake and all required dependencies first')
      File "/tmp/pip-install-2k6_q4kj/lightgbm/setup.py", line 86, in silent_call
        raise Exception("\n".join((error_msg, LOG_NOTICE)))
    Exception: Please install CMake and all required dependencies first
    The full version of error log was saved into /root/LightGBM_compilation.log
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-2k6_q4kj/lightgbm/setup.py'"'"'; __file__='"'"'/tmp/pip-install-2k6_q4kj/lightgbm/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-azijamx_/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.6m/lightgbm Check the logs for full command output.](url)

**Comment by queirozfcom** [comment]
Also, started seeing this error earlier today (UTC) both on MacOS and on Linux. On MacOS, it seems it goes away after installing `cmake` via brew but on Linux I haven't had the chance to ry that out yet.

**Comment by ucabsdp** [comment]
I think this maybe linked to the new scipy release today?

**Comment by queirozfcom** [comment]
My previous successful builds used scipy 1.3.3, and the ones that are failing also use this very same version. From my use case it doesn't look like it's because of scipy.

**Comment by ucabsdp** [comment]
Same, we use an older version of scipy so I'm not 100%, but the scipy release is the only thing I can find that has changed since the error started occurring.

**Comment by queirozfcom** [comment]
We worked around the problem by adding `cmake` to the list of OS packages to be installed before running the build (debian-based linux)

**Comment by ucabsdp** [comment]
hmm, we also had cmake installed in our images but still got the error which makes me think it was another dependency

**Comment by StrikerRUS** [comment]
@mlubej 

> Collecting lightgbm
  Using cached lightgbm-2.3.1.tar.gz (679 kB)
...
Building wheels for collected packages: lightgbm
  Building wheel for lightgbm (setup.py) ... \

I wonder, why it doesn't use pre-built wheel but compiles from sources?.. 
https://pypi.org/project/lightgbm/#files

@queirozfcom 

> Did anything change on your side?

Nope. The latest PyPI release of LightGBM: Nov 29, 2019.

@mlubej @ucabsdp @queirozfcom 

I guess the reason is behind the following:

![image](https://user-images.githubusercontent.com/25141164/72856813-be2f7e80-3ccc-11ea-9b88-f02c80b48388.png)

Can you try to downgrade `pip` itself?

**Comment by mlubej** [comment]
@StrikerRUS Yep, good call. Tried downgrading to pip==19.3.1 and installation was successful. Tried uninstalling and again installing again a few times on the latest pip and 19.3.1 pip and always the same outcome.

**Comment by mlubej** [comment]
Also solved the problem on Windows10

**Comment by StrikerRUS** [comment]
@mlubej Thank you for your feedback!

**Comment by StrikerRUS** [comment]
Closing in favor of #2707 which has some insights about wheel naming issue.
