### ISSUE TITLE
Update packages on conda-forge

### ISSUE THREAD

**Issue by jimmywan** [microsoft/LightGBM#2704]
## Summary

conda-forge  is currently out of date:
https://anaconda.org/conda-forge/lightgbm

## Motivation

Lots of people use conda to ease the burden of installing packages that require library installations to work properly.

**Comment by StrikerRUS** [comment]
@jimmywan Sorry, but we do not maintain that package. Please post an issue in LightGBM conda-forge recipe repo: https://github.com/conda-forge/lightgbm-feedstock/issues
