### ISSUE TITLE
How does lightGBM handle prediction using a feature having no missing data in training but missing data in testing?

### ISSUE THREAD

**Issue by Sanchita-P** [microsoft/LightGBM#2706]
How does lightGBM handle prediction using a feature having no missing data in training but missing data in testing?
Recently, I came across a scenario where my training data did not have nulls for a feature while training but had nulls while testing. This didn't raise an error but caused the model performance to drop significantly. 
@guolinke & @Laurae2 Thank you for your help in advance! :)

**Comment by StrikerRUS** [comment]
Refer to https://github.com/microsoft/LightGBM/issues/2292#issuecomment-517103167.
