### ISSUE TITLE
predict probabilities parameter clarification

### ISSUE THREAD

**Issue by geoHeil** [Microsoft/LightGBM#271]
What is `num_iteration` parameter used for when predicting probabilities via the sklearn API?

**Comment by guolinke** [comment]
@geoHeil It is the trained number of iterations(trees) you want to predict with.
e.g. if num_iteration==2, it will use the tree trained of first 2 trees to predict for non-multi-class task, and use first 2*num_class  trees for  multi-class task.

**Comment by geoHeil** [comment]
@guolinke  But usually I would want to predict with all the num_iterations trained for binary classification?

**Comment by guolinke** [comment]
@geoHeil 
If you want to used all of them, just keep num_iterations as default value.

**Comment by geoHeil** [comment]
@guolinke so do I understand correctly that: `def predict_proba(self, X, raw_score=False, num_iteration=0):` from https://github.com/Microsoft/LightGBM/blob/master/python-package/lightgbm/sklearn.py will use **all** trees to form a prediction?

What is the reason to use less trees?

**Comment by guolinke** [comment]
@geoHeil 
Yes, it will use all of trees.

There are many reasons to use less trees, e.g. too much trees may cause over-fitting .
