### ISSUE TITLE
Problem: LightGBMError: std::bad_alloc with relatively small data

### ISSUE THREAD

**Issue by PhilipMay** [microsoft/LightGBM#2711]
## Environment info
- Operating System: Ubuntu 18.04.3 LTS (bionic)
- CPU/GPU model: not using GPU
- C++/Python/R version: Python 3.6
- LightGBM version or commit hash: lightgbm 2.3.1 (from pip)
- Server with 32 GB RAM with about 30 GB free

## Error message
```
---------------------------------------------------------------------------
LightGBMError                             Traceback (most recent call last)
<ipython-input-3-fe069a1da455> in <module>
     17         early_stopping_rounds=15,
     18         evals_result=evals_result,
---> 19         num_boost_round  = 10000,
     20         )

~/miniconda3/envs/homl/lib/python3.6/site-packages/lightgbm/engine.py in train(params, train_set, num_boost_round, valid_sets, valid_names, fobj, feval, init_model, feature_name, categorical_feature, early_stopping_rounds, evals_result, verbose_eval, learning_rates, keep_training_booster, callbacks)
    226     # construct booster
    227     try:
--> 228         booster = Booster(params=params, train_set=train_set)
    229         if is_valid_contain_train:
    230             booster.set_train_data_name(train_data_name)

~/miniconda3/envs/homl/lib/python3.6/site-packages/lightgbm/basic.py in __init__(self, params, train_set, model_file, model_str, silent)
   1714                 train_set.construct().handle,
   1715                 c_str(params_str),
-> 1716                 ctypes.byref(self.handle)))
   1717             # save reference to data
   1718             self.train_set = train_set

~/miniconda3/envs/homl/lib/python3.6/site-packages/lightgbm/basic.py in _safe_call(ret)
     43     """
     44     if ret != 0:
---> 45         raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))
     46 
     47 

LightGBMError: std::bad_alloc
```

## Reproducible examples
I created 2 files with `Dataset.save_binary()` one train one validation. 
``` python
train_data = lgb.Dataset(x_train, label=y_train)
val_data = lgb.Dataset(x_val, label=y_val)

train_data.save_binary('data/train_data.bin')
val_data.save_binary('data/val_data.bin')
```

Here is the shape:
```
x_train.shape: (12310880, 34)
y_train.shape: (12310880,)
x_val.shape: (3077720, 34)
y_val.shape: (3077720,)
```

And the sizes:
```
x_train size in MB 1596
y_train size in MB 46
x_val size in MB 399
y_val size in MB 11
```

Code here:
``` python
import numpy as np
import lightgbm as lgb

num_classes = 395

param = {
        'objective': 'multiclass',            
        'num_class': num_classes,
        'max_bin': 20,
        'num_leaves': 10,
        }    

train_data = lgb.Dataset('data/train_data.bin')
val_data = lgb.Dataset('data/val_data.bin')

evals_result = {}

bst = lgb.train(
        param, 
        train_data, 
        valid_sets=[val_data], 
        early_stopping_rounds=15, 
        evals_result=evals_result,
        num_boost_round  = 10000,
        )
```

## Steps to reproduce

Run the code. Exception is thrown.
There should be enough memory for the data since the server has about 30 GB of free mem.

Can someone please tell me if this is a bug and if there is a workaround?

I saw some other issues with this `LightGBMError: std::bad_alloc` problem. But all are already closed (for some reason).

**Comment by StrikerRUS** [comment]
Hi @PhilipMay !

Aren't `num_classes * num_boost_round = 395 * 10000 = 3 950 000` estimators (in the worst scenario where early stopping doesn't occur) too much for your machine?

ping @guolinke for further investigation

**Comment by PhilipMay** [comment]
@StrikerRUS yes that might be the case but the training does not even begin.

@guolinke what do you think?

**Comment by guolinke** [comment]
@PhilipMay 
there are 3 arrays (gradients, hessians, and  scores ), whose size is `num_class x num_data`. I guess your memory is not enough for the `395` classes.

**Comment by PhilipMay** [comment]
Hi @guolinke 
thanks for the answer.
Do LightGBM stores the "train and validation" data as it is plus 3 times num_class x num_data in float32 I guess?

**Comment by guolinke** [comment]
gradients and hessians are only for training data, and their type is float32. 
For score, both training data and val data need, and it type is float64.

**Comment by PhilipMay** [comment]
@guolinke Great thanks! Last remaining question is if it is possible to apply LightGBM in a batch mode?

**Comment by guolinke** [comment]
you can try the `refit`  mode, but it, of course, will lose on accuracy.

**Comment by PhilipMay** [comment]
Ok. Thanks. Closing this now.
