### ISSUE TITLE
Missing value handle in prediction

### ISSUE THREAD

**Issue by ogru** [microsoft/LightGBM#2712]
Hello everyone, 

Here is my problem:
I trained a model with the CLI version. The training data has missing values. No specific handle was used (i.e. NA or NaN), missing values were simply represented with ",," in the csv. I used the default settings, suggesting that LightGBM would insert zeros where it finds missing, or ",,". 

The problem that I have is with prediction. I get completely different results when I manually insert zeros into my test data frame vs when I let python handle it. Here is the code I was using:

import lightgbm as lgb

model = lgb.Booster(model_file="myCLI_trained_model.txt")

prediction = model.predict(test)
prediction2 = model.predict(test.fillna(value=0))

What am I doing wrong?

Many thanks!

**Comment by guolinke** [comment]
could you provide the reproduce example? 
`myCLI_trained_model.txt` and `test` is needed.

**Comment by ogru** [comment]
Hi @guolinke,
Unfortunately, I cannot share the data nor the model due to company's policy. 

Is there any other way I could help resolve this? Perhaps debug it myself if you let me know what to look for?

Many thanks

**Comment by guolinke** [comment]
If you can reproduce this by randomly generative data, it would be better.
I guess the reason is the `test`, if it is load by np or other package, `,,` may be parsed as `na`,  while LightGBM will parse it as `0`.

**Comment by guolinke** [comment]
@ogru 
any updates?

**Comment by ogru** [comment]
Hi @guolinke,

Yes! LightGBM parses ",," as "nan" I confirmed that empirically. The entire pipeline: CLI + python behaves as designed. 

Closing the ticket.

Thanks,
