### ISSUE TITLE
Improving compatibility with Scikit-learn

### ISSUE THREAD

**Issue by daviddiazvico** [microsoft/LightGBM#2720]
## Summary

Move parameter validation and "_ parameter" setting from `__init__` to `fit` in the sklearn wrapper.

## Motivation

Attain full compatibility with sklearn and skopt automated hyper-parameter search. 

## Description

According to the [Scikit-learn development guide](https://scikit-learn.org/stable/developers/develop.html#parameters-and-init), the `__init__` method should not do any parameter validation or set any "trailing _" parameter.

In order to have an estimator compatible with the automated hyper-parameter search objects (GridSearchCV, RandomizedSearchCV, skopt.BayesSearchCV, etc.), that should be handled by the `fit` method.

In particular, the instantiation of `_Booster` and other parameters should be moved from `__init__` to the beginning of `fit` in the sklearn wrapper.

This is related to (a sub problem of) #2628 

Related PR: #2721 

Thanks!

## References

* [Scikit-learn development guide](https://scikit-learn.org/stable/developers/develop.html#parameters-and-init)

**Comment by StrikerRUS** [comment]
Refer to https://github.com/microsoft/LightGBM/pull/2721#issuecomment-580902791.
