### ISSUE TITLE
Problem / Bug: LightGBMError: Multiclass objective and metrics don't match

### ISSUE THREAD

**Issue by PhilipMay** [microsoft/LightGBM#2735]
## Environment info
- Operating System: Ubuntu 18.04.3 LTS (bionic)
- CPU/GPU model: not using GPU
- C++/Python/R version: Python 3.6
- LightGBM version or commit hash: lightgbm 2.3.1 (from pip)

## Error message
```
---------------------------------------------------------------------------
LightGBMError                             Traceback (most recent call last)
<ipython-input-18-3244fbab7e4b> in <module>
     25         #feval=mltb.lightgbm.multi_class_accuracy_score_factory(num_classes),
     26         evals_result=evals_result,
---> 27         num_boost_round  = 10000,
     28         )
     29 

~/miniconda3/envs/homl/lib/python3.6/site-packages/lightgbm/engine.py in train(params, train_set, num_boost_round, valid_sets, valid_names, fobj, feval, init_model, feature_name, categorical_feature, early_stopping_rounds, evals_result, verbose_eval, learning_rates, keep_training_booster, callbacks)
    226     # construct booster
    227     try:
--> 228         booster = Booster(params=params, train_set=train_set)
    229         if is_valid_contain_train:
    230             booster.set_train_data_name(train_data_name)

~/miniconda3/envs/homl/lib/python3.6/site-packages/lightgbm/basic.py in __init__(self, params, train_set, model_file, model_str, silent)
   1712             self.handle = ctypes.c_void_p()
   1713             _safe_call(_LIB.LGBM_BoosterCreate(
-> 1714                 train_set.construct().handle,
   1715                 c_str(params_str),
   1716                 ctypes.byref(self.handle)))

~/miniconda3/envs/homl/lib/python3.6/site-packages/lightgbm/basic.py in construct(self)
   1083                                 init_score=self.init_score, predictor=self._predictor,
   1084                                 silent=self.silent, feature_name=self.feature_name,
-> 1085                                 categorical_feature=self.categorical_feature, params=self.params)
   1086             if self.free_raw_data:
   1087                 self.data = None

~/miniconda3/envs/homl/lib/python3.6/site-packages/lightgbm/basic.py in _lazy_init(self, data, label, reference, weight, group, init_score, predictor, silent, feature_name, categorical_feature, params)
    885             self.__init_from_csc(data, params_str, ref_dataset)
    886         elif isinstance(data, np.ndarray):
--> 887             self.__init_from_np2d(data, params_str, ref_dataset)
    888         elif isinstance(data, list) and len(data) > 0 and all(isinstance(x, np.ndarray) for x in data):
    889             self.__init_from_list_np2d(data, params_str, ref_dataset)

~/miniconda3/envs/homl/lib/python3.6/site-packages/lightgbm/basic.py in __init_from_np2d(self, mat, params_str, ref_dataset)
    935             c_str(params_str),
    936             ref_dataset,
--> 937             ctypes.byref(self.handle)))
    938         return self
    939 

~/miniconda3/envs/homl/lib/python3.6/site-packages/lightgbm/basic.py in _safe_call(ret)
     43     """
     44     if ret != 0:
---> 45         raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))
     46 
     47 

LightGBMError: Multiclass objective and metrics don't match
```

## Reproducible examples
Before the training even starts I get the error.

``` python
param = {
        'objective': 'multiclass',            
        'metric': 'auc_mu',
        'num_class': 100,
        }    

train_data = lgb.Dataset(x_train, label=y_train)
val_data = lgb.Dataset(x_val, label=y_val)

evals_result = {}

bst = lgb.train(
        param, 
        train_data, 
        valid_sets=[val_data], 
        early_stopping_rounds=5, 
        evals_result=evals_result,
        num_boost_round  = 100,
        )
```

What's the problem here?

**Comment by PhilipMay** [comment]
Well I guess it is because auc_mu is not releases in the current PIP package.
Closing again.

**Comment by bernarde01** [comment]
Hi Philip
I came across the same error. I was hoping to make use of auc_mu - is this currently not available?

**Comment by PhilipMay** [comment]
@bernarde01 Yes. It is in the master branch but not yet released.

**Comment by bernarde01** [comment]
Thanks Phillip. I'm very eager to take a look at this metric. I have taken a look at the article that describes this and it looks very promising as a performance metric for multi-class classification.

**Comment by PhilipMay** [comment]
@bernarde01 Yes. You could try to compile LightGBM from the sources: https://lightgbm.readthedocs.io/en/latest/Installation-Guide.html

For multi class problems with LightGBM I use F1 (mostly micro). Thats why I wrote a small util to plug SkLearn F1 into LightGBM. See here:
- https://github.com/PhilipMay/mltb#module-lightgbm
- https://github.com/PhilipMay/mltb/blob/master/mltb/lightgbm.py#L7

PS: Feedback is very welcome.

**Comment by bernarde01** [comment]
@PhilipMay Thanks, I checked the util you generated. To confirm, the feval parameter allows for a custom evaluation function. I am curious: if a 'metric' is defined in the parameters, like:
params = {
        'objective' : 'multiclass',
        'metric' : {'multi_logloss'},
    }

will this metric be overwritten by the custom evaluation function defined in feval? As I understand the 'metric' defined in the parameters is used for evaluation (from the lgbm documentation, description of 'metric': "metric(s) to be evaluated on the evaluation set(s)" )

**Comment by PhilipMay** [comment]
In LightGBM you can provide more then just 1 metric that is evaluated after each boosting round. So if you provide one by `metric` and one by `feval` both should be evaluated. But for early stopping lightGBM checks the metric provided by `metric`.

**Comment by StrikerRUS** [comment]
> But for early stopping lightGBM checks the metric provided by metric.

LightGBM checks all metrics: from `metric` and from `feval` params. Also, you can use `first_metric_only` param to overwrite that behavior.
