### ISSUE TITLE
MissingType info seems missing from decision_type when loading model from text file

### ISSUE THREAD

**Issue by thirdwing** [microsoft/LightGBM#2738]
## Environment info

Operating System: OSX

CPU/GPU model: CPU

C++/Python/R version: 2.2.4

LightGBM version or commit hash: 86269ee38da20785097cd35aa7eb0b946864fe76

## Reproducible examples

[random_lgbm_model.zip](https://github.com/microsoft/LightGBM/files/4150762/random_lgbm_model.zip)

## Steps to reproduce

1. there is a lightgbm model in text format and tiny data set containing many NA values
2.
3.

As I understand, when we load model from text file, the `decision_type_` is read from file and no missing type is set: https://github.com/microsoft/LightGBM/blob/master/src/io/tree.cpp#L588

`decision_type_` is 2 in this model.

When we predict, we first get missing type from decision type: https://github.com/microsoft/LightGBM/blob/master/include/LightGBM/tree.h#L223

I am afraid we always get missing type 0 if the decision type is 2 using the following function:

```cpp
  inline static int8_t GetMissingType(int8_t decision_type) {
    return (decision_type >> 2) & 3;
  }
```

With missing type 0, the NA values would be filled with zeros: https://github.com/microsoft/LightGBM/blame/master/include/LightGBM/tree.h#L224-L228

In this model, we have `use_missing=True` and `zero_as_missing=False`, so I don't think NA values should be filled with zeroes.

```
[use_missing: 1]
[zero_as_missing: 0]
```

Is this expected? Or did I miss anything?

**Comment by guolinke** [comment]
sorry, I don't understand what is the problem. 
The missing type is the last 3-rd and 4-th bits, total 4 values, in `decision_type`. for `decision_type_ = 2`, the missing type is 0.  

the last two bit of `decision_type` is to indicate the is_categorical and is_default_left.

**Comment by thirdwing** [comment]
The model has `use_missing=True`, I don't think the NA values should be filled with zeroes.

**Comment by guolinke** [comment]
If not nan in one feature in training data, LightGBM will set the missing type of that feature as none.

**Comment by thirdwing** [comment]
Thanks!
