### ISSUE TITLE
LightGBMError: Check failed: best_split_info.left_count > 0 for ranking task

### ISSUE THREAD

**Issue by kenyeung128** [microsoft/LightGBM#2742]
hi, 

when would lightgbm 2.3.2 be released? as the documentation online (https://lightgbm.readthedocs.io/) is 2.3.2 with some new features but the latest python package is lightgbm 2.3.1. Thanks.

**Comment by StrikerRUS** [comment]
@kenyeung128 Hi!

You can download the latest nightly version from this page: https://lightgbm.readthedocs.io/en/latest/Installation-Guide.html if you do not want to build from sources.

I think we need some time to test large changes introduced in #2699, fix some critical issues, wait for any news for #2628 and so on.

Also, I believe the next release should be 2.4.0 at least, or even 3.0.0, according to the semantic versioning we try to follow due to removal of some parameters.

cc @guolinke

**Comment by kenyeung128** [comment]
hi @StrikerRUS thanks for the info, i have followed the installation guide and installed the python version with the latest source code.

however, i get an error as below when i tried to fit a LGBMRanker

LightGBMError: Check failed: best_split_info.left_count > 0 at /data/github/LightGBM/src/treelearner/serial_tree_learner.cpp, line 706 .

do u have any idea?

**Comment by guolinke** [comment]
@kenyeung128 can you provide the reproduce example?

**Comment by kenyeung128** [comment]
hi @guolinke 

the example is like this 

gbm = lgb.LGBMRanker(n_estimators=800, score='ncdg')
gbm.fit(x_train.drop(columns=columns_exclude), y_train, group=q_train, 
            categorical_feature=columns_cateogry,
            eval_set=[(x_valid.drop(columns=columns_exclude), y_valid)],
            eval_group=[q_valid], eval_at=[1,2,3], early_stopping_rounds=200, verbose=True,
            eval_metric='ndcg')

and found out seems the root cause is that it's using **categorical_feature**, there are examples in x_train but not in x_valid, so it throws out the exception. But in previous version 2.3.1 lightgbm, it's working

**Comment by guolinke** [comment]
Thanks @kenyeung128 , could you provide the data for debugging?

**Comment by kenyeung128** [comment]
@guolinke it's quite a big dataset, but i tried to provide data in smaller dataset but it didn't come up with the error. I suspect it's something with the split of data not evenly distributed between train/valid, and somehow it throws the exception

**Comment by guolinke** [comment]
@kenyeung128 is that possible to reproduce this by randomly generated data?

**Comment by rgranvil** [comment]
@guolinke I've also been running into this error when fitting models with categorical predictors in the latest master branch.  Here is a reproducible example in R v3.5.2:

**Code:**
```r
library(lightgbm)
set.seed(1)
data <- data.frame(
  y = as.integer(runif(1000) > .5)
  ,x = sample(c(1,1,1,2), 1000, replace = TRUE)
)
data_matrix <- as.matrix(data[, "x", drop = FALSE])
dtrain <- lgb.Dataset(data_matrix, label = data$y, categorical_feature = "x")

model <- lgb.train(
  params = list(objective = "binary")
  ,data = dtrain
  ,nrounds = 1
)
```

**Error:**
```r
[LightGBM] [Fatal] Check failed: best_split_info.right_count > 0 at /tmp/RtmpE5HQrB/R.INSTALL1226e7bebac9e/lightgbm/src/src/treelearner/serial_tree_learner.cpp, line 706 .
```

**Comment by guolinke** [comment]
@kenyeung128 @rgranvil thanks very much, could you try the #2824 ?

**Comment by rgranvil** [comment]
@guolinke I confirmed #2824 fixes the issue for me.  Thanks for the quick fix.

**Comment by chameleonTK** [comment]
I still found this issue when I use GPU.

**Comment by DeiPlusAY** [comment]
I also found this issue on GPU build.

**Comment by Dronablo** [comment]
I also found this issue occurring from time to time on relatively fresh GPU build. For ~4 Gb dataset with 250000 rows and 1500 columns it could train normally for hours, than I got 
```LightGBMError: Check failed: (best_split_info.right_count) > (0) at D:\Python\projects\lib\2003_lgbm\LightGBM\src\treelearner\serial_tree_learner.cpp, line 614``` which is at https://github.com/microsoft/LightGBM/blob/a2a38b6cd527f8c87d0250e0cbb89b12899c27dd/src/treelearner/serial_tree_learner.cpp#L632 in current code. Any ideas @guolinke, @StrikerRUS ?

**Comment by chutcheson** [comment]
I'm encountering a very similar issue to this on 3.0.0 on GPU. I dropped my categorical columns because I was concerned that was the cause. 

But, I still get the error, even though I might hit it less frequently?

**Comment by MrRobot2211** [comment]
Is this still going on? we should start a new entry

**Comment by Marmeladenbrot** [comment]
I have this error on CPU with the latest version on Windoes 10 x64.

Data is private so I sadly can't share it.

`Check failed: (best_split_info.right_count) > (0) at c:\users\vssadministrator\appdata\local\temp\pip-req-build-lqyem8a1\compile\src\treelearner\serial_tree_learner.cpp, line 661 .`

**Comment by muttoni** [comment]
Same here on CPU with macOS using virtualenv
```
File "/Users/user/.virtualenvs/flask/lib/python3.8/site-packages/lightgbm/sklearn.py", line 770, in fit
    super(LGBMRegressor, self).fit(X, y, sample_weight=sample_weight,
  File "/Users/user/.virtualenvs/flask/lib/python3.8/site-packages/lightgbm/sklearn.py", line 612, in fit
    self._Booster = train(params, train_set,
  File "/Users/user/.virtualenvs/flask/lib/python3.8/site-packages/lightgbm/engine.py", line 252, in train
    booster.update(fobj=fobj)
  File "/Users/user/.virtualenvs/flask/lib/python3.8/site-packages/lightgbm/basic.py", line 2458, in update
    _safe_call(_LIB.LGBM_BoosterUpdateOneIter(
  File "/Users/user/.virtualenvs/flask/lib/python3.8/site-packages/lightgbm/basic.py", line 55, in _safe_call
    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))
lightgbm.basic.LightGBMError: Check failed: (best_split_info.left_count) > (0) at /Users/runner/work/1/s/python-package/compile/src/treelearner/serial_tree_learner.cpp, line 651 .

```

**Comment by shiyu1994** [comment]
@muttoni @chutcheson Could you provide a reproducible example, or, if possible, share your dataset with us? We are trying to remove this bug before the next release. Any help is really appreciated. Thanks.

**Comment by arkothiwala** [comment]
[lgbm bug.zip](https://github.com/microsoft/LightGBM/files/5949195/lgbm.bug.zip)

The issue is reproducible with attached dataset @shiyu1994 

### Error message:
_LightGBMError: Check failed: (best_split_info.left_count) > (0) at D:\a\1\s\python-package\compile\src\treelearner\serial_tree_learner.cpp, line 651 ._

### Code to reproduce:
```
from sklearn.model_selection import train_test_split
train_df, test_df  = pd.read_csv('train.csv'),  pd.read_csv('test.csv')
final_df = pd.concat([train_df, test_df], ignore_index = True)
y = final_df["domain"]
x = final_df.drop("domain", axis = 1)

clf = lightgbm.LGBMClassifier(n_jobs=-1, boosting_type='goss', random_state=0)

# Change test_size parameter to remove error 
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=0) 
clf.fit(x_train,y_train)

# Uncomment this line to remove error
#clf.fit(x,y)                                             
```

### **Few Observations**
1. Does not throw error upon changing **test_size** from 0.2 to any value (0.21, 0.3 etc.)
2. Does not throw error if you run `clf.fit(x,y)` instead of `clf.fit(x_train, y_train)`
3. Throws same error if **random_state** is changed in either `sklearn.model_selection.train_test_split` or `lightgbm.LGBMClassifier`

**Comment by victor-ab** [comment]
I ran into the same problem here when using multiclassova. Multiclass worked nicely.

**Comment by zacheberhart-kd** [comment]
I also have this issue when using a similar workflow as the example @arkothiwala posted.

**Comment by shiyu1994** [comment]
@arkothiwala @zacheberhart-kd The example is OK with the latest master branch. You can clone the source code and build the python package from source.

**Comment by Teeeto** [comment]
I built from source today, have this error on GPU both Windows and Linux

Params = {
    'objective': 'multiclass',
    'metric':['auc_mu','multiclass'],
    'device':'gpu',
    'num_threads': 6,
    'num_leaves': 127,
    'num_class': 7,
    'max_bin': 63,
    'min_data_in_leaf':50,
    'bin_construct_sample_cnt' :5*100*1000,
    'learning_rate': 0.03,
    'verbose': 1
}

[LightGBM] [Info] This is the GPU trainer!!
[LightGBM] [Info] Total Bins 29705
[LightGBM] [Info] Number of data points in the train set: 8293105, number of used features: 964
[LightGBM] [Info] Using GPU Device: TITAN RTX, Vendor: NVIDIA Corporation
[LightGBM] [Info] Compiling OpenCL Kernel with 64 bins...
[LightGBM] [Info] GPU programs have been built
[LightGBM] [Info] Size of histogram bin entry: 8
[LightGBM] [Info] 935 dense feature groups (7402.75 MB) transferred to GPU in 2.895087 secs. 1 sparse feature groups
[LightGBM] [Info] Start training from score -1.620340
[LightGBM] [Info] Start training from score -2.736469
[LightGBM] [Info] Start training from score -2.609875
[LightGBM] [Info] Start training from score -2.799483
[LightGBM] [Info] Start training from score -2.936053
[LightGBM] [Info] Start training from score -3.110144
[LightGBM] [Info] Start training from score -0.682573
[LightGBM] [Fatal] Check failed: (best_split_info.left_count) > (0) at /C/lgb/LightGBM/python-package/compile/src/treelearner/serial_tree_learner.cpp, line 653 .

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/lightgbm/engine.py", line 249, in train
    booster.update(fobj=fobj)
  File "/usr/local/lib/python3.8/dist-packages/lightgbm/basic.py", line 2636, in update
    _safe_call(_LIB.LGBM_BoosterUpdateOneIter(
  File "/usr/local/lib/python3.8/dist-packages/lightgbm/basic.py", line 110, in _safe_call
    raise LightGBMError(_LIB.LGBM_GetLastError().decode('utf-8'))
lightgbm.basic.LightGBMError: Check failed: (best_split_info.left_count) > (0) at /C/lgb/LightGBM/python-package/compile/src/treelearner/serial_tree_learner.cpp, line 653 .

**Comment by shiyu1994** [comment]
@Teeeto Thanks for the information. For GPU version, this bug has a separated issue #2793. Currently, we are focusing on releasing a new version. And fixing this bug is not included in the new release plan. But I can investigate this next week.

**Comment by abbey2017** [comment]
@Teeeto Increasing the number of features resolved the exception for me on CPU.

**Comment by Teeeto** [comment]
> @Teeeto Increasing the number of features resolved the exception for me on CPU.
I dont have this issue on CPU. However CPU is slow - one iteration per 2 minutes on my dataset (a 60-core machine).
GPU is like 30x faster.


> @Teeeto Thanks for the information. For GPU version, this bug has a separated issue #2793. Currently, we are focusing on releasing a new version. And fixing this bug is not included in the new release plan. But I can investigate this next week.
Thank You! I think it would be great to prioritize this fix since the issue is prohibitive in certain use cases.

**Comment by Teeeto** [comment]
Just built on linux - problem still persists, there is a circle of issues referencing each other all closed, not sure which one to reopen.

**Comment by Jumabek** [comment]
Issue disappered when 

```
pip uninstall lightgbm-3.1.1  
pip install lightgbm-3.2.1
```

**Comment by sharpe5** [comment]
Solution from @Junbabek works - but pip does not seem to have v3.2.1 which is the minimum version.

If using Anaconda install [LightGBM v3.2.1](https://anaconda.org/conda-forge/lightgbm):
```
conda install -c conda-forge lightgbm
```

To summarise this entire thread:
* Issue caused when category 0 is the most common feature. 
* Install v3.2.1 to fix.

**Comment by StrikerRUS** [comment]
@sharpe5 

> but under Windows, pip does not have v3.2.1 yet.

Wheel file `v3.2.1` for Windows has been on PyPI since April, please double check:
https://pypi.org/project/lightgbm/#files

![image](https://user-images.githubusercontent.com/25141164/129356902-98127975-8cf5-4d0b-b6f3-95238e398a34.png)

**Comment by pavlexander** [comment]
got the version 3.3.3, python. 

The issue is bugging me for the past 2 days.. The data set is 500k, with 1500 features. There seems to be some correlation with `min_gain_to_split` parameter. When the value is 1 I have not yet seen any errors, however on value 0 (default) it seems to crash quite often. Take this comment with caution since I have not ran enough tests yet.. Training on GPU.

crashed on

> {'learning_rate': 0.43467624523546383, 'max_depth': 8, 'num_leaves': 201, 'feature_fraction': 0.9, 'bagging_fraction': 0.7000000000000001, 'bagging_freq': 8}

> {'learning_rate': 0.021403440298427053, 'max_depth': 2, 'num_leaves': 176, 'lambda_l1': 3.8066251775052895, 'lambda_l2': 1.08526150100961e-08, 'feature_fraction': 0.6, 'bagging_fraction': 0.9, 'bagging_freq': 6}

> {'learning_rate': 0.3493368922746614, 'max_depth': 6, 'num_leaves': 109, 'lambda_l1': 4.506588272812341e-05, 'lambda_l2': 2.5452579091348995e-07, 'feature_fraction': 0.7000000000000001, 'bagging_fraction': 1.0, 'bagging_freq': 6, 'min_gain_to_split': 0}

> {'learning_rate': 0.17840010040986135, 'max_depth': 12, 'num_leaves': 251, 'lambda_l1': 0.004509589012189404, 'lambda_l2': 3.882151732343819e-08, 'feature_fraction': 0.30000000000000004, 'bagging_fraction': 1.0, 'bagging_freq': 8, 'min_gain_to_split': 0}

the code is:


```
    params = {
        'device_type': "gpu",
        'objective': 'multiclass',  # 
        'metric': 'multi_logloss',  # 
        "boosting_type": "gbdt",
        "num_class": 3,
        'random_state': 123,
        'verbosity': -1,  # hides "No further splits with positive gain, best gain: -inf" warnings
        "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.9, log=True),  # 0.1
        'max_depth': trial.suggest_int('max_depth', 2, 12),
        'num_leaves': trial.suggest_int('num_leaves', 2, 256),  # def 31
        'lambda_l1': trial.suggest_float('lambda_l1', 1e-8, 10.0, log=True),  # 0
        'lambda_l2': trial.suggest_float('lambda_l2', 1e-8, 10.0, log=True),  # 0
        'feature_fraction': trial.suggest_float('feature_fraction', 0.1, 1.0, step=0.1),  # 1
        'bagging_fraction': trial.suggest_float('bagging_fraction', 0.1, 1.0, step=0.1),  # 1
        'bagging_freq': trial.suggest_int('bagging_freq', 0, 10),  # 0
        'min_gain_to_split': trial.suggest_int('min_gain_to_split', 0, 5),
    }
```

with a few changes here and there

**Comment by dpalbrecht** [comment]
I've been consistently having this issue in Kaggle and Colab notebooks while using the [HDFSequence example](https://github.com/microsoft/LightGBM/blob/master/examples/python-guide/dataset_from_multi_hdf5.py) and a GPU when I increase the number of leaves. Is there a generally accepted fix for this issue?

**Comment by ZaydH** [comment]
I also observe this issue with LightGBM version 3.3.2 and a GPU.

My setup for what it's worth:
* OS: Pop!_OS 22.04
* Python: 3.7.13
* CUDA: 12.0
* Nvidia Driver: 525.60.11
* GPU: Nvidia 3090
