### ISSUE TITLE
subset function cause corruption using 2.3.2

### ISSUE THREAD

**Issue by aprilffff** [microsoft/LightGBM#2744]
I have updated to  version 2.3.2. During dataset construction, espectially when I use the function `dataset.subset`, It caused corruption occasionally.  Corruptions not happened every time, but mostly on small datasets(less than 50k samples).

also，`dataset.add_features_from` caused corruptions at the same time.

Any idea on that？

**Comment by guolinke** [comment]
which code version you used?

**Comment by aprilffff** [comment]
> which code version you used?

2.3.2

**Comment by guolinke** [comment]
I mean the git commit id, as we didn't officially release 2.3.2 yet.

**Comment by aprilffff** [comment]
dbb804f

**Comment by guolinke** [comment]
Thanks, I will investigate that. BTW, could you provide the example that can cause corruption? As I didn't see corruption before, it will be helpful for debugging.

**Comment by aprilffff** [comment]
pls use attached files below.
[testfile.zip](https://github.com/microsoft/LightGBM/files/4168696/testfile.zip)

```
import pandas as pd
import lightgbm as lgb
ref=lgb.Dataset('test_ref.bin')
data=pd.read_pickle('test_data.pkl').values
ds=lgb.Dataset(data,reference=ref).construct()

##will cause corruption below##
ds.subset(np.arange(10)).construct()  
```

I though it might be related to the reference. If no ref, it wont  crash.

**Comment by guolinke** [comment]
is "test_ref.bin" generated by the same code version? 
The binary format of Dataset is changed in recent commits.

**Comment by aprilffff** [comment]
same version for sure
