### ISSUE TITLE
segmentation fault on dataset construct

### ISSUE THREAD

**Issue by zcyang** [microsoft/LightGBM#2757]
Hi,

I am dealing with a large data set with 3 million samples and 1500 features, all in float32 type. The total size is about 12G and I want to save it as bin file to save the memory. The segmentation fault happened at construct step. I didn't see this problem with smaller dataset.

```
# save the data as bin
train_data = lgb.Dataset(train_X)
train_data.save_binary("train.bin")

# load the data 
train_data = lgb.Dataset("train.bin")
train_data.construct()  #<- segmentation facult
```

I checked previous issues #385 and #1303 and didn't find useful information there.

The problem also disappeared by setting max_bin smaller values like 128.

**Comment by guolinke** [comment]
@zcyang which code version you used? could you share the data with me?

**Comment by zcyang** [comment]
I am using python version 2.2.3
The data is too large to share. It can be reproduced by generating random matrix of size 3million x1500. Thanks!

**Comment by guolinke** [comment]
Could you share the scripts for reproducing?

**Comment by StrikerRUS** [comment]
ping @zcyang
