### ISSUE TITLE
crash of lightgbm binary

### ISSUE THREAD

**Issue by geoHeil** [Microsoft/LightGBM#277]
The lightgbm binary will crash without any notice.
## Environment info
Operating System: 10.12.3 (happened on 10.12.2 as well)
CPU:
MacBook Pro (Retina, 15', Mitte 2014), 2,5 GHz Intel Core i7
C++/Python/R version: 
- current master branch for lightgbm
- python 3.5.2 (Python 3.5.2 :: Anaconda custom (x86_64))

## Error Message:
none present

## Reproducible examples
- https://github.com/geoHeil/lightGBMCrashReport/blob/master/lightGBM%20crashing.ipynb

## Steps to reproduce

1. with these settings
```
assignments['bagging_fraction'] = 1.0
assignments['learning_rate'] = 0.6
assignments['max_bin'] = 200
assignments['max_depth'] = 30
assignments['min_child_weight'] = 200
assignments['n_estimators'] = 6000
assignments['num_leaves'] = 2000000
assignments['subsample'] = 1.0
assignments['scale_pos_weight'] = 2000
assignments['boosting_type'] = 'gbdt'
assignments['reg_alpha'] = 0
assignments['reg_lambda'] = 2
assignments['is_unbalance'] = True
assignments['min_split_gain'] = 0
assignments['min_child_samples'] = 10
assignments['colsample_bytree'] = 0.8
assignments['subsample_freq'] = 3
assignments['subsample_for_bin'] = 50000
```

**Comment by wxchan** [comment]
num_leaves = 2000000??? out of memory

**Comment by geoHeil** [comment]
Well my bayesian optimization tool was trying a lot of value combinations.

**Comment by geoHeil** [comment]
45000 seems to work as a maximum.
