### ISSUE TITLE
Do inference in Java

### ISSUE THREAD

**Issue by sergun** [microsoft/LightGBM#2777]
Hi!

What is the easiest way to train lightgbm model in python and make predictions from java?

I see jpmml functionalty but wonder f there are no easier to take model and make predictions in java.

Thanks!

**Comment by StrikerRUS** [comment]
You can generate JAVA wrapper for C API functions via SWIG package: https://lightgbm.readthedocs.io/en/latest/Installation-Guide.html#build-java-wrapper. And then call prediction function.
Also, refer to #909.
