### ISSUE TITLE
[feature request] Faster Split (data partition) 

### ISSUE THREAD

**Issue by guolinke** [microsoft/LightGBM#2782]
Besides of histogram construction, the data partition is another time-consuming part in LightGBM. This process is to update the row set for each leaf. 

The code is in the following: 

https://github.com/microsoft/LightGBM/blob/997a469f780f2720055df3b8276c79d412cb15d3/src/treelearner/data_partition.hpp#L113-L172

**Comment by StrikerRUS** [comment]
Closed in favor of being in #2302. We decided to keep all feature requests in one place.

Welcome to contribute this feature! Please re-open this issue (or post a comment if you are not a topic starter) if you are actively working on implementing this feature.
