### ISSUE TITLE
[feature request] avoid re-creating subset for multi-val bin when using bagging

### ISSUE THREAD

**Issue by guolinke** [microsoft/LightGBM#2783]
Refer to the "TODO" 
at https://github.com/microsoft/LightGBM/blob/997a469f780f2720055df3b8276c79d412cb15d3/src/treelearner/serial_tree_learner.cpp#L94-L116

**Comment by StrikerRUS** [comment]
@guolinke Can we close this?

**Comment by guolinke** [comment]
Yeah
