### ISSUE TITLE
AttributeError: 'LGBMRegressor' object has no attribute 'feature_name_'

### ISSUE THREAD

**Issue by kiraaazzy** [microsoft/LightGBM#2784]
## Environment info

Operating System : macOS Catalina Version 10.15.2 

CPU/GPU model:CPU

C++/Python/R version: Python

LightGBM version : 2.3.1

## Error message

I was trying to get the feature name using the below code , then i encountered such error: 

'LGBMRegressor' object has no attribute 'feature_name_'.

Then I checked the docs, there indeed existed attribute 'feature_name_'.

Here is the error log:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-d982fd40dcd0> in <module>
     32 print('Feature importances:', list(gbm.feature_importances_))
     33 
---> 34 print('Feature names',gbm.feature_name_)

AttributeError: 'LGBMRegressor' object has no attribute 'feature_name_'

```

This is my code
```
from lightgbm import LGBMRegressor
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import GridSearchCV
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.externals import joblib

# load data
iris = load_iris()
data = iris.data
target = iris.target

# split dataset
X_train, X_test, y_train, y_test = train_test_split(data, target, test_size=0.2)

# training
gbm = LGBMRegressor(objective='regression', num_leaves=31, learning_rate=0.05, n_estimators=20)
gbm.fit(X_train, y_train, eval_set=[(X_test, y_test)], eval_metric='l1', early_stopping_rounds=5)

# save the model
joblib.dump(gbm, 'loan_model.pkl')


# load the model
gbm = joblib.load('loan_model.pkl')

y_pred = gbm.predict(X_test, num_iteration=gbm.best_iteration_)

print('The rmse of prediction is:', mean_squared_error(y_test, y_pred) ** 0.5)

# importances and feature_name_
print('Feature importances:', list(gbm.feature_importances_))

print('Feature names',gbm.feature_name_)# this is where went wrong
```

**Comment by sbushmanov** [comment]
You need to supply data as pandas df, and even after doing that the `feature_name_` attribute is still missing.

The minimal example to reproduce:

```
from lightgbm import LGBMRegressor
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

# load data
iris = load_iris()
data = pd.DataFrame(iris.data, columns=iris.feature_names)
target = pd.Series(iris.target)

# split dataset
X_train, X_test, y_train, y_test = train_test_split(data, target, test_size=0.2)

# training
gbm = LGBMRegressor(objective='regression', num_leaves=31, learning_rate=0.05, n_estimators=20)
gbm.fit(X_train, y_train, eval_set=[(X_test, y_test)], eval_metric='accuracy', early_stopping_rounds=5)

gbm.feature_names_

AttributeError                            Traceback (most recent call last)
<ipython-input-10-6fb22a92e253> in <module>
     15 gbm.fit(X_train, y_train, eval_set=[(X_test, y_test)], eval_metric='accuracy', early_stopping_rounds=5)
     16 
---> 17 gbm.feature_names_

AttributeError: 'LGBMRegressor' object has no attribute 'feature_names_'
```

**Comment by StrikerRUS** [comment]
`feature_name_` attribute has been merged in `master` recently and is not included in any official release yet. You can download nightly build or install from sources: https://lightgbm.readthedocs.io/en/latest/Installation-Guide.html.

**Comment by kiraaazzy** [comment]
> You need to supply data as pandas df, and even after doing that the `feature_name_` attribute is still missing.
> 
> The minimal example to reproduce:
> 
> ```
> from lightgbm import LGBMRegressor
> from sklearn.datasets import load_iris
> from sklearn.model_selection import train_test_split
> 
> # load data
> iris = load_iris()
> data = pd.DataFrame(iris.data, columns=iris.feature_names)
> target = pd.Series(iris.target)
> 
> # split dataset
> X_train, X_test, y_train, y_test = train_test_split(data, target, test_size=0.2)
> 
> # training
> gbm = LGBMRegressor(objective='regression', num_leaves=31, learning_rate=0.05, n_estimators=20)
> gbm.fit(X_train, y_train, eval_set=[(X_test, y_test)], eval_metric='accuracy', early_stopping_rounds=5)
> 
> gbm.feature_names_
> 
> AttributeError                            Traceback (most recent call last)
> <ipython-input-10-6fb22a92e253> in <module>
>      15 gbm.fit(X_train, y_train, eval_set=[(X_test, y_test)], eval_metric='accuracy', early_stopping_rounds=5)
>      16 
> ---> 17 gbm.feature_names_
> 
> AttributeError: 'LGBMRegressor' object has no attribute 'feature_names_'
> ```
> 
> LGBM v2.3.1 here.

Thankn u a lot! 

It seems that the official version contain 'feature_name_' hasn't been released yet!
