### ISSUE TITLE
[feature request] accelerate the data loading from Python/R object

### ISSUE THREAD

**Issue by guolinke** [microsoft/LightGBM#2789]
refer to the code in `src/c_api.cpp` (`LGBM_BoosterPredictFor*` and `LGBM_DatasetCreateFrom*`).
Currently, the data are read by the function wrapper, which may produce some overheads.

**Comment by jameslamb** [comment]
@guolinke could you elaborate on this? I don't understand which part of `src/c_api.cpp` you are referring to.

**Comment by guolinke** [comment]
@jameslamb 
refer to `LGBM_BoosterPredictFor*` and `LGBM_DatasetCreateFrom*`

**Comment by jameslamb** [comment]
> @jameslamb
> refer to `LGBM_BoosterPredictFor*` and `LGBM_DatasetCreateFrom*`

got it, thanks!

**Comment by StrikerRUS** [comment]
Closed in favor of being in #2302. We decided to keep all feature requests in one place.

Welcome to contribute this feature! Please re-open this issue (or post a comment if you are not a topic starter) if you are actively working on implementing this feature.
