### ISSUE TITLE
refine Documents

### ISSUE THREAD

**Issue by wxchan** [Microsoft/LightGBM#279]
- [x] check or unify formats, typos, words, grammars, punctuations and etc.

**python-package**:

- [x] auto update with docstrings

**R-package**:

- [x] add R docs

**Comment by wxchan** [comment]
@guolinke can you add a `call-for-contribution` tag here?

**Comment by coforfe** [comment]
Hello,

I can help with the "R docs".
I will need some basic info of the type of documents you want to create/update.

Regards,
Carlos.

**Comment by wxchan** [comment]
I am not familiar with R (docs). @guolinke @Laurae2 can you provide some info here?

**Comment by guolinke** [comment]
@wxchan @coforfe 
I think the first thing we need is the doc for the all interfaces in R. 
Just like the python api doc: https://github.com/Microsoft/LightGBM/blob/master/docs/Python-API.md
R will generate its doc in https://github.com/Microsoft/LightGBM/tree/master/R-package/man from the comment in R codes.
So we need to refine these comments.

**Comment by Laurae2** [comment]
@wxchan We have R doc as manual in the R-package
