### ISSUE TITLE
where is Python code for ndcg calculation

### ISSUE THREAD

**Issue by LiangqunLu** [microsoft/LightGBM#2794]
Hi I noticed that my ndcg@3 is pretty high in my project.  So I want to have a look at the lightGBM ndcg source code. I did not find it. Did somebody know and could point out to me? Thanks!

**Comment by StrikerRUS** [comment]
@LiangqunLu Hi!

It is done via C++ code. Please refer to 
https://github.com/microsoft/LightGBM/blob/master/src/metric/rank_metric.hpp
https://github.com/microsoft/LightGBM/blob/master/src/metric/dcg_calculator.cpp
