### ISSUE TITLE
Wrong implementation of SingleRowPredictor::IsPredictorEqual in c_api

### ISSUE THREAD

**Issue by AlbertoEAF** [microsoft/LightGBM#2798]
Hello,

I was looking at the code and found this definition in the c_api.cpp:

```
  bool IsPredictorEqual(const Config& config, int iter, Boosting* boosting) {
    return early_stop_ != config.pred_early_stop ||
      early_stop_freq_ != config.pred_early_stop_freq ||
      early_stop_margin_ != config.pred_early_stop_margin ||
      iter_ != iter ||
      num_total_model_ != boosting->NumberOfTotalModel();
  }
```

Shouldn't it be `return early_stop_ == config.pred_early_ctop && ...` ?

This is then used in PredictSingleRow(...) to reset the predictor in case the predictor is not the same:

```
    if (single_row_predictor_[predict_type].get() == nullptr ||
        !single_row_predictor_[predict_type]->IsPredictorEqual(config, num_iteration, boosting_.get())) {
      single_row_predictor_[predict_type].reset(new SingleRowPredictor(predict_type, boosting_.get(),
                                                                       config, num_iteration));
    }
```

which will result in creating a new SingleRowPredictor every time, and worse, not creating a new one if conditions change.

This worsens the performance for repeated calls, and results in not creating a new predictor in case parameters change (bug).

If you want I can gladly do a pull request to fix it.

**Comment by guolinke** [comment]
fixed in #2799
