### ISSUE TITLE
Is GPU used in scikit-learn API?

### ISSUE THREAD

**Issue by sbushmanov** [microsoft/LightGBM#2808]
I'm wondering is GPU used in scikit-learn API when I specify model like:

```
model = lgbm.LGBMClassifier(device="gpu")
```
Documents give 2 conflicting hints:

> **kwargs –
Other parameters for the model. Check http://lightgbm.readthedocs.io/en/latest/Parameters.html for more parameters.

and

> **kwargs is not supported in sklearn, it may cause unexpected issues.

so I would like to confirm it here.

**Comment by StrikerRUS** [comment]
Yes, it should work. If it doesn't cause any failures, then it works.
