### ISSUE TITLE
ERROR: lightgbm 2.3.2 has requirement scikit-learn<=0.21.3, but you'll have scikit-learn 0.22.1 which is incompatible.

### ISSUE THREAD

**Issue by SlowMonk** [microsoft/LightGBM#2810]
ERROR: lightgbm 2.3.2 has requirement scikit-learn<=0.21.3, but you'll have scikit-learn 0.22.1 which is incompatible.

**Comment by StrikerRUS** [comment]
LightGBM is incompatible with new versions of scikit-learn. Please install `scikit-learn<=0.21.3` which is the last officially supported version. Also keep eye on https://github.com/scikit-learn/scikit-learn/issues/16241 which is upstream blocking issue.
