### ISSUE TITLE
Different results in predict when passing np.nan and None values

### ISSUE THREAD

**Issue by oksanadanilova** [microsoft/LightGBM#2821]
## Environment info

Operating System: MAC OS

CPU/GPU model: 

C++/Python/R version: 3.6.8

LightGBM version or commit hash: version=2.3.0

## Steps to reproduce

1. train a classifier with data containing NaN values
2. predict test data containing NaN values of numpy.nan and None types
3. enjoy different results

Why does it happen?

**Comment by StrikerRUS** [comment]
@oksanadanilova What data type are you using? Are there any categorical columns in your dataset?

Can you please provide [MCVE](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by guolinke** [comment]
@oksanadanilova could you try the latest master branch?
