### ISSUE TITLE
Jupyter kernel dies while predicting with pred_contrib=True

### ISSUE THREAD

**Issue by singh0777** [microsoft/LightGBM#2823]
## Environment info

Operating System:
Ubuntu on EC2 : m5.8xlarge

CPU/GPU model:
32 cores

C++/Python/R version:
Python - 3.7.3

LightGBM version or commit hash:
2.0.12

## Error message
There is no error message. I am trying to predict using a dataset with 1500 columns and 4 rows.
The jupyter Kernel fails after 4-5 seconds. I have 128GB RAM on my EC2 machine.

## Reproducible examples
**model:**
LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
        is_unbalance=True, learning_rate=0.07725198514477963, max_bin=600,
        max_depth=70, min_child_samples=20, min_child_weight=0.001,
        min_split_gain=0.0, n_estimators=2000, n_jobs=-1, num_leaves=250,
        objective=None, random_state=13, reg_alpha=0.0, reg_lambda=0.0,
        silent=True, subsample=1.0, subsample_for_bin=200000,
        subsample_freq=1)

**model.booster_.predict( data, pred_contrib = True)**

## Steps to reproduce

1. Get a trained model. And small test dataset with 1500 columns.
2. predict using **model.booster_.predict( data, pred_contrib = True)**
3. Kernel dies within 4-5 seconds. It works fine if pred_contrib = False.

**Comment by singh0777** [comment]
![image](https://user-images.githubusercontent.com/8538279/75297975-17b42d00-57e6-11ea-9410-5c95e949acac.png)

**Comment by StrikerRUS** [comment]
Hi @singh0777 !

> 2.0.12

This is VERY old version (26 Dec 2017). Please try the latest one (2.3.1).

If crash will be reproduced with the latest version, please, set `silent` parameter to `False` and also specify `verbose=2` parameter. After that copy the log from Jupyter Console. It will look something like this:

![image](https://user-images.githubusercontent.com/25141164/75375432-0c90f800-58df-11ea-9cb3-7e418f033d48.png)


>2. predict using model.booster_.predict( data, pred_contrib = True)

Why do you predict in a such way? Please try to predict directly `model.predict(data, pred_contrib=True)`

**Comment by singh0777** [comment]
Pulling the latest lgbm version worked.
I think the `model.predict(data, pred_contrib=True)` was not available in 2.0.12 version. thanks.
