### ISSUE TITLE
R session crashes when fitting model with sparse features

### ISSUE THREAD

**Issue by rgranvil** [microsoft/LightGBM#2831]
Using latest master branch and R v3.5.2 the following code crashes my R session:

**Code:**
```r
library(lightgbm)
data <- data.frame(
  y = sample(c(0,1), size = 70000, replace = TRUE)
  ,x = as.numeric(sample(c(1:10, rep(NA, 50)), replace = TRUE, size = 70000))
)

data_matrix <- as.matrix(data[, "x", drop = FALSE])
dtrain <- lgb.Dataset(data_matrix, label = data$y)
lgb.train(
  params = list(objective = "binary", min_data = 1, min_data_in_bin = 1)
  ,data = dtrain
  ,nrounds = 1
)
```

**Comment by jameslamb** [comment]
Thanks for the report  @rgranvil ! I'll test in a few hours and let you know. Could you tell me:

* your operating system
* how you installed the `lightgbm` R package

**Comment by guolinke** [comment]
@rgranvil did this fix (https://github.com/microsoft/LightGBM/pull/2811) work for you?

**Comment by jameslamb** [comment]
I just tried this with the latest `master`, on R 3.5.2 on Linux (Debian 9). I could not reproduce this error (see logs below). Thanks again for providing a minimal example for us to work with!

<details><summary>log</summary>
```
[LightGBM] [Warning] Starting from the 2.1.2 version, default value for the "boost_from_average" parameter in "binary" objective is true.
This may cause significantly different results comparing to the previous versions of LightGBM.
Try to set boost_from_average=false, if your old models produce bad results
[LightGBM] [Info] Number of positive: 34991, number of negative: 35009
[LightGBM] [Info] Total Bins 12
[LightGBM] [Info] Number of data: 70000, number of used features: 1
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.499871 -> initscore=-0.000514
[LightGBM] [Info] Start training from score -0.000514
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
```
</details>

steps to reproduce:

1. create the container

```
cd docker
docker build \
    -t lightgbm-r-35 \
    -f dockerfile-r \
    --build-arg R_VERSION=3.5.2     .
```

2. shell in and create an R REPL

```
docker run -it lightgbm-r-35 R
```

3. Run your sample code

```r
library(lightgbm)
data <- data.frame(
  y = sample(c(0,1), size = 70000, replace = TRUE)
  ,x = as.numeric(sample(c(1:10, rep(NA, 50)), replace = TRUE, size = 70000))
)

data_matrix <- as.matrix(data[, "x", drop = FALSE])
dtrain <- lgb.Dataset(data_matrix, label = data$y)
lgb.train(
  params = list(objective = "binary", min_data = 1, min_data_in_bin = 1)
  ,data = dtrain
  ,nrounds = 1
)
```

If you are still seeing this error on `master`, then whenever you let us know your operating system and how you're installing the R package we can help more.

**Comment by jameslamb** [comment]
Thanks very much for the additional information! That sample-size observation is really interesting. II didn't have that same issue on Debian with R 3.5.2 and the same sample size, so I'm starting to worry that the problem is lower-level.

Do you know or can you tell from the logs which compiler and compiler version was used?

I'm still not sure why your code is working for me and not for you if we have the same R and `lightgbm`  versions.

We'll figure it out!

**Comment by guolinke** [comment]
Thanks @rgranvil , I realize there may be a bug, you can try the fix: #2841

**Comment by rgranvil** [comment]
Confirmed #2841 fixed the issue for me.  Thank you!

**Comment by jameslamb** [comment]
@rgranvil I added your example as a test so we don't reintroduce this (#2847)
