### ISSUE TITLE
how to customize the metric function in lightgbm such as ks?

### ISSUE THREAD

**Issue by jianqin123** [Microsoft/LightGBM#284]

**Comment by Laurae2** [comment]
For custom evaluation metric:

* Python: https://github.com/Microsoft/LightGBM/blob/master/examples/python-guide/advanced_example.py
* R: https://github.com/Microsoft/LightGBM/blob/master/R-package/demo/early_stopping.R

**Comment by jianqin123** [comment]
thanks a lot

**Comment by yangtian62** [comment]
Is there a way to self define eval metrics with CLI version for parallel training? @Laurae2 Thanks!
