### ISSUE TITLE
Dataset detects one column less than there's in the csv file

### ISSUE THREAD

**Issue by pakohan** [microsoft/LightGBM#2854]
I'm trying to construct a dataset from a csv file since pandas.Dataframe ones consume too much memory. But loading it detects one column less in the data than there are so it fives me an error.

## Environment info

Operating System: macOS

CPU/GPU model: Intel CPU

C++/Python/R version: Python 3

LightGBM version or commit hash: v2.3.1

## Error message

```
[LightGBM] [Warning] There are no meaningful features, as all feature values are constant.Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/usr/local/lib/python3.7/site-packages/lightgbm/basic.py", line 1085, in construct
    categorical_feature=self.categorical_feature, params=self.params)
  File "/usr/local/lib/python3.7/site-packages/lightgbm/basic.py", line 915, in _lazy_init
    return self.set_feature_name(feature_name)
  File "/usr/local/lib/python3.7/site-packages/lightgbm/basic.py", line 1363, in set_feature_name
    .format(len(feature_name), self.num_feature()))
ValueError: Length of feature_name(2) and num_feature(1) don't match
```

## Reproducible examples

```
import lightgbm as lgbm
train_dataset = lgbm.Dataset(
    data="test.txt",
    feature_name=["feature_1","feature_2"],
).construct()
```

test.txt:
```
0,0
1,1
```
## Steps to reproduce

1. create a csv file
2. construct a Dataset with the feature names passed as array.

I reproduced it with a minimal example of 2x2, but the results with the production data is the same.

**Comment by guolinke** [comment]
For the file input, the first column is the label, and the rest is feature. So there is one feature.
