### ISSUE TITLE
Example for LightGBM ranker model which accepts vector matrix as input

### ISSUE THREAD

**Issue by FaisalHBTU** [microsoft/LightGBM#2860]
Hi Team,
I have trained LightGBM model and got a binary file for it. 
Do you have any example which explains the process of loading the binary, providing vectors matrix as input and then get the output. Everywhere i see the same implementation: loading and running from files

**Comment by StrikerRUS** [comment]
@FaisalHBTU Hey!

Can you please provide steps how you
> trained LightGBM model and got a binary file for it.

Because LightGBM model cannot be saved into binary format.

**Comment by StrikerRUS** [comment]
ping @FaisalHBTU

**Comment by FaisalHBTU** [comment]
it is fine now
