### ISSUE TITLE
Continuous features can have incorrect bounds in the text file

### ISSUE THREAD

**Issue by vruusmann** [Microsoft/LightGBM#287]
I'm using the HEAD version of the master branch to train a poisson regression model.

On line 2216 of my input CSV file I have a data record where `hhnInc=0.0149999996647239`:
https://github.com/jpmml/jpmml-lightgbm/blob/master/src/test/resources/csv/Visit.csv#L2216

However, in the resulting LightGBM text file the bounds of `hhnInc` feature are recorded as `[0.015, 25]`:
https://github.com/jpmml/jpmml-lightgbm/blob/master/src/test/resources/lgbm/RegressionVisit.txt#L491

As a result, this data record "becomes" invalid, because `0.0149999996647239 < 0.015`.

Here's a reproducible example (lines 90 -- 98):
https://github.com/jpmml/jpmml-lightgbm/blob/master/src/test/resources/main.py#L90

The correct behaviour would be to record the bounds of `hhnInc` feature as `[0.0149999996647239, 25]`. Unfortunately, for some reason, LightGBM rounds the lower bound up.

**Comment by vruusmann** [comment]
The output when introducing `print(visit_X.as_matrix()[2215])` into the above example:
```
[  2.60000000e+01   0.00000000e+00   1.00000000e+00   0.00000000e+00
   1.00000000e+00   1.49999997e-02   1.20000000e+01   0.00000000e+00]
```

So, the rounding appears to take place inside the LightGBM library (as opposed to Pandas or Numpy libraries).

**Comment by wxchan** [comment]
It happens in Common::Atof, it parses 0.0149999996647239 as 0.015. Not sure how to fix it.

**Comment by wxchan** [comment]
You can add `str_buf.precision(20);` for example before https://github.com/Microsoft/LightGBM/blob/master/include/LightGBM/bin.h#L169 to see more decimal places. I am not sure what's the default precision here.

**Comment by vruusmann** [comment]
The main question is:

1. Does the "round up" happen when importing data? If so, then LightGBM decision tree algorithm sees `hhnInc=0.015`.

or

2. Does the "round up" happen when serializing the trained model into text file? If so, then LightGBM decision tree algorithm sees `hhnInc=0.0149999996647239`.

I would be slightly more concerned about the first scenario, because it means that all `hhnInc` threshold values are affected (ie. also rounded up).

**Comment by wxchan** [comment]
it happens in serializing.

**Comment by guolinke** [comment]
the feature bounds is not outputted in model file since LightGBM v2. 
I wonder is this feature still needed?

**Comment by vruusmann** [comment]
Apparently, you've decided to drop the "feature information" section of the text file in LightGBM v2. What's the supposed replacement method/mechanism for obtaining descriptive information about features then?

There needs to be some sort of "model schema" information available:

- Feature operational type: continuous or categorical. Previously available by checking the "decision_type" attribute of individual tree sections.
- Valid range (min -- max) for continuous features. Previously available in the "feature information" section.
- Valid levels for categorical features. Previously available in the "feature information" section.

Without "model schema" information, the LightGBM model is just a black box for the end user (ie. can't reliably answer a question "can I use this LightGBM model to score this dataset?"), and it becomes pointless to make any effort towards model export using the PMML data format.

**Comment by guolinke** [comment]
@vruusmann I see. will add it back.

**Comment by guolinke** [comment]
@vruusmann 
Fixed,
However, the format of feature bounds is changes.
It is outputted following by the ```feature_names```. 
```
feature_infos=[1:2],[1:100],[2:100]
```

**Comment by vruusmann** [comment]
@guolinke Thanks for making the `feature_info` attribute available. It's fully adequate for my PMML conversion needs.
