### ISSUE TITLE
min_sum_hessian_in_leaf vs min_data_in_leaf

### ISSUE THREAD

**Issue by zcyang** [microsoft/LightGBM#2870]
Hi,

The two parameters are very confusing to me.
For regression problem, the two values should be equivalent, because the hessian of a single sample is 1.

However, I find they behave rather differently in experiments.
More explanation would be helpful! Thanks!

**Comment by guolinke** [comment]
Dis you use sample weight?

**Comment by zcyang** [comment]
ah, yes, so the sum hessian is the sample weighted hessian? That may explain the difference.
