### ISSUE TITLE
Unable to execute LightGBM on MacOS: Caused by: java.lang.UnsatisfiedLinkError: Library not loaded: /usr/local/opt/libomp/lib/libomp.dylib

### ISSUE THREAD

**Issue by BhushG** [microsoft/LightGBM#2872]
## Environment info

Operating System: Mac OS

CPU/GPU model: MacBook Pro, RAM: 16GB

C++/Python/R version: I'm running the project on scala 2.11.8

LightGBM version or commit hash:

## Steps to reproduce
1. brew install lightgbm, brew install libomp
    
2. Write code for LightGBMClassifier on Mac Os using the following dependency.
```
<!-- https://mvnrepository.com/artifact/com.microsoft.ml.spark/mmlspark -->
        <dependency>
            <groupId>com.microsoft.ml.spark</groupId>
            <artifactId>mmlspark_2.11</artifactId>
            <version>0.18.1</version>
        </dependency>
```
3. Run the code
4. It throws following exception:
```
Caused by: java.lang.UnsatisfiedLinkError: /private/var/folders/bk/x34npyr17414f2y69fcjpspnfbmckp/T/mml-natives6334124481739065503/lib_lightgbm.dylib: dlopen(/private/var/folders/bk/x34npyr17414f2y69fcjpspnfbmckp/T/mml-natives6334124481739065503/lib_lightgbm.dylib, 1): Library not loaded: /usr/local/opt/libomp/lib/libomp.dylib
  Referenced from: /private/var/folders/bk/x34npyr17414f2y69fcjpspnfbmckp/T/mml-natives6334124481739065503/lib_lightgbm.dylib
  Reason: image not found
```

**The same code and same dependency works fine on Ubuntu.**

**Comment by StrikerRUS** [comment]
Sorry, but we do not maintain MMLSpark library here.

Please report this problem there.
https://github.com/Azure/mmlspark

I think that MMLSpark is not configured to detect LightGBM installed from brew.
