### ISSUE TITLE
Extra Tree Memory Corruprion

### ISSUE THREAD

**Issue by davutpolat** [microsoft/LightGBM#2874]
i cloned and installed  lgb from the source last week and i am using  python wrapper.  
i tried  extra trees  in our project, it crashed for a couple of runs. 

the error messages :  
free(): invalid next size (normal)

another error  :  double free or corruption (!prev)

i think  they are  C level errors.

**Comment by guolinke** [comment]
@davutpolat could you try the latest master branch? we have several fixes recently.

**Comment by davutpolat** [comment]
@guolinke  it seems  solved, thanks

**Comment by jameslamb** [comment]
@davutpolat great, glad to hear it!
