### ISSUE TITLE
How to specify LightGBM categorical features when loading from libsvm format?

### ISSUE THREAD

**Issue by shenkev** [microsoft/LightGBM#2880]
I'm using the Python library. My categorical features are encoded as integers. As far as I know, this is the correct representation for LightGBM as long as you pass in the "categorical_feature" argument. Here is an example:

    lgb_train = lgb.Dataset(X_train, y_train, categorical_feature=['ethnicity', 'city', 'country'])
        
However, how do you specify the categorical_feature when the dataset has been converted into the libsvm format? Concretely, suppose I saved X_train and y_train as "data.libsvm". "ethnicity", "city" and "country" would have been converted into column indices, say "1", "2", "3". Is below the correct way to specify categorical_features?

    lgb_train = lgb.Dataset("./data.libsvm", categorical_feature=['1', '2', '3'])

Furthermore, libsvm represents all data values as floats. Does LightGBM still correctly interpret the categorical columns as categorical and not numeric?

## Environment info (omitted because not relevant)

Operating System:

CPU/GPU model:

C++/Python/R version:

LightGBM version or commit hash:

## Steps to reproduce

1.
2.
3.

**Comment by guolinke** [comment]
you can use the feature index, which starts from 0, not 1.
