### ISSUE TITLE
How can I use LightGBM Ranker if I have many documents for a query and only label below 31 are allowed

### ISSUE THREAD

**Issue by tomleung1996** [microsoft/LightGBM#2892]
I have some samples (~5000) with their features, and I want to rank them in terms of a score. I have already built a regression model that directly predicts the score, but I still want to try the learning to rank methods, so I turned to the LightGBM Ranker.

Since LightGBM Ranker only accepts label value below 31, I have to group the scores into several categories, 1 to 4 for example. After training, the Ranker is able to rank samples and achieves a nice NDCG@20 score, but it is unable to rank items within the same group.

My problem is somewhat like one query v.s. ~5000 documents, seems a bit different from the ordinary IR problems. It would be perfect if the Ranker accepts the full order or actual scores of my samples as labels, but I don't know how to achieve this. Some posts suggest using the label_gain parameter, but I can't find any documentation on how to set it properly.

I am new to the ranking models, please help. Thanks!

**Comment by guolinke** [comment]
firstly, you can set `label_gain` to adapt the range of your label. If the range of label is `[0, k)`, you should set k values to it.

secondly, you can rank the samples in the same group, you can just sort them by the prediction scores. maybe I mis-understand how you do it, I assume that you put all docs into one query, with label 1~4.

**Comment by tomleung1996** [comment]
> firstly, you can set `label_gain` to adapt the range of your label. If the range of label is `[0, k)`, you should set k values to it.
> 
> secondly, you can rank the samples in the same group, you can just sort them by the prediction scores. maybe I mis-understand how you do it, I assume that you put all docs into one query, with label 1~4.

Yes, I put all docs into one query with label 1 to 4, but docs that have the same label still vary in their actual scores, I am wondering how to deal with this kind of situation.

As you suggested, should I set the `label_gain` to [0 ... 5000] and give every document a distinct label? 

Thanks!

**Comment by tomleung1996** [comment]
Maybe I didn't explain my problem well. I grouped my docs that have actual scores into 4 groups to train the LightGBM Ranker, but docs in the same group actually have different scores and should be properly ordered according to that score. I couldn't group them into 5000 groups because the Ranker only accepts labels below 31, so I don't know what to do to deal with this.

**Comment by guolinke** [comment]
in ranking problems, we usually focus on the top docs. So a comment solution to label the most "bad" docs to one label, like `0`. 
If you really need to rank all 5000 docs, maybe it is better to use regression, or the pair-wise ranking.

**Comment by tomleung1996** [comment]
> in ranking problems, we usually focus on the top docs. So a comment solution to label the most "bad" docs to one label, like `0`.
> If you really need to rank all 5000 docs, maybe it is better to use regression, or the pair-wise ranking.

Thanks for your advice!

I have already built a regression model and want to make a comparison between it and the LTR model, since it is also a kind of ranking problem. Does LightGBM Ranker support pair-wise ranking? I suppose it is list-wise by default, right?

**Comment by guolinke** [comment]
we don't support pair-wise ranking, but you can construct the pair by yourself.

**Comment by tomleung1996** [comment]
> we don't support pair-wise ranking, but you can construct the pair by yourself.

So I can make C(5000,2) groups, which are consist of 2 documents, right?
