### ISSUE TITLE
how to compile 2.2.350 version from source code

### ISSUE THREAD

**Issue by canli12138** [microsoft/LightGBM#2900]
i want to use mmlspark on ARM platform, so i need to compile lightgbmlib-2.2.350.jar on the ARM,but i don't know how to get the source code of 2.2.350 version

**Comment by StrikerRUS** [comment]
You can try to follow our installation guide: https://lightgbm.readthedocs.io/en/latest/Installation-Guide.html#id23.

But we do not officially support ARM platform yet. Please refer to #1129 and your feedback about ARM is very welcome!

I guess `mmlspark` release numeration differs from ours. The closest thing we have is `2.2.3` so you can `git clone` the following commit https://github.com/microsoft/LightGBM/commit/0d0e793ab61b626ff43c3e9d56d95793a5ed4017.
