### ISSUE TITLE
Why are goss and gbdt so close in training time in practice?

### ISSUE THREAD

**Issue by shenkev** [microsoft/LightGBM#2902]
The default top_rate and other_rate for GOSS is 0.2 and 0.1 respectively. Doesn't this mean theoretically there should be a 3.3333x speedup versus GBDT? Benchmarking on the [spanish train Kaggle dataset](https://www.kaggle.com/thegurusteam/spanish-high-speed-rail-system-ticket-pricing), I found that GOSS is only about 1.3 times faster than GBDT using the same hyperparameters.

GBDT average runtime: 1.43
GOSS average runtime: 1.08

I also benchmarked on a [slightly larger dataset](https://www.kaggle.com/austinreese/craigslist-carstrucks-data) and found 1.8x speedup.

GBDT: 5.69
GOSS: 3.22

## Environment info

Operating System:

CPU/GPU model:

C++/Python/R version:

LightGBM version or commit hash:

## Steps to reproduce

1.
2.
3.

**Comment by guolinke** [comment]
There are some operations are always on full dataset, no only in sampled subset, such as boosting, prediction, etc. these overheads limit the speed-up of using sample set. 
BTW, you can try the latest master branch, with force_row_wise=true. It should provide faster speed-up for sample subset.
