### ISSUE TITLE
Should you scale min_data_in_leaf with the dataset size?

### ISSUE THREAD

**Issue by shenkev** [microsoft/LightGBM#2905]
I'm hyperparameter tuning on a dataset that has 100k samples. Once I found the best parameters (including min_data_in_leaf), I train on a dataset with 1M samples (10x larger).

Theoretically should I scale min_data_in_leaf to 10x what it was during hyperparameter tuning or keep it the same?

**Comment by guolinke** [comment]
In my own experience, the performance with large `min_data_in_leaf` is not good, for it may cause under-fitting.
