### ISSUE TITLE
regularization for categorical variables

### ISSUE THREAD

**Issue by devilwing0723** [microsoft/LightGBM#2919]
Hi, I am using lightgbm to train model with some categorical variables. I am wondering where can I find more detailed documentation/introduction on the hyper parameters that can regularize the categorical variables, such as max_cat_threshold, max_cat_to_onehot, cat_l2, cat_smooth? Current documentation did not really specify how these parameters regularize, and what range of values is appropriate for hyper-tuning.

**Comment by guolinke** [comment]
refer to the code here: https://github.com/microsoft/LightGBM/blob/9654f16528d2d1e3462a298106cb1fc6ed43cbac/src/treelearner/feature_histogram.hpp#L259-L483

cat_l2 is the additional l2 reg for categorical features: https://github.com/microsoft/LightGBM/blob/9654f16528d2d1e3462a298106cb1fc6ed43cbac/src/treelearner/feature_histogram.hpp#L349
cat_smooth is the smooth term when calculating the target encoding: https://github.com/microsoft/LightGBM/blob/9654f16528d2d1e3462a298106cb1fc6ed43cbac/src/treelearner/feature_histogram.hpp#L352

`max_cat_to_onehot` is too force one-vs-rest splits, when total number of categories is smaller than `max_cat_to_onehot`. 

`max_cat_threshold` is the max number of thresholds will be chosen in split condition: https://github.com/microsoft/LightGBM/blob/master/src/treelearner/feature_histogram.hpp#L364-L365
