### ISSUE TITLE
JSONDecodeError at dump_model() from Python

### ISSUE THREAD

**Issue by Dronablo** [microsoft/LightGBM#2933]
## Environment info

Operating System: Windows 10

CPU/GPU model: Core i7-9800X / RTX 2060

C++/Python/R version: MSVC 19.25.28610.4 / Python 3.8.1

LightGBM version or commit hash: 2.3.2 / 9654f16528d2d1e3462a298106cb1fc6ed43cbac

## Error message
```
gbm.dump_model()
---------------------------------------------------------------------------
JSONDecodeError                           Traceback (most recent call last)
<ipython-input-52-a7d54b90eaa5> in <module>
----> 1 gbm.dump_model()

~\Anaconda3\envs\fc\lib\site-packages\lightgbm\basic.py in dump_model(self, num_iteration, start_iteration)
   2584                 ptr_string_buffer))
   2585         print(string_buffer.value.decode())
-> 2586         ret = json.loads(string_buffer.value.decode())
   2587         ret['pandas_categorical'] = json.loads(json.dumps(self.pandas_categorical,
   2588                                                           default=json_default_with_numpy))

~\Anaconda3\envs\fc\lib\site-packages\simplejson\__init__.py in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, use_decimal, **kw)
    523             parse_constant is None and object_pairs_hook is None
    524             and not use_decimal and not kw):
--> 525         return _default_decoder.decode(s)
    526     if cls is None:
    527         cls = JSONDecoder

~\Anaconda3\envs\fc\lib\site-packages\simplejson\decoder.py in decode(self, s, _w, _PY3)
    368         if _PY3 and isinstance(s, bytes):
    369             s = str(s, self.encoding)
--> 370         obj, end = self.raw_decode(s)
    371         end = _w(s, end).end()
    372         if end != len(s):

~\Anaconda3\envs\fc\lib\site-packages\simplejson\decoder.py in raw_decode(self, s, idx, _w, _PY3)
    398             elif ord0 == 0xef and s[idx:idx + 3] == '\xef\xbb\xbf':
    399                 idx += 3
--> 400         return self.scan_once(s, idx=_w(s, idx).end())

JSONDecodeError: Expecting value: line 11 column 87528 (char 115283)
```

## Reproducible examples

Preparing reproducible example is somewhat hard to me right now, sorry.

## Steps to reproduce

Investigation shows that I have such a fragment in feature_infos value:
```
"Inst_Trans_log":{"min_value":-inf,"max_value":6.1908478736877441,"values":[]}
```
So, I believe problem is in "-inf" value.

**Comment by StrikerRUS** [comment]
@Dronablo Thank you for reporting this!

@guolinke 
Should we use `AvoidInf` here as these values are used in JSON representation now (#2660)?
https://github.com/microsoft/LightGBM/blob/bd10918e666574af6b0210c93ba2198c075822e5/include/LightGBM/bin.h#L193-L198

Or is it better to truncate only for JSON here? But then text and JSON representations will be inconsistent, which is not good I think.
https://github.com/microsoft/LightGBM/blob/3a335e9d4f63da10094d690a92cbefd0f4e6faf6/src/boosting/gbdt_model_text.cpp#L51-L52

**Comment by guolinke** [comment]
Yeah, avoidinf is needed.

**Comment by StrikerRUS** [comment]
@guolinke There is no doubt that it is needed! But where?..

**Comment by guolinke** [comment]
As it is json problem, we can only add it before json. 
refer to https://stackoverflow.com/questions/13581843/php-how-to-encode-infinity-or-nan-numbers-to-json
