### ISSUE TITLE
[performance] Central MissingType handling in model/tree (suggestion - looking for input)

### ISSUE THREAD

**Issue by AlbertoEAF** [microsoft/LightGBM#2934]
Hello all :),

I was trying to understand the missing values handling code which deals with several possible MissingType handling mechanisms (None, Zero, NaN) and believe I've found some possibilities of optimization for a small speedup.

**Context**
- LightGBM's internals currently support choosing one different mechanism per node (as it's encoded in the node's decision_type bits related to missing_type).
- However, in the parameters, only one missing-value handling mechanism can be chosen.

**Current design criteria?**
Can I ask if the backend design is there for a particular purpose in mind, to allow such granular level of flexibility? For some future feature? 

I see that this could be used to allow a new boosting implementation to choose conditionally the missing-type-handling per node (don't know how/why that would be useful though), per feature, or per tree. Are we planning to do that though?

**Proposal**
If it's not needed, then all the bitwise operations that occur per node during train & validation to select the missing type handling mechanism can be removed and done once for the model, which simplifies the code, and allows further optimization.

Do you like the idea and should I submit a PR? Or there's a specific goal that I'm unaware for the current implementation?

P.S.: _(+ping @guolinke , as you're the original author ;))_

**Comment by AlbertoEAF** [comment]
Closing as irrelevant (after small tests).

**Comment by guolinke** [comment]
@AlbertoEAF 
for different features, the missing type could be different. for example, one feature may contains `nan`, while others don't.  So, at least per-feature operations is needed.

**Comment by AlbertoEAF** [comment]
Thanks @guolinke , agreed!

In that case I'll close the issue for I believe there wouldn't exist many speedups from changing to a different implementation and thus for the time being any code changes are not worth the investment.
