### ISSUE TITLE
Parallel socket version problem : Connection timed out

### ISSUE THREAD

**Issue by bighaidao** [Microsoft/LightGBM#294]
hi, when I use LightGBM  Parallel socket version,I have a  problem with it .And then only run on a machine.

> 20039hfi_wait_for_device: The /dev/hfi1_0 device failed to appear after 15.0 seconds: Connection timed out

but it is ok when I  use the Parallel MPI version .
Could anyone help me ?Thanks

**Comment by guolinke** [comment]
Did you check the firewall rule?

**Comment by bighaidao** [comment]
@guolinke 
 I fix this problem with  updating libfabric  to 1.4 version.
But  Ｉ still have problem whit socket version. As the step it  still  run just in one machine. 
the log like this 

> [LightGBM] [Info] Finished loading parameters
[LightGBM] [Info] Local rank: 0, total number of machines: 1
[LightGBM] [Info] Finished initializing network
[LightGBM] [Info] Finished loading 100 models
[LightGBM] [Warning] File libsvm.bin existed, cannot save binary to it
[LightGBM] [Warning] File libsvm.test.bin existed, cannot save binary to it
[LightGBM] [Info] Finished loading data in 0.059684 seconds
[LightGBM] [Info] Number of data: 31540, number of features: 999


## here is the  conf file.

mlist.txt 

> 10.3.4.100 12345
> 10.3.4.101 12345

train.conf
> 

```
# number of machines in parallel training, alias: num_machine
num_machines = 2

# local listening port in parallel training, alias: local_port
local_listen_port = 12345

# machines list file for parallel training, alias: mlist
machine_list_file = mlist.txt
```

**Comment by guolinke** [comment]
@bighaidao did you set the ```tree_learner``` ?

**Comment by bighaidao** [comment]
@guolinke  yes . tree_learner = feature  just as the parallel_learning example train.conf .

I just modify the data path  and the last 
```

num_machines = 2

# local listening port in parallel training, alias: local_port
local_listen_port = 12345

# machines list file for parallel training, alias: mlist
machine_list_file = mlist.txt
```

**Comment by guolinke** [comment]
@bighaidao 
From your log.
I think the ```num_machines``` is parsed to ```1``` in LightGBM. 
I think it should not happen since you set it to ```2```.
Can you paste your scrpits?

**Comment by bighaidao** [comment]
@guolinke 

hi,this is the conf 
```
task = train
boosting_type = gbdt

objective = regression
metric = l1

metric_freq = 10

is_training_metric = true

max_bin = 255


data =
valid_data = 
num_trees = 2500
learning_rate = 0.05

num_leaves = 63

tree_learner = feature

num_threads = 18

feature_fraction = 0.8

bagging_freq = 5

bagging_fraction = 0.8

min_data_in_leaf = 50

min_sum_hessian_in_leaf = 5.0

is_enable_sparse = true

use_two_round_loading = false

is_save_binary_file = true

output_model = LightGBM_model.txt

num_machines = 2

local_listen_port = 12345

machine_list_file = mlist.txt
```

and  this is my comand 
`../../lightgbm config=zlj_train.conf`

**Comment by guolinke** [comment]
@bighaidao 
I found "[LightGBM] [Info] Finished loading 100 models" in your log, but I cannot find "input_model" in your config. 
I wonder is this config the real one you used?

**Comment by jpison** [comment]
Are you using Red Hat or Fedora?

It could be an openmpi problem..

Look at this:   https://bugzilla.redhat.com/show_bug.cgi?id=1408316
