### ISSUE TITLE
[python] Migrate to parametrize_with_checks for scikit-learn integration tests

### ISSUE THREAD

**Issue by rth** [microsoft/LightGBM#2947]
Minor maintenance point but it could be worth migrating to `parametrize_with_checks` instead of using `check_estimator` directly in scikit-learn integration tests (or rather the private `_yield_all_checks` function from scikit-learn):

https://github.com/microsoft/LightGBM/blob/c870c57a14b61329bf493b3b1a9a2893a62405cf/tests/python_package_test/test_sklearn.py#L285-L292

It particular, this would make each pair of estimator-check an independent pytest check which will make them easier to skip or debug issues like https://github.com/microsoft/LightGBM/issues/2628

Reference : https://scikit-learn.org/stable/developers/develop.html#rolling-your-own-estimator

**Comment by StrikerRUS** [comment]
Thanks for letting us know about `parametrize_with_checks`! I believe that with estimator tags mechanism it'll simplify some code.

I'm adding this to our requests hub.

**Comment by StrikerRUS** [comment]
Closed in favor of being in #2302. We decided to keep all feature requests in one place.

Welcome to contribute this feature! Please re-open this issue (or post a comment if you are not a topic starter) if you are actively working on implementing this feature.
