### ISSUE TITLE
[python] how to set number of thread for lightgbm.train()?

### ISSUE THREAD

**Issue by TGalaxy** [microsoft/LightGBM#2948]
There seems no instruction on how to set number of threads in https://lightgbm.readthedocs.io/en/latest/pythonapi/lightgbm.train.html#lightgbm.train

I tried to set in lightgbm.train(.....,num_threads=8) but it gave me an error:

model = lgb.train(params, d_train, num_boost_round=config['num_iterations'], valid_sets=d_validation, early_stopping_rounds=50, verbose_eval=100,num_threads=config['num_thread'])
TypeError: train() got an unexpected keyword argument 'num_threads'

**Comment by StrikerRUS** [comment]
If parameter is not presented among function arguments, then you can set it via `params` or `kwargs`.
In your case:
```
params = {"num_threads":8}
model = lgb.train(params, d_train, num_boost_round=config['num_iterations'], ...)
```

**Comment by TGalaxy** [comment]
Thanks!
