### ISSUE TITLE
Is There any way to translate the dt.tree to 'if-else' like statement?

### ISSUE THREAD

**Issue by kevinzhangguangjin** [Microsoft/LightGBM#295]
Is There any way to translate the dt.tree to 'if-else' like statement?

with tree number and detail rules.

**Comment by zhangyafeikimi** [comment]
Yes, not a very hard work.

**Comment by kevinzhangguangjin** [comment]
@zhangyafeikimi  Would you mind give me some tips to do it?

**Comment by zhangyafeikimi** [comment]
You need to write a compiler to compile trees to source code. Is it hard?

A not-good-enough example:
https://github.com/zhangyafeikimi/ml-gbdt/blob/master/bin/json2cxx.py
