### ISSUE TITLE
When is the new release planned for?

### ISSUE THREAD

**Issue by AlbertoEAF** [microsoft/LightGBM#2952]
Hello, sorry to ask here but didn't find a result for this question.

Is there an ETA for the new LightGBM release? Or a place to get that information?

Basically I'm using maven in Java to get the latest LightGBM release of Nov 2019 (2.3.150).
However there are many critical bugfixes merged in the master branch that I depend on.

Is there a way to fetch a more recent build? Or when is there going to be a new release?

Thank you for your time.

**Comment by StrikerRUS** [comment]
Hey @AlbertoEAF !

Please refer to https://github.com/microsoft/LightGBM/issues/2820#issuecomment-596857585.

We have even more breaking changes in the `master` and should wait for the feedback from early adopters.

**Comment by AlbertoEAF** [comment]
Thank you @StrikerRUS :)
