### ISSUE TITLE
No trees_to_dataframe in the python package

### ISSUE THREAD

**Issue by Janhonho** [microsoft/LightGBM#2959]
## Environment info

Operating System: Win10

CPU/GPU model: CPU

C++/Python/R version: Python

LightGBM version or commit hash:

## Error message

I use pip install lightgbm to install the newest version of lightgbm, but I found I've not got the function trees_to_dataframe, and I open the basic.py in the package, I find there is no function in 
lgb.basic.Booster, but in the documentation, it exists.

**Comment by Janhonho** [comment]
I try to copy the function code from doc to the basic.py, it seems work well

**Comment by StrikerRUS** [comment]
The latest pip release doesn't contain `trees_to_dataframe` functionality.
You can install from sources for now or wait for the next pip release.
