### ISSUE TITLE
AttributeError: module 'lightgbm' has no attribute 'Dataset'

### ISSUE THREAD

**Issue by PointCloudNiphon** [microsoft/LightGBM#2964]
`no previously-included directories found matching 'build'
warning: no files found matching '*.txt'
warning: no files found matching '*.so' under directory 'lightgbm'
warning: no files found matching '*.so' under directory 'compile'
warning: no files found matching '*' under directory 'compile\compute'
warning: no files found matching '*.dll' under directory 'compile\windows\x64\DLL'
warning: no previously-included files matching '*.py[co]' found anywhere in distribution`

## Environment info

Operating System:win10  Visual Studio 16 2019.
CPU/GPU model:GPU
C++/Python/R version:Python

LightGBM version or commit hash:2.3.2
## Error message
`AttributeError: module 'lightgbm' has no attribute 'Dataset'`

## Steps to reproduce

1.cd LightGBM-master\LightGBM-master\python-package>
2.python setup.py install --user
3.

**Comment by jameslamb** [comment]
Can you please provide some more information?

1. What version of Python are you using?
2. Was the text snippet at the beginning of your issue the complete log? If not please provide it.
3. Did you experience the error you are reporting during installation? If not, please share the code you attempted to run.

I just installed the Python package on Windows 10, with Visual Studio 16 2019, for the current state of the `master` branch by running the following.

```
cd python-package
python setup.py install --user
```

and did not have any issues loading the library after

```python
import lightgbm as lgb
help(lgb.Dataset)
```

**Comment by PointCloudNiphon** [comment]
I rebuild, and the problem changed to GPU...

1. I have a python 3.7.6 with anaconda..
2. the complete log is here.
`running install
INFO:LightGBM:Starting to compile the library.
INFO:LightGBM:Starting to compile with MSBuild from existing solution file.
WARNING:LightGBM:Compilation with MSBuild from existing solution file failed.
INFO:LightGBM:Starting to compile with Visual Studio 16 2019.
running build
running build_py
creating build
creating build\lib
creating build\lib\lightgbm
copying lightgbm\basic.py -> build\lib\lightgbm
copying lightgbm\callback.py -> build\lib\lightgbm
copying lightgbm\compat.py -> build\lib\lightgbm
copying lightgbm\engine.py -> build\lib\lightgbm
copying lightgbm\libpath.py -> build\lib\lightgbm
copying lightgbm\plotting.py -> build\lib\lightgbm
copying lightgbm\sklearn.py -> build\lib\lightgbm
copying lightgbm\__init__.py -> build\lib\lightgbm
running egg_info
creating lightgbm.egg-info
writing lightgbm.egg-info\PKG-INFO
writing dependency_links to lightgbm.egg-info\dependency_links.txt
writing requirements to lightgbm.egg-info\requires.txt
writing top-level names to lightgbm.egg-info\top_level.txt
writing manifest file 'lightgbm.egg-info\SOURCES.txt'
reading manifest file 'lightgbm.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
no previously-included directories found matching 'build'
warning: no files found matching '*.txt'
warning: no files found matching '*.so' under directory 'lightgbm'
warning: no files found matching '*.so' under directory 'compile'
warning: no files found matching '*' under directory 'compile\compute'
warning: no files found matching '*.dll' under directory 'compile\windows\x64\DLL'
warning: no previously-included files matching '*.py[co]' found anywhere in distribution
writing manifest file 'lightgbm.egg-info\SOURCES.txt'
copying lightgbm\VERSION.txt -> build\lib\lightgbm
running install_lib
creating C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\lightgbm
copying build\lib\lightgbm\basic.py -> C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\lightgbm
copying build\lib\lightgbm\callback.py -> C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\lightgbm
copying build\lib\lightgbm\compat.py -> C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\lightgbm
copying build\lib\lightgbm\engine.py -> C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\lightgbm
copying build\lib\lightgbm\libpath.py -> C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\lightgbm
copying build\lib\lightgbm\plotting.py -> C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\lightgbm
copying build\lib\lightgbm\sklearn.py -> C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\lightgbm
copying build\lib\lightgbm\VERSION.txt -> C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\lightgbm
copying build\lib\lightgbm\__init__.py -> C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\lightgbm
INFO:LightGBM:Installing lib_lightgbm from: ['compile\\Release\\lib_lightgbm.dll']
copying compile\Release\lib_lightgbm.dll -> C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\lightgbm
byte-compiling C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\lightgbm\basic.py to basic.cpython-37.pyc
byte-compiling C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\lightgbm\callback.py to callback.cpython-37.pyc
byte-compiling C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\lightgbm\compat.py to compat.cpython-37.pyc
byte-compiling C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\lightgbm\engine.py to engine.cpython-37.pyc
byte-compiling C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\lightgbm\libpath.py to libpath.cpython-37.pyc
byte-compiling C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\lightgbm\plotting.py to plotting.cpython-37.pyc
byte-compiling C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\lightgbm\sklearn.py to sklearn.cpython-37.pyc
byte-compiling C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\lightgbm\__init__.py to __init__.cpython-37.pyc
running install_egg_info
Copying lightgbm.egg-info to C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\lightgbm-2.3.2-py3.7.egg-info
running install_scripts
`

when I run my code

`
params = {  
                'boosting_type': 'gbdt',  
                'objective': 'multiclass',  
                'num_class': 9,  
                'metric': 'multi_error',  
                'num_leaves': 120,  
                'min_data_in_leaf': 100,  
                'learning_rate': lr,  
                'feature_fraction': 0.8,  
                'bagging_fraction': 0.8,  
                'bagging_freq': 5,  
                'lambda_l1': 0.4,  
                'lambda_l2': 0.5,  
                'min_gain_to_split': 0.2,  
                'verbose': -1, 
                'device':'gpu'
            }  
            print('Training...')
            trn_data = lgb.Dataset(x_train, y_train)
            val_data = lgb.Dataset(x_valid, y_valid)
            clf = lgb.train(params, 
                            trn_data, 
                            num_boost_round = iterations_,
                            valid_sets = [trn_data,val_data], 
                            verbose_eval = 100, 
                            early_stopping_rounds = 100)
`
[LightGBM] [Fatal] GPU Tree Learner was not enabled in this build.
Please recompile with CMake option -DUSE_GPU=1
Traceback (most recent call last):
  File "lightgbmss.py", line 157, in <module>
    iterations_=10, seed_num=3, lr=0.037)
  File "lightgbmss.py", line 94, in trainlgb_single
    early_stopping_rounds = 100)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\lightgbm\engine.py", line 228, in train
    booster = Booster(params=params, train_set=train_set)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\lightgbm\basic.py", line 1790, in __init__       
    ctypes.byref(self.handle)))
  File "C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\lightgbm\basic.py", line 46, in _safe_call       
    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))
lightgbm.basic.LightGBMError: GPU Tree Learner was not enabled in this build.
Please recompile with CMake option -DUSE_GPU=1`



SO HOW TO INSTALL GPU python package ?

**Comment by PointCloudNiphon** [comment]
![image](https://user-images.githubusercontent.com/37015371/78236695-efb69880-750c-11ea-9122-af74898f7bbe.png)
I follow this steps,it was ok, but then ,how can I get python packages...

**Comment by jameslamb** [comment]
If you need to build for GPU, can you please try [these  installation steps](https://github.com/microsoft/LightGBM/tree/master/python-package#build-gpu-version).

If you don't need the bleeding-edge version:

```shell
pip install lightgbm --install-option=--gpu
```

If you want the most recent version on `master`:

```shell
python setup.py install --gpu
```

Also in case you've never seen it, can you please [use triple backticks to reformat code and log blocks](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks#fenced-code-blocks)? I've edited https://github.com/microsoft/LightGBM/issues/2964#issuecomment-607742567 to show you an example.

**Comment by StrikerRUS** [comment]
@PointCloudNiphon 
> `AttributeError: module 'lightgbm' has no attribute 'Dataset'`

The most possible cause is that your file is named `lightgbm.py`.

> I follow this steps,it was ok, but then ,how can I get python packages...

After compiling GPU-accelerated dll library manually, you can run `python setup.py install --precompile`

But as @jameslamb has already said, it is easier to pass `--gpu` option.

**Comment by PointCloudNiphon** [comment]
thanks for all of you who answer my question，now I will have a.try

**Comment by PointCloudNiphon** [comment]
when I run
`
 cmake -A x64 -DUSE_GPU=1 -DBOOST_ROOT=C:/local/boost_1_72_0 -DBOOST_LIBRARYDIR=C:/local/boost_1_72_0/lib64-msvc-14.2 -DOpenCL_LIBRARY="C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/lib/x64/OpenCL.lib" -DOpenCL_INCLUDE_DIR="C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/include" ..`
to build a gpu verison I get some failures 
`
-- Found Boost: C:/local/boost_1_72_0 (found suitable version "1.72.0", minimum required is "1.56.0") found components: filesystem system
-- Performing Test MM_PREFETCH
-- Performing Test MM_PREFETCH - Failed
-- Performing Test MM_MALLOC
-- Performing Test MM_MALLOC - Failed
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/Administrator/Desktop/installation/LGB_GPU/LightGBM/build

`
are they matter?

**Comment by StrikerRUS** [comment]
> are they matter?

Nope. Refer to the following code. You still benefit from these  speedups, because you use 
> Operating System:win10 Visual Studio 16 2019.



https://github.com/microsoft/LightGBM/blob/3a335e9d4f63da10094d690a92cbefd0f4e6faf6/include/LightGBM/utils/common.h#L29-L41

**Comment by PointCloudNiphon** [comment]
thx

**Comment by PointCloudNiphon** [comment]
are cuda10.1 supported?

**Comment by StrikerRUS** [comment]
It should be. We have a case of successful compilation with CUDA 10.0
https://github.com/microsoft/LightGBM/issues/2081#issuecomment-480504939
