### ISSUE TITLE
How to hypertune using LightGBM Tuner for regression task?

### ISSUE THREAD

**Issue by rahul4tripathi2** [microsoft/LightGBM#2967]
I'm working on project where I've to predict tea_supply based on some features. For Hyperparameter tuning I'm using Bayesian model-based optimization and gridsearchCV but it is very slow. can you please share any doc how to tune lightgbm using lightgbm tuner for regression?

**Comment by StrikerRUS** [comment]
Here is what we have for now: https://lightgbm.readthedocs.io/en/latest/Parameters-Tuning.html

Also, we already have a request for enhancing parameter tuning guide. Refer to #2617. Please feel free to contribute your observations!
