### ISSUE TITLE
Is there a plan to support time series splitting when using cv?

### ISSUE THREAD

**Issue by extremin** [Microsoft/LightGBM#297]
Is there a plan to support time series splitting when using cv？like the new splitting strategy of  sklearn below
http://scikit-learn.org/stable/modules/generated/sklearn.model_selection.TimeSeriesSplit.html

**Comment by wxchan** [comment]
I think it's not a key feature. You can use sklearn.model_selection.TimeSeriesSplit to split data and train with lightgbm.

**Comment by extremin** [comment]
Thx for your reply.I just think it's useful when dealing with time series data and we can get the best CV iteration easily using earlystopping.

**Comment by wxchan** [comment]
We can do like this: 

- [ ] add an argument called data_splitter for example to lightgbm.cv, it takes a Class instance with split() method
- [ ] update document
- [ ] add a test case 

are you interested in implementing it? You can reopen this thread.
