### ISSUE TITLE
Install on macOS

### ISSUE THREAD

**Issue by samyip123** [microsoft/LightGBM#2972]
when installing on macos using 
pip install lightgbm
the following occurred 
OSError: dlopen(/Users/anaconda3/lib/python3.7/site-packages/lightgbm/lib_lightgbm.so, 6): Library not loaded: /usr/local/opt/libomp/lib/libomp.dylib
  Referenced from: /Users/anaconda3/lib/python3.7/site-packages/lightgbm/lib_lightgbm.so
  Reason: image not found

when installing using 
git clone --recursive https://github.com/microsoft/LightGBM ; cd LightGBM
export CXX=g++-7 CC=gcc-7  # replace "7" with version of gcc installed on your machine
mkdir build ; cd build
cmake ..
make -j4
according to the installation guide, after  running the setup.py file, there is a CMake error 

CMake Error at /Users//anaconda3/lib/python3.7/site-packages/cmake/data/CMake.app/Contents/share/cmake-3.16/Modules/CMakeDetermineCCompiler.cmake:49 (message):
  Could not find compiler set in environment variable CC:
  gcc-7.
Call Stack (most recent call first):
  CMakeLists.txt:7 (PROJECT)
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "/Users//LightGBM/python-package/build_cpp/CMakeFiles/CMakeOutput.log".

**Comment by StrikerRUS** [comment]
> when installing on macos using
pip install lightgbm

The reason is in not installed `libomp`
```
not loaded: /usr/local/opt/libomp/lib/libomp.dylib
```

Please follow the installation guide: https://github.com/microsoft/LightGBM/tree/master/python-package#install-from-pypi-using-pip.
