### ISSUE TITLE
[R-package] Add support for non-ASCII feature names

### ISSUE THREAD

**Issue by jameslamb** [microsoft/LightGBM#2983]
## Summary

See #2976 for background. That PR adds support for non-ASCII features back to the C++ and Python libraries. A test in the R package was added in that PR but was breaking for reasons that weren't obvious, see for example https://github.com/microsoft/LightGBM/pull/2976#issuecomment-609905640.

I _think_ that closing this issue will mean changing `lgb.encode.char()`. You'll know that a f ix is working if you remove the  `testthat::skip()` call added in #2976 .

**Comment by jameslamb** [comment]
Closed in favor of being in #2302. We decided to keep all feature requests in one place.

Welcome to contribute this feature! Please re-open this issue (or post a comment if you are not a topic starter) if you are actively working on implementing this feature.

**Comment by jameslamb** [comment]
@StrikerRUS Even though Hacktoberfest is over, I still think that `good first issue` issues should be kept open actually, so that they're discoverable for new contributors. I think hiding them in #2302 makes them hard to find.

It's very common practice on GitHub for would-be new contributors to go to a repository and expect to be able to filter the open issues by `good first issue`.

**Comment by StrikerRUS** [comment]
@jameslamb I'm OK with that. But please add some words about that in #2302 opening message then.
