### ISSUE TITLE
Time Series Cross Validation

### ISSUE THREAD

**Issue by Solly7** [microsoft/LightGBM#2984]
Hi, I would like to ask and see if we do have a module to perform time series cross validation?

**Comment by StrikerRUS** [comment]
Hey!

You can use one from scikit-learn:
https://github.com/microsoft/LightGBM/blob/a8c1e0a11a5cbfac62fb57d16901fea16de95412/tests/python_package_test/test_engine.py#L16
https://github.com/microsoft/LightGBM/blob/a8c1e0a11a5cbfac62fb57d16901fea16de95412/tests/python_package_test/test_engine.py#L707-L714
