### ISSUE TITLE
[RFC] change strategy of defining LightGBM's dependencies

### ISSUE THREAD

**Issue by StrikerRUS** [microsoft/LightGBM#2987]
At present we assume that we are OK with all future versions of our dependencies by default. @henry0312 suggested to change that policy: https://github.com/microsoft/LightGBM/pull/2949#discussion_r401550141

Copying the discussion here

---
> @henry0312 
is this `'scikit-learn~=0.22,!=0.22.0'`?
---
> @StrikerRUS 
    Sorry, I can't find `~` in the `setuptools` docs. Can you please clarify what do you mean?
>> A version specifier is one of the operators <, >, <=, >=, == or !=, followed by a version identifier.
    https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-dependencies
---
> @henry0312 
  Version specifiers
https://www.python.org/dev/peps/pep-0440/#version-specifiers
---
> @StrikerRUS 
 OK. I guess that this specifier is not compatible with `setuptools` as it is not listed there, is it?
 Also, why do we need it? We are compatible with all (reasonable) versions except `0.22.0`.

---
> @henry0312 
>> OK. I guess that this specifier is not compatible with setuptools as it is not listed there, is it?

> I don't know the specific version but `setuptools` used in sklearn, numpy, scipy and pandas supports version specifier as least.

>> Also, why do we need it? We are compatible with all (reasonable) versions except 0.22.0.

> Not enough.
 As you know, many python packages follow [Semantic Versioning](https://semver.org/), including scikit-learn.
 If we specify `scikit-learn!=0.22.0` and v1.0.0 of scikit-learn is released, LightGBM will allow users to use v1.0.0, which can lead to break backward compatibility.
 Therefore, if we follow [Semantic Versioning](https://semver.org/), we should specify libraries' version by Version specifiers.
---
> @StrikerRUS 
>> If we specify scikit-learn!=0.22.0 and v1.0.0 of scikit-learn is released, LightGBM will allow users to use v1.0.0,

> I don't see any problems with it. Moreover, I believe that this should be an expected behavior.
Before now we have never blocked **future** versions of libraries, assuming that by default we are compatible with them. If it is not true, someone comes and posts an issue and we are investigating.
In case of prohibiting future releases it is highly likely that we'll forget to update those requirements or will do it with huge delay making user experience inconvenient.
---
> @henry0312 
>> Before now we have never blocked future versions of libraries, assuming that by default we are compatible with them. 

> When that is our policy, as you say, there is no problem and I'll approve this PR, though I don't think the policy is common in software engineering.
In other words, a new version which can breaks backward compatibility in terms of Semantic Versioning is released, we should check its compatibility and will add suuport of it in series.
---
> @henry0312 
 In fact, if we specified Sphinx version, https://github.com/microsoft/LightGBM/commit/ce08242567e1e37e1f947038a78ac671c98ed18e#diff-e0c7b285f2f2d8028247b8cfd4dc76fcR1 were not needed, though that are just tests.
 I think unless we follow the basic rules of software engineering, the quality of library won't increase so much even If we add more and more tests.
 So I'll approve this when our support policy is clear.

---
> @ekerazha
>@henry0312 Actually it's pretty common in software engineering to allow for future versions of dependencies in **libraries** (while it's common to be more strict in end-user products). If a dependency follows Semantic Versioning (SemVer), you could put a restriction on major versions (e.g. scikit-learn<1.0), but I don't think sklearn is following SemVer. Unless you're ready to release a new version of LightGBM every time a new minor version or patch for a dependency is released, of course.
---
> @StrikerRUS 
   @henry0312 
>> though I don't think the policy is common in software engineering.

> It's kind of debatable statements. And I don't think that this PR is a good place to discuss it. I think we should create a separate issue where we should at least get opinions of other maintainers before changing the current policy.
>> we should check its compatibility and will add suuport of it in series.

> In ideal situation, yes! You are absolutely right! But given that we are lacking human resources to do it in time, I suppose that it will be simply abandoned in the near future. Which will result in very old dependencies of LightGBM.
---
> @StrikerRUS 
>> Unless you're ready to release a new version of LightGBM every time a new minor version or patch for a dependency is released, of course.

> Absolutely agree! It is definitely not our case when only 2-3 maintainers work actively at the same time.
---
> @henry0312 
  @ekerazha @StrikerRUS I don't mean all of the future versions wont' be allowed, but only the future versions that can breaks backward compatibility (in other words, a release changes major version), which version specifiers (i.e. `scikit-learn~=0.22,!=0.22.0` or `scikit-learn>=0.22, == 0.*`) realizes.
  And is LightGBM an almost end-user products? I think so.
>> I don't think sklearn is following SemVer.

> oh, really...? Actually, I'm not sure.
---
> @ekerazha 
  @henry0312 
>> And is LightGBM an almost end-user products? I think so.

> LightGBM is a library, a travel website which uses LightGBM to recommend travels would be the end-user product.
>> oh, really...? Actually, I'm not sure.

>scikit-learn had breaking API changes in minor versions, so it's not following SemVer.
---
> @StrikerRUS 
  @henry0312 I guess `0.22` is a **minor** release, but it broke  backward compatibility.
  Again, please let's move all our discussion to a separate issue where everyone will be able to comment. It's very hard to find it here and I want to merge this PR ASAP to enable the latest scikit-learn support.

ping @henry0312 @guolinke @chivee @jameslamb @Laurae2 @ekerazha

**Comment by henry0312** [comment]
Thank you for your discussion.
I think we need to change the current policy only when scikit-learn (also including pandas, numpy and so on) follows Semantic Versioning.

**Comment by jameslamb** [comment]
I agree with @StrikerRUS that we should not block future versions of libraries.

Given a new version of `scikit-learn`:

1. (with blocking + LightGBM incompatible) --> users get error and open an issue asking us to support new version
2. (with blocking + LightGBM compatible) -->  users get error and open an issue asking us to support new version
3. (without blocking + LightGBM incompatible) --> users get error and open an issue asking us to support new version
4. (without blocking + LightGBM compatible) --> no errors and no issue

People are welcome to use `conda`, `virtualenv`, `pipenv`, Docker, or whatever else they want to peg versions of `scikit-learn` and  `LightGBM`  together. I feel we owe our users documentation on which versions are _tested_ and thus expected to work together, but not a guarantee that `LightGBM`'s `setup.py` will detect incompatibilities with newer versions of other libraries at installation time.

**Comment by StrikerRUS** [comment]
I mostly afraid (and to be honest, pretty sure) that we'll not be able to bump versions of dependencies in time due to lack of maintainers' hands. I believe that this will be more inconvenient for our users than suddenly (and I hope rarely) broken dependency. In addition it will allow us to know that some dependency is broken right after its release and do not wait when one come and create an issue.

As a workaround I guess we can try to use some tools for dependency versioning like https://dependabot.com/ or https://renovatebot.com/. I don't know whether any of them supports rules with `<=` or `~=`, I only saw `==`. It is field for the investigation. Auto-PRs look like the following (https://github.com/NewOrbit/load-image-react/pulls).

![image](https://user-images.githubusercontent.com/25141164/78999592-a3dea180-7b53-11ea-9090-bc1bd8099224.png)
