### ISSUE TITLE
Early stopping in a Scikit Pipeline

### ISSUE THREAD

**Issue by mratsim** [Microsoft/LightGBM#299]
I use LGBMClassifier as the last step of a Pipeline which works great.

However I am unable to use early stopping.
Early stopping needs "eval_set" to be set, but there is no way to easily reapply the pipeline transformation to eval_set.

For example, this code would not work because LGBMClassifier does not implement the transform method:
```python
eval_set = [(pipe.transform(X_test),pipe.transform(y_test))]
```

I see two potential solutions to this:

1. Implement a dummy transform method which according to this [Scikitlearn documentation](http://scikit-learn.org/stable/developers/contributing.html#pipeline-compatibility) will allow to apply the Pipeline to arbitrary data. 

2. Similar to [Keras](https://keras.io/models/sequential/), implement a validation_split parameter that  holds out part of the input data to be used as eval_set.

I checked the source code of XGBClassifier, it seems to suffer from the same issue, see https://github.com/dmlc/xgboost/issues/2039

**Comment by wxchan** [comment]
`transform` is deprecated in [`sklearn.ensemble.GradientBoostingClassifier`](http://scikit-learn.org/stable/modules/generated/sklearn.ensemble.GradientBoostingClassifier.html#sklearn.ensemble.GradientBoostingClassifier.transform), what will happen if you use it in pipeline?

**Comment by mratsim** [comment]
The transform method of `sklearn.ensemble.GradientBoostingClassifier` is actually selecting the top features from the train data and returning only that. My first proposal would be to have transform being an identity function.
Proposal 1 might actually be something to resolve/clear up upstream though: "How to apply Pipeline transformations without the last classifier step to a validation set"

Just for reference if I try to use it I get a NotFittedError (makes sense, you cannot check top features without fitting first).

```python
---------------------------------------------------------------------------
NotFittedError                            Traceback (most recent call last)
<ipython-input-23-7f4e8ac0c075> in <module>()
----> 1 pipe.transform(X)

/usr/lib/python3.6/site-packages/sklearn/pipeline.py in _transform(self, X)
    443         for name, transform in self.steps:
    444             if transform is not None:
--> 445                 Xt = transform.transform(Xt)
    446         return Xt
    447 

/usr/lib/python3.6/site-packages/sklearn/utils/deprecation.py in wrapped(*args, **kwargs)
     69         def wrapped(*args, **kwargs):
     70             warnings.warn(msg, category=DeprecationWarning)
---> 71             return fun(*args, **kwargs)
     72 
     73         wrapped.__name__ = fun.__name__

/usr/lib/python3.6/site-packages/sklearn/feature_selection/from_model.py in transform(self, X, threshold)
    116         """
    117         check_is_fitted(self, ('coef_', 'feature_importances_'),
--> 118                         all_or_any=any)
    119 
    120         X = check_array(X, 'csc')

/usr/lib/python3.6/site-packages/sklearn/utils/validation.py in check_is_fitted(estimator, attributes, msg, all_or_any)
    688     if not all_or_any([hasattr(estimator, attr) for attr in attributes]):
    689         # FIXME NotFittedError_ --> NotFittedError in 0.19
--> 690         raise _NotFittedError(msg % {'name': type(estimator).__name__})
    691 
    692 

NotFittedError: This GradientBoostingClassifier instance is not fitted yet. Call 'fit' with appropriate arguments before using this method.
```

I've checked further in Sklearn and there is an API proposal for early-stopping: https://github.com/scikit-learn/scikit-learn/issues/1626
And [implementation](https://github.com/scikit-learn/scikit-learn/pull/2570/commits/ecd606bfb4ab79e0aa4e6b574bcb0c75b1a7250f) for their GradientBoostingClassifier but there is no validation set support.

Regarding the test case, I'll work on a minimum example to reproduce over the weekend.

**Comment by wxchan** [comment]
Would you like to submit a pr for this issue?

**Comment by mratsim** [comment]
@wxchan Thank you for your follow-up.

After extensive talking with @Laurae2, I think both solution 1 and 2 should not be done at LightGBM level.

## For solution 1  - Implement a dummy `transform` method:
- This would be a workaround upon a lack of functionality in `sklearn` Pipeline API. Most classifiers even in sklearn do not have a `transform`. And for those that do have (Decision Trees and variants), it was used to extract features and is deprecated as you linked.
Adding a dummy `transform` method would be make it very confusing for people on what to expect (dummy, feature extraction, ...)

## For solution 2 - Implement a validation split like in `Keras`:
- The issue here as pointed by @laurae is the lack of control on the validation set and the split. I If there is a need to inspect deeper into validation issues, I suppose it would be non-trivial to extract it from the classifier or provide an API for it.


My recommendation would be for a Sklearn.pipeline method to apply all pipeline transformations to an arbitrary dataset (validation set usually).
Hence, I will open a ticket to `Scikit-learn` and close this ticket (unless further discussion) in the next 3 days.

**Comment by mratsim** [comment]
Closing, issue is raised with Scikit-learn.
