### ISSUE TITLE
use dart and goss at the same time

### ISSUE THREAD

**Issue by stanpcf** [microsoft/LightGBM#2991]
## Summary
Current version of lightgbm, there are four boosting algorithm: `dart`, `goss`, `rf`, `gbdt`. the first three inherit from `gbdt` and can't use them at the same time(for example use dart and goss at the same time).

## Motivation
those boosting algorithm which are not mutually exclusive. such as useing dart and goss at the samee time will get better accuary and speed.

**Comment by guolinke** [comment]
Closed in favor of being in #2302. We decided to keep all feature requests in one place.

Welcome to contribute to this feature! Please re-open this issue (or post a comment if you are not a topic starter) if you are actively working on implementing this feature.

**Comment by guolinke** [comment]
move the discussion to #3128
