### ISSUE TITLE
Maintained fork of external (unofficial) Julia wrapper

### ISSUE THREAD

**Issue by yalwan-iqvia** [microsoft/LightGBM#3008]
Hello
We have recently released https://github.com/IQVIA-ML/LightGBM.jl and registered it into the julia general registry. As far as I know, the link pointed to in the main README is not actively maintained any longer.
Would it be appropriate to update this link to the maintained fork I linked above?

**Comment by yalwan-iqvia** [comment]
For context, I refer to this line: https://github.com/microsoft/LightGBM/blame/master/README.md#L59

**Comment by StrikerRUS** [comment]
Hello @yalwan-iqvia !

Thank you raising this issue! Some time ago I saw activity in https://github.com/Allardvm/LightGBM.jl/pull/22, where maintainers discussed the fate of Julia package. Are you aware of that discussion?

**Comment by yalwan-iqvia** [comment]
Yes indeed, although I only just became aware of it. However I can see activity level is low, and both primary maintainer and contributor for that PR have expressed that they do not really wish to have maintenance burden (or at least this is how I understand). Our group is however, happy to have maintenance responsibility (which is why we have published fork and plan on actively developing it)

If you are referring to the notion of whether the julia wrapper could live inside this repository as well, this is a discussion we could have if you wish.

**Comment by StrikerRUS** [comment]
@yalwan-iqvia OK, I see. Thanks for your feedback!

> Our group is however, happy to have maintenance responsibility (which is why we have published fork and plan on actively developing it)

This is awesome! Can you please describe your group in more details or at least list all members with the aim to know who we may ping in the future?
Also, I think that question about the license is quite important. What type of license is planned to use?

Of course, we'd like to hear opinions on this question from the original author and Julia v1.x contributor. So gently ping @Allardvm and @wakakusa. Please feel free to express all your thoughts and objections.

Speaking about project location, I remember the following very old discussion: https://github.com/Allardvm/LightGBM.jl/issues/13. In the addition to the reasons listed in №1 of https://github.com/Allardvm/LightGBM.jl/issues/13#issuecomment-274072859, we do not have Julia experts in our core team, so I **personally** think that keeping the project in a separate repo would be the preffered way of development.

**Comment by yalwan-iqvia** [comment]
To answer your question about the licence, we planned on keeping original MIT expat licence.
I have made @Allardvm and @wakakusa aware of this thread on the other PR, so hopefully we can see responses soon.

You should hear from @iqml soon regarding our group.

**Comment by Allardvm** [comment]
As indicated (https://github.com/Allardvm/LightGBM.jl/pull/22), I would be perfectly happy with having @yalwan-iqvia take over maintenance of the packages and using https://github.com/IQVIA-ML/LightGBM.jl as the main repository.

Thanks a bunch for your efforts, and for having the courtesy to reach out for permission to swap repos 👍!

**Comment by wakakusa** [comment]
I have no problem with @yalwan-iqvia    taking over the maintenance and development of the package and using https://github.com/IQVIA-ML/LightGBM.jl as the main repository.

Thank you for tuning the repository and making LightGBM available to more Julia users.
