### ISSUE TITLE
Parallel training in R

### ISSUE THREAD

**Issue by anupkotalwar** [Microsoft/LightGBM#301]
Hello,

Is there way to perform parallelize training using R wrapper?

Thanks,
Anup

**Comment by minimaxir** [comment]
Use the `num_threads` parameter. You can verify that the training is indeed parallel by observing Task Manager/Activity Monitor.

**Comment by anupkotalwar** [comment]
How can we configure to run it on multiple machines?

**Comment by guolinke** [comment]
@anupkotalwar 
Currently, R/python package doesn't support parallel learning.
You can use CLI version instead.
