### ISSUE TITLE
Some clarifications for the algorithm

### ISSUE THREAD

**Issue by shenkev** [microsoft/LightGBM#3010]
1. Exclusive feature bundling has a notion of "joining features that rarely take on non-zero values simultaneously". What does "nonzero" mean in the context of joining 2 continuous variables? I'd imagine continuous variables are actually nonzero most of the time in most dataset. Is "zero" set to some mean value or would continuous features just not be bundled?

2. How do we expect EFB to behave when the features are dense and there are few exclusive sets? Will bundling still occur?

3. The algorithm seems to allow a small fraction of conflicts in feature bundling, how are conflicts handled? Are they set to 0 by default or the value of one feature is ignored or something else?

**Comment by guolinke** [comment]
1. EFB is used in the sparse data, which contains many zero/nan values. And in our implementation, we use `most_freq_bin` (the bucketed int value with most data) as "zero" to perform bundling. Therefore, EFB may work for dense data with many repeated values.
2. The EFB is always used. It may cannot find the bundle for dense data. 
3. The feature value in the conflicting row will be treated is zero/most_freq_bin.
