### ISSUE TITLE
Custom eval functions do not work

### ISSUE THREAD

**Issue by BaruchYoussin** [microsoft/LightGBM#3017]
## Environment info

Operating System: Ubuntu 18.04

CPU/GPU model: Intel® Core™ i5-7200U CPU @ 2.50GHz × 4 

C++/Python/R version: Python 3.6

LightGBM version or commit hash: 2.3.1

## Error message

TypeError: unsupported operand type(s) for -: 'Dataset' and 'float'

## Reproducible examples

```
import numpy as np
import pandas as pd
import lightgbm as lgbm

def median_absolute_percentage_error_lgbm(y_true, y_pred):
    return 'med_ape', np.median(np.abs((y_pred - y_true) / y_true)), False

all_train = pd.DataFrame({'f1': np.random.random(100), 'f2': np.random.random(100)})
target = pd.Series(np.random.random(100))

params = {'learning_rate': 0.06, 'objective': 'mape', 'num_iterations': 10000, "seed": 42,
          'metric': 'mape', 'alpha' : 0.5, 'first_metric_only': True,
          'feature_fraction': 0.75, "bagging_fraction": 0.8, "bagging_freq": 1,
          'early_stopping_rounds': 10}

train_set = lgbm.Dataset(all_train, target)
val_set = lgbm.Dataset(all_train, target)
train_results = {}
model = lgbm.train(params, train_set, valid_sets=[val_set], valid_names=['val'],
                   feval=median_absolute_percentage_error_lgbm,
                   verbose_eval=10,
                   evals_result=train_results)
```

## Steps to reproduce

1.  Run the above code.

## Comments
Custom eval function is called with the parameter y_pred being a dataset, instead of an array.

**Comment by StrikerRUS** [comment]
@BaruchYoussin Please use appropriate custom eval function for standard API (you are using one for scikit-learn wrapper).

```
def median_absolute_percentage_error_lgbm(y_pred, train_data):
    y_true = train_data.get_label()
    return 'med_ape', np.median(np.abs((y_pred - y_true) / y_true)), False
```

Refer to 
https://github.com/microsoft/LightGBM/blob/02a0089fc1c627e9f98776ab64c2aaac5209a56e/python-package/lightgbm/engine.py#L57-L60
and 
https://github.com/microsoft/LightGBM/blob/02a0089fc1c627e9f98776ab64c2aaac5209a56e/examples/python-guide/advanced_example.py#L136-L166

**Comment by BaruchYoussin** [comment]
@StrikerRUS Many thanks!
