### ISSUE TITLE
[R-package] MSVC compiler warnings

### ISSUE THREAD

**Issue by jameslamb** [microsoft/LightGBM#3025]
Working on #2963 , I see two warnings generated when building the R package using MSVC.

> C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(467,5):
    warning MSB8029: The Intermediate directory or Output directory cannot reside under the Temporary directory as it could lead to issues with incremental build.

> config.cpp
C:\Users\James\AppData\Local\Temp\Rtmpy8QQoo\R.INSTALL20184a692267\lightgbm\src\src\boosting\prediction_early_stop.cpp(86):
    warning C4715: 'LightGBM::CreatePredictionEarlyStopInstance': not all control paths return a value

I don't know yet if these are specific to the R package, and I'm not aware of any reported issues related to them. But we should still try to fix these so that other more worrying warnings are not lost in the noise of the logs.

**Comment by StrikerRUS** [comment]
Seems that all issues here were fixed and we can close it, can't we?

**Comment by jameslamb** [comment]
yes, thank you!
