### ISSUE TITLE
CreateParser may cause wrong num_col when libsvm-format data is sparse

### ISSUE THREAD

**Issue by stanpcf** [microsoft/LightGBM#3027]
https://github.com/microsoft/LightGBM/blob/2c18a0f3ed732df77d4304ed1d2b46a345d661c8/src/io/parser.cpp#L199 
lines will get at most 20 line of data from data file. the func `GetDataType` will parse the last featureid for each line and max(featureid) as `num_col`. 
If data is sparse, `num_col` will be wrong.

**Comment by guolinke** [comment]
It is hard to say which lines are enough for sparse data, but 20 indeed is too few.
Maybe we can have a reasonable guess from file size.
