### ISSUE TITLE
Using custom eval_metric with sklearn API

### ISSUE THREAD

**Issue by andreasmarxer** [microsoft/LightGBM#3029]
I do get the error message: **ValueError: Classification metrics can't handle a mix of binary and continuous targets**, when using my custom evaluation metrics defined as a function.

```
def calculate_recall(y_true, y_pred):
    c_matrix = sklearn.metrics.confusion_matrix(y_true, y_pred)
    TN = c_matrix[0,0]
    FN = c_matrix[1,0]
    FP = c_matrix[0,1]
    TP = c_matrix[1,1]
    recall = TP / (TP + FN)
    #call_test = metrics.recall_score(y_true, y_pred)
    #print(recall_test)
    return ('recall', recall, True)
```

```
params = {
    'objective': 'binary',
    'is_unbalance': False,
    'learning_rate': 0.01,
    'bagging_fraction': 0.8,
    'bagging_freq': 1,
    'random_state': None # random_state = None is also fixed from C++
}
```

```
for train_index, test_index in cv.split(X_df, y_df, groups_df):
    print('--- Participant %d ------------------------------------' % groups_df[test_index[0]])
    file.write('--- Participant %d ------------------------------------ \n' % groups_df[test_index[0]])

    # get CV split of train data
    X_train, X_test = X_df.iloc[train_index], X_df.iloc[test_index]
    y_train, y_test = y_df.iloc[train_index], y_df.iloc[test_index]
    
    print('# train: ', len(y_train))
    file.write('# train: %d \n' % len(y_train))
    print('# test: ', len(y_test))
    file.write('# test: %d \n' % len(y_test))
    
    # define new model and save
    model = lgb.LGBMClassifier(**params)
    
    # train model
    model.fit(X_train, y_train,
              verbose=2, # print validation every i'th iteration
              eval_metric=calculate_recall,
              #eval_metric='auc', #standard metric is log_loss! #choice: 'auc'
              eval_set=[(X_train, y_train), (X_test, y_test)],
              eval_names=['train', 'test'],
              early_stopping_rounds=10) # stop if ONE of the metrices does not improve for i rounds
    # predict
    y_pred = model.predict(X_test, num_iteration=model.best_iteration_)  # num_iteration only when loaded from pickle file??? else wise make it automatically ?!
    print('y_pred: ', y_pred)
    p_pred = model.predict_proba(X_test, num_iteration=model.best_iteration_)[:,1] # probability for predicted 1
    print('p_pred: ', p_pred)
```

When I change line `eval_metric=calculate_recall` to  `eval_metric=calculate_recall(y_true, y_pred)` the code works but only takes the default binary metrics log_loss into account.

Does anyone have an idea of what I'm doing wrong with my loss function?

**Comment by StrikerRUS** [comment]
@andreasmarxer Hi!
I guess your labels are not integer which is required in scikit-learn according to the error message.

Can you please provide a full repro?

**Comment by andreasmarxer** [comment]
Hi @StrikerRUS ,
thank you for your prompt reply!

The labels are of type int64, that should not be the issue.
Further, I will prepare a reproducible script.

**Comment by andreasmarxer** [comment]
Hi @StrikerRUS 
In the meantime, I have a reproducible jupyter notebook: 
https://drive.google.com/open?id=1PmPHMFegauUqZBlTYeEhhEoibpRzg0VI

A short sample of data I did provide here:
https://drive.google.com/open?id=1hYKwKt51QYfCd5sPdUtI17M_4km4T6u4

Best regards and thank you in advance

**Comment by andreasmarxer** [comment]
**Update:** 
I did find out the issue. Indeed it had something in common with integers, but not the labels were the problem.

y_pred must be a label for calculating binary metrics, and per default, it's a probability (inside the model.fit architecture) predicted by the model. I think in the definitions could be stated clearly as eval_func(y_true, p_pred) or mention that y_pred is a probability.

**Comment by StrikerRUS** [comment]
@andreasmarxer Thanks a lot for the feedback!

So, you fixed your issue by converting probabilities into class indices in custom metric by something like this?
```
class_index = np.argmax(y_pred, axis=1)
```

**Comment by andreasmarxer** [comment]
@StrikerRUS 
Not exactly, due to my knowledge, the sklearn model predicts the probability for the binary label 1 because you always assume 1 as the rare class and are interested in predicting p(y=1).

I did convert it in my evaluation function like this:

```
def calculate_recall(y_true, p_pred):
    # convert probability (y=1) to label with threshold 0.5
    y_pred = np.round(p_pred)
    c_matrix = sklearn.metrics.confusion_matrix(y_true, y_pred)
    TN = c_matrix[0,0]
    FN = c_matrix[1,0]
    FP = c_matrix[0,1]
    TP = c_matrix[1,1]
    recall = TP / (TP + FN)
    return 'recall', recall, False
```

A conversion like you mentioned would totally make sense if you would have the (two) probabilities as you get from:
`p_pred = model.predict_proba(X_test, num_iteration=model.best_iteration_)`

But inside the model.fit it seems that:
a) y_pred are probabilities (therefore I got the error when trying to calculate metrics from a probability and a label integer)
b) y_pred is a 1D vector, meaning that it only predicts the probability for one class, where I assumed that it is for class 1, e.g., p(y=1).

But still, for me, it's a bit weird and I did not find detailed information about this topic on the internet, so if you find something please keep me posted.

**Comment by StrikerRUS** [comment]
@andreasmarxer Ah, your classification is binary. Got it!

OK, I'll update the description with more details.
https://github.com/microsoft/LightGBM/blob/2c18a0f3ed732df77d4304ed1d2b46a345d661c8/python-package/lightgbm/sklearn.py#L412
https://github.com/microsoft/LightGBM/blob/2c18a0f3ed732df77d4304ed1d2b46a345d661c8/python-package/lightgbm/sklearn.py#L457-L481

If you have any ideas of how to make the fact of returning probabilities more clear, feel free to help us 🙂

**Comment by andreasmarxer** [comment]
@StrikerRUS 
For me, it would be more clear if naming the predicted probability `p_pred` and the predicted labels `y_pred`. 

Or if you don't want to change the naming mention here at line 468 that the predictions are probabilities:
https://github.com/microsoft/LightGBM/blob/2c18a0f3ed732df77d4304ed1d2b46a345d661c8/python-package/lightgbm/sklearn.py#L468

But I'm not that happy with the naming as `y_pred`, because in the definition of the fit function (see below), it is stated that y are class labels, and therefore I would conclude that `y_pred` inside the fit function are also class labels.
https://github.com/microsoft/LightGBM/blob/2c18a0f3ed732df77d4304ed1d2b46a345d661c8/python-package/lightgbm/sklearn.py#L391

**Comment by StrikerRUS** [comment]
@andreasmarxer Thank you very much for your proposals!

As LightGBM doesn't know anything about your custom metric,
`is_higher_better`
https://github.com/microsoft/LightGBM/blob/2c18a0f3ed732df77d4304ed1d2b46a345d661c8/python-package/lightgbm/sklearn.py#L478
is used in early stopping mechanism for determining when it should stop: when metric increases or decreases.

**Comment by andreasmarxer** [comment]
That completely makes sense, thank you too! @StrikerRUS 
I did see the provided comment but did not get it.

**Comment by StrikerRUS** [comment]
@andreasmarxer 
> Is it possible to have the train and test data monitored in the evaluation for early stopping but only stop according to the test data?

Sure! It is the default behavior.
https://github.com/microsoft/LightGBM/blob/2c18a0f3ed732df77d4304ed1d2b46a345d661c8/python-package/lightgbm/sklearn.py#L419-L420

**Comment by andreasmarxer** [comment]
@StrikerRUS 

Okay, thank you that totally makes sense!

Another unclarity of mine is about the best way of interpreting a fitted gradient boosting machine.

I can look at a specific tree or the feature importance values which seems to be a "weight" for the features of the hole boosting architecture fitted (and not only one tree). 

- According to the documentation the importance values are interpreted as "the higher, the more important the feature", but where exactly do they come from and how are they calculated? 

https://github.com/microsoft/LightGBM/blob/2c18a0f3ed732df77d4304ed1d2b46a345d661c8/python-package/lightgbm/sklearn.py#L273

- I can imagine that the importance values could be a kind of weights in the loss function as it is the case for neural networks, is this interpretation correct or how else are they defined and calculated? This interpretation would also make sense for the available implementation of L1 and L2 regularization. 

(Alternatively, the importance values could be a general measure of how important a feature is for the classification. Here it would be interesting how this measure is defined. )

- Generally, I'm thinking about if looking at the feature importance is an appropriate way of analyzing the fitted boosting machine and deciding if it did learn the "meaningful things" or what would you suggest doing for analyzation?

**Comment by StrikerRUS** [comment]
> but where exactly do they come from and how are they calculated?

There are two available types of importance in LightGBM:
https://github.com/microsoft/LightGBM/blob/2c18a0f3ed732df77d4304ed1d2b46a345d661c8/python-package/lightgbm/sklearn.py#L242-L245
And you can find the source code here:
https://github.com/microsoft/LightGBM/blob/2c18a0f3ed732df77d4304ed1d2b46a345d661c8/src/boosting/gbdt_model_text.cpp#L587-L621

> Generally, I'm thinking about if looking at the feature importance is an appropriate way of analyzing the fitted boosting machine and deciding if it did learn the "meaningful things" or what would you suggest doing for analyzation?

I'd recommend using `shap` package for interpreting fitted models.
https://github.com/microsoft/LightGBM/blob/2c18a0f3ed732df77d4304ed1d2b46a345d661c8/python-package/lightgbm/sklearn.py#L865-L874

**Comment by andreasmarxer** [comment]
Thank you @StrikerRUS, that completely makes sense and does clarify my issue of the interpretation of the `feature_importance`.

I will also look into the proposed SHAP values for analysis.

Coming back to the **initial problem** of the `eval_metric`, now that I have the custom evaluation function working I wanted to have multiple evaluation metrics defined. Herby I got from the documentation that therefore they must be assigned as a list. 

![image](https://user-images.githubusercontent.com/45263298/80797231-93917380-8ba1-11ea-9fef-1b194e7dc181.png)


But unfortunately, this only works for multiple built-in sklearn metrics and not anymore if I include my custom evaluation function into the list. Hereby I tried to include it as callable, and also string with the name defined in the custom evaluation function.

Do you have an idea, or is it just that it is not yet possible to mix the metrics?

### Overview
Working version with a list of strings of default metrics:
```
model.fit(X_train, y_train,
                  verbose=1, 
                  eval_metric=['auc','rmse'], 
                  eval_set=[(X_train, y_train), (X_test, y_test)],
                  eval_names=['train', 'test'],
                  early_stopping_rounds=10) 
```

Working version with a custom evaluation function as callable:
```
model.fit(X_train, y_train,
                  verbose=1, 
                  eval_metric=calculate_recall,
                  eval_set=[(X_train, y_train), (X_test, y_test)],
                  eval_names=['train', 'test'],
                  early_stopping_rounds=10) 
```

But it's **not anymore working properly** if I use a combination, as mentioned above:
In more detail, this means that it runs without error but the evaluation is done only for auc and not for the recall.
**a)**
`eval_metric=[calculate_recall, 'auc']`
**b)**
`eval_metric=['recall, 'auc']` and recall is defined as the name of my custom evaluation function:

```
def calculate_recall(y_true, p_pred):
    # convert probability (y=1) to label with threshold 0.5
    y_pred = np.round(p_pred)
    c_matrix = sklearn.metrics.confusion_matrix(y_true, y_pred)
    TN = c_matrix[0,0]
    FN = c_matrix[1,0]
    FP = c_matrix[0,1]
    TP = c_matrix[1,1]
    recall = TP / (TP + FN)
    #recall_test = sklearn.metrics.recall_score(y_true, y_pred)
    return 'recall', recall, True
```

To come back to my question, is there a way to combine the custom and the built-in evaluation metric?

**Comment by StrikerRUS** [comment]
> To come back to my question, is there a way to combine the custom and the built-in evaluation metric?

Sure! You can find the answer here: https://github.com/microsoft/LightGBM/issues/2182#issuecomment-493452818.

**Comment by andreasmarxer** [comment]
@StrikerRUS thank you, that explains it very well!

As a final question, it might be interesting for me to know if you have a good experience with early stopping and LGBT, or if there do there already exist some notes which you have in mind?
Actually I'm experiencing that early stopping mostly interacts very early, strictly speaking, e.g., in the first, third, or 10th iteration, which actually seems not convincing for me.

I thought about implementing adaptive learning coupled to the evaluation metric, instead of immediately stopping if the eval metric is not improving for some periods, just decrease the learning rate and use early stopping with a harder threshold if it still does not do improving.

**Comment by StrikerRUS** [comment]
Maybe your data is very easy to learn? And it results in very early stopping.
