### ISSUE TITLE
Why do the categorical features need to be encoded as non-negative integers?

### ISSUE THREAD

**Issue by hcz28** [microsoft/LightGBM#3039]
I understand LightGBM can deal with categorical features in an efficiency way. However, the document says that the categorical features must be encoded as non-negative integers. Why?

Thanks!

**Comment by StrikerRUS** [comment]
Please refer to https://lightgbm.readthedocs.io/en/latest/Parameters.html#categorical_feature

> Note: using large values could be memory consuming. Tree decision rule works best when categorical features are presented by consecutive integers starting from zero
Note: all negative values will be treated as missing values

and to #1636.

**Comment by hcz28** [comment]
> Please refer to https://lightgbm.readthedocs.io/en/latest/Parameters.html#categorical_feature
> 
> > Note: using large values could be memory consuming. Tree decision rule works best when categorical features are presented by consecutive integers starting from zero
> > Note: all negative values will be treated as missing values
> 
> and to #1636.

Thanks!
