### ISSUE TITLE
How to use advantage of CEGB?

### ISSUE THREAD

**Issue by Taube03** [microsoft/LightGBM#3044]
LightGBM [claims support ](https://lightgbm.readthedocs.io/en/latest/Advanced-Topics.html#cost-efficient-gradient-boosting) of Cost Efficient Gradient Boosting. There is information, how to set penalties for feature usages, but how to use advantage of cost efficient model? Is there any interface to provide expensive-to-calculate features on request from model evaluation?

**Comment by guolinke** [comment]
please refer to the original paper: https://papers.nips.cc/paper/6753-cost-efficient-gradient-boosting.pdf

**Comment by Taube03** [comment]
> please refer to the original paper: https://papers.nips.cc/paper/6753-cost-efficient-gradient-boosting.pdf

Thank you for your reply! But I couldn't find any reference to actual lightGBM interface to provide expensive-to-calculate features on request when applying model.

**Comment by guolinke** [comment]
@Taube03 
did you mean the code location?
you can refer to https://github.com/microsoft/LightGBM/blob/master/src/treelearner/cost_effective_gradient_boosting.hpp
