### ISSUE TITLE
python how to use is_unbalance or scale_pos_weight parameters?

### ISSUE THREAD

**Issue by Sandy4321** [microsoft/LightGBM#3049]
## How you are using LightGBM?

<!-- 
Choose one of the following components

* Python package

LightGBM component: 

## Environment info

Operating System: windows

CPU/GPU model: cpu

C++ compiler version:

CMake version:

Java version:

Python version: 3.7

R version:

Other:

## Error message and / or logs

https://lightgbm.readthedocs.io/en/latest/pythonapi/lightgbm.LGBMClassifier.html
stated 
class_weight (dict, 'balanced' or None, optional (default=None)) – Weights associated with classes in the form {class_label: weight}. Use this parameter only for multi-class classification task; for binary classification task you may use is_unbalance or scale_pos_weight parameters.

But there is no instructions of this page how to use 
is_unbalance or scale_pos_weight parameters
only on this page 
https://lightgbm.readthedocs.io/en/latest/Parameters.html
they are explained
so for class_weight it works like this
import lightgbm as lgbm
importance_type_LGB = 'gain' 
lgb_clf = lgbm.LGBMClassifier(class_weight = 'balanced' ,importance_type = importance_type_LGB)
lgb_clf.fit(X_train,target_train)

but what  will be for is_unbalance?
is it
import lightgbm as lgbm
importance_type_LGB = 'gain' 
lgb_clf = lgbm.LGBMClassifier(is_unbalance= True ,importance_type = importance_type_LGB)
lgb_clf.fit(X_train,target_train)

## Reproducible example(s)

import lightgbm as lgbm
importance_type_LGB = 'gain' 
lgb_clf = lgbm.LGBMClassifier(is_unbalance= True ,importance_type = importance_type_LGB)
lgb_clf.fit(X_train,target_train)

**Comment by Sandy4321** [comment]
it is not clear how  to use is_unbalance or scale_pos_weight parameters
do you have code example 
since I do you use class_weight = 'balanced' for binary data and it works

code example is
_____________________________________________________________________________
import lightgbm as lgbm
importance_type_LGB = 'gain'  
lgb_clf = lgbm.LGBMClassifier(class_weight = 'balanced' ,importance_type = importance_type_LGB)
lgb_clf.fit(train_data_with_NANs,target_train)
predicted_lgb = lgb_clf.predict(train_data_with_NANs)
predict_proba_train_data_lgb = lgb_clf.predict_proba(train_data_with_NANs)
_________________________________________________________________________________

As you wrote class_weight can not be used for binary data???
https://lightgbm.readthedocs.io/en/latest/pythonapi/lightgbm.LGBMClassifier.html
class_weight (dict, 'balanced' or None, optional (default=None)) – Weights associated with classes in the form {class_label: weight}. Use this parameter only for multi-class classification task; for binary classification task you may use is_unbalance or scale_pos_weight parameters. Note, that the usage of all these parameters will result in poor estimates of the individual class probabilities.

**Comment by dtomas1989** [comment]
Did you fix it?

**Comment by Sandy4321** [comment]
Good question, seems to be they do not care at all

**Comment by guolinke** [comment]
@Sandy4321 
'class_weight' is mainly designed for multi-class task, although current code supports to use it for binary classification.

**Comment by Sandy4321** [comment]
thanks
so you need to change user manual to remove confusion from word "only"
Use this parameter only for multi-class classification task;

also
 for binary classification task you may use is_unbalance or scale_pos_weight parameters
if we have 2 labels "green" and "red"
which one will be used for scale_pos_weight ?

**Comment by guolinke** [comment]
@Sandy4321 it depends on which one you set it to positive class (> 0).

**Comment by Sandy4321** [comment]
Can you share full code example
