### ISSUE TITLE
Segfault due to overflowing int with large datasets

### ISSUE THREAD

**Issue by cbecker** [Microsoft/LightGBM#305]
There is at least one overflow issue when using the C api with large datasets. What seems to happen is that int overflows, indexing with negative values, for example at https://github.com/Microsoft/LightGBM/blob/master/src/c_api.cpp#L998

I suspect there are multiple other places where this happens. I will take a look this week at fixing this issue, but this is also a warning against using `int` for indexing. My proposal is to use `size_t` from now on for all loops, and avoid `int`.

**Comment by guolinke** [comment]
@cbecker Thanks. I think using size_t for all loops is not need. 
And omp loop doesn't support size_t either.
The overflows are often caused by the multiplication of two int. 
I think fixing them is enough.

**Comment by guolinke** [comment]
@cbecker any updates?
