### ISSUE TITLE
Unable to replicate regression objective with LGBM_BoosterUpdateOneIterCustom

### ISSUE THREAD

**Issue by parsiad** [microsoft/LightGBM#3052]
LightGBM component: C++ library
LightGBM version or commit hash: v2.3.1

---

Hi LightGBM contributors,

I used `LGBM_BoosterUpdateOneIter` to attain reasonable accuracy for a dataset under the regression objective.

I wanted to try a custom objective so I swapped this function for `LGBM_BoosterUpdateOneIterCustom`. In order to verify that it was working as intended, I **tried to replicate the regression objective** as shown below:

```
// Get current prediction from training data
std::vector<double> yhat(dataset->num_data());
int64_t yhatLen;
LGBM_BoosterGetPredict(boosterHandle, 0, &yhatLen, yhat.data());

// Get labels
const float* y;
data_size_t yLen;
dataset->GetFloatField("label", &yLen, &y);

// Get weights
const float* weights;
data_size_t weightsLen;
dataset->GetFloatField("weight", &weightsLen, &weights);

// Compute grad and hess
std::vector<float> grad(dataset->num_data());
std::vector<float> hess(dataset->num_data());
for (int i = 0; i < dataset->num_data(); ++i)
{
    grad[i] = (yhat[i] - y[i]) * weights[i];
    hess[i] = weights[i];
}

// One iteration
int finished;
LGBM_BoosterUpdateOneIterCustom(boosterHandle, grad.data(), hess.data(), &finished);
```

However, the results I got this way were different. Sometimes this difference was floating point error, but sometimes it was larger. **Have I misunderstood the usage of `LGBM_BoosterUpdateOneIterCustom`?**

Thanks in advance.

**Comment by guolinke** [comment]
we have some tricks for the regression objectives. 
https://github.com/microsoft/LightGBM/blob/master/src/objective/regression_objective.hpp

for example, there is a label transformation in L2 loss, https://github.com/microsoft/LightGBM/blob/05d89a1a1f48a6096e3d2342a517e048d6765bdd/src/objective/regression_objective.hpp#L118

**Comment by parsiad** [comment]
Thanks!
