### ISSUE TITLE
Issue with min_gain_to_split and how to calculate weight as shown in create_tree_digraph

### ISSUE THREAD

**Issue by nirupamkar** [microsoft/LightGBM#3054]
I am seeing the following, when min_gain_to_spilt is specified I can see some splits are created with gain < the value. I created similar issue some time back, could not reproduce the error that time in a dummy data.
```
import pandas as panda
import numpy as numpy
from sklearn.metrics import roc_auc_score,log_loss

np.random.seed(42)
x=pd.DataFrame({"y":[int(np.random.random()>.75) for i in range(100)],
               "x1":[np.round(np.random.random(),1) for i in range(100)],"x2":[np.round(np.random.random(),1) for i in range(100)]})
x["weight"]=1
import lightgbm as lgb

valid_features=["x1","x2"]

lgb_train_data = lgb.Dataset(x[valid_features], label=x.y.values, 
                                  weight=x.weight.values,
                                  free_raw_data=False)
parameters = {
    'num_leaves': 10,
"boosting_type": 'gbdt', 
"objective" : 'binary',
    "min_data":2,
     'min_child_weight': 0,
    "random_state":2,"boost_from_average":False,"min_gain_to_split":0.4
}
print("running ")
model2 = lgb.train(parameters,
lgb_train_data,
num_boost_round=20,valid_names=['train'])

lgb.create_tree_digraph(model2,show_info=['split_gain', 'internal_value', 'internal_count', 'internal_weight',
    'leaf_count', 'leaf_weight', 'data_percentage'],tree_index=7)

```

<img width="900" alt="Screenshot 2020-05-06 at 6 08 17 PM" src="https://user-images.githubusercontent.com/37179907/81177671-af8f7d80-8fc4-11ea-8cb1-a5577f020c6c.png">

I need help in an another issue, how can I can calculate the "weight" as in create_tree_digraph? I understand it is min_child_weight or sum of weighted hessian. However not able to match the same.
I am testing for root node 1 of tree_index=0.

```
x["lpred"]=np.where(x.x1<.15,-0.171,-0.93)
x["pred"]=np.exp(x["lpred"])/(1+np.exp(x["lpred"]))
x["hess"]=2*x["pred"]*(1-x["pred"])*(x["weight"])
print(x[x.x1>.15].hess.sum())
lgb.create_tree_digraph(model2,show_info=['split_gain', 'internal_value', 'internal_count', 'internal_weight',
    'leaf_count', 'leaf_weight', 'data_percentage'],tree_index=0)
```

<img width="909" alt="Screenshot 2020-05-06 at 6 21 06 PM" src="https://user-images.githubusercontent.com/37179907/81178800-63ddd380-8fc6-11ea-93cd-6bf4852ba627.png">

Any help is really appreciated .

**Comment by nirupamkar** [comment]
@guolinke any help is really appreciated

**Comment by guolinke** [comment]
@nirupamkar the `gain` in the tree node already minus the `min_gain_to_split`. 
So as long as it is large than zero, there is no problem. 
refer to https://github.com/microsoft/LightGBM/blob/e50a9151ed0409183bee0dc8272e83b56f1f9e5a/src/treelearner/feature_histogram.hpp#L302

**Comment by guolinke** [comment]
the `internal_weight` and `leaf_weight` are the weighted (if the sample weight is provided) sum of hessians.

**Comment by nirupamkar** [comment]
@guolinke thanks for the reply, the split gain was really troublesome. One has to access model parameters to get the distribution of actual split gain.
For weight calculation I have used the weighted sum of hess. Here the weight was 1, and for binary classification problem the hess is p*(1-p), let me know if I am missing anything.

**Comment by guolinke** [comment]
@nirupamkar thanks, I think we can write the actual split gain to model file.

**Comment by shiyu1994** [comment]
@nirupamkar  Your calculation of weight is inconsistent with weights in the graph due to 
1. You tried to use the hessians after the first iteration (the leaf scores of the tree 0 is used to calculate the hessians), so you should compare your results with the graph of the second tree (tree 1). Hessians used by tree k + 1 is base on the prediction results of previous k trees.
2. It seems that -0.93 is the value of an internal node instead of a leaf. 

For simplicity, here is an example with trees of 2 leaves only (change the 'num_leaves' from 10 to 2 in your code).
<img width="843" alt="weight" src="https://user-images.githubusercontent.com/14541765/85985220-fe81ee00-ba1c-11ea-98c5-e1acaef650ae.png">

**Comment by nirupamkar** [comment]
@shiyu1994 thanks for the explanation. So
1.3.5 weight in 0th trees is nothing but 0.5*(1-0.5)*14
2.My understanding was lgb updates the hessian after all internal spilts as well which is not the case.

**Comment by shiyu1994** [comment]
@nirupamkar hessians are updated using the leaf values after a full tree is grown.
