### ISSUE TITLE
Feature Request & Question: Better Support for Tree Plot with multi class booster.

### ISSUE THREAD

**Issue by PhilipMay** [microsoft/LightGBM#3061]
I have a booster trained for 200 rounds with 401 classes (`'objective': 'multiclass'`). This gives 200 x 401 = 80200 trees. Now I want to plot them with `create_tree_digraph` where I have to provide a `tree_index`.

My first issue is that I do not know which index is which tree. Is index 1 the first class of 2nd boosting round or the 2nd class of the first boosting round? This maybe should either be made explicit or at least documented.

The 2nd issue is that the tree-diagram should baybe plot the class it predicts. Could this be added as a new feature?

**Comment by guolinke** [comment]
For your question, yeah, the tree is ordered by class first, then iteration. 
for example, for the i-th iteration, and j-th class, its tree index is `i * K +j`, where `K` is the number of total classes.

**Comment by guolinke** [comment]
Closed in favor of being in #2302. We decided to keep all feature requests in one place.

Welcome to contribute to this feature! Please re-open this issue (or post a comment if you are not a topic starter) if you are actively working on implementing this feature.
