### ISSUE TITLE
Adding real feature names to `create_tree_digraph` and `plot_tree`.

### ISSUE THREAD

**Issue by PhilipMay** [microsoft/LightGBM#3062]
When using  `create_tree_digraph` and `plot_tree` the features are named like `Column_21`. I would like to add a string list that maps `Column_0` to the string at index `0` and so on. This way the real features are displayed in the plot instead of just numbers.

**Comment by kidotaka** [comment]
In my experience with lightgbm 2.3.0, real feature names are displayed using plot_tree.

plot_tree and create_tree_diagram just display feature names via booster.dump_model().

I think that your model don't have real feature names.

In dataset construction time,
"Column_ + i" is used if there are no available feature names.

https://github.com/microsoft/LightGBM/blob/6f339d77a1bb9d16086a85439f68b4b9b74fe012/src/io/dataset_loader.cpp#L874

How do you create a dataset?

If you instantiate Dataset with pandas.DataFrame and feature_name='auto'(default), real feature names will be displayed.

if you don't use pandas.DataFrame, you can specify feature_name=list of strings.

**Comment by guolinke** [comment]
Thank you @kidotaka .
@PhilipMay Does that meet your request?

**Comment by StrikerRUS** [comment]
Yeah, plotting module has been showing real feature names for a long time.
```
import lightgbm as lgb

from sklearn.datasets import load_boston

X, y = load_boston(return_X_y=True)
lgb_data = lgb.Dataset(X, y, feature_name=[f"my_feature_{i}" for i in range(X.shape[1])])

est = lgb.train(params={'objective': 'l1'}, train_set=lgb_data, num_boost_round=5)
lgb.create_tree_digraph(est, orientation='vertical')
```

Script above produces the following image

![image](https://user-images.githubusercontent.com/25141164/104383154-7094cd00-5540-11eb-8aec-4e405ee1ad1c.png)
