### ISSUE TITLE
Segmentation fault if df.shape[1] == 0 (no columns)

### ISSUE THREAD

**Issue by kuraga** [Microsoft/LightGBM#307]
## Version

https://github.com/Microsoft/LightGBM/tree/ea6bc0a5ba80195fc214495ade8c4bdff532535a

## Environment info

Operating System: Gentoo Linux
CPU: Intel Core i7
C++/Python/R version: GCC 4.9.4, Python 3.4.5, Pandas 0.19.2

## Error Message:

Segmentation fault

## Steps to reproduce

Construct data next way:

```python
df_train = pd.read_csv('../regression/regression.train', header=None, sep='\t')
df_test = pd.read_csv('../regression/regression.test', header=None, sep='\t')
y_train = df_train[0]
y_test = df_test[0]
X_train = df_train.drop(df_train.columns, axis=1)
X_test = df_test.drop(df_train.columns, axis=1)
```

(train data has 0 columns). I don't know if Scikit Learn is important.

**Comment by guolinke** [comment]
you want to train with no columns ?
@wxchan  can you add some checks for this ?

**Comment by wxchan** [comment]
No errors shown on my machine, with latest version.

**Comment by kuraga** [comment]
@guolinke sure I got this situation while applying a wrong condition on dataset.

See #317 , please.

**Comment by wxchan** [comment]
it seems already fixed in master branch, no such error on my machine, try to merge into master in #317 . btw, why would you like to train with no columns anyway?

**Comment by guolinke** [comment]
@wxchan The travis test of #317 failed.

**Comment by wxchan** [comment]
@guolinke it's merged into v1 branch, I try this test case with master branch, seem no error.

**Comment by kuraga** [comment]
> it's merged into v1 branch

Is v1 branch maintainable, isn't?

> why would you like to train with no columns anyway?

As I said above, this situation is accident. But we have a __segmentation fault__ not just an exception - so does it matter, did I want to do this or not?..

**Comment by guolinke** [comment]
@kuraga 
v1 is a release of previous commits. It will not be updated any more. (or we will not call it a release)
And the bug in v1 will be fixed in v2.

**Comment by kuraga** [comment]
Ok, sorry. Seems like it's ok on master. Thanks.
