### ISSUE TITLE
[R-package] Remove lgb.prepare() and lgb.prepare_rules()

### ISSUE THREAD

**Issue by jameslamb** [microsoft/LightGBM#3075]
The R package currently has 4 functions for converting non-numeric inputs to numeric values for use with LightGBM training:

* `lgb.prepare()` ([docs](https://lightgbm.readthedocs.io/en/latest/R/reference/lgb.prepare.html))
* `lgb.prepare2()` ([docs](https://lightgbm.readthedocs.io/en/latest/R/reference/lgb.prepare2.html))

* `lgb.prepare_rules()` ([docs](https://lightgbm.readthedocs.io/en/latest/R/reference/lgb.prepare_rules.html))
* `lgb.prepare_rules2()` ([docs](https://lightgbm.readthedocs.io/en/latest/R/reference/lgb.prepare_rules2.html))

The `*2()` versions of these functions accomplish everything that their predecessors do, and in a better way. I think that `lgb.prepare()` and `lgb.prepare_rules()` should be deprecated in the next 2.x release, and that they should be removed completely in 3.0.0.

This will simplify the interface of the R package for users and reduce the maintenance burden for maintainers.

@Laurae2 @guolinke what do you think?

**Comment by jameslamb** [comment]
Just put this in #2302 . Will close it once I hear from the maintainers tagged in the description about whether this is a good idea.

**Comment by Laurae2** [comment]
@jameslamb as LightGBM does not crash anymore when using an R integer matrix, we can deprecate the non `*2()` versions.

**Comment by jameslamb** [comment]
@Laurae2 ok thanks! I'll open a PR with a deprecation warning, and then when we do 3.0.0 (#3071 ) we can remove them

**Comment by jameslamb** [comment]
Closing for now since we've agreed on direction. This issue is in #2302 with other features.
