### ISSUE TITLE
feature_fraction_bynode does not work

### ISSUE THREAD

**Issue by zcyang** [microsoft/LightGBM#3082]
I am using python version of lightgbm 2.2.3 and found 
```
feature_fraction_bynode
```
 does not seem to work. The results are the same no matter what value I set.

I only checked the  boosting```gbdt``` mode. Does it support random forest ```rf``` mode?

**Comment by StrikerRUS** [comment]
`feature_fraction_bynode` was added in `2.3.0` version (PR #2330). Please update your version of LightGBM.
