### ISSUE TITLE
[R-package] [ci] MacOS Travis builds timing out

### ISSUE THREAD

**Issue by jameslamb** [microsoft/LightGBM#3091]
See the conversation starting at https://github.com/microsoft/LightGBM/pull/3086#issuecomment-629481888. Currently, MacOS `r-package` builds on Travis are failing with an error like this:

> * checking whether package ‘lightgbm’ can be installed ...

> No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.

In this case, "no output" means "nothing written to the log".

It seems that our build times for the R package on Mac were already very close to 10 minutes but just under this. It's possible the issue is caused by one or some combination of these:

* maybe installation of the R package got slightly slower
* maybe something about the Travis Mac environment is slowing us down (for example, slower disk I/O)
* maybe changing `print()` (which prints to `stdout`) to `message()` (which prints to stderr) in #2965 is extending the time between logs to stdout

Some possible fixes for this, found by @StrikerRUS 

* https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received
* travis-ci/travis-ci#4190 (comment)

**Comment by jameslamb** [comment]
I did also try using `processx::run()` on Mac builds...that didn't have a meaningful impact on build times (the way it did for Windows in #2965 )

**Comment by StrikerRUS** [comment]
Interestingly, Azure build hasn't been affected: same ~7min.
