### ISSUE TITLE
Training was stuck when use 'goss' with the latest version 2.3.2

### ISSUE THREAD

**Issue by shaoguang123** [microsoft/LightGBM#3093]
## How you are using LightGBM?

LightGBM component: **Python package**

## Environment info

Operating System: **Windows**

CPU/GPU model: **CPU**

Other:

LightGBM version or commit hash:  The latest master branch downloaded on 16 May 2020.

## The parameters：
`model = LGBMRegressor(max_depth=10, learning_rate=0.01, n_estimators=1000, num_leaves=250,min_child_samples=200, colsample_bytree=0.2, boosting_type="goss", top_rate=0.9, other_rate=0.07, random_state=0, n_jobs=50)`

## Data info:
the dataset is about 1300000 samples and 3500 features

## Problem description

When I used "goss" with the latest version download from the master branch, since my learning_rate=0.01, training was stuck in the 101st iteration。

When I track the code, I found that It is stuck here https://github.com/microsoft/LightGBM/blob/5cc38e6aa363e6d04a62bcc5e36ea04ca36e917f/src/io/tree.cpp#L185

BTW, when I change the parameter other_rate from 0.07 into 0.05, it seems that this problem doesn't happen any more.

**Comment by guolinke** [comment]
@shaoguang123 could you provide a reproduce example?

**Comment by shaoguang123** [comment]
> @shaoguang123 could you provide a reproduce example?

Actually, this problem doesn't happen very often. Like the example above，when I use n_jobs=40, the problem maybe disappear.
In order to work out it easier for us, I will use some small dataset and try to reproduce this problem.
I'll let you know as soon as I make progress.@guolinke
