### ISSUE TITLE
[Feature] PMML support

### ISSUE THREAD

**Issue by damienrj** [Microsoft/LightGBM#31]
Being able to save the model in PMML format would be great (https://github.com/jpmml). Would make it easy to move LightGBM models into production.

**Comment by guolinke** [comment]
Model file of LightGBM is simple and readable. I think it is easy to write an parser to do this.

**Comment by rmhasan** [comment]
Hi I would like to work on this.

**Comment by guolinke** [comment]
@rmhasan Welcome and thanks very much.

**Comment by rmhasan** [comment]
Hi Can you explain what is in LightGBM_model.txt? I included a snippet of one tree.  It has 10 lines. The first two lines are self explanatory. The last 8 have a field name followed by an equal sign followed by an array of numbers. Can you explain the meaning of each field and the significance of the array of values following the field.

![screenshot from 2016-11-21 00-43-27](https://cloud.githubusercontent.com/assets/3707038/20471976/e757d4ee-af83-11e6-91b5-0f2b494db004.png)

**Comment by guolinke** [comment]
Sure, you can take a look at here: https://github.com/Microsoft/LightGBM/blob/master/src/io/tree.cpp#L42-L76.

``split_feature[i]`` means the feature used to split data at i-th node (note: node means non-leaf node).
``threshold[i]`` means the threshold used to split data at i-th node.
``left_child[i]`` means the index of i-th node's left child. ``>=0`` means non-leaf node. `<0` means leaf , and you can use ``~`` operation to get the index of leaf.
``right_child[i]`` like ``left_child[i]``
``leaf_parent[i]`` means the node index of i-th leaf`s parent. 
``leaf_value[i]`` means the prediction value of i-th leaf.
``internal_value[i]`` means the prediction value of i-th node.

**Comment by rmhasan** [comment]
Hi @guolinke , so the features used are continuous features? And each number in the split_feature array is the split point correct? Can you explain how the values in threshold affect the splitting at each node. Thanks.

**Comment by guolinke** [comment]
split point is {feature_idx(feature), threshold}. 
rule:
```
if(data.feature[feature_idx].value <= threshold){
  move to left node
} else {
  move to right node
}
```

**Comment by rmhasan** [comment]
Okay so in the image I uploaded up top, I see that split_feature contains integers, and threshold contain doubles. Also the numbers in split_feature are substantially larger then the numbers in threshold. So I believe that the numbers in split_feature are actually the indexes in the data.feature array. Is this correct?
Also what is the difference between split_feature_ and split_feature_real_ arrays that are in the code snippet you directed me to.

**Comment by guolinke** [comment]
both '''split_feature_''' and '''split_feature_real_ ''' stores index of feature, so it is integers.
The difference is ```split_feature_real_``` is the '''real''' feature index in dataset, and LightGBM only save this to model file: https://github.com/Microsoft/LightGBM/blob/master/src/io/tree.cpp#L108-L109 . I think you should use this as well.

```split_feature_``` is used inner for training. The reason is LightGBM will ignore some features in the dataset. So it use ```fake``` feature index to access used feature indices.

**Comment by rmhasan** [comment]
The first number in the left_child array, that is the index of the left child of the root node correct? I am working on writing an example pmml for a tree. When I am done I will ask for feedback.

**Comment by rmhasan** [comment]
Hi all please take a look at the [Pmml output](https://github.com/rmhasan/LightGBM/blob/master/examples/binary_classification/pmmlexample.txt) I got for a tree snippet from LightGBM_model.txt
Also look at the [tree example](http://dmg.org/pmml/pmml_examples/KNIME_PMML_4.1_Examples/single_audit_dectree.xml) from dmg.org for reference. Here is also [another example](http://dmg.org/pmml/pmml_examples/KNIME_PMML_4.1_Examples/single_iris_dectree.xml) from the site. However these are both examples of discrete decision trees. I will try to find an example of a continous one. I got the structure of the tree. However there are some parts I couldn't fill in. In place of values I left `...` instead. Could you take a look at my output and give me some guidance. Also how do you want me to handle all the trees in LightGBM_model.txt. Do you want me to print them one after the other in one file or print them to their own files?

**Comment by guolinke** [comment]
@rmhasan 
1. yes, ```0``` means root node.  
2. I think ```DataDictionary numberOfFields``` use to record the feature names and its value range.
I have no idea what ```<MiningSchema>``` is.
```score``` maybe the prediction of this node
```recordCount``` maybe the number of data in this node
```ScoreDistribution ``` maybe the probability of classification, I think we don't need this in regression.
And I think the ```field``` in ```SimplePredicate``` should be feature name, not ```split_feature```

Here is some resources may can help:

https://groups.google.com/forum/#!topic/jpmml/Z_3OCzF1qxQ
http://dmg.org/pmml/v1-1/treemodel.html

**Comment by rmhasan** [comment]
@guolinke Do you know where I can get the feature name? Is it stored somewhere?

**Comment by rmhasan** [comment]
@guolinke  Also are the prediction values of each node stored in the internal_value and leaf_value arrays.

**Comment by rmhasan** [comment]
@guolinke  Im looking at the SplitInfo class, it has  left_count and right_count fields. I think I can use those values for `recordCount`.

**Comment by guolinke** [comment]
@rmhasan , I can save feature name to model. 
internal_value is the prediction of non-leaf nodes, and leaf_value is the prediction of leaf node.
I also can save the count into model file.

Is there other data you need in model file?

**Comment by rmhasan** [comment]
@guolinke That sounds great. Nothing comes to mind now. If I need something Ill let you know. Thanks.

**Comment by guolinke** [comment]
@rmhasan I have put the feature name and data count into model file.
BTW, I add other field ```decision_type```.
When ```decision_type==0```, it means ```<=threshold``` is in left child, and ```>threshold``` is in right child. (numerical feature)
When ```decision_type==1```, it means ```==threshold``` is in left child, and ```!=threshold``` is in right child.(categorical feature)

**Comment by rmhasan** [comment]
Thanks. I will make some progress this week, and report back.

**Comment by rmhasan** [comment]
Hi @guolinke, so I was able to make some progress and filled in almost all the missing parts except for the miningschema part. I will do more research on that one. Please take a look at  [my pmml output](https://github.com/rmhasan/LightGBM/blob/master/examples/binary_classification/pmmlexample.txt) once again. So I was looking through this thread. In your first comment you talked about implementing a parser. So do you want me to implement a separate program that parses the LightGBM_model.txt or do you want me to add a function to the LightGBM program and a cmd line option to print out the pmml text. Also there are multiple trees in each LightGBM_model.txt file. Do you want me to output a pmml for each tree to it's own file  or put all the pmml's for each tree in one file?

**Comment by guolinke** [comment]
@rmhasan 

Add some references:
https://github.com/dmlc/xgboost/issues/839
https://github.com/jpmml/jpmml-xgboost

I think using an independent parser is better, maybe python or other easy-to-use implementations is better. 

I am not sure how PMML works, e.g. Does it support load multi tree models from one file? 
If yes, I think one file is better. If not, we only can output multi files.

**Comment by rmhasan** [comment]
@guolinke  I can do python. I will take a look at the links you gave me. Thanks.

**Comment by Alexkevin** [comment]
just want to know how is this progress going?  I can't wait to try it

**Comment by rmhasan** [comment]
Hi @Alexkevin, there is progress. I am producing pmml output. I am following the [schema for the tree model](http://dmg.org/pmml/v4-3/TreeModel.html) to produce a valid pmml document. The main part which is the tree structure is there.  You can pull my code, run it and take a look at the pmml output. The script is the pmml.py file in the pmml directory. First you need to create a LightGBM_model.txt file. You can create one by running the lightgbm executable on an example in the examples directory. Then you can run the script on the LightGBM_model.txt file.

**Comment by rmhasan** [comment]
Hi @guolinke, I have a script that translates each tree in the LightsGBM_model.txt file into a pmml output file. All the files get placed inside a directory called pmml_out. The pmml output can pass a validation check with it's schema. More information on the standard of pmml and the xsd schema I am outputting can be found  [here](http://dmg.org/pmml/pmml-v4-3.html). Feel free to clone my repo and run the pmml.py script in my pmml subdirectory. Please provide any feed back including any other additions or changes you want me to make. If you are satisfied, then I can make a pull request.

**Comment by guolinke** [comment]
@rmhasan , you can create PR first. If there are any problems, we can solve them together. 
Thanks!

**Comment by rmhasan** [comment]
Hi @guolinke, can you explain what is in LightGBM_predict_result.txt after running ./lightgbm config=predict.conf in one the examples, lets say binary_classification. Is it all scores? And can you explain what lightgbm in predict mode does with all the trees in LightGBM_model.txt.

**Comment by guolinke** [comment]
@rmhasan ,
For binary classification, the output is the probability of positive class. It is transformed from raw scores by sigmoid.
For other tasks, the output is raw score, and raw score is the sum on all tree's scores.

**Comment by rmhasan** [comment]
@guolinke Hi so you are taking the raw score and multiplying it by the sigmoid to get the output.

**Comment by rmhasan** [comment]
@guolinke Should I multiply the values in the leaf_value array and internal_value array for each node by the sigmoid value to get the score for each node.

**Comment by guolinke** [comment]
I think you don't need to do this. just raw score is fine

**Comment by rmhasan** [comment]
Hi Happy New Year to all. @guolinke the pmml output can be consumed by the jpmml-evaluator. I am ready to do a pull request. First I am going to right a detailed README the pmml.py script.

**Comment by vruusmann** [comment]
As an author or JPMML-Evaluator, I've been watching the progress on this issue with great interest. These are my observations so far:

- The PMML exporter should encode LightGBM model as a single segmentation-type [``MiningModel`` element](http://dmg.org/pmml/v4-3/MultipleModels.html), not a series of ``TreeModel`` elements (as implemented in PR #153).
- Features need to have correct type specifications, otherwise there will be a mismatch between LightGBM "native" predictions and PMML predictions. The case in point is the data type of continuous features. If LightGBM uses 32-bit FP data type internally, then `DataField` elements must specify `dataType="float"`, not `dataType="double"`. Also, the PMML exporter doesn't seem to know about categorical features yet.
- Using a text file for model data migration could be problematic. Currently, I'm concerned that the text file uses arbitrary precision for printing FP values. Printed values should conform to IEEE 754 specification, for example as implemented in Java by `Float#toString()` and `Double#toString()` methods. Again, this is needed to ensure the consistency of LightGBM and PMML predictions, especially where the workflow uses derived continuous features. I assume that LightGBM determines split points with <0.5 ULP predicsion, which must be "supported" by the text file.

The last point is the most important one. I would seriously consider creating my own LightGBM-to-PMML exporter library in Java. However, currently it cannot be done, because there is no way of extracting "untampered" data from LightGBM model objects (a missing converter is better than a one that produces incorrect/irreproducible models).

**Comment by guolinke** [comment]
Hi @vruusmann , Thanks for your comments.
1. @rmhasan , I think you can use MiningModelelement. 
2. I changed to double precision for float type data in recent update:  https://github.com/Microsoft/LightGBM/commit/1d7acf57ce461443bf510dd49b36fd2a5687f099
however, it seems still have lost on precision: http://stackoverflow.com/questions/4738768/printing-double-without-losing-precision. I am not sure this is ok or not. Do I need to output binary model to ensure precision ?
3. I am not familiar with pmml, So I not understand about ``` I assume that LightGBM determines split points with <0.5 ULP predicsion, which must be "supported" by the text file.```  ? Can you give more details about this ?
4. ```there is no way of extracting "untampered" data from LightGBM model objects``` ?  why ? 
Thanks!

**Comment by rmhasan** [comment]
@guolinke and @vruusmann  I will work on the `MiningModel` element. Also might I suggest using 17 as the decimal precision.  Here is a [link](http://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html) to a proof of why you would get lossless decimal recovery from text.

**Comment by vruusmann** [comment]
@rmhasan The upgrade to `MiningModel` element should be trivial:

Now:
```
<PMML>
  <TreeModel>
    <Node>..</Node>
  </TreeModel>
</PMML>
```

Then:
```
<PMML>
  <MiningModel>
    <Segmentation multipleModelMethod="sum">
      <Segment id="1">
        <True/>
        <TreeModel>..</TreeModel>
      </Segment>
      <Segment id="2">
        <True/>
        <TreeModel>..</TreeModel>
      </Segment>
      ..
      <Segment id="n">
        <True/>
        <TreeModel>..</TreeModel>
      </Segment>
    </Segmentation>
  </MiningModel>
</PMML>
```

**Comment by vruusmann** [comment]
> suggest using 17 as the decimal precision.

The suggested precision will be good for FP64 values whose magnitude is close to `1`. However, it may prove to be too little or too much for FP64 values that are much greater or much smaller, respectively, than `1` (eg. `1.234567+E10` and `1.234567E-10`).

C++ is a very mature language/ecosystem, so it should provide built-in utilities for formatting/parsing FP32 and FP64 values using "correct, dynamically chosen" precision. This SO question seems like a good lead: http://stackoverflow.com/questions/7197589/c-what-is-the-printf-format-spec-for-float

> LightGBM determines split points with <0.5 ULP predicsion

"ULP" refers to the "Unit in the Last Place": https://en.wikipedia.org/wiki/Unit_in_the_last_place

I can see that LightGBM encodes numeric split thresholds using FP64 values:
https://github.com/Microsoft/LightGBM/blob/master/include/LightGBM/tree.h#L180

So, the text file should contain `threshold_` values that are produced using printf's `%g` pattern. 

> Do I need to output binary model to ensure precision?

The current text file format will be perfectly fine if FP32 and FP64 values are printed according to the IEEE 754 specification.

At the moment this condition is not satisfied. By specifying `digits10 + 1` (in https://github.com/Microsoft/LightGBM/commit/1d7acf57ce461443bf510dd49b36fd2a5687f099), you're printing FP32 values with too much precision, and FP64 values with not enough precision.

Also, as briefly discussed in PR #151, you need to achieve a situation where the original Booster object, and its serialized/deserialized clone, contain exactly the same state, and produce exactly the same predictions. If you don't have this level of "reproducibility" within LightGBM, then it cannot be achieved between LightGBM and PMML either.

**Comment by guolinke** [comment]
@vruusmann 

actually, the output precision of ```std::numeric_limits<double>::digits10 + 1``` is enough for double precision. 
Check: http://stackoverflow.com/questions/554063/how-do-i-print-a-double-value-with-full-precision-using-cout
And I think it is better than C's ```printf with %g```

I also try some tests:
```
  double d = 3.14159265358979e-30;
  std::cout << std::setprecision(std::numeric_limits<double>::digits10 + 1);
  std::cout << "Pi: " << d << std::endl;
```
and it outputs ```3.14159265358979e-30```

Or you means to output hex code of FP64?


The string in model file is the serialized of Booster, and Booster can construct from string in model as well:

https://github.com/Microsoft/LightGBM/blob/master/include/LightGBM/boosting.h#L147
https://github.com/Microsoft/LightGBM/blob/master/include/LightGBM/boosting.h#L153

And I also can add the binary format serialized/deserialized clone if it is really need.

**Comment by vruusmann** [comment]
@guolinke Sorry about giving bad advice - I'm not familiar with C++ language/libraries/way of thinking.

Anyway, I got the impression that there's still something not quite right with Booster persistence. Specifically, if an Booster object is serialized into a text file, and then de-serialized into a new Booster object, then these two Boosters have different internal state (eg. perhaps their `threshold_` arrays are not equal if compared element-by-element), and/or different behaviour (eg. perhaps their predictions differ on the 7th decimal place).

If you can assure me that Booster persistence is correct, then I can start experimenting with my own Java-based LightGBM-to-PMML conversion library.

**Comment by guolinke** [comment]
@vruusmann It indeed existed some precision problem, but I fix it recently.
I also add test for it:
https://github.com/Microsoft/LightGBM/blob/master/tests/python_package_test/test_basic.py#L41-L46
its differ is on 16th decimal place now.

Do you think it is ok or not?

**Comment by vruusmann** [comment]
@guolinke Very nice, we're getting closer and closer to the destination.

Would it be possible to ensure that the values are identical? In other words, the test should use method like `assertExactlyEqual(double[] values, double[] serDeValues)` instead of `assertAlmostEqual(values, serDeValues, double tolerance)`?

In Java, the following test would pass cleanly:
```
double value = ...;
String fp64String = java.lang.Double.toString(value);
double serDeValue = java.lang.Double.valueOf(fp64String);
assertEqual(value, serDeValue); // Also, could do assertTrue(value == serDeValue)
```

**Comment by guolinke** [comment]
@vruusmann 
Now it is exact same: https://github.com/Microsoft/LightGBM/blob/master/tests/python_package_test/test_basic.py#L46-L50

I also test this in cpp:
```
  for (int _ = 0; _ < 100000; ++_) {
    double a = std::rand() * 1.234 * 3.14159265358979121231212e-100;
    std::stringstream str_buf;
    str_buf << std::setprecision(std::numeric_limits<double>::digits10 + 2);
    str_buf << a;
    double b = std::stod(str_buf.str().c_str());
    if (a != b) {
      printf("Failed\n"); // never met
    }
  }
```

**Comment by areshand** [comment]
seems the parser is broken.  The default values in the tree file cannot be parsed. The tree I was trying to parse is 
```
Tree=0
num_leaves=70
split_feature=6 78 78 59 40 52 40 59 52 6 40 5 74 52 58 58 40 33 6 53 74 58 56 58 56 6 59 56 74 52 58 62 8 40 52 8 59 40 61 56 59 61 78 54 59 67 59 59 55 5 6 65 54 8 52 59 58 0 59 61 56 52 58 56 8 59 40 40 74
split_gain=17202.528011494174 15226.695121565121 11570.586610459039 10887.393271292472 6786.6131547834884 6589.9272440091736 5265.9410258235221 5757.878348019527 6071.9507602927333 3363.657477458848 3114.1307863717907 2996.4003973238382 2567.1081804125561 2237.9515736410353 2230.548364784052 1891.8741171404108 1572.0106361343489 1565.0096036939212 1332.9658364041657 1285.9914270246081 1261.1499435463004 1222.0563182844489 1208.2443915636131 1290.903619189686 1059.7585873898825 964.77739047159162 946.10398783742846 859.84917479574369 851.42346351403103 819.48699082308428 817.34309663927775 798.67646205767755 762.81828666541617 757.12476710424949 742.3765068567111 708.76441279860796 667.63286885920138 623.70385214012913 619.81609947129425 618.67201262123035 587.62219986732998 586.58406208489214 572.17545665440457 571.99226513960457 541.23477522854148 474.01627354753873 471.36420082477889 429.76878203889169 422.72703175194079 410.04040175711498 405.90752990704596 400.83207191445285 400.71843408362474 388.56902979896358 387.33831133320103 380.66307078404157 371.19031415491736 362.57336806354851 362.52908713385841 361.34718991535169 356.46131950525739 352.03417596869667 344.58227638471851 333.89930656294359 329.32004299785729 418.29014592169983 314.51740252293786 307.88054954355539 303.85487914621524
threshold=-0.017972807437100002 0.75 0.75 0.030509136246149995 0.11270936500000001 0.16793171238900001 -0.10723451200000003 -0.03749083467455 -0.168889708262 -0.19690227686050002 -0.053431485000000001 0.19545638870500004 0.030981777209599999 -0.13272968833500004 0.069640811612550008 0.16254599833700001 0.068877815000000009 -0.0058141946899999998 0.18981002012100001 0.25465964475699998 -0.070665486984350032 -0.2828203568935001 0.051047038168949996 -0.062127608868150011 0.0030374306170949999 -0.22935349936900001 -0.048301030445400003 0.0095966908724400002 0.15416285331100005 -0.15247148827750001 0.47014406069050002 -0.10154068610850001 0.046261716109399997 0.31673815499999991 0.12088851189450002 -1.6251280205450001 0.10134312542600001 -0.34194445949999996 0.065640205497400003 -0.0081880207142500001 0.13433647869900001 -0.017287503461149999 0.41666666666649999 0.17274290703300005 -0.026167698664750001 3.1249929999999999 -0.13701884556550004 0.14735527772500001 0.39504867998750004 0.27083097033600012 -0.31366503371850002 -0.027825724999999999 -0.26704172775350005 0.077885155939100031 -0.66043742726699972 -0.1476209495345 0.36170462571850004 -0.099999950000000004 0.15007291920250002 -0.0048747067867249997 0.033030163056650005 0.52996177796450006 -0.049657403073750009 -0.16105972537150001 -0.12371232842150003 -0.14236373836300004 0.40720149999999999 0.037675825000000003 -0.054327052803400007
decision_type=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
default_value=0 0 0 -0.99846858649549985 -0.7655239949999999 -0.99998653041649999 0 -0.99846858649549985 0 -0.48738610423400014 0 -0.4886973180075001 1.7976931348623157e+308 0 1.7976931348623157e+308 -2.5967602336149995 -0.7655239949999999 0 1.7976931348623157e+308 -0.95921276745400008 -0.53933921632400006 0 -0.53384013140950004 -2.5967602336149995 -0.53384013140950004 -0.48738610423400014 -0.99846858649549985 1.7976931348623157e+308 -0.53933921632400006 0 1.7976931348623157e+308 -0.50579519840600007 -1.6251280205450001 -0.7655239949999999 -0.99998653041649999 -1.6251280205450001 -0.99846858649549985 -0.7655239949999999 -0.49979810024900007 -0.53384013140950004 -0.99846858649549985 -0.49979810024900007 0 -0.71884014336599988 0 -45.441758 -0.99846858649549985 -0.99846858649549985 -0.64139191763299985 1.7976931348623157e+308 -0.48738610423400014 0 0 -1.6251280205450001 -0.99998653041649999 0 -2.5967602336149995 -4.9888890000000004 -0.99846858649549985 -0.49979810024900007 -0.53384013140950004 -0.99998653041649999 0 -0.53384013140950004 0 0 -0.7655239949999999 -0.7655239949999999 -0.53933921632400006
left_child=1 20 12 10 5 15 9 8 25 50 41 30 35 -12 27 24 26 -10 61 43 42 52 23 29 -5 -8 32 44 47 -9 -6 37 38 -32 56 -2 51 -11 64 46 62 -4 57 45 -15 58 -23 -14 66 -30 -3 -31 -19 -18 -27 -44 60 -1 67 -24 -28 -7 -26 -33 -16 -66 -13 -17 -37
right_child=2 6 3 4 11 18 7 22 17 31 13 48 28 14 16 19 53 21 -20 -21 -22 39 59 -25 40 54 34 -29 49 36 33 63 -34 -35 -36 68 -38 -39 -40 -41 -42 -43 55 -45 -46 -47 -48 -49 -50 -51 -52 -53 -54 -55 -56 -57 -58 -59 -60 -61 -62 -63 -64 -65 65 -67 -68 -69 -70
leaf_parent=57 35 50 41 24 30 61 25 29 17 37 13 66 47 44 64 67 53 52 18 19 20 46 59 23 62 54 60 27 49 51 33 63 32 33 34 68 36 37 38 39 40 41 55 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 65 65 66 67 68
leaf_value=-0.018080040879845771 -0.0016796278316640366 -0.090408921933085515 0.027363864205969469 0.077713815789473686 -0.052492668621700878 -0.0090586145648312612 -0.053130929791271347 0.055987558320373255 0.016637478108581436 0.036875439831104855 0.064010786957587648 0.061868078960038521 0.0073717138295489844 -0.039935721937864543 -0.057714285714285718 0.081978047238664448 -0.064062889942600454 -0.025567010309278351 0.044780927835051554 -0.0047268262737876002 -0.00029934735929087471 -0.067840948726892225 -0.079178082191780824 0.028178740690589035 -0.017619047619047621 0.049179331306990884 0.040626738364546638 -0.068362410203782434 0.011992890617795253 0.012107023411371237 0.026678672498070495 0.080498469610843906 0.039945238819592332 -0.036590662323561347 -0.051040634291377611 -0.022968139089925965 0.010530482977038798 -0.025185972369819343 0.033144475920679893 -0.0846542469213767 0.056429829712272464 0.077291543465405094 0.00030979199680214713 0.029961089494163425 0.0021684737281067556 0.034850299401197604 -0.029350867375489649 -0.00036165061047859463 0.090824915824915822 0.026174114585451148 -0.037265068049254696 -0.04269852763697804 -0.090538563680147649 0.013290322580645162 0.0037359614943845982 -0.0098879599316542555 0.064458804523424881 -0.0085827972677233241 0.095367314509228696 -0.030498945888966972 -0.0049741345005968962 -0.052479041916167674 0.027289860535243123 0.035877862595419849 -0.052299829642248719 -0.0049846961084390037 0.0021526418786692761 0.037210682492581602 -0.0033341860663426283
leaf_count=86106 316201 2690 4389 7296 6479 3378 2108 1286 1713 2842 4079 2077 276842 8401 2100 17401 4007 970 3104 1629 283617 5734 3285 7385 2520 3290 5393 6821 119279 1495 3887 2287 3287 3684 1009 24042 3789 3764 2471 6334 5109 5073 70047 1799 4796 1670 7148 97055 2376 24593 3086 12429 44433 775 4363 76669 3714 75395 32724 2846 2513 4175 5306 6288 2348 9148 1533 1685 11727
internal_value=0 -0.23818441666816839 0.16312512226892961 0.62747255214531084 1.0267453075153943 1.2664358285115496 -0.85919808590282865 -1.0363140836770772 -1.3373372057876545 0.058691606623085368 0.015243729025652693 -0.023557596326612099 0.068008908419652334 -0.15070158719726595 -0.25349136185125831 1.4700994308974709 0.039004487964096286 -1.5540613881686065 -0.20775077413906354 1.6568496520700078 -0.10223136893115299 -1.6040792955632244 -0.33184683992003688 -0.14599757428744695 0.9447877020414216 0.13543694293617456 0.19891817528061784 -0.79068838045758816 0.15759537554392017 -0.4218116742986473 -0.52839857651245548 0.55292800210789805 -0.07895008783713961 -0.082155593712851666 0.6247525536463695 -0.063778162911611785 -0.5337322870208322 0.030275507114744173 -0.25854235389307278 -1.1813072439633638 0.60100502512562815 1.0826463749735786 -0.19079414827864782 1.7084607174514734 -0.49268773206031674 1.7457741211667914 -0.92966930600838382 0.10728623123480531 1.1613765452723019 0.28833963523131673 -1.2403047091412742 -0.73628267739155417 -1.7830099332643217 -1.0305311585110832 0.46543839017378807 -0.10038441615093105 0.76764199655765919 -0.27292710261855962 1.7795792318085313 -1.1316261621268962 0.52264103212749813 -0.66119422745928769 0.25658062867365194 0.9555685131195335 -0.42600764930862017 -0.29297146833681281 0.73019390581717447 1.5605155611442942 -0.33062148788056694
internal_count=1769294 721399 1047895 178156 107832 87796 129565 108608 76093 20957 70324 20036 869739 60862 56783 77139 36765 66332 10657 56908 591834 64619 32515 26384 20231 9761 31983 20018 517769 18999 14050 15181 19354 7571 12629 351970 17713 6606 16067 19216 12935 9462 308217 55279 13197 53480 12882 373897 5986 143872 5776 13924 45403 4782 7653 146716 11620 161501 51810 6131 7906 7553 7826 8575 13596 11496 3610 19086 35769
shrinkage=0.05
has_categorical=0
```

**Comment by qrqpjxq** [comment]
hi, @rmhasan @guolinke type of LightGBM_model.txt has been changed? when i use pmml.py to change model to pmml type, there's some error raised. if you have time to have a see? 

error:
Traceback (most recent call last):
  File "pmml.py", line 134, in <module>
    decision_type = get_array_ints(next(model_content))
  File "pmml.py", line 20, in get_array_ints
    return [int(token) for token in get_array_strings(line)]
ValueError: invalid literal for int() with base 10: '8.5'
