### ISSUE TITLE
[BUG]Does LightGBM support non-ASCII characters NOT THE FEATURE NAME 

### ISSUE THREAD

**Issue by STHSF** [microsoft/LightGBM#3102]
When using non-ASCII characters in the features it rase `LightGBMError: Do not support non-ASCII characters in feature name.`
The features as:
![image](https://user-images.githubusercontent.com/8037442/82302031-a69ea300-99eb-11ea-990b-0b123f9e60d0.png)

and the error as:
![image](https://user-images.githubusercontent.com/8037442/82302096-b918dc80-99eb-11ea-8748-f7853ca77207.png)

**Comment by StrikerRUS** [comment]
Should be fixed in #2976.

Please try the latest `master` branch or wait for a next release: #3071.
