### ISSUE TITLE
[BUG] LightGBM fails on GPU with high cardinality categorical variables

### ISSUE THREAD

**Issue by keyurjain** [microsoft/LightGBM#3106]
## How you are using LightGBM?

Python Package

## Environment info

Operating System:
Ubuntu

CPU/GPU model:
Nvidia P40

LightGBM version or commit hash:
Latest 

## Error message and / or logs
"bin size 16855 cannot run on GPU"

I know that there is an issue with lightgbm on gpu with high cardinality features. To quote @guolinke :
"GPU version cannot support categorical features with high cardinality.
You can fix it by split one categorical feature into multi categorical features."

Such a transformation is not feasible in our use case.
Is there any plan on making lightgbm work out of the box? Other popular algorithms like catboost currently do make use of the gpu while working with big data. 

Also, is there an exact upper limit on how granular our categorical variables can be to be able to run them on gpu?

**Comment by guolinke** [comment]
Catboost actually converts the categorical features into numerical ones. 
And you can convert them by yourself.
