### ISSUE TITLE
Calculation of scale_pos_weight for multi class

### ISSUE THREAD

**Issue by NaveenSrikanthD** [microsoft/LightGBM#3107]
I am working on an implementations and using lightgbm .I have a problem with unbalanced classes my target variable is multi class. I have seen other issue the formula to calculate scale_pos_weight for binary class data 

What has to be formula for Multiclass ?. can anyone please guide me 

Below is the distribution for of my classes
High:3646904
Low:217191
Medium:292517
Other:525522

Total Records : 4682134

**Comment by StrikerRUS** [comment]
`scale_pos_weight` is used only for binary classification. For multiclass problem you can use `balanced` option from `class_weight`: https://scikit-learn.org/stable/modules/generated/sklearn.utils.class_weight.compute_class_weight.html.
