### ISSUE TITLE
cstdint header in C API

### ISSUE THREAD

**Issue by ddxgz** [microsoft/LightGBM#3111]
Since `c_api.h` header file includes `<cstdint>` and `<cstring>`, when I was trying to call the C API from Swift, but got error that could not find those header files. 

There's no problem to call the C API of XGBoost by usinig the same way, as its c_api.h also includes  `<stdint.h>` if `<cstdint>` is not defined.

## How you are using LightGBM?
C API

## Environment info

Operating System: MacOS 10.15.4

LightGBM version or commit hash:

## Error message and / or logs

```
error: 'cstdint' file not found 
#include <cstdint>
```

## Steps to reproduce

Use the process described in [Swift Package Manager](https://github.com/apple/swift-package-manager/blob/master/Documentation/Usage.md#requiring-system-libraries).

**Comment by guolinke** [comment]
we do have `cstdint` in c_api.h

https://github.com/microsoft/LightGBM/blob/7fe10fa10b529805e447de523d56bbf8a589ae23/include/LightGBM/c_api.h#L18

and in c_api.c, it includes c_api.h:
https://github.com/microsoft/LightGBM/blob/7fe10fa10b529805e447de523d56bbf8a589ae23/src/c_api.cpp#L5

**Comment by momodi** [comment]
I got the same error, may I know how do you solve this problem?

**Comment by jameslamb** [comment]
@momodi are you able to provide a minimal, reproducible example demonstrating the error that you're reporting? The original post here did not contain that.
