### ISSUE TITLE
Performing Test MM_MALLOC - Failed

### ISSUE THREAD

**Issue by raphay3l** [microsoft/LightGBM#3118]
Hi!

Unable to build GPU support. Please help. 

I had tried VS 2017 with CUDA 8.0, 9.0, 10.0, 10.1 and 10.2 and also VS 2019 with CUDA 10.2. I am installing on Windows 10 inside Anaconda Prompt. 

Below reports show details of my software and failure report.

![image](https://user-images.githubusercontent.com/13442202/82837554-53cc5c00-9ec1-11ea-8f8e-6ac40bd5ec7d.png)

![image](https://user-images.githubusercontent.com/13442202/82837538-431be600-9ec1-11ea-9028-c23ec4ea32f6.png)

![image](https://user-images.githubusercontent.com/13442202/82837501-25e71780-9ec1-11ea-98c9-92ded76d194e.png)

![image](https://user-images.githubusercontent.com/13442202/82837520-35666080-9ec1-11ea-817d-8dd7d7889d20.png)

**Comment by jameslamb** [comment]
@raphay3l thanks for using `LightGBM` and for the report! `Performing test MM_MALLOC - failed` does not necessarily mean the installation is broken. It is just a check to see how the library should approach `malloc`-type operations (https://github.com/microsoft/LightGBM/blob/5c0baf6fe008a9d59d604d0dd2742d4be4f9d6e1/include/LightGBM/utils/common.h#L29-L41)

Did you experience some other issue running `LightGBM` code? If so can you please share the code you ran and the error it produced?

**Comment by Laurae2** [comment]
@raphay3l The `MM_MALLOC` macro failing is not an issue as it is related to choosing the correct header library containing `malloc` (unrelated to your GPU issue).

> Unable to build GPU support. 

What is the error you encountered while compiling LightGBM with GPU support?

**Comment by raphay3l** [comment]
@Laurae2 @jameslamb thank you for swift response. Noted. I am closing this issue - resolved.
