### ISSUE TITLE
Documentation Improvement: parameter 'num_iteration' of 'Booster.predict'

### ISSUE THREAD

**Issue by PhilipMay** [microsoft/LightGBM#3121]
The `num_iteration` parameter of `Booster.predict` is unclear for me. When I only want to use the first tree (first boosting round) for the prediction: Do I have to say `num_iteration=0` or `num_iteration=1`? Is it zero based?

If wanted I could provide a PR...

**Bonus question that should be documented:**
What happens if I use a random forest booster? Does `num_iteration` specify only one tree or all trees up to that number? Is that number included or excluded?

**Sidenote:** 
If I have a booster with 10 boosting rounds and call `Booster.predict` with `num_iteration=100` I just get a prediction. IMO it should at least show a warning or raise an exception.

Thanks
Philip

**Comment by PhilipMay** [comment]
My research showed that `num_iteration=0` is the same as `num_iteration=None`. So the first tree (boosting round) is like saying `num_iteration=1`. 

The other questions are still lasting. Feedback is very welcome. :-)

**Comment by StrikerRUS** [comment]
@PhilipMay Hi!

Here are answers for your questions.

Trees are zero-based.

`0` means "use all trees":
> If <= 0, all trees are used (no limits).
          https://lightgbm.readthedocs.io/en/latest/pythonapi/lightgbm.LGBMModel.html#lightgbm.LGBMModel.predict

RF has the same logic as all other boosters:
https://github.com/microsoft/LightGBM/blob/0a4a7a86f5a1d3146c36c7d8c082154a193d4893/src/boosting/gbdt_prediction.cpp#L53-L63

https://github.com/microsoft/LightGBM/blob/0a4a7a86f5a1d3146c36c7d8c082154a193d4893/src/boosting/gbdt_prediction.cpp#L13-L31

If number of iterations bigger than number of trees then it is truncated:
https://github.com/microsoft/LightGBM/blob/5cc38e6aa363e6d04a62bcc5e36ea04ca36e917f/src/boosting/gbdt.h#L349-L351
