### ISSUE TITLE
set_params to n_jobs does not resolve predict hanging with multiprocessing

### ISSUE THREAD

**Issue by ElmiRakh** [microsoft/LightGBM#3122]
## How you are using LightGBM?

* Python package

LightGBM component:  2.3.0 and 2.3.1

## Environment info

Operating System: Ubuntu 18.04

CPU/GPU model: N/A

C++ compiler version:  N/A

CMake version:  N/A
 
Java version:  N/A

Python version: 3.7.1

R version:  N/A

Other:  N/A

LightGBM version or commit hash:  2.3.0 and 2.3.1

## Error message and / or logs

I have a number of trained lgbm models that are being used in the app to make predictions. Each request causes spawn of a worker proocess that is making prediction. Yet lightgbm models hang during execution. After making some reading i found similar issue https://github.com/Microsoft/LightGBM/issues/989 and potential cure - change n_jobs param to 1, so it will work with multiprocess. Yet it didn't work on already trained model, despite parameters of the models being changed by set_params.

## Reproducible example(s)

`
```
import lightgbm as lgb
import numpy as np
import multiprocessing as mp
import joblib
```

```
def test_context_manager():
    # this runs fine
    X = [[i for i in range(5)] for j in range(5)]
    y = [i/10 for i in range(5)]

    model = lgb.LGBMRegressor(n_jobs=1)
    print(model)

    model.fit(X, y)

    test = [np.random.random((1, 5)), ]

    with mp.Pool(processes=1) as pool:
        predict = pool.map(model.predict, test)

    print(predict)

```
```
def test_context_manager_with_jobs():
    # This function hangs
    X = [[i for i in range(5)] for j in range(5)]
    y = [i/10 for i in range(5)]

    model = lgb.LGBMRegressor()
    print(model)

    model.fit(X, y)
    model.set_params(n_jobs=1)
    print(model)

    test = [np.random.random((1, 5)), ]

    with mp.Pool(processes=1) as pool:
        predict = pool.map(model.predict, test)

    print(predict)
```
`

## Steps to reproduce

Just paste and run, nothing fancy

**Comment by StrikerRUS** [comment]
@ElmiRakh I can't preproduce the issue locally, but `n_jobs` for prediction should be set via `kwargs` of `predict()` method. `set_params()` is for `fit()`.

https://lightgbm.readthedocs.io/en/latest/pythonapi/lightgbm.LGBMModel.html#lightgbm.LGBMModel.predict
