### ISSUE TITLE
[QST] What means the last column, the expected value, in pred_contrib output

### ISSUE THREAD

**Issue by ocworld** [microsoft/LightGBM#3123]
I have a question about pred_contrib output.

When I read doc in lightgbm web page, I found below comment.

If you want to get more explanations for your model’s predictions using SHAP values, like SHAP interaction values, you can install the shap package (https://github.com/slundberg/shap). Note that unlike the shap package, with pred_contrib we return a matrix with an extra column, where the last column is the expected value.

I don't clearly understand the mention "the last column is the expected value". What is the expected value? It means label, prediction, raw prediction, or other?

Please let me know about it.

**Comment by StrikerRUS** [comment]
Please refer to https://github.com/microsoft/LightGBM/issues/1969#issuecomment-480580776.

**Comment by ocworld** [comment]
@StrikerRUS Thanks for your comment
