### ISSUE TITLE
SHAP in C++

### ISSUE THREAD

**Issue by mayer79** [microsoft/LightGBM#3127]
An idea about SHAP: the R package of LightGBM offers native R code to calculate SHAP decompositions. This is great but e.g. lacks the relevant decompositions into pairwise contributions (=interaction decompositions). So an R user does not have direct access to SHAP interactions for LightGBM. Python users will usually rely on the "shap" package in Python but R users are a bit lost.

In XGBoost, there is a neat C++ implementation that also covers interaction decompositions. It is handled through the predict method interface.

https://github.com/dmlc/xgboost/blob/master/src/predictor/cpu_predictor.cc

Since model explainability gets more and more of key relevance, I'd love to see something like this for LightGBM as well.

**Comment by StrikerRUS** [comment]
Hi @mayer79 !
Actually, LightGBM has native SHAP values calculation in cpp from the original author. And I think that R-package calls these cpp functions, but do not re-implement it in the R code.

Unfortunately, it is unlikely that new features from SHAP package like feature interactions will be added into LightGBM code.

Please refer to https://github.com/microsoft/LightGBM/issues/1350#issuecomment-395903942.

**Comment by mayer79** [comment]
I see... bad news for R users then!
