### ISSUE TITLE
[bug][Python-package] - leaf_weights changes after saving and loading model

### ISSUE THREAD

**Issue by yanivzoh** [microsoft/LightGBM#3131]
## How you are using LightGBM?
Python package.
version=='2.3.1'

## Environment info

Operating System: Microsoft Windows 10 Pro, OS Version: 10.0.18363 N/A Build 18363

CPU/GPU model: Intel Core i7-1065G7 CPU @ 1.30GHz

C++ compiler version:

CMake version:

Java version:

Python version: Python 3.7.6 | packaged by conda-forge | (default, Jan  7 2020, 21:48:41) [MSC v.1916 64 bit (AMD64)] on win32

R version:

Other:

LightGBM version or commit hash: 2.3.1

## Error message and / or logs

leaf_weight changes upon model loading from file.
see example below (model.txt is different from model2.txt)

## Reproducible example(s)

```python
import lightgbm as lgb
import numpy as np
from hashlib import md5

y_train = np.array([1, 2, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0])
X_train = np.array([[1], [0.22], [0.33], [0.9], [0.5], [0.4], [0.55], [0.67], [0.66], [0.21], [0.11], [0.12], [0.13], [0.14], [0.15], [0.7], [0.8], [0.99], [0.18], [0.19], [0.41], [0.42], [0.43], [0.304], [0.167], [0.121], [0.205], [0.420], [0.380], [0.704], [0.695], [0.312], [0.431], [0.309], [0.458], [0.637], [0.976], [0.535], [0.638], [0.541], [0.559]])
lgb_train = lgb.Dataset(X_train, y_train, free_raw_data=False)

params = {
    'objective': 'multiclass',
    'num_classes': 3,
}

gbm = lgb.train(params,
                lgb_train)

print(md5(gbm.model_to_string().encode('utf-8')).hexdigest())

gbm.save_model('model.txt')
gbm2 = lgb.Booster(model_file='model.txt')
gbm2.save_model('model2.txt')

print(md5(gbm2.model_to_string().encode('utf-8')).hexdigest())
```

**Comment by StrikerRUS** [comment]
The only difference between two files is in one number:

![image](https://user-images.githubusercontent.com/25141164/83361511-5aac1080-a392-11ea-930b-bc3b995eddea.png)

And they differ in two last digits (17th and 18th). If I'm not mistaken, `double` has about 16 significant digits.

@guolinke

**Comment by guolinke** [comment]
It is related double2str/str2double functions.
I remember we used all standard c++ functions for them.

**Comment by StrikerRUS** [comment]
> I remember we used all standard c++ functions for them.

So we can't do anything with it, right?

**Comment by guolinke** [comment]
@StrikerRUS @yanivzoh I think #3148 should fix this
