### ISSUE TITLE
Running GPU on deep learning VM

### ISSUE THREAD

**Issue by kshitijmamgain** [microsoft/LightGBM#3134]
## How you are using LightGBM?
Hello this is my first time reporting an issue, I have succesfully built and run lightGBM with GPU in colab however I am unable to debug the problem while running it on the gcp vm. vm image had pre installed lightgbm I have tried installing lightgbm using both given approaches:
__Case 1.__ pip install lightgbm --install-option=--gpu which gave an error shown below
__Case 2.__ build LightGBM GPU version for linux [here](https://lightgbm.readthedocs.io/en/latest/Installation-Guide.html#build-gpu-version)
TIA, would appreciate a lot if some help is provided.

LightGBM component: Python Package

## Environment info

Operating System: Debian

CPU/GPU model: GPU

C++ compiler version:

CMake version: 3.7.2

Java version:

Python version: 3.7.6

R version: N/A

Other: libboost 1.62.0.1 OpenCL 
NVIDIA CUDA is installed to a customized location:
/usr/local/cuda/lib64/libOpenCL.so

LightGBM version or commit hash:

### Log in Case 1

-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is GNU 6.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: -fopenmp  
-- Looking for CL_VERSION_2_0
-- Looking for CL_VERSION_2_0 - not found
-- Looking for CL_VERSION_1_2
-- Looking for CL_VERSION_1_2 - not found
-- Looking for CL_VERSION_1_1
-- Looking for CL_VERSION_1_1 - not found
-- Looking for CL_VERSION_1_0
-- Looking for CL_VERSION_1_0 - not found
CMake Error at /usr/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find OpenCL (missing: OpenCL_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.7/Modules/FindOpenCL.cmake:127 (find_package_handle_standard_args)
  CMakeLists.txt:94 (find_package)

-- Configuring incomplete, errors occurred!
See also "/tmp/pip-install-nobnd5o3/lightgbm/build_cpp/CMakeFiles/CMakeOutput.log".
See also "/tmp/pip-install-nobnd5o3/lightgbm/build_cpp/CMakeFiles/CMakeError.log".

### Log in case 2:
jupyter@higgs-vm-vm:~/LightGBM/python-package$ python --version
Python 3.7.6
jupyter@higgs-vm-vm:~/LightGBM/python-package$ sudo python setup.py install --precompile
running install
running build
running build_py
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/lightgbm
copying lightgbm/compat.py -> build/lib.linux-x86_64-2.7/lightgbm
copying lightgbm/sklearn.py -> build/lib.linux-x86_64-2.7/lightgbm
copying lightgbm/basic.py -> build/lib.linux-x86_64-2.7/lightgbm
copying lightgbm/libpath.py -> build/lib.linux-x86_64-2.7/lightgbm
copying lightgbm/callback.py -> build/lib.linux-x86_64-2.7/lightgbm
copying lightgbm/engine.py -> build/lib.linux-x86_64-2.7/lightgbm
copying lightgbm/plotting.py -> build/lib.linux-x86_64-2.7/lightgbm
copying lightgbm/__init__.py -> build/lib.linux-x86_64-2.7/lightgbm
running egg_info
writing requirements to lightgbm.egg-info/requires.txt
writing lightgbm.egg-info/PKG-INFO
writing top-level names to lightgbm.egg-info/top_level.txt
writing dependency_links to lightgbm.egg-info/dependency_links.txt
reading manifest file 'lightgbm.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
no previously-included directories found matching 'build'
warning: no files found matching 'LICENSE'
warning: no files found matching '*.txt'
warning: no files found matching '*.so' under directory 'lightgbm'
warning: no files found matching '*.txt' under directory 'compile'
warning: no files found matching '*.so' under directory 'compile'
warning: no files found matching '*.dll' under directory 'compile/Release'
warning: no files found matching '*' under directory 'compile/compute'
warning: no files found matching '*' under directory 'compile/include'
warning: no files found matching '*' under directory 'compile/src'
warning: no files found matching 'LightGBM.sln' under directory 'compile/windows'
warning: no files found matching 'LightGBM.vcxproj' under directory 'compile/windows'
warning: no files found matching '*.dll' under directory 'compile/windows/x64/DLL'
warning: no previously-included files matching '*.py[co]' found anywhere in distribution
writing manifest file 'lightgbm.egg-info/SOURCES.txt'
copying lightgbm/VERSION.txt -> build/lib.linux-x86_64-2.7/lightgbm
running install_lib
copying build/lib.linux-x86_64-2.7/lightgbm/compat.py -> /usr/local/lib/python2.7/dist-packages/lightgbm
copying build/lib.linux-x86_64-2.7/lightgbm/sklearn.py -> /usr/local/lib/python2.7/dist-packages/lightgbm
copying build/lib.linux-x86_64-2.7/lightgbm/basic.py -> /usr/local/lib/python2.7/dist-packages/lightgbm
copying build/lib.linux-x86_64-2.7/lightgbm/libpath.py -> /usr/local/lib/python2.7/dist-packages/lightgbm
copying build/lib.linux-x86_64-2.7/lightgbm/VERSION.txt -> /usr/local/lib/python2.7/dist-packages/lightgbm
copying build/lib.linux-x86_64-2.7/lightgbm/callback.py -> /usr/local/lib/python2.7/dist-packages/lightgbm
copying build/lib.linux-x86_64-2.7/lightgbm/engine.py -> /usr/local/lib/python2.7/dist-packages/lightgbm
copying build/lib.linux-x86_64-2.7/lightgbm/plotting.py -> /usr/local/lib/python2.7/dist-packages/lightgbm
copying build/lib.linux-x86_64-2.7/lightgbm/__init__.py -> /usr/local/lib/python2.7/dist-packages/lightgbm
INFO:LightGBM:Installing lib_lightgbm from: ['../lib_lightgbm.so']
copying ../lib_lightgbm.so -> /usr/local/lib/python2.7/dist-packages/lightgbm
byte-compiling /usr/local/lib/python2.7/dist-packages/lightgbm/compat.py to compat.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/lightgbm/sklearn.py to sklearn.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/lightgbm/basic.py to basic.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/lightgbm/libpath.py to libpath.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/lightgbm/callback.py to callback.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/lightgbm/engine.py to engine.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/lightgbm/plotting.py to plotting.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/lightgbm/__init__.py to __init__.pyc
running install_egg_info
Copying lightgbm.egg-info to /usr/local/lib/python2.7/dist-packages/lightgbm-2.3.2-py2.7.egg-info
running install_scripts

jupyter@higgs-vm-vm:~/LightGBM/python-package$ sudo python3 setup.py install --precompile
running install
running build
running build_py
INFO:root:Generating grammar tables from /usr/lib/python3.5/lib2to3/Grammar.txt
INFO:root:Generating grammar tables from /usr/lib/python3.5/lib2to3/PatternGrammar.txt
running egg_info
writing dependency_links to lightgbm.egg-info/dependency_links.txt
writing lightgbm.egg-info/PKG-INFO
writing top-level names to lightgbm.egg-info/top_level.txt
writing requirements to lightgbm.egg-info/requires.txt
reading manifest file 'lightgbm.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
no previously-included directories found matching 'build'
warning: no files found matching 'LICENSE'
warning: no files found matching '*.txt'
warning: no files found matching '*.so' under directory 'lightgbm'
warning: no files found matching '*.txt' under directory 'compile'
warning: no files found matching '*.so' under directory 'compile'
warning: no files found matching '*.dll' under directory 'compile/Release'
warning: no files found matching '*' under directory 'compile/compute'
warning: no files found matching '*' under directory 'compile/include'
warning: no files found matching '*' under directory 'compile/src'
warning: no files found matching 'LightGBM.sln' under directory 'compile/windows'
warning: no files found matching 'LightGBM.vcxproj' under directory 'compile/windows'
warning: no files found matching '*.dll' under directory 'compile/windows/x64/DLL'
warning: no previously-included files matching '*.py[co]' found anywhere in distribution
writing manifest file 'lightgbm.egg-info/SOURCES.txt'
running install_lib
INFO:LightGBM:Installing lib_lightgbm from: ['../lib_lightgbm.so']
running install_egg_info
removing '/usr/local/lib/python3.5/dist-packages/lightgbm-2.3.2-py3.5.egg-info' (and everything under it)
Copying lightgbm.egg-info to /usr/local/lib/python3.5/dist-packages/lightgbm-2.3.2-py3.5.egg-info
running install_scripts

## Steps to reproduce

1. pip uninstall lightgbm
2. pip install lightgbm --install-option=--gpu
3.

**Comment by StrikerRUS** [comment]
Hi @kshitijmamgain !

For the **Case 1** you need to provide `opencl-include-dir` and `opencl-library` options. Refer to https://github.com/microsoft/LightGBM/tree/master/python-package#build-gpu-version for how to do it.

For the **Case 2** I don't see any issues. LightGBM installation was successful.

**Comment by kshitijmamgain** [comment]
<br>Thanks for your  response, I also tried pip install lightgbm --install-option=--gpu --install-option="--opencl-include-dir=/usr/local/cuda/include/" --install-option="--opencl-library=/usr/local/cuda/lib64/libOpenCL.so" and it ran successfully however I get the following error when I import the library:
__Error__:
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-3-b18b3f8a6dc8> in <module>
----> 1 import lightgbm

/opt/conda/lib/python3.7/site-packages/lightgbm/__init__.py in <module>
      6 from __future__ import absolute_import
      7 
----> 8 from .basic import Booster, Dataset
      9 from .callback import (early_stopping, print_evaluation, record_evaluation,
     10                        reset_parameter)

/opt/conda/lib/python3.7/site-packages/lightgbm/basic.py in <module>
     31 
     32 
---> 33 _LIB = _load_lib()
     34 
     35 

/opt/conda/lib/python3.7/site-packages/lightgbm/basic.py in _load_lib()
     26     if len(lib_path) == 0:
     27         return None
---> 28     lib = ctypes.cdll.LoadLibrary(lib_path[0])
     29     lib.LGBM_GetLastError.restype = ctypes.c_char_p
     30     return lib

/opt/conda/lib/python3.7/ctypes/__init__.py in LoadLibrary(self, name)
    440 
    441     def LoadLibrary(self, name):
--> 442         return self._dlltype(name)
    443 
    444 cdll = LibraryLoader(CDLL)

/opt/conda/lib/python3.7/ctypes/__init__.py in __init__(self, name, mode, handle, use_errno, use_last_error)
    362 
    363         if handle is None:
--> 364             self._handle = _dlopen(self._name, mode)
    365         else:
    366             self._handle = handle

OSError: libboost_filesystem.so.1.72.0: cannot open shared object file: No such file or directory

I don't know if I am missing something fundamental

**Comment by StrikerRUS** [comment]
According to your logs, **Case 2** worked fine for you. Why are you continuing experiments with `pip` installation?

**Comment by kshitijmamgain** [comment]
Hi!  that showed same error. I was unable to import lightgbm with Case2 as well

**Comment by StrikerRUS** [comment]
> that showed same error

What exact error?

Let's go with **Case 2** because it produces more logs by default.

As a starting point, remove old broken LightGBM installations, run these commands and paste logs here.
https://lightgbm.readthedocs.io/en/latest/Installation-Guide.html#build-gpu-version

**Comment by kshitijmamgain** [comment]
I am still learning on this side but, one thing I would like to highlight is that my default python version is 3.7 but log shows that lightgbm installs in python3.5.

**Comment by kshitijmamgain** [comment]
Hi, at the outset thanks for helping me with this.. so I have uninstalled the LightGBM installations and ran the commands on the link. Below is the log for it. However when I import the lightgbm now and run following on notebook:
>> import lightgbm; lightgbm 

>> output: <module 'lightgbm' (namespace)>

Thanks again, I don't know what is it I'm doing wrong
## log details
jupyter@higgs-vm-vm:$ pip uninstall lightgbm
Found existing installation: lightgbm 2.3.1
Uninstalling lightgbm-2.3.1:
  Would remove:
    /opt/conda/lib/python3.7/site-packages/lightgbm-2.3.1-py3.7.egg-info
    /opt/conda/lib/python3.7/site-packages/lightgbm/*
  Would not remove (might be manually added):
    /opt/conda/lib/python3.7/site-packages/lightgbm/lib_lightgbm.so
Proceed (y/n)? y
  Successfully uninstalled lightgbm-2.3.1
jupyter@higgs-vm-vm:$ pip uninstall lightgbm
WARNING: Skipping lightgbm as it is not installed.
jupyter@higgs-vm-vm:$ git clone --recursive https://github.com/microsoft/LightGBM ; cd LightGBM
Cloning into 'LightGBM'...
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 18043 (delta 0), reused 0 (delta 0), pack-reused 18036
Receiving objects: 100% (18043/18043), 12.11 MiB | 0 bytes/s, done.
Resolving deltas: 100% (13170/13170), done.
Submodule 'include/boost/compute' (https://github.com/boostorg/compute) registered for path 'compute'
Cloning into '/home/jupyter/LightGBM/compute'...
remote: Enumerating objects: 21728, done.        
remote: Total 21728 (delta 0), reused 0 (delta 0), pack-reused 21728        
Receiving objects: 100% (21728/21728), 8.51 MiB | 0 bytes/s, done.
Resolving deltas: 100% (17565/17565), done.
Submodule path 'compute': checked out '36c89134d4013b2e5e45bc55656a18bd6141995a'
jupyter@higgs-vm-vm:~/LightGBM$ mkdir build ; cd build

jupyter@higgs-vm-vm:/LightGBM/build$ cmake -DUSE_GPU=1 -DOpenCL_LIBRARY=/usr/local/cuda/lib64/libOpenCL.so -DOpenCL_INCLUDE_DIR=/usr/local/cuda/include/ ..
-- Found OpenCL: /usr/local/cuda/lib64/libOpenCL.so  
-- OpenCL include directory: /usr/local/cuda/include
Boost 1.56.0 found.
Found Boost components:
   filesystem;system
-- Performing Test MM_PREFETCH
-- Performing Test MM_PREFETCH - Success
-- Using _mm_prefetch
-- Performing Test MM_MALLOC
-- Performing Test MM_MALLOC - Success
-- Using _mm_malloc
-- Configuring done
-- Generating done
-- Build files have been written to: /home/jupyter/LightGBM/build
jupyter@higgs-vm-vm:/LightGBM/build$ make -j4
Scanning dependencies of target _lightgbm
Scanning dependencies of target lightgbm
[  1%] Building CXX object CMakeFiles/lightgbm.dir/src/main.cpp.o
[  3%] Building CXX object CMakeFiles/_lightgbm.dir/src/application/application.cpp.o
[  4%] Building CXX object CMakeFiles/_lightgbm.dir/src/boosting/boosting.cpp.o
[  6%] Building CXX object CMakeFiles/_lightgbm.dir/src/boosting/gbdt.cpp.o
[  8%] Building CXX object CMakeFiles/lightgbm.dir/src/application/application.cpp.o
[  9%] Building CXX object CMakeFiles/_lightgbm.dir/src/boosting/gbdt_model_text.cpp.o
[ 11%] Building CXX object CMakeFiles/_lightgbm.dir/src/boosting/gbdt_prediction.cpp.o
[ 12%] Building CXX object CMakeFiles/lightgbm.dir/src/boosting/boosting.cpp.o
[ 14%] Building CXX object CMakeFiles/_lightgbm.dir/src/boosting/prediction_early_stop.cpp.o
[ 16%] Building CXX object CMakeFiles/_lightgbm.dir/src/io/bin.cpp.o
[ 17%] Building CXX object CMakeFiles/_lightgbm.dir/src/io/config.cpp.o
[ 19%] Building CXX object CMakeFiles/_lightgbm.dir/src/io/config_auto.cpp.o
[ 20%] Building CXX object CMakeFiles/_lightgbm.dir/src/io/dataset.cpp.o
[ 22%] Building CXX object CMakeFiles/_lightgbm.dir/src/io/dataset_loader.cpp.o
[ 24%] Building CXX object CMakeFiles/lightgbm.dir/src/boosting/gbdt.cpp.o
[ 25%] Building CXX object CMakeFiles/_lightgbm.dir/src/io/file_io.cpp.o
[ 29%] Building CXX object CMakeFiles/lightgbm.dir/src/boosting/gbdt_model_text.cpp.o
[ 29%] Building CXX object CMakeFiles/_lightgbm.dir/src/io/json11.cpp.o
[ 30%] Building CXX object CMakeFiles/lightgbm.dir/src/boosting/gbdt_prediction.cpp.o
[ 32%] Building CXX object CMakeFiles/_lightgbm.dir/src/io/metadata.cpp.o
[ 33%] Building CXX object CMakeFiles/_lightgbm.dir/src/io/parser.cpp.o
[ 35%] Building CXX object CMakeFiles/lightgbm.dir/src/boosting/prediction_early_stop.cpp.o
[ 37%] Building CXX object CMakeFiles/lightgbm.dir/src/io/bin.cpp.o
[ 38%] Building CXX object CMakeFiles/lightgbm.dir/src/io/config.cpp.o
[ 40%] Building CXX object CMakeFiles/lightgbm.dir/src/io/config_auto.cpp.o
[ 41%] Building CXX object CMakeFiles/_lightgbm.dir/src/io/tree.cpp.o
[ 43%] Building CXX object CMakeFiles/lightgbm.dir/src/io/dataset.cpp.o
[ 45%] Building CXX object CMakeFiles/_lightgbm.dir/src/metric/dcg_calculator.cpp.o
[ 46%] Building CXX object CMakeFiles/_lightgbm.dir/src/metric/metric.cpp.o
[ 48%] Building CXX object CMakeFiles/_lightgbm.dir/src/objective/objective_function.cpp.o
[ 50%] Building CXX object CMakeFiles/lightgbm.dir/src/io/dataset_loader.cpp.o
[ 51%] Building CXX object CMakeFiles/_lightgbm.dir/src/network/linker_topo.cpp.o
[ 53%] Building CXX object CMakeFiles/_lightgbm.dir/src/network/linkers_mpi.cpp.o
[ 54%] Building CXX object CMakeFiles/_lightgbm.dir/src/network/linkers_socket.cpp.o
[ 56%] Building CXX object CMakeFiles/_lightgbm.dir/src/network/network.cpp.o
[ 58%] Building CXX object CMakeFiles/_lightgbm.dir/src/treelearner/data_parallel_tree_learner.cpp.o
[ 59%] Building CXX object CMakeFiles/_lightgbm.dir/src/treelearner/feature_parallel_tree_learner.cpp.o
[ 61%] Building CXX object CMakeFiles/lightgbm.dir/src/io/file_io.cpp.o
[ 62%] Building CXX object CMakeFiles/_lightgbm.dir/src/treelearner/gpu_tree_learner.cpp.o
[ 64%] Building CXX object CMakeFiles/lightgbm.dir/src/io/json11.cpp.o
[ 66%] Building CXX object CMakeFiles/lightgbm.dir/src/io/metadata.cpp.o
[ 67%] Building CXX object CMakeFiles/lightgbm.dir/src/io/parser.cpp.o
[ 69%] Building CXX object CMakeFiles/_lightgbm.dir/src/treelearner/serial_tree_learner.cpp.o
[ 70%] Building CXX object CMakeFiles/lightgbm.dir/src/io/tree.cpp.o
[ 72%] Building CXX object CMakeFiles/_lightgbm.dir/src/treelearner/tree_learner.cpp.o
[ 74%] Building CXX object CMakeFiles/lightgbm.dir/src/metric/dcg_calculator.cpp.o
[ 75%] Building CXX object CMakeFiles/_lightgbm.dir/src/treelearner/voting_parallel_tree_learner.cpp.o
[ 77%] Building CXX object CMakeFiles/lightgbm.dir/src/metric/metric.cpp.o
[ 79%] Building CXX object CMakeFiles/_lightgbm.dir/src/c_api.cpp.o
[ 80%] Building CXX object CMakeFiles/lightgbm.dir/src/objective/objective_function.cpp.o
[ 82%] Building CXX object CMakeFiles/lightgbm.dir/src/network/linker_topo.cpp.o
[ 83%] Building CXX object CMakeFiles/lightgbm.dir/src/network/linkers_mpi.cpp.o
[ 85%] Building CXX object CMakeFiles/lightgbm.dir/src/network/linkers_socket.cpp.o
[ 87%] Building CXX object CMakeFiles/lightgbm.dir/src/network/network.cpp.o
[ 88%] Building CXX object CMakeFiles/lightgbm.dir/src/treelearner/data_parallel_tree_learner.cpp.o
[ 90%] Building CXX object CMakeFiles/lightgbm.dir/src/treelearner/feature_parallel_tree_learner.cpp.o
[ 91%] Building CXX object CMakeFiles/lightgbm.dir/src/treelearner/gpu_tree_learner.cpp.o
[ 93%] Building CXX object CMakeFiles/lightgbm.dir/src/treelearner/serial_tree_learner.cpp.o
[ 95%] Building CXX object CMakeFiles/lightgbm.dir/src/treelearner/tree_learner.cpp.o
[ 96%] Linking CXX shared library ../lib_lightgbm.so
[ 96%] Built target _lightgbm
[ 98%] Building CXX object CMakeFiles/lightgbm.dir/src/treelearner/voting_parallel_tree_learner.cpp.o
[100%] Linking CXX executable ../lightgbm
[100%] Built target lightgbm
jupyter@higgs-vm-vm:~/LightGBM/build$

**Comment by StrikerRUS** [comment]
Nice!

Compilation was successful.

Now please manually check that there is no `lightgbm` folder in `/opt/conda/lib/python3.7/site-packages/` due to this strange message:
```
Would not remove (might be manually added):
/opt/conda/lib/python3.7/site-packages/lightgbm/lib_lightgbm.so
```

After doing that run 
```
cd ../python-package
python setup.py install --precompile
```

**Comment by kshitijmamgain** [comment]
Okay done that. The log is below, when I import it it still throws an error
![lightgbm-vm](https://user-images.githubusercontent.com/56703496/83556157-68ba7800-a4dd-11ea-9006-4d64a16508b4.png)


### Log
jupyter@higgs-vm-vm:/LightGBM/python-package$ python setup.py install --precompile
running install
running build
running build_py
creating build
creating build/lib
creating build/lib/lightgbm
copying lightgbm/compat.py -> build/lib/lightgbm
copying lightgbm/sklearn.py -> build/lib/lightgbm
copying lightgbm/basic.py -> build/lib/lightgbm
copying lightgbm/libpath.py -> build/lib/lightgbm
copying lightgbm/callback.py -> build/lib/lightgbm
copying lightgbm/engine.py -> build/lib/lightgbm
copying lightgbm/plotting.py -> build/lib/lightgbm
copying lightgbm/__init__.py -> build/lib/lightgbm
running egg_info
creating lightgbm.egg-info
writing lightgbm.egg-info/PKG-INFO
writing dependency_links to lightgbm.egg-info/dependency_links.txt
writing requirements to lightgbm.egg-info/requires.txt
writing top-level names to lightgbm.egg-info/top_level.txt
writing manifest file 'lightgbm.egg-info/SOURCES.txt'
reading manifest file 'lightgbm.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
no previously-included directories found matching 'build'
warning: no files found matching 'LICENSE'
warning: no files found matching '*.txt'
warning: no files found matching '*.so' under directory 'lightgbm'
warning: no files found matching '*.txt' under directory 'compile'
warning: no files found matching '*.so' under directory 'compile'
warning: no files found matching '*.dll' under directory 'compile/Release'
warning: no files found matching '*' under directory 'compile/compute'
warning: no files found matching '*' under directory 'compile/include'
warning: no files found matching '*' under directory 'compile/src'
warning: no files found matching 'LightGBM.sln' under directory 'compile/windows'
warning: no files found matching 'LightGBM.vcxproj' under directory 'compile/windows'
warning: no files found matching '*.dll' under directory 'compile/windows/x64/DLL'
warning: no previously-included files matching '*.py[co]' found anywhere in distribution
writing manifest file 'lightgbm.egg-info/SOURCES.txt'
copying lightgbm/VERSION.txt -> build/lib/lightgbm
running install_lib
creating /opt/conda/lib/python3.7/site-packages/lightgbm
copying build/lib/lightgbm/compat.py -> /opt/conda/lib/python3.7/site-packages/lightgbm
copying build/lib/lightgbm/sklearn.py -> /opt/conda/lib/python3.7/site-packages/lightgbm
copying build/lib/lightgbm/basic.py -> /opt/conda/lib/python3.7/site-packages/lightgbm
copying build/lib/lightgbm/libpath.py -> /opt/conda/lib/python3.7/site-packages/lightgbm
copying build/lib/lightgbm/VERSION.txt -> /opt/conda/lib/python3.7/site-packages/lightgbm
copying build/lib/lightgbm/callback.py -> /opt/conda/lib/python3.7/site-packages/lightgbm
copying build/lib/lightgbm/engine.py -> /opt/conda/lib/python3.7/site-packages/lightgbm
copying build/lib/lightgbm/plotting.py -> /opt/conda/lib/python3.7/site-packages/lightgbm
copying build/lib/lightgbm/__init__.py -> /opt/conda/lib/python3.7/site-packages/lightgbm
INFO:LightGBM:Installing lib_lightgbm from: ['../lib_lightgbm.so']
copying ../lib_lightgbm.so -> /opt/conda/lib/python3.7/site-packages/lightgbm
byte-compiling /opt/conda/lib/python3.7/site-packages/lightgbm/compat.py to compat.cpython-37.pyc
byte-compiling /opt/conda/lib/python3.7/site-packages/lightgbm/sklearn.py to sklearn.cpython-37.pyc
byte-compiling /opt/conda/lib/python3.7/site-packages/lightgbm/basic.py to basic.cpython-37.pyc
byte-compiling /opt/conda/lib/python3.7/site-packages/lightgbm/libpath.py to libpath.cpython-37.pyc
byte-compiling /opt/conda/lib/python3.7/site-packages/lightgbm/callback.py to callback.cpython-37.pyc
byte-compiling /opt/conda/lib/python3.7/site-packages/lightgbm/engine.py to engine.cpython-37.pyc
byte-compiling /opt/conda/lib/python3.7/site-packages/lightgbm/plotting.py to plotting.cpython-37.pyc
byte-compiling /opt/conda/lib/python3.7/site-packages/lightgbm/__init__.py to __init__.cpython-37.pyc
running install_egg_info
Copying lightgbm.egg-info to /opt/conda/lib/python3.7/site-packages/lightgbm-2.3.2-py3.7.egg-info
running install_scripts

**Comment by StrikerRUS** [comment]
OK, guess I found the reason!

> OSError: libboost_filesystem.so.1.72.0: cannot open shared object file: No such file or directory

> Boost 1.56.0 found.
Found Boost components:
filesystem;system

Your issue looks similar to https://github.com/microsoft/LightGBM/issues/2641#issuecomment-568095613 because of two different installed boost versions.

You should leave only one of them: either 1.56.0 or 1.72.0. Probably one comes from your conda environment.

**Comment by kshitijmamgain** [comment]
Okay..so which one should I remove? 1.72.0? I am inside /opt/conda/lib and I see many files
However, I don't see Boost 1.56.0 there
![lightgbm-vm2](https://user-images.githubusercontent.com/56703496/83570396-f43f0380-a4f3-11ea-8018-37665533f3f8.png)

**Comment by StrikerRUS** [comment]
Please run `conda list` command. I expect `libboost` should be there.

**Comment by kshitijmamgain** [comment]
Hello again, no libboost present
![conda_list](https://user-images.githubusercontent.com/56703496/83578284-57d12d00-a504-11ea-83bb-ca4fa93f09f1.png)

**Comment by StrikerRUS** [comment]
Hmm, indeed! Quite strange...

I see you have a lot of packages in your conda environment. So removing libboost 1.72.0 from `/opt/conda/lib` will probably break some of them.

I think it is better to remove libboost 1.56.0 in your case (which is a system-wide library, I guess). Then LightGBM will be linked against 1.72.0 from your conda environment and there should be no problems at runtime.

**Comment by kshitijmamgain** [comment]
Ok any instructions on how that is to be done.. sorry but this side is new to me

**Comment by StrikerRUS** [comment]
> Version: 1.62.0.1

Wow! Is it a third boost installation in your environment?

I'm sorry, I'm not very familiar with Linux. Can you try to remove all boost installations except one in your conda environment? I believe it can be done via `sudo apt-get --purge autoremove libboost` (or `libboost-dev`).

**Comment by kshitijmamgain** [comment]
Hi! So, as you suggested I did the following steps:
1. removed files via sudo apt-get --purge autoremove libboost-dev. The only  boost version that is installed is 1.72 for python3 and 1.70 for python2. 
2. I looked for boost 1.56.0 by searching '*1.56.0*', '*1.56*', '*1_56*  string but there is no file or directory by that name.
3. Uninstalled and re-installed the lightgbm, precompiled python package but it still throws the error:
libboost_filesystem.so.1.72.0: cannot open shared object file: No such file or directory

**Comment by kshitijmamgain** [comment]
I have dropped the plans to build with gpus anyways, thanks for your help. Would keep an eye if this gets sorted out in future.

**Comment by StrikerRUS** [comment]
> The only boost version that is installed is 1.72 for python3 and 1.70 for python2.

If possible, leave only one.

> Uninstalled and re-installed the lightgbm, precompiled python package but it still throws the error

Have you **re-compiled** LightGBM library file before re-installing Python package?

Also, you may try to add folder with `boost 1.72.0` from conda (`/opt/conda/lib`) into `LD_LIBRARY_PATH` variable.

**Comment by StrikerRUS** [comment]
> I have dropped the plans to build with gpus anyways, thanks for your help. Would keep an eye if this gets sorted out in future.

Ah, OK! As this is the problem with particular environment, I don't think that keeping this issue open will make any sense.
