### ISSUE TITLE
Is there any document about how to implement monotone constraint in lightgbm?

### ISSUE THREAD

**Issue by ZSCDumin** [microsoft/LightGBM#3135]
Is there any document about how to implement monotone constraint in lightgbm?

**Comment by StrikerRUS** [comment]
Hi @ZSCDumin !

Monotone constraints are already implemented in LightGBM. Refer to https://lightgbm.readthedocs.io/en/latest/Parameters.html#monotone_constraints for how to specify them.

Also, we have an unmerged PR that will add new version of monotone constraints: #2305. And here is the paper about it: https://github.com/microsoft/LightGBM/files/3457826/PR-monotone-constraints-report.pdf.
