### ISSUE TITLE
LGBMRanker: lightgbm.basic.LightGBMError: Unknown objective type name: rank_xendcg

### ISSUE THREAD

**Issue by artdgn** [microsoft/LightGBM#3142]
## How you are using LightGBM?
* Python package

LightGBM component: LGBMRanker

## Environment info
Operating System: Ubuntu 18
Python version: 3.6
LightGBM version or commit hash: 2.3.1

## Error message and / or logs

```
lightgbm.basic.LightGBMError: Unknown objective type name: rank_xendcg
```

## Reproducible example(s)

```python
lightgbm.LGBMRanker(objective='rank_xendcg').fit([[0], [0]], [0, 1], group=[1, 1])
```

**Comment by StrikerRUS** [comment]
Unfortunately, `rank_xendcg` is not available in `2.3.1` version.
You can either download nightly build

https://lightgbm.readthedocs.io/en/latest/Installation-Guide.html

![image](https://user-images.githubusercontent.com/25141164/83654577-fa9db000-a5c5-11ea-9cee-0a26980c1e5e.png)


or wait for a next release: #3071.
