### ISSUE TITLE
Documentation doesn't match latest release (e.g. objective functions)

### ISSUE THREAD

**Issue by artdgn** [microsoft/LightGBM#3146]
Feature (`rank_xendcg`) not yet released: https://github.com/microsoft/LightGBM/issues/3142

But objective is listed in docs: https://lightgbm.readthedocs.io/en/latest/Parameters.html#objective

**Comment by jameslamb** [comment]
Thanks for using LightGBM @artdgn !

Right now, our docs at that link match the `master` branch of this repository, which can be  ahead of the most recent release to package managers like PyPi.

Sorry for the confusion! We could probably do a better job of adding comments like "new as of version x.x.x" under newer features.

I'm going to close this issue but please comment if anything was unclear or you need  additional help.
