### ISSUE TITLE
Windows - 10.0.17763 - AMD64

### ISSUE THREAD

**Issue by fralychen** [microsoft/LightGBM#3150]
CPU/GPU model:  AMD64

CMake version: 3.17.3(X64)

Python version: 3.8

when use Command Line build ,  loger raise to me "The system is: Windows - 10.0.17763 - AMD64"

**Comment by StrikerRUS** [comment]
@fralychen 

Please re-open the issue with description about what difficulties you are facing using CLI interface of LightGBM.
