### ISSUE TITLE
Dialog box pops up when using Debug build of LightGBM

### ISSUE THREAD

**Issue by mjmckp** [microsoft/LightGBM#3151]
When I attempt to use a debug build of LightGBM, when I create the booster object with default parameters, I get the following dialog box pop up:

![image](https://user-images.githubusercontent.com/7776787/83837244-3c029c80-a739-11ea-8cb5-445c2ae059b2.png)

This doesn't happen with a release build.  I think this is being generated by OpenMP, I've seen mention of it elsewhere in projects that use OpenMP.

Steps to reproduce:
- Clone LightGBM.Net from https://github.com/rca22/LightGBM.Net
- ~~Switch to the `update_jun_20` branch~~ (No longer necessary, use master branch)
- Put a Debug build of LightGBM (built from master) in the `LightGBM.Net\native\Debug` folder
- Run the test BoosterTest.Create in LightGBMNet.Train.Test

**Comment by jameslamb** [comment]
Thanks for the report and for using `LightGBM`!

We do not maintain `LightGBM.NET`, could you please raise this issue in [that project's issues page](https://github.com/rca22/LightGBM.Net/issues)?

If you are able to reproduce this pop up using only `LightGBM` code here, please open a new issue and we'll be happy to help.

**Comment by mjmckp** [comment]
Sorry, I think you have misunderstood, the issue has nothing to do with LightGBM.Net, I maintain that project, and I am just using it as a way to explain how to replicate the issue.  The error is being generated by the native lightgbm dll.

**Comment by jameslamb** [comment]
oh I definitely did misunderstand. Can you please provide a reproducible example that doesn't rely on `LightGBM.Net`? That would help us to help you

**Comment by guolinke** [comment]
@mjmckp The `Debug' is the 'debug' mode of lightgbm.dll or LightGBM.net?

**Comment by mjmckp** [comment]
@guolinke The debug build of `lightgbm.dll`

**Comment by shiyu1994** [comment]
@mjmckp  This is due to a bug in undefined "num_threads" of the TrainingShareStates. The num_threads of a TrainingShareStates is set in this function. However, when the bin is nullptr, num_threads of TrainingShareStates is not set.
> https://github.com/microsoft/LightGBM/blob/f5f27ca88c69d194ca03df88c5c2a58acce15e33/include/LightGBM/dataset.h#L296-L308

But later on, this num_threads will be passed to num_threads argument of omp here

> https://github.com/microsoft/LightGBM/blob/f5f27ca88c69d194ca03df88c5c2a58acce15e33/src/io/dataset.cpp#L1336

which causes the error.

Inserting `num_threads = OMP_NUM_THREADS();` between line 297 and 298 of dataset.h resolve this issue. 

We will resolve this with a pull request together with the problem in #3152.

**Comment by guolinke** [comment]
@shiyu1994 I think you can create a PR to fix this first.
