### ISSUE TITLE
 reference for code for binary_classification

### ISSUE THREAD

**Issue by Sandy4321** [microsoft/LightGBM#3154]
there is no code for example in 
https://github.com/microsoft/LightGBM/tree/master/examples/binary_classification

but only data
can you add code or reference for code

**Comment by btrotta** [comment]
@Sandy4321  That example is for the command-line interface. You don't need any additional code to run the example, just execute the commands as shown in the readme.

Alternatively, you might like to use the Python or R interface. 
Quick-start guide for Python: https://lightgbm.readthedocs.io/en/latest/Python-Intro.html 
Docs for R: https://lightgbm.readthedocs.io/en/latest/R/

**Comment by Sandy4321** [comment]
Great thanks
