### ISSUE TITLE
[Question] Tweedie log-link transformation

### ISSUE THREAD

**Issue by ismailbbm** [microsoft/LightGBM#3155]
I am training a model using Tweedie and wanted to understand a bit more its inner working. In the documentation it is mentioned that a log-link is used.

However I am struggling to find in the code where the log-link is applied.

The Tweedie [metric](https://github.com/microsoft/LightGBM/blob/ac5f5e56d012b1f435f1a52cbd6600f100ffa187/src/metric/regression_metric.hpp#L311) does not have the log-link applied:
```c++
const double a = label * std::exp((1 - rho) * std::log(score)) / (1 - rho);
const double b = std::exp((2 - rho) * std::log(score)) / (2 - rho);
return -a + b;
```
The Tweedie [objective](https://github.com/microsoft/LightGBM/blob/master/src/objective/regression_objective.hpp#L711) has a log-link applied:
```c++
gradients[i] = static_cast<score_t>(-label_[i] * std::exp((1 - rho_) * score[i]) + std::exp((2 - rho_) * score[i]));
hessians[i] = static_cast<score_t>(-label_[i] * (1 - rho_) * std::exp((1 - rho_) * score[i]) +
          (2 - rho_) * std::exp((2 - rho_) * score[i]));
```
In the objective, it seems to me the only way to get a gradient equal to zero when score and label are the same is when a log transform has been applied beforehand: score = log(score).

Could you please help me understand what is happening in the code or direct me to where I can find what is happening?

**Comment by guolinke** [comment]
Refer to https://github.com/microsoft/LightGBM/blob/e83042f20633d7f74dda0d18624721447a610c8b/src/objective/regression_objective.hpp#L458-L460

Tweedie inherits RegressionPoissonLoss, which applies `exp` transformation to outputs.
