### ISSUE TITLE
[Python] ctypes.ArgumentError: argument 8

### ISSUE THREAD

**Issue by gugatr0n1c** [Microsoft/LightGBM#316]
I get error below in same cases, not sure where is the problem:

Traceback (most recent call last):
  File "search_44_test_jinak.py", line 216, in <module>
    prediction_valid = model.predict(matrix_valid, num_iteration = model.best_iteration)
  File "/usr/local/lib/python3.5/dist-packages/lightgbm-0.1-py3.5.egg/lightgbm/basic.py", line 1539, in predict
    return predictor.predict(data, num_iteration, raw_score, pred_leaf, data_has_header, is_reshape)
  File "/usr/local/lib/python3.5/dist-packages/lightgbm-0.1-py3.5.egg/lightgbm/basic.py", line 297, in predict
    predict_type)
  File "/usr/local/lib/python3.5/dist-packages/lightgbm-0.1-py3.5.egg/lightgbm/basic.py", line 357, in __pred_for_np2d
    preds.ctypes.data_as(ctypes.POINTER(ctypes.c_float))
ctypes.ArgumentError: argument 8: <class 'TypeError'>: Don't know how to convert parameter 8

## Environment info
Operating System: Linux
C++/Python/R version: Python 3.5

**Comment by wxchan** [comment]
pls provide a reproducible example

**Comment by gugatr0n1c** [comment]
@wxchan I probably found the case. I set:

iteration = numpy.random.choice([3000, 5000, 10000])

then iteration is numpy.int64 type, which cause problem in model.predict() with best_iteration setting...

When I convert iteration with int() then it is OK...

**Comment by guolinke** [comment]
@wxchan i think you can open a PR to fix this.

**Comment by wxchan** [comment]
I am not sure what exactly the bug is. Cannot reproduce it.

**Comment by guolinke** [comment]
@wxchan it seems is the passed parameter ```num_iteration``` in ```predict```. It may be the numpy type.

**Comment by wxchan** [comment]
I tried to pass np.int32 and np.int64 to num_iteration, met no bug. @gugatr0n1c can you provide a reproducible example here?

**Comment by gugatr0n1c** [comment]
@wxchan @guolinke 
I can reproduce it with this steps each time:

- iteration set as numpy.int64, ie = 1000
- use early stopping
- but set learning_rate is small, that early_stopping is not applied and all iterations are used
- use num_iteration = model.best_iteration inside predict:
model.predict(matrix_learn, num_iteration = model.best_iteration)

When early_stopping stops learning process it is working fine - no error.

**Comment by wxchan** [comment]
still cannot reproduce it. I think in this case, `model.best_iteration` should be -1.

**Comment by gugatr0n1c** [comment]
In this case yes, but I never know before when early_stopping will stop the learning process.
But when I transform it with int() it is working. So we can close this I guess.
