### ISSUE TITLE
folds in lgb.cv

### ISSUE THREAD

**Issue by JerryX2014** [microsoft/LightGBM#3161]
## How you are using LightGBM?

LightGBM component:  R package

## Environment info

Operating System: Linux

CPU/GPU model: N/A

C++ compiler version:N/A

CMake version:N/A

Java version:N/A

Python version:N/A

R version: 3.5.1
Other:

LightGBM version or commit hash: 2.3.2

## Error message and / or logs

[LightGBM] [Warning] Starting from the 2.1.2 version, default value for the "boost_from_average" parameter in "binary" objective is true.
This may cause significantly different results comparing to the previous versions of LightGBM.
Try to set boost_from_average=false, if your old models produce bad results
[LightGBM] [Info] Number of positive: 15643, number of negative: 7767
[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.080935 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 40766
[LightGBM] [Info] Number of data points in the train set: 23410, number of used features: 545
**[LightGBM] [Fatal] [Used indices of subset]: does not tolerate element [#8013 = 31424] outside [0, 31422]
[LightGBM] [Fatal] Length of weights is not same with #data**

## Steps to reproduce

Suppose modeldevelop contains the data, including weights, I created my folds using the following codes.

```
modeldevelop$cv_fold = findInterval(runif(nrow(modeldevelop)),vec = c(0,0.25,0.5,0.75,1),rightmost.closed = TRUE)
table(modeldevelop$cv_fold)
cv_fold = list(which(modeldevelop$cv_fold == 1),which(modeldevelop$cv_fold == 2),which(modeldevelop$cv_fold == 3),which(modeldevelop$cv_fold == 4))

```
Next, feed cv_fold as folds in the lgb.cv function.

I used debug function to check the source code and found that, the following piece of code generate the fatal error.

```
bst_folds <- lapply(X = seq_along(folds), FUN = function(k) {
        folds_have_group <- "group" %in% names(folds[[k]])
        if (folds_have_group) {
            test_indices <- folds[[k]]$fold
            test_group_indices <- folds[[k]]$group
            test_groups <- getinfo(data, "group")[test_group_indices]
            train_groups <- getinfo(data, "group")[-test_group_indices]
        }
        else {
            test_indices <- folds[[k]]
        }
        train_indices <- seq_len(nrow(data))[-test_indices]
        indexDT <- data.table::data.table(indices = test_indices, 
            weight = getinfo(data, "weight")[test_indices], init_score = getinfo(data, 
                "init_score")[test_indices])
        data.table::setorderv(indexDT, "indices", order = 1L)
        dtest <- slice(data, indexDT$indices)
        setinfo(dtest, "weight", indexDT$weight)
        setinfo(dtest, "init_score", indexDT$init_score)
        indexDT <- data.table::data.table(indices = train_indices, 
            weight = getinfo(data, "weight")[train_indices], 
            init_score = getinfo(data, "init_score")[train_indices])
        data.table::setorderv(indexDT, "indices", order = 1L)
        dtrain <- slice(data, indexDT$indices)
        setinfo(dtrain, "weight", indexDT$weight)
        setinfo(dtrain, "init_score", indexDT$init_score)
        if (folds_have_group) {
            setinfo(dtest, "group", test_groups)
            setinfo(dtrain, "group", train_groups)
        }
        booster <- Booster$new(params, dtrain)
        booster$add_valid(dtest, "valid")
        return(list(booster = booster))
    })
```
My guess is that, R resets the index after slicing the data. When it reads the weight with the original index, the index was out of the range.

Thanks!
Jerry

**Comment by jameslamb** [comment]
@JerryX2014 thanks for using `LightGBM`, and for the report! Is it possible to provide code that can reproduce the issue completely? 

This description leaves a lot to interpretation:

> Suppose modeldevelop contains the data, including weights, I created my folds using the following codes.

**Comment by guolinke** [comment]
@jameslamb 
maybe this could be reproduced by random data?

**Comment by jameslamb** [comment]
Maybe, but before I spend time trying to recreate this, I want to know if @JerryX2014 can provide a reproducible example

**Comment by JerryX2014** [comment]
@jameslamb  Sorry, all good now. I used the index from full sample instead of the training sample. I made the change and it works.

**Comment by jameslamb** [comment]
oh great! No need to be sorry, thanks for using `LightGBM`!
