### ISSUE TITLE
Issues with Light GBM C_API

### ISSUE THREAD

**Issue by nathans3** [microsoft/LightGBM#3166]
Hello, I've been trying to use the C-API solving a simple regression problem. I created a simple toy model of linear regression.
Basically, my code creates dataset handle from mat using DatasetCreateFromMat then adds label field, and then creates a booster using BoosterCreate. However, the resulting booster does not predict anything, the prediction result is always 0.
My code is attached.
Please advise what I am doing wrong in using the API.
Thank you,
[demo.txt](https://github.com/microsoft/LightGBM/files/4779943/demo.txt)

Nathan

**Comment by guolinke** [comment]
@nathans3 it seems you didn't call the training function?

**Comment by nathans3** [comment]
I was looking for a training function, but could not find an explicit one. Is it UpdateOneIter?

**Comment by guolinke** [comment]
Refer to https://github.com/microsoft/LightGBM/blob/e83042f20633d7f74dda0d18624721447a610c8b/src/c_api.cpp#L1335-L1344
