### ISSUE TITLE
"Cannot add validation data, since it has different bin mappers with training data" for  Datasets loading from binary file

### ISSUE THREAD

**Issue by JiaRu2016** [microsoft/LightGBM#3170]
I'v create an pair of train / test Dataset and `save_binary()` to a file. Then I load the Datasets from disk and and put them into  `lgb.train()` to train model, got the Error: 

"Cannot add validation data, since it has different bin mappers with training data"

this issue https://github.com/microsoft/LightGBM/issues/2552 seems very similar to mine, but my dataset do not contain any category feature

## Reproducible example(s)

here is a simulation example that is very close to my production code (I can not publish my code and data) . This example works well, but for my real-world data, it raise error. I tried to change my data, found that sometimes it works while  sometimes it raise the error, and i could not find the pattern.

```python
import numpy as np
import lightgbm as lgb
import gc

def gen_X_y():
    X = np.random.normal(size=(1000, 100))
    y = np.random.normal(size=(1000,))
    return X, y

X_train, y_train = gen_X_y()
ds_train = lgb.Dataset(X_train, label=y_train)

X_test, y_test = gen_X_y()
ds_test = ds_train.create_valid(X_test, label=y_test)

ds_train.save_binary('train')
ds_test.save_binary('test')

del X_train, y_train, X_test, y_test, ds_train, ds_test
gc.collect()

ds_train = lgb.Dataset('train', free_raw_data=False)
ds_train.construct()

ds_test = lgb.Dataset('test', free_raw_data=False)
ds_test.construct()

lgb.train(
    {
        'objective': 'rmse',
    },
    ds_train,
    valid_sets=[ds_train, ds_test],
    valid_names=['train', 'test'],
    verbose_eval=True
)
```

## How you are using LightGBM?
LightGBM component: Python package

## Environment info

Operating System: Ubuntu 18.04

CPU/GPU model: CPU

C++ compiler version: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

CMake version:  cmake version 3.17.1

Java version:

Python version: Python 3.7.4

R version:

Other:

LightGBM version or commit hash: e83042f20633d7f74dda0d18624721447a610c8b

## Error message and / or logs

Cannot add validation data, since it has different bin mappers with training data

**Comment by StrikerRUS** [comment]
@JiaRu2016 I guess you forgot to add `reference=ds_train` in your valid dataset creation command:
```
ds_test = lgb.Dataset('test', free_raw_data=False)
```

**Comment by JiaRu2016** [comment]
@StrikerRUS  add `reference=ds_train` does not sole this problem. And after days of trial, I works, I don't know why. Maybe it's related to evnironment

**Comment by guolinke** [comment]
@StrikerRUS the dataset is loaded by binary file, and the reference is set before (create_valid), so it is not the root cause. 

@JiaRu2016 did you use the multi-processing, and save/load the binary files by the same name? Can you test on other environments?

**Comment by JiaRu2016** [comment]
I saved and loaded the binary file in jupyter notebook (when then error occurs), maybe this is the root caule?  I'll try other environment and tries make this problem reporduceable

**Comment by guolinke** [comment]
@JiaRu2016 any updates?

**Comment by JiaRu2016** [comment]
I'v tried several envrionment: Mac or Linux, python script or jupyter notebook, lgb CPU version or GPU version, but can not reproduce this error , so I'm closing this issue
