### ISSUE TITLE
Why does default num_leaves is 2^n -1 instead of 2^n 

### ISSUE THREAD

**Issue by zyxue** [microsoft/LightGBM#3177]
More specifically, I'm reading the parameters of [LGBMRegressor](https://lightgbm.readthedocs.io/en/latest/pythonapi/lightgbm.LGBMRegressor.html#lightgbm.LGBMRegressor), the default `num_leaves` is 31, I wonder why not 32? What's the intuition behind it, please?

**Comment by guolinke** [comment]
Not actually, we just set it to 31 randomly and didn't change it since that.
