### ISSUE TITLE
Unknown parameter when using monotone_constraints_method and monotone_penalty

### ISSUE THREAD

**Issue by CanML** [microsoft/LightGBM#3178]
## How you are using LightGBM?

LightGBM component: Python package

## Environment info

Operating System: Windows 10

CPU/GPU model: Intel i9

C++ compiler version:

CMake version:

Java version:

Python version: 3.8

R version:

Other:

LightGBM version or commit hash: 2.3.2 (using build from https://www.lfd.uci.edu/~gohlke/pythonlibs/ )

## Error message and / or logs

[LightGBM] [Warning] Unknown parameter: monotone_penalty
[LightGBM] [Warning] Unknown parameter: monotone_constraints_method

## Steps to reproduce

When using either the Booster object with LGBM Dataset and train functions, or the sklearn "LGBMRegressor" interface, these warnings appear when I try to use these parameters. In all cases I have specified "monotone_constraints" and the monotonic enforcement functionality works properly. It is only the monotone_constraints_method (and all aliases) and monotone_penalty (and all aliases) as listed at (https://lightgbm.readthedocs.io/en/latest/Parameters.html) which do not seem to be available in Python via any interface choice despite being in the documentation for this version.

**Comment by StrikerRUS** [comment]
I guess `monotone_constraints` were merged later after creating those releases. They are very old.

![image](https://user-images.githubusercontent.com/25141164/85334673-4b793800-b4e4-11ea-9213-72dc53dd0ab2.png)


Please use official nightly builds in which `monotone_constraints` are included.

https://lightgbm.readthedocs.io/en/latest/Installation-Guide.html
![image](https://user-images.githubusercontent.com/25141164/85334756-73689b80-b4e4-11ea-962a-5e221976e469.png)

**Comment by CanML** [comment]
I didn't realize releases happened so frequently that included new features without changes to the minor version number. Thank you.

**Comment by StrikerRUS** [comment]
Just to be clear: the latest official release is `2.3.1` and it is very-very old (https://github.com/microsoft/LightGBM/releases, 28 Nov 2019). Next release will be a major release `3.0.0` (#3071). `2.3.2` is not a release but is just a dev version for `master` branch.

**Comment by CanML** [comment]
Got it, thanks again
