### ISSUE TITLE
Missing plot tree and create_tree_digraph from lightgbm

### ISSUE THREAD

**Issue by vignesh0710** [microsoft/LightGBM#3183]
I installed lightgbm from PyPI

```
pip install lightgbm

import lightgbm as light
light.__version__

'2.3.1'
```

`Python version - 3.7.2`

I am trying to convert the tree object for the model LGBMRegressor to graphviz.dot.Digraph but both plot_tree and create_tree_digraph are not in the attributes list

Error:

`'LGBMRegressor' object has no attribute 'plot_tree'`

Anyway to solve this would be great.

**Comment by StrikerRUS** [comment]
> but both plot_tree and create_tree_digraph are not in the attributes list

They are not methods of objects, but separate functions.

Refer to the example of how to use them

https://github.com/microsoft/LightGBM/blob/be85f56ffc0d3939a7140fc8686c7ba695aefdb5/examples/python-guide/plot_example.py#L56-L58

https://github.com/microsoft/LightGBM/blob/be85f56ffc0d3939a7140fc8686c7ba695aefdb5/examples/python-guide/plot_example.py#L60-L62

(Full example: https://github.com/microsoft/LightGBM/blob/master/examples/python-guide/plot_example.py)
