### ISSUE TITLE
Numerical Representation of Categorical Features in Persisted Model File

### ISSUE THREAD

**Issue by sebastian-janisch** [microsoft/LightGBM#3184]
Hi!

I am taking a closer look at the persisted model file and came across the feature_infos field and I’m puzzled as to what the values represent for categorical features.

From what I can gather we have value ranges for every feature. Continuous features have an interval denoted in brackets and categorical values have a list of numbers separated by a colon.

E.g. there’s a categorical feature in our calibration that gets below feature_infos:

1:0:3:2

Now, if I look all the way down in the model file I can also see a pandas_categorical which for every categorical feature lists the possible values.

My confusion is how the two link together. It looks like the feature_infos vector has indices in it as the highest value is never larger than the highest index of the pandas_categorical vector. Then again not every index is covered (e.g. could be the highest is say 70 which lines up with 71 possible categories but the value 39 does not come up).

Could you clarify what the exact format is? Ultimately the goal is to extract the numerical representation for each possible category for categorical features. It seems that this information is encoded in the model output file but I can’t fully stitch it together.

**Comment by guolinke** [comment]
@sebastian-janisch 
LightGBM will the low-frequency categories. The filtered categories will be not shown in `feature_infos`.
