### ISSUE TITLE
[R-package] RFC: require R >= 3.5.0

### ISSUE THREAD

**Issue by jameslamb** [microsoft/LightGBM#3212]
I'm opening this request for comment as part of the changes we're considering for `LightGBM` 3.0.0 (#3071 ).

I'd like to propose the following:

> as of LightGBM 3.0.0, the R package cannot be used with R versions older than 3.5.0.

## How this makes LightGBM better

Today, we maintain a couple places in the code for the R package which are if-else blocks checking whether you are on a version of R earlier than R 3.5.0

* https://github.com/microsoft/LightGBM/blob/1e2013a306c0ca719fa076a733796a6372e5b77e/CMakeLists.txt#L14
* https://github.com/microsoft/LightGBM/blob/1e2013a306c0ca719fa076a733796a6372e5b77e/R-package/src/R_object_helper.h#L21-L46
* https://github.com/microsoft/LightGBM/blob/1e2013a306c0ca719fa076a733796a6372e5b77e/R-package/src/install.libs.R#L173-L175

Removing this support would simplify the R package's code, reducing the risk of mistakes and the maintenance burden. This simplification would also make implementing #3016 easier.

## Why I think the impact to users will be minimal

R 3.5.0 was released more than 2 years ago, in April 2018 ([version history](https://cran.r-project.org/bin/windows/base/old/)).

In all of the R-package bug reports submitted by our users in the last 6 months, people have been using R version 3.5 or later

* #3139: 3.6.3
* #3112: 4.0.0
* #3099: 4.0.0
* #3064: 3.6.3 -> 4.0.0
* #2970: 3.6.3
* #2715: 3.5.x

## Note for reviewers

In addition to maintainers, I'd love comments from some of the people who have helped the R package by opening issues and pull requests: @mayer79 @rgranvil

**Comment by mayer79** [comment]
I remember there where some troubles when R 3.5 was being released. 

I think in this case it is fully justified to require R >= 3.5, even if one or the other company might still rely on older R versions (with old versions of LightGBM, probably, so no real issue).
