### ISSUE TITLE
Issues Fitting "Same" Data into Light GBM Classifier

### ISSUE THREAD

**Issue by dantetrick** [microsoft/LightGBM#3213]
I have an issue fitting my data to a LightGBM Classifier that hopefully I can get some help with. 

1. I have 1 notebook that works fine so I cloned it in order to try to optimize the flow. 
2. The cloned notebook fails using nearly the same code on the same data. The difference between the codes is found in how I 'filter' out test and training data.
3. The row count is exactly the same when I try to fit() the model.  
4. The notebook fails after I place a filter prior to the StringVectorization and OneHotEncoding steps instead of filtering out the data  post steps. The actual data that is Vectorized and Encoded is the same columns between notebooks. 
5. Below is the data sample 1 row of the data that goes into the 'working' classifier. 
![image](https://user-images.githubusercontent.com/11829494/86827916-6d77cc00-c047-11ea-83db-213b51e16c5c.png)
![image](https://user-images.githubusercontent.com/11829494/86827507-ed516680-c046-11ea-82c2-dbfe237a40d7.png)
6. Below is a data sample of the same row of data that goes into the 'non-working' classifier. 
![image](https://user-images.githubusercontent.com/11829494/86827866-5c2ebf80-c047-11ea-8eba-77a6f7ef6cc4.png)
![image](https://user-images.githubusercontent.com/11829494/86827690-2e497b00-c047-11ea-9a23-b46eb370d3b8.png)
![image](https://user-images.githubusercontent.com/11829494/86828566-45d53380-c048-11ea-95ef-5d655e859c2b.png)
![image](https://user-images.githubusercontent.com/11829494/86828639-5d142100-c048-11ea-8f28-9c820f38e2e7.png)

NOTES: 
A. The noticeable difference in the data is the numbers assigned to the column values from the indexer. I don't know why that would affect the fit() function but it may. 
B. I recently updated to the new library in MAVEN, but I haven't been able to remove the Azure:mmlspark0.17 library. Would that matter?
![image](https://user-images.githubusercontent.com/11829494/86829012-ca27b680-c048-11ea-9f97-e56ba9976630.png)

**Comment by StrikerRUS** [comment]
@dantetrick Sorry, we do not maintain MMLSpark here. Please copy the content of your issue in the appropriate repository: https://github.com/Azure/mmlspark/issues.
