### ISSUE TITLE
lightgbm 2.3.2 sklearn classifier/regressor does not have init_model in fit param

### ISSUE THREAD

**Issue by rjmcmcftw** [microsoft/LightGBM#3218]
## How you are using LightGBM?

LightGBM component: 

## Environment info

Operating System:

CPU/GPU model: CPU

C++ compiler version: 

CMake version:

Java version:

Python version: 3.6

R version:

Other:

LightGBM version or commit hash:

## Reproducible example(s)

```
import lightgbm as lgb
lgb.LGBMClassifier().fit(init_model=None)
```

## Steps to reproduce

As seen here, the init_model param does not exist in the sklearn api of the classifier. I verified with a friend and he had the same issue with lightgbm version 2.3.2. 

![image](https://user-images.githubusercontent.com/14790098/87181441-30097d80-c297-11ea-87cc-d68f3d03e9a8.png)

**Comment by StrikerRUS** [comment]
@rjmcmcftw Unfortunately, `init_model` param is available only in the latest LightGBM version (not yet released). But according to your screenshots, you have got `2.2.3` version, but not `2.3.2`.
