### ISSUE TITLE
SWIG - Using multiple matrices to build LightGBM train dataset

### ISSUE THREAD

**Issue by AlbertoEAF** [microsoft/LightGBM#3229]
Hello, 

With really large datasets  (>16GB worth of double values) in a single machine I'm hitting a limitation with malloc (limit of the non-teraspace malloc) to allocate a single buffer for the train data that will in turn be fed to https://lightgbm.readthedocs.io/en/latest/C-API.html#c.LGBM_DatasetCreateFromMat.

I thus need to use multiple smaller buffers and use `LGBM_DatasetCreateFromMats` instead. Whilst this is perfectly possible in the C API, AFAIK there aren't methods available in the SWIG interface to manipulate pointers of pointers to make this happen. Meaning, placing all those `double*` from those buffers in a single `void**` to use that function.

**Questions:**
1.  I don't mind adding  a very small PR to add manipulation of those pointers in SWIG. I wonder though if you've had such issue before and how you dealt with it **without** going multi-machine?
2.  Even if I fix this, is the LightGBM Dataset structure capable of holding >16GB of data or will have exactly the same problem as my single buffer?

Ping +1 @imatiach-msft for his extensive work on MMLSpark's LightGBM :)

Thank you guys! :D

**Comment by AlbertoEAF** [comment]
@imatiach-msft do you think this fix you made is enough to deal with this ?

https://github.com/microsoft/LightGBM/pull/2859

Thanks!

**Comment by imatiach-msft** [comment]
@AlbertoEAF I hope so, the fix should already be in latest master in mmlspark.  Any way you could share a way to reproduce the issue?  If not, are you able to validate the latest mmlspark fixes this issue?

This build:

```
Maven Coordinates

com.microsoft.ml.spark:mmlspark_2.11:1.0.0-rc1-106-254e44ea-SNAPSHOT
Maven Resolver

https://mmlspark.azureedge.net/maven
```

corresponds to this PR:

https://github.com/Azure/mmlspark/pull/882
