### ISSUE TITLE
Modifying model file

### ISSUE THREAD

**Issue by kobics** [microsoft/LightGBM#3230]
Hi
We would like to modify a model file, but few things seems wrong.
1 When we modify shrinkage/leaf values, and load, sometime the kernel dies
2 When we modify the shrinkage, and load the model (And the kernel does not die), the predictions are the same as the original model, before modifying the shrinkage

Thanks

**Comment by jameslamb** [comment]
Hi @kobics , thanks for using `LightGBM`! If you can please provide some more information, an appropriate maintainer will help you.

Can you please answer the questions you were asked when you clicked "New issue"? Copy this content (https://raw.githubusercontent.com/microsoft/LightGBM/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md) and fill it out in a comment here.

**Comment by guolinke** [comment]
@kobics if you change the model file manually, you should remove `tree_size` field.

**Comment by kobics** [comment]
> https://raw.githubusercontent.com/microsoft/LightGBM/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md

**Comment by kobics** [comment]
> Hi @kobics , thanks for using `LightGBM`! If you can please provide some more information, an appropriate maintainer will help you.
> 
> Can you please answer the questions you were asked when you clicked "New issue"? Copy this content (https://raw.githubusercontent.com/microsoft/LightGBM/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md) and fill it out in a comment here.

Hi @jameslamb thanks for your reply. please explain what you ask me
Thanks

**Comment by jameslamb** [comment]
it looks like you opened #3232 with the details I'm asking for. That wasn't my intention, but that works!

did @guolinke 's suggestion (https://github.com/microsoft/LightGBM/issues/3232#issuecomment-659409428) help you?

**Comment by kobics** [comment]
> @kobics if you change the model file manually, you should remove `tree_size` field.

works for the leafs (at this point), when i change the shrinkage and load, it still breaks

**Comment by kobics** [comment]
> it looks like you opened #3232 with the details I'm asking for. That wasn't my intention, but that works!
> 
> did @guolinke 's suggestion ([#3232 (comment)](https://github.com/microsoft/LightGBM/issues/3232#issuecomment-659409428)) help you?

partially : 

works for the leafs (at this point), when i change the shrinkage and load, it still breaks

**Comment by jameslamb** [comment]
Ok I've reopend this issue. Let's keep the conversation here and not use #3232 , so it is one conversation.

From #232 , it looks like you are using version 2.3.0 of the Python package. That version is quite old...could you try installing version 2.3.1 from PyPi (`pip install lightgbm`) or building from source in this repo?

If you need to be on 2.3.0 for stability reasons (totally understand!), is it possible to provide the model file here and the code that you are using to load it?

Python maintainers like @StrikerRUS will be able to be more helpful, but we need more information than what you've provided so far to give you the best possible help.

**Comment by guolinke** [comment]
@kobics what do "break" mean? it dies? 
> 2 When we modify the shrinkage, and load the model (And the kernel does not die), the predictions are the same as the original model, before modifying the shrinkage

The shrinkage rate is not used in prediction time. The leaf value is already shrinkage in training. It will not apply again.

**Comment by kobics** [comment]
> @kobics what do "break" mean? it dies?
> 
> > 2 When we modify the shrinkage, and load the model (And the kernel does not die), the predictions are the same as the original model, before modifying the shrinkage
> 
> The shrinkage rate is not used in prediction time. The leaf value is already shrinkage in training. It will not apply again.

@guolinke Thanks this is very helpful. Can you tell me if there additional parts of the model I can erase and still be able to : 
1 load and predict
2 load and continue to train

Thank you

**Comment by guolinke** [comment]
@kobics For the tree model, you can edit tree structure and tree outputs (but need to remove the tree_size). For the most remaining fields in tree, there are to record the status in training.

**Comment by kobics** [comment]
> @kobics For the tree model, you can edit tree structure and tree outputs (but need to remove the tree_size). For the most remaining fields in tree, there are to record the status in training.

@guolinke Thanks. is the status recorded used for later training (if we use it as an init model)?

**Comment by guolinke** [comment]
@kobics 
I don't think so.
