### ISSUE TITLE
Problems when modifying model file

### ISSUE THREAD

**Issue by kobics** [microsoft/LightGBM#3232]
## How you are using LightGBM?

LightGBM component: 

## Environment info

Operating System: Linux

CPU/GPU model: NA

C++ compiler version: NA

CMake version: NA

Java version: NA

Python version: conda install 2.3.0

R version: NA

Other: NA

LightGBM version or commit hash: NA

## Error message and / or logs

Hi
We would like to modify a model file, but few things seems wrong.
1 When we modify shrinkage/leaf values, and load, sometime the *kernel dies*
2 When we modify the shrinkage, and load the model (And the kernel does not die), the predictions are the same as the original model, before modifying the shrinkage

Thanks

## Steps to reproduce

1. Build LightGBM regression model
2. Save model to text file
3. Modify shrinkage/leaf values
4. Load and predict using the modified model

Two issues
a. either the kernel dies (both modifications)
b. the model predictions do not change (it if not dies) (in case of shrinkage change)

**Comment by guolinke** [comment]
@kobics if you change the model file manually, you should remove the tree_size field.
