### ISSUE TITLE
New release ETA?

### ISSUE THREAD

**Issue by AlbertoEAF** [microsoft/LightGBM#3236]
Hello,

Are there plans for a new release soon?

Thank you :)

**Comment by ekerazha** [comment]
@imatiach-msft is a new release of lightgbm also blocking a new release of mmlspark? Both projects got a massive amount of improvements in the latest months, but they don't get any new release since November 2019.

**Comment by imatiach-msft** [comment]
@ekerazha no, it is not blocking mmlspark.  There have been several lightgbm java (jar) releases in the recent past, and mmlspark depends on those.  mmlspark can be used from any PR build as a spark package, so a release shouldn't block anyone.  However, @mhamilton723 is planning to do an official rc-2 release soon for mmlspark (he is a part-time research SDE who currently owns MMLSpark but is also getting his PhD at MIT, I'm on the ResponsibleAI team mainly contributing to InterpretML OSS but also work on mmlspark in my free time based on user-requested features/bugs).  Hope that clears up any confusion.

**Comment by AlbertoEAF** [comment]
There's a new open-source Java wrapper which would really benefit from a release though, to benefit from the latest patches in the master: https://github.com/feedzai/feedzai-openml-java/tree/master/openml-lightgbm as it is focused in low-latency scoring.

@imatiach-msft basically you're releasing new versions of the lightgbm java based on the master right? In your experience, how stable is master vs the official LightGBM releases?

I wonder when a new release is coming out to know if we should wait a bit longer? Or if we need to risk using the master, which would be less desirable, as this is used in production systems? Or even fork LightGBM to have the latest release + cherry-picked critical fixes/changes.

**Comment by imatiach-msft** [comment]
@AlbertoEAF I think master is very stable, at least for the native code.  I've done many releases before from master, often due to critical bugs that were blocking users/customers from using the distributed version.  Yes, I can do another release of the maven jar.  Do you need a new release right now, or after a specific PR is merged?  Would be happy to do a release for that project.

**Comment by AlbertoEAF** [comment]
Thank you for your input and generosity @imatiach-msft! Due to development though we can no longer use those maven releases as we had to change the build process to build directly from source.

Based on @imatiach-msft's answers, it seems we have two hypothesis: wait for a new release or use master directly. 

Does someone have an idea of the next release date?

**Comment by guolinke** [comment]
@AlbertoEAF 
refer to #3071 , although I want to release the new version ASAP,  we have several issues that need to address.

**Comment by AlbertoEAF** [comment]
Thank you!
