### ISSUE TITLE
Monotonically constrain integer variables with missing values

### ISSUE THREAD

**Issue by cegafe3** [microsoft/LightGBM#3237]
I'm trying to impose monotonic constrains to variables that are integers and have missing values. The problem is, the default int32 format doesn't support missing values, and the int64 format that accepts missing values is not supported by LigthGBM.

What is the right way of dealing with this without having to cast the variable to float?

**Comment by guolinke** [comment]
you can use `zero_as_missing`, and set 0 to the missing values.
