### ISSUE TITLE
Support for multiple data files

### ISSUE THREAD

**Issue by ace7** [Microsoft/LightGBM#324]
It would be great if we can specify multiple data files, or file patterns, eg:
```
data = *.train
valid_data = 1.valid,2.valid,3.valid
```

**Comment by wxchan** [comment]
you can merge them into one with `cat`

**Comment by ace7** [comment]
Yes, I know. But for a Hadoop/Spark job, generally there will be many output files, it will be more convenient to use those files without an additional `cat` command.

**Comment by wxchan** [comment]
That's fair, but can you use lightgbm on hdfs now?

**Comment by ebernhardson** [comment]
something like this might also help with cross-validation for ranking. Currently CV doesn't split groups appropriately, but if i could generate folds externally and provide the path to each fold i want to use in train/test that would be a plausible workaround.
