### ISSUE TITLE
[bug] Introduced bug in *Fast() methods with the locking strategy PR

### ISSUE THREAD

**Issue by AlbertoEAF** [microsoft/LightGBM#3241]
The https://github.com/microsoft/LightGBM/pull/2760 PR introduced 2 bugs in the fast methods introduced in https://github.com/microsoft/LightGBM/pull/2992/.

The non-fast variants were correctly changed, but the Fast variants were not updated in the same manner:

- https://github.com/microsoft/LightGBM/commit/1c35c3b9ede9adab8ccc5fd7b4b2b6af188a79f0#diff-59f374370af59cd4cbd753881fc246c5R1936-R1981
- https://github.com/microsoft/LightGBM/commit/1c35c3b9ede9adab8ccc5fd7b4b2b6af188a79f0#diff-59f374370af59cd4cbd753881fc246c5R2079-R2114

I only noticed that when building the latest version, since the parameter "num_iteration" is not used anymore after the PR https://github.com/microsoft/LightGBM/pull/2760.

I can add a PR to fix it. However, this change to a separate `SetSingleRowPredictor` presents now an opportunity for further optimization, moving these calls to the FastInit, or a new FastUpdate, which would change the API of the Fast methods again (and in turn impact with the 3.0.0 release - https://github.com/microsoft/LightGBM/pull/3071). Also, not reusing `get_row_fun` as originally in https://github.com/microsoft/LightGBM/pull/2992/ considerably reduced the performance gains. Maybe it would be interesting to reintroduce that possibility. If a new data pointer is passed to Fast() scoring, that generates a new function, otherwise it uses the one stored in the FastConfig. Or, we can cache the data pointer and test if the pointer changed.
All this leads me to ask to delay a bit the 3.0 release again, since there's this new bug as well and changing the API a bit further would allow us to make LightGBM even faster for the Fast calls.

What are your thoughts @guolinke, @StrikerRUS, @StrikerRUS, @imatiach-msft, et al.?

Thanks!

**Comment by guolinke** [comment]
@AlbertoEAF I think delaying the release of  3.0.0-rc1 for about one-week (or slightly longer) is not a big deal. 
What is the ETA of this fix?

**Comment by JoanFM** [comment]
Hey @AlbertoEAF 

Sorry for the inconvenience, did I screw doing some realignment? Let me know if I can be of help on fixing the issue.

**Comment by AlbertoEAF** [comment]
The fix is quick, a two-liner and is done, however changing the API and measuring if there are improvements would take a little longer. I can only work on the weekend, so I can do it this weekend or the next. Is that ok @guolinke?

Otherwise I'd ask if we can release 3.0.0-rc1 with the commit before the merge of #2992 @guolinke to avoid being stuck with this API for the future.

No problem @JoanFM ;) it's an easy fix.

**Comment by guolinke** [comment]
@AlbertoEAF I think it is okay
