### ISSUE TITLE
[Python]model of best_iter cannot be saved correctly

### ISSUE THREAD

**Issue by zcschao** [Microsoft/LightGBM#325]
I found a problem when using LightGBM. The model during training iter and the trained model have different evalution results on predicting the same vaild set using the same self-defined eval metric. In order to exclude the cause of the parameter, I try using the parameter of /examples /python-guide/ simple_example.py, but the problem still exists.The difference is intolerable when iter_num is large.

My code is here.[https://github.com/zcschao/Issues_lgbm](https://github.com/zcschao/Issues_lgbm)

I think the problem may caused by my own code but I really need some help here.
[@guolinke](https://github.com/guolinke)

## Environment info
Python:Python 3.5.1 |Anaconda 4.0.0 (64-bit)

## Error Message:

Early stopping, best iteration is:
[8]     valid_0's l2: 163.05    valid_0's auc: 0.507561
Start predicting...
The rmse of prediction is: 163.496966821

## Steps to reproduce

1.run /src/get_sample.py
2.run /src/train_simple.py or /src/train_myeval.py

**Comment by guolinke** [comment]
@wxchan can you take a look for this?

**Comment by wxchan** [comment]
I can't find an obvious bug, is it something related to the issue raised in #319 when l2 is large?

**Comment by zcschao** [comment]
I think I find the bug in my code.I didn't pre-process the data.After dropna and normalization, LightGBM just runs well. I still have a lot to learn. :smile:
