### ISSUE TITLE
using CV with dart & early_stopping_rounds

### ISSUE THREAD

**Issue by anovember** [microsoft/LightGBM#3255]
I understand why using `lgb.train` with `dart` and  `early_stopping_rounds` won't work (earlier trees are mutated, as discussed in #1893 ), but it seems like using this combination in `lgb.cv` would be valid / useful for figuring out the optimal number of rounds. 

Or am I missing something? 
Thanks.

**Comment by guolinke** [comment]
@anovember yeah, when with `dart`, you can use the early stoping to get the optimal num_rounds, in both lgb.train and lgb.cv.
But you need to re-run the training without early stopping with the optimal num_rounds, to get the correct model.
