### ISSUE TITLE
[TYPO] DatasetLoader::ConstructFromSampleData

### ISSUE THREAD

**Issue by lcsdavid** [microsoft/LightGBM#3257]
May I add that there is an error in
<[LightGBM/include/LightGBM/dataset_loader.h](https://github.com/microsoft/LightGBM/blob/master/include/LightGBM/dataset_loader.h)>:30:26-48
CostructFromSampleData should be ConstructFromSampleData ?

Regards.

Originally posted by @lcsdavid in https://github.com/microsoft/LightGBM/issues/2341#issuecomment-662830604

Creating PR to fix it.

**Comment by lcsdavid** [comment]
Associated PR #3258

**Comment by StrikerRUS** [comment]
Fixed in #3258.
