### ISSUE TITLE
[Python]Clarification of num_trees in booster params and num_boost_round in training function

### ISSUE THREAD

**Issue by Haoychen** [Microsoft/LightGBM#327]
For python interface, I could specify the **_num_trees_** in booster configuration. Also, I could specify the **_num_boost_round_** in train function. Theoretically, in regression and binary classification problem, number of trees = number of iterations. It seems the two parameters stand for the same thing. But in python interface, after training, I check the model and find that only **_num_boost_round_** controls the number of trees and num_trees does nothing during training.

What does these two parameters exactly do during training?

**Comment by wxchan** [comment]
in multiclass classification, num_trees = num_boost_round * num_class.
in other task, they are the same.

specifying num_trees in booster configuration does nothing. you should use num_boost_round

**Comment by Haoychen** [comment]
Thanks for wxchan's explanation. Solved this problem.
