### ISSUE TITLE
More frequent releases

### ISSUE THREAD

**Issue by mirekphd** [microsoft/LightGBM#3274]
## Summary

Please start making more frequent releases, at least monthly.

## Motivation

The project is actively maintained and adds new features and corrects issues every month. 

The release frequency has dropped significantly compared to previous years (every 2 months in 2018 and every 4 months in 2019).

Currently the [latest version](https://github.com/microsoft/lightgbm/tags), 2.3.1, is 8 months old, and misses such important newly added features as e.g. [python 3.8 support](https://github.com/microsoft/LightGBM/pull/2713).

The closest competitor, xgboost has been making a few releases every month this year: see [xgboost tags](https://github.com/dmlc/xgboost/tags).

Compiling from sources (suboptimal due to larger time requirements and lower consistency) is also not available, because the code is not tagged either (one would have to checkout and pin commit hashes, like for under-resourced or abandoned projects).

**Comment by StrikerRUS** [comment]
> Compiling from sources ... is also not available,


You can always download and use our nightly builds: https://lightgbm.readthedocs.io/en/latest/Installation-Guide.html.

Speaking about making more frequent releases, we are already on the way to it! Please feel free to comment in the existing issue: #3210.

**Comment by mirekphd** [comment]
I dont think its a duplicate, because the other thread is calling for a 4-part version numbers, which is a blocker IMHO. I just need the more frequent releases under standard 3-part semantic versioning.
/reopen
