### ISSUE TITLE
"boost_from_average" parameter in "binary" objective is true.

### ISSUE THREAD

**Issue by hanzigs** [microsoft/LightGBM#3278]
Using lightgbm == 2.3.0
I get this warning
```
[LightGBM] [Warning] Starting from the 2.1.2 version, default value for the "boost_from_average" parameter in "binary" objective is true.
This may cause significantly different results comparing to the previous versions of LightGBM.
Try to set boost_from_average=false, if your old models produce bad results
```
I have set this parameter to False, still I get warning
```
lgbmmodel_senn = LGBMClassifier(boosting_type = 'gbdt', 
				num_leaves=31, 
				max_depth=-1, 
                                objective = 'binary', 
				class_weight = 'balanced', 
				boost_from_average = False,
                                subsample_for_bin = 200000, 
				min_child_samples = 20,
                                n_estimators=n_estimators, 
				learning_rate = learning_rate, 
                                colsample_bytree = colsample_bytree, 
				subsample = subsample, 
				min_child_weight = min_child_weight, 
				n_jobs = NJOBS,                                 
				verbose = VERBOSE, 
				random_state = 50)
```
How to get rid of this warning? Found these two link that already discussed this issue
https://github.com/Azure/mmlspark/issues/471
https://github.com/Microsoft/LightGBM/issues/1514

also in https://stackoverflow.com/questions/55499429/lightgbm-ignore-warning-about-boost-from-average
Thanks

**Comment by guolinke** [comment]
I think we can remove this warning in 3.0 release. 
ping @StrikerRUS @jameslamb 
any other warnings should we remove?

**Comment by guolinke** [comment]
@hanzigs I think this was already removed in the latest master branch. 
please update your LightGBM.

**Comment by hanzigs** [comment]
Updated to 2.3.1
![image](https://user-images.githubusercontent.com/30790120/89505068-5bd34100-d80c-11ea-9f49-786633631096.png)
Still I get this
![image](https://user-images.githubusercontent.com/30790120/89505103-6d1c4d80-d80c-11ea-9b17-1cd6060aa13a.png)

**Comment by guolinke** [comment]
@hanzigs I mean the latest master branch. 2.3.1 is not the latest one.

**Comment by StrikerRUS** [comment]
@guolinke 

> any other warnings should we remove?

I hope I removed all warnings in #3073 during to preparation for 3.0 release.

**Comment by jameslamb** [comment]
> I think we can remove this warning in 3.0 release.
> ping @StrikerRUS @jameslamb
> any other warnings should we remove?

sorry, missed this comment! But I can't think of any others that need to be removed.
