### ISSUE TITLE
There is still something wrong with custom objective under 'goss' mode

### ISSUE THREAD

**Issue by shaoguang123** [microsoft/LightGBM#3282]
## How you are using LightGBM?

LightGBM component: **Python package**

## Environment info

Operating System: **Windows**

CPU/GPU model: **CPU**

Other:

LightGBM version or commit hash:   The latest version download from the master branch at 2020/8/6

## Problem

I meet the error `Wrong type(int) for hessian. It shold be list, numpy 1-D array or pandas Series` after the commit #3263, when using custom objective under the "goss" mode.

**Comment by guolinke** [comment]
ping @shiyu1994 
it seems the array in python ctypes is changed in c++. 
@shaoguang123 can you provide a reproduce example, with random data, so that we can easily debug?

**Comment by shaoguang123** [comment]
> ping @shiyu1994
> it seems the array in python ctypes is changed in c++.
> @shaoguang123 can you provide a reproduce example, with random data, so that we can easily debug?

sorry, my bad. I miss something which cause that problem.
