### ISSUE TITLE
Save_model  doesn't support model larger than 2G？  if  num_boost_round is too large，the saved model cannot work.

### ISSUE THREAD

**Issue by Chianghung** [microsoft/LightGBM#3289]
Errors：  [LightGBM] [Fatal] Model format error, expect a tree here. met
when loading the model.txt

**Comment by guolinke** [comment]
Which wrapper did you use? Could you provide the code example?

**Comment by Chianghung** [comment]
> Which wrapper did you use? Could you provide the code example?

lgb_train = lgb.Dataset(X_train,label=y_train, free_raw_data=True,categorical_feature=['sta','time'])
lgb_eval = lgb.Dataset(X_test, label=y_test, reference=lgb_train)
print('Start training...')
gbm = lgb.train(params,lgb_train,categorical_feature=['sta','time'],valid_sets=lgb_eval,num_boost_round=10000,keep_training_booster=True,early_stopping_rounds=10) 
gbm = lgb.train(params,lgb_train,valid_sets=lgb_eval,num_boost_round=10000,keep_training_booster=True,early_stopping_rounds=10) 
print('Save model...') 
gbm.save_model('max201501-202006.model')  
print('Start predicting...')
y_pred = gbm.predict(X_test, num_iteration=gbm.best_iteration) 
print('The MAE of prediction is:', mean_absolute_error(y_test, y_pred)) 

Seems that I can't use categorical_feature(324 features),cause large models than cannot be saved Successfully.

**Comment by guolinke** [comment]
You can try to map the category to the continued int range, start from 0.

**Comment by Chianghung** [comment]
> You can try to map the category to the continued int range, start from 0.
Thank you very much.Problem solved,model is much smaller.New problem:categorical_feature is used,but the model file has none categorical_feature information as follows:
 [categorical_feature: ]
pandas_categorical:[]

**Comment by Chianghung** [comment]
> You can try to map the category to the continued int range, start from 0.

Thank you very much.Problem solved,model is much smaller.New problem:categorical_feature is used,but the model file has none categorical_feature information as follows:
[categorical_feature: ]
pandas_categorical:[]

**Comment by guolinke** [comment]
@Chianghung 
In this case, it is better to pass the numpy object to LightGBM.
like
```
X_train_numpy = X_train.values() #map categorical feature before this
categorical_feature = [#index of the categorical features]
lgb_train = lgb.Dataset(X_train_numpy ,label=y_train, free_raw_data=True,categorical_feature=categorial_feature)
```
And do the same preprocessing before prediction.

**Comment by Chianghung** [comment]
> @Chianghung
> In this case, it is better to pass the numpy object to LightGBM.
> like
> 
> ```
> X_train_numpy = X_train.values() #map categorical feature before this
> categorical_feature = [#index of the categorical features]
> lgb_train = lgb.Dataset(X_train_numpy ,label=y_train, free_raw_data=True,categorical_feature=categorial_feature)
> ```
> 
> And do the same preprocessing before prediction.

Thanks,but it doesn't work and seems a bug.
If  num_boost_round is too large,the model is so large that it cannot be loaded,besides, the model file still has none categorical_feature information as mentioned above.

**Comment by guolinke** [comment]
It is a limitation of string length of ctypes in python. It is not trivial for us to fix it. 
BTW, You should also use keep_training_booster=True, while disabling the pandas category feature.

**Comment by StrikerRUS** [comment]
Closing because we already have a feature request for extremely large model files (#2265). Feel free to vote in #2302.
