### ISSUE TITLE
Python: Add best_score callback when early stopping

### ISSUE THREAD

**Issue by mratsim** [Microsoft/LightGBM#329]
Like best_iteration, it would be useful to add a best_score callback when early stopping occurs.

The updates seem pretty straightforward :
- EarlyStopException class in [callback.py](https://github.com/Microsoft/LightGBM/blob/master/python-package/lightgbm/callback.py)
- The documentation

I'll propose a PR this weekend. Did I miss something ?

**Comment by wxchan** [comment]
best_iteration represents best model, which is used for prediction. what is best_score for?

**Comment by mratsim** [comment]
Hello @wxchan. Sorry for the late reply.

Best_score would be used for automation (Pipelines, GridSearches ...).
It should return the metric corresponding to best_iteration

**Comment by wxchan** [comment]
ok, you can open a pr for it, or I can do it later if you don't have time.

**Comment by wxchan** [comment]
@guolinke you can close this thread too

**Comment by Laurae2** [comment]
@guolinke You can close this issue.
