### ISSUE TITLE
Small doc error in Experiments

### ISSUE THREAD

**Issue by Shihab-Shahriar** [microsoft/LightGBM#3290]
In [Experiments](https://lightgbm.readthedocs.io/en/latest/Experiments.html) page, at the hyper-parameter setting of `xgboost_hist`, two different `tree_method ` are mentioned, both `approx` and `hist`.

**Comment by jameslamb** [comment]
@Shihab-Shahriar thanks for letting us know! We'd welcome a pull request to fix it, if you'd like to [submit one](https://github.com/microsoft/LightGBM/pulls).

I think you can remove `tree_method: approx`.
