### ISSUE TITLE
Python Sciki-learn API LGBMClassifier predict raw_score=True return probability outside 0 and 1

### ISSUE THREAD

**Issue by mikiwzh** [microsoft/LightGBM#3291]
## How you are using LightGBM?

 Python package
LightGBM component: LGBMClassifier from sklearn API

## Environment info

Operating System: Linux

CPU/GPU model:

C++ compiler version:

CMake version:

Java version:

Python version: 3.7.6

R version:

Other:

LightGBM version or commit hash:

## Reproducible example(s)

Tried both with and without 'objective': 'binary'
params = {
    'boosting_type': 'dart',
    'learning_rate': 0.1,
    'objective': 'binary',
    'drop_rate': 0.1,
    'verbose': 0
}

params = {
    'boosting_type': 'dart',
    'learning_rate': 0.1,
    'drop_rate': 0.1,
    'verbose': 0
}

gbm = lgb.LGBMClassifier(**params, n_estimators=500)

## Steps to reproduce

1.
2.
3.

**Comment by StrikerRUS** [comment]
Hi @mikiwzh !
When you pass `raw_score=True` it means that estimator will return not probability, but raw scores before transformation.
