### ISSUE TITLE
Make MPI ring connection retry count configurable

### ISSUE THREAD

**Issue by aakarshg** [microsoft/LightGBM#3301]
## Summary

Currently the maximum number of retries is [20](https://github.com/microsoft/LightGBM/blob/master/src/network/linkers_socket.cpp#L189), which might seem enough for normal cases, but when running with large number of machines, this isn't enough. If this can be made into a parameter that can be passed to the config, that'll be helpful

**Comment by jameslamb** [comment]
Thanks for the suggestion and for using `LightGBM`! We'd welcome a pull request if you're interested in making one.

Otherwise we will add this to our feature backlog (#2302) and try to get to it in a coming release
