### ISSUE TITLE
Unknown importance type: only support split=0 and gain=1

### ISSUE THREAD

**Issue by gharibkhani** [microsoft/LightGBM#3303]
Hi,

I am using the Lighgbm via ML.Net. I got the latest code and built the lib.lightgbm.dll and tried it but I am getting the "Unknown importance type: only support split=0 and gain=1" error. I tried to find out the parameter responsible for the feature_importance_type but I just found saved_feature_importance_type parameter. I believe the code needs the same logic that 
SaveModelToFile has to get the value from a config parameter.
I tried a version before introducing feature_importance_type and it worked fine without any issue.
The reason I did all this stuff is to build the GPU binary that I can use in ML.Net. With the older version, I do not have any problem but I would like to have the latest version with all the fixes.

**Comment by guolinke** [comment]
@gharibkhani We have several breaking changes in api recently, and need to change accordingly in ML.Net.

**Comment by gharibkhani** [comment]
Is it a work that needs to be done in ML.Net team?

**Comment by guolinke** [comment]
@gharibkhani 
Yes, we have several new api changes in v3.0.0, and ML.NET need to adapt these changes if they using LightGBM v3.0.0

**Comment by gharibkhani** [comment]
Hi,

This error can be reproduced by any example. I just used the example in docs.microsoft.com and able to reproduce it.

https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.lightgbmextensions.lightgbm?view=ml-dotnet

I created a console app and you can access it from the link below:

https://drive.google.com/drive/folders/1-wc04CM75-IGoxjRAniDuhqI-zrHTWwM?usp=sharing

**Comment by StrikerRUS** [comment]
I believe it it worth to open a feature request issue in the ML.NET repo and ask them update LightGBM to `3.0` version.
https://github.com/dotnet/machinelearning/blob/35d5a479f1f7215ca14a26e6f43e1eaeb32b1523/build/Dependencies.props#L17

**Comment by evo11x** [comment]
I get the same error

**Comment by jameslamb** [comment]
@evo11x thanks for using Lightgbm!

Please follow the advice in the previous comments above and ask the ML.NET developers to upgrade to at least LightGBM 3.0.0 (the newest release is 3.1.1 by now).

https://github.com/dotnet/machinelearning/issues

**Comment by gharibkhani** [comment]
I already opened an issue with them. You can follow and ask them to do it faster:

https://github.com/dotnet/machinelearning/issues/5447

**Comment by jameslamb** [comment]
thanks very much! I did not know about that issue, since it wasn't linked to this one.
