### ISSUE TITLE
[Feature Request] Auto early stopping in Sklearn API

### ISSUE THREAD

**Issue by rohan-gt** [microsoft/LightGBM#3313]
Is it possible to perform early stopping using cross-validation or automatically sampling data from the provided train set without explicitly specifying an eval set?

**Comment by guolinke** [comment]
lgb.cv supports early stopping, does it meet your request?

**Comment by rohan-gt** [comment]
I was actually looking for the same feature within the Sklearn API

**Comment by rohan-gt** [comment]
Optuna actually does this for LightGBM through the [LightGBMTunerCV](https://optuna.readthedocs.io/en/stable/reference/generated/optuna.integration.lightgbm.LightGBMTunerCV.html) method. But this is for automatic tuning

**Comment by rohan-gt** [comment]
@guolinke is it possible to add this functionality like @jameslamb mentioned?

**Comment by StrikerRUS** [comment]
> now that that decision has been made I think that LightGBM's scikit-learn interface should adapt to it.

But please note that things might change:
> Nothing really defined yet, but we're actually trying to go in the reverse direction. ... Basically, we're trying to move any parameter that is data-specific into `fit`, or at least out of `__init__`. Though again, nothing definite for now.
   https://github.com/microsoft/LightGBM/issues/2966#issuecomment-611500108

I [expect some changes](https://github.com/microsoft/LightGBM/issues/2966#issuecomment-611521270) in the sklearn public API in the (near) future.

**Comment by StrikerRUS** [comment]
Closed in favor of being in #2302. We decided to keep all feature requests in one place.

Welcome to contribute this feature! Please re-open this issue (or post a comment if you are not a topic starter) if you are actively working on implementing this feature.

**Comment by ClaudioSalvatoreArcidiacono** [comment]
I have been working on this feature lately, it would be great if someone could review it :)

**Comment by lorenzwalthert** [comment]
Timely PR, was looking for exactly this feature 😄 . @ClaudioSalvatoreArcidiacono seems like your PR passes all CI but is blocked for reviewing until you sign your commits the way the maintainers expect it. Would be great if this PR could pass the finish line before new merge conflicts arrive.

**Comment by jameslamb** [comment]
Sorry, this was locked accidentally. Just unlocked it.
