### ISSUE TITLE
LightGBM GPU Python 3.7 CUDA 10.1 Windows Server boost 1.73 success compilation but running error

### ISSUE THREAD

**Issue by dishkakrauch** [microsoft/LightGBM#3316]
## How you are using LightGBM?

Python package

LightGBM component: API

## Environment info

Operating System: Windows Server 2016

CPU/GPU model: GPU Tesla V100 32 GB

C++ compiler version: Visual Studio 16 2019

CMake version: 3.8.1

Java version: None

Python version: 3.7.7

R version: None

Other: None

LightGBM version or commit hash: e9fbd19d7cbaeaea1ca54a091b160868fc5c79ec

## Error message and / or logs

![path](https://user-images.githubusercontent.com/34490641/90540493-f8410000-e189-11ea-837b-510fd7cff6b7.png)
![cmd1](https://user-images.githubusercontent.com/34490641/90540502-fa0ac380-e189-11ea-9e05-59a19bc48e38.png)
![cmd2](https://user-images.githubusercontent.com/34490641/90540505-faa35a00-e189-11ea-869b-d3fa6400dbf0.png)
![cmd3](https://user-images.githubusercontent.com/34490641/90540512-fbd48700-e189-11ea-9b0c-b01f649f5f4f.png)
![jupyter](https://user-images.githubusercontent.com/34490641/90540518-fd05b400-e189-11ea-8bad-0bdc304f38a8.png)

## Steps to reproduce

1. Install as administrator Visual Studio 16 2016 Community including C++ libraries
2. Install as administrator CUDA Tookit 10.1
3. Download CudNN 7.6.5 for CUDA 10.1 and place it here: C:\cuda. Add it to your PATH
4. Download boost https://bintray.com/boostorg/release/boost-binaries/1.73.0#files/1.73.0/binaries, repack and place it here C:\boost\. Add it to your PATH.
5. Install Lightgbm step by step using following commands:

git clone --recursive https://github.com/Microsoft/LightGBM
cd LightGBM
mkdir build
cd build
cmake -DCMAKE_GENERATOR_PLATFORM=x64 -DUSE_GPU=1 -DBOOST_ROOT=C:/boost/boost_1_73_0 -DBOOST_LIBRARYDIR=C:/boost/boost_1_73_0/lib64-msvc-14.2 ..
cmake --build . --target ALL_BUILD --config Release
cd ../python-package
python setup.py install --precompile

**Comment by dishkakrauch** [comment]
@StrikerRUS can you help me out again?

**Comment by StrikerRUS** [comment]
Hi @dishkakrauch !

Sure, let's see what is going wrong.

Compilation itself looks fine.

Could you please add `verbose` param and post produced logs here?
```
model = lgbm.LGBMRegressor(verbose=4, device_type="gpu")
```

**Comment by dishkakrauch** [comment]
Thanks for the fastest reply @StrikerRUS 
Here we go with param verbose=4:
![debug1](https://user-images.githubusercontent.com/34490641/90680894-38c47a80-e26b-11ea-9285-c3fedfc98fbb.png)

**Comment by StrikerRUS** [comment]
Thanks for the logs!

What is your CPU?

I think you could try to play around with `gpu_platform_id` and `gpu_device_id` params: https://lightgbm.readthedocs.io/en/latest/Parameters.html#gpu-parameters.

**Comment by dishkakrauch** [comment]
My CPU is Interl(R) Xeon(R) Gold 6248 2.50 GHz.

I've tried all combinations from -1 to 1 with params `gpu_platform_id` and `gpu_device_id` but unfortunatelly nothing changed.

**Comment by StrikerRUS** [comment]
> but unfortunatelly nothing changed.

For all combinations the error is the same `Unknown OpenCL Error (218)`, right?

Could you please recompile LightGBM with GPU debug mode? Just uninstall the current package and run all steps from your original message, but before that change this line to `#define GPU_DEBUG 4`. It should give additional info from the GPU learner.
https://github.com/microsoft/LightGBM/blob/4d8d289d41d88b2b3d280aff42148dc7324a1c6b/src/treelearner/gpu_tree_learner.cpp#L17

Kindly ping @huanzhang12 for the further inverstigation

**Comment by dishkakrauch** [comment]
![datasets_503819_1433215_debug compile 1](https://user-images.githubusercontent.com/34490641/90859840-a10d7c00-e391-11ea-8d86-12a50e8cdc65.png)
![datasets_503819_1433215_debug compile 2](https://user-images.githubusercontent.com/34490641/90859856-a7035d00-e391-11ea-9079-62e9d6d6365c.png)
![datasets_503819_1433215_debug compile 3](https://user-images.githubusercontent.com/34490641/90859865-ab2f7a80-e391-11ea-8ba5-4f47d336735e.png)

**Comment by dishkakrauch** [comment]
> > but unfortunatelly nothing changed.
> 
> For all combinations the error is the same `Unknown OpenCL Error (218)`, right?
> 
> Could you please recompile LightGBM with GPU debug mode? Just uninstall the current package and run all steps from your original message, but before that change this line to `#define GPU_DEBUG 4`. It should give additional info from the GPU learner.
> https://github.com/microsoft/LightGBM/blob/4d8d289d41d88b2b3d280aff42148dc7324a1c6b/src/treelearner/gpu_tree_learner.cpp#L17
> 
> Kindly ping @huanzhang12 for the further inverstigation

**Comment by dishkakrauch** [comment]
I accidentally closed issue, sorry.
It's reopened now!

@StrikerRUS @huanzhang12

**Comment by dishkakrauch** [comment]
> > Debug installation logs are listed below:
> 
> Now please run your code and output logs should be more verbose.

Sorry, but it's the same...

**Comment by StrikerRUS** [comment]
Could you please double check Jupyter Console output? It is possible that debug messages are still printed into console, while normal logs uses Jupyter Notebook Cells output. Are you sure there is no additional debug info in the console to share with us?

**Comment by dishkakrauch** [comment]
![datasets_503819_1441057_Untitled1](https://user-images.githubusercontent.com/34490641/91157387-ec939300-e6cd-11ea-92a5-d5816e36282d.png)
![datasets_503819_1441057_Untitled](https://user-images.githubusercontent.com/34490641/91157397-f1584700-e6cd-11ea-8818-876b06479df2.png)
@StrikerRUS I've checked Jupyter output, but it's empty except notices that script is saved.

**Comment by StrikerRUS** [comment]
> I've checked Jupyter output, but it's empty except notices that script is saved.

Uh, seems that error happens very early without any additional logs.

My last idea is to try to reinstall another version of NVIDIA driver.

**Comment by dishkakrauch** [comment]
> > I've checked Jupyter output, but it's empty except notices that script is saved.
> 
> Uh, seems that error happens very early without any additional logs.
> 
> My last idea is to try to reinstall another version of NVIDIA driver.

I decided to reinstall literally everything.
Gonna asnwer you in a few days.

**Comment by dishkakrauch** [comment]
@StrikerRUS Everything has become okay after full os reinstalling.
Thanks for your time)

**Comment by StrikerRUS** [comment]
@dishkakrauch I'm glad that reinstallation solved the problem!

Thank you for the info!
