### ISSUE TITLE
segfault in LGBM_BoosterResetParameter()

### ISSUE THREAD

**Issue by glarb** [microsoft/LightGBM#3317]
Hello, in 2.3.2 and 3.0.0 the following segfaults in LGBM_BoosterResetParameter():

int out_num_iterations = 0;
BoosterHandle myBooster = 0;
int ret = LGBM_BoosterLoadModelFromString( model_str, &out_num_iterations, &myBooster );
if ( (!ret) && myBooster ) {
  ret = LGBM_BoosterResetParameter( myBooster, "num_threads=1" );
}

The crash occurs in gpdt.cpp
void GBDT::ResetConfig(const Config* config)
if (config_->forcedsplits_filename != new_config->forcedbins_filename) {
config_ is non-null but bogus, hence the segfault.

No crash in 2.2.3.

For 2.3.2/3.0.0, if I don't call LGBM_BoosterResetParameter() the booster works fine for inferencing.

Thank you for the help.

**Comment by guolinke** [comment]
ping @shiyu1994 for investigating.
@glarb could you provide a reproduce code example. It seems your are using c++ api directly. it will be better if you can share a code repo for reproducibility.

**Comment by glarb** [comment]
Hi, I can reproduce the segfault using tests/c_api_test; is this sufficient?

`
import test_
import ctypes

test_.test_booster()

num_total_model = ctypes.c_long()
booster = ctypes.c_void_p()
test_.LIB.LGBM_BoosterCreateFromModelfile (
  test_.c_str('model.txt'),
  ctypes.byref(num_total_model),
  ctypes.byref(booster)
)

print ( 'this segfaults:', flush=True )
test_.LIB.LGBM_BoosterResetParameter (
  booster, test_.c_str('num_threads=1')
)
`

Thanks.

**Comment by glarb** [comment]
Btw @shiyu1994 it doesn't matter what the parameter string is, or even if it's empty, the segfault always occurs if a reset is attempted after model loading.
Thanks.

**Comment by guolinke** [comment]
@glarb I guess the resetparameter is designed for the training, not for the prediction. 
In prediction, there is not `Ronfig` object in `Booster`, and cause the problem. 
To reset num_threads, you can simply use `omp_set_num_thread()` in c++ code.

**Comment by glarb** [comment]
Thanks @guolinke.

In the c_api.h comments for LGBM_BoosterPredictForMatSingleRowFast():

> Setting up the number of threads is only done once at ``LGBM_BoosterPredictForMatSingleRowFastInit`` instead of at each prediction.

That's my intention of using LGBM_BoosterResetParameter() once before many calls to LGBM_BoosterPredictForMat().  Why bother parsing the parameter in every call to LGBM_BoosterPredictForMat()?

It's nice that the new *FastInit() stuff could be used to configure parameters once for single-row predict, but it seems like LGBM_BoosterResetParameter() is broken for doing something similar for multi-row predict.

**Comment by shiyu1994** [comment]
The segment fault is fixed by #3373.

However, this does not indicates that the number of threads of a GBDT predictor can be controlled by resetting parameters. Currently resetting parameters is only for training. Passing the number of threads to the predict interface is still needed to control the number of threads for prediction.

**Comment by glarb** [comment]
Thank you very much for the fix @shiyu1994!

Why couldn't LGBM_BoosterResetParameter() just create the config if it's missing, so it could be used for prediction too?  It seems wasteful to have to parse the parameters string for each prediction.

If LGBM_BoosterResetParameter() is really only for training, it would be helpful if you also changed the c_api.h doxygen description to
\brief Reset training config for booster.

Thanks again.
