### ISSUE TITLE
[R-package] Support trees with linear models at leaves

### ISSUE THREAD

**Issue by btrotta** [microsoft/LightGBM#3319]
PR #3299 implements trees with linear models at the leaves. I have only tested this with the Python package, and it's possible that some additional changes are needed to get it working for R. To calculate the linear model, we need a Dataset object that contains the full feature data (for numerical features, not needed for categorical), rather than just the binned data. Therefore, when we create the dataset we need to know whether `linear_tree` is True. In the Python interface, we first create the dataset, then call `lgb.train` as follows:
```
train_data = lgb.Dataset(x)
params = {'linear_tree'=True}
est =  lgb.train(params, train_data)
```
So Python doesn't know the dataset parameters (e.g. `linear_tree`, or `max_bin`, etc), until we call `lgb.train`. This works because the dataset is initialised in the first line, but the data isn't actually loaded until `lgb.train` is called. The code that handles this seems quite complex and delicate, and I had to make a couple of small changes to get it to work properly (e.g. to use the refit functionality on an existing model). So I imagine some similar tweaks would be required for the R interface.

Also, the new code requires the Eigen library for linear algebra, which is causing some issues with the R code checks in CI. See this comment for details: https://github.com/microsoft/LightGBM/pull/3299#issuecomment-674703011

**Comment by jameslamb** [comment]
Thanks @btrotta ! If no one else picks this up before me, I'll come back and get it at some point.

For the issue with diagnostic-suppressing pragmas, we might have to do something like we do for the LightGBM ones: https://github.com/microsoft/LightGBM/blob/1804fd12ea240af438a8c2d6c67d6a0f9bdf4c5e/build-cran-package.sh#L45

**Comment by jameslamb** [comment]
I just added this to #2302 in the R package section, so based on our convention I'll close it.

Anyone reading this issue...please leave a comment if you'd like to create a pull request for it and I can re-open it!

**Comment by jameslamb** [comment]
When this is picked up, it should also get changes similar to https://github.com/microsoft/LightGBM/pull/3685.

1. `build_r.R` and `build-cran-package.sh` should be modified to only copy in the specific parts of Eigen that are needed (see `MANIFEST.in` changes in #3685) 
2. `-DEIGEN_MPL2_ONLY` should be added to `LGB_CPPFLAGS` in `R-package/configure.ac` and `R-package/configure.win`
