### ISSUE TITLE
is_unbalance parameter - documentation

### ISSUE THREAD

**Issue by mglowacki100** [Microsoft/LightGBM#332]
I've noticed following parameter:
`is_unbalance : bool `- Is unbalance for binary classification
As far I understand, when set to True, then there is some algorithm in LightGBM that deals with  imbalanced classes for binary classification. I didn't find any information what method is used.
Is it for example SMOTE from here [https://github.com/scikit-learn-contrib/imbalanced-learn]() or something completly different?
Btw. xgboost doesn't have this parameter, so it could be interesting to compare performance on dataset with unbalanced classes. Of course if I'm correct about meaning of this parameter.

**Comment by guolinke** [comment]
refer to this paper: 
Burges, Christopher JC. "From ranknet to lambdarank to lambdamart: An overview." Learning 11.23-581 (2010): 81.

**Comment by mglowacki100** [comment]
Thank you!
