### ISSUE TITLE
[Enhancement] Add default ranges for hyperparameter tuning

### ISSUE THREAD

**Issue by rohan-gt** [microsoft/LightGBM#3321]
Is it possible to add good default conservative ranges for each of the hyperparameters for tuning purposes in the documentation? By this I mean something like [0, 100] instead of [0, Infinity] based on results from testing on a lot of different datasets so that these ranges can directly be used for tuning without worrying about what the right values should be each time?

Another alternative could be to embed this info into the algorithm class itself so that HPO packages can directly pick it up

**Comment by StrikerRUS** [comment]
Hi @rohan-gt !
We already have a such feature request: #2617. You can vote for that in our feature request hub: https://github.com/microsoft/LightGBM/issues/2302#issuecomment-674561882.
