### ISSUE TITLE
lightgbm.sklearn estimators pass sklearn.utils.check_is_fitted() when fitted

### ISSUE THREAD

**Issue by tcleberg** [microsoft/LightGBM#3325]
## Summary

Currently, when fitted, these estimators raise errors when `sklearn.utils.check_is_fitted()` after having their `fit()` methods called. This causes problems with anything that uses this check- for example, creating [partial dependence plots](https://scikit-learn.org/0.18/auto_examples/ensemble/plot_partial_dependence.html). 

## Motivation

To have the `lightgbm.sklearn` estimators operate as expected of estimators within the sklearn API.

## Description

When `sklearn.utils.check_is_fitted()` is called on a `ightgbm.sklearn` estimator, "True" is returned.

## References

[sklearn.utils.check_is_fitted source code](https://github.com/scikit-learn/scikit-learn/blob/0fb307bf3/sklearn/utils/validation.py#L955)

One option for solving this would be to create a new attribute on these classes that ends in an underscore and does not begin in two underscores- for example `self.is_fitted_`

**Comment by StrikerRUS** [comment]
Please refer to https://github.com/microsoft/LightGBM/issues/3014#issuecomment-618056991.
