### ISSUE TITLE
[R-package] hex logo

### ISSUE THREAD

**Issue by jameslamb** [microsoft/LightGBM#3331]
now that a logo has been introduced (#3327 ), we should add a hex logo for the R package! These are very very popular in the R world. For example, see RStudio's collection here: https://github.com/rstudio/hex-stickers

I tried creating some tonight in R using the `{hexSticker}` package. That is working really well! here's an example:

![image](https://user-images.githubusercontent.com/7608904/90947747-e2d40c00-e3fd-11ea-9472-fc79e1a20bd9.png)

```r
hexSticker::sticker(
    "docs/logo/LightGBM_logo_black_text_medium.png"
    , package = ""
    , p_size = 9.5
    , p_y = 1.35
    , s_x = 1
    , s_y = 1.0
    , s_width = 0.9
    , filename = "logo/lightgbm-r-hex.png"
    , h_fill = "white"
    , h_color = "#1B9AD7"
    , h_size = 0.9
    , white_around_sticker = FALSE
    , dpi = 600
)
```

But here is my problem...in the R community, the name on the logo is always the name of the package. Our R package is called `lightgbm`, not `LightGBM`.

@StrikerRUS @guolinke what do you think about making a version of the logo that says `lightgbm` instead of `LightGBM`?

**Comment by guolinke** [comment]
@jameslamb 
l think unifying it to the `LightGBM` is better. The python package is also name `lightgbm`, but with this logo. 
I think XGBoost also only have one logo `XGBoost`. 
BTW, for hex logo, maybe it is better to use the black background?

**Comment by jameslamb** [comment]
Unlike in Python, the hex sticker practice in the R community is broadly followed, and they're always the name of the package. I feel pretty strongly that our hex sticker should be the package name. I don't believe there is a hex sticker for XGBooster's R package.

I can try one with the black backhround so you can see it! Will add one here shortly.

**Comment by guolinke** [comment]
@jameslamb okay, I see. It seems we can have a better design for the tex logo, after checking https://github.com/rstudio/hex-stickers . I will propose a new one here in several days.

**Comment by jameslamb** [comment]
oh sure! sounds good, thank you

**Comment by StrikerRUS** [comment]
@jameslamb 

> Could you or @guolinke create a version of logo_black_font.png that has the lowercase lightgbm?

Sorry, I have no font to change the wording. I just remember @guolinke said that it is 
> For the font, it is the slight costumed version of segoe UI, the same as in Microsoft logo.

but I don't know what means "slight costumed".

**Comment by jameslamb** [comment]
looking forward to @guolinke 's designs, I think we can have some fun with this! For inspiration, here is what it looks like with a black background instead

![lightgbm-r-hex](https://user-images.githubusercontent.com/7608904/91109405-78f77480-e640-11ea-928c-4620f351ed13.png)


```
hexSticker::sticker(
    "docs/logo/LightGBM_logo_grey_text_medium.png"
    , package = ""
    , p_size = 9.5
    , p_y = 1.35
    , s_x = 1
    , s_y = 1.0
    , s_width = 0.9
    , filename = "lightgbm-r-hex.png"
    , h_fill = "black"
    , h_color = "#1B9AD7"
    , h_size = 0.9
    , white_around_sticker = FALSE
    , dpi = 600
)
```
