### ISSUE TITLE
How to use C_API(with category feature) to predict the data from stdin

### ISSUE THREAD

**Issue by veridone** [microsoft/LightGBM#3334]
I want to use lightgbm like "cat file | ./lightgbm config=test.conf"
I has **category feature** in the model
I searched website to find a demo to use lightdbgm c api, but do not find
Use the LGBM_BoosterPredictForMat can covert data to predict matrix, But how to pass the category feature to the function?

**Comment by guolinke** [comment]
@veridone 
currently, we only support the prediction from the normal file, the pipe input is not supported yet.
For the categorical features, as long as your model is trained by the categorical features, it will be auto-used in prediction time.

**Comment by guolinke** [comment]
If you want to implement the prediction from stdin, you can follow this function:
https://github.com/microsoft/LightGBM/blob/ceb6265fba14be11b9ef086018d9cc67ff7f5450/src/c_api.cpp#L421-L447
the replace the omp-for-loop to line-by-line prediction.

**Comment by guolinke** [comment]
another solution is using the single-line prediction api.

https://github.com/microsoft/LightGBM/blob/ceb6265fba14be11b9ef086018d9cc67ff7f5450/src/c_api.cpp#L2114-L2152

you can use `LGBM_BoosterPredictForMatSingleRowFastInit` to create a prediction interface, and then call `LGBM_BoosterPredictForMatSingleRowFast` to predict for one line.
