### ISSUE TITLE
please, update conda-forge lightgbm package!

### ISSUE THREAD

**Issue by antonkulaga** [microsoft/LightGBM#3343]
Please, update conda-forge package to 3.x so we can upgrade our code smoothly!

**Comment by guolinke** [comment]
refer to https://github.com/conda-forge/lightgbm-feedstock/pull/23
it will be updated automatically.

**Comment by StrikerRUS** [comment]
Sorry, but we do not maintain conda package. Also, that PR has been merged, so LightGBM is `3.0` in `conda-forge` channel now.
