### ISSUE TITLE
[R-package] All functions should have explicit return statements

### ISSUE THREAD

**Issue by jameslamb** [microsoft/LightGBM#3352]
## Summary 

In R, the `return` statement is not strictly required in functions.

```r
# this returns NULL
gives_nothing <- function(x, y){
    print(x)
    print(y)
}

# this returns the value of n
gives_sum <- function(x, y){
    n <- x + y
    n
}
```

This means that it can sometimes be difficult to understand, from looking at the code, what a function will return.

## How to close this issue

To close this issue, make sure that every function in the R package is explicitly using a `return` statement. The R package's code can all be found in `R-package/R`.

For functions which look like they should not return anything, please add a new statement at the end:

```r
    return(invisible(NULL))
```

## How this improves LightGBM

This fix will make the R package a little bit more explicit, reducing the risk of mistakes during future development.

**Comment by Juniper-23** [comment]
I am fairly new to R but with whatever I have learnt so far I believe I can be of some help here :)

**Comment by jameslamb** [comment]
thanks @Juniper-23 ! I just assigned this to you so no one else will take it. It's not urgent so take your time. Let me know if you have any questions.

**Comment by Juniper-23** [comment]
@jameslamb Thanks! This would help :)

**Comment by jameslamb** [comment]
Hi @Juniper-23 , do you need any help with this? No rush at all, just want to help if you are stuck.

**Comment by Juniper-23** [comment]
Hi @jameslamb, not as of now. But, I would definitely need some help.

**Comment by jameslamb** [comment]
ok no problem. `@` me whenever you need!

**Comment by jameslamb** [comment]
@Juniper-23 do you think you'll have time to help us with this in the next week or two?

If not, I'd like to open it back up for someone else to come contribute.

**Comment by jameslamb** [comment]
@Juniper-23 I let @zenggyu take this since it's been open for a while, but I hope you'll consider coming back to LightGBM to contribute in the future!
