### ISSUE TITLE
Hacktoberfest Issues + "good first issue" issues

### ISSUE THREAD

**Issue by jameslamb** [microsoft/LightGBM#3353]
## Summary

Hacktoberfest 2020 starts in a few weeks (https://hacktoberfest.digitalocean.com/). This is an annual event where GitHub and DigitalOcean promise to send people shirts and stickers if they make 5 pull requests into open source projects.

On other project's I've worked on, I have had a really good experience with contributors coming in during this time to fix small issues.

These can be things like:

* fixing typos or ambiguities in documentation
* reducing duplication in documentation
* writing unit tests
* cutting the size of Docker containers by refactoring Dockerfiles

**maintainers**: Can you please think about issues which could be attractive to contributors who are not very familiar with LightGBM, and which are fairly small and self-contained? If you think of such issues, tag them with `good first issue` and the new `hacktoberfest` label I just created.

For an example, see #3352 that I just created. I'm planning to create more for the R package this weekend.

During October, GitHub will have a special page where they aggregate labels tagged `hacktoberfest`. The site https://goodfirstissues.com/ does this year-round for issues tagged `good first issue`. Both of these can be an effective way to get more outside contributors to come and work on LightGBM, reducing the maintenance burden for maintainers.

## References

* https://hacktoberfest.digitalocean.com/
* https://goodfirstissues.com/

**Comment by guolinke** [comment]
I think we can revise the feature request hub, and label some of them.

**Comment by jameslamb** [comment]
for these aggregators, it's important that each individual issue has the `good first issue` and `hacktoberfest` labels. So a section in #2302 titled "Good First Issue" wouldn't work.

**Comment by guolinke** [comment]
@jameslamb BTW, do the labeled issues need to be open? since most `feature request` issues are closed.

**Comment by jameslamb** [comment]
yes, they need to be open

**Comment by hcho3** [comment]
FYI Hacktoberfest now switched to opt-in: https://hacktoberfest.digitalocean.com/hacktoberfest-update. You should add `hacktoberfest` topic to the repository to opt in. Example:
![Screen Shot 2020-10-02 at 9 38 50 PM](https://user-images.githubusercontent.com/2532981/94983440-aa911480-04f7-11eb-9d10-1333179a9d06.png)

**Comment by jameslamb** [comment]
thank you! I juuuuust saw https://github.com/digitalocean/hacktoberfest/pull/596 on Twitter

I just added the `hacktoberfest` label to the repo

**Comment by jameslamb** [comment]
commenting in case any possible contributors have subscribed to this issue...I've added a new "good first issue" for the R package: #3471
