### ISSUE TITLE
[docs] update list of winning solutions

### ISSUE THREAD

**Issue by jameslamb** [microsoft/LightGBM#3357]
This project's documentation includes a list of winning solutions for machine learning competitions which used LightGBM.

https://github.com/microsoft/LightGBM/tree/master/examples#machine-learning-challenge-winning-solutions

With one exception (), this has not been updated since December 2019.

## How to close this issue

Look through "completed" competitions (from December 2019 to now) at https://www.kaggle.com/competitions.

![image](https://user-images.githubusercontent.com/7608904/92319025-af86a500-efd9-11ea-9183-c911085faef7.png)

For each competition, look through the message boards to find posts about the 1st, 2nd, or 3rd place solutions. If these used LightGBM (even as part of an ensemble), create a pull request which adds them to https://github.com/microsoft/LightGBM/blob/master/examples/README.md.

**Comment by Juniper-23** [comment]
Hi, I can help with the above. I need a quick clarification, from my understanding the above issue requires me to check for the usage of LightGBM in the solution description/discussions of the first three winning entries?

**Comment by guolinke** [comment]
@Juniper-23 
yeah, you can review the shared winning solutions in Kaggle/KDD, etc.

**Comment by StrikerRUS** [comment]
Can we close this issue? I think the majority of solutions from Kaggle are covered right now.

**Comment by jameslamb** [comment]
yeah I think so
