### ISSUE TITLE
[R-package] submit hex logo to hexb.in?

### ISSUE THREAD

**Issue by jameslamb** [microsoft/LightGBM#3361]
In #3331 , we added a hex logo for the R package. @guolinke @StrikerRUS any objection to me adding a PR to add this to http://hexb.in/?

Many other R packages are there including `{ggplot2}`, `{purrr}`, and `{data.table}`.  This is a place that people go to find standard-size hexagon logos when they want to print up laptop stickers. I think having the `{lightgbm}` logo there could be another way to raise awareness of the project and maybe to get a few people to create stickers and further raise awareness of it.

![image](https://user-images.githubusercontent.com/7608904/92348233-1bc7de00-f098-11ea-8274-ecbe5f9bdcb5.png)

**Comment by StrikerRUS** [comment]
> any objection

No any objections from me. Please do it!

**Comment by guolinke** [comment]
@jameslamb please move forward 😺

**Comment by StrikerRUS** [comment]
Their GitHub looks like they don't add new packages promptly 😢 :

![image](https://user-images.githubusercontent.com/25141164/92400717-05bc2b00-f135-11ea-9a05-4b6f26965d7e.png)

![image](https://user-images.githubusercontent.com/25141164/92400832-37cd8d00-f135-11ea-8e4a-ac5c79e69ffc.png)


Last merged PR was in April and some packages had been waiting for months: https://github.com/maxogden/hexbin/pull/266 (submitted 31 Dec 2019 and approved (right after the first review) 29 Mar)

**Comment by jameslamb** [comment]
@StrikerRUS yeah I saw that too :/

Thankfully we have  no urgency around this. I'll open the PR and link it here, it's ok if it takes a few months

**Comment by jameslamb** [comment]
ok I've added https://github.com/maxogden/hexbin/pull/280, so I think we can close this issue and move the discussion there. I saw clicking around in that repo that the maintainers sometimes ask for more information on the license and ownership of the logo, so I tagged both of you.
