### ISSUE TITLE
[R-package] allow use of MPI for distributed training

### ISSUE THREAD

**Issue by esvhd** [microsoft/LightGBM#3364]
## Summary

As @jameslamb suggested in his very helpful replies to #3354 , adding a switch in `build_r.R` script to enable GPU and MPI would be very helpful. 

## Motivation

Enable MPI support for R packages. A switch is already available for python builds. 

I'll let more capable minds to comment on the pros and cons for MPI vs sockets, and particularly when it comes to training. 

## Description

Current documentation for R package build might be missing some small details on how to enable MPI. See discussion in #3354 . 
@jameslamb went through this and successfully managed to build the package with both GPU and MPI switched on.

**Comment by jameslamb** [comment]
Thanks for reporting this! I'll close this for now and add it to #2302 , where we keep all feature requests. Anyone reading this, you're welcome to add this feature!

I also want to add some additional information. The goal of this feature is to provide an experience like:

```r
Rscript build_r.R --use-mpi
```

That should add `-DUSE_MPI=ON` to `cmake_flags` in `R-package/src/install.libs.R`.

Someone picking this up might also want to explore how this could be used for the CRAN package. A `configure` argument could be added so people can do something like this.

```shell
sh build-cran-package.sh
R CMD INSTALL lightgbm_3.0.0.tar.gz --configure-args='--use-mpi'
```

You can see more information on how to update the CRAN package at https://github.com/microsoft/LightGBM/blob/master/R-package/README.md#changing-the-cran-package. But getting this working for the CRAN package is not required.

**Comment by StrikerRUS** [comment]
I might be wrong, but I cannot find any references from R codebase to `LGBM_NetworkInit()` cpp function. If that's true, it means exposing `--use-mpi` flag will be not enough because actually R-package lacks support of parallel learning (even pure socket one). To enable it something similar to 
https://github.com/microsoft/LightGBM/blob/9eeac3c7a5f5df49bf5435de8bed30d32a0f9b53/python-package/lightgbm/basic.py#L2347-L2350

should be done.

**Comment by jameslamb** [comment]
you're correct.
