### ISSUE TITLE
How to install gpu-LightGBM quickly (linux)

### ISSUE THREAD

**Issue by Jie-Yuan** [microsoft/LightGBM#3365]

**Comment by StrikerRUS** [comment]
Here is the guide how to install GPU version for Linux: https://lightgbm.readthedocs.io/en/latest/Installation-Guide.html#id17

FYI, after resolving https://github.com/microsoft/LightGBM/pull/3144#issuecomment-687650386 we possibly will provide a separate Python wheel with GPU-enabled acceleration.
