### ISSUE TITLE
Create Dataset from Arrow format

### ISSUE THREAD

**Issue by jameslamb** [microsoft/LightGBM#3369]
## Summary

[Apache Arrow](https://github.com/apache/arrow) is an open source columnar in-memory storage format that's well-suited to tabular data. It offers efficient data loading from files or other input streams, and zero-copy data sharing between languages.

## Motivation

I think that this feature could allow for faster data loading, esp. from the parquet and CSV file formats. It would also allow directly training on Arrow tables, so we might be able to avoid some data copying in language wrappers (e.g. converting to a `pandas` data frame or R `data.frame`).

`pyarrow` offers a fast, efficient Parquet reader. I believe that reading from Parquet files directly into Arrow, then being able to efficiently create a LightGBM Dataset from that `pyarrow` table, would allow for faster I/O and better memory efficiency by avoiding the need to ever create a `pandas` data frame: https://arrow.apache.org/docs/python/generated/pyarrow.parquet.read_table.html. 

## Description

I'm admittedly not very experienced with C++, so maybe others can expand this description. But basically, I think it would involve adding a `LGBM_DatasetCreateFromArrow` similar to `LGBM_DatasetCreateFromCSV`: https://github.com/microsoft/LightGBM/blob/82e2ff7a018f2466f8102c80a7bafb9324238d19/src/c_api.cpp#L1245

Arrow is a fairly heavy dependency (and `pyarrow` in Python / `{arrow}` in R, by extension), so an implementation should also explore how to make these optional for users who do not need the Arrow features.

## References

There is an in-progress PR to add this feature to XGBoost: https://github.com/dmlc/xgboost/pull/5667

Spark added support for Arrow as a memory representation in pyspark 3 years ago: https://arrow.apache.org/blog/2017/07/26/spark-arrow/.

**Comment by StrikerRUS** [comment]
> Spark added support for Arrow as a memory representation in pyspark 3 years ago:

Does it mean that right now one can use MMLSpark (https://github.com/Azure/mmlspark) for Arrow + LightGBM (similarly to parquet https://github.com/microsoft/LightGBM/issues/1286#issuecomment-517380041)?

**Comment by jameslamb** [comment]
possibly! But that definitely does not satisfy this feature. Spark is a heavy dependency that many users are unlikely to have access to.

**Comment by guolinke** [comment]
I think @shiyu1994 can help with this. He has some ideas to refine the dataset class recently.

**Comment by yalwan-iqvia** [comment]
> > Spark added support for Arrow as a memory representation in pyspark 3 years ago:
> 
> Does it mean that right now one can use MMLSpark (https://github.com/Azure/mmlspark) for Arrow + LightGBM (similarly to parquet [#1286 (comment)](https://github.com/microsoft/LightGBM/issues/1286#issuecomment-517380041))?

I think it would be other way round. If LightGBM implemented datasetFromArrow, it would probably be useful to speed up / improve efficiency from within MMLSpark

**Comment by StrikerRUS** [comment]
Closed in favor of being in #2302. We decided to keep all feature requests in one place.

Welcome to contribute this feature! Please re-open this issue (or post a comment if you are not a topic starter) if you are actively working on implementing this feature.

**Comment by StrikerRUS** [comment]
For the reference: Parquet data reader implementation in XGBoost with optional Arrow dependency at compile time.
https://github.com/dmlc/dmlc-core/pull/653
https://github.com/dmlc/dmlc-core/blob/5eaff7643a88949c81af1e5de11945632920bf96/CMakeLists.txt#L71-L73

**Comment by jameslamb** [comment]
Linking the eventual XGBoost implementation: https://github.com/dmlc/xgboost/pull/7512

**Comment by jameslamb** [comment]
Sorry, this was locked accidentally. Just unlocked it.

**Comment by jameslamb** [comment]
Linking some related PRs:

* #6034
* #6100
* #6140
* #6163
* #6166
* #6167
* #6168
* #6210

And this related discussion about how Arrow support enables `polars` support: #6204
