### ISSUE TITLE
pip with GPU option installs to .local instead of conda environment path 

### ISSUE THREAD

**Issue by ticoneva** [microsoft/LightGBM#3383]
## How you are using LightGBM?

LightGBM component:  Python package

## Environment info

Operating System: Ubuntu 20.04.1

CPU/GPU model: HPC cluster with AMD Zen-2 CPUs and NVIDIA Pascal GPUs

CMake version: 3.14.0

Python version: Anaconda 3.8

LightGBM version or commit hash: 3.0.0

## Steps to reproduce

1. pip install lightgbm \
--install-option=--gpu \
--install-option="--opencl-include-dir=/usr/local/cuda/include/" \
--install-option="--opencl-library=/usr/local/cuda/lib64/libOpenCL.so" \
--install-option="--boost-include-dir=/usr/include/boost/" \
--install-option="--boost-librarydir=/usr/lib/x86_64-linux-gnu/"
2. lib_lightgbm.so will be under ~/.local/lib/python3.8/site-packages/lightgbm/ instead of the actual conda environment path.

**Comment by StrikerRUS** [comment]
We do not manipulate installation paths. It is definitely pip or/and conda issue. I believe your default pip comes from system folder instead of conda's one. Please run commands and see

```
which python
which pip
```

BTW, why do you need a separate Python 3.8 installation along with conda on your machine?
