### ISSUE TITLE
Lightgbm.cv doesn't work right with random forest boosting

### ISSUE THREAD

**Issue by Merudo** [microsoft/LightGBM#3387]
Lightgbm.cv doesn't returns the expected cross-validation result for a `boosting: 'rf'` (random forest) model.

It returns the CV results for each tree individually, instead of the overall CV for the random forest. For example with 300 trees, CV will return 300 results instead of 1...

## Environment info

Operating System:

CPU/GPU model:

C++ compiler version:

CMake version:

Java version:

Python version:

R version:

Other:

LightGBM version or commit hash:

**Comment by jameslamb** [comment]
hi @Merudo , thanks for using `LightGBM`! Are you able to provide some code that reproduces this issue, preferably with random data?

Can you also please answer the questions that showed up when you clicked "new issue"? I've just added them to your description.

**Comment by guolinke** [comment]
I think the return of 300 results in cv is expected. it represents the average results over different folds, in 300 iterations. 
In GBDT model, it also returns 300 results.
cc @StrikerRUS to confirm this.

**Comment by StrikerRUS** [comment]
Yes, results' structure is identical for all boosting types.
