### ISSUE TITLE
[R-package] use keyword arguments for all internal function calls

### ISSUE THREAD

**Issue by jameslamb** [microsoft/LightGBM#3390]
## Summary

Today in the R package, there are a lot of internal function calls which use only positional arguments. Change them to use keyword arguments for extra safety.

I've added this issue to provide a small, focused contribution opportunity for [Hacktoberfest 2020](https://hacktoberfest.digitalocean.com/) participants. If you are an experienced open source contributor, please leave this for beginners and consider contributing [on a different backlog item](https://github.com/microsoft/LightGBM/issues).

## Motivation

Using positional arguments in internal code is dangerous, because it can allow mistakes to slip through or can lead to confusing errors.

This is especially dangerous for cases where the values you'd pass to two parameters take on similar values. For example, in `lightgbm()`, `eval_freq` and `early_stopping_rounds` are both positive integers and can take on similar values. You might not known, unless you're very careful, that you accidentally specified them in the wrong order.

## How to Contribute

To help with this issue, propose a pull request which replaces uses of positional arguments in the R package with keyword arguments.

That means changing calls like this:

```r
# before
folds <- generate.cv.folds(
    nfold
    , nrow(data)
    , stratified
    , getinfo(data, "label")
    , getinfo(data, "group")
    , params
)

# after
folds <- generate.cv.folds(
    nfold = nfold
    , nrows = nrow(data)
    , stratified = stratified
    , label = getinfo(data, "label")
    , group = getinfo(data, "group")
    , params = params
)
```

1. Only change code in `R-package/R/`
1. Before submitting your PR, re-generate the documentation. Be sure you have `{roxygen2}` 7.1.1 installed. If you have any issues with this, just ask when you submit your PR and I can regenerate the docs for you
    ```shell
    sh build-cran-package.sh
    R CMD INSTALL --with-keep.source lightgbm_3.*.tar.gz
    cd R-package
    Rscript -e "roxygen2::roxygenize(load = 'installed')"
    ```
1. Do not modify any calls to `lgb.call()`
1. Do not worry about any function calls from the standard library (like `print()`,  `length()`, `is.character()`, etc.)
1. If adding these arguments makes lines too long, use comma-first style with one argument per line
    ```r
    result <- some_function(
        arg1 = TRUE
        , arg2 = 4
        , arg3 = "hello"
        , ...
    )
    ```

Refer to #3391 as an example. If you have any questions, tag me on this issue and I can help.

## Assignments

~If you are interested, please comment on this issue and indicate which file in `R-package/R/` you'd like to help on. **PLEASE ONLY TAKE ONE FILE**, so that multiple people can use this as a learning experience.~

~This issue is not urgent, so you can claim a file now and not contribute until [Hacktoberfest](https://hacktoberfest.digitalocean.com/) begins on October 1st.~

The list below tracks the assignments and completions so far.

* ~aliases.R~
* ~callback.R~ - @philip-khor (#3430) 
* ~lgb.Booster.R~ - @Pey-crypto (#3496)
* lgb.Dataset.R  - @zenggyu (#3617)
* ~lgb.Predictor.R~ - @AnshuTrivedi (#3464) 
* lgb.convert_with_rules.R - @zenggyu (#3617)
* lgb.cv.R - @zenggyu (#3617)
* lgb.importance.R - @zenggyu (#3617)
* lgb.interprete.R - @zenggyu (#3617)
* ~lgb.model.dt.tree.R~ - @zenggyu (#3605)
* lgb.plot.importance.R - @zenggyu (#3617)
* lgb.plot.interpretation.R - @zenggyu (#3617)
* ~lgb.train.R~ - @iadi7ya (#3452)
* lgb.unloader.R - @zenggyu (#3617)
* ~lightgbm.R~
* metrics.R - @zenggyu (#3617)
* readRDS.lgb.Booster.R - @zenggyu (#3617)
* ~removed.R~
* saveRDS.lgb.Booster.R - @zenggyu (#3617)
* ~utils.R~ - @mfrasco6 (#3604) 

Thanks for contributing to `LightGBM`!

**Comment by philip-khor** [comment]
can I claim callback.R please?

**Comment by iadi7ya** [comment]
Hi @jameslamb , I'm working on `lgb.train.R`. Thanks!

**Comment by jameslamb** [comment]
thanks @iadi7ya ! I appreciate you taking the time to contribute to `{lightgbm}`!

**Comment by AnshuTrivedi** [comment]
@jameslamb  I am working on `lgb.Predictor.R`

**Comment by Pey-crypto** [comment]
can i claim lgb.Booster.R?

**Comment by jameslamb** [comment]
> can i claim lgb.Booster.R?

yes please!

**Comment by zenggyu** [comment]
Hi, @jameslamb , I am working on `lgb.model.dt.tree.R`.

**Comment by jameslamb** [comment]
Thanks! Now that Hacktoberfest is over we'd like to finish this task, so feel free to take several files if you'd like.

**Comment by mfrasco6** [comment]
Hi, Mr. @jameslamb, I am working on `utils.R`.

**Comment by zenggyu** [comment]
Since Hacktoberfest is over, I want to claim all of the rest of files.

**Comment by jameslamb** [comment]
they're yours, thanks! Please bunch the contributions into one or two pull requests.

**Comment by georgiazoller** [comment]
I am running a multivariate regression using my own data from my qualtrics survey. In the survey I did a treatment (author vs no author), with outcome being the dependent, and age and party being the independent variables. This is my code: 
model.1 <- lm(Outcome ~ NoAuthor + PARTY + AGE, data=Party_Lines)
summary (model.1)

I then get this error: 

Error in lm.fit(x, y, offset = offset, singular.ok = singular.ok, ...) : 
  NA/NaN/Inf in 'y'
In addition: Warning message:
In storage.mode(v) <- "double" : NAs introduced by coercion

Help

**Comment by jameslamb** [comment]
@georgiazoller that does not look related to LigtGBM. If it is, please open a new issue instead of commenting on this one.
