### ISSUE TITLE
[Feature]Interface for data layers

### ISSUE THREAD

**Issue by chivee** [Microsoft/LightGBM#34]
I would like to open this issue for tracking progress on data/model in-memory transfer interface development.

the interface should offering:
- serialization from [memory, disk] to [memory,disk] for data
- access data in training/validating process
- porting libraries for other tools

**Comment by ArdalanM** [comment]
Also Interested. 
We made a python wrapper and so far, the main drawback is the read/write to disk before calling lightgbm.

**Comment by guolinke** [comment]
I add the the draw of c_api definition at [here](https://github.com/guolinke/LightGBM/blob/master/include/LightGBM/c_api.h)

**Comment by chivee** [comment]
please refer to #56 to see the draft

**Comment by guolinke** [comment]
I think this is finished , refer to #61.
Let us continue to implement Python/R package and some tests.
