### ISSUE TITLE
how to change lightgbm josn model to sql ？

### ISSUE THREAD

**Issue by Liansy** [microsoft/LightGBM#3400]

**Comment by Liansy** [comment]
I want to parse the JSON rule format of the lightgbm model into SQL statements for deployment on the database. Is there any good solution?

**Comment by jameslamb** [comment]
Hi @Liansy , thanks for using `LightGBM`! We don't have any code in this project that allows you to code-generate SQL from a trained model.

You can look through the [list of LightGBM extensions](https://github.com/microsoft/LightGBM#external-unofficial-repositories) to see if any of them have that type of functionality.

I know that such projects exist generally, like [`sqlflow`](https://github.com/sql-machine-learning/sqlflow), but I'm not aware of any that have support for LightGBM.

That project supports XGBoost (https://github.com/sql-machine-learning/sqlflow/blob/253578d4d2cb4e96f2162d77b97a31c9a0f6af81/doc/design/xgboost_on_sqlflow.md), so maybe if you raise an issue there they would also support LightGBM models.

**Comment by jameslamb** [comment]
For my own knowledge, could you explain why you're looking to use a SQL representation instead of, say, Python or C++?

**Comment by Liansy** [comment]
> For my own knowledge, could you explain why you're looking to use a SQL representation instead of, say, Python or C++?
In the process of project deployment, we usually use Python as a model building tool. However, when we finally deploy to the application, we can only deploy through hive SQL. We can't obtain the permission to use Java or C + +. Therefore, we want to parse the JSON model results saved by lightgbm into SQL case when.

**Comment by jameslamb** [comment]
I suspected that might be the case, thank you!

Unfortunately we do not support this today and I'm not aware of a project that does. I recommend opening an issue in https://github.com/sql-machine-learning/sqlflow and linking to this issue (so others who find this via search will know to go there).

@StrikerRUS @guolinke do you agree with that? Or do you think we should add this as a feature request in our backlog here? If we add it as a feature request here, I think it should be limited to scoring and we should not attempt training in SQL like `sqlflow` has done.

**Comment by Liansy** [comment]
Thank you！

**Comment by StrikerRUS** [comment]
@jameslamb I agree with you. It looks like a task for special libraries focused on ML with SQL, not for LightGBM main repo.

**Comment by jameslamb** [comment]
Ok great, I can see you've opened https://github.com/sql-machine-learning/sqlflow/issues/2942 so I will close this.
