### ISSUE TITLE
Expose number of bins used by the model while binning continuous features to C API

### ISSUE THREAD

**Issue by narendramukherjee** [microsoft/LightGBM#3406]
Hi,

I am using the sklearn api to lightgbm, and am wondering if there's a way I can get the number of bins (defined to be < max_bin) that the model creates while binning continuous features? I found the cpp code that counts up the bins (in `num_bin_`) here: https://github.com/Microsoft/LightGBM/blob/7a89d0054bcf0db9f96af3c53a078b6aa3152efe/src/io/bin.cpp#L207-L401 , going from #2063 , but is there a way to get this number from a trained model for each feature it binned?

Thanks in advance for any help!

**Comment by guolinke** [comment]
sorry, this api is not exposed. Exposing it is relatively easy, contribution is very welcome!

**Comment by narendramukherjee** [comment]
Thanks @guolinke - can you give me some pointers on how to go about exposing this part of the api? I can then make an appropriate PR

**Comment by guolinke** [comment]
you can add the related function in c_api.h and c_api.cpp.
like https://github.com/microsoft/LightGBM/blob/ceb6265fba14be11b9ef086018d9cc67ff7f5450/src/c_api.cpp#L1486-L1492

**Comment by StrikerRUS** [comment]
Closed in favor of being in #2302. We decided to keep all feature requests in one place.

Welcome to contribute this feature! Please re-open this issue (or post a comment if you are not a topic starter) if you are actively working on implementing this feature.

**Comment by jmoralez** [comment]
Reopening since I'm working on this.
