### ISSUE TITLE
Python scikit-learn predict_proba with objective='cross_entropy_lambda' returns probabilities > 1

### ISSUE THREAD

**Issue by econkc** [microsoft/LightGBM#3407]
I'm running my model on Mac 
Python version 3.0.0

LGBMClassifier(random_state=42, data_seed=42, objective='cross_entropy_lambda')

the predict_proba() returns value > 1.

**Comment by guolinke** [comment]
Refer to https://github.com/microsoft/LightGBM/blob/2870490073c537eeb3648893257be8692b63148c/src/objective/xentropy_objective.hpp#L219-L230

**Comment by econkc** [comment]
Thank you for a quick response

**Comment by StrikerRUS** [comment]
Also, it is worth to mention that `xentlambda` is listed in a separate application type. It is neither binary classification, nor multiclass classification problem. So, I think this objective should be used with general `LGBMModel` class, where `predict_proba()` method is unavailable, but not with `LGBMClassifier` to not get confusing results like described above.

![image](https://user-images.githubusercontent.com/25141164/94155230-64004200-fe87-11ea-9a39-42e93f46bf07.png)
