### ISSUE TITLE
Traning model on multi GPUs?

### ISSUE THREAD

**Issue by Brian0906** [microsoft/LightGBM#3416]
I prefer to use multi GPUs to speed up traning model, but there is only few information about this in the document. Does lightGBM works well on multi GPUs ?

**Comment by StrikerRUS** [comment]
Multi-GPU support has been introduced several days ago with new CUDA compilation option. That is why there is no info about this yet.

Early tests show it can work with 4 GPUs: https://github.com/szilard/GBM-perf/issues/12#issuecomment-699144433.
