### ISSUE TITLE
Please explain input variables of LIGHTGBM_EXPORT Dataset* ConstructFromSampleData

### ISSUE THREAD

**Issue by nathans3** [microsoft/LightGBM#3427]
Hello I am trying to use the method below. The meaning of some of the input variables is not clear. 
Can you please explain the meaning of the input variable? Thank you! 

LIGHTGBM_EXPORT Dataset* ConstructFromSampleData(double** sample_values,
    int** sample_indices, int num_col, const int* num_per_col,
    size_t total_sample_size, data_size_t num_data);

**Comment by guolinke** [comment]
both sample_values and sample_indices are the pointer of 2d vector. 
their first dimension size is num_feature, and second dimension size is num_per_col[j] (for j-th feature). we only store the non-zero feature values in sample_values, so different features may have different size, and therefore num_per_col is used.
sample_values[j][i] is the value of j-th feature at i-th sampled row. and sample_indices[j][i] is the original row index (in original data) of sample_values[j][i].
total_sample_size is the sampled size for bin construction, and it includes the zero values.
