### ISSUE TITLE
Issues with running in debug mode under Visual Studio

### ISSUE THREAD

**Issue by nathans3** [microsoft/LightGBM#3432]
Hello I am facing this issue - I am trying to use the C_API of LightGBM in my C++ project.
I have linked my project to LightGBM package which is stored in a different location than my project is located. All built and run well in Release mode. In debug mode however after a successful build, when I run I get the message that "the code execution cannot proceed because lightgbm.exe was not found. Reinstalling the program may fix the problem". However, lightgbm.exe does exist in the x64/Debug folder of LightGBM, and this path is successfully read by Visual Studio because it gets the lightgbm.lib file from the same path while linking. I am using Visual Studio 2019.
Please help, thank you! Nathan

**Comment by guolinke** [comment]
do you want to use LightGBM compiled with debug mode? or only your code in debug mode?
