### ISSUE TITLE
Issue when loading previously trained model file

### ISSUE THREAD

**Issue by jualbina** [microsoft/LightGBM#3442]
I am trying to load a previously trained model file, but having format errors. I suspect that it is a versioning issue, since the older trained model shows version as _v2_, while newer model files shows as version v3 and work as expected. I have inspected the file and, although there is extra information on the newer model file, nothing seemed obviously wrong in the older model file.

Newer model file, that works as expected: [S001.txt](https://github.com/microsoft/LightGBM/files/5336813/S001.txt)
Older model file, that fails to load: [N002.txt](https://github.com/microsoft/LightGBM/files/5336811/N002.txt)

In case the older file model requires a specific version to be successfully loaded, which version should I use? Is there a way to update this model file to a newer version so that it works on LightGbm version 3.0.0?

## How you are using LightGBM?

* Python package

## Environment info

Python version: 3.7.3

LightGBM version or commit hash: 3.0.0

## Error message and / or logs

Attached file with error messages (very long): [error.txt](https://github.com/microsoft/LightGBM/files/5336814/error.txt)

## Steps to reproduce

1. Open ipython.
2. Import lightgbm (version 3.0.0)
3. Run _model = lightgbm.Booster(model_file="S001.txt")_ (work successfully)
4. Run _model = lightgbm.Booster(model_file="N002.txt")_ (fails)

**Comment by guolinke** [comment]
V3 model version adds the `leaf_weight` and `internal_weight`, these fields are not affect for the prediction results. 
So as long as you can load the old model file successfully, you can safely use it.

If you cannot load it successfully, and can try to remove the `tree_sizes=...` line in the model file.
