### ISSUE TITLE
Are negative values (ie. missing values) in categorical features treated as a separate category?

### ISSUE THREAD

**Issue by leockl** [microsoft/LightGBM#3453]
Based on LightGBM's documentation in the link below, the parameter categorical_feature (for categorical features) states that "All negative values in categorical features will be treated as missing values."

https://lightgbm.readthedocs.io/en/latest/pythonapi/lightgbm.LGBMClassifier.html#lightgbm.LGBMClassifier

My question is: Are the negative values (ie. missing values) in categorical features treated as a separate category? Or are they just treated as missing values and are not included as a category in the model?

Many thanks in advance.

**Comment by guolinke** [comment]
the negative categories, missing categories and low-frequency categories will be merged into one category is LightGBM.
