### ISSUE TITLE
Can LightGBM be compiled and run on an embedded arm linux board?

### ISSUE THREAD

**Issue by scut-jack** [microsoft/LightGBM#3456]
Can LightGBM be compiled and run on an embedded arm linux board?   And if so, what should I do?

**Comment by guolinke** [comment]
If it is a linux OS, and can install cmake, gcc, g++, I think it could be compiled. 
you can try our installation guide for linux.

**Comment by scut-jack** [comment]
> 
> 
> If it is a linux OS, and can install cmake, gcc, g++, I think it could be compiled.
> you can try our installation guide for linux.

It cannot install cmake, gcc, but I usually use cross-compilation to compile the software and run it on it; But this time the cross-compilation is not successful.I am wondering if this light GBM does not support running on the arm board?

**Comment by mattsplats** [comment]
Note that you may need to compile differently for 32-bit embedded boards or OSes (Raspbian).

> Seems that you need special CMake version for ARM platform
The example above has to override an x86 CMake preinstalled on the Docker image LightGBM's CI uses. In the usual case, `apt-get install cmake` or `yum install cmake` installs the correct version for Arm without any workarounds.

**Comment by scut-jack** [comment]
> 
> 
> Note that you may need to compile differently for 32-bit embedded boards or OSes (Raspbian).
> 
> > Seems that you need special CMake version for ARM platform
> 
> The example above has to override an x86 CMake preinstalled on the Docker image LightGBM's CI uses. In the usual case, `apt-get install cmake` or `yum install cmake` installs the correct version for Arm without any workarounds.

There are no apt-get or yum command on the arm board. What I am currently doing is to install cmake and cross compiler arm-linux-gcc on my Ubuntu host, and then compile the machine code on Ubuntu and put it on the arm board to run, but the compilation fails.

**Comment by StrikerRUS** [comment]
> What I am currently doing is to install cmake and cross compiler arm-linux-gcc on my Ubuntu host, and then compile the machine code on Ubuntu and put it on the arm board to run, but the compilation fails.

Could you provide compilation logs and the guide to how we can reproduce this?
