### ISSUE TITLE
joblib error when using python Booster.predict

### ISSUE THREAD

**Issue by thomasdkelly** [microsoft/LightGBM#3457]
## How you are using LightGBM?

* Python package

Hi i am using LGBM classifier in a kaggle competition where we submit the code which is then run on a separate server

The code is simply:
`bst = Booster(model_file=FILE) 
pred=np.random.choice(np.arange(19),p=(bst.predict(obs)).flatten())`

This gives me the error 
`/opt/conda/lib/python3.7/site-packages/joblib/_multiprocessing_helpers.py:53: UserWarning: [Errno 38] Function not implemented.  joblib will operate in serial mode\n  warnings.warn('%s.  joblib will operate in serial mode' % (e,))\n"`

Ive been looking through the source code and cant find where the model calls the joblib library or how to fix it. Do you have any ideas?

It is definitely the .pred() function as there is no errors if i simply load the model in.

Thanks
Tom

**Comment by StrikerRUS** [comment]
Hi @thomasdkelly !
Indeed, as you've mentioned, LightGBM doesn't use `joblib` internally.

You wrote 
> i am using LGBM classifier

but from the one line of code you provided it looks like you are using `Booster` object from standard API, not LGBMClassifier.

Could you please provide [MCVE](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by thomasdkelly** [comment]
Sorry its not a proper MCVE as i know it works on kaggle notebooks and colab

**Comment by thomasdkelly** [comment]
Found the issue wasn't even related to the warning message, was to do with casting the prediction as an integer properly. Thanks for your help

**Comment by StrikerRUS** [comment]
Glad to hear that you've solved the problem! Thanks for letting us know.
