### ISSUE TITLE
R-package: lgb.save does not retain full information of the booster object?

### ISSUE THREAD

**Issue by everdark** [Microsoft/LightGBM#346]
Hi,

I am just wondering whether this is what I should expect for the behaviour of `lgb.save`.
Here is my script to reproduce what I am confused:

```r
require(lightgbm)
require(methods)

data(agaricus.train, package='lightgbm')
data(agaricus.test, package='lightgbm')
train <- agaricus.train
test <- agaricus.test

dtrain <- lgb.Dataset(data = train$data, label=train$label, free_raw_data=FALSE)
dtest <- lgb.Dataset(data = test$data, label=test$label, free_raw_data=FALSE)
valids <- list(train=dtrain, test=dtest)
bst <- lgb.train(data=dtrain, num_leaves=4, learning_rate=1, nrounds=2, valids=valids,
                 metric = c("binary_error","binary_logloss"),
                 nthread = 2, objective = "binary")

bst$record_evals # recorded here
lgb.save(bst, "some.model")
loaded <- lgb.load("some.model")
loaded$record_evals # it's gone
```

Since I'd like to also keep the eval metrics for each iteration. Can I achieve this by `lgb.save`. If it is not, I need to write out it on my own.

**Comment by Laurae2** [comment]
@everdark use `saveRDS` and `readRDS` for R objects if you do not want to save only the model.

See issue #296.

**Comment by everdark** [comment]
noted. thanks for the quick response.

**Comment by Laurae2** [comment]
@everdark record_evals should now be stored if you use the serialization interface: https://github.com/Microsoft/LightGBM/pull/347

This will not work with `lgb.save` and `lgb.load`.

**Comment by everdark** [comment]
Hi recently I just found that the model file output by R can not be used in CLI or python version due to lacking of the `feature_infos`. Does this mean that R is using a different version of lightgbm?

I already re-compiled lightgbm from master branch and re-install the python and R package.
I install the R package by using:

```r
cd LightGBM/R-package
Rscript build_package.R
R CMD INSTALL lightgbm_0.2.tar.gz
```

Is this by design? or how can i output a model file from R that is also able to be used latter in python?

**Comment by guolinke** [comment]
@everdark 
I think cli, R and python share the same format of model file. 
can you upload the model file generated by R here?

**Comment by everdark** [comment]
@guolinke 
The file generated is like this:
https://transfer.sh/QFgkV/lgb.model

It is generated by a call to `lgb.save` after `lgb.train`.

Head: (there is no `feature_infos` as I could find for other model files generated by the cli/python examples)
```
tree
num_class=1
label_index=0
max_feature_idx=4
objective=binary
sigmoid=1
feature_names=yhat cate price len_title len_desc

Tree=0
num_leaves=20
```

**Comment by guolinke** [comment]
@Laurae2 can you help to this ? 
I think maybe it maybe is caused by the string format in R. 
The line of "feature_info" contains something like ```[...]```.

**Comment by everdark** [comment]
sorry I think the problem is solved.
Probably because I was loading R package from cache (which using the old ver of lightgbm).
