### ISSUE TITLE
How to set initial estimates using Python API?

### ISSUE THREAD

**Issue by danioyuan** [microsoft/LightGBM#3461]
## Summary

Add init_score argument to train() just like in LGBMRegressor.fit().

## Motivation

The scikit-learn API can use the init_score argument of LGBMRegressor.fit() to set initial value of the estimates. This is helpful when the estimates have to be in a specific range. In the Python API, the train function only has init_model, which is different from initial values. It would be nice for train() to allow init_score as well.

## Description

See above.

**Comment by StrikerRUS** [comment]
`init_score` can be set in the `Dataset` constructor.
https://lightgbm.readthedocs.io/en/latest/pythonapi/lightgbm.Dataset.html#lightgbm.Dataset
