### ISSUE TITLE
splitting for nan value looks wrong

### ISSUE THREAD

**Issue by chloe-wang** [microsoft/LightGBM#3463]
hi,

I have a dataset which have a feature with value between -0.5 and 0.5. This feature also contains some missing value with nan.

However, I found the model split on some extremely big value like 1e300 which is very close to the infinity in python. 

![image](https://user-images.githubusercontent.com/22490931/96334080-a0971600-10a0-11eb-882a-159fa65818c8.png)

Per my understanding, missing value will not be used for splitting, so it's weird that the tree will split on that big value.

**Comment by chloe-wang** [comment]
This issue may be related to #2811 , but the issue still exits after I upgraded the lightgbm to v3.0.0.

**Comment by guolinke** [comment]
use 1e300 as split value, mean that non-missing goes to left, and missing goes to right. Is it wrong?

**Comment by chloe-wang** [comment]
Using 1e300 as split value shall not be a big issue, but we found the importance for the feature will increase a lot. We choose a feature in random, and set the half of its value to np.nan, the importance of this feature will be among top 10 while it's not informative at all.

**Comment by chloe-wang** [comment]
And one more thing, in xgboost, I think nan value will not be used for finding split point. Instead nan value will be mapped to the left node or right node after the split point has been decided by those non-missing values. It maybe more reasonable. I not sure for that though.

**Comment by guolinke** [comment]
for nan algorithm, lightgbm and xgboost use the same algorithm. it will try to put nan to left and right, and use the one with the larger gain.
Therefore, if one feature has lots of nan, it has more "freedom" than normal features, and thus, its importance may is higher.

**Comment by chloe-wang** [comment]
Then, why we can see the split value at 1e300, as the non-missing value range only from -0.5 to 0.5. So the split value shall not be bigger than 0.5....

**Comment by chloe-wang** [comment]
Maybe the nan is used for bin construction?

**Comment by guolinke** [comment]
`1e300` is not missing value. `1e300` is the upper bound of non-missing value.

**Comment by guolinke** [comment]
yeas, there is special bin for missing value. 
and in nan finding algorithm, this bin could be in left side or right side. 
In your above example, the nan bin is in the right side, and all non-missing values are in left side. 

In you want more details, you can check the value of decision_type, it contains the information of missing value handle in that node.

**Comment by chloe-wang** [comment]
@guolinke I think you are right. Thanks a lot. I will close the issue.

**Comment by shiyuangu** [comment]
> for nan algorithm, lightgbm and xgboost use the same algorithm. it will try to put nan to left and right, and use the one with the larger gain. 

@guolinke Could you point me to the source code where this logic occurs? I want to get a better understanding of this. Thank you!
