### ISSUE TITLE
Installing Trinity on Mac OS   clang: error: unsupported option '-fopenmp' 

### ISSUE THREAD

**Issue by zzhuna1** [microsoft/LightGBM#3476]
I am trying to install trinity on Mac OS, and get the errors:

clang: error: unsupported option '-fopenmp'
make[4]: *** [CMakeFiles/fastaToKmerCoverageStats.dir/src/fastaToKmerCoverageStats.cpp.o] Error 1
make[3]: *** [CMakeFiles/fastaToKmerCoverageStats.dir/all] Error 2
make[2]: *** [all] Error 2
make[1]: *** [all] Error 2
make: *** [inchworm_target] Error 2

Does anyone had the same problem?

**Comment by guolinke** [comment]
sorry, what is trinity ?

**Comment by jameslamb** [comment]
I think you have the wrong repo. This project is not related to https://github.com/trinityrnaseq/trinityrnaseq at all, and I suggest that you [open an issue there](https://github.com/trinityrnaseq/trinityrnaseq/issues)
