### ISSUE TITLE
How to use the Nuget package in C# project

### ISSUE THREAD

**Issue by yezhejack** [microsoft/LightGBM#3479]
I have a trained LightGBM model produced by python. I want to integrate it into my C# project. I found there is a package in Nuget. But I can't find any related docs. 

I tried to install the Nuget. When I add "using LightGBM;", it can not work. The error is
`The type or namespace name 'LightGBM' could not be found (are you missing a using directive or an assembly reference?)`.

**Comment by StrikerRUS** [comment]
Please refer to some other C# packages that have LightGBM as a dependency.

https://github.com/dotnet/machinelearning/tree/master/src/Microsoft.ML.LightGbm
https://github.com/rca22/LightGBM.Net

![image](https://user-images.githubusercontent.com/25141164/103142845-2af09b80-471c-11eb-81fe-b6564fd422d2.png)


Our Nuget package doesn't contain any C# code, it consists only of compiled dynamic library with which you can communicate by  making calls to [C API](https://lightgbm.readthedocs.io/en/latest/C-API.html) from your C# project.

For example:
https://github.com/dotnet/machinelearning/blob/cf7dbffa50f7bd65172bfcb11537207a81250994/src/Microsoft.ML.LightGbm/WrappedLightGbmInterface.cs#L36
https://github.com/dotnet/machinelearning/blob/cf7dbffa50f7bd65172bfcb11537207a81250994/src/Microsoft.ML.LightGbm/WrappedLightGbmInterface.cs#L214-L216

For your particular use case you need something like loading existing model from file or string:
https://github.com/rca22/LightGBM.Net/blob/02c23edb082b417e2f1e31e2b1418ccf689ff185/LightGBMNet.Train/Interface/PInvoke.cs#L512-L536
