### ISSUE TITLE
python advanced_example would fail on current pypi version (released on Sept 1)

### ISSUE THREAD

**Issue by songzy12** [microsoft/LightGBM#3482]
## How you are using LightGBM?

LightGBM component:  Python package

## Environment info

Operating System: Ubuntu 18.04.4 LTS 

Python version: Python 3.6.9

LightGBM version or commit hash:  116abc6 

## Error message and / or logs

```
Traceback (most recent call last):
  File "advanced_example.py", line 105, in <module>
    valid_sets=lgb_eval)
  File "/home/songzy/.local/lib/python3.6/site-packages/lightgbm/engine.py", line 259, in train
    evaluation_result_list.extend(booster.eval_valid(feval))
  File "/home/songzy/.local/lib/python3.6/site-packages/lightgbm/basic.py", line 2615, in eval_valid
    return [item for i in range_(1, self.__num_dataset)
  File "/home/songzy/.local/lib/python3.6/site-packages/lightgbm/basic.py", line 2616, in <listcomp>
    for item in self.__inner_eval(self.name_valid_sets[i - 1], i, feval)]
  File "/home/songzy/.local/lib/python3.6/site-packages/lightgbm/basic.py", line 3120, in __inner_eval
    feval_ret = feval(self.__inner_predict(data_idx), cur_data)
TypeError: 'list' object is not callable
```
## Steps to reproduce

1. Go to python example folder: 
```
cd examples/python-guide
```
2. Run advanced_example.py
```
python3 advanced_example.py
```

**Comment by songzy12** [comment]
oops sorry, let me double check.

**Comment by songzy12** [comment]
Just a note here:

Now the python advanced_example can not run on pypi version.

The reason is, the change of feval list is introduced on Sept 7:
https://github.com/microsoft/LightGBM/commit/afc76d2cb8234f6876ed75d923a7916bfef9a1e5

However, the pypi version is released on Sept 1:
https://pypi.org/project/lightgbm/

Feel free to close this.

**Comment by StrikerRUS** [comment]
@songzy12 Thanks for the report!

@guolinke I think it's time to think about the next release (the previous one was 1st September and we promised more frequent releases).
