### ISSUE TITLE
How can I get the right encoding for categorical features?

### ISSUE THREAD

**Issue by GorynyaE** [microsoft/LightGBM#3488]
Hi! How can I get the right encoding for categorical features? Consider example: I train model where I use one categorical features. In output tree a have key “feature_infos” with my categorical feature:
"Categorical_feature": {
            "min_value": -1,
            "max_value": 6,
            "values": [
                -1,
                2,
                6,
                4,
                0,
                1,
                5
            ]
Also there is another key with “pandas_categorical”: 
[
            "A1",
            "A2",
            "A3",
            "A4",
            "A5",
            "A6",
            "A7"
        ]
How can I get the correct encoding for my categorical feature? For example {0: A1, 1: A2 …}

**Comment by StrikerRUS** [comment]
@GorynyaE  Hi! LightGBM relies on pandas internal encoding. Please refer to the following lines:
https://github.com/microsoft/LightGBM/blob/a3862f151f8fa34154095217389d8661c015f662/python-package/lightgbm/basic.py#L371

https://github.com/microsoft/LightGBM/blob/a3862f151f8fa34154095217389d8661c015f662/python-package/lightgbm/basic.py#L378-L380

Also, the following discussions might be helpful: #2826 and #2761.

**Comment by GorynyaE** [comment]
Thank you for your answer
