### ISSUE TITLE
Why the max&min in feature_infos_， do not match the max&min of df.describe();

### ISSUE THREAD

**Issue by fydlzr** [microsoft/LightGBM#3491]
I get a dataframe with 4890800 lines, and I train a model with lambdarank and ndcg.

I saved the model into txt file and found the "feature_infos" like:
"feature_infos=[693.61992297118672:28891904.698301326].....".

Then I apply df.describe() and found the same feature's range should be  [3.573260e+02, 6.706632e+07].

It looks like that they do not match.

Also, when I shuffle or sort the data frame, I got different models.

Operating System:  mac

CPU/GPU model:  i7

Python version:  3

**Comment by guolinke** [comment]
@fydlzr you can increase bin_construct_sample_cnt 
 (https://lightgbm.readthedocs.io/en/latest/Parameters.html#bin_construct_sample_cnt) to get exact feature info.

**Comment by fydlzr** [comment]
> @fydlzr you can increase bin_construct_sample_cnt
> (https://lightgbm.readthedocs.io/en/latest/Parameters.html#bin_construct_sample_cnt) to get exact feature info.

Thanks very much.
One more question, how can I get the identical model  after I shuffle the dataframe?

**Comment by guolinke** [comment]
@fydlzr 
I think it would be hard. there are two factors:
1. the bin construct. If you use the bin_construct_sample_cnt larger than #data. It should be identical when shuffling samples.
2. the histogram sum-up, which is executed by the order of samples. The floating-point accumulated error may cause the slight different results.

**Comment by fydlzr** [comment]
Thanks again;
I just updated lgb from 2.3.1 to 3.0.0,  does the old param "max_position" equal to "lambdarank_truncation_level"?
