### ISSUE TITLE
Same Results with Different Seeds (random_state) in LightGBM

### ISSUE THREAD

**Issue by jmq19950824** [microsoft/LightGBM#3506]
**Reproductive codes**

import pandas as pd
import numpy as np
import lightgbm as lgb 
from sklearn import datasets

iris = datasets.load_iris()
X = iris.data[:, :2]  # we only take the first two features.
y = iris.target

model_1 = lgb.LGBMClassifier(random_state = 1)
model_1.fit(X,y)
p_1 = model_1.predict_proba(X)

model_2 = lgb.LGBMClassifier(random_state = 2)
model_2.fit(X,y)
p_2 = model_2.predict_proba(X)

print(all(p_1[:,0] == p_2[:,0]))
print(all(p_1[:,1] == p_2[:,1]))

**result:
True
True**

**Bug: Same Results with Different Seeds (random_state)**
Although model_1 and model_2 are trained with different seeds (i.e., 1 and 2), both models predict the same probability for given dataset. In fact, should **different** models (which are trained with different seeds) generate **different** results?

**Comment by guolinke** [comment]
if you don't use any random functions, like sub_feature or sub_row, the results are deterministic.

**Comment by jmq19950824** [comment]
> if you don't use any random functions, like sub_feature or sub_row, the results are deterministic.

Thanks for your replying. Actually, this is the reason why lightgbm generates the same result with different seeds. Now this issue should be closed.
