### ISSUE TITLE
Negative r2_score

### ISSUE THREAD

**Issue by gopikanand60** [microsoft/LightGBM#3507]
No matter how I change the parameters, I'm getting a negative r2_score with lightgbm which essentially means that a linear graph or model would be better for me to make predictions. Any suggestions on how I can tackle this?

**Comment by guolinke** [comment]
did you use the very small data? please provide more details.

**Comment by gopikanand60** [comment]
Well, it has to do with a project related to sales forecasting where the training set had daily sales values of 2017 and 2018 which would come around to say 730 rows of records (80% for training and 20% for cross validation) and I was trying to predict for 2019 and comparing the results

**Comment by guolinke** [comment]
yes, the data is too small. You can try to use `min_data=2` and `min_data_in_bin=1` for small data.

**Comment by gopikanand60** [comment]
I'm extremely sorry but I wasn't able to find a parameter called "min_data" in the list. However setting min_data_in_bin=1 didn't help much.

**Comment by guolinke** [comment]
https://lightgbm.readthedocs.io/en/latest/Parameters.html#min_data_in_leaf

**Comment by gopikanand60** [comment]
Thank you for the clarification. You mentioned that the data I have is small. How much would be required to make daily predictions for a year?

**Comment by guolinke** [comment]
@gopikanand60 for small data set, you can use the less-complexity parameters, like small num_leaves and num_trees, to prevent overfitting.

**Comment by gopikanand60** [comment]
Yeah, I'm trying to iterate through possible values for parameters which help with overfitting. However, my initial error was around 50% and I'm able to bring it down only to about 39%. Can you please let me know how much data is normally required for a similar task as I've mentioned above?(Predicting sales for a year)

**Comment by StrikerRUS** [comment]
It is possible that 2 years is not enough for model to catch seasonality. So it worth getting more historical data.

Anyway, closing this issue as the most recent questions are unrelated to LightGBM.
