### ISSUE TITLE
How to produce executable at same time than .so file ?

### ISSUE THREAD

**Issue by arita37** [microsoft/LightGBM#3516]
If we do
```
  cd lightgbm
  cd  python-package
  python setup.py install

```

It compiled well but does not  produce  binary executable, only .so file

How to generate executable ?

**Comment by StrikerRUS** [comment]
Hi @arita37 !

For Python package you don't need executables.

How to build executable you can read in https://lightgbm.readthedocs.io/en/latest/Installation-Guide.html (CMake target named `lightgbm` is for executables and `_lightgbm` is for shared library).

**Comment by arita37** [comment]
Un-fortunately j7 option does not work...

**Comment by StrikerRUS** [comment]
> Un-fortunately j7 option does not work...

Could you please elaboreate?
