### ISSUE TITLE
Wheel support for linux aarch64

### ISSUE THREAD

**Issue by odidev** [microsoft/LightGBM#3517]
**Summary**
Installing LightGBM on aarch64 via pip using command "pip3 install LightGBM" tries to build wheel from source code

**Problem description**
LightGBM doesn't have wheel for aarch64 on PyPI repository. So, while installing LightGBM via pip on aarch64, pip builds wheel for same resulting in it takes more time to install LightGBM. Making wheel available for aarch64 will benefit aarch64 users by minimizing LightGBM installation time.

**Expected Output**
Pip should be able to download LightGBM wheel from PyPI repository rather than building it from source code.

@LightGBM-team, please let me know if I can help you building wheel/uploading to PyPI repository. I am curious to make LightGBM wheel available for aarch64. It will be a great opportunity for me to work with you.

**Comment by StrikerRUS** [comment]
Hello @odidev ! Thanks a lot for your interest and willing to help!

Please refer to #3421. We decided to go with QEMU at Azure Pipelines to build ARM wheels (and possibly other available architectures) similarly to all other our artifacts. I'm trying to get familiar with QEMU first, but unfortunately don't have a lot of time to do this. I'll be very grateful for initial PR we can start working from.
P.S. searching GitHub might be very useful in this case: https://github.com/search?p=2&q=qemu+filename%3Aazure-pipelines.yml&type=Code.

**Comment by seekingdeep** [comment]
@odidev but in the end does it build successfully?
