### ISSUE TITLE
Malloc error (and SIGABRT) when calling .fit() on LGBMClassifier

### ISSUE THREAD

**Issue by kyleengel** [microsoft/LightGBM#3520]
## How you are using LightGBM?

LightGBM component: Python package

## Environment info

I'm including my Mac's info below, but I was also able to reproduce this on Ubuntu 18.04.4.

Operating System: macOS High Sierra, 10.13.6

CPU/GPU model: CPU is 2.6 GHz Intel Core i7. GPU is Radeon Pro 560X 4096 MB.

C++ compiler version:

```
$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

CMake version:

```
$ cmake --version
cmake version 3.18.4

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

Java version:

```
$ java -version
java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)
```

Python version: 3.7.4

R version: N/A

Other: N/A

LightGBM version or commit hash: I can reproduce the error on `3.0.0` and the most recent nightly build. I **cannot** reproduce the error on `2.3.1`.

## Error message and / or logs

```
python(22144,0x70000cb7b000) malloc: *** error for object 0x7f807783dc10: incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug
Process finished with exit code 134 (interrupted by signal 6: SIGABRT)
```

## Steps to reproduce

I can reproduce this error on version `3.0.0` and the nightly build, but I can't reproduce the error on `2.3.1`.

I can reproduce this error ~90% of the time when I follow the steps up to 3a. Sometimes, I run the same code up to 3a and there is no error.

1. Make sure `lightgbm` version `3.0.0` is installed.
2. [Download the .txt file attached to this Issue.](https://github.com/microsoft/LightGBM/files/5477197/data.txt) Update the code snippets below to reference this file.

3a. Run the code below (this produces the error):

```python
import pandas as pd
from lightgbm import LGBMClassifier
clf = LGBMClassifier(subsample_for_bin=250, n_jobs=-1, random_state=420)
X = pd.read_csv("data.txt")
y = X.pop("y").to_numpy()
clf.fit(X, y)
```

3b. The error disappears if you change `n_jobs` to `1` and rerun:

```python
import pandas as pd
from lightgbm import LGBMClassifier
clf = LGBMClassifier(subsample_for_bin=250, n_jobs=1, random_state=420)
X = pd.read_csv("data.txt")
y = X.pop("y").to_numpy()
clf.fit(X, y)
```

3c. The error disappears if you shuffle the data and rerun:

```python
from random import shuffle
import pandas as pd
from lightgbm import LGBMClassifier
clf = LGBMClassifier(subsample_for_bin=250, n_jobs=1, random_state=420)
X = pd.read_csv("data.txt")
y = X.pop("y").to_numpy()
new_idx = [i for i in range(len(X))]
shuffle(new_idx)
X_shuffled = X.iloc[new_idx, :]
y_shuffled = y[new_idx]
clf.fit(X_shuffled, y_shuffled)
```

3d. The error disappears if you change the `random_state` and rerun:

```python
import pandas as pd
from lightgbm import LGBMClassifier
clf = LGBMClassifier(subsample_for_bin=250, n_jobs=9, random_state=1)
X = pd.read_csv("data.txt")
y = X.pop("y").to_numpy()
clf.fit(X, y)
```

3e. The error disappears if you remove one row from `X` and `y` and rerun (I tried this with every single row):

```python
import pandas as pd
from lightgbm import LGBMClassifier
clf = LGBMClassifier(subsample_for_bin=250, n_jobs=9, random_state=420)
X = pd.read_csv("data.txt")
y = X.pop("y").to_numpy()
X = X.iloc[1:, :]
y = y[1:]
clf.fit(X, y)
```

3f. The error disappears if you change `subsample_for_bin` and rerun:

```python
import pandas as pd
from lightgbm import LGBMClassifier
clf = LGBMClassifier(subsample_for_bin=249, n_jobs=9, random_state=420)
X = pd.read_csv("data.txt")
y = X.pop("y").to_numpy()
clf.fit(X, y)
```

## More information

These are the versions of other packages I used in the examples above:
* Pandas: `0.25.3`
* Numpy: `1.19.3`

**Comment by StrikerRUS** [comment]
@kyleengel Thank you very much for reporting and for fully reproducible example!
I can confirm this code crashes on my Windows machine as well.

**Comment by jameslamb** [comment]
+1 to what @StrikerRUS said...this is one of the best issues I've ever seen opened on an open source project. Thank you SO MUCH for the reproducible example, should make it easier for us to test and fix this.

**Comment by guolinke** [comment]
Thank you so much @kyleengel , I will work on this.

**Comment by guolinke** [comment]
I found the root cause: you used the too small `subsample_for_bin`. 
For the best effiency, LightGBM uses the sampled data (number=`subsample_for_bin`) to estimate the number of non-zero values in the full data, and then use the smallest int type (like int8 or int16) to create related objects. 
When you use the small `subsample_for_bin`, the estimation will be very biased, and create the wrong types. 
For example, based on the sampled data, LightGBM think use int8 type is enough, but your data actually needs int16. 
Then, it will cause the (index) overflow problems, and results in the size of array errors, and then memory  corruption. 

Besides, using smaller `subsample_for_bin` is a bad choice in practice, it will also bias the feature bucketization, and result in poor performance.
