### ISSUE TITLE
add conda-forge as option in Installation guide?

### ISSUE THREAD

**Issue by raybellwaves** [microsoft/LightGBM#3542]
May be worth adding that LightGBM can be installed via conda-forge in the docs.

https://lightgbm.readthedocs.io/en/latest/Installation-Guide.html

As a windows user this is often what I use to get started quickly.

I also find LightGBM a little better than XGBoost is this regard as the py-xgboost package is currently pinned at all old version on windows whereas the lightgbm is up to date (I believe) (https://anaconda.org/anaconda/py-xgboost/files ; https://anaconda.org/conda-forge/lightgbm/files).

**Comment by jameslamb** [comment]
Good to see you hear @raybellwaves ! Thanks for the suggestion. I agree that this option should be documented, but it should also be clear that the conda-forge version of `lightgbm` is not maintained by LightGBM maintainers (https://github.com/conda-forge/lightgbm-feedstock)

Would you be willing to open a pull request documenting how to `conda install` LightGBM? Also I think this is a more appropriate part of the documentation to put that: https://lightgbm.readthedocs.io/en/latest/Python-Intro.html

**Comment by raybellwaves** [comment]
I'll sadly admit I didn't see to the Python Intro section and didn't expect it to have install instructions. Today was actually my time on the docs.

Wonder if it's worth adding a sentence at the top of the section referring to the the python section e.g. 
https://lightgbm.readthedocs.io/en/latest/Python-Intro.html#install

**Comment by jameslamb** [comment]
Sorry, could you clarify?

Both https://lightgbm.readthedocs.io/en/latest/Installation-Guide.html#installation-guide and https://lightgbm.readthedocs.io/en/latest/Python-Intro.html#install both have links back to the detailed Python installation docs at https://github.com/microsoft/LightGBM/blob/master/python-package/README.rst

**Comment by raybellwaves** [comment]
> detailed Python installation docs at https://github.com/microsoft/LightGBM/blob/master/python-package/README.rst

Thanks. I guess I was expecting a link in https://lightgbm.readthedocs.io/en/latest/Installation-Guide.html to https://lightgbm.readthedocs.io/en/latest/Python-Intro.html.

Now I think about it more is it worth removing

```You can install LightGBM via pip

pip install lightgbm
```

from https://lightgbm.readthedocs.io/en/latest/Python-Intro.html# and just keep the link to https://github.com/microsoft/LightGBM/blob/master/python-package/README.rst#installation That way we don't have to drop the conda-forge install instructions in two locations.
