### ISSUE TITLE
other optuna links

### ISSUE THREAD

**Issue by raybellwaves** [microsoft/LightGBM#3543]
The README has a link to https://medium.com/optuna/lightgbm-tuner-new-optuna-integration-for-hyperparameter-optimization-8b7095e99258

Could also add a link to the optuna repo examples
https://github.com/optuna/optuna/blob/master/examples/lightgbm_simple.py
https://github.com/optuna/optuna/blob/master/examples/lightgbm_tuner_simple.py
https://github.com/optuna/optuna/blob/master/examples/lightgbm_tuner_cv.py

**Comment by jameslamb** [comment]
Thanks for the suggestion @raybellwaves !

Could you open a pull request that updates https://github.com/microsoft/LightGBM/blame/e93fd3331348c805010d0a849776677024353b7f/README.md#L43? It could be something like this:

```text
[**Optuna Hyperparameter Tuner**](blog-link) provides automated tuning for LightGBM hyperparameters [code examples](https://github.com/optuna/optuna/blob/master/examples/)
```
