### ISSUE TITLE
[python] support saving and loading CVBooster

### ISSUE THREAD

**Issue by samFarrellDay** [microsoft/LightGBM#3556]
The two most immediately apparent ways to save a cvbooster (to me at least) would be to use pickle, or save_model() as is done with basic booster models. However, neither of these appear to work:

```
import pandas as pd
import numpy as np
import lightgbm as lgb
import dill

data = pd.DataFrame(np.random.rand(100, 10))
data.columns = [str(i) for i in range(len(data.columns))]
target = data.pop("9")
params = {
    'learning_rate': 0.1,
    'min_data_in_leaf':3,
    'verbose': -1
}
dtrain = lgb.Dataset(data=data)
lgbcv = lgb.cv(params,train_set=dtrain,return_cvbooster=True)
cvbooster = lgbcv.pop("cvbooster")

# Using save_model()
cvbooster.save_model("File.txt")

# Fails
cvbooster_from_file = lgb.CVBooster(model_file = "File.txt")

# Returns a single booster
cvbooster_from_file = lgb.Booster(model_file = "File.txt")


######## Using pickle (dill)
# Save
with open("File.pkl","wb") as f:
    dill.dump(cvbooster,f)

# Fails
with open("File.pkl","rb") as f:
    cvbooster_from_pickle = dill.load(f)
```

Would it be possible to get a `.save_model()` method for CVBooster?

**Comment by guolinke** [comment]
`cvbooster` contains a list of  `Booster`. So you can achieve it like
```
cvbooster = lgbcv.pop("cvbooster")
for i, booster in enumerate(cvbooster.boosters):
    booster.save_model("model_{}.txt".format(i))
```

For the restore, you can load model one-by-one, and append it to a empty cvbooster. refer to 
https://github.com/microsoft/LightGBM/blob/1bc27939a43c414c3424f339994d0aa11f3aa3b1/python-package/lightgbm/engine.py#L303-L305

**Comment by minhsphuc12** [comment]
That is a very inelegant way to do the job.

**Comment by minhsphuc12** [comment]
> `cvbooster` contains a list of `Booster`. So you can achieve it like
> 
> ```
> cvbooster = lgbcv.pop("cvbooster")
> for i, booster in enumerate(cvbooster.boosters):
>     booster.save_model("model_{}.txt".format(i))
> ```
> 
> For the restore, you can load model one-by-one, and append it to a empty cvbooster. refer to
> https://github.com/microsoft/LightGBM/blob/1bc27939a43c414c3424f339994d0aa11f3aa3b1/python-package/lightgbm/engine.py#L303-L305

This is a very inelegant way to do the job.

**Comment by jameslamb** [comment]
Re-opening this issue because I don't think it was totally resolved.

By chance, I got an email notification this week because someone left a comment on this issue and then deleted it.

First, I think it's important to include the actual text of the error messages, so that this issue can be found from search engines.

I tried running the example code given with `lightgbm` 3.2.1 built from the latest commit on `master` (https://github.com/microsoft/LightGBM/commit/ec1debcee84e6b02f749282d9a501021370e74a9).

This code fails with the following error.

> ---------------------------------------------------------------------------
> TypeError                                 Traceback (most recent call last)
<ipython-input-3-1f1534f140c8> in <module>
     20 
     21 # Fails
---> 22 cvbooster_from_file = lgb.CVBooster(model_file = "File.txt")
     23 
     24 # Returns a single booster

> TypeError: __init__() got an unexpected keyword argument 'model_file'

`cvbooster.save_model()` *seems to succeed* because it doesn't throw an error, but what it is doing is probably not what users would want.

https://github.com/microsoft/LightGBM/blob/ec1debcee84e6b02f749282d9a501021370e74a9/python-package/lightgbm/engine.py#L309-L317

`cvbooster.save_model()` is calling `.save_model()` on each Booster, which means that after that call only the final booster has been stored into `"File.txt"`.

<hr>

Trying to save the `CVBooster` object using `dill` results in the following error.

> ---------------------------------------------------------------------------
> TypeError                                 Traceback (most recent call last)
> <ipython-input-20-f849740f9497> in <module>
      6 # Fails
      7 with open("File.pkl","rb") as f:
----> 8     cvbooster_from_pickle = dill.load(f)

> ~/miniconda3/lib/python3.8/site-packages/dill/_dill.py in load(file, ignore, **kwds)
    311     See :func:`loads` for keyword arguments.
    312     """
--> 313     return Unpickler(file, ignore=ignore, **kwds).load()
    314 
    315 def loads(str, ignore=None, **kwds):

> ~/miniconda3/lib/python3.8/site-packages/dill/_dill.py in load(self)
    523 
    524     def load(self): #NOTE: if settings change, need to update attributes
--> 525         obj = StockUnpickler.load(self)
    526         if type(obj).__module__ == getattr(_main_module, '__name__', '__main__'):
    527             if not self._ignore:

> ~/miniconda3/lib/python3.8/site-packages/lightgbm/engine.py in handler_function(*args, **kwargs)
    312             """Call methods with each booster, and concatenate their results."""
    313             ret = []
--> 314             for booster in self.boosters:
    315                 ret.append(getattr(booster, name)(*args, **kwargs))
    316             return ret

> TypeError: 'function' object is not iterable

<hr>

So I think there are multiple issues here to be addressed:

* `CVBooster.save_model()` should throw a warning mentioning that it is only saving one Booster.
    - and in release 4.0.0, I think we should make the breaking change to have `CVBooster.save_model()` raise a `NotImplementedError`
* `CVBooster` should be pickleable and it should be possible to load a `CVBooster` that has been pickled

@StrikerRUS what do you think?

**Comment by StrikerRUS** [comment]
@jameslamb Seems reasonable to me.

**Comment by jameslamb** [comment]
I've updated the description and added this to #2302, where we store the full list of feature requests.

Closing this for now per our policy in #2302. Anyone is welcome to pursue adding this feature! Please just leave a comment here saying that you are interested, and the issue can be re-opened as a place to ask maintainers questions.

**Comment by hoangphucITJP** [comment]
Please if you have time work on this feature.
The CVBooster.save_model() is a lie I used it without any thought then load the model with the basic booster and believed the result was correct which frustrated me!

**Comment by dtararuj** [comment]
hello, i can't find solution to this error. it's appear only on google collab.

My model: 
def objective(trial,model_features,cat_features,lgb_train):
            num_iterations = 1000
            stop_rounds = 50
            
             
            lgb_params = {
                "learning_rate": trial.suggest_loguniform("eta", 1e-8, 1.0),
                'num_leaves': trial.suggest_int('num_leaves', 2, 60),
                'max_depth' : trial.suggest_int('max_depth',2,108),
                'lambda_l2': trial.suggest_loguniform('lambda_l2', 1e-8, 10.0),
                'colsample_bytree': trial.suggest_uniform('colsample_bytree',0,1),
                'min_child_samples': trial.suggest_int('min_child_samples', 3, 50),
                #"objective":"tweedie",
                "objective" :'gamma',
                "feature_pre_filter" : False,
                "monotone_constraints": [-1 if (a=='price_per_unit') | (a=='list_price') else 0 for a in model_features],
                "monotone_constraints_method": trial.suggest_categorical('monotone_constraints_method',['basic','intermediate','advanced']),
                'verbose': -1,
               }
               study = optuna.create_study(direction="minimize")        
               study.optimize(lambda trial: objective(trial,model_features,cat_features,lgb_train), n_trials=50, n_jobs=1)

        trial = study.best_trial
        num_iterations = 1000
        stop_rounds = 50

        lgb_params = {
            **study.best_params,
            'monotone_constraints': [-1 if (a=='price_per_unit') | (a=='list_price') else 0 for a in model_features],
            "verbosity": -1,
            "feature_pre_filter" : False
                }


        model_cv = lgb.cv(lgb_params,
                                lgb_train,
                                num_boost_round=num_iterations,
                                feval=lgb_maape,
                                nfold=3,
                                return_cvbooster=True,
                                stratified=False,
                                verbose_eval=False,
                                categorical_feature=cat_features,
                                early_stopping_rounds=stop_rounds)`

TypeError: cv() got an unexpected keyword argument 'return_cvbooster'
