### ISSUE TITLE
v3.1.0 missing CRAN package

### ISSUE THREAD

**Issue by galalH** [microsoft/LightGBM#3569]
The 3.0.0 release came with a CRAN package that made it super simple to install LightGBM. Can we have the same for the latest release as well?

**Comment by StrikerRUS** [comment]
@galalH Hi! Thanks a lot for using LightGBM and sharing your preferable way of installation with us!

We are working on this: https://github.com/microsoft/LightGBM/pull/3484#issuecomment-727712867.

**Comment by jameslamb** [comment]
Like @StrikerRUS mentioned, we're trying right now to actually get this release onto CRAN so you can just `install.packages("lightgbm")`.

But I can also add the CRAN artifact to the release manually. It's something that has to be done manually and the 3.1.0 release was only created last night (Central Standard Time, where I am).

I've just added it to https://github.com/microsoft/LightGBM/releases/tag/v3.1.0.

You can install with the following R code that uses the `{remotes}` package

```r
remotes::install_url(
    "https://github.com/microsoft/LightGBM/releases/download/v3.1.0/lightgbm-3.1.0-r-cran.tar.gz"
)
```

Thanks for using LightGBM and the LightGBM R package!

If you have time, we'd welcome contributions to some of the open issues in the R package!

* https://github.com/microsoft/LightGBM/issues?q=is%3Aopen+is%3Aissue+label%3Ar-package
* feature requests: #2302
