### ISSUE TITLE
Can saved binary file be used if max_bin changes?

### ISSUE THREAD

**Issue by cyfdecyf** [microsoft/LightGBM#3577]
I'm modifying the source code to add a new task "save_binary" to prepare data before running parameter tuning. The python package's `Dataset.save_binary` uses too much memory, thus I'd rather do it using cli version with `two_round=true` and `force_col_wise=true`.

I see [`max_bin`](https://github.com/microsoft/LightGBM/blob/0b5e60dd10338daa821bbb38cc022df8c0bc857e/src/io/dataset.cpp#L944) and [`BinMapper`](https://github.com/microsoft/LightGBM/blob/0b5e60dd10338daa821bbb38cc022df8c0bc857e/include/LightGBM/feature_group.h#L374) are saved in binary file. So I'm wondering whether binary file can be reused if I change the `max_bin` parameter to a different value than when save the file?

**Comment by guolinke** [comment]
The max_bin will be fixed after save_binary, and you cannot update it.

**Comment by cyfdecyf** [comment]
@guolinke Thanks for your reply.

I opened a pull request https://github.com/microsoft/LightGBM/pull/3592 to prevent binary file with non-matching parameters from being used.

**Comment by StrikerRUS** [comment]
Fixed via #3592.
