### ISSUE TITLE
GOSS benchmarking allowed? (NDA question)

### ISSUE THREAD

**Issue by Laurae2** [Microsoft/LightGBM#358]
@guolinke NDA question: is it allowed to provide **public** benchmark results of GOSS before the paper is out?

If yes, which PR do you recommend to use? I am currently using 1bf7bbd for benchmarking stuff on v2.

(just wondering, because the v2 pull request comment is empty now)

**Comment by guolinke** [comment]
@Laurae2 
better to keep these benchmark private for now since they may be not the final solution.  Thanks !
