### ISSUE TITLE
Model saved on Mac errors when loading on Windows

### ISSUE THREAD

**Issue by ankane** [microsoft/LightGBM#3589]
Hi, thanks for this great library! I'm running into an issue where a model saved on Mac loads on Mac and Linux but not Windows (details below). This seems similar to #3137.

## How you are using LightGBM?

LightGBM component: Python package

## Environment info

Operating System: Mac (10.15) and Windows (Server 2019)
Python version: 3.9.0
LightGBM version or commit hash: 3.1.0

## Error message and / or logs

```txt
[LightGBM] [Fatal] Model format error, expect a tree here. met  0.0029304048767349183 0.006430237132978316 0.0042985079018399118 ...
```

Full CI output: https://github.com/ankane/lightgbm_repro/runs/1437259664?check_suite_focus=true

## Steps to reproduce

Here's the [full code](https://github.com/ankane/lightgbm_repro) to reproduce, including `data.csv` and `model.txt`.

Save a model on Mac

```python
import lightgbm as lgb
import pandas as pd

df = pd.read_csv('data.csv')

X = df.drop(columns=['y'])
y = df['y']

train_data = lgb.Dataset(X, label=y)
bst = lgb.train({}, train_data)
bst.save_model('model.txt')
```

Load the model on Windows

```python
import lightgbm as lgb
import pandas as pd

df = pd.read_csv('data.csv')

X = df.drop(columns=['y'])
y = df['y']

bst = lgb.Booster(model_file='model.txt')
print('predict', bst.predict(X)[:2].tolist())
```

**Comment by guolinke** [comment]
did you check the end_of_line enocoding of the model file?
It should be always `\n` in all platforms. If not, it may is due to the file is re-saved manually or by some program. 
For example, you can use github/git to push and pull model files, the line encoding will be changed.

**Comment by ankane** [comment]
Hey @guolinke, thanks for the response! It looks like that's the cause, as GitHub Actions converts line endings by default (https://github.com/actions/checkout/issues/135). Will close this out, but it'd be nice if LightGBM could handle either format.
