### ISSUE TITLE
Normalising LGBMRanker Scores

### ISSUE THREAD

**Issue by davidmosca** [microsoft/LightGBM#3601]
LGBMRanker (trained with objective function lambdarank and metric ndcg) returns unbounded scores. Is there a way to normalise these scores (e.g. between 0 and 1) so that they are comparable across queries? Thanks.

**Comment by guolinke** [comment]
you can use sigmoid, as used in training. However, as the training objective only considers the docs in the same query. I think the score across queries still cannot be comparable.
