### ISSUE TITLE
Got features num diff error between training data and test data, when I use libsvm data to train and test

### ISSUE THREAD

**Issue by xuyufan936831611** [microsoft/LightGBM#3622]
## Environment info
Operating System:Linux version 4.14.81.bm.20-amd64
CPU/GPU model:CPU
gcc version 6.3.0
Python version:2.7

LightGBM version or commit hash:2.3.1

## Error message and / or logs

[LightGBM] [Fatal] The number of features in data (875) is not the same as it was in training data (1914).
Traceback (most recent call last):
  File "src/predict.py", line 40, in <module>
    main(model, predict, meta)
  File "src/predict.py", line 14, in main
    y_predict = bst.predict(predict, num_iteration=bst.best_iteration)
  File "/data05/home/xuyufan/.local/lib/python2.7/site-packages/lightgbm/basic.py", line 2415, in predict
    data_has_header, is_reshape)
  File "/data05/home/xuyufan/.local/lib/python2.7/site-packages/lightgbm/basic.py", line 525, in predict
    c_str(f.name)))
  File "/data05/home/xuyufan/.local/lib/python2.7/site-packages/lightgbm/basic.py", line 45, in _safe_call
    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))
lightgbm.basic.LightGBMError: The number of features in data (875) is not the same as it was in training data (1914).

**Comment by xuyufan936831611** [comment]
When I use data in libsvm format to predict, I always got the feature num diff error. Even when I use the train data to predict, I got the error also, so what should I do to fix it?

**Comment by shiyu1994** [comment]
@xuyufan936831611  Does the error still exists in the latest version?

**Comment by guolinke** [comment]
@xuyufan936831611 you can try 3.1.0 or the latest master branch.

**Comment by YanzeZHANG** [comment]
maybe you can try setting  `predict_disable_shape_check=ture` ,this may help

**Comment by fccoelho** [comment]
> maybe you can try setting `predict_disable_shape_check=ture` ,this may help

Where does this option go?

**Comment by jameslamb** [comment]
@fccoelho , if you are using the Python package, `predict_disable_shape_check` (documented at https://lightgbm.readthedocs.io/en/latest/Parameters.html#predict_disable_shape_check) can be provided directly to `Booster.predict()`.

```python
import lightgbm as lgb
from sklearn.datasets import make_regression

X, y = make_regression(n_samples=10_000)

dtrain = lgb.Dataset(
    data=X,
    label=y
)
bst = lgb.train(
    train_set=dtrain,
    params={
        "objective": "regression",
        "verbose": 1
    },
    num_boost_round=10
)

bst.predict(X, predict_disable_shape_check=True)
```

If you are encountering an error similar to the one mentioned in this issue, please open a new issue and provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), and we'll be happy to help out!

**Comment by geoexploring** [comment]
Is a command line parameter setting problem. The `input_model` is empty when predicting.
