### ISSUE TITLE
Categorical features in sklearn API warning

### ISSUE THREAD

**Issue by david26694** [microsoft/LightGBM#3625]
## How you are using LightGBM?

LightGBM component: Python package

## Environment info

Operating System: macOS Catalina Version 10.15.2 (19C57)

CPU/GPU model: 1,4 GHz Quad-Core Intel Core i5

C++ compiler version: Apple clang version 11.0.3 (clang-1103.0.32.59)

Python version: 3.7

## Error message and / or logs

I use the `categorical_feature` option in `LGBMRegressor` and I get the following warning:

```UserWarning: Using categorical_feature in Dataset. warnings.warn('Using categorical_feature in Dataset.')```

Is this expected? Do you know why is this happening, what does it mean?

## Reproducible example(s)

```python
import pandas as pd
from sklearn.datasets import load_iris
from lightgbm import LGBMRegressor
from category_encoders import OrdinalEncoder

X = load_iris()['data']
y = load_iris()['target']

X = OrdinalEncoder(cols=[3]).fit_transform(X)

dt = LGBMRegressor()
dt.fit(X, y, categorical_feature=[3])
```

**Comment by StrikerRUS** [comment]
Yes, it is expected. This warning was originally introduced to make users sure that their categorical features were not lost.

Please refer to #792.

And we already have a request to refactor group of warnings related to cat. features: #3379. Feel free to comment there and share your opinion on how these warnings can be improved.
