### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'copy'

### ISSUE THREAD

**Issue by hanzigs** [microsoft/LightGBM#3635]
Hi
Setting params={'verbose': -1}
```
lgbmgrid_result = lgbmgrid.fit(X_train, y_train, eval_metric = 'auc', eval_set = [(X_test, y_test)], early_stopping_rounds = 10, params={'verbose': -1})
```
throws error with the gridsearch
```
return (xb.x.copy() if isinstance(xb, Individual) else xb.copy()), xb_f
AttributeError: 'NoneType' object has no attribute 'copy'
```
but setting verbose=0, no error
To just hide the warning 
```
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
```
i used params={'verbose': -1}
may i know how to hide the warning please,
Thanks

**Comment by jameslamb** [comment]
> return (xb.x.copy() if isinstance(xb, Individual) else xb.copy()), xb_f

This code is not from LightGBM. Can you please provide more details? Ideally, a reproducible example using small dataset like the ones from `sklearn.datasets`.

**Comment by hanzigs** [comment]
Yes, its from the gridsearchCV module, i am in the wrong place, sorry, Thanks

**Comment by jameslamb** [comment]
no problem, thanks for using LightGBM! Come back any time.
