### ISSUE TITLE
Can not pickle Booster which is trained with init_model

### ISSUE THREAD

**Issue by JayveeHe** [Microsoft/LightGBM#364]
According to  #151 and #149 , we are able to dump trained Booster with Pickle and joblib.

Everything goes fine until I try to pickle a model which is trained with non-None param `init_model`(model object or .txt path).

I can pickle Booster model with init_model by calling save_model() first and then pickle a new Booster object init with `model_file`.  (see case `gbm7` in the example)

Is it possible to pickle these models directly?

Thanks.

## Environment info
Operating System:  MacOS
CPU: 1.6 GHz Intel Core i5
C++/Python/R version: Python 2.7.10

## Error Message:

>ValueError: ctypes objects containing pointers cannot be pickled

## Reproducible examples
see: 
https://gist.github.com/JayveeHe/2f9bc4b7e56c6a3924fdda51392f77c4

## Steps to reproduce

1. just run the example script

**Comment by wxchan** [comment]
there is a pointer in _InnerPredictor object, I think removing it before save model will be ok (not 100% sure)

**Comment by JayveeHe** [comment]
Yes, it works

**Comment by JayveeHe** [comment]
And the precision works fine, too.

Details:
https://gist.github.com/JayveeHe/2f9bc4b7e56c6a3924fdda51392f77c4
