### ISSUE TITLE
Spurious warning when passing valid_sets

### ISSUE THREAD

**Issue by memeplex** [microsoft/LightGBM#3640]
When passing valid_sets (or eval_set through the sklearn API) I get a spurious warning (similar to https://github.com/microsoft/LightGBM/issues/3379). Strangely, when running inside a Jupyter notebook, the warning is only thrown when there is a change in parameters, not on every train call, as if some state is persisting across calls. The more reliable way to reproduce the problem is to restart the kernel and do a clean run.

This issue is extremely annoying with grid searches, since the warning is thrown for *every* item in the grid, flooding the notebook with irrelevant messages.

## How you are using LightGBM?

LightGBM component: python package

## Environment info

Operating System: MacOS 11.0.1 (Big Sur)

CPU/GPU model: 2,3 GHz Dual-Core Intel Core i5 / Intel Iris Plus Graphics 640 1536 MB

Python version: 3.8.6

## Error message and / or logs

```
/Users/carlos/Projects/Jampp/Venvs/LTV/lib/python3.8/site-packages/lightgbm/basic.py:1286: UserWarning: Overriding the parameters from Reference Dataset.
  warnings.warn('Overriding the parameters from Reference Dataset.')
/Users/carlos/Projects/Jampp/Venvs/LTV/lib/python3.8/site-packages/lightgbm/basic.py:1098: UserWarning: categorical_column in param dict is overridden.
  warnings.warn('{} in param dict is overridden.'.format(cat_alias))
```

## Reproducible example(s)

```
import lightgbm as lgb
import pandas as pd
import numpy as np

X = pd.DataFrame({
    "x1": np.arange(100),
    "x2": np.arange(100),
})
y = X.x1 + X.x2
X = X.astype({"x1": "category"})
ts = lgb.Dataset(X[:70], y[:70])
vs = lgb.Dataset(X[70:], y[70:])
lgb.train({}, ts, valid_sets=[vs])
```

## Steps to reproduce

1. Create a notebook and copy the above code in a cell, run and check the output.
2. Run the cell again and check that the warning is not there.
3. Restart the kernel, run again and check that the warning reappeared.
4. Restart the kernel, remove `valid_sets=[vs]` from the code, run and check that the warning is not there.

**Comment by jameslamb** [comment]
I believe this was fixed in #4768, as mentioned in https://github.com/microsoft/LightGBM/issues/3718#issuecomment-1411438388.

I just tried with `lightgbm==4.0.0`, and found that those warnings are no longer raised by the example code provided.

Thanks very much for the clear report with a minimal example!
