### ISSUE TITLE
predict/predict_proba: sample_weight doesn't accept pd.Series

### ISSUE THREAD

**Issue by memeplex** [microsoft/LightGBM#3642]
In the sklearn interface fit and predict accept pandas data structures almost anywhere, but there is at least an exception: the sample_weight parameter in predict (and predict_proba) can't recognize a pandas Series as a valid argument (OTOH, the same series can be passed to fit sample_weight, which is inconsistent).

## How you are using LightGBM?

LightGBM component: Python package

## Environment info

Operating System: MacOS 11.0.1 (Big Sur)

CPU/GPU model: 2,3 GHz Dual-Core Intel Core i5 / Intel Iris Plus Graphics 640 1536 MB

Python version: 3.8.6

## Error message and / or logs

```
~/Projects/Jampp/Venvs/LTV/lib/python3.8/site-packages/lightgbm/basic.py in param_dict_to_str(data)
    153             pairs.append(str(key) + '=' + str(val))
    154         elif val is not None:
--> 155             raise TypeError('Unknown type of parameter:%s, got:%s'
    156                             % (key, type(val).__name__))
    157     return ' '.join(pairs)

TypeError: Unknown type of parameter:sample_weight, got:Series
```

## Reproducible example(s)

```
import lightgbm as lgb
import pandas as pd
import numpy as np

X = pd.DataFrame({
    "x1": np.arange(100),
    "x2": np.arange(100),
})
y = (X.x1 + X.x2) > 100
w = pd.Series(np.ones(100))

model = lgb.LGBMClassifier().fit(X, y, sample_weight=w)
model.predict(X, sample_weight=w)
```

**Comment by StrikerRUS** [comment]
Neither `predict()` nor `predict_proba()` methods doesn't accept `sample_weight` argument at all.
Where did you find the info about that `sample_weight` can be passed to `predict*` methods in LightGBM?

**Comment by StrikerRUS** [comment]
Here are params that can be passed as additional predict arguments via `**kwargs – Other parameters for the prediction.`:

https://lightgbm.readthedocs.io/en/latest/pythonapi/lightgbm.LGBMModel.html#lightgbm.LGBMModel.predict

https://lightgbm.readthedocs.io/en/latest/Parameters.html#predict-parameters

**Comment by memeplex** [comment]
Yeah, right, it makes no sense since only gradients and hessians are weighted so it has nothing to do during predict. I guess I just put it there by mistake and then the error message (type error, unknown type) suggested it was a type issue so I reported it without without giving it a second thought. Thanks!
