### ISSUE TITLE
Identify the decision path length in the tree booster during the training stage

### ISSUE THREAD

**Issue by xuyxu** [microsoft/LightGBM#3646]
Hi, thanks for developing this great lib ;-)

I have one problem when using LightGBM to conduct my own project.  The problem is that I want to **extract the decision path length of each sample in the tree booster**. This could be interesting because trees produced from the latter boosting iterations tend to be shallower, and it may be worth further investigating.

An alternative solution is to extract the tree structures for each tree booster after the training stage, and compute the decision path length for each training sample as a standalone stage. However, this could be time-consuming if I have millions of samples.

Therefore, I would like to ask that whether this task can be achieved during the training stage? (It looks like the callbacks provided by Python APIs do not have related functionalities.)

**Comment by guolinke** [comment]
Sorry for the late response. 
For your problem, I think it is quite easy to implement. 
You want the tree path length per sample, which actually is the `leaf_depth`.
LightGBM support to record to `leaf_depth`, refer to https://github.com/microsoft/LightGBM/search?q=leaf_depth
You can add a predict function, like `leaf_index`, to get the `leaf_depth` per sample. And use callback to get the leaf_depth per iteration.

**Comment by xuyxu** [comment]
Thanks @guolinke! This is exactly what I want.
