### ISSUE TITLE
can we convert xgboost model to lightgbm model

### ISSUE THREAD

**Issue by 7starsea** [microsoft/LightGBM#3652]
## Summary

Currently from my experience, the training time for xgboost with gpu is faster than that of lightgbm with gpu, however the inference time of lightgbm cpu is faster than that of xgboost cpu. Therefore, I am wondering whether we can directly convert xgboost model to lightgbm model?

**Comment by StrikerRUS** [comment]
@7starsea Thanks for the interesting idea! But I don't think that this is something that should be implemented on LightGBM side. It sounds like a good candidate for third-party library that will do converting from one tree-based model to another one.

For example, CatBoost allows to load LightGBM model for prediction via ONNX format.

> Added conversion from ONNX to CatBoost. Now you can convert XGBoost or LightGBM model to ONNX, then convert it to CatBoost and use our fast applier. Use ``model.load_model(model_path, format="onnx")`` for that.
  https://github.com/catboost/catboost/releases/tag/v0.16.5

https://github.com/catboost/catboost/blob/bff6a0af5115ca165c805c2a1e0063afdb7c2b32/catboost/tutorials/apply_model/fast_light_gbm_applier.ipynb

**Comment by 7starsea** [comment]
Thanks for letting me know the ONNX format. A quick question arising in my head is that can LightGBM load ONNX formatted model?

**Comment by StrikerRUS** [comment]
Unfortunately, LightGBM cannot load ONNX format.
Linking #1074 here as related to this question.
