### ISSUE TITLE
Parallel doc upgrade

### ISSUE THREAD

**Issue by yellowca** [microsoft/LightGBM#3653]
I have read and pratice accroding the  [https://lightgbm.readthedocs.io/en/latest/Parallel-Learning-Guide.html](Parallel Learning Guide),
However, when using the mpi version to train a large amout of data under data parallel mode, some points are unclear
1、 Do all the workers need to contain all the data? Will the lightgbm only read part of the whole dataset automatic?
2、Is the final model file under each worker's directory are all the same?
3、When using a hdfs version, how to config a large amount of hdfs files as the train data? "hdfs://path/to/data*" seem not support

**Comment by cy-zheng** [comment]
Hi @yellowca , I have the same question as you did. Do you figure out the answer for "Do all the workers need to contain all the data? Will the lightgbm only read part of the whole dataset automatic?" 

Thank you so much!

**Comment by yellowca** [comment]
yes , there is a config option named "pre_partition" or something like this, by setting it to true u can tell LightGbm to treat the train data as part of while data



---Original---
