### ISSUE TITLE
Subsequent runs of the same code results in different scores

### ISSUE THREAD

**Issue by ch3rn0v** [microsoft/LightGBM#3654]
## How you are using LightGBM?
* Python package

## Environment info

* Operating System: Ubuntu 20.04.1 LTS
* Python version: 3.8.5
* GCC 7.3.0
* LightGBM version or commit hash: 3.1.1

## Steps to reproduce

1. In jupyter lab's notebook, prepare train and validation datasets. (They are huge and private, so can't share a reproducible example).
2. Train lgbm with `random_state`, `bagging_fraction_seed`, `feature_fraction_seed` all set to the same constant. Evaluate against validation, write down the resulting score.
3. Shutdown the notebook's kernel, restart the notebook, repeat everything exactly the same way with exactly the same random seeds. Observe a slightly different score.

It's important to note that subsequent runs happen on the very same machine, without a lot of time between them. You can think that the datasets are prepared elsewhere and the script that runs lgbm simply loads them from a couple of pickle files. So the data is exactly the same every time. All lgbm params are also exactly the same.

**The issue is that the score differs sometimes. Other times it doesn't. Would you please advise how I fix this?**

No, I do not use gpu. In fact, I've specifically set `"device_type": "cpu",` in params.
Yes, I do use `"num_threads": 16,`.

Interestingly, the issue only happens when I set `bagging_fraction` and `bagging_freq` so that lgbm performs subsampling. When it doesn't, the score is always reproducible.

I'd like to take a moment to thank you for the awesome package! And thank you in advance for considering the issue. I've searched for similar questions, but didn't find a definitive solution.

**Comment by guolinke** [comment]
you can set `deterministic=true`. https://lightgbm.readthedocs.io/en/latest/Parameters.html#deterministic

**Comment by ch3rn0v** [comment]
@guolinke , thank you very much! I tried running a model with and without this option a few times with a quite large dataset and it seems to work.
