### ISSUE TITLE
Fit two dependent models iteratively

### ISSUE THREAD

**Issue by danioyuan** [microsoft/LightGBM#3658]
## Summary

Use two GBMs to fit two parameters of a distribution iteratively.

## Motivation

If the observed data is modeled as random variables from a distribution with two parameters (such as a normal distribution), GBM can be used to fit the two parameters.

## Description

Each parameter has its own gradient and hessian functions. So one gbm can be used to fit parameter 1 (with parameter 2 set to initial values), and then use a second gbm to fit parameter 2 based on predicted parameter 1. After this first iteration, parameter 1 can be fit with a updated gbm to improve the fit, and so on.

**Comment by btrotta** [comment]
I don't think this is a typical use case for GBMs. Have you considered using something like scipy optimize?
