### ISSUE TITLE
[R-package] [ci] use precompiled binaries from RPSM for Linux CI jobs

### ISSUE THREAD

**Issue by jameslamb** [microsoft/LightGBM#3665]
The R package's CI jobs on Linux are slower than those on Mac, by several minutes. Consider this recent run: https://github.com/microsoft/LightGBM/pull/3664/checks?check_run_id=1583981483

**linux (average: 10m33s)**

* r-package (ubuntu-latest, gcc, R 3.6, cmake): 11m2s
* r-package (ubuntu-latest, gcc, R 4, cmake): 9m4s
* r-package (ubuntu-latest, clang, R 3.6, cmake): 10m59s
* r-package (ubuntu-latest, clang, R 4, cmake): 10m26s
* r-package (ubuntu-latest, gcc, R 4, cran): 11m18s

**mac (average: 7m43s)**

* r-package (macOS-latest, gcc, R 3.6, cmake): 6m55s
* r-package (macOS-latest, gcc, R 4, cmake): 7m9s
* r-package (macOS-latest, clang, R 3.6, cmake): 7m38s
* r-package (macOS-latest, clang, R 4, cmake): 8m1s
* r-package (macOS-latest, clang, R 4, cran): 8m53s

I believe a large portion of this difference can be explained by the fact that CRAN does not prepare binaries for Linux distributions. This means all of the dependencies that have to be installed at CI time are compiled from source on Linux builds. On Mac builds, installation of dependencies is much faster because we get precompiled binaries from CRAN.

### How to fix this issue

I learned recently that RStudio runs a free, public package manager that mirrors CRAN and BioConductor AND (most importantly) provides precompiled binaries for several Linux flavors: http://dirk.eddelbuettel.com/blog/2020/07/03/#028_rocker_rspm. This is called RStudio Package Manager (RPSM).

I think that switching to RPSM as the CRAN mirror for Linux CI jobs in https://github.com/microsoft/LightGBM/blob/master/.ci/test_r_package.sh#L4 could result in saving several minutes per job of CI time.

I believe the right mirror URL would be something like this

```shell
if [[ $OS_NAME == "linux" ]];
    source /etc/os-release
    CRAN_URL="https://packagemanager.rstudio.com/all/__linux__/${VERSION_CODENAME}/latest"
fi
```

**Comment by StrikerRUS** [comment]
My only concern is about that fetching binaries from RPSM adds one more proxy layer that we aren't controlling. And I believe that this will move our CI one step aside from ordinary user behavior, while I believe that CI should simulate our users' use cases as closer as possible.

**Comment by jameslamb** [comment]
I agree with that! I should have called this "RFC", because I was also torn. I guess as long at the jobs aren't prohibitively long and our development pace stays at what it currently is, this is probably not something we should do.
