### ISSUE TITLE
How do I convert a pandas Dataframe into a csv / libSVM file to load directly into Dataset from disk to avoid memory spike?

### ISSUE THREAD

**Issue by krissy-fong** [microsoft/LightGBM#3669]
I have 25gb of RAM and a 5gb pandas dataframe all float32. When I load the dataframe into lgb.dataset everything is fine, but when I go to start training, the memory usage spikes and system crashes. 

My understanding is that this is due to multiple copies being created, but can be avoid if I save my data as a csv file and load directly from disk.

My questions:
1. How do I create the csv file?
2. What structure should that csv file be in, ie. where should the label and qid's go?
3. Will this fix the memory spike issue I have been encountering?
4. Does it have to be a csv file? THey are much larger on disk than parquet or feather.

**Comment by zyberg2091** [comment]
Just use the to_csv() method of the pandas dataframe

**Comment by guolinke** [comment]
you can try the simple solution first.
By converting the pandas to numpy.float32 first, and delete the pandas. 
Then try to load from numpy.float32.

If this still cannot work, you can save pandas to csv file, by @zyberg2091 mentioned to_csv. But you need to skip the header and row index. For label, you can put it to the first column; for qid, you can put it to the second column, and refer to https://lightgbm.readthedocs.io/en/latest/Parameters.html#group_column for more details.

To reduce the memory spike when loading from csv file, you can set `two_round=true`.
