### ISSUE TITLE
Wrong warning message pops up

### ISSUE THREAD

**Issue by ldmtwo** [microsoft/LightGBM#3670]
Issue:
Wrong warning message pops up. I misconfigured it by having dart+early_stopping_round on a binary class training task. That combo is invalid. The warnings below raised on line engine.py:153 make no sense and are more confusing than helpful.

This is output for a series of [train,predict].

```
/opt/conda/lib/python3.7/site-packages/lightgbm/engine.py:153: UserWarning: Found `early_stopping_round` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))
/opt/conda/lib/python3.7/site-packages/lightgbm/callback.py:188: UserWarning: Early stopping is not available in dart mode
  warnings.warn('Early stopping is not available in dart mode')
/opt/conda/lib/python3.7/site-packages/lightgbm/engine.py:153: UserWarning: Found `early_stopping_round` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))
/opt/conda/lib/python3.7/site-packages/lightgbm/callback.py:188: UserWarning: Early stopping is not available in dart mode
  warnings.warn('Early stopping is not available in dart mode')
```

**Comment by jameslamb** [comment]
Thanks for using LightGBM! Can you please elaborate? What would you like help with?

Alternatively, we'd welcome a [pull request](https://github.com/microsoft/LightGBM/pulls) with a proposal to improve the relevance and clarity of warnings from the Python package.

**Comment by StrikerRUS** [comment]
@ldmtwo First message says that you specified a param that has its own argument in function:
https://github.com/microsoft/LightGBM/blob/d90a16d520fa12d84ecd983fba323727348616a4/python-package/lightgbm/engine.py#L90-L98
And it informs you that value from `params` will be picked up and has higher priority over function argument.

Second warning is about that earlier stopping cannot be used with dart.

These two warning are complitely about different things.
