### ISSUE TITLE
the split_gain is inconsistent with the value manually calculated

### ISSUE THREAD

**Issue by chloe-wang** [microsoft/LightGBM#3674]
## How you are using LightGBM?
* Python package
LightGBM component:  plot_tree
Python version: 3.0.0
## Error message and / or logs
I'm using the "mse" metric and "regression" objective.  Here I set the tree have only two leaves and boosting 1 round, which means it can only split once. Then I got the prediction for each sample. Then I found the loss gain calculated with below formula is inconsistent with the split gain showed in the tree model file:
![image](https://user-images.githubusercontent.com/22490931/103065418-870ad100-45f1-11eb-8450-a2a61ff714df.png)

**Comment by guolinke** [comment]
refer to https://github.com/microsoft/LightGBM/blob/master/src/objective/regression_objective.hpp#L93
I think there is `1/2` for the mse loss.
