### ISSUE TITLE
[Question]how to use the float feature?

### ISSUE THREAD

**Issue by ucasiggcas** [microsoft/LightGBM#3695]
hi,dear all
in the [docs](https://lightgbm.readthedocs.io/en/latest/Python-Intro.html), it said that we should transform the **float** data to **int** type , but I want to use the float directly since it is **Numeric Features**, so how to deal with it ?
```
LightGBM can use categorical features as input directly. It doesn’t need to convert to one-hot coding, and is much faster than one-hot coding (about 8x speed-up).

Note: You should convert your categorical features to int type before you construct Dataset.
```

**Comment by StrikerRUS** [comment]
Hi @ucasiggcas !

This note is actual only for **categorical** features.
> You should convert your ***categorical*** features to int type

> but I want to use the float directly since it is **Numeric Features**, so how to deal with it ?

For **numeric** features, nothing special should be done. They all are converted to float internally.
