### ISSUE TITLE
Interpretation of LambdaRank results file

### ISSUE THREAD

**Issue by nlothian** [Microsoft/LightGBM#37]
How should the results in the LambdaRank results file be interpreted? 

I think the numbers are scores within the query group, and higher is better?

I assume we use the .query file to work out how many records are written for each query group?

**Comment by guolinke** [comment]
Hi, the label/prediction in lambdarank is the relevant score, higher means better.
for the query file: https://github.com/Microsoft/LightGBM/wiki/Configuration#query-data
I will close this now. please feel free to reopen if you still have questions.

**Comment by travisbrady** [comment]
Related question: do the labels in the input file obey the "higher is better" rule as well?
Pardon me if that's a silly question.
