### ISSUE TITLE
model trained by cli cannot be  loaded by python api 

### ISSUE THREAD

**Issue by rudaoshi** [Microsoft/LightGBM#370]
When loading the model using python Booster, it report:

lightgbm.basic.LightGBMError: Model file doesn't contain feature information

How can I solve this?

**Comment by wxchan** [comment]
I guess your model is trained in earlier version, my new trained model can be loaded into python Booster well.

**Comment by guolinke** [comment]
refer to this : https://github.com/Microsoft/LightGBM/issues/264#issuecomment-289008917
