### ISSUE TITLE
[Question] how to deal with data imbalance

### ISSUE THREAD

**Issue by ucasiggcas** [microsoft/LightGBM#3702]
hi,dear all
In **lgb.train** for binary classification,the positive data are more than the negetive ,so how to deal with the probelm ?
thx

**Comment by StrikerRUS** [comment]
Hi @ucasiggcas !

For imbalance data problem you can use any third-party solution from ones that are usually used for other ML algorithms. LightGBM has some special params that help to deal with the problem:
- [pos_bagging_fraction](https://lightgbm.readthedocs.io/en/latest/Parameters.html#pos_bagging_fraction) / [neg_bagging_fraction](https://lightgbm.readthedocs.io/en/latest/Parameters.html#neg_bagging_fraction);
- [is_unbalance](https://lightgbm.readthedocs.io/en/latest/Parameters.html#is_unbalance) / [scale_pos_weight](https://lightgbm.readthedocs.io/en/latest/Parameters.html#scale_pos_weight);
- [class_weight](https://lightgbm.readthedocs.io/en/latest/pythonapi/lightgbm.LGBMClassifier.html#lightgbm.LGBMClassifier.__init__).
