### ISSUE TITLE
Question about quantization

### ISSUE THREAD

**Issue by GLevV** [microsoft/LightGBM#3707]
Is it possible to add different quantization techniques? As I understand most of GBDTs use quantiles to quantize data (like pd.qcut or KBinsDiscretizer(strategy='quantile')), but there are other options, like uniform quantization (like pd.cut or KBinsDiscretizer(strategy='uniform')). There are also other techniques in Catboost (like entropy minimization) and in 1d classification/clustering (like jenkins/natural/head-tails breaks), but they require fitting of additional parameters and could be time-wasteful unlike uniform and quantile strategies. 

Third option could be geometric intervals which is increasing intervals that could be used when distribution of the feature is skewed. It is also easy to compute and gives different to uniform and quantile strategies results.

**Comment by StrikerRUS** [comment]
Closed in favor of being in #2302. We decided to keep all feature requests in one place.

Welcome to contribute this feature! Please re-open this issue (or post a comment if you are not a topic starter) if you are actively working on implementing this feature.
