### ISSUE TITLE
[dask] support 'pred_contrib' in predict()

### ISSUE THREAD

**Issue by jameslamb** [microsoft/LightGBM#3713]
## Summary

LightGBM's `Booster.predict()` can be use to get feature contributions, by passing `pred_contrib=True`. This should be supported for model objects from the Dask interface as well.

## Motivation

This is useful for inspecting the relative importance of features in a LightGBM model.

## Description

The check at https://github.com/microsoft/LightGBM/blob/aae4fe401b316e156bf1d4aa8bbc213a606aab5e/python-package/lightgbm/dask.py#L169 should also check whether `pred_contrib=True` has been passed, and return the full DataFrame of the result.

## References

* this change in a fork of `dask-lightgbm` shows what the relevant change might look like: https://github.com/h2oai/dask-lightgbm/commit/c19000b57c1239b2a6de65cf172163c8684ce7dc

**Comment by StrikerRUS** [comment]
Closing in favor of being in #2302 with other feature requests. Please leave a comment here if you'd like to work on this.

**Comment by jameslamb** [comment]
opening this as I'm actively working on it at the moment
