### ISSUE TITLE
[dask] allow customization of num_threads

### ISSUE THREAD

**Issue by jameslamb** [microsoft/LightGBM#3714]
## Summary

LightGBM training with Dask currently ignores the `num_threads` setting in user-provided parameters, and overwrites it with the number of CPU cores on each worker contributing to training.

This behavior is a good default, but it should be possible to override it.

## Motivation

There might be cases where it's desirable not to use as many threads as cores on each worker during training, and that should be possible.

## References

* See https://github.com/microsoft/LightGBM/blob/aae4fe401b316e156bf1d4aa8bbc213a606aab5e/python-package/lightgbm/dask.py#L144 for a proposed fix
* The current behavior comes from https://github.com/dask/dask-lightgbm

This behavior was recommended in https://github.com/microsoft/LightGBM/pull/3515#issuecomment-752709132.

**Comment by jameslamb** [comment]
Closing this in favor of being in #2302 with other features. Please leave a comment here if you'd like to work on it.

**Comment by jameslamb** [comment]
I'm going to open this because I'm actively working on it.

<hr>

@guolinke could tell me more about this note in the parameter docs for `num_threads`?

https://lightgbm.readthedocs.io/en/latest/Parameters.html#num_threads

> for parallel learning, do not use all CPU cores because this will cause poor performance for the network communication

I'm wondering if this means that I should change the default behavior of the Dask module to use `n_cores - 1` threads on each worker for this parameter.

**Comment by StrikerRUS** [comment]
@jameslamb 

> I'm going to open this because I'm actively working on it.

Just want to make sure you're aware of that `nthreads` can/should be used among additional params for `predict` methods as well as for model training.

Here are two examples where users are not happy with the default values:

https://github.com/microsoft/LightGBM/issues/1534#issuecomment-406485465
https://github.com/microsoft/LightGBM/issues/2225#issuecomment-501220332

**Comment by jameslamb** [comment]
I'm going to close this again for now, currently focusing on other Dask items. This can be done after 3.2.0 (#3872 ).

**Comment by StrikerRUS** [comment]
Related: https://github.com/dmlc/xgboost/pull/7337.

**Comment by StrikerRUS** [comment]
The following code of `joblib`'s [`DaskDistributedBackend`](https://github.com/joblib/joblib/blob/master/joblib/_dask.py) and [`MultiprocessingBackend`](https://github.com/joblib/joblib/blob/7742f5882273889f7aaf1d483a8a1c72a97d57e3/joblib/_parallel_backends.py#L433-L443) might be useful.
