### ISSUE TITLE
[error]lightgbm.basic.LightGBMError: Multiclass objective and metrics don't match

### ISSUE THREAD

**Issue by ucasiggcas** [microsoft/LightGBM#3719]
hi,dear all
set the param as follows
```
param = {'num_leaves': 31, 'objective': 'multiclass','num_class':3,'metrics': ['auc', 'multi_logloss'],
         'learning_rate': 0.08, 'is_unbalance':True,}
```
what's the matter?
could you please help me ?
thx

**Comment by StrikerRUS** [comment]
Hello @ucasiggcas !

`AUC` is a binary metric, but your task is multiclass with 3 classes. You can use `AUC-mu`.

https://lightgbm.readthedocs.io/en/latest/Parameters.html#metric

**Comment by ucasiggcas** [comment]
@StrikerRUS 
but now has the same bug either
```
param = {'num_leaves': 31, 'objective': 'multiclass','num_class':3,'metrics': ['auc_mu', 'multi_logloss'],
         'learning_rate': 0.08, 'is_unbalance':True,'max_bin' : 255,'metric_freq' : 1}
```
what's the problem?
thx

**Comment by ucasiggcas** [comment]
after update the version from 2.3.1 to 3.1.1,
Got Success,
thanks to you and myself

haha

**Comment by StrikerRUS** [comment]
Glad you got it work!

Yes, AUC-mu was released in `3.0.0` version. So the failure on `2.3.1` was expected.

Also please note that `is_unbalance`
> used only in `binary` and `multiclassova` applications
    https://lightgbm.readthedocs.io/en/latest/Parameters.html#is_unbalance

but not with `multiclass` objective.

**Comment by ucasiggcas** [comment]
@StrikerRUS 
so how to deal with the data imbalance in multiclass?

**Comment by StrikerRUS** [comment]
You are free to use any third-party solution or `class_weight` from https://github.com/microsoft/LightGBM/issues/3702#issuecomment-753535634 or sample weights (https://github.com/microsoft/LightGBM/issues/3687#issuecomment-753552824).
