### ISSUE TITLE
What's the difference between raw_score and leaf_value

### ISSUE THREAD

**Issue by Hailprob** [microsoft/LightGBM#3722]
By **lgb.create_tree_digraph()**, I got a tree plot with _leaf_value_ on every nodes. By **lgb.LGBMClassifier().predict(raw_score=True)**, I got an float64 arraylike _raw_score_ object. By **predict_proba()** I got the _positive predict value_ given X. I have 2 questions:

1. how is the _leaf_value_ calculated?
2. what are the relations among the three values? Maybe Sigmoid transformation ?

**Comment by guolinke** [comment]
leaf_value is the output of a single tree.
raw_score is the sum of leaf_value of all trees.
For some objectives, like binary, some transformation (like sigmoid for binary) will be applied on raw_score, and produce the final prediction results.

**Comment by bfeif** [comment]
I just spent 20 minutes trying to figure out what `raw_score` meant, and ended up here. This is informative, thank you! Can this information be included in the LGBM documentation for the parameter? For example, I suggest changing this [line of code here](https://github.com/microsoft/LightGBM/blob/df14e6077e07259163c9200d2c570a022e2625cd/python-package/lightgbm/basic.py#L772) from
```
raw_score : bool, optional (default=False)
            Whether to predict raw scores.
```
to 
```
raw_score : bool, optional (default=False)
            Whether to predict scores without applying transformation by the objective function.
```

**Comment by StrikerRUS** [comment]
@bfeif Thanks for the suggestion! Feel free to open a PR with it.
