### ISSUE TITLE
Installation bug 16.04

### ISSUE THREAD

**Issue by JustM57** [Microsoft/LightGBM#373]
## Environment info
Operating System: Ubuntu 16.04
CPU: Intel® Core™ i5-2300 CPU @ 2.80GHz × 4 
C++/Python/R version: 3.5
GCC 5.4.0

I just try to install lgm as it is written in instructions. And trying to complete make -j (it goes up to 93% and thats all) in a couple of seconds my PC stops answering.
Tried to reinstall lgm - same result

**Comment by guolinke** [comment]
can you Installation other project successfully? like xgboost.

**Comment by JustM57** [comment]
Yes, I've got xgboost installed. Btw I got Lunux on this PC about a week ago.

**Comment by JustM57** [comment]
I've tried another way of installation - through OpenMPI, but got same results. PC crashed on 'Building a CXX object"

**Comment by wxchan** [comment]
It sometimes happens to my machine too, just wait couples of minutes it might be fine.

**Comment by JustM57** [comment]
thanks... It seems to be 15 minutes. Quite a lot

**Comment by guolinke** [comment]
@wxchan  Did you know the reason ?

**Comment by wxchan** [comment]
No, I think it's not a lightgbm problem, it happens when I compiled other programs.
