### ISSUE TITLE
[Question] Does LightGBM cli support "feature_name" config?

### ISSUE THREAD

**Issue by cy-zheng** [microsoft/LightGBM#3731]
Hi,
I'm using libsvm as the input data format, and want to know how I could pass column name to LightGBM cli.
I found that LightGBM python API support a parameter `feature_name`, does cli version support the same field? I cannot find it through doc. 
https://lightgbm.readthedocs.io/en/latest/pythonapi/lightgbm.train.html#lightgbm.train

**Comment by StrikerRUS** [comment]
Yes, feature names are supported in CLI version via `header` param.
https://lightgbm.readthedocs.io/en/latest/Parameters.html#header

You just place column names in your file and specifies `header=true`.
