### ISSUE TITLE
Error installing Lightgbm R package: jsonlite Permission denied

### ISSUE THREAD

**Issue by saraswatmks** [Microsoft/LightGBM#374]
Hi

I am unable to install lightgbm package in R.

## Environment info
Operating System: Ubuntu 16.10
CPU: x86_64-pc-linux-gnu (64-bit)
C++/Python/R version:  3.3.3 (2017-03-06)

## Error Message:

Downloading GitHub repo Microsoft/LightGBM@master
from URL https://api.github.com/repos/Microsoft/LightGBM/zipball/master
Installing lightgbm
trying URL 'https://cran.rstudio.com/src/contrib/jsonlite_1.3.tar.gz'
Content type 'application/x-gzip' length 1060613 bytes (1.0 MB)
==================================================
downloaded 1.0 MB

Installing jsonlite
'/usr/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/tmp/RtmpG1TmLj/devtools30c254aca8fe/jsonlite' --library='/home/manish/R/x86_64-pc-linux-gnu-library/3.3'  \
  --install-tests 

* installing *source* package ‘jsonlite’ ...
** package ‘jsonlite’ successfully unpacked and MD5 sums checked
mv: cannot move '/home/manish/R/x86_64-pc-linux-gnu-library/3.3/jsonlite' to '/home/manish/R/x86_64-pc-linux-gnu-library/3.3/00LOCK-jsonlite/jsonlite': Permission denied
Warning in file.copy(f, instdir, TRUE) :
  problem copying ./NAMESPACE to /home/manish/R/x86_64-pc-linux-gnu-library/3.3/jsonlite/NAMESPACE: Permission denied
Warning in file.copy(f, instdir, TRUE) :
  problem copying ./LICENSE to /home/manish/R/x86_64-pc-linux-gnu-library/3.3/jsonlite/LICENSE: Permission denied
Warning in file.copy(f, instdir, TRUE) :
  problem copying ./NEWS to /home/manish/R/x86_64-pc-linux-gnu-library/3.3/jsonlite/NEWS: Permission denied
Warning in file(file, if (append) "a" else "w") :
  cannot open file '/home/manish/R/x86_64-pc-linux-gnu-library/3.3/jsonlite/DESCRIPTION': Permission denied
Error in file(file, if (append) "a" else "w") : 
  cannot open the connection
ERROR: installing package DESCRIPTION failed for package ‘jsonlite’
* removing ‘/home/manish/R/x86_64-pc-linux-gnu-library/3.3/jsonlite’
Error: Command failed (1)

## Reproducible examples

I am using this command to install package:
devtools::install_github("Microsoft/LightGBM", subdir = "R-package")

When I tried going to to the directory '/home/manish/R/x86_64-pc-linux-gnu-library/3.3/jsonlite' and manually deleting jsonlite package, I couldn't do it. I got the error: Namespace permission denied.

I can't figure out how to overcome this issue.

Thanks in advance
Manish

**Comment by Laurae2** [comment]
4 solutions:

* Run R with the required privileges (you have denied write access)
* Clone git locally and install from there
* Install while ignoring dependencies
* Change your R package directory to a directory where you have read/write access (nuclear option)

**Comment by saraswatmks** [comment]
I am unable to find out how to provide "required privileges" in R. Can you please help ??

**Comment by Laurae2** [comment]
@saraswatmks do you have admin rights on your machine to start R as a user with the permissions you need to write on the folders where you cannot as a regular user?

`ls -l <insert your R library directory>` to find out the permissions.

The problem is obvious in the log you pasted:

* Namespace permission denied
* Permission denied

If you don't change the user running R (someone with permissions to write), or if you don't fix permissions (most dangerous), this can't get fixed.

Run as another user/root example: https://www.cyberciti.biz/open-source/command-line-hacks/linux-run-command-as-different-user/

**Comment by saraswatmks** [comment]
@Laurae2 I am the admin of my machine. How do I give myself permissions to install lightgbm ? Please help me close this. My work is stalled due to this installation issue.

**Comment by saraswatmks** [comment]
This is resolved. Since I am new to linux, I didn't know the way to give permission to a folder.
The solution is:
sudo chmod -R 777 <your path>
