### ISSUE TITLE
feature importance

### ISSUE THREAD

**Issue by mdjabc** [microsoft/LightGBM#3743]
How can lightgbm calculate the importance of the input feature?
The LightGBM records the number of splits of the input features in a single tree, and then, sum the number of splits in all trees to grade the importance of the input characteristics?
some formula can be provided?such as(https://catboost.ai/docs/concepts/fstr.html#fstr).
Thank you!

**Comment by StrikerRUS** [comment]
Yes, you are right!

Here is the code to calculate the importance (2 types):

https://github.com/microsoft/LightGBM/blob/60985495123b0cb99caf0035e953d5152433f85e/src/boosting/gbdt_model_text.cpp#L609-L615

https://github.com/microsoft/LightGBM/blob/60985495123b0cb99caf0035e953d5152433f85e/src/boosting/gbdt_model_text.cpp#L620-L626
