### ISSUE TITLE
Incremental training with LightGBM - save model and resume on new data

### ISSUE THREAD

**Issue by ninenerd** [microsoft/LightGBM#3747]
```
lgbm_gridF = RandomizedSearchCV(**)  # Grid search

lgbm_bestF = lgbm_gridF.fit(X_train, y_train)  #Fit the model 

best_lgbm = lgbm_bestF.best_estimator_  # best estimator 
```

Once I have identified the best model params and saved it, I want to retrain on new data using the previous learnt model. 
I read we will have to save the model in .txt file and reuse using **init_model**  

Any insights how do i save the model and resume training on new data ?

**Comment by StrikerRUS** [comment]
You can use something like this to save the best model and use it as `init_model` later:
```
import lightgbm as lgb

from sklearn.datasets import load_boston
from sklearn.model_selection import RandomizedSearchCV

X_train, y_train = load_boston(return_X_y=True)
est = lgb.LGBMRegressor(n_estimators=5)

lgbm_gridF = RandomizedSearchCV(estimator=est,
                                param_distributions={'extra_trees': [True, False],
                                                     'boost_from_average': [True, False]})  # Grid search

lgbm_bestF = lgbm_gridF.fit(X_train, y_train)  #Fit the model 

best_lgbm = lgbm_bestF.best_estimator_  # best estimator 

best_lgbm.booster_.save_model('model.txt')
new_est = lgb.LGBMRegressor().fit(X, y, init_model='model.txt')
```

**Comment by ninenerd** [comment]
@StrikerRUS One more question, after .fit on new dataset, do we have do Hyper parameter tuning ?  
Is is recommended to change/add anything like add estimators ?  
Does resuming training simply require init_model and .fit ?

**Comment by StrikerRUS** [comment]
It depends on your data. I thinks it will be better to tune hyperparams for a new model, not just reuse params used to train `init_model` model.

**Comment by ninenerd** [comment]
@StrikerRUS After training on new dataset with init_model using :  
`new_est = lgb.LGBMRegressor().fit(X, y, init_model='model.txt')`  
How will grid-search retain the old learning.  
Usually we do HPT , identify best params and then fit on data. So where will we accomodate parameter tuning on re-training between these two lines ?  
`best_lgbm.booster_.save_model('model.txt')
new_est = lgb.LGBMRegressor().fit(X, y, init_model='model.txt')`

**Comment by StrikerRUS** [comment]
> So where will we accomodate parameter tuning on re-training between these two lines ?

I guess it should look like the following:

```
best_lgbm.booster_.save_model('model.txt')

new_search = RandomizedSearchCV().fit(X_tune, y_tune, init_model='model.txt')  # use `**fit_params` https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.RandomizedSearchCV.html#sklearn.model_selection.RandomizedSearchCV.fit

new_est = new_search.best_estimator_.fit(X, y, init_model='model.txt')
```

So that you will tune new model with `init_model` you saved before.

**Comment by ninenerd** [comment]
@StrikerRUS One last question, in my initial model I am using PCA for feature engineering, so two objects will be saved i.e min-max scaler and PCA object.  
When i resume training on data , will i have to create new objects or re-use old model objects for min-max and PCA ? 
Thanks

**Comment by StrikerRUS** [comment]
I think if you sure that your **new** data has the **same statistics** as your previous one, than it is not necessary to re-train old preprocessing models. For example, if max and min values of new data hasn't changed than you don't need to create new min-max scaler for this dataset.
