### ISSUE TITLE
LightGBM model does not load saved in different versions

### ISSUE THREAD

**Issue by u023** [Microsoft/LightGBM#375]
Please search your question on previous issues, stackoverflow or other search engines before you open a new one.

For bugs and unexpected issues, please provide following information, so that we could reproduce on our system.

## Environment info
Operating System: Windows
CPU:
C++/Python/R version: Python 3.5

## Error Message: 
lightgbm.basic.LightGBMError: b'unknow submodel type in model file model.txt
## Steps to reproduce

1. Saved model to model.txt after training using the version installed early this year, load worked for the same version with Python 3.5
2. Try to load with Python 3.6 and the latest LightGBM and got the error above in model load step

**Comment by guolinke** [comment]
refer to #264 .
