### ISSUE TITLE
Typo in Python package: Nump has no attribute RandomState

### ISSUE THREAD

**Issue by jfpuget** [Microsoft/LightGBM#376]
I just cloned the code, and had to modify line 239  in engine.py from
 ` randidx = np.RandomState(seed).random.permutation(num_data)
`
to

 `randidx = np.random.RandomState(seed).permutation(num_data)
`

to get it running correctly in Python 3.5 (Anaconda)

**Comment by Laurae2** [comment]
@jfpuget fixed in PR #377 , thanks for reporting it
