### ISSUE TITLE
 [R-Package] How to distinguish trees constructed for different classes in the output of lgb.model.dt.tree

### ISSUE THREAD

**Issue by ningxb1570** [microsoft/LightGBM#3769]
Hi. I'm using lightgbm package on R 3.6.1. I'm working on a multi-class classification problem and would like to take a closer look at the tree structure. The documentation says that "LightGBM constructs num_class * num_iterations trees for multi-class classification problems". This is consistent with what I saw from the output of lgb.model.dt.tree. But the tree_index ranges from 0 to num_class * num_iterations and I did not see a column that tells which class the node falls into. So I wonder how to distinguish trees constructed for different classes in that data table. 

Thanks.

**Comment by jameslamb** [comment]
Hi @ningxb1570 , thanks for using `{lightgbm}`!

**Short Answer**

For a multiclass task, the trees in the data.table created by `lgb.model.dt.tree()` are ordered by class. So for `num_class = 3`, for example, you'd have the following:

| tree_index | iteration number | class |
|:----------:|:----------------:|:------:|
|0                | 0                          | 0         |
|1                 | 0                          | 1         |
|2                | 0                          | 2         |
|3                | 1                          | 0         |
|4                | 1                          | 1         |
|5                | 1                          | 2         |

In other words, the class for a given tree is equal to `tree_index %% num_class` (remembering that tree_index and class both start at 0).

**Long Answer**

To see details of this, start by training a multiclass model.

```r
library(lightgbm)

set.seed(708L)

data(iris)

# We must convert factors to numeric
# They must be starting from number 0 to use multiclass
# For instance: 0, 1, 2, 3, 4, 5...
iris$Species <- as.numeric(as.factor(iris$Species)) - 1L

feature_names <- names(iris)[names(iris) != "Species"]

dtrain <- lgb.Dataset(
    data = as.matrix(iris[, feature_names])
    , label = iris[, "Species"]
)

bst <- lgb.train(
    params = list(
        metric = "multi_logloss"
        , num_leaves = 5L
    )
    , obj = "multiclass"
    , data = dtrain
    , nrounds = 10L
    , num_class = 3L
)
```

Next, get predictions for the first row of that dataset, based on the model through two iterations.

```r
# just predict on the first row, and get the raw leaf scores
tree2_preds <- bst$predict(
    data = as.matrix(iris[1L, feature_names])
    , start_iteration = 1L
    , num_iteration = 1L
    , rawscore = TRUE
)
tree2_preds
```

> [1]  0.16644193 -0.09554803 -0.09502179

Now grab the details of `lgb.model.dt.tree()` for trees 3, 4, and 5 (the second tree for each class).

```r
# get a data.table representation of the model
modelDT <- lightgbm::lgb.model.dt.tree(
    model = bst
)

# get leaf nodes from the second tree for each class
secondTreeDT <- modelDT[
    !is.na(leaf_value) & tree_index > 2 & tree_index < 6
    , .(tree_index, depth, leaf_value)
]
```

You should see that the score in `tree2_preds` for class=0 only shows up in the tree where tree_index=3, the score for class=1 only shows up in the tree where tree_index=4, and the score for class=2 only shows up in the tree where tree_index=5.

```r
# first predicted value only exists in tree 3
secondTreeDT[leaf_value == tree2_preds[1]]
```

>    tree_index depth leaf_value
1:          3     2  0.166441

```r
# first predicted value only exists in tree 3
secondTreeDT[leaf_value == tree2_preds[2]]
```

>   tree_index depth  leaf_value
1:          4     1 -0.09554803

```r
# first predicted value only exists in tree 3
secondTreeDT[leaf_value == tree2_preds[3]]
```

>   tree_index depth  leaf_value
1:          5     3 -0.09502179

Hope that helps!

**Comment by ningxb1570** [comment]
@jameslamb Thanks for providing such a detailed answer. That's very helpful!
