### ISSUE TITLE
[dask] GPU support 

### ISSUE THREAD

**Issue by jameslamb** [microsoft/LightGBM#3776]
## Summary

The Dask interface in https://github.com/microsoft/LightGBM/blob/706f2af7badc26f6ec68729469ec6ec79a66d802/python-package/lightgbm/dask.py currently only supports CPU-based training.

It should support GPU-based training as well, for those who want to use `lightgbm.dask` to perform multi-GPU training (https://github.com/dask/community/issues/104#issuecomment-718755797).

## Motivation

Adding this feature would allow users to use `lightgbm.dask` as a way to more easily perform multi-GPU training.

## Notes for Reviewers

This issue is intentionally vague on details, because "GPU support" could be done in different ways.

For example, we could consider allowing the Dask model objects to take in [`dask-cudf`](https://github.com/rapidsai/cudf/tree/e86cc6544a1e68bc194f69ef63c1890cbfe25681/python/dask_cudf) data frames if `lightgbm` has been built with CUDA-based GPU support.

## References

This issue was originally posted as https://github.com/dask/dask-lightgbm/issues/22, and more background is available there. Moving it here as part of https://github.com/dask/community/issues/104.

**Comment by jameslamb** [comment]
Closing this, as we use #2302 to track feature requests. Leave a comment below if you'd like to contribute this feature, and we'll be happy to re-open it!

**Comment by StrikerRUS** [comment]
Another action required to address this issue is bringing support of OpenCL-based GPU training or documenting why it can't be supported.

> At some point (maybe when investigating #3776 ), we should look again at why the Dask tests fail on non-CUDA GPU builds.
   https://github.com/microsoft/LightGBM/pull/3825#issuecomment-766271497
