### ISSUE TITLE
for v2, after save, load does not work

### ISSUE THREAD

**Issue by ryutek** [Microsoft/LightGBM#379]
Please search your question on previous issues, stackoverflow or other search engines before you open a new one.

For bugs and unexpected issues, please provide following information, so that we could reproduce on our system.

## Environment info
Operating System: Windows 10
CPU: i7
C++/Python/R version: Python 3.6

## Error Message:
[LightGBM] [Fatal] Wrong size of feature_names
Traceback (most recent call last):
  File "W10CoinLightGBMFinalSubmissionV2_bestscore_0.124101-Copy1.py", line 350, in <module>
    bst2 = lgb.Booster(model_file="model.txt")
  File "C:\Users\ryutek\Anaconda3\lib\site-packages\lightgbm-0.1-py3.6.egg\lightgbm\basic.py", line 1223, in __init__
    ctypes.byref(self.handle)))
  File "C:\Users\ryutek\Anaconda3\lib\site-packages\lightgbm-0.1-py3.6.egg\lightgbm\basic.py", line 47, in _safe_call
    raise LightGBMError(_LIB.LGBM_GetLastError())
lightgbm.basic.LightGBMError: b'Wrong size of feature_names'

## Steps to reproduce

1. Saved model to model.txt with 95 features
2. When trying to load, the error happens: bst = lgb.Booster(model_file="model.txt") 
3.

**Comment by wxchan** [comment]
can you provide a reproducible example with codes?

**Comment by Laurae2** [comment]
Also, can you provide the model file if you can't provide the dataset?

**Comment by ryutek** [comment]
[model.txt](https://github.com/Microsoft/LightGBM/files/901481/model.txt)

This is a simple code line to load the model and an error occurs here. The model file is attached.

import lightgbm as lgb

bst = lgb.Booster(model_file="model.txt")

**Comment by wxchan** [comment]
I see, it's a bug, the feature name is split by space in model file and some of your feature name has a space inside (creativeNameCotainsWeek 7). 

@guolinke how do you think to fix it?

**Comment by guolinke** [comment]
@wxchan convert the space to "_" when set the feature names? 
I think do it in the cpp side may be better.

**Comment by wxchan** [comment]
If we change the feature names, would the user notice it?

How about we use '\n' instead of space? I think '\n' won't appear in feature names (in most cases).

**Comment by Laurae2** [comment]
@guolinke What about preventing users from training a model when features have a space? - or, wrap each feature name with double quotes `""`? We could also use another delimiter which should never be in feature names (return carriages, etc.).

**Comment by guolinke** [comment]
@Laurae2 , if add ```""```, it will be not so straightforward to ```split```. 
I think we output some warnings and then replace these space symbols to ```_``` or ```-``` .
