### ISSUE TITLE
[Question]how to deal with the multi-values in one feature?

### ISSUE THREAD

**Issue by ucasiggcas** [microsoft/LightGBM#3790]
hi,dear all,
In a feature, I have many values,such as the samples down,

index, feature
1,[pretty,good]
2,[prefect,pretty]
3,[good,wonderful]
4,[pretty,good,wonderful]
5,[perfect,wonderful]

So how to address the problem?
thx

**Comment by StrikerRUS** [comment]
Closing as unrelated to LightGBM. Please ask such questions on StackOverflow or similar resources.

You, for example, can split these lists into separate features(columns).
Or maybe try using word/sentence embeddings to encode the whole list of words at once.

**Comment by ucasiggcas** [comment]
it's a pitty you close the issue,
it's the practical problem in industrial circles, and the rp does not support the utility.

**Comment by StrikerRUS** [comment]
Yeah, I understand that this type of data is quite common. But unfortunately, we cannot handle every general question about ML here due to the need to concentrate on **problems** with **LightGBM**.

**Comment by guolinke** [comment]
The simplest way is to split it to multiple one hot features.
