### ISSUE TITLE
[dask] remove testing dependency on dask-ml

### ISSUE THREAD

**Issue by jameslamb** [microsoft/LightGBM#3796]
## Summary

See https://github.com/microsoft/LightGBM/pull/3708#discussion_r558573080. LightGBM's tests currently rely on installing `dask-ml`, but only for a few lightweight metrics functions.

`dask-ml` should be factored out of the tests and CI scripts.

## Motivation

This would reduce the risk of dependency conflicts in CI setup and speed up builds a bit.

## References

@ffineis originally did this in https://github.com/microsoft/LightGBM/pull/3708#discussion_r558573080, but I asked him to pull it out into a separate future PR.

**Comment by jameslamb** [comment]
@ffineis I'm gonna take this one today

**Comment by ffineis** [comment]
<Thumbs up>
