### ISSUE TITLE
log_file param not working

### ISSUE THREAD

**Issue by Laurae2** [Microsoft/LightGBM#38]
I am trying to use the log_file param (as seen on [line 97 config.h](https://github.com/Microsoft/LightGBM/blob/master/include/LightGBM/config.h#L97))  but it seems to not work: no log is output to the file (the file is not even created).

However, the model is trained successfully. I end up with the model file only.

Here is my train.conf:

```
task=train
application=regression
data="lgbm_train.csv"
valid="lgbm_val.csv"
num_iterations=10
early_stopping_rounds=10
learning_rate=0.1
num_leaves=127
tree_learner=serial
num_threads=2
histogram_pool_size=-1
min_data_in_leaf=100
min_sum_hessian_in_leaf=10
feature_fraction=1
feature_fraction_seed=2
bagging_fraction=1
bagging_freq=0
bagging_seed=3
max_bin=255
data_random_seed=1
data_has_label=true
output_model="lgbm_model.txt"
log_file="lgbm_log.txt"
is_sigmoid=true
is_pre_partition=false
is_sparse=true
two_round=false
save_binary=false
sigmoid=1
is_unbalance=false
max_position=20
label_gain=0,1,3,7,15,31,63
metric=l2
metric_freq=1
is_training_metric=true
ndcg_at=1,2,3,4,5
num_machines=1
local_listen_port=12400
time_out=120
```

* Using commit: 1aefcd8a05419ab26e19d34e71c44f0c026e7ce3 (does not work on commit d365762873dac80b9cae7211373f1549a603e328 also)
* Operating System: Windows 8.1

I have looked for extra calls when log_file is present, but did not find any in the source code (except in [config.cpp](https://github.com/Microsoft/LightGBM/blob/master/src/io/config.cpp)). Is it because it is not yet implemented?

**Comment by guolinke** [comment]
@Laurae2  we don't provide the log_file function now, this parameter is dump, i will remove it soon.
You can use [Redirect](http://stackoverflow.com/questions/6674327/redirect-all-output-to-file) instead.

**Comment by chivee** [comment]
@guolinke , perhaps we should adding the function back rather than delete it

**Comment by guolinke** [comment]
I still think we don't need the log file. Redirect can solve most of these problems.
If you still need it, please free feel to reopen.
