### ISSUE TITLE
tree_linear uses only 1 core for predict

### ISSUE THREAD

**Issue by pseudotensor** [microsoft/LightGBM#3812]
using head of master to use tree_linear, and trying it out.  But prediction is very slow and it is using just 1 core..  I can manually parallelize, but wonder if this is just oversight?

**Comment by guolinke** [comment]
cc @btrotta

**Comment by StrikerRUS** [comment]
@pseudotensor Just to clarify: do you observe this with non-default `nthreads` passed to `predict()`?
Refer to https://github.com/microsoft/LightGBM/issues/2225#issuecomment-501220332.

**Comment by pseudotensor** [comment]
I'm using scikit-learn API with regression and assume n_jobs set in model construction will be used for predict.  This is usual for rest of lightgbm.  I only see the problem with tree_linear

I can provide repro if required if not observed by you guys.

**Comment by pseudotensor** [comment]
i.e. I see only these options:
```

predict_proba(X, raw_score=False, start_iteration=0, num_iteration=None, pred_leaf=False, pred_contrib=False, **kwargs) method of lightgbm.sklearn.LGBMClassifier instance
    Return the predicted probability for each class for each sample.
    
    Parameters
    ----------
    X : array-like or sparse matrix of shape = [n_samples, n_features]
        Input features matrix.
    raw_score : bool, optional (default=False)
        Whether to predict raw scores.
    start_iteration : int, optional (default=0)
        Start index of the iteration to predict.
        If <= 0, starts from the first iteration.
    num_iteration : int or None, optional (default=None)
        Total number of iterations used in the prediction.
        If None, if the best iteration exists and start_iteration <= 0, the best iteration is used;
        otherwise, all iterations from ``start_iteration`` are used (no limits).
        If <= 0, all iterations from ``start_iteration`` are used (no limits).
    pred_leaf : bool, optional (default=False)
        Whether to predict leaf index.
    pred_contrib : bool, optional (default=False)
        Whether to predict feature contributions.
    
        .. note::
    
            If you want to get more explanations for your model's predictions using SHAP values,
            like SHAP interaction values,
            you can install the shap package (https://github.com/slundberg/shap).
            Note that unlike the shap package, with ``pred_contrib`` we return a matrix with an extra
            column, where the last column is the expected value.
    
    **kwargs
        Other parameters for the prediction.
    
    Returns
    -------
    predicted_probability : array-like of shape = [n_samples, n_classes]
        The predicted probability for each class for each sample.
    X_leaves : array-like of shape = [n_samples, n_trees * n_classes]
        If ``pred_leaf=True``, the predicted leaf of every tree for each sample.
    X_SHAP_values : array-like of shape = [n_samples, (n_features + 1) * n_classes] or list with n_classes length of such objects
        If ``pred_contrib=True``, the feature contributions for each sample.


```

**Comment by pseudotensor** [comment]
I think this is due to unpickling the model state and then doing predict.  It seems this refreshes things but not all parameters are applied.  I'm not sure it's only due to linear_tree.

**Comment by StrikerRUS** [comment]
> i.e. I see only these options:

`nthreads` (commonly `n_jobs` for sklearn) is passed via `kwargs`:
> **kwargs
        Other parameters for the prediction.

Please try
```
predict_proba(X, n_jobs=8)
```

**Comment by StrikerRUS** [comment]
One more question.

> I'm using scikit-learn API with regression

`predict_proba` with **regression**?

**Comment by StrikerRUS** [comment]
I guess this is the same as https://github.com/microsoft/LightGBM/issues/2516#issuecomment-543474825.

**Comment by pseudotensor** [comment]
Ok thanks, will try that.  Yes, I guess I hit this issue before and wasn't clear if I had posted already, thanks.

**Comment by pseudotensor** [comment]
> One more question.
> 
> > I'm using scikit-learn API with regression
> 
> `predict_proba` with **regression**?

I was using regression but then when I started testing the problem I used a binary problem :)
