### ISSUE TITLE
Support Windows in CUDA version

### ISSUE THREAD

**Issue by StrikerRUS** [microsoft/LightGBM#3837]
Right now CUDA version can be built only on Linux. The main blocker of making CUDA working on Windows is 
>  Unfortunately the CUDA changes for LightGBM require pthreads, as of now, and Windows doesn't (easily) support pthreads.
    https://github.com/microsoft/LightGBM/pull/3160#issuecomment-669258806

**Comment by StrikerRUS** [comment]
Closed in favor of being in #2302. We decided to keep all feature requests in one place.

Welcome to contribute this feature! Please re-open this issue (or post a comment if you are not a topic starter) if you are actively working on implementing this feature.

**Comment by StrikerRUS** [comment]
@shiyu1994 
Are there any plans for supporting new CUDA implementation on Windows? #4528

**Comment by shiyu1994** [comment]
@StrikerRUS Thanks for proposing this, and thanks for the investigation! Definitely, we have plan for CUDA version on Windows, but not necessarily in 4.0.0. If the changes for windows require only minor revision, we may try to include it in 4.0.0. I think by now we'd better focus on make the new CUDA version stable on Linux. And then we can head for Windows. WDYT?

**Comment by StrikerRUS** [comment]
@shiyu1994 Yeah, totally fine! I just wanted to hear your opinion on this issue and further plans. Thanks!

**Comment by jameslamb** [comment]
Sorry, this was locked accidentally. Just unlocked it. We'd still love help with this feature!
