### ISSUE TITLE
Segmentation Fault when training with large dataset in Python

### ISSUE THREAD

**Issue by JayveeHe** [Microsoft/LightGBM#385]
I am using lightGBM in my Python project, I get a problem of segmentation fault when training with large dataset.

Definition of Large dataset: 
I have many csv files which contains samples and features data,  `n_feature=2890+`, `n_sample_per_csv=2230+`. 

To start training, I firstly combine 300+ csv file (parse into np.array) and then use lgb.Dataset() to construct dataset object. 

It will cost about 60+GB memory when I construct dataset with 300 files, and the training works fine.
But when I construct dataset with 320+ files, the memory usage is up to 64+GB, and the Segmentation fault happened.

Here are some of my code: 
```python

params = {
        'objective': 'regression_l2',
        'num_leaves': 7,
        'boosting': 'gbdt',
        'feature_fraction': 0.7,
        'bagging_fraction': 0.7,
        'bagging_freq': 50,
        'verbose': 0,
        'is_unbalance': False,
        'metric': 'l1,l2,huber',
        'num_threads': 24,
        'min_data_in_leaf': 80,
        'lambda_l2': 1.5,
        'save_binary': True,
        'two_round': False,
        'max_bin': 127
    }

data_process_logger.info('building dataset')
train_set = lgb.Dataset(vec_set, label_set, free_raw_data=False)
data_process_logger.info('complete building dataset')
gbm = lgb.train(params, train_set, num_boost_round=save_rounds,
                        early_stopping_rounds=early_stopping_rounds,
                        learning_rates=learning_rates,
                        valid_sets=[train_set],
                        init_model=tmp_model)
```

Outputs:
```
[2017-04-06 22:49:10,207][pid:26877-tid:140557490280192] model_utils.train_with_lightgbm: INFO: building dataset 
[2017-04-06 22:49:10,207][pid:26877-tid:140557490280192] model_utils.train_with_lightgbm: INFO: complete building dataset                         
[2]    26877 segmentation fault (core dumped)  python pipelines/train_models.py
```

*I think maybe there is a pointer problem in calling Booster() of lgb.train()
or any suggestion to avoid this segmentation problem?*

P.S.
- I'm using the latest version of lightGBM
- `two_round` in params seems to make no sense
- I have tested on 2 servers (with 128GB RAM and 256GB RAM), same problem happened.

## Environment info
Operating System: Ubuntu
CPU: Intel(R) Core(TM) i7-5960X CPU @ 3.00GHz
C++/Python/R version: Python 2.7.12

## Error Message:
Segmentation Fault

**Comment by wxchan** [comment]
Does it cause by python? Can you test it on c++ version?

**Comment by guolinke** [comment]
@JayveeHe 
It seems your ```num_data*num_feature``` exceed the ```int32_t::max()```.  refer to #305 
BTW, what is the format of your dataset? Mat ? CSR ? or ...?

**Comment by guolinke** [comment]
@JayveeHe Can you also help try the latest code. I fix one potential bug.

**Comment by JayveeHe** [comment]
@guolinke ok, I will try it.

**Comment by JayveeHe** [comment]
@wxchan I am not pretty sure is it caused by Python, sorry I can't test it on C++ at the moment (maybe later or not)

@guolinke Hi, I tested on the latest code, and the problem doesn't happend again.

I try to reproduce the problem by this [example code](https://gist.github.com/JayveeHe/cf67a90390d601319ec834e467ad0891), with the old(3 days ago, #381 ) version of LightGBM. 
By running the `pass_example1`, the memory usage can be over 70+GB and the problem doesn't happend, `pass_example2` is ok too. But the other examples can not pass and segmentation fault happend. 
So I think, when the dataset is large, there might be something wrong with the format of dataset (the `pass_example1 ` use CSR while the other examples ues np2d Mat).

When testing on the latest version of LightGBM, all of the examples is ok.

FYI, Thanks.

**Comment by guolinke** [comment]
@JayveeHe Thanks.
