### ISSUE TITLE
Using GPU but fall back on cpu 

### ISSUE THREAD

**Issue by lebronjdw** [microsoft/LightGBM#3851]
I am using LGBM on 1th GPU,but when I start training other mission(pytorch DNN) on 2th GPU,then the LGBM forced falling back on CPU without using 1th GPU.This is so weird!!!!
Any ideas?

**Comment by StrikerRUS** [comment]
Could you provide any reproducible example?

I guess `gpu_platform_id` and `gpu_device_id` may help.
https://lightgbm.readthedocs.io/en/latest/Parameters.html#gpu-parameters

**Comment by lebronjdw** [comment]
> Could you provide any reproducible example?
> 
> I guess `gpu_platform_id` and `gpu_device_id` may help.
> https://lightgbm.readthedocs.io/en/latest/Parameters.html#gpu-parameters

Sorry for reply so late,but I have try the parameters you mentioned above,but it failed.
btw,"the reproducible example" is just I cant use any program on cpu,once i use it. It just falls back on cpu

**Comment by jameslamb** [comment]
It's been almost 2 years since the last update on this issue. I'm going to close and lock it. If you're still encountering this, please open a new issue with a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).
