### ISSUE TITLE
When using Booster Method, AttrErr happened 

### ISSUE THREAD

**Issue by youwei2567** [microsoft/LightGBM#3857]
res = gbm.eval(lgb_test, 'test')
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-71-f864b1b98012> in <module>
----> 1 res = gbm.eval(lgb_test, 'test')

E:\anaconda3\lib\site-packages\lightgbm\basic.py in eval(self, data, name, feval)
   2625         if not isinstance(data, Dataset):
   2626             raise TypeError("Can only eval for Dataset instance")
-> 2627         data_idx = -1
   2628         # if data is self.train_set:
   2629             # data_idx = 0

AttributeError: 'Booster' object has no attribute 'train_set'

gbm.update()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-72-397d7fa6e7f5> in <module>
----> 1 gbm.update()

E:\anaconda3\lib\site-packages\lightgbm\basic.py in update(self, train_set, fobj)
   2434         """
   2435         # need reset training data
-> 2436         if train_set is None and self.train_set_version != self.train_set.version:
   2437             train_set = self.train_set
   2438             is_the_same_train_set = False

AttributeError: 'Booster' object has no attribute 'train_set'

## training code is down below:
params = {
    'num_threads':6,
    'boosting_type': 'gbdt', 
    'num_class':rnk,
    'num_leaves': 63,
    'min_gain_to_split':1e-3,
    'bagging_freq':5,
    'bagging_fraction':0.75,
    'feature_fraction':0.5,
    'learning_rate': 0.02,
    'verbose':-1,
}
gbm = lgb.train(params,
                lgb_train,
                num_boost_round=200,
                early_stopping_rounds=5,
                valid_sets=lgb_eval,  # eval training data
                fobj=post_fair,
                feval=r_2,
                )

## is there anything wrong when i call these two methods?

**Comment by StrikerRUS** [comment]
What is the order you execute your pieces of code? Please provide fully reproducible example ([MCVE](https://stackoverflow.com/help/minimal-reproducible-example)) so that we will be able to help.

For now, please check the following quite low-level test which might help you to understand what is going wrong in your code:
https://github.com/microsoft/LightGBM/blob/439c721a6ab2e2d59db0d245c14594367b5e3711/tests/python_package_test/test_basic.py#L15-L43

**Comment by youwei2567** [comment]
I use lgb.train() to get a booster called 'gbm', then I try to call gbm.update() and gbm.eval(). Then these two methods threw a AttrErr. My question is: Is it possible that I use the booster, got from lgb.train(), to call gbm.update() and gbm.eval()

**Comment by youwei2567** [comment]
And I run the snippet of code provided by you, no err happened! Then I use a small part of  my own data to test this snippet of code, last two assertions threw a exception!

**Comment by youwei2567** [comment]
## repoducible code
``
X_tr, X_te, y_tr, y_te = train_test_split(*load_breast_cancer(return_X_y=True), 
                                                     test_size=0.1, random_state=2) 
lgb_train = lgb.Dataset(X_tr, y_tr, free_raw_data=False)
lgb_eval = lgb.Dataset(X_te, y_te, reference=lgb_train, free_raw_data=False)
params = { 
    "objective": "binary", 
    "metric": "auc", 
    "min_data": 10, 
    "num_leaves": 15, 
    "verbose": -1, 
    "num_threads": 1, 
    "max_bin": 255,
} 
gbm = lgb.train(params,
                train_set=lgb_train,
                num_boost_round=20,
                early_stopping_rounds=2,
                valid_sets=lgb_eval,  # eval training data
                )

res = gbm.eval(lgb_eval, 'test')
gbm.update()

**Comment by StrikerRUS** [comment]
> My question is: Is it possible that I use the booster, got from lgb.train(), to call gbm.update() and gbm.eval()

Yeah, it is possible.

Just add `keep_training_booster=True` argument during calling `lgb.train()` function.
