### ISSUE TITLE
R-lintr failures at CI

### ISSUE THREAD

**Issue by StrikerRUS** [microsoft/LightGBM#3873]
Our R-lintr CI is broken. I see this error in `master`, #3866 and #3872.

https://github.com/microsoft/LightGBM/runs/1783657796

```
Warning message:
package ‘lintr’ was built under R version 3.6.3 
[1] 49 R files need linting
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  namespace ‘xfun’ 0.15 is being loaded, but >= 0.19 is required
Calls: <Anonymous> ... namespaceImportFrom -> asNamespace -> loadNamespace
Execution halted
```

**Comment by StrikerRUS** [comment]
cc @jameslamb

**Comment by jameslamb** [comment]
ok looking into this one now

**Comment by jameslamb** [comment]
The most recent release of `r-lintr` on conda-forge was 8 months ago. https://anaconda.org/conda-forge/r-lintr/files

So one of its dependencies must have broken it :confused:
