### ISSUE TITLE
[dask] Result shape from DaskLGBMClassifier.predict(pred_contrib=True) for CSC matrices is inconsistent with LGBMClassifier

### ISSUE THREAD

**Issue by jameslamb** [microsoft/LightGBM#3881]
See the discussion in https://github.com/microsoft/LightGBM/pull/3866#discussion_r566106219 for full details.

`lightgbm.dask.DaskLGBMClassifier` tries to stay as close as possible to the API of `lightgbm.sklearn.LGBMClassifier`. This feature describes one known inconsistency.

In `lightgbm.sklearn.LGBMClassifier`, for multiclass classification tasks, if you call `.predict(X, pred_contrib=True)` and X is a [`scipy.sparse.csc_matrix`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csc_matrix.html), the result will be a list of CSC matrices, 1 per class.

In `lightgbm.dask.DaskLGBMClassifier`, for multiclass classification taks, if you call `.predict(X, pred_contrib=True)` and X is a Dask Array whose partitions are each a [`scipy.sparse.csc_matrix`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csc_matrix.html), the result will be a Dask Array that, once `.compute()`'d, returns a [`scipy.sparse.coo_matrix`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.coo_matrix.html).

To complete this feature, try to make Dask's behavior match the behavior from `lightgbm.sklearn.LGBMClassifier`, or document why that can't / shouldn't be done.

**Comment by jameslamb** [comment]
Added this to #2302, where we store feature requests for this project. Anyone is welcome to contribute this feature. Leave a comment below if you'd like to pick it up and the issue can be re-opened.

**Comment by StrikerRUS** [comment]
One addition:

> In `lightgbm.sklearn.LGBMClassifier`, for multiclass classification tasks, if you call `.predict(X, pred_contrib=True)` and X is a [`scipy.sparse.csc_matrix`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csc_matrix.html), the result will be a list of CSC matrices, 1 per class.

The same is true for CSR matrix as well.

See the following core Python API test to better understand what is expected:
https://github.com/microsoft/LightGBM/blob/217642ca716df8cefb592630907a4e658cd3439a/tests/python_package_test/test_engine.py#L1058-L1100

**Comment by jameslamb** [comment]
re-opening this to note that I am currently working on a fix for this, to try to unblock #4351
