### ISSUE TITLE
[dask] Having workers without data kills the training process

### ISSUE THREAD

**Issue by jmoralez** [microsoft/LightGBM#3882]
## How you are using LightGBM?

LightGBM component: Python package

## Environment info

Operating System: Ubuntu 20.04

CPU/GPU model: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz

C++ compiler version: g++ 9.3.0

CMake version: 3.18.2

Python version: 3.7.9

LightGBM version or commit hash: b6386842d1b24d59928c9bf67333ddafdbda0da9

## Error message and / or logs

[LightGBM] [Warning] Set TCP_NODELAY failed                                                                                                       
[LightGBM] [Warning] Set TCP_NODELAY failed                                                                                                       
[LightGBM] [Info] Trying to bind port 38927...                                                                                                    
[LightGBM] [Info] Trying to bind port 44733...                                                                                                    
[LightGBM] [Info] Binding port 38927 succeeded                                                                                                    
[LightGBM] [Info] Binding port 44733 succeeded                                                                                                    
[LightGBM] [Warning] Set TCP_NODELAY failed                                                                                                       
[LightGBM] [Warning] Set TCP_NODELAY failed                                                                                                       
[LightGBM] [Info] Listening...                                                                                                                    
[LightGBM] [Info] Listening...                                                                                                                    
[LightGBM] [Warning] Connecting to rank 2 failed, waiting for 200 milliseconds                                                                    
[LightGBM] [Warning] Connecting to rank 2 failed, waiting for 200 milliseconds                                                                    
[LightGBM] [Warning] Connecting to rank 2 failed, waiting for 260 milliseconds
[LightGBM] [Warning] Connecting to rank 2 failed, waiting for 260 milliseconds
[LightGBM] [Warning] Connecting to rank 2 failed, waiting for 338 milliseconds
[LightGBM] [Warning] Connecting to rank 2 failed, waiting for 338 milliseconds
[LightGBM] [Warning] Connecting to rank 2 failed, waiting for 439 milliseconds
[LightGBM] [Warning] Connecting to rank 2 failed, waiting for 570 milliseconds
[LightGBM] [Warning] Connecting to rank 2 failed, waiting for 570 milliseconds
[LightGBM] [Warning] Connecting to rank 2 failed, waiting for 741 milliseconds
[LightGBM] [Warning] Connecting to rank 2 failed, waiting for 741 milliseconds
[LightGBM] [Warning] Connecting to rank 2 failed, waiting for 963 milliseconds
[LightGBM] [Warning] Connecting to rank 2 failed, waiting for 963 milliseconds
[LightGBM] [Warning] Connecting to rank 2 failed, waiting for 1251 milliseconds
distributed.nanny - WARNING - Restarting worker

## Reproducible example(s)

```python
import dask.dataframe as dd
import lightgbm.dask as dlgb
import numpy as np
import pandas as pd
from dask.distributed import Client


client = Client(n_workers=3, threads_per_worker=2)
df = pd.DataFrame({
    'x1': np.random.rand(100),
    'x2': np.random.rand(100),
    'y': np.random.rand(100)})
ddf = dd.from_pandas(df, npartitions=2).persist()
X, y = ddf.drop('y', 1), ddf.y
reg = dlgb.DaskLGBMRegressor().fit(X, y, client=client)
```
In this example I have only two partitions and three workers so one worker doesn't have any data but the training process tries to use it. I believe this is a bug that sometimes occurs out of bad luck in some scenarios when a worker is left without data.

**Comment by jameslamb** [comment]
Thank you for the excellent bug report!

I think you might be hitting the same issue that inspired https://github.com/microsoft/LightGBM/pull/3840. Could you try building from latest `master` and see if you still hit this?

I tried something very similar to your example today (more workers than partitions in the data) and didn't hit this problem, but I understand that it's tough because it doesn't ALWAYS happen.

**Comment by jmoralez** [comment]
I just rebuilt using ea8e47ea24fb942155f16da6720b32de976d5731 and I confirm I can't reproduce this anymore. Closing until I (hopefully not) run into this again.

**Comment by jameslamb** [comment]
Thanks! I think it would be good to have a unit test in https://github.com/microsoft/LightGBM/blob/master/tests/python_package_test/test_dask.py that tests that LightGBM behaves well in the "less partitions than workers" situation.

Are you interested in contributing that / do you have the time? If not, no problem and I can do it based on your great reproducible example in this issue.

**Comment by jmoralez** [comment]
I can give it a go if that's ok. Thank you for the suggestion.

**Comment by jameslamb** [comment]
we'd really appreciate it, thanks! `@` me if you have any questions.

**Comment by jmoralez** [comment]
Hi @jameslamb. Should this be a different PR or could I include this in the ports PR?

**Comment by jameslamb** [comment]
A different PR please
