### ISSUE TITLE
[dask] Add a scikit-learn compatibility test

### ISSUE THREAD

**Issue by jameslamb** [microsoft/LightGBM#3894]
## Summary

`scikit-learn` supports a test that people writing scikit-learn extensions can use to check API compatibility with the rest of the scikit-learn ecosystem. Such a test should be added for the code in `python-package/lightgbm/dask.py`.

## Motivation

The discussion in #3883 focused a lot on compatibility of the dask estimators, like `DaskLGBMClassifier`, with the broader scikit-learn ecosystem. It was proposed in https://github.com/microsoft/LightGBM/pull/3883#discussion_r568812631 that we should have a test on the Dask module similar to https://github.com/microsoft/LightGBM/blob/a4cae37c917b039590c0668867557de79212041e/tests/python_package_test/test_sklearn.py#L1169.

I think that actually several of the tests from that module should have Dask equivalents, to test compatibility with the scikit-learn ecosystem.

## References

More information on the scikit-learn API is available in ["Developing scikit-learn estimators"](https://scikit-learn.org/stable/developers/develop.html). In general, changes to `lightgbm.dask` that make it align more closely with that spec are welcome.

**Comment by imjwang** [comment]
Hey, I would like to be assigned this issue. I am in a software methodology class and passionate about data science.

**Comment by jameslamb** [comment]
Thanks @lmjwang! You're welcome to take it.

A few things you should know:

1. the Dask tests will only work on Linux, so you will have to develop in a Linux environment
2. you can build the package from source by running `cd python-package && python setup.py install`
3. you can run just the Dask tests to test your code by running `pytest tests/python_package_test/test_dask.py`

Feel free to ask questions here if you get stuck. Before beginning, please read the items that are linked in the issue's description.

**Comment by imjwang** [comment]
Hey @jameslamb, I'm going through test_sklearn.py and I'm curious why lgb.sklearn.LGBMRanker is not included here?
```
def _tested_estimators():
    for Estimator in [lgb.sklearn.LGBMClassifier, lgb.sklearn.LGBMRegressor]:
        yield Estimator()
```

**Comment by jameslamb** [comment]
Good question! I do not actually know. @StrikerRUS do you know?

By the way in the future, a link to code is more helpful than just copying it: https://github.com/microsoft/LightGBM/blob/e056237b22d4f744c4e3ddf9d9109817becff5e0/tests/python_package_test/test_sklearn.py#L1150

**Comment by StrikerRUS** [comment]
Scikit-learn doesn't have learning-to-rank applications. So there is no point to test LGBMRanker to be "compatible" with something that doesn't support ranking.
From the technical point of view, LGBMRanker requires `group` argument to be passed to `fit()` method. And scikit-learn API tests knows nothing about it.

**Comment by imjwang** [comment]
I copied these lines of code to test_dask.py with their dependencies, but used lgb.DaskLGBMClassifier, lgb.DaskLGBMRegressor for _tested_estimators():
https://github.com/microsoft/LightGBM/blob/a4cae37c917b039590c0668867557de79212041e/tests/python_package_test/test_sklearn.py#L1150-L1182

But running  `pytest tests/python_package_test/test_dask.py -k test_sklearn_integration`
is giving me a bunch of failed tests mostly with `ValueError: No clients found`.

Does this satisfy the task or am I missing something? @jameslamb

**Comment by jameslamb** [comment]
Seems like a good approach! If you feel like you have something that is mostly working, please open a pull request and I can give more specific help there.

For the `No clients found` error...

Creating an instance of the Dask estimators requires an active Dask client. We do this with [a `client` fixture from dask/distributed](https://github.com/dask/distributed/blob/7d2a22f94332974825e599dd779b4d98f44dbca2/distributed/utils_test.py#L544).

You can use this by passing the keyword argument `client` into the test function, like https://github.com/microsoft/LightGBM/blob/18d57934b0299c31637736deeb935242dc7aba13/tests/python_package_test/test_dask.py#L336

**Comment by StrikerRUS** [comment]
We may want to get back for this after resolving upstream issue https://github.com/dask/dask-ml/issues/796.
