### ISSUE TITLE
Cant handle large data on GPU!!!

### ISSUE THREAD

**Issue by lebronjdw** [microsoft/LightGBM#3899]
My GPU is 24G,but one I load data more than about 8.5G.The program breaks down.I found something in source code.But I dont want to modify source code to avoid this situation,so any idea about how to fix this with parameters?

**Comment by jameslamb** [comment]
Thanks for using LightGBM!

We need more details to answer your question. Are you able to provide a reproducible example, with details like:

* how you are using LightGBM (CLI, Python, R, Java, etc.)
* how you installed LightGBM
* what type of GPU you have
* sample code that we could use to reproduce the problem
* specifics on what you mean by "the program breaks down"

> I found something in source code

If you have a proposal to improve LightGBM, we would welcome a pull request with an explanation of the problem and how your code fixes that problem.

**Comment by chaaland** [comment]
A rather [old thread](https://forums.developer.nvidia.com/t/why-is-cl-device-max-mem-alloc-size-never-larger-than-25-of-cl-device-global-mem-size-only-on-nvidia/47745/11) but my understanding of it is that NVIDIA interprets the OpenCL standard as only allowing any particular blob of memory to be at most 25% of device memory. This is an issue I've run into on 32GB GPUs as well and have never known of any work around.

**Comment by lebronjdw** [comment]
> Thanks for using LightGBM!
> 
> We need more details to answer your question. Are you able to provide a reproducible example, with details like:
> 
> * how you are using LightGBM (CLI, Python, R, Java, etc.)
> * how you installed LightGBM
> * what type of GPU you have
> * sample code that we could use to reproduce the problem
> * specifics on what you mean by "the program breaks down"
> 
> > I found something in source code
> 
> If you have a proposal to improve LightGBM, we would welcome a pull request with an explanation of the problem and how your code fixes that problem.
Thank you for you quick replay.

1. By lgb.LGBMRegressor() in python
2. pip install lightgbm --install-option=--gpu
3. NIVIDA RTX TITAN 24GB
4. lgb.LGBMRegressor(x,y) where x is more than 8.5Gb
5. I use "lgb.LGBMRegressor()" in jupyter notebook,And "the program breaks down" means the jupyter kernel breaks down

Looking forward to your reply.
>

**Comment by jameslamb** [comment]
Can you share what you mean by "found something in source code"? If you believe you found an inefficiency in LightGBM that is leading to more memory consumption that necessary, we'd very much appreciate details on that so that it can be fixed.

**Comment by lebronjdw** [comment]
> Can you share what you mean by "found something in source code"? If you believe you found an inefficiency in LightGBM that is leading to more memory consumption that necessary, we'd very much appreciate details on that so that it can be fixed.

Sorry for that I am not sure what i find,so I need some time to check  it.
