### ISSUE TITLE
[dask] Add unit tests that signatures are the same between Dask and scikit-learn estimators

### ISSUE THREAD

**Issue by jameslamb** [microsoft/LightGBM#3907]
## Summary

In a refactoring in #3883, I made a silly mistake and forgot to remove a keyword argument from a method in `DaskLGBMRegressor`.

We should have unit tests on the Dask module that check that estimators' `.fit()` and `.predict()` methods have a similar signature to their scikit-learn equivalents.

## Description

The exposed keyword arguments in `.fit()` and `.predict()` in the Dask estimators are a subset of all the available keyword arguments in their scikit-learn equivalents.

For example,

```python
# lightgbm.dask.DaskLGBMClassifier
def fit(self, X, y, sample_weight=None, **kwargs)

# lightgbm.sklearn.LGBM
def fit(self, X, y,
        sample_weight=None, init_score=None,
        eval_set=None, eval_names=None, eval_sample_weight=None,
        eval_init_score=None, eval_metric=None, early_stopping_rounds=None,
        verbose=True, feature_name='auto', categorical_feature='auto',
        callbacks=None, init_model=None)
```

These tests should check the following:

* every keyword argument in the signature of the Dask estimator's method is in the sklearn estimator's method
* every keyword argument in the signature of the Dask estimator's method is in the same **position** as in the sklearn estimator's method (e.g. `X` is the first argument after `self`)
* every keyword argument in the signature of the Dask estimator's method has the same default value (or lack of default) as in the sklearn estimator's method

## References

Carried over from  this suggestion from @StrikerRUS https://github.com/microsoft/LightGBM/pull/3906#issuecomment-772853820.

See https://github.com/microsoft/LightGBM/blob/b1e000c04590b3437fd12da244528326aa0cc914/tests/python_package_test/test_dask.py#L816 for a reference on how to use `inspect` to do this.

**Comment by GOusignu** [comment]
Hey! I would like to work on this. Pretty new to this, but I'm willing to put in the time

**Comment by jameslamb** [comment]
Sure, thank you very much for volunteering! We look forward to your contribution. Please ask here if you need any help.

**Comment by GOusignu** [comment]
Cool, thanks!

**Comment by GOusignu** [comment]
I have a doubt , 
since checking for subsets (in order of course) is independent of the method (fit, predict) , and of the type of estimator (Regressor, Classifier, Ranker) , wouldn't a single test function do the job?  something like

`def task_dask_estimator_method_arguments_are_subset_of_sklearn_counterparts(methods):`

**Comment by jameslamb** [comment]
I don't understand the question, sorry. You're welcome to open a draft pull request with a proposal when you feel you have something working that accomplishes the goal of this issue. Giving direct feedback on code might be easier than discussing this abstractly.

**Comment by GOusignu** [comment]
ok sure
