### ISSUE TITLE
openmp/gcc compatibility problem with nothrow attribute -> lead compile error

### ISSUE THREAD

**Issue by bsergean** [microsoft/LightGBM#3915]
gcc-9 has a different interface for some function, using the nothrow attribute. I wonder if the fake interface for lightgbm should use nothrow for gcc as well to be compatible. See the compile error below.

## How you are using LightGBM?

* C++ library

## Environment info

Operating System: Linux Ubunu 18.04
C++ compiler version: gcc 9
CMake version: >= 3.17
LightGBM version or commit hash: v3.0.0rc1

## Error message and / or logs

```
/usr/lib/gcc/x86_64-linux-gnu/9/include/omp.h:112:12: error: declaration of 'int omp_get_num_threads() noexcept' has a different exception specifier
  112 | extern int omp_get_num_threads (void) __GOMP_NOTHROW;
In file included from /var/lib/jenkins/workspace/xxx//include/LightGBM/utils/common.h:9,
                 from /var/lib/jenkins/workspace/xxx//include/LightGBM/config.h:16,
                 from /var/lib/jenkins/workspace/xxx//include/LightGBM/dataset.h:8,
                 from /var/lib/jenkins/workspace/xxx//LGBMTree.cpp:7,
                 from /var/lib/jenkins/workspace/xxx/Unity/unity_27_cxx.cxx:5:
xxx/include/LightGBM/utils/openmp_wrapper.h:80:14: note: from previous declaration 'int omp_get_num_threads()'

      |            ^~~~~~~~~~~~~~~~~~~}
      |              ^~~~~~~~~~~~~~~~~~~
```

**Comment by bsergean** [comment]
Other pb with gcc-9 / https://github.com/lammps/lammps/pull/1483, maybe unrelated

**Comment by bsergean** [comment]
This spec does not mention the 'nothrow' attribute. https://www.openmp.org/spec-html/5.1/openmpsu121.html#x160-1930003.2.2

**Comment by jameslamb** [comment]
Hi @bsergean , thanks for using LightGBM, and for reporting this.

Could you please clarify some things for us, so we can be most helpful?

1. What commands did you use to compile LightGBM?
2. Have you tried this on the most recent version of the library (pulling from the most recent commit on `master`)? v3.0.0rc1 [was released several months ago](https://github.com/microsoft/LightGBM/releases/tag/v3.0.0) and there have been many changes since then.

**Comment by bsergean** [comment]
Hi @jameslamb and thanks for taking a look.

1. I was not able to reproduce the error outside of our CMake builds scripts, which use cmake and ExternalProject, and unity builds.
2. The problem is also present in the master branch of LightGBM.

I have made a PR with more info, where I define the attribue __GOMP_NOTHROW like the gcc header do, and like dmlc-core (used by xgboost) do as well.
