### ISSUE TITLE
Unable to install lightgbm in python jupyter - version `GLIBCXX_3.4.22' not found

### ISSUE THREAD

**Issue by saraswatmks** [Microsoft/LightGBM#394]
Please search your question on previous issues, stackoverflow or other search engines before you open a new one.

For bugs and unexpected issues, please provide following information, so that we could reproduce on our system.

## Environment info
Operating System: Ubuntu 16.10
CPU: x86_64-pc-linux-gnu (64-bit)
C++/Python/R version: Python 2.7.13
2.7.13 |Continuum Analytics, Inc.| (default, Dec 20 2016, 23:09:15) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]

I am running jupyter notebook in a conda environment. 
Following are the libraries installed in the environment:

packages in environment at /home/manish/anaconda2/envs/package15:

alabaster                 0.7.10                   py27_0  
astroid                   1.4.9                    py27_0  
babel                     2.4.0                    py27_0  
backports                 1.0                      py27_0  
backports_abc             0.5                      py27_0  
bleach                    1.5.0                    py27_0  
cairo                     1.12.18                       6  
chardet                   2.3.0                    py27_0  
configparser              3.5.0                    py27_0  
cycler                    0.10.0                   py27_0  
dbus                      1.10.10                       0  
decorator                 4.0.11                   py27_0  
docutils                  0.13.1                   py27_0  
entrypoints               0.2.2                    py27_1  
enum34                    1.1.6                    py27_0  
expat                     2.1.0                         0  
fontconfig                2.11.1                        6  
freetype                  2.5.5                         2  
functools32               3.2.3.2                  py27_0  
get_terminal_size         1.0.0                    py27_0  
glib                      2.50.2                        1  
gst-plugins-base          1.8.0                         0  
gstreamer                 1.8.0                         0  
harfbuzz                  0.9.39                        1  
html5lib                  0.999                    py27_0  
icu                       54.1                          0  
imagesize                 0.7.1                    py27_0  
ipykernel                 4.5.2                    py27_0  
ipython                   5.3.0                    py27_0  
ipython_genutils          0.2.0                    py27_0  
isort                     4.2.5                    py27_0  
jedi                      0.9.0                    py27_1  
jinja2                    2.9.5                    py27_0  
jpeg                      8d                            2  
jsonschema                2.5.1                    py27_0  
jupyter_client            5.0.0                    py27_0  
jupyter_core              4.3.0                    py27_0  
lazy-object-proxy         1.2.2                    py27_0  
libffi                    3.2.1                         1  
libgcc                    5.2.0                         0  
libgfortran               3.0.0                         1  
libiconv                  1.14                          0  
libpng                    1.6.27                        0  
libsodium                 1.0.10                        0  
libxcb                    1.12                          1  
libxml2                   2.9.4                         0  
**lightgbm**                  0.1                       <pip>
markupsafe                0.23                     py27_2  
matplotlib                2.0.0               np112py27_0  
mistune                   0.7.4                    py27_0  
mkl                       2017.0.1                      0  
nbconvert                 5.1.1                    py27_0  
nbformat                  4.3.0                    py27_0  
nltk                      3.2.2                    py27_0    anaconda
nose                      1.3.7                    py27_1  
notebook                  4.4.1                    py27_0  
numpy                     1.12.1                   py27_0  
numpydoc                  0.6.0                    py27_0  
openblas                  0.2.19                        0  
openssl                   1.0.2k                        1  
pandas                    0.19.2              np112py27_1  
pandocfilters             1.4.1                    py27_0  
pango                     1.39.0                        0  
path.py                   10.1                     py27_0  
pathlib2                  2.2.0                    py27_0  
pcre                      8.39                          1  
pep8                      1.7.0                    py27_0  
pexpect                   4.2.1                    py27_0  
pickleshare               0.7.4                    py27_0  
pip                       9.0.1                    py27_1  
pixman                    0.32.6                        0  
prompt_toolkit            1.0.13                   py27_0  
psutil                    5.2.1                    py27_0  
ptyprocess                0.5.1                    py27_0  
py2cairo                  1.10.0                   py27_2  
pycairo                   1.10.0                   py27_0  
pyflakes                  1.5.0                    py27_0  
pygments                  2.2.0                    py27_0  
pylint                    1.6.4                    py27_1  
pyparsing                 2.1.4                    py27_0  
pyqt                      5.6.0                    py27_2  
python                    2.7.13                        0  
python-dateutil           2.6.0                    py27_0  
pytz                      2017.2                   py27_0  
pyzmq                     16.0.2                   py27_0  
qt                        5.6.2                         0    anaconda
qtawesome                 0.4.4                    py27_0  
qtconsole                 4.3.0                    py27_0  
qtpy                      1.2.1                    py27_0  
readline                  6.2                           2  
requests                  2.13.0                   py27_0  
rope                      0.9.4                    py27_1  
scandir                   1.5                      py27_0  
scikit-learn              0.18.1              np112py27_1  
scipy                     0.19.0              np112py27_0  
seaborn                   0.7.1                    py27_0  
setuptools                27.2.0                   py27_0  
simplegeneric             0.8.1                    py27_1  
singledispatch            3.4.0.3                  py27_0  
sip                       4.18                     py27_0  
six                       1.10.0                   py27_0  
snowballstemmer           1.2.1                    py27_0  
sphinx                    1.5.4                    py27_0  
spyder                    3.1.3                    py27_0  
sqlite                    3.13.0                        0  
ssl_match_hostname        3.4.0.2                  py27_1  
subprocess32              3.2.7                    py27_0  
terminado                 0.6                      py27_0  
testpath                  0.3                      py27_0  
tk                        8.5.18                        0  
tornado                   4.4.2                    py27_0  
traitlets                 4.3.2                    py27_0  
wcwidth                   0.1.7                    py27_0  
wheel                     0.29.0                   py27_0  
wrapt                     1.10.8                   py27_0  
xgboost                   0.4.0.c4fa2f             py27_0    aterrel
zeromq                    4.1.5                         0  
zlib                      1.2.8                         3  

## Error Message:
import lightgbm as lgb

OSError: /home/manish/anaconda2/envs/package15/lib/python2.7/site-packages/zmq/backend/cython/../../../../.././libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /home/manish/anaconda2/envs/package15/lib/python2.7/site-packages/lightgbm-0.1-py2.7.egg/lightgbm/lib_lightgbm.so)

## Things I've tried
1. conda install libgcc   - isn't helping

What am I missing ?

**Comment by wxchan** [comment]
The error should have nothing to do with lightgbm. Have you tried http://askubuntu.com/questions/575505/glibcxx-3-4-20-not-found-how-to-fix-this-error?

**Comment by saraswatmks** [comment]
Hi @wxchan 
Thanks for the answer.
I don't know why I am facing this error only while installing lightgbm, not with any other package. I tried following the steps given in link above, but nothing seem to be helping.

I am stuck. :(

**Comment by lty1994** [comment]
Did you solve this problem？
