### ISSUE TITLE
[dask] add a DaskDataset

### ISSUE THREAD

**Issue by jameslamb** [microsoft/LightGBM#3944]
## Summary

`lightgbm.dask` should include a `DaskDataset`, a version of the LightGBM `Dataset` object where array-like inputs are provided as Dask collections.

## Motivation

This would greatly simplify the internals for of `lightgbm.dask`'s training code.  It could consolidate the work currently being done by [`_concat()`](https://github.com/microsoft/LightGBM/blob/84c4b7504a49eed63fa819a92db7d0b18292f3f4/python-package/lightgbm/dask.py#L136) + [`_split_to_parts()`](https://github.com/microsoft/LightGBM/blob/84c4b7504a49eed63fa819a92db7d0b18292f3f4/python-package/lightgbm/dask.py#L199) + [all of this `parts` stuff](https://github.com/microsoft/LightGBM/blob/84c4b7504a49eed63fa819a92db7d0b18292f3f4/python-package/lightgbm/dask.py#L289-L317).

This feature is also a necessary prerequisite to supporting a functional, non-sklearn interface (#https://github.com/microsoft/LightGBM/issues/3846). The non-Dask `train()` function takes in a Dataset object (https://github.com/microsoft/LightGBM/blob/84c4b7504a49eed63fa819a92db7d0b18292f3f4/python-package/lightgbm/engine.py#L27).

## Description

Some of LightGBM's most powerful features come from data pre-processing before the training process begins. This includes binning continuous data into histograms, bundling sparse features, and many other pre-processing steps. In LightGBM core, these steps are handled in the `Dataset` object.

* Python: https://github.com/microsoft/LightGBM/blob/84c4b7504a49eed63fa819a92db7d0b18292f3f4/python-package/lightgbm/basic.py#L1035
* C++: https://github.com/microsoft/LightGBM/blob/84c4b7504a49eed63fa819a92db7d0b18292f3f4/src/io/dataset.cpp
* R: https://github.com/microsoft/LightGBM/blob/84c4b7504a49eed63fa819a92db7d0b18292f3f4/R-package/R/lgb.Dataset.R

## References

I described the `Dataset` object at a high level in https://stackoverflow.com/questions/65924856/lightgbm-intent-of-lightgbm-dataset/66004139#66004139.

`xgboost.dask` has already done something similar with their dataset object, the DMatrix

* `DaskDMatrix`: https://github.com/dmlc/xgboost/blob/9a0399e8981b2279d921fe2312f7ab1b880fd3c3/python-package/xgboost/dask.py#L185
* this `xgboost.dask.DaskDMatrix._map_local_data()` is a good reference as well: https://github.com/dmlc/xgboost/blob/9a0399e8981b2279d921fe2312f7ab1b880fd3c3/python-package/xgboost/dask.py#L278

**Comment by jameslamb** [comment]
We keep all feature requests in #2302. Closing this and putting it there. It can be re-opened when it's in progress.

**Comment by StrikerRUS** [comment]
I think it is important to link here the following discussion:

> I am not familiar with dask interface, but I think the python interface lgb.Dataset should support construct by binary file as well.
   https://github.com/microsoft/LightGBM/issues/4026#issuecomment-789499942
