### ISSUE TITLE
[Question] Builtin metrics from python API

### ISSUE THREAD

**Issue by memeplex** [microsoft/LightGBM#3949]
I would like to score my models using metrics provided by lightgbm instead of generic scores like `r2_score` or other provided by sklearn. The closer I got was calling `est.booster_.eval(Dataset(X, y), "arbitrary_name", fobj)` but this:

1. Throws `'Booster' object has no attribute 'train_set'`, at least when `est` was fit using the sklearn API.
2. According to the Python API docs `fobj` is a callable or `None`, so it doesn't seem to support named builtin metrics.
3. Minor quirk: forces me to use an arbitrary name.

Maybe I'm misunderstanding the usage of the method. Maybe `name` is intended to refer to one of the already set validation datasets, but then I don't understand what the first argument is for. And I don't see why the error.

Notice that I don't want to use metrics in fit, for early stopping or whatever, but to score already fit models, for example to call metrics from the `score` method during CV.

Is there any way to access those metrics from python?

**Comment by StrikerRUS** [comment]
@memeplex Sorry for missing this issue!

Is this what you are looked for?

```
import lightgbm as lgb
from sklearn.datasets import load_boston

X, y = load_boston(return_X_y=True)
lgb_data = lgb.Dataset(X, y)
est = lgb.train({'objective': 'regression', 'metric': ['mape', 'rmse']},
                lgb_data, num_boost_round=10, keep_training_booster=True)

new_data = lgb.Dataset(X[:10, :], y[:10], reference=lgb_data)
est.eval(new_data, 'new_data')
```
```
>>> [('new_data', 'mape', 0.13074529807365748, False),
     ('new_data', 'rmse', 3.8224721524651835, False)]
```
