### ISSUE TITLE
[Question] How to realize distributed prediction?

### ISSUE THREAD

**Issue by heroxrq** [Microsoft/LightGBM#396]
My task is to predict a dataset with 400 millions records, with 2 millions (libsvm sparse) feature dimension. In a Linux server with 32 core, it cost 8 seconds predicting 10000 records with full cpu load. This is too slow! So, how to realize distributed prediction? Does LightGBM support spark now? or other solutions for consideration?

**Comment by guolinke** [comment]
A simple solution is partition your prediction data manually, and use different machine to predict the different part. 

The main reason of slow in your task is the high dimension features. I will try to optimize it. 

BTW, you can try the branch ```predict```, I think it can be faster.

**Comment by guolinke** [comment]
@heroxrq just push a new commit in ```predict``` branch. It should be faster for prediction in high dimension feature .

**Comment by heroxrq** [comment]
@guolinke 
it is faster, costs 7 seconds predicting 100000 records, about 10 times speed up. However,  it costs 8 hours to predict 400 millions records.

**Comment by wxchan** [comment]
perhaps you can predict with spark, but I didn't test its performance. you need to install https://github.com/lensacom/sparkit-learn first

one example:

```
import lightgbm as lgb
import pandas as pd
from sklearn.metrics import mean_squared_error

from pyspark import SparkContext
from splearn.rdd import ArrayRDD

class SparkLGBMRegressor(lgb.LGBMRegressor):
    def predict(self, X):
        return X.map(lambda X: super(SparkLGBMRegressor, self).predict(X))

sc = SparkContext()

df_train = pd.read_csv('../regression/regression.train', header=None, sep='\t')
df_test = pd.read_csv('../regression/regression.test', header=None, sep='\t')

y_train = df_train[0].values
y_test = df_test[0].values
X_train = df_train.drop(0, axis=1).values
X_test = df_test.drop(0, axis=1).values

gbm = SparkLGBMRegressor()
gbm.fit(X_train, y_train)
y_pred = gbm.predict(ArrayRDD(sc.parallelize(X_test)))
print('The rmse of prediction is:', mean_squared_error(y_test, y_pred.toarray()) ** 0.5)

sc.stop()
```

**Comment by heroxrq** [comment]
@guolinke 
I have tried to use hadoop streaming to use the lightgbm cli. However, the predict branch is much slower than the master branch.
200 files, with each is 100 M
master branch takes 1 min total to predict
predict branch takes 22 min total to predict
I wonder that why in local machine, the predict branch is faster, but in hadoop streaming, the predict branch is slower!

**Comment by guolinke** [comment]
@heroxrq 
The reason is: To reduce the cost of high dimension feature, it needs an additional cost to collect some information (one pass of all model). For one prediction task, it needs one time of this cost.

So it has 200 times of this additional cost since you have 200 prediction task.

**Comment by heroxrq** [comment]
@guolinke 
But the lightgbm is in mapper, each mapper just need to predict the local data in that node. It has 200 mappers. I think lightgbm in A mapper has no relationship with lightgbm in B Mapper.

**Comment by guolinke** [comment]
I didn't got your point. 
You run one prediction task by calling lightgbm in one mapper, right? So one mapper will have one additional cost.

**Comment by heroxrq** [comment]
@guolinke 
yes, I run one prediction task by calling lightgbm in each mapper as follows. rationally, one mapper have one additional cost. The total time consumed in predict branch should less than in master branch? 
--------------------------------------------------------------------------------------------
predict_mapper.sh:
python read_data_from_stdin.py
tar -zxvf LightGBM.tar.gz > /dev/null
export LD_LIBRARY_PATH="./LightGBM/lib64:${LD_LIBRARY_PATH}"
LightGBM/lightgbm config=predict.conf > /dev/null
.......

**Comment by guolinke** [comment]
@heroxrq 
The ```predict``` branch have such a additional cost, and the master branch not.
So ```predict``` branch may slow when data are small.

**Comment by heroxrq** [comment]
@guolinke 
I have tested almost the same data size in local or mapper. In local, the predict branch is faster, on the contrary, it is faster of master branch in mapper. I wonder whether the cluster environment affect the lightgbm.

**Comment by guolinke** [comment]
@heroxrq 
ok, I got it now.  Not sure about the reason.
BTW, I just push a commit in the predict branch, it avoid the additional cost for the prediction. Can you help to try it and give a speed-up result?

**Comment by heroxrq** [comment]
@guolinke 
I've tried just now, just like predict branch before (local fast, slow in mapper), seems no speed-up.

**Comment by guolinke** [comment]
@heroxrq just update again. Can you try it again.
