### ISSUE TITLE
feature selection

### ISSUE THREAD

**Issue by kingvision** [Microsoft/LightGBM#40]
hi:
  i want to use the code for feature selecting , can you give me some ideas?
or give me an example?
thanks

**Comment by guolinke** [comment]
The function of feature importance is not provided in LightGBM now. 

About the idea of feature selection , you can refer to http://scikit-learn.org/stable/modules/ensemble.html#feature-importance-evaluation .

> The relative rank (i.e. depth) of a feature used as a decision node in a tree can be used to assess the relative importance of that feature with respect to the predictability of the target variable. Features used at the top of the tree contribute to the final prediction decision of a larger fraction of the input samples. The expected fraction of the samples they contribute to can thus be used as an estimate of the relative importance of the features.
> By averaging those expected activity rates over several randomized trees one can reduce the variance of such an estimate and use it for feature selection.

LightGBM provide the readable model file, I think you can parse it then calculate the features importance.

Also welcome the contribution about this function.
