### ISSUE TITLE
linear_tree parameter not recognised by R version of LightGBM

### ISSUE THREAD

**Issue by SpeckledJim2** [microsoft/LightGBM#4001]
## Description
Warning message: [LightGBM] [Warning] Unknown parameter: linear_tree

## Reproducible example

library(lightgbm)
x <- matrix(data = sample(rnorm(100L), size = 100L), ncol = 1L)
y <- 2L * x + runif(nrow(x), 0L, 0.1)
dtrain <- lgb.Dataset(data = x, label = y)

lgb_parameters <- list(
    objective = "regression"
    , linear_tree = TRUE # this parameter isn't recognised by lightGBM
    , verbose = -1L
    , metric = "mse"
    , seed = 0L
    , num_leaves = 2L
    , bagging_freq = 1L
    , subsample = 1.0
)
  
bst_linear <- lgb.train(
  data = dtrain
  , nrounds = 10L
  , params = lgb_parameters
  , valids = list("train" = dtrain)
)

## Environment info
sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.5 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/libopenblasp-r0.2.20.so

lightgbm_3.1.1 R6_2.5.0, installed from CRAN using install.packages('lightgbm')

Many thanks for creating lightgbm!

**Comment by btrotta** [comment]
@SpeckledJim2 Linear trees are not yet available in the CRAN release. As a workaround you can build the package from source, see: https://github.com/microsoft/LightGBM/issues/3910#issuecomment-773430932

**Comment by StrikerRUS** [comment]
@SpeckledJim2 
You can subscribe to LightGBM repository releases

![image](https://user-images.githubusercontent.com/25141164/108500618-1adedd80-72c1-11eb-96bd-2676b7c0386d.png)

or to #3872 particularly 

![image](https://user-images.githubusercontent.com/25141164/108500505-ee2ac600-72c0-11eb-9649-b25586807721.png)


to be notified about updates.

**Comment by SpeckledJim2** [comment]
That's great, all installed and working, thank you!

I will raise another issue when I have created an example because when using predict() with predcontrib = TRUE the feature contributions no longer sum to prediction for the row if linear_tree = TRUE .  I think the feature contributions aren't using the linear model in the leaves, they are still using the constant value, even when linear_tree = TRUE.

**Comment by StrikerRUS** [comment]
> I will raise another issue

Could you please check this one #3998. I guess it is the same case.
