### ISSUE TITLE
MiKTeX setup error at CI in master

### ISSUE THREAD

**Issue by StrikerRUS** [microsoft/LightGBM#4005]
```
Setting up MiKTeX
miktexsetup.exe: The remote package repository is outdated. You have to choose another repository.
miktexsetup.exe: Data: url="https://ctan.math.illinois.edu/systems/win32/miktex/tm/packages/"
```
https://github.com/microsoft/LightGBM/blob/646267d2656cbd13d86e498e96c6db95a9bae5d8/.ci/test_r_package_windows.ps1#L59
Only for Windows. 
Full logs: https://github.com/microsoft/LightGBM/runs/1941681116

cc @jameslamb

**Comment by jameslamb** [comment]
haha NOOOOO we had been doing so well for so long!

I remember that the last time this happened, it went away on its own after a day.

https://github.com/microsoft/LightGBM/issues/3454#issuecomment-707474556

> I think this is just a thing that happens with CTAN a few times a year and we have to wait another day for it to hopefully improve :/

I'll try manually re-running the R jobs on `master` few times over the next few hours, let's see if it resolves itself. If

**Comment by StrikerRUS** [comment]
> it's fine with me if you want to merge things with administrator powers

I don't have them.

**Comment by jameslamb** [comment]
ah I see, my mistake. Well I'm busy for the next few hours, but can look at this tonight if it isn't resolved just by waiting.

**Comment by jameslamb** [comment]
I just started https://github.com/microsoft/LightGBM/runs/1943021929 and I'm hopeful about it, because it looks like the `math.illinois.edu` mirror was updated within the last hour

http://dante.ctan.org/mirmon/

![image](https://user-images.githubusercontent.com/7608904/108605651-22fb5380-737b-11eb-8873-b6afda641ecd.png)

**Comment by jameslamb** [comment]
nope, sad, same failure

> miktexsetup.exe: The remote package repository is outdated. You have to choose another repository.
miktexsetup.exe: Data: url="https://ctan.math.illinois.edu/systems/win32/miktex/tm/packages/"
Error: Process completed with exit code -1.

ok, I'll check back in a few hours

**Comment by StrikerRUS** [comment]
Thank you! I'll try to re-run `master` too.

**Comment by jameslamb** [comment]
@StrikerRUS looks like others have been reporting this too :/

https://github.com/MiKTeX/miktex/issues/720

first report on that issue was 16 hours ago, and maintainers there said 

>  the mirrors are behind the master repository. This is usually self-healing, i.e., it should be okay tomorrow.

So this should be fixed tomorrow, I hope. That's what happened with #3454 back in October as well.

Separately, I'm experimenting with [TinyTex](https://yihui.org/tinytex/) on my fork (https://github.com/jameslamb/LightGBM/pull/40). If we can get that working, we could avoid running into this problem every few months.

**Comment by StrikerRUS** [comment]
Seems the issue is gone now.

**Comment by StrikerRUS** [comment]
But now we have another error with `data.table`: #4008. 👿

**Comment by jameslamb** [comment]
this is happening again 🙃 

Same progression as we've seen before:

1. A bunch of R-package CI jobs start failing with the error "remote package repository is outdated" ([example recent failing build](https://github.com/microsoft/LightGBM/runs/4376112934?check_suite_focus=true))
2. MikTeX maintainers say "this is fixed" (https://github.com/MiKTeX/miktex/issues/980#issuecomment-981084926)
3. more than a day later, more reports that it has not yet actually been fixed (https://github.com/MiKTeX/miktex/issues/980#issuecomment-983026162)

Based on past experiences with this particular issue, I think we just have to wait for the `ctan.math.illinois.edu` mirror to get updated and I think we can expect that to happen in the next day.

**Comment by StrikerRUS** [comment]
Seems to be resolved for the `master` branch.

**Comment by jameslamb** [comment]
Great! I look forward to coming back to this in a few months 😂

**Comment by jameslamb** [comment]
this is happening again 🙃 

* `master`: https://github.com/microsoft/LightGBM/runs/4426237956?check_suite_focus=true
* #4854: https://github.com/microsoft/LightGBM/runs/4425373656?check_suite_focus=true
* #4860: https://github.com/microsoft/LightGBM/runs/4425638956?check_suite_focus=true

Did a little searching to try to learn more about this so we can consider actions other than "just wait and hopefully it will go away".

Here is the code where MiKTeX throws that error:

https://github.com/MiKTeX/miktex/blob/35dfb29cda6a3648d2f18a346caf9bf0f41456ef/Libraries/MiKTeX/PackageManager/RestRemoteService.cpp#L288

https://github.com/MiKTeX/miktex/blob/35dfb29cda6a3648d2f18a346caf9bf0f41456ef/Libraries/MiKTeX/PackageManager/RestRemoteService.cpp#L252

I tried walking back through that code but couldn't find anything that suggested how to ignore this check with an environment variable or command-line flag.

**Comment by jameslamb** [comment]
just pushed an empty commit to re-trigger CI jobs on #4860.

R package CI jobs seem happy again: https://github.com/microsoft/LightGBM/runs/4432231740?check_suite_focus=true
