### ISSUE TITLE
Load Big Model Using C API throw error: [LightGBM] [Fatal] Check failed: (strs.size()) == (static_cast<size_t>(n))

### ISSUE THREAD

**Issue by JackYangzg** [microsoft/LightGBM#4011]
## Description
Using lightgbm 3.1.1

train model using python 3.8, export the model as file.

python can load the model correctly, but using C api load the model, throw  [LightGBM] [Fatal] Check failed: (strs.size()) == (static_cast<size_t>(n))

## Reproducible example
train a model iteration > 5000, feature number: 150
load this model using C api LGBM_BoosterCreateFromModelfile

**Comment by shiyu1994** [comment]
@JackYangzg  Thanks for reporting the bug. Could you provide a code snippet that shows how you load model with C API? Thanks. And I think this issue may be related to #3778 . Both have trouble with `LGBM_BoosterCreateFromModelfile`.

**Comment by JackYangzg** [comment]
> @JackYangzg Thanks for reporting the bug. Could you provide a code snippet that shows how you load model with C API? Thanks. And I think this issue may be related to #3778 . Both have trouble with `LGBM_BoosterCreateFromModelfile`.

just using direct LGBM_BoosterCreateFromModelfile to load

INT32 loadModel(const char *modelPath)
  {
      return LGBM_BoosterCreateFromModelfile(modelPath, &(this->num_iterations), &(this->handle));
  }

**Comment by AlbertoEAF** [comment]
Hmm :thinking:, this is not exactly related, but I'm afraid there was some kind of regression in the master branch. Most code from `common/utils.h`'s `Common` namespace which had been ported to the `CommonC` namespace is there again. I think in the long run this can lead us to use that code again, which might give us locale issues again. Any ideas why this was reintroduced @StrikerRUS @guolinke ?

**Comment by shiyu1994** [comment]
@JackYangzg Could you please try to build from https://github.com/shiyu1994/LightGBM/tree/fix-3778 to see if that branch fixes your problem? I think that may be related to this issue. 

If that doesn't work, could you provide a reproducible example, or your model file, if convenient. Thanks in advanced!

**Comment by StrikerRUS** [comment]
@JackYangzg The above-mentioned fix is in `3.2.0` release, so you can check it.
