### ISSUE TITLE
can we define which category's score shall be plot on the tree with plot_tree function for multiclass classification?

### ISSUE THREAD

**Issue by chloe-wang** [microsoft/LightGBM#4012]
## Summary

I'm not sure the score on the leaves of the tree is for which category for multi class classification task with plot_tree function. I did not see the parameter related to this.

**Comment by shiyu1994** [comment]
@chloe-wang. Thanks for using LightGBM. For multi class classification tasks, the number of trees will be the number of iterations multiplied by the number of classes. So the `tree_index` parameter of `plot_tree` function should take this into account. For example, if you want to plot the tree for category 3 (assuming category count starts from 1) of iteration 100 (assuming iteration count starts from 1), and assuming that the number of classes is 5, then the you should call 
`plot_tree(model, tree_index=5 * 99 + 2)`.

**Comment by chloe-wang** [comment]
@shiyu1994 thanks a lot.

**Comment by chloe-wang** [comment]
sorry, one more question. I thought the tree structure will be shared for all categories while the value on the leaves may be different. However, I plot the trees, and it seems not the case. May I know why?
