### ISSUE TITLE
Unknown token nan(ind) in data file

### ISSUE THREAD

**Issue by tzipperle** [microsoft/LightGBM#4014]
## Description
I my dataset is a categorical feature with some missing rows. This rows are encoded as pd.NA. Fore lightgbm I am converting this feature to pandas category. The training of the model works fine. But when I load the model from a file I geht the following error:
`raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 34 column 18 (char 44602)`

`Unknown token nan(ind) in data file`

## Environment info
LightGBM version or commit hash:
lightgbm 3.1.1 (py38h885f38d_0 - conda-forge)

Command(s) you used to install LightGBM

```shell
conda install - c conda-forge lightgbm
```

Python 3.8.6 | packaged by conda-forge | (default, Dec 26 2020, 04:30:06) [MSC v.1916 64 bit (AMD64)] on win32

**Comment by shiyu1994** [comment]
@tzipperle Did you train the model, then save it to the file, and finally load it from the file again? Could you please produce a reproducible example, or provide the model file? Thanks!

**Comment by tzipperle** [comment]
Here is a reproducible example:

```python
import lightgbm as lgb
import numpy as np
import pandas as pd
from joblib import dump, load
from sklearn.model_selection import train_test_split

# Create dataset
data = pd.DataFrame(np.random.randint(0, 1000, size=(1000, 4)), columns=list('ABCD'))
data['cat'] = np.random.choice(['f1', 'f2', 'f3', 'f4', 'NA'], 1000, p=[0.5, 0.1, 0.1, 0.25, 0.05])
data['cat'] = data['cat'].replace('NA', pd.NA)
data['cat'] = data['cat'].astype('category')
target = np.random.randint(0, 2, size=(1000, 1))

x_train, x_test, y_train, y_test = train_test_split(data, target, test_size=0.3, random_state=27)

# Create model
model = lgb.LGBMClassifier(random_state=1, is_unbalance=True, n_estimators=1_000, learning_rate=0.1, objective='binary',
                           metric='binary_logloss', boosting_type='gbdt')

params_fit = {'early_stopping_rounds': 10,
              'eval_metric': 'auc',
              'eval_names': ['train', 'test'],
              'verbose': 10,
              'eval_set': [(x_train, y_train), (x_test, y_test)]}

model.fit(x_train, y_train, **params_fit)
dump(model, 'model.joblib')
model = load('model.joblib')
```
The line `model = load('model.joblib')` leads to following error:

> [LightGBM] [Fatal] Unknown token nan(ind) in data file
[LightGBM] [Fatal] Unknown token nan(ind) in data file
[LightGBM] [Fatal] Unknown token nan(ind) in data file
[LightGBM] [Warning] [LightGBM] [Warning] Unknown token nan(ind) in data file
Unknown token nan(ind) in data file

**Comment by StrikerRUS** [comment]
I think LightGBM doesn't support `pandas.NA` in category features.

> Unfortunately, LightGBM supports only simple types of categories, e.g. int, float, string.
   https://github.com/microsoft/LightGBM/issues/2134#issuecomment-520261059

What is the purpose of this line?
```
data['cat'] = data['cat'].replace('NA', pd.NA)
```

**Comment by tzipperle** [comment]
The row `data['cat'] = data['cat'].replace('NA', pd.NA)` is just an example. I have a dataset with some missing rows and there this error occurs. When I drop this code row then it is possible to dump and load the model. But when I do this the accuracy goes down - in this example and also in my “realistic” example. Is there a reason for this effect?

Here is the example with an random seed:

```python
import lightgbm as lgb
import numpy as np
import pandas as pd
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split

np.random.seed(42)

# Create dataset
data = pd.DataFrame(np.random.randint(0, 1000, size=(1000, 4)), columns=list('ABCD'))
data['cat'] = np.random.choice(['f1', 'f2', 'f3', 'f4', 'NA'], 1000, p=[0.5, 0.1, 0.1, 0.25, 0.05])
data['cat'] = data['cat'].replace('NA', pd.NA)
data['cat'] = data['cat'].astype('category')
target = np.random.randint(0, 2, size=(1000, 1))

x_train, x_test, y_train, y_test = train_test_split(data, target, test_size=0.3, random_state=27)

# Create model
model = lgb.LGBMClassifier(random_state=1, is_unbalance=True, n_estimators=1_000, learning_rate=0.1, objective='binary',
                           metric='binary_logloss', boosting_type='gbdt')

params_fit = {'early_stopping_rounds': 10,
              'eval_metric': 'auc',
              'eval_names': ['train', 'test'],
              'verbose': 10,
              'eval_set': [(x_train, y_train), (x_test, y_test)]}

model.fit(x_train, y_train, **params_fit)

y_predict = model.predict(x_test)
print(classification_report(y_true=y_test, y_pred=y_predict))
```

with: `data['cat'] = data['cat'].replace('NA', pd.NA)`:
```
              precision    recall  f1-score   support

           0       0.51      0.69      0.59       136
           1       0.63      0.45      0.52       164

    accuracy                           0.56       300
   macro avg       0.57      0.57      0.55       300
weighted avg       0.58      0.56      0.55       300
```

without ~`data['cat'] = data['cat'].replace('NA', pd.NA)`~: 
````
              precision    recall  f1-score   support

           0       0.49      0.72      0.58       136
           1       0.62      0.38      0.47       164

    accuracy                           0.53       300
   macro avg       0.55      0.55      0.53       300
weighted avg       0.56      0.53      0.52       300
```

**Comment by StrikerRUS** [comment]
Could you please try `numpy.nan` instead of `pandas.NA`?

**Comment by tzipperle** [comment]
It seems that the error occurs when the dump command is inside a project and its dependencies. If I try to reproduce the error in an standalone script I have no problems.
