### ISSUE TITLE
lgbm categorical, dataset or parameter dictionary

### ISSUE THREAD

**Issue by germayneng** [microsoft/LightGBM#4017]
## Description
warning from lgbm when passing categorical_features list in parameter dictionary 

## Reproducible example

```
print('Loading data...')
# load or create your dataset
df_train = pd.read_csv('../binary_classification/binary.train', header=None, sep='\t')
df_test = pd.read_csv('../binary_classification/binary.test', header=None, sep='\t')
W_train = pd.read_csv('../binary_classification/binary.train.weight', header=None)[0]
W_test = pd.read_csv('../binary_classification/binary.test.weight', header=None)[0]

y_train = df_train[0]
y_test = df_test[0]
X_train = df_train.drop(0, axis=1)
X_test = df_test.drop(0, axis=1)

num_train, num_feature = X_train.shape

# create dataset for lightgbm
# if you want to re-use data, remember to set free_raw_data=False
lgb_train = lgb.Dataset(X_train, y_train,
                        weight=W_train, free_raw_data=False)
lgb_eval = lgb.Dataset(X_test, y_test, reference=lgb_train,
                       weight=W_test, free_raw_data=False)

# specify your configurations as a dict
params = {
    'boosting_type': 'gbdt',
    'objective': 'binary',
    'metric': 'binary_logloss',
    'num_leaves': 31,
    'learning_rate': 0.05,
    'feature_fraction': 0.9,
    'bagging_fraction': 0.8,
    'bagging_freq': 5,
    'verbose': 0,
    'categorical_feature': [21,22],
    'num_boost_round':10,
    'seed':10
}

# generate feature names
feature_name = ['feature_' + str(col) for col in range(num_feature)]

print('Starting training...')
# feature_name and categorical_feature
gbm = lgb.train(params,
                lgb_train,
                 valid_sets=[lgb_train,lgb_eval],  # eval training data
                feature_name=feature_name)

print('Finished first 10 rounds...')
# check feature name
print('7th feature name is:', lgb_train.feature_name[6])
```

## Environment info

LightGBM version or commit hash: 2.3.1

Command(s) you used to install LightGBM

```shell
conda forge 
```

Hi, the context was that i was using pandas to parse the categorical features. However at inference time, this made it harder to work with array as lgbm will complain and i will need to convert array to pandas. 

Hence, i decided to use the categorical feature index instead. notice that in the documentation, it is adviced to passed as parameter to .Dataset. However, using the example i found that parsing it via the parameter dictionary is giving the same result but got the complain here: 

```
UserWarning: categorical_feature keyword has been found in `params` and will be ignored.
Please use categorical_feature argument of the Dataset constructor to pass this parameter.
  .format(key))
```

Want to check if this is correctly done. I know the results are comparable vs passing it to .Dataset. Just need a confirmation as lgbm was complaining please use .... Dataset constructor.. Thanks!

**Comment by StrikerRUS** [comment]
Refer to https://github.com/microsoft/LightGBM/issues/1408#issuecomment-530096617.
As you've already mentioned, the correct way is to pass categorical features via Dataset constructor. Passing them is `params` is wrong.
