### ISSUE TITLE
[python-package] GPU version installation fails: "Cannot find lightgbm library file in the following path"

### ISSUE THREAD

**Issue by Cwei1** [microsoft/LightGBM#4025]
Hi I am getting the following error when I run python setup.py install --precompile --gpu

raise Exception('Cannot find lightgbm library file in the following paths:'\n'+ '\n'.join(dll_path))

I saw that there was a similar issue resolved in 2017, but there was no clear answer to how it was solved

**Comment by jameslamb** [comment]
Thanks for using LightGBM!

1. Could you please provide the full logs you get when trying to install?
2. Can you tell us what commit of LightGBM you are on?
3. Can you please provide a link to the LightGBM "issue resolved in 2017" you're referring to? Explicitly linking helps us to understand what you're referring to.

**Comment by Cwei1** [comment]
Hi,

I am unable to provide the full logs as it is on a private VM but the issue is essentially the same as issue 
https://github.com/microsoft/LightGBM/issues/474

I am on the most recent commit of LightGBM 3.1.1

As I recall the answer to this was that the user didn't build the lightgbm binary and lib_lightgbm.so
How do I do this?

My situation is a little strange in that I am trying to install lightgbm python package in a RHEL 6 environment, but I cannot do pip install

**Comment by Cwei1** [comment]
Just a note I am running cmake and then going to the python package and running

python setup.py install --precompile --gpu

**Comment by jameslamb** [comment]
By "running CMake", do you mean you exactly followed the steps at https://github.com/microsoft/LightGBM/blob/master/docs/Installation-Guide.rst#build-gpu-version, then ran `python setup.py install --precompile --gpu`? If not, could you share the exact set of commands you ran?

Also, is it absolutely necessary that you use a precompiled version? If you use `python setup.py install --gpu`, you might find that issues like path that you stored the library at are handled for you.

**Comment by Cwei1** [comment]
Yes it is like that cmake command, with the OPENCL and Boost options. As for the precompile, this was the way I was told to do it. Does it not just use the .so file created with the cmake and make command? Or am I completely wrong here

**Comment by Cwei1** [comment]
Also I think I realized the issue might be something to do with the path to BOOST that I have.

**Comment by Cwei1** [comment]
Is there a difference in the CMAKE for RHEL6 vs RHEL7? I seemed to have narrowed down the issue to it not finding CL_VERSION in RHEL6

**Comment by jameslamb** [comment]
> Does it not just use the .so file created with the cmake and make command? Or am I completely wrong here

No that's a totally valid way to install the Python package with GPU support. it's just not the only valid way.

> Is there a difference in the CMAKE for RHEL6 vs RHEL7?

Different operating system versions do commonly have different default versions of packages available when you install them from package managers. Can you tell us the result of running `cmake --version`? I could at least tell you if you have a version of CMake that is supported for LightGBM.

Sorry, it's very difficult to help out when we can't see any logs from CMake or from `python setup.py install`.

**Comment by StrikerRUS** [comment]
`--precompile` flag **cannot** be mixed with any other installation flags.
You either compile dynamic library on your own and then use it during installation via `--precompile` flag, or you shift responsibility 
 for all installation stuff to our Python scripts in `setup.py` file with different optional flags like `--gpu`.

**Comment by StrikerRUS** [comment]
Indeed, without any logs we won't be able to help, unfortunately. Maybe you can remove all sensitive info from logs (they shouldn't be very large) like folder names and post them here? Or probably you can take a look at successful GPU compilation logs https://dev.azure.com/lightgbm-ci/lightgbm-ci/_build/results?buildId=9330&view=logs&j=9ce42e5d-f31a-544a-a6de-dc42f8c013ed&t=b696def5-78ae-590c-4234-04332342ba2d&l=336 and tell us what lines look different in your case?

**Comment by Cwei1** [comment]
Hello, 

So I was given an update to the situation, the GPU portion is no longer and issue, basically as we are trying to install this in a RHEL 6 machine, which only supports up to glibc 2.12 I believe, we need to link it to another library. Where in the make file or the installation process might I be able to put a -lrt and a -fopenmp flag?

**Comment by Cwei1** [comment]
Forgot to add, the current error I am getting is boosting.cpp undefined reference to 'GOMP_parallel'

**Comment by StrikerRUS** [comment]
> RHEL 6 machine, which only supports up to glibc 2.12

According to [this article](https://developers.redhat.com/articles/build-your-first-app-native-gcc-rhel-6-or-7), RHEL 6 has gcc 4.4, but LightGBM can be compiled only with `> 4.8.2` version.
> The native GCC versions are 4.4 on RHEL 6 ...

https://github.com/microsoft/LightGBM/blob/6356e659af74909aa77eb87d54b79f0373772509/CMakeLists.txt#L35-L38


> which only supports up to glibc 2.12 I believe, we need to link it to another library. 

Yeah, LightGBM supports only `> 2.14` GLIBC library. TBH, I don't think that reinstallation of core system-wide OS library is a good idea. It may result in whole system instability. It would be better to use newer OS, RHEL 7, for instance. 

> undefined reference to 'GOMP_parallel'

looks like glibc incompatibility issue, not like OpenMP one.

> Where in the make file or the installation process might I be able to put a -lrt and a -fopenmp flag?

However, if you are brave enough to alter core OS components, the whole LightGBM building process is in [`CMakeLists.txt` file](https://github.com/microsoft/LightGBM/blob/master/CMakeLists.txt) and we rely on CMake for linking OpenMP library properly: 
https://github.com/microsoft/LightGBM/blob/6356e659af74909aa77eb87d54b79f0373772509/CMakeLists.txt#L121-L124

**Comment by Cwei1** [comment]
I am changing the CXX and CC environment variables to link to more recent versions of gcc that are in different directories, and I wanted to do the same with glibc, but I was unsure as to how to do it, or for that matter where in the code to link it. Apologies in advance, I am not very well versed in the gcc libraries and so forth.

**Comment by StrikerRUS** [comment]
> I wanted to do the same with glibc, but I was unsure as to how to do it

I guess you can do it via modifying `LD_LIBRARY_PATH` variable, but again, it is better not to do this, especially if you are not familiar with this.
