### ISSUE TITLE
[LightGBM] [Fatal] Input format error when parsing as LibSVM

### ISSUE THREAD

**Issue by heroxrq** [Microsoft/LightGBM#403]
[LightGBM] [Fatal] Input format error when parsing as LibSVM
[LightGBM] [Fatal] Unknown token abcd-1234 in data file

I use lightgbm to predict LibSVM format data. However it report the above fatal error. I place id (contains Letters and Numbers) of each record in the first column so as to know the id. Since in predict dataset, the label column (first column) has no relationship with predict process. It seems that lightgbm only support Numbers.

**Comment by guolinke** [comment]
yea, it only support numbers except header.
