### ISSUE TITLE
[R-package] Parallelization

### ISSUE THREAD

**Issue by ticarki** [microsoft/LightGBM#4039]
## Description
I work on trained lightGBM models that were exported from python and imported to R. With this model, I want to perform predictions for several thousand samples. By default, it seems like lightgbm::predict() uses as many cores as possible, which is problematic on multi-user systems. I did not find any parameter to change this. Changing the `[num_threads: 0]` parameter in the saved model does not have any effect. Is there any possibility to change the number of used cores?

**Comment by StrikerRUS** [comment]
Hi @ticarki !
You can control number of used threads during prediction via `num_threads` param **passed to [`predict()`](https://lightgbm.readthedocs.io/en/latest/R/reference/predict.lgb.Booster.html) method**.

> ... Additional named arguments passed to the `predict()` method of the `lgb.Booster` object passed to `object`.

**Comment by StrikerRUS** [comment]
Also, `num_threads=0` means
> `0` means default number of threads in OpenMP
     https://lightgbm.readthedocs.io/en/latest/Parameters.html#num_threads

> which is usually the number of cores.
    https://stackoverflow.com/a/4301511

So, it is better to specify exact number of threads you want to use (positive integer number).

**Comment by ticarki** [comment]
Hi @StrikerRUS , thanks a lot for the quick answer! I misunderstood the documentation and only tried `predict(mat, params=list(num_threads=2))`. Now it works, thanks a lot!
