### ISSUE TITLE
linear_tree in lightgbm 3.1.1 / python 3.6

### ISSUE THREAD

**Issue by galenyip** [microsoft/LightGBM#4041]
Hello, may I know if linear_tree is available in the captioned?  Tried to add linear_tree = true in the parm but found a warning:

[LightGBM] [Warning] Unknown parameter: linear_tree

Platform: Windows 10
Python: 3.6.12
Lightgbm 3.1.1 installed via pypi

Thanks!

**Comment by jameslamb** [comment]
Thanks for using LightGBM!

Linear trees are not available in LightGBM 3.1.1. They were adding December 24, 2020 (https://github.com/microsoft/LightGBM/pull/3299) and 3.1.1 was released December 7, 2020 (https://github.com/microsoft/LightGBM/releases/tag/v3.1.1).

The next release (3.2.0) is very close and should be out in the next few weeks. You can subscribe to #3872 to be notified of the 3.2.0 release.

**Comment by StrikerRUS** [comment]
Feel free to install nightly wheel for now:

https://lightgbm.readthedocs.io/en/latest/Installation-Guide.html

![image](https://user-images.githubusercontent.com/25141164/109723088-ad835480-7bbe-11eb-8ba5-446223b0dffd.png)
