### ISSUE TITLE
[python-package] `init_score` and data structures in custom functions shape for multiclass classification

### ISSUE THREAD

**Issue by jmoralez** [microsoft/LightGBM#4046]
## Description

When using `init_score` in multiclass classification it would be very intuitive to use an `(n_samples, n_classes)` collection, as is suggested in https://github.com/microsoft/LightGBM/issues/2595#issuecomment-558561739, however this isn't currently supported in the python package, so you have to reshape this to an `(n_samples * n_classes, )` collection.

This probably isn't that big of a deal with local models, however since dask partitions the collections by rows, this could produce problems with the partitioning.

## Reproducible example

```python
import lightgbm as lgb
import numpy as np

n_samples = 100
n_features = 2
n_classes = 3

X = np.random.rand(n_samples, n_features)
y = np.random.randint(0, n_classes, n_samples)
init_score = np.random.rand(n_samples, n_classes)
lgb.LGBMClassifier().fit(X, y, init_score=init_score)
```

```
Traceback (most recent call last):
  File "init_score.py", line 7, in <module>
    lgb.LGBMClassifier().fit(X, y, init_score=init_score)
  File "/hdd/github/LightGBM/python-package/lightgbm/sklearn.py", line 895, in fit
    callbacks=callbacks, init_model=init_model)
  File "/hdd/github/LightGBM/python-package/lightgbm/sklearn.py", line 688, in fit
    callbacks=callbacks, init_model=init_model)
  File "/hdd/github/LightGBM/python-package/lightgbm/engine.py", line 228, in train
    booster = Booster(params=params, train_set=train_set)
  File "/hdd/github/LightGBM/python-package/lightgbm/basic.py", line 2229, in __init__
    train_set.construct()
  File "/hdd/github/LightGBM/python-package/lightgbm/basic.py", line 1472, in construct
    categorical_feature=self.categorical_feature, params=self.params)
  File "/hdd/github/LightGBM/python-package/lightgbm/basic.py", line 1294, in _lazy_init
    self.set_init_score(init_score)
  File "/hdd/github/LightGBM/python-package/lightgbm/basic.py", line 1843, in set_init_score
    init_score = list_to_1d_numpy(init_score, np.float64, name='init_score')
  File "/hdd/github/LightGBM/python-package/lightgbm/basic.py", line 165, in list_to_1d_numpy
    "It should be list, numpy 1-D array or pandas Series".format(type(data).__name__, name))
TypeError: Wrong type(ndarray) for init_score.
It should be list, numpy 1-D array or pandas Series
```

## Environment info

LightGBM version or commit hash: 37e987828d3141aded1a6e356fdcc7954a6f2f5c

Command(s) you used to install LightGBM

```shell
git clone --recursive https://github.com/microsoft/LightGBM.git
cd LightGBM/python-package
python setup.py install
```

**Comment by StrikerRUS** [comment]
I think this can be applied not only for `init_score` but for all other user-defined data in multiclass case, e.g. `y_pred`, `grad`, `hess` in custom objectives. At least for the consistency. WDYT, @jmoralez ?

**Comment by jmoralez** [comment]
Yes, that'd be nice. I remember a while ago I was very confused when using custom objectives with multiclass classification because `grad` and `hess` were 1d. I'll check this week if this would be easy to implement.

**Comment by StrikerRUS** [comment]
We already re-shape prediction result in the opposite way:
https://github.com/microsoft/LightGBM/blob/e4cf2e4feb2f2cb29cec55070febd74ba8fa28cc/python-package/lightgbm/basic.py#L747-L752

**Comment by StrikerRUS** [comment]
I'd like to broaden this issue and include data structures used in custom objectives and metrics here based on the conversation above and this comment
> I'd also like investigate the possibility to allow `grad` and `hess` to be 2d collections as well for custom objectives.
    https://github.com/microsoft/LightGBM/pull/4150#issue-847900869

to not split the discussion.

**Comment by jameslamb** [comment]
@StrikerRUS I agree, thanks for re-wording and re-opening this.

**Comment by shiyu1994** [comment]
@StrikerRUS Thank you. I do think 2D data structures will be more intuitive for multi-class customized gradients and hessians.

**Comment by StrikerRUS** [comment]
Closing this due to the lack of active work on this issue.

**Comment by jmoralez** [comment]
Reopening since I'm working on this.
