### ISSUE TITLE
Allow LightGBM to be easily used in external projects via modern CMake style with `find_package` and `target_link_libraries`

### ISSUE THREAD

**Issue by nims11** [microsoft/LightGBM#4067]
## Summary

Generate pkg-config file for the library.

## Motivation

pkg-config is a widely used way to provide linker flags and include directories for use in other projects. For example, with cmake, a project can just call `find_package(LightGBM REQUIRED)` and it will set the include directories and linker flags.

Note this applies to use cases when precompiled lightgbm is installed in a system/container. This doesn't apply to projects building with lightgbm with `add_subdirectory`.

## Description

Generate a `.pc` file as part of the build.

## References

https://people.freedesktop.org/~dbn/pkg-config-guide.html

**Comment by jameslamb** [comment]
Thanks very much for your interest in LightGBM! The guide you attached looks helpful.

Could you point to a project that you use that has `pkg-config` support, so that anyone picking up this feature could look at the code there as a reference?

**Comment by nims11** [comment]
[zlib](https://github.com/madler/zlib) has pkg-config support. They do this by having a `[zlib.pc.cmakein](https://github.com/madler/zlib/blob/master/zlib.pc.cmakein)` template which is used to generate the `pc` file during build ([relevant CMakelists.txt lines](https://github.com/madler/zlib/blob/master/CMakeLists.txt#L81-L83)). Afaik, this is a common way of adding pkg-config support.

I will also be happy to contribute if it is something the project considers worth having.

**Comment by StrikerRUS** [comment]
> For example, with cmake, a project can just call `find_package(LightGBM REQUIRED)` and it will set the include directories and linker flags.

For the reference, see how huge refactoring was required for XGBoost to achieve this goal: https://github.com/dmlc/xgboost/pull/4323#issuecomment-480162720.

To be honest, I'm quite sceptical about that `pkg-config` will do all the magic for us.

**Comment by StrikerRUS** [comment]
Closed in favor of being in #2302. We decided to keep all feature requests in one place.

Welcome to contribute this feature! Please re-open this issue (or post a comment if you are not a topic starter) if you are actively working on implementing this feature.

**Comment by StrikerRUS** [comment]
Also, for pkg-config example refer to https://github.com/dmlc/xgboost/pull/5744.
