### ISSUE TITLE
convert Booster model into LGBMClassifier

### ISSUE THREAD

**Issue by huzq2016** [microsoft/LightGBM#4072]
## Description
I used mmlspark.LightGBMClassifier to train a model and saved it and then used lightgbm.Booster to load model, then I want to convert it into onnx model. For some reason, I need to convert Booster into LGBMClassifier before I am able to convert it to onnx.

The part of code snippet:
```
from lightgbm import Booster, LGBMClassifier

# first used mmlspark.LightGBMClassifier to train a model, 
# then saved mode
# then used lightgbm.Booster to load model
bst = Booster(model_file='mmpspark_lightgbmclassifier_model.txt')  

print('The type of model: ', type(bst))
# The type of model:  <class 'lightgbm.basic.Booster'>

# then need to convert Booster into LGBMClassifier

```

**Comment by StrikerRUS** [comment]
Please refer to https://github.com/microsoft/LightGBM/issues/1942#issuecomment-453975607.
