### ISSUE TITLE
How do I print the predict_leaf_index of each predicted value?

### ISSUE THREAD

**Issue by xumotong** [microsoft/LightGBM#4080]
I was doing prediction using a trained a LightGBM classifier.
I set the parameter "predict_leaf_index = True" since I would like to know the leaf node index of each prediction.
But still I don't see the output result contains that information.
Is there any solution to my problem?

**Comment by jameslamb** [comment]
Hi @xumotong , thanks for using LightGBM!

If you are using LightGBM's Python package, you can use `predict(pred_leaf = True)` to see the leaf index in each tree that an observation falls into (note that it is `pred_leaf` not `pred_leaf_index`).

```python
import lightgbm as lgb
from sklearn.datasets import load_breast_cancer

X, y = load_breast_cancer(return_X_y=True)
clf = lgb.LGBMClassifier()
clf.fit(X, y)

leaf_preds = clf.predict(X, pred_leaf=True)
```

See https://stackoverflow.com/a/66188525/3986677 for more information.

If that didn't answer your question, please rephrase and we can reopen the issue.
