### ISSUE TITLE
[LightGBM] [Fatal] Check failed: static_cast<size_t>(num_total_features_) == io_config.monotone_constraints.size()

### ISSUE THREAD

**Issue by flippercy** [microsoft/LightGBM#4083]
When building stacked ensembles in sklearn, sometimes I got an error message in the .out file of Jupyter:

[LightGBM] [Fatal] Check failed: static_cast<size_t>(num_total_features_) == io_config.monotone_constraints.size() at /__w/1/s/python-package/compile/src/io/dataset.cpp, line 314 .

When this happens, the kernel of Jupyter would die.

I used monotone_constraints for the base LightGBM models and they all seemed fine.

Anyone knows what this error means?

Thank you.

**Comment by jameslamb** [comment]
Thanks for using LightGBM!

Can you please provide a reproducible example, including information about how you built LightGBM / the version you're using?

That would help us to give you a better answer.

**Comment by flippercy** [comment]
It is a bit complicated. I am using FLAML (https://github.com/microsoft/FLAML) to do automl. For that, I created a few customized learners with monotone constraints, including two lightGBMs, one using GBDT and the other DART.

If I do not request to build an ensemble, the process ran well; however, when I ask for an ensemble with at least one customized LightGBM learner, I got the issue mentioned above - the kernel just died without any error message and there was an error message logged in the .out file of Jupyter.

As far as I know FLAML uses sklearn to build ensembles and it seems that the issue is not due to FLAML, but probably lightGBM itself.

The codes I used to build the customized lightGBM learner is:

class MyMonotonicLightGBMGBDTClassifier(BaseEstimator):


    def __init__(self, task = 'binary:logistic', n_jobs = num_cores, **params):

        super().__init__(task, **params)

        self.estimator_class = LGBMClassifier

        # convert to int for integer hyperparameters
        self.params = {
            'n_jobs': params['n_jobs'] if 'n_jobs' in params else num_cores,
            'boosting_type':params['boosting_type'] if 'boosting_type' in params else 'gbdt',
            'learning_rate': params['learning_rate'],
            'min_split_gain': params['min_split_gain'],
            'max_depth': int(params['max_depth']),
            'min_data_in_leaf': int(params['min_data_in_leaf']),
            'min_sum_hessian_in_leaf': params['min_sum_hessian_in_leaf'],
            'subsample': params['subsample'],
            'colsample_bytree':params['colsample_bytree'],
            'n_estimators':int(params['n_estimators']),
            'subsample_freq':int(params['subsample_freq']),
            'reg_lambda': params['reg_lambda'],
            'reg_alpha': params['reg_alpha'],
            'random_state': params['random_state'] if 'random_state' in params else randomseed,
            "monotone_constraints":params['monotone_constraints'] if 'monotone_constraints' in params else monotone,
            
       }   

    @classmethod
    def search_space(cls, data_size, task):
        
        space = {        
        'max_depth': {'domain': tune.uniform(lower=4, upper=15), 'init_value': 8},
        'subsample_freq': {'domain': tune.uniform(lower=1, upper=10), 'init_value': 5},
        'n_estimators': {'domain': tune.uniform(lower = 50, upper = 800), 'init_value': 200},
        'min_data_in_leaf': {'domain': tune.uniform(lower = 1, upper = 1000), 'init_value': 100},
        'min_sum_hessian_in_leaf': {'domain': tune.loguniform(lower = 0.000001, upper = 0.1), 'init_value': 0.001},
        'subsample': {'domain': tune.uniform(lower = 0.5, upper = 1), 'init_value': 0.67},
        'colsample_bytree': {'domain': tune.uniform(lower = 0.5, upper = 1), 'init_value': 0.9},
        'learning_rate': {'domain': tune.loguniform(lower = 0.001, upper = 1), 'init_value': 0.1},
        'min_split_gain': {'domain': tune.loguniform(lower = 0.000000000001, upper = 0.001), 'init_value': 0.00001},
        'reg_lambda': {'domain': tune.loguniform(lower = 0.000000000001, upper = 1), 'init_value': 1},
         'reg_alpha': {'domain': tune.loguniform(lower = 0.000000000001, upper = 1), 'init_value': 0.000000000001},
        }
        return space

Is there anything wrong?

**Comment by jameslamb** [comment]
Are you able to share the data or code that could create a dataset that results in this error? And could you please tell me how you built LightGBM / the version you're using?

There has been a lot of work on monotone constraints stuff in the last few months, so I'd like to narrow things down a bit. I agree with the implication of this issue that that error message is hard to understand, and it should probably be caught and replaced with something a bit easier to digest. But I need some more details before I can tell you why your code hit that and how to avoid it.

**Comment by flippercy** [comment]
Sure I will copy the codes here later tonight.

**Comment by shiyu1994** [comment]
@flippercy Currently LightGBM does not check the length of features vs. length of monotone constraints before training. But we provide a description in the document of parameter `monotone_constraints`, which says that `you need to specify all features in order`. That means the user must provide the constraints of all features, if the monotone constraint is used.
