### ISSUE TITLE
Deepcopy lightgbm model causing missing parameters?

### ISSUE THREAD

**Issue by noklam** [microsoft/LightGBM#4085]
## Description
Deepcopy lightgbm model causing model lost parameters
## Reproducible example

```
import pandas as pd
import numpy as np
import lightgbm as lgb
from copy import deepcopy

params = {
'objective': 'regression',
'verbose': -1,
'num_leaves': 3
}

X = np.random.rand(100,2)
Y = np.ravel(np.random.rand(100,1))
lgbm = lgb.train(params, lgb.Dataset(X,label=Y),num_boost_round=1)


print(lgbm.params)

## Deep copy will missing params
new_model = deepcopy(lgbm)
print(new_model.params)

```

Output:

>  {'objective': 'regression', 'verbose': -1, 'num_leaves': 3}
>   Finished loading model, total used 1 iterations
>   {}

## Environment info
Windows 10, Python 3.7.5
LightGBM version or commit hash:
Tested with both lightgbm==2.3.1 and lightgbm==3.1.1 (latest pip version)

Command(s) you used to install LightGBM

```shell

```

**Comment by noklam** [comment]
After digging into the source code, this seems to be the root cause, the `__deepcopy__` only create the Boost object.

https://github.com/microsoft/LightGBM/blob/d6ebd063fff7ff9ed557c3f2bcacc8f9456583e6/python-package/lightgbm/basic.py#L2279-L2282

```
    def __deepcopy__(self, _):
        model_str = self.model_to_string(num_iteration=-1)
        booster = Booster(model_str=model_str)
        return booster
```

**Comment by StrikerRUS** [comment]
Hi @noklam !
Indeed, params are not pre-saved at the Python wrapper layer after save/load process. However, underlying model is correct and it doesn't affect model behavior.
We already have the feature request for displaying original params used to train a model: #2613.

>  I wonder why a custom implementation of `__deepcopy__` is necessary in the first place.

Custom `__deepcopy__` is needed to make `Booster` class picklable.

**Comment by noklam** [comment]
If I understand correctly, the fix should be release in the next version?

**Comment by StrikerRUS** [comment]
Unfortunately, there is no fix for that yet.

**Comment by noklam** [comment]
It seems picklable even without the deepcopy method? I try removed the `__deepcopy__` and parameters is preserved and I can just pickle the model.

```python
import lightgbm
from lightgbm import Booster
del Booster.__deepcopy__

params = {
'objective': 'regression',
'verbose': -1,
'num_leaves': 3
}

X = np.random.rand(100,2)
Y = np.ravel(np.random.rand(100,1))
lgbm = lgb.train(params, lgb.Dataset(X,label=Y),num_boost_round=1)


deepcopy_lgbm = deepcopy(lgbm)
lgbm.params, deepcopy_lgbm.params
```


![image](https://user-images.githubusercontent.com/18221871/111814286-429f8080-8915-11eb-95e7-f7c24479cddd.png)

**Comment by StrikerRUS** [comment]
Please refer to the following PR where custom `__deepcopy__` was introduced and feel free to provide a PR if you think that this code can be removed.
#151

**Comment by StrikerRUS** [comment]
But I think that without custom `__deepcopy__` cloned Booster will handle the same underlying cpp object as the original one.
