### ISSUE TITLE
Inconsistent prediction when the order of the columns of pandas dataframe is different from training

### ISSUE THREAD

**Issue by louis925** [microsoft/LightGBM#4102]
## Description
Reorder the columns of a pandas dataframe during prediction will result in inconsistent result if that columns order is different from what was used in training. Lightgbm python API doesn't seem to recognize the column names of pandas dataframes.

## Reproducible example
```python
import numpy as np
import pandas as pd
import lightgbm as lgb
df = pd.DataFrame(
    [[0, 1, 1]] * 24 + [[0, 1, 0]] * 24 + [[1, 0, 0]] * 21 + [[1, 0, 1]] * 21,
    columns=['y', 'x1', 'x2'],
)
cols_feat = ['x1', 'x2']
y_true = df['y']
lgb_train = lgb.Dataset(df[cols_feat], y_true)
model = lgb.train({}, lgb_train)

# original order of columns
y_pred = model.predict(df[cols_feat])
print(y_pred)
# [1.23953194e-05, ..., 9.99985834e-01, ...]
print('loss:', np.mean((y_pred - y_true)**2))
# loss: 1.7559308212239284e-10

# reverse the order of columns
y_pred2 = model.predict(df[cols_feat[::-1]])
print(y_pred2)
# [1.23953194e-05, ..., 9.99985834e-01, ..., 1.23953194e-05. ...]
print('loss:', np.mean((y_pred2 - y_true)**2))
# loss: 0.49998666045229395, much worse than the original order
```

## Environment info

LightGBM version or commit hash:  2.3.1

Command(s) you used to install LightGBM

```shell
pip3 install lightgbm
```

## Additional Comments

Not sure if this is a bug or should be a feature request. Since Lightgbm model clearly know the feature name (`model.feature_name()`) but the prediction stage doesn't check this, which can lead to some confusion, it will be great if lightgbm can check the order of columns for prediction. Thanks!

**Comment by StrikerRUS** [comment]
> Not sure if this is a bug or should be a feature request. 

It is more likely to be a feature request. Please refer to https://github.com/microsoft/LightGBM/issues/4020#issuecomment-785862574.

**Comment by StrikerRUS** [comment]
I remembered we already have a such feature request. Anybody is welcome to contribute!
Refer to https://github.com/microsoft/LightGBM/issues/812#issuecomment-538069245.
