### ISSUE TITLE
[R-package] test on non-ASCII feature names fails on debian + clang CRAN check

### ISSUE THREAD

**Issue by jameslamb** [microsoft/LightGBM#4105]
## Description

`{lightgbm}` 3.2.0 was recently released to CRAN (#3872 , https://cran.r-project.org/web/packages/lightgbm/index.html). One of the CRAN checks is currently failing while running unit tests.

https://cran.r-project.org/web/checks/check_results_lightgbm.html

![image](https://user-images.githubusercontent.com/7608904/112347477-e336cd00-8c94-11eb-8397-c6843b7dcc3d.png)

```text
  == Failed tests ================================================================
  -- Failure (test_basic.R:1233:5): lgb.train() supports non-ASCII feature names --
  dumped_model[["feature_names"]] not identical to `feature_names`.
  4/4 mismatches
  x[1]: "F_é\u009b¶"
  y[1]: "F_<U+96F6>"
  
  x[2]: "F_äž\u0080"
  y[2]: "F_<U+4E00>"
  
  x[3]: "F_äº\u008c"
  y[3]: "F_<U+4E8C>"
  
  x[4]: "F_äž\u0089"
  y[4]: "F_<U+4E09>"
  
  [ FAIL 1 | WARN 0 | SKIP 3 | PASS 633 ]
  Error: Test failures
  Execution halted
checking PDF version of manual ... OK
checking for non-standard things in the check directory ... OK
DONE
Status: 1 ERROR
````

Full logs are too large to post, but they'll be available at https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-debian-clang/lightgbm-00check.html for a few days.

## Reproducible example

N/A - this failure happened on CRAN. I haven't had a chance yet to try it on the equivalent R Hub environment.

## Environment info

Details on this test can be found at https://cran.r-project.org/web/checks/check_flavors.html#r-devel-linux-x86_64-debian-clang.

## Additional Comments

`{lightgbm}`'s CRAN package is currently only tested with with `gcc`: https://github.com/microsoft/LightGBM/blob/ab474dc4035416ef512961ea14595a729b55e1ef/.github/workflows/r_package.yml#L104-L108

although the R package built with CMake is tested on Linux with `clang`: https://github.com/microsoft/LightGBM/blob/ab474dc4035416ef512961ea14595a729b55e1ef/.github/workflows/r_package.yml#L33-L42

**Comment by jameslamb** [comment]
Some additional notes:

1. I'll open a PR tonight that just adds a `testthat::skip_on_cran()` to the one problematic test. Then we can avoid being removed from CRAN and can fix the issue on our own timeline.
2. Based on previous interactions with CRAN, I won't re-submit until they send an email asking us to. @guolinke can you please let me know if you receive any emails from CRAN?
3. Tonight, I'll also try adding a CI job that uses `clang` on `ubuntu-latest` with the `cran` package to see if this would have caught it. If not, I'll try running on `r-devel-linux-x86_64-debian-clang` using R Hub.

**Comment by StrikerRUS** [comment]
I also see some weird warnings in the logs:
```
     [LightGBM] [Warning] Unknown parameter: 0x76d8268>
     [LightGBM] [Warning] Unknown parameter: valids
     [LightGBM] [Warning] Unknown parameter: 0x76d8268>
     [LightGBM] [Warning] Unknown parameter: valids
     [LightGBM] [Warning] Unknown parameter: 0x76d8268>
     [LightGBM] [Warning] Unknown parameter: valids

...

     [LightGBM] [Warning] Unknown parameter: categorical_featurs
     [LightGBM] [Warning] Unknown parameter: categorical_featurs
     [LightGBM] [Warning] Unknown parameter: categorical_featurs
     [LightGBM] [Warning] Unknown parameter: categorical_featurs

...

     [LightGBM] [Warning] Unknown parameter: 2,3
     [LightGBM] [Warning] Unknown parameter: 127,3
     [LightGBM] [Warning] Unknown parameter: 2,3
     [LightGBM] [Warning] Unknown parameter: 2,3

...

     [LightGBM] [Warning] Unknown parameter: 2,3
     [LightGBM] [Warning] Unknown parameter interaction_constraints=cap-shape=bell
     [LightGBM] [Warning] Unknown parameter cap-shape=conical,cap-shape=convex
     [LightGBM] [Warning] Unknown parameter: ,
     [LightGBM] [Warning] Unknown parameter: 2,3
```

Are they all from that failing test?..

**Comment by jameslamb** [comment]
hmmm not sure! Will have to investigate. Those all seem related to places where we take an R vector, concatenate its values, and write the to a string so they could also be related to encoding issues.

**Comment by StrikerRUS** [comment]
> `categorical_featurs`

This one looks like a typo (`categorical_featurEs`). And seems it comes from here (not failing test), so I guess we see logs from ALL tests on CRAN page in case of at least one of them fails.
https://github.com/microsoft/LightGBM/blob/b2705dc49daadc772a0d57a60e35070a0e6584cb/R-package/tests/testthat/test_basic.R#L1886

**Comment by jameslamb** [comment]
ah!!! Good eye.

**Comment by jameslamb** [comment]
I wasn't able to add a CI test for this and investigate further, will try to check tomorrow. I've opened #4109 to fix the `categorical_features` typo. I also kicked off an R Hub build on `debian-clang-devel`, with the package built from `master`.

Posting the link here, it should be done in the next few minutes but I'm signing off for the day: https://builder.r-hub.io/status/lightgbm_3.2.0.99.tar.gz-2492c0f28ca84993b53a3778f3dc5138

**Comment by jameslamb** [comment]
Well, "good" news...the R Hub check failed with exactly the same error we got on CRAN.

![image](https://user-images.githubusercontent.com/7608904/112523176-7b53b580-8d6c-11eb-9179-91b4dd3c43d3.png)

So at least that means that check is probably a reliable way to replicate CRAN, and therefore a good way to test fixes.

**Comment by StrikerRUS** [comment]
@jameslamb 
> **guolinke** can you please let me know if you receive any emails from CRAN?

I remember, he asked email him for important things.

> If not, I'll try running on `r-devel-linux-x86_64-debian-clang` using R Hub.


We can replicate valuable things or use this Docker directly, I think.
https://github.com/r-hub/rhub-linux-builders/blob/master/debian-clang-devel/Dockerfile

**Comment by jameslamb** [comment]
Oh right! Will send an email right now.

**Comment by jameslamb** [comment]
Guolin emailed me back...CRAN has not asked for a re-submission. So this issue should still be fixed but it seems that right now we don't need to worry about the time pressure of re-submitting to CRAN.

**Comment by jameslamb** [comment]
I think this can be closed, given:

* #5526
* https://github.com/microsoft/LightGBM/issues/5502#issuecomment-1304715420
