### ISSUE TITLE
What label= should be for the regression model?

### ISSUE THREAD

**Issue by Roffild** [microsoft/LightGBM#4115]
```python
mylbl = numpy.array([[0.], [0.], [1.], [0.], [1.]], dtype=numpy.float32)
mylbl.ndim == 2
```

xgboost.DMatrix(label=)
* `label : list, numpy 1-D array or cudf.DataFrame, optional
            Label of the training data.`
* `label=None`
`xgboost.core.XGBoostError: src/objective/regression_obj.cu:57: Check failed: preds.Size() == info.labels_.Size() (61872 vs. 0) :  labels are not correctly providedpreds.size=61872, label.size=0, Loss: binary:logistic`
* `label=mylbl` - OK

catboost.Pool(label=)
* `label : list or numpy.ndarrays or pandas.DataFrame or pandas.Series, optional (default=None)
            Label of the training data.
            If not None, giving 1 or 2 dimensional array like data with floats.`
* `label=None`
`File "catboost\core.py", line 976, in _build_train_pool
    raise CatBoostError("Label in X has not been initialized.")`
* `label=mylbl` - OK

lightgbm.Dataset(label=)
* `label : list, numpy 1-D array, pandas Series / one-column DataFrame or None, optional (default=None)
            Label of the data.`
* `label=None` - OK
* `label=mylbl`
`File "lightgbm\basic.py", line 93, in list_to_1d_numpy
    raise TypeError("Wrong type({0}) for {1}.\n"
TypeError: Wrong type(ndarray) for label.
It should be list, numpy 1-D array or pandas Series`

Can you accept a single standard?

Parameter description is incorrect.

**Comment by Roffild** [comment]
https://github.com/dmlc/xgboost/issues/6786
https://github.com/catboost/catboost/issues/1623
https://github.com/microsoft/LightGBM/issues/4115

**Comment by Roffild** [comment]
Used training.

**Comment by StrikerRUS** [comment]
Please update LightGBM to `3.2.0` version. Refer to #3943.


```
import numpy as np
import lightgbm as lgb

mylbl = np.array([[0.], [0.], [1.], [0.], [1.]], dtype=np.float32)
assert mylbl.ndim == 2

X = np.array([[1, 2], [1, 2], [3, 4], [7, 8], [3, 4]])
lgb_data = lgb.Dataset(X, mylbl)

lgb.train({'objective': 'binary'}, lgb_data, num_boost_round=2)
```

```
...
>>> E:\Miniconda3\lib\site-packages\lightgbm\basic.py:154: UserWarning: Converting column-vector to 1d array
```
