### ISSUE TITLE
[help wanted] how to use cuda version

### ISSUE THREAD

**Issue by 7starsea** [microsoft/LightGBM#4120]
I compiled the cuda version of lightgbm by following https://lightgbm.readthedocs.io/en/latest/Installation-Guide.html#build-cuda-version-experimental

However, when I try to run the cuda version (with the same parameter used in GPU version based on OpenCL), I encounter the following error
"lightgbm.basic.LightGBMError: GPU Tree Learner was not enabled in this build, Please recompile with CMake option -DUSE_GPU=1" 

Is the parameters in the cuda version different from the gpu version? 
Could any one help me here? 

Thanks.
Aimin

**Comment by StrikerRUS** [comment]
@7starsea Hi!

Good catch, thanks!
Please use `device_type="cuda"` instead of `device_type="gpu"`.
I'll fix docs clarifying this.

**Comment by 7starsea** [comment]
I trained a project (project size (sample, feature) = (18909697, 128)) with the gpu version and the max gpu memory obsesrved is around 3000MB, however, I failed to train this project with the cuda version because of cuda out of memory error.

**Comment by StrikerRUS** [comment]
Please open a new issue with more details for out of memory error preferably with reproducible example on randomly generated data.

I guess this difference can be due to the fact that 

> in CUDA implementation only double precision is currently supported

and in OpenCL one single precision is used by default.

Maybe you can try to use multiple GPUs with CUDA version?
