### ISSUE TITLE
Enable MM_PREFETCH and MM_MALLOC on aarch64

### ISSUE THREAD

**Issue by StrikerRUS** [microsoft/LightGBM#4124]
Refer to https://github.com/microsoft/LightGBM/pull/3948#issuecomment-778392829.

Related source codes:

https://github.com/microsoft/LightGBM/blob/e98da99d88aaee09a8dbd5204c5355fc099fe5f0/CMakeLists.txt#L243-L271

https://github.com/microsoft/LightGBM/blob/e98da99d88aaee09a8dbd5204c5355fc099fe5f0/include/LightGBM/meta.h#L16-L23

https://github.com/microsoft/LightGBM/blob/e98da99d88aaee09a8dbd5204c5355fc099fe5f0/include/LightGBM/utils/common.h#L44-L58

**Comment by StrikerRUS** [comment]
Closed in favor of being in #2302. We decided to keep all feature requests in one place.

Welcome to contribute this feature! Please re-open this issue (or post a comment if you are not a topic starter) if you are actively working on implementing this feature.

**Comment by jameslamb** [comment]
See the error at https://clang.llvm.org/doxygen/xmmintrin_8h_source.html.

```text
"This header is only meant to be used on x86 and x64 architecture"
```

This can be reproduced like this:

```cpp
// conftest.cpp
#include <xmmintrin.h>

void main() {
    int a = 0;
    _mm_prefetch(&a, _MM_HINT_NTA);
    return 0;
}
```

```shell
clang++ -arch arm64 -std=gnu++17 -o conftest conftest.cpp
```

**Comment by StrikerRUS** [comment]
I'm not an expert in all these thing at all, but it looks like Arm Compiler support prefetching via `__builtin_prefetch`.
https://developer.arm.com/documentation/101458/2404/Optimize/Prefetching-with---builtin-prefetch?lang=en

**Comment by StrikerRUS** [comment]
Linking #4331 and https://github.com/microsoft/LightGBM/pull/6514#issuecomment-2224968725.
