### ISSUE TITLE
[ci] CUDA builds failing to start

### ISSUE THREAD

**Issue by jameslamb** [microsoft/LightGBM#4165]
## Description

For the last day, I've observed that CUDA builds (defined in https://github.com/microsoft/LightGBM/blob/b674439aec933e0c1b72efc7dda482a9c7e75283/.github/workflows/cuda.yml) are failing without logs.

Jobs just failed with "This check failed".

![image](https://user-images.githubusercontent.com/7608904/113763148-f60ec000-96de-11eb-89cf-7242e8bf885b.png)

## Reproducible example

I've seen this across several pull requests so I don't think it's specific to any one PR's changes. See https://github.com/microsoft/LightGBM/actions/workflows/cuda.yml.

The most recent successful run was 23 hours ago, the first failed run was 21 hours ago.

![image](https://user-images.githubusercontent.com/7608904/113763425-4be36800-96df-11eb-895f-60afcc0bd102.png)

## Additional Comments

I can't debug this because I don't think I have access to wherever the machine for this job is managed (https://github.com/microsoft/LightGBM/issues/3402#issuecomment-699198779).

I've labeled this `blocking` because it seems to be happening across all recent PRs.

**Comment by StrikerRUS** [comment]
I can't find `linux-gpu-pool` anymore. I guess it was removed...

![image](https://user-images.githubusercontent.com/25141164/113765871-7b1cc800-9725-11eb-8352-0f5e376a5356.png)

**Comment by jameslamb** [comment]
ah!! @shiyu1994 is it something you can help us with?

**Comment by jameslamb** [comment]
I came back to this and based on the URL in that screenshot, I do actually have permissions to see those agent pools! Just didn't notice it in the UI before.

But I do see the same as you...the `linux-gpu-pool` pool is gone.

**Comment by StrikerRUS** [comment]
I'll ask @guolinke in email today.

**Comment by StrikerRUS** [comment]
Guolin replied in email that he asked his colleagues fix this issue.

**Comment by guolinke** [comment]
Hi @StrikerRUS and @jameslamb 
I think the GPU agent is hosted in github actions, not the azure pipeline, right?

![image](https://user-images.githubusercontent.com/16040950/114301526-e1279780-9af7-11eb-90c1-13332b237e1d.png)

The VM of that agent is down, we just restart it.

**Comment by StrikerRUS** [comment]
@guolinke Yes you are right!

Could you please wipe everything on that runner, install just GitHub Actions agent and NVIDIA driver and restart the agent?
Right now jobs fail with
```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:367: starting container process caused: process_linux.go:495: container init caused: Running hook #0:: error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: initialization error: nvml error: driver not loaded: unknown.
```

**Comment by guolinke** [comment]
@StrikerRUS oh, sure, it seems the driver is dead, as the kernel upgraded.

**Comment by StrikerRUS** [comment]
@guolinke Thank you very much!
