### ISSUE TITLE
[Help] - advice on how to modify code for research

### ISSUE THREAD

**Issue by dancaspi** [Microsoft/LightGBM#417]
Hey,
I am researching methods of improving tree based predictions. I have various schemes I would like try for fitting leaf scores. What would be the recommended approach to modify the source code such that I could **use the generated trees** but modify the eventual leaf scores? My preference would be to use only R/Python ,  even somewhat at the cost of speed (as this is mainly theoretical as this point). If this is not possible, I could also modify the underlying C/C++ code, but prefer to test new hypothesis without recompiling the source code.

thanks,
Dan

**Comment by guolinke** [comment]
@dancaspi 
you can use these two c_api to edit leave output vaules: https://github.com/Microsoft/LightGBM/blob/master/src/c_api.cpp#L1065-L1083

**Comment by dancaspi** [comment]
@guolinke  Wow thanks for the quick reply. much appreciated!
