### ISSUE TITLE
[mmlspark] how to deal with "Stopped training because there are no more leaves that meet the split requirements"

### ISSUE THREAD

**Issue by imatiach-msft** [microsoft/LightGBM#4178]
## Description
Customer is seeing issue where LightGBM regressor in mmlspark is giving bad outputs with default parameters.  Investigating the issue, I found that LightGBM is outputting "[Warning] Stopped training because there are no more leaves that meet the split requirements".  The problem seems to be that we hit this code:

https://github.com/microsoft/LightGBM/blob/master/src/boosting/gbdt.cpp#L441

But then this last tree seems to cause junk predictions, values close to infinity:
[LightGBM] [Debug] Trained a tree with leaves = 1 and max_depth = 1

For example (true label vs what lightgbm predicted for target):
![image](https://user-images.githubusercontent.com/24683184/114812406-ebf35e00-9d7d-11eb-8f7f-e5d924451565.png)

Setting fewer iterations than the last iteration seems to resolve the issue.
Although I can detect that LGBM_BoosterUpdateOneIter is returning false when it hits this case, should I actually be setting the iteration on the booster to be the one before last, or is that something that lightgbm should be doing?  Or, should the last tree with a single node not be producing values close to infinity?

In python API I see we return that function's result:
https://github.com/microsoft/LightGBM/blob/master/python-package/lightgbm/basic.py#L2647
but it doesn't look like it is used or checked anywhere, including the dask implementation:
https://github.com/microsoft/LightGBM/blob/master/python-package/lightgbm/dask.py#L90
or python implementation:
https://github.com/microsoft/LightGBM/blob/master/python-package/lightgbm/engine.py#L249

## Reproducible example
Since this is in spark it will be difficult to reproduce, but I have access to a cluster with dummy data that reproduces the issue so I can validate any fixes.
Full output from lightgbm logs in spark:
[LightGBM] [Info] Trying to bind port 12400...
[LightGBM] [Info] Binding port 12400 succeeded
[LightGBM] [Info] Listening...
[LightGBM] [Info] Connected to rank 1
[LightGBM] [Info] Connected to rank 2
[LightGBM] [Info] Local rank: 0, total number of machines: 3
2021-04-15T03:15:39.704+0000: [GC (Allocation Failure) [PSYoungGen: 10960185K->213453K(11862528K)] 13872080K->3125356K(16915456K), 0.0432352 secs] [Times: user=0.31 sys=0.01, real=0.04 secs] 
[LightGBM] [Debug] Dataset::GetMultiBinFromSparseFeatures: sparse rate 0.823075
[LightGBM] [Debug] Dataset::GetMultiBinFromAllFeatures: sparse rate 0.091021
[LightGBM] [Debug] init for col-wise cost 0.034652 seconds, init for row-wise cost 0.083892 seconds
[LightGBM] [Warning] Auto-choosing row-wise multi-threading, the overhead of testing was 0.056562 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Debug] Using Dense Multi-Val Bin
[LightGBM] [Info] Total Bins 5350
[LightGBM] [Info] Number of data points in the train set: 915789, number of used features: 29
[LightGBM] [Info] Start training from score 1.020676
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 10
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 9
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 9
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 8
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 7
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 8
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 8
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 9
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 7
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 9
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 9
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 7
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 10
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 10
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 9
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 11
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 11
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 10
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 11
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 12
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 11
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 17
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 13
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 16
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 17
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 14
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 12
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 15
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 11
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 12
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 17
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 14
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 17
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 21
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 12
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 16
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 15
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 14
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 17
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 12
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 13
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 1 and max_depth = 1
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Info] Finished linking network in 11.926274 seconds

## Environment info

LightGBM version or commit hash:
From this PR: https://github.com/Azure/mmlspark/pull/1015
commit: https://github.com/microsoft/LightGBM/commit/1ce4b22b8ccb4a9d8651ca29cddfd247defe5653
from 14 days ago
Command(s) you used to install LightGBM
This was installed in mmlspark.

**Comment by imatiach-msft** [comment]
I think this might be a similar issue other users have reported:
https://github.com/Azure/mmlspark/issues/986

**Comment by imatiach-msft** [comment]
notice the last few lines, up to the very end the trees trained are valid and then we train one weird tree that predicts very high values:
[LightGBM] [Debug] Trained a tree with leaves = 31 and max_depth = 13
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 1 and max_depth = 1
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Info] Finished linking network in 11.926274 seconds

**Comment by imatiach-msft** [comment]
I saw what looked like a similar issue here:
https://github.com/microsoft/LightGBM/issues/4026
I wonder if it is related

**Comment by shiyu1994** [comment]
It is weird that the last 1-leaf tree should affect the prediction value. Because according to the logic in our code, such a tree won't affect the prediction value of both training and validation data at all.
@imatiach-msft Could you please provide the tree models produced in the example, so that we can check the leaf outputs of these trees. Thanks!

**Comment by imatiach-msft** [comment]
@shiyu1994  based on the file I see inf split gain starting at tree 35, maybe that's the tree where the problem starts?  With 10 iterations the results are much better.
[part-00000-tid-7157605944795263871-fccfc1cc-b6d0-4bc9-9622-c6ca2a793269-1097-1-c000.txt](https://github.com/microsoft/LightGBM/files/6322467/part-00000-tid-7157605944795263871-fccfc1cc-b6d0-4bc9-9622-c6ca2a793269-1097-1-c000.txt)

**Comment by imatiach-msft** [comment]
@shiyu1994 if the file does not help, where do you think might be a good place to add debug in the native code to get more info on the issue?

**Comment by imatiach-msft** [comment]
when running lightgbm to iteration=35 the results seem to still be ok

**Comment by imatiach-msft** [comment]
the predictions start to get unreasonably bad at exactly iteration=36 and then get much worse from there, it's interesting this is when the split gain starts to see "inf" values

**Comment by imatiach-msft** [comment]
when I specify iterations=2000 I can indeed see that lightgbm stops early at 64 iterations but it seems that by then the model has long ago been corrupted and has horrible leaf values that seemed to get worse and worse as the split gain started to get infs in it

**Comment by shiyu1994** [comment]
May I know which distributed learning mode is using? `data`, `feature` or `voting`? If using `data` or `voting`, can different machines contain very diverse value distributions of the same feature? For example, machine 1 contains feature A values in range [0, 10], while machine 2 contains feature A values in range [11, 20], as in the case #4026. If so, probably it is caused by the same bug as mentioned here https://github.com/microsoft/LightGBM/issues/4026#issuecomment-806583176.

Maybe I can fix the bug first, to see if the problem still exists.

**Comment by imatiach-msft** [comment]
@shiyu1994 mmlspark uses data_parallel by default.  Feature parallel is not supported there currently.
"can different machines contain very diverse value distributions of the same feature?"
I tried with and without normalizing the features in spark beforehand, and the issue happened regardless, either way.  If the features are normalized but have different value ranges would this still occur?  If you can merge the fix I can publish new jar and try it out on customer's dataset, since I have a local repro.

**Comment by imatiach-msft** [comment]
@shiyu1994 closing this issue as I have confirmed on customer dataset the issue has been fixed with PR
https://github.com/microsoft/LightGBM/pull/4185
thank you!
