### ISSUE TITLE
[help needed] train large sparse dataset on GPU / CUDA vs OpenCL

### ISSUE THREAD

**Issue by normanwang92** [microsoft/LightGBM#4179]
hello, I have a large dataset of 30M by 800 but is quite sparse, with about 85% of it being NANs. Is it better to train it on CPU or GPU and if GPU is better is there a way to force it to train on GPU? 

Also, what's the difference between the CUDA and the OpenCL implementation, both accuracy-wise and speed-wise?

Thank you!

**Comment by shiyu1994** [comment]
@normanwang92 Thanks for using LightGBM! For sparse data, we suggest to use CPU. Currently GPU version has no special optimization for sparsity.
So far, LightGBM OpenCL version only supports single GPU training, while CUDA version supports multiple GPUs. But OpenCL version uses a more sophisticated optimization to reduce conflicts within a warp when constructing histograms, so it should be more efficient when using a single GPU.

**Comment by ssh352** [comment]
> 

I have a machine with 8x Nvidia A100 gpus, should I install the OpenCL or the cuda version for max efficiency?

**Comment by shiyu1994** [comment]
The `cuda` version is recommended.
