### ISSUE TITLE
dask early stopping and eval-set

### ISSUE THREAD

**Issue by pseudotensor** [microsoft/LightGBM#4189]
I had provided code to support early stopping and eval_set in general way for lightgbm using lightgbm_dask package.   This was several months ago.  I see that still early stopping and eval_set are not supported.

Is there a timeline to add this?

@jameslamb

**Comment by pseudotensor** [comment]
I see there is some discussoin: https://github.com/microsoft/LightGBM/pull/3952

But I guess it's alot less easy in native lightgbm for some reason?

**Comment by pseudotensor** [comment]
https://github.com/microsoft/LightGBM/pull/4101

**Comment by jameslamb** [comment]
> Is there a timeline to add this?
> But I guess it's alot less easy in native lightgbm for some reason?

It looks like you found the related issues but I'll just confirm here...yes, it's actively being worked on. You can see the discussion in #3952 and #4101 for more details on why it isn't as simple as what was proposed in  https://github.com/microsoft/LightGBM/pull/3515#issuecomment-752709132.. There are a few challenges related to the fact that we can't safely assume that validation sets are partitioned exactly the same way that the training data is.

@ffineis has been doing great work and has been very patient with us, I think we'll get there in the near future!
