### ISSUE TITLE
Wiki installation guide: add glibc >= 2.14 requirement

### ISSUE THREAD

**Issue by Laurae2** [Microsoft/LightGBM#419]
LightGBM cannot be installed using libgc below 2.14.

Quote for a Slack chat:

> ICT: (...) unable to install LightGBM and xgboost (...)
> they both requires a higher version of glibc (2.14) than we have (2.12)

Even though glibc <2.14 is old, a lot of large businesses are still using last decade tools and are not expecting to update to newer tools in the near future.

![image](https://cloud.githubusercontent.com/assets/9083669/25063192/fa854976-21dd-11e7-84bc-a49e80a3ede2.png)

**Comment by guolinke** [comment]
Thanks. I will add it to wiki.
