### ISSUE TITLE
[R-package] docs for lgb.Dataset in R are incomplete

### ISSUE THREAD

**Issue by david-cortes** [microsoft/LightGBM#4193]
In the R package, the function `lgb.Dataset` has a parameter `categorical_feature`, with this description:
```
categorical features
```
https://github.com/microsoft/LightGBM/blob/7ea2bc4dbca53c03eaae2aa2b22f9b30447caea4/R-package/R/lgb.Dataset.R#L736

It does not describe what kind of input it needs to be, in contrast to `lgb.Dataset.set.categorical`.

**Comment by jameslamb** [comment]
Thanks for using `{lightgbm}` and for looking into the documentation.

In this case, the parameter `categorical_feature` can be either:

1. A character vector of feature names
2. A numeric or integer vector of column indices (1-based, so e.g. "3" would mean "the third column")

Are you interested in contributing some improvements to the R package's documentation? If you are, we would be really grateful for the help! If not, then no problem at all and I can update this documentation soon.

**Comment by david-cortes** [comment]
Thanks but I'll pass on that as I'm not really familiar with it.

BTW I notice it's missing the docs for allowed parameters.

**Comment by jameslamb** [comment]
Ok no problem. Can you please clarify what you mean by "allowed parameters"?

**Comment by david-cortes** [comment]
> Ok no problem. Can you please clarify what you mean by "allowed parameters"?

Functions `lightgbm`, `lgb.train`, `lgb.cv`, have an argument `params` which says: `List of parameters`.

**Comment by jameslamb** [comment]
I see, ok. Yes we should be linking to https://lightgbm.readthedocs.io/en/latest/Parameters.html in those places.
