### ISSUE TITLE
Multiple Quantile Regression

### ISSUE THREAD

**Issue by imatiach-msft** [microsoft/LightGBM#4201]
See issue in mmlspark:
https://github.com/Azure/mmlspark/issues/966

## Summary

Add multiple quantile regression to lightgbm, see linked issue for details from user

I don't think this feature currently exists in lightgbm, are there any plans to add it?

**Comment by shiyu1994** [comment]
That's related to a previous issue #3447, which is already in the feature request & voting hub #2302. Contributions are welcome.
