### ISSUE TITLE
Adding correlation metrics

### ISSUE THREAD

**Issue by GLevV** [microsoft/LightGBM#4209]
## Summary

Pearson R, CCC - could be used in regression.

Spearman R, Kendall Tau, Kendall Tau Weighted - could be used in classification, as well as multiclassification (for ordinal targets) and ranking tasks.

**Comment by shiyu1994** [comment]
@GLevV Thanks! Yes. These metrics are useful in some cases. Would you like to contribute?

**Comment by StrikerRUS** [comment]
Closed in favor of being in #2302. We decided to keep all feature requests in one place.

Welcome to contribute this feature! Please re-open this issue (or post a comment if you are not a topic starter) if you are actively working on implementing this feature.
