### ISSUE TITLE
Duplicate evaluations during fit

### ISSUE THREAD

**Issue by Mark531** [microsoft/LightGBM#4212]
## Description
If I train a LGBMClassifier with n estimators, the length of evals_result_ is 2 * n.
Moreover, during the fit process, all evaluations are displayed twice.

## Reproducible example
```
X_fit, X_val, y_fit, y_val = train_test_split(X_train, y_train, test_size=0.3, random_state=42)
model = LGBMClassifier(objective="binary", n_estimators=5)
model.fit(X_fit, y_fit, eval_metric="binary_logloss", eval_set=[(X_fit, y_fit), (X_val, y_val)], eval_names=["train", "valid"])
```

> [1]	train's binary_logloss: 0.648788	train's binary_logloss: 0.648788	valid's binary_logloss: 0.64884	valid's binary_logloss: 0.64884
> [2]	train's binary_logloss: 0.617951	train's binary_logloss: 0.617951	valid's binary_logloss: 0.61815	valid's binary_logloss: 0.61815
> [3]	train's binary_logloss: 0.592358	train's binary_logloss: 0.592358	valid's binary_logloss: 0.592702	valid's binary_logloss: 0.592702
> [4]	train's binary_logloss: 0.571285	train's binary_logloss: 0.571285	valid's binary_logloss: 0.57174	valid's binary_logloss: 0.57174
> [5]	train's binary_logloss: 0.553073	train's binary_logloss: 0.553073	valid's binary_logloss: 0.553632	valid's binary_logloss: 0.553632

`len(model.evals_result_["train"]["binary_logloss"])`

> 10

## Environment info

LightGBM version or commit hash:
2.2.1

Command(s) you used to install LightGBM

```
pip install lightgbm
```

## Additional Comments
This problem does not seem data-dependent.

**Comment by ffineis** [comment]
@Mark531 can you provide a reproducible example? Perhaps you may be making copies of `model`, with a different number of iterations. The model training logs you've provided end at iteration `[5]`, suggesting that 5 iterations were evaluated.

A minimally reproducible example shows that there are 5 iterations evaluated:

```
import lightgbm as lgb
import numpy as np

X_fit = np.random.normal(size=(100,5))
X_val = X_fit[0:30, :]

y_fit = np.random.choice(range(2), size=100, replace=True)
y_val = y_fit[0:30]

model = lgb.LGBMClassifier(objective="binary", n_estimators=5)
model.fit(X_fit, y_fit, eval_metric="binary_logloss", eval_set=[(X_fit, y_fit), (X_val, y_val)], eval_names=["train", "valid"])

print(f"len(model.evals_result_['train']['binary_logloss']): {len(model.evals_result_['train']['binary_logloss'])}")
```

**Comment by Mark531** [comment]
Well, if I execute your example with my current version of lightgbm (on Ubuntu), the results are consistent with the problem I raised:

> [1]     train's binary_logloss: 0.679111        train's binary_logloss: 0.679111        valid's binary_logloss: 0.682795        valid's binary_logloss: 0.682795
> [2]     train's binary_logloss: 0.663703        train's binary_logloss: 0.663703        valid's binary_logloss: 0.674396        valid's binary_logloss: 0.674396
> [3]     train's binary_logloss: 0.649136        train's binary_logloss: 0.649136        valid's binary_logloss: 0.66321 valid's binary_logloss: 0.66321
> [4]     train's binary_logloss: 0.637901        train's binary_logloss: 0.637901        valid's binary_logloss: 0.651804        valid's binary_logloss: 0.651804
> [5]     train's binary_logloss: 0.626252        train's binary_logloss: 0.626252        valid's binary_logloss: 0.643134        valid's binary_logloss: 0.643134
> len(model.evals_result_['train']['binary_logloss']): 10
> 

Now, I tried the same example with a 3.1.1 version of lightgbm (on Windows) and the results are correct:

> [1]	train's binary_logloss: 0.677679	valid's binary_logloss: 0.6994
> [2]	train's binary_logloss: 0.667645	valid's binary_logloss: 0.695665
> [3]	train's binary_logloss: 0.659459	valid's binary_logloss: 0.696212
> [4]	train's binary_logloss: 0.650087	valid's binary_logloss: 0.692992
> [5]	train's binary_logloss: 0.644979	valid's binary_logloss: 0.6858
> len(model.evals_result_['train']['binary_logloss']): 5
> 

So, it may be due to the version 2 of lightgbm. Is this bug known?

**Comment by jameslamb** [comment]
> Is this bug known?

I don't remember any specific change to fix this bug, but either way I think the effect is the same. LightGBM doesn't support a concept of "long-term support" releases, so we won't, for example, consider a patch for this behavior that then results in something like a version 2.2.1.1 release.

Is there anything that prevents you from upgrading to the newest release of LightGBM, 3.2.1?

You can see the changelog for all releases at https://github.com/microsoft/LightGBM/releases.

**Comment by Mark531** [comment]
Well, I'm not the owner of the environment, but I'll make do with it.

Anyway, it's surprising to find such a big bug in a relased version.

**Comment by jameslamb** [comment]
Ok it seems like this is resolved. @ffineis thanks for the assist!

@Mark531 thanks again for the report.
