### ISSUE TITLE
Request: add option for baseline/prior when fitting a model

### ISSUE THREAD

**Issue by david-cortes** [microsoft/LightGBM#4213]
Would be nice if lightgbm allowed passing a vector or matrix of scores to use as a starting point when fitting a model, akin to catboost's "baseline" - that is, if I fit a binary classification model and pass a score of 0.1 for that observation, it should already start with a prediction/residual slightly oriented towards the positive class.

I see it currently has an "init_model" option, but it's not exactly the same.

**Comment by jameslamb** [comment]
Can you please provide some specifics on how LightGBM's `init_score` is different from what you'd like to see?

**Comment by david-cortes** [comment]
Apologies, had interpreted the docs incorrectly, from some experimentation it is the same indeed.

**Comment by jameslamb** [comment]
No problem! If you think there is a way to make the documentation clearer, we'd welcome a pull request with a proposed improvement.
