### ISSUE TITLE
Add approx_contrib option for feature contributions

### ISSUE THREAD

**Issue by gravesee** [microsoft/LightGBM#4219]
xgboost has two methods for calculating feature contributions: TreeSHAP and Approximate. The approximate is much faster and has some nice properties w.r.t. monotonicity that aren't guaranteed when using TreeSHAP. It is also easier to port the approximate method to production systems when the lightgbm object can't be used directly.

## Motivation

TreeSHAP is the gold standard but there are practical reasons for preferring a fast, simple method of calculating feature contributions. The approach outlined below can still be used for interpretation, is easier to port to other production systems, and is quicker to calculate.

## Description

The approximate method of feature contribution first distributes the leaf weights up through the internal nodes of the tree. The parent weight is equal to the cover-weighted sum of the left and right child weights. If lightgbm already calculates internal leaf weights then this becomes even simpler to implement.

After the weights are distributed up through all nodes of the tree, then the feature contribution for a split is calculated by subtracting the parent node weight from the child node weights and aggregating across all features and trees in the ensemble.

## References

http://blog.datadive.net/interpreting-random-forests/

**Comment by StrikerRUS** [comment]
@gravesee Thanks a lot for the feature request!

Just to clarify, are you aware of that you can get feature importance with the help of the following function (and corresponding Booster methods in language wrappers)?
https://github.com/microsoft/LightGBM/blob/d517ba12f2e7862ac533908304dddbd770655d2b/include/LightGBM/c_api.h#L1233-L1246

**Comment by gravesee** [comment]
@StrikerRUS thanks for the response. It looks like the code you linked to returns the feature importance gain in the model for each feature *overall*. What I am requesting in this issue is the approximate feature contribution for all features for each input record. The output would be a matrix where the number of rows matches the number of inputs and the number of columns matches the number of features + 1 (with one extra column for the model bias).

**Comment by StrikerRUS** [comment]
@gravesee Ah, I see! Thanks for clarifying!

**Comment by StrikerRUS** [comment]
Closed in favor of being in #2302. We decided to keep all feature requests in one place.

Welcome to contribute this feature! Please re-open this issue (or post a comment if you are not a topic starter) if you are actively working on implementing this feature.
