### ISSUE TITLE
[Question] Why RF model predictions are better than predictions of ensemble of single-tree models?

### ISSUE THREAD

**Issue by slonoslon** [microsoft/LightGBM#4223]
When I am trying to train a manually created ensemble of 100 predictors (boosting='rf', num_iterations=1) and then use their average as a custom random forest - the predictions I obtain are constantly worse (have higher RMSE) than the results of training an "official" random forest (boosting='rf', num_iterations=100). 
In my manual version I do initialize each model with its own random seed, but it still looks like they are somehow "less random". 
What am I missing?

**Comment by shiyu1994** [comment]
@slonoslon Thanks for using LightGBM. Have you correctly set the subsampling parameters, including `bagging_freq`, `bagging_fraction` and `feature_fraction` in your own version?
A small reproducible example would be very helpful for us to identify the problem.
