### ISSUE TITLE
Truncation level for rank_xendcg objective

### ISSUE THREAD

**Issue by miguellacerda** [microsoft/LightGBM#4227]
Does the `lambdarank_truncation_level` parameter work with `objective = 'rank_xendcg'`? The docs say it only works with the `lambdarank` objective, but I don't see why it shouldn't also work with `rank_xendcg`.

Also, what is the default truncation level for `rank_xendcg`? Is it 30 like `lambdarank`?

**Comment by StrikerRUS** [comment]
I don't think `lambdarank_truncation_level` (`truncation_level_` internally) is used in `rank_xendcg` objective. It is used in `LambdarankNDCG` class but `RankXENDCG` class is inheriting from `RankingObjective` not from `LambdarankNDCG`.
https://github.com/microsoft/LightGBM/blob/master/src/objective/rank_objective.hpp
