### ISSUE TITLE
Add BoostFromAverage to Python model.

### ISSUE THREAD

**Issue by JoshuaC3** [microsoft/LightGBM#4234]
## Summary

Add the BoostFromAverage output to the init_score on the train_set Dataset. It seems to me that they serve the same function - that is, reducing training time by allowing the model to have some previous knowledge of the data before the first boosting round. BoostingFromAverage is a simply a subset of the `init_score` functionality.

## Motivation

This allows us to recover the mean of the target variable after training and then when saving the model. There are many instances where we may not have access to the label data (and therefore the mean) after saving a model.

This is also the equivalent to the intercept in EBMs so aids in comparisons of LightGBM and EBM. See https://github.com/microsoft/LightGBM/issues/3905#issuecomment-797136404 and [EBM intercept calculations](https://github.com/interpretml/interpret/blob/ac5e727498cbdcb6911444420343454b0f328a46/python/interpret-core/interpret/glassbox/ebm/ebm.py#L1021).

Finally, and maybe most importantly, this would allow a user better insights into how the model is working at each stage and would help with model interpretability #4065 and #3095.

## Description

Something like, writing the results from `BoostFromAverage` back to the model here
https://github.com/microsoft/LightGBM/blob/d517ba12f2e7862ac533908304dddbd770655d2b/src/boosting/gbdt.cpp#L344

**Comment by StrikerRUS** [comment]
Superseded by #4313 as a more general approach.
