### ISSUE TITLE
lambdarank example: query file group numbers do not sum to training data samples 

### ISSUE THREAD

**Issue by esvhd** [microsoft/LightGBM#4241]
Hi there,

In `examples\lambdarank`, my understanding is that the entries in `rank.train.query` should sum to the size of the training data - `rank.train` - 3005 entries. But `rank.train.query` only sums to 3004. 

What am I missing here? 

Thanks.

Code below to produce the counts.

```
import pandas as pd
from sklearn.datasets import load_svmlight_file
import scipy.sparse as ss
import path

folder = 'git/LightGBM/examples/lambdarank/'

train_data = 'rank.train'
train_query = 'rank.train.query'

x, y = load_svmlight_file(folder+train_data)
X = ss.csc_matrix.todense(x)

# X.shape, y.shape
# ((3005, 300), (3005,))

query = pd.read_csv(folder+train_query).values.squeeze()
query.sum()
# 3004
```

**Comment by shiyu1994** [comment]
@esvhd Thanks for using LightGBM. In `query = pd.read_csv(folder+train_query).values.squeeze()`, without setting `header=None` in `pd.read_csv`, the first line of `rank.train.query` will be take as the column header of the file. It happens that the first line has value `1` in `rank.train.query`, which causes the `query.sum()` to be `3005 - 1 = 3004`.

**Comment by esvhd** [comment]
That solves it, thank you very much @shiyu1994
