### ISSUE TITLE
[docs] what should LGBM_BoosterGetEvalNames be used for?

### ISSUE THREAD

**Issue by jameslamb** [microsoft/LightGBM#4264]
## Description

While working on #4256, I was confused by the use of `LGBM_BoosterGetEvalNames`. Based on the documentation, I expected that this function would return the names of validation sets.

https://github.com/microsoft/LightGBM/blob/f83180883a51729af9562ccac7b450c6da79a04a/include/LightGBM/c_api.h#L587

However, I found that in the places where this function is used in the R and Python packages, it seems to actually be returning a list of evaluation *metrics*.

https://github.com/microsoft/LightGBM/blob/f83180883a51729af9562ccac7b450c6da79a04a/python-package/lightgbm/basic.py#L3463-L3481

https://github.com/microsoft/LightGBM/blob/f83180883a51729af9562ccac7b450c6da79a04a/R-package/R/lgb.Booster.R#L684-L706

Is the documentation incorrect? Or have I just misunderstood it?

## Reproducible example

 The code below uses the same code paths in the Python and R packages linked above. I expected that the output of `LGBM_BoosterGetEvalNames` would be `["valid_1"]` (the name I used for one eval set).

**Python**

```python
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split

import lightgbm as lgb

X_train, X_test, y_train, y_test = train_test_split(
    *load_breast_cancer(return_X_y=True),
    test_size=0.1,
    random_state=2
)

train_data = lgb.Dataset(X_train, label=y_train)
valid_data = train_data.create_valid(X_test, label=y_test)

params = {
    "objective": "binary",
    "num_leaves": 31,
    "metric": ["binary_logloss", "auc"]
}
bst = lgb.Booster(params, train_data)
bst.add_valid(valid_data, "valid_1")

# check the result of a call to LGBM_BoosterGetEvalNames()
bst._Booster__get_eval_info()
print(bst._Booster__name_inner_eval)

# ['binary_logloss', 'auc']
```

**R**

```r
library(lightgbm)

data(agaricus.train, package = "lightgbm")
data(agaricus.test, package = "lightgbm")
dtrain <- lgb.Dataset(
    agaricus.train$data
    , label = agaricus.train$label
)
bst <- lgb.train(
    params = list(
        objective = "regression"
        , metric = c("l2", "l1")
    )
    , data = dtrain
    , nrounds = 2L
    , valids = list(
        "valid_1" = lgb.Dataset.create.valid(
            dtrain
            , agaricus.test$data
            , label = agaricus.test$label
        )
    )
)

eval_info <- bst$.__enclos_env__$private$get_eval_info()
print(eval_info)

# [1] "l2" "l1"
```

## Environment info

LightGBM version or commit hash: latest `master` as of May 6, 2021 (https://github.com/microsoft/LightGBM/commit/0246721303e492bb563263d7ad0aad081a22b606)

Command(s) you used to install LightGBM

```shell
# python
cd python-package
python setup.py install

# R
sh build-cran-package.sh
R CMD INSTALL lightgbm_*.tar.gz
```

**Comment by StrikerRUS** [comment]
Looks like the issue in docs. Thanks for spotting this!

Incorrectness was introduced here:
https://github.com/microsoft/LightGBM/pull/2076/files#diff-0b41a7775380c6d2b3321f189fe3fd3412c6621c4075ce00067b74f9312f38efR590
Probably with the "help" of my suggestions for that huge PR. Sorry!

**Comment by jameslamb** [comment]
Ah ok, thanks! I'll open a PR updating the docs.
