### ISSUE TITLE
ArrayArgs::Partition causes UB when called with interval of size 1

### ISSUE THREAD

**Issue by kruda** [microsoft/LightGBM#4272]
## Description

ArrayArgs::Partition causes undefined when called with interval of size 1
## Reproducible example

Run test case SearchThresholdMVS.PartitionOneElement from my repository https://github.com/kruda/LightGBM/commit/d018ed0bb509cf95e9f9cbddf7ebc67cb5ce9d42 with sanitisers.
## Environment info

LightGBM version or commit hash: current main branch 
Looks like this bug was introduced in https://github.com/microsoft/LightGBM/commit/4f77bd2860913a9a210c72a367fc88b4a9c13b3d
Command(s) you used to install LightGBM

```shell

```

## Additional Comments

Possible fix: https://github.com/kruda/LightGBM/commit/8cee27e8f23eb142355987bb8e29238e1a1e88b1

**Comment by StrikerRUS** [comment]
Fixed via #4280.
