### ISSUE TITLE
[R-package] gcc warning on CMake-based builds: 'cast between incompatible function types'

### ISSUE THREAD

**Issue by jameslamb** [microsoft/LightGBM#4273]
## Description

Building the R package with `CMake`-based installation (https://github.com/microsoft/LightGBM/blob/master/R-package/README.md#install) and `gcc` (or `MINGW` on Windows results in the following compiler warnings:

```text
/private/var/folders/xq/wktq4zdx4jd3qdpk34d28m940000gn/T/Rtmp7sAM9p/R.INSTALL71b1ac713c8/lightgbm/src/src/lightgbm_R.cpp:722:41: warning: cast between incompatible function types from 'SEXPREC* (*)(LGBM_SE, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP)' {aka 'SEXPREC* (*)(LGBM_SER*, SEXPREC*, SEXPREC*, SEXPREC*, SEXPREC*, SEXPREC*, SEXPREC*, SEXPREC*, SEXPREC*, SEXPREC*, SEXPREC*)'} to 'DL_FUNC' {aka 'void* (*)()'} [-Wcast-function-type]
  722 |   {"LGBM_BoosterPredictForMat_R"      , (DL_FUNC) &LGBM_BoosterPredictForMat_R      , 11},
      |                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/private/var/folders/xq/wktq4zdx4jd3qdpk34d28m940000gn/T/Rtmp7sAM9p/R.INSTALL71b1ac713c8/lightgbm/src/src/lightgbm_R.cpp:723:41: warning: cast between incompatible function types from 'SEXPREC* (*)(LGBM_SE, SEXP, SEXP, SEXP)' {aka 'SEXPREC* (*)(LGBM_SER*, SEXPREC*, SEXPREC*, SEXPREC*)'} to 'DL_FUNC' {aka 'void* (*)()'} [-Wcast-function-type]
  723 |   {"LGBM_BoosterSaveModel_R"          , (DL_FUNC) &LGBM_BoosterSaveModel_R          , 4},
      |                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/private/var/folders/xq/wktq4zdx4jd3qdpk34d28m940000gn/T/Rtmp7sAM9p/R.INSTALL71b1ac713c8/lightgbm/src/src/lightgbm_R.cpp:724:41: warning: cast between incompatible function types from 'SEXPREC* (*)(LGBM_SE, SEXP, SEXP)' {aka 'SEXPREC* (*)(LGBM_SER*, SEXPREC*, SEXPREC*)'} to 'DL_FUNC' {aka 'void* (*)()'} [-Wcast-function-type]
  724 |   {"LGBM_BoosterSaveModelToString_R"  , (DL_FUNC) &LGBM_BoosterSaveModelToString_R  , 3},
      |                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/private/var/folders/xq/wktq4zdx4jd3qdpk34d28m940000gn/T/Rtmp7sAM9p/R.INSTALL71b1ac713c8/lightgbm/src/src/lightgbm_R.cpp:725:41: warning: cast between incompatible function types from 'SEXPREC* (*)(LGBM_SE, SEXP, SEXP)' {aka 'SEXPREC* (*)(LGBM_SER*, SEXPREC*, SEXPREC*)'} to 'DL_FUNC' {aka 'void* (*)()'} [-Wcast-function-type]
  725 |   {"LGBM_BoosterDumpModel_R"          , (DL_FUNC) &LGBM_BoosterDumpModel_R          , 3},
```

One such warning is generated for each entry in this list of routines:

https://github.com/microsoft/LightGBM/blob/08d1ce4bbf9391f5cc945f5f015840f4a57774a6/R-package/src/lightgbm_R.cpp#L684

## Reproducible example

Follow https://github.com/microsoft/LightGBM/blob/master/R-package/README.md#install, using `gcc` on Mac or Linux, or MinGW on Windows.

This warning does not appear to show up when using `MSVC` or `clang`.

This warning does not appear when using the CRAN-based installation method (https://github.com/microsoft/LightGBM/blob/master/R-package/README.md#installing-the-cran-package).

I've observed this warning with  `gcc` 10, on both R 3.6.3  and R 4.0.5.

## Additional Comments

* based on these previous discussions:
    - https://github.com/microsoft/LightGBM/pull/4265#issuecomment-836760440
    -  https://github.com/microsoft/LightGBM/issues/3016#issue-605212323
    - https://github.com/microsoft/LightGBM/pull/3009#issuecomment-617219336
* the following searches on the unofficial CRAN mirror at github.com/cran can be used to inspect how other packages that use a C++ source file (`.cc` or `.cpp`) instead of a CC source file (`.c`) do this
    - https://github.com/search?q=R_CallMethodDef+org%3Acran+filename%3A*.cpp
    - https://github.com/search?q=R_CallMethodDef+org%3Acran+filename%3A*.cc

**Comment by jameslamb** [comment]
Looking at build logs today, I see the following flags used.

**CRAN build**

```shell
/usr/local/bin/g++-10 \
  -std=gnu++11 \
  -I"/Library/Frameworks/R.framework/Resources/include" \
  -DNDEBUG \
  -I./include \
  -DEIGEN_MPL2_ONLY \
  -DMM_PREFETCH=1 \
  -DMM_MALLOC=1 \
  -DUSE_SOCKET \
  -DLGB_R_BUILD \
  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk \
  -I/usr/local/include \
  -pthread \
  -fPIC \
  -Wall \
  -g \
  -O2 \
  -c lightgbm_R.cpp \
  -o lightgbm_R.o
```

**CMake-based**

I got these by adding a `MESSAGE(FATAL_ERROR "CMAKE_CXX_FLAGS: ${CMAKE_CXX_FLAGS}")` near the end of `CMakelists.txt`

```text
/usr/local/bin/g++-10 \
    -fopenmp \
    -std=c++11 \
    -pthread \
    -Wextra \
    -Wall
    -Wno-ignored-attributes \
    -Wno-unknown-pragmas \
    -Wno-return-type \
    -O3 \
    -fPIC \
    -funroll-loops
```

<hr>

I think the use of `-Wextra` explains why these warnings only show up in CMake-based builds of the R package.

https://github.com/microsoft/LightGBM/blob/08d1ce4bbf9391f5cc945f5f015840f4a57774a6/CMakeLists.txt#L273-L274

`-Wcast-function-type` is included with `-Wextra`, which is used on CMake-based builds but not CRAN-based builds.

reference: https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html

<hr>

I think that this warning can safely be ignored for the R package specifically. The pattern used in `{lightgbm}` is exactly the same one used in many other R packages on CRAN, and the extensive unit tests covering the package give me confidence that this isn't causing any issues.

I'll submit a pull request to suppress it.

**Comment by david-cortes** [comment]
I think the issue here is that the functions are declared as C++ when they should be declared as extern C.

**Comment by jameslamb** [comment]
> the functions are declared as C++ 

Can you please clarify what leads you to believe that they are missing `extern C`? These functions are all defined with `LIGHTGBM_C_EXPORT` like this

https://github.com/microsoft/LightGBM/blob/893702204563376dff1a20c58efcc42c8181b279/R-package/src/lightgbm_R.h#L38

which, if I'm not mistaken, will end up adding `extern "C"` at compile time

https://github.com/microsoft/LightGBM/blob/d517ba12f2e7862ac533908304dddbd770655d2b/include/LightGBM/export.h#L10-L23

What are we missing?

**Comment by david-cortes** [comment]
My bad, it's not an issue with those then. Although in any case I'd also include the R headers in an an extern C block just in case.

**Comment by david-cortes** [comment]
Actually, looking at the R headers in the latest version of R, there doesn't seem to be any need to declare them as extern C, and `R_USE_C99_IN_CXX` is now added automatically with C++11 and higher.
