### ISSUE TITLE
doubt about "number of used features"

### ISSUE THREAD

**Issue by heroxrq** [Microsoft/LightGBM#428]
[LightGBM] [Info] Number of data: 2012548, number of used features: 552754

My training data has 2,000,000 (libsvm sparse format) features, but the log info of lightgbm say used features are 552754. I want to know whether some features are not used and what process lightgbm does to reduce features?

**Comment by guolinke** [comment]
check ```bin_construct_sample_cnt``` in https://github.com/Microsoft/LightGBM/blob/master/docs/Parameters.md .
LightGBM use sampling data to construct feature bin mappers.
If features didn't show in the sampling data, they will be ignored.  
And if the number of non-zero values of one feature is smaller than ```min_data_in_leaf```, this feature will be ignored as well. 

You can set ```bin_construct_sample_cnt``` to a bigger value to solve this.
