### ISSUE TITLE
[R-package] R memory leaks

### ISSUE THREAD

**Issue by david-cortes** [microsoft/LightGBM#4282]
There are some situations in which the R version can leak memory by not destructing C++ objects that become unreachable:

* Functions that return an R external pointer are wrapped into R6 classes, with the finalizer for the external pointer being under the R6 finalizer. If an error occurs during initialization (when calling `Class$new(...)`, like it is done when creating a dataset), the finalizer will not be called, thus leaking the C++ object (e.g. a dataset or a model). This could be solved by setting the finalizer in the R external pointer object itself.
* Some of the C++ functions allocate R vectors, such as these:
https://github.com/microsoft/LightGBM/blob/893702204563376dff1a20c58efcc42c8181b279/R-package/src/lightgbm_R.cpp#L203
https://github.com/microsoft/LightGBM/blob/893702204563376dff1a20c58efcc42c8181b279/R-package/src/lightgbm_R.cpp#L507
https://github.com/microsoft/LightGBM/blob/893702204563376dff1a20c58efcc42c8181b279/R-package/src/lightgbm_R.cpp#L683
https://github.com/microsoft/LightGBM/blob/893702204563376dff1a20c58efcc42c8181b279/R-package/src/lightgbm_R.cpp#L706
If the allocation of the R vectors fail, it will trigger a long jump which would leave the C++ vectors that were allocated before undestructed and unreachable. This could be solved by using unwind protection as described in the R extensions manual.
* Same as per the other issues, calling `Rf_error` also triggers long jumps. Could either change it to something else while throwing the error on the R side, or add unwind protection for those too.

**Comment by jameslamb** [comment]
Thanks for writing this up!

> unwind protection as described in the R extensions manual

Are you referring to https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Condition-handling-and-cleanup-code? In the future, we'd very much appreciate if you included relevant links or supporting evidence when opening issues like this or leaving comments like https://github.com/microsoft/LightGBM/issues/4273#issuecomment-840172158.

**Comment by david-cortes** [comment]
Yes, that's what I was referring to.

**Comment by jameslamb** [comment]
Ok perfect, thanks very much!
