### ISSUE TITLE
[R-package] Request: work with R serialization functions

### ISSUE THREAD

**Issue by david-cortes** [microsoft/LightGBM#4296]
Currently, lightgbm for R provides custom functions for serializing models in RDS files.

These functions do not play well with R's native serialization capabilities - for example:
* If using lightgbm from some machine learning framework that wraps it (creating an object that contains a lightgbm model object inside), it will not be possible to de-serialize models, since such objects (from the wrapper framework) will only be serializable through R's own functions.
* If restarting an R session, lightgbm models will be lost.

This additionally has the issue that there is no checking for null pointers (which happens after de-serializing a model that was not serialized through lightgbm's own functions) - see https://github.com/microsoft/LightGBM/issues/4208

Would be better if it would instead play along with R's own `save`/`load` and `saveRDS`/`readRDS`. In order for this to work, it'd have to keep a copy of the model as serialized raw bytes inside the object, check if a model pointer is null before using it, and reconstruct it from the raw bytes if so. Would be nice if it also could give an informative error message when a dataset object contains a null pointer.

**Comment by jameslamb** [comment]
Thanks very much  for writing this up. I think we need some more information about this request.

Could you provide more details on what you mean by "play along with R's own `save / load` and `saveRDS / readRDS`? 
    * It would be helpful if you could, for example, provide a code snippet showing something you wish you could do in `{lightgbm}` that is impossible or difficult today.

**Comment by david-cortes** [comment]
Example:
* Launch RStudio.
* If it doesn't have the default settings, go to `Tools` -> `Global Options...` -> `Workspace` -> `Save workspace to .RData on exit:` -> set to `Ask`.
* Run the following code:
```r
library(lightgbm)
data(iris)
y = iris$Sepal.Length
X = as.matrix(iris[, -1])
m = lightgbm(data=X, label=y, params=list(objective="regression"), verbose=-1)
```
* Click `Session` -> `Restart R`.
* Run the following code (will crash, but even if it didn't, the model would not be usable):
```r
predict(m, as.matrix(X))
```

**Comment by jameslamb** [comment]
Ah ok perfect, thank you! Yes I definitely think we'd like to support this. Thank you very much for writing it up.

Following our policy for feature requests, I'm going to close this now that I've added it to the list of feature requests at #2302. Contributions toward this feature are welcomed! Anyone reading this, please leave a comment if you'd like to help with this feature and the issue will be re-opened.
