### ISSUE TITLE
Replace calls of `POINTER()` by `byref()` in Python interface to pass data arrays

### ISSUE THREAD

**Issue by StrikerRUS** [microsoft/LightGBM#4298]
It was proposed by @jameslamb in https://github.com/microsoft/LightGBM/pull/4297#discussion_r633853474 that `byref` calls will be faster according to `ctypes` official docs.

**Comment by jameslamb** [comment]
I asked @tara-jawahar about this, as I know she has some past experience with numpy's ctypes library. Some quotes from our conversation:

>Based on what I know about ctypes and how Python works at the lower level, byref() sounds like a good option! In my projects, I've used NumPy's ctypes library which works a little differently since NumPy objects are created and stored at a lower level than Python objects, so I just passed in pointers to the NumPy arrays without explicitly calling a pointer() function.

> If you're using NumPy or pandas objects, it might make sense to use NumPy's ctypes library

> ...it makes sense that byref() is faster because it looks like the Python version of ctypes uses Python objects that are stored as references to values in memory, whereas C objects such as NumPy arrays are stored as references to pointers.

So at some point I think it is worth investigating this further and doing some benchmarking. But I think that's efficiency work that can be done any time in a non-breaking way, so I personally am going to resist the urge to try it right now, in favor of some of the other items mentioned in #4310

**Comment by StrikerRUS** [comment]
Closed in favor of being in #2302. We decided to keep all feature requests in one place.

Welcome to contribute this feature! Please re-open this issue (or post a comment if you are not a topic starter) if you are actively working on implementing this feature.
