### ISSUE TITLE
[python-package] Graphviz ImportError confusion

### ISSUE THREAD

**Issue by AngelikaAntsmae** [microsoft/LightGBM#4299]
When trying to plot the tree, the ImportError regarding Graphviz 'You must install graphviz to plot tree.' can be a little confusing since one also must restart their session in addition to installing it. This has been brought up before but the error message wasn't changed - @jameslamb was it intentionally left out or may I create a PR to add that clarification?

---

'I think we could add a better message like "if you've recently installed graphviz, be sure to restart your session". We'd welcome a PR to add that if you'd like to contribute it! Otherwise I will probably add it in a few days.'
_Originally posted by @jameslamb in https://github.com/microsoft/LightGBM/issues/2428#issuecomment-533693087_

**Comment by jameslamb** [comment]
Oh wow, thanks very much @AngelikaAntsmae ! I'm embarrassed that I forgot to come back to that.

That's an oversight. We would welcome a PR to add that clarification! Please `@` me if you have any questions about the contribution process.
