### ISSUE TITLE
Ouput margin like xgboost

### ISSUE THREAD

**Issue by quancore** [microsoft/LightGBM#4300]
Maybe it seems a question but I need to output margins. XGBoost has this feature to output margin but how can I do that with LightGBM?

**Comment by StrikerRUS** [comment]
Please use the following parameter:
https://lightgbm.readthedocs.io/en/latest/Parameters.html#predict_raw_score

**Comment by quancore** [comment]
@StrikerRUS Thank you for the answer. What is the difference between _raw_score_ parameter in `predict` and `predict_proba` methods?

**Comment by StrikerRUS** [comment]
There is no difference between them.
