### ISSUE TITLE
Custom objective cv index

### ISSUE THREAD

**Issue by quancore** [microsoft/LightGBM#4309]
So I have a problem with custom objective function and cross validation. I am passing an external parameter used in custom objective func called `errors`
```python
def metric_func_generator(cls, errors: np.ndarray):
    def _metric_softmax(predt: np.ndarray, dtrain: lightgbm.Dataset) -> (str, float, bool):
        n_classes = errors.shape[1]
        predt = predt.reshape((n_classes, -1)).T
        n_rows = predt.shape[0]

        # calculate softmax of prediction (weights)
        predt = np.exp(predt)
        sp = predt.sum(axis=1)
        sp = np.repeat(sp, n_classes).reshape(n_rows, n_classes)
        predt = predt / sp

        # calculate weighted error
        rowsumerrors = predt * errors

        return "Weighted-OWA", rowsumerrors.sum(), False
    return _metric_softmax
```
But the proble is that when I use lightgbm cv function, a portion of `predt` is passed as expected but I could not get the train and test indices to filter external `errors` to calculate objective function. How could I achieve it?

**Comment by shiyu1994** [comment]
@quancore Thanks for using LightGBM. The `used_indices` in `dtrain` should give the actual data indices of the `Dataset` passed to the customized objective function. So we can use the `dtrain.used_indices` to index the `errors`.
