### ISSUE TITLE
python api can't continue train with binary file data

### ISSUE THREAD

**Issue by papillonyi** [microsoft/LightGBM#4311]
## Description

when i tried to continue train with binary file data, it raise a error
![image](https://user-images.githubusercontent.com/17263630/119078557-04176680-ba29-11eb-9507-cc707d33571d.png)
I train with a binary file with 10 iterations first and it success;
then, i try to train with `init_model=last_train_result,` and it raise such error;

And i try do the same thing with lightgbm cli, it works

## Reproducible example

here is my code
![image](https://user-images.githubusercontent.com/17263630/119078389-af73eb80-ba28-11eb-83a8-f942abdd0c58.png)

## Environment info

th version of lightGBM i used is 3.1.1 in linux

Command(s) you used to install LightGBM

```shell

```

**Comment by jameslamb** [comment]
@papillonyi thanks very much for using LightGBM. sorry for the very long delay in responding to this!

In the future, please do not post logs, error messages, or code as screenshots. Post such things as text instead, so others facing the same challenges can find this discussion from search engines.

Providing a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that can be easily copied and run by others would also make it much more likely that issues will be addressed quickly.

-------------------------------------------

I tried to create a minimal, reproducible example based on the provided code snippet, using the Python package as of the latest commit on `master` (https://github.com/microsoft/LightGBM/commit/af5b40e1f653e25a5f3470e09de4d1c68dc59663).

The code below produces the reported error.

```python
import lightgbm as lgb
from sklearn.datasets import make_regression

X, y = make_regression(n_samples=1_000, n_informative=5)

data_file_name = "output.bin"
model_file_name = "model-temp.text"
params = {
    "boosting_type": "gbdt",
    "verbose": 1,
    "deterministic": True,
    "objective": "regression"
}

# create dataset and save it to binary file
lgb.Dataset(data=X, label=y).save_binary(data_file_name)
```

> [LightGBM] [Info] Saving data to binary file output.bin

```python
# train for 10 iterations on data from file
dtrain = lgb.Dataset(data_file_name)
booster = lgb.train(
    params=params,
    train_set=dtrain,
    num_boost_round=10
)
booster.save_model(model_file_name)
```

> [LightGBM] [Info] Load from binary file output.bin
[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.002147 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 25500
[LightGBM] [Info] Number of data points in the train set: 1000, number of used features: 100
[LightGBM] [Info] Start training from score 0.505056

```python
# clear booster and dataset
del booster
del dtrain

# try to containue training for 10 more rounds on
# model and Dataset from file
dtrain = lgb.Dataset(data_file_name)

booster = lgb.train(
    params=params,
    train_set=dtrain,
    init_model=model_file_name,
    num_boost_round=10
)
```

> [LightGBM] [Info] Load from binary file output.bin
> [LightGBM] [Fatal] Unknown format of training data. Only CSV, TSV, and LibSVM (zero-based) formatted text files are supported.

**Comment by jameslamb** [comment]
Looking at the stacktrace, this is coming from a call to `LGBM_BoosterPredictForFile()` inside `Booster.predict(), here

https://github.com/microsoft/LightGBM/blob/af5b40e1f653e25a5f3470e09de4d1c68dc59663/python-package/lightgbm/basic.py#L784

`LGBM_BoosterPredictForFile()` cannot be used with LightGBM Dataset binary files at the moment.

Related conversations:

* https://github.com/microsoft/LightGBM/issues/4034#issuecomment-843003438
* #4545

-------------------

> I try to do the same thing with lightgbm cli, it works

I was able to replicate that behavior as well, and confirm that **the CLI does support training continuation using a Dataset binary file**

First, I installed the Python package and built the CLI.

```shell
cd python-package
python setup.py install
cd ..

mkdir build
cd build
cmake ..
make -j2
cd ..
```

Then I ran the following Python code to generate the Dataset binary file and initial model.

```python
import lightgbm as lgb
from sklearn.datasets import make_regression

X, y = make_regression(n_samples=1_000, n_informative=5)

data_file_name = "output.bin"
model_file_name = "model-temp.text"
params = {
    "boosting_type": "gbdt",
    "verbose": 1,
    "deterministic": True,
    "objective": "regression"
}

# create dataset and save it to binary file
lgb.Dataset(data=X, label=y).save_binary(data_file_name)

# train for 10 iterations on data from file
dtrain = lgb.Dataset(data_file_name)
booster = lgb.train(
    params=params,
    train_set=dtrain,
    num_boost_round=10
)
booster.save_model(model_file_name)
```

Checked that the model produced had exactly 10 trees.

```shell
cat model-temp.text | grep 'Tree=' | tail -1
```

> Tree=9

Next, I created a file `train.conf` with configuration for the CLI.

```text
task = train
objective = regression
data = output.bin
num_trees = 7
output_model = model-from-cli.txt
input_model = model-temp.text
```

Next, ran training with the CLI and checked that a new model file was produced, with 17 total trees (10 from initial training, 7 from training continuation).

```shell
./lightgbm config=train.conf
cat model-from-cli.txt | grep 'Tree=' | tail -1
```

> Tree=16

**Comment by jameslamb** [comment]
I think at this point we should convert this issue into a feature request like `"[python] support training continuation using a text model file and binary Dataset  file"` (and probably `[R-package]`), what do you think @shiyu1994 @StrikerRUS ?

And that solutions for supporting that might be one of the following:

* support predicting on a constructed Dataset (#1939, #4546)
* figure out the code path used to support this in the CLI, and invoke the same code path from the Python package

**Comment by jameslamb** [comment]
Going through old issues today, I realize that this and #6144 describe exactly the same problem.

Since #6144 is more recent, I'm cross-linking these two and closing this one.
