### ISSUE TITLE
Support ignoring some features during training on constructed dataset

### ISSUE THREAD

**Issue by wangmn93** [microsoft/LightGBM#4317]
I want to get a subset of features from a contructed dataset because reconstructing the dataset is time-consuming. Is there any way to do this or any suggestion on how to modify the source code? 

Another way is ignoring some features on constructed dataset, but this feature does not work on constructed dataset.

**Comment by shiyu1994** [comment]
@wangmn93 Thanks for using LightGBM. Currently LightGBM don't support extracting a subset of features from a constructed data. But I think there's a quick hack to do this.

In addition to `ignore_column`, which is used when constructing dataset, we can add a new parameter `ignore_column_training`, which is dedicated to ignore some features during training. Then we can parse `ignore_column_training` in the same way as `ignore_column`, and store it in the `config_` object. Then in `src/treelearner/serial_tree_learner.cpp`, we can set the `is_feature_used` according to `ignore_column_training` in the `SerialTreeLearner::FindBestSplits` method.

In this way, `ignore_column_training` is not involved in the dataset constructing process. Instead, it only affects the training process, and can be safely changed through setting `params` in the `lgb.train` method.

If you have any further problem about the implementation, or need any other help, please feel free to post here.

**Comment by shiyu1994** [comment]
BTW, when setting `is_feature_used`, we should notice that `is_feature_used` uses the so called inner feature index of LightGBM, which is different from the real feature index in the input data. So we need to remap the real feature index specified by `ignore_column_training` to inner feature index through `train_data_->InnerFeatureIndex` method.

**Comment by StrikerRUS** [comment]
Closed in favor of being in #2302. We decided to keep all feature requests in one place.

Welcome to contribute this feature! Please re-open this issue (or post a comment if you are not a topic starter) if you are actively working on implementing this feature.
