### ISSUE TITLE
[installation] error in git clone (Linux)

### ISSUE THREAD

**Issue by zigongyu** [microsoft/LightGBM#4318]
## Description
I have followed the [installation guide](https://lightgbm.readthedocs.io/en/latest/Installation-Guide.html#linux) to install LGBM but I have failed on the first step..

## Reproducible example
`(base) [zigong@node5 code]$ git clone --recursive https://github.com/microsoft/LightGBM
Cloning into 'LightGBM'...
remote: Enumerating objects: 22143, done.
remote: Counting objects: 100% (689/689), done.
remote: Compressing objects: 100% (428/428), done.
remote: Total 22143 (delta 410), reused 434 (delta 249), pack-reused 21454
Receiving objects: 100% (22143/22143), 17.55 MiB | 276.00 KiB/s, done.
Resolving deltas: 100% (16120/16120), done.
**error: Unable to open /data/nethome/zigong/code/LightGBM/.git/HEAD.lock for writing**
Checking out files: 100% (470/470), done.
Submodule 'include/boost/compute' (https://github.com/boostorg/compute) registered for path 'external_libs/compute'
Submodule 'eigen' (https://gitlab.com/libeigen/eigen.git) registered for path 'external_libs/eigen'
Submodule 'external_libs/fast_double_parser' (https://github.com/lemire/fast_double_parser.git) registered for path 'external_libs/fast_double_parser'
Submodule 'external_libs/fmt' (https://github.com/fmtlib/fmt.git) registered for path 'external_libs/fmt'
Cloning into 'external_libs/compute'...
error: could not lock config file /data/nethome/zigong/code/LightGBM/.git/modules/include/boost/compute/config: File exists
error: could not lock config file /data/nethome/zigong/code/LightGBM/.git/modules/include/boost/compute/config: File exists
error: could not lock config file /data/nethome/zigong/code/LightGBM/.git/modules/include/boost/compute/config: File exists
error: could not lock config file /data/nethome/zigong/code/LightGBM/.git/modules/include/boost/compute/config: File exists
fatal: 'origin' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Clone of 'https://github.com/boostorg/compute' into submodule path 'external_libs/compute' failed
`

## Environment info
Linux

LightGBM version or commit hash:
latest version

**Comment by jameslamb** [comment]
Thanks for using LightGBM! Could you please `rm -rf ./LightGBM` and try again?

**Comment by zigongyu** [comment]
thank you for your reply,  I have downloaded all external_libs manually and the  problem is solved.
