### ISSUE TITLE
[R-package] Accept data frames as inputs

### ISSUE THREAD

**Issue by jameslamb** [microsoft/LightGBM#4323]
## Summary

It should be possible to use R data frames directly as inputs in `{lightgbm}`, without converting them to matrices.

## Motivation

The `data.frame` is a very common data structure in R, and many statistics and machine learning projects accept data frames as inputs, including but not limited to `{caret}`, `{randomForest}`, and the packages listed in https://github.com/microsoft/LightGBM/issues/4295#issuecomment-841753885.

Allowing the use of `data.frame` objects would reduce friction for R users working with LightGBM.

## Description

I think this work can be broken down into the following components

* [ ] accept `data.frame` inputs for `data` argument to `lgb.Dataset()`
* [ ] accept `data.frame` inputs for `data` argument to `lightgbm()`
* [ ] accept `data.frame` inputs for `data` argument to `lgb.cv()`
* [ ] automatically encode categorical-looking column types (factor, character) in a LightGBM-friendly way
* [ ] accept `data.frame` inputs for `predict.lgb.Booster()` / `Booster$predict()` / `Predictor$predict()`
    - once "automatically encode categorical-looking column types" is implemented, this should also including converting categorical-looking columns with the same rules
* [ ] allow passing a column name for `init_score` in `lgb.Dataset()` if `data` is a `data.frame`
* [ ] allow passing a column name for `label` in `lgb.Dataset()` if `data` is a `data.frame`
* [ ] allow passing a column name for `weight` in `lgb.Dataset()` if `data` is a `data.frame`

## References

See #4207 for a prior proposal and https://github.com/microsoft/LightGBM/pull/4207#pullrequestreview-659266142 for reference on this issue.

This feature precedes #4295.

**Comment by jameslamb** [comment]
I've added this feature request to #2302, per this project's standard approach for managing its backlog.

If you are interested in contributing to this feature or have additional information to add, please leave a comment and the issue can be re-opened.

**Comment by jameslamb** [comment]
Want to add that when this feature is picked up, the R package should support categorical features for data frames using the same interface as the Python package:

* setting `categorical_feature = "auto"` in `Dataset` (the default) means "automatically detect categorical features"
* if `categorical_feature` in `Dataset` is a vector of feature indices or names, use that list of features for `categorical_feature` instead

https://github.com/microsoft/LightGBM/blob/8a90ea3f267a81a529e3f069cc13e0f6320e7989/python-package/lightgbm/basic.py#L1127

https://github.com/microsoft/LightGBM/blob/8a90ea3f267a81a529e3f069cc13e0f6320e7989/python-package/lightgbm/basic.py#L534-L540

https://github.com/microsoft/LightGBM/blob/8a90ea3f267a81a529e3f069cc13e0f6320e7989/python-package/lightgbm/basic.py#L555-L556

**Comment by mayer79** [comment]
The tricky thing here is that we would need to store factor levels in the Booster object in order to allow for save predictions. This could be a named list like `xlevs = list(gender = c("m", "f"), age = c("young", "old"))`.

**Comment by jameslamb** [comment]
Sorry, this was locked accidentally. Just unlocked it. We'd still love help with this feature!
