### ISSUE TITLE
Clarify how to specify monotonic constraints in docu

### ISSUE THREAD

**Issue by mayer79** [microsoft/LightGBM#4345]
## Description

In https://lightgbm.readthedocs.io/en/latest/Parameters.html, it is unclear how to pass the `monotone_constraints` parameter.

> monotone_constraints 🔗︎, default = None, type = multi-int, aliases: mc, monotone_constraint
> 
> - used for constraints of monotonic features
> - 1 means increasing, -1 means decreasing, 0 means non-constraint
> - you need to specify all features in order. For example, mc=-1,0,1 means decreasing for 1st feature, non-constraint for 2nd feature and increasing for the 3rd feature

In R and Python, we can pass neither a "multi-int" like `mc=-1,0,1` nor a list, but rather a string like "-1,0,1". 

## Suggestion

Add to the docu a sentence like: "In R and Python, pass a string of the form '-1,0,1'." (If this is correct.)

**Comment by jameslamb** [comment]
Thanks very much for the write-up and request! I'll add this right now.

**Comment by jameslamb** [comment]
I've opened a draft PR, #4346, to update the documentation.

For the Python package, you can pass a string or a list like `[-1, 0, 1]`. For the R package, you can pass a string or a vector like `c(-1, 0, 1)`.

**Comment by mayer79** [comment]
oh wow! I wasn't even aware that you *can* pass a list/vector!
