### ISSUE TITLE
DASK api has some problem (AttributeError: 'Future' object has no attribute 'get_params')

### ISSUE THREAD

**Issue by zzhaobh** [microsoft/LightGBM#4347]
## Description
 Traceback (most recent call last):
  File "StartProject.py", line 78, in <module>
    ProjectStart()
  File "StartProject.py", line 64, in ProjectStart
    ModelTrainingGroupByAll(store_id_list,machines,o_connect,cur_dt)
  File "Project_Modeling.py", line 91, in ModelTrainingGroupByAll
    'metric': 'mse', 'boosting_type': 'gbdt', 'objective': 'poisson', 'num_threads': 14})
  File "Model.py", line 183, in run_model
    save_model=False
  File "/Model.py", line 45, in train_model
    gbm.fit(X=x, y=y, categorical_feature=category_features)
  File "/usr/local/share/anaconda3/lib/python3.6/site-packages/lightgbm/dask.py", line 890, in fit
    **kwargs
  File "/usr/local/share/anaconda3/lib/python3.6/site-packages/lightgbm/dask.py", line 629, in _lgb_dask_fit
    self.set_params(**model.get_params())
AttributeError: 'Future' object has no attribute 'get_params'

## Environment info
dask cluster,600G memory,1host 9clients

when I just input a little part of data to train, everything is ok. when input about 100G data entirely, error is comming.

**Comment by jameslamb** [comment]
Thanks for using LightGBM. Are you able to provide a reproducible example for this behavior?

And can you please tell us how you installed `lightgbm`, and what version / commit hash you are using?

**Comment by zzhaobh** [comment]
> Thanks for using LightGBM. Are you able to provide a reproducible example for this behavior?
> 
> And can you please tell us how you installed `lightgbm`, and what version / commit hash you are using?

I just install lightgbm last version3.2.1.
I want to use lightgbm with dask in our company, but I crazy about this problem.

**Comment by jameslamb** [comment]
> I just install lightgbm last version3.2.1.

Which of these did you use?

* `pip install lightgbm`
* `conda install -c conda-forge lightgbm`
* something else (if so, please share the commands)

> I want to use lightgbm with dask in our company

We are here to help! But an error message by itself is not enough information for us to help you. Can you please try to provide a reproducible example? (some code we can run that replicates the issue)

Since I see you're using `conda`, can you also please provide the output of the commands `conda info`  and `conda env  export`?

**Comment by jameslamb** [comment]
@zzhaobh why did you close this? If you found a solution to the problem you were facing, can you please share that solution here? It will be helpful to others who find this issue from search engines.
