### ISSUE TITLE
Use Time series split for while doing lgm.cv

### ISSUE THREAD

**Issue by rachitagrwl** [microsoft/LightGBM#4363]
I tried this with this issue - https://github.com/microsoft/LightGBM/issues/2984, still I can't run my model successfully here as it is throwing a value error. Anyone can share some insights on how to make it work.?

![image](https://user-images.githubusercontent.com/14933484/121332836-24439280-c910-11eb-853a-83ee64f4d6a9.png)

**Comment by StrikerRUS** [comment]
Hey @rachitagrwl !
You are passing wrong argument (`nfold`). You should pass `folds` one.

**Comment by rachitagrwl** [comment]
Hi @StrikerRUS Thanks for coming back but error is still intact.
![image](https://user-images.githubusercontent.com/14933484/121362320-ece3de80-c92d-11eb-9fb3-7a4dedaf32fd.png)

**Comment by StrikerRUS** [comment]
Sorry, probably it was unclear as you have `folds` variable in you code. But I meant you should pass either `tss` or `folds` via `folds` parameter of `cv()` function.

```
lgb.cv(params, train_data, folds=tss, verbose_eval=200, metrics=['mae'])
```
