### ISSUE TITLE
Apple M1 chip compilation support

### ISSUE THREAD

**Issue by fayeshine** [microsoft/LightGBM#4369]
We can only compile LGB by x86 instruction set now, however apple m1 has much higher performance with ARM instruction set. If we use x86 version, the mac with M1 will run in a  intel compatible mode (need compile translation) and the performance is much  lower. So I suggest we support mac M1's ARM instruction set.

**Comment by StrikerRUS** [comment]
Hey @fayeshine !

Do you have logs of failed compilation on Apple M1?
We've recently started to provide Python wheels for ARM64 (`aarch64`) platform and had no problems with compilation.

Also, Homebrew provides LightGBM bottles for `arm64_big_sur`.
https://github.com/Homebrew/homebrew-core/blob/2e25c708a3f396feb76dd5d9ce74e1641378aa85/Formula/lightgbm.rb#L10
I guess they compile with native ARM support.

**Comment by fayeshine** [comment]
@StrikerRUS Hi,

I found that the python wheels for arm64 is for linux, do we have arm64 wheel for mac?

**Comment by StrikerRUS** [comment]
> do we have arm64 wheel for mac?

Unfortunately, we don't.

**Comment by fayeshine** [comment]
@StrikerRUS homebew's arm64 version is a command line program, not a python package, so could we provide a arm64 wheel for mac? Or could you tell me how to compile with arm64 instruction set on mac, it seems that cmake automatically compile into an intel version.

**Comment by StrikerRUS** [comment]
My example with Homebrew was about possibility of compilation on ARM platform. Unfortunately, we can't provide wheels right now due to infrastructure limitations. We are looking forward for mac M1 availability on free CI services (e.g. https://github.com/actions/virtual-environments/issues/2187#issuecomment-737339211).

>  Or could you tell me how to compile with arm64 instruction set on mac, it seems that cmake automatically compile into an intel version.

What makes you think so? Please share the logs here. Also, I believe it worth using the latest CMake.
Try passing `-DCMAKE_OSX_ARCHITECTURES=arm64`.
https://gitlab.kitware.com/cmake/cmake/-/issues/20989

**Comment by StrikerRUS** [comment]
According to this article, you can simply download

**Comment by fayeshine** [comment]
@StrikerRUS thank you! this link solved my problem. I tested that arm64 version is about 12% faster than x86 version, my train set is about 1000000*1000, num_iteration=10.

**Comment by StrikerRUS** [comment]
Very glad you've solved the problem!

> this link solved my problem.

Are you referring the article about XGBoost and LightGBM installation?

**Comment by fayeshine** [comment]
@StrikerRUS, Yes, I reffered to the article about xgboost and lightgbm installation, this mini-conda package is all compiled in arm64, as well as the lgb package, I know this because it runs in APPLE mode in activity monitor. 

As for your question: 
'Or could you tell me how to compile with arm64 instruction set on mac, it seems that cmake automatically compile into an intel version.
What makes you think so? Please share the logs here. Also, I believe it worth using the latest CMake.'

Because I can see it runs in INTEL mode in activity monitor of mac, there's no bug during the compilation, so I don't have useful logs. Maybe I need to pass '-DCMAKE_OSX_ARCHITECTURES=arm64' to force cmake compile in arm64 version, but the mini-conda's package works just fine.

**Comment by StrikerRUS** [comment]
Thanks a lot the detailed answer!
