### ISSUE TITLE
Use C++ API LGBM_BoosterPredictMat  predict multiply data get erroe

### ISSUE THREAD

**Issue by SkylerHuang** [microsoft/LightGBM#4370]
## Description
I want to inference multiply data at the same time, but i found that when nrow > 3 , it will occur errors, how can i fix it?

**Comment by jameslamb** [comment]
Thanks for using LightGBM!

This is not enough information for us to help you. Can you please provide the following things that were asked for in the issue template?

* what version / commit hash of LightGBM are you using?
* what commands did you run to install LightGBM?
* can you please share any logs, especially the error messages you're seeing?
* can you please share a reproducible example, some code we can run to replicate the problem?
