### ISSUE TITLE
Inconsistent model scores in different environments

### ISSUE THREAD

**Issue by jonastim** [microsoft/LightGBM#4372]
## Description
We are observing deviations in the model scores of our LGBM 2.2.3 model depending on the execution environment.

The model is trained, serialized using pickle and uploaded to S3 in the training environment and then loaded and scored in a different serving environment.

The model has 12 numerical features and the scores on our 10 sample reference data-set vary by up to 15%.

```
Serving env	Training env	Absolute diff	Relative diff
0.1902309019	0.16711855	0.023112352	13.83%
0.04489842625	0.04489843	-0.000000004	0.00%
0.1319186224	0.11462316	0.017295462	15.09%
0.8061076	0.80513056	0.000977040	0.12%
0.02757219904	0.0275722	-0.000000001	0.00%
0.06424271142	0.06424271	0.000000001	0.00%
0.9132584798	0.91325848	0.000000000	0.00%
0.1631256643	0.18658064	-0.023454976	-12.57%
0.7605371311	0.76021494	0.000322191	0.04%
0.282613484	0.28261348	0.000000004	0.00%
```

## Reproducible example
Our first suspicion was a library mismatch between the environments but we couldn't reproduce the error in the training environment when installing the dependencies of the serving environment (`pip install --upgrade --force-reinstall -r requirements3.txt`) and deserializing the model in the same way. So, the model outputs the expected scores in the training environment with the same Python package versions as in the serving environment (also confirmed with pip list).
Both environments are pretty similar docker images (`Ubuntu 18.04.5 LTS (Bionic Beaver)`) running on Kubernetes. 

## Environment info

Command(s) you used to install LightGBM: part of requirements file, pinned to version 2.2.3, which gets pip installed

### Training environment
```
lightgbm                          2.2.3
scikit-learn                      0.19.2
'3.6.9 (default, Jan 26 2021, 15:33:00) \n[GCC 8.4.0]'
```
### Training environment with overwritten libraries
Deserialized and loaded model in this environment and received identical scores as in the original training environment.
```
lightgbm                          2.2.3
scikit-learn                      0.18.1
'3.6.9 (default, Jan 26 2021, 15:33:00) \n[GCC 8.4.0]'
```
### Serving environment
```
lightgbm                          2.2.3
scikit-learn                      0.18.1
'3.6.9 (default, Jan 26 2021, 15:33:00) \n[GCC 8.4.0]'
```

## Additional Comments
Do LGBM models reliably serialize with pickle or do we need to use another mechanism?
This is how we serialize the model:
```
class PickleSerializer(StaticSerializer):

    @staticmethod
    def save(model: Any, file: str) -> None:
        with open(file, 'wb') as f:
            pickle.dump(model, f, pickle.HIGHEST_PROTOCOL)

    @staticmethod
    def load(file: str) -> Any:
        with open(file, 'rb') as f:
            model = pickle.load(f)
        return model
```

There's a similar issue (with the same LGBM version) here: https://github.com/microsoft/LightGBM/issues/2449
We'd appreciate any advice on how to troubleshoot this.

**Comment by StrikerRUS** [comment]
@jonastim Sorry about the issue you are having!
`2.2.3` is very old release, a lot of improvements and bug fixes have been merged since that time. Could you please migrate to the most recent release (`3.2.1`)?

> Do LGBM models reliably serialize with pickle ... ?

Given the same environment (especially the same Python version), I believe pickle is a reliable protocol.

Also, I can think about the following sources of inconsistency:
- different versions of `pandas` can encode/decode categorical features (if any) differently
- `LabelEncoder` in different version of `scikit-learn` can behave differently

> ... or do we need to use another mechanism?

To narrow the problem, please try native `save`/`load` mechanism for `Booster` object.
https://lightgbm.readthedocs.io/en/latest/pythonapi/lightgbm.Booster.html#lightgbm.Booster.save_model

**Comment by jonastim** [comment]
Thanks for the quick response, @StrikerRUS!
The problem with upgrading the LGBM version is that we still have to serve a couple of older models. 
Is `3.2.1` backwards compatible to pickled `2.2.3` models (and potentially older ones)?
For the same reason, it's tricky to change the serialization scheme.

We use pandas `1.1.5` in both environments and one of the models that has problems only uses numerical features.
The problem happens with three of our LGBM models while a bunch of other ones work fine. 

I'll keep digging but if you have any other advice what to look out for, it would be highly appreciated.

**Comment by StrikerRUS** [comment]
> Is `3.2.1` backwards compatible to pickled `2.2.3` models (and potentially older ones)?

I don't think so. Unfortunately pickle is not so smart to handle internal changes of the object from version to version.

Here is what scikit-learn says about pickle:

> While models saved using one version of scikit-learn might load in other versions, this is entirely unsupported and inadvisable. It should also be kept in mind that operations performed on such data could give different and unexpected results.
    https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations

I guess the first step should be saving an underlying model into file (with [`save_model()`](https://lightgbm.readthedocs.io/en/latest/pythonapi/lightgbm.Booster.html#lightgbm.Booster.save_model)) in both environments and check them for identity.
