### ISSUE TITLE
[R-package] Dataset construction fails if `data` does not have feature names and categorical_features is specified

### ISSUE THREAD

**Issue by jameslamb** [microsoft/LightGBM#4374]
## Description

If you specify `categorical_features` and the training data does not have feature names, Dataset construction fails.

## Reproducible example

```r
library(lightgbm)
X <- matrix(
    data = c(
        rnorm(100L)
        , rnorm(100L)
        , as.integer(runif(100L, min = 0.0, max = 1.0) / 0.02)
    )
    , ncol = 3L
)
y <- rnorm(100L)

dtrain <- lgb.Dataset(
    data = X
    , label = y
    , categorical_feature = 3L
)
dtrain$construct()

# note that X does not have column names
names(X)
```

Results in the following error message:

> Error in dtrain$construct() : 
  lgb.self.get.handle: supplied a too large value in categorical_feature: 3 but only 0 features

## Environment info

LightGBM version or commit hash: latest `master` (https://github.com/microsoft/LightGBM/commit/53ffba7c5c4a4d64853ad6c5409735b986283d2d)

Command(s) you used to install LightGBM

```shell
sh build-cran-package.sh
R CMD INSTALL lightgbm_*.tar.gz
```

## Additional Comments

For anyone reading this who is not familiar with LightGBM's internals...this bug will also affect `lightgbm()`, `lgb.cv()` and `lgb.train()`.

This bug is caused by the fact that the R packages uses `length(colnames)` to compute "number of features". 

https://github.com/microsoft/LightGBM/blob/53ffba7c5c4a4d64853ad6c5409735b986283d2d/R-package/R/lgb.Dataset.R#L148

This is not reliable, since creating a `Dataset` without feature names is supported.

**Comment by LimpEmu** [comment]
This problem also happens when the data does have feature names. When I look at length(colnames) for my data, it returns 10, yet I get this message for the last column in the categorical feature list. This package is really difficult to use.
