### ISSUE TITLE
Use or return all workers eval_set evaluation data

### ISSUE THREAD

**Issue by ffineis** [microsoft/LightGBM#4392]
Related to #4393

## Motivation

DaskLGBM estimators, as per #4101, would only return eval_set-related data artifacts (like `evals_result_`, `best_score_`, ...) from the "rank 0" worker, but all workers have some amount of evaluation metrics from their local `eval_set` data. Providing the user with either access or a complete summary of the full evaluation of `eval_set` would be preferable to just randomly choosing a worker's model and calling its `evals_result_` *the* `evals_result_`.

## Description

The `_train` routine in `dask.py` selects a random worker's model to be returned as the final fitted estimator for `_DaskLGBMModel._lgb_dask_fit` (see line 776 in dask.py).

When the user has provided `eval_set` data (see #4101), all workers will have the results of evaluating each `eval_set` during training stored in `best_score_` and `evals_result_`. But each worker was distributed different `eval_set` chunks, and therefore, each worker will have different `_best_score` and `evals_result_` data. As mentioned in <the following issue>, some workers may not even receive chunks of particular individual eval_sets in the original `eval_set`, and their values in the `best_score_` and `evals_result_` data dictionaries are imputed with the string 'not set'.

Since each worker has *some* results from the whole validation dataset, there is probably a better way to aggregate `best_score_`, `evals_result_`, etc. than to just return those attached to rank 0. As mentioned in the comment, there are some viable strategies for how to improve the current "rank 0 approach."

## References

This first issue was first raised in https://github.com/microsoft/LightGBM/pull/4101#discussion_r603751676 and that comment provides several good options for handling *all* `eval_set` metrics data:

```
1. Make DaskLGBM models return the model from every _train_part() task, and store the "non-rank-0" evals_result_ data on a new property in the Dask model objects like .other_evals_ or something like that. So accessing .evals_result_ will look and feel just like the sklearn API, but you can go find the other evaluation results in that other property if you want them.
2. try to write a different evaluation callback for Dask specifically, which, after each boosting round, aggregates evaluation metrics across all workers somehow
3. when training is over, before exiting fit() combine all the evaluation results by taking something like a mean weighted by sample count. This probably would give misleading or inaccurate results with some metrics though :/.
4. change nothing and just say "this is how it works, copy your eval data onto every Dask worker if you want to be sure you get eval results"
```
Regarding 3, this could be achieved by supporting a `.fit` argument called like `evals_combine_method` whose values can be `'average'` or `'weighted'` and let the user choose. Some eval_set data artifacts like `best_iteration_` would not support averaging.

**Comment by StrikerRUS** [comment]
Closed in favor of being in #2302. We decided to keep all feature requests in one place.

Welcome to contribute this feature! Please re-open this issue (or post a comment if you are not a topic starter) if you are actively working on implementing this feature.
