### ISSUE TITLE
[Python] Problem with passing arguments when inheriting from LGBMRegressor

### ISSUE THREAD

**Issue by j-adamczyk** [microsoft/LightGBM#4426]
## Description
When trying to use class inheriting from `LGBMRegressor`, it can't properly pass parameters and returns an error:
```
Traceback (most recent call last):
  File "/home/jakub/PycharmProjects/ml-models/venv/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py", line 431, in _process_worker
    r = call_item()
  File "/home/jakub/PycharmProjects/ml-models/venv/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py", line 285, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/home/jakub/PycharmProjects/ml-models/venv/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "/home/jakub/PycharmProjects/ml-models/venv/lib/python3.8/site-packages/joblib/parallel.py", line 262, in __call__
    return [func(*args, **kwargs)
  File "/home/jakub/PycharmProjects/ml-models/venv/lib/python3.8/site-packages/joblib/parallel.py", line 262, in <listcomp>
    return [func(*args, **kwargs)
  File "/home/jakub/PycharmProjects/ml-models/venv/lib/python3.8/site-packages/sklearn/utils/fixes.py", line 222, in __call__
    return self.function(*args, **kwargs)
  File "/home/jakub/PycharmProjects/ml-models/venv/lib/python3.8/site-packages/sklearn/feature_selection/_rfe.py", line 37, in _rfe_single_fit
    return rfe._fit(
  File "/home/jakub/PycharmProjects/ml-models/venv/lib/python3.8/site-packages/sklearn/feature_selection/_rfe.py", line 241, in _fit
    estimator.fit(X[:, features], y)
  File "/home/jakub/PycharmProjects/ml-models/venv/lib/python3.8/site-packages/lightgbm/sklearn.py", line 818, in fit
    super().fit(X, y, sample_weight=sample_weight, init_score=init_score,
  File "/home/jakub/PycharmProjects/ml-models/venv/lib/python3.8/site-packages/lightgbm/sklearn.py", line 570, in fit
    if isinstance(params['random_state'], np.random.RandomState):
KeyError: 'random_state'
```

It happens for any dataset, any case that I could find. There is no error if I add e.g. `params['random_state'] = 0` directly before the line causing error in `lightgbm/sklearn.py`. Passing `random_state` explicitly during LightGBM model creation does not fix this. Everything works for regular model creation, without inheritance.

## Reproducible example
Class inheriting from `LGBMRegressor`:
```
import lightgbm as lgb

class MyRegressor(lgb.LGBMRegressor):
    def __init__(self, objective="regression_l1", **kwargs):
        super().__init__(objective=objective, **kwargs)
```

Example usage resulting in error:
```
from sklearn.feature_selection import RFECV

model = MyRegressor(objective="regression_l1")
cv = RFECV(model)
cv.fit(X, y)
```

## Environment info

LightGBM version or commit hash: 3.2.1

Command(s) you used to install LightGBM

```shell
pip install lightgbm
```

**Comment by jose-moralez** [comment]
`scikit-learn` looks for the model parameters in the `__init__` signature, so overriding it makes this kind of expected since `get_params` only returns `objective`, see [this answer](https://stackoverflow.com/a/40027200/8998310) for more details.

I'm guessing you're not subclassing `LGBMRegressor` just to change the `objective` so maybe you could share some more details to see if there's a better way to achieve your goal.

**Comment by j-adamczyk** [comment]
@jose-moralez so to fix this, I just have to copy and paste arguments for `LGBMRegressor` to my custom regressor `__init__`, right?

I'm doing this, since this custom regressor is part of bigger custom pipeline, e.g. logging is done as decoractors for `.fit()` and `.predict()`, which also basically just call the superclass. This construction allows us to easily swap estimators inside - previously `GradientBoostingRegressor` from Scikit-learn was used, but I decided to switch to LightGBM. Code base is quite large, so wrapping estimator in custom class makes experiments easy, I just change the code of a single class and it's proparated automatically.

Curiously, for `GradientBoostingRegressor` code above worked, without having to pass any other arguments to the constructor.

**Comment by jose-moralez** [comment]
> @jose-moralez so to fix this, I just have to copy and paste arguments for LGBMRegressor to my custom regressor __init__, right?

I'd say that's the safest choice, because even if it doesn't throw an error you may get unexpected behaviour by not defining all your parameters, for example:

```python
from sklearn.base import clone
from sklearn.ensemble import GradientBoostingRegressor

class MyGBR(GradientBoostingRegressor):
    def __init__(self, max_depth, **kwargs):
        super().__init__(max_depth=max_depth, **kwargs)

myreg = MyGBR(max_depth=5, learning_rate=2)
myreg2 = clone(myreg)
myreg2.learning_rate
# 0.1
```
`sklearn.base.clone` is used in many of the `*CV` objects, like `GridSearchCV` and `RandomSearchCV`, and what it does is just take the output of `estimator.get_params()` and initialize a new estimator with those parameters. So in this example even though you *set* `learning_rate=2`, since that parameter isn't specified in `__init__` cloning it only copies `max_depth`

**Comment by j-adamczyk** [comment]
Ok, thank you, I see that this was a misunderstanding on my part, not LightGBM problem.

**Comment by jameslamb** [comment]
thanks for the assist, @jose-moralez !

@j-adamczyk I just want to add that the `scikit-learn` maintainers have extensively documented some guidance for developing `scikit-learn`-style estimators at https://scikit-learn.org/stable/developers/develop.html

That document helped me a lot when I started working on this project's Dask estimators (which sub-class the estimators in `lightgbm.sklearn`).
