### ISSUE TITLE
 LightGBMError: Dataset max_bin 1667309669 != config 63 

### ISSUE THREAD

**Issue by jtsw1990** [microsoft/LightGBM#4433]
## Description
Running lightgbm==2.1.3 in python. 
Using reticulate to read function into R.

The dataset is first saved into a binary file:
```
lgb_train = lgb.Dataset(
        df.loc[:, predictors],
        label=df[response].values,
        weight=df[weights].values,
        free_raw_data=False,
        feature_name=predictors,
        categorical_feature=categorical_predictors,
        reference=reference_data,
        params={"max_bin": 63}
    ).save_binary(bin_name)
```

The training dataset:

```
lgb_train = lgb.Dataset(lgb_train, feature_name=predictors, params={"max_bin": 63})
```

params:

```
LARGE_PARAMS = {
    "num_leaves": 40,
    "max_depth": 6,
    "boosting": "gbdt",
    "learning_rate": 1.0,
    "objective": "fair",
    "metric": "tweedie",
    "tweedie_variance_power": 1.05,
    "histogram_pool_size": 49152,
    "two_round": True,
    "verbosity": 0,
    "max_bin": 63
}

```

the main training function:
```
    bst_test_run = lgb.train(
        params=params, 
        train_set=lgb_train,
        valid_sets=[lgb_test],
        learning_rates=learn_rate_schedule,
        num_boost_round=int(max_rounds),
        callbacks=[lgb.record_evaluation(bst_res)],
        early_stopping_rounds=10)
```

I keep getting this error:

```
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  LightGBMError: Dataset max_bin 1667309669 != config 63 
```

![image](https://user-images.githubusercontent.com/32478278/124360065-0b0dd780-dc6b-11eb-996b-fcb153ca005a.png)

I am not too sure where this max_bin number is coming from as I have explicity set my max_bins in the dataset and at the  training step. There is not much support nor documentation on this issue from what I can see.

## Reproducible example
I cannot provide that much information due to sensitivity of the work, but I will try my best to give all I can in order to get some help.

## Environment info
Command(s) you used to install LightGBM

```
# Python dependencies
if (reticulate::py_available(initialize = TRUE) == FALSE) {
  keras::install_keras(extra_packages=c(
    "lightgbm==2.3.1",
    "snowflake-connector-python==2.1.3",
    "pyodbc==4.0.28",
    "pandas==0.25.3",
    "matplotlib==3.1.2",
    "pyarrow==0.15.1"
  ))
}

```

**Comment by jameslamb** [comment]
Thanks for the report and for using LightGBM!

I'll look into this when I have time in the next few days, but first I have two questions:

1. Is it possible for you to update to a newer version of `lightgbm`?
    - v2.3.1 was released in November 2019, and there have been many changes and fixes since then
2. Why are you using `{reticulate}` instead of installing `{lightgbm}` directly from CRAN?
3. How are you running the code you provided?
    - I understand that you said you're using `{reticulate}`, but the same code you shared is all Python code. How are you calling that code from R? I'm not personally very familiar with  `{reticulate}` so more information that would help.

**Comment by jameslamb** [comment]
I've added the label `awaiting response`. @jtsw1990 , are you able to work with maintainers here on this issue?

If not, it will be closed after 30 days without a response.

**Comment by jtsw1990** [comment]
Hey @jameslamb thanks for your time, I can't seem to replicate the scenario again strangely, am going to close this issue.

**Comment by jameslamb** [comment]
Sure, no problem. Come back any time and open an issue if you need additional help (or want to contribute 😛 ).

Thanks for using LightGBM!
