### ISSUE TITLE
Setting num_thread = 1 does not work on Windows

### ISSUE THREAD

**Issue by cnll0075** [microsoft/LightGBM#4447]
Hi there,

when setting num_threads = 1, on my linux machine CPU usage dropped from 70% to 10%, however, it didn't change CPU usage on windows machine. All 16 cores show the same CPU usage pattern (almost 100%) as shown in the attached screenshot. I've verified the high usage is from running lightGBM (i.e. not from other processes). Any idea what might have caused the different behavior on linux vs windows? Both machines have very similar specs. Thanks!

<img width="732" alt="Screen Shot 2021-07-05 at 4 02 24 PM" src="https://user-images.githubusercontent.com/31741624/124526126-a19adf80-ddb6-11eb-86f6-7ad07ed72c09.png">

Windows version: Windows Server 2016
LightGBM version: 2.3.0

**Comment by jameslamb** [comment]
Thanks for using LightGBM!

Can you please provide the information that was asked for when you clicked "new issue"?

1. a reproducible example (self-contained code that we could run which replicates the issue)
2. a description of how you installed LightGBM

Without that information, maintainers will have to guess at how your are using LightGBM, which will extend the time it takes to resolve this issue and draw maintainers' limited attention away from other work on the project.

**Comment by cnll0075** [comment]
Hi thanks for the reply! First I'd like to reframe my question and be more specific. The reason we're seeing high CPU usage on windows is because each training job takes 5X - 10X times longer than Linux, and because we have a lot of small jobs like the ones pasted below we see the CPU usage constantly at over 99%. Linux was like that before, but when we added `num_threads=1` it improved greatly -- CPU usage dropped to 10% and the running time actually improved (because our individual training job are very small so we don't need any parallelism). However, it did not help on Windows.  

Here is some example data and code. 
[example_data.csv](https://github.com/microsoft/LightGBM/files/6773236/example_data.csv)

`import pandas as pd
import lightgbm as lgb

data = pd.read_csv('example_data.csv')
CATEGORICALS = ['feature_1','feature_2', 'feature_3', 'feature_4', 'feature_5', 'feature_6', 'feature_7']
train_labels = data['label']
train_data = data.drop(['label'], axis=1)
dataset = lgb.Dataset(data[:-1],
                      label=train_labels[:-1],
                      categorical_feature=CATEGORICALS,  
                      free_raw_data=False) 
lb, ub = [lgb.train({'objective': 'quantile', 'alpha': alpha, 'verbose': -1, 'feature_fraction_bynode': 0.9,
                        'lambda_l2': 0.1, 'num_threads': 1},
                        dataset,
                        num_boost_round=10,
                        categorical_feature=CATEGORICALS).predict(train_data.iloc[-1]).item()
              for alpha in [0.01, 0.99]]`

Regarding lightGBM installation, for both machines we use conda install.

**Comment by shiyu1994** [comment]
@cnll0075 Thanks for using LightGBM.
On my windows 10, setting `num_threads` do make a difference. Setting `num_threads=8` makes a 100% CPU utility when training, while setting `num_threads=1` brings only about 30%. (My machine has 8 cores).
The number of threads is set with `omp_set_num_threads` if the `num_threads > 0`. I cannot come up with why this is not taking effect.
Does adjusting `num_threads` to other values (like 2, 4 and so on) affect the CPU utility?

**Comment by cnll0075** [comment]
Hi, yes setting it higher will make the CPU slightly higher, however, the difference is not as big as yours. Have you tried running the training longer (e.g. run it consecutively for 1000 times)?

Also should I try setting `omp_set_num_threads` in addition to `num_threads`?
