### ISSUE TITLE
Installation of CMake&MinGW is slow than Visual Studio

### ISSUE THREAD

**Issue by starrynight79** [Microsoft/LightGBM#446]
I tried the two method of installaion on my computer (6core,3.6Ghz). trainning and predicting with the same datasets(one million samples and 150 features). two method have different CPU occupancy. the detail info as follow:

CMake+MinGW:
trainning cost 560 seconds (CPU occupancy is 70%)
testing cost 44 seconds (CPU occupancy is 50%) 

Visual Studio:
trainning cost 547 seconds (CPU occupancy is 100%)
testing cost 23 seconds (CPU occupancy is 100%)

**Comment by guolinke** [comment]
Did you use the same ```num_thread``` ? 
you can try set it to ```12``` explicitly.

**Comment by starrynight79** [comment]
I used python in windows 10. In the windows task manager,I saw 12 logic processor are used in two method of installation, the difference is every logic processor occupancy is less than 70% in CMake&MinGW installation mode, but every logic processor occupancy is nearly 100% in VS installation mode.

**Comment by guolinke** [comment]
OK. I think the reason is the MinGW is not so efficient in windows.

**Comment by starrynight79** [comment]
maybe. i just want to know why the two compilation mode have nearly the same efficiency during training，but the big difference during predicting.

**Comment by guolinke** [comment]
The bottleneck in training is the memory speed. So increasing the ```num_thread``` not always can help. 

you also can try to set ```num_thread=6```. maybe VS version is better for the hyper-threading.

**Comment by starrynight79** [comment]
it sounds possible, thank you, i try later.

**Comment by huanzhang12** [comment]
I think the MinGW's OpenMP implementation is probably not as efficient as the VS's one.
When I tested GPU acceleration (compiled with MinGW) on Windows I also found it is slower than on Linux.

**Comment by Laurae2** [comment]
@huanzhang12 In MinGW it seems to be approximately 2% slower than MSVC.

For CPU + OpenCL + MinGW, it seems to be about 50% slower than pure CPU, which is not bad for OpenCL code. Also, accuracy is better than pure CPU for low depth models.
