### ISSUE TITLE
[Question] Passing categorical feature with data-type "Category" without passing "categorical_feature"

### ISSUE THREAD

**Issue by mohammad-saber** [microsoft/LightGBM#4460]
Thank you for sharing your great work. I have a question about handling categorical features without using ohe-hot enconding.

Assume that in the dataset, I have 2 categorical features. 

```
df = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': ['a', 'b', 'b', 'c', 'c'],
    'C': ['x', 'x', 'y', 'y', 'z'] })
```

I convert them into ordinal integer values and then convert data-type into "category".

```
columns_cat = ['B', 'C']

from sklearn.preprocessing import OrdinalEncoder
encoder = OrdinalEncoder(dtype='int')
x[columns_cat] = encoder.fit_transform(x[columns_cat])

for column in columns_cat:
    x[column] = x[column].astype('category')
```

**Question:** 
When data-type is `"Category"`, do I need to pass parameter `categorical_feature` when fitting model?

**CASE 1:**
In the following case, does LightGBM handles columns `['B', 'C']` as categorical?

```
from lightgbm import LGBMRegressor
model = LGBMRegressor()
model.fit(x, y)  
```

**CASE 2:**
And what is the difference when I pass `categorical_feature` as below:

```
from lightgbm import LGBMRegressor
model = LGBMRegressor()
model.fit(x, y, categorical_feature=columns_cat)  
```

Thank you for your time.

**Comment by StrikerRUS** [comment]
@mohammad-saber Thanks for using LightGBM!

'category' columns in pandas.DataFrame are treated as categorical features by default in LightGBM. So,

> When data-type is `"Category"`, do I need to pass parameter `categorical_feature` when fitting model?

you don't need to pass `categorical_feature` param in this case.

> **CASE 1:**
In the following case, does LightGBM handles columns `['B', 'C']` as categorical?

Yes, it does.

> **CASE 2:**
And what is the difference when I pass `categorical_feature` as below:

Should be no difference with **CASE 1**.

Maybe the following unit test will help to better understand handling categorical features in pandas.DataFrame.
https://github.com/microsoft/LightGBM/blob/d05f54701ee88a1373bd9e0a1ea4317827015c9c/tests/python_package_test/test_sklearn.py#L470

Also, please note that **ordered** categorical columns (`pd.Categorical(..., ordered=True)`) aren't treated as categorical features by default.
https://github.com/microsoft/LightGBM/blob/d05f54701ee88a1373bd9e0a1ea4317827015c9c/tests/python_package_test/test_sklearn.py#L484-L485
https://github.com/microsoft/LightGBM/blob/d05f54701ee88a1373bd9e0a1ea4317827015c9c/tests/python_package_test/test_sklearn.py#L515-L516

**Comment by mohammad-saber** [comment]
Thank you. 

Is there any attribute that we can get "features which were treated as categorical" after model fitting?

**Comment by StrikerRUS** [comment]
You can get this info from the LightGBM logs:
```
UserWarning: categorical_feature in Dataset is overridden.
New categorical_feature is <your cat features here>
```
#3379.

Also, categorical features are written differently in a model file.
https://github.com/microsoft/LightGBM/blob/48257d45e577df69abbc86542d0515159e524eb2/src/boosting/gbdt_model_text.cpp#L60-L67
