### ISSUE TITLE
[Question] Using SKLearn API, getting "UserWarning: Using categorical_feature in Dataset" when passing list of categorical features to "model.fit"

### ISSUE THREAD

**Issue by mohammad-saber** [microsoft/LightGBM#4465]
Thank you for your great work. I have a misunderstanding about categorical features when using scikit-learn API. I appreciate it if you could guide me on this issue. 

In the following code, I have a dataframe which has 1 numerical feature and 5 categorical features. I convert categorical features into ordinal integer starting from 0. Then, I pass list of categorical features into `model.fit.` 

```
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OrdinalEncoder
from lightgbm import LGBMClassifier


# Data
data_filepath = 'titanic_train.csv'

features_all = ['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Embarked']   # all features
features_cat = ["Pclass", "Sex", "SibSp", "Parch", "Embarked"]   # list of categorical features

data = pd.read_csv(data_filepath)[features_all + ['Survived']]

y = data['Survived']
x = data[features]


# Convert categorical features into ordinal integer values
encoder = OrdinalEncoder(dtype='int')
x[features_cat] = encoder.fit_transform(x[features_cat])


x_train, x_test, y_train, y_test = train_test_split(x, y, random_state= 0)

model = LGBMClassifier(num_leaves = 20, learning_rate=0.1, n_estimators=100)

# This line gives warning : "Using categorical_feature in Dataset"
model.fit(x_train, y_train, categorical_feature=features_cat)
``` 

When I run `model.fit`, I get the warning:

```
UserWarning: Using categorical_feature in Dataset.
  _log_warning('Using categorical_feature in Dataset.')
```

I was wondering what it means. Does it mean that LightGBM didn't consider the `categorical_feature` list that I passed, and selected the categorical features from dataset automatically. 

After fitting model, when I run the following line, I get an empty list:

`model.booster_.pandas_categorical 
`

Result ---> []

I tried model fitting by passing `feature_name` as below. I still get the same warning.

`
model.fit(x_train, y_train, categorical_feature=features_cat, feature_name=features_all)
`

Thank you for your time. 

**Dataset:**
[titanic_test.csv](https://github.com/microsoft/LightGBM/files/6796203/titanic_test.csv)

**Comment by StrikerRUS** [comment]
> Does it mean that LightGBM didn't consider the `categorical_feature` list that I passed, and selected the categorical features from dataset automatically.

No, it means that LightGBM is using **some** categorical features during this particular run. Since you pass categorical features explicitly as a list of column names, they are used in LightGBM.

> After fitting model, when I run the following line, I get an empty list:

That list `pandas_categorical` stores only categorical features that were extracted from `category` typed columns and when `categorical_feature='auto'` param. So in your case (explicitly passed list with category column names) this list is expected to be empty.

You can run
```
model.booster_.dump_model()
```
to make sure your `features_cat` features are treated as categorical.

**Comment by mohammad-saber** [comment]
Thank you. 
In the output of `model.booster_.dump_model()`, where can I find the list of categorical features?

**Comment by StrikerRUS** [comment]
In the `'feature_infos'` field. Categorical features will have `min_value` and `max_value` typed as `int` and `values` array won't be empty.
