### ISSUE TITLE
GPU documentation is not clear

### ISSUE THREAD

**Issue by cookielee77** [microsoft/LightGBM#4467]
Looks like "device=gpu" only supports single gpu training but "device=cuda" can support multi-gpus training. In addition, "cuda" looks like only support double-precision which is memory consuming. 

Is it possible to update the documentation for GPU argument more clearer (it took me a lot of time to find these secrets)? Also, is there a plan to support the single-prevision calculation with CUDA version in the near future? Double-precision is super memory-costly. 

Thanks!

**Comment by StrikerRUS** [comment]
@cookielee77 Thanks a lot for bringing this up!

> Is it possible to update the documentation for GPU argument more clearer (it took me a lot of time to find these secrets)?

Sure! Could you please suggest how these wordings can be improved to be clearer?
https://lightgbm.readthedocs.io/en/latest/Parameters.html#num_gpu
https://lightgbm.readthedocs.io/en/latest/Parameters.html#gpu_use_dp

> Also, is there a plan to support the single-prevision calculation with CUDA version in the near future?

You can subscribe to the following GitHub issue to get all news about single-prevision mode with CUDA version.

#3836.

For now, no one have taken this feature request, unfortunately.

**Comment by shiyu1994** [comment]
@cookielee77 Yes, we have a plan to support single-precision calculation with CUDA in the very near future.

**Comment by BinchaoPeng** [comment]
hi，I would like to realize the difference   @@between gpu version and cuda version, do you know where the doc is? @cookielee77 @jameslamb @StrikerRUS @shiyu1994 @cbecker

**Comment by StrikerRUS** [comment]
@BinchaoPeng Hi!
Sure, here it is: https://lightgbm.readthedocs.io/en/latest/Installation-Guide.html#build-cuda-version-experimental.

CUDA version is a re-written in CUDA language GPU version for systems where OpenCL is not available.

**Comment by BinchaoPeng** [comment]
> @BinchaoPeng Hi!
> Sure, here it is: https://lightgbm.readthedocs.io/en/latest/Installation-Guide.html#build-cuda-version-experimental.
> 
> CUDA version is a re-written in CUDA language GPU version for systems where OpenCL is not available.

okay，thank you！
