### ISSUE TITLE
Crossvalidation with TimeSeriesSplit

### ISSUE THREAD

**Issue by Dr4cky** [microsoft/LightGBM#4470]
I found the following post when searching for lightgbm.cv with TimeSeriesSplit: https://github.com/microsoft/LightGBM/issues/2984.

I have the following questions:

1. What is the difference between using folds=folds and folds=tss, where
tss = TimeSeriesSplit(3)
folds = tss.split(X_train)
2. Is it not necessary to specify Shuffle=False?

Thank you!

**Comment by StrikerRUS** [comment]
Hey @Dr4cky, thanks for using LightGBM!

> 1. What is the difference between using folds=folds and folds=tss, where ...

There is no difference. If you pass `folds=TimeSeriesSplit(3)`, LightGBM will call `split()` internally.
https://github.com/microsoft/LightGBM/blob/5b7a6f3e7150aeb704d1dd2b852d246af3e913a3/python-package/lightgbm/engine.py#L337

> 2. Is it not necessary to specify Shuffle=False?

When you pass `folds` argument explicitly, `shuffle` argument will be simply ignored.
