### ISSUE TITLE
Question on interaction constraints

### ISSUE THREAD

**Issue by mayer79** [microsoft/LightGBM#4481]
This is not a bug report but rather a question on how LightGBM deals with overlapping interaction constraints. If I understand the doc string correctly, each branch from root to leaf will split only on features appearing in one set of constraints.

So if the (Python) constraints are [[0, 1], [1, 2, 3, 4]], then the split path x0 -> x1 -> x2 is not possible because there is no constraint containing 0, 1, 2. Is this correct?

I think/hope the answer is "yes". I am asking, because for XGB, the answer surprisingly is "no".

https://github.com/dmlc/xgboost/issues/7115

@btrotta maybe?

**Comment by shiyu1994** [comment]
@mayer79
The answer is "yes".
LightGBM keeps track for each leaf the features on the path from the root to the leaf. And when splitting each leaf, only features in a interaction constraint set that contains all the features in the path are allowed.
See
https://github.com/microsoft/LightGBM/blob/5b7a6f3e7150aeb704d1dd2b852d246af3e913a3/src/treelearner/col_sampler.hpp#L92-L111

**Comment by mayer79** [comment]
Wonderful, thanks for confirmation and also the code snippet @shiyu1994 !
