### ISSUE TITLE
[Feature] Julia Package / Interface compatibility

### ISSUE THREAD

**Issue by Allardvm** [Microsoft/LightGBM#45]
It would be great if you would consider Julia's requirements when designing LightGBM's interface for R and Python. There's some quite extensive documentation on how Julia can call C and C++ code here: http://docs.julialang.org/en/release-0.5/manual/calling-c-and-fortran-code/#man-calling-c-and-fortran-code, but we can use this issue for discussion as well.

To get things started until LightGBM's interface is finished, I've build a Julia package that uses the current command-line interface to LightGBM for anyone interested: https://github.com/Allardvm/LightGBM.jl.

**Comment by guolinke** [comment]
Thanks, @Allardvm , we are working on c_api of LightGBM now. 
I took a look for the link you provided. It seems Julia can directly call the c_api without additional works on c interface.
Did I miss something?

**Comment by Allardvm** [comment]
If it's a regular C API then everything should be fine. As far as I can see the only limitation is _"Packed structs and union declarations are not supported by Julia."_

Looking forward to the API!

**Comment by guolinke** [comment]
@Allardvm I think the c_api in dev branch is ready to use. I will merge it after finished some tests and reviews. 
Please feel free to give some suggestions and feedback.
Thanks

**Comment by Allardvm** [comment]
Thanks! Will take a look.

**Comment by Allardvm** [comment]
I have pushed a new version of the Julia package that uses the C-API  to https://github.com/Allardvm/LightGBM.jl. The pull requests covered the bugs that I encountered, but I still have several minor suggestions that I will get back to later. Thanks!

**Comment by guolinke** [comment]
OK, BTW, i change/updated some c_api function (on python-package branch) for better flexibility, you can also take a look.

**Comment by Allardvm** [comment]
Closing this issue, since we now have a functional Julia package.
