### ISSUE TITLE
Question: Understanding increase of NDCG scores

### ISSUE THREAD

**Issue by PG20R** [microsoft/LightGBM#4502]
Hi!
I have a small question:
I am currently using lightgbm in a ranking application and hence try to optimize ndcg. In my project - as well as in other examples  I found online - I noticed the following behavior during training: The ndcg scores of the training and validation data seem to get much better already with a very small number of boosting rounds (with n_estimators = 5 already an ndcg improvement from 0,3 to 0,6 on training and validation data with only a few seconds training time). Increasing n_estimators more (to values like 50 or 100 or even more and hence more training time) doesn't make the ndcg values better anymore. Instead they are doing very small oscillations around a the value 0,6.
How to interprete this behavior? Is this the usual behavior in ranking applications when using lightgbm, is this a sign that the model is working well or is this behavior a reason to worry whether the model works correctly? And if the latter is the case, what could theoretically be the reasons for this behavior and how to improve it (as far as one can speculate about this without knowing the code)?

Thanks in advance for your answers.

PG

**Comment by guolinke** [comment]
Hi @PG20R , very sorry for the late response. The performance highly depends on data. In your case, I guess this data is not easy to fit ( NDCG=0.6 is not a very good score), and model may learn some easy rules (like predict the mean/median value), and achieve a score better than random guess.
