### ISSUE TITLE
Unable to suppress parameter alias related warnings

### ISSUE THREAD

**Issue by memeplex** [microsoft/LightGBM#4518]
## Description

Many parameter aliases trigger warnings that may be annoying and repetitive, specially in the context of model selection using grid search. These warnings can't be silenced except by changing the parameter to some specific alias. Often, this specific alias is not the one "recommended" (most used or first listed) in the documentation.

## Reproducible example

See https://github.com/microsoft/LightGBM/issues/3641#issuecomment-898092405

## Environment info

LightGBM version or commit hash: 3.2.1

**Comment by StrikerRUS** [comment]
@jameslamb I believe it's rather `bug` than `feature request`. Users ask to not print warnings (via `verbose=-1`) but this one is printed.

**Comment by jameslamb** [comment]
sure, fine with me

**Comment by rm17tink** [comment]
None of these comments or links work. They are circuitous to suppressing the [LightGBM] [Warning]

**Comment by StrikerRUS** [comment]
@rm17tink What exact warning you're trying to suppress? We aren't aware of any warnings other than 
```
[LightGBM] [Warning] param_alias_1 is set=xxx, param_alias_2=yyy will be ignored. Current value: param_alias_1=xxx
```
which cannot be suppressing by `verbosity=-1`.

**Comment by jmoralez** [comment]
These warnings are coming from https://github.com/microsoft/LightGBM/blob/23da5fc56abceac9ccb8ca2b09f945684e0f769e/include/LightGBM/config.h#L1135
which is called before setting the logging level. I believe if we set the logging level before this: https://github.com/microsoft/LightGBM/blob/23da5fc56abceac9ccb8ca2b09f945684e0f769e/src/io/config.cpp#L45
we can fix the issue. I'm not sure though so I'd like to discuss this first before opening a PR.

**Comment by StrikerRUS** [comment]
> I believe if we set the logging level before this

How will we know a requested logging level without parsing user's params ([`verbosity` param](https://lightgbm.readthedocs.io/en/latest/Parameters.html#verbosity) to be more precise)?
https://github.com/microsoft/LightGBM/issues/3641#issuecomment-898438044

**Comment by jmoralez** [comment]
What I was doing was something like:
```
int verbosity = Config().verbosity
GetInt(&verbosity, params, "verbose")
GetInt(&verbosity, params, "verbosity") 
```
before the alias call. So the default verbosity is used if it wasn't specified or it is set to what the user specified, and then the aliases are resolved for the other params.

**Comment by jameslamb** [comment]
I like your approach @jmoralez ! I'd support special handling of verbosity in `ParameterAlias::KeyAliasTransform()` to ensure that all log messages can be controlled by `verbose`.
