### ISSUE TITLE
feature_importances shouldn't take the first boosting iteration in account for regression tasks

### ISSUE THREAD

**Issue by kmike** [Microsoft/LightGBM#454]
Hey,

In a Python wrapper feature importances are calculated based on all trees in the model dump - see
https://github.com/Microsoft/LightGBM/blob/0eb9921991d21f7a61f5404494bad810811b1209/python-package/lightgbm/basic.py#L1633. 

But in case of a regression task the first tree (zeroth boosting iteration) is not relevant - it just produces a constant (a mean), it doesn't matter what feature is used for a split. So it seems this method of calculation inflates feature importance of a 0-th feature, and for correct computation it is better to use only trees starting from 1 in case of regression.

**Comment by guolinke** [comment]
@kmike 
the first tree in regression is add a constant for all samples. You can set boost_from_average=false to disable it.

**Comment by kmike** [comment]
I understand that it is a constant and that it can be disabled, the issue is that when the constant is enabled feature importances are not computed correctly. What do you think about changing feature importance computation, so that it doesn't take first iteration in account if boost_from_average is True?

**Comment by guolinke** [comment]
ok. I will fix it.

**Comment by kmike** [comment]
Thanks!

However, it seems the issue with Python wrapper is not fixed yet: it computes feature importances from the model dump, without using GBDT::FeatureImportance().

**Comment by guolinke** [comment]
@kmike Oh, sorry, I forget that.
@wxchan Can you help to fix that in python package? just ignore features with split-gain <= 0.
