### ISSUE TITLE
Enable use of constructed Dataset in predict() methods

### ISSUE THREAD

**Issue by jameslamb** [microsoft/LightGBM#4546]
## Summary

It should be possible to call `predict()` on a constructed `Dataset` and get raw predictions.

Note that it is currently possible to get an *evaluation* (value of metrics) on a constructed dataset  in LightGBM's public API. See https://github.com/microsoft/LightGBM/issues/4034#issuecomment-843003438.

## Motivation

Getting raw predictions can be useful for purposes other than evaluation of how a model performs on some set of metrics.

For example, in LightGBM the `predict()` method can be used for purposes like analyzing which leaf nodes each sample matches in each tree (`pred_leaf`). Without the ability to call `predict()` on a constructed `Dataset`, doing such analysis requires loading the raw data in memory.

## Description

N/A

## References

* #4034
* #4210

**Comment by jameslamb** [comment]
I opened this feature request in response to https://github.com/microsoft/LightGBM/issues/4034#issuecomment-843003438.

Added it to #2302, per this project's standard practice. If you are interested in contributing this feature, please leave a comment here and maintainers can re-open the issue and answer any questions you have.

tagging @shiyu1994 and @StrikerRUS , in case you want to add any additional details.

**Comment by StrikerRUS** [comment]
This is duplicate of #1939.

**Comment by jameslamb** [comment]
> This is duplicate of #1939.

oh! Forgot about that one. Since it isn't in #2302 I didn't think we already had a feature request for it.

I'll add a link to that to the existing item for this feature in #2302.
