### ISSUE TITLE
Multi-class R demo does not run (api error)

### ISSUE THREAD

**Issue by nnormandin** [Microsoft/LightGBM#455]
When trying to use the lightGBM R-package for some work I encountered the error "Number of classes should be specified and greater than 1 for multiclass training." I confirmed that my factor labels were converted to numeric and started at 0, but the error still occurred. I ran the exact code from the demo [here](https://github.com/Microsoft/LightGBM/blob/master/R-package/demo/multiclass.R), and received the same error.

## Environment info
Operating System: Ubuntu 16.04
CPU: i7, 7th gen
R version: 3.3.3

## Error Message:
`Error in lgb.call("LGBM_DatasetCreateFromMat_R", ret = handle, private$raw_data,  : 
  api error: Number of classes should be specified and greater than 1 for multiclass training`

I produced this error by running /lightGBM/R-class/demo/multiclass.R

**Comment by nnormandin** [comment]
I started up a parallel R session and am unable to reproduce the error, even after loading the same packages. I cleared the environment on the session producing the error and it continues to occur. Closing issue due to inability to reproduce.

**Comment by Laurae2** [comment]
@nnormandin use `lgb.unloader` to fix this. If you try to train a model with wrong/unexpected inputs, it will always error until you unload and restart the package.

**Comment by nnormandin** [comment]
@Laurae2 ahhhh thanks! rookie mistake on my part.

**Comment by guolinke** [comment]
@Laurae2 should we add this into document?
