### ISSUE TITLE
What does the parameter 'reference' mean in the lightgbm dataset API?

### ISSUE THREAD

**Issue by nitinmnsn** [microsoft/LightGBM#4555]
I used to think that the parameter means the bins cutoffs created in the training data would be used in the validation data if while creating the validation dataset I specify the training dataset as the value to the reference argument. However, I am not able to see any difference with or without passing anything to the reference parameter. Following is the code I used to study the parameter:

```
train = lightgbm.Dataset(xtrain,ytrain.target_variable,feature_name=feature_name,params={'verbose':-1}).construct()

val_ref = lightgbm.Dataset(xval,yval.target_variable,reference=train,free_raw_data=False,\
                           feature_name=feature_name,params={'verbose':-1}).construct()
val_noref = lightgbm.Dataset(xval,yval.target_variable,feature_name=feature_name,\
                             free_raw_data=False,params={'verbose':-1}).construct()
model1 = lightgbm.train(params={'metric':['auc']},train_set=train,valid_sets=[val_noref],\
                        early_stopping_rounds=50,num_boost_round=10000)
model2 = lightgbm.train(params={'metric':['auc']},train_set=train,valid_sets=[val_ref],\
                        early_stopping_rounds=50,num_boost_round=10000)
model1.predict(xtest)
output: array([0.01691352, 0.21934348, 0.12057389, ..., 0.40199047, 0.27511304,
       0.41782435])
model2.predict(xtest)
output: array([0.01691352, 0.21934348, 0.12057389, ..., 0.40199047, 0.27511304,
       0.41782435])
np.allclose(model1.predict(xtest),model2.predict(xtest))
output: True
```

The train, test and validation datasets are 40k, 30k and 10k records respectively. If the reference parameter was used to alter the binning I think the two models would have trained slightly differently and test results would have been somewhat different but, as you can see, they are exactly the same. 

So, Can you please explain what the 'reference' parameter does and if possible give an example that showcases the difference between using it and not using it.

Thank you for your time!

**Comment by guolinke** [comment]
Reference is to align the bin mapper (feature float values to bucketed int values) to the train set.
bin mapper will be calculated based on feature values, if without reference.
In your case, the val_noref may have a slightly different bin mapper as the train set, but almost the same. If the distribution of val and train is very different, the bin mapper could be very different. 

And as you only use val for early stopping, and use the exact same training set, the final model is likely to be the same. 

BTW, I don't remember, But LightGBM may check the bin mapper of train set and val set. If they are different, LightGBM may re-align the valset to trainset. 
cc @StrikerRUS  to confirm this detail.

**Comment by StrikerRUS** [comment]
@guolinke 
> BTW, I don't remember, But LightGBM may check the bin mapper of train set and val set. If they are different, LightGBM may re-align the valset to trainset.

Looks like LightGBM produces an error in a such case:
https://github.com/microsoft/LightGBM/blob/b78175b7468c727d1bd8d45bf675557598272c8b/src/boosting/gbdt.cpp#L140-L144

**Comment by nitinmnsn** [comment]
So, to summarise

1. If the distributions of val set and train set are so similar that they result in same bin mappers then it does not matter if or not you reference the train set while creating the val set
2. If the distributions of val set and train set are different (there's covariate shift) and the bin mappers thus produced are different then in that case:

- If the val set references the train set then the bin mapper of train set would be used

- If the val set does not reference the train set then this raises an error as pointed out by @StrikerRUS 

Have I got this correct?

**Comment by shiyu1994** [comment]
@nitinmnsn I think the conclusion is basically correct. On the other hand, if the Dataset is not explicitly constructed (`construct` method is not called), when passed to the `train` method as valid data, the method will set `reference` of the valid data to the training data automatically, according to
https://github.com/microsoft/LightGBM/blob/29857c8adb3c879268cddc23037e0651c2ec4df6/python-package/lightgbm/engine.py#L225
