### ISSUE TITLE
[GPU] gpu load only on 26 percent

### ISSUE THREAD

**Issue by gugatr0n1c** [Microsoft/LightGBM#456]
I successfully compile gpu version on win10. 
Machine:

![image](https://cloud.githubusercontent.com/assets/17110787/25377115/e6474484-29a6-11e7-8cb7-bf832183609b.png)

Bellow is speed and accuracy comparision (private datasets, regression task, 500k x 400x size of matrix).

![image](https://cloud.githubusercontent.com/assets/17110787/25377171/144abe4c-29a7-11e7-8038-aed3c389b8a6.png)

And as you can see gpu is aprox 2x faster then cpu (accuracy almost same), what is great. I just wonder about slow utilization of gpu ~ only about 26percent. I am ware of that tree algorithm is not matrix multiplication, so it is more complex. So is this "normal"?

**Comment by Laurae2** [comment]
I think it's because your your dataset is "too small" for the power of your GPU, hence not scaling well.

I noticed this behavior on my AMD GPU on very small datasets.

**Comment by gugatr0n1c** [comment]
@Laurae2 yes, this make sence, ok thx, closing this
