### ISSUE TITLE
[doc] A page for listing related projects and links  

### ISSUE THREAD

**Issue by Blaizzy** [microsoft/LightGBM#4576]
## Summary

Hi,

My name is Prince Canuma, I’m a Data Scientist & DevRel at Neptune.ai,

Following the discussions in the https://github.com/microsoft/LightGBM/pull/4529  issue, 

I want to propose the creation of a related projects page devoted list and describe in-brief tools that have an integration or support LightGBM.

## Motivation

By creating this page, you will be creating a template for contributions from both SaaS or FOSS that integrate or support your project and ensuring they have high-quality and facilitating best practices.

This initiative, will give you the chance to collaborate with vendors and other open-source projects that are building or want to build customised solutions to augment the capabilities of LighGBM as well as ensuring that these solutions are inline with the current and future project roadmap. 

Finally, to clarify to stakeholders and your community of users, you can make a note that states your non-affiliation and non-endorsement of the projects listed on the related projects page. And you can also state that any issues with said projects should be directed to the vendor's or community communication channels.

## Description

Proposed page format:
* Tool - Description.
    * Docs link (to the integration or support page)
    * Github repo

## References

List of FOSS projects that have links to commercial products on their GitHub and docs that integrate or support their software
1. **Sklearn**
    1. Website(Recommended read): https://scikit-learn.org/stable/related_projects.html
    2. Github: https://github.com/scikit-learn/scikit-learn/blob/main/doc/related_projects.rst
2. **Pytorch ecosystem**
    1. Website: https://pytorch.org/ecosystem
3. **Xgboost**:
    1. Github: https://github.com/dmlc/xgboost/blob/3e7e426b36eb307dff64a2f81f8a5a225377891d/demo/README.md#integrations-with-3rd-party-software
4. **Fastai**
    1. Website: https://docs.fast.ai/callback.neptune.html
    2. Github: https://github.com/fastai/fastai/blob/master/fastai/callback/neptune.py#L14
5. **PyTorch lightning**
    1. Website: https://pytorch-lightning.readthedocs.io/en/stable/api/pytorch_lightning.loggers.neptune.html#module-pytorch_lightning.loggers.neptune
    2. Github: https://github.com/PyTorchLightning/pytorch-lightning/blob/0a71fe285966527472018e131ec34bd9c6b0f98d/docs/source/common/loggers.rst
6. **Open mmcv**
    1. Website: https://mmcv.readthedocs.io/en/latest/api.html?highlight=neptune#mmcv.runner.NeptuneLoggerHook
    2. Github: https://github.com/open-mmlab/mmcv/blob/c47c9196d067a0900b7b8987a8e82768edab2fff/mmcv/runner/hooks/logger/neptune.py

**Tip**: I think PyTorch ecosystem submission’s page have a great template start from. Link: https://pytorch.org/ecosystem/join

**Comment by StrikerRUS** [comment]
Closed in favor of being in #2302. We decided to keep all feature requests in one place.

Welcome to contribute this feature! Please re-open this issue (or post a comment if you are not a topic starter) if you are actively working on implementing this feature.

**Comment by jameslamb** [comment]
Sorry, this was locked accidentally. Just unlocked it. We'd still love help with this feature!
