### ISSUE TITLE
Compute partial dependencies from learned trees

### ISSUE THREAD

**Issue by ChristophAymannsQC** [microsoft/LightGBM#4578]
## Summary

Partial dependencies can be computed directly from the data distribution in the leaves of the trees in the booster, rather than by calling `predict`, see references below. This tends to be faster. It would be nice if LightGBM allowed for direct computation of the partial dependencies using this method.

## Motivation
Partial dependency plots are widely used to interpret a model. Providing a fast method for computing them would be a big asset.

## References

- A good overview of the method can be found here: http://nicolas-hug.com/blog/pdps.
- The original idea goes back to Friedman, Jerome H. 'Greedy function approximation: a gradient boosting machine.' Annals of statistics (2001): 1189-1232.

**Comment by StrikerRUS** [comment]
Closed in favor of being in #2302. We decided to keep all feature requests in one place.

Welcome to contribute this feature! Please re-open this issue (or post a comment if you are not a topic starter) if you are actively working on implementing this feature.

**Comment by jameslamb** [comment]
Sorry, this was locked accidentally. Just unlocked it. We'd still love help with this feature!
