### ISSUE TITLE
LGBM_DatasetCreateFromCSC does not allow thread control

### ISSUE THREAD

**Issue by david-cortes** [microsoft/LightGBM#4598]
The C api has a function named `LGBM_DatasetCreateFromCSC` which runs a parallel openmp block with the default number of threads, which will typically be the maximum number of available threads.

I think it'd be better and more transparent if the number of threads were user-controllable, allowing a parameter `int nthreads` in the function signature instead, just like it does for other functions within the package.

This function is also problematic for the R package as it gets called by `LGBM_DatasetCreateFromCSC_R`, which is used in one of the R tests (currently skipped because it fails some checks). The CRAN policies state that examples and tests are not supposed to use more than 1 or 2 threads, and this thus prevents the R test from becoming enabled once the other issues it raises become solved.

**Comment by jameslamb** [comment]
Thanks very much for reporting this. Can you please provide specific links / quotes for what you're referring to when you say "the CRAN policies"?

**Comment by david-cortes** [comment]
The CRAN Repository Policy:
https://cran.r-project.org/web/packages/policies.html

Says the following:
>> If running a package uses multiple threads/cores it must never use more than two simultaneously: the check farm is a shared resource and will typically be running many checks simultaneously.

Some of the configs they test on might even crash the R process if you attempt to do some multi-threaded computation with the maximum number of threads.


** *

The issue is BTW not just about the R package since this function is used by other interfaces too.

**Comment by jameslamb** [comment]
> I think it'd be better and more transparent if the number of threads were user-controllable, allowing a parameter int nthreads in the function signature instead, just like it does for other functions within the package.

None of the Dataset creation functions in LightGBM's C API have `nthreads` in their function signatures.

<details><summary>LBGM_DatasetCreate function signatures in C API (click me)</summary>

https://github.com/microsoft/LightGBM/blob/b462d0a40f6978c0a66a47af4522c2ae12532316/include/LightGBM/c_api.h#L109-L112

https://github.com/microsoft/LightGBM/blob/b462d0a40f6978c0a66a47af4522c2ae12532316/include/LightGBM/c_api.h#L126-L133

https://github.com/microsoft/LightGBM/blob/b462d0a40f6978c0a66a47af4522c2ae12532316/include/LightGBM/c_api.h#L203-L213

https://github.com/microsoft/LightGBM/blob/b462d0a40f6978c0a66a47af4522c2ae12532316/include/LightGBM/c_api.h#L226-L231

https://github.com/microsoft/LightGBM/blob/b462d0a40f6978c0a66a47af4522c2ae12532316/include/LightGBM/c_api.h#L248-L258

https://github.com/microsoft/LightGBM/blob/b462d0a40f6978c0a66a47af4522c2ae12532316/include/LightGBM/c_api.h#L272-L279

https://github.com/microsoft/LightGBM/blob/b462d0a40f6978c0a66a47af4522c2ae12532316/include/LightGBM/c_api.h#L294-L302

</details>

> if the number of threads were user-controllable
> runs a parallel openmp block with the default number of threads, which will typically be the maximum number of available threads

The number of threads used in Dataset construction is user-controllable, via parameter `num_threads`.

As you can see in the links above, all of the `LGBM_DatasetCreate*` functions support passing `parameters`.

In each of those methods, the `num_threads` found in parameters is passed to `OMP_SET_NUM_THREADS()`, which will set the result of any later call to `omp_get_num_threads()` (and implicitly set the number of threads used for OpenMP parallel regions that don't explicitly set a number of threads, as noted at https://www.openmp.org/spec-html/5.0/openmpsu110.html).

For example, in `LGBM_DatasetCreateFromCSC()`, the parameter value `num_threads` is passed to `OMP_SET_NUM_THREADS()`.

https://github.com/microsoft/LightGBM/blob/b462d0a40f6978c0a66a47af4522c2ae12532316/src/c_api.cpp#L1326-L1329

Given all that....I don't think it is accurate that "LGBM_DatasetCreateFromCSC does not allow thread control".

Passing `num_thread=1` (or any of the aliases of `num_thread` listed at https://lightgbm.readthedocs.io/en/latest/Parameters.html#num_threads) through `params` will change the number of threads used in Dataset construction.

The following example demonstrates construction of a LightGBM `Dataset` from a CSC matrix in the R package, as of latest `master` (https://github.com/microsoft/LightGBM/commit/b462d0a40f6978c0a66a47af4522c2ae12532316). 

```r
# test.R
library(lightgbm)
library(Matrix)

X <- matrix(
    data = rnorm(1e8)
    , nrow = 1e5
)
Xcsc <- as(X, "CsparseMatrix")
num_threads <- as.integer(Sys.getenv("EXAMPLE_NTHREAD"))

start_time <- Sys.time()
dtrain <- lightgbm::lgb.Dataset(
    data = Xcsc
    , params = list(num_threads = num_threads)
)
dtrain$construct()
print(sprintf("--- construction (num_threads=%d) ---", num_threads))
print(Sys.time() - start_time)
```

On my Mac, I ran this script 3 times each with `num_threads` 1, 2, and 4. As you can see below, higher values of that parameter resulted in faster construction.

```shell
EXAMPLE_NTHREAD=1 Rscript --vanilla ./test.R
# [1] "--- construction (num_threads=1) ---"
# Time difference of 17.88016 secs
# Time difference of 17.72601 secs
# Time difference of 17.60532 secs

EXAMPLE_NTHREAD=2 Rscript --vanilla ./test.R
# [1] "--- construction (num_threads=2) ---"
# Time difference of 10.77466 secs
# Time difference of 10.12384 secs
# Time difference of 10.49387 secs

EXAMPLE_NTHREAD=4 Rscript --vanilla ./test.R
# [1] "--- construction (num_threads=4) ---"
# Time difference of 7.150842 secs
# Time difference of 7.223807 secs
# Time difference of 7.122708 secs
```

----

Therefore, I think that the proposal in this issue (add an `nthreads` argument to the signature of `LGBM_DatasetCreate*` functions) is just one possible solution to #4705, and that this issue should be closed to consolidate discussion of the problem "thread control in LightGBM without globally altering OpenMP's default number of threads" in one place.
