### ISSUE TITLE
OpenMP seems very slow in AMD CPU. 

### ISSUE THREAD

**Issue by guolinke** [Microsoft/LightGBM#460]
The speed of multi-threading is even slower than the single thread .

**Comment by huanzhang12** [comment]
What CPU and how many threads you were running? In my experience if there are many (over 20?) threads the speed up will not be great.

**Comment by guolinke** [comment]
@huanzhang12 
Azure A7 machine, windows system. number of threads is the default setting.

**Comment by huanzhang12** [comment]
So the same VM with Linux is fine?

**Comment by guolinke** [comment]
@huanzhang12 I cannot test that due to I don't have permission to change OS on these VMs. 
But I think it could be the problem in windows.

**Comment by huanzhang12** [comment]
It is probably an issue with Azure. 

I am currently running some other applications on Azure, and I found that on Azure the performance is not as good as a real machine with a similar configuration (about 2x slower).

I guess the VM host machines are oversold a little bit; but the performance is predictable: I tried three virtual machines across 3 locations, with different CPUs (Intel/AMD), and my application on the 3 VMs run almost at the same speed (although 2X slower on my home server with a similar CPU clock rate).

**Comment by Laurae2** [comment]
@huanzhang12 Azure is heavily underperforming, even SPECint is 40% slower on Azure for an identical dual CPU setup (dual E5-2667v3, 842 for the original model, 569.6 for Azure).

real:

![image](https://cloud.githubusercontent.com/assets/9083669/25526388/9ec1a234-2c13-11e7-9b82-d913589e09cb.png)

Azure doc:

![image](https://cloud.githubusercontent.com/assets/9083669/25526396/a451010e-2c13-11e7-9682-4ea1f21cd451.png)

Also, most cloud sellers are providing hyperthreaded cores as part of physical cores, or never providing hyperthreaded cores. The first case is half (50%) of real performance, while the second case is 35% less real performance for well parallelized workloads.

@guolinke I might have a friend test benchmarking LightGBM on AMD Ryzen on Windows soon, but using MinGW (can't test Visual Studio). Will let you know if it's reproducible on his rig.

**Comment by Laurae2** [comment]
@guolinke I tested on a AMD Ryzen 7 1800X this morning, and it was way faster than i7-7700K 5.1GHz overclock. This was on Windows + MinGW + Python.

**Comment by guolinke** [comment]
@Laurae2 Thanks very much. It seems the problem is the VM, Not the AMD.
