### ISSUE TITLE
when predict ,raw_score =True and False ,result is same.  When the model train with custom object

### ISSUE THREAD

**Issue by zwqjoy** [microsoft/LightGBM#4629]
params = {'metric': 'auc', "objective": "binary", 'verbose': -1, "max_depth": 2, "max_bin": 32, "num_leaves": 64}
bst2 = lgb.train(params=params, train_set=dtrain, num_boost_round=15,
                 valid_sets=valid_sets, valid_names=valid_names, verbose_eval=-1, fobj=logloss_obj)

dpred = lgb.Dataset('../demo_data/agaricus.txt.test', free_raw_data=False)
dpred.construct()

print("2. use custom object")
pred3 = bst2.predict(dpred.get_data(), raw_score=False)
print(pred3)

[-1.10048319  1.02263501 -1.10048319 ...  1.81410851 -2.03927137
  1.81410851]

pred4 = bst2.predict(dpred.get_data(), raw_score=True)
print(pred4)

[-1.10048319  1.02263501 -1.10048319 ...  1.81410851 -2.03927137
  1.81410851]

**Comment by guolinke** [comment]
It is expected. 
when with custom obj, the model will always output the raw scores.

**Comment by zwqjoy** [comment]
Thanks
