### ISSUE TITLE
cannot clone with --recursive because of libeigen problems

### ISSUE THREAD

**Issue by lmassaron** [microsoft/LightGBM#4645]
## Description
fatal: repository 'https://gitlab.com/libeigen/eigen.git/' not found
fatal: clone of 'https://gitlab.com/libeigen/eigen.git' into submodule path 'C:/Users/Luca/Desktop/LightGBM/external_libs/eigen' failed
Failed to clone 'external_libs/eigen'. Retry scheduled

## Reproducible example
git clone --recursive https://github.com/Microsoft/LightGBM

**Comment by TaehyunJo-CP** [comment]
https://gitlab.com/libeigen/eigen/-/issues/2336

Maybe It seems a cause of the problem.

**Comment by StrikerRUS** [comment]
All our recent CI jobs are failing with this error.
#4644
Thanks for reporting this! Hope they restore the repository ASAP.

**Comment by jameslamb** [comment]
I don't even understand how this can happen 😭 

There aren't any active incidents or reports of degraded service at https://status.gitlab.com/

**Comment by jameslamb** [comment]
According to https://gitlab.com/libeigen/eigen/-/issues/2336#note_694339283, the Eigen repo is now back up on GitLab. Not all features of that repo have been restored, but for LightGBM's purposes (just cloning the latest state of the `master` branch), the repo is up and I believe this issue can be closed.

Just ran the following successfully.

```shell
git clone --recursive git@github.com:microsoft/LightGBM.git
```

Thanks very much for reporting this @lmassaron , and to @TaehyunJo-CP for finding the relevant discussion with the Eigen maintainers.

**Comment by StrikerRUS** [comment]
@jameslamb Just one minor note
> ... but for LightGBM's purposes (just cloning the latest state of the `master` branch) ...

We are not cloning the **latest** state of the Eigen repo, but a particular one specified via a commit hash:
https://github.com/microsoft/LightGBM/tree/master/external_libs
Right now it is `8ba1b0f`.

**Comment by jameslamb** [comment]
Ah ok, maybe I misunderstood how submodules work. I didn't see any specific commits referenced in https://github.com/microsoft/LightGBM/blob/a77260f03eb735923125024b0f36df9f63a6e0f3/.gitmodules
