### ISSUE TITLE
[question] best way to learn from arbitrary-placed sequences

### ISSUE THREAD

**Issue by JivanRoquet** [microsoft/LightGBM#4652]
In the end what I'm aiming at is sort-of mimicking how convolutions work in a neural network, but I don't know if this is possible at all in LightGBM, and if so, what is the best way to do it.

Suppose there is an input feature which consists of sequence of tri-gram characters.

```
example 1: [ams, mst, ste, ter, erd, rda, dam]
example 2: [new, ewy, wyo, yor, ork]
```

I would like the model to learn that the sequence `mst -> ste -> ter` in that order is indicative of the class `amsterdam`, but the place at which this sequence is located should not be a hard condition.

The issue I'm struggling with is that if I simply encode each tri-gram as a separate categorical feature, then the model would learn that if `trigram_1: ams, trigram_2: mst, trigram_3: ste` then this is indicative of `amsterdam`, but then this information wouldn't generalize if the trigrams are offset by one or more characters e.g. `trigram_4: ams, trigram_5: mst, trigram_6: ste`.

However, I would still like the model to keep some degree of preference in the position of appearance of a sequence, for instance the above sequence would be *more* indicative or `amsterdam` if it's in the beginning of the string, rather than at the end, but still able to generalise flexible positions.

This is typically a good use case for convolutions in a neural network. Is it possible to reproduce this with LightGBM and what would be the best way to achieve this?

**Comment by JivanRoquet** [comment]
Hello and thank you for the guidance.

I apologize if my question was unclear, but my intention was specifically to make the order of trigrams matter.

For instance, the following trigrams in this order would be indicative of `rotterdam` (for the model):

```
rot, ott, tte, ter, erd
```

But the same trigrams in the following order would not be (or less so):

```
erd, tte, ter, ott, rot
```

I'm wondering how (and if) present the data to LightGBM so that the order matters in its learning.

**Comment by guolinke** [comment]
you can refer to feature process in https://arxiv.org/pdf/1702.08835.pdf
