### ISSUE TITLE
How to teach LightGBM about distances between target labels in multiclass?

### ISSUE THREAD

**Issue by JivanRoquet** [microsoft/LightGBM#4665]
I was experimenting around custom objective functions but in the meantime, I'd like to know if there's any other (perhaps more appropriate) method of dealing with the following problem.

Say I have a multinomial classification model which can predict a city based on some features:

| language_spoken | preferred_plate | city |
| ----------------- | --------------- | ----- |
| French | Fries | Bruxels |
| French | Frogs | Paris |
| French | Duck | Bordeaux |
| English | Fish&Chips | London |
| English | Burger | New York |
| English | Duck | Hong Kong |
| German | Steak Pie | Berlin |

I'd like to make this model aware that Paris and Bordeaux are "kind of" more related together than London and Beijing are, for instance. A possibility is to assume this on a geographical distance basis, or on a "same-country" basis, or both.

My first thought was implementing a custom function that, at each iteration, would join the (precalculated) distance between the predicted city and the observed label city, and multiply the `grad` accordingly.

The problem with this approach is that this custom function makes the training very slow, as it's implemented in Python instead of C++ (as is the standard `multiclass` objective function).

Would there be any other way, besides using a custom objective function, to teach the model about the respective similarities between the cities it's trying to predict?

I've thought of embedding the target city along a number of floating-point vectors, based on name, latitude, longitude, country, and other parameters, and then turn this problem into a (n-vectors)-class regression model, but I'm afraid that the predictions would be somehow more noisy

- is this idea of embedding a target category a common approach?
- how then to replicate the `predict_proba()` method that gives output probabilities instead of just one value?

**Comment by shiyu1994** [comment]
@JivanRoquet Thanks for using LightGBM. There's no official implementation in LightGBM to encode different distances of target labels during training. I think a customized objective function is an appropriate choice, and it won't be too slow if we write the vectorized code (with numpy for example).
On the other hand, I don't think turning the target labels into float values and change the task to regression is an ideal solution. Sometimes we just cannot encode the `distance` (which can be distance in 2D or even higher dimensional space) on the 1-dimensional axis of real number. And I'm not sure whether there is a standard way to recover the probabilities with the regression predictions.
