### ISSUE TITLE
[R-package] `predict` ignores `predict_raw_score`

### ISSUE THREAD

**Issue by david-cortes** [microsoft/LightGBM#4670]
After fitting a binary classification model, calling `predict` with `predict_raw_score=TRUE` or its aliases as explained in [the docs](https://lightgbm.readthedocs.io/en/latest/Parameters.html#predict-parameters) will not output the raw score, only a probability as it would without this parameter:
```r
library(lightgbm)
data("agaricus.train")
pool = lgb.Dataset(agaricus.train$data, label=agaricus.train$label)
params = list(
    objective_type="binary",
    force_row_wise=TRUE,
    seed=123
)
model = lgb.train(params, pool, verbose=0)
summary(predict(model, agaricus.train$data, params=list(predict_raw_score=TRUE)))
```
```
     Min.   1st Qu.    Median      Mean   3rd Qu.      Max. 
0.0000201 0.0000212 0.0000232 0.4821127 0.9999774 0.9999774 
```
```r
summary(predict(model, agaricus.train$data))
```
```
     Min.   1st Qu.    Median      Mean   3rd Qu.      Max. 
0.0000201 0.0000212 0.0000232 0.4821127 0.9999774 0.9999774 
```

**Comment by jameslamb** [comment]
Thanks for raising this! This is an inconsistency we should resolve.

As documented in [the R package docs](https://lightgbm.readthedocs.io/en/latest/R/reference/predict.lgb.Booster.html) or in `?lightgbm::predict.lgb.Booster`, that function has a keyword argument `rawscore` which you can set  to `TRUE` to get raw scores.

However, we should consider raising warnings on inconsistencies between those keyword arguments and the equivalent core-LightGBM parameters, and clearly document the expectation for which value "wins" when both are supplied.
