### ISSUE TITLE
Build Python wheels that support both GPU and CPU versions out of the box for non-Windows

### ISSUE THREAD

**Issue by StrikerRUS** [microsoft/LightGBM#4684]
Right now Python wheels from PyPI can be used to run training of LightGBM on both CPU and GPU (OpenCL-based implementation), thanks to #3144. It is done only for Windows, but can be implemented and for non-Windows systems as well, refer to 
> the static build technique also works on Linux, but will require a small upstream change in the build options for the Khronos ICD library. For now, I'm referencing my fork with that change in the Khronos build script. Depending on community feedback (that is, whether this build option would be useful on Linux too) I'll either pursue the upstream change in the Khronos library or pull out the Linux build code from this PR.
    https://github.com/microsoft/LightGBM/pull/3144#issue-630174938

https://github.com/microsoft/LightGBM/pull/3144#issuecomment-689182207

Also linking #2263 here as related.

To close this issue take #3144, #3660 as a reference and do the same for non-Windows systems.

I'm trying to push this forward due to the agreement on that OpenCL-based version is still important and shouldn't be abandoned after releasing new CUDA implementation: https://github.com/microsoft/LightGBM/pull/4630#discussion_r719122750.

**Comment by StrikerRUS** [comment]
Closed in favor of being in #2302. We decided to keep all feature requests in one place.

Welcome to contribute this feature! Please re-open this issue (or post a comment if you are not a topic starter) if you are actively working on implementing this feature.

**Comment by StrikerRUS** [comment]
Kindly ping @tpboudreau @itamarst for the answer to this question https://github.com/microsoft/LightGBM/pull/3144#issuecomment-877126007.

**Comment by jgiannuzzi** [comment]
I have tried to implement this in #5252.

**Comment by jgiannuzzi** [comment]
@StrikerRUS could you please re-open this issue and have a look at #5252?

**Comment by jameslamb** [comment]
Thanks very much for your work! I've re-opened the issue and assigned it to you for now (as a way to indicate to others that you are working on it). Let's keep all conversation about the specific code changes in #5252.

**Comment by StrikerRUS** [comment]
@jameslamb Is this issue resolved and Linux wheels can be used for GPU training?

![image](https://github.com/user-attachments/assets/8301fede-1fcf-4edc-bdf9-a7aeb672b215)

**Comment by jameslamb** [comment]
Ah yes definitely! This was complete as of #5252. I'll check that off as completed in #2302. Thanks for checking into these older issues!
