### ISSUE TITLE
There is something wrong with cv()

### ISSUE THREAD

**Issue by fstonezst** [Microsoft/LightGBM#470]
params = {
            'objective': 'binary',
            'metric': 'binary_logloss',
            'verbose': -1
        }

evalHis = lgb.cv(params, train, nfold=fold, num_boost_round=num_round,
                     stratified=True, metrics='auc', early_stopping_rounds=earlyStop,
                     verbose_eval=10, seed=0)

Error Message:
================================================================
/home/peter/anaconda2/lib/python2.7/site-packages/lightgbm-0.1-py2.7.egg/lightgbm/engine.pyc in cv(params, train_set, num_boost_round, data_splitter, nfold, stratified, shuffle, metrics, fobj, feval, init_model, feature_name, categorical_feature, early_stopping_rounds, fpreproc, verbose_eval, show_stdv, seed, callbacks)
    360         params.setdefault('metric', [])
    361         if isinstance(metrics, string_type):
--> 362             params['metric'].append(metrics)
    363         else:
    364             params['metric'].extend(metrics)

AttributeError: 'str' object has no attribute 'append'

If the metric in the params is a string type and the metrics has been set in cv()，
the cv function will crash.

**Comment by wxchan** [comment]
you can remove 'metric' in params for now, I will fix this later

**Comment by fstonezst** [comment]
I change the metric in my params:
'metric': ['binary_logloss'] :)
