### ISSUE TITLE
[R-package] lightgbm removed from CRAN

### ISSUE THREAD

**Issue by jameslamb** [microsoft/LightGBM#4713]
## Description

As of this morning, `{lightgbm}` has been removed from CRAN.

https://cran.r-project.org/web/packages/lightgbm/index.html

> Package ‘lightgbm’ was removed from the CRAN repository.

> Formerly available versions can be obtained from the archive.

> Archived on 2021-10-25 as check problems were not corrected in time.

> A summary of the most recent check results can be obtained from the check results archive.

> Please use the canonical form https://CRAN.R-project.org/package=lightgbm to link to this page.

## Additional Comments

"check problems" most likely refers to #4674 and #4680.

**Comment by StrikerRUS** [comment]
Looks like v3.3.1 release is starting to roll out at the CRAN 🤞 

https://cran.r-project.org/web/checks/check_results_lightgbm.html
![image](https://user-images.githubusercontent.com/25141164/139537982-769b9534-2ed5-4d29-ab5a-d8ef4aa8af4c.png)

**Comment by shiyu1994** [comment]
Great to hear that!

**Comment by jameslamb** [comment]
A few more checks (linux, mac, solaris) have passed, and `clang-ASAN` and `gcc-ASAN` issues have been removed from the package's checks page.

![image](https://user-images.githubusercontent.com/7608904/139608731-8564ca9e-d0e7-4611-b22b-c6e16e95f045.png)

https://cran.r-project.org/web/checks/check_results_lightgbm.html

I don't know if it's possible to see any information for the "Additional Checks" (like `gcc-ASAN`) that says "CRAN ran this and it passed"...in my experience, you only get to learn that those checks ran if they fail.

At the moment, according to https://cran.r-project.org/web/packages/lightgbm/index.html, there are v3.3.1 binaries available for `armg64` mac environments, and otherwise the package can be installed from source.

![image](https://user-images.githubusercontent.com/7608904/139608718-9a54a676-7dbb-47dc-998a-fce613415c29.png)

Still a lot of checks to go, but at least now it is once again possible to get `{lightgbm}` from CRAN with `install.packages("lightgbm", repos = "https://cran.r-project.org")`!

**Comment by jameslamb** [comment]
According to https://cran.r-project.org/web/packages/lightgbm/index.html, binaries for Mac are now available.

![image](https://user-images.githubusercontent.com/7608904/139696984-49e3190c-b06f-42fb-8efd-e5760d47ef10.png)

No checks have been run yet on Windows, I think related to some expected maintenance on CRAN's Windows cluster today. From `r-pkg-devel` mailing list (https://stat.ethz.ch/pipermail/r-package-devel/2021q4/007498.html):

> Dear all,

> winbuilder service and CRAN incoming checks (submission is possible) 
will be offline tomorrow (Nov 1) from 10 am CET to not later than 6pm.

> Some CRAN hardware in Dortmund will be physically migrated to a new 
location.

> Best,
  Uwe Ligges
  (CRAN team)

**Comment by jameslamb** [comment]
Checks going well so far. Windows binaries for R 4.2.x are now available.

Comparing https://cran.r-project.org/web/checks/check_results_lightgbm.html to https://cran.r-project.org/web/checks/check_results_xgboost.html, I think the following checks remain:

* `r-devel-linux-x86_64-debian-clang`
* `r-devel-windows-x86_64`
* `r-devel-windows-x86_64-gcc10-UCRT`
* `r-patched-linux-x86_64`
* `r-release-linux-x86_64`
* `r-oldrel-windows-ix86+x86_64`

As well as any of CRAN's "Additional Checks" ([link](https://cran.r-project.org/web/checks/check_issue_kinds.html)), whose status we can't see.

**Comment by mayer79** [comment]
Excellent, thank you so much!

**Comment by jameslamb** [comment]
According to https://cran.r-project.org/web/checks/check_results_lightgbm.html, `{lightgbm}` 3.3.1 is now passing all of CRAN's checks, and CRAN has finished preparing Windows and Mac binaries.

Thanks to everyone who helped with this issue, and apologies for the disruption!
