### ISSUE TITLE
Problem with OpenMP when installing on Mac OS.

### ISSUE THREAD

**Issue by AdamsMi** [Microsoft/LightGBM#473]
## Environment info
Operating System: El Capitan 10.11.6
CPU: 1,3 GHz Intel Core i5

## Error Message:
CMake Error at /usr/local/Cellar/cmake/3.4.3/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find OpenMP (missing: OpenMP_CXX_FLAGS)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.4.3/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/Cellar/cmake/3.4.3/share/cmake/Modules/FindOpenMP.cmake:231 (find_package_handle_standard_args)
  CMakeLists.txt:27 (find_package)

I've followed the steps in Instalation guide multiple times and there is always the error with OpenMP. I've reinstalled gcc --without-multilib, but it doesn't help. Do you know how to face this issue? After several days googling about this problem (and finding that the solutions posted don't work), I've given up.

**Comment by Laurae2** [comment]
Use gcc-5 and not gcc-6 and it should compile.

You should get something like [this](https://github.com/Microsoft/LightGBM/issues/421#issuecomment-295331469):

```
$ /usr/local/Cellar/gcc@5/5.4.0_1/bin/gcc-5 --version
gcc-5 (Homebrew GCC 5.4.0_1 --without-multilib) 5.4.0
```

**Comment by AdamsMi** [comment]
I run this command and got: gcc-5 (Homebrew gcc 5.3.0 --without-multilib) 5.3.0.
What should I change during the process to change 6 -> 5?

**Comment by AdamsMi** [comment]
I've followed the steps from the beginning, and now there is a new problem..
When I run `cmake -DCMAKE_CXX_COMPILER=g++-6 -DCMAKE_C_COMPILER=gcc-6 ..`
(no matter whether I change 6 -> 5 or not ), I got the error:

The CMAKE_C_COMPILER:

    gcc-6

  is not a full path and was not found in the PATH.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.


CMake Error at CMakeLists.txt:8 (PROJECT):
  The CMAKE_CXX_COMPILER:

    g++-6

  is not a full path and was not found in the PATH.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.

**Comment by Laurae2** [comment]
@AdamsMi You need to pass the folder paths to g++ / gcc, and not only `g++-6` and `gcc-6`.

like: `-DCMAKE_CXX_COMPILER=/usr/local/Cellar/gcc@5/5.4.0_1/bin/g++-5 -DCMAKE_C_COMPILER=/usr/local/Cellar/gcc@5/5.4.0_1/bin/gcc-5`

You can pass without the folder paths only if you do have the folder paths in the PATH environment variable.

Like this picture in Windows:

![](https://cloud.githubusercontent.com/assets/9083669/24919175/1301b42e-1ee3-11e7-9823-70a1d4c8c39e.png)

**Comment by AdamsMi** [comment]
Thanks, I've managed to run this (I think that g++5 and gcc5 where in the PATH), and now I've got a new problem when installing. But that's a progress so thank you very much! :)

**Comment by Laurae2** [comment]
You can close this issue and open another issue with the new problem you got :p
