### ISSUE TITLE
Problem running setup.py ('cannot find lightgbm library...')

### ISSUE THREAD

**Issue by AdamsMi** [Microsoft/LightGBM#474]
Operating System: El Capitan
CPU:
C++/Python/R version:

Hi guys,
I've managed to get through the installation process (had to change g++ and gcc versions in the CMakeList.txt from 6 to 5 - maybe it has an impact here?) and I've been trying to run the setup.py file.

It fails both for python and python3 runs in the same way.  

## Error Message:

The error msg for python (python setup.py install) :

> Traceback (most recent call last):
>   File "setup.py", line 19, in <module>
>     LIB_PATH = [os.path.relpath(path, CURRENT_DIR) for path in libpath['find_lib_path']()]
>   File "lightgbm/libpath.py", line 29, in find_lib_path
>     raise Exception('Cannot find lightgbm Library in following paths: ' + ','.join(dll_path))
> Exception: Cannot find lightgbm Library in following paths: /Users/Michal/L/LightGBM/python-package/lightgbm/lib_lightgbm.so,/Users/Michal/L/LightGBM/lib/lib_lightgbm.so,/Users/Michal/L/LightGBM/lib_lightgbm.so,/Users/Michal/L/LightGBM/python-package/lightgbm/lib/lib_lightgbm.so,/System/Library/Frameworks/Python.framework/Versions/2.7/lightgbm/lib_lightgbm.so
> 

...and for python 3 (python3 setup.py install):

> Traceback (most recent call last):
>   File "setup.py", line 19, in <module>
>     LIB_PATH = [os.path.relpath(path, CURRENT_DIR) for path in libpath['find_lib_path']()]
>   File "lightgbm/libpath.py", line 29, in find_lib_path
>     raise Exception('Cannot find lightgbm Library in following paths: ' + ','.join(dll_path))
> Exception: Cannot find lightgbm Library in following paths: /Users/Michal/L/LightGBM/python-package/lightgbm/lib_lightgbm.so,/Users/Michal/L/LightGBM/lib/lib_lightgbm.so,/Users/Michal/L/LightGBM/lib_lightgbm.so,/Users/Michal/L/LightGBM/python-package/lightgbm/lib/lib_lightgbm.so,/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lightgbm/lib_lightgbm.so

The content of /Users/Michal/L/LightGBM/python-packaged/lightgbm/ folder is the following:
__init__.py callback.py engine.py   plotting.py
basic.py    compat.py   libpath.py  sklearn.py

**Comment by guolinke** [comment]
can you paste the list of file/folder in ```/Users/Michal/L/LightGBM/``` ?

**Comment by AdamsMi** [comment]
Of course, it is:
CMakeLists.txt README.md      docker         include        src
LICENSE        build          docs           pmml           tests
R-package      compute        examples       python-package windows

**Comment by guolinke** [comment]
@AdamsMi 
It seems you didn't build the ```lightgbm``` binary and ```lib_lightgbm.so```.

**Comment by vedayoung** [comment]
me too, so what did u do to solve this problem :D

**Comment by jameslamb** [comment]
hi @vedayoung , thanks for using `LightGBM`!

If you're having trouble installing LightGBM, can you please open a new issue and describe what you're trying and the error messages you see?
