### ISSUE TITLE
[RFC] Add FreeForm2 Into LightGBM

### ISSUE THREAD

**Issue by shiyu1994** [microsoft/LightGBM#4742]
## Summary

FreeForm2 is a module that transforms original feature values according to the arithmetic and logic expressions specified by users. The transformed features will be used as inputs to the model for training. We plan to integrate FreeForm2 into LightGBM.

## Motivation

Quote the description from @chjinche in #4733:
FreeForm2 is a flexible type of feature transforms, created by Microsoft Core Ranking and used widely over Microsoft production model training. As the name indicates, FreeForm2 empowers users to compose a free combination of features as they like. It is expressed by formulas to be applied in the model inputs. The surface syntax is s-expression, with parentheses in a LISP-like fashion to delimit. FreeForm2 has implicit type systems and evaluate a single, nested expression that returns a floating-point number. Please see more info about FreeForm in doc PR #4735.

Integration of FreeForm2 allows LightGBM to be more widely used in our products.

## Description

We plan to divide the integration into 3 parts:
1. Add the source code of FreeForm2 into LightGBM code base (PR #4733). The source code was originally a part of our product code, and we've got the approval to open source it. Though this is a large PR, it will have no interference with our current code base.
2. Adding interface in LightGBM allows use of FreeForm2 end-to-end with the model training. This PR adds two parameters for data construction from file, `transform_file` and `header_file`. `transform_file` describes the transform expressions, and `header_file` is a separate file for the original feature names. This PR also adds some tests and enables checks for transform in both Github action workflow and Azure Pipeline. (#4734)
3. Update the documents for how to use transform in LightGBM (#4735)

**Comment by chjinche** [comment]
@StrikerRUS @jameslamb, thanks for your comments. With some discussions, we figured out a way that may solved concerns you raised :wink:. Could we add a reflection mechanism for base class `Parser` in lightGBM? 
In this way, users could use lightgbm as dependency and customize the parser they like to do data preprocessing in a built-in way. And no extra ci and limited compiler/os problems are introduced. 
We could prepare examples and tutorials in [`lightgbm-transform`](https://github.com/microsoft/lightgbm-transform) repo, user could go there and learn how to play with parser.

**Comment by StrikerRUS** [comment]
@chjinche Thank you very much for your response!

> In this way, users could use lightgbm as dependency and customize the parser they like to do data preprocessing in a built-in way.

I believe this is the best way to go! And I think it's OK to add some API changes that are required by `lightgbm-transform`. We are doing almost the same with the SWIG wrapper: API is added in this repo but all tests are done in consumer's repository and we sometimes receive bug fixes (e.g. #2958).

> user could go there and learn how to play with parser.

Please don't forget to add some links in LightGBM docs to `lightgbm-transform` with the aim to help users discover it (e.g. like here #4584).

**Comment by chjinche** [comment]
Thanks @StrikerRUS for the plan approval! We will prepare a new pr soon as we discussed.

**Comment by jameslamb** [comment]
I don't understand what "a reflection mechanism for base class `Parser` in LightGBM" means, but as long as LightGBM isn't responsible for compiling FreeForm2 and pull requests / tests / bug reports for FreeForm2 live in a separate repo, I'm supportive of that proposal. Thanks for finding an alternative integration plan.

**Comment by chjinche** [comment]
hi @shiyu1994 @jameslamb @StrikerRUS hope you are doing well! 😄 
I've sent out the new integration PR #4782, could you please kindly review it? And looks most ci jobs passed except three R ones, but I did not change R package nor c api, could you please help take a look or share some simple debug way? Thanks a lot.

**Comment by chjinche** [comment]
Thanks @shiyu1994 for review the PR! @jameslamb @StrikerRUS May I know if you have time to take a look? 😄 all ci jobs passed now.

**Comment by jameslamb** [comment]
> May I know if you have time to take a look? 

Sorry for the delay, I've been traveling this week. I just reviewed and I'm comfortable with those changes, just looks like there is a bit of extra work to do to ensure the library continues to meet the strict portability requirements for CRAN.

**Comment by StrikerRUS** [comment]
Hey @chjinche ! Can the [branch `feat/enable_transform_to_lgbm`](https://github.com/microsoft/LightGBM/tree/feat/enable_transform_to_lgbm) be removed now from the LightGBM repo?

**Comment by StrikerRUS** [comment]
Gently ping @chjinche

**Comment by chjinche** [comment]
> Hey @chjinche ! Can the [branch `feat/enable_transform_to_lgbm`](https://github.com/microsoft/LightGBM/tree/feat/enable_transform_to_lgbm) be removed now from the LightGBM repo?

Sorry for the late response, deleted the unused branch.
