### ISSUE TITLE
Custom fold partition to cv

### ISSUE THREAD

**Issue by yutkin** [Microsoft/LightGBM#475]
Hello! I'm using Python API and I'm trying to pass my own fold partition to cv. In docs there is an argument for CV function:
```
data_splitter : an instance with split(X) method
    Instance with split(X) method.
```
but its description is very scarce. What should return this instance? What type of X it is accepting? etc.

**Comment by guolinke** [comment]
@wxchan

**Comment by wxchan** [comment]
@yutkin it should be similar to sklearn.model_selection.Kfold(http://scikit-learn.org/stable/modules/generated/sklearn.model_selection.KFold.html#sklearn.model_selection.KFold.split), take training features X_train as input and output a generator or iterator of (train_idx, test_idx). I will make the docs more clear later.
Do you think it's better to directly pass a generator or iterator of (train_idx, test_idx)?

**Comment by fstonezst** [comment]
@yutkin  
X is the number of samples.
Returns: a generator of (train_idx, test_idx)
