### ISSUE TITLE
Are there plans to fix: "LightGBM hangs when multithreading (OpenMP) and using forking in Linux at the same time."

### ISSUE THREAD

**Issue by ivannp** [microsoft/LightGBM#4751]
## Description
This is a well-know issue, mentioned in the [documentation (#11)](https://lightgbm.readthedocs.io/en/latest/FAQ.html). Are there plans to fix it?

**Comment by jameslamb** [comment]
Just noting that I think the part of the documentation @ivannp is referencing is the FAQ question https://lightgbm.readthedocs.io/en/latest/FAQ.html#lightgbm-hangs-when-multithreading-openmp-and-using-forking-in-linux-at-the-same-time.

Which refers to LightGBM issue #1789.

@ivannp are you currently facing this issue, and could you tell us about your specific use case? (e.g. how you're using LightGBM, what operating system, what version of LightGBM, etc.)

For your specific question, I personally don't know enough about OpenMP or #1789 to give a good answer. Maybe @Laurae2 or @guolinke can help.

**Comment by ivannp** [comment]
@jameslamb it's clear I am seeing the same issue, the flow is similar to the [#1789 repro](https://github.com/microsoft/LightGBM/issues/1789). I am basically asking whether this will be ever addressed, or, is it considered a by product of Python and OpenMP.

**Comment by Laurae2** [comment]
@ivannp This deadlock issue is not fixable on our side. It must be fixed on the compiler side (not every compiler is affected - for instance it's approximately a decade long bug on gcc, but works fine in icc). We are unable to directly fix it from LightGBM.

Each compiler will behave differently to forks inside forks. If you absolutely require to OpenMP in a fork while the master already used OpenMP, multiple possibilities:
* use a compiler that supports OpenMP at both levels (example: switch to Intel compilers)
* use only 1 thread in the fork to not use any OpenMP features in the fork
* don't use fork and use socket communication instead to spawn fully new processes (the latter does not benefit from COW nor shared memory, hence requires memory copies)

In the case you are using gcc and if you intend to use OpenMP inside a fork, absolutely make sure you never used OpenMP features before forking. In this case, OpenMP will initialize correctly in each fork (OpenMP inside a fork) and will correctly work without deadlocking on forked threads' parallel regions (fork in fork).

**Comment by jameslamb** [comment]
Thanks for the excellent explanation, @Laurae2 !
