### ISSUE TITLE
how to call LGBM_BoosterGetFeatureNamesSWIG from java

### ISSUE THREAD

**Issue by reneix** [microsoft/LightGBM#4760]
## Summary
I saw this, but still have no idea about how to call LGBM_BoosterGetFeatureNamesSWIG from java
can any one show some code please

method from libgbmlibJNI:
public static final native long LGBM_BoosterGetFeatureNamesSWIG(long var0);

https://github.com/microsoft/LightGBM/issues/2814

## Description

		<dependency>
			<groupId>com.microsoft.ml.lightgbm</groupId>
			<artifactId>lightgbmlib</artifactId>
			<version>2.3.180</version>
		</dependency>

**Comment by StrikerRUS** [comment]
Hey @reneix !
Unfortunately, we are not maintaining any high-level JAVA package here. We simply create a jar file via SWIG wrapper: https://lightgbm.readthedocs.io/en/latest/Installation-Guide.html#build-java-wrapper.

Some other libraries use our SWIG wrapper, so I believe their code may help you:
- https://github.com/feedzai/feedzai-openml-java/search?q=LGBM_BoosterGetFeatureNamesSWIG
- https://github.com/metarank/lightgbm4j/search?q=LGBM_BoosterGetFeatureNamesSWIG

**Comment by reneix** [comment]
@StrikerRUS thanks very much, will close
