### ISSUE TITLE
[python] CVBooster.predict does not use the best iteration

### ISSUE THREAD

**Issue by wuchihsu** [microsoft/LightGBM#4777]
I don't know if it is a bug. The `predict` of CVBooster will not use the best iteration as the `num_iteration` when `num_iteration=None`. It will use the best iterations of underlying Boosters, but they are all -1.

**Comment by shiyu1994** [comment]
@wuchihsu Thanks for using LightGBM. To identify the `best_iteration`, we need to enable early stopping by either specify early stopping rounds or by using early stopping callback, see
https://lightgbm.readthedocs.io/en/latest/pythonapi/lightgbm.train.html#lightgbm.train
and
https://lightgbm.readthedocs.io/en/latest/pythonapi/lightgbm.early_stopping.html#lightgbm.early_stopping

**Comment by StrikerRUS** [comment]
@wuchihsu Is it possible to share some code that illustrates the behavior you've described?

**Comment by wuchihsu** [comment]
If train with a valid set and early stopping,
```python
booster = lgb.train(params,
                    train_set,
                    num_boost_round=20,
                    valid_sets=[valid_set],
                    early_stopping_rounds=5)
```
then when the booster predicts,
```python
y_pred = booster.predict(X_test)
```
it will use the best iteration automatically. But if cv,
```python
eval_hist = lgb.cv(params,
                   train_set,
                   num_boost_round=20,
                   early_stopping_rounds=5,
                   return_cvbooster=True)

y_pred_list = eval_hist['cvbooster'].predict(X_test)
```
the cvbooster will not use its best iteration automatically. Because cvbooster will call predict of The underlying boosters, and their best iterations are -1. This can be solve by setting the num_iteration,
```python
cvbooster = eval_hist['cvbooster']
y_pred_list = cvbooster.predict(X_test, num_iteration=cvbooster.best_iteration)
```
but I just think it is more reasonable that cvbooster also use its best iteration automatically.

**Comment by shiyu1994** [comment]
@wuchihsu Thanks for finding that. I agree with you.

I think one possible solution may be setting the `best_iteration` of the `Booster`s to that of `CVBooster` after training a `CVBooster`. Gently ping @StrikerRUS for suggestions.

**Comment by StrikerRUS** [comment]
Another way will be to not overwrite individual boosters' `best_iteration` attributes for the possible further research, but instead override `predict()` method of the `CVBooster` and use its `best_iteration` as a default value for `num_iteration` argument
https://github.com/microsoft/LightGBM/blob/3b6ebd794b82e02f8d5e1d0b915533bb4c36dbfc/python-package/lightgbm/engine.py#L654

**Comment by shiyu1994** [comment]
> may be setting the best_iteration of the Boosters to that of CVBooster will be better.

I see. I can do that when I have time.

**Comment by jameslamb** [comment]
> I can do that when I have time.

@shiyu1994 @StrikerRUS I can also pick this one up if you haven't started on it yet!

And I'll be sure to check this in the R package too 😛

**Comment by shiyu1994** [comment]
@jameslamb That's great! Thank you.

**Comment by jmoralez** [comment]
Is it ok for me to pick this up? I wasn't aware of this and just got bit by it haha.

**Comment by jameslamb** [comment]
oh yeah totally! please do! @jmoralez @shiyu1994 sorry I didn't come back to this one sooner.
