### ISSUE TITLE
Relax constraint on logger class in `register_logger`

### ISSUE THREAD

**Issue by RustingSword** [microsoft/LightGBM#4783]
## Summary

Allow any logger instance to be registered via `register_logger`, as long as it has `info` and `warning` methods defined.

## Motivation

Currently only instance of `logging.Logger` or its subclass can be registered. I'd like to use logger from [`loguru`](https://github.com/Delgan/loguru), which is more convenient, however it will trigger `TypeError` now. Since only `info` and `warning` are used to log messages, any logger class providing these two methods would suffice.

## Description

Instead of checking the class of logger, just check the existence of `info` and `warning` method.

Reference implementation:
```python
def register_logger(logger) -> None:
    def _has_method(method):
        return callable(getattr(logger, method, None))

    if not _has_method("info") or not _has_method("warning"):
        raise TypeError("Logger must provide 'info' and 'warning' method")
    global _LOGGER
    _LOGGER = logger
```

## References

N/A

**Comment by jameslamb** [comment]
Thanks very much for the excellent feature request, and sorry for the delayed response. I totally support this relaxed constraint.

@StrikerRUS @jmoralez what do you think?

@RustingSword are you interested in contributing this? If you are and if other Python maintainers I've tagged support the idea, I'd be happy to answer any questions you have about the contribution process.

**Comment by RustingSword** [comment]
Sure, happy to contribute :)

**Comment by StrikerRUS** [comment]
I support the idea of allowing to register custom advanced logger classes.

Also, I think that for the forward compatibility we should ask custom class to provide `error()` method, even though we are not using it right now.
