### ISSUE TITLE
Error on `master` during creating R-package artifact

### ISSUE THREAD

**Issue by StrikerRUS** [microsoft/LightGBM#4810]
The error is
```
/usr/bin/bash --noprofile --norc /__w/_temp/a33835bd-d281-4493-92c1-a75b47d5fc5a.sh
Installing packages into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
Warning in install.packages(c("R6", "data.table", "jsonlite", "knitr", "Matrix",  :
  'lib = "/usr/local/lib/R/site-library"' is not writable
Error in install.packages(c("R6", "data.table", "jsonlite", "knitr", "Matrix",  : 
  unable to install packages
Execution halted
##[error]Bash exited with code '255'.
```
https://dev.azure.com/lightgbm-ci/lightgbm-ci/_build/results?buildId=11589&view=logs&j=5da18647-a2c4-530c-67bd-d83884ef8652&t=35f4e228-47be-5b41-fe2b-23aac79c123c

We are not creating R-package artifact for PRs, that's why #4775 passed all CI checks.
https://github.com/microsoft/LightGBM/blob/5fa887bb79d0e4d1961c8adafce9832448535e71/.vsts-ci.yml#L296
We need to comment that line during testing a fix and then uncomment it back.

I guess we just should either set env variable for a writable directory
https://github.com/microsoft/LightGBM/blob/5fa887bb79d0e4d1961c8adafce9832448535e71/.ci/test_r_package.sh#L5-L7
or specify it as `lib` argument 
https://github.com/microsoft/LightGBM/blob/5fa887bb79d0e4d1961c8adafce9832448535e71/.ci/test_r_package.sh#L108

cc @jameslamb

**Comment by jameslamb** [comment]
Ah! Thanks for writing this up. I can test in a few hours.
