### ISSUE TITLE
[LightGBM] [Fatal] Check failed: (best_split_info.left_count) > (0) at /LightGBM/src/treelearner/serial_tree_learner.cpp, line 686 .

### ISSUE THREAD

**Issue by nancyxjp2019** [microsoft/LightGBM#4817]
When I use default parmas to train the data on gpu ,sometimes to show this error, sometimes  succeed.
data shape: (2753921, 691)
os: macos 12
gpu: AMD Radeon Pro 5500M
lightgbm version: 3.3.1.99

**Comment by StrikerRUS** [comment]
@nancyxjp2019 Thanks for raising this issue! We are already aware of this error. Please copy-paste your message in #3679. Also, reproducible example will be highly appreciated! And I'd like to note that LightGBM is not officially supported for macOS: https://github.com/microsoft/LightGBM/issues/4333#issuecomment-853392437.
