### ISSUE TITLE
Python documents

### ISSUE THREAD

**Issue by henry0312** [Microsoft/LightGBM#485]
For example, I made python documents from source codes.
Please see https://henry.animeo.jp/lightgbm/index.html (this is a temporary example).
How do you think about it?
I can create a pull requet if you like.

**Comment by guolinke** [comment]
@henry0312 can this auto update when the interfaces is updated? 
if yes, is it based on the comments in py file or the generated docs ?

**Comment by henry0312** [comment]
> can this auto update when the interfaces is updated?

Sure, though if you want **completely** auto update, we need to use git push hock.

> if yes, is it based on the comments in py file or the generated docs ?

It is based on the comments in py file.
I used [Sphinx](http://www.sphinx-doc.org/en/stable/).

**Comment by guolinke** [comment]
oh great. "henry.animeo.jp" is your own url?
I think we can just host it in the ReadTheDocs.

**Comment by henry0312** [comment]
> "henry.animeo.jp" is your own url?

yes, it is.

> I think we can just host it in the ReadTheDocs.

I don't know ReadTheDcos very much, but ReadTheDocs seems to support Sphinx.
i guess we can also use [GitHub Pages](https://pages.github.com/).

**Comment by guolinke** [comment]
@henry0312 
can github page support sphinx ?

**Comment by henry0312** [comment]
Github Pages hosts any html, and Sphinx can build html from rst.
In short,

1. git push to master
2. update docs throw git push hock or something
3. git push to gh-pages

cf. https://daler.github.io/sphinxdoc-test/includeme.html

**Comment by guolinke** [comment]
@henry0312 ok. that is great. 
@Laurae2 I think we can also put R's documents like this.

**Comment by guolinke** [comment]
@henry0312 just open the github page: https://microsoft.github.io/LightGBM/
It will read the contents in the ```/docs/```

**Comment by henry0312** [comment]
ok, I'll try in my fork reopsitory at first.

**Comment by henry0312** [comment]
@guolinke How do you think about https://henry0312.github.io/LightGBM/python/ ? 😁

**Comment by guolinke** [comment]
it looks great. 
BTW, can we hidden the method/class starting with ```_``` .

**Comment by henry0312** [comment]
I've hidden these methods, I guess...
For example, if you search '_to_graphviz`, nothing is hit.

**Comment by kmike** [comment]
my 2c: readthedocs is better than github pages at least because it allows to host multiple documentation versions - it is possible to update docs for master without breaking docs for a stable release, and it is possible to get docs for older versions; this is all automatic.

**Comment by henry0312** [comment]
hum....

I can't decide which to use because I haven't use ReadTheDocs, though GIthub pages seems enough.

@guolinke which would you like to use?

**Comment by guolinke** [comment]
@henry0312 my only concern is:
it seems need to run Sphinx manually then push html if using github page. 

using ReadTheDocs seems can avoid that?

**Comment by henry0312** [comment]
> using ReadTheDocs seems can avoid that?

According to the http://docs.readthedocs.io/en/latest/getting_started.html, yes.
ReadTheDocs has webhook in Github.

**Comment by guolinke** [comment]
@henry0312 great. So, it seems ReadTheDocs is the best choice for now.

**Comment by henry0312** [comment]
However, If we use ReadTheDocs, we may need to create all docs via Sphinx...

**Comment by henry0312** [comment]
Okay, I'll try ReadTheDocs.
We should be able to use it because XGBoost also use it 😄

**Comment by henry0312** [comment]
@guolinke Please check http://testlightgbm.readthedocs.io/en/latest/ and get "lightgbm" account if you like.

**Comment by guolinke** [comment]
@henry0312 I just take the name ```lightgbm```. 
http://lightgbm.readthedocs.io/en/latest/

**Comment by henry0312** [comment]
Okay, I'll create a minimum pull requet.
After merging it, we will improve documetns including styles.

**Comment by guolinke** [comment]
@henry0312 can you give me your readTheDoc id? I can add you as a maintainer.

**Comment by henry0312** [comment]
Thank you! My account is henry0312.

**Comment by henry0312** [comment]
I though these works have finished, but I find there are some problems.
When Read the Docs build the documentation, it needs `lib_lightgbm` (which is also needed in python-package), so building the docs fails...
I'll fix.

**Comment by guolinke** [comment]
@henry0312 Thanks very much. 
Actually, I think we can add more documents into `docs`. And continue to refine the ReadTheDocs

**Comment by henry0312** [comment]
Python api reference, which is built from source files, are published on http://lightgbm.readthedocs.io/en/latest/python/lightgbm.html.

**Comment by guolinke** [comment]
@wxchan http://lightgbm.readthedocs.io/en/latest/python/lightgbm.html#module-lightgbm.basic
I saw many functions that should not be exposed in ```basic.py```. 
e.g.``` lightgbm.basic.C_API_DTYPE_INT64 ```

I think we should change their name to begin with ```_``` .

**Comment by henry0312** [comment]
However, theare are still some problems... 😢 

```
/home/docs/checkouts/readthedocs.org/user_builds/lightgbm/checkouts/latest/docs/python/lightgbm.rst:47: WARNING: autodoc: failed to import module 'lightgbm.plotting'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/lightgbm/envs/latest/local/lib/python3.5/site-packages/sphinx/ext/autodoc.py", line 551, in import_object
    __import__(self.modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/lightgbm/checkouts/latest/docs/../python-package/lightgbm/plotting.py", line 13, in <module>
    from .sklearn import LGBMModel
  File "/home/docs/checkouts/readthedocs.org/user_builds/lightgbm/checkouts/latest/docs/../python-package/lightgbm/sklearn.py", line 9, in <module>
    from .compat import (SKLEARN_INSTALLED, LGBMClassifierBase, LGBMDeprecated,
ImportError: cannot import name 'LGBMDeprecated'
/home/docs/checkouts/readthedocs.org/user_builds/lightgbm/checkouts/latest/docs/python/lightgbm.rst:55: WARNING: autodoc: failed to import module 'lightgbm.sklearn'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/lightgbm/envs/latest/local/lib/python3.5/site-packages/sphinx/ext/autodoc.py", line 551, in import_object
    __import__(self.modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/lightgbm/checkouts/latest/docs/../python-package/lightgbm/sklearn.py", line 9, in <module>
    from .compat import (SKLEARN_INSTALLED, LGBMClassifierBase, LGBMDeprecated,
ImportError: cannot import name 'LGBMDeprecated'
```

I'll continue to fix these issues.

**Comment by guolinke** [comment]
@henry0312 It seems miss sklearn.

**Comment by wxchan** [comment]
can we only expose functions and classes in this list? https://github.com/Microsoft/LightGBM/blob/master/python-package/lightgbm/__init__.py#L26-L30

**Comment by henry0312** [comment]
@wxchan I guess we may expose only `__all__` if we can put them into basic,py instead of \_\_init__.py
http://www.sphinx-doc.org/en/stable/ext/autodoc.html

**Comment by wxchan** [comment]
we only have one module. for example, lightgbm.Dataset, lightgbm.Booster, not lightgbm.basic.Dataset, lightgbm.basic.Booster.

**Comment by henry0312** [comment]
I see.
Does we publish exclude lightbm.basic?
We can control what modules are published by editing https://github.com/Microsoft/LightGBM/blob/master/docs/python/lightgbm.rst

**Comment by henry0312** [comment]
Okay, all issues have been fixed!
http://lightgbm.readthedocs.io/en/latest/python/lightgbm.html

**Comment by guolinke** [comment]
@henry0312 can you refine the document according to @wxchan  's suggestions ?

**Comment by henry0312** [comment]
yes, I'll check.

**Comment by henry0312** [comment]
I'm improving Python API docs.
That will have been finished in 2 or 3 hours.
