### ISSUE TITLE
On Histogram, is lightgbm binning according to each feature?

### ISSUE THREAD

**Issue by MJChku** [microsoft/LightGBM#4869]
Is lightgbm binning according to each feature and maintain histogram for each feature, 
or the whole dataset, all features combined, and maintain a single histogram?

**Comment by shiyu1994** [comment]
@MJChku Thanks for using LightGBM. The binning (choosing boundaries of histogram and converting feature values to bin ID's) and histograms are both per feature.

**Comment by MJChku** [comment]
Thank you, that's my guess as well.
