### ISSUE TITLE
Any suggestions about prediction for hundreds of millions of instances?

### ISSUE THREAD

**Issue by PayneJoe** [Microsoft/LightGBM#488]
Hi, I have a task of prediction for 400M instances and a pre-trained model. How can I achieve that as soon as possible with less development cost?

Best regards!

**Comment by guolinke** [comment]
@PayneJoe try our new feature in PR #469 and  #482 .
It convert the model to the hard code. 

you need to do:
1. convert you model to the code by set ```task=convert_model``` and ```input_model``` .
2. re-compile LightGBM.
3. Prediction like the normal prediction task.

if you met any problems,  @wxchan can provide more helps.

**Comment by PayneJoe** [comment]
@guolinke, thanks for the reply.

Sorry failed to write it clear, what I wanted to say is how can I deal with these huge FEATURED instances?  The disk cost is relatively expensive(do not need to be like that), especially when feature size is also great,  as the NORMAL PREDICTION TASK is a OFFLINE mode that is done after loading these instances. 

I thought I can adopt ONLINE mode, generating features in the fly, and then use the  c/c++ interfaces to do the prediction task(multiple threads or multiple nodes). But I doubt that the development would be consuming. Do you ever deal with this case like that? Do I have any other options? 

Best regards!

**Comment by guolinke** [comment]
Sorry, I didn't quite got your point. 

1. the prediction is Comand Line version LightGBM actually isn't the full offline mode. It uses a pipeline (2 threads, one reads data, one prediction). However, it predicts from file and write the result to the file. 

2. you can use these c_api to prediction: https://github.com/Microsoft/LightGBM/blob/master/src/c_api.cpp#L1010-L1025 . 

3. python/R version also support prediction from memory. 

4. the prediction is multi-threading, even for one data.

**Comment by PayneJoe** [comment]
Never mind, thanks all the same. You can leave this issue closed.
