### ISSUE TITLE
[R-package] Support R 4.2

### ISSUE THREAD

**Issue by jameslamb** [microsoft/LightGBM#4881]
## Summary

R 4.2 is going to include some significant changes to how packages are built on Windows. I've created this "feature request" to document those changes in this project's backlog and so that we have something to link conversations to if users report issues on R 4.2.x, but R 4.2 has not yet been released.

## Motivation

`{lightgbm}`, the R package for LightGBM, should continue to work with new versions of R.

## Description

See https://developer.r-project.org/Blog/public/2021/12/07/upcoming-changes-in-r-4.2-on-windows/. This was shared by Tomas Kalibera on the r-pkg-devel mailing list.

Some notable quotes

> R 4.2 for Windows will support UTF-8 as native encoding

> ...will require at least Windows 10 (version 1903) on desktop systems, Windows Server 2022 on long-term support server systems or Windows Server 1903 from the semi-annual channel

> R 4.2 will also drop support for 32-bit builds on Windows

> A new compiler toolchain, RTools42, will be used for building Windows binaries of R and R packages from source

According to that blog post, there is now support for testing on R Hub with the UCRT toolchain. See https://builder.r-hub.io/advanced.

<img width="1172" alt="Screen Shot 2021-12-11 at 10 57 30 PM" src="https://user-images.githubusercontent.com/7608904/145700918-eef6e45b-b0a4-43d6-a403-9dd306d48cac.png">

So I think it would be useful to add a new comment-triggered workflow, similar to the existing Solaris one.

https://github.com/microsoft/LightGBM/blob/80662618996431c222e6c92cbba7e784f8a935cd/.github/workflows/r_solaris.yml

## References

Since March of this year, CRAN has been running checks with this toolchain on existing packages. `{lightgbm}` is currently passing those checks without WARNINGs or ERRORs!

https://cran.r-project.org/web/checks/check_results_lightgbm.html

<img width="1098" alt="Screen Shot 2021-12-11 at 11 00 18 PM" src="https://user-images.githubusercontent.com/7608904/145700956-fbc817a8-bfc2-4963-afd7-e5f8d56b19f2.png">

**Comment by jameslamb** [comment]
Linking this helpful doc that was mentioned on the r-pkg-devel mailing list this week: https://cran.r-project.org/bin/windows/base/howto-R-4.2.html

**Comment by jameslamb** [comment]
R 4.2 will be released on April 22 (11 days from now): https://developer.r-project.org/

**Comment by StrikerRUS** [comment]
With logs from #5140, we have an evidence that LightGBM can be successfully compiled for the `R-4.2.0alpha`.
