### ISSUE TITLE
RMSLE Custom Objective Function

### ISSUE THREAD

**Issue by wiamadaya** [microsoft/LightGBM#4886]
Hi,

I would like to train a model using a custom objective function, Root Mean Squared Logarithmic Error (RMSLE), can someone help point me to the right direction how to create the function properly?

```
def custom_rmsle(y_true, y_pred):
    ....
    return grad, hess
```

`model = LGBMRegressor(objective = custom_rmsle)`

**Comment by TpTheGreat** [comment]
Hi @wiamadaya ,
I believe you can simply log transform your target values before training, and use the 'RMSE' loss.
after training, transform the predictions back.

**Comment by jameslamb** [comment]
Going to close this based on @wiamadaya 's emoji response to @TpTheGreat 's comment.

If that suggestion doesn't work and you can't find what you need in the other issues and documentation here, please leave a comment and this can be re-opened.
