### ISSUE TITLE
Multi-Class classification C++ example

### ISSUE THREAD

**Issue by kingvision** [Microsoft/LightGBM#49]
Hi:
    can you provide a Multi-Class classification C++ example?
thanks

**Comment by guolinke** [comment]
hi, @kingvision , LightGBM doesn't support multi class classification, but we will add this feature soon.
please follow the update of #43 .

**Comment by chivee** [comment]
@kingvision , please check https://github.com/Microsoft/LightGBM/tree/master/examples/multiclass_classification
