### ISSUE TITLE
[R-package] Check size of custom objective function outputs

### ISSUE THREAD

**Issue by yaxxie** [microsoft/LightGBM#4905]
https://github.com/microsoft/LightGBM/pull/4815

The above PR made changes to the python package and tests to check the outputs of the custom gradient functions conform to the assumptions made by the `LGBM_BoosterUpdateOneIterCustom` C-API call. 
Additionally, the C-API docs were updated to make it clear that it is the callers responsbility to provide correctly sized arrays to this library call.

The R package needs updating to include this safety check as well.

**Comment by jameslamb** [comment]
Thanks for writing this up and for all your help with the custom objective function stuff @yaxxie !

I've added this to #2302 with other feature requests, per this project's policy. I'm going to close it for now.

For anyone reading this...please comment if you'd like to work on this, and we can re-open it and answer questions.

**Comment by jameslamb** [comment]
Sorry, this was locked accidentally. Just unlocked it. We'd still love help with this feature!
