### ISSUE TITLE
Histogram algorithm behaviour not as expected

### ISSUE THREAD

**Issue by kapytaine** [microsoft/LightGBM#4907]
## Description
I recently observed that shifting a numerical feature changed the result of the training. This is not what I expected when I read ["LightGBM uses the simplest greedy equally density binning algorithm"](https://github.com/microsoft/LightGBM/issues/2063). Maybe I do not know well enough the algorithm. I expected that the split value would be the median of the dataset (since I set max_bins to 2), which is not what I observed for the first model (trained on the first dataset). Is this the expected behaviour? If my expectation is wrong, would you have an explanation? I tried to read the C code but I have trouble to understand it since I have not used it for many years.

In the following example, I trained 2 models on two datasets with a single numerical feature. The second dataset is simply shifted.

## Reproducible example
```
# packages
import numpy as np
import lightgbm
from lightgbm import LGBMClassifier
print(np.__version__)  # 1.21.5
print(lightgbm.__version__)  # 3.3.1

# datasets
np.random.seed(2)
m = 1000
X = np.random.normal(size=(m, 1), loc=1, scale=1)
y = np.random.choice(["Y", "N"], size=m, p=[0.2, 0.8])
X_shifted = X - np.median(X)

# models
kwargs = {"n_estimators": 1, "max_bins": 2}
model_x = LGBMClassifier(**kwargs)
model_x.fit(X, y)
model_x_shifted = LGBMClassifier(**kwargs)
model_x_shifted.fit(X_shifted, y)

# comparison
comparison = (model_x.predict_proba(X) == model_x_shifted.predict_proba(X_shifted))
print(comparison.all())  # False

print(model_x._Booster.dump_model()["tree_info"][0]["tree_structure"]["threshold"])  # -1.0000000180025095e-35
print(np.sum(X[:,0]<=model_x._Booster.dump_model()["tree_info"][0]["tree_structure"]["threshold"]))  # 174
print(model_x_shifted._Booster.dump_model()["tree_info"][0]["tree_structure"]["threshold"])  # -1.0000000180025095e-35
print(np.sum(X_shifted[:,0]<=model_x_shifted._Booster.dump_model()["tree_info"][0]["tree_structure"]["threshold"]))  # 500
```

## Environment info

LightGBM version or commit hash: 3.3.1

Command(s) you used to install LightGBM

```shell
pip install lightgbm
```

**Comment by mayer79** [comment]
I *think* LGB uses 0 as fixed binning position. So if you shift x or take log, this can affect the fit. I can't find a reference for this, so it would be good if one of the core developers could clarify.

**Comment by jmoralez** [comment]
As pointed out by @shiyu1994 in https://github.com/microsoft/LightGBM/issues/4682#issuecomment-948287182 there's always a bin for missing values and a bin for zero, so using `max_bin=2` allows for only those two bins to exist. This isn't obvious and there's already a request in #4757 to clarify the bin construction procedure.

Using your example with some data that defines an obvious split and setting `max_bin=3` you can see that split point is chosen when shifting the data.

```python
# packages
import numpy as np
import lightgbm
from lightgbm import LGBMClassifier
print(np.__version__)  # 1.21.5
print(lightgbm.__version__)  # 3.3.1

# datasets
X = np.linspace(-1, 1, 100).reshape(-1, 1)
y = (X[:, 0] < 0).astype(int)  # best split is 0
X_shifted = X + 1  # best split is 1

kwargs = {"n_estimators": 1, "max_bins": 3}
model_x = LGBMClassifier(**kwargs)
model_x.fit(X, y)
model_x_shifted = LGBMClassifier(**kwargs)
model_x_shifted.fit(X_shifted, y)

info_cols = ['node_index', 'left_child', 'right_child', 'split_feature', 'threshold', 'decision_type', 'value', 'count']
model_x.booster_.trees_to_dataframe()[info_cols]
```

| node_index   | left_child   | right_child   | split_feature   |   threshold | decision_type   |   value |   count |
|:-------------|:-------------|:--------------|:----------------|------------:|:----------------|--------:|--------:|
| 0-S0         | 0-L0         | 0-L1          | Column_0        |       1e-35 | <=              |     0   |     100 |
| 0-L0         |              |               |                 |     nan     |                 |     0.2 |      50 |
| 0-L1         |              |               |                 |     nan     |                 |    -0.2 |      50 |

```python
model_x_shifted.booster_.trees_to_dataframe()[info_cols]
```
| node_index   | left_child   | right_child   | split_feature   |   threshold | decision_type   |     value |   count |
|:-------------|:-------------|:--------------|:----------------|------------:|:----------------|----------:|--------:|
| 0-S0         | 0-L0         | 0-L1          | Column_0        |      1.0202 | <=              |  0        |     100 |
| 0-L0         |              |               |                 |    nan      |                 |  0.192157 |      51 |
| 0-L1         |              |               |                 |    nan      |                 | -0.2      |      49 |

In this case the second split isn't exactly 1, which produces slightly different results. I also observed this in https://github.com/microsoft/LightGBM/issues/4500#issuecomment-891514772 and I'm not sure of the reason behind it, might be worth investigating further.

**Comment by kapytaine** [comment]
@jmoralez thank you for the clear answer, all the links and the example.
