### ISSUE TITLE
[python-package] [tests] FutureWarning: load_boston will be removed in scikit-learn 1.2.

### ISSUE THREAD

**Issue by TremaMiguel** [microsoft/LightGBM#4910]
## Description

Scikit-learn `load_boston` function will be removed in future version. 

```
FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.
```

python-package tests `test_engine.py`, `test_plotting.py`, and `test_sklearn.py` uses boston dataset. Some of this tests have already been changed in #4895 

## Solution

Tests should be changed to another available regression dataset like [load_diabetes](https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_diabetes.html#sklearn.datasets.load_diabetes) or use proposed [synthetic regression dataset](https://github.com/microsoft/LightGBM/blob/master/tests/python_package_test/utils.py#L115).

**Comment by TremaMiguel** [comment]
I'm open to develop this once there is an agreement on which dataset to use.

**Comment by StrikerRUS** [comment]
@TremaMiguel  Thanks a lot for bringing this to our attention! But we have already created an issue for this problem: #4793. Please let's continue discussion there.

**Comment by gargargargarden** [comment]
it's just a version issue ,just don't bother

**Comment by jameslamb** [comment]
> just don't bother

To be clear, for anyone finding this from search...LightGBM absolutely needs to fix this issue and remove uses of `load_boston()`, so that it can be tested in environments with `scikit-learn>=1.2`.

**Comment by mahmuudtolba** [comment]
just use the one on kaggle https://www.kaggle.com/datasets/vikrishnan/boston-house-prices

**Comment by jameslamb** [comment]
> 
just use the one on kaggle https://www.kaggle.com/datasets/vikrishnan/boston-house-prices


Since this is the second comment like this, I'm locking this thread. To be clear:

* there are ethical problems with the `boston` housing dataset
* LightGBM's tests no longer rely on the `boston` housing dataset, and that's not going to change
