### ISSUE TITLE
OSError: exception: access violation writing 0x0000000000000000

### ISSUE THREAD

**Issue by beast331** [microsoft/LightGBM#4912]
## Description
I have a large training dataset (44 million rows, 9 columns). When I pass it into LightGBM and run the fit method, it throws this error. 
The code I used is below. It's very short and fairly simple. 

## Reproducible example
import lightgbm as lbm
model = lbm.LGBMClassifier(learning_rate=0.2,max_depth=-5,random_state=42)
model.fit(X, y, verbose=1)

## Environment info
Running a Windows 10 with 8GB ram. Using Anaconda and Jupyter notebook. 

LightGBM version or commit hash:
LightGBM version 3.3.1

Command(s) you used to install LightGBM - I used a couple of different commands to try and fix the issue. All install commands were run through Jupyter notebook

```shell
!{sys.executable} -m pip install lightgbm
pip install --no-binary :all: lightgbm
```

**Comment by shiyu1994** [comment]
@beast331 Thanks for using LightGBM. Is it possible to share the data with us, so that we can reproduce the error?

**Comment by beast331** [comment]
> @beast331 Thanks for using LightGBM. Is it possible to share the data with us, so that we can reproduce the error?

Hi thanks for the quick reply! Is there somehow I can upload the CSV file here?

Also, I decided to try the "train" function instead of "fit" and it seems to be working. What is the difference?

**Comment by shiyu1994** [comment]
Not sure whether GitHub has a limitation of the attached file size. You may send that to my email shiyu_k1994@qq.com as well. Thanks!
