### ISSUE TITLE
[python-package] [docs]: weights params description should read weights should be non-negative

### ISSUE THREAD

**Issue by TremaMiguel** [microsoft/LightGBM#4921]
## Description

Following conversation on PR #4894, any method using `weight` parameter should describe the following 

> Weight should be non-negative values because the Hessian value multiplied by weight is supposed to be non-negative.

**Comment by jameslamb** [comment]
Thanks for writing this up @TremaMiguel . In the future, when referencing a particular comment thread please provide a link directly to it: https://github.com/microsoft/LightGBM/pull/4894#discussion_r774379923. There are many resolved conversations on #4894 and it might be difficult to figure out which conversation on that PR this issue's description refers to.

Are you interested in opening a pull request with this addition to the documentation?

**Comment by StrikerRUS** [comment]
@jameslamb 
> Are you interested in opening a pull request with this addition to the documentation?

I believe answer is
> yes, once this PR is done.
   https://github.com/microsoft/LightGBM/pull/4894#discussion_r776783414

**Comment by akshitadixit** [comment]
Hi is this issue available to work on?

**Comment by jameslamb** [comment]
thanks for the interest @akshitadixit ! But based on the comment above, I think @TremaMiguel wanted to do this.

**Comment by akshitadixit** [comment]
Okay no worries

**Comment by TremaMiguel** [comment]
Ok @jameslamb I'll start working on this. Thanks for the reminder.
