### ISSUE TITLE
[python-package] record_evaluation callback doesn't work with cv function

### ISSUE THREAD

**Issue by jmoralez** [microsoft/LightGBM#4943]
## Description

The `record_evaluation` callback fails when trying to use it with the `cv` function. Since some integrations that log metrics may use that callback to save the training information and the `cv` function is very useful to do hyperparameter tuning I believe these two should work together.

## Reproducible example

```python
import lightgbm as lgb
import numpy as np

X = np.random.rand(100, 2)
y = np.random.rand(100)
ds = lgb.Dataset(X, y)
params = {'objective': 'l2', 'num_leaves': 5, 'verbose': -1}
eval_result = {}
callbacks = [lgb.record_evaluation(eval_result)]
bst = lgb.train(params, ds, num_boost_round=2, valid_sets=[ds], callbacks=callbacks)
print(eval_result)
# {'training': OrderedDict([('l2', [0.08664710410521784, 0.08580684200793261])])}

eval_result = {}
callbacks = [lgb.record_evaluation(eval_result)]
cv_hist = lgb.cv(
    params, ds, num_boost_round=2, stratified=False, callbacks=callbacks, eval_train_metric=True
)
# Traceback (most recent call last):
#   File "record_eval.py", line 14, in <module>
#     cv_hist = lgb.cv(params, ds, stratified=False, callbacks=callbacks)
#   File "/hdd/github/LightGBM/python-package/lightgbm/engine.py", line 582, in cv
#     cb(callback.CallbackEnv(model=cvfolds,
#   File "/hdd/github/LightGBM/python-package/lightgbm/callback.py", line 140, in _callback
#     _init(env)
#   File "/hdd/github/LightGBM/python-package/lightgbm/callback.py", line 134, in _init
#     for data_name, eval_name, _, _ in env.evaluation_result_list:
# ValueError: too many values to unpack (expected 4)
```
This can be easily fixed by capturing the extra content from `env.evaluation_result_list` with `*_` here: https://github.com/microsoft/LightGBM/blob/4aaeb22932b72aaff632b40ba596ca2533071ca2/python-package/lightgbm/callback.py#L134 and here: https://github.com/microsoft/LightGBM/blob/4aaeb22932b72aaff632b40ba596ca2533071ca2/python-package/lightgbm/callback.py#L141
which would yield:
`{'cv_agg': OrderedDict([('train l2', [0.06319766819578873, 0.06253713563921684]), ('valid l2', [0.06679350623951755, 0.06694167044391186])])}`

## Environment info

LightGBM version or commit hash: db045f40305dfeae0b1dcff0658dbaa172dcab37

## Additional Comments

I'm happy to make the described changes if other maintainers agree with my solution.

**Comment by StrikerRUS** [comment]
Ah, I remember we had a similar problem in `early_stopping` callback: #2209 and had to split that string.
https://github.com/microsoft/LightGBM/blob/4aaeb22932b72aaff632b40ba596ca2533071ca2/python-package/lightgbm/callback.py#L281-L282
I believe we should preserve the nested structure of resulting dictionery in which we have dataset names at the first level and metric names at the second one, e.g.
```
{
  'cv_agg':
    {
      'train':
        {
          'l2': [0.06319766819578873, 0.06253713563921684]
        },
          'valid':
        {
          'l2': [0.06679350623951755, 0.06694167044391186]
        }
    }
}
```

**Comment by jmoralez** [comment]
I agree with preserving the structure but I think the `cv_agg` key doesn't provide much value, maybe we could drop it?

**Comment by StrikerRUS** [comment]
> ... maybe we could drop it?

Yeah, for sure!
