### ISSUE TITLE
[question] Understanding num_leaves parameter

### ISSUE THREAD

**Issue by simpsus** [microsoft/LightGBM#4944]
If lightGBM uses binary trees, is the max number of leaves not limited to` 2**max_depth`?
If so, is the num_leaves parameter only used to force not using all available leaves? What would be a motivation?
The standard is 31. With max_depth standard 5 and `2**5 == 32` this makes sense. But why 31 and not 32? 
Would it not make sense to set the standard to `2**max_depth` and not a fixed value?

Thank you very much!

**Comment by Nitinsiwach** [comment]
Yes, it is nodes. If you go through the link I have added for your reference you will find this line ```The num_leaves parameter sets the maximum number of nodes per tree.```

**Comment by jmoralez** [comment]
I believe that statement in the docs meant to be terminal nodes. Take this example:
```python
import lightgbm as lgb
import numpy as np

X = np.linspace(-1, 1, 100).reshape(-1, 1)
y = X[:, 0] ** 2
ds = lgb.Dataset(X, y)
params = {'objective': 'l2', 'num_leaves': 15, 'min_child_samples': 1}
bst = lgb.train(params, ds, num_boost_round=1)
trees_df = bst.trees_to_dataframe()
print(trees_df.shape[0]) # 29 (number of nodes)
print(trees_df['left_child'].isnull().sum())  # 15 (number of leaves or terminal nodes)
```

**Comment by simpsus** [comment]
I would agree to @jmoralez statement, and looking at the "Leaf wise growth" illustration in the link provided by @Nitinsiwach I think it means leaves at any point in time, some of those leaves will become inner nodes by the addition of more nodes. I do not think that there are aliases like max_leaves, max_leaf, max_leaf_nodes when the parameter is affecting all nodes. 

I close this issue, thank you for all your comments.

**Comment by Nitinsiwach** [comment]
Did this answer why the num_leaves is 31 and not 32?

**Comment by simpsus** [comment]
I think so, because my mistake was assuming the max_depth is default 5. It is not, actually it is not limited by default, so it does not make sense to try to connect the default values of max_depth and num_leaves.
As with depth-first growth and unlimited depth it is unlikely to growth balanced trees, assuming it would be 32 is pointless.
