### ISSUE TITLE
[ci] [docs] readthedocs configuration options are deprecated

### ISSUE THREAD

**Issue by jameslamb** [microsoft/LightGBM#4954]
## Description

This project uses readthedocs to build and host its documentation at https://lightgbm.readthedocs.io/en/latest/.

The way those docs are built is configured here: https://github.com/microsoft/LightGBM/blob/4aaeb22932b72aaff632b40ba596ca2533071ca2/.readthedocs.yaml#L1-L14

According to the documentation for that service, some of the configuration options used in this project's `.readthedocs.yaml` are deprecated.

*python.version* ([link](https://docs.readthedocs.io/en/stable/config-file/v2.html#python-version))

> This option is now deprecated and replaced by [build.tools.python](https://docs.readthedocs.io/en/stable/config-file/v2.html#build-tools-python). See [python.version (legacy)](https://docs.readthedocs.io/en/stable/config-file/v2.html#python-version-legacy) for the description of this option.

According to https://docs.readthedocs.io/en/stable/config-file/v2.html#python-version-legacy, using `version: 3` is also deprecated.

> Make sure to use quotes `(")` to make it a string. We previously supported using numbers here, but that approach is deprecated.

## Additional Comments

These deprecated configuration should be removed, so that documentation builds don't break when those features are removed in future changes to the readthedocs service.

Given the discussion in #4948, I think this should be accomplished by switching the project's readthedocs builds to use `mamba`, as documented at "Making builds faster with mamba" ([RTD docs link](https://docs.readthedocs.io/en/stable/guides/conda.html#making-builds-faster-with-mamba)).

**Comment by jameslamb** [comment]
Linking some relevant discussions showing support for `mamba` on RTD added a few months ago.

* https://github.com/readthedocs/readthedocs.org/pull/8453
* https://github.com/readthedocs/readthedocs.org/issues/7239

**Comment by akshitadixit** [comment]
Hi @jameslamb is this available to work on?

**Comment by jameslamb** [comment]
Thanks for your interest @akshitadixit ! But no, #4957 (linked above) is already addressing this.
