### ISSUE TITLE
python import error

### ISSUE THREAD

**Issue by brucebismarck** [Microsoft/LightGBM#496]
Problem: I followed https://github.com/Microsoft/LightGBM/blob/master/docs/GPU-Windows.md this method to install lightgbm in my windows computer (GPU) for python using. All things went well. But when I import it, python reported an OS error.

I found this problem also occurred in xgboost https://github.com/dmlc/xgboost/issues/908. They closed that issue by install python 64bit version. However, my python is 64 bit, but still reported this error.

Operating System: Windows 10
CPU: Intel 6700k
GPU GTX 1060
Python: Python 3.5.2 |Anaconda 4.2.0 (64-bit)| (default, Jul  5 2016, 11:41:13) [MSC v.1900 64 bit (AMD64)] on win32

## Environment info
Operating System:
CPU:
C++/Python/R version:

## Error Message:
>>> import lightgbm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\bruce\Anaconda3\lib\site-packages\lightgbm-0.1-py3.5.egg\lightgbm\__init__.py", line 9, in <module>
    from .basic import Booster, Dataset
  File "C:\Users\bruce\Anaconda3\lib\site-packages\lightgbm-0.1-py3.5.egg\lightgbm\basic.py", line 31, in <module>
    _LIB = _load_lib()
  File "C:\Users\bruce\Anaconda3\lib\site-packages\lightgbm-0.1-py3.5.egg\lightgbm\basic.py", line 26, in _load_lib
    lib = ctypes.cdll.LoadLibrary(lib_path[0])
  File "C:\Users\bruce\Anaconda3\lib\ctypes\__init__.py", line 425, in LoadLibrary
    return self._dlltype(name)
  File "C:\Users\bruce\Anaconda3\lib\ctypes\__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 is not a valid Win32 application

**Comment by guolinke** [comment]
@brucebismarck 
can you try using msvc build: https://github.com/Microsoft/LightGBM/wiki/Installation-Guide#windows-2
I think you build a 32-bit MinGW version.

**Comment by brucebismarck** [comment]
Yes, I built with 32-bit MinGW.

I tried to use msvc to build, but  when I run cmake -DCMAKE_GENERATOR_PLATFORM=x64 -DUSE_GPU=1 .. in the command line, it says

C:\Users\bruce\LightGBM\build>cmake -DCMAKE_GENERATOR_PLATFORM=x64 -DUSE_GPU=1 ..
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:8 (PROJECT):
  No CMAKE_C_COMPILER could be found.
CMake Error at CMakeLists.txt:8 (PROJECT):
  No CMAKE_CXX_COMPILER could be found.
-- Configuring incomplete, errors occurred!
See also "C:/Users/bruce/LightGBM/build/CMakeFiles/CMakeOutput.log".
See also "C:/Users/bruce/LightGBM/build/CMakeFiles/CMakeError.log".


I am really a green hand in these things, any suggestions?

**Comment by guolinke** [comment]
Did you have visual studio on your windows ?

**Comment by brucebismarck** [comment]
I do have visual studio, and I will try to build with 64bit MinGW tomorrow. Thanks!

**Comment by brucebismarck** [comment]
Hi Guolin, 

I found my problem is because I am using static version rather than a dynamic version of the library. But not the problem of 32bit or 64bit I guess. 

The problem diagnostics is described here.
http://catherineh.github.io/programming/2016/07/07/troubleshooting-windows-dll-imports-in-python

Do you know how to compile it to a dynamic version? Or which step is the most suspicious step made me get a static version?
I tried to use visual studio method,

**Comment by Laurae2** [comment]
@brucebismarck Can you provide the following?:

* run this in a console to get the Python version: `python -V`
* PATH environment variable full content

Which method did you use?

* If MinGW, then you must compile Boost with the identical MinGW used to compile LightGBM
* If Visual Studio, either use precompiled binaries (recommended) or use the identical Visual Studio compiler used to compile LightGBM/

**Comment by brucebismarck** [comment]
Sure! 

Python 3.5.2 :: Anaconda 4.2.0 (64-bit) (Because I am using keras, so I did not update python to 3.6)
PATH
C:\ProgramData\Oracle\Java\javapath;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\libnvvp;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;%USERPROFILE%\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;E:\Program Files\MATLAB\R2016b\runtime\win64;E:\Program Files\MATLAB\R2016b\bin;E:\Program Files\MiKTeX 2.9\miktex\bin\x64\;C:\Program Files\nodejs\;C:\Program Files\PuTTY\; 
**C:\Program Files\Git\cmd;C:\Program Files (x86)\mingw-w64\i686-6.3.0-posix-dwarf-rt_v5-rev2\mingw32\bin;C:\Program Files\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev2;C:\Program Files\boost\boost-build\bin;C:\Program Files\boost\boost-build\include\boost**

I used MinGW and followed this tutorial https://github.com/Microsoft/LightGBM/blob/master/docs/GPU-Windows.md
The only difference is that in the Boost compilation, under c/boost/, I do not have 'lib' and 'share' folder as shown in the tutorial.

**Comment by guolinke** [comment]
@brucebismarck can you try latest commit ?

**Comment by brucebismarck** [comment]
@guolinke  I git cloned it again, but it reported the same error. 

File "C:\Users\bruce\Anaconda3\lib\ctypes\__init__.py", line 425, in LoadLibrary
    return self._dlltype(name)
File "C:\Users\bruce\Anaconda3\lib\ctypes\__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)

**Comment by guolinke** [comment]
@brucebismarck 
can you remove ```C:\Program Files (x86)\mingw-w64\i686-6.3.0-posix-dwarf-rt_v5-rev2\mingw32\bin;`` from your path?

**Comment by brucebismarck** [comment]
@guolinke  Cool!!!! I made it!!!! Thanks a lot guolin!
