### ISSUE TITLE
Count number of leaves in the final ensemble

### ISSUE THREAD

**Issue by samanemami** [microsoft/LightGBM#4969]
## Summary

During the training, the model builds a decision tree regressor with a different number of leaves.

The question here is that each tree has how many leaves?

## Motivation
To compare the lightGBM model size with different models such as XGBoost

We can check the size of the model

## Description

The model already has the dump method, is there any feature to return the leaves from the dumped model?

**Comment by StrikerRUS** [comment]
Hey @samanemami, thanks for using LightGBM!

You can count number of leaves with the help of `trees_to_dataframe()` method which parses a dumped model for you.
https://github.com/microsoft/LightGBM/issues/4944#issuecomment-1011201077

**Comment by samanemami** [comment]
Thank you @StrikerRUS
