### ISSUE TITLE
Something is wrong with the portability of lightGBM between python and R

### ISSUE THREAD

**Issue by flippercy** [microsoft/LightGBM#4991]
Hi @jameslamb, @shiyu1994, @StrikerRUS:

I just noticed an issue with the portability of lightgbm models between python and R. There was no such issue as late as Dec. 2021 so I suspect it is due to some recent upgrades.

Specifically, when I built a lightgbm model in python, saved the booster as a model file and then loaded it in R using lgb.load() from the R library, the behavior of the model changed. For example, I used the pima indians diabetes data at Kaggle (https://www.kaggle.com/uciml/pima-indians-diabetes-database) to build a simple lightgbm model with the default parameters in python first and checked its prediction on the modeling data:

import lightgbm as lgb
import pandas as pd
data_diabetes=pd.read_csv('/data/home/diabetes.csv')
predictors_to_consider=["Pregnancies", "Glucose", "BloodPressure", "SkinThickness", "Insulin", "BMI", "DiabetesPedigreeFunction", "Age"]
targetvariable=["Outcome"]
X_train=data_diabetes[data_diabetes.columns.intersection(predictors_to_consider)]
y_train=data_diabetes[data_diabetes.columns.intersection(targetvariable)].values.ravel()
clf = lgb.LGBMClassifier()
clf.fit(X_train, y_train)
clf._Booster.save_model('/data/home/best_lgbm_test')
clf.predict_proba(X_train)[:50,1]

array([9.10814314e-01, 1.43603829e-02, 9.38999460e-01, 4.22573637e-03,
       9.51802788e-01, 2.79330573e-03, 8.71726550e-01, 2.66937649e-01,
       9.84464036e-01, 8.30263346e-01, 3.03920524e-03, 9.91787501e-01,
       6.68660475e-02, 9.42786246e-01, 9.45174336e-01, 8.94270968e-01,
       9.02935202e-01, 9.55209642e-01, 1.93975502e-02, 9.24372837e-01,
       2.03089845e-02, 9.00449011e-02, 9.64529639e-01, 9.41826314e-01,
       9.54141968e-01, 8.84774454e-01, 9.26958259e-01, 1.09877844e-04,
       2.91525644e-02, 7.27040687e-02, 1.65254473e-01, 9.52672011e-01,
       1.75877790e-03, 1.87055317e-04, 1.47215695e-01, 3.28143745e-02,
       1.42721580e-01, 9.62330093e-01, 8.34390573e-01, 8.22648228e-01,
       2.00530109e-01, 1.94591653e-01, 3.72958458e-03, 9.88935169e-01,
       1.78609115e-01, 9.64550359e-01, 9.91923743e-02, 2.62673405e-03,
       9.40098588e-01, 4.40577651e-02])

Everything looks correct. Then I loaded the model in RStudio using the lightgbm R package and used it to score the exactly same modeling data (below are R codes):

model.lgbm <- lgb.load(filename='/data/home/best_lgbm_test')
model.data <- read.csv('/data/home/diabetes.csv')
model.data.lgb <- as.matrix(model.data[, 1:50])
predict(model.lgbm, model.data.lgb)
 [1] 0.5743202 0.3371747 0.6527197 0.3946316 0.6741911 0.3305872 0.5498595 0.5132993 0.6932124 0.5106016 0.3213856 0.7621632
[13] 0.3867050 0.6218742 0.6364434 0.6451677 0.5727645 0.6295622 0.3856371 0.5606471 0.3986027 0.3967512 0.7090362 0.5722322
[25] 0.6975422 0.6516545 0.6473985 0.2462471 0.3655242 0.4726768 0.5511087 0.6955833 0.2502115 0.2793609 0.4793841 0.4471168
[37] 0.4852715 0.6275293 0.5155178 0.6436254 0.5074005 0.5209218 0.3384884 0.7252188 0.5115217 0.6420615 0.4882979 0.3211548
[49] 0.5755094 0.4344007

As shown above, the result is totally different from what I got in python.

Is it a bug or did I miss anything? Such procedures have been used for a long time and I never had this issue before.

Thank you.

**Comment by jmoralez** [comment]
I can't reproduce the issue. Are you predicting on the same data? The R one says `model.test.data` instead of `model.data`.

There could also be a version mismatch, which versions do you have on each language? I tried 3.3.1 on both.

**Comment by flippercy** [comment]
@jmoralez sorry 'model.test.data' is a typo; it should be 'model.data' so the data is exactly the same.

Let me check on the version; however, must I use the same version in both environments?

**Comment by flippercy** [comment]
@jmoralez:

Updates: previously the version of my python lightgbm library was 2.3.1, which was quite old; after upgrading it to 3.3.2, the issue disappeared.

So it is a version mismatch. Thank you very much for the help!
