### ISSUE TITLE
version `GLIBCXX_3.4.18' not found

### ISSUE THREAD

**Issue by samoidev** [microsoft/LightGBM#4998]
## Description
I'm trying to install and use lightgbm package in python, but it seems like there is a version conflict related to gcc.

After installing the package, using pip install lightgbm, when trying to import it, the following error appear:

```
>>>import lightgbm

OSError: /usr/company/pkgs/gcc/4.7.2/lib64/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by /nfs/user/.venv_notebook/lib/python3.7/site-packages/lightgbm/lib_lightgbm.so
```

Although I have other versions of GCC installed, I'm not sure how to make it use the appropriate version it needs.

```
ls /usr/company/pkgs/gcc/

10.1.0  10.3.0  11.1.0  4.7.2  4.8.1  4.9.2  5.3.0  6.2.0  6.3.0b  6.4.0  6.5.0  7.2.0  8.2.0  8.3.0  9.1.0  9.2.0
```

## Environment info

LightGBM version or commit hash: 3.3.2

Command(s) you used to install LightGBM : 

```shell
pip install lightgbm
```

Linux machine (SUSE)

**Comment by guolinke** [comment]
it looks like a environment probelm. Following link may help
https://stackoverflow.com/questions/19386651/how-to-fix-usr-lib-libstdc-so-6-version-glibcxx-3-4-15-not-found
