### ISSUE TITLE
Override column names when saving LightGBM native model.

### ISSUE THREAD

**Issue by makquel** [microsoft/LightGBM#4999]
## Summary

When dumping a lgbm native model (command below) the refered model object comes with a generic ordinal numeration for column names. 
```python
json.dumps(
    final_model.booster_.dump_model(
        num_iteration=-1, importance_type="gain"
   )
)
```
The JSON schema that comes from dumping the model looks like this:
```json
{
  "name": "tree",
  "version": "v3",
  "num_class": 1,
  "num_tree_per_iteration": 1,
  "label_index": 0,
  "max_feature_idx": 1816,
  "objective": "cross_entropy",
  "average_output": false,
  "feature_names": [
    "Column_0",
    "Column_1",
    ...
    "Column_1815",
    "Column_1816"
  ],
  "monotone_constraints": [],
  "feature_infos": {}
```
Would be very useful to have a native method to override features names to match exactly the ones used for training the model.

## Motivation

Using the native model as PMML format could facilitate integration with other platforms and even for those who implement a custom `.predict` function.

**Comment by jmoralez** [comment]
Hi @makquel, thank you for your interest in LightGBM. The features are saved in the same order they were used for training, i.e.:
```python
import lightgbm as lgb
import numpy as np

X = np.random.rand(100, 3)
y = np.random.rand(100)
ds = lgb.Dataset(X, y, feature_name=['x2', 'x0', 'x1'])
bst = lgb.train({'num_leaves': 3, 'verbose': -1}, ds, num_boost_round=1)
print(bst.dump_model()['feature_names'])
# ['x2', 'x0', 'x1'] 
```
 Are you able to provide a [minimal reproducible example](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) where this isn't the case?
