### ISSUE TITLE
Can't find executable lightgbm 

### ISSUE THREAD

**Issue by zyzhong** [Microsoft/LightGBM#5]
I follow the Installation Guide, and the compile success. But there is no lightgbm file, the CMakeLists.txt might have some problem?

**Comment by chivee** [comment]
@zyzhong , the default folder for binary file is the root folder, please double check weather is LightGBM in your root folder.

you can share your compiling log for further debug. i'll close the issue first, please feel free to reopen if the problem still in there.

**Comment by zyzhong** [comment]
Oh, it's the LightGBM file, maybe it should be put in bin/ somewhere

**Comment by guolinke** [comment]
@zyzhong It actually has name error in cmake. have fixed. you can pull latest code to build again.
Thanks very much.
