### ISSUE TITLE
OpenCL with Cuda under Windows

### ISSUE THREAD

**Issue by spedygiorgio** [Microsoft/LightGBM#501]
Hi All, I am following your tutorial to build the R package with MGCVWIN under windows. I have a NVIDA GPU graphics card so I downloaded the Cuda toolkit.
When building the development version of the package the following error raises to me: 

```
* installing *source* package 'lightgbm' ...
** libs
c:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-34~1.0/include" -DNDEBUG -I../..//include -I"C:/boost/boost-build/include" -I"C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0/include/CL" -I../compute/include -DUSE_SOCKET -DUSE_GPU=1    -I"d:/Compiler/gcc-4.9.3/local330/include"  -fopenmp -pthread -std=c++11   -O2 -Wall  -mtune=core2 -c lightgbm-all.cpp -o lightgbm-all.o
In file included from C:/boost/boost-build/include/boost/compute/config.hpp:16:0,
                 from C:/boost/boost-build/include/boost/compute/buffer.hpp:14,
                 from C:/boost/boost-build/include/boost/compute/core.hpp:18,
                 from ../../src/treelearner/gpu_tree_learner.h:27,
                 from ../../src/treelearner/parallel_tree_learner.h:8,
                 from ../../src/treelearner/data_parallel_tree_learner.cpp:1,
                 from lightgbm-all.cpp:31:
C:/boost/boost-build/include/boost/compute/cl.hpp:17:19: fatal error: CL/cl.h: No such file or directory
 #include <CL/cl.h>
                   ^
compilation terminated.
make: *** [lightgbm-all.o] Error 1
Warning: running command 'make -f "Makevars.win" -f "C:/PROGRA~1/R/R-34~1.0/etc/x64/Makeconf" -f "C:/PROGRA~1/R/R-34~1.0/share/make/winshlib.mk" CXX='$(CXX11) $(CXX11STD)' CXXFLAGS='$(CXX11FLAGS)' CXXPICFLAGS='$(CXX11PICFLAGS)' SHLIB_LDFLAGS='$(SHLIB_CXX11LDFLAGS)' SHLIB_LD='$(SHLIB_CXX11LD)' SHLIB="lightgbm.dll" WIN=64 TCLBIN=64 ' had status 2
ERROR: compilation failed for package 'lightgbm'
* removing 'D:/RPackages/lightgbm'
* restoring previous 'D:/RPackages/lightgbm'
```
I found the indicated files for OpenCL in the following dirs:

BOOST_INCLUDE_DIR = "C:/boost/boost-build/include"
BOOST_LIBRARY = "C:/boost/boost-build/lib"
OpenCL_INCLUDE_DIR = "C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0/include/CL"
OpenCL_LIBRARY = "C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0/lib/win32"

Any help will be appreciated

**Comment by Laurae2** [comment]
Use this for `OpenCL_INCLUDE_DIR`:

`OpenCL_INCLUDE_DIR = "C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0/include"`

Because LightGBM is looking for the folder/file `CL/cl.h`, in your case it was looking for `C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0/include/CL/CL/cl.h` (causing an error as it does not exist).

**Comment by spedygiorgio** [comment]
Well, it goes on but it throw the following error: 


* installing *source* package 'lightgbm' ...
** libs
c:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-34~1.0/include" -DNDEBUG -I../..//include -I"C:/boost/boost-build/include" -I"C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0/include" -I../compute/include -DUSE_SOCKET -DUSE_GPU=1    -I"d:/Compiler/gcc-4.9.3/local330/include"  -fopenmp -pthread -std=c++11   -O2 -Wall  -mtune=core2 -c lightgbm-all.cpp -o lightgbm-all.o
c:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-34~1.0/include" -DNDEBUG -I../..//include -I"C:/boost/boost-build/include" -I"C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0/include" -I../compute/include -DUSE_SOCKET -DUSE_GPU=1    -I"d:/Compiler/gcc-4.9.3/local330/include"  -fopenmp -pthread -std=c++11   -O2 -Wall  -mtune=core2 -c lightgbm_R.cpp -o lightgbm_R.o
c:/Rtools/mingw_64/bin/g++ -shared -s -static-libgcc -o lightgbm.dll tmp.def ./lightgbm-all.o ./lightgbm_R.o -fopenmp -pthread -lws2_32 -liphlpapi -LC:/boost/boost-build/lib -lboost_filesystem -lboost_system -LC:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0/lib/win32 -lOpenCL -Ld:/Compiler/gcc-4.9.3/local330/lib/x64 -Ld:/Compiler/gcc-4.9.3/local330/lib -LC:/PROGRA~1/R/R-34~1.0/bin/x64 -lR
C:/Rtools/mingw_64/bin/../lib/gcc/x86_64-w64-mingw32/4.9.3/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0/lib/win32/OpenCL.lib when searching for -lOpenCL
C:/Rtools/mingw_64/bin/../lib/gcc/x86_64-w64-mingw32/4.9.3/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0/lib/win32/OpenCL.lib when searching for -lOpenCL
C:/Rtools/mingw_64/bin/../lib/gcc/x86_64-w64-mingw32/4.9.3/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0/lib/win32\OpenCL.lib when searching for -lOpenCL
C:/Rtools/mingw_64/bin/../lib/gcc/x86_64-w64-mingw32/4.9.3/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lOpenCL
collect2.exe: error: ld returned 1 exit status
no DLL was created


I have an NVIDIA Quadro M3000M cuda above, I used R 3.4 x 64 path below: C:\Program Files\Microsoft MPI\Bin\;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\SASHome\x86\SASFoundation\9.4\ets\sasexe;C:\Program Files\SASHome\Secure\ccme4;C:\Program Files\SASHome\x86\Secure\ccme4;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\PROGRA~1\IBM\SQLLIB\BIN;C:\PROGRA~1\IBM\SQLLIB\FUNCTION;C:\PROGRA~1\IBM\SQLLIB\SAMPLES\REPL;C:\Program Files\Anaconda3;C:\Program Files\Anaconda3\Scripts;C:\Program Files\Anaconda3\Library\bin;C:\Program Files\Git\cmd;C:\Program Files\MiKTeX 2.9\miktex\bin\x64\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Plantronics\Spokes3G\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files\dotnet\;C:\Program Files (x86)\Xoreax\IncrediBuild;C:\Program Files\Java\jdk1.8.0_121\bin;C:\Users\UGA04625\AppData\Local\rstudio\spark\Cache\spark-2.0.1-bin-hadoop2.7\bin;C:\Rtools\bin;c:\Rtools\mingw_64\bin;C:\Program Files\qpdf-6.0.0\bin;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\CMake\bin;C:\boost\boost-build\bin;C:\boost\boost-build\include\boost

**Comment by spedygiorgio** [comment]
fixed this steps thanks. By the way I suggest to add some reverences to NVIDIA cuda in the docs.

G
