### ISSUE TITLE
how do I sub-class lightgbm.sklearn estimators and add new parameters?

### ISSUE THREAD

**Issue by psyntelis** [microsoft/LightGBM#5010]
## Description

Hi. I was trying to subclass the LGBMRegressor calls to create a customer training pipeline. To do so, I followed the discussion [here](https://github.com/microsoft/LightGBM/issues/3758) on how to do it. This discussion pointed that passing new parameters to the new class should be done in `set_params` rather than `__init__`.

Doing so, leads to a warning error 
`
[LightGBM] [Warning] Unknown parameter: test_param
`
which cannot be suppressed using verbosity = -1

## Reproducible example
```
from lightgbm import LGBMRegressor
from copy import deepcopy
import numpy as np

class LGBMRegressorTest(LGBMRegressor):
    def set_params(self, test_param=2, **params):
        new_params = deepcopy(params)
        new_params["test_param"] = test_param
        super().set_params(**new_params)


def train_model():
    X = np.random.rand(10,5)
    model = LGBMRegressorTest(
        test_param=2,
        verbosity=-1
    )

    model.fit(X=X[:,0:4], y=X[:,4])
    
if __name__ == "__main__":
    train_model()

```

## Environment info

LightGBM version or commit hash: 3.3.2

Command(s) you used to install LightGBM

```shell
pip install lightgbm
```

**Comment by psyntelis** [comment]
Hi @jameslamb. Thank you for the fast and very detailed reply. Much approeciated!

The thing that confused me with using `__init__` was that I couldn't get the default parameters of the subclass to the new class.

For example, this:
```
from lightgbm import LGBMRegressor
from copy import deepcopy
import numpy as np

class LGBMRegressorTest(LGBMRegressor):
    def __init__(self, test_param=2, **kwargs):
        self.test_param=test_param
        super().__init__(**kwargs)

def train_model():
    X = np.random.rand(10,5)
    model = LGBMRegressorTest(
        test_param=2
    )

    print(model.get_params())
    
if __name__ == "__main__":
    train_model()
```

will print `{'test_param': 2}` rather than the full list of default parameters, with the addition of the `test_param`

Based on the dask.py script, what I am doing wrong here is that I should be setting all the default values to the new parent class, and not expect to get them for free through inheritance. Is that correct?

**Comment by StrikerRUS** [comment]
I just want to note that the root cause of 
> `[LightGBM] [Warning] Unknown parameter: test_param`
which cannot be suppressed using verbosity = -1

is the same as in #4518. Logging level is set **after** parameters parsing based on the parsed `verbosity` param value.

**Comment by psyntelis** [comment]
Thank you both for the replies. For completeness, I get the error even if I set the parameters at the `__init__` stage. Expanding on the example, I added `test_param` in `__init__` , along with the default values to avoid the inheritance issues, similar to the dask example:

```
from lightgbm import LGBMRegressor
from copy import deepcopy
import numpy as np

class LGBMRegressorTest(LGBMRegressor):
    def __init__(
            self, 
            test_param=2, 
            boosting_type= 'gbdt',
            num_leaves=31,
            max_depth= -1,
            learning_rate=0.1,
            n_estimators=100,
            subsample_for_bin=200000,
            objective=None,
            class_weight=None,
            min_split_gain=0.,
            min_child_weight=1e-3,
            min_child_samples=20,
            subsample=1.,
            subsample_freq=0,
            colsample_bytree=1.,
            reg_alpha=0.,
            reg_lambda=0.,
            random_state=None,
            n_jobs=-1,
            importance_type='split',
            **kwargs
        ):
        self.test_param = test_param
        super().__init__(
            boosting_type=boosting_type,
            num_leaves=num_leaves,
            max_depth=max_depth,
            learning_rate=learning_rate,
            n_estimators=n_estimators,
            subsample_for_bin=subsample_for_bin,
            objective=objective,
            class_weight=class_weight,
            min_split_gain=min_split_gain,
            min_child_weight=min_child_weight,
            min_child_samples=min_child_samples,
            subsample=subsample,
            subsample_freq=subsample_freq,
            colsample_bytree=colsample_bytree,
            reg_alpha=reg_alpha,
            reg_lambda=reg_lambda,
            random_state=random_state,
            n_jobs=n_jobs,
            importance_type=importance_type,
            **kwargs
         )

def train_model():
    X = np.random.rand(10,5)
    model = LGBMRegressorTest(
        test_param=2,
        verbosity=-1
    )

    print(model.get_params())

    model.fit(X=X[:,0:4], y=X[:,4])
    
if __name__ == "__main__":
    train_model()
```

Then, `print(model.get_params())` returns  to
```
{'boosting_type': 'gbdt', 'class_weight': None, 'colsample_bytree': 1.0, 'importance_type': 'split', 'learning_rate': 0.1, 'max_depth': -1, 'min_child_samples': 20, 'min_child_weight': 0.001, 'min_split_gain': 0.0, 'n_estimators': 100, 'n_jobs': -1, 'num_leaves': 31, 'objective': None, 'random_state': None, 'reg_alpha': 0.0, 'reg_lambda': 0.0, 'subsample': 1.0, 'subsample_for_bin': 200000, 'subsample_freq': 0, 'test_param': 2, 'verbosity': -1}
```
so, `test_param` has been assigned the value correctly.

However, I still get the same error message

`[LightGBM] [Warning] Unknown parameter: test_param`

**Comment by jameslamb** [comment]
> However, I still get the same error message

That warning is telling you that there is no LightGBM parameter called `test_param`. The LightGBM sklearn estimators expect that every keyword argument passed in the constructor is one of the core parameters recognized by LightGBM, listed at https://lightgbm.readthedocs.io/en/latest/.

Since `client`, for example, is not such a parameter, we had to take special care everywhere in the Dask interface to avoid passing it through to LightGBM's C++ library.

https://github.com/microsoft/LightGBM/blob/d31346f6c265e994c54ebddd19ed1fb6445ba0c9/python-package/lightgbm/dask.py#L1017-L1024

https://github.com/microsoft/LightGBM/blob/d31346f6c265e994c54ebddd19ed1fb6445ba0c9/python-package/lightgbm/dask.py#L1047-L1048

https://github.com/microsoft/LightGBM/blob/d31346f6c265e994c54ebddd19ed1fb6445ba0c9/python-package/lightgbm/dask.py#L1080

**Comment by psyntelis** [comment]
Thank you both! Much appreciate the detailed explanations.
