### ISSUE TITLE
cannot compile Boost properly (Windows 10; R)

### ISSUE THREAD

**Issue by slfan2013** [Microsoft/LightGBM#503]
My PATH has two related system paths
`c:\Rtools\bin` and `c:\Rtools\mingw_64\bin`.
I am working on the [Boost Compilation](https://github.com/Microsoft/LightGBM/blob/master/docs/GPU-Windows.md#boost-compilation) step.
Instead of 
- In command prompt, run `b2 install --prefix="C:\boost\boost-build" toolset=gcc`.

I ran
`b2 install --build_dir="C:\boost\boost-build" --prefix="C:\boost\boost-build" toolset=gcc --with=filesystem,system threading=multi --layout=system release -j 2`

From the page, the result folder structure should be like,
`
- C
  |--- boost
  |------ boost_1_63_0
  |--------- some folders and files
  |------ boost-build
  |--------- bin
  |--------- include
  |------------ boost
  |------ lib
  |------ share

But after my installation, the folder structure is 

- C
 |---boost
 |-----boost_1_63_0
 |--------- some folders and files
 |-----boost-build
 |--------- bin
 |------------b2.exe
 |------------bjam.exe
 |--------- share
 |------------boost-build
`

Why there is such a difference?
This difference makes it impossible to do the [R: final step](https://github.com/Microsoft/LightGBM/blob/master/docs/GPU-Windows.md#lightgbm-setup-and-installation-for-r-r-final-step) because there is no `"C:/boost/boost-build/lib"`

Thanks.

**Comment by spedygiorgio** [comment]
I have the same problem

**Comment by guolinke** [comment]
@Laurae2 can you help for this ?

**Comment by Laurae2** [comment]
@slfan2013 @spedygiorgio delete your `boost_1_63_0` and `boost-build` folders, and make sure to follow the steps carefully.

This includes:

* Setting the PATH before even starting a command prompt
* Changing folder for the last Boost compilation step so you don't have b2 in the current folder but you are in boost main directory (`C:\boost\boost_1_63_0`)

I tried to check this issue and it works correctly here.

![image](https://cloud.githubusercontent.com/assets/9083669/26015136/eb4f7048-375f-11e7-9c68-9313f4d30e49.png)

**Comment by slfan2013** [comment]
Thanks @Laurae2 
It worked. Maybe a numbered list would be better than a bulleted list for a newbie like me, who rarely use command prompt.

Thank you again.

**Comment by Laurae2** [comment]
@guolinke this issue is solved
