### ISSUE TITLE
eigen does not work

### ISSUE THREAD

**Issue by ysong2123** [microsoft/LightGBM#5038]
## Description

I found out that:
Eigen in [https://github.com/microsoft/LightGBM/tree/fix/r-windows-ci/external_libs](https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2FLightGBM%2Ftree%2Ffix%2Fr-windows-ci%2Fexternal_libs&data=04%7C01%7Cysong2%40paypal.com%7C3adb3c9d373a498d853708d9fa7dac8c%7Cfb00791460204374977e21bac5f3f4c8%7C0%7C0%7C637816240551678764%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C2000&sdata=SGdIN108SmHn0063E2Hhg4XgMrnnbg5Ln33mBtAUtfM%3D&reserved=0) is not reachable,   
and i can't  wget https://gitlab.com/libeigen/eigen either.

My goal:  wanted to  build lightgbm in my local, due to Mac Big Sur incompatible with latest lightgbm lib.
could you team help me on this?
## Environment info

LightGBM version or commit hash:

Command(s) you used to install LightGBM

```shell

```

**Comment by jameslamb** [comment]
Thanks for using LightGBM and for this report. Since you said your goal is "to build lightgbm in my local", can you please fill in the request information "Command(s) you used to install LightGBM"? You haven't told us, even, whether your are trying to build the CLI, Python package, R package, etc.

You should not be trying to build the `fix/r-windows-ci` branch from #5037 and you shouldn't need to "wget" Eigen.

Please see:
* Installation Guide ([link](https://lightgbm.readthedocs.io/en/latest/Installation-Guide.html)): instructions for compiling LightGBM
* Python README ([link](https://github.com/microsoft/LightGBM/blob/master/python-package/README.rst)): instructions for installing the Python package
* R README ([link](https://github.com/microsoft/LightGBM/blob/master/R-package/README.md)): instructions for installing the R package

**Comment by ysong2123** [comment]
my original plan is 'pip install lightgbm', assuming that everything will be ok afterwards.   but i got same issue when i tried to import lightgbm as lgb as below:
https://stackoverflow.com/questions/44937698/lightgbm-oserror-library-not-loaded
so, i keep researching and found out that we can build python package from source code.  But i got some issue in master branch(Eigen/fmt, .. can't be found)

**Comment by shiyu1994** [comment]
@ysong2123 Thanks for using LightGBM. Did you clone LightGBM repo directly with the master branch? Could you please try to execute the following command to see if the `eigen` submodule can be downloaded?
```
git submodule update --init
```

**Comment by jameslamb** [comment]
I'm closing this due to lack of response. @ysong2123 if you are still struggling with this issue, please comment here and we can re-open it and help you.

**Comment by LXlearning** [comment]
I also need deal this problem in Mac, can you update eigen

**Comment by jameslamb** [comment]
@LXlearning as I asked the original poster of this issue...please tell us what exactly you tried and what happened. "eigen does not work" is not enough information for us to help you.

**Comment by LXlearning** [comment]
> @LXlearning as I asked the original poster of this issue...please tell us what exactly you tried and what happened. "eigen does not work" is not enough information for us to help you.
I use this Installation Guide: [link](https://lightgbm.readthedocs.io/en/latest/Installation-Guide.html#macos) ,but there are  **OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443** error in git clone.
Then I download ZIP in https://github.com/microsoft/LightGBM to make.It show missing files about /external_libs/eigen. and I can't solve this problem when use  https://gitlab.com/libeigen/eigen.

**Comment by jameslamb** [comment]
If you ran the following

```shell
git clone --recursive https://github.com/microsoft/LightGBM.git
```

And got an error like

> OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443 error in git clone

then I suspect that the issue you're facing is not related to LightGBM at all. Maybe you're on a network that prevents cloning from GitHub? You could test that by running something like the following to clone a different repo.

```shell
git clone https://github.com/dmlc/xgboost.git
```

**Comment by LXlearning** [comment]
> :443 error in git clone

I know there are problems in git clone. So I try to download it to make but it failed

**Comment by jameslamb** [comment]
I guess you must be talking about the zip archive that you can get by clicking "Download Zip" at https://github.com/microsoft/LightGBM.

<img width="395" alt="image" src="https://user-images.githubusercontent.com/7608904/163831924-2ae36e32-de41-4633-b5a1-be1024fd8238.png">

GitHub does not fetch and bundle in git submodules when creating that zip archive.

If you want to build the package from source, you have two options:

* fix your local development environment such that `git clone --recursive https://github.com/microsoft/LightGBM.git` succeeds
* individually download the sources of each of LightGBM's submodules (https://github.com/microsoft/LightGBM/tree/master/external_libs) and place them in `external_libs/` at the root of the repo

If you just want to *use* (not develop and recompile) the latest version of a specific component of LightGBM, such as the Python or R package, you can try the nightly builds available from https://lightgbm.readthedocs.io/en/latest/Installation-Guide.html#installation-guide.

<img width="1460" alt="Screen Shot 2022-04-18 at 10 33 25 AM" src="https://user-images.githubusercontent.com/7608904/163832461-a6e9b75d-bceb-45c4-b507-35a5b367514d.png">

**Comment by StrikerRUS** [comment]
> GitHub does not fetch and bundle in git submodules when creating that zip archive.

Also, I'd like to add that we attach complete source code under each GitHub release, e.g.
https://github.com/microsoft/LightGBM/releases/tag/v3.3.2
![image](https://user-images.githubusercontent.com/25141164/164134245-e3a3b5a2-908b-42be-a959-64985aefb249.png)
