### ISSUE TITLE
LBGMRanker with Sklearn pipeline?

### ISSUE THREAD

**Issue by antaradas94** [microsoft/LightGBM#5041]
## Description

Hi all, i have been trying to use LGBRanker() model at the end of a sklearn pipeline. Along with that i am trying to implement hyper parameter search using Randomizedsearchcv from sklearn.  However, i couldnt get any meaningful results have stumbled upon  constantly the following error: 
raise LightGBMError(_LIB.LGBM_GetLastError().decode('utf-8'))
lightgbm.basic.LightGBMError: Sum of query counts is not same with #data 
![grafik](https://user-images.githubusercontent.com/29475679/156017163-dd3fab2c-1f12-44ba-ab87-9651e5a1b795.png)

Can someone help me point out what am i doing wrong here? Thanks 

## Reproducible example

        preprocessing_pipeline = FeatureUnion(
            transformer_list=[
                ("categorical_pipeline", categorical_pipeline),
                ("numerical_pipeline", numerical_pipeline),
            ]
        )
              sklearn_pipeline = Pipeline(
            steps=[
                ("preprocessing_pipeline", preprocessing_pipeline),
                ("model", LGBMRanker(objective="lambdarank")),
            ]
        )
        hyperparameters = {
            "model__min_child_weight": [0.5, 0.7, 1],
            "model__reg_alpha": [0, 5,10],
            "model__reg_lambda": [0, 5, 10],
            "model__subsample": [0.01, 1]
        }
        x_train = train.append(val)

        y_train = x_train.pop(self.target)

        fit_params = {
            "model__group": np.array([x_train.shape[0]]),
            "model__eval_metric": "ndcg"
        }

        split_index = np.array([-1] * len(train) + [0] * len(val))
        train_val_split = PredefinedSplit(test_fold=split_index)
        scorer = make_scorer(ndcg_score, greater_is_better=True)
        hyperparam_pipeline = RandomizedSearchCV(estimator=pipeline,
                                                 param_distributions=hyperparameters,
                                                 scoring=scorer,
                                                 cv=train_val_split
                                                 )
        ranker = hyperparam_pipeline.fit(x_train, y_train, **fit_params)

## Environment info

LightGBM version or commit hash:
i am using lightgbm version 3.3.1

Command(s) you used to install LightGBM

```shell
poetry add lightgbm

```

**Comment by StrikerRUS** [comment]
@antaradas94 Hey, sorry about the problem you are having!
Unfortunately, `LGBMRanker` isn't fully compatible with scikit-learn ecosystem because scikit-learn itself doesn't provide any ranking algorithms, and thus doesn't has an established API for rankers. Please refer to https://github.com/microsoft/LightGBM/issues/4664#issuecomment-939368082.

**Comment by antaradas94** [comment]
OK thanks for your reply. Isnt there any other workaround for this?

**Comment by StrikerRUS** [comment]
>  Isnt there any other workaround for this?

Unfortunately, there is no any one that I'm aware of.

> Or can we pass param grid to LGBRanker model itself?

Do you mean built-in hyper-opt mechanism in LightGBM? No.
