### ISSUE TITLE
A external repository : Multi-Tasks GBDT

### ISSUE THREAD

**Issue by antmachineintelligence** [microsoft/LightGBM#5047]
## Summary

We propose Multi-task Gradient Boosting Machine (MT-GBM), a GBDT-based method for multi-task learning. The MT-GBM can find the shared tree structures and split branches according to multi-task losses.  It can be widely used in realistic scenes.

We hope to add our repository here: https://github.com/microsoft/LightGBM#external-unofficial-repositories.  
Looking forward for your reply!

Repository: https://github.com/antmachineintelligence/mtgbmcode
Paper:https://arxiv.org/abs/2201.06239

**Comment by shiyu1994** [comment]
@antmachineintelligence Sure! It is very exciting to see a Multi-Task GBDT has been implemented based on LightGBM.

**Comment by jameslamb** [comment]
@antmachineintelligence thanks very much, it seems like an interesting project!

I have two questions I'd like to understand the answers to before we consider linking to this from LightGBM's documentation.

1. Will this project be actively maintained?
2. What is your plan for integrating with LightGBM?

Right now at https://github.com/antmachineintelligence/mtgbmcode I only see one branch, `main`, last updated around two months ago, which seems to be a fork of a fairly-old version of LightGBM.

For example, it still has the `compute/` folder with all of the Boost sources files (even its CI configs), something that was changed on `master` of `LightGBM` more than a year ago (#3809).

<img width="1253" alt="Screen Shot 2022-03-08 at 10 07 20 PM" src="https://user-images.githubusercontent.com/7608904/157370945-ebb4db14-66c2-4226-b964-712579173f90.png">

It contains an R package still named `lightgbm`, with Version 2.3.2 and only a few authors listed.

<img width="893" alt="image" src="https://user-images.githubusercontent.com/7608904/157371132-0ef7c67e-b068-4fe5-bd6f-c9952ad6698d.png">

These things make me worried that this project is something that was done as an experiment more than a year ago that won't be actively maintained. If that's true, I'd prefer not to direct LightGBM users to it.

**Comment by antmachineintelligence** [comment]
Hi, @jameslamb,
Thank you for your time! We are here because we hope to share this work with people who need it. 
We finished the work at version 2.3.2 and it seems to be a lot of work to do to keep up with the LightGBM. So we didn't maintain the repository actively. 
However, we are happy to help if you accept to merge this work into the LightGBM. Or we can update our code to the latest version if you wish.

**Comment by shiyu1994** [comment]
If MT-GBM uses single prediction values on the leaves (each leaf has only one prediction value.), I think it is possible to integrate it with LightGBM. I'm willing to help with that. But that will take some time.

**Comment by antmachineintelligence** [comment]
> If MT-GBM uses single prediction values on the leaves (each leaf has only one prediction value.), I think it is possible to integrate it with LightGBM. I'm willing to help with that. But that will take some time.

Our code is not graceful enough since we do not know the code architecture well. If you need any help please let me know.
Where shall we start to integrate it?

**Comment by jameslamb** [comment]
> Or we can update our code to the latest version if you wish.

The projects at https://github.com/microsoft/LightGBM#external-unofficial-repositories are expected to be at least somewhat actively-maintained and current.

If https://github.com/antmachineintelligence/mtgbmcode was created mainly for a paper but you don't intend to maintain it or encourage others to use it, I'd recommend that we link to the _paper_ somewhere else in LightGBM's documentation.

> Where shall we start to integrate it?

If you want to add new functionality to LightGBM, you are welcome to propose a pull request at https://github.com/microsoft/LightGBM/pulls. That would give maintainers a better understanding of the amount of complexity you are asking us to take responsibility for maintaining, and make it easier to to weigh that maintenance burden against the value of providing multi-task boosting as a part of this project instead of as a standalone project.

**Comment by antmachineintelligence** [comment]
> If you want to add new functionality to LightGBM, you are welcome to propose a pull request at https://github.com/microsoft/LightGBM/pulls. That would give maintainers a better understanding of the amount of complexity you are asking us to take responsibility for maintaining, and make it easier to to weigh that maintenance burden against the value of providing multi-task boosting as a part of this project instead of as a standalone project.

That is fine! We will push a merge asap.

**Comment by antmachineintelligence** [comment]
https://github.com/microsoft/LightGBM/pull/5111 
Here is the new pull request. 
:)

**Comment by jameslamb** [comment]
closing this due to lack of response. It should have been closed when #5111 was closed: https://github.com/microsoft/LightGBM/pull/5111#issuecomment-1157208351
