### ISSUE TITLE
error when compiling lightgbm + windows gpu (cuda)

### ISSUE THREAD

**Issue by spedygiorgio** [Microsoft/LightGBM#505]
I receive the following errors when compiling:

 installing *source* package 'lightgbm' ...
** libs
c:/Rtools/mingw_64/bin/g++ -shared -s -static-libgcc -o lightgbm.dll tmp.def ./lightgbm-all.o ./lightgbm_R.o -fopenmp -pthread -lws2_32 -liphlpapi -LC:/boost/boost-build/lib -lboost_filesystem -lboost_system -LC:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0/lib/x64 -lOpenCL -Ld:/Compiler/gcc-4.9.3/local330/lib/x64 -Ld:/Compiler/gcc-4.9.3/local330/lib -LC:/PROGRA~1/R/R-34~1.0/bin/x64 -lR
./lightgbm-all.o:lightgbm-all.cpp:(.text+0x2ff90): undefined reference to `LightGBM::GPUTreeLearner::GPUTreeLearner(LightGBM::TreeConfig const*)'
./lightgbm-all.o:lightgbm-all.cpp:(.text+0x300b2): undefined reference to `LightGBM::GPUTreeLearner::GPUTreeLearner(LightGBM::TreeConfig const*)'
./lightgbm-all.o:lightgbm-all.cpp:(.text$_ZN8LightGBM26FeatureParallelTreeLearnerINS_14GPUTreeLearnerEED1Ev[_ZN8LightGBM26FeatureParallelTreeLearnerINS_14GPUTreeLearnerEED1Ev]+0x3d): undefined reference to `LightGBM::GPUTreeLearner::~GPUTreeLearner()'
./lightgbm-all.o:lightgbm-all.cpp:(.text$_ZN8LightGBM23DataParallelTreeLearnerINS_14GPUTreeLearnerEED1Ev[_ZN8LightGBM23DataParallelTreeLearnerINS_14GPUTreeLearnerEED1Ev]+0xa3): undefined reference to `LightGBM::GPUTreeLearner::~GPUTreeLearner()'
./lightgbm-all.o:lightgbm-all.cpp:(.text$_ZN8LightGBM25VotingParallelTreeLearnerINS_14GPUTreeLearnerEE5SplitEPNS_4TreeEiPiS5_[_ZN8LightGBM25VotingParallelTreeLearnerINS_14GPUTreeLearnerEE5SplitEPNS_4TreeEiPiS5_]+0x22): undefined reference to `LightGBM::GPUTreeLearner::Split(LightGBM::Tree*, int, int*, int*)'
./lightgbm-all.o:lightgbm-all.cpp:(.text$_ZN8LightGBM23DataParallelTreeLearnerINS_14GPUTreeLearnerEE5SplitEPNS_4TreeEiPiS5_[_ZN8LightGBM23DataParallelTreeLearnerINS_14GPUTreeLearnerEE5SplitEPNS_4TreeEiPiS5_]+0x22): undefined reference to `LightGBM::GPUTreeLearner::Split(LightGBM::Tree*, int, int*, int*)'
./lightgbm-all.o:lightgbm-all.cpp:(.text$_ZN8LightGBM25VotingParallelTreeLearnerINS_14GPUTreeLearnerEED0Ev[_ZN8LightGBM25VotingParallelTreeLearnerINS_14GPUTreeLearnerEED0Ev]+0x1ac): undefined reference to `LightGBM::GPUTreeLearner::~GPUTreeLearner()'
./lightgbm-all.o:lightgbm-all.cpp:(.text$_ZN8LightGBM25VotingParallelTreeLearnerINS_14GPUTreeLearnerEED1Ev[_ZN8LightGBM25VotingParallelTreeLearnerINS_14GPUTreeLearnerEED1Ev]+0x1b3): undefined reference to `LightGBM::GPUTreeLearner::~GPUTreeLearner()'
./lightgbm-all.o:lightgbm-all.cpp:(.text$_ZN8LightGBM25VotingParallelTreeLearnerINS_14GPUTreeLearnerEE19BeforeFindBestSplitEPKNS_4TreeEii[_ZN8LightGBM25VotingParallelTreeLearnerINS_14GPUTreeLearnerEE19BeforeFindBestSplitEPKNS_4TreeEii]+0x1b): undefined reference to `LightGBM::GPUTreeLearner::BeforeFindBestSplit(LightGBM::Tree const*, int, int)'
./lightgbm-all.o:lightgbm-all.cpp:(.text$_ZN8LightGBM23DataParallelTreeLearnerINS_14GPUTreeLearnerEEC2EPKNS_10TreeConfigE[_ZN8LightGBM23DataParallelTreeLearnerINS_14GPUTreeLearnerEEC2EPKNS_10TreeConfigE]+0x9): undefined reference to `LightGBM::GPUTreeLearner::GPUTreeLearner(LightGBM::TreeConfig const*)'
./lightgbm-all.o:lightgbm-all.cpp:(.text$_ZN8LightGBM23DataParallelTreeLearnerINS_14GPUTreeLearnerEEC1EPKNS_10TreeConfigE[_ZN8LightGBM23DataParallelTreeLearnerINS_14GPUTreeLearnerEEC1EPKNS_10TreeConfigE]+0x9): undefined reference to `LightGBM::GPUTreeLearner::GPUTreeLearner(LightGBM::TreeConfig const*)'
./lightgbm-all.o:lightgbm-all.cpp:(.text$_ZN8LightGBM23DataParallelTreeLearnerINS_14GPUTreeLearnerEED2Ev[_ZN8LightGBM23DataParallelTreeLearnerINS_14GPUTreeLearnerEED2Ev]+0xa3): undefined reference to `LightGBM::GPUTreeLearner::~GPUTreeLearner()'
./lightgbm-all.o:lightgbm-all.cpp:(.text$_ZN8LightGBM26FeatureParallelTreeLearnerINS_14GPUTreeLearnerEEC2EPKNS_10TreeConfigE[_ZN8LightGBM26FeatureParallelTreeLearnerINS_14GPUTreeLearnerEEC2EPKNS_10TreeConfigE]+0x9): undefined reference to `LightGBM::GPUTreeLearner::GPUTreeLearner(LightGBM::TreeConfig const*)'
./lightgbm-all.o:lightgbm-all.cpp:(.text$_ZN8LightGBM26FeatureParallelTreeLearnerINS_14GPUTreeLearnerEEC1EPKNS_10TreeConfigE[_ZN8LightGBM26FeatureParallelTreeLearnerINS_14GPUTreeLearnerEEC1EPKNS_10TreeConfigE]+0x9): undefined reference to `LightGBM::GPUTreeLearner::GPUTreeLearner(LightGBM::TreeConfig const*)'
./lightgbm-all.o:lightgbm-all.cpp:(.text$_ZN8LightGBM26FeatureParallelTreeLearnerINS_14GPUTreeLearnerEED2Ev[_ZN8LightGBM26FeatureParallelTreeLearnerINS_14GPUTreeLearnerEED2Ev]+0x3d): undefined reference to `LightGBM::GPUTreeLearner::~GPUTreeLearner()'
./lightgbm-all.o:lightgbm-all.cpp:(.text$_ZN8LightGBM25VotingParallelTreeLearnerINS_14GPUTreeLearnerEEC2EPKNS_10TreeConfigE[_ZN8LightGBM25VotingParallelTreeLearnerINS_14GPUTreeLearnerEEC2EPKNS_10TreeConfigE]+0x9): undefined reference to `LightGBM::GPUTreeLearner::GPUTreeLearner(LightGBM::TreeConfig const*)'
./lightgbm-all.o:lightgbm-all.cpp:(.text$_ZN8LightGBM25VotingParallelTreeLearnerINS_14GPUTreeLearnerEEC1EPKNS_10TreeConfigE[_ZN8LightGBM25VotingParallelTreeLearnerINS_14GPUTreeLearnerEEC1EPKNS_10TreeConfigE]+0x9): undefined reference to `LightGBM::GPUTreeLearner::GPUTreeLearner(LightGBM::TreeConfig const*)'
./lightgbm-all.o:lightgbm-all.cpp:(.text$_ZN8LightGBM25VotingParallelTreeLearnerINS_14GPUTreeLearnerEED2Ev[_ZN8LightGBM25VotingParallelTreeLearnerINS_14GPUTreeLearnerEED2Ev]+0x1b3): undefined reference to `LightGBM::GPUTreeLearner::~GPUTreeLearner()'
./lightgbm-all.o:lightgbm-all.cpp:(.text$_ZN8LightGBM25VotingParallelTreeLearnerINS_14GPUTreeLearnerEE4InitEPKNS_7DatasetEb[_ZN8LightGBM25VotingParallelTreeLearnerINS_14GPUTreeLearnerEE4InitEPKNS_7DatasetEb]+0x1e): undefined reference to `LightGBM::GPUTreeLearner::Init(LightGBM::Dataset const*, bool)'
./lightgbm-all.o:lightgbm-all.cpp:(.text$_ZN8LightGBM26FeatureParallelTreeLearnerINS_14GPUTreeLearnerEE4InitEPKNS_7DatasetEb[_ZN8LightGBM26FeatureParallelTreeLearnerINS_14GPUTreeLearnerEE4InitEPKNS_7DatasetEb]+0x12): undefined reference to `LightGBM::GPUTreeLearner::Init(LightGBM::Dataset const*, bool)'
./lightgbm-all.o:lightgbm-all.cpp:(.text$_ZN8LightGBM23DataParallelTreeLearnerINS_14GPUTreeLearnerEE4InitEPKNS_7DatasetEb[_ZN8LightGBM23DataParallelTreeLearnerINS_14GPUTreeLearnerEE4InitEPKNS_7DatasetEb]+0x14): undefined reference to `LightGBM::GPUTreeLearner::Init(LightGBM::Dataset const*, bool)'
./lightgbm-all.o:lightgbm-all.cpp:(.text$_ZN8LightGBM25VotingParallelTreeLearnerINS_14GPUTreeLearnerEE11BeforeTrainEv[_ZN8LightGBM25VotingParallelTreeLearnerINS_14GPUTreeLearnerEE11BeforeTrainEv]+0xa): undefined reference to `LightGBM::GPUTreeLearner::BeforeTrain()'
./lightgbm-all.o:lightgbm-all.cpp:(.text$_ZN8LightGBM26FeatureParallelTreeLearnerINS_14GPUTreeLearnerEE11BeforeTrainEv[_ZN8LightGBM26FeatureParallelTreeLearnerINS_14GPUTreeLearnerEE11BeforeTrainEv]+0x12): undefined reference to `LightGBM::GPUTreeLearner::BeforeTrain()'
./lightgbm-all.o:lightgbm-all.cpp:(.text$_ZN8LightGBM23DataParallelTreeLearnerINS_14GPUTreeLearnerEE11BeforeTrainEv[_ZN8LightGBM23DataParallelTreeLearnerINS_14GPUTreeLearnerEE11BeforeTrainEv]+0x1c): undefined reference to `LightGBM::GPUTreeLearner::BeforeTrain()'
./lightgbm-all.o:lightgbm-all.cpp:(.rdata$_ZTVN8LightGBM23DataParallelTreeLearnerINS_14GPUTreeLearnerEEE[_ZTVN8LightGBM23DataParallelTreeLearnerINS_14GPUTreeLearnerEEE]+0x28): undefined reference to `LightGBM::GPUTreeLearner::ResetTrainingData(LightGBM::Dataset const*)'
./lightgbm-all.o:lightgbm-all.cpp:(.rdata$_ZTVN8LightGBM23DataParallelTreeLearnerINS_14GPUTreeLearnerEEE[_ZTVN8LightGBM23DataParallelTreeLearnerINS_14GPUTreeLearnerEEE]+0x38): undefined reference to `LightGBM::GPUTreeLearner::Train(float const*, float const*, bool)'
./lightgbm-all.o:lightgbm-all.cpp:(.rdata$_ZTVN8LightGBM23DataParallelTreeLearnerINS_14GPUTreeLearnerEEE[_ZTVN8LightGBM23DataParallelTreeLearnerINS_14GPUTreeLearnerEEE]+0x60): undefined reference to `LightGBM::GPUTreeLearner::BeforeFindBestSplit(LightGBM::Tree const*, int, int)'
./lightgbm-all.o:lightgbm-all.cpp:(.rdata$_ZTVN8LightGBM23DataParallelTreeLearnerINS_14GPUTreeLearnerEEE[_ZTVN8LightGBM23DataParallelTreeLearnerINS_14GPUTreeLearnerEEE]+0x68): undefined reference to `LightGBM::GPUTreeLearner::ConstructHistograms(std::vector<signed char, std::allocator<signed char> > const&, bool)'
./lightgbm-all.o:lightgbm-all.cpp:(.rdata$_ZTVN8LightGBM26FeatureParallelTreeLearnerINS_14GPUTreeLearnerEEE[_ZTVN8LightGBM26FeatureParallelTreeLearnerINS_14GPUTreeLearnerEEE]+0x28): undefined reference to `LightGBM::GPUTreeLearner::ResetTrainingData(LightGBM::Dataset const*)'
./lightgbm-all.o:lightgbm-all.cpp:(.rdata$_ZTVN8LightGBM26FeatureParallelTreeLearnerINS_14GPUTreeLearnerEEE[_ZTVN8LightGBM26FeatureParallelTreeLearnerINS_14GPUTreeLearnerEEE]+0x38): undefined reference to `LightGBM::GPUTreeLearner::Train(float const*, float const*, bool)'
./lightgbm-all.o:lightgbm-all.cpp:(.rdata$_ZTVN8LightGBM26FeatureParallelTreeLearnerINS_14GPUTreeLearnerEEE[_ZTVN8LightGBM26FeatureParallelTreeLearnerINS_14GPUTreeLearnerEEE]+0x60): undefined reference to `LightGBM::GPUTreeLearner::BeforeFindBestSplit(LightGBM::Tree const*, int, int)'
./lightgbm-all.o:lightgbm-all.cpp:(.rdata$_ZTVN8LightGBM26FeatureParallelTreeLearnerINS_14GPUTreeLearnerEEE[_ZTVN8LightGBM26FeatureParallelTreeLearnerINS_14GPUTreeLearnerEEE]+0x68): undefined reference to `LightGBM::GPUTreeLearner::ConstructHistograms(std::vector<signed char, std::allocator<signed char> > const&, bool)'
./lightgbm-all.o:lightgbm-all.cpp:(.rdata$_ZTVN8LightGBM26FeatureParallelTreeLearnerINS_14GPUTreeLearnerEEE[_ZTVN8LightGBM26FeatureParallelTreeLearnerINS_14GPUTreeLearnerEEE]+0x70): undefined reference to `LightGBM::GPUTreeLearner::FindBestThresholds()'
./lightgbm-all.o:lightgbm-all.cpp:(.rdata$_ZTVN8LightGBM26FeatureParallelTreeLearnerINS_14GPUTreeLearnerEEE[_ZTVN8LightGBM26FeatureParallelTreeLearnerINS_14GPUTreeLearnerEEE]+0x80): undefined reference to `LightGBM::GPUTreeLearner::Split(LightGBM::Tree*, int, int*, int*)'
./lightgbm-all.o:lightgbm-all.cpp:(.rdata$_ZTVN8LightGBM25VotingParallelTreeLearnerINS_14GPUTreeLearnerEEE[_ZTVN8LightGBM25VotingParallelTreeLearnerINS_14GPUTreeLearnerEEE]+0x28): undefined reference to `LightGBM::GPUTreeLearner::ResetTrainingData(LightGBM::Dataset const*)'
./lightgbm-all.o:lightgbm-all.cpp:(.rdata$_ZTVN8LightGBM25VotingParallelTreeLearnerINS_14GPUTreeLearnerEEE[_ZTVN8LightGBM25VotingParallelTreeLearnerINS_14GPUTreeLearnerEEE]+0x38): undefined reference to `LightGBM::GPUTreeLearner::Train(float const*, float const*, bool)'
./lightgbm-all.o:lightgbm-all.cpp:(.rdata$_ZTVN8LightGBM25VotingParallelTreeLearnerINS_14GPUTreeLearnerEEE[_ZTVN8LightGBM25VotingParallelTreeLearnerINS_14GPUTreeLearnerEEE]+0x68): undefined reference to `LightGBM::GPUTreeLearner::ConstructHistograms(std::vector<signed char, std::allocator<signed char> > const&, bool)'
collect2.exe: error: ld returned 1 exit status

**Comment by guolinke** [comment]
can you try the latest commit ?

**Comment by spedygiorgio** [comment]
@guolinke  I will check and tell

**Comment by guolinke** [comment]
@spedygiorgio 
updates ?

**Comment by spedygiorgio** [comment]
it works  thanks!!!
