### ISSUE TITLE
constructing a dataset from an H5 file using float32 values lead to an error

### ISSUE THREAD

**Issue by PhillipMaire** [microsoft/LightGBM#5057]
## Description
constructing a dataset from an H5 file using float32 values lead to an error

## Reproducible example
```
import h5py
import numpy as np
class HDFSequence(lgb.Sequence):
  def __init__(self, hdf_dataset, batch_size):
    self.data = hdf_dataset
    self.batch_size = batch_size
  def __getitem__(self, idx):
    return self.data[idx]
  def __len__(self):
    return len(self.data)


h5_tmp = '/content/tmp5.h5'
x = np.random.rand(10, 5).astype('float32') # change to float 64 and it works fine
y = np.round(np.random.rand(10)).astype('int')
print(x.dtype)
with h5py.File(h5_tmp, 'w') as h: 
  h.create_dataset('features',
                    np.shape(x),
                    # h5py.h5t.IEEE_F32LE,
                    maxshape=(None, None),
                    chunks=True,
                    data=x)

  train_data = lgb.Dataset(HDFSequence(h['features'], 8192), label=y)
  print(h['features'].dtype)
  train_data.construct()
```
`ValueError: sample_data[0] type float32 is not double`

## Environment info
python linux (google colab CPU with large RAM (~51GB))

LightGBM version or commit hash: 3.3.2

Command(s) you used to install LightGBM
`!pip install lightgbm -U
`

## Additional Comments
is this due auto category determining that this is categorical data?

**Comment by StrikerRUS** [comment]
Hey @PhillipMaire !
Unfortunately, constructing Dataset with Sequence API and float32 data is not possible. Please refer to #5045.
