### ISSUE TITLE
How to stop model snapshots?

### ISSUE THREAD

**Issue by nxgtr** [Microsoft/LightGBM#506]
I am aware of many benefits of model snapshots being automatically saved. However, training a 10k iterations model is being problematic for me, as models are being saved every 100 iterations.

This is new, as I have been using LGBM for months and this did not happen.

I checked https://github.com/Microsoft/LightGBM/blob/master/docs/Parameters.md but I might be missing something.

As title say, how do I stop the automatic saving?

Thanks!

##Extra Info:
I just cloned the repo and compiled. Under Linux and using no interface, just the executable and a config text file with parameters.

**Comment by nxgtr** [comment]
Got it by looking at the code, in src/application/application.cpp at line 234.

You need to document that parameter.

**Comment by guolinke** [comment]
you can set ```snapshot_freq=0``` to disable it.
