### ISSUE TITLE
[ci] switch to a supported no-response bot

### ISSUE THREAD

**Issue by jameslamb** [microsoft/LightGBM#5060]
## Description

This project uses `probot/no-response` to automatically close issues where the original poster has stops interacting with the issue.

I noticed today that that project is no longer supported.

As of July 2021, the README at https://github.com/probot/no-response reads as follows:

> ⚠️ We no longer recommend using this app
> Use the action instead: https://github.com/lee-dohm/no-response

This project should switch to https://github.com/lee-dohm/no-response, to limit the risk of this useful automation failing due to incompatibilities with future GitHub Actions changes.

## Additional Comments

Noticed this while considering a contribution to https://github.com/dask/community/issues/60 and reading the discussion there.

**Comment by jameslamb** [comment]
Just re-opening to discuss one more thing.

I just saw this comment posted by the new action: https://github.com/microsoft/LightGBM/issues/5039#issuecomment-1091055784

1. 🎉 this is great, it works!
2. ...but I didn't realize that it would post as @guolinke , I think because the GitHub token used for this project's automation is tied to your account. @guolinke are you ok with this action posting those comments as you? If not, maybe @shiyu1994 could identify or create a service user (i.e. bot account) in Microsoft's GitHub organization.

**Comment by guolinke** [comment]
@jameslamb It is okay for me, but bot account is better.

**Comment by StrikerRUS** [comment]
@jameslamb 

According to the https://github.com/lee-dohm/no-response#inputs,
> `token` — Token used to access repo information. **The default GitHub Actions token is sufficient.**

Docs: https://docs.github.com/en/actions/security-guides/automatic-token-authentication

We just need to replace `${{ secrets.WORKFLOW }}` with `${{ github.token }}` here
https://github.com/microsoft/LightGBM/blob/3798f8720f4fbc4f1249717fb8f2f037e0075a46/.github/workflows/no-response.yml#L23
and closing comment will be posted by `github-actions [bot]` account.


Example:
https://github.com/10up/ElasticPress/blob/ffb8eb61b915e73a9d0cdab87a14c262cdf36068/.github/workflows/no-response.yml#L20
https://github.com/10up/ElasticPress/issues/2674#issuecomment-1086151366

**Comment by jameslamb** [comment]
oh excellent find @StrikerRUS , thanks!!

Ok great, I'll put up a PR with that change. Then people won't respond to those comments by tagging @guolinke 😂

**Comment by jameslamb** [comment]
Closed by #5136.
