### ISSUE TITLE
[docs] no line breaks in sklearn estimators attributes

### ISSUE THREAD

**Issue by jmoralez** [microsoft/LightGBM#5073]
## Description

The current build for the docs doesn't create line breaks to separate different attributes in the sklearn estimators.

## Reproducible example

[v.3.2.1](https://lightgbm.readthedocs.io/en/v3.2.1/pythonapi/lightgbm.LGBMRegressor.html#lightgbm.LGBMRegressor.best_iteration_)
![image](https://user-images.githubusercontent.com/8473587/158211450-c6e99e98-e3cd-4af9-9489-c4d2fb837f8a.png)

[v.3.3.0+](https://lightgbm.readthedocs.io/en/v3.3.0/pythonapi/lightgbm.LGBMRegressor.html#lightgbm.LGBMRegressor.best_iteration_)
![image](https://user-images.githubusercontent.com/8473587/158211609-bd07cf8a-31f9-4319-9e81-c4b4aa5851e8.png)

**Comment by StrikerRUS** [comment]
I believe this is due to some changes in [`sphinx_rtd_theme`](https://github.com/readthedocs/sphinx_rtd_theme)
https://github.com/microsoft/LightGBM/blob/f834cab49a3e394969d087bb209d500b70f428dd/docs/env.yml#L18

Probably our patch is related also:
https://github.com/microsoft/LightGBM/blob/f834cab49a3e394969d087bb209d500b70f428dd/docs/_static/js/script.js#L2-L3

**Comment by StrikerRUS** [comment]
> Probably our patch is related also:

No line breaks after removing the patch.

![image](https://user-images.githubusercontent.com/25141164/158298516-e64cc213-efe4-4452-964d-8725a2ad049f.png)

**Comment by jmoralez** [comment]
I don't know much about HTML and CSS but it seems that the main difference is that in the previous version the properties had the method class:
![image](https://user-images.githubusercontent.com/8473587/158437673-bc9c6775-1c0c-4c09-bfe9-d6ca15b08eac.png)
And now there is a property class:
![image](https://user-images.githubusercontent.com/8473587/158437746-5e34ad50-cc80-406b-bc44-58fd25d94622.png)
And that class sets `display: inline-block`:
![image](https://user-images.githubusercontent.com/8473587/158437844-963b9a1d-8413-430a-a9a2-ff8385e34f6d.png)
which allows items to be on the same line:

> Compared to display: block, the major difference is that display: inline-block does not add a line-break after the element, so the element can sit next to other elements. ([source](https://www.w3schools.com/css/css_inline-block.asp))

Removing that property solves the issue:
![image](https://user-images.githubusercontent.com/8473587/158438186-d6c7099b-2de3-4148-b80d-2c12f8eb4172.png)

I'm not sure where to make that change though 🤣

**Comment by StrikerRUS** [comment]
@jmoralez Thank you very much for investigating this!

> I'm not sure where to make that change though 🤣

I can prepare a PR with the fix you've found.

However, I think it worth creating upstream issue in the [`sphinx_rtd_theme`](https://github.com/readthedocs/sphinx_rtd_theme) repository describing that new `inline-block` style for properties makes look them ugly.

**Comment by jmoralez** [comment]
> However, I think it worth creating upstream issue in the [sphinx_rtd_theme](https://github.com/readthedocs/sphinx_rtd_theme) repository describing that new inline-block style for properties makes look them ugly.

I believe [this](https://github.com/readthedocs/sphinx_rtd_theme/issues/1247) is the same issue.

**Comment by StrikerRUS** [comment]
I guess you're right. Thanks for finding that issue!
