### ISSUE TITLE
Q: What affects max_bin: unable to set max_bin= 15

### ISSUE THREAD

**Issue by torronen** [microsoft/LightGBM#5077]
## Question
Are there other parameters or some features in the dataset which could force LightGBM to use higher max_bin?
For example, does the number of values in categorical features have something to do with how low it can be set?

## Description
I try to set  `res["max_bin"] = 15;` in C# code passed to GPU-version of LightGBM.dll. I am using ML.NET, more specifically Microsoft.ML.AutoML with a custom build. LightGBM.dll should receive this parameters, because device_type = gpu is set the same way.

However, in one dataset I always get 
   _Compiling OpenCL Kernel with 64 bins..._ and a bigger dataset
   _Compiling OpenCL Kernel with 256 bins..._

**For 256 bins**
[LightGBM] [Warning] Starting from the 2.1.2 version, default value for the "boost_from_average" parameter in "binary" objective is true.
This may cause significantly different results comparing to the previous versions of LightGBM.
Try to set boost_from_average=false, if your old models produce bad results
[LightGBM] [Info] Number of positive: 687224, number of negative: 670255
[LightGBM] [Info] This is the GPU trainer!!
[LightGBM] [Info] Total Bins 107495
[LightGBM] [Info] Number of data: 1357479, number of used features: 6766
[LightGBM] [Info] Using requested OpenCL platform 0 device 0
[LightGBM] [Info] Using GPU Device: NVIDIA GeForce RTX 3090, Vendor: NVIDIA Corporation
[LightGBM] [Info] Compiling OpenCL Kernel with 256 bins...
[LightGBM] [Info] GPU programs have been built
[LightGBM] [Info] Size of histogram bin entry: 12
_application terminates, see Additional info for event log data_ 

**For 64 bins**
[LightGBM] [Warning] Starting from the 2.1.2 version, default value for the "boost_from_average" parameter in "binary" objective is true.
This may cause significantly different results comparing to the previous versions of LightGBM.
Try to set boost_from_average=false, if your old models produce bad results
[LightGBM] [Info] Number of positive: 13767, number of negative: 18424
[LightGBM] [Info] This is the GPU trainer!!
[LightGBM] [Info] Total Bins 39320
[LightGBM] [Info] Number of data: 32191, number of used features: 2667
[LightGBM] [Info] Using requested OpenCL platform 0 device 0
[LightGBM] [Info] Using GPU Device: NVIDIA GeForce RTX 3090, Vendor: NVIDIA Corporation
[LightGBM] [Info] Compiling OpenCL Kernel with 64 bins...
[LightGBM] [Info] GPU programs have been built
[LightGBM] [Info] Size of histogram bin entry: 12
[LightGBM] [Info] 2549 dense feature groups (78.35 MB) transferred to GPU in 0.047711 secs. 67 sparse feature groups
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.427666 -> initscore=-0.582759
[LightGBM] [Info] Start training from score -0.582759

## Reproducible example
I suppose it is related to dataset characteristics. Smaller dataset is 3 gb, bigger is 79 gb.

Code which could be used for debugging at https://github.com/torronen/lightgbm-comparison (MLNET folder)
If needed, I can edit it to testing this issue, but my current dataset is confidential client data.

## Environment info
_LightGBM version or commit hash:_   2.3.1.   (to support ML.NET)
_Command(s) you used to install LightGBM_
Compiled in Visual Studio according to instructions on LightGBM website

## Additional data
The application crash produces this in Windows Event Log
![image](https://user-images.githubusercontent.com/26261427/158459624-f94a245b-cec5-4bac-b04d-87b525b003f7.png)

Application: Kwork.AI.AutoML.Runner.exe CoreCLR Version: 6.0.322.12309 .NET 
Version: 6.0.3 Description: The process was terminated due to an unhandled 
exception. Exception Info: exception code e06d7363, exception address 
00007FFF04004F69

**Comment by guolinke** [comment]
it is possibly caused by the categorical features, whose num_bin is the number of different categories (values).
