### ISSUE TITLE
Docs are unclear at explaining a "Data Query"

### ISSUE THREAD

**Issue by stefanomeara** [microsoft/LightGBM#5084]
I am currently trying to build a ranker using LambdaRank; however, I still do not understand what a "data query" is.

The docs explain it here: https://lightgbm.readthedocs.io/en/latest/Parameters.html#group_column

Unfortunately, the docs are very brief on this and it's very hard to decipher by looking into the sample dataset included in the LambdaRank Example.

Others have asked the same thing as detailed on this post: https://stats.stackexchange.com/questions/427918/learning-to-rank-for-time-series-with-lightgbm-data-formatting

Any help would be appreciated, thanks!

**Comment by shiyu1994** [comment]
@JohnDoesDev Thanks for using LightGBM. First, each row in a data input for LambdaRank is a document. And 
the `query` (`id`), or `group` (`id`) in the dataset means the ID of query that the document belongs to. So LambdaRank will rank all documents in the same query.

**Comment by RishiMalhotra920** [comment]
Hi @shiyu1994 and team, 

I still do not understand what you mean by the group or query id. Can you please explain in more detail?

**Comment by shiyu1994** [comment]
@RishiMalhotra920 In learning to rank, we have many documents. Each instance in a learning to rank dataset is a document. Group/query ID means the query of which a document is a searching result. You may see
https://en.wikipedia.org/wiki/Learning_to_rank
for a more clear concept of queries and documents. Thanks!
