### ISSUE TITLE
R: parameter name confusion.

### ISSUE THREAD

**Issue by slfan2013** [Microsoft/LightGBM#509]
There are some parameters that have a different name in R help page (`?lgb.train`) and the [parameter website](https://github.com/Microsoft/LightGBM/blob/master/docs/Parameters.md).

For example, `nrounds` in `?lgb.train` but `num_iterations` in the website.

**Comment by guolinke** [comment]
look the note under the parameter ```num_iterations```.

note: For python/R package, cannot use this parameters to control number of iterations.
