### ISSUE TITLE
[Feature]LightGBM_model.txt also record internal node output values or SummedWeights in leaf

### ISSUE THREAD

**Issue by chenghuige** [Microsoft/LightGBM#51]
Say if one leaf split trun into internal node indexOfNewInternal , we can record like

`_previousLeafValue[indexOfNewInternal] = _leafValue[leaf];`

and at last output previousLeafValue (length as NumInternalNodes) to  LightGBM_model.txt.

So we can use this info for writting wrapper code to calc each feature importance for one specific instance prediction/inference by summing up value diff before and after split following the inference tree path.

Another work around might be record for SummedWeights in each leaf, so we can reconstruct internal node output/value.

**Comment by guolinke** [comment]
I think this is easy to be done. Welcome to contribute

**Comment by chenghuige** [comment]
This feature is done and merged in master.
Based on LightGBM txt file I have written one wrapper for prediction feature importance, 
looks like below, I will opensource that soon.

> In [2]: from libgbdt import GbdtPredictor, Vector

> In[3]: p = GbdtPredictor('./LightGBM_model.txt')
WARNING: Logging before InitGoogleLogging() is written to STDERR
I1114 14:22:06.767840 15872 LoadSave.h:55] gbdt try load as text from ./LightGBM_model.txt
I1114 14:22:06.767949 15872 GbdtPredictor.h:339] Loading from text file ./LightGBM_model.txt of LightGBM format
I1114 14:22:06.769248 15872 GbdtPredictor.h:240] numFeatures --- [420]
I1114 14:22:06.783113 15872 GbdtPredictor.h:310] _trees.size() --- [100]
I1114 14:22:06.783154 15872 Predictor.h:794] Try load feature names from ./feature_name.txt

> In[4]: p.PrintFeatureGain(Vector('1:3.0,2:4.5,359:100'), sortByAbsGain=True)
I1114 14:22:22.320636 15872 GbdtPredictor.h:514] Per feature gain for this predict:
0:f359:old_Term_freq_weight             	3.64444	359:100
1:f352:keyword_length                   	-2.85426	352:0
2:f360:old_Keyword_length               	-2.18092	360:0
3:f334:click_avg_wordrank               	0.870828	334:0
4:f413:old_ner_PER                      	-0.771697	413:0
5:f35:title_normed_wordrank_weight      	0.627194	35:0
6:f37:title_avg_wordrank_weight         	-0.592333	37:0
7:f358:old_Clickquery_freq              	-0.381908	358:0
8:f354:old_Title_freq                   	-0.304026	354:0

>
