### ISSUE TITLE
[R-package] tests and examples should not use more than 2 threads

### ISSUE THREAD

**Issue by jameslamb** [microsoft/LightGBM#5102]
## Description

CRAN's submission policies at https://cran.r-project.org/web/packages/policies.html include the following guidance

> If running a package uses multiple threads/cores it must never use more than two simultaneously: the check farm is a shared resource and will typically be running many checks simultaneously.

Currently, most of `{lightgbm}`'s examples and tests do not explicitly set the number of threads to use, which means LightGBM defaults to using whatever the result of `omp_get_num_threads()` is.

https://github.com/microsoft/LightGBM/blob/60e72d5f4ec5ec2a4d30a53633e1e2d59c81309b/include/LightGBM/utils/openmp_wrapper.h#L30-L34

## Work to be done

To ensure that `{lightgbm}` is always respectful of the CRAN check farm, all of its examples and tests should be changed to default to using 2 threads when run on CRAN.

Similar to the work done for #4862 

https://github.com/microsoft/LightGBM/blob/820ae7e65e90860061ec89cc4a1ad0a39b96e051/R-package/tests/testthat/test_lgb.Booster.R#L1-L3

this should be done in a way that allows LightGBM's CI to override that behavior and use all available CPUs in its CI environments (which might sometimes be more than 2).

```r
NUM_THREADS <- as.integer(
    Sys.getenv("LGB_NUM_THREADS", "2")
)
```

## References

Opened as a result of https://github.com/microsoft/LightGBM/pull/4972#discussion_r836043334.

**Comment by StrikerRUS** [comment]
I think we can determine whether we are in a CI environment or at CRAN and set `0` and `2` respectively. This can be done via checking `CI=true` env variable:
- https://docs.travis-ci.com/user/environment-variables/#default-environment-variables
- https://www.appveyor.com/docs/environment-variables/
- https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables
- https://issues.jenkins.io/browse/JENKINS-36707
- https://circleci.com/docs/2.0/env-vars/#built-in-environment-variables

I only can't find for Azure Pipelines (need investigation): 
https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml
https://github.com/MicrosoftDocs/vsts-docs/issues/1949

**Comment by jameslamb** [comment]
Thanks for those links!

But since the environment variable `CI` is such a general-purpose name, and since a CRAN rejection is so expensive (in terms of our time and the risk of CRAN archiving the package), I'd feel safer with a LightGBM-specific environment variable that is very very unlikely to be defined on CRAN.

Maybe I'm just being paranoid, I've just developed this habit of trying to minimize as much as possible assumptions about what CRAN will do or what their check environment will look like.

**Comment by jmoralez** [comment]
I was going to add `num_threads` in params for all tests but I thought maybe we could set `OMP_NUM_THREADS=2` instead. Running `OMP_NUM_THREADS=2 Rscript testthat.R` restricts the number of threads to 2 since the default is 0 and that means "use what openmp says" and when that variable is set it will use that number of threads. However I don't think this is possible on CRAN so I was trying `Sys.setenv(OMP_NUM_THREADS = 2)` on `testthat.R` but that doesn't seem to work. WDYT @jameslamb?

**Comment by jmoralez** [comment]
I think that doesn't work because `lgb.get.default.num.threads` is only called by `lightgbm`, not by `lgb.train` :(

**Comment by jameslamb** [comment]
hmmmm ok, and I realize now that even for `lightgbm()` that might not work, since tests that pass `num_threads = {something}` to `lightgbm()` will also not end up calling that function

https://github.com/microsoft/LightGBM/blob/44fe591a60d7427d64997c37b22768a92c97c47b/R-package/R/lightgbm.R#L162-L164

What about adding instead something like the following in `lgb.train()` and `lgb.cv()`?

```r
# LightGBM-internal fix to comply with CRAN policy of only using up to 2 threads in tests and example
threads_from_opts <- options()[["lightgbm.num.testing.threads"]]
if (!is.null(threads_from_opts)) {
    params[["num_threads"]] <- threads_from_opts
}
```

And now that I see it...maybe we should use a name that makes it clearer that this isn't intended to be used by users. Like `lightgbm.internal.override.num.threads` or something like that.

I think that could work as a minimally-invasive change that could be reverted once #4705 is addressed.

**Comment by jameslamb** [comment]
Based on https://github.com/microsoft/LightGBM/pull/5367#issuecomment-1294436821, I am going to pick this up. Assigning it to myself to claim it so no one else spends time on it.

**Comment by jmoralez** [comment]
Hey @jameslamb. I was thinking that since we can't set `OMP_NUM_THREADS` in the test file itself we could maybe use [system](https://stat.ethz.ch/R-manual/R-devel/library/base/html/system.html) or something similar so that we can set the env variable before the process starts. I tried this by renaming `testthat.R` to `_testthat.R` and then defining `testthat.R` as:
```R
system("OMP_NUM_THREADS=1 Rscript _testthat.R")
```
and tried different values for the variable (by calling `time Rscript testthat.R`) and it seems to work (1 shows less cpu usage than 4).

This is way too hacky and may not work but we could maybe try something in that direction.

**Comment by jameslamb** [comment]
Interesting idea @jmoralez ! I hadn't considered that.

I would expect it to work in local testing, but I don't think we should pursue it as a way to satisfy CRAN.

1. that will cause `Rscript` to be looked up on `PATH`, and there's no guarantee that that'll be the same build of R used by `R CMD check` (e.g., in some environments the binary might be called `RDscript` or similar)
2. that still doesn't help with the issue of examples in documentation

I think we should pursue more permanent solutions, on the C++ side of LightGBM, to more tightly control the number of threads used.
