### ISSUE TITLE
[python-package] reset parameter callback with num_leaves fails silently

### ISSUE THREAD

**Issue by deadsoul44** [microsoft/LightGBM#5104]
## Description
Reset parameter callback with `num_leaves` fails silently in a Kaggle notebook. It makes notebook restart and lose variables. I tried other parameters (e.g. min_data_in_leaf) and they work.

## Reproducible example
It should be possible to reproduce with any data.

## Environment info

LightGBM version or commit hash: 3.3.2

Command(s) you used to install LightGBM

```shell
!pip install -U lightgbm
```

Kaggle notebook

**Comment by jameslamb** [comment]
> It should be possible to reproduce with any data.

Please provide a reproducible example. If it is "possible with any data", it should be easy for you to create a reproducible example with the built-in datasets from `scikit-learn` (like this example: https://github.com/microsoft/LightGBM/issues/4842#issuecomment-986170715).

Maintainers and the rest of the LightGBM community would really appreciate that, as it reduces the effort required for someone wanting to fix this issue to investigate it, which should reduce the time it takes to provide a fix.

Without that, we will have to guess what you mean by "lose variables" and by "tried other parameters".
