### ISSUE TITLE
It is not Good...

### ISSUE THREAD

**Issue by IvanaXu** [microsoft/LightGBM#5112]
So what ended up solving it for me was:
`mkdir -p /etc/OpenCL/vendors && \
    echo "libnvidia-opencl.so.1" > /etc/OpenCL/vendors/nvidia.icd`

I got this from the [gpu docker file](https://github.com/Microsoft/LightGBM/blob/master/docker/gpu/dockerfile.gpu). Solved my problem, hope it helps!

_Originally posted by @ryanferg in https://github.com/microsoft/LightGBM/issues/586#issuecomment-352845980_

**Comment by jameslamb** [comment]
Please keep posts on this issues board related to bug reports, questions, or feature requests. You do not need to open issues re-posting comments from old discussions.

I'm going to close and lock this thread. If you have a bug report, question, or feature request, please open a new issue and fill out the template provided there.

Thanks for using LightGBM!
