### ISSUE TITLE
Best practices regarding num_threads and prediction

### ISSUE THREAD

**Issue by mosscoder** [microsoft/LightGBM#5130]
LightGBM documentation suggests that it is best practice not to exceed the physical core count for model training. Is this also true of prediction? In other words, could there be a performance benefit to hyperthreading when predicting to new data with a trained model?

**Comment by guolinke** [comment]
@mosscoder the multi-thread in prediction is the data-parallel mode, so it is highly parallelized.
So if you predict with many data, num_threads <= CPU cores is recommended.

**Comment by mosscoder** [comment]
Thanks. When you say CPU cores, do you mean physical cores or logical cores (Hyperthreading)?

**Comment by guolinke** [comment]
it mean physical core

**Comment by mosscoder** [comment]
Thank you!
