### ISSUE TITLE
linear_tree uses original values of features or binned values?

### ISSUE THREAD

**Issue by blindape2** [microsoft/LightGBM#5138]
Are original values of features used for the linear regression or it is using the binned values?
I hope the answer is original values... but I would like to confirm.

**Comment by shiyu1994** [comment]
@blindape2 Thanks for using LightGBM. `linear_tree` in LightGBM uses original values.

**Comment by jameslamb** [comment]
Just adding for anyone finding this from search engines that the use of original values for linear learners is why https://lightgbm.readthedocs.io/en/latest/Parameters.html#linear_tree contains the following note:

> **Note**: setting linear_tree=true significantly increases the memory use of LightGBM
