### ISSUE TITLE
How can I disable/surpress  message like `valid_0 ...` ?

### ISSUE THREAD

**Issue by eromoe** [microsoft/LightGBM#5158]
I have searched for surpress log.

I found three methods , 

1. `verbose=-1`,  nothing changed
2. `verbose_eval` , sklearn api doesn't contain it .
1. `lgb.log_evaluation` is not found . 
	  ```
	  gbm = lgb.LGBMRegressor(num_leaves=31,
	                          learning_rate=0.05,
	                          n_estimators=20,
	                          verbose=-1
	                         )
	  
	  callbacks = [lgb.early_stopping(10, verbose=0), lgb.log_evaluation(period=0)]
	  
	  gbm.fit(X_train, y_train,
	          eval_set=[(X_test, y_test)],
	          eval_metric='tweedie',
	          callbacks=callbacks,
	         )
	  ```
1. change `lgb.log_evaluation(period=0)]`  to `lgb.print_evaluation(period=0)]`  , didn't take effect .

So , what should I do ?

**Comment by StrikerRUS** [comment]
Hey @eromoe !

I can't reproduce this issue with the latest `master` fc0c8fd4521ab4814fe3f59999115b70984e76c1.

`verbose=False` in `early_stopping()` callback works fine for me.

----

#### `callbacks = [lgb.early_stopping(10, verbose=True)]`

```python
import numpy as np
import lightgbm as lgb

X_train = np.random.random((100, 15))
y_train = np.random.random((100))

X_test = np.random.random((10, 15))
y_test = np.random.random((10))

gbm = lgb.LGBMRegressor(num_leaves=31,
                        learning_rate=0.05,
                        n_estimators=20,
                        verbose=-1
                       )

callbacks = [lgb.early_stopping(10, verbose=True)]

gbm.fit(X_train, y_train,
        eval_set=[(X_test, y_test)],
        eval_metric='tweedie',
        callbacks=callbacks,
       )
```

![image](https://user-images.githubusercontent.com/25141164/164133174-6eeb527f-3e95-46f6-8c87-3bcdc64a41b0.png)

#### `callbacks = [lgb.early_stopping(10, verbose=False)]`

```
import numpy as np
import lightgbm as lgb

X_train = np.random.random((100, 15))
y_train = np.random.random((100))

X_test = np.random.random((10, 15))
y_test = np.random.random((10))

gbm = lgb.LGBMRegressor(num_leaves=31,
                        learning_rate=0.05,
                        n_estimators=20,
                        verbose=-1
                       )

callbacks = [lgb.early_stopping(10, verbose=False)]

gbm.fit(X_train, y_train,
        eval_set=[(X_test, y_test)],
        eval_metric='tweedie',
        callbacks=callbacks,
       )
```

![image](https://user-images.githubusercontent.com/25141164/164133257-9a0c06e4-8d24-421c-a55b-012106ea527e.png)

**Comment by eromoe** [comment]
@StrikerRUS  Maybe you are using jupyter notebook instead of jupyter lab ?

![image](https://user-images.githubusercontent.com/3938751/164373277-8b09dc8d-21bd-42c3-84aa-c8ddc111c58c.png)

**Comment by StrikerRUS** [comment]
> Maybe you are using jupyter notebook instead of jupyter lab ?

It shouldn't matter. LightGBM wouldn't make those prints if `verbose=False`.

What version of LightGBM are you using?

**Comment by eromoe** [comment]
lightgbm     3.2.1
windows 10 
python 3.8.8

**Comment by StrikerRUS** [comment]
Ah, I see!
Then please set `verbose=False` argument of `fit()` method.
https://lightgbm.readthedocs.io/en/v3.2.1/pythonapi/lightgbm.LGBMRegressor.html#lightgbm.LGBMRegressor.fit

That argument has been removed and doesn't exist in recent versions.

**Comment by eromoe** [comment]
Also due to lighgbm version, update to 3.3.2 ,  `verbose=False` could take effect too.

**Comment by StrikerRUS** [comment]
So, output is suppressed now?

**Comment by eromoe** [comment]
Yeah!

**Comment by eromoe** [comment]
I am in a new machine with lightgbm 3.3.5, `verbose=False` doesn't surpress valid_0.

**Comment by eromoe** [comment]
OK, it is come from optuna https://github.com/optuna/optuna/pull/4335   and 3.1.0 doesn't publish yet.
