### ISSUE TITLE
Documentation for hyperparameters

### ISSUE THREAD

**Issue by AnjaliSetiya** [microsoft/LightGBM#5165]
## Description
A proper description of what should be the range for the hyperparameters is lacking. It becomes very difficult to use the algorithm without it.Randomly trying to use different ranges is highly time consuming

## Environment info

LightGBM version or commit hash:

Command(s) you used to install LightGBM

```shell

```

**Comment by samFarrellDay** [comment]
The constraints are listed on the [readthedocs parameters page](https://lightgbm.readthedocs.io/en/latest/Parameters.html).

**Comment by jameslamb** [comment]
Thanks for using LightGBM!

As @samFarrellDay mentioned, the parameter documentation at https://lightgbm.readthedocs.io/en/latest/Parameters.html describes the constraints on parameter values (e.g. `0.0 < feature_fraction <= 1.0`).

Beyond that, it's very difficult for LightGBM's documentation to provide guidance on what *good* values are, as the "good" values are highly dependent on the structure of your training data and choice of machine learning task / objective function.

If there are specific places in the existing documentation where you have found incorrect or missing information, please point them out or propose pull requests changing them. But documentation like "here are good values of `max_bin`" is not something that can be done in a general way.

**Comment by jameslamb** [comment]
> with a parameter tuning package like optuna or hyperopt

@samFarrellDay would you be willing to propose a PR adding a link to `hyperopt` in the documentation on Parameter Tuning?

https://github.com/microsoft/LightGBM/blame/416ecd5a8de1b2b9225ded3c919cb0d40ec0d9bd/docs/Parameters-Tuning.rst#L11

**Comment by samFarrellDay** [comment]
@jameslamb Will do.

**Comment by StrikerRUS** [comment]
We already have a [such feature request](https://github.com/microsoft/LightGBM/issues/2617) in our [Hub](https://github.com/microsoft/LightGBM/issues/2302).
