### ISSUE TITLE
Python LightGBMError: Cannot change bin_construct_sample_cnt after constructed Dataset handle.

### ISSUE THREAD

**Issue by Dcwjh** [microsoft/LightGBM#5166]
## Description
The code is as follows.
```
train_features = train_features.to_numpy()
test_features = test_features.to_numpy()
train_set = lgb.Dataset(train_features, label = train_labels)
test_set = lgb.Dataset(test_features, label = test_labels)
hyperparameters = model.get_params()
cv_results = lgb.cv(hyperparameters, train_set, num_boost_round = 10000, nfold = 5, metrics = 'auc', 
           early_stopping_rounds = 100, verbose_eval = False, seed = 42)
```

**Comment by jameslamb** [comment]
Thanks for using LightGBM!

Unfortunately, this is not enough information for maintainers to help you. Please provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that produces the error you're facing.

Please also provide the information you were asked for when you clicked "New Issue", like:

* operating system
* version of Python
* version of LightGBM (commit hash if you installed it from source)
* how you installed LightGBM
