### ISSUE TITLE
lgb.train() encountering TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by hongwang-wang** [microsoft/LightGBM#5170]
## Description

I encountered this error when I tried to train with random forest type with the following parameters, 
```
num_boost_round=500

{'boosting_type': 'rf',
 'objective': 'regression',
 'bagging_freq': 1,
 'verbose': 1,
 'bagging_fraction': 0.5,
 'feature_fraction': 0.75,
 'min_data_in_leaf': 250}
```
The issue can be reproduced via the attached example which includes  fail_0.py and ml_rf.pkl.

I did search prior report wrt "TypeError: 'NoneType' object is not iterable" and found 2 (issue #1971 and #1994) but both seem to be related to the model fit() function instead of the train() function. In my case, the training data sets have no inf/nan. And in my use of the train(), I specified 3 columns as categorical (which appears to produce a user warning)

The console output upon running the reproducible script is as follows.

```console
$ python fail_0.py
C:\work\anaconda3\lib\site-packages\lightgbm\basic.py:2065: UserWarning: Using categorical_feature in Dataset.
  _log_warning('Using categorical_feature in Dataset.')
Traceback (most recent call last):
  File "fail_0.py", line 20, in <module>
    model = lgb.train(params=params,
  File "C:\work\anaconda3\lib\site-packages\lightgbm\engine.py", line 271, in train
    booster = Booster(params=params, train_set=train_set)
  File "C:\work\anaconda3\lib\site-packages\lightgbm\basic.py", line 2607, in __init__
    params.update(train_set.get_params())
TypeError: 'NoneType' object is not iterable
```

## Reproducible example

The script to reproduce the issue is very simple as shown below. It is in the attached tar.gz along with the pkl file 

```script
import _pickle as pickle
import pandas as pd
import numpy as np
import lightgbm as lgb

data_from_pickle_file = open("ml_rf.pkl", 'rb')
read_data_pickle = pickle.load(data_from_pickle_file)
data_from_pickle_file.close()

(params, num_boost_round, categoricals, outcome_data, label, train_idx, test_idx) = read_data_pickle

lgb_data = lgb.Dataset(data=outcome_data.drop(label, axis=1),
                       label=outcome_data[label],
                       categorical_feature=categoricals,
                       free_raw_data=False)

lgb_train = lgb_data.subset(train_idx.tolist()).construct()
lgb_test = lgb_data.subset(test_idx.tolist()).construct()

model = lgb.train(params=params,
                  train_set=lgb_train,
                  num_boost_round=num_boost_round)
```

## Environment info

LightGBM version or commit hash:  3.3.2
```
lightgbm                  3.3.2                    pypi_0    pypi
```

Command(s) you used to install LightGBM: 
```
pip install lightgbm
```

Shell:  git bash on Windows 10 

## Additional Comments

[fail.tar.gz](https://github.com/microsoft/LightGBM/files/8537342/fail.tar.gz)

**Comment by StrikerRUS** [comment]
Hey @hongwang-wang ! Thanks for posting this issue.

Unfortunately, I can't run your repro due to the following pandas (I guess version mismatch) error:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-3b91722eeb0f> in <module>
      1 data_from_pickle_file = open(r"C:\Users\nekit\Downloads\fail\ml_rf.pkl", 'rb')
----> 2 read_data_pickle = pickle.load(data_from_pickle_file)
      3 data_from_pickle_file.close()
      4 
      5 (params, num_boost_round, categoricals, outcome_data, label, train_idx, test_idx) = read_data_pickle

AttributeError: Can't get attribute 'new_block' on <module 'pandas.core.internals.blocks' from 'D:\\Miniconda3\\lib\\site-packages\\pandas\\core\\internals\\blocks.py'>
```

Can you refactor your example so that it won't use pickle?

**Comment by hongwang-wang** [comment]
Hi StrikerRUS,

In (issue #1971 and #1994) as I referred previously, pickle was used to reproduce the issue. That is the reason I also used pickle.

pickle is part of any python after 3.x as noted in https://stackoverflow.com/questions/68582382/how-to-pip-install-pickle-under-python-3-9-in-windows.

thanks

**Comment by StrikerRUS** [comment]
Well, that's great that pickle is a standard Python package. But how this info will help me overcome pandas error?

**Comment by hongwang-wang** [comment]
Hi StrikerRUS

The version of pandas I used is:

```
pandas                    1.3.1            py38h60cbd38_0    conda-forge
```

**Comment by StrikerRUS** [comment]
OK, the error happens here
https://github.com/microsoft/LightGBM/blob/56ccea4243aba4c538ebca9de8c67ee0c9bc60eb/python-package/lightgbm/basic.py#L2614-L2615
because `train_set.get_params()`
https://github.com/microsoft/LightGBM/blob/56ccea4243aba4c538ebca9de8c67ee0c9bc60eb/python-package/lightgbm/basic.py#L1352
returns `None`.

I think we can fix it by returning empty dict instead of `None` in `get_params()` method.

@hongwang-wang As a  quick workaround you can pass `params={}` to the Dataset constructor.

**Comment by hongwang-wang** [comment]
Hi StrikerRUS

thanks for the update. 

I found another workaround which might point to a potential issue with the use of subset().construct(). As shown below, when I replace 

```
lgb_train = lgb_data.subset(train_idx.tolist()).construct()
```
with 
```

my_train_df = outcome_data.iloc[train_idx.tolist()]

lgb_train = lgb.Dataset(data=my_train_df.drop(label, axis=1), 
                     label=my_train_df[label], 
                     categorical_feature=categoricals,
                     free_raw_data=False)

```
in other words, doing what the subset().construct() is supposed to do, then train() works fine without the error reported earlier.

The snippet is shown below. I also attached the success_0.py
[success.tar.gz](https://github.com/microsoft/LightGBM/files/8559011/success.tar.gz)


```
import _pickle as pickle
import pandas as pd
import numpy as np
import lightgbm as lgb

data_from_pickle_file = open("ml_rf.pkl", 'rb')
read_data_pickle = pickle.load(data_from_pickle_file)
data_from_pickle_file.close()

(params, num_boost_round, categoricals, outcome_data, label, train_idx, test_idx) = read_data_pickle

lgb_data = lgb.Dataset(data=outcome_data.drop(label, axis=1),
                       label=outcome_data[label],
                       categorical_feature=categoricals,
                       free_raw_data=False)

#lgb_train = lgb_data.subset(train_idx.tolist()).construct()
#lgb_test = lgb_data.subset(test_idx.tolist()).construct()

my_train_df = outcome_data.iloc[train_idx.tolist()]

lgb_train = lgb.Dataset(data=my_train_df.drop(label, axis=1), 
                     label=my_train_df[label], 
                     categorical_feature=categoricals,
                     free_raw_data=False)


model = lgb.train(params=params,
                  train_set=lgb_train,
                  num_boost_round=num_boost_round)
```

**Comment by ronaldgevern** [comment]
This error means that python is trying to iterate over a None object. With Python, you can only iterate over an object if that object has a value. This is because iterable objects only have a next item which can be accessed if their value is not equal to None. If you try to iterate over a None object, you encounter the TypeError: ‘NoneType’ object is not iterable error.

For example, [list.sort()](http://net-informations.com/python/ds/listsort.htm) only change the list but return None. 

Python's interpreter converted your code to pyc bytecode. The Python virtual machine processed the bytecode, it encountered a looping construct which said iterate over a variable containing None. The operation was performed by invoking the `__iter__` method on the None. None has no `__iter__` method defined, so Python's virtual machine tells you what it sees: that NoneType has no `__iter__` method.

Technically, you can avoid the NoneType exception by checking if a value is equal to None before you iterate over that value.
