### ISSUE TITLE
Does LGBMClassifier take the class_weight parameter into account while calculating metrics?

### ISSUE THREAD

**Issue by bhargav0795** [microsoft/LightGBM#5171]
I'm trying to solve a multi-class classification problem with imbalanced data. I've 53 classes and data skewed towards 5 of them. I passed **class_weights** to account for data distribution.

Does LGBMClassifier take the class_weight parameter into account while calculating metrics? If not, what's the best way to create a custom metric? I can't find an option to do it using LGBMClassifier API. TIA

**Comment by guolinke** [comment]
class_weight is python-only parameter. And i believe it actually converts to sample weight. And in metric, sample weight is taken into account.  refer to https://github.com/microsoft/LightGBM/blob/1617a63e96333cd0b129a38e6292e19fe989b759/src/metric/multiclass_metric.hpp#L89
