### ISSUE TITLE
LightGBM can not dump, ValueError: Invalid control character

### ISSUE THREAD

**Issue by heroxrq** [Microsoft/LightGBM#518]
feature_name contains chinese and some symbols, it cause the LightGBM can not dump!!
However, I have set the defaultencoding --> sys.setdefaultencoding('utf-8')
I don't know why it cannot dump?
---------------------------------------------------------------------------------------------------
<pre><code>
Traceback (most recent call last):
  File "train.py", line 52, in <module>
    model_json = gbm.dump_model()
  File "/home/uaa/install/anaconda2/lib/python2.7/site-packages/lightgbm-0.1-py2.7.egg/lightgbm/basic.py", line 1569, in dump_model
    return json.loads(string_buffer.value.decode())
  File "/home/uaa/install/anaconda2/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/home/uaa/install/anaconda2/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/uaa/install/anaconda2/lib/python2.7/json/decoder.py", line 380, in raw_decode
ValueError: Invalid control character at: line 6 column 43 (char 145)
--------------------------------------------------------------------------------------------------
<pre><code>
#!/usr/bin/python
# -*- coding: utf-8 -*-

import sys
import json
import lightgbm as lgb

reload(sys)
sys.setdefaultencoding('utf-8')

# create dataset for lightgbm
# if you want to re-use data, remember to set free_raw_data=False
lgb_train = lgb.Dataset('train_multi.dat', free_raw_data=False)
lgb_valid = lgb.Dataset('valid_multi.dat', free_raw_data=False)
lgb_test = lgb.Dataset('test_multi.dat', free_raw_data=False)

# specify your configurations as a dict
params = {
    'task': 'train',
    'boosting_type': 'gbdt',
    'objective': 'multiclass',
    'num_class': 3,
    'learning_rate': 0.1,
    'num_leaves': 256,
    'max_depth': 10,
    'feature_fraction': 0.9,
    'bagging_fraction': 0.8,
    'bagging_freq': 5,
    'max_bin': 255,
    'metric': {'multi_logloss', 'multi_error'},
    'metric_freq': 1,
    'is_training_metric': True
}

# generate a feature name
feature_name = ['feature_0']
with open('mapping.txt', 'r') as mapping_file:
    for line in mapping_file:
        feature_name.append(line.split('\t')[0])

print('Start training...')
# feature_name and categorical_feature
gbm = lgb.train(params,
                lgb_train,
                num_boost_round=2,
                valid_sets=[lgb_valid, lgb_test],
                feature_name=feature_name)

# save model to file
gbm.save_model('model.txt.new')

model_json = gbm.dump_model()

with open('model.json', 'w+') as f:
    json.dump(model_json, f, indent=4)

# load model to predict
print('Load model to predict')
bst = lgb.Booster(model_file='model.txt.new')

graph = lgb.create_tree_digraph(bst, tree_index=1, encoding='utf-8', name='Tree1')
graph.render(view=True)

**Comment by guolinke** [comment]
@heroxrq  can you put your code into a code-block ?

**Comment by heroxrq** [comment]
@guolinke It's ok.

**Comment by heroxrq** [comment]
didn't support Chinese as feature name?  if I want to plot the tree graph use create_tree_digraph, it call dump function. Is there other way I can do it? replace the name after dump? 
<pre><code>
    model = booster.dump_model()
    tree_infos = model['tree_info']
    if 'feature_names' in model:
        feature_names = model['feature_names']
    else:
        feature_names = None

    if tree_index < len(tree_infos):
        tree_info = tree_infos[tree_index]
    else:
        raise IndexError('tree_index is out of range.')

    if show_info is None:
        show_info = []

    graph = _to_graphviz(tree_info, show_info, feature_names,
                         name=name, comment=comment, filename=filename, directory=directory,
                         format=format, engine=engine, encoding=encoding, graph_attr=graph_attr,
                         node_attr=node_attr, edge_attr=edge_attr, body=body, strict=strict)

**Comment by guolinke** [comment]
@heroxrq 
I think it can work. 
The model are dumped by cpp code, so we didn't let it support utf-8 .
