### ISSUE TITLE
[R-package] can't set categorical feature when dataset doesn't have feature names

### ISSUE THREAD

**Issue by jmoralez** [microsoft/LightGBM#5181]
## Description

When passing `categorical_feature` to the `lgb.Dataset` function a check is performed over the length of the column names. https://github.com/microsoft/LightGBM/blob/d893cd1ff0bce1b9ab965a95090259ded14c2db6/R-package/R/lgb.Dataset.R#L172-L180

However if no column names are provided that check fails because `length(NULL) == 0`.

## Reproducible example

```R
library(lightgbm)

ds <- lgb.Dataset(matrix(1:20, nrow = 10), categorical_feature = 1L)
ds$construct()
# Error in ds$construct() : 
#   lgb.self.get.handle: supplied a too large value in categorical_feature: 1 but only 0 features
```

## Environment info

LightGBM version or commit hash: d893cd1ff0bce1b9ab965a95090259ded14c2db6

Command(s) you used to install LightGBM

```shell
./build-cran-package.sh --no-build-vignettes
R CMD INSTALL --with-keep.source lightgbm_3.3.2.99.tar.gz
```

## Additional Comments

I'll try to work on a fix for this if it's actually a bug.

**Comment by jameslamb** [comment]
Hey thanks for writing this up!

I think it's a slightly different flavor of https://github.com/microsoft/LightGBM/issues/4374, with the same root cause.

Definitely think it's a bug.

**Comment by jmoralez** [comment]
Oh that's my bad, I didn't find that issue. Should I close this one?
