### ISSUE TITLE
Unknown type of parameter:objective, got:method

### ISSUE THREAD

**Issue by seanyboi** [microsoft/LightGBM#5185]
## Description
I am trying to add a custom objective to the parameters variable of `lightgbm.train()`. The custom objective is a method of a class I have built so `self.<class>.<method>`

The error being returned is:

```python
raise TypeError(f'Unknown type of parameter:{key}, got:{type(val).__name__}')
TypeError: Unknown type of parameter:objective, got:method
```

## Environment info

LightGBM version or commit hash:

Command(s) you used to install LightGBM

```shell
pip3 install lightgbm
```

Version: 3.3.2

**Comment by jameslamb** [comment]
Thanks for using LightGBM!

For v3.3.2 of `lightgbm`, custom object functions must be passed to `lgb.train()` via the keyword argument `fobj`.

You can view the documentation for that release at https://lightgbm.readthedocs.io/en/v3.3.2/pythonapi/lightgbm.train.html.

Passing a custom objective function via `params` was only very recently added here in GitHub (#5052), and will be a part of the v4.0.0 release.

If this suggestion doesn't resolve your issue, please provide a reproducible example showing what you're trying, and we'd be happy to provide further help.

**Comment by seanyboi** [comment]
AH that makes complete sense! Thanks for getting back to me :). I was using the 'latest' documentation. You'd assume the latest documentation would be inline with the current latest release of lightgbm. May be something to consider rolling back the latest documentation for now because it may stump a few more people!

Thanks!

**Comment by jameslamb** [comment]
> May be something to consider rolling back the latest documentation

Thanks very much for your report and suggestion @seanyboi ! I agree with you. As the gap between the latest `lightgbm` release and the current state of the repo has widened, we've been seeing other reports of similar "didn't realize I was looking at `latest` docs" confusion.

I've opened #5342 for discussion of what we might do with LightGBM's docs site. If you'd like to add anything to that discussion, we'd welcome it!
