### ISSUE TITLE
R package: `feature_pre_filter` vanished

### ISSUE THREAD

**Issue by mayer79** [microsoft/LightGBM#5200]
## Description

Version: LightGBM 3.3.2 in R.

In a grid search, I am trying to optimize (amonst others) the parameter `min_data_in_leaf`. When the value of this parameter is getting smaller, an error is launched that `feature_pre_filter=FALSE` should be set in dataset construction. However, that parameter does not exist anymore (it used to be part of the `...`, which was removed in the latest version).

Here is the message:

[LightGBM] [Fatal] Reducing `min_data_in_leaf` with `feature_pre_filter=true` may cause unexpected behaviour for features that were pre-filtered by the larger `min_data_in_leaf`.
You need to set `feature_pre_filter=false` to dynamically change the `min_data_in_leaf`.
Error in doTryCatch(return(expr), name, parentenv, handler) : 
  Reducing `min_data_in_leaf` with `feature_pre_filter=true` may cause unexpected behaviour for features that were pre-filtered by the larger `min_data_in_leaf`.
You need to set `feature_pre_filter=false` to dynamically change the `min_data_in_leaf`.

## Reprex

```{r}
library(lightgbm)

dtrain <- lgb.Dataset(
  data.matrix(iris[, c("Sepal.Length", "Petal.Length")]), 
  label = iris$Sepal.Width,
  #feature_pre_filter=FALSE
)

# Grid with decreasing min_data_in_leaf
grid <- expand.grid(
  iteration = NA,
  score = NA,
  learning_rate = 0.05,
  objective = "regression_l2",
  metric = "rmse",
  min_data_in_leaf = c(10, 5),
  stringsAsFactors = FALSE
)

for (i in seq_along(grid$iteration)) {
  cvm <- lgb.cv(
    params = as.list(grid[i, -(1:2)]),
    data = dtrain,
    nrounds = 5000,
    nfold = 5,
    early_stopping_rounds = 2,
    verbose = -1
  )
  
  grid[i, 1:2] <- as.list(cvm)[c("best_iter", "best_score")]
}
```

**Comment by jameslamb** [comment]
Thanks for the report and reproducible example, @mayer79 !

I've reduced the size of the example a bit, and can confirm the following code run on the latest commit of LightGBM (https://github.com/microsoft/LightGBM/commit/dad391574137958402bec4b417bc594fa1c5fbed) produces the error you mentioned.

```r
library(lightgbm)

dtrain <- lgb.Dataset(
  data.matrix(iris[, c("Sepal.Length", "Petal.Length")])
  , label = iris$Sepal.Width
)

cv_booster <- lgb.cv(
  params = list(
    objective = "regression_l2"
    , min_data_in_leaf = 10L
  )
  , data = dtrain
  , nrounds = 10L
  , nfold = 2L
)

# run cv again with a smaller min_data_in_leaf
cv_booster <- lgb.cv(
  params = list(
    objective = "regression_l2"
    , min_data_in_leaf = 9L
  )
  , data = dtrain
  , nrounds = 10L
  , nfold = 2L
)
```

> [LightGBM] [Fatal] Reducing `min_data_in_leaf` with `feature_pre_filter=true` may cause unexpected behaviour for features that were pre-filtered by the larger `min_data_in_leaf`.

As mentioned in https://lightgbm.readthedocs.io/en/latest/R/reference/lgb.Dataset.html#arguments, any of the Dataset-specific parameters found at https://lightgbm.readthedocs.io/en/latest/Parameters.html#dataset-parameters can be provided to `lgb.Dataset()` via that `params` list.

I tried running the same code, but just changing the `lgb.Dataset()` call to the following.

```r
dtrain <- lgb.Dataset(
  data.matrix(iris[, c("Sepal.Length", "Petal.Length")])
  , label = iris$Sepal.Width
  , params = list(
    feature_pre_filter = FALSE
  )
)
```

Using the R package built from the latest commit of LightGBM (https://github.com/microsoft/LightGBM/commit/dad391574137958402bec4b417bc594fa1c5fbed) and v3.3.2 installed from CRAN, that example works for me without any errors.

**Comment by mayer79** [comment]
The `params` argument... thanks a lot for that hint! This will solve the problem.
