### ISSUE TITLE
Effect of group_column for Regression problems using LightGBM

### ISSUE THREAD

**Issue by pidahbus** [microsoft/LightGBM#5201]
I am training a regression model using LightGBM. The issue is that I am using a complicated software (which is a wrapper over LightGBM) where I must have to pass one valid column name in the `group_column` [parameter](https://lightgbm.readthedocs.io/en/latest/Parameters.html#group_column). As `group_column` parameter is only valid for learning to rank problems, can I specify any column as `group_column` for my regression model? Kindly confirm that passing any column name in the `group_column` parameter does not have any effect on the output for regression (non learning-to-rank) problems. Thanks in advance.

**Comment by StrikerRUS** [comment]
Hey @pidahbus ! Thanks for using LightGBM!

Yes, you're right, `group_column` is used only for learning to rank problems.

**Comment by pidahbus** [comment]
Hi, @StrikerRUS thanks for the reply. Just confirming, using any column in the group_column parameter would not have any effect on the model predictions and metrics for regression (or classification) problems right?

**Comment by StrikerRUS** [comment]
Specifying a random column as `group_column` will not only increase your dataset creation time but also will exclude that column from features LightGBM is trained on.
https://github.com/microsoft/LightGBM/blob/0fb09e779e0334b6bbba944bb31c710e73146ef5/src/io/dataset_loader.cpp#L147-L167
Specifically,
https://github.com/microsoft/LightGBM/blob/0fb09e779e0334b6bbba944bb31c710e73146ef5/src/io/dataset_loader.cpp#L165

Consider checking the following proving example:
```python
import lightgbm as lgb

# data: https://github.com/microsoft/LightGBM/blob/master/examples/regression/regression.test
lgb_data = lgb.Dataset(
    data=r'C:\Users\nekit\Downloads\LightGBM\examples\regression\regression.test',
    params={'label_column': 0, 'group_column': 1}
)
lgb.train({}, lgb_data, num_boost_round=1)
```
Please note the following two lines from the logs:
```
...
[LightGBM] [Info] Using column number 1 as group/query id
...
[LightGBM] [Info] Number of data points in the train set: 500, number of used features: 27
...
```
Then remove `group_column` parameter and note that number of features will be 28 then
```
...
[LightGBM] [Info] Number of data points in the train set: 500, number of used features: 28
...
```
