### ISSUE TITLE
Initial Score Usage and Documentation

### ISSUE THREAD

**Issue by lcrmorin** [microsoft/LightGBM#5219]
I am trying to use an initial score from another model. The main goal is not to get a better score, but to rely on a widely used baseline.I lack direction on what should be used and how it affect ouptut explainability.

Regarding initial score imputation. It is unclear on what scale it should be expressed. When not imputing an initial score and using verbosity, I usually get scores that seems to be on a log scale. But it does not seems to match the log of average proba. 

1) For exemple I want to take a sklearn model output as an initial score. What should be imputed in lgbm ? predict_proba ? predict_log_proba ? something else ?

2) How does the initial score affect the ouptut ? I get conflicted message (and experimentation). Should the initial score be added to the output ? How does that initial score should be added ? (plain addition or something else ?)

3) How does the initial score affect the explainability ? I don't see many info about this online. Given contribution (trough contrib = True or from shap Tree Explainer) how do I add explainability from the initial score ? If the initial score is built on a model that have a shap explainability. Can I add both contrib ? (I reckon the last question is more about shap as an approximation of Shapley Values). 

4) How does this generally interact with imbalanced data set and setting the corresponding option to True ?

 (If anything is unclear, I have built a kaggle notebook that shows what I am trying to do: https://www.kaggle.com/code/lucasmorin/using-base-score-lgbm)

**Comment by jmoralez** [comment]
Hi @lcrmorin.

1. On binary classification tasks the init_score should be the log odds of the predicted probabilities, as you correctly do in your notebook.
2. The initial score should be added to the raw predictions of LightGBM and then converted to probabilities, which is the part you're missing in the notebook, i.e. this: `preds = special.expit(log_odds_test + clf2.predict(X_test))` should be `preds = special.expit(log_odds_test + clf2.predict(X_test, raw_score=True))`
3. When you predict the contribution you get a matrix `(n_samples, n_features + 1)` where the last column is the expected value. I believe you have to add the initial score to that column but I'm not 100% sure.
4. I don't fully understand the question nor which option you mean.

Please let us know if you have further doubts.
