### ISSUE TITLE
callbacks = [log_evaluation(0)] does not suppress outputs but verbose_eval is deprecated

### ISSUE THREAD

**Issue by Jakobhenningjensen** [microsoft/LightGBM#5241]
## Description
setting `callbacks = [log_evalutaion(0)]` does not do anything.
Setting `verbose_eval` does remove the outputs, but throws "deprecated" warning and that I should use `log_evalution` instead

I know I'm using the `optuna` "wrapper", but the error is thrown from the `lightgbm` package. Should I raise the issue by Optuna instead?

## Reproducible example
```python
import optuna
import optuna.integration.lightgbm as lgb
from lightgbm import early_stopping
from lightgbm import log_evaluation
from sklearn.model_selection import train_test_split
from sklearn.datasets import make_classification


optuna.logging.set_verbosity(optuna.logging.ERROR) #Ignore outputs from Optuna when training

X,y = make_classification(n_samples = 3_000, n_features = 3, n_informative=3, n_redundant=0,n_classes=4,weights = [0.6,0.2,0.1,0.1])


train_x, val_x, train_y, val_y = train_test_split(X, y, test_size=0.25)
dtrain = lgb.Dataset(train_x, label=train_y)
dval = lgb.Dataset(val_x, label=val_y)

params = {
    "objective": "softmax",
    "metric":"multi_logloss",
    "boosting_type": "gbdt",
    "is_unbalance":True,
    "num_classes":4,
    "num_boost_round":10,
    "verbose":-1,
    
}

model = lgb.train(
    params,
    dtrain,
    valid_sets=[dtrain, dval],
    callbacks=[log_evaluation(0),early_stopping(100,verbose=False)],
    verbose_eval=False # removing this line prints a lot of evaluation info that I want to remove

)
```
With `verbose_eval=True`

![image](https://user-images.githubusercontent.com/37367467/170231048-affdf08c-b4ab-47ae-907a-f76263bf59b8.png)

With `verbose_eval=False`:

![image](https://user-images.githubusercontent.com/37367467/170231254-f30ee40c-571c-4dc4-a054-fcb1f4f09d20.png)

## Environment info

LightGBM version or commit hash: v.3.3.2

Command(s) you used to install LightGBM

```shell
pip install lightgbm --upgrade --no-deps
```

**Comment by StrikerRUS** [comment]
@Jakobhenningjensen Hey! Thanks for raising this issue!

> Should I raise the issue by Optuna instead?

Yeah! The root cause of these warnings is on optuna side. They pass deprecated parameter `verbose_eval` which **ADDS** one more logging process.
https://github.com/optuna/optuna/blob/40b097650d312913989b5825aa9c9adf4b15c396/optuna/integration/_lightgbm_tuner/optimize.py#L392
You can see that if you pass for example `log_evalutaion(2)` without specifying `verbose_eval` in your code, output will contain duplicated lines:
```
[1]	valid_0's multi_logloss: 1.00793	valid_1's multi_logloss: 1.01777
[2]	valid_0's multi_logloss: 0.898405	valid_1's multi_logloss: 0.919014
[2]	valid_0's multi_logloss: 0.898405	valid_1's multi_logloss: 0.919014
[3]	valid_0's multi_logloss: 0.816504	valid_1's multi_logloss: 0.849246
[4]	valid_0's multi_logloss: 0.729403	valid_1's multi_logloss: 0.769757
[4]	valid_0's multi_logloss: 0.729403	valid_1's multi_logloss: 0.769757
[5]	valid_0's multi_logloss: 0.662035	valid_1's multi_logloss: 0.709658
[6]	valid_0's multi_logloss: 0.61128	valid_1's multi_logloss: 0.664647
[6]	valid_0's multi_logloss: 0.61128	valid_1's multi_logloss: 0.664647
...
```

**Comment by nzw0301** [comment]
This issue on optuna side has been resolved. I believe that the warning message doesn't appear anymore.
https://github.com/optuna/optuna/pull/3014
