### ISSUE TITLE
Substr Parameter Error

### ISSUE THREAD

**Issue by lzy960601** [microsoft/LightGBM#5242]
https://github.com/microsoft/LightGBM/blob/b0137debe6e9cc92b65ec71b0fe8a56ea213c143/src/io/parser.cpp#L161

In one line of libsvm format file, I think the last space is before the last colon.
Maybe this will be "colon_pos - space_pos - 1"?

**Comment by jameslamb** [comment]
Thanks for using LightGBM!

Are you able to provide a valid LibSVM-formatted file that LightGBMM currently fails to parse? It's very difficult for maintainers to address this concern based only on a link to a line of code.
