### ISSUE TITLE
[Help] - How to modify code to get leaf outputs

### ISSUE THREAD

**Issue by sushmit-goyal** [microsoft/LightGBM#5245]
Hey,
I am researching methods of applying domain adaptation on LightGBM. I would like to get the leaf outputs and apply some transformation in each boosting round before fitting the next tree. What would be the recommended approach to modify the source code such that I could achieve the same? I am not quite comfortable using the C API and would prefer modifying the python code even at the cost of speed. If this is not possible I could modify the C source code as well but need some help with that.

Thanks

**Comment by StrikerRUS** [comment]
You can get leaf outputs via [`LGBM_BoosterGetLeafValue()`](https://lightgbm.readthedocs.io/en/latest/C-API.html#c.LGBM_BoosterGetLeafValue) function. Then you can modify that value and set modified value back via [`LGBM_BoosterSetLeafValue()`](https://lightgbm.readthedocs.io/en/latest/C-API.html#c.LGBM_BoosterSetLeafValue) function.
