### ISSUE TITLE
Different results with almost the same inputs

### ISSUE THREAD

**Issue by pngingg** [microsoft/LightGBM#5247]
I have two inputs that were generated by C++ and Python respectively. They have little differences ( at most 9.668930e-13). 

When I feed them to the same model for prediction,  I expect the same outputs but they are not. I think the little differences cause some nodes split into different branches. 

How can I get the same results when inputs have such little differences? 

I have uploaded related files below. Could you please give me some advices on how to fix it? Thank you very much.
```
In [1]: import pandas as pd

In [2]: import lightgbm as lgb

In [3]: lgb.__version__
Out[3]: '3.3.0'

In [4]: bst = lgb.Booster(model_file="model_tree14.txt")

In [5]: df1 = pd.read_csv("test_factors.csv", header=None, names = ["factor%d" % i for i in range(468)])[bst.feature_name()]

In [6]: df2 = pd.read_csv("test_factors2.csv", header=None, names = ["factor%d" % i for i in range(468)])[bst.feature_name()]

In [7]: abs(df1 - df2).max(axis=1)
Out[7]: 
0    9.668930e-13
dtype: float64

In [8]: pd.DataFrame(bst.predict(df1))
Out[8]: 
          0         1        2
0  0.337904  0.332635  0.32946

In [9]: pd.DataFrame(bst.predict(df2))
Out[9]: 
          0         1         2
0  0.338588  0.331284  0.330128
```
[model_tree14.txt](https://github.com/microsoft/LightGBM/files/8790337/model_tree14.txt)
[test_factors.csv](https://github.com/microsoft/LightGBM/files/8790338/test_factors.csv)
[test_factors2.csv](https://github.com/microsoft/LightGBM/files/8790339/test_factors2.csv)

**Comment by shiyu1994** [comment]
@pngingg Thanks for using LightGBM. With slightly different feature values, a sample can fall in different leaves in the trees. That will cause differences in the prediction values. This is because tree ensemble is a discontinous model interanally.

**Comment by pngingg** [comment]
@shiyu1994 Hi, thanks for your reply. 

Suppose that we have two samples each with only one feature: x1 = 0, x2 = 1, and the labels are y1=0, y2=1. In the training process, a node  in a tree will decide if the feature ">=p". In the simple example, any p with 0<p<=1 will make the node do the same thing (put x1 to the left and put x2 to the right). I think p = 0.5 will be the best. Does LGBM perform like this or just choose a bound like p=1?

**Comment by shiyu1994** [comment]
@pngingg
>I think p = 0.5 will be the best. Does LGBM perform like this or just choose a bound like p=1?

Yes, in our algorithm for finding the bin boundaries
https://github.com/microsoft/LightGBM/blob/4971a06668df7eabeb7d4bb1987abb442f2970c9/src/io/bin.cpp#L144-L154
it takes the means of two continous feature values as bondaries.

However, when all the feature values are concentrated in a very small range, small changes in the feature values may cause some data points to cross the bin boundaries, causing different prediction results.

**Comment by shiyu1994** [comment]
@pngingg Thanks. Then will close this issue for now. If you have any further question, please feel free to reopen this.
