### ISSUE TITLE
inference

### ISSUE THREAD

**Issue by hepengfei-ml** [microsoft/LightGBM#5257]
Which method is recommended for model online inference? I want high performance concurrency,
PMML ?

**Comment by StrikerRUS** [comment]
It depends on your use case.

Initially, LightGBM wasn't optimized for fast predictions. Some time ago `*SingleRowFast` API was introduced: #2992. You can start with it.

Also, you can try to convert fitted model into `if/else` cpp code: https://lightgbm.readthedocs.io/en/latest/Parameters.html#convert_model.

In addition, you can find a lot of third-party libraries to inference LightGBM models here: https://github.com/microsoft/LightGBM#external-unofficial-repositories.

I'd personally recommend starting from the [`treelite`](https://github.com/dmlc/treelite) library.
