### ISSUE TITLE
lightGBM+GPU Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by wylqq312715289** [Microsoft/LightGBM#526]
Load data...
Start training...
[LightGBM] [Info] This is the GPU trainer!!
[LightGBM] [Info] Total Bins 6143
[LightGBM] [Info] Number of data: 7000, number of used features: 28
beignet-opencl-icd: no supported GPU found, this is probably the wrong opencl-icd package for this hardware
(If you have multiple ICDs installed and OpenCL works, you can ignore this message)
[LightGBM] [Info] Using GPU Device: GeForce GTX 1060 6GB, Vendor: NVIDIA Corporation
[LightGBM] [Info] Compiling OpenCL Kernel with 256 bins...
Segmentation fault (core dumped)

what can i do?

**Comment by frenzykryger** [comment]
#528 I'm facing similar problem when training on GPU and feeding sparse matrix as input.

**Comment by wylqq312715289** [comment]
@frenzykryger how to solve this problem.

**Comment by huanzhang12** [comment]
@wylqq312715289 Can you provide more information on your system and setup? Like OS version, GPU driver version, etc.

**Comment by wylqq312715289** [comment]
@huanzhang12  sys:ubuntu16.06, GPU:Nvidia GTX 1060, CPU:intel 7700K, libboost:1.58

**Comment by Laurae2** [comment]
@wylqq312715289 if you are using NVIDIA proprietary drivers then do not use Beignet.

**Comment by wylqq312715289** [comment]
@Laurae2   I had execute $ sudo apt-get autoremove --purge  beignet-opencl-icd and reset cmake -DUSE_GPU=1 ..

**Comment by wylqq312715289** [comment]
@Laurae2 I had execute $ sudo apt-get autoremove --purge beignet-opencl-icd and reset 
$ cmake -DUSE_GPU=1 ..
$ make -j 
$ python setup.py install 
but the "Segmentation fault (core dumped)" alse returned

**Comment by huanzhang12** [comment]
Can you run some other OpenCL programs to test if your driver/setup is good?
You can try to compile and run CLPeak https://github.com/krrishnarraj/clpeak.git and see if it works for you.

**Comment by wylqq312715289** [comment]
$ dmesg
return :
traps: python[12887] general protection ip:7fbf8a7e9793 sp:7fbfa289d590 error:0 in libboost_filesystem.so.1.58.0[7fbf8a7da000+17000]

**Comment by huanzhang12** [comment]
@wylqq312715289 Try to remove the macro BOOST_COMPUTE_USE_OFFLINE_CACHE in `gpu_tree_learner.h`, line 26: https://github.com/Microsoft/LightGBM/blob/master/src/treelearner/gpu_tree_learner.h#L26

**Comment by wylqq312715289** [comment]
@huanzhang12  right, thank you.
