### ISSUE TITLE
getting number of iterations from lgb.cv

### ISSUE THREAD

**Issue by ironv** [microsoft/LightGBM#5270]
I am running 200 trials of a hyperpram search using `Optuna` with `lightgbm`.  The call within Objective looks like this

```
    def f1_eval(preds,dtrain):
      preds = preds.reshape(self.nclass,-1).T
      f_score = f1_score(dtrain.get_label(),preds.argmax(axis=1),average="micro")
      return "f1_score",f_score,True
    
    early_stop = lgb.early_stopping(20, first_metric_only=False, verbose=False)
    eval_hist = lgb.cv(lgb_prm, dtrain, seed=12345, num_boost_round=200, 
                            feval=f1_eval, callbacks=[early_stop])
    return eval_hist["f1_score-mean"][-1]
```

Later based on the "best" set of params I am retraining one final model as shown below.
```
    model_init = lgb.train(lgb_prm, dtrain, num_boost_round=50, feval=None)
    early_stop = lgb.early_stopping(20, first_metric_only=False, verbose=False)
    model = lgb.train(lgb_prm, dtrain, valid_sets=[dvalid], num_boost_round=150, 
                          init_model=model_init, feval=f1_eval, callbacks=[early_stop])
```

By default, lgb.cv using 5-way x-val and my train/valid split has similar sizes.  I am requiring my final training run to go at least 50 iterations before early_stop can be invoked!

Is there a way to get the average number of iterations (based on the early stop) for the 5 x-val runs so that I can use that instead of the 50?

**Comment by ironv** [comment]
Looks like I can get this info by setting `return_cvbooster=True` and this to record as part of the trial `trial.set_user_attr("niter", np.sort(eval_hist["cvbooster"].num_trees())[3])`.  I am finding it odd that niter is coming out to be 293 even though `num_boost_round=200`.

**Comment by jmoralez** [comment]
Hi @ironv, thank you for your interest in LightGBM. After you set `return_cvbooster=True` you can access the best iteration as `eval_hist["cvbooster"].best_iteration`, because the `num_trees()` method will return the total number of iterations instead of the best one, i.e. will not take into account the early stopping.

Please let us know if this helps.
