### ISSUE TITLE
Run tests with ClangCL and Visual Studio on our CI services

### ISSUE THREAD

**Issue by StrikerRUS** [microsoft/LightGBM#5280]
Created in the response to #5259.

**Comment by StrikerRUS** [comment]
Closed in favor of being in https://github.com/microsoft/LightGBM/issues/2302. We decided to keep all feature requests in one place.

Welcome to contribute this feature! Please re-open this issue (or post a comment if you are not a topic starter) if you are actively working on implementing this feature.

**Comment by jameslamb** [comment]
Sorry, this was locked accidentally. Just unlocked it. We'd still love help with this feature!
