### ISSUE TITLE
Segmentation Fault with Dill pickling library

### ISSUE THREAD

**Issue by chrisdonlan** [microsoft/LightGBM#5293]
## Description
Lightgbm fails to serialize with a segmentation fault 11 after recent version upgrades after training on a subset of data, but not when trained on more data. 

## Reproducible example
```
from lightgbm import LGBMClassifier
clf = LGBMClassifier()
clf.fit(my_dataset)

import dill
with open("output.pkl", 'wb+") as out:
    dill.dump(clf)
```
Unfortunately, I can't share my data, as it belongs to my employer.

## Environment info

LightGBM version or commit hash:

`3.2.1`

Command(s) you used to install LightGBM

```shell
python3 -m pip install lightgbm
```

## Additional Comments

It used to only happen on MacOSX. Now it happens on both Mac and Linux. It is important that LGBM supports pickle, as I will have to drop the library otherwise. 

I am searching for the version of lightgbm which works.

**Comment by jameslamb** [comment]
Thanks for taking the time to come back and explain why you closed this, @chrisdonlan !
