### ISSUE TITLE
【机器学习】jupyter中导入模型后怎么显示默认参数？

### ISSUE THREAD

**Issue by GCYMZL** [microsoft/LightGBM#5295]
显示结果：
![image](https://user-images.githubusercontent.com/51354123/173989399-0879560e-98a7-4226-84b2-5355312cc654.png)

期望结果：
![image](https://user-images.githubusercontent.com/51354123/173989446-93c6a959-da7d-47cb-af60-ff7ede2f6f04.png)

**Comment by jameslamb** [comment]
Thank you for using LightGBM!

I cannot read Chinese, but according to Google Translate this issue's title roughly translates to *"How to display default parameters after importing a model"*.

You haven't provided much code so it is difficult for maintainers to help answer this question. I've provided a few possible answers below.

* to see the default values used by LightGBM's core C/C++ code, see https://lightgbm.readthedocs.io/en/latest/Parameters.html
* to see the default values used in the LightGBM Python package, see https://lightgbm.readthedocs.io/en/latest/Python-API.html
* to view the parameters that a `lightgbm.LGBMClassifier` instance was configured with, use `.get_params()`

```python
import lightgbm as lgb
from sklearn.datasets import make_blobs

X, y = make_blobs(n_samples=1234, centers=[[-4, -4], [-4, 4]])
clf = lgb.LGBMClassifier(num_iterations=10, subsample=0.5)
clf.fit(X, y)
clf.get_params()
```

I hope that one of these suggestions answers your question. @guolinke or @shiyu1994 could you please double-check this, in case Google Translate wasn't correct or I've misunderstood the question?

**Comment by StrikerRUS** [comment]
I *guess* @GCYMZL wants to get params of `Booster` the same way they are printed out for classes in the sklearn wrapper.
You can use `params` property of the `Booster` class.

Add the following line in @jameslamb's example above

```python
clf.booster_.params
```

**Comment by shiyu1994** [comment]
@jameslamb @StrikerRUS Thanks for your answering! I believe both of you provide expected approaches. @GCYMZL could you please check these methods? Thanks.
