### ISSUE TITLE
Prediction outside prediction interval with LGBMRegressor

### ISSUE THREAD

**Issue by masakljun** [microsoft/LightGBM#5296]
## Description
I am using LGBMRegressor to obtain predictions and prediction intervals as suggested in an article https://developer.ibm.com/articles/prediction-intervals-explained-a-lightgbm-tutorial/. However, the issue I am having is that the predicted point (with alpha set to 0.5) is sometimes outside the prediction interval (alpha = 0.05 and alpha = 0.95). I suppose this is due to the issue of "crossing quantiles", however, I am wondering if there is any fix for this? Thanks in advance!

## Reproducible example
Can't share data due to data policy at company.
```
reg = lgb.LGBMRegressor(objective = 'quantile', alpha = 0.5, learning_rate = 0.05, max_depth = 15, n_estimators = 900, random_state = 0).fit(X_train, y_train)

lower = lgb.LGBMRegressor(objective = 'quantile', alpha = 0.05, learning_rate = 0.05, max_depth = 15, n_estimators = 900, random_state = 0).fit(X_train, y_train)

upper = lgb.LGBMRegressor(objective = 'quantile', alpha = 0.95, learning_rate = 0.05, max_depth = 15, n_estimators = 900, random_state = 0).fit(X_train, y_train)
```

## Environment info

LightGBM version or commit hash:
'3.3.2'

Command(s) you used to install LightGBM
`pip install lightgbm`

**Comment by jmoralez** [comment]
We already have this as a feature request in #3447 and #4201. The problem is described here: https://github.com/microsoft/LightGBM/issues/3447#issuecomment-819399569
