### ISSUE TITLE
distributed trainning with DASK

### ISSUE THREAD

**Issue by ysong2123** [microsoft/LightGBM#5305]
## Summary

distributed trainning with DASK. 

## Description

there's only one  sample with local cluster:
cluster = LocalCluster(n_workers=2)
    client = Client(cluster)
could you team provide more details about how to allocate DASK data into an on-prem or cloud cluster and train by lgb.DaskLGBMRegressor?

**Comment by jameslamb** [comment]
> could you team provide more details

Thanks for your interest in LightGBM! This project has the following sources of documentation relevant to your question:

* how to configure `lgb.DaskLGBMRegressor`: https://lightgbm.readthedocs.io/en/latest/pythonapi/lightgbm.DaskLGBMRegressor.html#lightgbm.DaskLGBMRegressor
* how to perform distributed training with Dask: https://lightgbm.readthedocs.io/en/latest/Parallel-Learning-Guide.html#dask
* sample code which uses `lightgbm.dask`: https://github.com/microsoft/LightGBM/tree/master/examples/python-guide/dask

If you have additional questions after reading these, please leave a comment here with *specific* questions, and we'd be happy to help.

**Comment by StrikerRUS** [comment]
@ysong2123 
> into an on-prem or cloud cluster

Here is an example for Saturn Cloud provider written by @jameslamb some time ago: https://github.com/saturncloud/workshop-lightgbm-dask/blob/main/01-lightgbm.ipynb

Also, the following repo might be what you're searching for: https://github.com/jameslamb/lightgbm-dask-testing.
