### ISSUE TITLE
LightGBM crashes silently if Pytorch is imported

### ISSUE THREAD

**Issue by rickdzekman** [microsoft/LightGBM#5315]
## Description

Trying to run `lgb.train()` crashes if Pytorch is imported in the same notebook. This crash happens silently with no errors given.

## Reproducible example

I ran this in a Juypter Lab notebook:

```
import torch # <--- comment this line out and it no longer crashes

import pandas as pd
from sklearn.preprocessing import LabelEncoder

import lightgbm as lgb

labelencoder = LabelEncoder()
X_train = pd.DataFrame({'x_1': [0,1,2,3,4,5,6,7], 'x_2':[100,500,300,400,1000,20,500,300], 'label': ['Y','N','N','Y','Y','N','N','Y']})
y_train = labelencoder.fit_transform(X_train['label'])
X_train = X_train[['x_1','x_2']]

train_data = lgb.Dataset(X_train, label=y_train)

num_round = 100
param = {    
    'objective': 'binary', 
    'metric': 'binary_logloss',
    
    'verbosity': 0
}

clf = lgb.train(param, train_data, num_round)
```

## Environment info

LightGBM version or commit hash: 3.3.2

Command(s) you used to install LightGBM

```shell
pip3 install lightgbm
```

MacOS Big Sur, Python 3.10

**Comment by jmoralez** [comment]
Hi @rickdzekman. I think this could be related to #4897, could you check your `libomp` version?

**Comment by rickdzekman** [comment]
My `libomp` version is:  `stable 13.0.1 (bottled)`

**Comment by jmoralez** [comment]
Thanks @rickdzekman, that's probably the reason. You can find two possible solutions here: https://github.com/microsoft/LightGBM/issues/4897#issuecomment-998349622
