### ISSUE TITLE
Check failed: (best_split_info.left_count) > (0) when using the ''cegb_penalty_feature_coupled'' parameter

### ISSUE THREAD

**Issue by ZhangTP1996** [microsoft/LightGBM#5317]
## Description

[LightGBM] [Fatal] Check failed: (best_split_info.left_count) > (0) at /__w/1/s/python-package/compile/src/treelearner/serial_tree_learner.cpp, line 653 .

## Reproducible example

The error happens when I use the "cegb_penalty_feature_coupled" parameter. If we remove the parameter, the error disappears.
A minimal example to reproduce the error:
```
import lightgbm as lgb
import pandas as pd

X = pd.read_csv('./cegb_X.csv', index_col=0)
y = pd.read_csv('./cegb_Y.csv', index_col=0)
params = {"n_estimators": 1000, "importance_type": "gain", "num_leaves": 64,
          "cegb_penalty_feature_coupled": [1 for _ in range(X.shape[1])],
          "seed": 1, "n_jobs": 40}
gbm = lgb.LGBMRegressor(**params)
gbm.fit(X, y)
```
[cegb_X.csv](https://github.com/microsoft/LightGBM/files/8956918/cegb_X.csv)
[cegb_Y.csv](https://github.com/microsoft/LightGBM/files/8956919/cegb_Y.csv)

**Comment by ZhangTP1996** [comment]
The problem is fixed by installing the latest version 3.3.2.99

**Comment by jameslamb** [comment]
Thanks very much for coming back to close this!

I suspect the issue you faced was the same as #3679, which was fixed in #5164.

**Comment by jameslamb** [comment]
And thank you very much for providing a reproducible example, it's greatly appreciated 😊

**Comment by ZhangTP1996** [comment]
> And thank you very much for providing a reproducible example, it's greatly appreciated 😊

You are welcome 😊
