### ISSUE TITLE
can swig of lgbm support golang？

### ISSUE THREAD

**Issue by zhuangAnjun** [microsoft/LightGBM#5319]
## Description

can swig of lgbm support golang？

**Comment by jameslamb** [comment]
Thanks for your interest in LightGBM!

This project does not ship any official golang releases. The SWIG code here is primarily used for generating an interface to LightGBM for JVM languages.

https://github.com/dmitryikh/leaves is a Go project that supports scoring with an existing LightGBM model...maybe there will be some useful information in that project you could use.

According to https://www.swig.org/Doc3.0/Go.html#Go_running_swig, it is possible to use SWIG to generate a Go interface to C/C++ code, so I guess it might be possible...but not something we support or have tested.

We cannot take on support of an official LightGBM Go wrapper at this time, but if you try to generate one using SWIG and find small changes which might make that easier, we'd welcome pull requests. And if you do get it working, please come back to this issue and post a comment, so others finding this discussion from search engines can benefit from what you learn.
