### ISSUE TITLE
GPU version train error

### ISSUE THREAD

**Issue by caohaox** [Microsoft/LightGBM#532]
Please search your question on previous issues, stackoverflow or other search engines before you open a new one.

For bugs and unexpected issues, please provide following information, so that we could reproduce on our system.

## Environment info
Operating System:linux
CPU:
C++/Python/R version:

## Error Message:
~/DMTK/LightGBM$ ./lightgbm config=lightgbm_gpu.conf data=higgs.train valid=higgs.test objective=binary metric=auc
[LightGBM] [Info] Finished loading parameters
[LightGBM] [Info] Finished loading data in 12.825387 seconds
[LightGBM] [Info] Number of positive: 5564616, number of negative: 4935384
[LightGBM] [Info] This is the GPU trainer!!
[LightGBM] [Info] Total Bins 1535
[LightGBM] [Info] Number of data: 10500000, number of used features: 28
Met Exceptions:
No OpenCL device found
## Steps to reproduce

1.
2.
3.
export LIBRARY_PATH=/usr/local/cuda/lib64:$LIBRARY_PATH

**Comment by Laurae2** [comment]
@caohaox do you have a GPU?

If yes:

* Which one?
* Do you have the same issue with other datasets?
