### ISSUE TITLE
Categorical Features in Booster object 

### ISSUE THREAD

**Issue by MayankKr8** [microsoft/LightGBM#5321]
## Summary

Unable to find the datatypes of features used in lightgbm booster object in python.

## Motivation

This would help set the datatypes more easily for validation and prediction datasets 

## Description

 I have been working with lightgbm Booster objects by loading already saved models from filespace.  I want the process of setting the data types of the validation dataset to be more automated. At the current stage, I can't find any attribute or method that helps fetch the categorical features of the booster, but only the names of all features used.  Since if there's a mismatch in categorical features used the model would fail in predicting and raises the specific exception of mismatch, I am hoping this information is already present in the booster object, it would be only logical to expose this information.

**Comment by jmoralez** [comment]
Hi @MayankKr8, thank you for your interest in LightGBM. This is a known issue and is documented in #2613 and there's an ongoing effort to read the parameters from the saved booster in #4802, you can subscribe to that PR if you're interested in following the progress.
