### ISSUE TITLE
can't find lib_lightgbm.dll

### ISSUE THREAD

**Issue by CWJ666** [microsoft/LightGBM#5335]
## Description

I encountered this situation：
``` python
Python 3.8.13 (default, Mar 28 2022, 06:59:08) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>import lightgbm
['D:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\lightgbm\\lib_lightgbm.dll']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\ProgramData\Anaconda3\envs\test\lib\site-packages\lightgbm\__init__.py", line 8, in <module>
    from .basic import Booster, Dataset, Sequence, register_logger
  File "D:\ProgramData\Anaconda3\envs\test\lib\site-packages\lightgbm\basic.py", line 126, in <module>
    _LIB = _load_lib()
  File "D:\ProgramData\Anaconda3\envs\test\lib\site-packages\lightgbm\basic.py", line 117, in _load_lib
    lib = ctypes.cdll.LoadLibrary(lib_path[0])
  File "D:\ProgramData\Anaconda3\envs\test\lib\ctypes\__init__.py", line 451, in LoadLibrary
    return self._dlltype(name)
  File "D:\ProgramData\Anaconda3\envs\test\lib\ctypes\__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'D:\ProgramData\Anaconda3\envs\test\lib\site-packages\lightgbm\lib_lightgbm.dll' (or one of its dependencies). Try using the full path with constructor syntax.
```
['D:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\lightgbm\\lib_lightgbm.dll'] is result that i added `print(lib_path)` before `lib = ctypes.cdll.LoadLibrary(lib_path[0])` in lightgbm\basic.py

The compilation process is based on the [lightgbm gpu version for windows](https://lightgbm.readthedocs.io/en/latest/Installation-Guide.html#build-gpu-version) process:
>vs 2019, boost 1_71_0, cuda 11.2 , lightgbm gpu version

I have tried looking for a solution to the problem and I found this thing with dll dependency walker in lib_lightgbm.dll: my computer miss many dll dependencies!

but when i `python setup.py install` and `import lightgbm`, the above problem disappeared!

this problem may be similar to #499.

## Environment info

LightGBM version or commit hash:

Command(s) you used to install LightGBM

```shell
git clone --recursive https://github.com/microsoft/LightGBM
cd LightGBM
mkdir build
cd build
cmake -DUSE_GPU=1 -DOpenCL_LIBRARY=D:/ProgramData/CUDA TOOLS/cuda11.2/lib DOpenCL_INCLUDE_DIR=D:/ProgramData/CUDA TOOLS/cuda11.2 ..
cmake --build . --target ALL_BUILD --config Release
cd ../python-package
python setup.py install gpu
```

## Additional Comments

my computer: win10, RTX 3080 gpu

**Comment by jameslamb** [comment]
Thanks for using LightGBM!

When I was answering a similar question in #5261 last night (https://github.com/microsoft/LightGBM/issues/5261#issuecomment-1178502774) I didn't realize that what you'd posted there was directly related to this issue.

Since I've already provided an answer there, let's close this issue and focus discussion in #5261.
