### ISSUE TITLE
[python-package] converting model trained in native api to sklearn api

### ISSUE THREAD

**Issue by 123Kudo** [microsoft/LightGBM#5351]
Hi, do we have a way to load the model trained using native API using the sklearn API and turn the object into a sklearn estimator ?

**Comment by jameslamb** [comment]
Thanks for your interest in LightGBM!

Unfortunately, creating a scikit-learn estimator from a `lightgbm.Booster` in this project's Python package is not supported. Just like other estimators in the `scikit-learn` ecosystem, classes like `LGBMClassifier` do some significant work during `.fit()`.

See the code in https://github.com/microsoft/LightGBM/blob/a5b2e049011da6a9b772116c5dde8174986b0bab/python-package/lightgbm/sklearn.py#L1022 to see the properties that are set during `LGBMClassifier.fit()`.

If you absolutely need to do this, you could try creating an instance of one of the `lightgbm` scikit-learn estimators and setting all the relevant attributes, like in the following example.

```python
import lightgbm as lgb
import numpy as np
from sklearn.datasets import make_blobs

X, y = make_blobs(n_samples=1234, centers=[[-4, -4], [-4, 4]])

# train and create a Booster
bst = lgb.train(
    train_set = lgb.Dataset(X, y),
    params = {
        "objective": "binary",
        "num_iterations": 10,
        "verbose": 0
    }
)

# create an LGBMClassifier from the Booster
clf = lgb.LGBMClassifier(**bst.params)
clf._Booster = bst
clf.fitted_ = True
clf._n_classes = 2
clf._n_features = bst.num_feature()
clf._le = lgb.sklearn._LGBMLabelEncoder().fit(y)
clf._class_map = dict(zip(clf._le.classes_, clf._le.transform(clf._le.classes_)))

# test that predictions are the same
booster_preds = bst.predict(X, raw_score=True)
sklearn_preds = clf.predict(X, raw_score=True)
np.testing.assert_equal(booster_preds, sklearn_preds)
```

However, please note that while this is *possible*, **this behavior is not supported**. There is significant room for error in doing this, and you should assume that we may make changes at any time that breaks this pattern by re-arranging internal implementation details.

**Comment by peiji1981** [comment]
> Thanks for your interest in LightGBM!
> 
> Unfortunately, creating a scikit-learn estimator from a `lightgbm.Booster` in this project's Python package is not supported. Just like other estimators in the `scikit-learn` ecosystem, classes like `LGBMClassifier` do some significant work during `.fit()`.
> 
> See the code in
> 
> https://github.com/microsoft/LightGBM/blob/a5b2e049011da6a9b772116c5dde8174986b0bab/python-package/lightgbm/sklearn.py#L1022
> 
> to see the properties that are set during `LGBMClassifier.fit()`.
> If you absolutely need to do this, you could try creating an instance of one of the `lightgbm` scikit-learn estimators and setting all the relevant attributes, like in the following example.
> 
> ```python
> import lightgbm as lgb
> import numpy as np
> from sklearn.datasets import make_blobs
> 
> X, y = make_blobs(n_samples=1234, centers=[[-4, -4], [-4, 4]])
> 
> # train and create a Booster
> bst = lgb.train(
>     train_set = lgb.Dataset(X, y),
>     params = {
>         "objective": "binary",
>         "num_iterations": 10,
>         "verbose": 0
>     }
> )
> 
> # create an LGBMClassifier from the Booster
> clf = lgb.LGBMClassifier(**bst.params)
> clf._Booster = bst
> clf.fitted_ = True
> clf._n_classes = 2
> clf._n_features = bst.num_feature()
> clf._le = lgb.sklearn._LGBMLabelEncoder().fit(y)
> clf._class_map = dict(zip(clf._le.classes_, clf._le.transform(clf._le.classes_)))
> 
> # test that predictions are the same
> booster_preds = bst.predict(X, raw_score=True)
> sklearn_preds = clf.predict(X, raw_score=True)
> np.testing.assert_equal(booster_preds, sklearn_preds)
> ```
> 
> However, please note that while this is _possible_, **this behavior is not supported**. There is significant room for error in doing this, and you should assume that we may make changes at any time that breaks this pattern by re-arranging internal implementation details.

how about fit one round after load the init_model as follow codes:



model = lgb.LGBMClassifier(n_estimators=100)
model.fit(X, y)
model2 = lgb.LGBMClassifier(n_estimators=1)
model2.fit(X, y, init_model=model.booster_)

**Comment by jameslamb** [comment]
(re-opening to address @peiji1981 's question)

> how about fit one round after load the init_model

That *could* work, but the same caution applies to that approach as well. That is not an officially-supported pattern, which means that it could be broken at any point by changes in this project, and that maintainers wouldn't necessarily consider inconsistencies caused by that approach "bugs".
