### ISSUE TITLE
predict return the probability of which class?

### ISSUE THREAD

**Issue by luigif2000** [microsoft/LightGBM#5352]
Dear,
I'm so sorry but it need to know exactly the probability of which class return the predit method??
I explain better:
1) i save model
2) load model
3) use predict
and the predict method return an array with some probability and the name of the column are 0=ZERO!?!?!?
this is the probability of which class? class zero or class one (BINARY CLASSIFICATION OF COURSE)
Please could someone help and return the exact solution?
thanks a lot in advance and waiting

**Comment by jmoralez** [comment]
Hi @luigif2000, thank you for your interest in LightGBM. Assuming you're using the training interface, when you call `predict` you get the probabilities of the class one, i.e. the probability of your case being positive. If you have further doubts please post a [minimal reproducible example](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

**Comment by luigif2000** [comment]
Dear, thanks thanks thanks !

best regards

luigi

Il giorno mar 12 lug 2022 alle ore 01:15 José Morales <
***@***.***> ha scritto:
