### ISSUE TITLE
Mapping of categorical features to integers

### ISSUE THREAD

**Issue by sh0gg0th** [microsoft/LightGBM#5355]
My dataset doesn't fit in memory, so I'm doing a manual mapping of Pandas `str` types to integers. For best efficiency, where I have a lot of categories, should I map all strings consistently across columns  - e.g. if I have a string `a` appearing in columns 1 and 2, should I make sure that all `a`s resolve to the same value - say `0` - across all columns, or should I always start the mapping for a new column from zero and keep the mapping consistent only within the column, like when `a` always maps to `0` in column 1 but always maps to say `1` in column 2?

**Comment by jmoralez** [comment]
Hi @sh0gg0th, thank you for your interest in LightGBM. When training LightGBM only sees the numbers so it won't know which one was `a` originally, so the second option you described is the best one, start the mapping of each column from zero and use consecutive integers. If memory is a concern I'd suggest using float32 numpy arrays or having a single data type dataframe. In case your data still doesn't fit in memory you can take a look at the [HDF5 example](https://github.com/microsoft/LightGBM/blob/273c9b043e11b24a95e40f99ef81c4888d2089c9/examples/python-guide/dataset_from_multi_hdf5.py).

Please let us know if you have further doubts.

**Comment by sh0gg0th** [comment]
Thanks a lot @jmoralez! Ok I'll go with my second option then, and I'm already using the HDF5 interface.
