### ISSUE TITLE
How to build the python package after building LightGBM (MPI version) from source?

### ISSUE THREAD

**Issue by samfux84** [microsoft/LightGBM#5375]
Hi,

I have just built the MPI version of LightGBM and now I would like to build the Python package using the library that I just built.

Is this possible or will building the Python package again build LightGBM instead of using the library that I provide?

This is somehow not obvious from the documentation.

Best regards

Sam

**Comment by jameslamb** [comment]
Thanks for using LightGBM!

If you've built `lib_lightgbm.so` from source, you can use it in the Python package by running the following.

```shell
cd python-package
python setup.py install --precompile
```

As described in https://github.com/microsoft/LightGBM/tree/master/python-package#install-from-github.

**Comment by samfux84** [comment]
@jameslamb Thank you for your help. This is exactly what I was looking for.

Sorry for overlooking it in the documentation.

Best regards

Sam

**Comment by jameslamb** [comment]
No problem! It's easy to miss, there is a lot of documentation there.

Thanks for using LightGBM 👋
