### ISSUE TITLE
[R-package] Make saveRDS usable in R

### ISSUE THREAD

**Issue by sebffischer** [microsoft/LightGBM#5376]
## Summary
Is it possible to make `saveRDS` usable with lightgbm models?

## Motivation
It is quite annoying to not be able to use `saveRDS`

**Comment by jameslamb** [comment]
Thanks for using LightGBM!

Support for saving boosters with `saveRDS()` and loading them with `readRDS()` was added in #4685. That functionality has not made it into a release yet, so to use it you'll have to build the package from source.

```shell
git clone --recursive https://github.com/microsoft/LightGBM.git
cd LightGBM
sh build-cran-package.sh
R CMD INSTALL ./lightgbm_3.3.2.99.tar.gz
```

**Comment by sebffischer** [comment]
that is great to hear, thanks!
