### ISSUE TITLE
[R-package] init_model should accept booster

### ISSUE THREAD

**Issue by sebffischer** [microsoft/LightGBM#5377]
## Summary

It would be great if one could pass the lgb.Booster directly as `init_model` and not have to save it to disk first.

**Comment by jameslamb** [comment]
Thanks for your interest in LightGBM!

It is possible to pass an `lgb.Booster` model into `lgb.train()` as `init_model` without saving it to disk.

The following minimal example works on the latest released version (v3.3.2) and on the latest development version (https://github.com/microsoft/LightGBM/commit/44fe591a60d7427d64997c37b22768a92c97c47b).

```r
library(lightgbm)

data(agaricus.train, package = "lightgbm")

dtrain <- lgb.Dataset(
    agaricus.train$data
    , label = agaricus.train$label
    , free_raw_data = FALSE
)

initial_model <- lightgbm::lgb.train(
    data = dtrain
    , params = list(
        objective = "binary"
        , num_iterations = 10L
    )
)

new_model <- lightgbm::lgb.train(
    init_model = initial_model
    , data = dtrain
    , params = list(
        objective = "binary"
        , num_iterations = 17
    )
)
new_model$current_iter()
# 27
```

In the future, when you open issues here please provide the information asked for in the issue template. Including:

* version of LightGBM + how you installed it
* version of R
* [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) demonstrating specifically what you are asking about.

**Comment by sebffischer** [comment]
Thanks, what threw me off here were the docs (version 3.2.2)

```
init_model: path of model file of ‘lgb.Booster’ object, will continue
          training from this model
```

**Comment by jameslamb** [comment]
ha! that should say "OR" lgb.Booster not "OF" .

Would you like to open a pull request fixing that in the documentation?

**Comment by sebffischer** [comment]
Sure, will do it tomorrow :)
