### ISSUE TITLE
[R-package] R build for CUDA

### ISSUE THREAD

**Issue by asheetal** [microsoft/LightGBM#5378]
https://lightgbm.readthedocs.io/en/latest/R/index.html

There does not seem any option to build a CUDA version for R package. Is it possible to have multiple GPU support via CUDA build?

**Comment by jameslamb** [comment]
> There does not seem any option to build a CUDA version for R package

That's correct, there isn't currently a CUDA build for the R package. We have an existing feature request for adding such support in the CRAN-style package (#3465) but don't have an equivalent feature request for the CMake-based build.

I've added this request to #2302, where we track feature requests for this repo. Per our policy on feature requests, I'll close this in a few days whenever the active conversation on it stops.

It would be great to have support for building the CUDA-based version of the R package using a similar approach to the one documented at https://lightgbm.readthedocs.io/en/latest/R/index.html#installing-a-gpu-enabled-build for the OpenCL-based builds. Are you interested in trying to contribute such a feature?

If not, you can subscribe to this issue to watch for updates, in case someone attempts to add it in the future.

**Comment by jameslamb** [comment]
Sorry, this was locked accidentally. Just unlocked it. We'd still love help with this feature!
