### ISSUE TITLE
[python-sklearn] Is there any way to print the training log during training as before? 

### ISSUE THREAD

**Issue by lj976264709** [microsoft/LightGBM#5380]
## Description

[44fe591](https://github.com/microsoft/LightGBM/commit/44fe591a60d7427d64997c37b22768a92c97c47b)

I can't see the training log when training,(`eval_set=[(train_x, train_y)]` )

Is there any way to print the training log during training as before?

Such as:
[1]     training's binary_logloss: -0.0276216   training's focal_loss: 0.00275511
[2]     training's binary_logloss: -0.0636605   training's focal_loss: 0.00258841
[3]     training's binary_logloss: -0.0971508   training's focal_loss: 0.00243332
...

## Reproducible example

```
    clf = LGBMClassifier(
        learning_rate=config_save['LGBMConfig']['learning_rate'],
        n_estimators=config_save['LGBMConfig']['n_estimators'],
        num_leaves=config_save['LGBMConfig']['num_leaves'],
        subsample=config_save['LGBMConfig']['subsample'],
        colsample_bytree=config_save['LGBMConfig']['colsample_bytree'],
        random_state=config_save['LGBMConfig']['random_state'],
        metric=None,
        objective=focal_loss_lgb,
    )
    print('************** training **************')
    clf.fit(
        train_x, train_y,
        sample_weight = np.sum(train_x,axis=1),
        eval_set=[(train_x, train_y)],
        eval_metric=focal_loss_lgb_eval,
        # verbose=1  #TypeError: fit() got an unexpected keyword argument 'verbose'
    )
```

## Environment info

LightGBM version or commit hash:
[44fe591](https://github.com/microsoft/LightGBM/commit/44fe591a60d7427d64997c37b22768a92c97c47b)
Command(s) you used to install LightGBM
`python setup.py install`
```shell

```

**Comment by shiyu1994** [comment]
@lj976264709 Thanks for using LightGBM. We have changed our API and now the logging during training can be done with `log_evaluation` callback, see
https://lightgbm.readthedocs.io/en/latest/pythonapi/lightgbm.log_evaluation.html#lightgbm.log_evaluation

**Comment by lj976264709** [comment]
Thanks a lot！
