### ISSUE TITLE
Re-Activate Laurae++ interactive documentation

### ISSUE THREAD

**Issue by takashioya** [microsoft/LightGBM#5385]
Hi, 

[Laurae++ interactive documentation](https://sites.google.com/view/lauraepp/parameters) which I know extremely helpful seems not available. 😢 😢 😢  
This great link is listed in [the documentation of LightGBM](https://lightgbm.readthedocs.io/en/latest/Parameters.html). 

@Laurae2  Could you check this issue and re-activate this app? I truly love this documentation and I'm sure this is the best one in the world. It's a great loss for all humanity. 😢 😢 😢

**Comment by jameslamb** [comment]
Thanks for letting us know that the app is down.

LightGBM's maintainers do not own that service, so unfortunately I can't tell you that we'll get it back up. I'll mark this `awaiting response`. If we don't hear from @Laurae2 in the next 30 days, this issue will automatically be closed and at that time I'll remove the `Laura++` links from LightGBM's documentation.

**Comment by Laurae2** [comment]
@takashioya It seems the service I was using was taken down for overusage.

I'll redevelop a new one (and ideally update the content if I have time to update).
