### ISSUE TITLE
[ci] Azure Linux jobs not running

### ISSUE THREAD

**Issue by jameslamb** [microsoft/LightGBM#5387]
## Description

Since around July 17, this project's CI has been broken.
Specifically, `Linux` and `Linux_Latest` jobs running in Azure DevOps have been stuck in "queued" indefinintely.

![image](https://user-images.githubusercontent.com/7608904/180844981-50f088fe-2d70-4362-9a85-84da5771c3ca.png)

## Reproducible example

This was first observed in https://github.com/microsoft/LightGBM/pull/5362#issuecomment-1186592726, but affects all pull requests and commits to `master`.

## Environment info

These jobs run on a dedicated Azure node pool that Microsoft pays for.

Azure DevOps is refusing to schedule CI jobs onto the nodes in that pool because the pool's authentication information has expired (https://github.com/microsoft/LightGBM/pull/5362#issuecomment-1188606982).

![image](https://user-images.githubusercontent.com/7608904/180845795-927731fe-df2b-4dbb-92c8-e8fcbad1bdf4.png)

Only Microsoft-employed maintainers have administrative access to this node pool, and those maintainers apparently do not have access to update the pool's security settings  (https://github.com/microsoft/LightGBM/pull/5362#issuecomment-1192779688) .

## Additional Comments

This project's CI will continue to be blocked until @shiyu1994 gets assistance from whoever inside Microsoft has the power to update that node pool.

Opening this issue since it's now been more than a week that we've been facing this problem, and so that comments in pull request reviews and other issues can link to this instead of needing to link to the first PR where we happened to notice the problem (#5362).

**Comment by shiyu1994** [comment]
The issue has been resolved. Now the Linux agent for CI tests on Azure DevOps is available. I'm going to close this. Thanks!

**Comment by jameslamb** [comment]
@shiyu1994 thanks for the help!

But let's please not close this until we actually see a successful build on Azure DevOps.

When I look at https://dev.azure.com/lightgbm-ci/lightgbm-ci/_build?definitionId=1&_a=summary, all builds since July 15 have failed.

I've just pushed a commit to #5388 (which fixes the other issue blocking the project's CI). If that has a successful Azure build, I'll come back and close this.

**Comment by jameslamb** [comment]
I just observed a full, successful run of Azure CI jobs, so I think this can be closed.

https://dev.azure.com/lightgbm-ci/lightgbm-ci/_build/results?buildId=13155&view=results

thanks for the help @shiyu1994 

If you have time today, please do look at #5388 , which fixes the other issues currently blocking all CI.
