### ISSUE TITLE
[test] python Dask test fails

### ISSUE THREAD

**Issue by shiyu1994** [microsoft/LightGBM#5392]
## Description
Today ci jobs fail on the following tests
![image](https://user-images.githubusercontent.com/14541765/181433057-eb5b71d3-f883-4606-9500-084d6295be3b.png)

Failure happens with the following settings:
1. cuda and cuda_exp build
2. Some Linux builds on Azure DevOps

**Comment by jameslamb** [comment]
There is already an open issue, #5390 , tracking this exact problem.

And in the future please post the text of logs, not screenshots, so conversations can be foundfrom search engines.

**Comment by shiyu1994** [comment]
@jameslamb Sorry for the duplication. Thanks for your reminder!
