### ISSUE TITLE
libSVM format does not work for prediction anymore

### ISSUE THREAD

**Issue by ArdalanM** [Microsoft/LightGBM#54]
I use [```dump_svmlight_file```](url) to dump an array for prediction.
Since two days ago, I get the following errors when I try to predict from a dumped array.

```
[LightGBM] [Info] Data file: /tmp/tmpum15hb5w/X_to_pred.svm doesn't contain label column
[LightGBM] [Fatal] input format error, should be LibSVM
[LightGBM] [Fatal] input format error, should be LibSVM
```

It should not look for label since we are at prediction phase.

**Comment by guolinke** [comment]
Thanks, had fixed, can you try it again?
