### ISSUE TITLE
Number of estimated parameters in a tree ? 

### ISSUE THREAD

**Issue by lcrmorin** [microsoft/LightGBM#5408]
For comparaison and notably (using AIC/BIC information criterion) I was wondering if there is a natural equivalent of number of trainable parameters for trees. Intuitively I would consider one parameter at each split (the level of the split) + one parameter for each final leaf (the value to predict), summed over all trees.

Is my calculation correct ?  Is this info directly accessible in the library ?

**Comment by jameslamb** [comment]
I'm not qualified to comment on how you might calculate measures like AIC, intended for parametric models, on non-parametric models like the tree-based ones produced by LightGBM. Maybe others will have a comment on that.

But I can directly answer the question "is [information about all the splits for all trees] available in LightGBM?". Yes, it is.

* Python: use `Booster.trees_to_dataframe()`, see https://github.com/microsoft/LightGBM/issues/4784#issuecomment-966805032 for an example
* R: use `lgb.model.dt.tree()`, see https://github.com/microsoft/LightGBM/issues/5223#issuecomment-1188602396 for an example

There are also other options to examine the structure of a fitted LightGBM model, like `Booster.dump_model()` (available in several of the LightGBM libraries) to dump the model format to JSON.

**Comment by lcrmorin** [comment]
I've found an authoritative answer to the technical question on the [Stats SE](https://stats.stackexchange.com/questions/584759/tree-models-and-information-criterion/584765?noredirect=1#comment1080477_584765) that extend to the way to evaluate a model. The issue seems to be closable.

**Comment by jameslamb** [comment]
Thanks for coming back to share this and close this issue!
