### ISSUE TITLE
how to get group/query data when input file is 'csv' format

### ISSUE THREAD

**Issue by kyowill** [Microsoft/LightGBM#541]
Please search your question on previous issues, stackoverflow or other search engines before you open a new one.

For bugs and unexpected issues, please provide following information, so that we could reproduce on our system.

## Environment info
Operating System:
CPU:
C++/Python/R version:

## Steps to reproduce

1.
2.
3.

**Comment by guolinke** [comment]
refer to https://github.com/Microsoft/LightGBM/blob/master/docs/Parameters.md#query-data .
