### ISSUE TITLE
Method to efficiently extract instances allocated to each leaf in each tree making up the trained GBM model

### ISSUE THREAD

**Issue by pgeertsema** [microsoft/LightGBM#5430]
## Summary

I am looking for an efficient way to extract the training data *instances* allocated to each *leaf node* of an arbitrary tree from a trained LightGBM model.

More formally, a way to extract the partitioning of training data instances induced by the leaf nodes of each tree in the trained LightGBM ensemble.

(I am assuming that LightGBM keeps track internally of which training data instances are allocated to the nodes of the constituent trees.... please do let me know if this is not the case!)

## Motivation

There is currently no easy/convenient/performant way to extract the training data instances that have been allocated to the same leaf of a particular tree in a trained GBM model (that I know of...). Efficient access to the instances in each tree leaf would enable:

1. Custom approaches to generating tree-level predictions. For regression problems, a tree prediction for a given leaf is simply the mean of the targets of training data instances allocated to that leaf during training. But suppose you would prefer the median rather than the mean, of the 5th percentile (=>quantile regression), or the variance across all instances in the leaf, or some other arbitrary calculation over all the instances collected in a leaf?

2. Measures of instance importance based on which instances are allocated to the same leaf for a particular prediction.

3. Efficient troubleshooting by examining the kinds of instances that underpin the calculation of a particular prediction.

## Description

I can think of two approaches to extract the instances allocated to a particular leaf of a particular tree for a trained LightGBM booster object. Neither are particularly robust, convenient or performant...

### Approach 1:

Assume that if two training data instances share the same predicted value from a specific tree, then it is the case that they are allocated to the same leaf in that tree tree. This reasonably easy to implement. But of course, the assumption won't always hold, and in that case this approach will fail.

```python
# utility function to create leaf membership matrix D
# element d_f,c in D takes value of 1 IFF observations f and c are allocated to the same leaf, else 0
# (we assume instances f and c with equal tree predictions implies allocated to same leaf)

def getD(tree):
    # tree contains a list of predicted values from a tree
    tree_len = len(tree)
    D = np.full((tree_len, tree_len), np.nan)
    for f in range(0, tree_len):
        for c in range(0, tree_len):
            same = (tree[f] == tree[c])
            #print(f" [{f},{c}] is {same}")
            D[f][c] = same
    return D
```

### Approach 2

Extract the tree structure using ```model.trees_to_dataframe()``` or ```model.dump_model()``` and then programmatically allocate training data instances to each leaf using the tree structure and rules provided. Ironically, this is simply re-doing what LightGBM needs to do internally in order to make predictions; but it will be *much* slower...

## What else?

As a starting point I'd be happy to hack a local cloned version of the LightGBM codebase... any pointers as to which data structures to look at or which functions/objects might be useful for implementing this kind of functionality would be appreciated.

**Comment by jameslamb** [comment]
Thanks for using LightGBM and opening this report.

> There is currently no easy/convenient/performant way to extract the training data instances that have been allocated to the same leaf of a particular tree

I'm happy to tell you that LightGBM directly supports this via `pred_leaf` predictions. The R package, Python package, and C API all support that type of prediction.

Consider the following example in Python.

```python
import lightgbm as lgb
from sklearn.datasets import make_regression

X, y = make_regression(n_samples=1000, n_features=10)

dtrain = lgb.Dataset(X, y)

lgb_params = {
    "objective": "regression",
    "verbose": -1,
    "n_estimators": 10,
    "max_depth": 2,
}

bst = lgb.train(
    params = lgb_params,
    train_set = dtrain
)

tree_preds = bst.predict(X[:10], pred_leaf=True)
tree_preds
```

```text
array([[2, 1, 1, 3, 0, 2, 3, 1, 3, 0],
       [3, 3, 2, 2, 3, 2, 2, 2, 3, 0],
       [3, 3, 1, 2, 3, 2, 2, 2, 3, 0],
       [1, 1, 0, 3, 1, 2, 0, 1, 2, 0],
       [3, 3, 3, 1, 1, 2, 1, 2, 2, 2],
       [0, 0, 0, 1, 0, 3, 0, 0, 0, 0],
       [3, 3, 1, 2, 0, 2, 2, 2, 3, 0],
       [2, 2, 1, 2, 2, 3, 2, 3, 3, 2],
       [0, 3, 3, 1, 2, 2, 2, 2, 0, 2],
       [3, 3, 2, 2, 3, 2, 2, 2, 3, 2]], dtype=int32
```

Each column in that array represents one tree in the model, and the value in each corresponding row is the index of the leaf node that that observation falls into for that tree.

I think that should efficiently provide the raw data for the types of questions you're asking.

**Comment by pgeertsema** [comment]
Works perfectly! Thanks & closed.
