### ISSUE TITLE
Implementing prediction early stopping

### ISSUE THREAD

**Issue by cbecker** [Microsoft/LightGBM#545]
Hi there.

I was experimenting with early stopping for prediction, which can reduce prediction time significantly. My current test was something like:

```c++
std::vector<double> GBDT::PredictRawEarlyStopping(const double* value,
        const EarlyStoppingConfiguration &config) const {
  std::vector<double> ret(num_class_, 0.0f);

  for (int i = 0; i < num_iteration_for_pred_; ++i)
  {
    // should we early stop?
    if ((i > 0) && (i % config.iterationsPeriod == 0))
    {
        auto votes = ret;
        std::partial_sort(votes.begin(), votes.begin() + 2, votes.end(), std::greater<double>());

        const auto margin = votes[0] - votes[1];

        if (margin > config.marginThreshold)
            return ret;
    }

    for (int j = 0; j < num_class_; ++j)
    {
      ret[j] += models_[i * num_class_ + j]->Predict(value);
    }
  }
  return ret;
}
```

It checks the margin of the top-ranked class and stops if it is higher than a given value. 

I am wondering what would be the preferred way for implementing this to have it structured enough and customizable. It could be a callback function, and we would need to specify how often it should be called (e.g. `config.iterationsPeriod`). Would that fit well in the LightGBM code? I'm open to other possibilities as well.

**Comment by guolinke** [comment]
@cbecker 
this is only for multi-class, right ?

**Comment by cbecker** [comment]
It would also work for binary. Then the margin would be `fabs(2 * score)`, what do you think?

Actually if we have a callback it can be user-defined, and then it could also be non-symmetric if the user needs that.

**Comment by guolinke** [comment]
@cbecker 
sure, welcome to create a PR for this.

**Comment by cbecker** [comment]
Thanks, where would you prefer the function ptr to be stored (I mean in which structure)?

**Comment by guolinke** [comment]
@cbecker 
I think using a callback (or a class?) is good and we can use the config to specific the used callback.
Maybe a global dictionary (```std::unordered_map<std::string, std::function...>```) is needed to store the mapping from ```name``` to  callback.

**Comment by cbecker** [comment]
Thanks. I've just noticed that in the latest master `PredictRaw()` is parallelized, which makes applying this type of early stopping more difficult, and it may slow down prediction.

Would it make sense to have a separate function to predict with a single thread? Also, for some cases users may want to do this in a single thread, as it would be faster to parallelize at the sample level, if multiple samples are being classified at the same time. (actually that's what we're doing now where I work, but we're using an earlier version of LightGBM)

**Comment by guolinke** [comment]
@cbecker 
Our early parallel prediction version is parallel at the sample level, and it is faster in the most cases. 
Actually, I am also think about rollback it, and find another way to speed up the prediction for only one sample.

**Comment by cbecker** [comment]
What about passing a parameter `num_threads` to the prediction function? Or making it part of the boosting class, so by default it uses a single thread, otherwise multiple ones?

This can be done with very little overhead (to be tested) by using `#pragma omp parallel for schedule(static) num_threads(number_of_threads)`

**Comment by cbecker** [comment]
This was already merged in master, closing the issue.
