### ISSUE TITLE
"double free or corruption" error when running predict 

### ISSUE THREAD

**Issue by txjmb** [Microsoft/LightGBM#546]
This error just started happening after I ran some system updates.  Tried latest build with same issue.  Looks to be something external to LightGBM that LightGBM depends on.  Training works, prediction throws this error.

Googling the error, I found that Tensorflow was having a similar issue.  The workaround they used worked in this case.  But, I still wanted to put in this issue to see if it can be resolved without the workaround.

Here is the workaround:
```
sudo apt-get install libtcmalloc-minimal4
export LD_PRELOAD="/usr/lib/libtcmalloc_minimal.so.4"
```

## Environment info
Operating System: Ubuntu 16.04.2
CPU: Intel
C++/Python/R version: Python 3.5, GCC  5.4

## Error Message:
[LightGBM] [Info] Finished loading 911 models
*** Error in `python': double free or corruption (!prev): 0x000000000305c510 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7fd51bab37e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x7fe0a)[0x7fd51babbe0a]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7fd51babf98c]
/home/user/anaconda3/lib/python3.5/site-packages/lightgbm-0.1-py3.5.egg/lightgbm/lib_lightgbm.so(_ZN8LightGBM7Booster7PredictEiiiSt8functionIFSt6vectorISt4pairIidESaIS4_EEiEEPdPl+0x235)[0x7fd4ffe59b55]
/home/user/anaconda3/lib/python3.5/site-packages/lightgbm-0.1-py3.5.egg/lightgbm/lib_lightgbm.so(LGBM_BoosterPredictForMat+0x9d)[0x7fd4ffe5206d]
/home/user/anaconda3/lib/python3.5/lib-dynload/_ctypes.so(ffi_call_unix64+0x4c)[0x7fd51b1d6370]
/home/user/anaconda3/lib/python3.5/lib-dynload/_ctypes.so(ffi_call+0x1f5)[0x7fd51b1d5b15]
/home/user/anaconda3/lib/python3.5/lib-dynload/_ctypes.so(_ctypes_callproc+0x3dc)[0x7fd51b1cd5dc]
/home/user/anaconda3/lib/python3.5/lib-dynload/_ctypes.so(+0x9c43)[0x7fd51b1c5c43]
/home/user/anaconda3/bin/../lib/libpython3.5m.so.1.0(PyObject_Call+0x56)[0x7fd51c9a1236]
/home/user/anaconda3/bin/../lib/libpython3.5m.so.1.0(PyEval_EvalFrameEx+0x66f4)[0x7fd51ca7b314]
/home/user/anaconda3/bin/../lib/libpython3.5m.so.1.0(PyEval_EvalFrameEx+0x9546)[0x7fd51ca7e166]

**Comment by guolinke** [comment]
@txjmb 
can you update code from latest master branch ? I think I had fixed it.

**Comment by kiminh** [comment]
@guolinke Sorry,what't related pull? I'm encountering this issue when predict use lightgbm on spark. I want to figure out how this issue is fixed in original cpp code. Seems like the memory management has some bug.

**Comment by guolinke** [comment]
@kiminh I remember I fixed this by adding a mutex in prediction, avoiding the buffer be used by multiply python processes at the same time.

**Comment by kiminh** [comment]
19/01/30 11:25:23 [Executor task launch worker for task 769] INFO Executor: Finished task 49.1 in stage 14.0 (TID 769). 2865 bytes result sent to driver
19/01/30 11:25:49 [Executor task launch worker for task 780] INFO MemoryStore: Block rdd_42_76 stored as values in memory (estimated size 360.2 MB, free 235.4 MB)
19/01/30 11:25:49 [Executor task launch worker for task 780] INFO Executor: Finished task 76.1 in stage 14.0 (TID 780). 2593 bytes result sent to driver
*** Error in `/usr/java/default/bin/java': double free or corruption (!prev): 0x00007f7414950370 ***
======= Backtrace: =========
/lib64/libc.so.6[0x36c0e732af]
/lib64/libc.so.6[0x36c0e78b1e]
/lib64/libc.so.6[0x36c0e797f7]
/lib64/ld-linux-x86-64.so.2(_dl_deallocate_tls+0x58)[0x36c0a11578]
/lib64/libpthread.so.0[0x36c1607257]
/lib64/libpthread.so.0[0x36c160736f]
/lib64/libpthread.so.0[0x36c1608318]
/lib64/libc.so.6(clone+0x6d)[0x36c0ee6e9d]
======= Memory map: ========


Seems the problem exists in java version which generated by swig

**Comment by guolinke** [comment]
@imatiach-msft any ideas about this?

**Comment by imatiach-msft** [comment]
hi @kiminh , sorry about the trouble you are having.  Are you getting this error when using mmlspark or are you running your own Java code around the LightGBM jar?  If the latter, would you be able to send a small example (eg sample code) that you are using in Java to call the API?  It could be an issue in how you are constructing and passing in parameters.  If you are just using the LightGBMClassifier or Regressor in mmlspark, would you be able to share the parameters and dataset that you are using (so I can try to reproduce this issue)?
