### ISSUE TITLE
[CUDA] Random number generation on CUDA

### ISSUE THREAD

**Issue by shiyu1994** [microsoft/LightGBM#5471]
## Summary
Support generation of random numbers on CUDA.

## Motivation
Sometimes random number generation is repeatedly called during the training process. For example, in the `rank_xendcg` objective. Supporting generation of random numbers on CUDA can accelerates these processes.

## References

See the code snippet below for random number generation in boosting with `rank_xendcg`
https://github.com/microsoft/LightGBM/blob/f0e3296232a98be70dc420977a3c5c5d731771ba/src/objective/rank_objective.hpp#L301-L328

**Comment by shiyu1994** [comment]
Closed in favor of being in https://github.com/microsoft/LightGBM/issues/2302. We decided to keep all feature requests in one place.

Welcome to contribute this feature! Please re-open this issue (or post a comment if you are not a topic starter) if you are actively working on implementing this feature.

**Comment by jameslamb** [comment]
Sorry, this was locked accidentally. Just unlocked it. We'd still love help with this feature!
