### ISSUE TITLE
lightgbm 3.3.1 take more execution time compare with lightgbm 2.1.2

### ISSUE THREAD

**Issue by Piecer-plc** [microsoft/LightGBM#5475]
## Description
Hi, I test the execution time of lightgb.train when adopt different lightgbm version. I noticed that 2.1.2 only need 17s.
In my program, when the lightgbm version was **3.3.1**, the execution time was **74s**, but when I changed the lightgbm  to the **2.1.2**, the execution tim was **17s**.
I also tested other versions of lightgbm, and the detailed experiments The results are shown in the table below.
My question is, why is there a new version that take more execution time and is there a way to fix it?

|Lightgbm Version|Execution time|
|--|--|
|3.3.1|74s|
|3.2.1|74s|
|3.1.1|74s|
|3.0.0|74s|
|2.3.1|74s|
|2.2.3|74s|
|2.1.2|17s|
## Reproducible example

```python
import numpy as np 
import pandas as pd
import lightgbm as lgb
from sklearn.model_selection import KFold
from sklearn.metrics import mean_squared_error
import category_encoders as ce

df_train = pd.read_csv("train.csv") 
df_test = pd.read_csv("test.csv") 
df_sample = pd.read_csv("sample_submission.csv") 
df_train.drop("id", axis=1, inplace=True) 
df_test.drop("id", axis=1, inplace=True) 
cat_labels = [f"cat{i}" for i in range(10)]

onehot_encoder = ce.one_hot.OneHotEncoder() 
onehot_encoder.fit(pd.concat([df_train[cat_labels], df_test[cat_labels]], axis=0))
train_ohe = onehot_encoder.transform(df_train[cat_labels]) 
test_ohe = onehot_encoder.transform(df_test[cat_labels]) 
train_ohe.columns = [f"OHE_{col}" for col in train_ohe]  
test_ohe.columns = [f"OHE_{col}" for col in test_ohe] 
numerical_labels = [f"cont{i}" for i in range(14)] 
train_x = pd.concat([df_train[numerical_labels],train_ohe], axis=1) 
train_y = df_train["target"]
folds = KFold(n_splits=5, shuffle=True, random_state=2021) 
lgb_params = dict({'objective': 'regression',  
 'metric': 'rmse', 
 'verbosity': -1, 
 'learning_rate': 0.01, 
 'early_stopping_round' : 200, 
 'num_iterations' : 20000}) 
oof_preds = np.zeros_like(train_y) 
models = [] 
import time
start_time = time.time()
for tr_idx, va_idx in folds.split(train_x): 
    tr_x, va_x = train_x.iloc[tr_idx], train_x.iloc[va_idx] 
    tr_y, va_y = train_y[tr_idx], train_y[va_idx] 
       
    lgb_train_dataset = lgb.Dataset(tr_x, tr_y) 
    lgb_valid_dataset = lgb.Dataset(va_x, va_y) 
    model = lgb.train(lgb_params, lgb_train_dataset, valid_sets=[lgb_valid_dataset], verbose_eval=100) 
    models.append(model) 
    oof_pred = model.predict(va_x) 
    oof_preds[va_idx] = oof_pred 
over_time = time.time()
total_time = over_time - start_time
print("Time: %s s" % total_time)
```
The dataset is provided by this competition. [Tabular Playground Series - Feb 2021](https://www.kaggle.com/competitions/tabular-playground-series-feb-2021/data)
## Environment info
OpenCV = 4.5.1.48 ; OpenCV = 4.1.0.25
Operating System: Linux Ubuntu 16.04
CPU: Intel(R) Core(TM) i9-9900K CPU
GPU: TITAN V
Python = 3.7.10

**Comment by jameslamb** [comment]
I'm closing and locking this due to lack of response (it has been 1 year today since we asked for more details).

If you notice similar timing differences between more recent releases of LightGBM, are willing to prepare a benchmark, and have time to work with us here, please open a new issue linking to this one.
