### ISSUE TITLE
Groupwise interaction constraints

### ISSUE THREAD

**Issue by septfleur** [microsoft/LightGBM#5477]
## Beyond interaction constraints
This is an "upgraded" interaction constraint problem. Consider the following genetic problem:

We predict the mutation probability of the offspring of two parents.

Mother and father have the same number of features (age, diet preferences, etc). $\textbf{x} = (x_1, \cdots, x_n)$ for the mother, and $\textbf{y} = (y_1, \cdots, y_n)$ for the father. Therefore, for each data entry, there are $2n$ features: $(\textbf{x}, \textbf{y})$ and 1 target (mutation probability).

The child mutation probability is modeled as:
$$p = f\big(\mathcal{L}(\textbf{x}), \mathcal{L}(\textbf{y})\big)\,$$
where $f(a, b) = \textrm{sigmoid}(a+b)$.
LGBM needs to fit for $\mathcal{L}$, a $\textbf{same}$ model that applys to the mother and the father.

## Summary
The problem goes a little beyond what the current interaction constraints can support. LGBM model does $\textit{NOT}$ apply to all the features in a data entry, but on groups of them individually (mother and father) before consolidated by a known function $f$. The problem also extends to more than two groups.

## References
Interaction constraints
https://github.com/microsoft/LightGBM/issues/2884

**Comment by btrotta** [comment]
Would something like the following work? Concatenate the mother data and the father data vertically, using the same target data for both. (So if your original dataset has $m$ rows and $2n$ features, this new dataset would have $2m$ rows and $n$ features, and each offspring would appear in 2 rows, both having the same value for the target.)  Train a model on the concatenated data. To make predictions, predict separately using the mother data and the father data, and average the 2 predictions.
