### ISSUE TITLE
how can use the model txt file to make prediction in a different environment?

### ISSUE THREAD

**Issue by hanamiqi** [Microsoft/LightGBM#548]
I want to use the model file outputed by save_model method during training to make prediction in another environment without the training dataset, do i need to use the model file and the training data(copy from the source environment) to retrain the model?
Or just have to use the input_model parameter to designate the directory and name of the model file to generate a booseter instance and use it for prediction? if so, how should code it? I have not seen any example for this issue!

**Comment by Laurae2** [comment]
@hanamiqi If you have the model exported, you do not need the training data to do predictions. Just use the model to make predictions (load the model, and predict using your datasets).

**Comment by hanamiqi** [comment]
@Laurae2 could you please gave me some code example for this? i read the all the help document but have not seen any example for this

**Comment by hanamiqi** [comment]
@Laurae2 i got it through reading the advanced_example.py, still thank u very much!
