### ISSUE TITLE
Question: 3.4 release schedule

### ISSUE THREAD

**Issue by jonashaag** [microsoft/LightGBM#5483]
Hi there, are the any plans on making a 3.4 release (vs. a 4.0 release), and if so what could be the release date?

**Comment by jameslamb** [comment]
We are not planning out a 3.4.x release series. The next release of LightGBM will be 4.0.0, unless some very critical security or compatibility issue forces the release of aa 3.3.3 (but even that would only contain just the patches necessary to fix that specific problem).

See the discussion in https://github.com/microsoft/LightGBM/issues/3210#issuecomment-1216083602 for more details about why the next release will be 4.0.

You can subscribe to #5153 to be notified about progress towards a 4.0 release.

**Comment by jonashaag** [comment]
Thank you!
