### ISSUE TITLE
Eigen/Dense”: No such file or directory

### ISSUE THREAD

**Issue by ArtificialZeng** [microsoft/LightGBM#5495]
when I compile it. Eigen/Dense”: No such file or directory

## Environment info

LightGBM version or commit hash:

Command(s) you used to install LightGBM

```shell

```

**Comment by ArtificialZeng** [comment]
> 

I‘m using Visual Studio. First I download the whole code, then I find out it's empty in the Eigen/Dense directory. It can't be compiled in the Visual Studio?

**Comment by ArtificialZeng** [comment]
> Thanks for using LightGBM!
> 
> Since you didn't fill out the issue template (especially "commands you used to install LightGBM"), you're asking us to guess how you've installed LightGBM.
> 
> I suspect that maybe you are building the project from a cloned copy of this repository, and forgot to initialize the submodules.
> 
> If you've already cloned this repo with `git clone`, run the following prior to re-building.
> 
> ```shell
> git submodule init
> git submodule update --recursive
> ```
> 
> Then try rebuilding.
> 
> If this answer doesn't help you resolve the error, please fill out the description with all of the information that was requested.

Actually, What  I'm really asking is that: How to compile it from the source under Windows OS.

**Comment by jameslamb** [comment]
LightGBM can be compiled with Visual Studio.

I'm not sure what specifically "download the code means", but if it is something other than `git clone --recursive`, then you need to run the `git` commands I shared to get Eigen and the other git submodules.

**Comment by ArtificialZeng** [comment]
> LightGBM can be compiled with Visual Studio.
> 
> I'm not sure what specifically "download the code means", but if it is something other than `git clone --recursive`, then you need to run the `git` commands I shared to get Eigen and the other git submodules.

Or, the problem I mentioned is solved by using your method, but another bug appears: https://github.com/microsoft/LightGBM/issues/5499

**Comment by jameslamb** [comment]
For those finding this issue from search engines... the "bug" mentioned here is that the source code zip file that GitHub generates for repos does not include the source of git submodules, and as a result LightGBM cannot be compiled from source code downloaded that way.

This is the same issue that was described and addressed in https://github.com/microsoft/LightGBM/issues/5038#issuecomment-1101503222.

I'm going to close this discussion. We can use #5498 to discuss how to update LightGBM's documentation to provide better guidance around this.
