### ISSUE TITLE
[python-package] Set evaluate frequency

### ISSUE THREAD

**Issue by fecet** [microsoft/LightGBM#5518]
I'm using a quite slow evaluate function in python's `feval` arguments , which will slow down my training speed 10x if I evaluate it every round, however, this seems to be the default behavior. It's possible to change the frequency? I check `metric_freq` and `verbose_eval` parameters, but the previous one only work on CLI version while the later one seems only affect the log frequency.

**Comment by jmoralez** [comment]
Hi @fecet, thank you for your interest in LightGBM. We already have this as a feature request in #4107, but hasn't been implemented yet. In the meantime, you can find a suggestion on how to manually do it in https://github.com/microsoft/LightGBM/issues/4107#issuecomment-808161805.

Please let us know if you have further doubts.
