### ISSUE TITLE
LightGBM + Flaml/AutoML

### ISSUE THREAD

**Issue by wil70** [microsoft/LightGBM#5534]
Hello

I'm using the distributed socket version via command line, it works well. I got some roadblock with MPI but anyway socket works well..

**Question:** Is there a way to use AutoML (Flaml) for parameters tuning with LightGBM CLI/Socket? that would be awesome

Note:
- I tried the ML.net version but there are issues (for instance, I couldn't retrain LightGBM, distributed isn't really there). On the plus side: AutoML was great and fast, I was also able to use 300GB+ csv files. Retrain and Distrubted are too important, so I do not use it anymore.
- I tried the python version but it is not super clear how to make ditributed computing (like MARS) work with Flaml/AutoML + LightGBM. It seems I can either do MARS or Flaml/AutoML but not both... I need to try Ray, I saw an article where they use AutoML+LightGBM, hopefully it can handle TB files.

**Comment by jameslamb** [comment]
Thanks for your interest in LightGBM!

It looks like you've posted the same question here and in FLAML: https://github.com/microsoft/FLAML/issues/758. Please don't do this! Maintainers of both projects have limited time and attention, and posting the same question in multiple places is effectively asking multiple people to do the same work.

Since your questions are all specifically about FLAML, I'm going to close this and let the maintainers there answer your questions.

You might also consider investigating some of the other options described at https://lightgbm.readthedocs.io/en/latest/Parallel-Learning-Guide.html.

**Comment by wil70** [comment]
Thanks, I'm able to train in parallel with LightGBM (c/c++), but I'm wondering how I can get some help with all those parameters to tune and so I saw Flaml and optura but those do not seem to work with the c/c++ version (I know the python version call the c++, but I have other issues with DAS, Mars and I didn't try Ray yet)

I guess I can always train on a subset iwth Flaml+Python and then extract the parameters and feed them to the c/c++ version? will that help?
Note:Sorry for posting in several places. The thinking is many none-pro (like none msft employees) are registered to only a few projects, and so it feels natural to reach to more people to get answers I wouldn't have got in posting in 1 forum.
Thanks 
Wil
    On Monday, October 10, 2022 at 07:56:52 PM PDT, James Lamb ***@***.***> wrote:  
 
 


Thanks for your interest in LightGBM!

It looks like you've posted the same question here and in FLAML: microsoft/FLAML#758. Please don't do this! Maintainers of both projects have limited time and attention, and posting the same question in multiple places is effectively asking multiple people to do the same work.

Since your questions are all specifically about FLAML, I'm going to close this and let the maintainers there answer your questions.

You might also consider investigating some of the other options described at https://lightgbm.readthedocs.io/en/latest/Parallel-Learning-Guide.html.

**Comment by wil70** [comment]
Still stuck even after closing a lot of forum andso many days @jameslamb , I discovering those are 1/2 baked libraries. Any advice on something that can scale and is production quality?

I think LightGBM c++ is good and I can scale but I'm missing the parameter tuning help part.

**Comment by jameslamb** [comment]
"can scale" and "production quality" have multiple possible interpretations.

If you feel you need to use distributed training, all of the officially supported options for doing so are listed in doc I linked, https://lightgbm.readthedocs.io/en/latest/Parallel-Learning-Guide.html.

If it's possible in your environment, you might also consider just getting a larger machine and performining single-node training, which would allow the use of lots of popular hyperparamter tuning frameworks.

**Comment by wil70** [comment]
Thanks @jameslamb 

yeah, thanks, and I have been able to run training on 2 machines with the "Voting Parallel" mode. The two machines each have 128GB RAM but the csv files is 1TB. I use the c++ LightGBM CLI version with "socket mode" (as I ran into some issues with MPI), any way that work well with socket mode.

More RAM would too expensive for me. I could look at a very fast SSD NVME drive but that would probably wear it very fast and that would be probably very slow compare to memory and an algo well design for streaming.

I'm new to those libraries. I would like to run some hyperparameters tuning fwk. From your comment I understand
1. if the machine doesnt have the full dataset in memory then it might not be able use some hyperparameters framework? hopefully some framework can deal with streaming huge dataset instead of loading everything in memory?
2. So far the only way I was able to play with AutoML, FLAML, Tune, optuna,MLJar is via c# or python. Is there a way to use a good hyperparameters tuning framework directly with the LightGBM CLI (socket mode)?
3. I'm wondering if I can play on a smaller dataset with hyperparameter tuning in python and then feed the LightGBM CLI socket mode with those parameters, do you think that could work?

Thanks for your advises!
--w

**Comment by jameslamb** [comment]
> if the machine doesnt have the full dataset in memory then it might not be able use some hyperparameters framework

Correct, some frameworks only work on a single machine and expect all of the training data to be loaded in memory.

> Is there a way to use a good hyperparameters tuning framework directly with the LightGBM CLI (socket mode)

Not that I am aware of and definitely not that is maintained in this repository, sorry.

> I'm wondering if I can play on a smaller dataset with hyperparameter tuning in python and then feed the LightGBM CLI socket mode with those parameters, do you think that could work?

Overall, yes that could possibly work. If you do that, try to ensure that the smaller dataset you use is roughly representative of the largest set. That's a complicated task but at least roughly:

* all possible values of categorical columns are captured in the smaller dataset
* distribution of features (proportions for categoricals, continuous distribution for continuous features) is roughly the same in the smaller dataset
* distribution of the target is roughly the same in the smaller dataset

You might also be able to use the `lightgbm.LGBMClassifier()` combined with `dask-ml` (https://examples.dask.org/machine-learning/hyperparam-opt.html).

**Comment by wil70** [comment]
Thanks @jameslamb 
I'm playing with the dask right now.

5. I'm wondering another approach, like if I could get some "Hyperparameter tuning framework" (like FLAML) call back from python that I could feed to the LightGBM CLI (like a subprocess.call()) then return back the results to the "Hyperparameter tuning framework" for the next iteration. Theorically that should work isn't it? and that should be fast, it would allow to use all the LighGBM native goodies (like distrbiuted etc..)

**Comment by wil70** [comment]
Hi @jameslamb is there a way with "LightGBM CLI socket mode" to give the parameters to a master (like run 10 iterations with parameters a=x,b=y,c=z....) and it propagate that information to all slaves before starting? 
Otherwize I might need to write a demon process that will control (stop/start/setup config file) from slave to master. I think it make sens to have one point of control? That way hyperparameter optimizer become easier to work with it as they will only give new set of parameters to the master who will take care of updating it friends.

**Comment by jameslamb** [comment]
> is there a way with "LightGBM CLI socket mode" to give the parameters to a master (like run 10 iterations with parameters a=x,b=y,c=z....) and it propagate that information to all slaves before starting

LightGBM does not use the terms "master" and "slave", and we'd prefer that you didn't either while posting in this repo.

LightGBM also does not have the *concept* of  "leader", "controller", etc. and "workers" in its core code. In LightGBM distributed training, you start up multiple processes which know about each other via a list of IP addresses and ports ([see parameter "machines"](https://lightgbm.readthedocs.io/en/latest/Parameters.html#machines)), and those processes do work via collective operations.

However, some higher-level interfaces to LightGBM distributed training do work similarly to the way you've suggested. For example, when you use `lightgbm.dask` (Dask) or SynapseML (Spark), a main process (the Dask "client" or Spark "driver") is responsible for starting up `n` identical worker processes, which each have the same training parameters but work on a separate physical chunk of the data.
