### ISSUE TITLE
Azure Publish MSBuild Duplicated Path

### ISSUE THREAD

**Issue by andrewkittredge** [microsoft/LightGBM#5535]
## Description
I have a .net standard 2.0 project which imports the LightGBM package through the Microsoft.ML.LightGbm package.  I reference the .net standard 2.0 project from a .net framework asp.net project.  Publishing the asp.net project to Azure fails with the below error, notice the path is duplicated.

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Unable to copy file "C:\Users\andre\repos\calcbench\packages\LightGBM.3.3.2\build\..\runtimes\win-x64\native\lightgbm.exe" to "C:\Users\andre\repos\calcbench\AndrewXBRLService\obj\Release\xbrlWebSite\C:\Users\andre\repos\calcbench\packages\LightGBM.3.3.2\build\..\runtimes\win-x64\native\lightgbm.exe". The given path's format is not supported.	AndrewXBRLService	C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VisualStudio\v17.0\Windows Azure Tools\2.9\Microsoft.WindowsAzure.targets	2829
```

See this stackoverflow with a similar problem, https://stackoverflow.com/questions/34100740/error-copying-typescript-files-when-packaging-azure-project-visual-studio-2015.

## Environment info
LightGBM.3.3.2

**Comment by jameslamb** [comment]
Thanks for using LightGBM!

But sorry, we do not maintain `LightGBM.NET` here. Can you please try opening an issue at https://github.com/rca22/LightGBM.Net/issues and linking to this one?

**Comment by andrewkittredge** [comment]
Are you sure?

https://www.nuget.org/packages/LightGBM/ is the nuget package I am referencing, which points to this repo.

Also the copy that is failing is generated @ https://github.com/microsoft/LightGBM/blob/5c8a331bf5966f1df546f154f64ed9b8856a90ee/.nuget/create_nuget.py#L55.

**Comment by mjmckp** [comment]
@andrewkittredge didn't mention the LightGBM.Net nuget package, instead he was referring to the LightGBM and Microsoft.ML.LightGbm nuget packages.

However, I would recommend using LightGBM.Net over Microsoft.ML.LightGbm, there are a large number of bugs and numerical inconsistencies between the native trees trained by Microsoft.ML.LightGbm and the corresponding managed trees.  Also, the last time I checked, it doesn't implement the full feature set of LightGBM (for example, linear trees).

**Comment by jameslamb** [comment]
Thank you! Sorry, maybe this is my ignorance of .NET showing. I thought that the `Microsoft.ML.LightGbm` NuGet package was a dependency of `LightGBM.Net`.

**Comment by StrikerRUS** [comment]
Just to make it clear.
In this repo we only maintain `LightGBM` NuGet package: https://www.nuget.org/packages/LightGBM/

`Microsoft.ML.LightGbm` NuGet package (https://www.nuget.org/packages/Microsoft.ML.LightGbm/) is maintained by another team in another GitHub repo: https://github.com/dotnet/machinelearning.

> However, I would recommend using LightGBM.Net over Microsoft.ML.LightGbm, there are a large number of bugs and numerical inconsistencies between the native trees trained by Microsoft.ML.LightGbm and the corresponding managed trees. Also, the last time I checked, it doesn't implement the full feature set of LightGBM (for example, linear trees).

I believe maintainers of that package will be grateful if you share your observations about incompleteness and bugs with them, for example, there is the following meta-issue for LightGBM-related bugs: https://github.com/dotnet/machinelearning/issues/6337

**Comment by mjmckp** [comment]
@StrikerRUS It was a while ago I looked into this, and there were a significant number of numerical inconsistencies in Microsoft.ML.LightGbm.  Someone needs to implement proper unit tests for Microsoft.ML.LightGbm which trains trees on randomised data with a randomised configuration, and then value check the output of the managed tree implementation implemented in C# against the output of the native tree implementation implemented in C++, then run a large set of these tests and work through the test failures systematically.

**Comment by jameslamb** [comment]
Sorry for the very long delay in response.

We don't have much .NET expertise on the maintenance team right now. It's been a year and a half since the last comment on this discussion, so I'm going to close this.

@andrewkittredge or anyone else following this, we'd welcome contributions to fix whatever packaging problem you're seeing with the LightGBM NuGet package, if there are still issues.
