### ISSUE TITLE
[gpu] LightGBM GPU Trainer is stuck at Compiling OpenCL Kernel with 64 bins

### ISSUE THREAD

**Issue by ParthasarathySubburaj** [microsoft/LightGBM#5536]
## Description
I am trying to train a LightGBM model with GPU. I was able to successfully install the GPU version of the LightGBM and compile all he required binaries by following the procedure [here](https://lightgbm.readthedocs.io/en/latest/GPU-Tutorial.html#build-lightgbm). However, when I try to train my model the code is just stuck with the following logs 

```
[LightGBM] [Info] This is the GPU trainer!!
[LightGBM] [Info] Total Bins 5293
[LightGBM] [Info] Number of data points in the train set: 789, number of used features: 105
[LightGBM] [Info] Using GPU Device: Tesla V100-SXM2-32GB, Vendor: NVIDIA Corporation
[LightGBM] [Info] Compiling OpenCL Kernel with 64 bins...
```

## Reproducible example
The following config and code snippet was used for training the model

```
lgb_train = lgb.Dataset(data = train_x,  
                        label = train_y, 
                        feature_name = feature_names,
                        free_raw_data=False)

lgb_val = lgb.Dataset(data = val_x,
                        label = val_y, 
                        feature_name = feature_names,
                        free_raw_data=False)

parameters = {'max_bin': 63,
          'num_leaves': 255,
          'learning_rate': 0.1,
          'tree_learner': 'serial',
          'task': 'train',
          'is_training_metric': 'false',
          'min_data_in_leaf': 1,
          'min_sum_hessian_in_leaf': 100,
          'device': 'gpu',
          'num_thread': -1,
          }

gbm = lgb.train(params = parameters,
                train_set = lgb_train,
                num_boost_round = 1000,
                valid_sets=[lgb_train, lgb_val],
                feature_name=feature_names,
               )
```
where train_x, train_y, val_x, val_y are training the validation datasets

## Environment info

LightGBM version: '3.3.2.99'

Command(s) you used to install LightGBM

```shell
sudo apt-get install --no-install-recommends git cmake build-essential libboost-dev libboost-system-dev libboost-filesystem-dev

git clone --recursive https://github.com/microsoft/LightGBM
cd LightGBM
mkdir build
cd build
cmake -DUSE_GPU=1 -DUSE_CUDA=1 -DOpenCL_LIBRARY=/usr/local/cuda/lib64/libOpenCL.so -DOpenCL_INCLUDE_DIR=/usr/local/cuda/include/ ..
make -j$(nproc)
cd ..

sudo apt-get -y install python-pip
sudo -H pip install setuptools numpy scipy scikit-learn -U
cd python-package/
sudo python setup.py install --precompile
cd ..
```
These instructions are the ones located [here](https://lightgbm.readthedocs.io/en/latest/GPU-Tutorial.html#build-lightgbm)

## Additional Comments

The code works fine if I change the `device` to `cuda` in the configuration, and I see the GPU being consumed. 

Any leads on this will be really useful. Thank you.

**Comment by ParthasarathySubburaj** [comment]
@jameslamb, any updates on this?

**Comment by jameslamb** [comment]
"any updates" types of comments are really not appreciated, especially only 2 days after an issue was opened.

If you'd like to help investigate this, we welcome other debugging information or ideas you can provide. Otherwise, please wait patiently for someone from the small team of mostly volunteers maintaining this project to find time to investigate this report.

**Comment by jmoralez** [comment]
@ParthasarathySubburaj Can you try with `device='cuda'` instead?

**Comment by ParthasarathySubburaj** [comment]
Hi @jmoralez, thanks a lot for your response. Setting `device=cuda` works for me and GPU is also being consumed, but I am wondering why `device=gpu` is not working. Also may I know what is the difference between `device=cuda` and `device=gpu`?
If you need any further logs or configurations please let me know so that I can get the same for you.

**Comment by jmoralez** [comment]
I think it's due to the fact that you set both flags in your install:

> cmake -DUSE_GPU=1 -DUSE_CUDA=1

if you want the OpenCL version (`device='gpu'`) you should only have `DUSE_GPU=1`, you can refer to the [installation guide](https://lightgbm.readthedocs.io/en/latest/Installation-Guide.html#build-gpu-version).

The difference between the device types is described [here](https://lightgbm.readthedocs.io/en/latest/Installation-Guide.html#build-cuda-version-experimental):

> The [original GPU build](https://lightgbm.readthedocs.io/en/latest/Installation-Guide.html#build-gpu-version) of LightGBM (device_type=gpu) is based on OpenCL.

> The CUDA-based build (device_type=cuda) is a separate implementation and requires an NVIDIA graphics card with compute capability 6.0 and higher. It should be considered experimental, and we suggest using it only when it is impossible to use OpenCL version (for example, on IBM POWER microprocessors).

You can also try the experimental CUDA version (`-DUSE_CUDA_EXP=1` and `device='cuda_exp'`) that is more efficient.

**Comment by ParthasarathySubburaj** [comment]
Thanks a lot for your response @jmoralez, I tried building lightGBM with only `DUSE_GPU=1` flag but still the code gets stuck with the same logs. Also, I am using a NVIDIA GPU and as per the [documentation](https://lightgbm.readthedocs.io/en/latest/Installation-Guide.html#build-gpu-version) I understand that `device=cuda` should be used when we use NVIDIA GPU and `device=gpu` should be used when we use non NVIDIA GPU, is my understanding correct?

**Comment by jmoralez** [comment]
Did you remove your cmake files before? It may have re-used your previous configuration. OpenCL works on different accelerators, so it works with CUDA as well. I just tried it on my machine and it worked fine, got the following logs:
```
[LightGBM] [Info] This is the GPU trainer!!
[LightGBM] [Info] Total Bins 68
[LightGBM] [Info] Number of data points in the train set: 100, number of used features: 2
[LightGBM] [Info] Using GPU Device: NVIDIA GeForce GTX 1050, Vendor: NVIDIA Corporation
[LightGBM] [Info] Compiling OpenCL Kernel with 64 bins...
[LightGBM] [Info] GPU programs have been built
[LightGBM] [Info] Size of histogram bin entry: 8
[LightGBM] [Info] 2 dense feature groups (0.00 MB) transferred to GPU in 0.000279 secs. 0 sparse feature groups
```
Using `device='cuda'` should be better though, since that's targeted specifically to nvidia gpus. I'd also suggest trying `cuda_exp`, it's built to be significantly faster.

**Comment by ParthasarathySubburaj** [comment]
Hi @jmoralez, thanks a lot for your response. I cleared all the previous cmake files and started afresh and it worked for me. When I use the setting `device=gpu` it worked for me.  However, I see that there is hardly any difference between my CPU version and GPU version when it comes to training time for the same configuration.

GPU version took `1 min 42 sec`, and my CPU version took `2 min 8s`? Is this acceptable?

**Comment by jmoralez** [comment]
Yes, it is a known issue. You can find more information here: https://github.com/microsoft/LightGBM/issues/768#issuecomment-320573774. I'm closing this since the original issue was solved.
