### ISSUE TITLE
[ci] CUDA CI jobs are broken: "driver/library version mismatch"

### ISSUE THREAD

**Issue by jameslamb** [microsoft/LightGBM#5546]
## Description

The CUDA CI jobs for this project are all failing, with the following error.

```text
docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
nvidia-container-cli: initialization error: nvml error: driver/library version mismatch: unknown.
Error: Process completed with exit code 125.
```

## Reproducible example

* build from #5544 ([build link](https://github.com/microsoft/LightGBM/actions/runs/3257866953))
* build from #5545 ([build link](https://github.com/microsoft/LightGBM/actions/runs/3262973002))

## References

Here is the line where these jobs are failing.

https://github.com/microsoft/LightGBM/blob/0c0eb2a6a1ba111f0896dd16a579342fa16f7629/.github/workflows/cuda.yml#L109

The references at https://stackoverflow.com/questions/43022843/nvidia-nvml-driver-library-version-mismatch suggest that this issue could be resolved by rebooting.

**Comment by jameslamb** [comment]
@shiyu1994 since you are the only person with administrative access to the machine the CUDA jobs runs on, can you please try rebooting that machine and investigating other fixes for this?

I'm happy to help do other research however I can, but you are the only person who can reboot the machine.

**Comment by jameslamb** [comment]
I just re-triggered a CUDA job...this is still broken.

https://github.com/microsoft/LightGBM/actions/runs/3281397887/jobs/5452120895

@shiyu1994 is there any way I can help you resolve this?

**Comment by jameslamb** [comment]
I just triggered another run and this is still happening.

https://github.com/microsoft/LightGBM/actions/runs/3350110051/jobs/5563225006

@shiyu1994 I really hope you're able to get to this soon. `@` me any time if there's any way I can help.

**Comment by shiyu1994** [comment]
@jameslamb Sorry for the long delay.

I've fixed the virtual machine. And now the CI tests should be able to run.

**Comment by jameslamb** [comment]
Excellent, thanks @shiyu1994 ! I'll try re-running the checks from #5545 right now. If they work, I'll work on merging some of the approved PRs today.

**Comment by jameslamb** [comment]
🎉 🎉 🎉 

that worked!

https://github.com/microsoft/LightGBM/actions/runs/3281397887/jobs/5609753729

<img width="750" alt="image" src="https://user-images.githubusercontent.com/7608904/199576921-69751e3c-0356-41e7-90dc-91bc866a69f3.png">

Thank you so much for the help @shiyu1994 !
