### ISSUE TITLE
offline installation fails: "Please install CMake first"

### ISSUE THREAD

**Issue by qinhaohcen** [microsoft/LightGBM#5547]
I want to install offline. However, the following problems have occurred.How can I solve it?

Windows PowerShell
版权所有（C） Microsoft Corporation。保留所有权利。

安装最新的 PowerShell，了解新功能和改进！https://aka.ms/PSWindows

PS G:\★★★study\2022\3.投稿材料\小论文\LightGBM-master\python-package> python setup.py install
running install
INFO:LightGBM:Starting to compile the library.
INFO:LightGBM:Starting to compile with MSBuild from existing solution file.
WARNING:LightGBM:Compilation with MSBuild from existing solution file failed.
INFO:LightGBM:Starting to compile with Visual Studio 17 2022 (x64).
Traceback (most recent call last):
  File "G:\★★★study\2022\3.投稿材料\小论文\LightGBM-master\python-package\setup.py", line 97, in silent_call
    subprocess.check_call(cmd, stderr=log, stdout=log)
  File "G:\Anaconda3\lib\subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', 'G:\\★★★study\\2022\\3.投稿材料\\小论文\\LightGBM-master\\python-package\\build_cpp', '--target', '_lightgbm', '--config', 'Release']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:\★★★study\2022\3.投稿材料\小论文\LightGBM-master\python-package\setup.py", line 354, in <module>
    setup(name='lightgbm',
  File "G:\Anaconda3\lib\site-packages\setuptools\__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "G:\Anaconda3\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "G:\Anaconda3\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "G:\Anaconda3\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "G:\★★★study\2022\3.投稿材料\小论文\LightGBM-master\python-package\setup.py", line 263, in run
    compile_cpp(use_mingw=self.mingw, use_gpu=self.gpu, use_cuda=self.cuda, use_cuda_exp=self.cuda_exp, use_mpi=self.mpi,
  File "G:\★★★study\2022\3.投稿材料\小论文\LightGBM-master\python-package\setup.py", line 207, in compile_cpp
    silent_call(["cmake", "--build", str(build_dir), "--target", "_lightgbm", "--config", "Release"], raise_error=True,
  File "G:\★★★study\2022\3.投稿材料\小论文\LightGBM-master\python-package\setup.py", line 101, in silent_call
    raise Exception("\n".join((error_msg, LOG_NOTICE)))
Exception: Please install CMake first
The full version of error log was saved into C:\Users\86159\LightGBM_compilation.log
PS G:\★★★study\2022\3.投稿材料\小论文\LightGBM-master\python-package>

**Comment by jameslamb** [comment]
Thanks for using LightGBM!

As the error message in that log says:

> Exception: Please install CMake first

You can follow the instructions at https://cmake.org/install/ to install it on your machine. Once CMake and LightGBM's dependencies have been installed, internet access should not be required to compile LightGBM.

**Comment by qinhaohcen** [comment]
> Thanks for using LightGBM!
> 
> As the error message in that log says:
> 
> > Exception: Please install CMake first
> 
> You can follow the instructions at https://cmake.org/install/ to install it on your machine. Once CMake and LightGBM's dependencies have been installed, internet access should not be required to compile LightGBM.

But I have installed successfully. I suspect it is a problem with the path, but I'm not sure.

**Comment by qinhaohcen** [comment]
How to add cmake to my PATH？

**Comment by jameslamb** [comment]
`PATH` is an environment variable containing a list of folders that your computer looks in when you tell it to run commands. Find `cmake.exe` on your machine, then add its location to that variable.

For help, see a tutorial like https://www.java.com/en/download/help/path.html. Follow the Windows instructions, ignore anything about Java.

After editing `PATH`, close and re-open whatever program you are using to compile LightGBM (cmd prompt, Visual Studio, etc.).

**Comment by qinhaohcen** [comment]
I have add the address of cmake.exe on the PATH variable. But it still doesn't work.

**Comment by jameslamb** [comment]
Please share a screenshot with the contents of your `PATH` environment variable, and we can try to help you.
