### ISSUE TITLE
Why my script of searching for best hyperparameters take so long on AWS EC2 Instance

### ISSUE THREAD

**Issue by DariusMargineanNicolae** [microsoft/LightGBM#5564]
As the name suggest, I created an AWS EC2 Instance and ran a script for searching of the best hp for a lightgbm Regressor timeseries model. The EC2 instance that I've created is a c5.18xlarge instance, and I ran a script to loop over 9 Dataframes with minimum data points 280 and maximum datapoints 285 and for each of those to search of the best hyperparameters of a lightgbm regressor model accordingly to the dataframe given. The search is performed using optuna, with 4000 trials. I ran the same script, for 12 Dataframes with 250 points each and it was perfectly fine, so I don't quite get what am I missing.

For example: I started 2 instances, 1 for the dfs: 280 datapoints < df < 285 datapoints, and the 2nd one for the dfs with 260-270 datapoints. Same code for both. The instances were started on Friday, and by this time (Monday) the 2nd instance managed to compute 8 of 9 dataframes, and the first (the one with 280 datapoints < df < 285 datapoints) managed to compute only 1 dataframe out of 9. I also checked locally on my machine for 4 trials, the one with 280 datapoints < df < 285 datapoints and it works perfectly fine end to end.

Does anybody have an idea, why does it take so long to perform the 9 dataframes with up to 20-30 more datapoints?

**Comment by jameslamb** [comment]
Thanks for using LightGBM!

You've decided not to provide some important information that we ask for in the issue template, including:

* how are you using LightGBM? (Python package? R package? C++? Java?)
* what version of LightGBM are you using? how did you install it?
* a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that maintainers could run to try to replicate the problem you're facing

Without details like that, you are asking us to guess at what your code is doing and what your environment looks like, which is not likely to generate a high-quality answer.

I can at least tell you the following:

* 250 rows is considered a very small dataset by LightGBM...you should not see any meaningful difference in training time between a DataFrame with 250 rows and one with 280 or even 2800 or 28,000 rows
* 9 training datasets x 4000 different combinations of hyperparameters is 36,000 training runs. Even if each run took only 1 second and `optuna` introduced 0 overhead, that many training runs would take 10 hours to complete if run serially.

Without the details I've asked for above, we cannot commit to providing any additional information for you.

**Comment by DariusMargineanNicolae** [comment]
So, with my apologies for not giving enough details, here they are:
I use lightgbm with python 3
```
lightgbm==3.3.2
optuna==2.10.0

```
I ve install both of the above using pip. One thing to mention is that I used skforecast for wrapping the lightgbm model, basically something like this:


```python
from skforecast.ForecasterAutoreg import ForecasterAutoreg

def get_best_hp(df_to_process_with_lags, column_name_for_date, column_name_for_qty):
    
    def objective(trial):

        lgbm_param = {
            'objective': 'mse',
            'verbose': -1,
            'metric': 'mse',
            'seed': 321,
            # 'device_type':'cuda', 
            
            'n_estimators': trial.suggest_categorical('n_estimators', [50, 500, 1000, 2000, 5000]),
            'boosting_type': trial.suggest_categorical('boosting_type',['dart']),
            'max_depth': trial.suggest_categorical('max_depth', [11, 20, 30]),
            'learning_rate': trial.suggest_categorical('learning_rate',  [0.01]),
            'num_leaves': trial.suggest_categorical('num_leaves', [50, 150, 500]),
            
            'lambda_l1':trial.suggest_categorical('lambda_l1', [0.1, 0.3, 0.5, 0.7, 0.9, 1.1, 1.3, 1.5, 1.7, 1.9]),
            'lambda_l2':trial.suggest_categorical('lambda_l2', [0.1, 0.3, 0.5, 0.7, 0.9, 1.1, 1.3, 1.5, 1.7, 1.9]),
            'min_child_samples':trial.suggest_categorical('min_child_samples', [5, 10, 20, 30])
        
        }
        
        cols = [col for col in df_to_process_with_lags.columns if col not in [column_name_for_date, column_name_for_qty]]
        print("--------------Doing CV for Lightgbm model----------")

        rmse_lgbm= []
        mse_lgbm=[]
        # rmse_lgbm_test
        #df_to_process_lightgbm.set_index("ds", inplace=True)

        timeseries_splitcv_object = TimeSeriesSplit(n_splits=4, test_size=4)
        for train_index, test_index in timeseries_splitcv_object.split(df_to_process_with_lags):
            # print("NP ### TRAIN:", train_index, "TEST:", test_index)

            # print("LGBM DF +++ ", df_to_process_with_lags.head(10))
            df_train = df_to_process_with_lags.loc[train_index]
            # print(f"Dataframe train: {df_train}")
            df_test = df_to_process_with_lags.loc[test_index]
            # print(f"Dataframe test: {df_test}")
            forecaster = ForecasterAutoreg(
                regressor=LGBMRegressor(**lgbm_param),
                lags=4,
            )
            # print(forecaster)
            exog_train = df_train[cols]
            exog_test = df_test[cols]
            forecaster.fit(y=df_train[column_name_for_qty], exog=exog_train)
            predictions = forecaster.predict(steps=4, exog = exog_test)
           
            test_error_mse = mean_squared_error(
                y_true=df_test[column_name_for_qty],
                y_pred=predictions
            )
            
            mse_lgbm.append(test_error_mse)

            error_rmse = math.sqrt(test_error_mse)
            print(f"Test error (mse): {error_rmse}")
            rmse_lgbm.append(error_rmse)

        # rmse_lightgbm = mean(rmse_lgbm)
        mse_lightgbm = mean(mse_lgbm)
        

        return  mse_lightgbm

    optuna_lgbm = optuna.create_study(direction='minimize', sampler=TPESampler(seed=321))

    # * n_trials optuna hyperparameter.
    optuna_lgbm.optimize(objective, n_trials=4000)
    
    lgbm_trial = optuna_lgbm.best_trial
    lgbm_trial_params = lgbm_trial.params  
    
    return lgbm_trial_params
```
The one from the above is the function I've used for searching for the best hyperparameters & this is how I call it

```python
dict_with_hp ={}
for number in range(9):
    df = pd.read_csv(f'{number}.csv')
    dict_with_hp[number]= get_best_hp(df, 'ds', 'y')
```

**Comment by jameslamb** [comment]
Thanks for that!

I'm sorry but as described, this is too large for us to investigate and is also not reproducible (for example, missing most `import` statements, relies on CSV files that we can't see).

If you're able to generate a **minimal** reproducible example which doesn't rely on `skforecast` or `optuna`, or to at least describe *specifically* what you expected LightGBM to do and how what you're seeing differs from that expectation, we could help.

But the small team of maintainers here cannot commit to helping to optimize code which heavily uses libraries we don't maintain (e.g. `optuna` and `skforecast`).
