### ISSUE TITLE
[R] auto convert factor to categorical feature

### ISSUE THREAD

**Issue by guolinke** [Microsoft/LightGBM#557]
We already have this in python-package. I think we can add it to the R package as well.
@Laurae2 can you help for this ?

**Comment by Laurae2** [comment]
Going to add a dataset builder with different methods.

Method 1 (only for dense):

* Parse factors -> numeric
* Parse characters -> numeric
* Keep data as dense, but convert to matrix format

Method 2 (default, only for dense):

* Parse characters -> factor
* Parse factors -> one hot encoding
* Convert data to sparse

**Comment by guolinke** [comment]
@Laurae2 
I think method_1 is better. 
Actually, for the categorical feature, but best solution is not the one-hot coding. Using method 1 is more flexible for the future updates.
