### ISSUE TITLE
C++ coredump in LightGBM::Predictor::Predictor by GOMP_parallel

### ISSUE THREAD

**Issue by lioncruise** [microsoft/LightGBM#5573]
## Description

This is the brief coredump stack caused by parallelly invoking LGBM_BoosterPredictForMat, which seems to be realted with openmp, how to troubleshoot this problem?

<img width="1187" alt="image" src="https://user-images.githubusercontent.com/12690984/199939244-618d3af5-b208-4ae6-8837-99349589902b.png">

## Environment info

LightGBM version or commit hash:

v3.3.3

Command(s) you used to install LightGBM

```shell

```

**Comment by jameslamb** [comment]
Thanks for using LightGBM!

A screenshot and a version number is not enough information for maintainers to help you. Please provide at least the following additional information that was requested in the issue template:

* exact commands you used to install LightGBM
* a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) which reproduces the issue
