### ISSUE TITLE
[python-package] outdated callback version in latest python library release

### ISSUE THREAD

**Issue by pavlexander** [microsoft/LightGBM#5575]
## Description
According to the website `early_stopping` function accepts `min_delta` parameter: https://lightgbm.readthedocs.io/en/latest/pythonapi/lightgbm.early_stopping.html

I went to check the code on **github** and can confirm that it in fact exists in the source code: https://github.com/microsoft/LightGBM/blob/4162485da0abb583e548af640c61a8fd6c5a2b06/python-package/lightgbm/callback.py#L367

However, after installing the latest version of the package from pip and invoking a callback function in the code - the code complains that the parameter `min_delta` does not exist..

## Reproducible example

```
    model = lgb.train(
        params,
        train_ds,
        num_boost_round=20,
        valid_sets=[test_ds],
        callbacks=[
            lgb.early_stopping(stopping_rounds=10, min_delta=0.01)
        ])
```

## Environment info

```pip
pip show lightgbm                               
Name: lightgbm
Version: 3.3.3

python --version
Python 3.10.7
```

Command(s) you used to install LightGBM

```shell
pip install lightgbm
```

Windows 10 x64

## Additional Comments

I have installed the latest version of the library so I expect the officially documented functionality to be present in the latest version in the library (**unless it's explicitly stated that the feature is only experimental or is only available in beta/preview version**)..

If the feature is not yet available in latest version then I suggest mention it on the website.. Relevant on this case - a person has faced the same issue 11 months ago: https://stackoverflow.com/questions/70216196/lightgbm-3-3-1-early-stopping-got-an-unexpected-keyword-argument-min-delta

The solution was to install the package from source..

I am wondering if there is something wrong in publishing pipeline if some of the features are not making it to the package repository?!

side note: absolutely astonishing project! Appreciate your work for maintaining this project!

**Comment by jmoralez** [comment]
Thanks for using LightGBM. That feature (along with many others) will be included in the next major release, you can subscribe to #5153 if you want to follow the progress.

Regarding the documentation, even though there have been a couple of releases since it was added, they have been just changes to the R package, so we changed [the docs page](https://lightgbm.readthedocs.io/) to go to v3.3.2 instead of latest by default, but now I see that the website for the project on github has the latest suffix, is that how you got to the docs?

**Comment by pavlexander** [comment]
@jmoralez I found the page on google :)

**Comment by jameslamb** [comment]
Just adding a bit more details to what @jmoralez said... 

* `https://lightgbm.readthedocs.io/en/latest/` = docs for latest commit on `master`
* `https://lightgbm.readthedocs.io/en/{version}` = docs for specific version

You can navigate between versions by modifying the URL or choosing a version from the drop-down in the bottom left corner.

<img width="1723" alt="Screen Shot 2022-11-07 at 2 32 18 PM" src="https://user-images.githubusercontent.com/7608904/200413073-a3fd2437-e92b-4a7d-9f93-041fb58efc79.png">

I'm going to close this.
