### ISSUE TITLE
[swig] switch to SWIG_ADD_LIBRARY() in CMakeLists.txt

### ISSUE THREAD

**Issue by jameslamb** [microsoft/LightGBM#5586]
## Summary

Starting with `cmake` 3.8, compilation of SWIG targets for LightGBM raises the following deprecation warning.

```text
CMake Deprecation Warning at /usr/local/share/cmake-3.23/Modules/UseSWIG.cmake:734 (message):
  SWIG_ADD_MODULE is deprecated.  Use SWIG_ADD_LIBRARY instead.
Call Stack (most recent call first):
  CMakeLists.txt:460 (swig_add_module)
```

The project should be modified to avoid that warning.

## Motivation

Removes a warning in compilation logs, reducing the risk of other important information being missed.

Reduces the risk of LightGBM SWIG compilation failing on future releases of CMake where `SWIG_ADD_MODULE()` is removed.

## Description

1. Replace uses of `SWIG_ADD_MODULE()` in `CMakeLists.txt` with `SWIG_ADD_LIBRARY()`.

2. the minimum required version for CMake should be increased to 3.8 when compiling the SWIG targets.

https://github.com/microsoft/LightGBM/blob/f1d3181ced9fd01f4b2899054abd99be6773e939/CMakeLists.txt#L28-L36

## References

`SWIG_ADD_LIBRARY()` has been available since CMake 3.8 ([docs link](https://cmake.org/cmake/help/latest/module/UseSWIG.html#command:swig_add_library)), which was released in November 2018 ([release details](https://github.com/Kitware/CMake/releases/tag/v3.8.0)).

**Comment by shogohida** [comment]
Hi @jameslamb, I made a pull request which fixes this issue. Please take a look!

https://github.com/microsoft/LightGBM/pull/5603
