### ISSUE TITLE
GPU version gives non-reproducible results even with random seed set

### ISSUE THREAD

**Issue by u39kun** [Microsoft/LightGBM#559]
When training on GPUs, the training results give slightly different results on each run even with the random seed set, whereas training on CPUs with the same exact code gives perfectly reproducible results.

**Comment by Laurae2** [comment]
LightGBM GPU results are not reproducible even though the code/seed is identical. Use the CPU version for reproducibility.

**Comment by wxchan** [comment]
There is a discussion about reproducibility on kaggle https://www.kaggle.com/c/zillow-prize-1/discussion/33719, not sure if it's the same issue.

**Comment by guolinke** [comment]
@wxchan 
It is not the same issue. 
When using same compiler, it is reproducible. 
But it is hard to ensure the reproducible when using different compilers.

For the GPU version. I think the result maybe is the float point sum-up order. 
@huanzhang12 can you give more details ?

**Comment by huanzhang12** [comment]
Yes, GPU uses single precision arithmetic, and we cannot guarantee the exact results. The threads scheduling on GPU will affect the sum-up order, and it is noticeable when using single precision arithmetic. 

For best reproducibility, set `gpu_use_dp=true` to enable double precision math on GPU (but it's slower).

**Comment by u39kun** [comment]
Thanks for the explanation and documentation changes to state this limitation up front via #560.
