### ISSUE TITLE
training and eval with different weights

### ISSUE THREAD

**Issue by dsrub** [microsoft/LightGBM#5593]
Is it possible to use two different weights for training/eval?  For my use case I'd like to train with one weight, and use a custom eval function which uses a different weight.  Of course I can retrieve the weights from an lgbm dataset in my eval function with .get_weights(), but this will retrieve the training weights.  Is this possible?  Is there any hack around this?

**Comment by jmoralez** [comment]
Hi @dsrub, thanks for using LightGBM. What you mean is that you want to have the same object holding both weights, right? Because you can create a second dataset with the same data and label but different weight, like:
```python
import lightgbm as lgb
import numpy as np

X = np.random.rand(100, 2)
y = np.random.rand(100)
train_weight = np.random.rand(100)
valid_weight = np.random.rand(100)
train_ds = lgb.Dataset(X, y, weight=train_weight)
valid_ds = train_ds.create_valid(X, y, weight=valid_weight)
```
