### ISSUE TITLE
Add quantized training

### ISSUE THREAD

**Issue by shiyu1994** [microsoft/LightGBM#5606]
## Summary

Add quantized training algorithm, which accelerates training on both CPU and GPU. See our latest NeurIPS 2022 paper (https://neurips.cc/virtual/2022/poster/53370).

**Comment by jameslamb** [comment]
Interesting! Is there a link to the poster materials that doesn't require creating an account?

<img width="1424" alt="image" src="https://user-images.githubusercontent.com/7608904/204065122-3cb7faba-a042-441d-bf77-818e8e116b1d.png">

**Comment by shiyu1994** [comment]
Maybe this link can be accessed without registration to the conference.
https://nips.cc/Conferences/2022/Schedule?showEvent=53370

**Comment by jameslamb** [comment]
Yep that worked, thank you! Very exciting!

**Comment by replacementAI** [comment]
Is there an update regarding the above?

**Comment by AllenSun1024** [comment]
> Is there an update regarding the above?

It seems like that it's not updated.

**Comment by jameslamb** [comment]
Given that quantized training is now supported for CPU and CUDA, I think this issue can be closed.

I'm closing this. @guolinke @shiyu1994 if I'm wrong about that please do re-open it and add a comment explaining what else still needs to be done.

Thanks for the quick translation from your research work into working, released code in this project that its users can get with just a `pip install`. Pretty exciting!!!

**Comment by jameslamb** [comment]
Ah sorry, did not realize #5933 was not merged yet. I'll re-open this.

**Comment by shiyu1994** [comment]
@jameslamb No worries. I will continue my work in #5933.

**Comment by jameslamb** [comment]
I got too excited about closing old issues, sorry 😆
