### ISSUE TITLE
`Booster.refit()` fails when the booster used a custom objective function `fobj`

### ISSUE THREAD

**Issue by jrvmalik** [microsoft/LightGBM#5609]
## Description
I first train an `lgb.Booster` with a custom objective function. I then try to update the leaf values using another dataset, but it fails on an assertion that the objective must not be `None`.  

## Reproducible example
```
import lightgbm as lgb
import numpy as np
from dataclasses import dataclass

X = np.random.randn(300, 3)
y = np.random.randn(300)
y_new = np.random.randn(300)

data = lgb.Dataset(X, label=y)
params = {"max_depth": 3, 'learning_rate': 0.1}


def fobj(predictions, dataset: lgb.Dataset) -> tuple[np.ndarray, np.ndarray]:
    targets = dataset.get_label()
    return (predictions - targets), np.ones(predictions.shape)
    

model = lgb.train(params, data, num_boost_round=10, keep_training_booster=True, fobj=fobj)
model = model.refit(data=X, label=y_new, decay_rate=0.0)

```

This yields the following error.
```
---------------------------------------------------------------------------
LightGBMError                             Traceback (most recent call last)
Input In [3], in <cell line: 19>()
     15     return (predictions - targets), np.ones(predictions.shape)
     18 model = lgb.train(params, data, num_boost_round=10, keep_training_booster=True, fobj=fobj)
---> 19 model = model.refit(data=X, label=y_new, decay_rate=0.0)

File /data/johnmalik/miniconda3/envs/rig_env-1.25.0/lib/python3.9/site-packages/lightgbm/basic.py:3565, in Booster.refit(self, data, label, decay_rate, **kwargs)
   3543 """Refit the existing Booster by new data.
   3544 
   3545 Parameters
   (...)
   3562     Refitted Booster.
   3563 """
   3564 if self.__set_objective_to_none:
-> 3565     raise LightGBMError('Cannot refit due to null objective function.')
   3566 predictor = self._to_predictor(deepcopy(kwargs))
   3567 leaf_preds = predictor.predict(data, -1, pred_leaf=True)

LightGBMError: Cannot refit due to null objective function.
```

The expected behavior should be getting the same result as this, where the refitting succeeds.
```
import lightgbm as lgb
import numpy as np
from dataclasses import dataclass

X = np.random.randn(300, 3)
y = np.random.randn(300)
y_new = np.random.randn(300)

data = lgb.Dataset(X, label=y)
params = {"max_depth": 3, 'learning_rate': 0.1}


def fobj(predictions, dataset: lgb.Dataset) -> tuple[np.ndarray, np.ndarray]:
    targets = dataset.get_label()
    return (predictions - targets), np.ones(predictions.shape)
    

model = lgb.train(params, data, num_boost_round=10, keep_training_booster=True)
model = model.refit(data=X, label=y_new, decay_rate=0.0)
```

**Comment by jmoralez** [comment]
Hi @jrvmalik, thanks for using LightGBM. This is deliberate because refit doesn't support using a custom objective https://github.com/microsoft/LightGBM/pull/1699#issuecomment-425329484. The reason is that when training we have the option to run one boosting iteration passing the gradients and hessians, but the refit method updates all the trees in one go. https://github.com/microsoft/LightGBM/blob/6fa4673f69fa377477e74f986e216c5c186b5b1f/src/boosting/gbdt.cpp#L353-L389
Supporting this would involve changing the refit method, I'm not sure how extensive these changes would have to be, maybe @guolinke can comment.

**Comment by jrvmalik** [comment]
I see. Yeah it would be great if this was supported!

**Comment by jmoralez** [comment]
Closed in favor of being in https://github.com/microsoft/LightGBM/issues/2302, where we keep all feature requests.

You're welcome to contribute this feature! Please re-open this issue (or post a comment if you are not a topic starter) if you are actively working on implementing this feature.
