### ISSUE TITLE
[R-package] CRAN warning about use of `vsprintf()`

### ISSUE THREAD

**Issue by shiyu1994** [microsoft/LightGBM#5618]
## Description
On Dec 3rd, I received the following email from CRAN

```
[????????? ripley@stats.ox.ac.uk ????????? [https://aka.ms/LearnAboutSenderIdentification?????????????]](https://aka.ms/LearnAboutSenderIdentification?????????????%5d)

Dear maintainer,

Please see the problems shown on
<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcran.r-project.org%2Fweb%2Fchecks%2Fcheck_results_lightgbm.html&data=05%7C01%7Cyushi2%40microsoft.com%7C6bbf2f089d94451d7c7208dad50de56c%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638056552948658112%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=QhvwqS7zT0kfP%2FUXkBOB00Y%2FTm%2FRzCVKSa3FfBl8w1I%3D&reserved=0>.

Please correct before 2022-12-17 to safely retain your package on CRAN.

Do remember to look at the 'Additional issues'.

The CRAN Team
```
We need to fix the issue before 17th Dec.

**Comment by shiyu1994** [comment]
The URL is pasted here for convenience.
https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcran.r-project.org%2Fweb%2Fchecks%2Fcheck_results_lightgbm.html&data=05%7C01%7Cyushi2%40microsoft.com%7C6bbf2f089d94451d7c7208dad50de56c%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638056552948658112%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=QhvwqS7zT0kfP%2FUXkBOB00Y%2FTm%2FRzCVKSa3FfBl8w1I%3D&reserved=0

**Comment by guolinke** [comment]
cc @jameslamb

**Comment by shiyu1994** [comment]
@jameslamb Thanks for the reminder.

**Comment by jameslamb** [comment]
v3.3.4 is now on CRAN (#5619). It's passing all CRAN checks without warnings.

https://cran.r-project.org/web/checks/check_results_lightgbm.html

So this is resolved. Thanks for letting us know so quickly @shiyu1994 !
