### ISSUE TITLE
LGBMRanker prediction value explain

### ISSUE THREAD

**Issue by hhaootian** [microsoft/LightGBM#5620]
How can one explain the score/value of LGBMRanker (lambdarank) prediction? Thanks!

**Comment by MadRabbit05** [comment]
I don't answer the question but it may help.

The relevance score is used to determine final ranking order. Values seems to vary from -??? to 1 #[648].
Output is the predicted score for each item passed as input to the predict function.
The score is the value of the leave defining the input item in the tree.
 
If the predict output is like [-0,10, -0.033, 0.5, 0.6, 0.3], you have to understand that the final order (from highest predicted relevance to lowest) will be [3, 2, 4, 1, 0] (index in input dataset). 
If your dataset have qid/group, the score have to be sort within each qid/group.

**Comment by htian97** [comment]
@MadRabbit05 Thanks for youre explanation. I'm wondering if there's any scientific papers/blogs to present a formal explanation.
