### ISSUE TITLE
is LGBM_BoosterPredictForMat running in parallel? 

### ISSUE THREAD

**Issue by tesla1060** [microsoft/LightGBM#5658]
If LGBM_BoosterPredictForMat is running in parallel is it possible to tell it which cores the functions can use?

**Comment by jameslamb** [comment]
Thanks for using LightGBM. Sorry it took so long for someone to answer you here.

> is LGBM_BoosterPredictForMat running in parallel?

Yes, `LGBM_BoosterPredictForMat()` will parallelize over multiple threads, if you're using a build of LightGBMM linked to OpenMP (the default).

https://github.com/microsoft/LightGBM/blob/e9fface2f7013014a4100270b01f44efd2b920d3/src/c_api.cpp#L2369

https://github.com/microsoft/LightGBM/blob/e9fface2f7013014a4100270b01f44efd2b920d3/src/c_api.cpp#L2372-L2373

https://github.com/microsoft/LightGBM/blob/e9fface2f7013014a4100270b01f44efd2b920d3/src/c_api.cpp#L424

https://github.com/microsoft/LightGBM/blob/e9fface2f7013014a4100270b01f44efd2b920d3/src/c_api.cpp#L440-L447

> is it possible to tell it which cores the functions can use?

It is possible to limit the number of threads used, but I'm not aware of any way to limit *which* specific CPUs execute those threads.

The interface for parallelism in LightGBM is to pass parameter `num_threads`, which controls the size of the thread pool allocated by OpenMP.

When that isn't passed or is passed the value `-1`, the number of threads will be set to environment variable `OMP_NUM_THREADS`.
