### ISSUE TITLE
LightGBM import error again!

### ISSUE THREAD

**Issue by llmercury** [Microsoft/LightGBM#566]
This might be related to issue #499. It appears the same error. Lightgbm 0.1 has been working well ever since. Then I decided to switch to v 0.2. First I cloned the newest repository and then CMake on MSVC. (I followed the installation instruction at: https://github.com/Microsoft/LightGBM/wiki/Installation-Guide#windows-2). It looked like every step was successful. However, Jupyter notebook failed to import Lightgbm. Here are the details.

## Environment info
Operating System: Windows 10 Home, 64 bit
CPU: Intel i7-7700
C++/Python/R version: Microsoft Visual Studio Community 2017/ Python 3.5.2 /Anaconda 4.3.1 (64-bit)

My laptop has 2 hard drives, C: and D:.

This has GPU support. For D:\local\boost_1_64_0\ and D:\local\boost_1_64_0\lib64-msvc-14.0, the location of the Boost binaries, I set them to the system environment variables BOOST_ROOT and BOOST_LIBRARYDIR. No errors during installation. After installation, I checked it by "conda list lightgbm", it shows lightgbm 0.2. 

However, when I imported the lightgbm in Jupyter Notebook, I got Error messages:

## Error Messages:

OSError                                   Traceback (most recent call last)
<ipython-input-1-2ae3725bef24> in <module>()
----> 1 import lightgbm as lgb

D:\ProgramFiles\Anaconda3\envs\py35\lib\site-packages\lightgbm-0.2-py3.5.egg\lightgbm\__init__.py in <module>()
      7 from __future__ import absolute_import
      8 
----> 9 from .basic import Booster, Dataset, PredictionEarlyStopInstance
     10 from .callback import (early_stopping, print_evaluation, record_evaluation,
     11                        reset_parameter)

D:\ProgramFiles\Anaconda3\envs\py35\lib\site-packages\lightgbm-0.2-py3.5.egg\lightgbm\basic.py in <module>()
     29 
     30 
---> 31 _LIB = _load_lib()
     32 
     33 

D:\ProgramFiles\Anaconda3\envs\py35\lib\site-packages\lightgbm-0.2-py3.5.egg\lightgbm\basic.py in _load_lib()
     24     if len(lib_path) == 0:
     25         return None
---> 26     lib = ctypes.cdll.LoadLibrary(lib_path[0])
     27     lib.LGBM_GetLastError.restype = ctypes.c_char_p
     28     return lib

D:\ProgramFiles\Anaconda3\envs\py35\lib\ctypes\__init__.py in LoadLibrary(self, name)
    423 
    424     def LoadLibrary(self, name):
--> 425         return self._dlltype(name)
    426 
    427 cdll = LibraryLoader(CDLL)

D:\ProgramFiles\Anaconda3\envs\py35\lib\ctypes\__init__.py in __init__(self, name, mode, handle, use_errno, use_last_error)
    345 
    346         if handle is None:
--> 347             self._handle = _dlopen(self._name, mode)
    348         else:
    349             self._handle = handle

OSError: [WinError 126] The specified module could not be found

Please help!

**Comment by llmercury** [comment]
I added this line:
print(lib_path) before lib = ctypes.cdll.LoadLibrary(lib_path[0]) in the file D:\Program_Files\Anaconda3\envs\py35\lib\site-packages\lightgbm-0.2-py3.5.egg\lightgbm\basic.py

and  import lightgbm in Jupyter Notebook again and I got:

D:\ProgramFiles\Anaconda3\envs\py35\Lib\site-packages\lightgbm-0.2-py3.5.egg\lightgbm\lib_lightgbm.dll

I did find the lib_lightgbm.dll in the above folder.

**Comment by guolinke** [comment]
@llmercury 
Just try it, and it imports successfully. 
Did you build and install with the administrator permission ?

**Comment by llmercury** [comment]
@guolinke
I'm not sure how to build and install with the administrator permission. Here is what I did.
 
I built it in Administrator Windows Powershell by:

cd LightGBM
mkdir build
cd build
cmake -DCMAKE_GENERATOR_PLATFORM=x64 -DUSE_GPU=1 ..
cmake --build . --target ALL_BUILD --config Release

, and installed it from Anaconda Prompt (py35) by:

D:\PythonModules\LightGBM\python-package>python setup.py install

**Comment by guolinke** [comment]
@llmercury 
I use the same commands, and it success.. 
Did you update/change the boost/opencl ?

**Comment by guolinke** [comment]
@llmercury 
can you try the latest code ? it fixes a potential problem.

**Comment by llmercury** [comment]
@guolinke 
I tried the latest code. The same problem persists.

I did not update or change the boost and opencl. 

I think the only thing I changed before installation was I repaired MSVS 2015 through 'Control Panel' - 'Uninstall or change a program'. That was for installing another module (not LightGBM) because when I did "cmake .. -G”Visual Studio 14 2015 Win64″  cmake could not find compiler. Anyway, the LightGBM was compiled by MSVS 2017 19.10.25019.0.
![imageedit_2_4351452603](https://cloud.githubusercontent.com/assets/10424610/26599489/982be4ce-452d-11e7-8489-52e4f7ea8511.png)

**Comment by guolinke** [comment]
@llmercury 
I see.
from your log, you are using vs2017(msvc14.10). so you need to use ```msvc-14.1-64.exe``` for boost.

**Comment by llmercury** [comment]
Geez! The error persists after I used the msvc-14.1-64.exe! Still the same error. (Very smooth build but failed to import.) I cannot believe that! I'm totally out of ideas now. :(

**Comment by guolinke** [comment]
I remember I also try vs2017 with boost, and it failed..
can you rollback to vs2015 and uninstall boost for 14.1?

**Comment by llmercury** [comment]
I uninstalled both vs2017 and vs2015 and reinstall vs2015 only. I used vs2015 and boost 14.0. Again, the build and installation were very smooth. During building 14 warnings appeared. Nevertheless, no errors. After installation I used 'conda list lightgbm' and showed lightgbm 0.2. 

I added this line:
print(lib_path) before lib = ctypes.cdll.LoadLibrary(lib_path[0]) in the file D:\Program_Files\Anaconda3\envs\py35\lib\site-packages\lightgbm-0.2-py3.5.egg\lightgbm\basic.py

Import lightgbm in Jupyter notebook, I got the same error message, a screen shot:
![cmake_lightgbm_import_error](https://cloud.githubusercontent.com/assets/10424610/26751279/75520432-47ea-11e7-81aa-b1ebd0f2a126.png)

**Comment by guolinke** [comment]
Can you run the example: https://github.com/Microsoft/LightGBM/tree/master/examples/binary_classification 
by using the exe you build with GPU (locate at LightGBM/Release/lightgbm.exe) ?

**Comment by guolinke** [comment]
@llmercury 
Did you upgrade the windows 10 to the 15063.332 ? 
I find the OpenCL.dll are missing after update. 
It should have a "OpenCL.dll" in ```C:\Windows\System32``` . 
It seems can be fixed after re-install nvidia driver.

**Comment by llmercury** [comment]
@guolinke 
Indeed, re-installing nvidia driver solved it! No more import error! Awesome diagnosis. Thanks a lot!
