### ISSUE TITLE
OpenCL error UNKNOWN ERROR CODE -1001 happened in file ../common/oclobject.cpp

### ISSUE THREAD

**Issue by das-ankur** [microsoft/LightGBM#5663]
## Error Message
![image](https://user-images.githubusercontent.com/43563075/210718310-6d2cb25b-7a16-4ccd-ada3-cea012b4aff4.png)

I am using Ubuntu 20.04. I am was trying to execute the given code example: BitonicSort

**Comment by jameslamb** [comment]
This question does nor appear to be related to LightGBM.

If this is somehow related to LightGBM, we need a lot more information to help you. For example, a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the problem you're facing and a explanation of how it is related to LightGBM.
