### ISSUE TITLE
Error installing lightgbm R version on Ubuntu

### ISSUE THREAD

**Issue by Blackfish13** [Microsoft/LightGBM#567]
Hi,

I tried installing the R version of lightgbm on both windows and ubuntu, thinking it was a compiler issue on windows I switched to Ubuntu. When using the command devtools::install_github("Microsoft/LightGBM", subdir = "R-package") I get the following error message:
Can you please offer advice?
## Environment info
Operating System: Ubuntu 16.04 (Xenial)
CPU: I5-4460
C++/Python/R version: 3.4.0

## Error Message:
> devtools::install_github("Microsoft/LightGBM", subdir = "R-package")
Downloading GitHub repo Microsoft/LightGBM@master
from URL https://api.github.com/repos/Microsoft/LightGBM/zipball/master
Installing lightgbm
'/usr/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/tmp/RtmpSYyCXE/devtoolsb8758ea3b68/Microsoft-LightGBM-e04a8bb/R-package'  \
  --library='/home/blackfish/R/x86_64-pc-linux-gnu-library/3.4' --install-tests 

* installing *source* package ‘lightgbm’ ...
** libs
g++ -std=gnu++11 -I/usr/share/R/include -DNDEBUG -I../..//include -DUSE_SOCKET -Wno-deprecated-declarations    -fopenmp  -std=c++11 -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g -c lightgbm-all.cpp -o lightgbm-all.o
g++ -std=gnu++11 -I/usr/share/R/include -DNDEBUG -I../..//include -DUSE_SOCKET -Wno-deprecated-declarations    -fopenmp  -std=c++11 -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g -c lightgbm_R.cpp -o lightgbm_R.o
lightgbm_R.cpp: In function ‘LGBM_SER* LGBM_BoosterPredictForFile_R(LGBM_SE, LGBM_SE, LGBM_SE, LGBM_SE, LGBM_SE, LGBM_SE, LGBM_SE, LGBM_SE)’:
lightgbm_R.cpp:507:32: error: too few arguments to function ‘int LGBM_BoosterPredictForFile(BoosterHandle, const char*, int, int, int, PredictionEarlyStoppingHandle, const char*)’
     R_CHAR_PTR(result_filename)));
                                ^
lightgbm_R.cpp:28:8: note: in definition of macro ‘CHECK_CALL’
   if ((x) != 0) { \
        ^
In file included from ./lightgbm_R.h:6:0,
                 from lightgbm_R.cpp:14:
../..//include/LightGBM/c_api.h:520:23: note: declared here
 LIGHTGBM_C_EXPORT int LGBM_BoosterPredictForFile(BoosterHandle handle,
                       ^
lightgbm_R.cpp: In function ‘LGBM_SER* LGBM_BoosterPredictForCSC_R(LGBM_SE, LGBM_SE, LGBM_SE, LGBM_SE, LGBM_SE, LGBM_SE, LGBM_SE, LGBM_SE, LGBM_SE, LGBM_SE, LGBM_SE, LGBM_SE)’:
lightgbm_R.cpp:555:64: error: cannot convert ‘double*’ to ‘int64_t* {aka long int*}’ for argument ‘13’ to ‘int LGBM_BoosterPredictForCSC(BoosterHandle, const void*, int, const int32_t*, const void*, int, int64_t, int64_t, int64_t, int, int, PredictionEarlyStoppingHandle, int64_t*, double*)’
     nrow, pred_type, R_AS_INT(num_iteration), &out_len, ptr_ret));
                                                                ^
lightgbm_R.cpp:28:8: note: in definition of macro ‘CHECK_CALL’
   if ((x) != 0) { \
        ^
lightgbm_R.cpp: In function ‘LGBM_SER* LGBM_BoosterPredictForMat_R(LGBM_SE, LGBM_SE, LGBM_SE, LGBM_SE, LGBM_SE, LGBM_SE, LGBM_SE, LGBM_SE, LGBM_SE)’:
lightgbm_R.cpp:580:58: error: cannot convert ‘double*’ to ‘int64_t* {aka long int*}’ for argument ‘10’ to ‘int LGBM_BoosterPredictForMat(BoosterHandle, const void*, int, int32_t, int32_t, int, int, int, PredictionEarlyStoppingHandle, int64_t*, double*)’
     pred_type, R_AS_INT(num_iteration), &out_len, ptr_ret));
                                                          ^
lightgbm_R.cpp:28:8: note: in definition of macro ‘CHECK_CALL’
   if ((x) != 0) { \
        ^
/usr/lib/R/etc/Makeconf:168: receptet för målet ”lightgbm_R.o” misslyckades
make: *** [lightgbm_R.o] Fel 1
ERROR: compilation failed for package ‘lightgbm’
* removing ‘/home/blackfish/R/x86_64-pc-linux-gnu-library/3.4/lightgbm’
Installation failed: Command failed (1)
Warning message:
GitHub repo contains submodules, may not function as expected!

**Comment by guolinke** [comment]
@Blackfish13 
The latest commit break the R package,  you can rollback to version ```2cca82834ff8b40ccf117a1929081aff325ba193``` to temporarily solve this.

**Comment by Blackfish13** [comment]
Thanks! How do I rollback to that version? Sorry, I'm new to github etc.

**Comment by guolinke** [comment]
@Blackfish13 
```git reset --hard 2cca82834ff8b40ccf117a1929081aff325ba193 ```

**Comment by Blackfish13** [comment]
Thank! I used devtools::install_github("Microsoft/LightGBM@2cca82834ff8b40ccf117a1929081aff325ba193", subdir = "R-package")

Mucho gracias
