### ISSUE TITLE
[python-package] What is the best way for Booster to fit the Booster model to residuals?

### ISSUE THREAD

**Issue by johnkimdy** [microsoft/LightGBM#5673]
I am trying to convert the DecisionTreeClassifier model by SciKit Learn to LGBM using the existing model specs. The only problem is that I would have to import the lgbm model using lgb.Booster, but this doesn't have the '.fit()' feature that Scikit-learn provides. What is the best alternative for the LGBM Booster model? refit, retrain, or update? Is there a way to replicate the model by using lightgbm.lgbmclassifier?  Thanks,

**Comment by jameslamb** [comment]
Thanks for using LightGBM!

The `lightgbm` Python package has a scikit-learn compatible interface.

See this example:

https://github.com/microsoft/LightGBM/blob/c2d2c99f44dcaad1f6dfc05d877e47aad13ddfc9/examples/python-guide/sklearn_example.py#L24-L30

and the docs at https://lightgbm.readthedocs.io/en/v3.3.4/pythonapi/lightgbm.LGBMClassifier.html

**Comment by johnkimdy** [comment]
Is there a way to access each individual tree and fit each tree separately? for Booster or sklearn LGBM?

**Comment by jameslamb** [comment]
@johnkimdy what do you mean by "fit each tree separately", exactly?

LightGBM training builds an ensemble of trees.

**Comment by johnkimdy** [comment]
1. can we run LGBMRegressor iteratively for each individual tree to replicate lgb.train?
2. Is LGBMRegressor the counterpart of decisiontreeregressor in sklearn?

**Comment by johnkimdy** [comment]
> @johnkimdy what do you mean by "fit each tree separately", exactly?
> 
> LightGBM training builds an ensemble of trees.

can we run LGBMRegressor iteratively for each individual tree to replicate lgb.train?
Is LGBMRegressor the counterpart of decisiontreeregressor in sklearn?

**Comment by jameslamb** [comment]
@johnkimdy sorry for the delayed response.

No, `LGBMRegressor.fit()` fits an *ensemble* of trees, meaning a collection of multiple trees whose output is combined to produce a prediction.

The closest equivalent in `scikit-learn` is `sklearn.ensemble.HistGradientBoostingRegressor` ([docs](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.HistGradientBoostingRegressor.html)).
