### ISSUE TITLE
[python-package] Add min_delta for early stopping to package release

### ISSUE THREAD

**Issue by gcaria** [microsoft/LightGBM#5686]
It's been quite some time that I see the argument min_delta being available for the early stopping in the master branch, but not in a release.

I don't see an open issue about this, am I missing anything?

**Comment by jameslamb** [comment]
The next release of LightGBM will be v4.0.0. You can go to #5153 to subscribe to updates about it's timing.

We've been facing a severe lack of maintainer availability and attention here over the last year, apologies for how long some changes have sat on `master` unreleased.
