### ISSUE TITLE
Skip Ignore Columns When Prediction

### ISSUE THREAD

**Issue by namespace-io** [microsoft/LightGBM#5733]
## Description

I have 7 feature columns in lightgbm cli distributed training while the 4th column is ignored by ignore column,
I want to input an array which its' length is 6 not 7  and `predict_disable_shape_check=True` because i don't  want to input the 4th column data.
but it's behavior is not expected. What can i do to skip ignore columns when prediction.
## Reproducible example

```
file_name2 = 'test_model_10.txt'
booster2 = lgb.Booster(model_file = file_name2)
X_test = np.array([[4,32965,74,241,17752,90,0], [4,23764,74,220,57336,84,1098516]])
X1_test = np.array([[4,32965,74,17752,90,0], [4,23764,74,57336,84,1098516]])


# make predictions on new data
y_pred = booster2.predict(X_test)
print(y_pred)
y_pred1 = booster2.predict(X1_test,predict_disable_shape_check=True)
print(y_pred1)
```
Output: 
```
[0.00000000e+00 2.72066642e-09]
[9.93991283e-01 3.12861130e-09]
```
Expected:
```
[0.00000000e+00 2.72066642e-09]
[0.00000000e+00 2.72066642e-09]
```
## Environment info
I use lightgbm cli to do distributed training, version 2.3.1
python lib lightgbm 3.2.1
```shell
wget https://github.com/microsoft/LightGBM/archive/refs/tags/v2.3.1.tar.gz && \
tar -xvzf v2.3.1.tar.gz  && \
mkdir LightGBM-2.3.1/build && \
cd LightGBM-2.3.1/build && \
cmake .. && \
make -j4 && \
make install 
```
## Addition Comments
It seems that if i put ignore column to  the end of array(eg. put the ignore column to 7th feature when training and prediction) and set `predict_disable_shape_check=True`. the output is same which is expected. but it seems not so convenient for users.

**Comment by shiyu1994** [comment]
> It seems that if i put ignore column to the end of array(eg. put the ignore column to 7th feature when training and prediction) and set predict_disable_shape_check=True. the output is same which is expected. but it seems not so convenient for users.

Yes. If the ignored column appears in the middle of the features, the features after the ignored column will have a different feature index with the trained model.

If you want to save memory for ignored columns, perhaps you should sparse matrix (or use LibSVM format without the ignored column, but with the index of all other columns unchanged.), instead of numpy array. The sparse matrix still have 7 columns (instead of 6), but with the ignored column storing 0's.
