### ISSUE TITLE
R Session crashes everytime with LightGBM

### ISSUE THREAD

**Issue by abhishekkant** [Microsoft/LightGBM#574]
Hi 

I am trying to use LightGBM - R Interface in my experiment using RStudio. 

Each time I try to run the experiment, RSession crashes. I am not sure why's that happening.

## Environment info
Operating System: Windows 10 Pro -10.0.15063
CPU: Intel i5-6200 CPU with 2 cores; 4 Logical with HyperV
RAM: 8 GB
C++/Python/R version: R version 3.3.3 (2017-03-06)
LightGBM package Version: 0.1 (via packageVersion)

## Error Message:
<img width="364" alt="rstudiokilled" src="https://cloud.githubusercontent.com/assets/1725266/26676738/a720e5aa-46e6-11e7-97e0-fd466f363ff6.PNG">

If it helps, I am getting the following in the event log: 
Faulting application name: rsession.exe, version: 1.0.143.0, time stamp: 0x58efc68f
Faulting module name: lightgbm.dll, version: 0.0.0.0, time stamp: 0x58b92639
Exception code: 0xc0000005
Fault offset: 0x00000000000030f3
Faulting process id: 0xe84
Faulting application start time: 0x01d2dac506a28a18
Faulting application path: C:\Program Files\RStudio\bin\x64\rsession.exe
Faulting module path: C:\Users\asus\Documents\R\win-library\3.3\lightgbm\libs\x64\lightgbm.dll
Report Id: 53d5234e-3b4c-4d7b-84b8-83cc617f6e29
Faulting package full name: 
Faulting package-relative application ID: 

## Reproducible examples
I have prepared a github repo with my sample data and R Script that I am using available here: 
https://github.com/abhishekkant/healthcarequeryclassifier/blob/master/QueryClassifier-LightGBM.R

## Steps to reproduce
Download the test data set and the R file. Execute from RStudio. 
Observe the crash.

Kindly do have a look and advise.

Cheers
Abhishek Kant

**Comment by guolinke** [comment]
@abhishekkant 
can you reproduce by these demos?  https://github.com/Microsoft/LightGBM/tree/master/R-package/demo

**Comment by abhishekkant** [comment]
I just tried the multiclass demo from the repo and it worked fine! No crashes! 
Is it my data or config?

**Comment by guolinke** [comment]
@abhishekkant 
can you provide more details ? e.g. crash log, which line cause crash ?

**Comment by abhishekkant** [comment]
The crash occurs on the line where we create the model with lgb.train command (line 43)...

I am not sure where I can find further logs.. I had reproduced the one from the event viewer in the main question..

**Comment by Laurae2** [comment]
@abhishekkant Can you provide a more simpler example? (one example we can directly run from an interactive R console without having to download stuff beforehand)

**Comment by guolinke** [comment]
@abhishekkant 
updates

**Comment by GlobalMin** [comment]
I also get this issue constantly now.

**Comment by alberthkcheng** [comment]
+1. I am using Mac.

I think it is data specific. My crashed one has only 1, 0, NA.
could it be data type issue. I am trying to get a simple reproducible example.

**Comment by guolinke** [comment]
@Laurae2

**Comment by StrikerRUS** [comment]
I found related issue first and commented about this error in python package in #833.
