### ISSUE TITLE
At which stage of the algorithm does GOSS operate?

### ISSUE THREAD

**Issue by CHENHUI-X** [microsoft/LightGBM#5742]
Hi, I have a question about the GOSS algorithm. According to the content I saw in the paper and the integration information on the Internet, I learned that GOSS can reduce the amount of data through weight sampling. I want to know the execution order of the GOSS algorithm and the histogram algorithm : first use the GOSS algorithm to sample the dataset, and then divide the sample data to bins , right ? Or what order, please help me.

**Comment by AllenSun1024** [comment]
Firstly, the data sample strategy is **bagging** by default.

>So, GOSS algorithm won't work if you don't set core parameter **data_sample_strategy = goss**.

Secondly, constructing the histogram is after sampling the dataset.

**Comment by CHENHUI-X** [comment]
> Firstly, the data sample strategy is **bagging** by default.
> 
> > So, GOSS algorithm won't work if you don't set core parameter **data_sample_strategy = goss**.
> 
> Secondly, constructing the histogram is after sampling the dataset.

Got it, thank you very much !
