### ISSUE TITLE
Upload trained LGBMRanker model in Elastic Search

### ISSUE THREAD

**Issue by mjadhav1** [microsoft/LightGBM#5763]
Hi, 

Is lightgbm especially lgbmranker model currently supporting model integration with elastic search like ranklib or xgboost supports? If not, is there any other way to integrate ranker model file/pickle file in elastic search?

**Comment by jameslamb** [comment]
@mjadhav1 Sorry it took so long for someone to answer you here.

We do not maintain any integrations with Elasticsearch in this repo. I suspect that by "like ranklib or xgboost supports", you're referring to this project:

* https://elasticsearch-learning-to-rank.readthedocs.io/en/latest/training-models.html
* https://github.com/o19s/elasticsearch-learning-to-rank

Pretty cool project!

I recommend that you take this feature request over there. Mention this issue there.

My personal opinion.... having that project take on ONNX support as @robhowley suggested in https://github.com/o19s/elasticsearch-learning-to-rank/issues/424 is a very promising path to adding support for LightGBM there, which would make that project more easily extensible to other model types.
