### ISSUE TITLE
Why the EFB bundling of exclusive features is loss-less

### ISSUE THREAD

**Issue by falcon8241** [microsoft/LightGBM#5767]
In the LightGBM paper, it is suggested the exclusive features can be merged as long as "the values of the original
features can be identified from the feature bundles." I am not sure if I follow this argument completely. I think we can claim the merge of exclusive features is loss-less only if we can achieve the same splitting of samples using the merged feature as we can achieve using the original features. However, this is not the case for the merged features. For example, assuming there are 5 samples (A to E) and 2 mutually exclusive features:

> | Sample | Feature A | Feature B | Merged Feature AB |
> |--------|-----------|-----------|---------------------|
> | A      | 0         | 1         | 6                   |
> | B      | 0         | 9         | 14                  |
> | C      | 3         | 0         | 3                   |
> | D      | 1         | 0         | 1                   |
> | E      | 0         | 0         | 0                   |

By splitting Feature A alone, we can split samples as 
ABE vs. CD
ABEDE vs. C

By splitting Feature B alone, we can split samples as
AB vs. CDE
ACDE vs. B

However, splitting the combined feature AB, we can split samples as 
ABCD vs. E
ABC vs. DE
AB vs. CDE
B vs. ACDE

It is obvious that we can not generate certain split (e.g. ABE vs. CD) using the merged feature AB. How does this affect the tree model which LightGBM finally trained? Am I missing something?

**Comment by guolinke** [comment]
the split finding is not on the merged histogram. 
The per-feature histograms will be recoveried for the split finding.

**Comment by falcon8241** [comment]
Thanks @guolinke. In this case, why the EFT speed up the training, as we recovered the per-feature histogram? What is the difference from using original feature directly?

**Comment by vudzung06011992** [comment]
The EFB is confusing me:
Based on the above discussion:
1. How to find split point from merged features? If merged features is not for finding split points, what is the benefit of merged features?
2. you said that " Iterating Histograms ( bin * column) costs very little." ==> what is the EFB benefit of reduction of the number of features ?

**Comment by guolinke** [comment]
> The EFB is confusing me: Based on the above discussion:
> 
> 1. How to find split point from merged features? If merged features is not for finding split points, what is the benefit of merged features?
> 2. you said that " Iterating Histograms ( bin * column) costs very little." ==> what is the EFB benefit of reduction of the number of features ?


1. split points are found on the histograms, not the merged features. 
2. It reduces the time of the of iterating data (#row * #bundle_features), and the time of finding the split points are the same as previous  (#bin * #features). Please note the #bin is very small, such as 255, while #row could be very large like millions.
