### ISSUE TITLE
[LightGBM] [Warning] Unknown parameter: data_sample_strategy

### ISSUE THREAD

**Issue by simpsus** [microsoft/LightGBM#5781]
## Description
above error message appears when I pass the parameter in the params dictionary

## Reproducible example

`lgb.train(params={'data_sample_stragety':'goss'},train_set=lgb.Dataset(data=np.random.rand(100,100), label=np.random.rand(100,1)))`

## Environment info

LightGBM version or commit hash:
python package, train api, version 3.3.5

**Comment by jameslamb** [comment]
`data_sample_strategy` was added to LightGBM in #4827, which hasn't made it into a release yet.

To take advantage of it, you'll have to build from source. You can also subscribe to notifications on #5153 to be notified when the v4.0 release goes out.

**Comment by simpsus** [comment]
thank you very much. I just wonder then why it is listed in the [official documentation](https://lightgbm.readthedocs.io/en/latest/Parameters.html)

**Comment by jameslamb** [comment]
You won't find it in the docs for the latest release (`v3.3.5`).

https://lightgbm.readthedocs.io/en/v3.3.5/Parameters.html

That link you've shared, https://lightgbm.readthedocs.io/en/latest/Parameters.html, is built from this repo's `master` branch.

Sorry for the confusion.

**Comment by simpsus** [comment]
My bad. I mistook the "latest" in the URL for the latest release. No idea why I am surfing that version!
