### ISSUE TITLE
lightgbm.LGBMRegressor always outputs the same predicted values when inputting different samples.

### ISSUE THREAD

**Issue by SteamerLee** [microsoft/LightGBM#5783]
## Description

I tried to make a demo of LGBMRegressor by generating random samples, but it always outputs the same predicted results.

## Reproducible example

from lightgbm import LGBMRegressor
import numpy as np
trainX = np.random.rand(10, 100) # 10 samples with 100 features
trainY = np.random.rand(10)
m = LGBMRegressor()
m.fit(trainX, trainY)
testX = np.random.rand(5, 100)
predX = m.predict(testX)
print(predX) # the predicted values of the five testing samples are the same.

## Environment info

LightGBM version or commit hash:

Command(s) you used to install LightGBM

```shell

```

**Comment by jameslamb** [comment]
Thanks for using LightGBM.

To get LightGBM to fit to such a small dataset, you'll need to override the default values of some of its parameters.

See https://stackoverflow.com/a/66728185/3986677.

**Comment by SteamerLee** [comment]
I see. Thanks for your prompt response!!!
