### ISSUE TITLE
Segmentation fault (core dumped) on imbalanced binary classification

### ISSUE THREAD

**Issue by NanqingD** [Microsoft/LightGBM#579]
Please search your question on previous issues, stackoverflow or other search engines before you open a new one.

For bugs and unexpected issues, please provide following information, so that we could reproduce on our system.

## Environment info
Operating System: Ubuntu 16.04 LTS
CPU:  Intel(R) Core(TM) i7-6800K CPU @ 3.40GHz
C++/Python/R version:
Python 2.7.12
numpy 1.12.1

## Error Message:
[LightGBM] [Info] Number of positive: 1057, number of negative: 186442
[LightGBM] [Info] Total Bins 56
[LightGBM] [Info] Number of data: 187499, number of used features: 4
[LightGBM] [Info] Number of positive: 1057, number of negative: 186442
[LightGBM] [Info] Total Bins 56
[LightGBM] [Info] Number of data: 187499, number of used features: 4
[LightGBM] [Info] Number of positive: 1058, number of negative: 186443
[LightGBM] [Info] Total Bins 56
[LightGBM] [Info] Number of data: 187501, number of used features: 4
[LightGBM] [Info] Number of positive: 1058, number of negative: 186443
[LightGBM] [Info] Total Bins 56
[LightGBM] [Info] Number of data: 187501, number of used features: 4
[LightGBM] [Info] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Trained a tree with leaves=9 and max_depth=4
[LightGBM] [Info] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Trained a tree with leaves=8 and max_depth=4
[LightGBM] [Info] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Trained a tree with leaves=7 and max_depth=4
[LightGBM] [Info] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Trained a tree with leaves=9 and max_depth=4
Segmentation fault (core dumped)

## Reproducible examples
I want to reproduce [https://www.kaggle.com/mmueller/road-2-0-4](url) in LightGBM. (The original code is xgboost. I didn't want to outperform the xgboost, just want to test LightGBM.

## Steps to reproduce

1. Make necessary replacement:
```
import lightgbm as lgb
......

lgb_params = {
    'seed': 0,
    'colsample_bytree': 0.7,
    'silent': 1,
    'subsample': 0.7,
    'learning_rate': 0.01,
    'objective': 'binary',
    'max_depth': 3,
    'num_parallel_tree': 1,
    'min_child_weight': 2,
    'metric': 'auc',
}

dtrain = lgb.Dataset(train, label=y)
res = lgb.cv(lgb_params, dtrain, num_boost_round=5, nfold=4, seed=0, stratified=True, early_stopping_rounds=1, verbose_eval=1, show_stdv=True)
```

**Comment by guolinke** [comment]
@NanqingD 
just run it successfully. 
Can you try the latest code ?  (re-clone, rebuild dll, then re-install python package. )

**Comment by NanqingD** [comment]
@guolinke 
It works now after reinstall it.

However, I installed it two days ago and it didn't work for same code. Interesting.

**Comment by guolinke** [comment]
@NanqingD 
Not the bug. It is because your dataset didn't meet the min split rule (min_child_weight=2).
