### ISSUE TITLE
[python-package] Some loops may be parallelized in Python Engine so as to save time for training.

### ISSUE THREAD

**Issue by AllenSun1024** [microsoft/LightGBM#5796]
## Description
Loop [for cb in callbacks_before_iter](https://github.com/microsoft/LightGBM/blob/2fe2bf0675ef127a29f9bc49511fc0099cf3e140/python-package/lightgbm/engine.py#L244) will be optimized by using [multiprocessing](https://docs.python.org/3/library/multiprocessing.html) if there exist multiple callbacks.
The same for loop [for cb in callbacks_after_iter](https://github.com/microsoft/LightGBM/blob/2fe2bf0675ef127a29f9bc49511fc0099cf3e140/python-package/lightgbm/engine.py#L261).

## Reproducible example
Not necessary to reproduce.

## Environment info

LightGBM version or commit hash:  **LightGBM 3.3.5.99**

Command(s) you used to install LightGBM

```shell
git clone --recursive https://github.com/microsoft/LightGBM
cd LightGBM
mkdir build
cd build
cmake -DUSE_GPU=1 -DOpenCL_LIBRARY=/usr/local/cuda/lib64/libOpenCL.so -DOpenCL_INCLUDE_DIR=/usr/local/cuda/include/ ..
make -j$(nproc)
cd ..
```

## Additional Comments
No comments.

**Comment by jameslamb** [comment]
Thanks for using LightGBM and taking the time to post this!

I don't support this proposal, though. Callbacks can contain arbitrary user-provided code, and can interfere with each other (for example, one could modify the Booster in `env.model` and another could then rely on that modified Booster), so I don't think it would be safe for LightGBM to assume that they could be executed in any order (which is what I think you're suggesting `mulltiprocessing` be used for).

If you can provide a **specific** example showing estimated performance gains from such a change, we'd be happy to discuss this more. But without that, I don't think `lightgbm` should change those `for` loops over callbacks that you've linked to into concurrent execution of multiple callbacks.

**Comment by AllenSun1024** [comment]
Thanks for your reply!

This is just an idea when I try to improve the training speed of lightgbm, so I can't give a specific example yet. The prerequisite **`there is no order dependency between callbacks`** must be met if we want parallelism, just like what you've said.
