### ISSUE TITLE
There is no parameter data_sample_strategy and goss is to be implemented via 'boosting' parameter. Documentation says otherwise

### ISSUE THREAD

**Issue by nitinmnsn** [microsoft/LightGBM#5799]
## Description
As per the [documentation](https://lightgbm.readthedocs.io/en/latest/Parameters.html#data_sample_strategy) ```goss``` is to be implemented via ```data_sample_strategy```, however the api returns a warning ```Unknown parameter: data_sample_strategy```

## Reproducible example
```
import pandas as pd
import numpy as np
import lightgbm
from sklearn.datasets import make_classification
from model_selection import optuna_lgbmcv_selection

#creating dummy data
data = make_classification(n_samples = 10_000, n_features = 20, n_informative = 7)

#setting dummy column names
dt = pd.DataFrame(data[0],columns = [str(i) for i in range(data[0].shape[1])])
#dummy labels
yt = pd.Series(data[1])

d = lightgbm.Dataset(dt,label=yt)
lightgbm.train(params = {'learning_rate':0.1,"data_sample_strategy":'goss'},train_set = d)
```

## Environment info

LightGBM version or commit hash:
3.3.5

Command(s) you used to install LightGBM

```
```pip install lightgbm```

```

**Comment by jmoralez** [comment]
Hey @nitinmnsn, thanks for using LightGBM. I believe this is the same as #5781 and it's due to the fact that the `latest` docs point to the `master` branch, not the latest release. Sorry for the confusion.
