### ISSUE TITLE
Changing only a variable of a dataset

### ISSUE THREAD

**Issue by BlindApe** [Microsoft/LightGBM#580]
This would be very useful for obtain permutation based relative importance: 

Computing the prediction over the original dataset and changing a variable with a random permutation of it is possible to estimate the effect of each variable.
Just now is necessary construct the lgb.dataset for each variable so is more costly.

Could be possible in future a method in lgb.dataset class to do this?

**Comment by Laurae2** [comment]
@BlindApe I think this is not possible due to how LightGBM binary datasets are constructed. This is the same for xgboost.

**Comment by BlindApe** [comment]
@Laurae2 I guessed the problem would be the same. Really would be nice for both xgboost and lightgbm this feature, not only for relative importance but for marginal plots and other applications.
I hope in future other tools have a binary compressed data representation that let change a column without computing all the object.
