### ISSUE TITLE
Question about predictive performance

### ISSUE THREAD

**Issue by nipnipj** [microsoft/LightGBM#5806]
Is there any difference in the predictive performance of lgbm when used in R vs when used in Python?

**Comment by jameslamb** [comment]
Thanks for using LightGBM.

LightGBM's main logic is implemented in C/C++, and both the R and Python libraries call that same code. We try to make the libraries' functionality match as closely as possible, but of course there are differences.

That is as specific an answer as we can give to such a broad question. If you identify areas where one of those LightGBM APIs is performing better or worse than the other, please report them on this project's issues page.
