### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by royshan** [Microsoft/LightGBM#582]
## Environment info
Operating System: Ubuntu 16.04
CPU: Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz
C++/Python/R version: gcc 5.4.0

## Error Message:
Segmentation fault (core dumped)

## Reproducible examples
examples/binary_classification

## Steps to reproduce
1. git clone the current repository
2. follow the official installation procedure
3. go to examples/binary_classification and run 'lightgbm config=train.conf'

**Comment by guolinke** [comment]
@royshan 
which version you are using ? 
the latest master branch ?

**Comment by royshan** [comment]
yes, the latest master branch

**Comment by royshan** [comment]
deep@ubuntu:~/LightGBM/examples/binary_classification$ ~/LightGBM/lightgbm config=train.conf
[LightGBM] [Info] Finished loading parameters
[LightGBM] [Info] Loading weights...
[LightGBM] [Info] Loading weights...
[LightGBM] [Info] Finished loading data in 0.102863 seconds
[LightGBM] [Info] Number of positive: 3716, number of negative: 3284
[LightGBM] [Info] Total Bins 6143
[LightGBM] [Info] Number of data: 7000, number of used features: 28
[LightGBM] [Info] Finished initializing training
[LightGBM] [Info] Started training...
[LightGBM] [Info] Trained a tree with leaves=63 and max_depth=11
Segmentation fault (core dumped)

**Comment by royshan** [comment]
@guolinke 

thank you so much for the quick response. the fix works.
