### ISSUE TITLE
Multiclass classification doesn't improve with custom objective

### ISSUE THREAD

**Issue by anitaschaefer** [microsoft/LightGBM#5839]
## Description
I wanted to implement a custom objective for a multiclass classification task. According to the [documentation](https://lightgbm.readthedocs.io/en/latest/pythonapi/lightgbm.LGBMClassifier.html#lightgbm.LGBMClassifier.__init__), a custom objective for a multiclass classification task receives y_pred in the shape of [n_samples, n_classes]. Though when I debug the code, y_pred is of shape [n_samples * n_classes], which is why I reshape it in the custom objective function. Since the inputs are flat, I had to flatten the outputs grad and hess as well (otherwise "TypeError: Wrong type(ndarray) for gradient. It should be list, numpy 1-D array or pandas Series" was raised). The model performance doesn't improve with training, the output looking like this:

[1]     training's multi_error: 1       training's multi_logloss: 34.5388
[2]     training's multi_error: 1       training's multi_logloss: 34.5388
[3]     training's multi_error: 1       training's multi_logloss: 34.5388
[4]     training's multi_error: 1       training's multi_logloss: 34.5388
[5]     training's multi_error: 1       training's multi_logloss: 34.5388
[6]     training's multi_error: 1       training's multi_logloss: 34.5388
[7]     training's multi_error: 1       training's multi_logloss: 34.5388
[8]     training's multi_error: 1       training's multi_logloss: 34.5388
[9]     training's multi_error: 1       training's multi_logloss: 34.5388
[10]    training's multi_error: 1       training's multi_logloss: 34.5388

## Reproducible example
```python
import numpy as np
import torch
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
import lightgbm as lgb

def cross_entropy_obj(y_true, y_pred):
    n_classes = len(np.unique(y_true))
    y_pred = y_pred.reshape((y_true.size, -1), order='F')
    n_samples = y_pred.shape[0]
    y_true = np.identity(n_classes)[y_true.astype(int)]
    y_pred = np.clip(y_pred, a_min=1e-7, a_max=1.0)

    grad = (y_pred - y_true)  
    hess = y_pred * (1 - y_pred)
    return grad.flatten(order="F"), hess.flatten(order="F")

X, y = load_iris(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

model = lgb.LGBMClassifier(objective=cross_entropy_obj,
                       n_estimators=10, random_state=42)
model.fit(X_train, y_train, eval_metric="multi_error",
          eval_set=(X_train, y_train), verbose=True)
```
## Environment info

LightGBM version or commit hash: Version: 3.3.5

Command(s) you used to install LightGBM

```shell
pip install lightgbm
```

**Comment by jmoralez** [comment]
Hi @anitaschaefer, thanks for using LightGBM. The change to use 2D collections hasn't been included in a release yet, the documentation you're looking at refers to the master branch, not the last released version.

You can find an example on how to implement multilogloss as a custom objective with the 1D collections below
https://github.com/microsoft/LightGBM/blob/caa087bcc5de5023097de84646976013fc3e353d/tests/python_package_test/test_dask.py#L274-L290

Please let us know if you have further doubts.

**Comment by anitaschaefer** [comment]
@jmoralez your loss function works in my code, thanks!
