### ISSUE TITLE
[LightGBM] [Warning] Contains only one class?

### ISSUE THREAD

**Issue by kyoungrok0517** [microsoft/LightGBM#5842]
## Description
I see `[LightGBM] [Warning] Contains only one class` warning even though the Dataset contains multiple classes properly. Here's the dataset.

## Reproducible example
```python
params = {
 'bagging_fraction': 0.95,
 'bagging_freq': 1,
 'boosting_type': 'dart',
 'device_type': 'gpu',
 'drop_rate': 0.1,
 'feature_fraction': 0.75,
 'gpu_use_dp': True,
 'lambda_l1': 5,
 'lambda_l2': 70,
 'learning_rate': 0.08525718720079171,
 'max_bin': 63,
 'max_depth': 12,
 'metric': 'multi_error',
 'min_data_in_leaf': 200,
 'min_gain_to_split': 0.001234125039267734,
 'n_estimators': 1000,
 'num_leaves': 1780,
 'objective': 'multiclassova',
 'num_gpu': 2,
 'verbose': 0,
 'num_class': 4
}

train_data = ...

from collections import Counter
Counter(train_data.get_label())
# Counter({0.0: 12, 4.0: 12, 3.0: 12, 5.0: 12})

# Here I see "[LightGBM] [Warning] Contains only one class"
model = lgb.train(params, train_data, valid_sets=[valid_data])
```

## Environment info

LightGBM version or commit hash: 3.3.5  

Command(s) you used to install LightGBM

```shell
pip install lightgbm --install-option=--gpu
```

## Other question
* Only one GPU is in use even though I set `params["num_gpu"] = 2`. What would be the reason?

**Comment by jameslamb** [comment]
Thanks for using LightGBM, and apologies for the long delay.

Can you please provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), some fully-self-contained code we could copy and run which replicates this?

This warning is about the content of the `Dataset`, but your report doesn't include information about the `Dataset` other than your claim that there's more than one value in the target. So as of now we don't have enough information to investigate this without guessing, which wouldn't be an efficient use of maintainers' limited time.

For example...are you able to replicate this with one of the datasets from `sklearn.datasets`? Or synthetic data generated with `numpy` code? Does the issue persist if you remove parameters related to GPU-based training?
