### ISSUE TITLE
[Question] Need clarification for histogram subtraction and FixHistogram

### ISSUE THREAD

**Issue by haoul124** [microsoft/LightGBM#5862]
Hi all, I am a new user of LightGBM and I am trying to understand how histogram construction is handled. So I have two main questions:
1. Histogram subtraction: There is an illustrative example from this [blog post](https://robotenique.github.io/posts/gbm-histogram/):

![Example](https://robotenique.github.io/img/gbm4.png)
  where the author shows we only need to calculate the histogram gradient values for the smaller child of a split. The subtract function here https://github.com/microsoft/LightGBM/blob/d0dfceec377d34cddd6722f870d073f7aa64ca2d/src/treelearner/feature_histogram.hpp#L79-L83 seems to agree with the explanation. Now what I don't get is that for numerical features, at each leaf we find splits on the sorted histogram bins' boundaries. It means that all feature values belonging to the same bin should fall into one of the two child leafs: smaller or larger, not both.

  If that is the case, then the subtract method basically zeros out the bins in the larger leaf which belong to the smaller leaf? The two child leaf histograms are "exclusive" and cannot have non-zero gradient values in the same bin at the same time. However, the figure above shows an example where both child leaves have non-zero gradient values at all three bins. How can it happen?

2. I have also a question around the FixHistogram function here:
https://github.com/microsoft/LightGBM/blob/d0dfceec377d34cddd6722f870d073f7aa64ca2d/src/treelearner/serial_tree_learner.cpp#L400-L403

If I understand correctly, when performing a split and constructing child leaves' histograms, the `most_frequent_value` bins are ignored and recovered later. It is mentioned here https://github.com/microsoft/LightGBM/issues/4221#issuecomment-1073553838. Now the code I just linked seems to do so for the smaller child leaf. However, in order to fix the histogram, we need to know the sum of gradients first. And to know the sum of gradients for the smaller child leaf, we need to know the gradient values of all its bins. So why do we have fix histogram here? It feels like a chicken and egg problem for me.

I can kinda understand it if the fix histogram function is used only for the larger child leaf, because we can derive the sum of gradients from subtraction. But for smaller leaf we need to calculate the sum from scratch.

If you know the answer to just 1 of the two questions, please feel free to help. Thanks in advance!

**Comment by guolinke** [comment]
for question 1, there are multiple features, not just one feature. Different features have different histogram, and will get different subtraction results. 
for question 2. all features share the same sum_gradient and sum_hessian.
