### ISSUE TITLE
class lightgbm.Booster :      gbm.eval  don't have a  parameter  like gbm.best_iteration

### ISSUE THREAD

**Issue by guicunbin** [Microsoft/LightGBM#587]
gbm  is a lightgbm.Booster
gbm.predict   has  a   parameter:  　gbm.best_iteration
but  why  gbm.eval_train  and  gbm.eval_valid   don't  have  this parameter,
this  is a  problem to eval   my  gbm  model.

**Comment by Laurae2** [comment]
Why is it a problem? You can do this, for instance on binary logloss:

```r
library(data.table)
perf <- as.numeric(rbindlist(temp_model$record_evals$test$binary_logloss))
min(perf)
which.min(perf)
```

**Comment by guicunbin** [comment]
@Laurae2       thank  you,   I solved  it ,  I can use this:       
      ***  eval_valid =   gbm.eval( gbm.predict(lgb_Dataset.data,  gbm.best_iteration) )  ***
but  I  think  if  there  is  a  parameter  like  gbm.best_iteration  in  gbm.eval_valid() ,    it  will  more easily !

**Comment by Laurae2** [comment]
@wxchan "but I think if there is a parameter like gbm.best_iteration in gbm.eval_valid() , it will more easily !" ?

**Comment by wxchan** [comment]
I think eval_train() and eval_valid() is only used for eval current iteration during training.

**Comment by guicunbin** [comment]
I use  gbm.best_iteration to predict   X_test,
So meanwhile  I  need  to  use  gbm.best_iteration  to  eval_train()  and  eval_valid()  to eval  my  model .
so  I think eval_train()  and eval_valid()  need  this  parameter  to  keep pace with  gbm.predict(X_test,  gbm.best_iteration).

**Comment by wxchan** [comment]
eval_train() and eval_valid() is used for one iteration, and it supposed to be private method. 

use evals_result in lgb.train if you want to monitor evals_result in train and valid set.
