### ISSUE TITLE
Documentation: How to improve prediction speed.

### ISSUE THREAD

**Issue by arthurwolf** [microsoft/LightGBM#5879]
## Summary

I'd like to learn how to improve the speed of predictions.
Currently, running prediction takes on average 2200ms in my setup (~860 features, predicting for a single row). I'd need it to take significantly less.
If there is some type of method, or configuration, to do this, I'd like to learn and implement it.

It seems like convert_model might lead to something faster, maybe? But from just the documentation I have not so far been able to get that to work. I'll keep exploring though.

Once I learn this, I'd make a PR to actually add the information learned to the documentation, so I contribute back and others can learn about this too.

## Motivation

Speed is good.

**Comment by jmoralez** [comment]
Hey @arthurwolf, thanks for using LightGBM. Can you provide more details on which API you're using? Also model size would be useful (number of trees and leaves)

**Comment by arthurwolf** [comment]
Thanks for the reply.

I'm using the command line interface, and my configs are pretty much the default (based on the github examples) in terms of trees/leaves/everything else.
My datasets have between 450 and 1200 columns, and around 34000 rows.

**Comment by jmoralez** [comment]
If you're using the CLI with `task=predict` for a single sample then loading the model could take most of the time. Are you isolating the prediction time?

**Comment by arthurwolf** [comment]
Thanks for the reply, it's very possible that model loading is most of the time.

I'm not sure how to isolate prediction time, I tried increasing verbosity but did not get anything useful, is there some option/function I'm missing?

Assuming this is the issue, how would I go about gaining speed? I'm going to try loading the model from a ramdisk tonight, but I'm guessing some processing will also be involved, any way I can get the loading time down? Any recommendation?

Thanks!

**Comment by jmoralez** [comment]
That's exactly what I meant, preload the model and run several predictions with it. You can probably get some speedup by using numpy arrays instead of pandas dataframe, since it seems you're not using categorical features and thus can avoid the conversion.

Also, here's how we test the model to if-else if you want to give it a shot:
https://github.com/microsoft/LightGBM/blob/d47006f4d018a9dfe59a06e935ea8a411d25e4de/.ci/test.sh#L40-L45

**Comment by arthurwolf** [comment]
> That's exactly what I meant, preload the model and run several predictions with it. You can probably get some speedup by using numpy arrays instead of pandas dataframe, since it seems you're not using categorical features and thus can avoid the conversion.

I'll try numpy, I hope I get a significant speedup, 2 seconds just won't work for my needs.

> Also, here's how we test the model to if-else if you want to give it a shot:

I *just* found this a few hours ago and implemented it. I couldn't get it to work.

My problem is, I replace the cpp file with the generated one, I compile, but then when I run the command with a predict.conf file, it absolutely wants a model file (and crashes if none is provided), which makes the entire process pointless (the whole goal here is to skip having to load a model...).

Is there some way to get this to work without loading a model?

For reference here is what I do:

```
#!/bin/sh

# Define the folder name
folder_name="/tmp/lightgbm-cpp/"

# Check if the folder exists
if [ ! -d "$folder_name" ]
then
    # If the folder doesn't exist, clone a Git repository into it
    git clone --recursive git@github.com:microsoft/LightGBM.git "$folder_name"
fi

# Move to the folder.
cd "$folder_name"

# Copy the cpp file in place.
cp /home/arthur/dev/test-file.cpp "$folder_name/src/boosting/gbdt_prediction.cpp"

# Make the build folder.
mkdir build

# Move to the build folder.
cd "$folder_name/build"

# Run cmake.
cmake ..

# Run make.
make lightgbm -j4
```

then I run:

```
./lightgbm config=/home/arthur/dev/xxx/predict.conf predict_disable_shape_check=true
```

and it complains abotu not having a model file if I give none. or if I give one, it just loads that which makes the entire process useless.

how do I get around this? am I doing something wrong?

thanks for a ll the help!

**Comment by arthurwolf** [comment]
Here is the result:

```
╭─arthur at aquarelle in ~/dev/btc/champs on main✘✘✘ 23-05-16 - 18:11:09
╰─⠠⠵ time ts-node src/tools/TestLGBMServer.ts                                                                                                                                                                                                                                                                                     on main|✚3…13
{
  data_loading_time: 0.01931492204312235,
  predicting_time: 0.003187835041899234,
  prediction: [ 0.42408509950307505 ]
}
ts-node src/tools/TestLGBMServer.ts  2,29s user 0,08s system 196% cpu 1,208 total
╭─arthur at aquarelle in ~/dev/btc/champs on main✘✘✘ 23-05-16 - 18:11:12
╰─⠠⠵ time ts-node src/tools/TestLGBMServer.ts                                                                                                                                                                                                                                                                                     on main|✚3…13
{
  data_loading_time: 0.017587607027962804,
  predicting_time: 0.0027302640373818576,
  prediction: [ 0.42408509950307505 ]
}
ts-node src/tools/TestLGBMServer.ts  2,12s user 0,10s system 191% cpu 1,160 total
╭─arthur at aquarelle in ~/dev/btc/champs on main✘✘✘ 23-05-16 - 18:11:13
╰─⠠⠵ time ts-node src/tools/TestLGBMServer.ts                                                                                                                                                                                                                                                                                     on main|✚3…13
{
  data_loading_time: 0.02091433701571077,
  predicting_time: 0.0030097090057097375,
  prediction: [ 0.42408509950307505 ]
}
ts-node src/tools/TestLGBMServer.ts  2,20s user 0,06s system 186% cpu 1,207 total
╭─arthur at aquarelle in ~/dev/btc/champs on main✘✘✘ 23-05-16 - 18:11:15
╰─⠠⠵ time ts-node src/tools/TestLGBMServer.ts                                                                                                                                                                                                                                                                                     on main|✚3…13
{
  data_loading_time: 0.019319797051139176,
  predicting_time: 0.00293577101547271,
  prediction: [ 0.42408509950307505 ]
}
ts-node src/tools/TestLGBMServer.ts  1,97s user 0,15s system 193% cpu 1,096 total
╭─arthur at aquarelle in ~/dev/btc/champs on main✘✘✘ 23-05-16 - 18:11:17
╰─⠠⠵ time ts-node src/tools/TestLGBMServer.ts                                                                                                                                                                                                                                                                                     on main|✚3…13
{
  data_loading_time: 0.03697547595947981,
  predicting_time: 0.005554488976486027,
  prediction: [ 0.42408509950307505 ]
}
ts-node src/tools/TestLGBMServer.ts  2,20s user 0,08s system 189% cpu 1,204 total
╭─arthur at aquarelle in ~/dev/btc/champs on main✘✘✘ 23-05-16 - 18:11:20
╰─⠠⠵             
```

are the timings measured in seconds ??

if so, it seems like loading/prediction is actually extremely fast, and there is some other kind of overhead in either loading/running the script, or in the HTTP calls? Am I correct? or is it measured in minutes or something?

**Comment by arthurwolf** [comment]
Ok, it actually takes two full seconds to just start a typescript script...

Didn't realize that... will look into why and how to fix it, but it's irrelevant to this issue, looks like this is solved.

Thank you **so much** for all the help.
