### ISSUE TITLE
Ordinal Objective Function(s) in Multiclass Classification

### ISSUE THREAD

**Issue by asmichaels** [microsoft/LightGBM#5882]
## Summary

I am working on a classification problem where the target values have some order to them. I would appreciate a native objective function that increases the penalty for a prediction that is further from the target in terms of order, given it is equally far in probability terms.

## Motivation

Many classification problems exhibit some kind of order - even if small. I think many users would be interested in the option to define their own custom distance matrix between the target classes, and have the objective function of the model take this into account in the training process.

## References

- https://aclanthology.org/2022.coling-1.407.pdf
    - https://github.com/glanceable-io/ordinal-log-loss

**Comment by jmoralez** [comment]
Hey @asmichaels, thanks for using LightGBM. You can use a custom objective function through `fobj` as described [here](https://lightgbm.readthedocs.io/en/v3.3.5/pythonapi/lightgbm.train.html).
