### ISSUE TITLE
[Question] What is `gain` computing?

### ISSUE THREAD

**Issue by adfea9c0** [microsoft/LightGBM#5891]
Hi, I'm trying to better understand the algorithm in LightGBM, and I'm a bit stuck looking at the function that computes the gain of a split [1]. My question is: what is the `gain` actually computing, mathematically?

Let's assume `objective="regression_l2"` for the moment, `GetLeafGain` has two branches. The second one seems to be more general, first computing the `output`  and then using `GetLeafGainGivenOutput` to compute the incremental gains. Let's simplify notation a bit and write:
 - `L[i] = -gradients_[i] / hessians_[i]` the output we are trying to predict
 - `vc = output, vp = parent_output` the outputs of the potential leaf we are considering and the existing parent node.

Intuitively I would imagine the gain to be `\sum_i (L[i] - vp)^2 - (L[i] - vc)^2`. This rewrites to:
`\sum_i (2 L[i] (vc - vp) - vp^2 - vc^2)`. But the function in the snippet, `GetLeafGainGivenOutput` doesn't look anything like that:

https://github.com/microsoft/LightGBM/blob/d47006f4d018a9dfe59a06e935ea8a411d25e4de/src/treelearner/feature_histogram.hpp#L1099-L1100 

I can see why you would drop the `vp^2` term because it is constant across all splits. But other than that I'm a bit lost. The other direct branch of GetLeafGain looks even simpler, it doesn't involve the `output` at all. (Although I assume in that branch, `output = -sum_gradients / sum_hessians` ?)

Could someone point me to what this gain actually is? I tried reading the original paper that comes with LightGBM but I couldn't find a formula.

https://github.com/microsoft/LightGBM/blob/d47006f4d018a9dfe59a06e935ea8a411d25e4de/src/treelearner/feature_histogram.hpp#L1073-L1102

**Comment by guolinke** [comment]
There are several ways to get this equation. The second-order Taylor expansion (https://xgboost.readthedocs.io/en/latest/tutorials/model.html) is the most intuitive one.
