### ISSUE TITLE
EFB algorithm

### ISSUE THREAD

**Issue by vudzung06011992** [microsoft/LightGBM#5892]
lightgbm uses the efb algorithm to bundle features to reduce the number of features.
The new bundle feautue will aggregate split points from the component features. Therefore, instead of the model having to scan multiple variables to try to select each split point, the model will only need to try on the bundle feature.
I would expect that decision tree with initial variables and decision tree model with only bundle variables will give the same results. However when I try experiments, the results are different.
So I understand that the bundle feature can change the outcome of the model run.
I want to ask that:
1. Does bundling exactly change the cutoff results?
2. The purpose of using bundling (minimizing the number of variables), in the end, for what?

**Comment by guolinke** [comment]
EFB is an almost loss-less algorithm. In most cases, it should produce the same trees. However, several factors may cause the different results.
1) the floating-point sum-up error. As the histogram is built in different way, the results may slightly different.
2) The bundle features are determined based on a sampled data for efficency, it may cause some conflicts.

The purpose of using EFB is to speed up the training, as the time of constructing feature histogram is reduced.
