### ISSUE TITLE
Split point finding step in EFB

### ISSUE THREAD

**Issue by vudzung06011992** [microsoft/LightGBM#5893]
Regarding the EFB algorithm, I am confused about the split finding step of EFB. Please let me know which below statements are true (I am trying to give the prediction of the algorithm):

(1) if each of N exclusive features have m bins (discritized value) then the feature bundle (from N exclusive features) should have (N * m) bins in order not to skip any discritized value; if not, I assume that the information is actually lost during bundling.
(2) All non-zeros value of each original features will fall into one bin of the feature bundle. Therefore, the feature bundle should have at least N bins.
(3) The histogram (gradient histogram) of exclusive features are preserved and used during the spliting point step. Each time a new tree is build, the histogram of exclusive features need to be build again?
(4) If the statement 3 is true. From my understand, the original features need to be extracted from the feature bundle to calculate the gradient histogram each time the new tree is built.

I hope that you can spend time on helping me clarify those questions. I look forward to receiving your response.

Sincerely,

**Comment by guolinke** [comment]
In any cases, the histogram is always rebuilt for each tree, for both normal features and bundled features. 

The bundled feature is to merge several features into one feature. And the histogram is dynamically rebuilt during training.

**Comment by vudzung06011992** [comment]
if each of N exclusive features have m bins (discritized value) then the feature bundle (from N exclusive features) should have (N * m) bins in order not to skip any discritized value?

**Comment by guolinke** [comment]
yes, basically it is.
