### ISSUE TITLE
LGBMClassifier.fit is very slow in EMR cluster when using pex

### ISSUE THREAD

**Issue by gunjan075** [microsoft/LightGBM#5895]
## Description
`clf_lgb = lgb.LGBMClassifier(boosting_type='dart', learning_rate=0.01, importance_type='gain', class_weight = 'balanced')`
`clf_lgb.fit(X_train, y_train)` is very slow when we package the lightgbm in [pex](https://pex.readthedocs.io/en/v2.1.137/)

we use pex for packing all our application and dependencies to run in EMR cluster as pyspark job

But when i run the same code without packaging into pex it runs very fast.

## Reproducible example
run spark submit 
1.zip dependencies and application in a zip file and run `fit`  =>Faster
2.make pexfile using command pex -r requirements.txt  -o env.pex -vvv and run spark-submit  =>very slow

## Environment info
EMR cluster linux

LightGBM version or commit hash:
lightgbm==3.3.2
Command(s) you used to install LightGBM

```shell
pip install lighgbm =>in .venv and zip =>fast
pex -r requirements.txt  -o env.pex =>slow
```

**Comment by gunjan075** [comment]
Answer 1 I am trading both model with same data and same parameters.

Answer 2 whn I run spark submit without packaging the lightgbm in. Pex it runs faster
When I package lightgbm in. Pex and distribute the package in cluster and run it then it's slower.
Slow only when I call model.fit()

Answer 3 I know there is synapseml but I just want to use standard package

**Comment by jameslamb** [comment]
It's good that you're using the same data and same parameters. But **are the models the same?**. i.e., do they generate the same predictions on a fixed set of data? Have the same feature importances?

> Answer 2 ... it's slower

I understand that you're saying one method is slower. Can you please describe **how much slower**? And have you confirmed that your training job is the only thing running on the cluster at the time that you're running model training, so these comparisons are fair?
