### ISSUE TITLE
Odd behavior in multithreading with python

### ISSUE THREAD

**Issue by miguelgfierro** [Microsoft/LightGBM#590]
## Environment info
Operating System: Ubuntu kernel: 4.4.0-78-generic
CPU:
C++/Python/R version: GCC 4.4.7, python 3.5.2 

## Error Message:
When using the sklean API in python (in a notebook) and leaving nthreads to the default value, -1, the system doesn't use all the processors. If you define nthreads=20, it runs correctly, then in you define nthreads=-1 it runs correctly again. It looks there is a problem witht he initialization

## Reproducible examples
https://github.com/Azure/fast_retraining/blob/new_parameters/experiments/02_BCI.ipynb

**Comment by guolinke** [comment]
@miguelgfierro 
When set ```num_thread=-1```, actually, it is ignored. So it the ```num_thread``` is still 20 after the second time set it to ```-1```. 
And the default value of ```num_thread``` is set by openmp. So its values vary according to compiler and platform. But its expect value should be the max num_threads of current platform.
