### ISSUE TITLE
[Question] Clarification on Catboost's `misclass_cost_matrix` and LightGBM's `auc_mu_weights` for 'auc-mu'

### ISSUE THREAD

**Issue by YangWu1227** [microsoft/LightGBM#5905]
In Catboost's implementation `auc_mu`, the [misclass_cost_matrix](https://catboost.ai/en/docs/concepts/loss-functions-multiclassification#AUC) parameter represents the cost of misclassifying a sample from class 'j' as class 'i.' On the other hand, LightGBM has the `auc_mu_weights` parameter. Are these two parameters the same, and if so, could you clarify whether auc_mu_weights[i * n + j] corresponds to the cost of misclassifying a sample from class 'j' as class 'i' or vice versa? Thanks.

**Comment by Recepguel** [comment]
No they are not. Auc_mu_weights is introduced to alleviate class skew issue when there is a heavy class skew. Here is the corresponding part in the paper cited in lightgbm documentation. Link: http://proceedings.mlr.press/v97/kleiman19a/kleiman19a.pdf

![Image 17 06 23 at 14 36](https://github.com/microsoft/LightGBM/assets/43893851/8f606c08-4762-467e-84a5-544d0310b205)

**Comment by YangWu1227** [comment]
@Recepguel Thanks for the clarification.
