### ISSUE TITLE
[CUDA] Regression metrics for cuda_exp

### ISSUE THREAD

**Issue by Xuweijia-buaa** [microsoft/LightGBM#5908]
## Summary
Only a few metrics (evaluation) in current master branch have CUDA implementations. More metrics (evaluation) should be implemented on CUDA. 
I open this issue to first add one or more regression metrics for new CUDA version.
```[tasklist]
### Tasks
- [x] regression metrics
```

**Comment by guolinke** [comment]
Your contribution is very welcomed!

**Comment by shiyu1994** [comment]
@Xuweijia-buaa Thanks for you contribution!

**Comment by Xuweijia-buaa** [comment]
It is my pleasure

**Comment by Xuweijia-buaa** [comment]
it's my pleasure! @shiyu1994 @guolinke

**Comment by jameslamb** [comment]
I believe this is closed by #5924.

It appears to me that all of LightGBM's built-in regression metrics now have CUDA support.

https://github.com/microsoft/LightGBM/blob/ef2a49cd3bc595b55898c626a53c5519b24b5541/src/metric/metric.cpp#L19-L81
