### ISSUE TITLE
@bushmanov 's GPU issue (crash on OpenCL kernel compile)

### ISSUE THREAD

**Issue by Laurae2** [Microsoft/LightGBM#591]
Reference: https://github.com/Microsoft/LightGBM/pull/584#issuecomment-306174083 (to declutter the thread)

@bushmanov @guolinke @huanzhang12 

> Successfully built with this instructions
> 
> ```
> [LightGBM] [Info] This is the GPU trainer!!
> [LightGBM] [Info] Total Bins 137
> [LightGBM] [Info] Number of data: 5211, number of used features: 116
> [LightGBM] [Info] Using GPU Device: GeForce GTX 1080 Ti, Vendor: NVIDIA Corporation
> [LightGBM] [Info] Compiling OpenCL Kernel with 16 bins...
> ```
> 
> but crashed at the last line (even though as I said there are no problem with standard build instructions and Python interface). Any suggestions are greatly appreciated!

Does it work on CLI?

**Comment by bushmanov** [comment]
When I compare the @guolinke R build to "normal" explicit build via  `cmake/make` I see that in R build's  `lightgbm` is missing at the root. When I copy it from another build and execute:

`$./lightgbm config=train.conf device=gpu`

the command completes successfully:

```
[LightGBM] [Info] Finished loading parameters
[LightGBM] [Info] Loading weights...
[LightGBM] [Info] Loading weights...
[LightGBM] [Info] Finished loading data in 0.055578 seconds
[LightGBM] [Info] Number of positive: 3716, number of negative: 3284
[LightGBM] [Info] This is the GPU trainer!!
[LightGBM] [Info] Total Bins 6143
[LightGBM] [Info] Number of data: 7000, number of used features: 28
[LightGBM] [Info] Using GPU Device: GeForce GTX 1080 Ti, Vendor: NVIDIA Corporation
[LightGBM] [Info] Compiling OpenCL Kernel with 256 bins...
[LightGBM] [Info] GPU programs have been built
[LightGBM] [Info] Size of histogram bin entry: 12
```
and so on...

**Comment by Laurae2** [comment]
> The issue has been resolved after restarting RStudio
