### ISSUE TITLE
Err Msg: LightGBMError: GPU Tree Learner was not enabled in this build. Please recompile with CMake option -DUSE_GPU=1

### ISSUE THREAD

**Issue by studiocardo** [microsoft/LightGBM#5927]
## Environment info

LightGBM version or commit hash:

Command(s) you used to install LightGBM

```shell

```

**Comment by jameslamb** [comment]
I'm closing this. There is nothing we can do with a report that only says "Err Msg".

If you want help here, please clearly describe the issue you're facing, with enough detail for others to help investigate.

**Comment by studiocardo** [comment]
The thread closed before I had the change to reverify the installation.  I will open a new thread.

**Comment by jameslamb** [comment]
Please don't create a new issue. You can edit this one, I'll re-open it.
