### ISSUE TITLE
lightgbm.readthedocs.io redirects to v3.3.2 not the latest version available (v3.3.5)

### ISSUE THREAD

**Issue by jaceklaskowski** [microsoft/LightGBM#5930]
https://lightgbm.readthedocs.io/ should redirect to the latest version available (3.3.5 atm).

**Comment by jameslamb** [comment]
Thanks so much for reporting that!

I found the relevant configuration in the readthedocs Admin page

<img width="633" alt="image" src="https://github.com/microsoft/LightGBM/assets/7608904/22f8a0ec-5945-4672-bb9e-782b77ed6f9b">

and updated it to v3.3.5. I now see that page redirecting to v3.3.5 correctly.

```shell
curl -I curl -I https://lightgbm.readthedocs.io
```

```text
HTTP/2 302
date: Thu, 15 Jun 2023 14:32:00 GMT
content-type: text/html; charset=utf-8
content-length: 0
location: https://lightgbm.readthedocs.io/en/v3.3.5/
```

**Comment by jaceklaskowski** [comment]
Shouldn't it be `latest` or similar since it's done manually rather than through a readthedocs configuration file or some other automated way?

As said [here](https://docs.readthedocs.io/en/stable/config-file/v2.html#migrating-from-the-web-interface), RTD does not support `Default version` through a configuration file 😞

**Comment by jameslamb** [comment]
> shouldn't it be `latest` or similar

In this project, `latest` on RTD points to the docs built from the most recent commit merged to the target branch (`master`). See e.g. https://lightgbm.readthedocs.io/en/latest/index.html.

I agree with you though... it would be preferable to have the base URL https://lightgbm.readthedocs.io redirect to the docs for the most recent **release**.

On each new release, we update the tag `stable` to point to that new release. I just enabled building from that tag on RTD, and changed the settings such that https://lightgbm.readthedocs.io/ now redirects to https://lightgbm.readthedocs.io/en/stable.

```shell
curl -I https://lightgbm.readthedocs.io
```

```text
HTTP/2 302
date: Mon, 19 Jun 2023 06:58:31 GMT
content-type: text/html; charset=utf-8
content-length: 0
location: https://lightgbm.readthedocs.io/en/stable/
```

So now, to summarize

* `{base_url}` = redirects to `{base_url}/stable`
* `{base_url}/latest` = most recent commit on `master`
* `{base_url}/stable` = commit that `stable` tag points to (most recent release from https://github.com/microsoft/LightGBM/releases)
* `{base_url}/v{n}.{n}.{n}` = docs from a specific release

cc @guolinke @shiyu1994 @jmoralez so you're aware of this change to the docs hosting.

Thanks for bringing it to our attention.
