### ISSUE TITLE
LightGBM R installation breaking whole R installation

### ISSUE THREAD

**Issue by Laurae2** [Microsoft/LightGBM#594]
I am wondering if the R installation is hitting other files in the R folder.

After trying several installations, I am now getting always this error:

```r
> install.packages("ggplot2")
Error in install.packages : missing value where TRUE/FALSE needed
> install.packages("shiny")
Error in install.packages : missing value where TRUE/FALSE needed
> install.packages("lattice")
Error in install.packages : missing value where TRUE/FALSE needed
```

Tried with different packages, same issue. I also tried on another computer (just a simple installation from scratch), just trying to install it broke the whole R installation (cannot install any package anymore).

![image](https://cloud.githubusercontent.com/assets/9083669/26786155/e486ce38-4a05-11e7-9dac-27a8eea0707d.png)

**Comment by guolinke** [comment]
@Laurae2 
It seems is the cache problem. 
can you try to restart the r session, then install other packages?

**Comment by Laurae2** [comment]
@guolinke I wiped all temp folders and tried to install other packages, it always get this error now.

**Comment by Laurae2** [comment]
Reproduced on a fresh machine:

![image](https://cloud.githubusercontent.com/assets/9083669/26786718/cf4cc232-4a07-11e7-938c-64b410ceb896.png)

It seems the LightGBM installation script is not letting anything run anymore when it gives an error (what is weird is I'm not seeing the folder lock in the R installation, which should appear when a package installation happens).

**Comment by guolinke** [comment]
@cbecker 
I just try it on a windows, and I can install other packages after install lightgbm

**Comment by guolinke** [comment]
@Laurae2 
Oh sorry, i just reproduce it.

**Comment by guolinke** [comment]
@Laurae2 It seems is a bug of R in windows:

https://stackoverflow.com/questions/44054022/installing-package-is-failing-with-error-in-if-file-existsdest-file-mtime

Can you try on the ubuntu ?

**Comment by Laurae2** [comment]
@guolinke Works correctly in Ubuntu.

I tried R-patched and can't reproduce the error.

Current solutions:

* Switch to R-patched
* Reinstall R (you can keep library folder, not a problem)
* Turn off computer, then turn it on (for some reason, "restart" sometimes keeps the issue - maybe due to Windows' Fast Boot)
