### ISSUE TITLE
[Request] Slack team

### ISSUE THREAD

**Issue by henry0312** [Microsoft/LightGBM#595]
We can create a [Slack](https://slack.com/) team (also can use 'lightgbm' as team name), where users can freel free to ask how to use, tuning and contirube.

**Comment by henry0312** [comment]
May I create a team?

**Comment by guolinke** [comment]
@henry0312 
sure. feel free to create it 😄

**Comment by henry0312** [comment]
@guolinke Thanks! I'll do.

**Comment by henry0312** [comment]
@guolinke please tell me your e-mail address.

**Comment by guolinke** [comment]
@henry0312 
i@yumumu.me

**Comment by henry0312** [comment]
@guolinke I just sent you an invitation.
BTW, I don't know you can use Slack in China 🤔

**Comment by henry0312** [comment]
@guolinke I also gave you owner permmision. Please check https://lightgbm.slack.com/admin/settings.
