### ISSUE TITLE
How to use gpu with C_API?

### ISSUE THREAD

**Issue by n4sbsxp** [microsoft/LightGBM#5966]
For some personal reason I need to run the code in c++ but I didn't found any function showing how to change the device in the document. [https://lightgbm.readthedocs.io/en/latest/C-API.html](https://lightgbm.readthedocs.io/en/latest/C-API.html)

**Comment by wil70** [comment]
Hi @n4sbsxp, did you find a solution to this?
Thanks
w

**Comment by n4sbsxp** [comment]
> Hi @n4sbsxp, did you find a solution to this? Thanks w

nah, you can try rewritting the code with cuda and recompile it.

**Comment by jmoralez** [comment]
How are you using the C API? If you're using for example `LGBM_BoosterCreate` you can specify `device="gpu"` in the parameters.

**Comment by wil70** [comment]
Hi @jameslamb , 

I'm not sure how @n4sbsxp is doing it?

I'm have been using 'device=gpu', but I'm blocked by https://github.com/microsoft/LightGBM/issues/6220

Best

Wil
