### ISSUE TITLE
tiny logic bug? branch v2.0 run on iris dataset

### ISSUE THREAD

**Issue by hlee13** [Microsoft/LightGBM#597]
## Error Message:
[LightGBM] [Info] Finished loading parameters
[LightGBM] [Fatal] No usable features in data file iris.train
Met Exceptions:
No usable features in data file

## Steps to reproduce

1.
2.
3.

**Comment by guolinke** [comment]
@hlee13 
paramaters ? 
iris dataset is very small, you can try to set ```min_data=1``` .

**Comment by hlee13** [comment]
thanks
