### ISSUE TITLE
[docs] R API docs not included in readthedocs PDF

### ISSUE THREAD

**Issue by Sinansi** [microsoft/LightGBM#5973]
I downloaded the documentation PDF. The documentation date is July 13, 2023. The R API is not included in the documentation. Please, include R API in the pdf documentation.

Thank you!

**Comment by jameslamb** [comment]
Thanks for using LightGBM.

What does "downloaded the documentation PDF" mean, specifically? Can you please provide a link describing what you're referring to?

**Comment by Sinansi** [comment]
The link for the documentation. 

https://lightgbm.readthedocs.io/en/stable/index.html

Scroll down and click on "Read the Docs", then go to "Downloads".

**Comment by jameslamb** [comment]
Interesting! I did not know readthedocs provided that.

You can view the R docs in your browser by following the "R API" link from that same page: https://lightgbm.readthedocs.io/en/stable/R/reference/

Or get a PDF of the R package's manual from CRAN: https://cran.r-project.org/web/packages/lightgbm/lightgbm.pdf

----

Out of curiosity... why do you need a PDF of the documentation? Your answer would help us to understand the value of spending time trying to figure out how to change our readthedocs configuration to include that.

**Comment by Sinansi** [comment]
Thats a good idea James. I will check it on CRAN. Although, I prefer to get the PDF from readthedocs, since it is usually more recent, and it is being a primary source, directly from your company.

I read the documentation on PDF because I convert the PDF into word, then I edit or summarize the word document to the part of the documentation that fit my needs. Reading from a website does not allow me to edit, neither does it allow me to add notes to the important parts of the documentation. Then finally, I paste the important notes in the code.

One reason I prefer R over Python, is that in R everything is in PDF.

**Comment by Sinansi** [comment]
I will use the CRAN PDF. Hopefully, they update it soon. You can close the case.

Thank you!

**Comment by jameslamb** [comment]
Thanks for taking the time to explain that, we really appreciate it! I'm sorry that the readthedocs PDF doesn't currently meet your needs.

> I will use the CRAN PDF. Hopefully, they update it soon

CRAN is only updated when we push a new version of the library...which I'll hopefully be doing today.

I'll close this for now. Thanks again for using LightGBM!

**Comment by jameslamb** [comment]
CRAN rejected v4.0.0 of the R package twice because of the issue described in #5987.

The next release will also not go to CRAN bevause we haven't fixed that yet.

Please subscribe to that issue to be notified when it's resolved.

**Comment by Sinansi** [comment]
Thanks for the update. I will subscribe to the issue you linked.
