### ISSUE TITLE
Python bindings fail to build without internet connection

### ISSUE THREAD

**Issue by yurivict** [microsoft/LightGBM#5979]
## Description
They build with the connection, but not in an isolated VM:
```
===>  Building for py39-lightgbm-4.0.0
building lightgbm
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: build>=0.10.0 in /usr/local/lib/python3.9/site-packages (0.10.0)
Requirement already satisfied: packaging>=19.0 in /usr/local/lib/python3.9/site-packages (from build>=0.10.0) (23.1)
Requirement already satisfied: pyproject_hooks in /usr/local/lib/python3.9/site-packages (from build>=0.10.0) (1.0.0)
Requirement already satisfied: tomli>=1.1.0 in /usr/local/lib/python3.9/site-packages (from build>=0.10.0) (2.0.1)
--- building wheel ---
* Creating venv isolated environment...
* Installing packages in isolated environment... (scikit-build-core>=0.4.4)
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x86f60fb80>: Failed to establish a new connection: [Errno 8] Name does not resolve')': /simple/scikit-build-core/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x86f60feb0>: Failed to establish a new connection: [Errno 8] Name does not resolve')': /simple/scikit-build-core/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x86f60fee0>: Failed to establish a new connection: [Errno 8] Name does not resolve')': /simple/scikit-build-core/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x8705b42e0>: Failed to establish a new connection: [Errno 8] Name does not resolve')': /simple/scikit-build-core/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x8705b4490>: Failed to establish a new connection: [Errno 8] Name does not resolve')': /simple/scikit-build-core/
ERROR: Could not find a version that satisfies the requirement scikit-build-core>=0.4.4 (from versions: none)
ERROR: No matching distribution found for scikit-build-core>=0.4.4
```

scikit-build-core-0.4.7 is already installed, which should be sufficient.

All packages are built in isolated VMs in most distros. For security reasons downloads aren't allowed.

How can we build Python bindings without internet connection?

## Environment info

LightGBM version or commit hash: 4.0.0
Python-3.9
FreeBSD 13.2

**Comment by jameslamb** [comment]
Thanks for the report! I actually just experienced the same as well two days ago, trying to build while on a plane.

I'll put up a PR momentarily to allow optionally passing through `--no-build-isolation` to `pip install` and `--no-isolation` to `build`. Sorry for the inconvenience.

To make progress without waiting for that, you could patch your copy of this project's `build-python.sh` like this:

```diff
--- a/build-python.sh
+++ b/build-python.sh
@@ -179,7 +179,7 @@ while [ $# -gt 0 ]; do
   shift
 done

-pip install --prefer-binary 'build>=0.10.0'
+# pip install --prefer-binary 'build>=0.10.0'

 # create a new directory that just contains the files needed
 # to build the Python package
@@ -344,6 +344,7 @@ if test "${BUILD_WHEEL}" = true; then
     echo "--- building wheel ---"
     rm -f ../dist/*.whl || true
     python -m build \
+        --no-isolation \
         --wheel \
         --outdir ../dist \
         ${BUILD_ARGS} \
```

And then build as mentioned in https://github.com/microsoft/LightGBM/issues/5977#issuecomment-1636115440

```shell
sh build-python.sh bdist_wheel
```

**Comment by jameslamb** [comment]
And thanks for coming to the repo to report these things, and for helping to make LightGBM usable by more people!

We did not know that there were these FreeBSD ports of `LightGBM` and the `lightgbm` Python package:

* https://cgit.freebsd.org/ports/tree/misc/lightgbm
* https://cgit.freebsd.org/ports/tree/misc/py-lightgbm

**Comment by jameslamb** [comment]
@yurivict I've put up https://github.com/microsoft/LightGBM/pull/6042 with fixes to LightGBM's build system which I hope will resolve this issue for you.

If you have time, please do look at that PR and comment if it doesn't meet what you're looking for.

**Comment by yurivict** [comment]
With this PR it still creates venv and fails because it can't download packages:
```
===>  Building for py39-lightgbm-4.0.0
building lightgbm
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: build>=0.10.0 in /usr/local/lib/python3.9/site-packages (0.10.0)
Requirement already satisfied: packaging>=19.0 in /usr/local/lib/python3.9/site-packages (from build>=0.10.0) (23.1)
Requirement already satisfied: pyproject_hooks in /usr/local/lib/python3.9/site-packages (from build>=0.10.0) (1.0.0)
Requirement already satisfied: tomli>=1.1.0 in /usr/local/lib/python3.9/site-packages (from build>=0.10.0) (2.0.1)
--- building wheel ---
* Creating venv isolated environment...
* Installing packages in isolated environment... (scikit-build-core>=0.4.4)
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x87759eb80>: Failed to establish a new connection: [Errno 8] Name does not resolve')': /simple/scikit-build-core/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x87759eeb0>: Failed to establish a new connection: [Errno 8] Name does not resolve')': /simple/scikit-build-core/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x87759eee0>: Failed to establish a new connection: [Errno 8] Name does not resolve')': /simple/scikit-build-core/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x8775c72e0>: Failed to establish a new connection: [Errno 8] Name does not resolve')': /simple/scikit-build-core/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x8775c7490>: Failed to establish a new connection: [Errno 8] Name does not resolve')': /simple/scikit-build-core/
ERROR: Could not find a version that satisfies the requirement scikit-build-core>=0.4.4 (from versions: none)
ERROR: No matching distribution found for scikit-build-core>=0.4.4
```

It should  not create any isolated environment.

Somehow virtually all other Python packages don't have such problem.

**Comment by jameslamb** [comment]
What command did you run? I did not see that running the following in an environment without internet access.

```shell
sh build-python.sh bdist_wheel --no-isolation
```

> Somehow virtually all other Python packages don't have such problem.

LightGBM is not just a Python package... it's a single source tree used to build a CLI, C++ shared library, Python package, R package, Java jar, and more... and as such, it's build system is different than pure-python projects

**Comment by yurivict** [comment]
It runs:
```
python3.9 -m build --no-isolation --wheel
```

**Comment by yurivict** [comment]
> What command did you run?

I build the FreeBSD port ```misc/py-lightgbm``` using the test framework. I run ```cd /usr/ports/misc/py-lightgbm && make```. This command succeeds with internet access and fails without it.

The way how I test it without internet access - is running in a virtual machine.

Under the hood ```make``` runs the command from my previous message, which is the standard way to build Python ports.

**Comment by jameslamb** [comment]
> Under the hood `make` runs the command from my previous message, which is the standard way to build Python ports

As of v4.0.0 of the project, LightGBM's Python package cannot just by built by `cd`-ing into a directory and running `python -m build`.

If you want to build a custom wheel from sources in this repo, invoke the shell script at the root of the repo exactly as I did at https://github.com/microsoft/LightGBM/issues/5979#issuecomment-1679251758.

> standard way to build Python ports

I'm sorry that the design decisions we've made have made it difficult for you to build FreeBSD ports. I can try to explain in greater detail why this project's build system is as it currently is.

In response to changes outside of our control in upstream tools like `build`, `pip`, and `setuptools`, the build system for this project absolutely needed to change. In response, we chose a build toolchain that we felt balances complexity and correctness best for the majority of `lightgbm`'s users... people who `pip install` or `conda install` from package repositories.

You can read about the history of those changes in the following places (and all the other places linked from them):

* https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html
* #5061 (open as a request-for-comment since March 2022)
* #5837
* https://github.com/dmlc/xgboost/pull/9021

I'm happy to help and to try to accommodate less-common use cases we hadn't considered with changes to the interface like #6042, but to be clear **we have no plans to support `cd python-package && python -m build`** in the near future. 

My top priority is ensuring that LightGBM publishes correct, highly-portable source distributions and wheels of its Python package to package repositories like PyPI and conda-forge, so that for the majority of users running `pip install lightgbm` "just works" and they can focus on the machine learning task at hand.

If you have a specific suggestion for how to do that in a way that reintroduces the ability to `cd python-package && python -m build` without introducing significant new maintenance burden, we'd be happy to hear it.
