### ISSUE TITLE
How to setup LightGBM with GPU support in a specific Conda environment for Python?

### ISSUE THREAD

**Issue by enesgencer18** [microsoft/LightGBM#5989]
## Summary

I would like to setup LightGBM with GPU support in a specific Conda environment for Python. How can I do that?

Thanks,

**Comment by jameslamb** [comment]
Thanks for using LightGBM.

As far as I know, the `lightgbm` package available via `conda-forge` doesn't have GPU support enabled. Some references:

* https://github.com/microsoft/LightGBM/issues/5419#issuecomment-1275514349
* https://github.com/conda-forge/lightgbm-feedstock/pull/40 (notice it's closed without merge)
* I don't see OpenCL used in the recipe for that package: https://github.com/search?q=repo%3Aconda-forge%2Flightgbm-feedstock+opencl&type=code

*(we don't maintain that package, though)*

You can `pip install` the project into a `conda` environment. If you're Windows or Linux, as of LightGBM 4.0 the wheels we publish already come with OpenCL-based GPU support compiled, so you don't need any additional build customization.

```shell
conda create \
    -c conda-forge \
    --name lgb-gpu \
        python=3.10 \
        numpy \
        scipy

source activate lgb-gpu

pip install lightgbm
```

On macOS, or if you're on an older Linux distribution that doesn't support at least GLIBC 2.28, you could run the following (as documented at https://github.com/microsoft/LightGBM/blob/master/python-package/README.rst#install-from-pypi).

```shell
# (optionally) get Boost if you don't have it
conda install --yes -c conda-forge boost

# compile the GPU version of LightGBM from sources on PyPI
pip install \
    --no-binary lightgbm \
    --config-settings=cmake.define.USE_GPU=ON \
    lightgbm
```

Once you've installed `lightgbm` using one of these messages, just pass `"device": "gpu"` to perform training on the GPU.

```python
import lightgbm as lgb
from sklearn.datasets import make_regression

X, y = make_regression(n_samples=10_000)
dtrain = lgb.Dataset(X, label=y, params={"device": "gpu"})
bst = lgb.train(
    train_set=dtrain,
    params={
        "device_type": "gpu",
        "objective": "rmse",
        "verbosity": 1
    }
)
```

For completeness... also note the LightGBM ships with two different build types for GPU acceleration. The one I described above is based on OpenCL... it's not limited to NVIDIA GPUs, and has been in LightGBM for several years.

There's also a newer CUDA-based build, which you can use to target NVIDIA GPUs if you have CUDA 11.0 or newer available. As of `lightgbm==4.0.0`, that requires compilation from source on all platforms.

```shell
# compile the GPU version of LightGBM from sources on PyPI
pip install \
    --no-binary lightgbm \
    --config-settings=cmake.define.USE_CUDA=ON \
    lightgbm
```

And you can then use it by passing the following in `params`.

```python
{"device_type": "cuda"}
```

**Comment by enesgencer18** [comment]
Hi @jameslamb,

I have tried the solution you have provided. I uninstalled the boost and lightgbm packages and installed them with the following code:

`# (optionally) get Boost if you don't have it
conda install --yes -c conda-forge boost

# compile the GPU version of LightGBM from sources on PyPI
pip install \
    --no-binary lightgbm \
    --config-settings=cmake.define.USE_GPU=ON \
    lightgbm`

However, I received the following error:
` [LightGBM] [Fatal] GPU Tree Learner was not enabled in this build.
Please recompile with CMake option -DUSE_GPU=1`

Then, I tried the following:
`pip install \
    --no-binary lightgbm \
    --config-settings=cmake.define.USE_GPU=1 \
    lightgbm`

However, it also did not work.

How should I proceed?

**Comment by domtisdell** [comment]
Don't know if it will help you but I was having problems building cuda version until I switched gcc (and g++ for good measure) to version 10 for compiling.

Lead came from this reference: https://github.com/NVIDIA/nccl/issues/650

**Comment by enesgencer18** [comment]
I solved the problem with the following way.

`conda create -n myenv python=3.8
conda activate myenv
conda install numpy scipy scikit-learn cmake
conda install -c conda-forge opencl-dev
git clone --recursive https://github.com/microsoft/LightGBM
cd LightGBM
mkdir build
cd build
cmake -DUSE_GPU=1 ..
make -j4
cd ../python-package
python setup.py install
python
import lightgbm as lgb
print(lgb.compat.LGBM_GPU)
conda deactivate
`

**Comment by mjkanji** [comment]
@jameslamb Would it be possible for you to either ask for ownership of the the feedstock or to submit a PR to that repo which allows for a `conda` package with GPU support? It would be really amazing if we could install the GPU variant via `conda` directly. 

Using `pip` with `conda` often causes issues, with `pip` overwriting many of the packages that were installed by `conda`.

**Comment by prasithats** [comment]
> I solved the problem with the following way.
> 
> ```
> conda create -n myenv python=3.8
> conda activate myenv
> conda install numpy scipy scikit-learn cmake
> conda install -c conda-forge opencl-dev
> git clone --recursive https://github.com/microsoft/LightGBM
> cd LightGBM
> mkdir build
> cd build
> cmake -DUSE_GPU=1 ..
> make -j4
> cd ../python-package
> python setup.py install
> python
> import lightgbm as lgb
> print(lgb.compat.LGBM_GPU)
> conda deactivate
> ```


While am trying this am getting an error like does not appear to contain CMakeLists.txt.

**Comment by prasithats** [comment]
@enesgencer18 could you please let me know whether you have created any CMakeLists.txt?

**Comment by StrikerRUS** [comment]
>  It would be really amazing if we could install the GPU variant via conda directly.

It's finally possible now! 🎉  Default version supports training with OpenCL-based acceleration `{"device_type": "gpu"}` and CUDA version supports CUDA-based acceleration `{"device_type": "cuda"}`.
Refer to #5419.
