### ISSUE TITLE
Parallel Learning: every machine will generate a model file

### ISSUE THREAD

**Issue by hlee13** [Microsoft/LightGBM#599]
Every machine will generate a model file，model files are different，which model file should be used。
## Environment info
Operating System:
CPU:
C++/Python/R version:

## Steps to reproduce

1.
2.
3.

**Comment by chivee** [comment]
do you enable the parallel training option ? and what's your option?

https://github.com/Microsoft/LightGBM/wiki/Parallel-Learning-Guide

**Comment by guolinke** [comment]
@hlee13 
The model files in different machine should be the same. you can use any of them.
