### ISSUE TITLE
How to get feature importances

### ISSUE THREAD

**Issue by yuhai-china** [Microsoft/LightGBM#60]
Hey,

LightGBM is greate, I try to use it for several datasets, but I cannot get feature importance after training.
How can I enable to output  feature importance after training?

Thanks

**Comment by guolinke** [comment]
feature importance will write to model file automatically. you can check the model file.

**Comment by yuhai-china** [comment]
[LightGBM_model.txt](https://github.com/Microsoft/LightGBM/files/563780/LightGBM_model.txt)

[train.conf.txt](https://github.com/Microsoft/LightGBM/files/563781/train.conf.txt)

However, I cannot find feature importance from the model file as attached, anything wrong?

Thanks

**Comment by chenghuige** [comment]
@yuhai-china you can find from LightGBM_model.txt last line

**Comment by yuhai-china** [comment]
@chenghuige I cannot find feature importance from the model file as attached, anything wrong about config file?

Thanks

**Comment by guolinke** [comment]
@yuhai-china are you run this with the latest code?

**Comment by yuhai-china** [comment]
the code was downloaded about one week ago.

**Comment by yuhai-china** [comment]
I update to the latest code and finally get the feature importance, thanks
