### ISSUE TITLE
[python-package] `verbose` does not supress warnings with custom objectives

### ISSUE THREAD

**Issue by lbittarello** [microsoft/LightGBM#6014]
## Description

In the Python package of LightGBM 4.0.0, setting the `verbose` parameter to `-1` does not suppress warnings if the objective is a user-defined function.

## Reproducible example

```python
import numpy as np
import pandas as pd

from lightgbm import LGBMRegressor

df = pd.DataFrame({"x": [0, 0, 1, 1, 1], "y": [0, 1, 0, 1, 1]})


def l2_obj(y_true, y_pred):
    grad = y_pred - y_true
    hess = np.ones_like(y_pred)
    return grad, hess


estimator = LGBMRegressor(
    objective=l2_obj, min_child_samples=1, n_estimators=1, n_jobs=1, verbose=-1
)

estimator.fit(df[["x"]], df["y"])
```

## Environment info

LightGBM version or commit hash: 4.0.0

Command(s) you used to install LightGBM

```shell
conda install -y lightgbm
```

**Comment by celestinoxp** [comment]
is this related to https://github.com/pycaret/pycaret/issues/3660 ? I installed lightgbm via pip...

**Comment by Tialo** [comment]
Also encounter it when using `lightgbm.cv`. But works fine with `lightgbm.train`

**Comment by Tialo** [comment]
GidonKR, thanks for temporary solution!

**Comment by jefferythewind** [comment]
From @GidonKR here is some code that worked for me in Python 3.12

```
import logging


class CustomLogger:
    def init(self):
        self.logger = logging.getLogger('lightgbm_custom')
        self.logger.setLevel(logging.ERROR)

    def info(self, message):
        self.logger.info(message)

    def warning(self, message):
        # Suppress warnings by not doing anything
        pass

    def error(self, message):
        self.logger.error(message)
l = CustomLogger()
l.init()
lgb.register_logger(l)
```

**Comment by jameslamb** [comment]
Thanks for using LightGBM and for putting the effort into a minimal, reproducible example!

I'm able to reproduce this with the latest `lightgbm` built from source here (https://github.com/microsoft/LightGBM/commit/14435485bd7e9c4d72ab43bd269c33fc4230212f).

```python
import numpy as np
import pandas as pd

from lightgbm import LGBMRegressor

df = pd.DataFrame({"x": [0, 0, 1, 1, 1], "y": [0, 1, 0, 1, 1]})


def l2_obj(y_true, y_pred):
    grad = y_pred - y_true
    hess = np.ones_like(y_pred)
    return grad, hess


params = {
    "min_child_samples": 1,
    "n_estimators": 1,
    "n_jobs": 1,
    "verbose": -1
}

LGBMRegressor(
    **{**params, "objective": l2_obj}
).fit(df[["x"]], df["y"])

# [LightGBM] [Info] Using self-defined objective function
# [LightGBM] [Warning] No further splits with positive gain, best gain: -inf

LGBMRegressor(
    **{**params, "objective": "regression"}
).fit(df[["x"]], df["y"])

# (no logs)
```

The uses of `lightgbm.register_logger()` mentioned by others in this thread is a totally valid way to address this, but this is definitely a bug. I'll investigate and hopefully put up a fix shortly.

**Comment by jameslamb** [comment]
And very sorry for the delayed response. This project has a very small number of maintainers relative to its popularity, and 0 who work on LightGBM maintenance full-time.

If any of you involved in this thread have feedback on what we could do to make it more likely that you'll investigate such issues and contribute fixes yourself in the future, we'd love to hear them here or over in #6350.

**Comment by jameslamb** [comment]
Looks like this behavior is not specific to the `scikit-learn` interface, and happens with `lgb.train()` too.

```python
import numpy as np
import pandas as pd

import lightgbm as lgb

df = pd.DataFrame({"x": [0, 0, 1, 1, 1], "y": [0, 1, 0, 1, 1]})

def l2_obj(y_pred, train_data):
    y_true = train_data.get_label()
    grad = y_pred - y_true
    hess = np.ones_like(y_pred)
    return grad, hess

params = {
    "min_child_samples": 1,
    "n_estimators": 1,
    "n_jobs": 1,
    "verbosity": -1
}

lgb.train(
    params={
        **params,
        "objective": l2_obj
    },
    train_set=lgb.Dataset(df[["x"]], label=df[["y"]])
)

lgb.train(
    params={
        **params,
        "objective": "regression"
    },
    train_set=lgb.Dataset(df[["x"]], label=df[["y"]])
)
```

**Comment by jameslamb** [comment]
I believe I've found the root cause.

This call in `Booster.update()` (the function that runs 1 boosting round)

https://github.com/microsoft/LightGBM/blob/14435485bd7e9c4d72ab43bd269c33fc4230212f/python-package/lightgbm/basic.py#L4132-L4133

Calls `LGBM_BoosterResetParameter()` in the C API.

https://github.com/microsoft/LightGBM/blob/14435485bd7e9c4d72ab43bd269c33fc4230212f/src/c_api.cpp#L2035-L2040

Which eventually calls `Config::SetVerbosity()` on the C++ side... which reset the verbosity level back to `INFO` if `"verbose"` or `"verbosity"` aren't found in the parameters passed to it.

https://github.com/microsoft/LightGBM/blob/14435485bd7e9c4d72ab43bd269c33fc4230212f/src/io/config.cpp#L42-L55

**Comment by celestinoxp** [comment]
@jameslamb Did you forget to merge with release 4.4.0?

**Comment by jameslamb** [comment]
Nope, #6428 wasn't ready in time for the 4.4.0 release. We will try to get it into the next one.
