### ISSUE TITLE
parallel training, every machine has a different LightGBM_model.txt

### ISSUE THREAD

**Issue by hlee13** [Microsoft/LightGBM#602]
As title described, which I should use

## config item

#machine0 
is_pre_partition = true
tree_learner = data
data = data.train.partition.0

output LightGBM_model.txt: f6c9af2b4026558d0931c95faba70a6e  data_model.txt

#machine1
is_pre_partition = true
tree_learner = data
data = data.train.partition.1
output LightGBM_model.txt: c2591e79db202b639b89e7ddfafd5fb2  data_model.txt

# two model file only diff on Tree=0, other Trees are same:

#machine0
Tree=0
num_leaves=2
split_feature=0
split_gain=-1
threshold=0
decision_type=0
default_value=0
left_child=-1
right_child=-2
leaf_parent=0 0
leaf_value=52.586637443099526 52.586637443099526
leaf_count=0 38749049
internal_value=0
internal_count=38749049
shrinkage=1
has_categorical=0

#machine1
Tree=0
num_leaves=2
split_feature=0
split_gain=-1
threshold=0
decision_type=0
default_value=0
left_child=-1
right_child=-2
leaf_parent=0 0
leaf_value=52.142971758326794 52.142971758326794
leaf_count=0 41732951
internal_value=0
internal_count=41732951
shrinkage=1
has_categorical=0

**Comment by guolinke** [comment]
temporary solution: set ```boost_from_average=false``` .
I will fix it soon.

**Comment by hlee13** [comment]
@guolinke , can directly give me a patch now .

**Comment by hlee13** [comment]
temporary solution: set boost_from_average=false .
=======
@guolinke  Is this a trick?

**Comment by guolinke** [comment]
@hlee13 it is a parameter.

**Comment by hlee13** [comment]
got it
