### ISSUE TITLE
Can not install LightGBM on macOS

### ISSUE THREAD

**Issue by dyllanwli** [Microsoft/LightGBM#603]
I have tried 
Official Installation Guide by Microsoft
anaconda installation: conda install -c derickl lightgbm=20170422
and this website: https://aichamp.wordpress.com/2017/02/07/my-experiment-using-lightgbm-microsoft-from-scratch-at-osx/ 
Even though each output is the same as the website guide
But I still can not install LightGBM

Here is my environment info:
macOS 10.12.5
cmake version 3.8.2
Apple LLVM version 8.1.0 (clang-802.0.38)
Target: x86_64-apple-darwin16.6.0
Thread model: posix

**Comment by dyllanwli** [comment]
Python version: 3.6

**Comment by guolinke** [comment]
any logs ?

**Comment by dyllanwli** [comment]
logs is the same as the blog( https://aichamp.wordpress.com/2017/02/07/my-experiment-using-lightgbm-microsoft-from-scratch-at-osx/)

**Comment by guolinke** [comment]
So, how did you know it install fail ? It doesn't have any errors from the logs in that website.

**Comment by guolinke** [comment]
@dyllanwli BTW, the guide of that website seems is not correct. 
It miss the installation of python package : https://github.com/Microsoft/LightGBM/tree/master/python-package#installation

**Comment by dyllanwli** [comment]
Thank you, I fix it.
