### ISSUE TITLE
Support C++20

### ISSUE THREAD

**Issue by jameslamb** [microsoft/LightGBM#6033]
## Summary

As reported in https://github.com/microsoft/LightGBM/pull/4803#issuecomment-1675428818, and as I've observed working on #5981, LightGBM does not currently support C++20.

Attempting to compile fails with errors like the following.

> [ 27%] Building CXX object source_subfolder/CMakeFiles/lightgbm.dir/src/io/config_auto.cpp.o
In file included from /home/algo/.conan/data/lightgbm/3.3.5///build/3402b31e727359cf1945dc386665e8a8c324a0f7/source_subfolder/src/io/bin.cpp:16:
/home/algo/.conan/data/lightgbm/3.3.5///build/3402b31e727359cf1945dc386665e8a8c324a0f7/source_subfolder/src/io/dense_bin.hpp:473:28: error: expected unqualified-id before ‘const’
473 | DenseBin<VAL_T, IS_4BIT>(const DenseBin<VAL_T, IS_4BIT>& other)

LightGBM should support C++20.

## Motivation

Supporting a wider range of C++ standards reduces the risk of failures when updating vendored-in dependencies like `fmt` and `fast_double_parser`.

## Description

See #5981 (will add more details later).

## References

#5150 
#5500

**Comment by kdarby-cqg** [comment]
Thanks @jameslamb  as a workaround I was able to:

> conan profile update settings.compiler.cppstd=${CPP_VERSION} ${PROFILE}
conan profile update settings.lightgbm:compiler.cppstd=11 ${PROFILE}


I'm sure the wider world would appreciate a lightgbm v4 conan package too, thanks!

**Comment by jameslamb** [comment]
> the wider world would appreciate a lightgbm v4 conan package too

Whatever `lightgbm` conan package you're referring to isn't maintained in this project. See the discussion in https://github.com/microsoft/LightGBM/issues/5770#issuecomment-1571315931.

**Comment by StrikerRUS** [comment]
Closed in favor of being in https://github.com/microsoft/LightGBM/issues/2302. We decided to keep all feature requests in one place.

Welcome to contribute this feature! Please re-open this issue (or post a comment if you are not a topic starter) if you are actively working on implementing this feature.
