### ISSUE TITLE
LightGBM import error related to dll

### ISSUE THREAD

**Issue by frostmanfrost** [Microsoft/LightGBM#604]
Please search your question on previous issues, stackoverflow or other search engines before you open a new one.

**_Seems to be a similar issue to "LightGBM import error #499" and "[GPU] LightGBM import error again! nvidia OpenCL.dll not found #566." However, re-installing nvidia driver or re-cloning the latest build does not solve the problem._**

For bugs and unexpected issues, please provide following information, so that we could reproduce on our system.

## Environment info
Operating System: Windows 7
CPU: Intel i5-3750k
GPU: GeForce GTX 1070
C++/Python/R version:  Anaconda 4.3.21, Python 3.6.1

## Error Message:

**_Please note that "print(lib_path)" is added at line 26 per #499 and #566._**

['D:\\Anaconda3\\lib\\site-packages\\lightgbm-0.2-py3.6.egg\\lightgbm\\lib_lightgbm.dll']
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-6-1cc4a28fa485> in <module>()
     43 plt.style.use('seaborn-whitegrid')
     44 
---> 45 import lightgbm as lgb

D:\Anaconda3\lib\site-packages\lightgbm-0.2-py3.6.egg\lightgbm\__init__.py in <module>()
      7 from __future__ import absolute_import
      8 
----> 9 from .basic import Booster, Dataset
     10 from .callback import (early_stopping, print_evaluation, record_evaluation,
     11                        reset_parameter)

D:\Anaconda3\lib\site-packages\lightgbm-0.2-py3.6.egg\lightgbm\basic.py in <module>()
     30 
     31 
---> 32 _LIB = _load_lib()
     33 
     34 

D:\Anaconda3\lib\site-packages\lightgbm-0.2-py3.6.egg\lightgbm\basic.py in _load_lib()
     25         return None
     26     print(lib_path)
---> 27     lib = ctypes.cdll.LoadLibrary(lib_path[0])
     28     lib.LGBM_GetLastError.restype = ctypes.c_char_p
     29     return lib

D:\Anaconda3\lib\ctypes\__init__.py in LoadLibrary(self, name)
    424 
    425     def LoadLibrary(self, name):
--> 426         return self._dlltype(name)
    427 
    428 cdll = LibraryLoader(CDLL)

D:\Anaconda3\lib\ctypes\__init__.py in __init__(self, name, mode, handle, use_errno, use_last_error)
    346 
    347         if handle is None:
--> 348             self._handle = _dlopen(self._name, mode)
    349         else:
    350             self._handle = handle

OSError: [WinError 127] The specified procedure could not be found

## Steps to reproduce

1.
2.
3.

**Comment by frostmanfrost** [comment]
Also, I can run the testing in CLI without any issues.

/github_repos/LightGBM/examples/binary_classification
"../../lightgbm.exe" config=train.conf data=binary.train valid=binary.test objective=binary device=gpu

**Comment by guolinke** [comment]
@frostmanfrost 
if you can run it by cli, the possible reason is your python version is 32-bit. 

Can you try to build without GPU, and try the install python-package ? The problem is in gpu side if this can work.

**Comment by frostmanfrost** [comment]
Thank you, guolinke.  Finally figured out the problem:  the dll chain broke at libstdc++-6.dll, which is in .../mingw64/bin.  Though the location was added to PATH, basic.py still could not load it.  Copying the dll to c:/windows/system32 solved the problem.
