### ISSUE TITLE
Where are the LightGBM dependencies defined?

### ISSUE THREAD

**Issue by falcon8241** [microsoft/LightGBM#6068]
Pardon me if this is a stupid question:
I am wondering where can I find the dependency requirements for LightGBM Python package, especially for a specific version. E.g. I found a pyproject.toml (https://github.com/microsoft/LightGBM/blob/master/python-package/pyproject.toml) under the `master` branch. But such file does not exist for a specific version (e.g. if I switch to Tag v3.3.3, this file does not exist). 

How do I know the dependency requirement for a specific version?

**Comment by jameslamb** [comment]
Thanks for using LightGBM!

Not a stupid question.

As you noted, `lightgbm` (the Python package for LightGBM) now uses `pyproject.toml`-based builds (#5759). The first release containing that change was `v4.0.0`.

For the latest unreleased version of `lightgbm` here on GitHub, look in https://github.com/microsoft/LightGBM/blob/master/python-package/pyproject.toml.

For prior releases, look in `setup.py`, e.g. https://github.com/microsoft/LightGBM/blob/v3.3.5/python-package/setup.py#L338-L351

For **any Python package**, if you're ok with installing it then use `pip show` to see the dependencies.

```shell
pip install 'lightgbm==3.3.5'
pip show lightgbm
```

shows the following

```text
Name: lightgbm
Version: 3.3.5
Summary: LightGBM Python Package
Home-page: https://github.com/microsoft/LightGBM
Author:
Author-email:
License: The MIT License (Microsoft)
Requires: numpy, scikit-learn, scipy, wheel
Required-by:
```

**Comment by falcon8241** [comment]
Thank you. That helps a lot.
