### ISSUE TITLE
why run so slowly after update to lightgbm4.0.0.0

### ISSUE THREAD

**Issue by DengxiaoHong999** [microsoft/LightGBM#6070]
## Environment info

LightGBM version or commit hash:

Command(s) you used to install LightGBM

```shell

```

**Comment by jameslamb** [comment]
Thanks for using LightGBM.

You might find these suggestions helpful: https://github.com/microsoft/LightGBM/issues/5348#issuecomment-1175728860

But "why is my code slow" is not enough information for us to help you. If you can provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) showing how you're using LightGBM, how you're measuring timings, and what specifically you mean by "so slowly", we'd be happy to help.

But without that effort from you, we won't spend time investigating this report.

**Comment by DengxiaoHong999** [comment]
thanks, my code used lightgbm,and now i update the lgbm's version, lgbm.cv removed some para,and the doc not info about these para,.when i use the new lgbm,run my model with same data and para,i feel so slowly.

**Comment by jameslamb** [comment]
That is not even close to enough information for us to help you, sorry. Please review the information at the comment I linked above.
