### ISSUE TITLE
Parallel Training, continuous variable feature infos are all 0

### ISSUE THREAD

**Issue by hlee13** [Microsoft/LightGBM#609]
## Example model file segment sample below:
While values on Tree=0 are not all 0.

feature_infos=none 0:1 [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] [0:0] 55:130:30 4:3:5:2 2:1 2:1 1:0 none 5:6:7:4:8 2:1:3 55:130:30 4:3:5:2 2:1 2:1 1:0 none 5:6:7:4:8 2:1:3

Tree=0
num_leaves=31
split_feature=351 24 349 29 29 349 20 31 349 41 13 25 29 9 37 8 41 13 9 13 20 9 37 29 333 37 351 20 25 25
split_gain=570651983537.81616 116316298995.62183 105665634896.86536 38593707335.593109 33956802893.2677 24761134486.14325 19793202306.595535 18069020455.339722 13591126658.400818 13317402975.652649 13030202107.030685 12512410145.188721 8823240493.4719543 7597873072.3323364 4838994248.756897 4304904505.9786835 4151789216.4196472 3829369080.4668884 3589419114.0963898 3552798581.8453979 3476242403.6172104 3444315792.5570831 3255466718.9993591 3211688127.3360825 3165898106.3824158 3050029368.4733734 2976457809.8967896 2711398187.2144871 2666079347.4325752 2310261593.7174416
threshold=207.5 80.5 222.5 78.5 103.5 346.5 41.5 125.5 158.5 155 3.5 125.5 218.5 1.5 326.5 0.5 187.5 15.5 12.5 2.5 90.5 4.5 184.5 176.5 106.5 189.5 446.5 0.5 128.5 37.5
decision_type=0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
left_child=1 3 4 6 21 9 15 11 17 12 23 19 -4 20 16 27 -10 -6 29 -3 -8 -2 -9 -5 -7 -19 -11 -1 -23 -17
right_child=2 7 5 10 8 24 13 22 14 26 -12 -13 -14 -15 -16 18 -18 25 -20 -21 -22 28 -24 -25 -26 -27 -28 -29 -30 -31
leaf_parent=27 21 19 12 23 17 24 20 22 16 26 10 11 12 13 14 29 16 25 18 19 20 28 22 23 24 25 26 27 28 29
leaf_value=9.6284137082311538 17.434682053450029 8.6060241383078786 15.390017443216701 13.411355882073401 21.340028364815581 42.487627004240473 6.2224350010462253 11.399546175309567 21.127267050743939 33.903717191297488 6.4705107330513911 10.71248441152713 32.848279222720087 3.7368536567602373 32.695875586536054 1.0840910267027852 27.78778364845676 12.863608831257929 2.7157977484568825 5.8548548854345794 12.056858517328179 6.7666538922449408 15.824841524400009 21.669054163517433 57.670783675598557

**Comment by guolinke** [comment]
@hlee13 
It doesn't have any effect on model. I will fix it when have time.

**Comment by hlee13** [comment]
@guolinke  yes, it is. just report. thanks
