### ISSUE TITLE
[R-package] Docs: add warning for MSVCP140.dll missing

### ISSUE THREAD

**Issue by Laurae2** [Microsoft/LightGBM#610]
To add to docs: warning for MSVCP140.dll missing when using precompiled DLL on a machine without Microsoft C++ Build Tools.

![image](https://user-images.githubusercontent.com/9083669/27005169-2a98af24-4e19-11e7-9c71-049f4e91ead7.png)

**Comment by guolinke** [comment]
@Laurae2 
You also can add the solution. install the vc runtime(https://my.visualstudio.com/Downloads?pid=2082).

**Comment by Laurae2** [comment]
@guolinke I get blank page:

![image](https://user-images.githubusercontent.com/9083669/27009488-47778a62-4e90-11e7-9349-72247ba7ffbb.png)

Installing with this makes it work: https://www.visualstudio.com/downloads/#build-tools-for-visual-studio-2017

**Comment by guolinke** [comment]
@Laurae2 
try this one : https://www.microsoft.com/en-us/download/details.aspx?id=52685 

The build tools is too heavy when comparing with vc runtime.

**Comment by Laurae2** [comment]
@guolinke Added to docs with #614.
