### ISSUE TITLE
[gpu] install lightgpu without root permission

### ISSUE THREAD

**Issue by hfl112** [microsoft/LightGBM#6103]
Hi lightgbm team,
I've been looking into the details of installing gpu version: https://lightgbm.readthedocs.io/en/latest/GPU-Tutorial.html#gpu-setup
it looks like it needs the sudo permission. is there any solutions for that, can I install it locally?

System: linux centos 7
GPU: V100 /T5 on HPC

Thanks!
![image](https://github.com/microsoft/LightGBM/assets/33510929/816ad114-bc82-4b12-b043-f88db6ecdc3f)

**Comment by jameslamb** [comment]
Thanks for using LightGBM.

What component of LightGBM are you trying to install? e.g. the Python package, R package, CLI?

If you are following the instructions at that doc, have you tried simply removing `sudo` from the commands running them?

**Comment by hfl112** [comment]
> Thanks for using LightGBM.
> 
> What component of LightGBM are you trying to install? e.g. the Python package, R package, CLI?
> 
> If you are following the instructions at that doc, have you tried simply removing `sudo` from the commands running them?

Hi I am trying to install Python package.
I didn't have apt-get in my system. So I was wondering is there any other way to install it?

Thanks

**Comment by wangzheyuan** [comment]
Are you trying to install python-pip?

**Comment by hfl112** [comment]
> python-pip

Yes, I do have pip and can install the cpu version of lightGBM

**Comment by atwahsz** [comment]
Did you find solution?

**Comment by StrikerRUS** [comment]
> Yes, I do have pip and can install the cpu version of lightGBM

Starting from the 3.2.0 version, LightGBM Python packages have been having built-in support of training on GPU devices.
