### ISSUE TITLE
[R-package] Windows R package installation

### ISSUE THREAD

**Issue by ChingChuan-Chen** [Microsoft/LightGBM#611]
## Environment info
Operating System: windows 10 x64
CPU: i7-3770K
C++/Python/R version:  Microsoft R Open 3.4.0

## Error Message:

Error in eval(ei, envir) : Cannot find lib_lightgbm.dll
* removing 'C:/R/MRO-3.4.0/library/lightgbm'
* restoring previous 'C:/R/MRO-3.4.0/library/lightgbm'

## Steps to reproduce

1. `R CMD INSTALL --build .`  with `use_precompile = FALSE`, `use_gpu = FALSE` and `use_mingw = FALSE`

There is a missing `/` in the [install.libs.R#L49](https://github.com/Microsoft/LightGBM/blob/master/R-package/src/install.libs.R#L49), and it need to be `lib_folder <- paste0(R_PACKAGE_SOURCE, "/src/Release/")`

**Comment by guolinke** [comment]
fixed in the latest PR.

**Comment by Laurae2** [comment]
Is this a bug of R which happens only in Windows 10? I think it might be worth reporting the missing slash issue in Windows 10 to the R team so it gets patched.

**Comment by guolinke** [comment]
@Laurae2 
I think the reason is different R version ( like Microsoft R Open) .

**Comment by zheguzai100** [comment]
·* installing *source* package 'lightgbm' ...·
·** libs·
·installing via 'install.libs.R' to D:/R/soft/R-3.4.1/library/lightgbm·
·Warning: 运行命令'cmake  -DCMAKE_GENERATOR_PLATFORM=x64  ..'的状态是127·
·Warning: 运行命令'cmake --build . --target _lightgbm  --config Release'的状态是127·
·Error in eval(ei, envir) : Cannot find lib_lightgbm.dll·
·* removing 'D:/R/soft/R-3.4.1/library/lightgbm'·
·Installation failed: Command failed (1)·
·Warning message:··
·GitHub repo contains submodules, may not function as expected! ·


in R, is it only one wtep to install with sentence `devtools::install_github("Microsoft/LightGBM", subdir = "R-package")`? or i need to install git and cmake first?

**Comment by guolinke** [comment]
refer to: https://github.com/Microsoft/LightGBM/tree/master/R-package#preparation

**Comment by zheguzai100** [comment]
@guolinke  after my installation of git /cmake and rtools in win10(x64), all of them are set in env--path, but when i run `devtools::install_github("Microsoft/LightGBM", subdir = "R-package")`, it always ask me to install rtools again and again... and  same issues happened as above..
when i tried `cd d:/R` `git clone --recursive https://github.com/Microsoft/LightGBM` `cd LightGBM/R-package` ' R.exe CMD INSTALL --build .'  it shows:

* installing to library 'D:/R/soft/R-3.4.1/library'
* installing *source* package 'lightgbm' ...
** libs
installing via 'install.libs.R' to D:/R/soft/R-3.4.1/library/lightgbm
-- Building for: NMake Makefiles
CMake Error at CMakeLists.txt:8 (PROJECT):
  Generator

    NMake Makefiles

  does not support platform specification, but platform

    x64

  was specified.


CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "D:/R/LightGBM/R-package/src/build/CMakeFiles/CMakeOutput.log".
Warning: 'cmake  -DCMAKE_GENERATOR_PLATFORM=x64  ..'1
系统找不到指定的文件。
CMake Error: Generator: execution of make failed. Make command was: "nmake" "/NOLOGO" "_lightgbm"
Warning: 'cmake --build . --target _lightgbm  --config Release'1
Error in eval(ei, envir) : Cannot find lib_lightgbm.dll
* removing 'D:/R/soft/R-3.4.1/library/lightgbm'

**Comment by chivee** [comment]
@zheguzai100 , please make sure that your system was x64 supported, as well as your build tools

**Comment by guolinke** [comment]
@zheguzai100 
you need the visual studio in windows. And you should run it by the windows CMD ( not mingw or others ). 
BTW, what is ```NMake ``` in your logs ?

**Comment by zheguzai100** [comment]
can't the R package run in rstudio instead of visual studio ?? and i run senetences in Windows powershell

**Comment by guolinke** [comment]
Lightgbm is written by cpp, and visual studio is used for the compiling cpp codes in windows. 
And can you make sure your R/Rtools is 64bit version?

**Comment by zz327** [comment]
I have very similar problem here. Let me list out my tool version first:
win10 (x64)
`R version 3.4.1 (2017-06-30) -- "Single Candle" Platform: x86_64-w64-mingw32/x64 (64-bit)`
Rtool: `Rtools34.exe`. (Rtools 2.12 and later include both 32 bit and 64 bit tools.)
Cmake: `cmake-3.7.2-win64-x64`
Visual Studio: `Community 2017 (2), Vewrsion 15.2`
This is my PATH: 
`"C:\\ProgramData\\Oracle\\Java\\javapath;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files (x86)\\ATI Technologies\\ATI.ACE\\Core-Static;C:\\Program Files\\Git\\cmd;C:\\Program Files\\nodejs\\;C:\\Anaconda2;C:\\Anaconda2\\Scripts;C:\\Anaconda2\\Library\\bin;C:\\Users\\zhouzilu\\AppData\\Roaming\\npm;C:\\Program Files\\R\\R-3.4.1\\bin;C:\\Rtools\\bin;C:\\Rtools\\mingw_64\\bin;C:\\mingw64;C:\\Program Files\\cmake-3.7.2-win64-x64\bin"`

When I trying to run `devtools::install_github("Microsoft/LightGBM", subdir = "R-package")`, it shows
Downloading GitHub repo Microsoft/LightGBM@master
from URL https://api.github.com/repos/Microsoft/LightGBM/zipball/master
Installing lightgbm
"C:/PROGRA~1/R/R-34~1.1/bin/x64/R" --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD INSTALL  \
  "C:/Users/zhouzilu/AppData/Local/Temp/Rtmp2xMwLa/devtools51c04da97060/Microsoft-LightGBM-bde7f7c/R-package"  \
  --library="C:/Users/zhouzilu/Documents/R/win-library/3.4" --install-tests 

* installing *source* package 'lightgbm' ...
** libs

*** arch - i386
installing via 'install.libs.R' to C:/Users/zhouzilu/Documents/R/win-library/3.4/lightgbm
-- Building for: NMake Makefiles
CMake Error at CMakeLists.txt:8 (PROJECT):
  Generator

    NMake Makefiles

  does not support platform specification, but platform

    x64

  was specified.


CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "C:/Users/zhouzilu/AppData/Local/Temp/Rtmp2xMwLa/devtools51c04da97060/Microsoft-LightGBM-bde7f7c/R-package/src/build/CMakeFiles/CMakeOutput.log".
Warning: running command 'cmake  -DCMAKE_GENERATOR_PLATFORM=x64  ..' had status 1
The system cannot find the file specified
CMake Error: Generator: execution of make failed. Make command was: "nmake" "/NOLOGO" "_lightgbm"
Warning: running command 'cmake --build . --target _lightgbm  --config Release' had status 1
Error in eval(ei, envir) : Cannot find lib_lightgbm.dll
* removing 'C:/Users/zhouzilu/Documents/R/win-library/3.4/lightgbm'
Installation failed: Command failed (1)
Warning message:
GitHub repo contains submodules, may not function as expected! 

I then try to install with 
`git clone --recursive https://github.com/Microsoft/LightGBM
cd LightGBM/R-package
R CMD INSTALL --build .`
Same error here,
* installing to library 'C:/Users/zhouzilu/Documents/R/win-library/3.4'
* installing *source* package 'lightgbm' ...
** libs

*** arch - i386
installing via 'install.libs.R' to C:/Users/zhouzilu/Documents/R/win-library/3.4/lightgbm
-- Building for: NMake Makefiles
CMake Error at CMakeLists.txt:8 (PROJECT):
  Generator

    NMake Makefiles

  does not support platform specification, but platform

    x64

  was specified.


CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "C:/Users/zhouzilu/Desktop/LightGBM/R-package/src/build/CMakeFiles/CMakeOutput.log".
Warning: running command 'cmake  -DCMAKE_GENERATOR_PLATFORM=x64  ..' had status 1
The system cannot find the file specified
CMake Error: Generator: execution of make failed. Make command was: "nmake" "/NOLOGO" "_lightgbm"
Warning: running command 'cmake --build . --target _lightgbm  --config Release' had status 1
Error in eval(ei, envir) : Cannot find lib_lightgbm.dll
* removing 'C:/Users/zhouzilu/Documents/R/win-library/3.4/lightgbm'
I have also tried different CMake Version including 3.8.2 and 3.9.0-rc5. Also tried installer and ZIP, but in vain. Somebody helps me plz.

**Comment by guolinke** [comment]
@zz327 
1. when installing Rtools, can you only install the 64-bit version? from your log, it is built by 32-bit Rtools.
![image](https://user-images.githubusercontent.com/16040950/27873930-50d2b61e-61e0-11e7-842c-409d47ac1979.png)

2. The default compiler is Visual Studio (or [MS Build](https://www.visualstudio.com/downloads/#build-tools-for-visual-studio-2017)) in Windows. You need to install one.

**Comment by zz327** [comment]
@guolinke 
Thank you for your answer. 
I uninstall my Rtools and reinstall as you stated above. Also I have installed Visual Studio 2017 Community Version 15.2. In addtion, I add MSBuild as the extension. However, it shows the same problem as above. Should I add any thing related to the Visual Studio to my PATH? I am a little confused...
ttttyyyy

**Comment by zheguzai100** [comment]
git ; cmake ; visual studio installed automatically
R 3.4.1 x64 ; rtools34 x64 ; 


this morning, i try to install lightgbm,  
1. asking me to install rtools again(but i'v installed and  set in system env --path ) 
2. ‘devtools::install_github("Microsoft/LightGBM", subdir = "R-package")’
Downloading GitHub repo Microsoft/LightGBM@master
from URL https://api.github.com/repos/Microsoft/LightGBM/zipball/master
Installing lightgbm
"D:/R/soft/R-34~1.1/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/Jose/AppData/Local/Temp/RtmpawkL4J/devtools10741faf4377/Microsoft-LightGBM-13ce3dc/R-package"  \
  --library="D:/R/soft/R-3.4.1/library" --install-tests 

* installing *source* package 'lightgbm' ...
** libs
installing via 'install.libs.R' to D:/R/soft/R-3.4.1/library/lightgbm
-- Building for: NMake Makefiles
CMake Error at CMakeLists.txt:8 (PROJECT):
  Generator

    NMake Makefiles

  does not support platform specification, but platform

    x64

  was specified.


CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "C:/Users/Jose/AppData/Local/Temp/RtmpawkL4J/devtools10741faf4377/Microsoft-LightGBM-13ce3dc/R-package/src/build/CMakeFiles/CMakeOutput.log".
Warning: 运行命令'cmake  -DCMAKE_GENERATOR_PLATFORM=x64  ..'的状态是1
绯荤粺鎵句笉鍒版寚瀹氱殑鏂囦欢銆?CMake Error: Generator: execution of make failed. Make command was: "nmake" "/NOLOGO" "_lightgbm"
Warning: 运行命令'cmake --build . --target _lightgbm  --config Release'的状态是1
Error in eval(ei, envir) : Cannot find lib_lightgbm.dll
* removing 'D:/R/soft/R-3.4.1/library/lightgbm'
Installation failed: Command failed (1)
Warning message:
GitHub repo contains submodules, may not function as expected!

**Comment by guolinke** [comment]
@zheguzai100 @zz327 
I just test the installation based on your environment, it will fail if using cmake 3.7.2 . Can you upgrade your cmake to the latest version ?

**Comment by zheguzai100** [comment]
@zz327 
@guolinke 
hi all, i tried another way and get the target
`devtools::install_github("Laurae2/lgbdl")`
`library(lgbdl)`
`lgb.dl(commit = "master",`
`       compiler = "gcc",`
`       repo = "https://github.com/Microsoft/LightGBM",`
`       cores = 4)`

but at  the beginning of lgb.dl, i saw a cmake error reported:
`CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage`
`CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!`

fortunately, it doesn't influence th eresult,  it worked when i run `library(lightgbm)`

**Comment by guolinke** [comment]
@zheguzai100 
I think your installation may actually fails, can you run some demos ?

**Comment by zheguzai100** [comment]
@guolinke 
does it mean fail or not?
`> require(lightgbm)
载入需要的程辑包：lightgbm
载入需要的程辑包：R6
> bst <- lightgbm(data = train$data,
+                 label = train$label,
+                 num_leaves = 4,
+                 learning_rate = 1,
+                 nrounds = 2,
+                 objective = "binary")
[LightGBM] [Fatal] len of label is not same with #data
[LightGBM] [Warning] Only contain one class.
[LightGBM] [Info] Number of positive: 0, number of negative: 209258376
[LightGBM] [Info] Total Bins 112
[LightGBM] [Info] Number of data: 209258376, number of used features: 63
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements.
[1]:	train's binary_logloss:9.99201e-16 
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements.
[2]:	train's binary_logloss:0 `

**Comment by zz327** [comment]
@guolinke 
Thanks for your response! I downloaded the latest release Cmake 3.8.2 and modified my PATH.
-- Building for: NMake Makefiles
CMake Error at CMakeLists.txt:8 (PROJECT):
  Generator

    NMake Makefiles

  does not support platform specification, but platform

    x64

  was specified.


CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "C:/Users/zhouzilu/AppData/Local/Temp/RtmpKimkeL/devtools76d43a9355f7/Microsoft-LightGBM-8dde231/R-package/src/build/CMakeFiles/CMakeOutput.log".
Warning: running command 'cmake  -DCMAKE_GENERATOR_PLATFORM=x64  ..' had status 1
The system cannot find the file specified
CMake Error: Generator: execution of make failed. Make command was: "nmake" "/NOLOGO" "_lightgbm"
Warning: running command 'cmake --build . --target _lightgbm  --config Release' had status 1
Error in eval(expr, envir, enclos) : Cannot find lib_lightgbm.dll
* removing 'C:/Users/zhouzilu/Documents/R/win-library/3.3/lightgbm'
Error: Command failed (1)
In addition: Warning message:
GitHub repo contains submodules, may not function as expected! 
Still same error... I have decided to use Python for now, but I will keep trying...

**Comment by guolinke** [comment]
@zheguzai100 it is success. But your data only have one class, which cannot be trained by binary classification.

**Comment by guolinke** [comment]
@zz327 
cmake will have some cache files. 
can you delete the LightGBM folder, then re-clone and try again ?

**Comment by zheguzai100** [comment]
> # We load in the agaricus dataset
> # In this example, we are aiming to predict whether a mushroom is edible
> data(agaricus.train, package = "lightgbm")
> data(agaricus.test, package = "lightgbm")
> train <- agaricus.train
> test <- agaricus.test
> 
> # The loaded data is stored in sparseMatrix, and label is a numeric vector in {0,1}
> class(train$label)
[1] "numeric"
> class(train$data)
[1] "dgCMatrix"
attr(,"package")
[1] "Matrix"
> table(train$label)

   0    1 
3373 3140 

why does it recognize only one class??

**Comment by zz327** [comment]
@guolinke 
Tried, still the same error...
Is this maybe due to win10? Can you try uninstall and then reinstall CMake to see if it works?

**Comment by guolinke** [comment]
I am using win10 as well.
restalling cmake still works.

Did you choose the visual c++ when installing visual studio 2017?

**Comment by guolinke** [comment]
can you paste the contents of running 'cmake --help' ?

Also, from your log, it seems you have many R versions(i saw 3.3, 3.4, 3.4.1) .

Can you paste the latest installation log?

**Comment by howardnewyork** [comment]
I seem to getting a similar error when installing in R:

`Build succeeded.

"C:\Users\Howard\AppData\Local\Temp\Rtmpeq7jnP\devtools3538ea06bf\Microsoft-LightGBM-43d5037\R-package\src\build\_lightgbm.vcxproj" (default target) (1) ->
"C:\Users\Howard\AppData\Local\Temp\Rtmpeq7jnP\devtools3538ea06bf\Microsoft-LightGBM-43d5037\R-package\src\build\ZERO_CHECK.vcxproj" (default target) (2) ->
(PrepareForBuild target) -> 
  C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargets\Microsoft.CppBuild.targets(395,5): warning MSB8029: The Intermediate directory or Output directory cannot reside under the Temporary directory as it could lead to issues with incremental build. [C:\Users\Howard\AppData\Local\Temp\Rtmpeq7jnP\devtools3538ea06bf\Microsoft-LightGBM-43d5037\R-package\src\build\ZERO_CHECK.vcxproj]


"C:\Users\Howard\AppData\Local\Temp\Rtmpeq7jnP\devtools3538ea06bf\Microsoft-LightGBM-43d5037\R-package\src\build\_lightgbm.vcxproj" (default target) (1) ->
  C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargets\Microsoft.CppBuild.targets(395,5): warning MSB8029: The Intermediate directory or Output directory cannot reside under the Temporary directory as it could lead to issues with incremental build. [C:\Users\Howard\AppData\Local\Temp\Rtmpeq7jnP\devtools3538ea06bf\Microsoft-LightGBM-43d5037\R-package\src\build\_lightgbm.vcxproj]

    2 Warning(s)
    0 Error(s)

Time Elapsed 00:00:41.75
Found library file: C:/Users/Howard/AppData/Local/Temp/Rtmpeq7jnP/devtools3538ea06bf/Microsoft-LightGBM-43d5037/R-package/src/Release/lib_lightgbm.dll to move to C:/Users/Howard/Documents/R/win-library/3.3/lightgbm/libs/x64** R
** data
** demo
** tests
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
*** arch - i386
Error: package or namespace load failed for 'lightgbm' in inDL(x, as.logical(local), as.logical(now), ...):
 unable to load shared object 'C:/Users/Howard/Documents/R/win-library/3.3/lightgbm/libs/i386/lib_lightgbm.dll':
  LoadLibrary failure:  %1 is not a valid Win32 application.

Error: loading failed
Execution halted
*** arch - x64
ERROR: loading failed for 'i386'
* removing 'C:/Users/Howard/Documents/R/win-library/3.3/lightgbm'
Installation failed: Command failed (1)
Warning message:
GitHub repo contains submodules, may not function as expected!`

**Comment by guolinke** [comment]
Refer to this issue: https://github.com/Microsoft/LightGBM/issues/675#issuecomment-313593182 

you only can use 64 bit R and R tools.

**Comment by ChiuYeeLau** [comment]
had the same problem. Updating cmake to the latest version solves my problem
