### ISSUE TITLE
Where is the PredictContrib() of an individual tree implemented?

### ISSUE THREAD

**Issue by wmmxk** [microsoft/LightGBM#6112]
I was trying to figure out why the sum of shap values of all features plus the mean of the model is equal to the prediction.

I found the PredictContrib() [calculate](https://github.com/microsoft/LightGBM/blob/60a4a13e72f18f55a024d6912836fb9583aed67a/src/boosting/gbdt.cpp#L624) the prediction of each feature in /src/boosting/gbdt.cpp. The function call the PredictContrib of each [individual tree of the boosting tree](https://github.com/microsoft/LightGBM/blob/60a4a13e72f18f55a024d6912836fb9583aed67a/src/boosting/gbdt.cpp#L632).

I run  _**grep -r -n 'PredictContrib' ./src**_ but only found hit in gbdt.cpp  and predictor.hpp. 

So where is the method PredictContrib of an individual tree, say the serial_tree_learner, define?

**Comment by jmoralez** [comment]
Hey @wmmxk. Do you mean this one? https://github.com/microsoft/LightGBM/blob/f175cebd2d971ca6140455035e526d67f04237eb/include/LightGBM/tree.h#L666-L675
