### ISSUE TITLE
ValueError: Found missing inputs in X_df. It should have one row per id and date for the complete forecasting horizon

### ISSUE THREAD

**Issue by KathyGCY** [microsoft/LightGBM#6122]
I kept getting this error `ValueError: Found missing inputs in X_df. It should have one row per id and date for the complete forecasting horizon`
Even though a very thorough validation shows there's absolutely no missing. 

**Background:**
Lightgbm time series forecast with external features (already forecasted).
And train model like this, when yX_train is all historical data per cohort with daily continuous date and target value, and 3 external features [feat1, feat2, feat3]

```
f_reg.fit(
    df=yX_train,
    id_col="cohort",
    time_col="date",
    target_col="target",
    static_features=[],
)
```

And predict like this, in which it has the next year's daily non-missing feature forecast of [feat1~feat3]

```
y_pred_reg = f_reg.predict(
        h=365,
        X_df=X_test,
    )
```

**Comment by jameslamb** [comment]
Thanks for using LightGBM.

LightGBM does not raise an error message like that. Based on a quick search of GitHub, I strongly suspect that the error you encountered is coming from `mlforecast`:

https://github.com/Nixtla/mlforecast/blob/f1c4d9f936a422b09043274b35dd235968461a38/mlforecast/core.py#L595-L599

Please report this there: https://github.com/Nixtla/mlforecast/issues.

When you do that, please provide enough information for maintainers to help you without guessing and unnecessary effort.:

*  a minimal, reproducible example that reproduces this error ([click here to learn what that is](https://stackoverflow.com/help/minimal-reproducible-example))
* version of LightGBM and `mlforecast` you are using
* how you installed those libraries
* any logs or error traces printed by the code you're running
* any other information which might help (Python version? `numpy` version? `pandas` version?)
