### ISSUE TITLE
[python-package] Cannot import LGBMClassifier

### ISSUE THREAD

**Issue by Nayoneeka23** [microsoft/LightGBM#6127]
```python
from lightgbm import LGBMClassifier as lgb
```

This command is not running on my macOS and giving me the error

> "Unexpected exception formatting exception. Falling back to standard exception"

Please help me regarding this.

**Comment by jameslamb** [comment]
Thanks for using LightGBM.

It appears that the error you're reporting comes from IPython: https://github.com/ipython/ipython/blob/d688ff095b8d7b20a94655b0fc3da202e25e133a/IPython/core/interactiveshell.py#L2127

I suspect that maybe your installation of `lightgbm` is broken in some other way, and that IPython is disguising that. Please open a Python session without using Jupyter / IPython by running the following from a terminal

```shell
python
```

And try importing `lightgbm` in it

```python
import lightgbm as lgb
```

Tell us what happens.

Beyond that, we need more information to try to help you with this:

1. What version of `lightgbm` are you using?
2. How did you install it?
3. What operating system are you on?
4. What version of Python?

-----

I've reformatted your post to make the difference between your own words, your code, and output printed by code clearer. If you're unsure how I did that, please review https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax.

**Comment by jameslamb** [comment]
Also note that it's more common to do the following:

```python
import lightgbm as lgb

model = lgb.LGBMClassifier(...)
```

That exact code you've provided should absolutely work, but just noting that since you might run into confusing errors aliasing `lightgbm.LGBMClassifier` to the name `lgb` and then trying to follow examples from documentation that run e.g. `lgb.early_stopping()`, `lgb.train()`, etc.
