### ISSUE TITLE
[R-package] Providing precompiled DLL (licensing?)

### ISSUE THREAD

**Issue by Laurae2** [Microsoft/LightGBM#613]
Are we allowed to host precompiled LightGBM DLLs on GitHub?

**Comment by guolinke** [comment]
@Laurae2 
I think it didn't have licensing issues. 

There are 2 problems:
1. cross platform, and cpu/gpu. This will request many dll/so .
2. needs to update all dll/so every time changing the code. This is very inconvenient.

**Comment by Laurae2** [comment]
@guolinke I think for CPU it is not too much an issue, but GPU is too difficult.

Most important I think is to have the Visual Studio compiled DLL which is not easy to setup for most users. Even if it is not the bleeding edge version, it is not too much an issue.

**Comment by guolinke** [comment]
@Laurae2 
Now the appveyor can compile dll, and push back to github release : https://github.com/Microsoft/LightGBM/releases
