### ISSUE TITLE
Dataset object has more features than the source file

### ISSUE THREAD

**Issue by jacopocecch** [microsoft/LightGBM#6149]
Hi, I have a LibSVM file with 220 features (going from 1 to 220). The source file is not sparse. Here's an example of a row:
`1 1:1.79769313486e+308 2:1008 3:2 4:288...217:1 218:0 219:0 220:0 `
However, when I create the Dataset object and use the `get_feature_name()` method it gives me 221 features, going from column_0 to column_220. 
I don't know whether this affects training, but my main problem is that when I try to use the model for prediction it gives me the following error:

> [LightGBM] [Fatal] The number of features in data (220) is not the same as it was in training data (221).

What should I do? Just add a feature with a value of 0 during inference phase?

Thanks in advance.

**Comment by shiyu1994** [comment]
@jacopocecch Thanks for using LightGBM. By default, LightGBM use a 0-based column index in LibSVM files (though this may not be the tradition of LibSVM, which should be 1-based.). So, when the training file contains 1~220 columns, LightGBM will think it has 221 columns.

The key problem is that why there's such a mismatch between the training and inference files. Could you please check if your file for inference LibSVM file also contains columns 1~220? If that is the case, there should be no mismatch. Or did you try to inference using other input format like numpy or pandas arrays with only 220 columns? In that case, there should be a mismatch.
