### ISSUE TITLE
[python-package] Interpreting the contents of dump_model for multi-label classification

### ISSUE THREAD

**Issue by Opt-Mucca** [microsoft/LightGBM#6157]
I am currently having issues determining which trees correspond to which class from the output of ```LGBMClassifier.booster_.dump_model()```. 

Take a simple scenario of ```LGBMClassifier``` has ```n_classes_=3``` and ```n_estimators_=2```. From my understanding of GBDTs and RFs in LightGBM, for each class label ```n_estimators_``` are constructed. This is supported by the output of ```raw = LGBMClassifier.booster_.dump_model()```, where ```raw["tree_info"]``` is a list containing 2*3 decision trees.

My question is: 
How do I know which set of ```n_estimators_``` decision trees correspond to a given class?

In the output of ```raw = LGBMClassifier.booster_.dump_model()``` I can find no information on which class from the set {0, 1, 2} ```raw["tree_info"][i]``` corresponds to for i in {0,...,5}. So let the classes be {0, 1, 2}. Are the 6 trees assumed to be ordered in any of the following ways?: [0, 1, 2, 0, 1, 2] or [0, 0, 1, 1, 2, 2]. If not, where would I find this information? (I have looked into the reader and believe it is doing the first option [0, 1, 2, 0, 1, 2] , but would like some confirmation. I would also assume this information should be somewhere in the output of ```dump_model```, but I cannot find anything).

**Comment by jameslamb** [comment]
Thanks for using LightGBM.

> for each class label n_estimators_ are constructed

This is correct specifically in the case of multi-class classification.

For binary classification, there will be `n_estimators_` trees (assuming no early stopping).

> are the 6 trees assumed to be ordered in any of the following ways?

Using the terminology from your example, the trees for a multiclass classification model are ordered `[0, 1, 2, 0, 1, 2, ...]`.

You could also confirm this by checking the predictions, e.g. like this example with the R package: https://github.com/microsoft/LightGBM/issues/5223#issuecomment-1188602396.

**Comment by Opt-Mucca** [comment]
Thanks for the great response! It perfectly answers the question. Additional thanks for even specifying the binary case.
