### ISSUE TITLE
bins in case of a variable with few different values

### ISSUE THREAD

**Issue by BlindApe** [Microsoft/LightGBM#616]
I know bins are computed by frequency but how this affects when a variable takes only a few values?
Supose a variable takes 1 (100 times), 2 (100 times), 3 (100 times) and 4 (900 times)
We select nbins = 4 so for a frequency of 1200 each bin should have 300 cases.

a) 1, 2 and 3 goes to bin 1 and 4 goes to bins 2, 3, and 4 (cumulative frequency criteria)
b) given the different values of the variable are 4, that is lower or equal the max number of bins so no recoding is done (few values, so safeguard exception)

Is some safeguard criteria like b) considered or always the a) rule is applied?

**Comment by guolinke** [comment]
@BlindApe 
We check the num_distinct_value first. If it is smaller than nbins, it use one distinct value for one bin.
So, when you set nbins >= 4, it is safe.
