### ISSUE TITLE
[python-package] Renaming feature_name and categorical_feature attributes and setters

### ISSUE THREAD

**Issue by Eyal8** [microsoft/LightGBM#6169]
I would like to suggest changing the attribute `feature_name` and `categorical_feature` to `feature_names` and `categorical_features` respectively, as they both represent lists, and their current naming is misleading.

Example of where to change:
https://github.com/microsoft/LightGBM/blob/fcf76bceb902a69e1af7cdeac289d31916ddc3f5/python-package/lightgbm/engine.py#L51-L52

However, the use of these attributes is apparent in many additional places.
In addition I would suggest renaming their corresponding setter methods `set_feature_name` and `set_categorical_feature` in all the places, e.g.:
https://github.com/microsoft/LightGBM/blob/fcf76bceb902a69e1af7cdeac289d31916ddc3f5/python-package/lightgbm/basic.py#L2638
https://github.com/microsoft/LightGBM/blob/fcf76bceb902a69e1af7cdeac289d31916ddc3f5/python-package/lightgbm/basic.py#L2543

**Comment by jameslamb** [comment]
Thanks for your interest in LightGBM.

I'm -1 on this suggestion. I agree that `set_categorical_features()` (plural) and similar would be clearer, but at this point the use of the singular form (`categorical_feature`, `feature_name`) is a significant part of the project's public API. I don't support breaking users' code in exchange for the slight improvement in clarity of the names.

I'll wait to close this for a few days to give @shiyu1994 @guolinke @jmoralez a chance to offer their opinions.

**Comment by jameslamb** [comment]
> I'll wait to close this for a few days

turns out that was actually 8 months 😂 

I'm going to close this. Thanks very much for taking the time to write this up @Eyal8 , we hope you'll come back to contribute again in the future.
