### ISSUE TITLE
Adding intercept to the linear models at the leafs. (Linear Tree)

### ISSUE THREAD

**Issue by eldadp100** [microsoft/LightGBM#6170]
## Summary
Hello, I am using LGBM with linear_tree=True. I noticed that the linear fit at the leafs doesn't use intercept. 

## Motivation
For certain leafs the features along the path are not enough to express the correct value for the leaf. It might cause longer convergence (more trees) due to additional errors at each tree.

## References
I didn't find any reference to confirm the effect of adding intercept to the linear models at the leafs.

**Comment by shiyu1994** [comment]
@eldadp100 Thanks for using LightGBM. I think we do have `intercept` or `const` for linear models in leaves. You may refer to the code for inference of linear trees here.

https://github.com/microsoft/LightGBM/blob/fcf76bceb902a69e1af7cdeac289d31916ddc3f5/src/treelearner/linear_tree_learner.h#L85

Before adding the feature value multiplied by coefficients, we have a constant value first added to the final prediction.

**Comment by eldadp100** [comment]
Thanks
