### ISSUE TITLE
exit without err log when training with ~20 million lines

### ISSUE THREAD

**Issue by GerryWang89** [Microsoft/LightGBM#618]
There isn't any err log when training with ~20M ob items, it just failed and then exit after finish loading parameters. 

The training file size is about 13G with about ~200 features.

## Environment info
Operating System: windows
CPU: x64
C++/Python/R version: c++ CLI version

**Comment by guolinke** [comment]
@GerryWang89 
I think the 20M * 200 data isn't the problem. 
Can you provide the details ? 
Did you run by powershell or cmd ? and use the latest code?

**Comment by GerryWang89** [comment]
@guolinke Thanks for your kindly reply.
Yes, I ran it by cmd with the latest code I cloned this morning. 
I'm training a binary classifier with command line. And I can run the binary_classification sample. I'm just trying to train it with my larger data in the same config.

I can also run it successfully when I only use the first 2k lines. But it simply quit when I use my 20M full training set without any log after
"[LightGBM] [Info] Finished loading parameters".

Two example lines of my training data:
0	59767	65252	7241	23	23	11	189	164	189	164	179	23	1	0	1737	1743	36	8	0	0	0	328	296	364	338	325	307	316	271	286	207	0	0	0	0	0	0	0	0	0	0	60	56	293	0	0	0	0	3	100	76	95	424	6	2468	38360	113030	33600	148330	0	300	500	0	0	1	8056	0	96	59	586	14	2581	2147	1	1	666	50000	3333	1111	96	585	11459	10462	36	5	3	20	170	11957	11224	52	47	2	170	363	10849	10299	69	5	23	9	40	10910	10581	62	13	4	56	2	3	44051	92957	460477	460477	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	7	17	10907	24	62	24	0	0	0	4	17	4	0	0	0	10541	10719	10541	0	0	0	20	0	68	110	0	0	2	4	0	0	1	2	0	0	40	0	9	10676	0	10438	4	10554	10541	10541	0	0	0	0	1000
1	87373	82875	7044	23	17	7	154	153	154	153	161	23	1	0	1737	1743	36	7	0	1737	1743	284	290	299	298	299	298	292	291	0	0	12	3	0	0	3	0	10	33	20	7	33	20	53	0	0	0	0	0	100	76	100	116	7	1630	38360	113030	42570	109090	0	300	300	0	0	0	6450	0	96	100	616	18	0	0	0	0	0	20000	0	0	96	585	11459	10462	36	5	3	20	170	11957	11224	52	47	2	170	363	10849	10299	69	5	23	9	40	10910	10581	62	13	4	56	2	3	44051	92957	460477	460477	0	0	0	0	0	0	0	0	0	0	48604	102369	10627	125	1	1185	10070	10627	125	1	9319	30594	10832	128	398	3676	10832	128	211098	437312	10542	111	4211	36084	10542	111	1	1	125	125	71382	61505	54222	67775	102	18	10595	122	92	129	0	0	0	21	20	21	0	0	0	10602	10699	10626	0	0	0	40	0	121	129	124	124	8	21	0	0	7	19	0	0	100	100	56	10810	2	10452	21	10578	10626	10579	0	0	0	0	1000

**Comment by GerryWang89** [comment]
@guolinke 
"20M" is 20 Million lines, not 20 MB size... Sorry for the confusion. The input file size is about 13GB.  Does LightGBM have a max size limit for training data?

**Comment by guolinke** [comment]
@GerryWang89 
I know it is 20M lines. We had tried billions of data, so it is not a problem.
But it depends on the memory size of your machine. 
Can you provide your machine info ?

**Comment by guolinke** [comment]
solved it offline. caused by incorrect bulid
