### ISSUE TITLE
Weight Parameter in Dataset method

### ISSUE THREAD

**Issue by xinming365** [microsoft/LightGBM#6183]
Hi, I'm trying to re-weight the sample by assigning the weight in the lgb.Dataset instance. However, I cannot find the model difference under different sample weights setting. It's not working even if I use the random  weight. 

Actually, the idea is from the DoubleEnsemble model described in this paper: [https://arxiv.org/pdf/2010.01265.pdf
](https://arxiv.org/pdf/2010.01265.pdf
)

What's the role of the weight during the training? Is it possible to change the weight of the sample.

Thalnkls!

**Comment by jmoralez** [comment]
Hey @xinming365, thanks for using LightGBM. Can you provide a [minimal reproducible example](https://matthewrocklin.com/minimal-bug-reports)?

**Comment by xinming365** [comment]
@jmoralez  Thanks for you reply.  Here is the minimal example:

```python
import lightgbm as lgb

# train_x, train_y are ndarray with shape of (N, features) , (N, 1)
weights = np.random.random(len(train_x)) # actually the weights will be adjusted according the learning curve 
# The weights are changing during the training, but the validation metric is always the same as before. Then I just  assgin weights into random variables. It still not work.

dtrain = lgb.Dataset(train_x, label=train_y, weight=weights)
dvalid = lgb.Dataset(val_x, label=val_y)

"""
we have implemented our own feval function to observe the return metric.
"""
callbacks = [lgb.log_evaluation(5)]
model = lgb.train(params,  dtrain, num_boost_round, valid_sets, valid_names=["valid"], feval=[custom_feval], callbacks=callbacks)

```

Sorry for providing such little example. Maybe, You can do experiments on some public dataset to find the reason.
