### ISSUE TITLE
[python-package] ImportError: cannot import name 'log_evaluation' from 'lightgbm'

### ISSUE THREAD

**Issue by Massawe14** [microsoft/LightGBM#6187]
## Description

> ImportError: cannot import name 'log_evaluation' from 'lightgbm' (C:\Users\MASSAWE\Anaconda3\lib\site-packages\lightgbm\__init__.py) 

## Reproducible example

```python
from lightgbm import early_stopping, log_evaluation 
```

## Environment info
LightGBM version = 4.1.0:

Command(s) you used to install LightGBM

```shell
pip install lightgbm
```

**Comment by jameslamb** [comment]
Thanks for using LightGBM.

I was not able to reproduce this.

```shell
docker run --rm -it python:3.11 /bin/bash
pip install 'lightgbm==4.1.0'
python -c "from lightgbm import log_evaluation"
echo $?
# 0
```

I suspect that one of the following is happening:

* you are using a local file called `lightgbm.py` and that's conflicting with the installed LightGBM library
    - _solution: rename such files to anything other than `lightgbm.py`_
* somewhere in your code, you've imported something else as the name `lightgbm`, like `import sklearn as lightgbm`
    - _solution: do not do that_
* mixing `pip` with `conda` has resulted in some unexpected behavior
    - *I noticed that you said you ran `pip install`, but that Python is looking in an `Anaconda3/` directory*
    - _solution:_:
    - ```shell
        pip uninstall --yes lightgbm
        conda uninstall --yes lightgbm
        conda install -c conda-forge lightgbm
        ```
* something else
    - _solution: provide us with more information, like the output of `pip freeze` and `conda env export`_

---

I've reformatted your post to make the difference between your own statements, code, and output from code clearer. If you're unsure how I did that, please review https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax

**Comment by Massawe14** [comment]
Thanks for your explanation.

**Comment by Massawe14** [comment]
Glad to hear it!

**Comment by Massawe14** [comment]
Thanks a lot.
