### ISSUE TITLE
How to make lightgbm into a static or dynamic library used on Android and IOS apps.

### ISSUE THREAD

**Issue by guxiaobo** [microsoft/LightGBM#6200]
## Summary

We want to use Lightgbm on mobile apps to train local models using local private data which can't be moved outside the phones.

## Description

We  store the data in a local SQLite database, and want to train a prediction model using LightGBM to give suggestions to phone users.

**Comment by guxiaobo** [comment]
For Android we can use the NDK toolchains to build LightGBM, but the question is whether LightGBM is designed to be run on mobile platforms, do the external libraries LightGBM depends on can be built  for mobile platforms too?

**Comment by jameslamb** [comment]
> whether LightGBM is designed to be run on mobile platforms

Not explicitly, and we don't have any tests running on mobile platforms.

> the external libraries LightGBM depends on can be built for mobile platforms too

I'm unsure.

To start, I recommend trying to compile LightGBM as a static library and without linking to OpenMP, like this:

```shell
cmake \
    -B ./build \
    -S . \
    -DUSE_OPENMP=OFF \
    -DBUILD_STATIC_LIB=ON \
    -DBUILD_CLI=OFF \
    -G 'Unix Makefiles'

make -j4 -C ./build _lightgbm
```

That assumes that "train local models" means that you want to run your own application code that loads `lib_lightgbm.so` and calls functions from its C API. 

I'm not very knowledgeable about mobile development (not sure if others are here), but I'm happy to answer questions here as you have them.
