### ISSUE TITLE
[R package] Error with deprecated 'reshape' argument usage in version 4.2.0 (which is not used)

### ISSUE THREAD

**Issue by jhk0530** [microsoft/LightGBM#6235]
Hi, thanks for nice work.

few days ago (at 12.8) I updated `lightgbm`'s version to **4.2.0** from **3.3.5** and it generates unexpected error.

## Description

<img src='https://github.com/microsoft/LightGBM/assets/6457691/59b8d6a9-2ab5-4b8c-a1e0-571ab936be77' width ='500px'> 

However, as my code doesn't use any `reshape`, but it broke (I think one of default parameter use it) 

Can you give any comment?

## Reproducible example
It generates problem in custom R package, I couldn't generate reprex yet. 

But I'll try to organize as soon as possible.

## Environment info

- `lightgbm` version **4.2.0**

that is version **3.3.5** does work well. 

## Additional Comments

I think this issue is similar. 

https://github.com/microsoft/LightGBM/issues/5115

Thanks !

Kim.

**Comment by jameslamb** [comment]
Thanks for using LightGBM.

Yes, `reshape` was removed in #4971.

I see from that screenshot that you're using `{treesnip}`. As noted in that project's docs ([link](https://github.com/curso-r/treesnip/blob/b9265ae514b182e0fca90a384db438a2b0642591/README.md#L23-L25)), `{treesnip}` has been abandoned. Please try switching to `{bonsai}` (https://github.com/tidymodels/bonsai) if you want a `{tidymodels}`-style interface to LightGBM. `{bonsai}` is actively developed and keeps up with the latest changes in LightGBM.

**Comment by jhk0530** [comment]
Oh, thanks. I'll check.

**Comment by PhilippPro** [comment]
I have similar problem after updating to 4.3.0:
![image](https://github.com/microsoft/LightGBM/assets/11573242/59284285-afac-4941-a181-9b26fb61cc0c)
Can you help?
Maybe the model was trained on a different ligthGBM version, but ideally that should not lead to a problem.

**Comment by jameslamb** [comment]
Please open a new issue with a reproducible example.

**Comment by PhilippPro** [comment]
After updating the old model with the new lightgbm it works. Ideally old models should not be broken by new versions of the package. ;)
