### ISSUE TITLE
[Windows, Cpp] LNK2001 - unresolved external symbol OMP_NUM_THREADS

### ISSUE THREAD

**Issue by wil70** [microsoft/LightGBM#6238]
## Description
Linker issues after compilation
"LNK2001 - unresolved external symbol OMP_NUM_THREADS"

![image](https://github.com/microsoft/LightGBM/assets/7807709/97cf4748-aee6-4cc2-943d-70675adee996)

## Reproducible example
Download the latest code as of Dec 15. Compile for windows in x64 bits.
You will see many linker issue in the error dialog
"LNK2001 - unresolved external symbol OMP_NUM_THREADS"

## Environment info
Windows 10 PRO

LightGBM version or commit hash:
Latest as of dec 15

Command(s) you used to install LightGBM

```git pull
start vs 
set project to release in x64 bits
clean
compile

```

## Additional Comments
I tried to compile on 2 machines, same result.
The windows GPU version via cmake compile well.

**Comment by jameslamb** [comment]
Thanks for the report and sorry about that!

I suspect it's because in #6226, I forgot to add this new file `src/utils/openmp_wrapper.cpp` to the Visual Studio solution files in https://github.com/microsoft/LightGBM/tree/master/windows.

Would you be willing to try adding it there and putting up a pull request?

**Comment by jameslamb** [comment]
@wil70 I suspect you meant to post https://github.com/microsoft/LightGBM/issues/6190#issuecomment-1858310857 over here.

Copying it here:

> That worked with the additional file - TY!

> I tried to push the code but got an error

> I attached the 2 modified project files in a zip
[LightGBM.vcxproj.zip](https://github.com/microsoft/LightGBM/files/13688612/LightGBM.vcxproj.zip)

> ```shell
> git.exe push --progress "origin" master:master
> ```
>
> ```text
> remote: Permission to microsoft/LightGBM.git denied to wil70.
> fatal: unable to access 'https://github.com/microsoft/LightGBM/': The requested URL returned error: 403
> git did not exit cleanly (exit code 128) (12032 ms @ 2023-12-15 10:14:51 AM)
> ```

1. you cannot push directly to this repository
2. when you propose changes, do it from a new branch not one called `master`

If you're unfamiliar with creating pull requests on GitHub, see https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork.

The process is as follows:

1. fork this repository by clicking the "fork" button at https://github.com/microsoft/LightGBM
2. clone your fork to your local environment

```shell
# clone
git clone --recursive git@github.com:wil70/LightGBM.git

# (optional) add another remote pointing to the main LightGBM project
git remote add upstream git@github.com:microsoft/LightGBM.git
```

3. create a new branch

```shell
git checkout -b fix/vs-solution
```

4. make changes on that branch and then commit and push them

```shell
cd ./LightGBM
git add ./windows
git commit -m "[c++] add openmp_wrapper to Visual Studio solution files"
git push origin fix/vs-solution
```

5. in the GitHub UI, go to https://github.com/microsoft/LightGBM/pulls and click "open pull request"

`@` if you need any help! We appreciate you taking the time to contribute to LightGBM.

**Comment by jameslamb** [comment]
@wil70 are you still interested in submitting a pull request for this?

If not or if you don't have time right now, let me know and I'll put up a fix.

**Comment by wil70** [comment]
Hi @jameslamb , sorry, for the delay, if you can do it that would be great! (otherwise I shall e back home on 3rd and will be able to do it, but please feel free to push the fix before - TY)

**Comment by jameslamb** [comment]
Ok no problem! I'll do it shortly. Thanks again for bringing it to our attention.
