### ISSUE TITLE
[C++] Prediction fails when data includes 'object' feature

### ISSUE THREAD

**Issue by leedchou** [microsoft/LightGBM#6239]
Hi all,

I trained a multi-class classification model with python API. However, predict with C API did not work. I think it is the input data that led to this problem.

In my case, train and test data include object columns. Python package 'pandas' can easily transform object to category. When it came to   C API, it is hard to process the test data.

Any solutions?

Thanks,
Leed

**Comment by jmoralez** [comment]
Hey @leedchou, thanks for using LightGBM. The C API only handles floats. When you use categorical features in Python they get translated to their numeric representation. https://github.com/microsoft/LightGBM/blob/074b3e885503dfcb12a05268d6f4169054b15264/python-package/lightgbm/basic.py#L813

So you can extract the mappings of the categorical features from your dataframe and use that in your C application, e.g.

```python
mappings = {
    col: {val: enc for enc, val in enumerate(dtype.categories)}
    for col, dtype in df.dtypes.items() if isinstance(dtype, pd.CategoricalDtype)
}
```
where `df` is your training dataframe.

Please let us know if you have further doubts.

**Comment by leedchou** [comment]
Thank you @jmoralez very much for quick reponse, that is helpful.
