### ISSUE TITLE
[python-package] The setup.py file is missing

### ISSUE THREAD

**Issue by onlinepy** [microsoft/LightGBM#6240]
Hi, 
   I am trying to run the LightGBM model on a GPU, and my computer is configured with x64 /NVIDIA x3060.
1.  Compile and construct the source file 
    -   Set BOOST_ROOT=C:/local/boost_1_69_0/ 
    -  Set BOOST_LIBRARYDIR=C:/local/boost_1_64_0/lib64-msvc-14.1 
    -  git clone --recursive https://github.com/Microsoft/LightGBM
    
2.  CMake GUI is compiled successfully

3.  Go to ".\LightGBM\build" from the command line and type:
    - cmake --build. --target ALL_BUILD --config Release Correct;
  
4. But go to ".\LightGBM\python-package\" from the command line and type
    python setup.py install -- error on gpu: C:\Users\19049\AppData\Local\Programs\Python\Python310\python.exe:  can't open file 
    'C:\\Users\\19049\\LightGBM\\python-package\\setup.py': [Errno 2] No such file or directory

So I wonder if this 【\LightGBM\python-package】is missing the setup.py startup file

Reference link: https://www.jianshu.com/p/30555fd2bd50
[Doc1.docx](https://github.com/microsoft/LightGBM/files/13723561/Doc1.docx)

**Comment by jameslamb** [comment]
Thanks for using LightGBM.

I'm not sure what that `jianshu.com` link is, but it's not official LightGBM documentation. `setup.py` was removed from `lightgbm` as of v4.0.0.

Please follow the installation instructions at https://github.com/microsoft/LightGBM/blob/master/python-package/README.rst.

**Comment by onlinepy** [comment]
Very Thanks~
