### ISSUE TITLE
lost help docs on how to build R package with GPU

### ISSUE THREAD

**Issue by spedygiorgio** [Microsoft/LightGBM#627]
I was trying to use ligthGbm with GPU, but I lost the instruction on how to build in R... Once there was a full documentation at this regard... Is it possible to put it again? Thnks

**Comment by guolinke** [comment]
Set `use_gpu` to `TRUE` in `R-package/src/install.libs.R` to enable the build with GPU support. You will need to install Boost and OpenCL first: details for installation can be found in [gpu-support](https://github.com/Microsoft/LightGBM/wiki/Installation-Guide#with-gpu-support).

**Comment by spedygiorgio** [comment]
I meant that once the documentation provided that details in full. I was suggesting to put it in the official documentation again. G
