### ISSUE TITLE
[ci] python-package "regular" CI jobs failing to install dependencies

### ISSUE THREAD

**Issue by jameslamb** [microsoft/LightGBM#6282]
## Description

The `TASK=regular` jobs in this project's CI run the Python package's unit tests and test a few other things:

* the example notebookes in the `examples/` directory
* that `lightgbm` can be imported after all of its dependencies have been removed

Those jobs are currently failing across all operating systems, with an error like this:

```text
[NbConvertApp] Converting notebook interactive_plot_example.ipynb to notebook
[IPKernelApp] ERROR | KeyboardInterrupt caught in kernel.
[NbConvertApp] Writing 178679 bytes to interactive_plot_example.ipynb

PackagesNotFoundError: The following packages are missing from the target environment:
  - dask

Error: Process completed with exit code 255.
```

## Reproducible example

Logs from latest commit on `master`:

* Azure DevOps `Linux_latest regular` ([link](https://dev.azure.com/lightgbm-ci/lightgbm-ci/_build/results?buildId=15695&view=logs&j=275189f9-c769-596a-7ef9-49fb48a9ab70&t=3a9e7a4a-04e6-52a0-67ea-6e8f6cfda74f))
* Azure DevOps `macOS regular` ([link](https://dev.azure.com/lightgbm-ci/lightgbm-ci/_build/results?buildId=15695&view=logs&j=31d31d6b-9897-5af8-16dd-840b6b6b4fac&t=83900217-b42d-5232-5e45-a25e1385a5c6))
* GitHub Actions `regular (macOS-latest, Python 3.9)` ([link](https://github.com/microsoft/LightGBM/actions/runs/7551480124/job/20558779338))

## Environment info

LightGBM version or commit hash: https://github.com/microsoft/LightGBM/commit/255c93b551c13b5d9b0bd8eff83ef828b14b9547

## Additional Comments

I don't see any of the dependencies like `dask`, `dask-core`, etc. getting installed in the logs.

It seems that this might be silently failing:

https://github.com/microsoft/LightGBM/blob/255c93b551c13b5d9b0bd8eff83ef828b14b9547/.ci/test.sh#L128-L135

**Comment by jmoralez** [comment]
I believe the command that's failing is the uninstall, maybe it's due to  a difference between installing with mamba and trying to uninstall with conda.
https://github.com/microsoft/LightGBM/blob/255c93b551c13b5d9b0bd8eff83ef828b14b9547/.ci/test.sh#L312
https://github.com/microsoft/LightGBM/blob/255c93b551c13b5d9b0bd8eff83ef828b14b9547/.ci/test.sh#L322

I can submit a PR with that change if you think that may be it.

**Comment by jameslamb** [comment]
ooooo interesting. Yeah I'd welcome that PR, thank you!

**Comment by jameslamb** [comment]
If that doesn't work, could you test another idea I just had?

Maybe the problem is that the package we install is named `dask-core`

https://github.com/microsoft/LightGBM/blob/255c93b551c13b5d9b0bd8eff83ef828b14b9547/.ci/test.sh#L128

but then we're asking `conda uninstall` to remove a package called `dask`.

https://github.com/microsoft/LightGBM/blob/255c93b551c13b5d9b0bd8eff83ef828b14b9547/.ci/test.sh#L322-L325

Maybe something has changed recently in `conda`, `mamba`, or the `dask-core` metapackage that breaks that.

Either way, I think we should probably be adding `dask-core` to that `conda uninstall` call.
