### ISSUE TITLE
Is it possible to partition my data into sets that are keyed on a single column, where that column is not a feature, and still use only one model?

### ISSUE THREAD

**Issue by ToadstoolJam** [microsoft/LightGBM#6290]
Imagine I have a fictional need to predict the food hygiene safety of foods based upon certain environmental factors, e.g. age of product, storage temperature, time at room temperature, number of reported cases of food poisoning, etc. I currently have one model per food type, e.g. one for cheese, one for bread, etc. For simplicity, I'm using binary classification for "is safe" / "isn't safe" predictions.

Having a separate model per food type seems to provide good results, but when I have thousands of food types, I have thousands of models and it can take a long time to load all the relevant models when making bulk/batch queries, even with lazy loading and pooling.

I'm currently assuming that a single model can only answer one question, hence the need for a model per food type, e.g. will food X be safe, will food Y be safe, etc. I would like to have one model that can answer the same questions, for all food types in my training data.

Is it technically possible to have a single large model that includes all food types, instead of having lots of smaller models?

If I include my food type column in the training data, without any special considerations, I'm assuming it will be considered as just another feature that may or may not be used by the model, and not properly used to partition the model data structures internally - is this correct?

If LightGBM cannot implement this single large model, are there any other tools/technologies/algorithms that can do this?

**Comment by wil70** [comment]
Corret @ToadstoolJam. Adding a column type should work. I would just try. 

You want this ("may or may not be used") so some trees might use the food type, some might not. That will allow it to find interresting similatrities/relations accrosss those food types.

One issue you might meet is the number of row per food type category. You might need to play with "weight" or get more data to balance this out so it doesn't focus/bias only on the food type with the most data.

**Comment by ToadstoolJam** [comment]
Thanks @wil70. I'll give it a go and see how it compares to a model per food type. 

In my use-case scenario, the food type is actually very key to the decision making process. If there's any chance that food type might become unused because the algorithm/data suggests it has low value when compared to other columns/features, that might actually make my model worse for my scenario.

As you suggest, I just need to try it and evaluate the models to see what actually happens!

The most significant motivation for trying to get one large model instead of lots of smaller models was to decrease load time and memory usage of the model.

I've just found that if I switch my .NET project from Debug to Release mode, model loading and query times are significantly reduced. So much that a model per food type now runs within an acceptable time period, even if the models collectively consume a huge amount of memory.
