### ISSUE TITLE
LGBM_DatasetCreateFromMat question

### ISSUE THREAD

**Issue by limingyao001** [microsoft/LightGBM#6291]
I keep getting a return value of -1 when attempting to create a dataset using LGBM_DatasetCreateFromMat. My vertex_dataset is a float type vector with a length of 87,220, and vertex_labels has a length of 490. The number of features is 178, which matches the product of the number of samples and features, so the dimensions should be correct. I've also confirmed that the data is stored in row-major order. I'm unsure where the issue lies.

auto result_1 = LGBM_DatasetCreateFromMat(static_cast<void*>(vertex_dataset.data()), C_API_DTYPE_FLOAT32, int32_t(vertex_labels.size()), int32_t(featureNum * 2), 1, nullptr, nullptr, &dataset_handle);

**Comment by guolinke** [comment]
It is mostly caused by the mis-used of this api.
please refer to this test: https://github.com/microsoft/LightGBM/blob/252828fd86627d7405021c3377534d6a8239dd69/tests/c_api_test/test_.py#L124-L154
