### ISSUE TITLE
The training process on the ARM platform is thousands of times slower than that on the x86 platform. How to solve this problem?

### ISSUE THREAD

**Issue by hulexing1008** [microsoft/LightGBM#6296]
## References

```[tasklist]
### Tasks
```

**Comment by hulexing1008** [comment]
The training process on the ARM platform is thousands of times slower than that on the x86 platform. How to solve this problem?

**Comment by jameslamb** [comment]
Thanks for using LightGBM.

This is not enough information for anyone to help you. Please:

* reproducible example? (code you ran and how you estimated it was "thousands" of times slower)
* operating system?
* version of LightGBM?
* method you used to install LightGBM?

**Comment by hulexing1008** [comment]
> Thanks for using LightGBM.
> 
> This is not enough information for anyone to help you. Please:
> 
> * reproducible example? (code you ran and how you estimated it was "thousands" of times slower)
> * operating system?
> * version of LightGBM?
> * method you used to install LightGBM?

Thanks for replying. I used the c++ interface in application.cpp (version: 3.35） for regression task and classifcation task(all parameters are default parameters), then compared the training time and the prediction time between the Windows and Linux platform.  The prediction time just has a small gap, while the training time has a big gap. 



![image](https://github.com/microsoft/LightGBM/assets/87417924/8474d60d-ab6a-4ec2-a9df-8a2d35f8cd92)

**Comment by jameslamb** [comment]
Thanks but please provide the information I asked for, or we won't be able to help.

You've reported that "on the ARM platform" LightGBM is "thousands of time slower", but you haven't:

* shown any actual timings
* told us what you mean by "the ARM platform"
* showed how you're calculating those timings or how you installed LightGBM

**Comment by hulexing1008** [comment]
> Thanks but please provide the information I asked for, or we won't be able to help.
> 
> You've reported that "on the ARM platform" LightGBM is "thousands of time slower", but you haven't:
> 
> * shown any actual timings
> * told us what you mean by "the ARM platform"
> * showed how you're calculating those timings or how you installed LightGBM

Some of timings information is below (I used the "std::chrono::system_clock::now()" function to do the timing):
![image](https://github.com/microsoft/LightGBM/assets/87417924/0adf8449-df19-4ede-88a3-770bf0422f37)

1. "the ARM platform"：the Linux operating system with arm cpu architecture.
2. the lightGBM is installed just follow by the Installztion Guide (https://lightgbm.readthedocs.io/en/latest/Installation-Guide.html)

**Comment by jameslamb** [comment]
Until you provide the information we've asked for, I personally won't spend any more time trying to help with this.

"I followed the installation guide" is not specific enough, for example. That guide describes many different customizations, including two different methods of enabling GPU acceleration.
