### ISSUE TITLE
Windows version DLL and Release are not compiling - Cannot open include file fast_double_parser.h: No such file or directory

### ISSUE THREAD

**Issue by wil70** [microsoft/LightGBM#6297]
## Description
I did a pull of the latest version for windows and neither the DLL and Release project are compiling.
It seems files related to fast_double_parser are missing.

## Reproducible example
git pull
compile in VS

## Environment info
Windows 10 PRO, latest git, Lightgbm and VS

LightGBM version or commit hash:
Lastest

Command(s) you used to install LightGBM
![image](https://github.com/microsoft/LightGBM/assets/7807709/7c7c8082-851e-4c7a-8516-c8e8394e4a26)
![image](https://github.com/microsoft/LightGBM/assets/7807709/41dd6d56-f959-4bc5-ae79-c12da8dacb48)

Thanks!
w

**Comment by jameslamb** [comment]
`fast_double_parser` is included here as a git submodule. I suspect you didn't initialize those.

Please run this from the root of the repo:

```shell
git submodule update --init --recursive
```

**Comment by wil70** [comment]
Working - Super - Thank you @jameslamb !

**Comment by jameslamb** [comment]
No problem!

At some point maybe we should consider adding some `FetchContent()` calls in `CMakeLists.txt` so people don't trip over this. We get a report like this about once every other month... it's an easy thing to miss and hard to diagnose if you're not used to `git` submodules.

**Comment by wil70** [comment]
Hello, 

I was behind on my version, I updated it and I have the same error again "Severity	Code	Description	Project	File	Line	Suppression State	Details
`Error	C1083	Cannot open include file: 'fast_double_parser.h': No such file or directory	LightGBM	C:\\LightGBM\utils\common.h" 

`I did 
`git submodule update --init --recursive`
but the issue is still there.

I tried from another machine and I have the same issue

I'm using latest version of LightGBM from Git and lastest Visual Studio on win pro 10

Thanks

Wilhelm

**Comment by wil70** [comment]
Hello,

I was behind on my version, I updated it and I have the same error again "Severity Code Description Project File Line Suppression State Details
`Error C1083 Cannot open include file: 'fast_double_parser.h': No such file or directory LightGBM C:\LightGBM\utils\common.h"

I did git submodule update --init --recursive`
but the issue is still there.

I tried from another machine and I have the same issue

I'm using latest version of LightGBM from Git and lastest Visual Studio on win pro 10

Thanks

Wilhelm

    On Friday, February 2, 2024 at 12:58:42 PM PST, James Lamb ***@***.***> wrote:  
 
 


No problem!

At some point maybe we should consider adding some FetchContent() calls in CMakeLists.txt so people don't trip over this. We get a report like this about once every other month... it's an easy thing to miss and hard to diagnose if you're not used to git submodules.

**Comment by jameslamb** [comment]
Did you re-generate your build directory after pulling in the submodules? If not, that could explain those files still not being present.

```shell
rm -rf ./build
cmake -B build -S .
cmake --build build --target _lightgbm
```

**Comment by wil70** [comment]
The file are present but in the $(ProjectDir)\..\external_libs\

Like if I add the following to VS in "Additional include lib" then it compile:
$(ProjectDir)\..\external_libs\eigen;$(ProjectDir)\..\external_libs\fast_double_parser\include;$(ProjectDir)\..\external_libs\compute\include\boost;$(ProjectDir)\..\external_libs\fmt\include;%(AdditionalIncludeDirectories)

**Comment by jameslamb** [comment]
Yes, that's where they get cloned to.

https://github.com/microsoft/LightGBM/blob/3175a91224b5d2d505131e9254e4bb24a76afbea/.gitmodules#L10-L11

It makes sense to me that if you are using a GUI to drive a compiler, you'd have to tell that tool to look there for headers. Heres's the equivalent CMake:

https://github.com/microsoft/LightGBM/blob/3175a91224b5d2d505131e9254e4bb24a76afbea/CMakeLists.txt#L118-L129

If it's possible to just use CMake instead, I recommend doing that.

That `external_libs/` location has been the same in LightGBM for almost 4 years (#3405), and LightGBM is tested with multiple different versions of Visual Studio (programmatically) on every commit. So I suspect the issue you're facing is related to your local configuration of the Visual Studio GUI. I personally don't use that tool, so won't be able to help much more.

**Comment by wil70** [comment]
Thanks James, I will try the cmake command later on, all good for now with VS
thanks again
Wilhelm
    On Friday, August 2, 2024 at 08:39:35 PM PDT, James Lamb ***@***.***> wrote:  
 
 


Yes, that's where they get cloned to.

https://github.com/microsoft/LightGBM/blob/3175a91224b5d2d505131e9254e4bb24a76afbea/.gitmodules#L10-L11

It makes sense to me that if you are using a GUI to drive a compiler, you'd have to tell that tool to look there for headers. Heres's the equivalent CMake:

https://github.com/microsoft/LightGBM/blob/3175a91224b5d2d505131e9254e4bb24a76afbea/CMakeLists.txt#L118-L129

If it's possible to just use CMake instead, I recommend doing that.

That external_libs/ location has been the same in LightGBM for almost 4 years (#3405), and LightGBM is tested with multiple different versions of Visual Studio (programmatically) on every commit. So I suspect the issue you're facing is related to your local configuration of the Visual Studio GUI. I personally don't use that tool, so won't be able to help much more.
