### ISSUE TITLE
Build instructions for inference-only static library

### ISSUE THREAD

**Issue by mvelbaum** [microsoft/LightGBM#6302]
Hi,

I have a single-threaded application (pinned to a core) that needs to only perform inference on an exported LightGBM model with low-latency.

Looking at the [installation instructions](https://lightgbm.readthedocs.io/en/latest/Installation-Guide.html#build-threadless-version-not-recommended) it seems that compiling a threadless version is not recommended. Does this recommendation also apply to my use-case?

It is not really clear to me if OpenMP is required for inference or not, or if there are more optimized build options for this type of use-case.

Thanks!

**Comment by jameslamb** [comment]
Thanks for using LightGBM.

OpenMP is not **required** for inference with LightGBM.

If you are trying to minimize the latency of **one-row-at-a-time** latency, you might find that building LightGBM without OpenMP helps (smaller library and no dynamic linking = faster library loading).

LightGBM **can** use OpenMP at inference time. For example, see the implementation of `Predictor::Predict()`:

https://github.com/microsoft/LightGBM/blob/7435cd8d084314692b367a74f1b5250dca0fd4f1/src/c_api.cpp#L441-L448

Notice that that's parallelizing over *rows*. That'll give you better throughput than running single-threaded if the process is allowed to use multiple CPUs, if you've built LightGBM with linking to OpenMP (the default), and if you're predicting on multiple rows at once.

If you're calling LightGBM on a single row at a time, and want to minimize the prediction time, see the `LGBM_*SingleRowFast*()` APIs, e.g.:

https://github.com/microsoft/LightGBM/blob/7435cd8d084314692b367a74f1b5250dca0fd4f1/include/LightGBM/c_api.h#L1350-L1357

Hope that helps. To provide more information for this question:

> *Does this recommendation also apply to my use-case?*

We need more details about your application.

* what format is the model stored in?
* are you loading the model into memory every time you generate a prediction, and therefore is that loading time part of what you're trying to minimize?
* are you performing one-row inference, or batch inference on mulltiple rows at a time?

**Comment by mvelbaum** [comment]
@jameslamb thanks for a very thorough response, I really appreciate it! :)

To answer your questions:

> what format is the model stored in?

We use `Booster.model_to_string()` from python and store it in a DB. This is later on dumped to a text file to be loaded by the app.

Btw, I understand that there might also be a way to convert this model directly to C++ code. It may be less flexible, but I wonder if this is something worth doing (whether it will be more performant than what we do now).

> are you loading the model into memory every time you generate a prediction, and therefore is that loading time part of what you're trying to minimize?

On our app's init we do:
1. `LGBM_BoosterCreateFromModelfile(model_filename, &num_iterations, &booster_handle)` to load the previously stored model from file.
2. `LGBM_BoosterPredictForMatSingleRowFastInit(booster_handle, C_API_PREDICT_NORMAL, 0, -1, C_API_DTYPE_FLOAT64, num_features, "", &fch)` and store the FastConfigHandle object for later use.

> are you performing one-row inference, or batch inference on mulltiple rows at a time?

Yes, the prediction function just runs `LGBM_BoosterPredictForMatSingleRowFast(fch, data, out_len, out_result)`.

I'm building the inference-only static lib with these flags:
```
-DCMAKE_BUILD_TYPE=Release
-DUSE_OPENMP=OFF
-D__BUILD_FOR_PYTHON=OFF
-DDISABLE_TESTS=ON
-DINSTALL_HEADERS=ON
-DBUILD_CLI=OFF
-DBUILD_STATIC_LIB=ON
```

**Comment by jameslamb** [comment]
Thanks for those details, that helps a lot!

> the inference-only static lib with these flags

These look good to me. Based on what you described, I do expect that turning off OpenMP is worthwhile.

But one small note... LightGBM's CMake configuration doesn't have an option `DISABLE_TESTS`. Did you maybe mean `-DBUILD_CPP_TEST=OFF`?

https://github.com/microsoft/LightGBM/blob/ecfdc76cc2c1e105d9624fcddc84c635f114014c/CMakeLists.txt#L19

You might also try different compilation flags. LightGBM build tries to balance between library size and execution speed, e.g. for GCC / MinGW the project use `-O3` optimization by default:

https://github.com/microsoft/LightGBM/blob/ecfdc76cc2c1e105d9624fcddc84c635f114014c/CMakeLists.txt#L337-L341

You might find you get faster execution compiling the library with, say, `-Ofast`. See https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html (search for "speed") to see other things you can try changing.

Other things you could try:

* dumping the model to C++ (as you've already mentioned)
* enabling prediction early stopping, such that LightGBM will stop adding results from further trees if the score isn't changing by much ([parameter docs](https://lightgbm.readthedocs.io/en/latest/Parameters.html#pred_early_stop))
* try compiling the model with `tl2cgen` ([docs](https://tl2cgen.readthedocs.io/en/latest/tutorials/optimize.html)) and serving it with `treelite` ([dmlc/treelite](https://github.com/dmlc/treelite/tree/mainline))
   - related conversation: https://github.com/microsoft/LightGBM/issues/5257#issuecomment-1146692863

**Comment by mvelbaum** [comment]
Thank you so much! I guess you can close this issue now.

**Comment by jameslamb** [comment]
Alright, we'll close this. Happy that helped!

We'd welcome contributions if you find any areas for improvement, come back any time 👋🏻
