### ISSUE TITLE
Error while downloading LightGBM on Windows GPU version. -cmake error is attached below.

### ISSUE THREAD

**Issue by asking28** [Microsoft/LightGBM#631]
![error](https://user-images.githubusercontent.com/29248466/27250826-805874b6-5356-11e7-9b60-3477466c4ae0.png)

1.I installed CUDA, then I clone GPU version LightGBM in path C:\github_repos using Git Bash.Then I ran cmake which gave error.

**Comment by guolinke** [comment]
@asking28 
It seems you don't have cpp compiler. Do you have MS build or visual studio ?
And the correct version of boost ?

**Comment by asking28** [comment]
Yes Sir I have 2 versions of boost ,boost_1_63_0 and boost_1_64_0. I have Miscrosoft Visual Studio Code. And codeblocks Installed.

**Comment by guolinke** [comment]
@asking28 
code::blocks ?  A cpp compiler ? 
We only test it with visual studio (VS code is only a editor, not a IDE), MS Build and cmake. 
refer to https://github.com/Microsoft/LightGBM/wiki/Installation-Guide#windows

**Comment by asking28** [comment]
@guolinke 
Yes Sir,Code::blocks.I am downloading Visual Studio.If it works I will let you know.Thank You,

**Comment by asking28** [comment]
![image](https://user-images.githubusercontent.com/29248466/27251473-9f358cde-5365-11e7-87e2-e164da077a6f.png)
Sir,now I get this error.

**Comment by guolinke** [comment]
Lightgbm is in your system32 folder?
please run it in the corrct folder

**Comment by asking28** [comment]
![error3](https://user-images.githubusercontent.com/29248466/27251945-9345b8e0-536f-11e7-9c54-d1a39ca0fa91.png)
It is giving same error.

**Comment by guolinke** [comment]
It seems your installation of MS Build is not correct.  How do you install it ?  
BTW, can you paste the text log instead ?

**Comment by guolinke** [comment]
@asking28 
You installed the Visual Studio 2017 ? Did you enable the visual C++ when installing ?

**Comment by asking28** [comment]
I enabled Visual Studio General while installing.

**Comment by guolinke** [comment]
You can install it again, make sure you enable the visual C++ functions .

**Comment by asking28** [comment]
I reinstalled it but it did not ask me this time to enable Visual C++.

**Comment by guolinke** [comment]
@asking28 refer to this: https://docs.microsoft.com/en-us/visualstudio/install/modify-visual-studio

**Comment by asking28** [comment]
Thanks for the great help.It is working now.
