### ISSUE TITLE
Question: Why does dataset construction take such a long time? Is there any way to make it use the data that is already in memory?

### ISSUE THREAD

**Issue by simpsus** [microsoft/LightGBM#6311]
Basically title.
I have a dataset with ~4mio samples and ~2k features, I want to train multiple times with different targets (so decoupling the dataset creation from the training is not an option).

constructing the dataset takes 6 minutes on my setup. training 1k trees then takes 5 minutes. The dataset construction time is completely unnecessary. the data is already in memory, binned and preprocessed.

Is there a way to create the dataset (datatype or the like) without processing the whole data again?
Can I somehow tell the library to ... not do anything with the data, just take it as it is?
Can I swap/recreate datasets with different targets and leave the bulk of the data (the features) the same?

Thank you very much!

**Comment by jameslamb** [comment]
Thanks for using LightGBM.

If you can provide some of the details that were requested when you clicked "new issue" (version of LightGBM? programming language? how you're installing it?) we can recommend alternatives and explain the limitations in greater detail.

**Comment by jmoralez** [comment]
Hey @simpsus, I believe you can create a Dataset with all of your features and then just use [set_label](https://lightgbm.readthedocs.io/en/stable/pythonapi/lightgbm.Dataset.html#lightgbm.Dataset.set_label) to change the label and train a different model, e.g.
```python
import lightgbm as lgb
import numpy as np

N = 1_000
X = np.random.rand(N, 2)
y1 = np.random.rand(N)
y2 = 2 * y1
ds = lgb.Dataset(X).construct()  # build dataset with features once
ds.set_label(y1)  # set first label
bst1 = lgb.train({}, ds)
print(round(bst1.get_leaf_output(0, 0), 1))  # 0.5
ds.set_label(y2)  # set second label
bst2 = lgb.train({}, ds)
print(round(bst2.get_leaf_output(0, 0), 1))  # 1.1
```

**Comment by simpsus** [comment]
@jmoralez  That is a great hint, thank you. Let me try that and repeat back!

**Comment by simpsus** [comment]
That was a very good tipp @jmoralez. Thank you very much. Now the dataset creation is no longer an issue in my training pipeline.
