### ISSUE TITLE
[python-package] Trying to have the l2 score during `fit` method of LGBMRegressor

### ISSUE THREAD

**Issue by maylisdvoodoo** [microsoft/LightGBM#6312]
## Description
Hi, 
I'm migrating from v3.1.0 to v4.3.0. 
Befofre, I could have in my `fit` method of LGBMRegressor a `verbose` argument showing me during the execution l2 score. 
This was the line logged `[400]	valid_0's l2: 0.0158431`
Now that I'm using v.4.3.0 I have no clue on how to get those logs back, `verbose` argument is not supported anymore in the `fit` metho as we can see[ here ](https://lightgbm.readthedocs.io/en/latest/pythonapi/lightgbm.LGBMRegressor.html#lightgbm.LGBMRegressor.fit)

## Reproducible example
I'm initializing LGBMRegressor with : 
```params = {'min_data_in_leaf': 279, 'n_estimators': 1202, 'max_depth': 6, 'learning_rate': 0.0076356268613033944, 'feature_fraction': 0.6081695832061086, 'lambda_l1': 0.10539052073909096, 'num_leaves': 384, 'max_bin': 931, 'objective': 'regression', 'metric': 'mse', 'boosting': 'gbdt', 'zero_as_missing': True, 'bagging_seed': 1234, 'seed': 1234, 'verbosity': -1} 
clf = lgb.LGBMRegressor(**params, verbose = -1) <--- Here is to avoid too much not usefull logs for me `No further splits with positive gain, best gain: -inf`
clf.fit(
    train_df[features],
    train_df[target_name],
    sample_weight=train_df[weight_name],
    eval_set=[(test_df[features], test_df[target_name])],
    eval_sample_weight=[test_df[weight_name]],
    eval_metric='l2',   <-- The metric I would like to follow during execution
)
```

## Environment info
Python 3.10
LGBM 4.3.0

LightGBM version or commit hash: 4.3.0
<img width="404" alt="Capture d’écran 2024-02-14 à 14 24 41" src="https://github.com/microsoft/LightGBM/assets/135015618/8c5a9b79-5eda-41e5-acdd-ccabde5f3044">

**Comment by jmoralez** [comment]
Hey @maylisdvoodoo, thanks for using LightGBM. This is now done with the [log_evaluation callback](https://lightgbm.readthedocs.io/en/stable/pythonapi/lightgbm.log_evaluation.html#lightgbm.log_evaluation). So you'd need to add that to your fit method, e.g.
```python
clf.fit(
    train_df[features],
    train_df[target_name],
    sample_weight=train_df[weight_name],
    eval_set=[(test_df[features], test_df[target_name])],
    eval_sample_weight=[test_df[weight_name]],
    eval_metric='l2',
    callbacks=[lgb.log_evaluation(period=100)],  # this will print the evaluation every 100 iterations
)
```

**Comment by maylisdvoodoo** [comment]
Thanks a lot @jmoralez 🙏
