### ISSUE TITLE
[python-package] [c++] support scipy sparse arrays

### ISSUE THREAD

**Issue by jameslamb** [microsoft/LightGBM#6352]
## Summary

LightGBM currently has APIs to support two formats of sparse matrices:

* CSC = "Compressed Sparse Column"
* CSR  = "Compressed Sparse Row"

In the Python library `scipy`, these are represented by classes `scipy.sparse.csc_matrix` and `scipy.sparse.csr_matrix`, respectively.

Per `scipy`'s docs ([link](https://docs.scipy.org/doc/scipy/reference/sparse.html))

> *This package is switching to an array interface, compatible with NumPy arrays, from the older matrix interface. We recommend that you use the array objects ([bsr_array](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.bsr_array.html#scipy.sparse.bsr_array), [coo_array](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.coo_array.html#scipy.sparse.coo_array), etc.) for all new work.*

`lightgbm` should add support for `scipy.sparse.csc_array` and `scipy.sparse.csr_array` in all places that currently support the corresponding `*_matrix` classes.

## Motivation

Allows continued use of `scipy` sparse types with `lightgbm`, even after future `scipy` releases remove those matrix types.

## Description

See the discussion in #6348 for more information.

## References

Created based on this comment: https://github.com/microsoft/LightGBM/pull/6348#issuecomment-1973471486

Good visual summary of these types: https://matteding.github.io/2019/04/25/sparse-matrices/#compressed-sparse-rowcolumn

**Comment by StrikerRUS** [comment]
Closed in favor of being in https://github.com/microsoft/LightGBM/issues/2302. We decided to keep all feature requests in one place.

Welcome to contribute this feature! Please re-open this issue (or post a comment if you are not a topic starter) if you are actively working on implementing this feature.
