### ISSUE TITLE
Question - use of is_unbalance or scale_pos_weight parameters in LGBMClassifier (scikit-learn API)

### ISSUE THREAD

**Issue by shimooper** [microsoft/LightGBM#6359]
Hi,
I wonder if the parameters is_unbalance or scale_pos_weight can be passed to the constructor of LGBMClassifier (in the scikit-learn API)? They don't appear in the documentation of the class.
Will it have any effect if I pass one of them?
If the scikit-learn API doesn't support those parameters, how should I handle a binary classification task with imbalanced training data?

**Comment by jmoralez** [comment]
Hey @shimooper, thanks for using LightGBM. The extra arguments provided through the constructor are captured by the `**kwargs` and are passed to the model (see the description for kwargs [here](https://lightgbm.readthedocs.io/en/stable/pythonapi/lightgbm.LGBMClassifier.html)).

> Other parameters for the model. Check http://lightgbm.readthedocs.io/en/latest/Parameters.html for more parameters.
