### ISSUE TITLE
Segmentation fault when use compilation option -DUSE_TIMETAG=ON

### ISSUE THREAD

**Issue by Piao-WU** [microsoft/LightGBM#6386]
> As far as I know, in CLI version there's no way to store the intermediate results in all iterations into a structured data format.

Yeah, that's right.

There is a special compilation option `-DUSE_TIMETAG=ON` to make LightGBM prints timings.
> Users who want to perform benchmarking can make LightGBM output time costs for different internal routines by adding `-DUSE_TIMETAG=ON` to CMake flags.
   https://lightgbm.readthedocs.io/en/latest/Installation-Guide.html

_Originally posted by @StrikerRUS in https://github.com/microsoft/LightGBM/issues/4693#issuecomment-949056678_

**Comment by jameslamb** [comment]
Immediately after this was closed, it was replaced by #6387.

Locking discussion here.
