### ISSUE TITLE
[QUESTION] Adding trees manually on txt file

### ISSUE THREAD

**Issue by NDanies** [microsoft/LightGBM#6392]
## Description

I'm trying to add trees manually to the txt file on lightgbm. This is because I want to train the same lightgbm model on different computers with slightly different datasets and eventually try to incorporate all the trees in a new bagged model (the parameters are the same throught all computers, the feature_infos are continously adjusted, and I add iteratively the tree_sizes and the new tree). It works perfectly for a few iterations, but eventually the following error appears:

```text
LightGBM] [Fatal] Model format error, expect a tree here. met 
[LightGBM] [Warning] Model format error, expect a tree here. met 
libc++abi: terminating due to uncaught exception of type std::runtime_error: Model format error, expect a tree here. met
```

My question is if there is a more intelligent way to add this trees? I don't know if the problem is that I am not taking something into account when adding trees to the file, or there is a better way to add the trees that I haven't found yet. Any suggestions would be greatly appreciated.

For more context, the new trees are constructed by iterating over the previously saved model. Therefore it is a new iteration from an already functioning model:

```python
lgb_model_client = lgb.Booster(model_file='global_model.txt')
num_additional_rounds = 1
lgb_model_client = lgb.train(params, lgb_train, num_boost_round=1, init_model=lgb_model_global)
```

From that new iteration, i save the new tree iteration (last tree generated) and add it to the global model. 

## Reproducible example

[model_no_issue.txt](https://github.com/microsoft/LightGBM/files/14800602/model_no_issue.txt)

[model_issue.txt](https://github.com/microsoft/LightGBM/files/14800603/model_issue.txt)

It works when I load the following tree:

```python
import lightgbm as lgb
lgb_model_client = lgb.Booster(model_file='model_no_issue.txt')
```

When I add another tree with the same parameters, the error above mentioned appears:

```python
import lightgbm as lgb
lgb_model_client = lgb.Booster(model_file='model_issue.txt')
```

The way I add the trees is 

1.  add to the line 10 called tree_sizes the size of the new tree (in this example 3540)
2. add the new tree before "end of trees" (in this example Tree=11)

Are there parameters that limit this intuition?  

## Environment info

LightGBM version or commit hash:

Command(s) you used to install LightGBM
I am using lightgbm 4.3.0

```shell
pip install lightgbm
```

**Comment by jameslamb** [comment]
Thanks for using LightGBM.

I've reformatted your post a bit to make the difference between code, output from code, and your own words a bit clearer. If you're new to GitHub and/or writing markdown, please see https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code to learn about how I did that.

---

I don't immediately see what's wrong with your model file but in general... don't manually merge files like this. There are just too many ways for it to go wrong (mixed line endings, accidental inclusion of special characters, failure to update all parameters correctly, etc.).

If it's acceptable to not be training both models at the same time, do this:

1. train the first model
2. save it to a text file with `.save_model()`
3. move that file over to the other machine
4. train another model on that machine, with new data, passing the path to the first model file to `init_model`

That will cause LightGBM to begin boosting from the end of the first model, using your new dataset. It's not exactly the same as the process you described (where you train two models from scratch and then combine them), but it's a good way to incorporate learnings from new data into an already-training model.

Like this pattern:

https://github.com/microsoft/LightGBM/blob/28536a0a5d0c46598fbc930a63cec72399a969e4/tests/python_package_test/test_engine.py#L1050-L1063

There are some more details on how to do this at https://stackoverflow.com/questions/73664093/lightgbm-train-vs-update-vs-refit/73669068#73669068

----

There *is* an API in LightGBM's C API, `LGBM_BoosterMerge()`, that I believe can be used to take 2 models and combine them together without training, but it's not currently exposed in the Python package.

https://github.com/microsoft/LightGBM/blob/28536a0a5d0c46598fbc930a63cec72399a969e4/src/c_api.cpp#L2008-L2009

We could consider adding that in the Python package.
