### ISSUE TITLE
[R-package] Expose start_iteration to dump/save/lgb.model.dt.tree

### ISSUE THREAD

**Issue by mayer79** [microsoft/LightGBM#6397]
The `predict()` function has a `start_iteration` argument. As in Python, we could expose this argument to 

- `lgb.dump()` and `Booster$dump_model()`,
- `lgb.save()` and `Booster$save_model()`, and
- `Booster$save_model_to_string()`.

Furthermore, we can also add it to `lgb.model.dt.tree()`, providing a straight-forward solution to https://github.com/microsoft/LightGBM/issues/6380

**Comment by jameslamb** [comment]
Thank you, I support this!
