### ISSUE TITLE
[LightGBM] [Info] No further splits with positive gain, best gain: -inf

### ISSUE THREAD

**Issue by zyoohv** [Microsoft/LightGBM#640]
## Environment info
Operating System: Ubuntu16.04
CPU:Intel
Python version: Python 2.7

## Error Message:

Could you tell me what's the mean of this message?

```
[LightGBM] [Info] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Trained a tree with leaves=58 and max_depth=14
```

## Param

```
    "param": {  
    "task":"train",  
    "boosting":"gbdt",  
    "application":"binary",  
    "num_leaves":63,  
    "min_data_in_leaf":1000,  
    "learning_rate":0.1,  
    "feature_fraction":1.0,  
    "bagging_freq":50,  
    "bagging_fraction":0.8  
    }
```

**Comment by guolinke** [comment]
@zyoohv 
it means the learning of tree in current iteration should be stop, due to cannot split any more. 
I think this is caused by ```"min_data_in_leaf":1000```, you can set it to a smaller value.

**Comment by zyoohv** [comment]
@guolinke 
Thank you very much. I changed it according your recommend. And now it works! :)

**Comment by guolinke** [comment]
@zyoohv 
This is not a bug, it is a feature.
The output message is to warn user that your parameters may be wrong, or your dataset is not easy to learn.

**Comment by AdamsMi** [comment]
And how to disable this 'feature', if it's possible :)?

**Comment by guolinke** [comment]
you can shut up the warning by set verbose

**Comment by xuwiliam** [comment]
I also meet this problem, but can not deal with it using the solution referenced in issue640

**Comment by guolinke** [comment]
@xuwiliam it should work if you on the latest master branch. 
If it still doesn't work, you can provide a re-produce code with random generated input data.

**Comment by goldentom42** [comment]
Hi there, the problem still occurs even with the latest master. 

Using lgb.train and verbose set to -1 you don't get the warning *if and only if* you don't provide an argument for valid_sets. If valid_sets is provided you can set verbose or verbosity to whatever value the warning will be displayed.

Hope this helps in finding the issue.

**Comment by wxkpythonwork** [comment]
set lgb.LGBMRegressor(verbose=-1), it works!
