### ISSUE TITLE
[python-package] CUDA version not truly installing

### ISSUE THREAD

**Issue by T-Flet** [microsoft/LightGBM#6417]
## Description
Following the [Python package CUDA Version installation instructions](https://github.com/microsoft/LightGBM/tree/master/python-package#build-cuda-version) produces no errors, but running it with device = 'cuda' in the parameter dictionary does (at least on Windows), yielding

```
LightGBMError: CUDA Tree Learner was not enabled in this build.
Please recompile with CMake option -DUSE_CUDA=1
```

Is there a workaround?

## Installation process (with no errors)

```
pip install lightgbm --config-settings=cmake.define.USE_CUDA=ON
```
(=ON or =1) while having each of the following installed:
* [CMake](https://cmake.org/download/) (3.29.2)
* [VS / VS Tools](https://visualstudio.microsoft.com/downloads/) (2022)
* [CUDA Toolkit](https://developer.nvidia.com/cuda-downloads) (12.4.1)
* Either or both of the boost Python package (`conda install -c conda-forge boost`) and the [Boost binaries](https://sourceforge.net/projects/boost/files/boost-binaries/) (of version higher than the first supporting the C++ compiler in the installed VS) (1.84.0)

### --no-binary
The following fails in `Building wheel for lightgbm (pyproject.toml)`:
```
pip install --no-binary lightgbm --config-settings=cmake.define.USE_CUDA=1 lightgbm
```
Error (after very long processing, silently running the cmakes in the next attempt):
```
...
      *** CMake build failed
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for lightgbm
Failed to build lightgbm
ERROR: Could not build wheels for lightgbm, which is required to install pyproject.toml-based projects
```
(No clear cause in the endless log above this, which is the same one produced during the successful build below).

### Local python-package folder install after successful build
(Trying to follow [this post](https://github.com/microsoft/LightGBM/issues/5989#issuecomment-1700534791) just in case the Python package is able to use the built version).
```
git clone --recursive https://github.com/microsoft/LightGBM
cd LightGBM
mkdir build
cd build
cmake -A x64 -DUSE_CUDA=1 -DBOOST_ROOT=C:/local/boost_1_84_0 -DBOOST_LIBRARYDIR=C:/local/boost_1_84_0\lib64-msvc-14.3 ..
cmake --build . --target ALL_BUILD --config Release
cd ..
```
After the build succeeds, try and appease
```
pip install -e .\python-package\ --config-settings=cmake.define.USE_CUDA=1
```
by copying CMakeLists.txt, LICENSE and the src folder into the python-package folder, eventually producing the same error as above.

**Comment by jameslamb** [comment]
Thanks for using LightGBM.

As the documentation  ([link](https://lightgbm.readthedocs.io/en/latest/Installation-Guide.html#build-cuda-version)) states:

> **Windows**
> _The CUDA version is not supported on Windows. Use the GPU version (device_type=gpu) for GPU acceleration on Windows._

There is a very conversation about this in #6325.

If you'd like to help with getting that support added here, we'd welcome more specifics on exactly the issue you're facing. You could provide the following:

* what version of Python?
* what version of Windows?
* what version of the CUDA Toolkit, how did you install it, and what path is it installed at?
* what is the full build log you get from running the following command? Attach it as a text file like https://github.com/microsoft/LightGBM/issues/6325#issuecomment-1951279662

```shell
pip install \
    --no-binary lightgbm \
    --config-settings=cmake.define.USE_CUDA=ON \
    'lightgbm>=4.3.0'
```

----

> *into the python-package folder*

Do not try to `pip install python-package/`, `cd python-package/ && python setup.py install`, or similar here. This project's source layout does not support that.

If you want to build the Python package from a cloned copy of the entire repo, do it like this:

```shell
sh build-python.sh install --cuda
```

**Comment by T-Flet** [comment]
Thank you for the quick reply and apologies for not linking the CLI documentation bit about CUDA support on Windows (I thought there might have been a chance for the Python package since its documentation gives the installation command shortly after mentioning the build requirement for Windows, and the GPU version installs and works fine for me).

### Environment
Here are the additional environment details:
* Python 3.11.7
* Windows 11 Pro - 23H2 - 22631.3447

And the previous ones restated for convenience:
* [CMake](https://cmake.org/download/) (3.29.2)
* [VS / VS Tools](https://visualstudio.microsoft.com/downloads/) (2022)
* [CUDA Toolkit](https://developer.nvidia.com/cuda-downloads) (12.4.1)
* Both the boost Python package (`conda install -c conda-forge boost`) and the [Boost binaries](https://sourceforge.net/projects/boost/files/boost-binaries/) (1.84.0)

The CUDA Toolkit was installed with the Windows 11 x86_64 exe from the link and resides at C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4; the build command detected it on its own so I did not have to supply its path as an extra argument.


### Full output of install command
```
pip install \
    --no-binary lightgbm \
    --config-settings=cmake.define.USE_CUDA=ON \
    'lightgbm>=4.3.0'
```
[console_output.txt](https://github.com/microsoft/LightGBM/files/14996102/console_output.txt)


### Full output of build-python.sh
```
sh build-python.sh install --cuda
```
in the cloned repo.
[console_output2.txt](https://github.com/microsoft/LightGBM/files/14996411/console_output2.txt)

**Comment by shiyu1994** [comment]
Thank you for reporting this. The CUDA version has not been tested on Windows yet. I can help to verify it on windows environment when I find some time.

**Comment by jameslamb** [comment]
@shiyu1994 I have an old Windows laptop with a GeForce, I can help test this one too. I just wanted to get the full output from this report first to be sure we understood the issue.
