### ISSUE TITLE
[R] How to save an lgb.CVBooster model to file?

### ISSUE THREAD

**Issue by bosonnn** [Microsoft/LightGBM#643]
- run the cv 

```{r}
lgb_model_cv <- lgb.cv(params = param, dtrain, nfold = 10, nrounds = 100000, verbose = 1, early_stopping_rounds = 5)
```

- get an error when trying to save the output
```{r}
lgb.save(lgb_model_cv, 'output/lgb_0622_logloss')
```

> lgb.save(lgb_model_cv, 'output/lgb_0622_logloss')
Error in lgb.save(lgb_model_cv, "output/lgb_0622_logloss") : 
  lgb.save: booster should be an ‘lgb.Booster’

**Comment by guolinke** [comment]
@bosonnn 
I think CV actually doesn't contain a model, it contains many models. 
CV is used for the parameter tuning. 
So a better way is using the parameters used CV to train a model by ```lgb.train```.
