### ISSUE TITLE
Predictions are very slow when feature dimension is large

### ISSUE THREAD

**Issue by araujoalexandre** [Microsoft/LightGBM#644]
Hi, 

I have a dataset with 800M instances for training and 100M for validation. 
The dataset is in LibSVM format. I use the command line interface with Ubuntu. 

The training time was very reasonable compare to the size of the dataset ~ 6-7 hours. 
After the training finished, I overridden the **gbdt_prediction.cpp** with the hard coded model dumped from the convert_model, convert_model_language option. 

Even with all this, the prediction are really slow. After 3 hours, I have only a few hundred thousand instances predicted dumped in the prediction file. 

How can I speed up the prediction drastically ? 

Thank you,

**Comment by guolinke** [comment]
@araujoalexandre 
can you provide the number of your feature ? 
and the parameters used in training ? 
Did you try the prediction without if-else conversion ? Is that even slower ?

**Comment by araujoalexandre** [comment]
I have 134 features
Yes I tried without If-else conversion. I think it's a bot slower.

**Comment by guolinke** [comment]
@araujoalexandre Did you use the code of master branch? 
I think it should be very fast.

**Comment by araujoalexandre** [comment]
Yes, I used the master branch. 
In the LibSVM, indexes are in a 2**25 dimension space. 
Would that be the problem ?

**Comment by guolinke** [comment]
@araujoalexandre 
134 feature with  2**25 dimension ? 
Yeah, it will be a big problem.

A possible solution: set ```num_thread``` to ```1``` or ```2```, to reduce the memory cost.

**Comment by araujoalexandre** [comment]
I used the hashing trick to create the dataset. 
So the number of feature is not very high but the dimension is very large to avoid collision. 

I'll try with 1 or 2 treads. 
Otherwise I guess I need to re map the index in a smaller dimension space. 

Would that resolve the problem ?

**Comment by guolinke** [comment]
@araujoalexandre 
yeah, it will be much faster if feature dimension is small. But you need to retrain the model as well.

**Comment by araujoalexandre** [comment]
@guolinke 
I tried with 1 thread, it is still very slow. 
I tried to do a re map of the index into a much smaller dimension space. 

The thing I don't understand is why the training is fast with the same dimension space but the prediction is slow.

**Comment by guolinke** [comment]
@araujoalexandre 
We have many optimizations for the training with high dimension data.
However, for the prediction, it needs many random access on feature space. And we didn't optimize for it yet.

**Comment by araujoalexandre** [comment]
@guolinke 
It worked, after a re map of the index into a decent dimension space, the predictions took only a few minutes on 100M rows  !
Thanks a lot !

**Comment by guolinke** [comment]
@araujoalexandre 
I think the slow prediction with sparse high dimension had been fixed in the latest version.
