### ISSUE TITLE
Q: thread safe, In file src/application/predictor.hpp

### ISSUE THREAD

**Issue by hlee13** [Microsoft/LightGBM#645]
Such as the title.

branch master, file: src/application/predictor.hpp , line:150

if I change the function 'fprintf' to 'fwrite', it would not be thread safe.
I want to use fwrite, but found do not work. If I need use lock when call fwrite function

**Comment by guolinke** [comment]
sorry, I didn't get you. 
why need to change to `fwrite` ?

**Comment by hlee13** [comment]
![image](https://user-images.githubusercontent.com/4981187/27481735-cb85caca-5850-11e7-840e-96fcec6035d8.png)

I found the problem.

**Comment by hlee13** [comment]
I what to binary to file.

data is std::vector<double>
when I use fwrite, the file contains both Big_endian and Little_endian.

**Comment by hlee13** [comment]
I get it, sorry.
