### ISSUE TITLE
Any suggestions for predicting all values to be 0?

### ISSUE THREAD

**Issue by MatthewZhuang** [microsoft/LightGBM#6460]
I'm working on the stock return prediction task, when I use the logarithmic return as the label, the model predicts that the value is close to 0, and when it is changed to the original value, the model can predict normally; What are the possible reasons for this?

**Comment by jameslamb** [comment]
Thanks for using LightGBM.

Can you share a minimal, reproducible example showing this behavior? I don't quite understand what you're asking.
