### ISSUE TITLE
Add parameter to configure connetcing time between ranks?

### ISSUE THREAD

**Issue by strint** [Microsoft/LightGBM#649]
When running socket version parallel lightGBM, multiple lightGBM instances cannot start at the same time in my situation. One rank maybe start 15 minutes later the other rank, but the socket will only try to connect 20 times(200 seconds, 3.3 minutes) and fail(link to the code https://github.com/Microsoft/LightGBM/blob/842c592eafd56a570ca726f9fe045d98c149180b/src/network/linkers_socket.cpp#L194 ).

To deal with the situation that multiple lightGBM instances cannot start at the same time, adding a parameter to configure connetcing time between ranks will be vary helpful.

Synchronizing before different ranks starts can also solve this problem, but will not be that easy to use as configuring one parameter.

**Comment by guolinke** [comment]
@strint 
I think this situation is rare, so add a parameter may is too heavy. 
A simple solution is set ```connect_fail_retry_cnt ``` or (```connect_fail_delay_time ```) to a larger number directly.

**Comment by strint** [comment]
@guolinke 
Yes, it's a little heavy.

 I will just edit the number and re-compile the code for the moment.

thx!
