### ISSUE TITLE
LightGBM\include\LightGBM/utils/common.h(33,10): fatal error C1083: Cannot open include file: 'fast_double_pa rser.h': No such file or directory

### ISSUE THREAD

**Issue by CRossel87a** [microsoft/LightGBM#6505]
Hi,

The latest version fails to compile. Someone removed a file?

LightGBM\include\LightGBM/utils/common.h(33,10): fatal error C1083: Cannot open include file: 'fast_double_pa
rser.h': No such file or directory

**Comment by CRossel87a** [comment]
There are access issues

D:\Source\LightGBM>git submodule update --init --recursive
Cloning into 'D:/Source/LightGBM/external_libs/eigen'...
git@gitlab.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'https://gitlab.com/libeigen/eigen.git' into submodule path 'D:/Source/LightGBM/external_libs/eigen' failed
Failed to clone 'external_libs/eigen'. Retry scheduled
Cloning into 'D:/Source/LightGBM/external_libs/eigen'...
git@gitlab.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'https://gitlab.com/libeigen/eigen.git' into submodule path 'D:/Source/LightGBM/external_libs/eigen' failed
Failed to clone 'external_libs/eigen' a second time, aborting

**Comment by jameslamb** [comment]
Did you make some modifications to LightGBM? I'm surprised to see any errors about SSH (`git@gitlab.com`) issues cloning Eigen... LightGBM uses an HTTPS remote for Eigen.

https://github.com/microsoft/LightGBM/blob/e9a6c798071632f0e9bdf4c5fa2fdf16bfd5eb36/.gitmodules#L4-L6

And the repository at https://gitlab.com/libeigen/eigen absolutely exists and is publicly available.

What happens if you simply run this?

```text
git clone https://gitlab.com/libeigen/eigen external_libs/eigen
```

---

I've edited your post to make the difference between code, output from code, and your own words clearer. Please see https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax if you're not familiar with editing text on GitHub.

**Comment by CRossel87a** [comment]
> Did you make some modifications to LightGBM? I'm surprised to see any errors about SSH (`git@gitlab.com`) issues cloning Eigen... LightGBM uses an HTTPS remote for Eigen.
> 
> https://github.com/microsoft/LightGBM/blob/e9a6c798071632f0e9bdf4c5fa2fdf16bfd5eb36/.gitmodules#L4-L6
> 
> And the repository at https://gitlab.com/libeigen/eigen absolutely exists and is publicly available.
> 
> What happens if you simply run this?
> 
> ```
> git clone https://gitlab.com/libeigen/eigen external_libs/eigen
> ```
> 
> I've edited your post to make the difference between code, output from code, and your own words clearer. Please see https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax if you're not familiar with editing text on GitHub.

This worked and required a password entry for the public key. I got around this by cloning on Ubuntu and moving the files to Windows...

**Comment by jameslamb** [comment]
> *and required a password entry for the public key*

There shouldn't be any "public key" or other SSH details used in any part of this process...everything should be using only HTTPS to clone, and shouldn't require any authentication.

Maybe your `git` client is configured to redirect HTTPS remotes to their SSH equivalents with `.insteadOf` entries, like this: https://stackoverflow.com/a/11383587/3986677. You could look in `~/.gitconfig` (I'm not sure what the equivalent is on Windows) to see if you have any entries like that. Or maybe you are using a managed machine from an employer where that's happening automatically, I'm not sure.

But either way, I don't believe this is something LightGBM can change. If your `git` client is rewriting HTTPS remotes to SSH ones, you'll need to create an account on GitLab and add SSH keys to it, following https://docs.gitlab.com/ee/user/ssh.html. Or you'll need to get your `git` client to stop doing that.

**Comment by CRossel87a** [comment]
> > _and required a password entry for the public key_
> 
> There shouldn't be any "public key" or other SSH details used in any part of this process...everything should be using only HTTPS to clone, and shouldn't require any authentication.
> 
> Maybe your `git` client is configured to redirect HTTPS remotes to their SSH equivalents with `.insteadOf` entries, like this: https://stackoverflow.com/a/11383587/3986677. You could look in `~/.gitconfig` (I'm not sure what the equivalent is on Windows) to see if you have any entries like that. Or maybe you are using a managed machine from an employer where that's happening automatically, I'm not sure.
> 
> But either way, I don't believe this is something LightGBM can change. If your `git` client is rewriting HTTPS remotes to SSH ones, you'll need to create an account on GitLab and add SSH keys to it, following https://docs.gitlab.com/ee/user/ssh.html. Or you'll need to get your `git` client to stop doing that.

Alright, thanks so much for all that detailed info!
