### ISSUE TITLE
unclear how to prepare data for `lambdarank_position_bias_regularization` option

### ISSUE THREAD

**Issue by greyowl** [microsoft/LightGBM#6506]
[documentation](https://lightgbm.readthedocs.io/en/latest/Parameters.html#lambdarank_position_bias_regularization)

I want to train a learning to rank model with position bias regularization option(`lambdarank_position_bias_regularization`) turned on. But the documentation is unclear on how the position data needs to be prepared for training.

<img width="1071" alt="image" src="https://github.com/microsoft/LightGBM/assets/10393904/faa4dd5b-a152-4d96-869a-036bcbc6855e">

Can I get a pointer on how to prepare training data with position information? I am planning to use python

**Comment by jameslamb** [comment]
And there are some Python examples in tests:

https://github.com/microsoft/LightGBM/blob/e9a6c798071632f0e9bdf4c5fa2fdf16bfd5eb36/tests/python_package_test/test_engine.py#L727

**Comment by shiyu1994** [comment]
You may use a `.position` file
https://lightgbm.readthedocs.io/en/latest/Advanced-Topics.html#support-for-position-bias-treatment
or you may specify the `position` argument in Python API of `Dataset`
https://lightgbm.readthedocs.io/en/latest/Advanced-Topics.html#support-for-position-bias-treatment
