### ISSUE TITLE
[python-package] using lgb.Booster(model_file='model.txt') hangs when loading gbdt regression model

### ISSUE THREAD

**Issue by myron0330** [microsoft/LightGBM#6513]
I setup a dev environment at ubuntu 20, gcc v9, python 3.9. and install the lightgbm==4.1.0.

when I try to load my model, it hangs from the beginning, can not be interupted and no error being throwed.
I also tried a mini-case as follows, it can not work either. I want to know that is there anything else to do upon training and using a gbdt regression model? How can i debug this problem? Is it related to gcc stuff?

```
import numpy as np
import lightgbm as lgb
from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split

# 生成一些示例数据
X, y = make_regression(n_samples=100, n_features=10, noise=0.1)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 创建数据集
train_data = lgb.Dataset(X_train, label=y_train)

# 设置参数
params = {
    'objective': 'regression',
    'metric': 'rmse',
    'boosting_type': 'gbdt'
}

# 训练模型
bst = lgb.train(params, train_data, num_boost_round=10)

# 保存模型
model_path = 'small_model.txt'
bst.save_model(model_path)

# 加载模型
try:
    bst_loaded = lgb.Booster(model_file=model_path)
    print("Model loaded successfully.")
except Exception as e:
    print(f"Error loading model: {e}")
```

**Comment by myron0330** [comment]
It hungs at 
```
bst = lgb.train(params, train_data, num_boost_round=10)
```

**Comment by jameslamb** [comment]
Thanks for using LightGBM.

If it hands on `lgb.train()`, then I guess the code after that line is not necessary, correct? If so, please remove it from the example.

Can you please share any logs produced by `lightgbm` prior to it "hanging"?

**Comment by myron0330** [comment]
ok, thanks for your help. In fact, i had a model file and i just wanted to load it at beginning. It hanged at "lgb.Booster(model_file=model_path)" when loading, after that i tried the mini-case and it hanged at "lgb.train()". 

By the way, what's the default log path by `lightgbm`? I will try to find more information tonight~

**Comment by jameslamb** [comment]
> By the way, what's the default log path by lightgbm? 

By default, `lightgbm` does not write logs to a file. It writes them directly to standard output (for example, printed in the terminal or the output below an executing Jupyter notebook cell).

**Comment by myron0330** [comment]
I tried to install by sh build and encountered a problem that:
```
CMake Error at /home/myron/opt/anaconda3/lib/python3.9/site-packages/cmake/data/share/cmake-3.29/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES)
Call Stack (most recent call first):
  /home/myron/opt/anaconda3/lib/python3.9/site-packages/cmake/data/share/cmake-3.29/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  /home/myron/opt/anaconda3/lib/python3.9/site-packages/cmake/data/share/cmake-3.29/Modules/FindOpenMP.cmake:581 (find_package_handle_standard_args)
  CMakeLists.txt:178 (find_package)
```

**Comment by myron0330** [comment]
it hangs at after print(1), at code `_safe_call(_LIB.LGBM_BoosterCreateFromModelfile(
                _c_str(str(model_file)),
                ctypes.byref(out_num_iterations),
                ctypes.byref(self._handle)))` 


```
        elif model_file is not None:
            # Prediction task
            out_num_iterations = ctypes.c_int(0)
            print(1)
            _safe_call(_LIB.LGBM_BoosterCreateFromModelfile(
                _c_str(str(model_file)),
                ctypes.byref(out_num_iterations),
                ctypes.byref(self._handle)))
            print(2)
            out_num_class = ctypes.c_int(0)
            _safe_call(_LIB.LGBM_BoosterGetNumClasses(
                self._handle,
                ctypes.byref(out_num_class)))
            print(3)
            self.__num_class = out_num_class.value
            print(4)
            self.pandas_categorical = _load_pandas_categorical(file_name=model_file)
            print(5)
            if params:
                _log_warning('Ignoring params argument, using parameters from model file.')
            params = self._get_loaded_param()
            print(6)
```

**Comment by myron0330** [comment]
maybe it's better for the team to maintain the conda installation with higher versions.

**Comment by jameslamb** [comment]
> *ok, I find the problem. It's because of my numpy, scipy, pandas version is not compatible to the model file.*

Can you please provide **specific** details about this? I don't understand this statement.

You may want to see "How to create a reproducible example" ([link](https://stackoverflow.com/help/minimal-reproducible-example)) for some advice on reporting software problems in a way that others can help confirm and investigate them.
