### ISSUE TITLE
Minor: feature_importance python docstring formatting

### ISSUE THREAD

**Issue by louispotok** [Microsoft/LightGBM#652]
The docstring for the `feature_importance` function in python is formatted wrong. In the "parameters" section of the docstring, each line is being parsed as a separate parameter.

[Code](https://github.com/Microsoft/LightGBM/blob/master/python-package/lightgbm/basic.py#L1651) and [how it looks in the documentation](https://lightgbm.readthedocs.io/en/latest/python/lightgbm.html#lightgbm.Booster.feature_importance)

Compare to the `predict` function which looks okay, I think the explanation just needs to be indented one more time.

**Comment by guolinke** [comment]
@louispotok Thanks, I will fix it directly.
