### ISSUE TITLE
[RFC] Sync supported CUDA versions with a new support policy for CUDA Container Images

### ISSUE THREAD

**Issue by StrikerRUS** [microsoft/LightGBM#6520]
New CUDA **Container Support Policy**: https://gitlab.com/nvidia/container-images/cuda/-/blob/master/doc/support-policy.md and the corresponding tags support table: https://gitlab.com/nvidia/container-images/cuda/-/blob/master/doc/container_tags.pdf.
> After a period of Six Months time, the EOL tags **WILL BE DELETED from Docker Hub and Nvidia GPU Cloud (NGC)**. This deletion ensures unsupported tags (and image layers) are not left lying around for customers to continue using after they have long been abandoned.

The main reason for this RFC is that it will be very hard to support old CUDA versions and debug errors without access to official CUDA image of officially unsupported version.

Our old related RFC about CUDA versions support: #5789 and a PR with upgrades for GPU examples that use CUDA image: #6452.

### What should be done right now to keep CI healthy after `CUDA 13 release + 6 months` date.
> We are announcing the policy change today, but it will not get activated until the next CUDA toolkit major version is released. Then six months after that we will start removing tags.

- `12.2.0` as reached its' EOL should be replaced by `12.2.2`
   https://github.com/microsoft/LightGBM/blob/9a10b19ad833f6dae56349f77b4e2f6c72d3f781/.github/workflows/cuda.yml#L91
- (?) a more recent version (eg. `12.5.0`) should be tested insted of duplicated `11.8.0` one
   https://github.com/microsoft/LightGBM/blob/9a10b19ad833f6dae56349f77b4e2f6c72d3f781/.github/workflows/cuda.yml#L85
   https://github.com/microsoft/LightGBM/blob/9a10b19ad833f6dae56349f77b4e2f6c72d3f781/.github/workflows/cuda.yml#L97

**Comment by jameslamb** [comment]
I'm +1 on this, thanks for writing it up.
