### ISSUE TITLE
tests failed

### ISSUE THREAD

**Issue by celestinoxp** [microsoft/LightGBM#6547]
## Description

I cant use artifacts with latest commit, because tests failed and no build with latest commit

![image](https://github.com/user-attachments/assets/9079aece-9402-46f1-95b9-a68db1983ac9)

All tests should be passed

**Comment by StrikerRUS** [comment]
Hi @celestinoxp ! Thanks a lot for raising this issue. We have already noticed this situation and corresponding bugs are being tracked in #6543 and  #6544. Could you please share your use case for using nightly builds?

**Comment by celestinoxp** [comment]
@StrikerRUS in https://lightgbm.readthedocs.io/en/stable/Installation-Guide.html have a line with direct link:  "You can also download the artifacts of the latest successful build on master branch (nightly builds) here: download artifacts."

It turns out that this link goes to the most recent build, but it only has the build of the commits that pass all the tests... that is, at the time of writing, the last commit that passed the tests was: https://github. com/microsoft/LightGBM/commit/00d6edd2c27710458fec3aa17b12a7d3ef75dcd1 which was 2 weeks ago and there are already 21 new commits after that. So, to use the build with the latest code, I will have to wait for a commit to appear that passes all tests

**Comment by StrikerRUS** [comment]
@celestinoxp Thank you for clarification!
Do you just always use the latest code of any package or you need just a build of LightGBM with a recently included commit?

**Comment by celestinoxp** [comment]
@StrikerRUS I like to use the latest code when there are bug fixes, in this case I would like to use the fix made at https://github.com/microsoft/LightGBM/commit/2bc3ab86b78e6904da49a1053219695f83c2d21e because on my notebook I get a lot of boring logs, and when it comes to with large notebooks, it is impossible.
I don't use lightgbm directly, I use pycaret because it automatically pre-processes the data... in my case, I'm doing some tests with datasets with many columns, so it makes it easier.
But pycaret also uses lightgbm for feature selection.

**Comment by StrikerRUS** [comment]
@celestinoxp Got it! Thanks a lot for sharing your scenario of using nightly builds.
