### ISSUE TITLE
Roadmap link does not work on the CONTRIBUTING.md file

### ISSUE THREAD

**Issue by JAroyan** [microsoft/LightGBM#6556]
Hi,
on the CONTRIBUTING.md file the link "Roadmap" does not work.
https://github.com/microsoft/LightGBM/blob/master/CONTRIBUTING.md
![image](https://github.com/user-attachments/assets/574faf17-edc9-46ea-b770-082a8c61a2f5)

**Comment by jameslamb** [comment]
Thanks very much for reporting this! We'll remove that link.

I believe it's left over from a brief period where Microsoft had assigned a Product Manager to LightGBM. We don't maintain a public roadmap (with sequencing, priority, or due dates)... at this point, the work is very self-directed.

You can see #2302 for a list of all feature requests.
