### ISSUE TITLE
How to Use lightGBM in CPP Project ? 

### ISSUE THREAD

**Issue by jiang1406124224** [Microsoft/LightGBM#657]
Please search your question on previous issues, stackoverflow or other search engines before you open a new one.

For bugs and unexpected issues, please provide following information, so that we could reproduce on our system.

## Environment info
Operating System:
CPU:
C++/Python/R version:

## Steps to reproduce

1.
2.
3.

**Comment by guolinke** [comment]
1. just include all codes of LightGBM to your project.
2. compile the library, and use our c_api interface:  https://github.com/Microsoft/LightGBM/blob/master/include/LightGBM/c_api.h
