### ISSUE TITLE
gpu support osx

### ISSUE THREAD

**Issue by geoHeil** [Microsoft/LightGBM#658]
What about gnu support on OS X? https://github.com/Microsoft/LightGBM/wiki/Installation-Guide does not mention it. I believe e-gpus will become popular. It would be great to see gpu support on OS X as well.

**Comment by guolinke** [comment]
@geoHeil 
We doesn't have a osx gpu machine to test. 
But I think the process is similar to the linux: https://github.com/Microsoft/LightGBM/wiki/Installation-Guide#linux-2

**Comment by Laurae2** [comment]
@guolinke Travis provides support for Mac OSX, but we need someone who knows Mac to set it up correctly.

**Comment by Laurae2** [comment]
Refer to #667
