### ISSUE TITLE
Package about LIghtgbm_GPU

### ISSUE THREAD

**Issue by Zhongli2002** [microsoft/LightGBM#6584]
Hi! When I try to download the python package following the introduction, I fail to find setup.py.I don not kown how to successfully make the python package. Now ,i have successfully finish these steps:

```shell
git clone --recursive https://github.com/Microsoft/LightGBM`
cd LightGBM
mkdir build ; cd build
cmake -DUSE_GPU=1 ..
# if you have installed the NVIDIA OpenGL, please using following instead
# sudo cmake -DUSE_GPU=1 -DOpenCL_LIBRARY=/usr/local/cuda/lib64/libOpenCL.so -OpenCL_INCLUDE_DIR=/usr/local/cuda/include/ ..
make -j$(nproc)
```

I'm really sorry to bother you. I would like to try the GPU version of lightgbm for experimentation and learning.

**Comment by jameslamb** [comment]
Thanks for using LightGBM.

I've reformatted your post to make the difference between code and your own words clearer. You may find this helpful for doing such formatting yourself in the future: https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax.

> *I fail to find setup.py*

`lightgbm` (the Python package for LightGBM) removed its `setup.py` about 1.5 years ago, in #5837.

The most complete information about installing `lightgbm` is available at https://github.com/microsoft/LightGBM/tree/master/python-package.

But I can help tell you exactly what to do. Please provide enough information for us to help you:

* what operating system? (macOS, Linux, Windows?)
* what type of GPU do you have?
* is it OK to use the latest **release** of LightGBM? Or do you want to be able to build the latest development version?

**Comment by Zhongli2002** [comment]
Dear James Lamb:
&nbsp; &nbsp; I hope this email finds you well. Firstly, I would like to express my gratitude for the valuable information you have provided about GitHub writing. It has been very helpful.&nbsp;
&nbsp; &nbsp; I am reaching out to seek your assistance regarding the use of LightGBM.&nbsp;&nbsp;I have been using the CPU version of LightGBM for my computations, but I find the processing time to be quite extensive. To address this, I am considering leveraging my GPU to accelerate the computations.Here is some context about my setup :&nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 1. Operating System: Linux
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 2. GPU: NVIDIA RTX 3090 (24GB)&nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 3. It is OK for me to use the latest version of LightGBM with GPU support.&nbsp;
&nbsp; &nbsp; Thank you once again for your support and assistance. I look forward to your response.&nbsp;
Best regards.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "microsoft/LightGBM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月2日(星期五) 中午12:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [microsoft/LightGBM] Package about LIghtgbm_GPU (Issue #6584)





 
Thanks for using LightGBM.
 
I've reformatted your post to make the difference between code and your own words clearer. You may find this helpful for doing such formatting yourself in the future: https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax.
  
I fail to find setup.py
  
lightgbm (the Python package for LightGBM) removed its setup.py about 1.5 years ago, in #5837.
 
The most complete information about installing lightgbm is available at https://github.com/microsoft/LightGBM/tree/master/python-package.
 
But I can help tell you exactly what to do. Please provide enough information for us to help you:
  
what operating system? (macOS, Linux, Windows?)
 
what type of GPU do you have?
 
is it OK to use the latest release of LightGBM? Or do you want to be able to build the latest development version?

**Comment by jameslamb** [comment]
Ok great! Then the easiest way to do this will be to just use `conda-forge`.

You can install `conda` (if you don't have it locally) by following the instructions from https://github.com/conda-forge/miniforge?tab=readme-ov-file#unix-like-platforms-mac-os--linux.

Then run the following:

```shell
conda install -c conda-forge 'lightgbm>=4.4.0'
```

That should give you a GPU-enabled version of `lightgbm`. In your code, use `"device": "cuda"`, like this:

```python
import lightgbm as lgb
from sklearn.datasets import make_regression

X, y = make_regression()
dtrain = lgb.Dataset(X, label=y, params={"device": "cuda"})
model = lgb.train(
    params={
        "objective": "regression",
        "device": "cuda"
    },
    train_set = dtrain
)
```
