### ISSUE TITLE
MAE objective function

### ISSUE THREAD

**Issue by binga** [Microsoft/LightGBM#66]
Hi,
For regression problems, the objective function typically used is RMSE. However, if the evaluation metric is MAE, there have good discussions on Kaggle on modifying the objective function. Reference: https://www.kaggle.com/c/allstate-claims-severity/forums/t/24520/effect-of-mae. Is there any way to use a custom objective function in LightGBM?
Thank you.

**Comment by guolinke** [comment]
@binga , we are working on c_api and python/R package. The custom objective will be supported in python and R package.
You also can directly change the code to add self-defined objective function.

**Comment by binga** [comment]
Looking forward to it. Thank you.

**Comment by kkimdev** [comment]
Can we have this issue open meantime to track the progress?

**Comment by Laurae2** [comment]
@kkimdev fixed already in https://github.com/Microsoft/LightGBM/pull/180 and https://github.com/Microsoft/LightGBM/pull/178 - or, use your own custom objective using the API (straightforward in R/Python).

**Comment by kkimdev** [comment]
Great, thanks!

**Comment by kkimdev** [comment]
@Laurae2 Is python custom objective function API documented anywhere? I can't find it... And looks like the available objective functions are hard-coded in the cpp file? https://github.com/Microsoft/LightGBM/blob/master/src/objective/objective_function.cpp
