### ISSUE TITLE
[Question] predict_leaf_index = true

### ISSUE THREAD

**Issue by wil70** [microsoft/LightGBM#6615]
Hello, 
I have a question about indexes with predict_leaf_index = true.
This model has 5 classes (class_1 to class_5). The model was made after 4 iterations, so 20 trees.
I gave the model an input and here is the prediction it did
`1.015255231935523e-15	1.015255231935523e-15	0.18041775027339391	0.58236594870204317	0.23721630102456087`
so it means "classe_4" is the choosen one 

I also asked for the index
`0	0	0	81	4	0	0	104	101	106	0	0	116	80	52	0	0	107	50	4`
so I get 20 indexes as expected (4 iteration x 5 classes)
So I'm guessing `116	80	52	0` are the indexes of class_4 for iteration 1 to 4
Are my assumptions correct?

Thanks
--w

**Comment by jameslamb** [comment]
Thanks for using LightGBM.

When you ask questions here, please clarify which LightGBM API you're talking about (CLI? Python? R?). I know by context from your other recent posts that you are probably talking about the CLI, but someone finding this from a search engine would not know that.

The `pred_leaf` outputs are ordered by **iteration**, and then in order by *class* within iteration's results.

So the leaf node indices for predicting class 4 (the fourth class, using 1-based indexing as your original post did) are:

```text
iteration 1: 81
iteration 2: 101
iteration 3: 80
iteration 4: 50
```

For more discussion, see these:

* #5223
* #5384

Sorry this is not clearer in the documentation, we should improve that. I also encourage you to try using small datasets and shallow models to experiment a bit and investigate what LightGBM is doing. I found this very helpful in https://github.com/microsoft/LightGBM/issues/5223#issuecomment-1188602396, for example.

**Comment by wil70** [comment]
Thanks!
