### ISSUE TITLE
[Python]Error Regression:Stopped training because there are no more leaves that meet the split requirements.

### ISSUE THREAD

**Issue by asking28** [Microsoft/LightGBM#663]
```
`X_train,X_test,Y_train,Y_test=train_test_split(data,Y,test_size=0.2,random_state=seed)
Y_train=Y_train.tolist()
X_train=X_train.tolist()
X_test=X_test.tolist()
Y_test=Y_test.tolist()

lgb_train=lgb.Dataset(X_train,Y_train)
lgb_test=lgb.Dataset(X_test,Y_test,reference=lgb_train)
params={
'task':'train',
'objective':'regression_l1',
'boosting':'gbdt',
'num_leaves':10,
'learning_rate':0.05,
'metric':'l1',
'feature_fraction':0.9,
'bagging_fraction':0.8,
'bagging_freq':5,
'verbose':0

}
print('start training')
gbm=lgb.train(params,lgb_train,num_boost_round=20,valid_sets=lgb_test,early_stopping_rounds=5)
preds=gbm.predict(X_test,num_iteration=gbm.best_iteration)
mae=metrics.mean_absolute_error(Y_test,preds)
print(mae)`
```
This is my code snippet. I am trying to predict so value using these parameters and it throws error before completing first round.
Error is -start training
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements.
[1]     valid_0's l1: 6.88414e+06
What is the possible cause of this error. And how can it be fixed?

**Comment by guolinke** [comment]
@asking28 
This is not a error. It is warning that you data cannot be learned by tree algorithm.

possible reasons: 1. your data is too small. 2. your data is very random, cannot learn trees from it.

you can try the ```min_data=1``` .
