### ISSUE TITLE
[python-package] Using sparse features with CUDA is currently not supported.

### ISSUE THREAD

**Issue by OrangeAoo** [microsoft/LightGBM#6631]
## Description
I got the following warnings when setting `device_type='cuda'`
```python
 [Warning] Using sparse features with CUDA is currently not supported.
 [Fatal] CUDA Tree Learner was not enabled in this build.
Please recompile with CMake option -DUSE_CUDA=1
```
## Reproducible example

```python
## Train-test split 
# X_train.shape==(18840083, 3), y_train.shape==(18840083,1)
# X_val.shape==(2379462, 3), y_val.shape==(2379462, 1)

## parameters 
params = {
    'learning_rate': 0.01,
    'metric':'mse',
    'max_bin':63,
    'max_depth':15,
    'num_leaves':10000,
    'gpu_use_dp':True,
    'n_estimators':750,
    'tree_type':'data_parallel',
    'device_type':'cuda',
    'n_jobs':-1,
    'verbose':1
}

## Train 
start=time.time()
LGBmodel = lgb.LGBMRegressor(**params)
LGBmodel.fit(X_train,y_train,eval_set=[(X_val,y_val)])  
print(f"Training LGBoost completed in {time.time()-start:.4f} seconds!")
```

**Comment by jameslamb** [comment]
Thanks for using LightGBM.

That warning is expected, but the **error** means you haven't installed a CUDA-enabled build of LightGBM. To install a CUDA-enabled build of LightGBM, follow the instructions in the docs:

* `pip`: https://github.com/microsoft/LightGBM/blob/master/python-package/README.rst#build-cuda-version
* `conda` (preferred): https://github.com/microsoft/LightGBM/blob/master/python-package/README.rst#install-from-conda-forge-channel

**Comment by Zaffer** [comment]
using `pip install lightgbm --config-settings=cmake.define.USE_CUDA=ON` does not fix this issue. It simply returns the same error. I tried purging the pip cache and using `-no-cache-dir`, but still does nothing.

**Comment by jameslamb** [comment]
@Zaffer if you can provide the complete logs from running that command, we can help you. I strongly suspect there's an error in those logs somewhere, or maybe a warning where `pip` is refusing to update your already-installed `lightgbm`.

**Comment by StrikerRUS** [comment]
@Zaffer Could you please try the following command?
```
pip install lightgbm --no-binary lightgbm --config-settings=cmake.define.USE_CUDA=ON
```
I guess instructions in the README document are incorrect. Without `--no-binary` flag `pip` doesn't try to build from sources but simply installs precompiled wheel file regardless specified `--config-settings` flags.

**Comment by jameslamb** [comment]
Oh wow, thanks @StrikerRUS ! I could *swear* that it used to be the case that if you passed `--config-settings`, `pip` would automatically try to download a source distribution and build from source.

But I tested that tonight with a couple of different versions of `pip` and couldn't reproduce it, so maybe I'm misremembering.

If there are any places in the docs that have `pip install --config-settings ...` without `--no-binary lightgbm`, I'd support a PR adding that `--no-binary lightgbm`.

**Comment by StrikerRUS** [comment]
@jameslamb 
Already on the way: #6767.

**Comment by jameslamb** [comment]
Oh great, thanks!
