### ISSUE TITLE
Is the function "LGBM_BoosterPredictForMat" thread safe?

### ISSUE THREAD

**Issue by zhxwmessi** [Microsoft/LightGBM#666]
Is the function "LGBM_BoosterPredictForMat" in c_api  thread safe ? If I call this function to predict with multi thread. Since Xgboost predict function is not thread safe

**Comment by guolinke** [comment]
@zhxwmessi 
1. The prediction is already multi-threading. 
2. If using the different model, it is thread-safe.
3. if using the same model but with the same number of iterations, it is thread-safe.

**Comment by ameyais** [comment]
@guolinke 
> 1. The prediction is already multi-threading.
> 2. If using the different model, it is thread-safe.
> 3. if using the same model but with the same number of iterations, it is thread-safe.

I want to remove the lock, because I want to use predict with multi thread to speed up
If I remove the lock, is it still thread safe under situation 3?

**Comment by l616q** [comment]
> @guolinke
> 
> > 1. The prediction is already multi-threading.
> > 2. If using the different model, it is thread-safe.
> > 3. if using the same model but with the same number of iterations, it is thread-safe.
> 
> I want to remove the lock, because I want to use predict with multi thread to speed up
> If I remove the lock, is it still thread safe under situation 3?

hi, have you remove lock and can get the right predict result?

**Comment by guolinke** [comment]
@ameyais it is thread-safe.

**Comment by l616q** [comment]
@guolinke Is there a possible way to rewrite the predict function to make the prediction more faster?except delete this lock.

**Comment by guolinke** [comment]
@l616q refer to https://github.com/dmlc/treelite
LightGBM is designed for the training.
