### ISSUE TITLE
[Python] memory leak after training

### ISSUE THREAD

**Issue by fo40225** [Microsoft/LightGBM#668]
## Environment info
Operating System: Windows 10 1703
CPU: Intel Xeon E3-1230v2
GPU: Geforce GTX 780ti 3GB (Driver 382.05)
C++/Python version:
Cmake 3.7.2
Visual Studio 2015 Update 3
Boost 1.64 lib64-msvc-14.0
CUDA 8.0.61
Python 3.6.0 64bit (Anaconda 4.3.0.1)
LightGBM 2.0.4 with GPU by pip

## Error Message:
    ---------------------------------------------------------------------------
    LightGBMError                             Traceback (most recent call last)
    <ipython-input-2-70f7c6bbbc9d> in <module>()
         18                        early_stopping_rounds=250,
         19                        verbose_eval=False,
    ---> 20                        seed=seed
         21                       )
         22     num_boost_rounds = len(cv_output['rmse-mean'])
    
    C:\Users\User\Anaconda3\lib\site-packages\lightgbm\engine.py in cv(params, train_set, num_boost_round, folds, nfold, stratified, shuffle, metrics, fobj, feval, init_model, feature_name, categorical_feature, early_stopping_rounds, fpreproc, verbose_eval, show_stdv, seed, callbacks)
        405                                     end_iteration=num_boost_round,
        406                                     evaluation_result_list=None))
    --> 407         cvfolds.update(fobj=fobj)
        408         res = _agg_cv_result(cvfolds.eval_valid(feval))
        409         for _, key, mean, _, std in res:
    
    C:\Users\User\Anaconda3\lib\site-packages\lightgbm\engine.py in handlerFunction(*args, **kwargs)
        220             ret = []
        221             for booster in self.boosters:
    --> 222                 ret.append(getattr(booster, name)(*args, **kwargs))
        223             return ret
        224         return handlerFunction
    
    C:\Users\User\Anaconda3\lib\site-packages\lightgbm\basic.py in update(self, train_set, fobj)
       1368             _safe_call(_LIB.LGBM_BoosterUpdateOneIter(
       1369                 self.handle,
    -> 1370                 ctypes.byref(is_finished)))
       1371             self.__is_predicted_cur_iter = [False for _ in range_(self.__num_dataset)]
       1372             return is_finished.value == 1
    
    C:\Users\User\Anaconda3\lib\site-packages\lightgbm\basic.py in _safe_call(ret)
         45     """
         46     if ret != 0:
    ---> 47         raise LightGBMError(_LIB.LGBM_GetLastError())
         48 
         49 
    
    LightGBMError: b'Memory Object Allocation Failure'

## Reproducible examples
    # Create the dataset
    from sklearn.datasets.samples_generator import make_regression  
    
    X, Y = make_regression(n_samples=50000, n_features=300)
    seed = 42
    
    import lightgbm as lgb
    
    lgb_params = {
        'application': 'regression',
        'learning_rate':0.1,
        'device':'gpu', # video memory leak
        #'device':'cpu', # main memory leak
        'metric':'rmse'
    }
    
    train_data = lgb.Dataset(X,Y)
    models = []
    for i in range(1,1000):
        
        cv_output = lgb.cv(lgb_params, train_data,
                           num_boost_round=1,
                           nfold=4,
                           shuffle=True,
                           early_stopping_rounds=250,
                           verbose_eval=False,
                           seed=seed
                          )
        num_boost_rounds = len(cv_output['rmse-mean'])
        
        model=lgb.train(lgb_params, train_data,
                        num_boost_round=num_boost_rounds)
        
        # memory leak workaround 
        #model.save_model('temp.txt')
        #model = lgb.Booster(model_file='temp.txt')
        
        models.append(model)
    
    import xgboost as xgb
    
    xgb_params = {
        'eta': 0.06,
        'objective': 'reg:linear',
        'eval_metric': 'rmse'
    }
    
    d_matrix = xgb.DMatrix(X,Y)
    models = []
    for i in range(1,1000):
        cv_output = xgb.cv(xgb_params, d_matrix,
                           num_boost_round=1,
                           nfold=4,
                           early_stopping_rounds=250,
                           verbose_eval=False,
                           seed=seed
                          )
        
        num_boost_rounds = len(cv_output)
        
        model = xgb.train(xgb_params, d_matrix,
                          num_boost_round=num_boost_rounds)
        
        models.append(model)

## Steps to reproduce
1. The video memory didn't release after training, if use cpu, main memory leak.
2. xgb have no problem in this situation.

**Comment by guolinke** [comment]
can you provide the log of memory leak?
your log seem is gpu error.

**Comment by fo40225** [comment]
when gpu error occurred, the video memory usage is full.
if change setting to use cpu, it can obsessed the python.exe memory usage is grow up.

**Comment by guolinke** [comment]
@fo40225 
I think the root reason is ```models.append(model)```.  The ```booster``` will use some temporary memory for the training, and we cannot free this memory automatically since we cannot know whether training is finished or not. So your workaround solution is right, it will free all temporary memory.

@wxchan 
Can we add a function in Booster to free the old booster handle, then load the new one from the model string?

**Comment by fo40225** [comment]
Is it not the end of the training process when the lgb.train or lgb.cv returns?

It shouldn't have lazy evaluation problem here.

**Comment by guolinke** [comment]
@fo40225 The training is performed by calling this: https://github.com/Microsoft/LightGBM/blob/master/python-package/lightgbm/basic.py#L1336 .
And lgb.train and lgb.cv is only a wrapper to call this function. So from the view of Booster, we cannot know when is the training end. 

I want to add parameter ```keep_training_booster``` to ```lgb.train```. if ```keep_training_booster``` is false, we can free the training Booster object, and convert it to a prediction Booster. @wxchan Do you think it is okay ?

**Comment by wxchan** [comment]
@guolinke it's ok, but I think perhaps users won't use Booster to keep training, they can always use a Predictor as init model for continue training.

**Comment by guolinke** [comment]
@wxchan okay, so we can set default value of ```keep_training_booster``` to ```False```. 
Can you help to this change ?

**Comment by wxchan** [comment]
@guolinke I am not sure I have time before this weekend.

**Comment by wxchan** [comment]
@guolinke I can do it later tonight.

**Comment by guolinke** [comment]
@wxchan Thanks, any updates?
