### ISSUE TITLE
not able to set num_threads using c_api interface

### ISSUE THREAD

**Issue by niehui1983** [Microsoft/LightGBM#669]
Hi, I am using lightgbm c_api interface, and not able to set num_threads. The program will also run with the max of avaiable cpus. Instead, I would like to run it in only one cpu. I am running it with c++ under linux system. Below is the sample code

{
......

//initialize model from a file
int suc = LGBM_BoosterCreateFromModelfile(_modelFile.c_str(),&_out_num_iterations, &_out);

//set num_threads as 1
const char * param = "num_threads=1 ";
int suc2 = LGBM_BoosterResetParameter(_out, param);

............

//make prediction
int suc2 = LGBM_BoosterPredictForMat(_out,data,C_API_DTYPE_FLOAT64,n1,n2,1,C_API_PREDICT_NORMAL,_out_num_iterations,"num_threads=1 ",&out_len,out_result);

......
}

Could someone please let me know why the program is not running with one cpu? And what is the correct way to do it? Thanks.

Sincerely,
Hui 

Please search your question on previous issues, stackoverflow or other search engines before you open a new one.

For bugs and unexpected issues, please provide following information, so that we could reproduce on our system.

## Environment info
Operating System:
CPU:
C++/Python/R version:

## Steps to reproduce

1.
2.
3.

**Comment by guolinke** [comment]
It is very strange. From your code, the number of threads should be set.

can you try to use ```omp_set_num_threads(1);``` ? (need to include "omp.h")

**Comment by niehui1983** [comment]
Hi @guolinke,

Thanks for your quick response. I tested what your described. This is what command "ps -fTP" outputs:
UID          PID    SPID    PPID PSR  C STIME TTY          TIME CMD
hnie     3980609 3980609 3356829  22 99 09:34 pts/0    00:03:06 ./binary -p config
hnie     3980609 3980610 3356829  25  0 09:34 pts/0    00:00:00 ./binary -p config
hnie     3980609 3980611 3356829  17  0 09:34 pts/0    00:00:00 ./binary -p config
hnie     3980609 3980612 3356829  26  0 09:34 pts/0    00:00:00 ./binary -p config
hnie     3980609 3980613 3356829   2  0 09:34 pts/0    00:00:00 ./binary -p config
hnie     3980609 3980614 3356829  27  0 09:34 pts/0    00:00:00 ./binary -p config
hnie     3980609 3980615 3356829  19  0 09:34 pts/0    00:00:00 ./binary -p config
hnie     3980609 3980616 3356829  28  0 09:34 pts/0    00:00:00 ./binary -p config
hnie     3980609 3980617 3356829  20  0 09:34 pts/0    00:00:00 ./binary -p config
hnie     3980609 3980618 3356829  29  0 09:34 pts/0    00:00:00 ./binary -p config
hnie     3980609 3980619 3356829  21  0 09:34 pts/0    00:00:00 ./binary -p config
hnie     3980609 3980620 3356829  30  0 09:34 pts/0    00:00:00 ./binary -p config
hnie     3980609 3980621 3356829  22  0 09:34 pts/0    00:00:00 ./binary -p config
hnie     3980609 3980622 3356829  31  0 09:34 pts/0    00:00:00 ./binary -p config
hnie     3980609 3980623 3356829  23  0 09:34 pts/0    00:00:00 ./binary -p config
hnie     3980609 3980624 3356829  24  0 09:34 pts/0    00:00:00 ./binary -p config
hnie     3980609 3980625 3356829  16  0 09:34 pts/0    00:00:00 ./binary -p config
hnie     3980609 3980626 3356829   8  0 09:34 pts/0    00:00:00 ./binary -p config
hnie     3980609 3980627 3356829   1  0 09:34 pts/0    00:00:00 ./binary -p config
hnie     3980609 3980628 3356829  16  0 09:34 pts/0    00:00:00 ./binary -p config
hnie     3980609 3980629 3356829   9  0 09:34 pts/0    00:00:00 ./binary -p config
hnie     3980609 3980630 3356829   3  0 09:34 pts/0    00:00:00 ./binary -p config
hnie     3980609 3980631 3356829  10  0 09:34 pts/0    00:00:00 ./binary -p config
hnie     3980609 3980632 3356829   4  0 09:34 pts/0    00:00:00 ./binary -p config
hnie     3980609 3980633 3356829  11  0 09:34 pts/0    00:00:00 ./binary -p config
hnie     3980609 3980634 3356829   5  0 09:34 pts/0    00:00:00 ./binary -p config
hnie     3980609 3980635 3356829  12  0 09:34 pts/0    00:00:00 ./binary -p config
hnie     3980609 3980636 3356829   6  0 09:34 pts/0    00:00:00 ./binary -p config
hnie     3980609 3980637 3356829  13  0 09:34 pts/0    00:00:00 ./binary -p config
hnie     3980609 3980638 3356829   7  0 09:34 pts/0    00:00:00 ./binary -p config
hnie     3980609 3980639 3356829  14  0 09:34 pts/0    00:00:00 ./binary -p config
hnie     3980609 3980640 3356829  18  0 09:34 pts/0    00:00:00 ./binary -p config

It seems that only the first line has the non-zero running time "00:03:06", which probably means it is running on this threads. All others have 0. But it seems that the job still reaches all cpus, even if running time is 0. Is it by design? If not, is there a way that I could only run this job on one pre-specified cpu?

Thanks.

Sincerely,
Hui

**Comment by guolinke** [comment]
@niehui1983 
We use openmp for the multi-threading, I think it may is the feature of openmp.

**Comment by niehui1983** [comment]
@guolinke'

Yeah, it could be the case.
