### ISSUE TITLE
[python-package]  Question for lgb.reset_parameter

### ISSUE THREAD

**Issue by yanrudan** [microsoft/LightGBM#6708]
My code is:
```
from lightgbm import LGBMRegressor

def train(train_x, train_y, train_w, objective, alpha, metric, lr, num_leaves, n_estimators):
    print('Train model')
    if 'quantile' in objective:
        lightgbm = LGBMRegressor(boosting_type='gbdt', objective=objective, metric=metric, alpha=alpha, random_state=0, learning_rate=lr, num_leaves=num_leaves, n_estimators=n_estimators)
    else:
        lightgbm = LGBMRegressor(boosting_type='gbdt', objective=objective, metric=metric, random_state=0, learning_rate=lr, num_leaves=num_leaves, n_estimators=n_estimators)
    model = lightgbm.fit(train_x, train_y, train_w, eval_set=[(train_x, train_y)], eval_metric='mae',
        callbacks=[
            lgb.early_stopping(stopping_rounds=20, verbose=True),
            lgb.log_evaluation(),
            lgb.reset_parameter(learning_rate=lambda i: lr - 0.0003*i)
            ])
    return model

```
I want to know if the parameter `i` in the **lambda** function is automatically assigned the current training iteration. Can `i` be replaced with any other string such as `iter`, `m` and so on?

**Comment by jameslamb** [comment]
> Can i be replaced with any other string such as iter, m and so on?

You can name it anything you want. The iteration number is passed positionally.

https://github.com/microsoft/LightGBM/blob/8d5dca2e3a6181ba788f8aa3d7a69d08e9d0ea07/python-package/lightgbm/callback.py#L232

Did you run into some issue when you tested this, or are you just asking? If just asking... please do try testing things yourself before opening issues here.

**Comment by yanrudan** [comment]
Thank you for the reply. I will try more next time...:)
