### ISSUE TITLE
[Python] How to suppress Info messages during cross-validation?

### ISSUE THREAD

**Issue by alexander-rakhlin** [Microsoft/LightGBM#671]
Hello all,

Is there way to suppress Info messages during cross-validation? verbosity level in params and in lgb.cv call makes no difference. LightGBM version '2.0.1' was installed via pip

> [6]	cv_agg's binary_logloss: 0.67779
> [LightGBM] [Info] Trained a tree with leaves=95 and max_depth=13
> [LightGBM] [Info] Trained a tree with leaves=95 and max_depth=13
> [LightGBM] [Info] Trained a tree with leaves=95 and max_depth=14
> [LightGBM] [Info] Trained a tree with leaves=95 and max_depth=12
> [LightGBM] [Info] Trained a tree with leaves=95 and max_depth=12

**Comment by guolinke** [comment]
@wxchan Is it a bug?

**Comment by wxchan** [comment]
@guolinke look like some bug. The params are set 3 times in c_api and is wrong last time. Not sure the reason now.

**Comment by alexander-rakhlin** [comment]
Thank you, this patch sets params in subset(...) as intended, however this does not stop multiple messages:

> [LightGBM] [Warning] Unknown parameter categorical_column=
> [LightGBM] [Warning] Unknown parameter categorical_column=
> [LightGBM] [Warning] Unknown parameter categorical_column=
> [LightGBM] [Info] Number of positive: 27984, number of negative: 28017
> [LightGBM] [Info] Total Bins 967
> [LightGBM] [Info] Number of data: 56001, number of used features: 14
> [LightGBM] [Warning] Unknown parameter categorical_column=
> [LightGBM] [Info] No further splits with positive gain, best gain: -inf
> [LightGBM] [Info] Trained a tree with leaves=32 and max_depth=5
> [LightGBM] [Info] No further splits with positive gain, best gain: -inf
> [LightGBM] [Info] Trained a tree with leaves=31 and max_depth=5
> [LightGBM] [Info] No further splits with positive gain, best gain: -inf
> [LightGBM] [Info] Trained a tree with leaves=31 and max_depth=5
> [LightGBM] [Info] No further splits with positive gain, best gain: -inf
> [LightGBM] [Info] Trained a tree with leaves=31 and max_depth=5
> [LightGBM] [Info] No further splits with positive gain, best gain: -inf
> [LightGBM] [Info] Trained a tree with leaves=32 and max_depth=5
> [LightGBM] [Info] No further splits with positive gain, best gain: -inf
> [LightGBM] [Info] Trained a tree with leaves=32 and max_depth=5
> [LightGBM] [Info] No further splits with positive gain, best gain: -inf


I have "verbosity": -1 in params
```
param = {
    "objective": "binary",
    "metric": ["binary_error", "binary_logloss"],
    "verbosity": -1,
```

**Comment by wxchan** [comment]
@alexander-rakhlin I see, you can use "verbose" instead of "verbosity", it will work. The reason is, there is another argument called "silent" which has higher priority, I will fix this later.

**Comment by alexander-rakhlin** [comment]
@wxchan thank you, "verbose" works!
There are few warning in the beginning, but they do not disturb much

> [Warning] Unknown parameter categorical_column=

**Comment by wxchan** [comment]
@alexander-rakhlin how do you set categorical_column? empty list?

**Comment by alexander-rakhlin** [comment]
@wxchan this parameter left default ('auto'?)

**Comment by wxchan** [comment]
@alexander-rakhlin ok, I know the reason. The categorical_column is set to empty list when input is pandas.DataFrame, you can use .values to use numpy as input to remove this warning.

**Comment by dwy904** [comment]
The output message is still here and I have tried both.

**Comment by guolinke** [comment]
@dwy904 please try the latest master branch
