### ISSUE TITLE
[python-package] Refit does not work for regression (Python API)

### ISSUE THREAD

**Issue by bhvieira** [microsoft/LightGBM#6737]
## Description
Refit does not work for regression (Python API)

## Reproducible example

```python
import lightgbm as lgb
import numpy as np
import pandas as pd

# Generate synthetic data
np.random.seed(42)
X_train = np.random.rand(100, 5)  # Training features
y_train = X_train @ np.array([1.5, -2.0, 1.0, 0.5, -1.0]) + np.random.normal(scale=0.1, size=100)  # Training targets

# Prepare data for LightGBM
train_data = lgb.Dataset(X_train, label=y_train)

# Define training parameters
params = {
    "objective": "regression",
    "verbosity": -1,
}

# Train the model
print("Training initial model...")
model = lgb.train(
    params,
    train_data,
    num_boost_round=1,
)

# Generate new data for refitting
X_new = np.random.rand(60, 5)  # New training features
y_new = X_new @ np.array([1.5, -2.0, 1.0, 0.5, -1.0]) + np.random.normal(scale=0.1, size=60)  # New training targets

# Refit the model
print("Refitting the model with new data...")
model_refit = model.refit(X_new, y_new)
# ValueError: not enough values to unpack (expected 2, got 1)
```

## Environment info

LightGBM version or commit hash:

Command(s) you used to install LightGBM

```shell
poetry add lightgbm
```

name = "lightgbm"
version = "4.3.0"
description = "LightGBM Python Package"
category = "main"
optional = false
python-versions = ">=3.6"

**Comment by jameslamb** [comment]
Thanks for using LightGBM and for the clear report. This definitely looks like a bug!

Here's a smaller reproducible example, and logs with traceback showing the location of the error.

```python
import lightgbm as lgb
from sklearn.datasets import make_regression

X, y = make_regression(n_samples=10_000, n_features=10)

dtrain = lgb.Dataset(X, label=y)

model = lgb.train(
    params={
        "objective": "regression",
        "verbosity": -1
    },
    train_set=dtrain,
    num_boost_round=1,
)

model_refit = model.refit(X, y)
```

> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jlamb/miniforge3/envs/lgb-dev/lib/python3.11/site-packages/lightgbm/basic.py", line 4866, in refit
    nrow, ncol = leaf_preds.shape
    ^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)

That's comine from here:

https://github.com/microsoft/LightGBM/blob/d4d6c87db02a146ac6dc04b00f538e02a3b22250/python-package/lightgbm/basic.py#L4874

I'm not sure how we haven't caught this before... this project has tests on `Booster.refit()` for regression models:

https://github.com/microsoft/LightGBM/blob/d4d6c87db02a146ac6dc04b00f538e02a3b22250/tests/python_package_test/test_engine.py#L3684

**Comment by jameslamb** [comment]
@bhvieira can you share here the output of running `pip freeze` (or whatever the `poetry` equivalent is)? I'm curious to see what version of `numpy` you have.

**Comment by bhvieira** [comment]
@jameslamb I have the whole poetry lock file, but it's quite long for my current project.

```
[[package]]
name = "numpy"
version = "1.26.4"
description = "Fundamental package for array computing in Python"
category = "main"
optional = false
python-versions = ">=3.9"
```

**Comment by RektPunk** [comment]
I think the issue might be with `pred_leaf`. It seems like the number of trees is too small, so the condition https://github.com/microsoft/LightGBM/blob/b33a12ea3883f306388e69f12ceb421b1ee7ec29/python-package/lightgbm/basic.py#L1251-L1253 wasn’t satisfied, which caused the problem with the shape. 
I believe modifying the if condition such as 
```python
if not is_sparse and preds.size != nrow or pred_leaf: 
```
could fix it. Would it be okay if I give it a try?

**Comment by jameslamb** [comment]
Thanks for that... sure!

When you put up a pull request, place include a minimal unit test that would fail without your fix, to be sure we don't reintroduce this bug in the future.

**Comment by RektPunk** [comment]
Thanks @jameslamb. I’ve created the PR and also added a simple test :).
