### ISSUE TITLE
Installation fails on Windows 10/R 3.4.1/Visual Studio 15 2017

### ISSUE THREAD

**Issue by janamejaya** [Microsoft/LightGBM#675]
Hi all,

I am unable to install LightGBM with R. 
Although I have tried several approaches for LightGBM/R-package installation, this post is specifically for installation with RStudio.
Please advise.

## Environment info
C compiler: Visual Studio 15 2017
Rtools: version 3.4 (64 bit only)
Cmake: version 3.9.0-rc5

R and Windows information from sessionInfo() in R session
sessionInfo()
R version 3.4.1 (2017-06-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)
Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.4.1 tools_3.4.1

## Error Message:
*** arch - i386
Error: package or namespace load failed for 'lightgbm' in inDL(x, as.logical(local), as.logical(now), ...):
 unable to load shared object 'C:/Users/J/Documents/R/win-library/3.4/lightgbm/libs/i386/lib_lightgbm.dll':
  LoadLibrary failure:  %1 is not a valid Win32 application.

Error: loading failed
Execution halted
*** arch - x64
ERROR: loading failed for 'i386'

## Reproducible examples
devtools::install_github("Microsoft/LightGBM", subdir = "R-package")

## Complete Installation log
devtools::install_github("Microsoft/LightGBM", subdir = "R-package")
Downloading GitHub repo Microsoft/LightGBM@master
from URL https://api.github.com/repos/Microsoft/LightGBM/zipball/master
Installing lightgbm
"C:/PROGRA~1/R/R-34~1.1/bin/x64/R" --no-site-file --no-environ --no-save --no-restore  \
  --quiet CMD INSTALL  \
  "C:/Users/J/AppData/Local/Temp/RtmpIzBmOg/devtools31fc218634b7/Microsoft-LightGBM-ac73638/R-package"  \
  --library="C:/Users/J/Documents/R/win-library/3.4" --install-tests 

* installing *source* package 'lightgbm' ...
** libs

*** arch - i386
installing via 'install.libs.R' to C:/Users/J/Documents/R/win-library/3.4/lightgbm
-- Building for: Visual Studio 15 2017
-- The C compiler identification is MSVC 19.10.25019.0
-- The CXX compiler identification is MSVC 19.10.25019.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Tools/MSVC/14.10.25017/bin/HostX86/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Tools/MSVC/14.10.25017/bin/HostX86/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Tools/MSVC/14.10.25017/bin/HostX86/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Tools/MSVC/14.10.25017/bin/HostX86/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning (dev) at C:/Program Files/CMake/share/cmake-3.9/Modules/FindOpenMP.cmake:212 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "MSVC" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.9/Modules/FindOpenMP.cmake:324 (_OPENMP_GET_FLAGS)
  CMakeLists.txt:28 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found OpenMP_C: -openmp (found version "2.0") 
-- Found OpenMP_CXX: -openmp (found version "2.0") 
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/J/AppData/Local/Temp/RtmpIzBmOg/devtools31fc218634b7/Microsoft-LightGBM-ac73638/R-package/src/build
Microsoft (R) Build Engine version 15.1.1012.6693
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 7/7/2017 12:15:15 AM.
Project "C:\Users\J\AppData\Local\Temp\RtmpIzBmOg\devtools31fc218634b7\Microsoft-LightGBM-ac73638\R-package\src\build\_lightgbm.vcxproj" on node 1 (default targets).
Project "C:\Users\J\AppData\Local\Temp\RtmpIzBmOg\devtools31fc218634b7\Microsoft-LightGBM-ac73638\R-package\src\build\_lightgbm.vcxproj" (1) is building "C:\Users\J\AppData\Local\Temp\RtmpIzBmOg\devtools31fc218634b7\Microsoft-LightGBM-ac73638\R-package\src\build\ZERO_CHECK.vcxproj" (2) on node 1 (default targets).
PrepareForBuild:
  Creating directory "x64\Release\ZERO_CHECK\".
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargets\Microsoft.CppBuild.targets(395,5): warning MSB8029: The Intermediate directory or Output directory cannot reside under the Temporary directory as it could lead to issues with incremental build. [C:\Users\J\AppData\Local\Temp\RtmpIzBmOg\devtools31fc218634b7\Microsoft-LightGBM-ac73638\R-package\src\build\ZERO_CHECK.vcxproj]
  Creating directory "x64\Release\ZERO_CHECK\ZERO_CHECK.tlog\".
InitializeBuildStatus:
  Creating "x64\Release\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
CustomBuild:
  Checking Build System
  CMake does not need to re-run because C:/Users/J/AppData/Local/Temp/RtmpIzBmOg/devtools31fc218634b7/Microsoft-LightGBM-ac73638/R-package/src/build/CMakeFiles/generate.stamp is up-to-date.
FinalizeBuildStatus:
  Deleting file "x64\Release\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild".
  Touching "x64\Release\ZERO_CHECK\ZERO_CHECK.tlog\ZERO_CHECK.lastbuildstate".
Done Building Project "C:\Users\J\AppData\Local\Temp\RtmpIzBmOg\devtools31fc218634b7\Microsoft-LightGBM-ac73638\R-package\src\build\ZERO_CHECK.vcxproj" (default targets).
PrepareForBuild:
  Creating directory "_lightgbm.dir\Release\".
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargets\Microsoft.CppBuild.targets(395,5): warning MSB8029: The Intermediate directory or Output directory cannot reside under the Temporary directory as it could lead to issues with incremental build. [C:\Users\J\AppData\Local\Temp\RtmpIzBmOg\devtools31fc218634b7\Microsoft-LightGBM-ac73638\R-package\src\build\_lightgbm.vcxproj]
  Creating directory "C:\Users\J\AppData\Local\Temp\RtmpIzBmOg\devtools31fc218634b7\Microsoft-LightGBM-ac73638\R-package\src\Release\".
  Creating directory "_lightgbm.dir\Release\_lightgbm.tlog\".
InitializeBuildStatus:
  Creating "_lightgbm.dir\Release\_lightgbm.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
CustomBuild:
  Building Custom Rule C:/Users/J/AppData/Local/Temp/RtmpIzBmOg/devtools31fc218634b7/Microsoft-LightGBM-ac73638/R-package/src/CMakeLists.txt
  CMake does not need to re-run because C:/Users/J/AppData/Local/Temp/RtmpIzBmOg/devtools31fc218634b7/Microsoft-LightGBM-ac73638/R-package/src/build/CMakeFiles/generate.stamp is up-to-date.
ClCompile:
  C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.10.25017\bin\HostX86\x64\CL.exe /c /I"C:\Users\J\AppData\Local\Temp\RtmpIzBmOg\devtools31fc218634b7\Microsoft-LightGBM-ac73638\R-package\src\include" /nologo /W4 /WX- /diagnostics:classic /O2 /Ob2 /Oi /Ot /Oy /GL /D WIN32 /D _WINDOWS /D NDEBUG /D USE_SOCKET /D "CMAKE_INTDIR=\"Release\"" /D _lightgbm_EXPORTS /D _WINDLL /D _MBCS /Gm- /EHsc /MD /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /openmp /Fo"_lightgbm.dir\Release\\" /Fd"_lightgbm.dir\Release\vc141.pdb" /Gd /TP /errorReport:queue "C:\Users\J\AppData\Local\Temp\RtmpIzBmOg\devtools31fc218634b7\Microsoft-LightGBM-ac73638\R-package\src\src\c_api.cpp" "C:\Users\J\AppData\Local\Temp\RtmpIzBmOg\devtools31fc218634b7\Microsoft-LightGBM-ac73638\R-package\src\src\lightgbm_R.cpp" "C:\Users\J\AppData\Local\Temp\RtmpIzBmOg\devtools31fc218634b7\Microsoft-LightGBM-ac73638\R-package\src\src\application\application.cpp" "C:\Users\J\AppData\Local\Temp\RtmpIz... <truncated>
  c_api.cpp
  lightgbm_R.cpp
  application.cpp
  boosting.cpp
  gbdt.cpp
  gbdt_prediction.cpp
  prediction_early_stop.cpp
  bin.cpp
  config.cpp
  dataset.cpp
  dataset_loader.cpp
  metadata.cpp
  parser.cpp
  tree.cpp
  dcg_calculator.cpp
  metric.cpp
  objective_function.cpp
  linker_topo.cpp
  linkers_mpi.cpp
  linkers_socket.cpp
  Compiling...
  network.cpp
  data_parallel_tree_learner.cpp
  feature_parallel_tree_learner.cpp
  gpu_tree_learner.cpp
  serial_tree_learner.cpp
  tree_learner.cpp
  voting_parallel_tree_learner.cpp
Link:
  C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.10.25017\bin\HostX86\x64\link.exe /ERRORREPORT:QUEUE /OUT:"C:\Users\J\AppData\Local\Temp\RtmpIzBmOg\devtools31fc218634b7\Microsoft-LightGBM-ac73638\R-package\src\Release\lib_lightgbm.dll" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:"C:/Users/J/AppData/Local/Temp/RtmpIzBmOg/devtools31fc218634b7/Microsoft-LightGBM-ac73638/R-package/src/Release/lib_lightgbm.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/Users/J/AppData/Local/Temp/RtmpIzBmOg/devtools31fc218634b7/Microsoft-LightGBM-ac73638/R-package/src/Release/lib_lightgbm.lib" /MACHINE:X64  /machine:x64 /DLL _lightgbm.dir\Release\c_api.obj
  _lightgbm.dir\Release\lightgbm_R.obj
  _lightgbm.dir\Release\application.obj
  _lightgbm.dir\Release\boosting.obj
  _lightgbm.dir\Release\gbdt.obj
  _lightgbm.dir\Release\gbdt_prediction.obj
  _lightgbm.dir\Release\prediction_early_stop.obj
  _lightgbm.dir\Release\bin.obj
  _lightgbm.dir\Release\config.obj
  _lightgbm.dir\Release\dataset.obj
  _lightgbm.dir\Release\dataset_loader.obj
  _lightgbm.dir\Release\metadata.obj
  _lightgbm.dir\Release\parser.obj
  _lightgbm.dir\Release\tree.obj
  _lightgbm.dir\Release\dcg_calculator.obj
  _lightgbm.dir\Release\metric.obj
  _lightgbm.dir\Release\objective_function.obj
  _lightgbm.dir\Release\linker_topo.obj
  _lightgbm.dir\Release\linkers_mpi.obj
  _lightgbm.dir\Release\linkers_socket.obj
  _lightgbm.dir\Release\network.obj
  _lightgbm.dir\Release\data_parallel_tree_learner.obj
  _lightgbm.dir\Release\feature_parallel_tree_learner.obj
  _lightgbm.dir\Release\gpu_tree_learner.obj
  _lightgbm.dir\Release\serial_tree_learner.obj
  _lightgbm.dir\Release\tree_learner.obj
  _lightgbm.dir\Release\voting_parallel_tree_learner.obj
  c_api.obj : MSIL .netmodule or module compiled with /GL found; restarting link with /LTCG; add /LTCG to the link command line to improve linker performance
     Creating library C:/Users/J/AppData/Local/Temp/RtmpIzBmOg/devtools31fc218634b7/Microsoft-LightGBM-ac73638/R-package/src/Release/lib_lightgbm.lib and object C:/Users/J/AppData/Local/Temp/RtmpIzBmOg/devtools31fc218634b7/Microsoft-LightGBM-ac73638/R-package/src/Release/lib_lightgbm.exp
  Generating code
  Finished generating code
  _lightgbm.vcxproj -> C:\Users\J\AppData\Local\Temp\RtmpIzBmOg\devtools31fc218634b7\Microsoft-LightGBM-ac73638\R-package\src\Release\lib_lightgbm.dll
FinalizeBuildStatus:
  Deleting file "_lightgbm.dir\Release\_lightgbm.tlog\unsuccessfulbuild".
  Touching "_lightgbm.dir\Release\_lightgbm.tlog\_lightgbm.lastbuildstate".
Done Building Project "C:\Users\J\AppData\Local\Temp\RtmpIzBmOg\devtools31fc218634b7\Microsoft-LightGBM-ac73638\R-package\src\build\_lightgbm.vcxproj" (default targets).

Build succeeded.

"C:\Users\J\AppData\Local\Temp\RtmpIzBmOg\devtools31fc218634b7\Microsoft-LightGBM-ac73638\R-package\src\build\_lightgbm.vcxproj" (default target) (1) ->
"C:\Users\J\AppData\Local\Temp\RtmpIzBmOg\devtools31fc218634b7\Microsoft-LightGBM-ac73638\R-package\src\build\ZERO_CHECK.vcxproj" (default target) (2) ->
(PrepareForBuild target) -> 
  C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargets\Microsoft.CppBuild.targets(395,5): warning MSB8029: The Intermediate directory or Output directory cannot reside under the Temporary directory as it could lead to issues with incremental build. [C:\Users\J\AppData\Local\Temp\RtmpIzBmOg\devtools31fc218634b7\Microsoft-LightGBM-ac73638\R-package\src\build\ZERO_CHECK.vcxproj]

"C:\Users\J\AppData\Local\Temp\RtmpIzBmOg\devtools31fc218634b7\Microsoft-LightGBM-ac73638\R-package\src\build\_lightgbm.vcxproj" (default target) (1) ->
  C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargets\Microsoft.CppBuild.targets(395,5): warning MSB8029: The Intermediate directory or Output directory cannot reside under the Temporary directory as it could lead to issues with incremental build. [C:\Users\J\AppData\Local\Temp\RtmpIzBmOg\devtools31fc218634b7\Microsoft-LightGBM-ac73638\R-package\src\build\_lightgbm.vcxproj]

    2 Warning(s)
    0 Error(s)

Time Elapsed 00:01:31.43
Found library file: C:/Users/J/AppData/Local/Temp/RtmpIzBmOg/devtools31fc218634b7/Microsoft-LightGBM-ac73638/R-package/src/Release/lib_lightgbm.dll to move to C:/Users/J/Documents/R/win-library/3.4/lightgbm/libs/i386
*** arch - x64
installing via 'install.libs.R' to C:/Users/J/Documents/R/win-library/3.4/lightgbm
-- Building for: Visual Studio 15 2017
-- The C compiler identification is MSVC 19.10.25019.0
-- The CXX compiler identification is MSVC 19.10.25019.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Tools/MSVC/14.10.25017/bin/HostX86/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Tools/MSVC/14.10.25017/bin/HostX86/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Tools/MSVC/14.10.25017/bin/HostX86/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Tools/MSVC/14.10.25017/bin/HostX86/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning (dev) at C:/Program Files/CMake/share/cmake-3.9/Modules/FindOpenMP.cmake:212 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "MSVC" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.9/Modules/FindOpenMP.cmake:324 (_OPENMP_GET_FLAGS)
  CMakeLists.txt:28 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found OpenMP_C: -openmp (found version "2.0") 
-- Found OpenMP_CXX: -openmp (found version "2.0") 
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/J/AppData/Local/Temp/RtmpIzBmOg/devtools31fc218634b7/Microsoft-LightGBM-ac73638/R-package/src/build
Microsoft (R) Build Engine version 15.1.1012.6693
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 7/7/2017 12:17:53 AM.
Project "C:\Users\J\AppData\Local\Temp\RtmpIzBmOg\devtools31fc218634b7\Microsoft-LightGBM-ac73638\R-package\src\build\_lightgbm.vcxproj" on node 1 (default targets).
Project "C:\Users\J\AppData\Local\Temp\RtmpIzBmOg\devtools31fc218634b7\Microsoft-LightGBM-ac73638\R-package\src\build\_lightgbm.vcxproj" (1) is building "C:\Users\J\AppData\Local\Temp\RtmpIzBmOg\devtools31fc218634b7\Microsoft-LightGBM-ac73638\R-package\src\build\ZERO_CHECK.vcxproj" (2) on node 1 (default targets).
PrepareForBuild:
  Creating directory "x64\Release\ZERO_CHECK\".
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargets\Microsoft.CppBuild.targets(395,5): warning MSB8029: The Intermediate directory or Output directory cannot reside under the Temporary directory as it could lead to issues with incremental build. [C:\Users\J\AppData\Local\Temp\RtmpIzBmOg\devtools31fc218634b7\Microsoft-LightGBM-ac73638\R-package\src\build\ZERO_CHECK.vcxproj]
  Creating directory "x64\Release\ZERO_CHECK\ZERO_CHECK.tlog\".
InitializeBuildStatus:
  Creating "x64\Release\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
CustomBuild:
  Checking Build System
  CMake does not need to re-run because C:/Users/J/AppData/Local/Temp/RtmpIzBmOg/devtools31fc218634b7/Microsoft-LightGBM-ac73638/R-package/src/build/CMakeFiles/generate.stamp is up-to-date.
FinalizeBuildStatus:
  Deleting file "x64\Release\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild".
  Touching "x64\Release\ZERO_CHECK\ZERO_CHECK.tlog\ZERO_CHECK.lastbuildstate".
Done Building Project "C:\Users\J\AppData\Local\Temp\RtmpIzBmOg\devtools31fc218634b7\Microsoft-LightGBM-ac73638\R-package\src\build\ZERO_CHECK.vcxproj" (default targets).
PrepareForBuild:
  Creating directory "_lightgbm.dir\Release\".
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargets\Microsoft.CppBuild.targets(395,5): warning MSB8029: The Intermediate directory or Output directory cannot reside under the Temporary directory as it could lead to issues with incremental build. [C:\Users\J\AppData\Local\Temp\RtmpIzBmOg\devtools31fc218634b7\Microsoft-LightGBM-ac73638\R-package\src\build\_lightgbm.vcxproj]
  Creating directory "_lightgbm.dir\Release\_lightgbm.tlog\".
InitializeBuildStatus:
  Creating "_lightgbm.dir\Release\_lightgbm.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
CustomBuild:
  Building Custom Rule C:/Users/J/AppData/Local/Temp/RtmpIzBmOg/devtools31fc218634b7/Microsoft-LightGBM-ac73638/R-package/src/CMakeLists.txt
  CMake does not need to re-run because C:/Users/J/AppData/Local/Temp/RtmpIzBmOg/devtools31fc218634b7/Microsoft-LightGBM-ac73638/R-package/src/build/CMakeFiles/generate.stamp is up-to-date.
ClCompile:
  C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.10.25017\bin\HostX86\x64\CL.exe /c /I"C:\Users\J\AppData\Local\Temp\RtmpIzBmOg\devtools31fc218634b7\Microsoft-LightGBM-ac73638\R-package\src\include" /nologo /W4 /WX- /diagnostics:classic /O2 /Ob2 /Oi /Ot /Oy /GL /D WIN32 /D _WINDOWS /D NDEBUG /D USE_SOCKET /D "CMAKE_INTDIR=\"Release\"" /D _lightgbm_EXPORTS /D _WINDLL /D _MBCS /Gm- /EHsc /MD /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /openmp /Fo"_lightgbm.dir\Release\\" /Fd"_lightgbm.dir\Release\vc141.pdb" /Gd /TP /errorReport:queue "C:\Users\J\AppData\Local\Temp\RtmpIzBmOg\devtools31fc218634b7\Microsoft-LightGBM-ac73638\R-package\src\src\c_api.cpp" "C:\Users\J\AppData\Local\Temp\RtmpIzBmOg\devtools31fc218634b7\Microsoft-LightGBM-ac73638\R-package\src\src\lightgbm_R.cpp" "C:\Users\J\AppData\Local\Temp\RtmpIzBmOg\devtools31fc218634b7\Microsoft-LightGBM-ac73638\R-package\src\src\application\application.cpp" "C:\Users\J\AppData\Local\Temp\RtmpIz... <truncated>
  c_api.cpp
  lightgbm_R.cpp
  application.cpp
  boosting.cpp
  gbdt.cpp
  gbdt_prediction.cpp
  prediction_early_stop.cpp
  bin.cpp
  config.cpp
  dataset.cpp
  dataset_loader.cpp
  metadata.cpp
  parser.cpp
  tree.cpp
  dcg_calculator.cpp
  metric.cpp
  objective_function.cpp
  linker_topo.cpp
  linkers_mpi.cpp
  linkers_socket.cpp
  Compiling...
  network.cpp
  data_parallel_tree_learner.cpp
  feature_parallel_tree_learner.cpp
  gpu_tree_learner.cpp
  serial_tree_learner.cpp
  tree_learner.cpp
  voting_parallel_tree_learner.cpp
Link:
  C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.10.25017\bin\HostX86\x64\link.exe /ERRORREPORT:QUEUE /OUT:"C:\Users\J\AppData\Local\Temp\RtmpIzBmOg\devtools31fc218634b7\Microsoft-LightGBM-ac73638\R-package\src\Release\lib_lightgbm.dll" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:"C:/Users/J/AppData/Local/Temp/RtmpIzBmOg/devtools31fc218634b7/Microsoft-LightGBM-ac73638/R-package/src/Release/lib_lightgbm.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/Users/J/AppData/Local/Temp/RtmpIzBmOg/devtools31fc218634b7/Microsoft-LightGBM-ac73638/R-package/src/Release/lib_lightgbm.lib" /MACHINE:X64  /machine:x64 /DLL _lightgbm.dir\Release\c_api.obj
  _lightgbm.dir\Release\lightgbm_R.obj
  _lightgbm.dir\Release\application.obj
  _lightgbm.dir\Release\boosting.obj
  _lightgbm.dir\Release\gbdt.obj
  _lightgbm.dir\Release\gbdt_prediction.obj
  _lightgbm.dir\Release\prediction_early_stop.obj
  _lightgbm.dir\Release\bin.obj
  _lightgbm.dir\Release\config.obj
  _lightgbm.dir\Release\dataset.obj
  _lightgbm.dir\Release\dataset_loader.obj
  _lightgbm.dir\Release\metadata.obj
  _lightgbm.dir\Release\parser.obj
  _lightgbm.dir\Release\tree.obj
  _lightgbm.dir\Release\dcg_calculator.obj
  _lightgbm.dir\Release\metric.obj
  _lightgbm.dir\Release\objective_function.obj
  _lightgbm.dir\Release\linker_topo.obj
  _lightgbm.dir\Release\linkers_mpi.obj
  _lightgbm.dir\Release\linkers_socket.obj
  _lightgbm.dir\Release\network.obj
  _lightgbm.dir\Release\data_parallel_tree_learner.obj
  _lightgbm.dir\Release\feature_parallel_tree_learner.obj
  _lightgbm.dir\Release\gpu_tree_learner.obj
  _lightgbm.dir\Release\serial_tree_learner.obj
  _lightgbm.dir\Release\tree_learner.obj
  _lightgbm.dir\Release\voting_parallel_tree_learner.obj
  c_api.obj : MSIL .netmodule or module compiled with /GL found; restarting link with /LTCG; add /LTCG to the link command line to improve linker performance
     Creating library C:/Users/J/AppData/Local/Temp/RtmpIzBmOg/devtools31fc218634b7/Microsoft-LightGBM-ac73638/R-package/src/Release/lib_lightgbm.lib and object C:/Users/J/AppData/Local/Temp/RtmpIzBmOg/devtools31fc218634b7/Microsoft-LightGBM-ac73638/R-package/src/Release/lib_lightgbm.exp
  Generating code
  Finished generating code
  _lightgbm.vcxproj -> C:\Users\J\AppData\Local\Temp\RtmpIzBmOg\devtools31fc218634b7\Microsoft-LightGBM-ac73638\R-package\src\Release\lib_lightgbm.dll
FinalizeBuildStatus:
  Deleting file "_lightgbm.dir\Release\_lightgbm.tlog\unsuccessfulbuild".
  Touching "_lightgbm.dir\Release\_lightgbm.tlog\_lightgbm.lastbuildstate".
Done Building Project "C:\Users\J\AppData\Local\Temp\RtmpIzBmOg\devtools31fc218634b7\Microsoft-LightGBM-ac73638\R-package\src\build\_lightgbm.vcxproj" (default targets).

Build succeeded.

"C:\Users\J\AppData\Local\Temp\RtmpIzBmOg\devtools31fc218634b7\Microsoft-LightGBM-ac73638\R-package\src\build\_lightgbm.vcxproj" (default target) (1) ->
"C:\Users\J\AppData\Local\Temp\RtmpIzBmOg\devtools31fc218634b7\Microsoft-LightGBM-ac73638\R-package\src\build\ZERO_CHECK.vcxproj" (default target) (2) ->
(PrepareForBuild target) -> 
  C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargets\Microsoft.CppBuild.targets(395,5): warning MSB8029: The Intermediate directory or Output directory cannot reside under the Temporary directory as it could lead to issues with incremental build. [C:\Users\J\AppData\Local\Temp\RtmpIzBmOg\devtools31fc218634b7\Microsoft-LightGBM-ac73638\R-package\src\build\ZERO_CHECK.vcxproj]

"C:\Users\J\AppData\Local\Temp\RtmpIzBmOg\devtools31fc218634b7\Microsoft-LightGBM-ac73638\R-package\src\build\_lightgbm.vcxproj" (default target) (1) ->
  C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargets\Microsoft.CppBuild.targets(395,5): warning MSB8029: The Intermediate directory or Output directory cannot reside under the Temporary directory as it could lead to issues with incremental build. [C:\Users\J\AppData\Local\Temp\RtmpIzBmOg\devtools31fc218634b7\Microsoft-LightGBM-ac73638\R-package\src\build\_lightgbm.vcxproj]

    2 Warning(s)
    0 Error(s)

Time Elapsed 00:01:26.63
Found library file: C:/Users/J/AppData/Local/Temp/RtmpIzBmOg/devtools31fc218634b7/Microsoft-LightGBM-ac73638/R-package/src/Release/lib_lightgbm.dll to move to C:/Users/J/Documents/R/win-library/3.4/lightgbm/libs/x64** R
** data
** demo
** tests
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
*** arch - i386
Error: package or namespace load failed for 'lightgbm' in inDL(x, as.logical(local), as.logical(now), ...):
 unable to load shared object 'C:/Users/J/Documents/R/win-library/3.4/lightgbm/libs/i386/lib_lightgbm.dll':
  LoadLibrary failure:  %1 is not a valid Win32 application.

Error: loading failed
Execution halted
*** arch - x64
ERROR: loading failed for 'i386'
* removing 'C:/Users/J/Documents/R/win-library/3.4/lightgbm'
* restoring previous 'C:/Users/J/Documents/R/win-library/3.4/lightgbm'
Installation failed: Command failed (1)
Warning message:
GitHub repo contains submodules, may not function as expected!

**Comment by Laurae2** [comment]
You can only install 64 bit version, not the 32 bit version of the LightGBM R package.

**Comment by guolinke** [comment]
From your logs, it seems the 32-bit and 64-bit are both compiled.
However, we didn't support for the 32-bit R. 
Can you only install the 64-bit R? 

![image](https://user-images.githubusercontent.com/16040950/27943896-7480c656-6315-11e7-9646-05b096d13c74.png)

@Laurae2 Is there any solution that we can avoid the building for the 32-bit R ? And giving a error when user run it in 32-bit R .

**Comment by janamejaya** [comment]
@Laurae2 and @guolinke : Thank you! 
After reinstalling only the 64-bit version of R, I was able to successfully compile lightgbm.

To summarize what worked for me on Windows 10/R-Studio
1. Install R (only the 64-bit version, no 32-bit version present).
2. Install R-tools (only the 64-bit version, no 32-bit version present)
3. Install Microsoft Visual Studio
4. Install Cmake (64-bit)
5. devtools::install_github("Microsoft/LightGBM", subdir = "R-package")

**Comment by zenkzz** [comment]
If both 64-bit R and 32-bit R are installed then the following command helps:
R CMD INSTALL --build . --no-multiarch

The option --no-multiarch does not allow to install the 32-bit version

**Comment by guolinke** [comment]
@zenkzz  thanks very much. It is very helpful .
