### ISSUE TITLE
early_stopping_rounds doesn't work as expected

### ISSUE THREAD

**Issue by aamster** [Microsoft/LightGBM#677]
When I set `early_stopping_rounds` greater than `num_boost_round`, I would expect `early_stopping_rounds` to override `num_boost_round`. I.e I set early_stopping_rounds = 400. num_boost_round defaults to 100. I would expect the number of boosting rounds to continue until the metric doesn't improve, but instead it stops at 100 rounds. 

If I instead set  `num_boost_round` greater than  `early_stopping_rounds` then the number of boosting rounds continues until `num_boost_round`, even if the metric does not improve.

**Comment by guolinke** [comment]
I think it have no reason to set the a ```early_stopping_rounds``` greater than the ```num_boost_round``` . 

if you set ```early_stopping_rounds = 400```, it means the training should stop if the metric of last 400 iterations have no improvement.

**Comment by aamster** [comment]
Fine, that's the first scenario I pointed out. But for the second scenario, let's say I set num_boost_round = 400 and early_stopping_rounds = 300. 

I see in the eval output:
valid_0's auc: 0.833976
valid_0's auc: 0.833972
valid_0's auc: 0.833968

Why didn't it stop the boosting rounds?

**Comment by guolinke** [comment]
@aamster 
if you set ```early_stopping_round=1''', it will stop in your case.

However, you set it to ```300```,  so it will stop when the ```best(metric of last 300 iterations) < best(metric of all iterations)```.
