### ISSUE TITLE
not able to install lightgbm module in spyder 

### ISSUE THREAD

**Issue by sagar-m** [Microsoft/LightGBM#681]
Hi, I am not able to install lightgbm module in spyder using the steps as detailed here. I get the followinf error...would appreciate any help on how to fix this. Yes, there is a proxy at my workplace Thanks..!

Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000002B1188BDB38>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed',)': /simple/lightgbm/

**Comment by chivee** [comment]
Can you installer lightGBM successfully using pure PIP?
What proxy are you using? socks or http?

some refers could help:

https://stackoverflow.com/questions/29267646/how-to-enable-proxy-servers-with-anaconda-python
https://github.com/spyder-ide/spyder/issues/4668
https://github.com/spyder-ide/spyder/issues/4217

**Comment by sagar-m** [comment]
Hi Qiwei, thanks for your note. I have also posted on this link
https://stackoverflow.com/questions/29267646/how-to-enable-proxy-servers-with-anaconda-python/45071662#45071662


0down vote

I am working behind a proxy server at work. I went through your answers
above, but as I am new to python, not clear how does one create .condarc
file?I type conda config --help and it gives me some command tips. Thank
you very much.

The following commands described above, how do I add to and save as a .condarc
file?

 channels:
 - defaults
# Show channel URLs when displaying what is going to be downloaded
and# in 'conda list'. The default is False.
show_channel_urls: True
allow_other_channels: True

proxy_servers:                     #edited for mine
http: http://FG**1:3***
https: https://FG**1:3***


ssl_verify: False

**Comment by chivee** [comment]
`.condarc` was only functional when you are using conda as your python environment. and it's locate vary from your OS.  refs: https://conda.io/docs/config.html#the-conda-configuration-file-condarc
 windows: https://conda.io/docs/winxp-proxy.html
 linux : on your `~` folder

I'll close this issue first, please fell free to reopen it if you still have same issue

**Comment by sagar-m** [comment]
0down vote

I'm working behind a proxy server at work, but as I am new to python, not
clear how does one create .condarc file? Should I be pasting the below
commands in text editor and simply save it as .condarc.py file in root
directory? (i was not able to find the extension .condarc in save as type)
. Thank you very much.

The following commands described above, how do I add to and save as a .condarc
file?

 channels:
 - defaults
# Show channel URLs when displaying what is going to be downloaded
and# in 'conda list'. The default is False.
show_channel_urls: True
allow_other_channels: True

proxy_servers:                     #edited for mine
http: http://FG**1:3***
https: https://FG**1:3***


ssl_verify: False
