### ISSUE TITLE
[R_package] options of  'objective' in lgb.train()

### ISSUE THREAD

**Issue by zheguzai100** [Microsoft/LightGBM#682]
@guolinke
Options : regression, regression_l1, huber, binary, lambdarank, multiclass, multiclass in 'objctive'
in my mind, 
regression is for linear regression
binary is for logistic(0/1) regression
multiclass is for multi-class(1/2/3...) classification
is it right ?  
and what does the rest(reg-l1/huber/lambdarank/multiclass(last)) mean?

**Comment by guolinke** [comment]
@zheguzai100 
I think the last ```multiclass``` is a typo.
and multi-class is use (0,1,2,...) as labels.

More details can be found in here: https://github.com/Microsoft/LightGBM/blob/master/docs/Parameters.md
