### ISSUE TITLE
Importing lightgbm using Spyder takes lot of time and ends with error

### ISSUE THREAD

**Issue by munitech4u** [Microsoft/LightGBM#683]
Please search your question on previous issues, stackoverflow or other search engines before you open a new one.

For bugs and unexpected issues, please provide following information, so that we could reproduce on our system.

## Environment info
Operating System: Win -7 
CPU: Intel Core - i7
C++/Python/R version: Python 3.5

## Error Message:
1. Takes lot of time to import and ends after some time with error: "AttributeError: module 'lightgbm' has no attribute 'Dataset'"

## Reproducible examples
import lightgbm as lgb

## Steps to reproduce

1. pip install lightgbm
2. import lightgbm as lgb

It takes lot of time to import and then ends with attribute error

**Comment by guolinke** [comment]
Did you install vc runtime ?

**Comment by munitech4u** [comment]
Ok. After compiling and creating the executable file, its working for me now. Instructions here helped:

https://www.analyticsvidhya.com/blog/2017/06/which-algorithm-takes-the-crown-light-gbm-vs-xgboost/
