### ISSUE TITLE
the difference between two ways of prediction

### ISSUE THREAD

**Issue by journeycheng** [Microsoft/LightGBM#684]
## Environment
 linux + python

## Question
things likes this:
i successfully trained the lightgbm model with libsvm format dataset. Also, i want to do a prediction with  libsvm format data.
```python
df_test = lgb.Dataset('test.libsvm')
bst = lgb.Booster(model_file='model.txt')
y_pred_prob = bst.predict(dtest)
```
then it throws the ERROR:
```
  y_pred_prob = bst.predict(dtest)
  File "/Library/Python/2.7/site-packages/lightgbm/basic.py", line 1616, in predict
    return predictor.predict(data, num_iteration, raw_score, pred_leaf, data_has_header, is_reshape)
  File "/Library/Python/2.7/site-packages/lightgbm/basic.py", line 383, in predict
    raise TypeError("Cannot use Dataset instance for prediction, please use raw data instead")
TypeError: Cannot use Dataset instance for prediction, please use raw data instead
```
so, i have to change the libsvm format to other, like csv (used in official examples), which results in a much bigger and  bigger data file.

but i also find another way to do a prediction:
 
with a predict.conf file:
```
task = predict
data = test.libsvm
input_model = model.txt
```
and run the command:
```linux
> ${path_to_lightgbm}/lightgbm predict.conf
```
this way just make it and output a file of prediction result 

so, why this way can use libsvm file? and what's the difference between this two ways of loading data when predict?

thanks.

**Comment by guolinke** [comment]
@journeycheng 
you cannot use ```lgb.Dataset``` to prediction.
You can pass the file path directly in predict function: 

```
bst = lgb.Booster(model_file='model.txt')
y_pred_prob = bst.predict('test.libsvm')
```

**Comment by journeycheng** [comment]
@guolinke
that works and helps me a lot, really thankful

**Comment by journeycheng** [comment]
@guolinke
execuse, another question.
if i only need to predict one piece of data, a string, its content is also in libsvm format, but i don't want to write it into a file. How can i do a prediction?
```python
example = '0 885:1 1211:1 1349:1 1353:18 1354:16 1357:1 1359:1 1362:1 1363:1 1369:2 1370:2 1371:2 1372:2 1373:2 1390:1 1392:1 1434:9.53674316406e-06'
bst = lgb.Booster(model_file='model.txt')
```

**Comment by guolinke** [comment]
@journeycheng 
you should covert it to the matric/CSR format first. 

However, the predict function is designed for the multi-line data, using it to predict with single line is not efficient.

**Comment by journeycheng** [comment]
@guolinke 
get it.

**Comment by byte-dance** [comment]
> @journeycheng
> you should covert it to the matric/CSR format first.
> 
> However, the predict function is designed for the multi-line data, using it to predict with single line is not efficient.

If model is trained using libsvm format dataset, I failed to predict using single row numpy or matric/CSR features. Any suggestions?
