### ISSUE TITLE
How to use to LightGBM to run my own Data? Need Help.

### ISSUE THREAD

**Issue by Gautamshahi** [Microsoft/LightGBM#690]
Please search your question on previous issues, stackoverflow or other search engines before you open a new one.

For bugs and unexpected issues, please provide following information, so that we could reproduce on our system.

## Environment info
Operating System:
CPU:
C++/Python/R version:

## Steps to reproduce

1.
2.
3.

**Comment by chivee** [comment]
please look at https://github.com/Microsoft/LightGBM/tree/master/examples for guideline
