### ISSUE TITLE
is pip installation sufficient or we need to compile the git files as well for windows installation

### ISSUE THREAD

**Issue by munitech4u** [Microsoft/LightGBM#696]
Please search your question on previous issues, stackoverflow or other search engines before you open a new one.

For bugs and unexpected issues, please provide following information, so that we could reproduce on our system.

## Environment info
Operating System: win -7
CPU: intel core - i7
C++/Python/R version: Python 3.5

## Error Message: I installed using pip, though it created the libraries in Anaconda, its taking forever to import. 
I tried creating exe and dll files using mingw32 as per the documentation. But not sure how to use them inside python. I followed it by "python setup.py install" step, but its throwing the error "Failed to run MSBuild command", however MSBuild and VC++ is installed in my system.

## Reproducible examples

git clone --recursive https://github.com/Microsoft/LightGBM
cd LightGBM
mkdir build
cd build
cmake -G "MinGW Makefiles" ..
mingw32-make.exe -j4
cd python-package
python setup.py install

## Steps to reproduce

Run above steps in sequence

**Comment by guolinke** [comment]
@munitech4u it doesn't need to build the CLI (exe and dll) first for install python-package.
You can install python package just via:

```
git clone --recursive https://github.com/Microsoft/LightGBM
cd LightGBM
cd python-package
python setup.py install
```

And can you paste the log of installing python-package ?

**Comment by munitech4u** [comment]
Here is the log:

running install
creating lightgbm\include
creating lightgbm\include\LightGBM
copying ..\include\LightGBM\application.h -> ./lightgbm\include\LightGBM
copying ..\include\LightGBM\bin.h -> ./lightgbm\include\LightGBM
copying ..\include\LightGBM\boosting.h -> ./lightgbm\include\LightGBM
copying ..\include\LightGBM\config.h -> ./lightgbm\include\LightGBM
copying ..\include\LightGBM\c_api.h -> ./lightgbm\include\LightGBM
copying ..\include\LightGBM\dataset.h -> ./lightgbm\include\LightGBM
copying ..\include\LightGBM\dataset_loader.h -> ./lightgbm\include\LightGBM
copying ..\include\LightGBM\export.h -> ./lightgbm\include\LightGBM
copying ..\include\LightGBM\feature_group.h -> ./lightgbm\include\LightGBM
copying ..\include\LightGBM\lightgbm_R.h -> ./lightgbm\include\LightGBM
copying ..\include\LightGBM\meta.h -> ./lightgbm\include\LightGBM
copying ..\include\LightGBM\metric.h -> ./lightgbm\include\LightGBM
copying ..\include\LightGBM\network.h -> ./lightgbm\include\LightGBM
copying ..\include\LightGBM\objective_function.h -> ./lightgbm\include\LightGBM
copying ..\include\LightGBM\prediction_early_stop.h -> ./lightgbm\include\LightG
BM
copying ..\include\LightGBM\R_object_helper.h -> ./lightgbm\include\LightGBM
copying ..\include\LightGBM\tree.h -> ./lightgbm\include\LightGBM
copying ..\include\LightGBM\tree_learner.h -> ./lightgbm\include\LightGBM
creating lightgbm\include\LightGBM\utils
copying ..\include\LightGBM\utils\array_args.h -> ./lightgbm\include\LightGBM\ut
ils
copying ..\include\LightGBM\utils\common.h -> ./lightgbm\include\LightGBM\utils
copying ..\include\LightGBM\utils\log.h -> ./lightgbm\include\LightGBM\utils
copying ..\include\LightGBM\utils\openmp_wrapper.h -> ./lightgbm\include\LightGB
M\utils
copying ..\include\LightGBM\utils\pipeline_reader.h -> ./lightgbm\include\LightG
BM\utils
copying ..\include\LightGBM\utils\random.h -> ./lightgbm\include\LightGBM\utils
copying ..\include\LightGBM\utils\text_reader.h -> ./lightgbm\include\LightGBM\u
tils
copying ..\include\LightGBM\utils\threading.h -> ./lightgbm\include\LightGBM\uti
ls
creating lightgbm\src
creating lightgbm\src\application
copying ..\src\application\application.cpp -> ./lightgbm\src\application
copying ..\src\application\predictor.hpp -> ./lightgbm\src\application
creating lightgbm\src\boosting
copying ..\src\boosting\boosting.cpp -> ./lightgbm\src\boosting
copying ..\src\boosting\dart.hpp -> ./lightgbm\src\boosting
copying ..\src\boosting\gbdt.cpp -> ./lightgbm\src\boosting
copying ..\src\boosting\gbdt.h -> ./lightgbm\src\boosting
copying ..\src\boosting\gbdt_prediction.cpp -> ./lightgbm\src\boosting
copying ..\src\boosting\goss.hpp -> ./lightgbm\src\boosting
copying ..\src\boosting\prediction_early_stop.cpp -> ./lightgbm\src\boosting
copying ..\src\boosting\rf.hpp -> ./lightgbm\src\boosting
copying ..\src\boosting\score_updater.hpp -> ./lightgbm\src\boosting
copying ..\src\c_api.cpp -> ./lightgbm\src
creating lightgbm\src\io
copying ..\src\io\bin.cpp -> ./lightgbm\src\io
copying ..\src\io\config.cpp -> ./lightgbm\src\io
copying ..\src\io\dataset.cpp -> ./lightgbm\src\io
copying ..\src\io\dataset_loader.cpp -> ./lightgbm\src\io
copying ..\src\io\dense_bin.hpp -> ./lightgbm\src\io
copying ..\src\io\dense_nbits_bin.hpp -> ./lightgbm\src\io
copying ..\src\io\metadata.cpp -> ./lightgbm\src\io
copying ..\src\io\ordered_sparse_bin.hpp -> ./lightgbm\src\io
copying ..\src\io\parser.cpp -> ./lightgbm\src\io
copying ..\src\io\parser.hpp -> ./lightgbm\src\io
copying ..\src\io\sparse_bin.hpp -> ./lightgbm\src\io
copying ..\src\io\tree.cpp -> ./lightgbm\src\io
copying ..\src\lightgbm_R.cpp -> ./lightgbm\src
copying ..\src\main.cpp -> ./lightgbm\src
creating lightgbm\src\metric
copying ..\src\metric\binary_metric.hpp -> ./lightgbm\src\metric
copying ..\src\metric\dcg_calculator.cpp -> ./lightgbm\src\metric
copying ..\src\metric\map_metric.hpp -> ./lightgbm\src\metric
copying ..\src\metric\metric.cpp -> ./lightgbm\src\metric
copying ..\src\metric\multiclass_metric.hpp -> ./lightgbm\src\metric
copying ..\src\metric\rank_metric.hpp -> ./lightgbm\src\metric
copying ..\src\metric\regression_metric.hpp -> ./lightgbm\src\metric
creating lightgbm\src\network
copying ..\src\network\linkers.h -> ./lightgbm\src\network
copying ..\src\network\linkers_mpi.cpp -> ./lightgbm\src\network
copying ..\src\network\linkers_socket.cpp -> ./lightgbm\src\network
copying ..\src\network\linker_topo.cpp -> ./lightgbm\src\network
copying ..\src\network\network.cpp -> ./lightgbm\src\network
copying ..\src\network\socket_wrapper.hpp -> ./lightgbm\src\network
creating lightgbm\src\objective
copying ..\src\objective\binary_objective.hpp -> ./lightgbm\src\objective
copying ..\src\objective\multiclass_objective.hpp -> ./lightgbm\src\objective
copying ..\src\objective\objective_function.cpp -> ./lightgbm\src\objective
copying ..\src\objective\rank_objective.hpp -> ./lightgbm\src\objective
copying ..\src\objective\regression_objective.hpp -> ./lightgbm\src\objective
creating lightgbm\src\treelearner
copying ..\src\treelearner\data_parallel_tree_learner.cpp -> ./lightgbm\src\tree
learner
copying ..\src\treelearner\data_partition.hpp -> ./lightgbm\src\treelearner
copying ..\src\treelearner\feature_histogram.hpp -> ./lightgbm\src\treelearner
copying ..\src\treelearner\feature_parallel_tree_learner.cpp -> ./lightgbm\src\t
reelearner
copying ..\src\treelearner\gpu_tree_learner.cpp -> ./lightgbm\src\treelearner
copying ..\src\treelearner\gpu_tree_learner.h -> ./lightgbm\src\treelearner
copying ..\src\treelearner\leaf_splits.hpp -> ./lightgbm\src\treelearner
creating lightgbm\src\treelearner\ocl
copying ..\src\treelearner\ocl\histogram16.cl -> ./lightgbm\src\treelearner\ocl
copying ..\src\treelearner\ocl\histogram256.cl -> ./lightgbm\src\treelearner\ocl

copying ..\src\treelearner\ocl\histogram64.cl -> ./lightgbm\src\treelearner\ocl
copying ..\src\treelearner\parallel_tree_learner.h -> ./lightgbm\src\treelearner

copying ..\src\treelearner\serial_tree_learner.cpp -> ./lightgbm\src\treelearner

copying ..\src\treelearner\serial_tree_learner.h -> ./lightgbm\src\treelearner
copying ..\src\treelearner\split_info.hpp -> ./lightgbm\src\treelearner
copying ..\src\treelearner\tree_learner.cpp -> ./lightgbm\src\treelearner
copying ..\src\treelearner\voting_parallel_tree_learner.cpp -> ./lightgbm\src\tr
eelearner
copying ../CMakeLists.txt -> ./lightgbm/
copying ../LICENSE -> ./
CMake Error at CMakeLists.txt:8 (PROJECT):
  Failed to run MSBuild command:

    MSBuild.exe

  to get the value of VCTargetsPath:

    Microsoft (R) Build Engine version 15.1.1012.6693
    Copyright (C) Microsoft Corporation. All rights reserved.

    Build started 7/16/2017 7:58:12 PM.
    Project "C:\Users\mbansa001c\LightGBM\python-package\build_cpp\CMakeFiles\3.
9.0-rc5\VCTargetsPath.vcxproj" on node 1 (default targets).
    C:\Users\mbansa001c\LightGBM\python-package\build_cpp\CMakeFiles\3.9.0-rc5\V
CTargetsPath.vcxproj(14,2): error MSB4019: The imported project "C:\Program File
s (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargets\Microso
ft.Cpp.Default.props" was not found. Confirm that the path in the <Import> decla
ration is correct, and that the file exists on disk.
    Done Building Project "C:\Users\mbansa001c\LightGBM\python-package\build_cpp
\CMakeFiles\3.9.0-rc5\VCTargetsPath.vcxproj" (default targets) -- FAILED.

    Build FAILED.

    "C:\Users\mbansa001c\LightGBM\python-package\build_cpp\CMakeFiles\3.9.0-rc5\
VCTargetsPath.vcxproj" (default target) (1) ->
      C:\Users\mbansa001c\LightGBM\python-package\build_cpp\CMakeFiles\3.9.0-rc5
\VCTargetsPath.vcxproj(14,2): error MSB4019: The imported project "C:\Program Fi
les (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargets\Micro
soft.Cpp.Default.props" was not found. Confirm that the path in the <Import> dec
laration is correct, and that the file exists on disk.

        0 Warning(s)
        1 Error(s)

    Time Elapsed 00:00:00.31


  Exit code: 1



-- Configuring incomplete, errors occurred!
See also "C:/Users/mbansa001c/LightGBM/python-package/build_cpp/CMakeFiles/CMake
Output.log".
CMake Error at CMakeLists.txt:8 (PROJECT):
  Failed to run MSBuild command:

    MSBuild.exe

  to get the value of VCTargetsPath:

    Microsoft (R) Build Engine version 15.1.1012.6693
    Copyright (C) Microsoft Corporation. All rights reserved.

    Build started 7/16/2017 7:58:13 PM.
    Project "C:\Users\mbansa001c\LightGBM\python-package\build_cpp\CMakeFiles\3.
9.0-rc5\VCTargetsPath.vcxproj" on node 1 (default targets).
    C:\Users\mbansa001c\LightGBM\python-package\build_cpp\CMakeFiles\3.9.0-rc5\V
CTargetsPath.vcxproj(14,2): error MSB4019: The imported project "C:\Program File
s (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargets\Microso
ft.Cpp.Default.props" was not found. Confirm that the path in the <Import> decla
ration is correct, and that the file exists on disk.
    Done Building Project "C:\Users\mbansa001c\LightGBM\python-package\build_cpp
\CMakeFiles\3.9.0-rc5\VCTargetsPath.vcxproj" (default targets) -- FAILED.

    Build FAILED.

    "C:\Users\mbansa001c\LightGBM\python-package\build_cpp\CMakeFiles\3.9.0-rc5\
VCTargetsPath.vcxproj" (default target) (1) ->
      C:\Users\mbansa001c\LightGBM\python-package\build_cpp\CMakeFiles\3.9.0-rc5
\VCTargetsPath.vcxproj(14,2): error MSB4019: The imported project "C:\Program Fi
les (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargets\Micro
soft.Cpp.Default.props" was not found. Confirm that the path in the <Import> dec
laration is correct, and that the file exists on disk.

        0 Warning(s)
        1 Error(s)

    Time Elapsed 00:00:00.33


  Exit code: 1



-- Configuring incomplete, errors occurred!
See also "C:/Users/mbansa001c/LightGBM/python-package/build_cpp/CMakeFiles/CMake
Output.log".
CMake Error at CMakeLists.txt:8 (PROJECT):
  Failed to run MSBuild command:

    MSBuild.exe

  to get the value of VCTargetsPath:

    Microsoft (R) Build Engine version 15.1.1012.6693
    Copyright (C) Microsoft Corporation. All rights reserved.

    Build started 7/16/2017 7:58:14 PM.
    Project "C:\Users\mbansa001c\LightGBM\python-package\build_cpp\CMakeFiles\3.
9.0-rc5\VCTargetsPath.vcxproj" on node 1 (default targets).
    C:\Users\mbansa001c\LightGBM\python-package\build_cpp\CMakeFiles\3.9.0-rc5\V
CTargetsPath.vcxproj(14,2): error MSB4019: The imported project "C:\Program File
s (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargets\Microso
ft.Cpp.Default.props" was not found. Confirm that the path in the <Import> decla
ration is correct, and that the file exists on disk.
    Done Building Project "C:\Users\mbansa001c\LightGBM\python-package\build_cpp
\CMakeFiles\3.9.0-rc5\VCTargetsPath.vcxproj" (default targets) -- FAILED.

    Build FAILED.

    "C:\Users\mbansa001c\LightGBM\python-package\build_cpp\CMakeFiles\3.9.0-rc5\
VCTargetsPath.vcxproj" (default target) (1) ->
      C:\Users\mbansa001c\LightGBM\python-package\build_cpp\CMakeFiles\3.9.0-rc5
\VCTargetsPath.vcxproj(14,2): error MSB4019: The imported project "C:\Program Fi
les (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargets\Micro
soft.Cpp.Default.props" was not found. Confirm that the path in the <Import> dec
laration is correct, and that the file exists on disk.

        0 Warning(s)
        1 Error(s)

    Time Elapsed 00:00:00.34


  Exit code: 1



-- Configuring incomplete, errors occurred!
See also "C:/Users/mbansa001c/LightGBM/python-package/build_cpp/CMakeFiles/CMake
Output.log".
Traceback (most recent call last):
  File "setup.py", line 175, in <module>
    url='https://github.com/Microsoft/LightGBM')
  File "C:\Anaconda3\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Anaconda3\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\Anaconda3\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 124, in run
    compile_cpp(use_mingw=self.mingw, use_gpu=self.gpu)
  File "setup.py", line 87, in compile_cpp
    raise Exception('Please install Visual Studio or MS Build first')
Exception: Please install Visual Studio or MS Build first

**Comment by guolinke** [comment]
@munitech4u 
from your log, it seems you didn't install the visual c++ compiler in MSBuild.
you should install it:

![image](https://user-images.githubusercontent.com/16040950/28248427-35e0afec-6a77-11e7-8ae1-f77a6df461d1.png)

**Comment by munitech4u** [comment]
I have it installed. I hope that is sufficient. I have added the path to windows environment variable as well. Do I need a reboot after installation?
![msbuild](https://user-images.githubusercontent.com/7777086/28248479-d10b3f42-6a62-11e7-9c00-213834391bc4.jpg)

**Comment by guolinke** [comment]
@munitech4u 
can you list the file in this path: ```C:\Program Fi
les (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargets\``` ?

**Comment by munitech4u** [comment]
I don't have VC folder inside IDE. Am I missing something here?

**Comment by guolinke** [comment]
@munitech4u 
As I said before, I think it means you didn't choose visual c++ when installing MSBuild.

**Comment by munitech4u** [comment]
Yea, that seemed to be the problem. I tried reinstalling and this time it worked. Thanks a lot!!
