### ISSUE TITLE
TypeError: Wrong type(ndarray) for label, should be list or numpy array

### ISSUE THREAD

**Issue by munitech4u** [Microsoft/LightGBM#700]
Please search your question on previous issues, stackoverflow or other search engines before you open a new one.

For bugs and unexpected issues, please provide following information, so that we could reproduce on our system.

## Environment info
Operating System:win-7
CPU: intel -core -i7
C++/Python/R version: Python 3.5

## Error Message:
TypeError: Wrong type(ndarray) for label, should be list or numpy array

## Reproducible examples

y_train=train[['target']].values
y_train.shape
Out[36]: (1000, 1)
![variables_details](https://user-images.githubusercontent.com/7777086/28264544-10aea278-6b09-11e7-943e-a8054a8f0c6b.jpg)

params = {
    'boosting_type': 'gbdt',
    'objective': 'binary',
    'metric': 'binary_logloss',
    'num_leaves': 31,
    'learning_rate': 0.05,
    'feature_fraction': 0.9,
    'bagging_fraction': 0.8,
    'bagging_freq': 5,
    'verbose': 0
}

feature_name = ['feature_' + str(col) for col in range(num_feature)]

gbm = lgb.train(params,
                train_lgb,
                num_boost_round=500,
                valid_sets=train_lgb,  # eval training data
                feature_name=feature_name
                )

## Steps to reproduce

Running these steps in sequence.

y_train is a one dimensional array. I believe that is a valid input for the lightgbm.

**Comment by guolinke** [comment]
@munitech4u 
I think  (1000, 1) is a 2D array.

**Comment by munitech4u** [comment]
Ok. I can see that as per the basic.py program, it checks for condition: len(data.shape) == 1

Do I need to convert it into one dimensional before feeding to lgb.train?

I was following the instructions on: https://github.com/Microsoft/LightGBM/blob/master/examples/python-guide/advanced_example.py

But it doesn't mention anything like that

**Comment by munitech4u** [comment]
Ok, though the example doesn't mention it.

This worked for me:

y=y_train.ravel()
train_lgb = lgb.Dataset(X, y)

**Comment by guolinke** [comment]
@munitech4u your data type is a Data Frame of pandas ? 

@wxchan Does pandas always use (n,1) as the shape of label ? If it does, maybe we should take some conversion for this.

**Comment by munitech4u** [comment]
yes it is a pandas dataframe and it always take the form (n,1) for data.values

**Comment by wxchan** [comment]
@munitech4u you are using two brackets. Using one will solve it. `y_train=train['target'].values`

@guolinke we have the conversion of pandas.Series, it's 1-d array.

**Comment by munitech4u** [comment]
Thanks, that is indeed the case

**Comment by munitech4u** [comment]
Change this: 
Y = train[['Made Donation in March 2007']] 
to >>
Y = train['Made Donation in March 2007']

**Comment by vivek2319** [comment]
Thank you.

**Comment by dmh-cs** [comment]
This definitely needs a better error message.
