### ISSUE TITLE
AttributeError: module 'lightgbm' has no attribute 'Dataset'

### ISSUE THREAD

**Issue by WuZhuoran** [Microsoft/LightGBM#706]
## Environment info
Operating System: `Windows 10`
CPU: `i7-4710MQ`
C++/Python/R version: `Python 3.5.2`

## Error Message:
```
Traceback (most recent call last):
  File "D:/Coding/github/DataFountain/VIPCOM/src/lightgbm.py", line 7, in <module>
    import lightgbm as lgb
  File "D:\Coding\github\DataFountain\VIPCOM\src\lightgbm.py", line 78, in <module>
    train_lgb = lgb.Dataset(dftrain, label=train_label)
AttributeError: module 'lightgbm' has no attribute 'Dataset'
```

## Reproducible examples
```python
RS = 1
ROUNDS = 500
lgb_params = {
    'objective': 'regression',
    'metric': 'rmse',
    'boosting': 'gbdt',
    'learning_rate': 0.01,  # small learn rate, large number of iterations
    'verbose': 0,
    'num_leaves': 2 ** 5,
    'bagging_fraction': 0.95,
    'bagging_freq': 1,
    'bagging_seed': RS,
    'feature_fraction': 0.7,
    'feature_fraction_seed': RS,
    'max_bin': 100,
    'max_depth': 7,
    'num_rounds': ROUNDS,
}

train_lgb = lgb.Dataset(dftrain, label=train_label)

cv_output = lgb.cv(lgb_params, train_lgb, num_boost_round=ROUNDS, verbose_eval=50, show_stdv=False, nfold=5)
print(cv_output[['train-rmse-mean', 'test-rmse-mean']])

```

**Comment by chivee** [comment]
please check https://github.com/Microsoft/LightGBM/issues/683

**Comment by WuZhuoran** [comment]
Hi @chivee 

I have already checked that issue, but that doesn't work for me.

I am sure that lightgbm is installed well.

Do you have a better idea?

**Comment by chivee** [comment]
What is your VC version ?

**Comment by WuZhuoran** [comment]
MSVC 2015 14.0.24215

**Comment by guolinke** [comment]
@WuZhuoran 
make sure your vc runtime is 64-bit.

another possible reason is your lightgbm installation is not complete. 
you can try to uninstall it, and re-install again (may need to `run as administrator` ) .

**Comment by chivee** [comment]
@WuZhuoran , Could you please also check your VC Runtime is x64 based version? and make sure your vc runtime was well set in your environments.

and if you are pretty sure you have lightgbm installed. you can try binary version first

**Comment by zouzias** [comment]
The issue here is that the name of your Python script is `lightgbm.py` which confuses Python at the statement `from lightgbm import Dataset`.

`  File "D:\Coding\github\DataFountain\VIPCOM\src\lightgbm.py", line 78, in <module>`
