### ISSUE TITLE
[R PACKAGE]doubt with lgb.importance and lgb.interprete

### ISSUE THREAD

**Issue by zheguzai100** [Microsoft/LightGBM#709]
@guolinke
 as said in syntax:
lgb.importance  -- Compute feature importance in a model
lgb.interprete -- Compute feature contribution for prediction
what's the difference between them indeed?? can u show me a simple example?? 
and which is the key part for feather selection?

**Comment by Laurae2** [comment]
Run the R manual doc examples to check the difference between both.

**Comment by guolinke** [comment]
I think the feature importance is a statistic from the model file, and it is based on the split-gain on training data.
The "feature contribution for prediction" is using the validation data to verify the model. It can be used for the checking of over-fitting. e.g. if a feature have a large gain in training, but small gain in validation, that feature could be a bad feature that cause the over-fitting. 

@yanyachen Is that right ?

**Comment by yanyachen** [comment]
The feature importance is the statistic for model performance on training data, it contains split-gain and split count.
the feature contribution is trying to explain the feature contribution for single row prediction. It's like "which feature drives this particular prediction by how far". Further detailed explanation can be found on here: http://blog.datadive.net/interpreting-random-forests/
I will send PR to refine documents and codes later. @guolinke

**Comment by zheguzai100** [comment]
@guolinke 
@yanyachen 
`lgb.interprete` compute the contribution of each feather for predictions, it's a influence element. and it has positive and negative directions.  while, `importance` seems to be `abs(interpretation)/sum(abs(interpretation))`  which is as same as influence computing in linear regression.   
Is this true ??

**Comment by Laurae2** [comment]
@zheguzai100 Just run the examples to check.

Interpretation is locally (by row), importance is globally (in general).

```r
> tree_interpretation <- lgb.interprete(model, test$data, 1:5)
> str(tree_interpretation)
List of 5
 $ :Classes ‘data.table’ and 'data.frame':	6 obs. of  2 variables:
  ..$ Feature     : chr [1:6] "stalk-root=club" "odor=none" "bruises?=bruises" "cap-shape=bell" ...
  ..$ Contribution: num [1:6] -55.55 25.12 17.63 7.22 3.52 ...
  ..- attr(*, ".internal.selfref")=<externalptr> 
 $ :Classes ‘data.table’ and 'data.frame':	13 obs. of  2 variables:
  ..$ Feature     : chr [1:13] "odor=none" "odor=anise" "stalk-root=club" "cap-color=pink" ...
  ..$ Contribution: num [1:13] 25.12 -17.67 7.62 -4.02 -3.81 ...
  ..- attr(*, ".internal.selfref")=<externalptr> 
 $ :Classes ‘data.table’ and 'data.frame':	6 obs. of  2 variables:
  ..$ Feature     : chr [1:6] "stalk-root=club" "odor=none" "bruises?=bruises" "cap-shape=bell" ...
  ..$ Contribution: num [1:6] -55.55 25.12 17.63 7.22 3.38 ...
  ..- attr(*, ".internal.selfref")=<externalptr> 
 $ :Classes ‘data.table’ and 'data.frame':	6 obs. of  2 variables:
  ..$ Feature     : chr [1:6] "stalk-root=club" "odor=none" "bruises?=bruises" "cap-shape=bell" ...
  ..$ Contribution: num [1:6] -55.55 25.12 17.63 7.22 3.52 ...
  ..- attr(*, ".internal.selfref")=<externalptr> 
 $ :Classes ‘data.table’ and 'data.frame':	13 obs. of  2 variables:
  ..$ Feature     : chr [1:13] "odor=none" "bruises?=bruises" "cap-surface=fibrous" "stalk-surface-below-ring=smooth" ...
  ..$ Contribution: num [1:13] -33.29 8.23 6.9 5.1 3.67 ...
  ..- attr(*, ".internal.selfref")=<externalptr> 
```

and the other one:

```r
> tree_imp1 <- lgb.importance(model, percentage = TRUE)
> tree_imp2 <- lgb.importance(model, percentage = FALSE)
> str(tree_imp1)
Classes ‘data.table’ and 'data.frame':	41 obs. of  4 variables:
 $ Feature  : chr  "odor=none" "stalk-root=club" "stalk-root=rooted" "spore-print-color=green" ...
 $ Gain     : num  0.6168 0.178 0.0877 0.0312 0.0224 ...
 $ Cover    : num  0.2012 0.1142 0.1003 0.087 0.0961 ...
 $ Frequency: num  0.0613 0.0613 0.0613 0.0613 0.0675 ...
 - attr(*, ".internal.selfref")=<externalptr> 
> str(tree_imp2)
Classes ‘data.table’ and 'data.frame':	41 obs. of  4 variables:
 $ Feature  : chr  "odor=none" "stalk-root=club" "stalk-root=rooted" "spore-print-color=green" ...
 $ Gain     : num  67465 19476 9589 3416 2453 ...
 $ Cover    : int  130260 73960 64960 56300 62218 12937 61040 55240 55197 765 ...
 $ Frequency: int  20 20 20 20 22 36 20 20 39 5 ...
 - attr(*, ".internal.selfref")=<externalptr>
```
