### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by aszalucha** [Microsoft/LightGBM#71]
I have a big train data in libsvm format (11GB) like: 
```
-1 1:1 2:1 3:1 4:1 5:1 6:1 7:1 8:1 9:1 10:1 11:1 12:1 13:1 14:1 15:1 16:1 17:1 18:1 19:1 20:1 21:1
-1 22:1 23:1 24:1 25:1 26:1 27:1 28:1 29:1 30:1 31:1 32:1 33:1 34:1 35:1 36:1 37:1 38:1 39:1 18:1 40:1 41:1
-1 42:1 43:1 44:1 3:1 45:1 46:1 47:1 48:1 49:1 50:1 10:1 51:1 52:1 53:1 54:1 55:1 56:1 38:1 18:1 57:1 58:1
+1 59:1 60:1 61:1 62:1 63:1 64:1 65:1 66:1 67:1 68:1 69:1 70:1 71:1 72:1 73:1 74:1 75:1 38:1 18:1 76:1 77:1
-1 78:1 79:1 80:1 3:1 81:1 82:1 83:1 84:1 85:1 86:1 10:1 87:1 88:1 89:1 90:1 91:1 92:1 93:1 94:1 95:1 96:1
```
and instance with 26GB RAM. Even with `use_two_round_loading = true` it runs out of RAM

```
[LightGBM] [Info] Finished loading parameters
Killed
```

So I tried to use it with `head -n10000` of train and validation. 
```
[LightGBM] [Info] Finished loading parameters
[LightGBM] [Info] Saving data to binary file train_sample.libsvm
Segmentation fault (core dumped)
```

It looks like train data were loaded but then program crashed. How can I track the reason?

**Comment by guolinke** [comment]
hi, @aszalucha: 
1. it seems your data using different feature indices in different row. Is this normal? How many features in your data?  #data * 20 ? 
2. can you shared this sampled top-10000 data to me? I will debug on it.
Thanks.

**Comment by aszalucha** [comment]
Yes, my data is very sparse, libfm's binary converter says that in the whole train data I have:
`num_rows=74907727     num_values=1573062267     num_features=16447701     min_target=-1     max_target=1`

The data sample top-10000 of train and validation I used is here https://www.dropbox.com/s/inb1bkz0qec2adf/tran_validation_sample.zip?dl=0

**Comment by guolinke** [comment]
I have fixed this in dev branch. you can checkout to dev branch and have a try.
I also reduce some memory cost in dev banch as well. And you can set ```histogram_pool_size=1024``` (unit is MB) to reduce memory cost. 

BTW, GBDT is not recommended when #features is very large.

**Comment by guolinke** [comment]
close for now. feel free to reopen if problem still exists.
