### ISSUE TITLE
A bug in libsvm format ?

### ISSUE THREAD

**Issue by MenglaiWang** [Microsoft/LightGBM#718]
My dataset consists of over 10 million samples by 57 feature columns in libsvm format. And the max_feature_idx is 57. When I use the csv format, max_feature_idx becomes 56.

**Comment by guolinke** [comment]
Did you use the 1-based (the index of first column starts from 1) libsvm format ?

**Comment by MenglaiWang** [comment]
@guolinke yes. So Is that the reason?

**Comment by guolinke** [comment]
yes. 
It is not a bug. we use the 0-based libsvm format.

**Comment by MenglaiWang** [comment]
Oh, thanks for answering! : )
