### ISSUE TITLE
num_class is missing from Configuration page

### ISSUE THREAD

**Issue by franklin5** [Microsoft/LightGBM#72]
The parameter num_class is missing from Configuration page:
https://github.com/Microsoft/LightGBM/wiki/Configuration

**Comment by franklin5** [comment]
num_leave should have been num_leaves in Tuning Parameters section:  https://github.com/Microsoft/LightGBM/wiki/Configuration#tuning-parameters

**Comment by guolinke** [comment]
Thanks, we add many features these days. will update the documents ASAP

**Comment by franklin5** [comment]
Thanks! Looking forward to see more features and amazing performances from lightGBM and your teams' contributions.

I am using the python binding to get started with lightGBM, https://github.com/ArdalanM/pyLightGBM

I personally do not want to reinvest my time and energy just for the sake of another language to build the workflow that has worked: hyperopt + xgboost/sklearn. So far, the pyLightGBM has served my purpose well. Cheers,

**Comment by chivee** [comment]
refer to #76 #11
