### ISSUE TITLE
Make issue - Install on OS X

### ISSUE THREAD

**Issue by Inho311** [Microsoft/LightGBM#722]
Hi,

I am a new machine learning learner, and trying to install LightGBM in RStudio, I got the following error (highlighted in bold below).
I don't really understand, but it seems there is an error with Apple Clang and Make. I have Xcode up to date as well. I have updated cmake to the 3.9.0 version via Homebrew, but I dont understand what is wrong.

Can you please help me ?

Thanks in advance!
Nicolas
------------------------------------------------------------------------------------ install_github("Microsoft/LightGBM", subdir = "R-package")
Downloading GitHub repo Microsoft/LightGBM@master
from URL https://api.github.com/repos/Microsoft/LightGBM/zipball/master
Installing lightgbm
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/1s/24913f111ml7kdpt08ppxrqh0000gn/T/Rtmpai7ABg/devtools7bf221cbbf06/Microsoft-LightGBM-ac975e7/R-package'  \
  --library='/Library/Frameworks/R.framework/Versions/3.4/Resources/library' --install-tests 

* installing *source* package ‘lightgbm’ ...
** libs
installing via 'install.libs.R' to /Library/Frameworks/R.framework/Versions/3.4/Resources/library/lightgbm
-- The C compiler identification is AppleClang 8.1.0.8020042
-- The CXX compiler identification is AppleClang 8.1.0.8020042
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
**_CMake Error at CMakeLists.txt:18 (message):
  AppleClang wasn't supported.  Please see
  https://github.com/Microsoft/LightGBM/wiki/Installation-Guide#osx_**

-- Configuring incomplete, errors occurred!
See also "/private/var/folders/1s/24913f111ml7kdpt08ppxrqh0000gn/T/Rtmpai7ABg/devtools7bf221cbbf06/Microsoft-LightGBM-ac975e7/R-package/src/build/CMakeFiles/CMakeOutput.log".
make: *** No rule to make target `_lightgbm'.  Stop.
Error in eval(ei, envir) : Cannot find lib_lightgbm.so
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/lightgbm’
Installation failed: Command failed (1)
Warning message:
GitHub repo contains submodules, may not function as expected!

**Comment by guolinke** [comment]
as said in the document: https://github.com/Microsoft/LightGBM/tree/master/R-package

you need to install gcc first  : https://github.com/Microsoft/LightGBM/wiki/Installation-Guide#osx

and run ```export CXX=g++-7 CC=gcc-7``` before installation
