### ISSUE TITLE
Error when installing lgbm (windows7)

### ISSUE THREAD

**Issue by germayneng** [Microsoft/LightGBM#728]
## Environment info
Operating System: windows 7
CPU:
R version: 

## Error Message:

![capture](https://user-images.githubusercontent.com/22788747/28606664-b768ff5c-720a-11e7-80fa-5d85c36d2b33.JPG)

## Steps to reproduce

```
git clone --recursive https://github.com/Microsoft/LightGBM
cd LightGBM/R-package
Rscript build_package.R
```

built the .tar.gz file and i installed it via Rstudio and got the error.

**Comment by guolinke** [comment]
Did you have rtools ?

**Comment by germayneng** [comment]
@guolinke yes i installed Rtools. 

on a side question, how do one obtain the lib_lightgbm.dll. i download it from https://github.com/Microsoft/LightGBM/releases

**Comment by guolinke** [comment]
@germayneng Did you use 64-bit R, Rtools, and windows 7 ? 

@Laurae2 any idea about this error ?

**Comment by germayneng** [comment]
@guolinke  yes windows 7 enterprise, Rtools 3.4 installed. I even reinstalled R and Rstudios so i only have 64 bit. 

Also, I am not able to set PATH variables. after setting them, cmd still does not recognize them

**Comment by guolinke** [comment]
@germayneng can you paste your PATH  ?

**Comment by guolinke** [comment]
@germayneng 
when I removing the Rtools from path, i got the similar error:
```
** libs
Warning: running command 'make -f "Makevars.win" -f "C:/PROGRA~1/R/R-34~1.1/etc/x64/Makeconf" -f "C:/PROGRA~1/R/R-34~1.1/share/make/winshlib.mk" SHLIB="lightgbm.dll" WIN=64 TCLBIN=64 OBJECTS=""' had status 127
ERROR: compilation failed for package 'lightgbm'
* removing 'C:/Program Files/R/R-3.4.1/library/lightgbm'
* restoring previous 'C:/Program Files/R/R-3.4.1/library/lightgbm'
```

So it seems you didn't install Rtools correctly.

**Comment by germayneng** [comment]
@guolinke 

![capture](https://user-images.githubusercontent.com/22788747/28631560-3a3aabf6-7260-11e7-9c56-a2999da08bca.PNG)


I am still getting the error u got. How do i ensure i installed Rtools correctly?

**Comment by germayneng** [comment]
i manage to solved the PATH variables and added Rtools as well as cmake 

now i am getting this error : 
![capture](https://user-images.githubusercontent.com/22788747/28632363-dae1fc9c-7262-11e7-964b-c1fdeb67d107.PNG)

**Comment by guolinke** [comment]
can you paste the text log instead of picture?
also, full log is needed since the installation could be acutally success .

**Comment by germayneng** [comment]
@guolinke sorry but how do i get the text log out?

**Comment by guolinke** [comment]
2 solutions to fix it:

1. install visual studio according to documents.

2. add the mingw64/bin insides Rtools to path

**Comment by germayneng** [comment]
> C:\Users\Germayne>cd Desktop\LightGBM\R-package
> 
> C:\Users\Germayne\Desktop\LightGBM\R-package>R CMD INSTALL --build . --no-multiarch
> * installing to library 'C:/Users/Germayne/Documents/R/win-library/3.4'
> * installing *source* package 'lightgbm' ...
> ** libs
> installing via 'install.libs.R' to C:/Users/Germayne/Documents/R/win-library/3.4/lightgbm
> CMake Error at C:/Program Files/CMake/share/cmake-3.9/Modules/CMakeMinGWFindMake.cmake:12 (message):
>   sh.exe was found in your PATH, here:
> 
>   C:/Rtools/bin/sh.exe
> 
>   For MinGW make to work correctly sh.exe must NOT be in your path.
> 
>   Run cmake from a shell that does not have sh.exe in your PATH.
> 
>   If you want to use a UNIX shell, then use MSYS Makefiles.
> 
> Call Stack (most recent call first):
>   CMakeLists.txt:9 (PROJECT)
> 
> 
> CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
> CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
> -- Configuring incomplete, errors occurred!
> Warning: running command 'cmake  -G "MinGW Makefiles"  ..' had status 1
> -- The C compiler identification is GNU 4.9.3
> -- The CXX compiler identification is GNU 4.9.3
> -- Check for working C compiler: C:/Rtools/mingw_64/bin/gcc.exe
> -- Check for working C compiler: C:/Rtools/mingw_64/bin/gcc.exe -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: C:/Rtools/mingw_64/bin/g++.exe
> -- Check for working CXX compiler: C:/Rtools/mingw_64/bin/g++.exe -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Found OpenMP_C: -fopenmp (found version "4.0")
> -- Found OpenMP_CXX: -fopenmp (found version "4.0")
> -- Configuring done
> -- Generating done
> -- Build files have been written to: C:/Users/Germayne/Desktop/LightGBM/R-package/src/build
> Scanning dependencies of target _lightgbm
> [  7%] [  7%] Building CXX object CMakeFiles/_lightgbm.dir/src/boosting/boosting.cpp.obj
> Building CXX object CMakeFiles/_lightgbm.dir/src/c_api.cpp.obj
> [ 10%] Building CXX object CMakeFiles/_lightgbm.dir/src/io/bin.cpp.obj
> [ 17%] Building CXX object CMakeFiles/_lightgbm.dir/src/io/config.cpp.obj
> [ 25%] [ 89%] Building CXX object CMakeFiles/_lightgbm.dir/src/lightgbm_R.cpp.obj
> Building CXX object CMakeFiles/_lightgbm.dir/src/boosting/gbdt.cpp.obj
> [ 89%] Building CXX object CMakeFiles/_lightgbm.dir/src/io/metadata.cpp.obj[ 89%] Building CXX object CMakeFiles/_lightgbm.dir/src/io/parser.cpp.obj[ 89%]
> [ 89%] [ 89%] Building CXX object CMakeFiles/_lightgbm.dir/src/network/linkers_mpi.cpp.obj[ 89%] [ 89%] [ 89%] Building CXX object CMakeFiles/_lightgbm.dir/src/treelearner/gpu_tree_learner.cpp.obj[ 89%] Building CXX object CMakeFiles/_lightgbm.dir/src/treelearner/serial_tree_learner.cpp.objBuilding CXX object CMakeFiles/_lightgbm.dir/src/io/dataset_loader.cpp.obj
> [ 89%] [ 89%]
> 
> [ 89%]
> Building CXX object CMakeFiles/_lightgbm.dir/src/network/linker_topo.cpp.obj[ 89%] Building CXX object CMakeFiles/_lightgbm.dir/src/treelearner/feature_parallel_tree_learner.cpp.objBuilding CXX object CMakeFiles/_lightgbm.dir/src/io/tree.cpp.obj
> Building CXX object CMakeFiles/_lightgbm.dir/src/network/linkers_socket.cpp.obj[ 89%]
> [ 89%] Building CXX object CMakeFiles/_lightgbm.dir/src/treelearner/data_parallel_tree_learner.cpp.objBuilding CXX object CMakeFiles/_lightgbm.dir/src/io/dataset.cpp.objBuilding CXX object CMakeFiles/_lightgbm.dir/src/network/network.cpp.obj
> Building CXX object CMakeFiles/_lightgbm.dir/src/boosting/prediction_early_stop.cpp.obj
> [ 89%] [ 89%]
> 
> Building CXX object CMakeFiles/_lightgbm.dir/src/boosting/gbdt_prediction.cpp.obj
> 
> 
> [ 89%]
> Building CXX object CMakeFiles/_lightgbm.dir/src/objective/objective_function.cpp.obj[ 89%]
> Building CXX object CMakeFiles/_lightgbm.dir/src/application/application.cpp.objBuilding CXX object CMakeFiles/_lightgbm.dir/src/metric/metric.cpp.objBuilding CXX object CMakeFiles/_lightgbm.dir/src/metric/dcg_calculator.cpp.obj
> 
> 
> C:\Users\Germayne\Desktop\LightGBM\R-package\src\src\c_api.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
>  #include <LightGBM/utils/openmp_wrapper.h>
>  ^
> C:\Users\Germayne\Desktop\LightGBM\R-package\src\src\boosting\boosting.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
>  #include <LightGBM/boosting.h>
>  ^
> C:\Users\Germayne\Desktop\LightGBM\R-package\src\src\lightgbm_R.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
>  #include <vector>
>  ^
> C:\Users\Germayne\Desktop\LightGBM\R-package\src\src\application\application.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
>  #include <LightGBM/application.h>
>  ^
> C:\Users\Germayne\Desktop\LightGBM\R-package\src\src\boosting\gbdt.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
>  #include "gbdt.h"
>  ^
> cc1plus.exe: warning: unrecognized command line option "-Wno-ignored-attributes"
> C:\Users\Germayne\Desktop\LightGBM\R-package\src\src\boosting\gbdt_prediction.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
>  #include "gbdt.h"
>  ^
> C:\Users\Germayne\Desktop\LightGBM\R-package\src\src\boosting\prediction_early_stop.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
>  #include <LightGBM/prediction_early_stop.h>
>  ^
> cc1plus.exe: warning: unrecognized command line option "-Wno-ignored-attributes"
> cc1plus.exe: warning: unrecognized command line option "-Wno-ignored-attributes"
> C:\Users\Germayne\Desktop\LightGBM\R-package\src\src\io\bin.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
>  #include <LightGBM/utils/common.h>
>  ^
> cc1plus.exe: warning: unrecognized command line option "-Wno-ignored-attributes"
> cc1plus.exe: warning: unrecognized command line option "-Wno-ignored-attributes"
> cc1plus.exe: warning: unrecognized command line option "-Wno-ignored-attributes"
> cc1plus.exe: warning: unrecognized command line option "-Wno-ignored-attributes"
> C:\Users\Germayne\Desktop\LightGBM\R-package\src\src\io\config.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
>  #include <LightGBM/config.h>
>  ^
> C:\Users\Germayne\Desktop\LightGBM\R-package\src\src\io\dataset.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
>  #include <LightGBM/dataset.h>
>  ^
> C:\Users\Germayne\Desktop\LightGBM\R-package\src\src\io\dataset_loader.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
>  #include <LightGBM/utils/openmp_wrapper.h>
>  ^
> C:\Users\Germayne\Desktop\LightGBM\R-package\src\src\io\metadata.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
>  #include <LightGBM/dataset.h>
>  ^
> cc1plus.exe: warning: unrecognized command line option "-Wno-ignored-attributes"
> C:\Users\Germayne\Desktop\LightGBM\R-package\src\src\io\parser.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
>  #include "parser.hpp"
>  ^
> cc1plus.exe: warning: unrecognized command line option "-Wno-ignored-attributes"
> cc1plus.exe: warning: unrecognized command line option "-Wno-ignored-attributes"
> cc1plus.exe: warning: unrecognized command line option "-Wno-ignored-attributes"
> C:\Users\Germayne\Desktop\LightGBM\R-package\src\src\io\tree.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
>  #include <LightGBM/tree.h>
>  ^
> cc1plus.exe: warning: unrecognized command line option "-Wno-ignored-attributes"
> C:\Users\Germayne\Desktop\LightGBM\R-package\src\src\metric\dcg_calculator.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
>  #include <LightGBM/metric.h>
>  ^
> cc1plus.exe: warning: unrecognized command line option "-Wno-ignored-attributes"
> cc1plus.exe: warning: unrecognized command line option "-Wno-ignored-attributes"
> C:\Users\Germayne\Desktop\LightGBM\R-package\src\src\metric\metric.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
>  #include <LightGBM/metric.h>
>  ^
> cc1plus.exe: warning: unrecognized command line option "-Wno-ignored-attributes"
> C:\Users\Germayne\Desktop\LightGBM\R-package\src\src\objective\objective_function.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
>  #include <LightGBM/objective_function.h>
>  ^
> C:\Users\Germayne\Desktop\LightGBM\R-package\src\src\network\linker_topo.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
>  #include <LightGBM/network.h>
>  ^
> C:\Users\Germayne\Desktop\LightGBM\R-package\src\src\network\linkers_mpi.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
>  #ifdef USE_MPI
>  ^
> cc1plus.exe: warning: unrecognized command line option "-Wno-ignored-attributes"
> cc1plus.exe: warning: unrecognized command line option "-Wno-ignored-attributes"
> cc1plus.exe: warning: unrecognized command line option "-Wno-ignored-attributes"
> C:\Users\Germayne\Desktop\LightGBM\R-package\src\src\network\linkers_socket.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
>  #ifdef USE_SOCKET
>  ^
> cc1plus.exe: warning: unrecognized command line option "-Wno-ignored-attributes"
> C:\Users\Germayne\Desktop\LightGBM\R-package\src\src\network\network.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
>  #include <LightGBM/network.h>
>  ^
> C:\Users\Germayne\Desktop\LightGBM\R-package\src\src\treelearner\data_parallel_tree_learner.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
>  #include "parallel_tree_learner.h"
>  ^
> C:\Users\Germayne\Desktop\LightGBM\R-package\src\src\treelearner\feature_parallel_tree_learner.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
>  #include "parallel_tree_learner.h"
>  ^
> [ 92%] Building CXX object CMakeFiles/_lightgbm.dir/src/treelearner/voting_parallel_tree_learner.cpp.obj
> C:\Users\Germayne\Desktop\LightGBM\R-package\src\src\treelearner\gpu_tree_learner.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
>  #ifdef USE_GPU
>  ^
> [ 96%] Building CXX object CMakeFiles/_lightgbm.dir/src/treelearner/tree_learner.cpp.obj
> cc1plus.exe: warning: unrecognized command line option "-Wno-ignored-attributes"
> cc1plus.exe: warning: unrecognized command line option "-Wno-ignored-attributes"
> cc1plus.exe: warning: unrecognized command line option "-Wno-ignored-attributes"
> cc1plus.exe: warning: unrecognized command line option "-Wno-ignored-attributes"
> cc1plus.exe: warning: unrecognized command line option "-Wno-ignored-attributes"
> C:\Users\Germayne\Desktop\LightGBM\R-package\src\src\treelearner\serial_tree_learner.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
>  #include "serial_tree_learner.h"
>  ^
> C:\Users\Germayne\Desktop\LightGBM\R-package\src\src\treelearner\voting_parallel_tree_learner.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
>  #include "parallel_tree_learner.h"
>  ^
> C:\Users\Germayne\Desktop\LightGBM\R-package\src\src\treelearner\tree_learner.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
>  #include <LightGBM/tree_learner.h>
>  ^
> cc1plus.exe: warning: unrecognized command line option "-Wno-ignored-attributes"
> cc1plus.exe: warning: unrecognized command line option "-Wno-ignored-attributes"
> cc1plus.exe: warning: unrecognized command line option "-Wno-ignored-attributes"
> [100%] Linking CXX shared library ..\lib_lightgbm.dll
> [100%] Built target _lightgbm
> Found library file: C:/Users/Germayne/Desktop/LightGBM/R-package/src/lib_lightgbm.dll to move to C:/Users/Germayne/Documents/R/win-library/3.4/lightgbm/libs/x64** R
> ** data
> ** demo
> ** preparing package for lazy loading
> Warning: package 'R6' was built under R version 3.4.1
> ** help
> *** installing help indices
> ** building package indices
> ** testing if installed package can be loaded
> Warning: package 'R6' was built under R version 3.4.1
> * MD5 sums
> packaged installation of 'lightgbm' as lightgbm_2.0.4.zip
> * DONE (lightgbm)

**Comment by germayneng** [comment]
@guolinke  After adding the PATH you mentioned (add the mingw64/bin insides Rtools to path) i got the log above. Is it completed?

**Comment by guolinke** [comment]
yeah, it is success

**Comment by germayneng** [comment]
@guolinke  many thanks for taking your time out for this :) cheers

**Comment by Laurae2** [comment]
@guolinke l'll add it to the R readme and to the FAQ for compilation in R and PATH requirement (tell user to not skip PATH during installation) when I'll get on a computer.
