### ISSUE TITLE
Load lib_lightgbm.so in Python or R

### ISSUE THREAD

**Issue by Lchiffon** [Microsoft/LightGBM#73]
When I using OpenMPI to build LightGBM, I cannot load the `lib_lightgbm.so` in R or Python:
```
import ctypes
lib = ctypes.cdll.LoadLibrary('lib_lightgbm.so')
```
`OSError: lib_lightgbm.so: undefined symbol: ompi_mpi_comm_world`

```
library(Rcpp)
dyn.load("~/git/LightGBM/lib_lightgbm.so")
```
`...lib_lightgbm.so: undefined symbol: ompi_mpi_comm_world`

However when I build lightGBM without openMPI, these methods can load the lib_lightgbm.so as normal.

Python 2.7.6
R 3.2.5
Unbuntu 14.04 x64
mpirun (Open MPI) 2.0.1

**Comment by guolinke** [comment]
@Lchiffon I forget to link to openmpi when building .so.  
Have updated cmake. can you try it again?
