### ISSUE TITLE
LightGBM benchmarks on Microsoft Blog

### ISSUE THREAD

**Issue by Laurae2** [Microsoft/LightGBM#736]
Did you get the same performance issue as in https://github.com/Microsoft/LightGBM/issues/460 ?

https://blogs.technet.microsoft.com/machinelearning/2017/07/25/lessons-learned-benchmarking-fast-machine-learning-algorithms/

I am getting for 31 leaves on Higgs dataset:

i7-7700K 4.5/4.4 GHz vs 2x 10 core Ivy Bridge 3.3/2.7 GHz:

| Threads | 200 iters i7 | 200 iters 2x Xeon |
| ---: | ---: | ---: |
| 1 | 270 | 562 |
| 2 | 154 | 298 |
| 3 | 115 | 224 |
| 4 | 100 | 162 |
| 5 | 103 | 135 |
| 6 | 98 | |
| 7 | 93 | |
| 8 | 88 | |
| 10 | | 98 |
| 20 | | 121 |
| 40 | | 134 |

For xgboost:

i7-7700K 4.5/4.4 GHz vs 20 core Ivy Bridge 3.3/2.7 GHz:

| Threads | 200 iters i7 | 200 iters 2x Xeon |
| ---: | ---: | ---: |
| 1 | 381 | 758 |
| 2 | 240 | 453 |
| 3 | 191 | 347 |
| 4 | 162 | 316 |
| 5 | 153 | 260 |
| 6 | 144 | |
| 7 | 138 | |
| 8 | 138 | |
| 10 | | 197 |
| 20 | | 179 |
| 40 | | 177 |

**Comment by guolinke** [comment]
@Laurae2 yeah, we find the multi-threading performance is not good (compared with local machine) in azure. We had contacted Azure team for this issue. 
And the problem seems is caused by the memory speed.
