### ISSUE TITLE
MATLAB Support / Wrapper

### ISSUE THREAD

**Issue by RoyiAvital** [microsoft/LightGBM#743]
Hello,

Any chance you add MATLAB support for LightGBM?  
Maybe somekind of a wrapper to allow basic features under MATLAB?

Thank You.

**Comment by chivee** [comment]
Hi @RoyiAvital , we don't have any plan for extending to MATLAB yet,

I'm not quite sure but I guess you can calling python function using [this](https://www.mathworks.com/help/matlab/call-python-libraries.html).

**Comment by RoyiAvital** [comment]
Yea,
Well that would be a big "Bypass" to do.  

I wish you reconsider this.
Even well documented DLL could work and MATLAB support will expose this great package to many more users.

Thank You.

**Comment by ungil** [comment]
I just published a wrapper at https://github.com/ungil/LightGBM-MATLAB

It's not really tested, so there may be plenty of issues, and a few functions are not yet done (see TODO comments).

**Comment by RoyiAvital** [comment]
@ungil , This is great.
Hopefully will be able to check it soon and report.

Thank You.

**Comment by lopezco** [comment]
By any chance, is someone working on this?

**Comment by StrikerRUS** [comment]
Closed in favor of being in #2302. We decided to keep all feature requests in one place.

Welcome to contribute this feature! Please re-open this issue (or post a comment if you are not a topic starter) if you are actively working on implementing this feature.
