### ISSUE TITLE
Test of missing value handling

### ISSUE THREAD

**Issue by Laurae2** [Microsoft/LightGBM#744]
This issue is to test fixes for issue #122. The case below is the worst scenario ever existing when 0 and NAs are mixed.

Users can run this demo in R to test the conflict between zero values and missing values.

Objective to have:

- [x] Pass test (AUC = 1)

```r
library(matrixStats)

generated <- matrix(nrow = 10000, ncol = 10)
for (i in 1:10) {
  set.seed(i)
  generated[sample.int(10000, 1000, replace = FALSE), i] <- 0
}

gen_labels <- as.numeric(rowAnys(generated, value = 0, na.rm = TRUE)) # 6534
to_sort <- order(gen_labels)
generated <- generated[to_sort, ]
gen_labels <- gen_labels[to_sort]

# devtools::install_github("Microsoft/LightGBM/R-package")
# lgb.unloader(wipe = TRUE)
library(lightgbm)

dtrain <- lgb.Dataset(generated, label = gen_labels)
valids <- list(test = dtrain)

model <- lgb.train(list(objective = "regression",
                        metric = "auc",
                        min_data = 1,
                        learning_rate = 1),
                   dtrain,
                   2,
                   valids,
                   early_stopping_rounds = 2)

plot(predict(model, generated))
```

If you are getting this, there is a conflict between zeroes and missing values:

```r
[LightGBM] [Info] Total Bins 0
[LightGBM] [Info] Number of data: 10000, number of used features: 0
[LightGBM] [Info] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Trained a tree with leaves=1 and max_depth=1
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements.
[1]:	test's auc:0.5 
[LightGBM] [Info] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Trained a tree with leaves=1 and max_depth=1
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements.
[2]:	test's auc:0.5
```

![image](https://user-images.githubusercontent.com/9083669/28716236-57133a08-739c-11e7-825a-5fb661e9dfa8.png)

This is xgboost good behavior for comparison:

```r
library(xgboost)

dtrain <- xgb.DMatrix(generated, label = gen_labels)
valids <- list(test = dtrain)

model <- xgb.train(list(objective = "reg:linear",
                        eval_metric = "auc",
                        eta = 1),
                   dtrain,
                   nrounds = 2,
                   valids,
                   early_stopping_rounds = 2)

plot(predict(model, generated))
```

```r
[1]	test-auc:0.864019 
Will train until test_auc hasn't improved in 2 rounds.

[2]	test-auc:1.000000
```

(convergence not over, but we reached the separation point):

![image](https://user-images.githubusercontent.com/9083669/28716353-0eeb179a-739d-11e7-8655-407206585a43.png)

**Comment by guolinke** [comment]
This is the worst case (need to use NA and zero to split data). 
But it is not a usual case in real data, right ?

**Comment by Laurae2** [comment]
@guolinke It is the most common case for real data when users don't know how to encode properly zero values (this happens a lot, especially with old school Excel users / research beginners / fresh graduates).

I would say it might be better if LightGBM handles NAs on the most extreme possible values (like the last bin), such as:

```
    Bin | New | Old
Bin 001 | NAs |   0 + NAs
Bin 002 |   0 |   x
Bin 003 |   x |   x
Bin 004 |   x |   x
...
Bin 254 |   x |   x
Bin 255 |   x |   x
```

I currently do not know how the wrappers are working, but we may let the wrappers do the correct transformation of data if needed.

Example of potential rules:

* Non-negative input
* Non-zero input unless "NA" (0)

But this would make LightGBM extremely difficult to use on large datasets, as processing them would take a long time (potentially longer than just training).

Another possibility: accept only sparse matrices as input, which is the most obvious way to deal with this problem. Sparse matrices have missing values, and those missing values must be the correct one. Currently, the non-expert user will not encounter this issue until they attempt to interpret the model and notice the issue of 0 / NAs values (eventually).

Again another possibility: warn the user in front page or in documentations about zeroes as missing value because the expected input format is interpreted like a sparse matrix.

**Comment by guolinke** [comment]
@Laurae2 I will try to fix it.
BTW, will it be a problem if force using 'na' as missing value ?

**Comment by Laurae2** [comment]
@guolinke If the R/Python wrappers can handle NA as 'na' it should be fine.

I think we may also add an option "missing" like xgboost in that case (specify if it is NA, or a specific value like 0, etc.).

Example:

* Sparse matrix: what is missing = missing elements in the sparse matrix, ignore "missing" parameter
* Dense matrix: what is missing = by default NA, else "missing" parameter is considered missing

**Comment by guolinke** [comment]
@Laurae2 
I will only allow NA as missing in c++ side. Or it will increase many complexity. 
I think using arbitrary values as missing can be processed in python / R side. (e.g. convert them to NA first).

**Comment by guolinke** [comment]
For sparse matrices, it is okay to just using the unshown values as missing ? or need to explicitly contain n/a ?

**Comment by Laurae2** [comment]
@guolinke For sparse matrices, only allow unknown values as missing as they are implicit NAs.

**Comment by guolinke** [comment]
@Laurae2 
if doing this, how can user use 0 and na at the same time ?

**Comment by Laurae2** [comment]
@guolinke Sparse matrices are supposed to allow arbitrary missing values. In R and Python, we can have zeroes and missing values at the same time in a sparse matrix of type dgCMatrix (not sure if other formats allow it, but I think LightGBM does not allow the other formats anyway).

**Comment by guolinke** [comment]
if zeroes and missing values at the same time in a sparse matrix, which values will be ignored ? zero or missing ?

**Comment by Laurae2** [comment]
missing values are ignored, zeroes are intrepreted like other numbers (not missing).

**Comment by guolinke** [comment]
@Laurae2 
oh, it is bad .. so as the libsvm format ? 
So the sparse matrices will have two behaves: 1. ignore the zero values if not missing, 2. ignore the n/a value if having missing .

**Comment by guolinke** [comment]
I just test it in python:
```
>>> import numpy as np
>>> import scipy.sparse as sp
>>> X_train = np.array([[ 1., -1.,  np.nan],
...     [ 2.,  0.,  0.],
...     [ 0.,  1., -1.]])
>>> s = sp.csr_matrix(X_train)
>>> s.data
array([  1.,  -1.,  nan,   2.,   1.,  -1.])
>>>
```
The zeros are ignored.

**Comment by Laurae2** [comment]
@guolinke The default behavior of sparse matrices are 0s as missing values, you can write a 0 on the nan you have.

See this: https://www.kaggle.com/laurae2/sparse-matrix-with-explicit-zeroes

**Comment by guolinke** [comment]
Test in R:
```
> library('Matrix')
> A = Matrix(
+    c(2, 0, 0, 1, NA, 7), # the data elements
+    nrow=2,              # number of rows
+    ncol=3,              # number of columns
+    byrow = FALSE,
+    sparse = TRUE)        # fill matrix by rows
>
> A
2 x 3 sparse Matrix of class "dgCMatrix"

[1,] 2 . NA
[2,] . 1  7
```

**Comment by guolinke** [comment]
@Laurae2 yeah, But the default behave is ignored the zeros. We cannot expect user ignore the n/a explicitly. 

maybe I can try to add a parameter: ```zero_as_missing```. default is false.
And we treat all unshown values in sparse matrics (and libsvm) as zero.
