### ISSUE TITLE
prediction results for classification are not probability?

### ISSUE THREAD

**Issue by pyr-revs** [Microsoft/LightGBM#75]
With latest version, prediction results for classification can have minus value (value<0), but I want probability for results (0 - 1).
(working on AWS EC2 AMI)

`
git clone --recursive https://github.com/Microsoft/LightGBM ; cd LightGBM
git checkout 0702b2ffbff9148c30768f23eaffc84dcb45cae4 # Nov 11, 2016 change GetTrainnigScore to non-const. # https://github.com/Microsoft/LightGBM/commit/0702b2ffbff9148c30768f23eaffc84dcb45cae4
mkdir build ; cd build
cmake .. 
make -j 

cd ..
cp ./lightgbm examples/binary_classification/
cd examples/binary_classification/
./lightgbm config=train.conf
./lightgbm config=predict.conf
head LightGBM_predict_result.txt
`

0.571395
**-0.057555**
**-1.24912**
0.0390908
**-0.949834**
**-0.764455**
**-0.656284**
0.0431959
0.928821
**-0.263096**

With older version (Nov 8, 2016), prediction results for classification are probability.

`
git clone --recursive https://github.com/Microsoft/LightGBM ; cd LightGBM
git checkout 785398a2443be461bd0f58c680b285852113232e # Commits on Nov 8, 2016 https://github.com/Microsoft/LightGBM/commit/785398a2443be461bd0f58c680b285852113232e
mkdir build ; cd build
cmake .. 
make -j 

cd ..
cp ./lightgbm examples/binary_classification/
cd examples/binary_classification/
./lightgbm config=train.conf
./lightgbm config=predict.conf
head LightGBM_predict_result.txt

0.758192
0.471254
0.075981
0.519535
0.130146
0.178153
0.212058
0.521585
0.865022
0.371406
`

**Comment by guolinke** [comment]
have fixed. can you try it again?

**Comment by pyr-revs** [comment]
fix verified, thanks for quick fix!
