### ISSUE TITLE
feature importance in saved model ignores the num_iteration parameter (uses full model)

### ISSUE THREAD

**Issue by ungil** [Microsoft/LightGBM#750]
Feature importance reported by LGBM_BoosterSaveModel and LGBM_BoosterSaveModelToString is always for the full model, ignoring the num_iteration parameter used to limit the number of trees reported.

**Comment by guolinke** [comment]
@wxchan

**Comment by wxchan** [comment]
@ungil your actual issue is`feature_importance doesn't have num_iteration option`, right?

**Comment by ungil** [comment]
This is not an issue relative to the python API. I'm talking about to the contents of the model.txt file, say, produced by the API call LGBM_BoosterSaveModel.

Of course, it affects also the python function save_model. For example if we add to examples/python-guide/simple_example.py the line
```
gbm.save_model('model1.txt',1)
```
the file model1.txt will contain only trees 0 and 1, while model.txt contains trees 0-20. However, the "feature importances:" section at the end is identical. The importance is always for the full model, ignoring num_iteration. From src/boosting/gbdt.cpp:

```
std::string GBDT::SaveModelToString(int num_iteration) const {
  [...]
  std::vector<std::pair<size_t, std::string>> pairs = FeatureImportance();
```

**Comment by wxchan** [comment]
@ungil ok, I got it. It should be easy to fix, do you want to submit a pr? or I can fix it later.

**Comment by ungil** [comment]
I've never used pull requests and I've not really looked at how to fix the issue. It may be easier for you to take care of this, thank you. Anyway it's not a critical bug, I just noticed by chance that the feature importance reported in the file was incorrect/misleading.

**Comment by wxchan** [comment]
@ungil ok, I will do it.
