### ISSUE TITLE
Should the categorical feature be int ?

### ISSUE THREAD

**Issue by yananchen1989** [Microsoft/LightGBM#751]
`train_data = lgb.Dataset(data, label=label, feature_name=['c1', 'c2', 'c3'], categorical_feature=['c3'])`
In the construction of lgb.Dataset, we can specify some columns as categorical feature.
In the example above, what the c3 feature's dtype should be ?  Since category feature exists in the train_x, which is a array and all the column are float. Although the category features are int, when I add them in the train_x array, their type become float. So I am not sure whether it will defect the function of specifying categorical features of lightGBM.
Thanks.

**Comment by guolinke** [comment]
yeah, it should be int type, but converting to float is okay (the precision is 2^23 for 32-bit float). 
LightGBM will force convert the categorical feature to int type.
