### ISSUE TITLE
Is there any method to solve the memory overload problem ?

### ISSUE THREAD

**Issue by yananchen1989** [Microsoft/LightGBM#752]
Hi team. Since the train data is to large to load in my laptop's memory, is there any way to load it from external memory? In xgboost, external memory method can solve the problem that too large the dataset to load in.
So currently, I want to know whether LightGBM has similar function. Thanks.

**Comment by guolinke** [comment]
@yananchen1989 
you can try use ```two_round=true``` , which can reduce the memory usage when loading data from file.
