### ISSUE TITLE
c_api & python: clarification

### ISSUE THREAD

**Issue by ArdalanM** [Microsoft/LightGBM#76]
Hi,

I am working on using `c_api.cpp` to improve the current python binding for LightGBM.
The implementation of `c_api.cpp` is really close to what already exist with xgboost thus it help a lot to better understand your version, thanks for that.

I am planning on creating two classes that will be equivalent to [`Booster()`](https://github.com/dmlc/xgboost/blob/master/python-package/xgboost/core.py#L633) and [`DMatrix()`](https://github.com/dmlc/xgboost/blob/master/python-package/xgboost/core.py#L211). However I m having hard time understanding how to use some `c_api.cpp` functions. 

I have created a [gist](https://gist.github.com/ArdalanM/92f115d698d9101d662a1b68b90bfd32) to explain my problems (the script work if you want to try it):

- [L55](https://gist.github.com/ArdalanM/92f115d698d9101d662a1b68b90bfd32#file-train_from_numpy_array-py-L55): What `reference` parameter stands for ?
- [L56](https://gist.github.com/ArdalanM/92f115d698d9101d662a1b68b90bfd32#file-train_from_numpy_array-py-L56): Is it the proper way to create validation data ?
- [L73](https://gist.github.com/ArdalanM/92f115d698d9101d662a1b68b90bfd32#file-train_from_numpy_array-py-L73): How can I use `LGBM_BoosterEval` to evaluate both `train` and `test` data ? 

Thanks you !

**Comment by wxchan** [comment]
- L55: see comment [here](https://github.com/Microsoft/LightGBM/blob/master/include/LightGBM/c_api.h#L53)
- L56: you should read this script, [here](https://github.com/Microsoft/LightGBM/blob/master/tests/c_api_test/test.py#L181), be careful about DatasetFree
- L73: do it separately: `LIB.LGBM_BoosterEval(booster, 0, ...)` then `LIB.LGBM_BoosterEval(booster, 1, ...)`...

Perhaps you could let the owner design official python binding first.

**Comment by guolinke** [comment]
@ArdalanM 
Thanks for the @wxchan , I will give more details:
1. reference is used to construct validation data.
2. see in this line, https://github.com/Microsoft/LightGBM/blob/master/tests/c_api_test/test.py#L178
you should use train-set as reference to construct validation data.
3. use data_idx to get evaluation on different data. 0 means training data. 1 means 1st validation data, ...

**Comment by ArdalanM** [comment]
@guolinke, @wxchan, thanks for the clarification, helped a lot.

@wxchan, I am looking forward using the official python binding :+1: 

Thanks
