### ISSUE TITLE
Output model from Python to C/C++ in if/else format

### ISSUE THREAD

**Issue by sami043** [Microsoft/LightGBM#769]
Is there any built in method to export the model to .c/.cpp in if/else format? I could potentially parse the text model but that may be a little more prone to error. I saw on here someone had created a python script to do it for binary but for multiclaas it requires modifications. Specifically, what does a decision type of '2' represent?

**Comment by guolinke** [comment]
We have this feature. 
refer to our test here: https://github.com/Microsoft/LightGBM/tree/master/tests/cpp_test

BTW, the decision_type = 2 is out of date now. maybe you need to retrain your model with the latest code. 

@wxchan can you add more documents for the if-else conversion ?

**Comment by sami043** [comment]
I just built the latest lightGBM yesterday so that's strange that I am getting that decision type. With save_model?

**Comment by guolinke** [comment]
@sami043 It is updated today. decision_type is still there, but its value range is changed.
if you model file has ```num_cat``` field, it is up to date.

**Comment by wxchan** [comment]
@sami043 you can add `convert_model=SOME_PATH` and `convert_model_language=cpp` to params , 1st is output address and 2nd is output language(now c++ is only option). And you need to re-compile c++ and python to make it work.

I actually never tried it from python. You can take a try.

@guolinke I will write some docs maybe tomorrow.

**Comment by sami043** [comment]
@wxchan,

params = {
'task': 'train',
'convert_model_language': 'cpp',
'convert_model': 'C:\Some\Path\'
}

did not yield any outputs.

**Comment by wxchan** [comment]
@sami043 sorry, I forgot. It is only implemented in command line version now.

**Comment by sami043** [comment]
@wxchan 

Thanks for the quick replies.

Are there plans to expand it to non-command line later on? Or would it be possible to load a .txt model through the command line interface and export the .cpp code?

**Comment by wxchan** [comment]
@sami043 for 2nd one, yes, set `task : convert_model`, you can see #469 

for 1st one, maybe in the future, I am a little busy these days.

**Comment by sami043** [comment]
That did the trick! Thanks!

**Comment by beutlgb** [comment]
Hey,
I have a model.txt file, i understand thet i can use the CLI to convert it to an if-else code. but i didnt understand exactly how to do it.
can you write the command line i need to use to convert the model.txt file. 
can i do this from the pyhton interface?
Thanks very much'
Great package!!

**Comment by SoftwareApe** [comment]
Is there also a guide somewhere on how to use the converted C++ model? I can't find anything using Google.
