### ISSUE TITLE
[R] lgb.Dataset should not remember parameter passed from lgb.train 

### ISSUE THREAD

**Issue by guolinke** [Microsoft/LightGBM#775]
@wxchan @Laurae2 can you help to fix this ?

**Comment by wxchan** [comment]
@guolinke I find out a new question. What about feature_name and categorical_feature from lgb.train? Should they be remembered by Dataset?

**Comment by guolinke** [comment]
@wxchan 
I think there are some parameters (like categorical_feature, ... ) cannot be changed after dataset is constructed, and lgb.train will construct the dataset. 

So maybe a new solution is, we try to use dataset.param + param_from_lgb_train to construct dataset first. If it fails, we remove the parameter from lgb_train, otherwise we add it to the dataset.param.

**Comment by wxchan** [comment]
@guolinke can we seperate two kind of params: for Dataset and for Booster?

**Comment by wxchan** [comment]
@guolinke I guess I over-think this. The params are only updated in `train_set._update_params(params)`, I can just make a copy of original one and copy it back after training.

**Comment by Laurae2** [comment]
@guolinke I think we should separate dataset creation and training like xgboost did, it allows to avoid mistakes when using a lgb.Dataset straight away for the training.

Or, another solution:

* When training, copy lgb.Dataset (do not use the original one)
* Perform dataset construction on that copy so the original lgb.Dataset is intact

**Comment by guolinke** [comment]
@Laurae2 We construct Dataset in lgb.train is because it can avoid user to specific many "reference", 

Copying a Dataset is also not trivial, e.g. we need to write more codes to manage the raw memories, since many Datasets may share the same pointer(handle). And it will cost more memories.

So the simple pop up the train_params after training is much easier.
