### ISSUE TITLE
LightGBM does not run inside Azure ML R script

### ISSUE THREAD

**Issue by zenkzz** [Microsoft/LightGBM#777]
When using a LightGBM R package in Azure ML I get the following error:

    [Error]         +++ NT HARD ERROR (0xc0000139) +++
    [Error]             Parameter 0: 0x4ad4bc8 [log2f]
    [Error]             Parameter 1: 0x4b5e2e8 [C:\src\lightgbm\libs\x64\lib_lightgbm.dll]
    [Error]             Parameter 2: 0xffffffffc0000139
    [Error]         [FATAL] Exception: 0xc0000139 (!! HARD ERROR !!) {Params: 0x4ad4bc8, 0x4b5e2e8, 0xffffffffc0000139, 0x0}
    [Error]         [ERROR] A fatal error occurred in the running application. The application will be terminated. Code: 0xc0000139.

on [page][1] `0xc0000139` is described as "Entry Point Not Found". What does this error mean and how can I solve it?

I used XGBoost in the same way in Azure ML and it worked. And it did not ask for external libraries (dlls). LightGBM on the contrary asks lots of libraries (dlls) and I think the problem is connected with the dlls, but this error does not indicate what is actually missing.

**What I did:** <br>Installed LightGBM R package  on a Virtual Machine with Windows Server 2016. For this I used:

 - CMake
 - C++ Development kit (installed almost all packages)
 - RTools

Included in lightgbm\libs\x64 are the following packages because I previously got error `0xc0000135` with the names of these libraries:

 - msvcp140.dll
 - vcomp140.dll
 - vcruntime140.dll
 - all api-ms-win-core-\*.dll and all api-ms-win-crt-\*.dll

I tried to change the R version from Microsoft R Open 3.2.2 to CRAN R 3.1.0. It executes witout errors but does not execute code after library import.

The full output of Azure ML R script:

    Record Starts at UTC 08/03/2017 12:28:27:
    
    Run the job:"/dll "LanguageWorker, Version=6.0.0.0, Culture=neutral, PublicKeyToken=69c3241e6f0468ca;Microsoft.MetaAnalytics.LanguageWorker.LanguageWorkerClientRS;RunRSNR" /Output0 "..\..\Result Dataset\Result Dataset.dataset" /Output1 "..\..\R Device\R Device.dataset"  /dataset1 "..\..\Dataset1\Dataset1.csv"    /bundlePath "..\..\Script Bundle\Script Bundle.zip"  /rStreamReader "script.R"  /rLibVersion "Microsoft R Open 3.2.2"  /ContextFile "..\..\_context\ContextFile.txt""
    [Start] Program::Main
    [Start]     DataLabModuleDescriptionParser::ParseModuleDescriptionString
    [Stop]     DataLabModuleDescriptionParser::ParseModuleDescriptionString. Duration = 00:00:00.0045866
    [Start]     DllModuleMethod::DllModuleMethod
    [Stop]     DllModuleMethod::DllModuleMethod. Duration = 00:00:00.0000221
    [Start]     DllModuleMethod::Execute
    [Start]         DataLabModuleBinder::BindModuleMethod
    [Verbose]             moduleMethodDescription LanguageWorker, Version=6.0.0.0, Culture=neutral, PublicKeyToken=69c3241e6f0468ca;Microsoft.MetaAnalytics.LanguageWorker.LanguageWorkerClientRS;RunRSNR
    [Verbose]             assemblyFullName LanguageWorker, Version=6.0.0.0, Culture=neutral, PublicKeyToken=69c3241e6f0468ca
    [Start]             DataLabModuleBinder::LoadModuleAssembly
    [Verbose]                 Loaded moduleAssembly LanguageWorker, Version=6.0.0.0, Culture=neutral, PublicKeyToken=69c3241e6f0468ca
    [Stop]             DataLabModuleBinder::LoadModuleAssembly. Duration = 00:00:00.0093763
    [Verbose]             moduleTypeName Microsoft.MetaAnalytics.LanguageWorker.LanguageWorkerClientRS
    [Verbose]             moduleMethodName RunRSNR
    [Information]             Module FriendlyName : Execute R Script
    [Information]             Module Release Status : Release
    [Stop]         DataLabModuleBinder::BindModuleMethod. Duration = 00:00:00.0125213
    [Start]         ParameterArgumentBinder::InitializeParameterValues
    [Verbose]             parameterInfos count = 6
    [Verbose]             parameterInfos[0] name = dataset1 , type = Microsoft.Numerics.Data.Local.DataTable
    [Start]             DataTableCsvHandler::HandleArgumentString
    [Stop]             DataTableCsvHandler::HandleArgumentString. Duration = 00:00:00.2364734
    [Verbose]             parameterInfos[1] name = dataset2 , type = Microsoft.Numerics.Data.Local.DataTable
    [Verbose]             Set optional parameter dataset2 value to NULL
    [Verbose]             parameterInfos[2] name = bundlePath , type = System.String
    [Verbose]             parameterInfos[3] name = rStreamReader , type = System.IO.StreamReader
    [Verbose]             parameterInfos[4] name = seed , type = System.Nullable`1[System.Int32]
    [Verbose]             Set optional parameter seed value to NULL
    [Verbose]             parameterInfos[5] name = rLibVersion , type = Microsoft.MetaAnalytics.LanguageWorker.LanguageWorkerClientRS+ExecuteRScriptRVersion
    [Verbose]             Converted string 'Microsoft R Open 3.2.2' to enum of type Microsoft.MetaAnalytics.LanguageWorker.LanguageWorkerClientRS+ExecuteRScriptRVersion
    [Stop]         ParameterArgumentBinder::InitializeParameterValues. Duration = 00:00:00.3175225
    [Verbose]         Begin invoking method RunRSNR ... 
    [ModuleOutput] Executing Against R 3.2.2.0
    [ModuleOutput] Executing Against R 3.2.2.0
    [Information]         Microsoft Drawbridge Console Host [Version 1.0.2108.0]
    [Error]         +++ NT HARD ERROR (0xc0000139) +++
    [Error]             Parameter 0: 0x4ad4bc8 [log2f]
    [Error]             Parameter 1: 0x4b5e2e8 [C:\src\lightgbm\libs\x64\lib_lightgbm.dll]
    [Error]             Parameter 2: 0xffffffffc0000139
    [Error]         [FATAL] Exception: 0xc0000139 (!! HARD ERROR !!) {Params: 0x4ad4bc8, 0x4b5e2e8, 0xffffffffc0000139, 0x0}
    [Error]         [ERROR] A fatal error occurred in the running application. The application will be terminated. Code: 0xc0000139.
    [Information]         [1] 56000
    [Information]         The following files have been unzipped for sourcing in path=["src"]:
    [Information]                            Name  Length                Date
    [Information]         1 data.table_1.10.4.zip 1487417 2017-07-07 16:48:00
    [Information]         2            lgb1.model   45142 2017-08-02 17:38:00
    [Information]         3            lgb2.model   83455 2017-08-02 17:38:00
    [Information]         4    lightgbm_2.0.4.zip 1350111 2017-08-03 14:26:00
    [Information]         5      magrittr_1.5.zip  152732 2017-07-07 15:34:00
    [Information]         6                R6.zip  317766 2017-08-03 10:33:00
    [Information]         Loading objects:
    [Information]           port1
    [Information]         [1] "Loading variable port1..."
    [Information]         package 'magrittr' successfully unpacked and MD5 sums checked
    [Information]         package 'R6' successfully unpacked and MD5 sums checked
    [Information]         package 'data.table' successfully unpacked and MD5 sums checked
    [Information]         package 'lightgbm' successfully unpacked and MD5 sums checked
    [Information]         data.table 1.10.4
    [Information]           The fastest way to learn (by data.table authors): https://www.datacamp.com/courses/data-analysis-the-data-table-way
    [Information]           Documentation: ?data.table, example(data.table) and browseVignettes("data.table")
    [Information]           Release notes, videos and slides: http://r-datatable.com
    [Error]         Process returned with non-zero exit code -1073741511
    [Stop]     DllModuleMethod::Execute. Duration = 00:00:14.8676292
    [Critical]     Error: Error 1000: RPackage library exception: Attempting to obtain R output before invoking execution process
    [Critical]     {"InputParameters":{"DataTable":[{"Rows":50,"Columns":131,"estimatedSize":16928768,..........."Errors":"Microsoft.Analytics.Exceptions.ErrorMapping+ModuleException: Error 1000: RPackage library exception: Attempting to obtain R output before invoking execution process ---> Microsoft.Analytics.Modules.R.ErrorHandling.RInvalidOperationException: Attempting to obtain R output before invoking execution process\r\n   at Microsoft.MetaAnalytics.LanguageWorker.NewRWorker.GetProcessOutputs(Boolean scrub) in d:\\_Bld\\8831\\7669\\Sources\\Product\\Source\\Modules\\LanguageWorker\\LanguageWorker.Dll\\TempWorkers\\NewRWorker.cs:line 459\r\n   at Microsoft.MetaAnalytics.LanguageWorker.LanguageWorkerClientRS.ExecuteR(NewRWorker worker, DataTable dataset1, DataTable dataset2, IEnumerable`1 bundlePath, StreamReader rStreamReader, Nullable`1 seed) in d:\\_Bld\\8831\\7669\\Sources\\Product\\Source\\Modules\\LanguageWorker\\LanguageWorker.Dll\\EntryPoints\\RModule.cs:line 278\r\n   at Microsoft.MetaAnalytics.LanguageWorker.LanguageWorkerClientRS._RunImpl(NewRWorker worker, DataTable dataset1, DataTable dataset2, String bundlePath, StreamReader rStreamReader, Nullable`1 seed, ExecuteRScriptExternalResource source, String url, ExecuteRScriptGitHubRepositoryType githubRepoType, SecureString accountToken) in d:\\_Bld\\8831\\7669\\Sources\\Product\\Source\\Modules\\LanguageWorker\\LanguageWorker.Dll\\EntryPoints\\RModule.cs:line 207\r\n   at Microsoft.MetaAnalytics.LanguageWorker.LanguageWorkerClientRS.RunRSNR(DataTable dataset1, DataTable dataset2, String bundlePath, StreamReader rStreamReader, Nullable`1 seed, ExecuteRScriptRVersion rLibVersion) in d:\\_Bld\\8831\\7669\\Sources\\Product\\Source\\Modules\\LanguageWorker\\LanguageWorker.Dll\\EntryPoints\\REntryPoint.cs:line 105\r\n   --- End of inner exception stack trace ---","Warnings":[],"Duration":"00:00:14.8605990"}
    Module finished after a runtime of 00:00:15.3186157 with exit code -2
    Module failed due to negative exit code of -2

  [1]: https://msdn.microsoft.com/en-us/library/cc704588.aspx

**Comment by guolinke** [comment]
@zenkzz we didn't test it on MS R open, not sure it can work or not.
For the CRAN R, I think it should work. 
@Laurae2 any ideas ?

**Comment by guolinke** [comment]
@zenkzz how do you install lightgbm ? can you provide the install log ?

**Comment by chivee** [comment]
@zenkzz , lightGBM on Azure ML was [only supported in Ubuntu](https://docs.microsoft.com/en-us/azure/machine-learning/machine-learning-data-science-virtual-machine-overview).

**Comment by chivee** [comment]
@zenkzz , However, you can installed the CLI version if you needed.

**Comment by guolinke** [comment]
@chivee I think @zenkzz installed LightGBM by himself, so it should be supported, since it is a standard windows OS.

**Comment by zenkzz** [comment]
I installed LightGBM myself. I initially compiled in CRAN R 3.4 and used it in MS R Open 3.2.2. I then tried to use the compiled version on Azure with CRAN R 3.1. It says everything is OK but there is no output after LightGBM import in R script. I compiled with MS R 3.2.5 and run on MS R 3.2.2 and it still fails with the same error.

**Comment by zenkzz** [comment]
@guolinke Install logs:

```
C:\Users\sergey\Downloads\LightGBM\R-package>R CMD INSTALL --build . --no-multiarch
* installing to library 'C:/Program Files/R/R-3.4.1/library'
* installing *source* package 'lightgbm' ...
Warning in as.POSIXlt.POSIXct(x, tz) :
  unable to identify current timezone 'C':
please set environment variable 'TZ'
** libs
installing via 'install.libs.R' to C:/Program Files/R/R-3.4.1/library/lightgbm
-- The C compiler identification is MSVC 19.10.25019.0
-- The CXX compiler identification is MSVC 19.10.25019.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Tools/MSVC/14.10.25017/bin/HostX86/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Tools/MSVC/14.10.25017/bin/HostX86/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Tools/MSVC/14.10.25017/bin/HostX86/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Tools/MSVC/14.10.25017/bin/HostX86/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning (dev) at C:/Program Files/CMake/share/cmake-3.9/Modules/FindOpenMP.cmake:212 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "MSVC" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.9/Modules/FindOpenMP.cmake:324 (_OPENMP_GET_FLAGS)
  CMakeLists.txt:41 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found OpenMP_C: -openmp (found version "2.0")
-- Found OpenMP_CXX: -openmp (found version "2.0")
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/sergey/Downloads/LightGBM/R-package/src/build
-- Found OpenMP_C: -openmp
-- Found OpenMP_CXX: -openmp
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/sergey/Downloads/LightGBM/R-package/src/build
Microsoft (R) Build Engine version 15.1.1012.6693
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 8/3/2017 8:22:39 AM.
Project "C:\Users\sergey\Downloads\LightGBM\R-package\src\build\_lightgbm.vcxproj" on node 1 (default targets).
Project "C:\Users\sergey\Downloads\LightGBM\R-package\src\build\_lightgbm.vcxproj" (1) is building "C:\Users\sergey\Dow
nloads\LightGBM\R-package\src\build\ZERO_CHECK.vcxproj" (2) on node 1 (default targets).
PrepareForBuild:
  Creating directory "x64\Release\ZERO_CHECK\".
  Creating directory "x64\Release\ZERO_CHECK\ZERO_CHECK.tlog\".
InitializeBuildStatus:
  Creating "x64\Release\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
CustomBuild:
  Checking Build System
  CMake does not need to re-run because C:/Users/sergey/Downloads/LightGBM/R-package/src/build/CMakeFiles/generate.stam
  p is up-to-date.
FinalizeBuildStatus:
  Deleting file "x64\Release\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild".
  Touching "x64\Release\ZERO_CHECK\ZERO_CHECK.tlog\ZERO_CHECK.lastbuildstate".
Done Building Project "C:\Users\sergey\Downloads\LightGBM\R-package\src\build\ZERO_CHECK.vcxproj" (default targets).

PrepareForBuild:
  Creating directory "_lightgbm.dir\Release\".
  Creating directory "C:\Users\sergey\Downloads\LightGBM\R-package\src\Release\".
  Creating directory "_lightgbm.dir\Release\_lightgbm.tlog\".
InitializeBuildStatus:
  Creating "_lightgbm.dir\Release\_lightgbm.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
CustomBuild:
  Building Custom Rule C:/Users/sergey/Downloads/LightGBM/R-package/src/CMakeLists.txt
  CMake does not need to re-run because C:/Users/sergey/Downloads/LightGBM/R-package/src/build/CMakeFiles/generate.stam
  p is up-to-date.
ClCompile:
  C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.10.25017\bin\HostX86\x64\CL.exe /c /I
  "C:\Users\sergey\Downloads\LightGBM\R-package\src\include" /nologo /W4 /WX- /diagnostics:classic /O2 /Ob2 /Oi /Ot /Oy
   /GL /D WIN32 /D _WINDOWS /D NDEBUG /D USE_SOCKET /D "CMAKE_INTDIR=\"Release\"" /D _lightgbm_EXPORTS /D _WINDLL /D _M
  BCS /Gm- /EHsc /MD /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /openmp /Fo"_lightgbm.dir\Release\\" /Fd"_
  lightgbm.dir\Release\vc141.pdb" /Gd /TP /errorReport:queue "C:\Users\sergey\Downloads\LightGBM\R-package\src\src\c_ap
  i.cpp" "C:\Users\sergey\Downloads\LightGBM\R-package\src\src\lightgbm_R.cpp" "C:\Users\sergey\Downloads\LightGBM\R-pa
  ckage\src\src\application\application.cpp" "C:\Users\sergey\Downloads\LightGBM\R-package\src\src\boosting\boosting.cp
  p" "C:\Users\sergey\Downloads\LightGBM\R-package\src\src\boosting\gbdt.cpp" "C:\Users\sergey\Downloads\LightGBM\R-pac
  kage\src\src\boosting\gbdt_prediction.cpp" "C:\Users\sergey\Downloads\LightGBM\R-package\src\src\boosting\prediction_
  early_stop.cpp" "C:\Users\sergey\Downloads\LightGBM\R-package\src\src\io\bin.cpp" "C:\Users\sergey\Downloads\LightGBM
  \R-package\src\src\io\config.cpp" "C:\Users\sergey\Downloads\LightGBM\R-package\src\src\io\dataset.cpp" "C:\Users\ser
  gey\Downloads\LightGBM\R-package\src\src\io\dataset_loader.cpp" "C:\Users\sergey\Downloads\LightGBM\R-package\src\src
  \io\metadata.cpp" "C:\Users\sergey\Downloads\LightGBM\R-package\src\src\io\parser.cpp" "C:\Users\sergey\Downloads\Lig
  htGBM\R-package\src\src\io\tree.cpp" "C:\Users\sergey\Downloads\LightGBM\R-package\src\src\metric\dcg_calculator.cpp"
   "C:\Users\sergey\Downloads\LightGBM\R-package\src\src\metric\metric.cpp" "C:\Users\sergey\Downloads\LightGBM\R-packa
  ge\src\src\objective\objective_function.cpp" "C:\Users\sergey\Downloads\LightGBM\R-package\src\src\network\linker_top
  o.cpp" "C:\Users\sergey\Downloads\LightGBM\R-package\src\src\network\linkers_mpi.cpp" "C:\Users\sergey\Downloads\Ligh
  tGBM\R-package\src\src\network\linkers_socket.cpp" "C:\Users\sergey\Downloads\LightGBM\R-package\src\src\network\netw
  ork.cpp" "C:\Users\sergey\Downloads\LightGBM\R-package\src\src\treelearner\data_parallel_tree_learner.cpp" "C:\Users\
  sergey\Downloads\LightGBM\R-package\src\src\treelearner\feature_parallel_tree_learner.cpp" "C:\Users\sergey\Downloads
  \LightGBM\R-package\src\src\treelearner\gpu_tree_learner.cpp" "C:\Users\sergey\Downloads\LightGBM\R-package\src\src\t
  reelearner\serial_tree_learner.cpp" "C:\Users\sergey\Downloads\LightGBM\R-package\src\src\treelearner\tree_learner.cp
  p" "C:\Users\sergey\Downloads\LightGBM\R-package\src\src\treelearner\voting_parallel_tree_learner.cpp"
  c_api.cpp
  lightgbm_R.cpp
  application.cpp
  boosting.cpp
  gbdt.cpp
  gbdt_prediction.cpp
  prediction_early_stop.cpp
  bin.cpp
  config.cpp
  dataset.cpp
  dataset_loader.cpp
  metadata.cpp
  parser.cpp
  tree.cpp
  dcg_calculator.cpp
  metric.cpp
  objective_function.cpp
  linker_topo.cpp
  linkers_mpi.cpp
  linkers_socket.cpp
  Compiling...
  network.cpp
  data_parallel_tree_learner.cpp
  feature_parallel_tree_learner.cpp
  gpu_tree_learner.cpp
  serial_tree_learner.cpp
  tree_learner.cpp
  voting_parallel_tree_learner.cpp
Link:
  C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.10.25017\bin\HostX86\x64\link.exe /ER
  RORREPORT:QUEUE /OUT:"C:\Users\sergey\Downloads\LightGBM\R-package\src\Release\lib_lightgbm.dll" /INCREMENTAL:NO /NOL
  OGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.
  lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:"C:/Users/sergey/Downloads/Light
  GBM/R-package/src/Release/lib_lightgbm.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/Users/serg
  ey/Downloads/LightGBM/R-package/src/Release/lib_lightgbm.lib" /MACHINE:X64  /machine:x64 /DLL _lightgbm.dir\Release\c
  _api.obj
  _lightgbm.dir\Release\lightgbm_R.obj
  _lightgbm.dir\Release\application.obj
  _lightgbm.dir\Release\boosting.obj
  _lightgbm.dir\Release\gbdt.obj
  _lightgbm.dir\Release\gbdt_prediction.obj
  _lightgbm.dir\Release\prediction_early_stop.obj
  _lightgbm.dir\Release\bin.obj
  _lightgbm.dir\Release\config.obj
  _lightgbm.dir\Release\dataset.obj
  _lightgbm.dir\Release\dataset_loader.obj
  _lightgbm.dir\Release\metadata.obj
  _lightgbm.dir\Release\parser.obj
  _lightgbm.dir\Release\tree.obj
  _lightgbm.dir\Release\dcg_calculator.obj
  _lightgbm.dir\Release\metric.obj
  _lightgbm.dir\Release\objective_function.obj
  _lightgbm.dir\Release\linker_topo.obj
  _lightgbm.dir\Release\linkers_mpi.obj
  _lightgbm.dir\Release\linkers_socket.obj
  _lightgbm.dir\Release\network.obj
  _lightgbm.dir\Release\data_parallel_tree_learner.obj
  _lightgbm.dir\Release\feature_parallel_tree_learner.obj
  _lightgbm.dir\Release\gpu_tree_learner.obj
  _lightgbm.dir\Release\serial_tree_learner.obj
  _lightgbm.dir\Release\tree_learner.obj
  _lightgbm.dir\Release\voting_parallel_tree_learner.obj
  c_api.obj : MSIL .netmodule or module compiled with /GL found; restarting link with /LTCG; add /LTCG to the link comm
  and line to improve linker performance
     Creating library C:/Users/sergey/Downloads/LightGBM/R-package/src/Release/lib_lightgbm.lib and object C:/Users/ser
  gey/Downloads/LightGBM/R-package/src/Release/lib_lightgbm.exp
  Generating code
  Finished generating code
  _lightgbm.vcxproj -> C:\Users\sergey\Downloads\LightGBM\R-package\src\Release\lib_lightgbm.dll
FinalizeBuildStatus:
  Deleting file "_lightgbm.dir\Release\_lightgbm.tlog\unsuccessfulbuild".
  Touching "_lightgbm.dir\Release\_lightgbm.tlog\_lightgbm.lastbuildstate".
Done Building Project "C:\Users\sergey\Downloads\LightGBM\R-package\src\build\_lightgbm.vcxproj" (default targets).


Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:55.40
Found library file: C:/Users/sergey/Downloads/LightGBM/R-package/src/Release/lib_lightgbm.dll to move to C:/Program Files/R/R-3.4.1/library/lightgbm/libs/x64** R
** data
** demo
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* MD5 sums
packaged installation of 'lightgbm' as lightgbm_2.0.4.zip
* DONE (lightgbm)
```

**Comment by guolinke** [comment]
@zenkzz 
from your log, the lightgbm is installed to ```C:/Program Files/R/R-3.4.1/library/lightgbm``` . 
But why the dll is loaded from ```C:\src\lightgbm\libs\x64\lib_lightgbm.dll``` ? it should be in ```C:/Program Files/R/R-3.4.1/library/lightgbm/libs/x64/lib_lightgbm.dll``` . 
Maybe you are using the wrong R to call LightGBM ?

**Comment by zenkzz** [comment]
@guolinke I am using Azure ML cloud service. There I execute R script with zip file attached, where there is lightgbm and other needed packages. R script is executed in a container with a Windows system. The files from the zip file are extracted into src directory. Install.packages installs the packages from zip files contained in the directory. So the original path is `C:\src\lightgbm_2.0.4.zip\lightgbm\libs\x64\lib_lightgbm.dll` And then library searches lots of dll files. Maybe you are right and the lightgbm directory does not exist.

**Comment by zenkzz** [comment]
I checked. Install.packages actually creates a directory lightgbm in src.

Just for info here is my R code:

```
dataset1 <- maml.mapInputPort(1)
install.packages("src/magrittr_1.5.zip",lib="src/",repos=NULL)
install.packages("src/R6.zip",lib="src/",repos=NULL)
install.packages("src/data.table_1.10.4.zip",lib="src/",repos=NULL)

install.packages("src/lightgbm_2.0.4.zip",lib="src/",repos=NULL)
library(R6,lib.loc="src/")
library(data.table,lib.loc="src/")

library(lightgbm,lib.loc="src/")
```

**Comment by guolinke** [comment]
I see. Maybe the problem is the "Azure ML cloud" doesn't support visual c++ runtime (it is funny...), and simply add more dlls is not working. 
You can try to use mingw version by set ```use_mingw <- TRUE``` in this line: https://github.com/Microsoft/LightGBM/blob/master/R-package/src/install.libs.R#L4

**Comment by guolinke** [comment]
you also can try to install from github in your R script: 
```
library(devtools)
options(devtools.install.args = "--no-multiarch") # if you have 64-bit R only, you can skip this
install_github("Microsoft/LightGBM", subdir = "R-package")
```

**Comment by zenkzz** [comment]
@guolinke Compiling with use_mingw <- TRUE worked. Thanks for solving my problem.

**Comment by Laurae2** [comment]
@zenkzz Can you report the printed output if you run `.libPaths()` in R? You might have two LightGBMs, double check the folders.

In addition, if `.libPaths()` returns more than one (at least two) values, then if you use scripts to use R (like Rscript), LightGBM may be loaded from the wrong folder which causes this issues (I had a similar issue in one of my servers).
