### ISSUE TITLE
Update macOS install instructions

### ISSUE THREAD

**Issue by fulldecent** [Microsoft/LightGBM#782]
This regards https://github.com/Microsoft/LightGBM/wiki/Installation-Guide

I cannot edit the file, so creating an issue.

Just want to note that the normal `brew install gcc` worked for me. This removes about two hours from the installation process for macOS as currently documented in this file.

**Comment by guolinke** [comment]
@wxchan @henry0312 
Does using ```brew install gcc``` have openmp support ?

**Comment by henry0312** [comment]
Yes, it have OpenMP, but I don't know whether it works fine.
How can I check simply?
https://computing.llnl.gov/tutorials/openMP/samples/C/omp_hello.c works at least.

**Comment by guolinke** [comment]
so why we need the ```--without-multilib``` ?

**Comment by henry0312** [comment]
I don't know the details, but there was a bug in the previous gcc.
cf. https://github.com/Homebrew/homebrew-core/commit/bc4ce49717a77a0debdb2c3b8b2542c87ab58daa.

**Comment by guolinke** [comment]
@wxchan  can you help to confirm this ?

**Comment by thierrygosselin** [comment]
Hi LightGBM team, I'm a new user. I've been working with XGBoost for imputations and tarting to try LightGBM. 

I have better doc on how to upgrade GCC and CLANG with OpenMP support for macOS. 
Both approach are _homebrew_ and _macport_ free. Additionally they take less than 5 min to do ... yep.

Can someone point me to the link where I could edit the latest doc on LightGBM ?

Best
Thierry

**Comment by Laurae2** [comment]
https://github.com/Microsoft/LightGBM/blob/master/docs/Installation-Guide.rst

and if there are extra requirements for R: https://github.com/Microsoft/LightGBM/blob/master/R-package/README.md
