### ISSUE TITLE
10 warnings for  "C4267" in compile gpu build

### ISSUE THREAD

**Issue by fenqingr** [Microsoft/LightGBM#788]
Hi There,

I found my GPU usage is constantly under 10%, most of time just 0% with some spike at around 20% to 50% so I suspect that my GPU build has problem and I deleted the installation folder and reinstalled it and I found 10 warnings about compiling issues(See below log). Can someone look at it ? Thanks a lot!

log below:

========================================

Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

D:\>Set BOOST_ROOT=C:\local\boost_1_64_0\

D:\>Set BOOST_LIBRARYDIR=C:\local\boost_1_64_0\lib64-msvc-14.0

D:\>git clone --recursive https://github.com/Microsoft/LightGBM
Cloning into 'LightGBM'...
remote: Counting objects: 7294, done.
remote: Compressing objects: 100% (50/50), done.
remote: Total 7294 (delta 18), reused 29 (delta 11), pack-reused 7231
Receiving objects: 100% (7294/7294), 5.01 MiB | 1.26 MiB/s, done.
Resolving deltas: 100% (5055/5055), done.
Submodule 'include/boost/compute' (https://github.com/boostorg/compute) register
ed for path 'compute'
Cloning into 'D:/LightGBM/compute'...
remote: Counting objects: 21127, done.
remote: Total 21127 (delta 0), reused 0 (delta 0), pack-reused 21127
Receiving objects: 100% (21127/21127), 8.37 MiB | 1.82 MiB/s, done.
Resolving deltas: 100% (17188/17188), done.
Submodule path 'compute': checked out '6de7f6448796f67958dde8de4569fb1ae649ee91'

D:\>cd LightGBM

D:\LightGBM\build>cmake -DCMAKE_GENERATOR_PLATFORM=x64 -DUSE_GPU=1 ..
-- Building for: Visual Studio 15 2017
-- The C compiler identification is MSVC 19.10.25019.0
-- The CXX compiler identification is MSVC 19.10.25019.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/
2017/Community/VC/Tools/MSVC/14.10.25017/bin/HostX86/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/
2017/Community/VC/Tools/MSVC/14.10.25017/bin/HostX86/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studi
o/2017/Community/VC/Tools/MSVC/14.10.25017/bin/HostX86/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studi
o/2017/Community/VC/Tools/MSVC/14.10.25017/bin/HostX86/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenMP_C: -openmp (found version "2.0")
-- Found OpenMP_CXX: -openmp (found version "2.0")
-- Looking for CL_VERSION_2_0
-- Looking for CL_VERSION_2_0 - not found
-- Looking for CL_VERSION_1_2
-- Looking for CL_VERSION_1_2 - found
-- Found OpenCL: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0/lib/x64
/OpenCL.lib (found version "1.2")
-- OpenCL include directory:C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v
8.0/include
-- Boost version: 1.64.0
-- Found the following Boost libraries:
--   filesystem
--   system
-- Configuring done
-- Generating done
-- Build files have been written to: D:/LightGBM/build
 
D:\LightGBM\build>cmake --build . --target ALL_BUILD --config Release
Microsoft (R) Build Engine version 15.1.1012.6693
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 08/05/2017 11:13:50 PM.
Project "D:\LightGBM\build\ALL_BUILD.vcxproj" on node 1 (default targets).
Project "D:\LightGBM\build\ALL_BUILD.vcxproj" (1) is building "D:\LightGBM\buil
d\ZERO_CHECK.vcxproj" (2) on node 1 (default targets).
PrepareForBuild:
  Creating directory "x64\Release\ZERO_CHECK\".
  Creating directory "x64\Release\ZERO_CHECK\ZERO_CHECK.tlog\".
InitializeBuildStatus:
  Creating "x64\Release\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild" because "
  AlwaysCreate" was specified.
CustomBuild:
  Checking Build System
  CMake does not need to re-run because D:/LightGBM/build/CMakeFiles/generate.s
  tamp is up-to-date.
FinalizeBuildStatus:
  Deleting file "x64\Release\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild".
  Touching "x64\Release\ZERO_CHECK\ZERO_CHECK.tlog\ZERO_CHECK.lastbuildstate".
Done Building Project "D:\LightGBM\build\ZERO_CHECK.vcxproj" (default targets).

Project "D:\LightGBM\build\ALL_BUILD.vcxproj" (1) is building "D:\LightGBM\buil
d\_lightgbm.vcxproj" (3) on node 1 (default targets).
PrepareForBuild:
  Creating directory "_lightgbm.dir\Release\".
  Creating directory "D:\LightGBM\Release\".
  Creating directory "_lightgbm.dir\Release\_lightgbm.tlog\".
InitializeBuildStatus:
  Creating "_lightgbm.dir\Release\_lightgbm.tlog\unsuccessfulbuild" because "Al
  waysCreate" was specified.
CustomBuild:
  Building Custom Rule D:/LightGBM/CMakeLists.txt
  CMake does not need to re-run because D:/LightGBM/build/CMakeFiles/generate.s
  tamp is up-to-date.
ClCompile:
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\1
  4.10.25017\bin\HostX86\x64\CL.exe /c /ID:\LightGBM\compute\include /I"C:\Prog
  ram Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include" /IC:\local\boost_1_
  64_0 /ID:\LightGBM\include /nologo /W4 /WX- /diagnostics:classic /O2 /Ob2 /Oi
   /Ot /Oy /GL /D WIN32 /D _WINDOWS /D NDEBUG /D USE_SOCKET /D BOOST_ALL_NO_LIB
   /D USE_GPU /D "CMAKE_INTDIR=\"Release\"" /D _lightgbm_EXPORTS /D _WINDLL /D
  _MBCS /Gm- /EHsc /MD /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR
  /openmp /Fo"_lightgbm.dir\Release\\" /Fd"_lightgbm.dir\Release\vc141.pdb" /Gd
   /TP /errorReport:queue D:\LightGBM\src\c_api.cpp D:\LightGBM\src\lightgbm_R.
  cpp D:\LightGBM\src\application\application.cpp D:\LightGBM\src\boosting\boos
  ting.cpp D:\LightGBM\src\boosting\gbdt.cpp D:\LightGBM\src\boosting\gbdt_pred
  iction.cpp D:\LightGBM\src\boosting\prediction_early_stop.cpp D:\LightGBM\src
  \io\bin.cpp D:\LightGBM\src\io\config.cpp D:\LightGBM\src\io\dataset.cpp D:\L
  ightGBM\src\io\dataset_loader.cpp D:\LightGBM\src\io\metadata.cpp D:\LightGBM
  \src\io\parser.cpp D:\LightGBM\src\io\tree.cpp D:\LightGBM\src\metric\dcg_cal
  culator.cpp D:\LightGBM\src\metric\metric.cpp D:\LightGBM\src\objective\objec
  tive_function.cpp D:\LightGBM\src\network\linker_topo.cpp D:\LightGBM\src\net
  work\linkers_mpi.cpp D:\LightGBM\src\network\linkers_socket.cpp D:\LightGBM\s
  rc\network\network.cpp D:\LightGBM\src\treelearner\data_parallel_tree_learner
  .cpp D:\LightGBM\src\treelearner\feature_parallel_tree_learner.cpp D:\LightGB
  M\src\treelearner\gpu_tree_learner.cpp D:\LightGBM\src\treelearner\serial_tre
  e_learner.cpp D:\LightGBM\src\treelearner\tree_learner.cpp D:\LightGBM\src\tr
  eelearner\voting_parallel_tree_learner.cpp
  c_api.cpp
  lightgbm_R.cpp
  application.cpp
  boosting.cpp
  gbdt.cpp
  gbdt_prediction.cpp
  prediction_early_stop.cpp
  bin.cpp
  config.cpp
  dataset.cpp
  dataset_loader.cpp
  metadata.cpp
  parser.cpp
  tree.cpp
  dcg_calculator.cpp
  metric.cpp
  objective_function.cpp
  linker_topo.cpp
  linkers_mpi.cpp
  linkers_socket.cpp
  Compiling...
  network.cpp
  data_parallel_tree_learner.cpp
D:\LightGBM\compute\include\boost/compute/program.hpp(318): warning C4267: 'arg
ument': conversion from 'size_t' to 'cl_uint', possible loss of data [D:\LightG
BM\build\_lightgbm.vcxproj]
  feature_parallel_tree_learner.cpp
D:\LightGBM\compute\include\boost/compute/program.hpp(318): warning C4267: 'arg
ument': conversion from 'size_t' to 'cl_uint', possible loss of data [D:\LightG
BM\build\_lightgbm.vcxproj]
  gpu_tree_learner.cpp
D:\LightGBM\compute\include\boost/compute/program.hpp(318): warning C4267: 'arg
ument': conversion from 'size_t' to 'cl_uint', possible loss of data [D:\LightG
BM\build\_lightgbm.vcxproj]
  serial_tree_learner.cpp
  tree_learner.cpp
D:\LightGBM\compute\include\boost/compute/program.hpp(318): warning C4267: 'arg
ument': conversion from 'size_t' to 'cl_uint', possible loss of data [D:\LightG
BM\build\_lightgbm.vcxproj]
  voting_parallel_tree_learner.cpp
D:\LightGBM\compute\include\boost/compute/program.hpp(318): warning C4267: 'arg
ument': conversion from 'size_t' to 'cl_uint', possible loss of data [D:\LightG
BM\build\_lightgbm.vcxproj]
Link:
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\1
  4.10.25017\bin\HostX86\x64\link.exe /ERRORREPORT:QUEUE /OUT:"D:\LightGBM\Rele
  ase\lib_lightgbm.dll" /INCREMENTAL:NO /NOLOGO "C:\Program Files\NVIDIA GPU Co
  mputing Toolkit\CUDA\v8.0\lib\x64\OpenCL.lib" "C:\local\boost_1_64_0\lib64-ms
  vc-14.1\libboost_filesystem-vc141-mt-1_64.lib" "C:\local\boost_1_64_0\lib64-m
  svc-14.1\libboost_system-vc141-mt-1_64.lib" kernel32.lib user32.lib gdi32.lib
   winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi
  32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:
  embed /PDB:"D:/LightGBM/Release/lib_lightgbm.pdb" /SUBSYSTEM:CONSOLE /TLBID:1
   /DYNAMICBASE /NXCOMPAT /IMPLIB:"D:/LightGBM/Release/lib_lightgbm.lib" /MACHI
  NE:X64  /machine:x64 /DLL _lightgbm.dir\Release\c_api.obj
  _lightgbm.dir\Release\lightgbm_R.obj
  _lightgbm.dir\Release\application.obj
  _lightgbm.dir\Release\boosting.obj
  _lightgbm.dir\Release\gbdt.obj
  _lightgbm.dir\Release\gbdt_prediction.obj
  _lightgbm.dir\Release\prediction_early_stop.obj
  _lightgbm.dir\Release\bin.obj
  _lightgbm.dir\Release\config.obj
  _lightgbm.dir\Release\dataset.obj
  _lightgbm.dir\Release\dataset_loader.obj
  _lightgbm.dir\Release\metadata.obj
  _lightgbm.dir\Release\parser.obj
  _lightgbm.dir\Release\tree.obj
  _lightgbm.dir\Release\dcg_calculator.obj
  _lightgbm.dir\Release\metric.obj
  _lightgbm.dir\Release\objective_function.obj
  _lightgbm.dir\Release\linker_topo.obj
  _lightgbm.dir\Release\linkers_mpi.obj
  _lightgbm.dir\Release\linkers_socket.obj
  _lightgbm.dir\Release\network.obj
  _lightgbm.dir\Release\data_parallel_tree_learner.obj
  _lightgbm.dir\Release\feature_parallel_tree_learner.obj
  _lightgbm.dir\Release\gpu_tree_learner.obj
  _lightgbm.dir\Release\serial_tree_learner.obj
  _lightgbm.dir\Release\tree_learner.obj
  _lightgbm.dir\Release\voting_parallel_tree_learner.obj
  c_api.obj : MSIL .netmodule or module compiled with /GL found; restarting lin
  k with /LTCG; add /LTCG to the link command line to improve linker performanc
  e
     Creating library D:/LightGBM/Release/lib_lightgbm.lib and object D:/LightG
  BM/Release/lib_lightgbm.exp
  Generating code
  Finished generating code
  _lightgbm.vcxproj -> D:\LightGBM\Release\lib_lightgbm.dll
FinalizeBuildStatus:
  Deleting file "_lightgbm.dir\Release\_lightgbm.tlog\unsuccessfulbuild".
  Touching "_lightgbm.dir\Release\_lightgbm.tlog\_lightgbm.lastbuildstate".
Done Building Project "D:\LightGBM\build\_lightgbm.vcxproj" (default targets).

Project "D:\LightGBM\build\ALL_BUILD.vcxproj" (1) is building "D:\LightGBM\buil
d\lightgbm.vcxproj" (4) on node 1 (default targets).
PrepareForBuild:
  Creating directory "lightgbm.dir\Release\".
  Creating directory "lightgbm.dir\Release\lightgbm.tlog\".
InitializeBuildStatus:
  Creating "lightgbm.dir\Release\lightgbm.tlog\unsuccessfulbuild" because "Alwa
  ysCreate" was specified.
CustomBuild:
  Building Custom Rule D:/LightGBM/CMakeLists.txt
  CMake does not need to re-run because D:/LightGBM/build/CMakeFiles/generate.s
  tamp is up-to-date.
ClCompile:
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\1
  4.10.25017\bin\HostX86\x64\CL.exe /c /ID:\LightGBM\compute\include /I"C:\Prog
  ram Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include" /IC:\local\boost_1_
  64_0 /ID:\LightGBM\include /nologo /W4 /WX- /diagnostics:classic /O2 /Ob2 /Oi
   /Ot /Oy /GL /D WIN32 /D _WINDOWS /D NDEBUG /D USE_SOCKET /D BOOST_ALL_NO_LIB
   /D USE_GPU /D "CMAKE_INTDIR=\"Release\"" /D _MBCS /Gm- /EHsc /MD /GS /fp:pre
  cise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /openmp /Fo"lightgbm.dir\Release
  \\" /Fd"lightgbm.dir\Release\vc141.pdb" /Gd /TP /errorReport:queue D:\LightGB
  M\src\main.cpp D:\LightGBM\src\application\application.cpp D:\LightGBM\src\bo
  osting\boosting.cpp D:\LightGBM\src\boosting\gbdt.cpp D:\LightGBM\src\boostin
  g\gbdt_prediction.cpp D:\LightGBM\src\boosting\prediction_early_stop.cpp D:\L
  ightGBM\src\io\bin.cpp D:\LightGBM\src\io\config.cpp D:\LightGBM\src\io\datas
  et.cpp D:\LightGBM\src\io\dataset_loader.cpp D:\LightGBM\src\io\metadata.cpp
  D:\LightGBM\src\io\parser.cpp D:\LightGBM\src\io\tree.cpp D:\LightGBM\src\met
  ric\dcg_calculator.cpp D:\LightGBM\src\metric\metric.cpp D:\LightGBM\src\obje
  ctive\objective_function.cpp D:\LightGBM\src\network\linker_topo.cpp D:\Light
  GBM\src\network\linkers_mpi.cpp D:\LightGBM\src\network\linkers_socket.cpp D:
  \LightGBM\src\network\network.cpp D:\LightGBM\src\treelearner\data_parallel_t
  ree_learner.cpp D:\LightGBM\src\treelearner\feature_parallel_tree_learner.cpp
   D:\LightGBM\src\treelearner\gpu_tree_learner.cpp D:\LightGBM\src\treelearner
  \serial_tree_learner.cpp D:\LightGBM\src\treelearner\tree_learner.cpp D:\Ligh
  tGBM\src\treelearner\voting_parallel_tree_learner.cpp
  main.cpp
  application.cpp
  boosting.cpp
  gbdt.cpp
  gbdt_prediction.cpp
  prediction_early_stop.cpp
  bin.cpp
  config.cpp
  dataset.cpp
  dataset_loader.cpp
  metadata.cpp
  parser.cpp
  tree.cpp
  dcg_calculator.cpp
  metric.cpp
  objective_function.cpp
  linker_topo.cpp
  linkers_mpi.cpp
  linkers_socket.cpp
  network.cpp
  Compiling...
  data_parallel_tree_learner.cpp
**D:\LightGBM\compute\include\boost/compute/program.hpp(318): warning C4267: 'arg
ument': conversion from 'size_t' to 'cl_uint', possible loss of data [D:\LightG
BM\build\lightgbm.vcxproj]
  feature_parallel_tree_learner.cpp
D:\LightGBM\compute\include\boost/compute/program.hpp(318): warning C4267: 'arg
ument': conversion from 'size_t' to 'cl_uint', possible loss of data [D:\LightG
BM\build\lightgbm.vcxproj]
  gpu_tree_learner.cpp
D:\LightGBM\compute\include\boost/compute/program.hpp(318): warning C4267: 'arg
ument': conversion from 'size_t' to 'cl_uint', possible loss of data [D:\LightG
BM\build\lightgbm.vcxproj]
  serial_tree_learner.cpp
  tree_learner.cpp
D:\LightGBM\compute\include\boost/compute/program.hpp(318): warning C4267: 'arg
ument': conversion from 'size_t' to 'cl_uint', possible loss of data [D:\LightG
BM\build\lightgbm.vcxproj]
  voting_parallel_tree_learner.cpp
D:\LightGBM\compute\include\boost/compute/program.hpp(318): warning C4267: 'arg
ument': conversion from 'size_t' to 'cl_uint', possible loss of data [D:\LightG
BM\build\lightgbm.vcxproj]**
Link:
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\1
  4.10.25017\bin\HostX86\x64\link.exe /ERRORREPORT:QUEUE /OUT:"D:\LightGBM\Rele
  ase\lightgbm.exe" /INCREMENTAL:NO /NOLOGO "C:\Program Files\NVIDIA GPU Comput
  ing Toolkit\CUDA\v8.0\lib\x64\OpenCL.lib" "C:\local\boost_1_64_0\lib64-msvc-1
  4.1\libboost_filesystem-vc141-mt-1_64.lib" "C:\local\boost_1_64_0\lib64-msvc-
  14.1\libboost_system-vc141-mt-1_64.lib" kernel32.lib user32.lib gdi32.lib win
  spool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.l
  ib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embe
  d /PDB:"D:/LightGBM/Release/lightgbm.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMI
  CBASE /NXCOMPAT /IMPLIB:"D:/LightGBM/Release/lightgbm.lib" /MACHINE:X64  /mac
  hine:x64 lightgbm.dir\Release\main.obj
  lightgbm.dir\Release\application.obj
  lightgbm.dir\Release\boosting.obj
  lightgbm.dir\Release\gbdt.obj
  lightgbm.dir\Release\gbdt_prediction.obj
  lightgbm.dir\Release\prediction_early_stop.obj
  lightgbm.dir\Release\bin.obj
  lightgbm.dir\Release\config.obj
  lightgbm.dir\Release\dataset.obj
  lightgbm.dir\Release\dataset_loader.obj
  lightgbm.dir\Release\metadata.obj
  lightgbm.dir\Release\parser.obj
  lightgbm.dir\Release\tree.obj
  lightgbm.dir\Release\dcg_calculator.obj
  lightgbm.dir\Release\metric.obj
  lightgbm.dir\Release\objective_function.obj
  lightgbm.dir\Release\linker_topo.obj
  lightgbm.dir\Release\linkers_mpi.obj
  lightgbm.dir\Release\linkers_socket.obj
  lightgbm.dir\Release\network.obj
  lightgbm.dir\Release\data_parallel_tree_learner.obj
  lightgbm.dir\Release\feature_parallel_tree_learner.obj
  lightgbm.dir\Release\gpu_tree_learner.obj
  lightgbm.dir\Release\serial_tree_learner.obj
  lightgbm.dir\Release\tree_learner.obj
  lightgbm.dir\Release\voting_parallel_tree_learner.obj
  main.obj : MSIL .netmodule or module compiled with /GL found; restarting link
   with /LTCG; add /LTCG to the link command line to improve linker performance
     Creating library D:/LightGBM/Release/lightgbm.lib and object D:/LightGBM/R
  elease/lightgbm.exp
  Generating code
  Finished generating code
  lightgbm.vcxproj -> D:\LightGBM\Release\lightgbm.exe
FinalizeBuildStatus:
  Deleting file "lightgbm.dir\Release\lightgbm.tlog\unsuccessfulbuild".
  Touching "lightgbm.dir\Release\lightgbm.tlog\lightgbm.lastbuildstate".
Done Building Project "D:\LightGBM\build\lightgbm.vcxproj" (default targets).

PrepareForBuild:
  Creating directory "x64\Release\ALL_BUILD\".
  Creating directory "x64\Release\ALL_BUILD\ALL_BUILD.tlog\".
InitializeBuildStatus:
  Creating "x64\Release\ALL_BUILD\ALL_BUILD.tlog\unsuccessfulbuild" because "Al
  waysCreate" was specified.
CustomBuild:
  Building Custom Rule D:/LightGBM/CMakeLists.txt
  CMake does not need to re-run because D:/LightGBM/build/CMakeFiles/generate.s
  tamp is up-to-date.
FinalizeBuildStatus:
  Deleting file "x64\Release\ALL_BUILD\ALL_BUILD.tlog\unsuccessfulbuild".
  Touching "x64\Release\ALL_BUILD\ALL_BUILD.tlog\ALL_BUILD.lastbuildstate".
Done Building Project "D:\LightGBM\build\ALL_BUILD.vcxproj" (default targets).

Build succeeded.

"D:\LightGBM\build\ALL_BUILD.vcxproj" (default target) (1) ->
"D:\LightGBM\build\_lightgbm.vcxproj" (default target) (3) ->
(ClCompile target) ->
  **D:\LightGBM\compute\include\boost/compute/program.hpp(318): warning C4267: 'a
rgument': conversion from 'size_t' to 'cl_uint', possible loss of data [D:\Ligh
tGBM\build\_lightgbm.vcxproj]
  D:\LightGBM\compute\include\boost/compute/program.hpp(318): warning C4267: 'a
rgument': conversion from 'size_t' to 'cl_uint', possible loss of data [D:\Ligh
tGBM\build\_lightgbm.vcxproj]
  D:\LightGBM\compute\include\boost/compute/program.hpp(318): warning C4267: 'a
rgument': conversion from 'size_t' to 'cl_uint', possible loss of data [D:\Ligh
tGBM\build\_lightgbm.vcxproj]
  D:\LightGBM\compute\include\boost/compute/program.hpp(318): warning C4267: 'a
rgument': conversion from 'size_t' to 'cl_uint', possible loss of data [D:\Ligh
tGBM\build\_lightgbm.vcxproj]
  D:\LightGBM\compute\include\boost/compute/program.hpp(318): warning C4267: 'a
rgument': conversion from 'size_t' to 'cl_uint', possible loss of data [D:\Ligh
tGBM\build\_lightgbm.vcxproj]

"D:\LightGBM\build\ALL_BUILD.vcxproj" (default target) (1) ->
"D:\LightGBM\build\lightgbm.vcxproj" (default target) (4) ->
  D:\LightGBM\compute\include\boost/compute/program.hpp(318): warning C4267: 'a
rgument': conversion from 'size_t' to 'cl_uint', possible loss of data [D:\Ligh
tGBM\build\lightgbm.vcxproj]
  D:\LightGBM\compute\include\boost/compute/program.hpp(318): warning C4267: 'a
rgument': conversion from 'size_t' to 'cl_uint', possible loss of data [D:\Ligh
tGBM\build\lightgbm.vcxproj]
  D:\LightGBM\compute\include\boost/compute/program.hpp(318): warning C4267: 'a
rgument': conversion from 'size_t' to 'cl_uint', possible loss of data [D:\Ligh
tGBM\build\lightgbm.vcxproj]
  D:\LightGBM\compute\include\boost/compute/program.hpp(318): warning C4267: 'a
rgument': conversion from 'size_t' to 'cl_uint', possible loss of data [D:\Ligh
tGBM\build\lightgbm.vcxproj]
  D:\LightGBM\compute\include\boost/compute/program.hpp(318): warning C4267: 'a
rgument': conversion from 'size_t' to 'cl_uint', possible loss of data [D:\Ligh
tGBM\build\lightgbm.vcxproj]

    10 Warning(s)**
    0 Error(s)

Time Elapsed 00:03:11.97

D:\LightGBM\build>

**Comment by guolinke** [comment]
I think it is not caused by these warnings, and these warnings are from boost.compute library. 

refer to https://github.com/Microsoft/LightGBM/issues/768, The gpu version is not perfect now, especially when #data is small .
