### ISSUE TITLE
Plotting gives error Invalid decision type in tree model

### ISSUE THREAD

**Issue by run2** [Microsoft/LightGBM#798]
Please search your question on previous issues, [stackoverflow](https://stackoverflow.com/questions/tagged/lightgbm) or other search engines before you open a new one.

For bugs and unexpected issues, please provide following information, so that we could reproduce on our system.

## Environment info
Operating System: Ubuntu 16.04
CPU:Intel(R) Xeon(R) CPU E5-2697
C++/Python/R version: Python 3.5.2

## Error Message:
Invalid decision type in tree model

## Steps to reproduce

1. Train any model
gbm = lgb.train(lgbparam, train_data, valid_sets=[valid_data],num_boost_round=18,evals_result=evals_result,verbose_eval=10)
2. Plot the tree
print('Plot 1st tree...') 
ax = lgb.plot_tree(gbm, tree_index=1, figsize=(200, 200), show_info=['split_gain'])
plt.show()
3.
ValueError Traceback (most recent call last)
in ()
9
10 print('Plot 1st tree...') # one tree use categorical feature to split
---> 11 ax = lgb.plot_tree(gbm, tree_index=1, figsize=(20, 8), show_info=['split_gain'])
12 plt.show()

/usr/local/lib/python3.5/dist-packages/lightgbm/plotting.py in plot_tree(booster, ax, tree_index, figsize, graph_attr, node_attr, edge_attr, show_info)
416 node_attr=node_attr,
417 edge_attr=edge_attr,
--> 418 show_info=show_info
419 )
420

/usr/local/lib/python3.5/dist-packages/lightgbm/plotting.py in create_tree_digraph(booster, tree_index, show_info, name, comment, filename, directory, format, engine, encoding, graph_attr, node_attr, edge_attr, body, strict)
365 name=name, comment=comment, filename=filename, directory=directory,
366 format=format, engine=engine, encoding=encoding, graph_attr=graph_attr,
--> 367 node_attr=node_attr, edge_attr=edge_attr, body=body, strict=strict)
368
369 return graph

/usr/local/lib/python3.5/dist-packages/lightgbm/plotting.py in _to_graphviz(tree_info, show_info, feature_names, name, comment, filename, directory, format, engine, encoding, graph_attr, node_attr, edge_attr, body, strict)
290 format=format, engine=engine, encoding=encoding, graph_attr=graph_attr,
291 node_attr=node_attr, edge_attr=edge_attr, body=body, strict=strict)
--> 292 add(tree_info['tree_structure'])
293
294 return graph

/usr/local/lib/python3.5/dist-packages/lightgbm/plotting.py in add(root, parent, decision)
274 l_dec, r_dec = 'is', "isn't"
275 else:
--> 276 raise ValueError('Invalid decision type in tree model.')
277 add(root['left_child'], name, l_dec)
278 add(root['right_child'], name, r_dec)

ValueError: Invalid decision type in tree model.

**Comment by run2** [comment]
This is caused due to the following code in plotting.py
            if root['decision_type'] == 'no_greater':
                l_dec, r_dec = '<=', '>'
            elif root['decision_type'] == 'is':
                l_dec, r_dec = 'is', "isn't"
            else:
raise ValueError('Invalid decision type in tree model.')

root['decision_type'] needs to be checked with '<=' or '='

**Comment by wxchan** [comment]
@run2 you can submit a pull request with your change.

**Comment by run2** [comment]
Done - thanks.
