### ISSUE TITLE
can LGBM_BoosterPredictForMat support sparse vector

### ISSUE THREAD

**Issue by hlee13** [Microsoft/LightGBM#805]
If one of feature value miss when I use function LGBM_BoosterPredictForMat，what should I input，0 ？ or other function can support sparse vector. I can input feature id and value.

**Comment by hlee13** [comment]
LGBM_BoosterPredictForCSR, LGBM_BoosterPredictForCSC any demo, doc?

**Comment by guolinke** [comment]
refer to the code of python package: https://github.com/Microsoft/LightGBM/blob/master/python-package/lightgbm/basic.py#L732-L778
