### ISSUE TITLE
Question - Xeon Phi support? what is best hardware?

### ISSUE THREAD

**Issue by gugatr0n1c** [Microsoft/LightGBM#81]
Hello,

I am thinking about new server configuration.
1] Is it possible to use Xeon Phi for LightGBM?
2] From devel point of view, is it better to use Xeon Phi or "classical" Xeon CPU?

Any experience about best hardware for this library?
Thx a lot..

**Comment by guolinke** [comment]
@gugatr0n1c , LightGBM doesn't have specific optimization for Xeon Phi. And we don't have environment to test this. So it is hard to say which one is better. 
About the optimizations relative to hardware, we use the multi-threading by openmp, and some cache hit chance improvement. But I am not sure can Xeon Phi support them or not.

**Comment by guolinke** [comment]
close for now. feel free to reopen.
