### ISSUE TITLE
LightGBM error - categorical feats

### ISSUE THREAD

**Issue by AljazJ** [Microsoft/LightGBM#811]
Hi there, 

the error I get: 

  File "C:\Program Files\Python35\lib\site-packages\lightgbm\engine.py", line 168, in train
    booster = Booster(params=params, train_set=train_set)
  File "C:\Program Files\Python35\lib\site-packages\lightgbm\basic.py", line 1250, in __init__
    train_set.construct().handle,
  File "C:\Program Files\Python35\lib\site-packages\lightgbm\basic.py", line 807, in construct
    categorical_feature=self.categorical_feature, params=self.params)
  File "C:\Program Files\Python35\lib\site-packages\lightgbm\basic.py", line 644, in _lazy_init
    .format(type(name).__name__, name))
TypeError: Wrong type(str) or unknown name(,) in categorical_feature

Does it mean there's really sth wrong with data structure or do you know of any other issues that may be causing this? It happens when I start training the model ..

Thx!

**Comment by guolinke** [comment]
@wxchan 
https://github.com/Microsoft/LightGBM/blob/master/python-package/lightgbm/basic.py#L637-L644
it seems the `str` type cannot be recognized. 
@AljazJ can you provide the re-produce code ?

**Comment by AljazJ** [comment]
Thanks for answering! This is the part that precedes it, I'm not posting everything since the code cannot be run without some dependent datasets, but if needed I could post also a larger part preceding it:

```

`features` = [
        'user_product_reordered_ratio', 'reordered_sum',
        'add_to_cart_order_inverted_mean', 'add_to_cart_order_relative_mean',
        'reorder_prob',
        'last', 'prev1', 'prev2', 'median', 'mean',
        'dep_reordered_ratio', 'aisle_reordered_ratio',
        'aisle_products',
        'aisle_reordered',
        'dep_products',
        'dep_reordered',
        'prod_users_unq', 'prod_users_unq_reordered',
        'order_number', 'prod_add_to_card_mean',
        'days_since_prior_order',
        'order_dow', 'order_hour_of_day',
        'reorder_ration',
        'user_orders', 'user_order_starts_at', 'user_mean_days_since_prior',
        'user_average_basket', 'user_distinct_products', 'user_reorder_ratio', 'user_total_products',
        'prod_orders', 'prod_reorders',
        'up_order_rate', 'up_orders_since_last_order', 'up_order_rate_since_first_order',
        'up_orders', 'up_first_order', 'up_last_order', 'up_mean_cart_position',
        'days_since_prior_order_mean',
        'order_dow_mean',
        'order_hour_of_day_mean'
    ]
    features.extend(embedings)
    categories = ['product_id', 'aisle_id', 'department_id']
    features.extend(embedings)
    cat_features = ','.join(map(lambda x: str(x + len(features)), range(len(categories))))
    features.extend(categories)

    print('not included', set(order_train.columns.tolist()) - set(features))

    data = order_train[features]
    labels = order_train[['reordered']].values.astype(np.float32).flatten()

    data_val = order_test[features]

    assert data.shape[0] == 8474661

    lgb_train = lgb.Dataset(data, labels, categorical_feature=cat_features)

    # specify your configurations as a dict
    params = {
        'task': 'train',
        'boosting_type': 'gbdt',
        'objective': 'binary',
        'metric': {'binary_logloss', 'auc'},
        'num_leaves': 256,
        'min_sum_hessian_in_leaf': 20,
        'max_depth': 12,
        'learning_rate': 0.05,
        'feature_fraction': 0.6,
        # 'bagging_fraction': 0.9,
        # 'bagging_freq': 3,
        'verbose': 1
    }

    print('Start training...')
    # train
    gbm = lgb.train(params,
                    lgb_train,
                    num_boost_round=380)
```

**Comment by wxchan** [comment]
@AljazJ can you print `cat_features` before `lgb_train = lgb.Dataset(data, labels, categorical_feature=cat_features)` and paste output here?

**Comment by guolinke** [comment]
@AljazJ if you have multi categorical features, please use list instead. 
e.g. `cat_features = [0,1,2,3]`

**Comment by AljazJ** [comment]
107,108,109 is the output. 

I'm fairly new to Python, but it seems that using list may not change a lot here, however I'll see and report - thanks @guolinke!
