### ISSUE TITLE
An issue of the MAP metric when using lambdarank

### ISSUE THREAD

**Issue by harryshics** [Microsoft/LightGBM#816]
I encountered an issue on the MAP@k metric when using lambdarank.

When running the sample code in "LightGBM/examples/lambdarank/", I found different setting of eval_at could return very different values of MAP@k.

For example, when setting eval_at = 1,3,5, we get 
 training map@1 : 0.9801
 training map@3 : 1.10945
 training map@5 : 1.18806

However, when setting eval_at = 1,2,3,4,5, we get
training map@1 : 0.9801
training map@2 : 0.96393
training map@3 : 0.953842
training map@4 : 0.942682
training map@5 : 0.922106

The values of MAP@3 (also MAP@5) in these two different settings are different. In my opinion, these values should be the same.

Is this a bug or I did something wrong?

**Comment by guolinke** [comment]
sorry, it is a bug. have fixed.

**Comment by guolinke** [comment]
It seems there is another bug. fixed in https://github.com/Microsoft/LightGBM/commit/e9ac42c31cc15a9875583854a3ef107d55ec5c31

**Comment by harryshics** [comment]
Thanks.
