### ISSUE TITLE
__func__ and MSVS2013

### ISSUE THREAD

**Issue by i3v** [Microsoft/LightGBM#817]
The `__func__` keyword, which is used in just two files, [here](https://github.com/Microsoft/LightGBM/blob/f8597c93bce24724349b8a17ffc4fab05b64e97c/src/metric/xentropy_metric.hpp#L81) and [here](https://github.com/Microsoft/LightGBM/blob/f8597c93bce24724349b8a17ffc4fab05b64e97c/src/objective/xentropy_objective.hpp#L54) seem to be not supported in older MSVS versions (pre-MSVS2015). 

MSVS2013 is able to compile all the code if I add 

```
#ifndef __func__
#define __func__ __FUNCTION__
#endif
```
to these two files. 

I'm not sure what's the best way to fix this. Maybe just add it to `LightGBM/utils/common.h`?

**Comment by guolinke** [comment]
@i3v 
you can use ```_MSC_VER ``` macro. 
e.g.
```
#if (_MSC_VER <= 1800)
...
#endif
```

**Comment by i3v** [comment]
@guolinke 
Yep, it looks like [my initial approach is not correct at all](https://stackoverflow.com/a/2282433/1032586).

So, is `LightGBM/utils/common.h` OK for this?
Should I submit a PR?

**Comment by guolinke** [comment]
@i3v you can create a PR. 
BTW, maybe put it in the `meta.h` is better.

**Comment by i3v** [comment]
The PR is now merged, thanks, @guolinke !
