### ISSUE TITLE
[python package] not raising exceptions

### ISSUE THREAD

**Issue by pplonski** [Microsoft/LightGBM#818]
The python package is not always raising exceptions, below is example code which ends with core dump and no exception is raised. 

```
import numpy as np
import lightgbm as lgb

try:
    lgb_train = lgb.Dataset(np.random.rand(10,1), np.random.rand(10))
    model = lgb.train({"feature_fraction": 0.5}, lgb_train)
except Exception:
    print 'ups, should be exception here'

```

I got following output:
```
[LightGBM] [Info] Total Bins 0
[LightGBM] [Info] Number of data: 10, number of used features: 0
Floating point exception (core dumped)
```

Thank you!

**Comment by wxchan** [comment]
It's not python related. I think it's caused by 0 features.

**Comment by pplonski** [comment]
Yes, the problem is caused by 0 features - I set it on purpose. The script is finishing with core dump, it should raise exception.
