### ISSUE TITLE
c_api: some experiences

### ISSUE THREAD

**Issue by bwilbertz** [Microsoft/LightGBM#82]
Hi all,

I've been hacking c_api this weekend in order to run some experiments from R. Doing so, I ran into some issues, which I would like to share here:

### Exposing C++ Objects
Why not directly exposing some C++ Objects like [Booster](https://github.com/Microsoft/LightGBM/blob/master/src/c_api.cpp#L23)? This would make creation of R (#19) and Python(#11)-Bindings quite straight forward, since Rcpp and python-boost provide excellent support for wrapping C++ Objects into these languages.
As a plus, Python and R garbage collector will automatically call the destructor of those objects, so no need to register any finalizer calling some explicit destruction method, etc.
Moreover, exceptions can be simply propagated into R or Python, without having to worry about unrolling the stack correctly.

There is really no reason to go back to C (with all the nasty `void *`-casts...) in order to provide simple and clean bindings for those languages. If you still find there is good reason to stick to plain C, one could also think of an `api.hpp`, which exposes `Booster` and some `Dataset` objects and `c_api.h` is only providing a thin C-layer on top of this (reusing the objects from `api.hpp`; that's actually what I did for my experiments).

### Error handling
Support for error messages is not yet available (cf. [LGBM_GetLastError](https://github.com/Microsoft/LightGBM/blob/master/src/c_api.cpp#L163)) and in my eyes this could be easily solved by propagating exceptions. Unfortunately, there exists in the moment one big show stopper, when it comes to fatal logging:

[log.h](https://github.com/Microsoft/LightGBM/blob/master/include/LightGBM/utils/log.h#L71) terminates the complete process in case of a fatal error with `exit(-1)`, which is a no go for any library use case. No one wants in such a situation to lose his whole R/Python session, just because he gave some bad parameters to LightGBM.

**Comment by guolinke** [comment]
@bwilbertz 
1. Some languages don't support directly using c++ object,  like julia. 
However, your suggestion is considerable, I can try to expose c++ object as well. 
2. I will quick fix the ```exit(-1)``` this while using c_api. 
For the error message and exception, we need to use RAII feature, so it may take some time to enable this.

**Comment by bwilbertz** [comment]
@guolinke thanks for picking this up (and pushing RAII forward).

For the different headers like `boost/python.hpp`and `Rcpp.h`:
No, you would not need them on the API side (i.e. inside the [src](https://github.com/Microsoft/LightGBM/tree/master/src)-folder). The idea would be to include them only inside the respective package dirs.

Since your design of c_api is closely following the lines of xgboost, let's pick this as an example:

`Rcpp.h` would be included in [xgboost_r.cc](https://github.com/dmlc/xgboost/blob/master/R-package/src/xgboost_R.cc) and functions like 

```
SEXP XGBoosterCreate_R(SEXP dmats) {
  SEXP ret;
  R_API_BEGIN();
  // transform input args
  [...]
  BoosterHandle handle;
  CHECK_CALL(XGBoosterCreate(BeginPtr(dvec), dvec.size(), &handle));
  ret = PROTECT(R_MakeExternalPtr(handle, R_NilValue, R_NilValue));
  R_RegisterCFinalizerEx(ret, _BoosterFinalizer, TRUE);
  R_API_END();
  UNPROTECT(1);
  return ret;
}
```

could be just expressed as:

```
using namespace LightGBM;
SEXP XGBoosterCreate_R(SEXP dmats) {
  // transform input args
  [...]
  Rcpp::XPtr < Booster > handle(new Booster(_input_args));

  return handle;
}
```

Similar with smart pointers from Python Boost (or even directly map the complete Booster object into a python object using `boost::python::class`).

**Comment by guolinke** [comment]
@bwilbertz 
Your point is : 
1. put "Booster" and its relative functions to same class, and place into one header. 
2. For python and R binding, using different code the expose "Booster" and "Dataset" in their own package dirs?

**Comment by bwilbertz** [comment]
Yes, having certain C++ objects exposed in a stable API and wrapping them for R & Python into their corresponding smart pointers + exception handling.

Note, that for providing a R package, there is no way to do so without writing a certain amount of C or C++ code **specific** for R. It's just the question if you want to handle all the R `PROTECT`/`R_RegisterCFinalizerEx` stuff by yourself or use a more modern Rcpp style (since we already have nice C++ objects around).

And I guess that you want to use some kind of garbage collection in R/Python, since relying on the end user to explicitly calling a delete function in order to free memory could be a bit problematic.

**Comment by guolinke** [comment]
@bwilbertz OK, I see. 
So we still call the c style function in Python/R, right? These c++ objects are mainly use for GC? 

My original idea is wrapping a basic class in Python by using these c_api, and user use this basic class or more high level interfaces without caring about c_api.
I am not familiar with R, but it will be better if we can delete it in c++.

**Comment by guolinke** [comment]
@bwilbertz  one other problem is it needs additional library to compile api for R. Can we avoid this?

**Comment by bwilbertz** [comment]
Which additional library do you mean? Rcpp? 
The only dependency would be that the user needs Rcpp package installed, when installing a potential RLightGBM package (because compilation of R C/C++ code takes places during installation of R packages). But Rcpp is anyway required for a huge number of recent R packages, so not really a restriction.

**Comment by guolinke** [comment]
OK, it seems reasonable. 
However, for boost/python.h, it needs to install boost. So i think it is better to use c_api directly by ```ctypes``` in python.

**Comment by bwilbertz** [comment]
Fine. I will close this issue for now, since it was only meant to share some experiences.
