### ISSUE TITLE
Segfault with data or voting parallel operation over sockets

### ISSUE THREAD

**Issue by coulls** [Microsoft/LightGBM#822]
## Environment info
Operating System: Ubuntu 16.04.2 LTS
CPU: Amazon EC2 m3.2xlarge instance
C++/Python/R version: gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4)

## Error Message:
From rank 0 machine:
```
[LightGBM] [Info] Finished loading parameters
[LightGBM] [Warning] Set TCP_NODELAY failed.
[LightGBM] [Info] Trying to bind port 12400...
[LightGBM] [Info] Binding port 12400 succeeded
[LightGBM] [Warning] Set TCP_NODELAY failed.
[LightGBM] [Info] Listening...
[LightGBM] [Warning] Set TCP_NODELAY failed.
[LightGBM] [Info] Connected to rank 1
[LightGBM] [Info] Local rank: 0, total number of machines: 2
[LightGBM] [Info] Finished initializing network
Segmentation fault (core dumped)
```

From rank 1 machine:
```
[LightGBM] [Info] Finished loading parameters
[LightGBM] [Warning] Set TCP_NODELAY failed.
[LightGBM] [Info] Trying to bind port 12400...
[LightGBM] [Info] Binding port 12400 succeeded
[LightGBM] [Info] Listening...
[LightGBM] [Warning] Set TCP_NODELAY failed.
[LightGBM] [Warning] Set TCP_NODELAY failed.
[LightGBM] [Info] Connected to rank 0
[LightGBM] [Info] Local rank: 1, total number of machines: 2
[LightGBM] [Info] Finished initializing network
Segmentation fault (core dumped)
```

## Reproducible examples
Using example from LightGBM/examples/parallel_learning/

## Steps to reproduce

1. Clone master branch of LightGBM repository
2. Build using standard installation instructions from https://github.com/Microsoft/LightGBM/wiki/Installation-Guide
3. Set mlist.txt in LightGBM/examples/parallel_examples/ to available machine IPs
4. Change existing train.conf to data parallel (voting parallel produces similar results)
```
tree_learner = data
```
5. Run LightGBM command per instructions in README.md
```
lightgbm config=train.conf
```

**Comment by coulls** [comment]
This also occurs with MPI-based parallel operation.

Segmentation fault occurs here:  https://github.com/Microsoft/LightGBM/blob/master/src/io/dataset_loader.cpp#L744

**Comment by guolinke** [comment]
@coulls  can you try the latest code ?

**Comment by coulls** [comment]
This appears to work now.  Thank you!
