### ISSUE TITLE
Memory error occurs when  preparing training

### ISSUE THREAD

**Issue by yananchen1989** [Microsoft/LightGBM#826]
My memory is 32G and swap memory is also 32G. Train data is 16G.
After converting it(pandas df format) to lightgbm dataset,  I deleted the pandas df to release RAM. 
There is much RAM left and I find that in the begin of training, it costs too much memory although in the course of training, the RAM usage % is very low. 
So why in the beginning of training, there alwasys comes memory error.
How many RAM should be prepared for the training. 

```
MemoryError                               Traceback (most recent call last)
<ipython-input-15-8ed11fc31ab5> in <module>()
     17 print 'Start training...'
     18 # train
---> 19 gbm = lgb.train(params,lgb_train,num_boost_round=500)

/root/anaconda2/lib/python2.7/site-packages/lightgbm/engine.pyc in train(params, train_set, num_boost_round, valid_sets, valid_names, fobj, feval, init_model, feature_name, categorical_feature, early_stopping_rounds, evals_result, verbose_eval, learning_rates, keep_training_booster, callbacks)
    166     """construct booster"""
    167     try:
--> 168         booster = Booster(params=params, train_set=train_set)
    169         if is_valid_contain_train:
    170             booster.set_train_data_name(train_data_name)

/root/anaconda2/lib/python2.7/site-packages/lightgbm/basic.pyc in __init__(self, params, train_set, model_file, silent)
   1248             """construct booster object"""
   1249             _safe_call(_LIB.LGBM_BoosterCreate(
-> 1250                 train_set.construct().handle,
   1251                 c_str(params_str),
   1252                 ctypes.byref(self.handle)))

/root/anaconda2/lib/python2.7/site-packages/lightgbm/basic.pyc in construct(self)
    805                                 weight=self.weight, group=self.group, predictor=self._predictor,
    806                                 silent=self.silent, feature_name=self.feature_name,
--> 807                                 categorical_feature=self.categorical_feature, params=self.params)
    808             if self.free_raw_data:
    809                 self.data = None

/root/anaconda2/lib/python2.7/site-packages/lightgbm/basic.pyc in _lazy_init(self, data, label, max_bin, reference, weight, group, predictor, silent, feature_name, categorical_feature, params)
    615             self.handle = None
    616             return
--> 617         data, feature_name, categorical_feature, self.pandas_categorical = _data_from_pandas(data, feature_name, categorical_feature, self.pandas_categorical)
    618         label = _label_from_pandas(label)
    619         self.data_has_header = False

/root/anaconda2/lib/python2.7/site-packages/lightgbm/basic.pyc in _data_from_pandas(data, feature_name, categorical_feature, pandas_categorical)
    255             msg = """DataFrame.dtypes for data must be int, float or bool. Did not expect the data types in fields """
    256             raise ValueError(msg + ', '.join(bad_fields))
--> 257         data = data.values.astype('float')
    258     else:
    259         if feature_name == 'auto':

MemoryError:
```

**Comment by guolinke** [comment]
The issue seems from Pandas (caused by this line ```data = data.values.astype('float')```) . I think this will consume many memories.

From this log, I think you didn't really delete the `pandas` Data frame. 
The lgb.Dataset will store the DataFrame, and construct from it when calling ```lgb.train``` . 

You can try to convert the pandas to numpy matrix first, then use it to construct lgb.Dataset .

**Comment by yananchen1989** [comment]
```
lgb_train = lgb.Dataset(order_train[features], order_train[['reordered']].values.astype('int').flatten(),\
            categorical_feature = ['product_id','aisle_id','department_id','f40','f41','f41'])
```
Thanks. order_train is my pandas dataframe. After I create lgb_train, I excute: `delete order_train` in ipython. You mean that the delete execution is not in effect (actually the RAM has not been released at all) and the dataframe is still there.  So it leads to memory error.

By the way, when I use numpy array instead, what change should I make to `categorical_feature` parameters. Should it be like categorical_feature = ['c40', 'c60', c'98'] where specify the order of category columns. If train array's shape is (4833291, 243), c40 means that array[:,40] is the catrgory column. Thanks a lot and I am looking forward your help.

**Comment by guolinke** [comment]
I think you can get feature_name from pandas.DataFrame. And you set feature_name and categorical_feature at the same time when define a lgb.Dataset. In that case, you can use the feature_name in categorical_feature (like `categorical_feature = ['product_id','aisle_id','department_id','f40','f41','f41']`).

**Comment by yananchen1989** [comment]
Fine.  This should solve the memory error problem. 
```
order_train_array = order_train[features].values
labels = order_train['reordered'].values.astype('int').flatten()
del order_train  # delete dataframe to release memory 
lgb_train = lgb.Dataset(order_train_array, labels, feature_name = features, categorical_feature =                                ['product_id','aisle_id','department_id','f40','f41','f41'])
```

**Comment by makrand12** [comment]
### Guys help me with this memory error, below is the code and pic shows the error
cat_cols = ["channelGrouping", "device.browser", 
            "device.deviceCategory", "device.operatingSystem", 
            "geoNetwork.city", "geoNetwork.continent", 
            "geoNetwork.country", "geoNetwork.metro",
            "geoNetwork.networkDomain", "geoNetwork.region", 
            "geoNetwork.subContinent", "trafficSource.adContent", 
            "trafficSource.adwordsClickInfo.adNetworkType", 
            "trafficSource.adwordsClickInfo.gclId", 
            "trafficSource.adwordsClickInfo.page", 
            "trafficSource.adwordsClickInfo.slot", "trafficSource.campaign",
            "trafficSource.keyword", "trafficSource.medium", 
            "trafficSource.referralPath", "trafficSource.source",
            'trafficSource.adwordsClickInfo.isVideoAd', 'trafficSource.isTrueD


for col in cat_cols:
    print(col)
    lbl = LabelEncoder()
    lbl.fit(list(train_df[col].values.astype('str')) + list(test_df[col].values.astype('str')))
    train_df[col] = lbl.transform(list(train_df[col].values.astype('str')))
    test_df[col] = lbl.transform(list(test_df[col].values.astype('str')))
_

![memory_error](https://user-images.githubusercontent.com/14368257/45933231-48b38100-bfa6-11e8-847a-0a7e865a738a.png)
