### ISSUE TITLE
Issues with installing GPU-enabled on Windows 10.

### ISSUE THREAD

**Issue by tyokota** [Microsoft/LightGBM#827]
I am trying to install the GPU-enabled LGB package in Windows 10... I see the following error:

```
C:\Users\tyoko\AppData\Local\Temp\RtmpgDP3Zd\LightGBM\build>cmake -DCMAKE_GENERATOR_PLATFORM=x64 -DUSE_GPU=1..
CMake Error: The source directory "C:/Users/tyoko/AppData/Local/Temp/RtmpgDP3Zd/LightGBM/build" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.

C:\Users\tyoko\AppData\Local\Temp\RtmpgDP3Zd\LightGBM\build>cmake --build . --target _lightgbm  --config Release
Error: could not load cache
Installing package into 'C:/Users/tyoko/Documents/R/win-library/3.4'
(as 'lib' is unspecified)
* installing *source* package 'lightgbm' ...
** libs
installing via 'install.libs.R' to C:/Users/tyoko/Documents/R/win-library/3.4/lightgbm
Error in eval(ei, envir) : Cannot find lib_lightgbm.dll
* removing 'C:/Users/tyoko/Documents/R/win-library/3.4/lightgbm'
* restoring previous 'C:/Users/tyoko/Documents/R/win-library/3.4/lightgbm'
[1] TRUE
Warning messages:
1: running command 'C:\Users\tyoko\AppData\Local\Temp\RtmpgDP3Zd\temp.bat' had status 1
2: running command '"C:/PROGRA~1/R/R-34~1.1/bin/x64/R" CMD INSTALL -l "C:\Users\tyoko\Documents\R\win-library\3.4" "C:/Users/tyoko/AppData/Local/Temp/RtmpgDP3Zd/LightGBM/R-package"' had status 1
3: In install.packages(file.path(lgb_git_dir, "LightGBM", "R-package",  :
  installation of package 'C:/Users/tyoko/AppData/Local/Temp/RtmpgDP3Zd/LightGBM/R-package' had non-zero exit status
```
Here's a snapshot of my PATH:
![image](https://user-images.githubusercontent.com/4334198/29240202-d23d12ca-7efb-11e7-857e-d391929e04ee.png)

Only installed 64-BIT R/R-Tools:
![image](https://user-images.githubusercontent.com/4334198/29240209-017847d0-7efc-11e7-9fe7-501ca9dd99db.png)

![image](https://user-images.githubusercontent.com/4334198/29240212-0ed537a8-7efc-11e7-8702-74b1d5b6d711.png)

Running out of ideas. Please help...

**Comment by guolinke** [comment]
It seems you are installing R package ? 
please refer to https://github.com/Microsoft/LightGBM/tree/master/R-package . 
And Set use_gpu to TRUE in R-package/src/install.libs.R

**Comment by tyokota** [comment]
Still the same issue with the .dll not being found..,
![image](https://user-images.githubusercontent.com/4334198/29243617-1a3123b2-7f3f-11e7-8f99-f3c2a7a6c71d.png)

**Comment by guolinke** [comment]
@tyokota 
can you provide the full log ? 
BTW, if you updating windows 10 recently, you may need to reinstall nvidia driver and cuda.

**Comment by tyokota** [comment]
@guolinke that was exactly it. I reinstalled Nvidia drivers and Cuda toolkit/CudNN.

**Comment by patarol** [comment]
@guolinke it seems that I have a similar issue when trying to install LightGBM for R. I get this erros message after type: `R CMD INSTALL --build . --no-multiarch`
`* installing to library 'C:/Users/luciano.pataro/Documents/R/win-library/3.4'
* installing *source* package 'lightgbm' ...
** libs
installing via 'install.libs.R' to C:/Users/luciano.pataro/Documents/R/win-library/3.4/lightgbm
Warning: comando ejecutado 'cmake  -G "MinGW Makefiles"  ..' tiene estatus 127
Warning: comando ejecutado 'cmake  -G "MinGW Makefiles"  ..' tiene estatus 127
MINGW3~1.EXE: *** No rule to make target '_lightgbm'.  Stop.
Warning: comando ejecutado 'mingw32-make.exe _lightgbm -j' tiene estatus 2
Error in eval(ei, envir) : Cannot find lib_lightgbm.dll
* removing 'C:/Users/luciano.pataro/Documents/R/win-library/3.4/lightgbm'`

Any idea what I am doing wrong?
Thank you
