### ISSUE TITLE
CV method restarts model each time

### ISSUE THREAD

**Issue by fulldecent** [Microsoft/LightGBM#828]
I am using this code 

```
classifier = lgb.Booster(
    params=params, 
    train_set=lgb_train_set,
)

result = lgb.cv(
    init_model=classifier,
    params=params, 
    train_set=lgb_train_set,
    num_boost_round=1000,
    early_stopping_rounds=20,
    verbose_eval=50,
    shuffle=True
)
```

It is my understanding that running the latter line multiple times would continue training the model. This would be useful if you would like to modify parameters and train it some more. Or maybe if you would like to feed in additional data. However when I try with the above it will erase and restart the model each time.

I have also posted this in https://stackoverflow.com/questions/45654998/lightgbm-continue-training-a-model to seek a workaround. But I am posting here because I think the CV method is not working as intended.

**Comment by Laurae2** [comment]
> It is my understanding that running the latter line multiple times would continue training the model.
> However when I try with the above it will erase and restart the model each time.

It is the expected behavior.

> This would be useful if you would like to modify parameters and train it some more. Or maybe if you would like to feed in additional data.

You can't resume training with a different dataset.

> But I am posting here because I think the CV method is not working as intended.

What is not working?

**Comment by fulldecent** [comment]
I am reading the source code at 

https://github.com/Microsoft/LightGBM/blob/70b17a545bd90ea92b4518c5e4f3548ab8a11b15/python-package/lightgbm/basic.py#L994-L1005

which states:

> Set predictor for continued training, not recommand for user to call this function.
> Please set init_model in engine.train or engine.cv

So it seems to me that continued training is supported but I am not doing it right.

**Comment by Laurae2** [comment]
ping @wxchan

**Comment by wxchan** [comment]
@fulldecent I check it yesterday, if you set init_model=None in lgb.cv, you will get different result. (w/o init model). How do you judge if it's a continued training or restart?

**Comment by guolinke** [comment]
@fulldecent updates ?

**Comment by fulldecent** [comment]
Here is my test case:

![screen shot 2017-08-20 at 5 18 26 pm](https://user-images.githubusercontent.com/382183/29498502-f586a17a-85cb-11e7-823e-4e4c53e39cb8.png)

And then immediately after, I run the same line:

![screen shot 2017-08-20 at 5 20 37 pm](https://user-images.githubusercontent.com/382183/29498518-fdcc3156-85cb-11e7-9b2a-37360dda1c8c.png)

My expectation was that run 2 would start with a score of 0.0677 because the knowledge from the first run would be incorporated. Instead, the second run is redoing everything from scratch.

**Comment by wxchan** [comment]
cv is training muplite models. we can't change one gbm object (init_model) into multiple gbms object.

**Comment by guolinke** [comment]
@wxchan init model can be used in CV.
@fulldecent from you code, you both use ```init_model=classfier``` in two runs.

**Comment by fulldecent** [comment]
@guolinke Correct I thought the CV was mutating the classifier object. This is because the CV method does not provide a classifier as an output.

**Comment by guolinke** [comment]
@fulldecent 
The lgb.CV doesn't return the lgb.Booster object. As a result, you cannot use it as the init_model.
You should use the return object of lgb.train as init_model.
