### ISSUE TITLE
set 'nthread' param is not work when using booster.predict() , there are too many threads

### ISSUE THREAD

**Issue by xujianjlu** [Microsoft/LightGBM#834]
Please search your question on previous issues, [stackoverflow](https://stackoverflow.com/questions/tagged/lightgbm) or other search engines before you open a new one.

For bugs and unexpected issues, please provide following information, so that we could reproduce on our system.

## Environment info
Operating System:
CPU:
C++/Python/R version:

## Steps to reproduce

1.
2.
3.

**Comment by guolinke** [comment]
please use the latest code, I think it is fixed.
