### ISSUE TITLE
Training on GPU does not utilise GPU properly 

### ISSUE THREAD

**Issue by mhmoudr** [Microsoft/LightGBM#836]
Mainly the issue is GPU utilisation. as after building LightGBM for GPU up to the described process, and running on a sample dataset, while monitoring both CPU and GPU (please check attached screen shot)
The process move the training dataset into GPU memory and nvidia-smi recognise it as a running process, while during the training GPU utilisation does not exceed 2-5%, on the other hand CPU seems to be fully utilised.

I am not sure if this is a defect of a kind of incomplete implementation.

## Environment info
Operating System: Ubuntu 16
CPU: 2 Xeon (total 48 Cores )
C++ version: latest C++ and calling the CLI process 

## Error Message:
![screenshot from 2017-08-16 09-38-27](https://user-images.githubusercontent.com/2888943/29341688-54a45140-8269-11e7-859a-9bb7fb2e2b2f.png)

N/A
## Steps to reproduce
Compile for GPU using the provided docs.
use the following config :
data = "/path/to/libsvm/file"
num_iterations = 3000
learning_rate = 0.01
max_depth = 12
device = gpu
gpu_platform_id = 0
gpu_device_id = 0

**Comment by fenqingr** [comment]
same thing here, most of time GPU usage stays at 0% with some spike ~10% to 20%. I though my CPU( i5 2500K @ 4G) caused bottle necking my GPU performance and from your case I believe it is not the case.

**Comment by guolinke** [comment]
It is normal if your training data is small. 
BTW, you are using `max_depth` = 12, but forget to set ```num_leaves```, so you are training the small model, which will also cause the low gpu usage.

**Comment by mhmoudr** [comment]
I am using a dataset that have ~14Mil row and ~1000 sparse features the memory foot print as you can notice in the `nvidia-smi` was 649MB, and in term of the `num_levels` I have set it to 12 as well and I had exactly the same behavior

**Comment by guolinke** [comment]
@mhmoudr ```num_leaves=2^max_depth```.  
@huanzhang12 I remember the sparse feature cannot use GPU to speed up, right ?

**Comment by mhmoudr** [comment]
As I am writing this I am running using `num_levels = 24` (as depth still on 12) but GPU utilization is closer to 1% this time.
The question that I have why CPU in this scenario are utilized with something close to 80%, doesn't this mean that all of the heavy lifting (calculation) that supposed to happen on GPU cores is happening actually on CPU? as in other packages when I train on GPU, CPUs seems to be idle (nearly doing nothing)

**Comment by guolinke** [comment]
@mhmoudr refer to #768 .
The LightGBM GPU still need to use CPU to do some calculations. 
And all sparse features cannot use GPU to speed up, so the CPU usage is high in your case.

**Comment by huanzhang12** [comment]
@mhmoudr Sparse features processing has too much irregularity and are currently not accelerated on GPU. Try to set `sparse_threshold` parameter to 1.0 or a number very close to 1.0 and see if there are any improvement. See more details in the [GPU performance tuning guide](https://github.com/Microsoft/LightGBM/blob/master/docs/GPU-Performance.md).

**Comment by Noxoomo** [comment]
I had the same problem. After changing num_threads option from cpu_cores (in my case 16) to 1 solved the problem. BTW, it's bug and should be fixed.
