### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by henry0312** [Microsoft/LightGBM#839]
Memory leak happens with the current HEAD of master (f1e3ab923cc6d296c95d28afb3c883dce0119628).
With v2.0.4, memory leak doesn't happen.

## Environment info

Operating System: Ubuntu 16.04.3
CPU: Intel Xeon E5-2623 v3
C++/Python/R version: gcc 5.4.0 and Python 3.6.1

## Reproducible examples

```python
import numpy
from lightgbm import LGBMRegressor

x_data = numpy.random.randint(0, 100, size=(10000, 100))
y_data = numpy.random.randint(0, 5, size=10000)

for i in range(10000):
    print(i)
    gbm = LGBMRegressor()
    gbm.fit(x_data, y_data)
    del gbm
```

## Steps to reproduce

1. Just run the above code

**Comment by henry0312** [comment]
There is something wrong with https://github.com/Microsoft/LightGBM/pull/673.

**Comment by wxchan** [comment]
@henry0312 don't have machine to run it right now. Can you paste error message here?

**Comment by Laurae2** [comment]
@henry0312 Can you provide RAM usage for these commits after your script runs?

f7d190a
ac73638

Make sure you also run the garbage collector at the end (otherwise it is not comparable).

**Comment by henry0312** [comment]
@wxchan There is no error message. Usage of memory just increases

**Comment by henry0312** [comment]
* https://github.com/Microsoft/LightGBM/commit/f7d190aa5c021de10fd5924d782d2cdf4eee9494 : 6% of 128GB = about 7.68GB
* https://github.com/Microsoft/LightGBM/commit/ac73638f29d9f5647922c69c6cbf983228fe382c : 0.1% of 128GB = about 1.28GB

```python
import numpy
from lightgbm import LGBMRegressor


x_data = numpy.random.randint(0, 100, size=(10000, 100))
y_data = numpy.random.randint(0, 5, size=10000)

for i in range(1000):
    print(i)
    gbm = LGBMRegressor()
    gbm.fit(x_data, y_data)
    del gbm
```

Note that `range(1000)`.

**Comment by henry0312** [comment]
@Laurae2 `gc.collect()` doesn't seem to fix the issue.

**Comment by Laurae2** [comment]
@henry0312 strangely in R the memory never increases.

```r
# Reproduce @henry0312 gc issue: https://github.com/Microsoft/LightGBM/issues/839#issuecomment-322723009

library(lightgbm)

x_data <- matrix(rnorm(n = 1000000, mean = 0, sd = 100), nrow = 10000, ncol = 100)
y_data <- rnorm(n = 10000, mean = 0, sd = 5)

data <- lgb.Dataset(x_data, label = y_data)

for (i in 1:1000) {
  print(i)
  gbm <- lgb.train(params = list(objective = "regression"),
                   data = data,
                   10)
  rm(gbm)
  gc(verbose = FALSE)
}
```

**Comment by guolinke** [comment]
@henry0312 can you try the lgb.train ?

**Comment by henry0312** [comment]
@Laurae2 That is because https://github.com/Microsoft/LightGBM/commit/f7d190aa5c021de10fd5924d782d2cdf4eee9494 affects only Python.

**Comment by Laurae2** [comment]
@henry0312 It means in Python there is a pointer or something preventing the garbage collector to clear everything from the `gbm` variable. It's weird that a new (unused in this case) parameter causes this issue.

**Comment by guolinke** [comment]
@wxchan I think it is cause by this line: https://github.com/Microsoft/LightGBM/commit/f7d190aa5c021de10fd5924d782d2cdf4eee9494#diff-c90239f8147ba65eec9e89412fe27c01R209 

you should free the handle first, than load string. Otherwise the handle will be just override without free memory

**Comment by henry0312** [comment]
@guolinke There are also memory leaks with the below code whith uses `lgb.train`:

```python
import numpy
import lightgbm as lgb


x_data = numpy.random.randint(0, 100, size=(10000, 100))
y_data = numpy.random.randint(0, 5, size=10000)

lgb_train = lgb.Dataset(x_data, y_data)

# specify your configurations as a dict
params = {
    'task': 'train',
    'boosting_type': 'gbdt',
    'objective': 'regression',
    'metric': {'l2', 'auc'},
    'num_leaves': 31,
    'learning_rate': 0.05,
    'feature_fraction': 0.9,
    'bagging_fraction': 0.8,
    'bagging_freq': 5,
    'verbose': 0
}

for i in range(1000):
    print(i)
    gbm = lgb.train(params,
                    lgb_train,
                    num_boost_round=20)
```
