### ISSUE TITLE
Instalation without MS Visual Studio

### ISSUE THREAD

**Issue by gugatr0n1c** [Microsoft/LightGBM#84]
Hi,

is there any chance to get working this library without using Visual Studio (Win7 64bit, Win10 64bit)?

a] pre-built, e.i. as mxnet is providing?

b] using something else like MinGW as XGBoost is supporting?

**Comment by chivee** [comment]
@gugatr0n1c , It haven't be tested. But if you have MSBuild installed, you can using cmake to build it. It could also be build under MinGW environment.

**Comment by guolinke** [comment]
close for now, feel free to reopen

**Comment by sockfull** [comment]
Is there a suggested version of MinGW to use? I tried the original and mingw-w64 and both failed to compile. At the make step

**Comment by guolinke** [comment]
@sockfull 
https://github.com/Microsoft/LightGBM/wiki/Installation-Guide#cmake-with-mingw

**Comment by sockfull** [comment]
I was using those commands from the installation guide when I got errors. I am wondering if I have not setup MinGW appropriately though, I have only used it once before to compile . I downloaded it from here: 
https://sourceforge.net/projects/mingw/files/ for the installer. The gcc and base installations are installed, and cmake from https://cmake.org.
