### ISSUE TITLE
[question] reading & changing parameters of fitted model

### ISSUE THREAD

**Issue by geoHeil** [Microsoft/LightGBM#842]
How can I read the parameters of ideal `n_estimators` after early stopping from the model?

How can I change a parameter after fitting the estimator? I.e. I want to train with let's say 40 threads, but predict only with 2?

**Comment by guolinke** [comment]
1 use booster.best_iter
2 you can pass param dict to predict function

**Comment by geoHeil** [comment]
@guolinke 
`clf.booster_.best_iteration` works. I.e. when the result is **0** and `'n_estimators': 100` obviously 100 are correct.

But assuming the result was 10. Would this mean 10 iterations were applied during the best run?

**Comment by guolinke** [comment]
when best_iteration <= 0, it means using all models.
