### ISSUE TITLE
PR and commits to merge back

### ISSUE THREAD

**Issue by Laurae2** [Microsoft/LightGBM#846]
@guolinke Do you have an idea which PRs and commits should be merged back to master branch?

I'm thinking about the following:

* https://github.com/Microsoft/LightGBM/pull/840 [python] fix python memory leak
* https://github.com/Microsoft/LightGBM/pull/838 Remove check of max_depth
* https://github.com/Microsoft/LightGBM/pull/832 python-package: fix version
* https://github.com/Microsoft/LightGBM/pull/829 [R-package] Merge iterations and early stopping with params
* https://github.com/Microsoft/LightGBM/pull/819 Fix __func__ is not defined in MSVS2013
* https://github.com/Microsoft/LightGBM/pull/815 fix AMD APP SDK download link
* https://github.com/Microsoft/LightGBM/pull/806 [MRG] [python] check params for num_boost_round & early_stopping_rounds
* https://github.com/Microsoft/LightGBM/pull/803 Create CODE_OF_CONDUCT.md
* https://github.com/Microsoft/LightGBM/pull/799 Fix [R-package] Prevent remembering parameters
* https://github.com/Microsoft/LightGBM/pull/797 [R-package] Unhandled errors must error properly
* https://github.com/Microsoft/LightGBM/pull/796 [R-package] Prevent remembering parameters
* https://github.com/Microsoft/LightGBM/pull/792 [python] fix categorical_feature in Dataset
* https://github.com/Microsoft/LightGBM/pull/791 [R-package] CV Improvements
* https://github.com/Microsoft/LightGBM/pull/786 [python] Dataset params back up before training
* https://github.com/Microsoft/LightGBM/pull/785 add docs for converting model to if-else format
* https://github.com/Microsoft/LightGBM/pull/784 fix R crash problem.
* https://github.com/Microsoft/LightGBM/pull/776 Update docs

Unsure if possible in the current state:

* https://github.com/Microsoft/LightGBM/pull/825 Explain individual predictions using SHAP value feature attributions

There are also your commits I'm missing as they don't appear in the PRs / commit history.

**Comment by henry0312** [comment]
oh my god...

**Comment by guolinke** [comment]
sorry, I will add them back

**Comment by henry0312** [comment]
If you don't want to lose contributors, don't do any force push to master, I think...
Good luck, @guolinke!

**Comment by wxchan** [comment]
What happened?

**Comment by henry0312** [comment]
To revert the direct support of categorical feature probably, he returned master to 64e52093b37d710836b74ce4291013a46d5a0dec, although [v2.0.6](https://github.com/Microsoft/LightGBM/tree/v2.0.6) still exists.
cf. https://github.com/Microsoft/LightGBM/commit/4181fd9f9b3e89f11eaa8442952518a30f48afd3

**Comment by guolinke** [comment]
used cherry-pick to add these PR back.
