### ISSUE TITLE
Categorical Feature Support

### ISSUE THREAD

**Issue by ChenZhiyong** [Microsoft/LightGBM#853]
There are some existing open-source GBDT tools support categorical feature:
1. Catboost, which converts the categorical features to numerical features.
2. H2O.gbm, which uses a sorting based solution and splits categories into 2 subset. 

Though LightGBM also support categorical feature, but it simply is a one-vs-rest partition. I don't think it is better than Catboost/H2O's solution. 

I would like to contribute this.

**Comment by AbdealiJK** [comment]
I may be wrong but after https://github.com/Microsoft/LightGBM/issues/699 this is not a one-hot-encoding based categorical feature support anymore.
Its more involved and theoretically nicer

What categorical support are you thinking of ?
