### ISSUE TITLE
LGBM_BoosterPredictForCSR performance is too slow? 

### ISSUE THREAD

**Issue by hlee13** [Microsoft/LightGBM#856]
when predict on 200 Trees and 10 depth, average cost 40 ms

**Comment by guolinke** [comment]
It depends on the number of features. 
When #feature is large, it will be slow.

**Comment by hlee13** [comment]
max feature num below 2000.  default cmake CFLAGS is O2?

**Comment by guolinke** [comment]
yeah, you can try O3.

can you show how you call LGBM_BoosterPredictForCSR ? 
you pass all data by one-call of LGBM_BoosterPredictForCSR ? or per data per call ?

**Comment by hlee13** [comment]
per data per call, cost 40ms, it is not my expectation. I think per data on 200 Trees and 10 depth, it will be return inside 10ms

**Comment by guolinke** [comment]
per data per data is very inefficient.
every time calling the LGBM_BoosterPredictForCSR, it has an additional init cost, and will be run in single thread.

The LGBM_BoosterPredictForCSR ( and other prediction apis) are designed for the multi-row data.

**Comment by hlee13** [comment]
additional init cost could be avoid? Because per data represent per request, it need real time.

**Comment by hlee13** [comment]
additional init cost is in omp lib?

**Comment by guolinke** [comment]
@hlee13 
refer to this function: https://github.com/Microsoft/LightGBM/blob/master/src/c_api.cpp#L174-L207

you can separate it to the two function:
1. init:  https://github.com/Microsoft/LightGBM/blob/master/src/c_api.cpp#L179-L195
2. predict: https://github.com/Microsoft/LightGBM/blob/master/src/c_api.cpp#L202

**Comment by Yang-HangWA** [comment]
@guolinke How can I split the init and predict work when I use python to do predict job?

**Comment by guolinke** [comment]
@Yang-HangWA sorry, you can't do it in python.
