### ISSUE TITLE
[R] Decision Type always 'is' in Mac while "<=" in Windows

### ISSUE THREAD

**Issue by alberthkcheng** [Microsoft/LightGBM#858]
I try to run the basic walkthrough demo for R and use lgb.model.dt.tree to get a data table.

But I got different data table for Windows and Mac. In 'decision_type' column, Mac shows "is", Windows shows "<=".

I try run another model in Mac with some continuous variable but the decision_type is "is". It seems the split is actually on <= although it show "is"...

update: when I save the model in Mac, decision_type=2 2 2 2 2 2 2
I think decision type should be only 0 or 1?

**Comment by guolinke** [comment]
you are using an old version in Macs. Please update to latest version.
And it may be somethings wrong for your R installation in MAC.

decision_type is not simply 0/1 now. It is a bitset (8-bit) contains the information of missing value handle.
