### ISSUE TITLE
Working with categorical features in R

### ISSUE THREAD

**Issue by hadjipantelis** [Microsoft/LightGBM#867]
Hello,

Thank you for making `LightGBM` available. Unfortunately I cannot find a documentation example on how to use the R implementation with categorical features. Is there one? 

 While in the [Python docs](https://github.com/Microsoft/LightGBM/blob/55de8ea651aa4f3af80d78d0452593be4e13bada/docs/Python-intro.md) clearly suggest that categorical features will *not* benefit from one-hot encoding and should be explicitly defined as categorical the  documentation for R is absent on this point and none of the [demo](https://github.com/Microsoft/LightGBM/tree/b6c973af3b7db1f8c8d07f79d0b51bf10859ced3/R-package/demo) scripts shows a relevant example. Outside LightGBM resources there was [this](https://github.com/szilard/GBM-perf/issues/2) so I suspect that we should do something like: `originalDataNice <- apply( originalData, 2, function(x){ if(is.numeric(x)){ x } else{ as.numeric(as.factor(x)) }})` before passing them to `lgb.Dataset` but things are a bit fuzzy  at this point... I have seen #561 and #699 but they do not offer a definite answer. Should I just do a numerical encoding on my own (say binary) and get things out of the way?

Minor point: There seems to be a bit of a disconnect between the error messages and the documentation. For example the error message can read: "`[LightGBM] [Fatal] Size of feature_names error, should equal with total number of features`" while there not actual argument in the `lgb.Dataset` or `lgb.Dataset.construct` that is called `features_names`.
(I am using 603bffc if that makes a difference - by the way, the install was so much smoother than the one I tried a few months back! Good job!)

Once again, thank you for all your work on `LightGBM`, it is very impressive.

Pantelis

**Comment by Laurae2** [comment]
See https://github.com/Microsoft/LightGBM/pull/228 for R.

Requirements are identical to command line interface, except it is 1-indexed instead of 0-indexed.

**Comment by hadjipantelis** [comment]
Thank you for the clarification; I will look into the CLI documentation in more detail. 

In any case, an example in demo scripts would help; aside `categorical_feature` also the `free_raw_data` functionality is a bit mystifying as the script provided does not explain how it is used.

Thanks again; feel free to close this issue.

**Comment by Laurae2** [comment]
You can just use `categorical_feature`.

**Comment by Laurae2** [comment]
@guolinke You can close this.
