### ISSUE TITLE
Saving 2GB+ models

### ISSUE THREAD

**Issue by i3v** [Microsoft/LightGBM#868]
Saving really large models (resulting in file sizes >2GB) fails due to limitations in code.
Here's a code demonstrating this:
```
import unittest
from unittest import TestCase
import numpy as np
import lightgbm as lgb


class TestCategoricalAccuracyWithUnknowns(TestCase):

    def setUp(self):
        np.random.seed(0)

    def test_saving_2GB(self):

        # Generate a large enough dataset (10M samples, 20 classes, 32 features)
        x_train = np.random.randint(0, 2**30, size=[10**7, 32])
        y_train = np.sum(np.expand_dims(x_train[:, 0], axis=1) > x_train[:, 1:32], axis=1)
        y_train = y_train % 20

        # create large enough LightGBM model (that would take >2GB in text format)
        params = {
            'task': 'train',
            'boosting_type': 'gbdt',
            'objective': 'multiclass',
            'metric': {'multi_error'},
            'num_class': 20,
            'num_leaves': 10**5,
            'learning_rate': 0.01,
            'verbose': 1
        }

        dataset = lgb.Dataset(x_train, y_train)
        gbm = lgb.train(params, dataset, num_boost_round=13)

        gbm.save_model('test.txt')  # no error, but file is broken

if __name__ == '__main__':
    unittest.main()
```
It should create ~2.3GB "test.txt" file.
(Note: needs ~32GB RAM and about a night and  on 2xE5-2630v3).

I do agree that such models are, probably, too large to be useful in daily practice. Still, personally, I ran into this issue during automatic meta-parameters tuning.

There are several places in code that, affecting this. Probably, the main limitation is [in c_api.h](https://github.com/Microsoft/LightGBM/blob/603bffcfac4a33ab243e52b9a0457be8b8cc5cbf/include/LightGBM/c_api.h#L680-L681) - it defines string length as `int`, instead of `int64_t` (or `size_t`). 

After fixing it (and few other files) I was able to make the test above work OK. (Not tested R yet)
Do you think changing those type in `c_api.h` is acceptable, and would be OK as a part of a PR?

PS [Here](https://github.com/i3v/LightGBM/commit/4ca5e1f4f147c5702ab4271032314af04899c335)'s my current patch.

**Comment by i3v** [comment]
Concerning R - AFAIU, it won't be that simple. 
I don't know much about R, but I've just googled a few things about it (`R-devel, package base version 3.4.0`).

1. They call objects with >2^31 elements "[long vectors](https://stat.ethz.ch/R-manual/R-devel/library/base/html/LongVectors.html)". And it looks like only some functions support such objects.

   > Currently all atomic (raw, logical, integer, numeric, complex, character) vectors, lists and expressions can be much longer on 64-bit platforms: such vectors are referred to as ‘long vectors’



2. Although "long", their "long vectors" [do not include](https://stat.ethz.ch/R-manual/R-devel/library/base/html/LongVectors.html) 1D long vectors:
   > Arrays (including matrices) can be based on long vectors provided each of their dimensions is at most 2^31 - 1: thus there are no 1-dimensional long arrays.


3. In particular, [strings should not exceed](https://stat.ethz.ch/R-manual/R-devel/library/base/html/Memory-limits.html) about 32-bit limit:
    > The number of bytes in a character string is limited to 2^31 - 1 ~ 2*10^9, which is also the limit on each dimension of an array



4. There's even no `as.integer64()` available by default, it's only provided as a separate package "bit64". And they [warn](https://cran.rstudio.com/web/packages/bit64/index.html) to not use it for subscripting.
    > WARNING: do not use them as replacement for 32bit integers, integer64 are not supported for subscripting by R-core



5. They use double to represent length of a "long vector":
    > such objects will have a length that is expressed as a double, and can be indexed by double vectors

Well.. Probably it's still possible to pass a long string in R... Say, as 2D array. But, IMHO, that won't look nice. So, it looks like the best thing one can do for R is to add a proper error message in the right place.

**Comment by guolinke** [comment]
refer to #372 and @Laurae2 
in our first version, the model is saved to file directly, without using string in R.
But it is hard to save/load Booster Object if using this way, so we change to use string to store the models. 
some solutions:
1. using 2D array and saving the string tree by tree.
2. using a more efficient format.
