### ISSUE TITLE
Expected behaviour of max_bin

### ISSUE THREAD

**Issue by alberthkcheng** [Microsoft/LightGBM#871]
What I understand is assuming I have a feature contains value [1,2,3,4,5,6] ,
if max_bin = 2, it will create at most 2 bin, e.g. [1,2,3], [4,5,6]
So the node split can only occur between 3.5.

However, when i do this in R, I still see the split at 1.5, 2.5, etc.

Did I misunderstand the meaning of max_bin?

**Comment by guolinke** [comment]
@alberthkcheng 
can you provide a re-produce sample ?

**Comment by alberthkcheng** [comment]
Now I think it could be caching problem.
I start with:
```
library(dplyr)
library(lightgbm)
set.seed(812)
data <- cbind(matrix(as.integer(10*rnorm(3000)), ncol = 3), rep(c(-1000, 1000), 500))
label <- as.integer(rowSums(data) > 0)
dtrain <- lgb.Dataset(data, label = label)
params <- list(objective = "binary", metric = "binary_logloss")
model <- lgb.train(params, dtrain,nrounds = 10,min_data = 1, min_data_in_bin=1,max_bin = 5, learning_rate = 1)
tree_df <- lgb.model.dt.tree(model)
tree_df %>% count(split_feature, threshold)
```
Everything looks fine. It have 5 bins. Then I run:
```
model <- lgb.train(params, dtrain,nrounds = 10,min_data = 1, min_data_in_bin=1,max_bin = 3, learning_rate = 1)
```
The result is exactly the same with before (there are 5 bins). What i did to get 3 bin is to reconstruct lgb.Dataset:
```
dtrain <- lgb.Dataset(data, label = label)
model <- lgb.train(params, dtrain,nrounds = 10,min_data = 1, min_data_in_bin=1,max_bin = 3, learning_rate = 1)
```
------------------------
Another Problem: If i set max_bin = 2, it crash (could be related to this [issue](https://github.com/Microsoft/LightGBM/issues/574))

**Comment by guolinke** [comment]
@alberthkcheng 
If you passing a Dataset to lgb.train, then this dataset is constructed, and it cannot be changed. 

if your feature have both negative and positive values, its max_bin should great than 2.

**Comment by alberthkcheng** [comment]
Thanks @guolinke , now i understand more about how these awesome thing works. 

I would assume the parameter under these [section](https://github.com/Microsoft/LightGBM/blob/master/docs/Parameters.md#io-parameters)  is used to construct the Dataset.

Do you think it would be better if the R / Python interface only allow defining those params in lgbm.Dataset() and require running lgb.Dataset.construct explicitly. Sometimes shorthand is convenient but also bring confusing.
