### ISSUE TITLE
Sane range of parameters for hyperparameters search? 

### ISSUE THREAD

**Issue by mrgloom** [Microsoft/LightGBM#872]
Can you specify sane range of parameters for hyperparameters search for binary and multiclass classification?

**Comment by Laurae2** [comment]
See https://github.com/Microsoft/LightGBM/issues/695

Applies to mostly any dataset.

But for common uses and fast optimal hyperparameter searches, only use `max_leaves` + `max_depth`, and optionally add `subsample` + `colsample_bytree`.
