### ISSUE TITLE
Possible memory leak (from R)

### ISSUE THREAD

**Issue by szilard** [Microsoft/LightGBM#879]
I'm trying to train a large number of models for this project: https://github.com/szilard/GBM-tune

I also want to ensemble the top models therefore I'm keeping the models in an R list. However memory usage is growing beyond expectation and also cannot account for the growth by looking at the memory footprint of the R objects in the session.

After 10 random param search iterations with 20 repeated CV:

memory usage of R process 26GB as reported by Linux

reported within R:
```
> gc()
            used   (Mb) gc trigger   (Mb)  max used   (Mb)
Ncells    706513   37.8    1442291   77.1   1442291   77.1
Vcells 525788016 4011.5  819430190 6251.8 575400965 4390.0
```
(so something like 6GB only (vs 26GB))

top RAM using objects:
```
> library(pryr)

> sort( sapply(ls(),function(x){object_size(get(x))/1e6}))
 ...
     rocr_pred              d         d_test      phat_avg1           phat
      6.803144       7.201024       7.201024       8.000200      16.000200
   d_test_list            mds        d1_test       d1_train        d0_test
    144.009280     151.016720     362.407264     375.728344     644.293560
            d0      d0_wrules       d0_train
    656.120656     656.144480     667.975728
```

so it looks like the 10*20 models take only 150MB (`mds` object), but something is taking 20GB of RAM...

Is lightgbm linking the model to the data and somehow the data is copied for each model (and maybe not freed)? (the train data is 600MB see above)

## Environment info
Operating System: Ubuntu 16.04
CPU: AWS EC2 r4.2xlarge
C++/Python/R version: Latest R and latest lightgbm from github

## Reproducible examples

Code [here](https://github.com/szilard/GBM-tune/blob/master/4_train_rs/run-tuning.R)

**Comment by Laurae2** [comment]
Try `reset_data` parameter on `lgb.train`, and/or remove the model after it was used. Each model uses a lot of memory as it holds the dataset separately. You can also `rm` + `gc` the model once used.

Also, you are free to use all cores on https://github.com/szilard/GBM-tune/blob/master/4_train_rs/run-tuning.R#L145 - unless you have too many cores in which case you have negative efficiency.

**Comment by szilard** [comment]
Thanks @Laurae2 

I'll try the `reset_data` param now.

What I want is 100 hyperparam combinations (each with 20 CV resamples) , then want to select top 10 and average the top 10, so I cannot really remove models until the end (well I could just keep the top 10 like a model "moving window"), but I'll try just `rm` the data and `gc()` first.

**Comment by szilard** [comment]
Btw I use half of cores because lightgbm used to be slower when using the hyper threaded cores, though I did not check again lately.

**Comment by Laurae2** [comment]
@szilard With `reset_data` the model will be as if the training data never existed, therefore it will have no link with the training data (and will not hold too much memory).

Note that with R, the automatic garbage collector does not work with custom objects from C/C++. You will need to manually call the garbage collector to clear memory left from models.

You can run the example below (it trains a model, and transforms the model into a "predictor model" - aka a model that can predict without the ability to retrain from the original data) with and without the garbage collector. Without garbage collector, the memory will steadily increase (very quickly).

```r
library(lightgbm)

set.seed(11111)
x_data <- matrix(rnorm(n = 100000000, mean = 0, sd = 100), nrow = 1000000, ncol = 100)
y_data <- rnorm(n = 1000000, mean = 0, sd = 5)

data <- lgb.Dataset(x_data, label = y_data)
data$construct()
gbm <- list()

for (i in 1:1000) {
  print(i)
  gbm[[i]] <- lgb.train(params = list(objective = "regression"),
                        data = data,
                        1,
                        reset_data = TRUE)
  gc(verbose = FALSE)
}
```

**Comment by szilard** [comment]
@Laurae2 Thanks for nice easily reproducible example (unlike mine).

With `reset=FALSE` you get after 500 iterations (not 1000): OS reports 27GB usage, while R gc() reports 1.5GB.

Just doing `reset=TRUE` will already improve things: OS reports 4.6GB.

Doing `reset=TRUE` and calling `gc()` in the loop will have OS 1.3GB. Thanks for the latest tip.

**Comment by NamLQ** [comment]
reset_data = TRUE does not work for lgb.cv. It said:
"Running k-fold cv ...[LightGBM] [Warning] Unknown parameter: reset"
