### ISSUE TITLE
[Feature] Lambdamart Mode

### ISSUE THREAD

**Issue by bj-wangjia** [Microsoft/LightGBM#88]
Are there any plan for modifications to be able to use LightGBM in Lamdamart mode?

**Comment by guolinke** [comment]
@bj-wangjia LightGBM support the lambdarank(lambdamart) , just set ```app=lambdarank``` and pass a query file or query_id (refer to https://github.com/Microsoft/LightGBM/wiki/Quick-Start#training-data-format).
