### ISSUE TITLE
Bagging does not perform a bootstrap sample

### ISSUE THREAD

**Issue by PetterS** [Microsoft/LightGBM#883]
When enabling `bagging_fraction`, each element of the data is picked 0 or 1 times. Bagging means [boostrap aggregation](https://en.wikipedia.org/wiki/Bootstrap_aggregating), so this is quite confusing.

In a bootstrap sample, elements are picked with replacement, i.e. potentially many times. It then does not make sense to require `bagging_fraction `≤ 1, since the bootstrap sample could be larger than the data (this is discussed in Breiman’s paper on Random Forests).

**Comment by guolinke** [comment]
Yeah, It actually is subrow, not the replacement sampling. 
We can add a note in the document.

**Comment by Laurae2** [comment]
Bagging in boosting (or by default) has no relation with Breiman's Random Forests.

In general, bagging is just taking a sample from the training set, without resampling (where the sample is called bag). The other meaning is a model average (bagging several LightGBM means taking average of the trained models).

**Comment by PetterS** [comment]
I completely agree that it has nothing to do with Random Forests per se.

However, bagging is literally short for “bootstrap aggregation,” and bootstrap means sampling with replacement. This library repuposes the term to mean without replacement, which is confusing.

**Comment by Laurae2** [comment]
@PetterS Bagging has several meanings and not only the one from Wikipedia (which is very biased towards Breiman, and that article is actually wrong).

Bagging techniques using sampling:

| Feature / Observations | Yes | No |
| --- | --- | --- |
| Yes | Patching / Random Patches | Subspacing / Random Subspaces |
| No | Pasting / Random Pastes | (non stochastic, population...) |

All these meta-algorithms fit under the bagging name. It is actually bootstrap aggregating which should not be confused directly with bagging, as it is a special case of pasting (pasting is done without replacement).

Although they are the theoretical names, it is very common to see the following denominations as hyperparameters for programs:
* Subspacing = Column Sampling
* Pasting = Bagging
* Boostrapping = Bootstrap

**Comment by PetterS** [comment]
Thanks a lot for the clarification @Laurae2!
