### ISSUE TITLE
Possible memory leak (Python)

### ISSUE THREAD

**Issue by coryandrewtaylor** [Microsoft/LightGBM#895]
Please search your question on previous issues, [stackoverflow](https://stackoverflow.com/questions/tagged/lightgbm) or other search engines before you open a new one.

Related issue: #879

For bugs and unexpected issues, please provide following information, so that we could reproduce on our system.

## Environment info
Operating System: Windows 7, 10
CPU: Intel Core i7-6820HQ (8 cores, 2.7 GHz)
C++/Python/R version: Python 3.6.0

## Error Message:
None

## Problem:
As in #879, I am seeing an increase in memory usage over time when calling `LGBMClassifier` repeatedly. However, deleting stale models and calling `gc.collect()` does not free up any memory.

## Code to Reproduce:
Code to reproduce the problem with and without garbage collection: https://gist.github.com/coryandrewtaylor/84c24b9a9442a2b331c768c01c5f4422

**Comment by guolinke** [comment]
@wxchan

**Comment by wxchan** [comment]
@coryandrewtaylor I didn't see memory leak with your gist. Are you using latest codes? Can you share your memory usage before and after training?

**Comment by coryandrewtaylor** [comment]
@wxchan I was on version 2.0.5 (which is the latest version available through `conda`). I've upgraded to version 2.0.6 via PyPI. The memory leak is gone.

Thanks!
