### ISSUE TITLE
GetAddress in socket_wrapper.hpp is not defined under _WIN32

### ISSUE THREAD

**Issue by dmi3kno** [Microsoft/LightGBM#90]
I am referring to `/src/network/socket_wrapper.hpp` line 189, Function GetAddress is not wrapped into `#if defined(_WIN32).. .#else... #endif`

This function contains reference to `inet_pton` which is not defined in _WIN32 systems. The function definition should be ok for non-Windows systems, but _WIN32 version needs to be added.

I don't feel qualified to PR, but just wanted to raise a flag. Without this fixed I can not compile [R package](https://github.com/bwilbertz/RLightGBM) which depends on LightGBM compiling under Windows from source.

P.S.: While you're on it, `/include/LightGBM/utils/text_reader.h` contains several comparisons of signed and unsigned int's (INDEX_T vs size_t types). Not that it is a big problem, just thought it could be checked.

**Comment by guolinke** [comment]
@dmi3kno Do you build with Visual Studio?

**Comment by guolinke** [comment]
@dmi3kno It seems you use GCC compiler in "mingw-like" command line tool on windows.
We only test it with Visual studio on windows now. However, I will fix this soon.
