### ISSUE TITLE
[R package] Verbosity of "[LightGBM] [Info] Trained a tree with leaves=XX and max_depth=XX"

### ISSUE THREAD

**Issue by jacquespeeters** [Microsoft/LightGBM#903]
R verbosity differ from Python.

In Python in order to only get evaluations of watchlist set i set verbose = 0 and verbose_eval = XX. Therefore in avoid to have all information how trees are trained in my console such as :
`[LightGBM] [Info] Trained a tree with leaves=XX and max_depth=XX`

In R  i tried with verbose = 0 then i've no verbosity at all. And with verbose = 1 and eval_freq = XX my console is flooded with all info.

It not a huge problem but it was a pleasure to use Lightgbm on Python for my last Kaggle, but R package seems to be behind.

## Reproducible examples

```
library(lightgbm)
data(agaricus.train, package = "lightgbm")
train <- agaricus.train
dtrain <- lgb.Dataset(train$data, label = train$label)
data(agaricus.test, package = "lightgbm")
test <- agaricus.test
dtest <- lgb.Dataset.create.valid(dtrain, test$data, label = test$label)
params <- list(objective = "regression", metric = "l2")
valids <- list(test = dtest)

# Not enough verbosity
model <- lgb.train(params,
                   dtrain,
                   100,
                   verbose = 0, eval_freq = 10,
                   valids,
                   min_data = 1,
                   learning_rate = 1,
                   early_stopping_rounds = 10)

# Too much verbosity
model <- lgb.train(params,
                   dtrain,
                   100,
                   verbose = 1, eval_freq = 10,
                   valids,
                   min_data = 1,
                   learning_rate = 1,
                   early_stopping_rounds = 10)
```

R behaviour
<img width="554" alt="r behaviour" src="https://user-images.githubusercontent.com/15957925/30253154-b13e499a-967f-11e7-9469-90af594e138c.png">

Expected behaviour as in Python

<img width="656" alt="python behaviour" src="https://user-images.githubusercontent.com/15957925/30253168-e4cdcbc8-967f-11e7-82ac-afb386e2c544.png">

**Comment by guolinke** [comment]
try the latest code.
