### ISSUE TITLE
It cost too much time while using the  lib_lightgbm.so for predicting 

### ISSUE THREAD

**Issue by MenglaiWang** [Microsoft/LightGBM#906]
## Environment info
Operating System:CentOS release 6.3 (Final)
CPU:Intel(R) Xeon(R) CPU E5-2620 v2 @ 2.10GHz
C++/Python/R version:C++

Hi, guolin,
     I am using the LGBM_BoosterPredictForMat  function for predicting in the so file. But it can be really slow.
I have 100 trees and 40 leaves.The  #feature is just 73.
Each round, I feed 10*73  into lightgbm, and it cost about 500+ us .   Sometimes it can be 7445 us. 
I think the so file is quite  instability.  How can I get out of the trouble?

**Comment by guolinke** [comment]
@MenglaiWang 
Every time you calling LGBM_BoosterPredictForMat, it will re-init the predictor. 
So the best practice is only calling it one time with all data. 

If you want calling it multi-time, you can separate the init work(https://github.com/Microsoft/LightGBM/blob/master/src/c_api.cpp#L177-L194) to a addition function, to avoid the many duplicated init.

**Comment by MenglaiWang** [comment]
OK，i  will try it😀

**Comment by MenglaiWang** [comment]
@guolinke 
Follow your advice, I have tried to separate the init work to avoid re-init the predictor, and it is exciting to get 2x faster speed. But it is not satisfying yet. How can I speed up 2x more faster?

**Comment by guolinke** [comment]
@MenglaiWang 
can you use more data in every single batch ?

**Comment by MenglaiWang** [comment]
@guolinke 
No,I can't. Each time I only need to predict for 10 samples.😫

**Comment by JianboTang** [comment]
after testing time consumed by the function ref_booster->Predict(), we found that the init part during LightGBM/src/c_api.cpp:#L185-202 and the predict part during LightGBM/src/c_api.cpp:#L203-213 both cost very few seconds, nearly zero. 

While test the function ref_booster->Predict() from outside, like the below:

1085   begin1 = clock();
1086   ref_booster->Predict(num_iteration, predict_type, nrow, get_row_fun,
1087                        config.io_config, out_result, out_len);
1088   end1 = clock();
1089   printf("in c++: predict boost time = %f\n", (double)(end1 - begin1) / CLOCKS_PER_SEC);

it took nearly 0.4 seconds.

when we test ref_booster->Predict()  from inside, like the below:

 181   void Predict(int num_iteration, int predict_type, int nrow,
 182                std::function<std::vector<std::pair<int, double>>(int row_idx)> get_row_fun,
 183                const IOConfig& config,
 184                double* out_result, int64_t* out_len) {
 185     clock_t begin1, end1, begin2, end2, begin, end;
 186     begin = clock();
 187     std::lock_guard<std::mutex> lock(mutex_);
...
...
224     end = clock();
 225     printf("in 225 takes total time : %.f seconds\n", (double)(end - begin) / CLOCKS_PER_SEC);
 226   }

it took 0 seconds ...
this phenomenon is really really hard to believe,
or this experiment has some wrong steps.

looking forward to your reply
