### ISSUE TITLE
[R Package] 'lgb.get.eval.result' function gives error 

### ISSUE THREAD

**Issue by patarol** [Microsoft/LightGBM#913]
Hi,

I'm running LightGBM in `R` for Windows.
I can run most fucntions and the speed improvement is huge. 
I'm trying to understand both `lgb.cv` and `lgb.train` output. So, I've tried to run `lgb.get.eval.result`, however I get an error message:
`Error in lgb.get.eval.result(model, "train", "regression") : 
  lgb.get.eval.result: wrong data name`

I already tried to use both my own data and `agaricus.train` data from the R Package.

I've tried this:
`lgb.get.eval.result(model, "dtrain", "regression")`
and this
`lgb.get.eval.result(model, "train", "regression")` even though I know it should use `dtrain `.

Any idea?

Thank you

**Comment by guolinke** [comment]
@Laurae2 it seems that is something wrong with R. Do you know why ?

**Comment by Laurae2** [comment]
@guolinke Works correctly here.

Reproducible example:

```r
library(lightgbm)
data(agaricus.train, package = "lightgbm")
train <- agaricus.train
dtrain <- lgb.Dataset(train$data, label = train$label)
data(agaricus.test, package = "lightgbm")
test <- agaricus.test
dtest <- lgb.Dataset.create.valid(dtrain, test$data, label = test$label)
params <- list(objective = "regression", metric = "l2")
valids <- list(test = dtest)
model <- lgb.train(params,
                   dtrain,
                   100,
                   valids,
                   min_data = 1,
                   learning_rate = 1,
                   early_stopping_rounds = 10)
lgb.get.eval.result(model, "test", "l2")
#  [1] 6.441652e-17 1.972152e-31 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00
# [11] 0.000000e+00 0.000000e+00 0.000000e+00
```

@patarol You are using the wrong values for the parameters. Check the reproducible example above.

**Comment by patarol** [comment]
@Laurae2 Thank you!! 

I tried to look up in `?lgb.get.eval.result` but no usage example comes within the [R documentation ](http://127.0.0.1:23738/library/lightgbm/html/lgb.get.eval.result.html) help. 
I didn't know that the dataset should be a `"lgb.Dataset" "R6"` data derived from `lgb.Datased`. 

It would be great if both the usage example (like this one used by you) and type of dataset should be used as argument for `lgb.get.eval.result` in R documentation help. 

Thank you again! 

P.S.: lgb.train runs amazingly fast.

**Comment by Laurae2** [comment]
re-open this, I'll make a PR to fix during this day and it will be closed automatically once the PR gets merged to the master branch.

**Comment by guolinke** [comment]
@Laurae2 updates ?
