### ISSUE TITLE
Make domain errors more specific

### ISSUE THREAD

**Issue by fulldecent** [Microsoft/LightGBM#914]
Errors can be thrown if there is a problem with input data. Example:

> terminate called after throwing an instance of 'std::runtime_error'
>  what():  Check failed: default_bin_ > 0 at /Users/travis/build/Microsoft/LightGBM/python-package/lightgbm/src/io/bin.cpp, line 367 .

These will be more helpful if they can identify exactly which data (row and column) violated the input requirement.

**Comment by guolinke** [comment]
it seems you are not using the latest code. 
can you try it ?

**Comment by fulldecent** [comment]
Sorry, that fixed it. Thank you.
