### ISSUE TITLE
Best option to install LightGBM on RHEL6 with dependencies

### ISSUE THREAD

**Issue by sp-expl-R** [Microsoft/LightGBM#915]
Hi,
I have been trying to install the LightGBM on a LINUX machine (64bit) trying various options without any success so far.
My server is behind a firewall, but I have access to internet through a Proxy server.
Below is what I have tried:
library(devtools)
install_github("Microsoft/LightGBM", subdir = "R-package",force = TRUE)

I get the below error:
Downloading GitHub repo Microsoft/LightGBM@master
from URL https://api.github.com/repos/Microsoft/LightGBM/zipball/master
Installation failed: Unknown SSL protocol error in connection to codeload.github.com:443
Warning message:
GitHub repo contains submodules, may not function as expected!

I also tried to install from source (tar.gz) both by using install_packages() and from command line using R CMD INSTALL. Both of them return the error below.

Warning in untar2(tarfile, files, list, exdir, restore_times) :
  skipping pax global extended headers
ERROR: cannot extract package from /path/to/tar.gz
Warning message:
In install.packages
installation of package /path/to/tar.gz  had non-zero exit status

Its been a few days since I tried to install this. I also want to resolve the dependency tree for this package if it has any. 
Any suggestions are highly appreciated. Is this package available in CRAN yet or soon planned to be in CRAN?

**Comment by russellwmy** [comment]
So I built with the dockerfile which is running ubuntu. But i need to test it functionality later.
I think You can modify the dockerfile to use RHEL6  as based image as well.

**Comment by guolinke** [comment]
@sp-expl-R "Installation failed: Unknown SSL protocol error in connection to codeload.github.com:443" i think this is not a LightGBM issue. 

refer to the https://github.com/Microsoft/LightGBM/tree/master/R-package . 

```
git clone --recursive https://github.com/Microsoft/LightGBM
cd LightGBM/R-package
# export CXX=g++-7 CC=gcc-7 # for OSX
R CMD INSTALL --build . --no-multiarch
```
