### ISSUE TITLE
Query/group input format for ranking task

### ISSUE THREAD

**Issue by travisbrady** [Microsoft/LightGBM#92]
Does LightGBM follow xgboost's group input format convention described here: https://github.com/dmlc/xgboost/blob/master/doc/input_format.md#group-input-format

I don't see it documented anywhere but would be happy to submit a PR to fill out the documentation a bit here.

**Comment by guolinke** [comment]
https://github.com/Microsoft/LightGBM/wiki/Quick-Start#training-data-format
https://github.com/Microsoft/LightGBM/wiki/Configuration#query-data

**Comment by travisbrady** [comment]
Ahh, thank you very much. I had missed that. Sorry for the noise.
