### ISSUE TITLE
"Unknown parameter: is_train_metric" after successful build

### ISSUE THREAD

**Issue by Christopher-Whitridge** [Microsoft/LightGBM#920]
Please search your question on previous issues, [stackoverflow](https://stackoverflow.com/questions/tagged/lightgbm) or other search engines before you open a new one.

For bugs and unexpected issues, please provide following information, so that we could reproduce on our system.

## Environment info
Operating System: Ubuntu 16.04
CPU: ppc64le
C++/Python/R version: 5.4.0 / 2.7.12 / 3.2.3

## Error Message:

[LightGBM] [Fatal] Unknown parameter: is_train_metric
Met Exceptions:
Unknown parameter: is_train_metric
[LightGBM] [Fatal] Unknown parameter: is_train_metric
Met Exceptions:
Unknown parameter: is_train_metric

## Steps to reproduce

1. git clone https://github.com/guolinke/boosting_tree_benchmarks.git
2. Download data from links provided in above repo
3. ./run_all.sh

**Comment by wxchan** [comment]
try to run `sed -i 's/is_train_metric/is_training_metric/g' lightgbm/lightgbm.conf` first
