### ISSUE TITLE
sklearn categorical handling of early stopping

### ISSUE THREAD

**Issue by geoHeil** [Microsoft/LightGBM#921]
https://github.com/Microsoft/LightGBM/issues/901 is re-enabling basic support for categorical. However, early stopping is still not supported as it dies not convert the categorical columns.

I.e. I see ` DataFrame.dtypes for data must be int, float or bool. Did not expect the data types in fields`  when early stopping is enabled for the scikit-learn API

**Comment by guolinke** [comment]
@wxchan are there some bugs ?

**Comment by wxchan** [comment]
@guolinke I don't have much time before Oct. @henry0312 @StrikerRUS can you help check this thread and #893 if you have time?

**Comment by StrikerRUS** [comment]
I can't reproduce the error. I use the @geoHeil's code from the previous issue:
```
import pandas as pd
import lightgbm as lgb

df_train = pd.DataFrame({'target':[0,1,0,0],
                         'A':['a','b','c','a'],
                        'B':[1,2,2,3]})
df_train.A = df_train.A.astype('category')

df_test = pd.DataFrame({'target':[0,1,1,0],
                         'A':['a','b','c','unseed'],
                       'B':[1,2,2,3]})
df_test.A = df_test.A.astype('category')

X_train = df_train.drop(['target'], axis=1)
X_test = df_test.drop(['target'], axis=1)

y_train = df_train.target
y_test = df_test.target

classifier = lgb.LGBMClassifier()
classifier.fit(X_train, y_train, eval_set=[(X_train, y_train), (X_test, y_test)],
               early_stopping_rounds=5, categorical_feature='auto')
```

@geoHeil Please provide your actual code.

**Comment by henry0312** [comment]
I'm sorry I don't have much time until next week, either.

**Comment by geoHeil** [comment]
I can conform now that as @StrikerRUS said it works on the minimal sample i.e. the error can't be reproduced. During the next 1-2 weeks I will try to run my actual code again and check if I can still reproduce the error.

**Comment by guolinke** [comment]
@geoHeil updates ?

**Comment by geoHeil** [comment]
Unfortunately not yet.

Guolin Ke <notifications@github.com> schrieb am Do., 26. Okt. 2017 um
03:40 Uhr:

**Comment by geoHeil** [comment]
For the python native api: it works just fine. Sklearn looks good too in the latest release
