### ISSUE TITLE
The output is bombared with useless logs '[LightGBM] [Info] Trained a tree with leaves ...'

### ISSUE THREAD

**Issue by MichalAdamczyk-Base** [Microsoft/LightGBM#926]
## Environment info
Operating System: Mac OS
Python version: 3.6.1

## Steps to reproduce

```
lgbm_parameters = {
    'boosting_type': 'gbdt', 'objective': 'multiclass', 'nthread': 4,
    'num_leaves': 2**7, 'learning_rate': 0.1, 'metric': 'multi_error', 'verbose' : 0, 'num_class' : 3
}

dtrain = lgb.Dataset(x_train, y_train, silent=True)

cv_results = lgb.cv(
    lgbm_parameters, dtrain, num_boost_round=70, nfold=5, stratified=True, shuffle=True,
    early_stopping_rounds=3, verbose_eval=10, show_stdv=True, seed=0)

```
I would like to see results after each 10 steps. However, I am bombarded with useless logs that I don't want to see (and I believe I told it to my lgbm model by setting 'verbose':0).

This is basic, most important thing about model - validate how it progresses. How to achieve this with LightGBMs?

**Comment by guolinke** [comment]
@MichalAdamczyk-Base you can try the code of latest branch, which put these info into dubeg level output.

**Comment by psinger** [comment]
@guolinke I have the newest master branch version and still see this output.
