### ISSUE TITLE
Reading model.txt file, decision_type

### ISSUE THREAD

**Issue by GushchinaVarya** [Microsoft/LightGBM#928]
Hello! Where can I find the information about way of forming model.txt file?

Especially I'm interested in question about decision_type. What means decision_type=2 2 2..? 

A month ago you wrote 
"decision_type is not simply 0/1 now. It is a bitset (8-bit) contains the information of missing value handle."

in issue #858

Where can I find full information about types?

Thank you

**Comment by guolinke** [comment]
it is a bitvector now.
refer to: https://github.com/Microsoft/LightGBM/blob/master/include/LightGBM/tree.h#L13-L15
https://github.com/Microsoft/LightGBM/blob/master/include/LightGBM/tree.h#L176-L195
