### ISSUE TITLE
The results of lightgbm in linux and windows are inconsistent under the same version

### ISSUE THREAD

**Issue by kbzhang** [Microsoft/LightGBM#934]
Operating System:
linux: ubuntu 14.04
windows: windows2008 R2

Version：
2.0.4

## Error Message:

1. Under the same configuration，the same trainset, the model of windows is different from linux
2. With two model to predict the same testset , There is a big difference between the results

**Comment by guolinke** [comment]
"big difference?"

There are many possible reasons. 
With different compilers, the result could be different. the main reason is the multi-threading and openmp executing order issues. 

The python in the different platform also may cause the difference. you can exclude this reason by using CLI version.
