### ISSUE TITLE
Using the C API LGBM_DatasetCreateFromSampledColumn

### ISSUE THREAD

**Issue by JohanGarp** [Microsoft/LightGBM#938]
I'm trying to use the LGBM_DatasetCreateFromSampledColumn function,
but I don't understand how to use the parameters.
Is there an example I could look at?

**Comment by guolinke** [comment]
refer to https://github.com/Microsoft/LightGBM/blob/master/include/LightGBM/c_api.h#L55-L66

/*!
* \brief create a empty dataset by sampling data.
* \param sample_data sampled data, grouped by the column.
* \param sample_indices indices of sampled data.
* \param ncol number columns
* \param num_per_col Size of each sampling column
* \param num_sample_row Number of sampled rows
* \param num_total_row number of total rows
* \param parameters additional parameters
* \param out created dataset
* \return 0 when succeed, -1 when failure happens
*/

The sampling data is like the CSC format, it only saves the non zero datas.
To get a data, you should use sample_data and sample_indices together.
for example, assume ```sample_data[i][j] = a``` and ```sample_indices[i][j] = b```, 
That means value of i-th column and b-th row is ```a```.

and ```num_per_col ``` is used to indicate the non-zero data per col, the length of sample_data[i] and sample_indices[i] is equal to ```num_per_col[i]``` .
