### ISSUE TITLE
Suggestion for EvalAndCheckEarlyStopping function

### ISSUE THREAD

**Issue by tt83** [Microsoft/LightGBM#941]
When early stopping is met last early_stopping_round_ models are removed, but scores are not:
```
    // pop last early_stopping_round_ models
    for (int i = 0; i < early_stopping_round_ * num_tree_per_iteration_; ++i) {
      models_.pop_back();
    }
```
May be better to update scores as well, something like this:
```
    for (int i = 0; i < early_stopping_round_; ++i) {
    	RollbackOneIter();
    }
```

**Comment by guolinke** [comment]
@tt83 will you use that score ?

**Comment by tt83** [comment]
Yes, I use. But if it is a feature, never mind.

**Comment by guolinke** [comment]
@tt83 adding this will slow down, since roll back one iteration is not efficient. 
It is better to not use the score. If you really want to use it, you can predict from begin.
