### ISSUE TITLE
How to detect the end of a model fitting in a callback?

### ISSUE THREAD

**Issue by yutkin** [Microsoft/LightGBM#943]
I need to invoke some function after the end of a model fitting. How can I detect this in the callback? I can figure it out by comparing current iteration with the last but it's not always true (for example I can use early_stopping callback).

**Comment by wxchan** [comment]
I think there is no straightforward way to do it right now. We can add a callback point after training stage ends.

There may be a stupid alternative to do it: one callback after each iteration and one callback to revert it before each iteration.

**Comment by wxchan** [comment]
why don't you just write codes after lgb.train() without a callback?

**Comment by yutkin** [comment]
I need to collect some kind of data in "a buffer" at every iteration, and after a training, it should be saved. I think that usage of a global buffer is not a good idea, so I've supposed there is a better solution. For example, local buffer and detection of the end of the training.

**Comment by wxchan** [comment]
@yutkin in this case, I think the easiest way to do it is copy all codes of early stopping callback and add your owns.

**Comment by guolinke** [comment]
close now. @wxchan @yutkin feel free to reopen if needed.
