### ISSUE TITLE
`eary_stop`

### ISSUE THREAD

**Issue by tyokota** [Microsoft/LightGBM#946]
Please review for the following line(s):

```
if (any(names(params) %in% eary_stop)) {
if (params[[which(names(params) %in% early_stop)[1]]] > 0) {
```
from `lgb.cv()` in the R package. I think that's a typo? It's preventing `lgb.cv()` from running.

**Comment by huanzhang12** [comment]
@bfgray3 please check this, thanks!

**Comment by huanzhang12** [comment]
@tyokota if you change `eary_stop` to `early_stop` does it work for you?
