### ISSUE TITLE
inconsistent parameter names: "n_estimators"

### ISSUE THREAD

**Issue by zkurtz** [Microsoft/LightGBM#954]
The [python API](http://lightgbm.readthedocs.io/en/latest/python/lightgbm.html#lightgbm-package) has an "n_estimators" argument.  It took me a while to figure out that this is the same as "num_boost_round", since this parameter is not even mentioned on [the main parameters page](https://github.com/Microsoft/LightGBM/blob/master/docs/Parameters.md).

It seems like it would be simplest to replace `n_estimators` with `num_boost_round` everywhere. Short of that, update the documentation?

**Comment by Laurae2** [comment]
@zkurtz This is the fault of the scikit-learn API, not the Python API (look up for parameters of `sklearn.ensemble.GradientBoostingClassifier` or similar).

**Comment by zkurtz** [comment]
Oh, OK.  I guess that means that there's no point in trying to replace the `n_estimators` parameter. But I propose replacing line 163 [here](https://github.com/Microsoft/LightGBM/blob/0350a9a6ff3a72e9c24eb28038bd10d4f4408c47/python-package/lightgbm/sklearn.py) with something like "Number of boosted trees to fit (i.e. num_boost_round in lightgbm.train)" to be clear about the relationship between the lightgbm parameters and the scikit-learn parameters.

**Comment by Laurae2** [comment]
The parameter is the same as [scikit-learn](http://scikit-learn.org/stable/modules/generated/sklearn.ensemble.GradientBoostingClassifier.html).

If we were to add the equivalent to the true API, we would have to add them to each parameter. However, `n_estimators` ("Number of boosted trees to fit.") is very easy to understand as it is equal to the number of boosting iterations (which is the same as `num_boost_round`), unless the user does not know what is boosting (and in that case, the user should just avoid using boosting due to its overfitting nature).

**Comment by zkurtz** [comment]
I'm well aware of what `num_boost_round` means, but was not previously familiar with the sklearn API and `n_estimators` seemed ambiguous to me.  For one thing, if sounds like it could refer to a collection of boosted trees, treating the output of a "single" lightgbm instance (with, say, `num_boost_round = 100`) as one estimator. 

If your lightgbm sklearn documentation is really just a copy of the sklearn documentation with no direct translation between the lightgbm parameters and the sklearn parameters, would it be sufficient then to just refer the reader to the sklearn documentation rather than reproducing it?

**Comment by mathcass** [comment]
I wanted to chime in on this to mention that I experienced the same sort of confusion as @zkurtz about the `n_estimators` parameter when working with the Scikit-Learn API. 

I think it's a good and important thing that the Scikit-Learn API confirms with other Scikit-Learn ensemble methods. 

I think a way to address this may just be to put `n_estimators` as an alias on the parameters guide: 

```
-  ``num_iterations``, default=\ ``100``, type=int,
   alias=\ ``num_iteration``, ``num_tree``, ``num_trees``, ``num_round``, ``num_rounds``, ``num_boost_round``, ``n_estimators``
```
