### ISSUE TITLE
C API  - Cannot construct Dataset since there are not useful features

### ISSUE THREAD

**Issue by travek** [Microsoft/LightGBM#955]
Hi!

I'm using lightgbm C_API and trying to construct dataset. I wrote a simple code to test dataset consytruction but this coderesults in FatalError:
Cannot construct Dataset since there are not useful features

Test code is the following:
	vector<float> v;

	for (int i = 0; i < rows; i++)
	{
		for (int j = 0; j < cols; j++)
		{
			v.push_back((((i + 1) * (j + 1)) % 3 == 0 ? 1 : (i + 1) * (j + 1)));
			cout << v[v.size() - 1] << ";";
		}
		cout << "\n";
	}
	DatasetHandle h_train;
	LGBM_DatasetCreateFromMat(&v[0], C_API_DTYPE_FLOAT32, rows, cols, 0, "", NULL, &h_train);

Please advise what should be fixed to correctly construct lightGBM Dataset.

PS: Some C++ examples of useing LightGBM C_API will also be useful.

**Comment by guolinke** [comment]
what is n_row ? 
if it is too small, you can try to set ```min_data=1 min_data_in_bin=1``` in your parameter.
