### ISSUE TITLE
R lgb.unloader crashes

### ISSUE THREAD

**Issue by zkurtz** [Microsoft/LightGBM#962]
In any R session, I get
```
> library(lightgbm)
Loading required package: R6
> lgb.unloader(wipe = TRUE)
Error in which(sapply(ls(.GlobalEnv), function(x) { :
  argument to 'which' is not logical
```

**Comment by guolinke** [comment]
@Laurae2 @bfgray3

**Comment by bfgray3** [comment]
@guolinke @Laurae2 @zkurtz this code is not the latest available on GitHub.  In my commit f90dfaf36ae6f9a9ace5e253269257eff2bba369 I switched away from using `sapply`.

**Comment by zkurtz** [comment]
Verified that this passes without error with a fresh build on my mac.
