### ISSUE TITLE
 module 'lightgbm' has no attribute 'xxxx' when running lightgbm in Python Module

### ISSUE THREAD

**Issue by OscarYuen** [Microsoft/LightGBM#972]
"module 'lightgbm' has no attribute xxxx" error message shows when using lightgbm(with/without gpu enabled) on IDLE
When running it on python shell line by line only, it has no problem

## Environment info
Operating System: Windows 10 64bit
CPU:  intel i7-6700
C++/Python/R version: Python 3.5.2 64bit

## Error Message:
`AttributeError: module 'lightgbm' has no attribute 'train'`
## Reproducible examples
When I run the below code on Python IDLE
`import lightgbm as lgb`
`lgb.train`

When I run it on Python shell, it could find 'train' and give
`<function train at 0x000001FB4819BEA0>`
## Steps to reproduce

1. Run the above code in python IDLE
2.
3.

**Comment by wxchan** [comment]
Do you have some scripts named lightgbm.py? If not, can you show how you install lightgbm?

**Comment by dotsonliu** [comment]
this is a bug? no body to slove it?

**Comment by guolinke** [comment]
@dotsonliu I think this is related to your environment.

**Comment by YoLinTsai** [comment]
@dotsonliu  Do you name your python file as lightgbm.py? It will result in importing your script but not the "lightgbm" library.

**Comment by dotsonliu** [comment]
thank you，i have found the problem


 
---Original---
