### ISSUE TITLE
Dataset columns slice or train feature selection.

### ISSUE THREAD

**Issue by Goorman** [Microsoft/LightGBM#978]
Is it possible to either slice dataset by columns or block certain features from being used in specific train call?

I construct dataset from big sparse libsvm file, so it would require to add a few extra computationally intensive steps to select features by myself.

**Comment by StrikerRUS** [comment]
You could use `ignore_column` parameter for this: http://lightgbm.readthedocs.io/en/latest/Parameters.html#io-parameters

**Comment by Goorman** [comment]
Thanks.
