### ISSUE TITLE
Segmentation Fault while continue training of dart

### ISSUE THREAD

**Issue by fcbruce** [Microsoft/LightGBM#984]
Continue training the model of `dart`, and the process crashed after serval iterations. And I try to the [`advanced_example.py`](https://github.com/Microsoft/LightGBM/blob/master/examples/python-guide/advanced_example.py) by changing `gbdt` to `dart`, it also crashed.

## Environment info
Operating System:
mac OS Sierra 10.12.5
CPU:
2.7 GHz Intel Core i5
C++/Python/R version:
Python

## Error Message:
segmentation fault  python3 advanced_example.py

## Reproducible examples
just change `gbdt` to `dart` in [line 37 of `examples/python-guide/advanced_example.py`](https://github.com/Microsoft/LightGBM/blob/master/examples/python-guide/advanced_example.py#L37)

## Steps to reproduce

python3 advanced_example.py

**Comment by guolinke** [comment]
ping @wxchan

**Comment by wxchan** [comment]
It fails at https://github.com/Microsoft/LightGBM/blob/master/src/io/tree.cpp#L127. split_feature_inner_.size() = 0. @guolinke any ideas why?

**Comment by guolinke** [comment]
@wxchan is that model from the continued train ?

**Comment by guolinke** [comment]
@wxchan the initial model cannot be dropped, since they don't have the inner_feature_indices.

**Comment by wxchan** [comment]
@guolinke so should we save it in model?

**Comment by guolinke** [comment]
@wxchan no. The real reason is the bin mapper. The init_model may is trained by the dataset with different bin mapper. As a result, we cannot use the innner_feature, inner_threashold to predict.

**Comment by wxchan** [comment]
@guolinke should we disallow dropping loaded trees?

**Comment by guolinke** [comment]
@wxchan , yeah, that should be disabled.

**Comment by guolinke** [comment]
@wxchan updates ?

**Comment by gwuillou** [comment]
Hello, 

I have also the problem of segmentation false when I am trying to use dart with continue training:
I am doing:
```
            gbm = lgb.train(params,
                            lgb_train,
                            num_boost_round=10,
                            valid_sets=lgb_train,
                            feature_name=header)
            y_val = gbm.predict(testset.x)
            y_train = gbm.predict(trainingset.x)
            ...
            nb_tree_by_it = 100
            nb_it = 100
            for jj in range(1, nb_it):
                lgb_train.init_score = None
                gbm = lgb.train(params,
                                lgb_train,
                                num_boost_round=nb_tree_by_it,
                                valid_sets=lgb_train,
                                feature_name=header,
                                verbose_eval=100,
                                init_model=gbm
                                )
                 ...
```


What I am doing wrong?
