### ISSUE TITLE
save and load model in python

### ISSUE THREAD

**Issue by gugatr0n1c** [Microsoft/LightGBM#99]
Hi,

thx for Python interface! Seems to me working nicely.
Can you add also add example how to safe and load model?

Thank you.

**Comment by guolinke** [comment]
@gugatr0n1c you can interactive with class ```Booster```. 
```Booster``` can be get by using ```LGBMModel.booster()```

**Comment by gugatr0n1c** [comment]
Ok I found save_model:
model.booster().save_model(path + model_name + '.txt', num_iteration=-1)
this is working nicely.

But not sure how load it back for later use... now method load_model or any where as input can be path for file

**Comment by guolinke** [comment]
@gugatr0n1c  I have add this into example:

https://github.com/Microsoft/LightGBM/blob/master/examples/python-guide/simple_example.py

**Comment by gugatr0n1c** [comment]
thx

**Comment by mtryout** [comment]
@guolinke the best, thanks..
