### ISSUE TITLE
Cant  install in the R

### ISSUE THREAD

**Issue by Royhuiy** [Microsoft/LightGBM#990]
Please search your question on previous issues, [stackoverflow](https://stackoverflow.com/questions/tagged/lightgbm) or other search engines before you open a new one.

For bugs and unexpected issues, please provide following information, so that we could reproduce on our system.

## Environment info
Operating System:
CPU:
C++/Python/R version:

## Steps to reproduce

1.i can not install successfully in the R-langugae.how to install?

**Comment by guolinke** [comment]
refer to https://github.com/Microsoft/LightGBM/tree/master/R-package
